export const amizades = {
  ativosAgora: "نشط الآن",
  procurando: "نرى من الموجود…",
  tudoTranquilo: "كل شيء هادئ الآن…",
  tudoTranquiloDetalhe: "عندما تنضم أنت أو صديق إلى مكالمة، ستظهر هنا — ويمكنك الانضمام بنقرة واحدة.",
  emVoz: "في محادثة صوتية",
  voce: "أنت",
  soVoce: "أنت فقط",
  pessoas: "{{quantas}} أشخاص",
  voltarParaChamada: "العودة إلى المكالمة",
  entrarNaChamada: "الانضمام إلى المكالمة",
  abrirCanal: "فتح {{canal}} في {{servidor}}",
  mensagensDiretas: "الرسائل المباشرة",
  encontreConversa: "ابحث عن محادثة",
  amigos: "الأصدقاء",
  conversas: "المحادثات",
  semConversas: "لا توجد محادثات بعد. أضف صديقًا للبدء.",
  semConversaComEsseNome: "لا توجد محادثة بهذا الاسم.",
  abrirMenu: "فتح الخوادم والمحادثات",
  solicitacoes: "طلبات الرسائل",
  pedidos: "الطلبات",
  spam: "مزعج",
  pedidosPendentes: "طلبات معلقة",
  marcadosComoSpam: "موسومة كمزعجة",
  aceitar: "قبول",
  ignorar: "تجاهل",
  marcarSpam: "وسم كمزعج",
  semPedidos: "لا توجد طلبات في الانتظار.",
  semPedidosDetalhe: "من ليس صديقك لكنه يشاركك خادمًا يصل إلى هنا قبل أن يصل إلى محادثاتك.",
  semSpam: "لا شيء موسوم كمزعج.",
  semSpamDetalhe: "ما يفرزه مرشح المزعج، أو ما تسمه أنت، يبقى في هذا التبويب.",
  umServidorEmComum: "خادم مشترك واحد",
  servidoresEmComum: "{{quantos}} خوادم مشتركة",
  semServidoresEmComum: "لا توجد خوادم مشتركة",
};
