export const chamada = {
  conectando: "جارٍ الاتصال بالمكالمة…",
  naoEntrou: "تعذّر الانضمام إلى المكالمة",
  sair: "مغادرة المكالمة",
  sairDaVoz: "مغادرة المكالمة الصوتية",
  desconectar: "قطع الاتصال",
  voltar: "العودة إلى المكالمة",
  voltarAosQuadros: "العودة إلى مربّعات المكالمة",
  fecharChat: "إغلاق الدردشة",
  carregandoPrevia: "جارٍ تحميل المعاينة…",
  maisOpcoes: "خيارات أخرى",
  deVideo: "مكالمة فيديو",
  deVoz: "مكالمة صوتية",
  alguem: "شخص ما",
  volume: {
    entrada: "مستوى الإدخال",
    saida: "مستوى الإخراج",
    live: "مستوى صوت البث",
    liveComPorcento: "مستوى صوت البث ({{porcento}}%)",
    liveSemSom: "البث بلا صوت",
  },
  aparelhos: {
    entrada: "جهاز الإدخال",
    saida: "جهاز الإخراج",
    camera: "الكاميرا",
    microfone: "الميكروفون",
    saidaCurto: "الإخراج",
    oDoSistema: "الافتراضي للنظام",
    aDoSistema: "الافتراضية للنظام",
    semEscolhaDeSaida: "هذا المتصفح لا يسمح باختيار الإخراج — النظام هو من يقرّر.",
    espelhar: "عكس الكاميرا",
    configEntrada: "إعدادات الإدخال",
    configSaida: "إعدادات الإخراج",
    configCamera: "إعدادات الكاميرا",
    configAudioEVideo: "إعدادات الصوت والفيديو",
  },
  tela: {
    compartilhar: "مشاركة الشاشة",
    compartilharAcao: "مشاركة",
    cancelar: "إلغاء",
    telas: "الشاشات",
    janelas: "النوافذ",
    somDoComputador: "إحضار صوت الحاسوب معها",
    somDoSistema: "إحضار صوت النظام معها",
    configCompartilhamento: "إعدادات المشاركة",
    mostrarSemVideo: "إظهار من بلا فيديو",
    semFontes: "لم يُرجع النظام أي شاشة أو نافذة للمشاركة.",
    pararDeCompartilhar: "إيقاف المشاركة",
    encerrarTransmissao: "إنهاء البث",
  },
  live: {
    etiqueta: "مباشر",
    etiquetaMaiuscula: "مباشر",
    assistir: "مشاهدة البث",
    assistirPessoa: "مشاهدة {{nome}}",
    pararDeAssistir: "إيقاف المشاهدة",
  },
  membro: {
    mudarMeuApelido: "تغيير لقبي",
    meuMicrofone: "الميكروفون الخاص بي",
    ouvirChamada: "الاستماع إلى المكالمة",
    copiarMeuId: "نسخ معرّفي",
    idCopiado: "تم نسخ المعرّف.",
    mensagem: "رسالة",
    silenciar: "كتم",
    alterarApelido: "تغيير اللقب",
    cargos: "الرتب",
    semCargo: "لم تُنشأ أي رتبة",
    moverPara: "النقل إلى",
    silenciarNoServidor: "كتم الصوت في الخادم",
    desativarAudioNoServidor: "تعطيل الصوت في الخادم",
    desconectar: "قطع الاتصال",
    apelidoTitulo: "لقبك في هذا الخادم",
    apelidoDeAlguem: "لقب {{nome}}",
    apelidoCampo: "اللقب",
    apelidoDicaPropria: "يسري هنا فقط. اتركه فارغًا ليعود اسمك المعتاد.",
    apelidoDicaDeOutro: "يسري في هذا الخادم فقط. اتركه فارغًا للعودة إلى الاسم الأصلي.",
  },
  detalhes: {
    abrir: "تفاصيل الصوت",
    titulo: "تفاصيل الصوت",
    conexao: "الاتصال",
    pingMedio: "متوسط الاستجابة",
    ultimoPing: "آخر استجابة",
    perda: "فقدان الحزم المرسلة",
    medindo: "جارٍ القياس…",
    criptografado: "مشفّر حتى الخادم (DTLS-SRTP)",
    explicacao: "فوق 250 مللي ثانية يصبح التأخير ملحوظًا في الحديث ويبدأ الناس بمقاطعة بعضهم. وفقدان الحزم فوق 10% يجعل الصوت آليًا. في الحالتين تكون المشكلة غالبًا بينك وبين الإنترنت: جرّب كابلًا بدل الواي فاي، أو أعد تشغيل الراوتر.",
  },
  microfone: {
    bloqueado: "الميكروفون محظور — أنت تستمع فقط. اسمح بالوصول من أذونات المتصفح.",
    bloqueadoNoMac: "يحظر macOS الميكروفون. علّم على",
    caminhoNoMac: "إعدادات النظام ← الخصوصية والأمان ← الميكروفون",
    abrirAjustes: "فتح الإعدادات",
    vaiReabrir: "سيطلب منك macOS إعادة فتح التطبيق.",
    naoAbriu: "تعذّر فتح الميكروفون — أنت تستمع فقط. تحقّق من الجهاز في الإعدادات ← الصوت والفيديو.",
  },
  gravacaoDeTela: {
    bloqueada: "لم يسمح macOS بتسجيل الشاشة بعد. بدونه تخرج المشاركة سوداء.",
    marque: "علّم على",
    reabra: "في «تسجيل الشاشة» ثم أعد فتح التطبيق.",
    jaMarcado: "إذا كان معلَّمًا بالفعل، فقد تقادم الإذن في التحديث الأخير: أزل العلامة، ضعها من جديد، ثم أعد فتح التطبيق.",
  },
  ruido: {
    titulo: "كتم الضوضاء",
    explicacao: "أزل ضجيج الخلفية من صوتك. جرّب التصفيق أو تحريك لوحة المفاتيح وأنت تتكلّم — من في المكالمة يسمعك أنت وحدك.",
    semSuporte: "هذا المتصفح لا يشغّل الكتم المتقدّم. يبقى كتم المتصفح نفسه ساريًا، وهو أضعف.",
    aplicando: "جارٍ التطبيق على المكالمة…",
    faleParaTestar: "تكلّم للاختبار",
    verdeQuandoPassa: "يصبح أخضر عندما يمرّ صوتك.",
    teOuvindo: "يسمعونك الآن.",
    feitoCom: "مصنوع بـ",
    aquiNoAparelho: "، هنا على جهازك",
    ajustes: "الإعدادات",
  },
  permissoes: {
    titulo: "أذونات macOS",
    detalhe: "يسأل macOS مرة واحدة فقط، وبعدها لا يتغيّر إلا من لوحته. هنا ترى ما هو ساري وتحلّ ما ينقص.",
    concedida: "ممنوح",
    negada: "مرفوض",
    naoPedida: "لم يُطلب",
    permitir: "السماح",
    abrirAjustes: "فتح الإعدادات",
    microfone: "الميكروفون",
    microfoneDetalhe: "التحدث في المكالمات واختبار الإدخال.",
    camera: "الكاميرا",
    cameraDetalhe: "تشغيل الفيديو في المكالمة.",
    tela: "تسجيل الشاشة",
    telaDetalhe: "مشاركة الشاشة والنوافذ.",
    monitoramento: "مراقبة الإدخال",
    monitoramentoDetalhe: "استخدام اضغط-للتحدث حتى مع تشغيل Gravaê في الخلفية.",
  },
  jaConectado: {
    titulo: "أنت في هذه المكالمة بالفعل",
    trazer: "إحضار المكالمة إلى هنا",
    deixar: "اتركها كما هي",
    detalhe: "بإحضارها إلى هنا يخرج الطرف الآخر من المكالمة — حسابك في مكان واحد في كل مرة.",
  },
};
