export const comum = {
  carregando: "جارٍ التحميل…",
  salvar: "حفظ",
  salvando: "جارٍ الحفظ…",
  descartar: "تجاهل",
  redefinir: "إعادة تعيين",
  naoSalvo: "لديك تغييرات غير محفوظة.",
  fechar: "إغلاق",
  criar: "إنشاء",
  nome: "الاسم",
  emoji: "إيموجي",
  previa: "معاينة",
  cancelar: "إلغاء",
  enviar: "إرسال",
  apagar: "حذف",
  excluir: "حذف",
  remover: "إزالة",
  trocar: "تغيير",
};
