export const comum = {
  voltar: "رجوع",
  agoraNao: "ليس الآن",
  erro: {
    tentarDeNovo: "المحاولة من جديد",
    recarregar: "إعادة التحميل",
    copiarDetalhes: "نسخ التفاصيل",
    parteQuebrou: "هذا الجزء من الشاشة تعطّل.",
    titulo: "تعثّر Gravaê.",
    detalhe: "حدث خلل في الطريق ولم تتمكّن الشاشة من الظهور. محادثتك لم تضع — كل شيء محفوظ على الخادم.",
  },
  conexao: {
    voltou: "عاد الاتصال",
    reconectando: "جارٍ إعادة الاتصال",
    tentativaSufixo: " · المحاولة {{numero}}",
    aSalvo: "المحادثة محفوظة على الخادم. سيعود كل شيء وحده حالما يعود الاتصال.",
  },
  avisoDoNavegador: {
    titulo: "هل تريد تنبيهات بالرسائل؟",
    detalhe: "عندما يكون Gravaê خلف نافذة أخرى، سينبّهك.",
  },
  atualizacao: {
    titulo: "التحديث",
    semAuto: "هذه النسخة من التطبيق لا تحدّث نفسها. نزّل أحدث مثبّت من الأسفل وثبّته فوقها.",
    versaoAtual: "أنت على النسخة {{versao}}.",
    instalando: "جارٍ تثبيت النسخة {{versao}}…",
    prontaVersao: "النسخة {{versao}} جاهزة للتثبيت",
    baixandoVersao: "جارٍ تنزيل النسخة {{versao}}…",
    baixandoComProgresso: "جارٍ تنزيل النسخة {{versao}}… {{porcento}}%",
    saiuVersao: "صدرت النسخة {{versao}}",
    saiuVersaoClique: "صدرت النسخة {{versao}} — انقر للتنزيل",
    instalarVersaoEReiniciar: "تثبيت النسخة {{versao}} وإعادة التشغيل",
    erroTenteDeNovo: "{{erro}} انقر للمحاولة من جديد.",
    procurando: "جارٍ البحث…",
    emDia: "أنت على أحدث نسخة",
    vaiFechar: "سيُغلق التطبيق بعد لحظات.",
    comoInstala: "يُغلق التطبيق، ويستبدل النسخة، ثم يفتح من جديد وحده. ستخرج من المكالمة إن كنت في واحدة.",
    semServidor: "تعذّر الاتصال بخادم النسخ.",
    procuraSozinho: "يبحث التطبيق وحده عند فتحه وكل ست ساعات.",
    instalandoReticencias: "جارٍ التثبيت…",
    instalandoCurto: "جارٍ التثبيت",
    baixandoCurto: "جارٍ التنزيل",
    tentarDeNovo: "المحاولة من جديد",
    reiniciarAgora: "إعادة التشغيل الآن",
    instalarEReiniciar: "التثبيت وإعادة التشغيل",
    baixar: "تنزيل",
    procurar: "بحث",
    baixarApp: "تنزيل التطبيق",
    ariaBotao: "تحديث التطبيق",
  },
  janela: {
    ajustarAltura: "ضبط الارتفاع",
    redimensionar: "تغيير حجم النافذة",
    ajustarLargura: "ضبط العرض",
  },
  dica: {
    rotulo: "ملاحظة:",
    pularConfirmacao: "اضغط مع الاستمرار على Shift أثناء النقر لتخطي هذا التأكيد.",
  },
  cor: {
    pescar: "التقاط لون من الشاشة",
    hex: "القيمة الست عشرية",
  },
  imagem: {
    titulo: "اختر صورة",
    enviar: "إرسال صورة",
    escolherGif: "اختيار صورة متحركة",
    buscarGif: "البحث عن صورة متحركة",
  },
  fonte: {
    rotulo: "خط الرسالة",
    padrao: "الافتراضي",
    comNome: "خط الرسالة — {{fonte}}",
  },
  recorte: {
    titulo: "اقتصاص الأيقونة",
    detalhe: "اسحب لاختيار الجزء المطلوب واستخدم الشريط للتقريب. تظهر الأيقونة دائرية في كل مكان داخل التطبيق.",
    voltarAoComeco: "العودة إلى البداية",
    usar: "استخدام هذا الاقتصاص",
  },
  mais: "المزيد",
  carregando: "جارٍ التحميل…",
  salvar: "حفظ",
  salvando: "جارٍ الحفظ…",
  descartar: "تجاهل",
  redefinir: "إعادة تعيين",
  naoSalvo: "لديك تغييرات غير محفوظة.",
  fechar: "إغلاق",
  criar: "إنشاء",
  nome: "الاسم",
  emoji: "إيموجي",
  previa: "معاينة",
  cancelar: "إلغاء",
  enviar: "إرسال",
  apagar: "حذف",
  excluir: "حذف",
  remover: "إزالة",
  trocar: "تغيير",
};
