export const configuracoes = {
  efeitos: {
    titulo: "تأثيرات المؤشّر",
    detalhe: "أثر وشرر يُرسمان فوق التطبيق. يبدآن مطفأين، ويختفيان وحدهما إن طلبت حركة أقل.",
    rastro: "أثر المؤشّر",
    rastroDetalhe: "خط يتبع المؤشّر ويخفت خلفه.",
    faisca: "شرر عند النقر",
    faiscaDetalhe: "خطوط قصيرة تنطلق من موضع نقرتك.",
    cor: "اللون",
    espessura: "السماكة",
    comprimento: "الطول",
    tamanho: "الحجم",
    quantidade: "العدد",
  },
  email: {
    verificarTitulo: "أكّد بريدك الإلكتروني",
    verificarDetalhe: "بعض المجتمعات لا تسمح بالكتابة إلا لمن أكّد بريده. الأمر بنقرة واحدة.",
    enviar: "أرسل الرابط",
    enviado: "راجع صندوق الوارد. الرابط صالح ليوم واحد.",
    falhou: "تعذّر إرسال البريد.",
    confirmado: "تم تأكيد البريد",
    confirmadoDetalhe: "تمّ الأمر. صرت تكتب في أي مجتمع يشترط ذلك.",
    linkIncompleto: "رابط ناقص",
    linkIncompletoDetalhe: "ينقص الرمز في العنوان. افتح الرابط من البريد مباشرة.",
    confirmando: "جارٍ التأكيد…",
    expirou: "استُخدم هذا الرابط من قبل أو انتهت صلاحيته.",
    irParaOApp: "الذهاب إلى التطبيق",
  },
  tema: {
    indisponivel: "السمة غير متاحة",
    indisponivelDetalhe: "حذفها ناشرها، أو أن الرابط خاطئ.",
    indisponivelLinha: "السمة غير متاحة. حذفها ناشرها، أو أن الرابط خاطئ.",
    importar: "استيراد السمة",
    importarCurto: "استيراد",
    importarDetalhe: "سيحل هذا محل السمة الحالية. يمكنك تعديلها لاحقًا من الإعدادات > المظهر > استوديو السمات.",
    porAutor: "بواسطة {{autor}}",
    umaCorTrocada: "لون واحد مُبدَّل",
    coresTrocadas: "{{quantas}} لونًا مُبدَّلًا",
    avisoDeCss: "تحمل هذه السمة CSS من كاتبها، وCSS يطال أي ركن من الشاشة. لا تستوردها إلا ممن تثق بهم.",
    soCores: "هذه السمة تبدّل الألوان فقط. لا CSS خارجي فيها.",
    verCss: "عرض CSS",
    esconderCss: "إخفاء CSS",
    aplicar: "تطبيق",
    previaSemMotor: "المعاينة لا تشغّل المحرّك. ثبّتها لتراه.",
    motorAnimado: "{{motor}} متحرك",
  },
  sair: "تسجيل الخروج",
  versoes: {
    termos: "شروط الخدمة",
    privacidade: "سياسة الخصوصية",
    copiar: "انقر للنسخ",
    copiado: "تم النسخ",
  },
  subscription: {
    seePlans: "عرض الخطط",
    upgradeSubtitle: "حدود أعلى وميزات حصرية للكتابة وإرسال الملفات والبث.",
    perMonth: "شهريًا",
    perYear: "سنويًا",
    save: "وفّر {{percent}}%",
    howToPay: "كيف تريد الدفع؟",
    legal: "يمكنك طلب استرداد خلال 7 أيام من الدفع. تعالج Stripe عملية الدفع؛ ولا نرى رقم بطاقتك أبدًا.",
    compare: "المجاني مقابل Infinity",
    featureColumn: "الميزة",
    freeColumn: "مجاني",
    messageRow: "حد أحرف الرسالة",
    attachmentRow: "حجم الملف المرسل",
    screenRow: "جودة الفيديو",
    megabytesValue: "{{value}} ميغابايت",
    screenValue: "{{resolution}} · {{fps}} إطار/ث",
    alreadyPremium: "لديك Infinity بالفعل حتى {{date}}.",
    upsell: "ارفع الحد مع Infinity",
    screenUpsell: "جودة أعلى مع Infinity",
    free: "أنت على الخطة المجانية.",
    activeUntil: "Infinity مفعّل حتى {{date}}.",
    renews: "يتجدد تلقائيًا في {{date}}.",
    endsAt: "أُلغي الاشتراك وينتهي في {{date}}.",
    pastDue: "فشلت آخر عملية دفع. حدّث بطاقتك حتى لا تفقد Infinity.",
    waiting: "جارٍ تأكيد الدفع…",
    subscribe: "اشترك",
    monthly: "شهري",
    yearly: "سنوي",
    automatic: "بطاقة، يتجدد تلقائيًا",
    manage: "إدارة الدفع",
    refund: "طلب استرداد",
    refundDetail: "يمكنك الانسحاب خلال 7 أيام من الدفع: {{amount}}، حتى {{date}}.",
    refundConfirm: "طلب الاسترداد؟",
    refundConfirmDetail: "يعود المبلغ إلى وسيلة الدفع نفسها وينتهي Infinity فورًا.",
    refunded: "تم طلب الاسترداد.",
    unavailable: "الاشتراك غير متاح بعد.",
    success: "تم استلام الدفع. شكرًا لك!",
    canceled: "أُلغي الدفع.",
    error: "حدث خطأ. حاول مرة أخرى.",
    no: "لا",
    tagRow: "وسم مستخدم مخصص",
    guildProfilesRow: "ملفات شخصية لكل مجتمع",
    badgeRow: "شارة الملف الشخصي",
    communitiesRow: "المجتمعات",
    savedRow: "الرسائل المحفوظة",
    animatedEmojiRow: "الرموز التعبيرية المتحركة",
    expressionsRow: "الرموز والملصقات من أي مكان",
    animatedProfileRow: "صور رمزية ولافتات متحركة",
    earlyAccessRow: "وصول مبكر إلى الميزات الجديدة",
    themesRow: "سمات مخصصة",
    pixOption: "Pix، لهذه الفترة فقط",
    pixHint: "افتح تطبيق البنك، واختر Pix وامسح رمز QR أو استخدم النسخ واللصق.",
    pixQrAlt: "رمز QR لـ Pix",
    pixCopy: "نسخ رمز Pix",
    pixCopied: "نُسخ رمز Pix",
    pixWaiting: "بانتظار الدفع",
    pixExpiresIn: "ينتهي خلال {{time}}",
    pixExpired: "انتهت صلاحية Pix هذا. أنشئ واحدًا جديدًا للمتابعة.",
    pixNew: "إنشاء Pix جديد",
    pixPaid: "تم استلام Pix! أصبح Infinity مفعّلًا.",
    forMe: "لي",
    asGift: "كهدية",
    buyGift: "شراء هدية",
    giftReady: "الهدية جاهزة! انسخ الرابط وأرسله لمن تريد.",
    giftClaimed: "تم استخدام الهدية! أصبح Infinity في حسابك.",
    gifts: "الهدايا",
    giftsEmpty: "لم تشترِ أي هدية بعد.",
    giftCode: "رمز الهدية",
    giftRedeem: "استخدام",
    giftCopyLink: "نسخ الرابط",
    giftLinkCopied: "نُسخ الرابط",
    giftClaimedBy: "استخدمها {{name}}",
    giftHint: "لديك رمز هدية؟ استخدمه هنا. الهدايا التي اشتريتها تظهر أدناه.",
  },
  telas: {
    subscription: "Infinity",
    conta: "حسابي",
    privacidade: "الخصوصية",
    conexoes: "الاتصالات",
    voz: "الصوت",
    video: "الفيديو",
    avisos: "الإشعارات",
    aplicativos: "التطبيقات",
    aparencia: "المظهر",
    batePapo: "الدردشة",
    acessibilidade: "إمكانية الوصول",
    idioma: "اللغة",
    aplicativo: "تنزيل التطبيق",
    atalhos: "الاختصارات",
    desktop: "تطبيق سطح المكتب",
    avancado: "متقدم",
    servidor: "الخادم",
    comunicado: "بيان النظام",
    denuncias: "البلاغات",
    publicacoes: "عمليات النشر",
  },
  grupos: {
    conta: "الحساب",
    app: "إعدادات التطبيق",
    desenvolvedor: "المطوّر",
    administracao: "الإدارة",
  },
  secoes: {
    detalhesDeLogin: "بيانات تسجيل الدخول",
    dispositivos: "الأجهزة",
    usuariosBloqueados: "المستخدمون المحظورون",
    aplicativosAutorizados: "التطبيقات المصرّح لها",
    sessoes: "الجلسات",
    amigosEDms: "الأصدقاء والرسائل المباشرة",
    compartilhamentoDeAtividade: "مشاركة النشاط",
    visibilidadeDoPerfil: "ظهور الملف الشخصي",
    exportarDados: "تصدير البيانات",
    exclusaoDeDados: "حذف البيانات",
    tema: "السمة",
    corDeDestaque: "لون التمييز",
    interface: "الواجهة",
    listaDeCanais: "قائمة القنوات",
    zoomDoApp: "مستوى تكبير التطبيق",
    escalaDaFonte: "حجم خط الدردشة",
    modoStreamer: "خصوصية البث",
    cursores: "المؤشرات",
    movimento: "الحركة",
    textoEmVoz: "تحويل النص إلى كلام",
    teclado: "لوحة المفاتيح",
    formatoDaHora: "تنسيق الوقت",
    idiomaDaInterface: "لغة الواجهة",
    dispositivosDeVoz: "الأجهزة",
    testeDoMicrofone: "اختبار الميكروفون",
    modoDeEntrada: "وضع الإدخال",
    sensibilidade: "حساسية الإدخال",
    qualidade: "الجودة",
    camera: "الكاميرا",
    transmissao: "البث",
    exibicao: "العرض",
    entrada: "الإدخال",
    midia: "الوسائط",
    geral: "عام",
    preferenciaDeMencao: "تفضيل الإشارات",
    sons: "الأصوات",
  },
};
