export const configuracoes = {
  sair: "تسجيل الخروج",
  versoes: {
    copiar: "انقر للنسخ",
    copiado: "تم النسخ",
  },
  telas: {
    conta: "حسابي",
    privacidade: "الخصوصية",
    conexoes: "الاتصالات",
    voz: "الصوت",
    video: "الفيديو",
    avisos: "الإشعارات",
    aplicativos: "التطبيقات",
    aparencia: "المظهر",
    batePapo: "الدردشة",
    acessibilidade: "إمكانية الوصول",
    idioma: "اللغة",
    aplicativo: "تنزيل التطبيق",
    atalhos: "الاختصارات",
    servidor: "الخادم",
  },
  grupos: {
    conta: "الحساب",
    app: "إعدادات التطبيق",
    desenvolvedor: "المطوّر",
    administracao: "الإدارة",
  },
  secoes: {
    detalhesDeLogin: "بيانات تسجيل الدخول",
    dispositivos: "الأجهزة",
    usuariosBloqueados: "المستخدمون المحظورون",
    aplicativosAutorizados: "التطبيقات المصرّح لها",
    sessoes: "الجلسات",
    amigosEDms: "الأصدقاء والرسائل المباشرة",
    compartilhamentoDeAtividade: "مشاركة النشاط",
    visibilidadeDoPerfil: "ظهور الملف الشخصي",
    exportarDados: "تصدير البيانات",
    exclusaoDeDados: "حذف البيانات",
    tema: "السمة",
    corDeDestaque: "لون التمييز",
    interface: "الواجهة",
    listaDeCanais: "قائمة القنوات",
    zoomDoApp: "مستوى تكبير التطبيق",
    escalaDaFonte: "حجم خط الدردشة",
    modoStreamer: "خصوصية البث",
    movimento: "الحركة",
    textoEmVoz: "تحويل النص إلى كلام",
    teclado: "لوحة المفاتيح",
    formatoDaHora: "تنسيق الوقت",
    idiomaDaInterface: "لغة الواجهة",
    dispositivosDeVoz: "الأجهزة",
    testeDoMicrofone: "اختبار الميكروفون",
    modoDeEntrada: "وضع الإدخال",
    sensibilidade: "حساسية الإدخال",
    qualidade: "الجودة",
    camera: "الكاميرا",
    transmissao: "البث",
    exibicao: "العرض",
    entrada: "الإدخال",
    midia: "الوسائط",
    geral: "عام",
    preferenciaDeMencao: "تفضيل الإشارات",
    sons: "الأصوات",
  },
};
