export const configuracoes = {
  efeitos: {
    titulo: "تأثيرات المؤشّر",
    detalhe: "أثر وشرر يُرسمان فوق التطبيق. يبدآن مطفأين، ويختفيان وحدهما إن طلبت حركة أقل.",
    rastro: "أثر المؤشّر",
    rastroDetalhe: "خط يتبع المؤشّر ويخفت خلفه.",
    faisca: "شرر عند النقر",
    faiscaDetalhe: "خطوط قصيرة تنطلق من موضع نقرتك.",
    cor: "اللون",
    espessura: "السماكة",
    comprimento: "الطول",
    tamanho: "الحجم",
    quantidade: "العدد",
  },
  email: {
    verificarTitulo: "أكّد بريدك الإلكتروني",
    verificarDetalhe: "بعض المجتمعات لا تسمح بالكتابة إلا لمن أكّد بريده. الأمر بنقرة واحدة.",
    enviar: "أرسل الرابط",
    enviado: "راجع صندوق الوارد. الرابط صالح ليوم واحد.",
    falhou: "تعذّر إرسال البريد.",
    confirmado: "تم تأكيد البريد",
    confirmadoDetalhe: "تمّ الأمر. صرت تكتب في أي مجتمع يشترط ذلك.",
    linkIncompleto: "رابط ناقص",
    linkIncompletoDetalhe: "ينقص الرمز في العنوان. افتح الرابط من البريد مباشرة.",
    confirmando: "جارٍ التأكيد…",
    expirou: "استُخدم هذا الرابط من قبل أو انتهت صلاحيته.",
    irParaOApp: "الذهاب إلى التطبيق",
  },
  tema: {
    indisponivel: "السمة غير متاحة",
    indisponivelDetalhe: "حذفها ناشرها، أو أن الرابط خاطئ.",
    indisponivelLinha: "السمة غير متاحة. حذفها ناشرها، أو أن الرابط خاطئ.",
    importar: "استيراد السمة",
    importarCurto: "استيراد",
    importarDetalhe: "سيحل هذا محل السمة الحالية. يمكنك تعديلها لاحقًا من الإعدادات > المظهر > استوديو السمات.",
    porAutor: "بواسطة {{autor}}",
    umaCorTrocada: "لون واحد مُبدَّل",
    coresTrocadas: "{{quantas}} لونًا مُبدَّلًا",
    avisoDeCss: "تحمل هذه السمة CSS من كاتبها، وCSS يطال أي ركن من الشاشة. لا تستوردها إلا ممن تثق بهم.",
    soCores: "هذه السمة تبدّل الألوان فقط. لا CSS خارجي فيها.",
    aplicar: "تطبيق",
    previaSemMotor: "المعاينة لا تشغّل المحرّك. ثبّتها لتراه.",
    motorAnimado: "{{motor}} متحرك",
  },
  sair: "تسجيل الخروج",
  versoes: {
    termos: "شروط الخدمة",
    privacidade: "سياسة الخصوصية",
    copiar: "انقر للنسخ",
    copiado: "تم النسخ",
  },
  telas: {
    conta: "حسابي",
    privacidade: "الخصوصية",
    conexoes: "الاتصالات",
    voz: "الصوت",
    video: "الفيديو",
    avisos: "الإشعارات",
    aplicativos: "التطبيقات",
    aparencia: "المظهر",
    batePapo: "الدردشة",
    acessibilidade: "إمكانية الوصول",
    idioma: "اللغة",
    aplicativo: "تنزيل التطبيق",
    atalhos: "الاختصارات",
    desktop: "تطبيق سطح المكتب",
    avancado: "متقدم",
    servidor: "الخادم",
    comunicado: "بيان النظام",
    denuncias: "البلاغات",
    publicacoes: "عمليات النشر",
  },
  grupos: {
    conta: "الحساب",
    app: "إعدادات التطبيق",
    desenvolvedor: "المطوّر",
    administracao: "الإدارة",
  },
  secoes: {
    detalhesDeLogin: "بيانات تسجيل الدخول",
    dispositivos: "الأجهزة",
    usuariosBloqueados: "المستخدمون المحظورون",
    aplicativosAutorizados: "التطبيقات المصرّح لها",
    sessoes: "الجلسات",
    amigosEDms: "الأصدقاء والرسائل المباشرة",
    compartilhamentoDeAtividade: "مشاركة النشاط",
    visibilidadeDoPerfil: "ظهور الملف الشخصي",
    exportarDados: "تصدير البيانات",
    exclusaoDeDados: "حذف البيانات",
    tema: "السمة",
    corDeDestaque: "لون التمييز",
    interface: "الواجهة",
    listaDeCanais: "قائمة القنوات",
    zoomDoApp: "مستوى تكبير التطبيق",
    escalaDaFonte: "حجم خط الدردشة",
    modoStreamer: "خصوصية البث",
    cursores: "المؤشرات",
    movimento: "الحركة",
    textoEmVoz: "تحويل النص إلى كلام",
    teclado: "لوحة المفاتيح",
    formatoDaHora: "تنسيق الوقت",
    idiomaDaInterface: "لغة الواجهة",
    dispositivosDeVoz: "الأجهزة",
    testeDoMicrofone: "اختبار الميكروفون",
    modoDeEntrada: "وضع الإدخال",
    sensibilidade: "حساسية الإدخال",
    qualidade: "الجودة",
    camera: "الكاميرا",
    transmissao: "البث",
    exibicao: "العرض",
    entrada: "الإدخال",
    midia: "الوسائط",
    geral: "عام",
    preferenciaDeMencao: "تفضيل الإشارات",
    sons: "الأصوات",
  },
};
