export const conversa = {
  lista: {
    carregando: "جارٍ تحميل الرسائل…",
    carregandoMais: "جارٍ التحميل…",
    verMais: "مرّر للأعلى لرؤية المزيد",
    semHistorico: "السجل غير متاح",
    semHistoricoDetalhe: "رتبتك لا تملك إذن قراءة سجل ‎#{{canal}}‎. الرسائل الجديدة ستظل تظهر ما دمت هنا.",
    boasVindas: "أهلًا بك في ‎#{{canal}}‎",
    boasVindasDetalhe: "هذه بداية قناة ‎#{{canal}}‎.",
  },
  data: {
    hoje: "اليوم",
    ontem: "أمس",
    hojeAs: "اليوم في {{hora}}",
    ontemAs: "أمس في {{hora}}",
  },
  digitando: {
    um: "{{nome}} يكتب الآن…",
    dois: "{{primeiro}} و{{segundo}} يكتبان الآن…",
    varios: "{{quantidade}} أشخاص يكتبون الآن…",
  },
  mensagem: {
    usou: "استخدم",
    fixada: "مثبّتة",
    editado: "(معدّلة)",
    ignorada: "رسالة من شخص تتجاهله.",
    mostrar: "إظهار",
    escPara: "Esc لـ",
    cancelar: "الإلغاء",
    enterParaSalvar: "Enter للحفظ",
    falhou: "لم تُرسَل. حاول مرة أخرى",
    naoLidasDaqui: "غير مقروءة من هنا.",
    linkCopiado: "تم نسخ الرابط.",
    idCopiado: "تم نسخ المعرّف.",
    naoDeuParaCopiar: "متصفحك لم يسمح بالنسخ.",
    apagarTitulo: "حذف الرسالة؟",
    apagarDescricao: "ستختفي عن جميع من في القناة، ولا يمكن استرجاعها.",
    apagarAcao: "حذف",
    citacaoAnexo: "انقر لرؤية المرفق",
    citacaoSumiu: "الرسالة الأصلية لم تعد هنا.",
    reagirCom: "تفاعل بـ {{emoji}} — اضغط مطوّلًا للتفاعل الخارق",
    segureParaSuper: "{{emoji}} — اضغط مطوّلًا للتفاعل الخارق",
  },
  acoes: {
    reagir: "تفاعل",
    responder: "رد",
    encaminhar: "إعادة توجيه",
    favoritar: "حفظ الرسالة",
    tirarDosFavoritos: "إزالة من المحفوظات",
    marcarNaoLida: "تعليم كغير مقروءة",
    copiarLink: "نسخ رابط الرسالة",
    copiarId: "نسخ معرّف الرسالة",
    fixar: "تثبيت الرسالة",
    desafixar: "إلغاء التثبيت",
    editar: "تعديل",
    apagar: "حذف",
    mais: "المزيد",
    adicionarReacao: "إضافة تفاعل",
    superReagirCom: "تفاعل خارق بـ {{emoji}}",
    fixarMensagem: "تثبيت الرسالة",
    desafixarMensagem: "إلغاء تثبيت الرسالة",
    editarMensagem: "تعديل الرسالة",
    apagarMensagem: "حذف الرسالة",
  },
  mencao: {
    cargo: "إشارة إلى رتبة",
    pessoa: "إشارة",
    alguem: "شخص ما",
    cargoSemNome: "رتبة",
    here: "ينبّه المتصلين الآن",
    everyone: "ينبّه الخادم كله",
  },
  codigo: {
    copiar: "نسخ",
    copiado: "تم النسخ",
    copiarAria: "نسخ الكود",
    copiadoAria: "تم نسخ الكود",
  },
  caixa: {
    escrever: "اكتب في ‎#{{canal}}‎",
    escreverSemCanal: "اكتب رسالة",
    semPermissao: "ليس لديك إذن بإرسال رسائل في هذه القناة",
    solteParaAnexar: "أفلت للإرفاق",
    respondendoPara: "رد على",
    vaiNotificar: "سيصله إشعار",
    naoVaiNotificar: "لن يصله إشعار",
    ligado: "مفعّل",
    desligado: "معطّل",
    pararDeResponder: "إلغاء الرد",
    mais: "المزيد",
    enviarArquivo: "إرسال ملف",
    criarEnquete: "إنشاء استطلاع",
    expressoes: "إيموجي وGIF وملصقات",
    enviar: "إرسال",
    aguardandoEnvio: "في انتظار الرفع",
    modoLento: "الوضع البطيء مفعّل ({{tempo}})",
    modoLentoDica: "الوضع البطيء مضبوط على {{segundos}} ثانية. انتظر قبل إرسال رسالة أخرى.",
  },
  anexos: {
    enviando: "جارٍ الرفع…",
    modificar: "تعديل {{arquivo}}",
    remover: "إزالة {{arquivo}}",
    ver: "عرض {{arquivo}}",
    mostrarSpoiler: "إظهار الحرق: {{arquivo}}",
    spoiler: "حرق",
    spoilerTitulo: "حرق",
    editarTitulo: "تعديل المرفق",
    nomeDoArquivo: "اسم الملف",
    descricao: "وصف النص البديل",
    descricaoDica: "صف هذه الوسائط لقارئات الشاشة",
    marcarSpoiler: "تعليم كحرق",
    cancelar: "إلغاء",
    salvar: "حفظ",
  },
  cartao: {
    tocador: "المشغّل",
    abrir: "فتح {{destino}}",
    tocar: "تشغيل {{titulo}}",
    video: "فيديو",
    verImagem: "عرض الصورة",
  },
  enquete: {
    titulo: "استطلاع",
    encerrada: "انتهى الاستطلاع",
    variasRespostas: "استطلاع — إجابات متعددة",
    umVoto: "{{quantidade}} صوت",
    votos: "{{quantidade}} صوتًا",
    umVotoNoTotal: "{{quantidade}} صوت في المجموع",
    votosNoTotal: "{{quantidade}} صوتًا في المجموع",
    encerraEm: "ينتهي في {{quando}}",
    encerrarAgora: "إنهاء الآن",
  },
  fixadas: {
    titulo: "الرسائل المثبّتة",
    vazio: "لا توجد رسائل مثبّتة في هذه القناة… حتى الآن.",
    desafixar: "إلغاء التثبيت",
    anexo: "(مرفق)",
    enquete: "(استطلاع)",
    dicaRotulo: "معلومة مفيدة:",
    dica: "من يملك صلاحية «إدارة الرسائل» يستطيع التثبيت مباشرة من قائمة الرسالة.",
  },
  encaminhar: {
    titulo: "إعادة توجيه الرسالة",
    paraOnde: "إلى أين؟",
    semTexto: "(رسالة بلا نص)",
    nenhumLugar: "لا يوجد مكان بهذا الاسم.",
    canais: "القنوات",
    conversas: "الرسائل المباشرة",
  },
  expressoes: {
    gifs: "صور GIF",
    buscarGifs: "ابحث في Klipy",
    figurinha: "ملصق",
    buscarFigurinha: "اعثر على الملصق المثالي",
    buscarEmoji: "اعثر على الإيموجي المثالي",
    buscarReacao: "اعثر على التفاعل المثالي",
    adicionarEmoji: "إضافة إيموجي",
    limparBusca: "مسح البحث",
  },
  busca: {
    fechar: "إغلاق البحث",
    procurando: "جارٍ البحث…",
    resultado: "{{quantos}} نتيجة",
    resultados: "{{quantos}} نتيجة",
    nadaCom: "لا شيء بخصوص {{termo}} هنا.",
    soOsQuePodeLer: "البحث ينظر فقط في القنوات التي يمكنك قراءتها.",
  },
  entrada: {
    titulo: "صندوق الوارد",
    naoLidas: "غير مقروءة",
    salvas: "المحفوظة",
    mencoes: "الإشارات",
    fimTitulo: "وصلت إلى النهاية",
    fimDetalhe: "لم يبقَ شيء للقراءة. عندما تصل رسالة جديدة، ستظهر هنا.",
    semSalvosTitulo: "لا عناصر محفوظة",
    semSalvosDetalhe: "اضغط Shift وانقر على علامة الرسالة لتحتفظ بها وتقرأها لاحقًا.",
    tirarDosSalvos: "إزالة من المحفوظات",
    semMencoesTitulo: "لا إشارات بعد",
    semMencoesDetalhe: "الإشارات إليك تظهر هنا لآخر 7 أيام.",
  },
  forum: {
    descricao: "كل موضوع يصير محادثة مستقلة — مفيد للسؤال الذي لا ينبغي أن يضيع وسط الدردشة.",
    novoAssunto: "موضوع جديد",
    vazio: "لا مواضيع بعد. ابدأ الأول وتبقى المحادثة مرتبة من البداية.",
    titulo: "العنوان",
    doQueSeTrata: "عمّ يدور؟",
    primeiraMensagem: "الرسالة الأولى",
    conteDoCaso: "احكِ القصة",
  },
};
