export const perfil = {
  carregando: "جارٍ التحميل…",
  editar: "تعديل الملف الشخصي",
  mensagem: "رسالة",
  abrirConversa: "فتح المحادثة",
  verCompleto: "عرض الملف الكامل",
  convidarParaServidor: "دعوة إلى الخادم",
  semServidores: "ليس لديك خوادم",
  conviteEnviado: "أُرسلت الدعوة إلى {{nome}}.",
  moderador: "فتح في عرض المشرف",
  mais: "المزيد",
  ignorar: "تجاهل",
  deixarDeIgnorar: "إلغاء التجاهل",
  copiarId: "نسخ معرّف المستخدم",
  idCopiado: "تم نسخ المعرّف.",
  conexoes: "الاتصالات",
  membroDesde: "عضو منذ",
  sobre: "نبذة",
  cargosTitulo: "الرتب",
  visaoGeral: "نظرة عامة",
  amigosEmComum: "أصدقاء مشتركون ({{quantidade}})",
  servidoresEmComum: "خوادم مشتركة ({{quantidade}})",
  amizade: {
    amigo: "صديق",
    pedidoEnviado: "أُرسل طلب الصداقة",
    respondaAbaixo: "أرسل لك طلبًا — أجب في الأسفل",
    adicionar: "إضافة صديق",
    teMandouPedido: "أرسل لك طلب صداقة",
    aceitar: "قبول",
    desfazer: "إلغاء الصداقة",
    desfazerTitulo: "إزالة {{nome}} من أصدقائك؟",
    desfazerDescricao: "لن تبقيا صديقين. تبقى المحادثة الخاصة في السجل، ويمكنك إضافته مرة أخرى لاحقًا.",
    bloquear: "حظر",
    bloquearTitulo: "حظر {{nome}}؟",
    bloquearDescricao: "لن تبقيا صديقين، وتتوقف المحادثة الخاصة عن استقبال الرسائل، ولن يستطيع إرسال طلب صداقة لك بعد الآن.",
    linkCopiado: "لستما صديقين — نُسخ الرابط لترسله بنفسك.",
  },
  recado: {
    escrever: "راسل ‎@{{usuario}}‎",
    enviar: "إرسال",
    enviada: "أُرسلت الرسالة",
    falhou: "تعذّر الإرسال. جرّب من المحادثة.",
  },
  cartao: {
    trocarFaixa: "تغيير غلاف البطاقة",
    trocarFaixaCurto: "تغيير الغلاف",
    trocarFoto: "تغيير صورة الملف الشخصي",
    trocarFotoCurto: "تغيير الصورة",
    suaEtiqueta: "وسمك",
    editarEtiqueta: "انقر لتعديل وسمك",
    conteAlgo: "احكِ لنا شيئًا عنك",
    adicionarStatus: "إضافة حالة",
    adicionarDescricao: "انقر لإضافة وصف",
    cargo: "رتبة",
    cargos: "رتب",
    cargosCom: "رتب — {{quantidade}}",
    tirarCargo: "إزالة رتبة {{cargo}}",
  },
  cargos: {
    adicionar: "إضافة رتبة",
    procurar: "البحث عن رتبة",
  },
  etiqueta: {
    escolher: "اختيار وسم الخادم",
    nenhuma: "لا يوجد وسم خادم",
    semEtiqueta: "لا يملك أي من خوادمك وسمًا",
  },
  emblemas: {
    doServidor: "شارات هذا الخادم",
    limite: "يمكنك ارتداء حتى {{quantidade}} شارات.",
  },
  nota: {
    vazia: "انقر لتدوين شيء",
    rotulo: "ملاحظة (تراها وحدك)",
  },
  status: {
    titulo: "الحالة",
    definir: "تحديد حالتك",
    escolherEmoji: "اختيار إيموجي",
    tirarEmoji: "إزالة الإيموجي",
    oQuePensa: "بم تفكّر؟",
    limparAgora: "مسح الحالة الآن",
    naoLimpar: "عدم المسح",
    limpar30m: "المسح بعد 30 دقيقة",
    limpar1h: "المسح بعد ساعة",
    limpar4h: "المسح بعد 4 ساعات",
    limparHoje: "المسح اليوم",
    limparAmanha: "المسح غدًا",
    comHora: "{{prazo}} في {{hora}}",
  },
  presenca: {
    disponivel: "متاح",
    ausente: "بعيد",
    naoPerturbar: "عدم الإزعاج",
    naoPerturbarDetalhe: "لا تصلك تنبيهات الرسائل الجديدة",
    invisivel: "خفي",
    invisivelDetalhe: "تظهر للآخرين غير متصل",
  },
  menu: {
    mudarDeConta: "تبديل الحساب",
    gerenciarContas: "إدارة الحسابات",
  },
  editor: {
    decoracao: "تغيير زخرفة الصورة الرمزية",
    naoSalvo: "لا تنسَ حفظ تغييراتك!",
    principal: "الملف الرئيسي",
  },
};
