export const servidor = {
  comunidade: {
    ativa: "المجتمع مفتوح",
    ativaDesde: "مفتوح منذ {{quando}}",
    membrosAgora: "{{quantos}} عضوًا",
    criarParaMim: "أنشئ واحدة من أجلي",
    canalDeRegras: "قناة القواعد",
    canalDeRegrasDetalhe: "المكان الذي توجد فيه القواعد التي يقرأها الجميع قبل الكتابة.",
    canalDeAvisos: "قناة إعلانات المجتمع",
    canalDeAvisosDetalhe: "وجهة ما يتغيّر هنا، ولمن يديرون المكان وحدهم.",
    canalDeSeguranca: "قناة تنبيهات الأمان",
    canalDeSegurancaDetalhe: "حيث يستلم المشرفون ما التقطته الفلاتر.",
    idiomaPrincipal: "اللغة الأساسية",
    idiomaPrincipalDetalhe: "اللغة التي يجري بها معظم الحديث.",
    semIdioma: "لم تُختَر لغة",
    semCanal: "بلا قناة",
    finalTitulo: "اقتربنا",
    finalDetalhe: "قبل الفتح، اطّلع على ما سيتغيّر لمن ينضمّ.",
    confereRegras: "من ينضمّ يرى قناة القواعد قبل كل شيء.",
    confereEveryone: "أصحاب الرتب وحدهم يستخدمون ‎@everyone‎ و‎@here‎.",
    confereMencoes: "الإشارة إلى الجميع دفعة واحدة تصبح بإذن.",
    concordo: "أوافق وأفهم",
    concordoDetalhe: "أنت تؤكّد أن المجتمع يلتزم بإرشادات المنصّة.",
    proximo: "التالي",
    terminar: "إنهاء الإعداد",
    visaoGeral: "نظرة عامة",
    visaoGeralDetalhe: "القنوات التي يخاطب بها المجتمع القادمين الجدد.",
    seguranca: "الأمان",
    segurancaDetalhe: "الكوابح التي تحجز الإزعاج والمحتوى الثقيل.",
    habilitada: "تم تفعيل المجتمع.",
    falhou: "تعذّر تفعيل المجتمع.",
    titulo: "المجتمع",
    ilustracao: "فقاعات محادثة",
    convite: "هل تبني مجتمعًا؟",
    conviteDetalhe: "حوّله إلى مجتمع لتحصل على أدوات من يدير مكانًا كبيرًا: قناة قواعد، وإعلانات من الفريق، وفلاتر تشرف وحدها.",
    contagem: "{{membros}} من {{minimo}} عضوًا",
    faltam: "يتبقّى {{quantos}} للفتح.",
    prontoParaAbrir: "صار جاهزًا للفتح.",
    habilitar: "تفعيل المجتمع",
    vantagemCrescer: "النمو",
    vantagemCrescerDetalhe: "يمكن للمجتمع التقدّم لقسم الاستكشاف، فيجدك من يبحث عن موضوعه.",
    vantagemModerar: "الإشراف",
    vantagemModerarDetalhe: "اشتراط بريد مُوثَّق، وفلترة الوسائط، وتشغيل AutoMod دفعة واحدة.",
    vantagemAvisos: "متابعة الجديد",
    vantagemAvisosDetalhe: "يرسل الفريق ما يتغيّر إلى من يدير المكان، في قناة خاصة بكم.",
    assistenteTitulo: "لنجهّز مجتمعك.",
    passoSeguranca: "فحوصات الأمان",
    passoBasico: "التجهيز الأساسي",
    passoFinal: "اللمسات الأخيرة",
    seguraTitulo: "حافظ على أمان المجتمع",
    seguraDetalhe: "المجتمعات الكبيرة تجذب الإزعاج. هذان الكابحان يعملان افتراضيًا، ويمكنك إيقافهما لاحقًا إن أزعجاك.",
    emailVerificado: "اشتراط بريد مُوثَّق",
    emailVerificadoDetalhe: "من لم يؤكّد بريده لا يرسل رسائل. أصحاب الرتب يمرّون مباشرة.",
    filtroDeMidia: "فلترة الوسائط الصريحة",
    filtroDeMidiaDetalhe: "تصل الصور ومقاطع الفيديو مخفية، ولا تظهر إلا حين يختار أحدهم رؤيتها.",
    basicoTitulo: "جهّز الأساسيات",
    basicoDetalhe: "حدّد قناة القواعد ووجهة إعلانات الفريق. إن لم تختر قناة، سأنشئ القناتين.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} أمرًا",
    previa: "شكل البطاقة",
    trocarIcone: "تغيير الأيقونة",
    tirarCapa: "إزالة الغلاف",
    heroComunidades: "هناك من يتحدّث عمّا تحبّه",
    heroComunidadesDetalhe: "مجتمعات فتحها من يستخدم المنصّة. ادخل، اقرأ الحديث، وابقَ إن أعجبك.",
    emDestaque: "مختارات",
    todasAsComunidades: "البقية",
    heroTitulo: "ما الذي ستستخدمه مجموعتك اليوم؟",
    heroDetalhe: "بوتات للموسيقى واللعب والإشراف، صنعها من هم هنا مثلكم. اختر واحدًا فينضمّ إلى خادمك.",
    novidades: "وصلت للتو",
    todosOsApps: "البقية",
    lojaTitulo: "صفحة التطبيق",
    lojaDetalhe: "هذا ما يظهر في الاستكشاف لمن لا يعرفه بعد.",
    capa: "صورة الغلاف",
    capaDetalhe: "الصورة العريضة أعلى الصفحة. مقاس 1280 × 720 مناسب.",
    trocarCapa: "تغيير الغلاف",
    categorias: "التصنيفات",
    categoriasDetalhe: "حتى {{quantas}}. عبرها يتصفّح الناس في الاستكشاف.",
    idiomas: "اللغات",
    idiomasDetalhe: "حتى {{quantos}}. اللغات التي يردّ بها التطبيق.",
    termos: "شروط الاستخدام",
    politica: "سياسة الخصوصية",
    politicas: "السياسات",
    servidorDeSuporte: "خادم الدعم",
    servidorDeSuporteDetalhe: "وجهة من يحتاج مساعدة بشأن التطبيق.",
    semServidor: "بلا خادم",
    emQuantosServidores: "في كم خادمًا",
    categoria: {
      GAMES: "الألعاب",
      MUSICA: "الموسيقى",
      MODERACAO: "الإشراف",
      PRODUTIVIDADE: "الإنتاجية",
      SOCIAL: "اجتماعي",
      UTILIDADES: "أدوات",
      ARTE_E_CRIACAO: "الفن والإبداع",
      EDUCACAO: "التعليم",
      OUTRA: "أخرى",
    },
    appIndisponivel: "التطبيق غير متاح",
    voltarParaExplorar: "العودة إلى الاستكشاف",
    adicionarApp: "إضافة التطبيق",
    copiarLink: "نسخ الرابط",
    denunciarApp: "الإبلاغ عن التطبيق",
    copiarIdDoApp: "نسخ معرّف التطبيق",
    visaoGeral: "نظرة عامة",
    comandos: "الأوامر",
    permissoes: "الأذونات",
    semPermissoes: "هذا التطبيق لا يطلب أي أذونات.",
    avisoDePermissoes: "يدخل برتبة خاصة به. يمكنك تعديل هذه الأذونات لاحقًا من إعدادات المجتمع ← الرتب.",
    servidoresEmComum: "مجتمعات مشتركة",
    umServidorEmComum: "مجتمع واحد",
    quantosServidoresEmComum: "{{quantos}} مجتمعات",
    feitoPor: "من صنع",
    publicadoEm: "نُشر في",
    denunciarNome: "الإبلاغ عن {{nome}}",
    denunciaDetalhe: "يصل البلاغ إلى فريق Gravaê. لن يعرف صاحب التطبيق أنك من أبلغ.",
    denunciaFalhou: "تعذّر إرسال البلاغ.",
    umMembro: "عضو واحد",
    semDescricao: "بلا وصف.",
    adicionar: "إضافة",
    jaEstaAqui: "أنت هنا بالفعل",
    entrando: "جارٍ الدخول…",
    entrar: "انضمام",
    comunidadePublica: "مجتمع عام",
    online: "{{quantos}} متصل",
    membros: "{{quantos}} عضو",
    abrirComunidade: "فتح المجتمع",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "إعدادات الخادم",
  novasMensagens: "رسائل جديدة",
  menu: {
    silenciar: "كتم المجتمع",
    reativar: "إلغاء كتم المجتمع",
    porQuinze: "لمدة 15 دقيقة",
    porMeiaHora: "لمدة 30 دقيقة",
    porTresHoras: "لمدة 3 ساعات",
    porTresDias: "لمدة 3 أيام",
    porUmaHora: "لمدة ساعة",
    porOitoHoras: "لمدة 8 ساعات",
    porUmDia: "لمدة 24 ساعة",
    ateReativar: "حتى أعيد التفعيل",
    notificacoes: "إعدادات الإشعارات",
    padrao: "استخدام الافتراضي",
    todas: "كل الرسائل",
    soMencoes: "الإشارات فقط",
    nada: "لا شيء",
    ocultarSilenciados: "إخفاء القنوات المكتومة",
    denunciar: "الإبلاغ عن المجتمع",
    marcarLida: "وضع علامة كمقروء",
    convidar: "دعوة أعضاء",
    editarPerfil: "تعديل ملف المجتمع",
    configuracoes: "إعدادات المجتمع",
    sair: "مغادرة المجتمع",
    sairTitulo: "مغادرة {{nome}}؟",
    sairDescricao: "ستحتاج إلى دعوة جديدة للعودة.",
    copiarId: "نسخ معرف المجتمع",
    idCopiado: "تم نسخ المعرف.",
  },
  convite: {
    cartaoTitulo: "تلقّيت دعوة للانضمام إلى مجتمع",
    indisponivel: "الدعوة غير متاحة",
    indisponivelDetalhe: "انتهت صلاحيتها، أو نفد عددها، أو حذفها من أنشأها.",
    entrar: "الانضمام إلى المجتمع",
    chamado: "تمت دعوتك للانضمام إلى",
    aceitarComo: "قبول باسم {{nome}}",
    abrir: "فتح المجتمع",
    recusar: "لا، شكرًا",
  },
  pasta: {
    silenciarTodas: "كتم المجتمعات",
    reativarTodas: "إلغاء كتم المجتمعات",
    mostrarSilenciados: "إظهار القنوات المكتومة",
    notificacoesDaComunidade: "إعدادات الإشعارات",
    silenciarEveryone: "كتم @everyone و @here",
    permitirEveryone: "السماح بـ @everyone و @here",
    silenciarCargos: "كتم إشارات الأدوار",
    permitirCargos: "السماح بإشارات الأدوار",
    dicaDaCor: "اكتب لونًا (hex أو rgb() أو hsl() أو اسمًا) أو استخدم المنتقي.",
    mostrarIcone: "إظهار الأيقونة عند الإغلاق",
    dicaDoIcone: "عند الإغلاق تظهر الأيقونة بدل الخوادم.",
    icone: "أيقونة المجلد",
    excluir: "حذف المجلد",
    icones: {
      pasta: "مجلد",
      estrela: "مفضّل",
      coracao: "قلب",
      salvar: "حفظ",
      jogo: "ذراع ألعاب",
      escudo: "درع",
      nota: "نوتة موسيقية",
    },
    marcarLida: "وضع علامة على المجلد كمقروء",
    configuracoes: "إعدادات المجلد",
    desfazer: "فك المجلد",
    titulo: "المجلد",
    nome: "الاسم",
    semNome: "بدون اسم",
    cor: "اللون",
    semCor: "بدون لون",
    salvar: "حفظ",
  },
  denuncia: {
    titulo: "الإبلاغ عن {{nome}}",
    descricao: "يصل البلاغ إلى فريق Gravaê. أخبرنا بما حدث.",
    motivo: "السبب",
    detalhes: "التفاصيل (اختياري)",
    enviar: "إرسال البلاغ",
    enviada: "تم إرسال البلاغ. شكرًا.",
    motivos: {
      spam: "رسائل مزعجة أو إعلانات",
      assedio: "تحرش أو كراهية",
      conteudo: "محتوى غير لائق",
      golpe: "احتيال",
      outro: "أخرى",
    },
  },
  selos: {
    verificada: "مجتمع موثّق",
    detectavel: "مجتمع قابل للاكتشاف",
  },
  auditoria: {
    todasAsAcoes: "كل الإجراءات",
    todosOsUsuarios: "كل المستخدمين",
    filtroMembros: "الأعضاء",
    filtroCanais: "القنوات",
    filtroEmojis: "الإيموجي",
    filtroServidor: "الخادم",
    titulo: "سجل الإجراءات",
    porUsuario: "تصفية حسب الشخص",
    porAcao: "تصفية حسب الإجراء",
    vazio: "لم يُسجَّل شيء بعد بهذا الفلتر.",
    motivo: "السبب:",
  },
  banimentos: {
    titulo: "قائمة المحظورين في الخادم",
    descricao: "من هنا لا يعود حتى بدعوة جديدة. رفع الحظر يعيد الوصول فورًا.",
    procurar: "ابحث في الحظر باسم المستخدم",
    vazioTitulo: "لا يوجد محظورون",
    vazio: "لم تحظر أحدًا بعد… لكن إن احتجت يومًا، فلا تتردد.",
    desbanir: "رفع الحظر",
  },
  excluir: {
    tudoVai: "ستُحذف كل قنوات {{servidor}} ورسائله ودعواته لدى {{membros}} عضوًا. ولن يستطيع أحد استرجاعها بعد ذلك.",
    digite: "اكتب {{servidor}} للتأكيد",
    titulo: "حذف الخادم",
    aviso: "لا يمكن التراجع عن هذا.",
  },
  emblemas: {
    apagarDescricao: "يُنزع عن كل من يرتديه. لا يمكن التراجع.",
    titulo: "الشارات",
    vazio: "لا توجد شارات بعد.",
    novo: "شارة جديدة",
  },
  convites: {
    revogarTitulo: "إلغاء الدعوة؟",
    revogarAcao: "إلغاء",
    revogarDescricao: "الرابط {{codigo}} يتوقف عن العمل فورًا. ومن دخل به من قبل يبقى في الخادم.",
    titulo: "الدعوات",
    descricao: "كل روابط الدعوة الفعّالة لهذا الخادم.",
    vazio: "لم تُنشأ أي دعوة بعد.",
    revogar: "إلغاء الدعوة",
  },
  integracoes: {
    opcionais: "‏username و avatar_url اختياريان ويسريان لكل رسالة. الحد 5 رسائل كل 5 ثوانٍ.",
    apagarDescricao: "يتوقف الرابط عن العمل فورًا. والرسائل التي أرسلها من قبل تبقى في القناة.",
    titulo: "التكاملات",
    descricao: "الويب هوك عنوان ينشر في قناة دون الحاجة إلى حساب. يفيد للإعلان بأن البناء نجح، أو أن أحدهم فتح طلبًا، أو أي شيء تريد إرساله من سكربت.",
    novo: "ويب هوك جديد",
    vazio: "لا توجد ويب هوكات بعد. أنشئ واحدًا وألصق الرابط حيث تريد أن تأتي الرسالة.",
    canal: "القناة",
    apagar: "حذف الويب هوك",
    comoUsar: "طريقة الاستخدام",
    comoUsarTexto: "أرسل POST بصيغة JSON:",
  },
  explorar: {
    titulo: "استكشاف",
  },
  engajamento: {
    semCanal: "بلا قناة نظام",
    titulo: "التفاعل",
    descricao: "ما يفعله الخادم من تلقاء نفسه كي لا يبدو فارغًا حين يصل شخص جديد.",
    sistema: "رسائل النظام",
    boasVindas: "أرسل رسالة ترحيب عند انضمام أحدهم",
    sorteio: "بدون نص خاص بك في الأسفل، تُسحب العبارة عشوائيًا — العبارة نفسها تملّ سريعًا.",
    canalDoSistema: "قناة رسائل النظام",
    mensagem: "رسالة الترحيب",
    deixeVazio: "اتركه فارغًا ليُسحب من العبارات الجاهزة",
  },
  automod: {
    titulo: "الإشراف التلقائي",
    descricao: "مرشّحات تُشرف من تلقاء نفسها، قبل أن توجد الرسالة أصلًا. من يدير الخادم لا يُرشَّح أبدًا — والأدوار المعفاة تمرّ مباشرة.",
    palavras: {
      titulo: "حظر كلماتك",
      descricao: "قائمتك بالكلمات التي لا يجوز لأحد كتابتها.",
    },
    mencoes: {
      titulo: "حظر إغراق الإشارات",
      descricao: "يحظر رسالة فيها إشارات كثيرة دفعة واحدة.",
    },
    links: {
      titulo: "حظر الروابط",
      descricao: "يوقف أي عنوان يُلصق في الدردشة.",
    },
    definir: "إعداد",
    nomeDaRegra: "اسم القاعدة",
    bloqueadas: "الكلمات المحظورة",
    digiteEnter: "اكتب واضغط Enter",
    comparacao: "المقارنة تتجاهل حالة الأحرف والتشكيل وعلامات الترقيم — ولا تلتقط كلمة داخل كلمة أخرى.",
    aPartirDe: "الحظر ابتداءً من كم إشارة",
    oQueFazer: "ما العمل",
    canalDoAlerta: "قناة التنبيه",
    escolhaCanal: "اختر قناة",
    castigo: "الإسكات (دقائق)",
    isentos: "الأدوار المعفاة",
    semCargos: "لم تُنشأ أدوار بعد.",
    salvarRegra: "حفظ القاعدة",
    apagar: "حذف القاعدة",
    excluirTitulo: "حذف قاعدة الإشراف التلقائي هذه؟",
    excluirDescricao: "يتوقف الخادم عن الترشيح بها فورًا. يمكنك إنشاؤها من جديد، لكن الإعداد الحالي يضيع.",
    excluirAcao: "حذف القاعدة",
  },
  cargos: {
    titulo: "الأدوار",
    descricao: "الأدوار تمنح اسمًا ولونًا وصلاحيات. من هو أعلى في القائمة يعلو على من تحته — ولا أحد يمسّ دورًا مساويًا لدوره أو أعلى منه.",
    criar: "إنشاء دور",
    vazio: "لا توجد أدوار بعد.",
    abaExibicao: "العرض",
    abaPermissoes: "الأذونات",
    abaMembros: "الأعضاء — {{quantos}}",
    everyone: "ينطبق على الجميع في الخادم. إنه الأساس الذي تُبنى عليه بقية الأدوار.",
    nomeDoCargo: "اسم الدور",
    cor: "لون الدور",
    corDica: "يلوّن اسم صاحب الدور في قائمة الأعضاء وفي الدردشة.",
    semCor: "بلا لون",
    corPersonalizada: "لون مخصص",
    estilo: "نمط الاسم",
    segundaCor: "اللون الثاني",
    segundaCorDica: "بدونه يعود التدرّج إلى لون واحد — لا يختفي.",
    limparSegundaCor: "مسح اللون الثاني",
    icone: "أيقونة",
    iconeDica: "تظهر بجانب الدور في بطاقة ملف صاحبه.",
    exibirSeparado: "اعرضه منفصلًا عن بقية الأعضاء",
    exibirSeparadoDica: "يحصل الدور على قسم خاص به في قائمة الأعضاء.",
    permitirMencionar: "السماح بالإشارة إلى هذا الدور",
    permitirMencionarDica: "سيتمكن أي أحد من تنبيه كل من لديه هذا الدور.",
    semPoderDeConceder: "{{descricao}} (لا تملك هذا الإذن لتمنحه)",
    adicionar: "أضف أحدًا إلى هذا الدور",
    tirar: "سحب الدور",
    semNinguem: "لا أحد يملك هذا الدور بعد.",
    apagar: "حذف الدور",
    excluirTitulo: "حذف الدور \"{{nome}}\"؟",
    excluirDescricao: "من لديه هذا الدور يفقد كل ما كان يمنحه. لا يمكن التراجع.",
    excluirAcao: "حذف الدور",
  },
  membros: {
    procurar: "ابحث بالاسم أو باسم المستخدم",
    membroDesde: "عضو منذ",
    vazio: "لم يُعثر على أحد.",
    acoesPara: "إجراءات {{nome}}",
    deCastigo: "إسكات",
    tirarCastigo: "رفع الإسكات",
    castigo5min: "5 دقائق",
    castigo1h: "ساعة",
    castigo1d: "يوم",
    castigo1s: "أسبوع",
    expulsar: "طرد",
    expulsarTitulo: "طرد {{nome}}؟",
    expulsarDescricao: "يغادر {{servidor}} فورًا. يمكنه العودة بدعوة — الطرد لا يمنع العودة.",
    banir: "حظر",
    banirTitulo: "حظر {{nome}}؟",
    banirDescricao: "يغادر {{servidor}} ولا يعود، ولا حتى بدعوة، حتى يُرفع الحظر.",
    motivo: "السبب (اختياري)",
    motivoDica: "يُسجَّل في سجل الإجراءات",
  },
  perfil: {
    titulo: "ملف الخادم",
    descricao: "هكذا يظهر خادمك في القائمة وفي روابط الدعوة.",
    icone: "أيقونة",
    faixa: "اللافتة العلوية",
    nomeDoServidor: "اسم الخادم",
    campoDescricao: "الوصف",
    doQueE: "عمّ يدور هذا الخادم؟",
    comprimido: "ضُغط قبل الرفع: {{economia}}",
  },
  etiqueta: {
    titulo: "وسم الخادم",
    descricao: "وسم من 4 أحرف كحد أقصى يظهر بجانب اسم كل عضو — في الدردشة وفي قائمة الأشخاص. هنا مجاني: بلا تعزيزات وبلا مستويات.",
    escolhaNome: "اختر اسمًا",
    limite: "4 أحرف كحد أقصى، حروف وأرقام.",
    escolhaInsignia: "اختر شارة",
    voce: "أنت",
    fala1: "في أحد للعب؟",
    fala2: "شوف وسمي!",
    fala3: "يا سلام، كيف حصلت عليه",
  },
  expressoes: {
    comoUsar: "أضف حتى {{limite}} إيموجي يمكن للجميع استخدامها في هذا الخادم. اكتب :اسم: في الدردشة لإرسالها.",
    imagem: "صورة",
    enviadoPor: "رفعها",
    semEmoji: "لا توجد إيموجي بعد.",
    figurinhas: "ملصقات",
    enviarFigurinha: "رفع ملصق",
    nomeDaFigurinha: "اسم الملصق",
    exemploFigurinha: "مثال: عناق قطة صغيرة",
    figurinhaGrande: "الملصق يتجاوز {{limite}}.",
    deixaPraLa: "دع الأمر",
    sons: "لوحة الأصوات",
    enviarSom: "رفع صوت",
    nomeDoSom: "اسم الصوت",
    semSom: "لا توجد أصوات بعد.",
    somGrande: "الصوت يتجاوز {{limite}}.",
    emojiRelacionado: "إيموجي مرتبط",
    ouvir: "استماع",
    ouvirAssim: "استمع هكذا",
    volumeDe: "مستوى صوت {{nome}}",
    volumeDica: "ينطبق على الجميع في الخادم. ويظل بإمكان كل شخص خفض الأصوات لنفسه فقط، من لوحة المكالمة.",
    falhaEnvio: "تعذّر رفع الملف.",
    excluirTitulo: "حذف {{tipo}} \"{{nome}}\"؟",
    excluirDescricao: "يختفي من الخادم عند الجميع. الرسائل التي استخدمته تبقى كما هي.",
  },
  canal: {
    tipoLink: "رابط",
    tipoLinkDica: "يشير إلى عنوان خارجي ويُفتح في المتصفّح",
    endereco: "العنوان",
    enderecoDica: "الوجهة التي تقود إليها القناة. لا بدّ أن تبدأ بـ https://",
    visaoGeral: "نظرة عامة",
    nome: "اسم القناة",
    topico: "موضوع القناة",
    topicoDica: "عمّ يُتحدَّث هنا؟",
    modoLento: "كل شخص يرسل رسالة واحدة فقط في كل فترة. من يدير الرسائل أو القنوات يمرّ مباشرة.",
    visibilidade: "ظهور المحتوى",
    padrao: "الافتراضي",
    padraoDica: "محتوى القناة ظاهر دائمًا.",
    spoiler: "قناة حرق أحداث",
    spoilerDica: "علّم هذه القناة بأنها تحتوي على حرق للأحداث، لتبقى المفاجآت والمواضيع الثقيلة مخفية حتى يختار أحدهم رؤيتها.",
    idade: "قناة بقيد عمري",
    idadeDica: "من يدخل عليه أن يؤكد بلوغه لرؤية المحتوى.",
    bitrateDica: "تجاوز 64 كيلوبت/ث قد يزعج من لديه اتصال ضعيف.",
    qualidadeDeVideo: "جودة الفيديو",
    automatica: "تلقائية",
    limite: "حد المستخدمين — {{valor}}",
    pessoas: "{{quantos}} أشخاص",
    semLimite: "بلا حد",
    permissoesDescricao: "هنا تغيّر ما يسري في هذه القناة. وما يبقى على «الوراثة» يظل تابعًا للدور.",
    excluir: {
      titulo: "حذف القناة",
      historico: "كل سجل {{canal}} يذهب معها، عند الجميع.",
      digite: "اكتب {{canal}} للتأكيد",
    },
  },
  moderacao: {
    titulo: "عرض المشرف",
    semPermissao: "تحتاج إذن «الإشراف على الأعضاء» لترى هذا.",
    fecharEsc: "إغلاق (Esc)",
    atividade: "النشاط في الخادم",
    mensagens: "الرسائل",
    links: "الروابط",
    midia: "الوسائط",
    acoesNaAuditoria: "الإجراءات في السجل",
    moderacoesSofridas: "ما تعرّض له من إشراف",
    permissoes: "الأذونات ({{quantas}})",
    semPermissaoEspecial: "لا أذونات خاصة.",
    conta: "الحساب",
    entrouNoServidor: "انضم إلى الخادم",
    contaCriadaEm: "أُنشئ الحساب في",
    deCastigoAte: "مُسكت حتى",
    formaDeAdesao: "كيف انضم",
    mensagem: "رسالة",
    castigo: "إسكات",
    copiarId: "نسخ المعرّف",
    idCopiado: "نُسخ المعرّف.",
    adicionarCargo: "إضافة دور",
    semCargos: "لم يُنشأ أي دور",
    soEveryone: "‏@everyone فقط.",
    voltar: "رجوع",
    vazio: "لا شيء هنا.",
    cinquenta: "تُعرض أحدث 50.",
    irParaMensagem: "الانتقال إلى الرسالة",
    precisaSerAmigo: "يجب أن تكونا صديقين لتتحدثا.",
    expulsarDescricao: "يغادر الخادم فورًا، لكنه يستطيع العودة بدعوة.",
    banirDescricao: "يغادر الخادم ولا يعود، ولا حتى بدعوة، حتى يُرفع الحظر.",
    castigarTitulo: "إسكات {{nome}}؟",
    castigoDescricao: "طوال مدته، لا يكتب ولا يتكلم في أي قناة من قنوات الخادم.",
    aplicarCastigo: "تطبيق الإسكات",
    duracao: "المدة بالدقائق",
    informeDuracao: "حدّد المدة بالدقائق.",
  },
  abas: {
    pesquisar: "ابحث في الإعدادات",
    semResultado: "لا شيء بهذا الاسم هنا.",
    comunidade: "المجتمع",
    expressoes: "التعبيرات",
    pessoas: "الأشخاص",
    apps: "التطبيقات",
    moderacao: "الإشراف",
    banimentos: "المحظورون",
  },
};
