export const amizades = {
  ativosAgora: "Actifs maintenant",
  procurando: "On regarde qui est là…",
  tudoTranquilo: "Tout est calme pour l'instant…",
  tudoTranquiloDetalhe: "Quand vous ou un ami rejoindrez un appel, il apparaîtra ici — et vous pourrez vous joindre en un clic.",
  emVoz: "En vocal",
  voce: "Vous",
  soVoce: "Vous seul",
  pessoas: "{{quantas}} personnes",
  voltarParaChamada: "Revenir à l'appel",
  entrarNaChamada: "Rejoindre l'appel",
  abrirCanal: "Ouvrir {{canal}} dans {{servidor}}",
  mensagensDiretas: "Messages privés",
  encontreConversa: "Trouver une conversation",
  amigos: "Amis",
  conversas: "Conversations",
  semConversas: "Aucune conversation pour l'instant. Ajoutez un ami pour commencer.",
  semConversaComEsseNome: "Aucune conversation à ce nom.",
  abrirMenu: "Ouvrir les serveurs et les conversations",
  solicitacoes: "Demandes de message",
  pedidos: "Demandes",
  spam: "Spam",
  pedidosPendentes: "Demandes en attente",
  marcadosComoSpam: "Marquées comme spam",
  aceitar: "Accepter",
  ignorar: "Ignorer",
  marcarSpam: "Marquer comme spam",
  semPedidos: "Aucune demande en attente.",
  semPedidosDetalhe: "Les personnes qui ne sont pas vos amies mais partagent un serveur avec vous arrivent ici avant vos conversations.",
  semSpam: "Rien de marqué comme spam.",
  semSpamDetalhe: "Ce que le filtre anti-spam écarte, ou ce que vous marquez, reste dans cet onglet.",
  umServidorEmComum: "1 serveur en commun",
  servidoresEmComum: "{{quantos}} serveurs en commun",
  semServidoresEmComum: "Aucun serveur en commun",
};
