export const chamada = {
  conectando: "Connexion à l'appel…",
  naoEntrou: "Impossible de rejoindre l'appel",
  sair: "Quitter l'appel",
  sairDaVoz: "Quitter l'appel vocal",
  desconectar: "Se déconnecter",
  voltar: "Revenir à l'appel",
  voltarAosQuadros: "Revenir aux vignettes de l'appel",
  fecharChat: "Fermer le chat",
  carregandoPrevia: "Chargement de l'aperçu…",
  maisOpcoes: "Plus d'options",
  deVideo: "Appel vidéo",
  deVoz: "Appel vocal",
  alguem: "Quelqu'un",
  volume: {
    entrada: "Volume d'entrée",
    saida: "Volume de sortie",
    live: "Volume du direct",
    liveComPorcento: "Volume du direct ({{porcento}} %)",
    liveSemSom: "Direct sans son",
  },
  aparelhos: {
    entrada: "Périphérique d'entrée",
    saida: "Périphérique de sortie",
    camera: "Caméra",
    microfone: "Micro",
    saidaCurto: "Sortie",
    oDoSistema: "Celui du système",
    aDoSistema: "Celle du système",
    semEscolhaDeSaida: "Ce navigateur ne laisse pas choisir la sortie — c'est le système qui décide.",
    espelhar: "Refléter ma caméra",
    configEntrada: "Réglages d'entrée",
    configSaida: "Réglages de sortie",
    configCamera: "Réglages de la caméra",
    configAudioEVideo: "Réglages audio et vidéo",
  },
  tela: {
    compartilhar: "Partager l'écran",
    compartilharAcao: "Partager",
    cancelar: "Annuler",
    telas: "Écrans",
    janelas: "Fenêtres",
    somDoComputador: "Emporter le son de l'ordinateur",
    somDoSistema: "Emporter le son du système",
    configCompartilhamento: "Réglages du partage",
    mostrarSemVideo: "Afficher les personnes sans vidéo",
    semFontes: "Le système n'a renvoyé aucun écran ni fenêtre à partager.",
    pararDeCompartilhar: "Arrêter le partage",
    encerrarTransmissao: "Terminer la diffusion",
  },
  live: {
    etiqueta: "En direct",
    etiquetaMaiuscula: "EN DIRECT",
    assistir: "Regarder la diffusion",
    assistirPessoa: "Regarder {{nome}}",
    pararDeAssistir: "Arrêter de regarder",
  },
  membro: {
    mudarMeuApelido: "Changer mon surnom",
    meuMicrofone: "Mon micro",
    ouvirChamada: "Écouter l'appel",
    copiarMeuId: "Copier mon ID",
    idCopiado: "ID copié.",
    mensagem: "Message",
    silenciar: "Couper le son",
    alterarApelido: "Changer le surnom",
    cargos: "Rôles",
    semCargo: "Aucun rôle créé",
    moverPara: "Déplacer vers",
    silenciarNoServidor: "Couper la voix sur le serveur",
    desativarAudioNoServidor: "Couper l'audio sur le serveur",
    desconectar: "Déconnecter",
    apelidoTitulo: "Votre surnom sur ce serveur",
    apelidoDeAlguem: "Surnom de {{nome}}",
    apelidoCampo: "Surnom",
    apelidoDicaPropria: "Valable ici seulement. Laissez vide pour revenir à votre nom habituel.",
    apelidoDicaDeOutro: "Valable sur ce serveur seulement. Laissez vide pour revenir au nom d'origine.",
  },
  detalhes: {
    abrir: "Détails de la voix",
    titulo: "Détails de la Voix",
    conexao: "Connexion",
    pingMedio: "Ping moyen",
    ultimoPing: "Dernier ping",
    perda: "Perte de paquets envoyés",
    medindo: "Mesure en cours…",
    criptografado: "Chiffré jusqu'au serveur (DTLS-SRTP)",
    explicacao: "Au-dessus de 250 ms le retard s'entend et les gens commencent à se couper la parole. Une perte de paquets au-dessus de 10 % rend la voix robotique. Dans les deux cas le problème est presque toujours entre vous et internet : essayez un câble plutôt que le Wi-Fi, ou redémarrez la box.",
  },
  microfone: {
    bloqueado: "Micro bloqué — vous êtes seulement à l'écoute. Autorisez l'accès dans les permissions du navigateur.",
    bloqueadoNoMac: "macOS bloque le micro. Cochez",
    caminhoNoMac: "Réglages Système → Confidentialité et sécurité → Microphone",
    abrirAjustes: "Ouvrir les réglages",
    vaiReabrir: "macOS vous demandera de rouvrir l'application.",
    naoAbriu: "Impossible d'ouvrir le micro — vous êtes seulement à l'écoute. Vérifiez le périphérique dans Réglages → Voix et vidéo.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS n'a pas encore autorisé l'enregistrement de l'écran. Sans ça, le partage sort en noir.",
    marque: "Cochez",
    reabra: "dans Enregistrement de l'écran, puis rouvrez l'application.",
  },
  ruido: {
    titulo: "Suppression du bruit",
    explicacao: "Enlevez le bruit de fond de votre voix. Essayez de taper dans les mains ou de faire glisser le clavier en parlant — les personnes dans l'appel n'entendent que vous.",
    semSuporte: "Ce navigateur ne fait pas tourner la suppression avancée. Celle du navigateur reste active, et elle est plus faible.",
    aplicando: "Application à l'appel…",
    faleParaTestar: "Parlez pour tester",
    verdeQuandoPassa: "Vert quand votre voix passe.",
    teOuvindo: "On vous entend en ce moment.",
    feitoCom: "Fait avec",
    aquiNoAparelho: ", ici sur votre appareil",
    ajustes: "Réglages",
  },
  permissoes: {
    titulo: "Permissions macOS",
    detalhe: "macOS ne demande qu'une fois, et ensuite ça ne change que dans son propre panneau. Ici vous voyez ce qui s'applique et vous réglez ce qui manque.",
    concedida: "Accordée",
    negada: "Refusée",
    naoPedida: "Non demandée",
    permitir: "Autoriser",
    abrirAjustes: "Ouvrir les réglages",
    microfone: "Microphone",
    microfoneDetalhe: "Parler dans les appels et tester votre entrée.",
    camera: "Caméra",
    cameraDetalhe: "Activer la vidéo dans l'appel.",
    tela: "Enregistrement de l'écran",
    telaDetalhe: "Partager l'écran et les fenêtres.",
    monitoramento: "Écoute de l'entrée",
    monitoramentoDetalhe: "Utiliser le push-to-talk même avec Gravaê en arrière-plan.",
  },
  jaConectado: {
    titulo: "Vous êtes déjà dans cet appel",
    trazer: "Amener l'appel ici",
    deixar: "Laisser comme c'est",
    detalhe: "En l'amenant ici, l'autre bout quitte l'appel — votre compte reste à un seul endroit à la fois.",
  },
};
