export const configuracoes = {
  sair: "Se déconnecter",
  versoes: {
    copiar: "Cliquez pour copier",
    copiado: "Copié",
  },
  telas: {
    conta: "Mon compte",
    privacidade: "Confidentialité",
    conexoes: "Connexions",
    voz: "Audio",
    video: "Vidéo",
    avisos: "Notifications",
    aplicativos: "Applications",
    aparencia: "Apparence",
    batePapo: "Discussion",
    acessibilidade: "Accessibilité",
    idioma: "Langue",
    aplicativo: "Télécharger l'app",
    atalhos: "Raccourcis",
    desktop: "Application de bureau",
    avancado: "Avancé",
    servidor: "Serveur",
  },
  grupos: {
    conta: "Compte",
    app: "Paramètres de l'app",
    desenvolvedor: "Développeur",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Identifiants",
    dispositivos: "Appareils",
    usuariosBloqueados: "Utilisateurs bloqués",
    aplicativosAutorizados: "Applications autorisées",
    sessoes: "Sessions",
    amigosEDms: "Amis et messages privés",
    compartilhamentoDeAtividade: "Partage d'activité",
    visibilidadeDoPerfil: "Visibilité du profil",
    exportarDados: "Exporter les données",
    exclusaoDeDados: "Supprimer les données",
    tema: "Thème",
    corDeDestaque: "Couleur d'accentuation",
    interface: "Interface",
    listaDeCanais: "Liste des salons",
    zoomDoApp: "Niveau de zoom de l'app",
    escalaDaFonte: "Taille du texte du chat",
    modoStreamer: "Confidentialité en direct",
    movimento: "Mouvement",
    textoEmVoz: "Synthèse vocale",
    teclado: "Clavier",
    formatoDaHora: "Format de l'heure",
    idiomaDaInterface: "Langue de l'interface",
    dispositivosDeVoz: "Périphériques",
    testeDoMicrofone: "Test du micro",
    modoDeEntrada: "Mode d'entrée",
    sensibilidade: "Sensibilité d'entrée",
    qualidade: "Qualité",
    camera: "Caméra",
    transmissao: "Diffusion",
    exibicao: "Affichage",
    entrada: "Saisie",
    midia: "Médias",
    geral: "Général",
    preferenciaDeMencao: "Préférence de mention",
    sons: "Sons",
  },
};
