export const configuracoes = {
  efeitos: {
    titulo: "Effets du pointeur",
    detalhe: "Une traînée et des étincelles dessinées par-dessus l'application. Elles arrivent éteintes et se coupent seules si vous avez demandé moins d'animation.",
    rastro: "Traînée du curseur",
    rastroDetalhe: "Un trait qui suit le pointeur et s'efface derrière.",
    faisca: "Étincelle au clic",
    faiscaDetalhe: "De petits traits qui partent de l'endroit cliqué.",
    cor: "Couleur",
    espessura: "Épaisseur",
    comprimento: "Longueur",
    tamanho: "Taille",
    quantidade: "Nombre",
  },
  email: {
    verificarTitulo: "Confirmez votre e-mail",
    verificarDetalhe: "Certaines communautés ne laissent écrire que ceux qui ont confirmé. Un clic suffit.",
    enviar: "Envoyer le lien",
    enviado: "Regardez la boîte de réception. Le lien tient une journée.",
    falhou: "L'e-mail n'a pas pu être envoyé.",
    confirmado: "E-mail confirmé",
    confirmadoDetalhe: "C'est fait. Vous écrivez désormais dans toute communauté qui l'exige.",
    linkIncompleto: "Lien incomplet",
    linkIncompletoDetalhe: "Il manque le code dans l'adresse. Ouvrez le lien directement depuis l'e-mail.",
    confirmando: "Confirmation…",
    expirou: "Ce lien a déjà servi ou a dépassé sa validité.",
    irParaOApp: "Aller à l'application",
  },
  tema: {
    indisponivel: "Thème indisponible",
    indisponivelDetalhe: "La personne qui l'a publié l'a supprimé, ou le lien est faux.",
    indisponivelLinha: "Thème indisponible. La personne qui l'a publié l'a supprimé, ou le lien est faux.",
    importar: "Importer le thème",
    importarCurto: "Importer",
    importarDetalhe: "Cela remplace le thème que vous avez actuellement. Vous pourrez le modifier ensuite dans Réglages > Apparence > Studio de thèmes.",
    porAutor: "par {{autor}}",
    umaCorTrocada: "1 couleur remplacée",
    coresTrocadas: "{{quantas}} couleurs remplacées",
    avisoDeCss: "Ce thème apporte le CSS de son auteur, et le CSS touche à tous les recoins de l'écran. N'importez que depuis des gens en qui vous avez confiance.",
    soCores: "Ce thème ne change que les couleurs. Aucun CSS venu d'ailleurs.",
    aplicar: "Appliquer",
    previaSemMotor: "L'aperçu ne lance pas le moteur. Installez-le pour le voir.",
    motorAnimado: "{{motor}} animé",
  },
  sair: "Se déconnecter",
  versoes: {
    termos: "Conditions d'utilisation",
    privacidade: "Politique de confidentialité",
    copiar: "Cliquez pour copier",
    copiado: "Copié",
  },
  telas: {
    conta: "Mon compte",
    privacidade: "Confidentialité",
    conexoes: "Connexions",
    voz: "Audio",
    video: "Vidéo",
    avisos: "Notifications",
    aplicativos: "Applications",
    aparencia: "Apparence",
    batePapo: "Discussion",
    acessibilidade: "Accessibilité",
    idioma: "Langue",
    aplicativo: "Télécharger l'app",
    atalhos: "Raccourcis",
    desktop: "Application de bureau",
    avancado: "Avancé",
    servidor: "Serveur",
    comunicado: "Annonce du système",
    denuncias: "Signalements",
    publicacoes: "Déploiements",
  },
  grupos: {
    conta: "Compte",
    app: "Paramètres de l'app",
    desenvolvedor: "Développeur",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Identifiants",
    dispositivos: "Appareils",
    usuariosBloqueados: "Utilisateurs bloqués",
    aplicativosAutorizados: "Applications autorisées",
    sessoes: "Sessions",
    amigosEDms: "Amis et messages privés",
    compartilhamentoDeAtividade: "Partage d'activité",
    visibilidadeDoPerfil: "Visibilité du profil",
    exportarDados: "Exporter les données",
    exclusaoDeDados: "Supprimer les données",
    tema: "Thème",
    corDeDestaque: "Couleur d'accentuation",
    interface: "Interface",
    listaDeCanais: "Liste des salons",
    zoomDoApp: "Niveau de zoom de l'app",
    escalaDaFonte: "Taille du texte du chat",
    modoStreamer: "Confidentialité en direct",
    cursores: "Curseurs",
    movimento: "Mouvement",
    textoEmVoz: "Synthèse vocale",
    teclado: "Clavier",
    formatoDaHora: "Format de l'heure",
    idiomaDaInterface: "Langue de l'interface",
    dispositivosDeVoz: "Périphériques",
    testeDoMicrofone: "Test du micro",
    modoDeEntrada: "Mode d'entrée",
    sensibilidade: "Sensibilité d'entrée",
    qualidade: "Qualité",
    camera: "Caméra",
    transmissao: "Diffusion",
    exibicao: "Affichage",
    entrada: "Saisie",
    midia: "Médias",
    geral: "Général",
    preferenciaDeMencao: "Préférence de mention",
    sons: "Sons",
  },
};
