export const conversa = {
  lista: {
    carregando: "Chargement des messages…",
    carregandoMais: "Chargement…",
    verMais: "Faites défiler vers le haut pour en voir plus",
    semHistorico: "Historique indisponible",
    semHistoricoDetalhe: "Votre rôle n'a pas la permission de lire l'historique de #{{canal}}. Les nouveaux messages continuent d'apparaître tant que vous êtes ici.",
    boasVindas: "Bienvenue dans #{{canal}}",
    boasVindasDetalhe: "C'est le début du salon #{{canal}}.",
  },
  data: {
    hoje: "Aujourd'hui",
    ontem: "Hier",
    hojeAs: "aujourd'hui à {{hora}}",
    ontemAs: "hier à {{hora}}",
  },
  digitando: {
    um: "{{nome}} est en train d'écrire…",
    dois: "{{primeiro}} et {{segundo}} sont en train d'écrire…",
    varios: "{{quantidade}} personnes sont en train d'écrire…",
  },
  mensagem: {
    usou: "a utilisé",
    fixada: "épinglé",
    editado: "(modifié)",
    ignorada: "Message de quelqu'un que vous ignorez.",
    mostrar: "Afficher",
    escPara: "Échap pour",
    cancelar: "annuler",
    enterParaSalvar: "Entrée pour enregistrer",
    falhou: "Il n'a pas été envoyé. Réessayer",
    naoLidasDaqui: "Non lus à partir d'ici.",
    linkCopiado: "Lien copié.",
    idCopiado: "ID copié.",
    naoDeuParaCopiar: "Votre navigateur n'a pas autorisé la copie.",
    apagarTitulo: "Supprimer le message ?",
    apagarDescricao: "Il disparaît pour tout le salon. Impossible de le récupérer.",
    apagarAcao: "Supprimer",
    citacaoAnexo: "cliquez pour voir la pièce jointe",
    citacaoSumiu: "Le message d'origine n'est plus là.",
    reagirCom: "Réagir avec {{emoji}} — maintenez pour super réagir",
    segureParaSuper: "{{emoji}} — maintenez pour super réagir",
  },
  acoes: {
    reagir: "Réagir",
    responder: "Répondre",
    encaminhar: "Transférer",
    favoritar: "Mettre le message en favori",
    tirarDosFavoritos: "Retirer des favoris",
    marcarNaoLida: "Marquer comme non lu",
    copiarLink: "Copier le lien du message",
    copiarId: "Copier l'ID du message",
    fixar: "Épingler le message",
    desafixar: "Désépingler",
    editar: "Modifier",
    apagar: "Supprimer",
    mais: "Plus",
    adicionarReacao: "Ajouter une réaction",
    superReagirCom: "Super réagir avec {{emoji}}",
    fixarMensagem: "Épingler le message",
    desafixarMensagem: "Désépingler le message",
    editarMensagem: "Modifier le message",
    apagarMensagem: "Supprimer le message",
  },
  mencao: {
    cargo: "Mention de rôle",
    pessoa: "Mention",
    alguem: "quelqu'un",
    cargoSemNome: "rôle",
    here: "Notifie les personnes en ligne",
    everyone: "Notifie tout le serveur",
  },
  codigo: {
    copiar: "Copier",
    copiado: "Copié",
    copiarAria: "Copier le code",
    copiadoAria: "Code copié",
    recolher: "Réduire",
    expandir: "Développer",
    verInteiro: "Voir tout le fichier",
    maisOpcoes: "Plus d'options",
    baixar: "Télécharger",
    recolherLinhas: "Réduire ({{linhas}} lignes)",
    expandirLinhas: "Développer ({{linhas}} lignes)",
    mudarIdioma: "Changer de langage",
    procurarIdioma: "Rechercher un langage…",
    nenhumIdioma: "Aucun langage trouvé.",
    quebrarTexto: "Retour à la ligne",
  },
  caixa: {
    escrever: "Écrire dans #{{canal}}",
    escreverSemCanal: "Écrire un message",
    semPermissao: "Vous n'avez pas la permission d'envoyer des messages dans ce salon",
    solteParaAnexar: "Déposez pour joindre",
    longaTitulo: "Ton message est trop long…",
    longaDescricao: "Tu as atteint la limite de {{limite}} caractères. Tu peux l'envoyer en fichier.",
    enviarComoArquivo: "Envoyer en fichier",
    textoComoArquivo: "Envoyer le texte en fichier",
    arquivoGrandeTitulo: "Ce fichier est trop lourd",
    arquivoGrandeDescricao: "« {{arquivo}} » dépasse la limite de {{limite}} Mo par fichier.",
    respondendoPara: "En réponse à",
    vaiNotificar: "La personne sera notifiée",
    naoVaiNotificar: "La personne ne sera pas notifiée",
    ligado: "activé",
    desligado: "désactivé",
    pararDeResponder: "Arrêter de répondre",
    mais: "Plus",
    enviarArquivo: "Envoyer un fichier",
    criarEnquete: "Créer un sondage",
    expressoes: "Emoji, GIF et autocollants",
    enviar: "Envoyer",
    aguardandoEnvio: "En attente de l'envoi",
    modoLento: "Mode lent actif ({{tempo}})",
    modoLentoDica: "Le mode lent est réglé sur {{segundos}} s. Patientez avant d'envoyer un autre message.",
  },
  anexos: {
    enviando: "Envoi…",
    modificar: "Modifier {{arquivo}}",
    verPrevia: "Aperçu de {{arquivo}}",
    remover: "Retirer {{arquivo}}",
    ver: "Voir {{arquivo}}",
    mostrarSpoiler: "Afficher le spoiler : {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Modifier la pièce jointe",
    nomeDoArquivo: "Nom du fichier",
    descricao: "Description du texte alternatif",
    descricaoDica: "Décrivez ce média pour les lecteurs d'écran",
    marcarSpoiler: "Marquer comme spoiler",
    cancelar: "Annuler",
    salvar: "Enregistrer",
  },
  cartao: {
    tocador: "Lecteur",
    abrir: "Ouvrir {{destino}}",
    tocar: "Lire {{titulo}}",
    video: "vidéo",
    verImagem: "Voir l'image",
  },
  enquete: {
    titulo: "Sondage",
    encerrada: "Sondage clos",
    variasRespostas: "Sondage — plusieurs réponses",
    umVoto: "{{quantidade}} vote",
    votos: "{{quantidade}} votes",
    umVotoNoTotal: "{{quantidade}} vote au total",
    votosNoTotal: "{{quantidade}} votes au total",
    encerraEm: "se termine le {{quando}}",
    encerrarAgora: "Clore maintenant",
  },
  fixadas: {
    titulo: "Messages épinglés",
    vazio: "Ce salon n'a aucun message épinglé… pour l'instant.",
    desafixar: "Désépingler",
    anexo: "(pièce jointe)",
    enquete: "(sondage)",
    dicaRotulo: "BON À SAVOIR :",
    dica: "toute personne ayant la permission « Gérer les messages » peut épingler directement depuis le menu du message.",
  },
  encaminhar: {
    titulo: "Transférer le message",
    paraOnde: "Vers où ?",
    semTexto: "(message sans texte)",
    nenhumLugar: "Aucun endroit avec ce nom.",
    canais: "Salons",
    conversas: "Messages privés",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Rechercher sur Klipy",
    figurinha: "Autocollant",
    buscarFigurinha: "Trouvez l'autocollant parfait",
    buscarEmoji: "Trouvez l'émoji parfait",
    buscarReacao: "Trouvez la réaction parfaite",
    adicionarEmoji: "Ajouter un émoji",
    limparBusca: "Effacer la recherche",
  },
  busca: {
    fechar: "Fermer la recherche",
    procurando: "Recherche…",
    resultado: "{{quantos}} résultat",
    resultados: "{{quantos}} résultats",
    nadaCom: "Rien avec {{termo}} par ici.",
    soOsQuePodeLer: "La recherche ne regarde que les salons que vous pouvez lire.",
  },
  entrada: {
    titulo: "Boîte de réception",
    naoLidas: "Non lues",
    salvas: "Enregistrées",
    mencoes: "Mentions",
    fimTitulo: "Vous êtes arrivé au bout",
    fimDetalhe: "Il n'y a plus rien à lire. Quand un message arrive, il apparaît ici.",
    semSalvosTitulo: "Aucun élément enregistré",
    semSalvosDetalhe: "Maintenez Maj et cliquez sur le marque-page d'un message pour le garder et le lire plus tard.",
    tirarDosSalvos: "Retirer des enregistrés",
    semMencoesTitulo: "Aucune mention pour l'instant",
    semMencoesDetalhe: "Les mentions vous concernant apparaissent ici sur les 7 derniers jours.",
  },
  forum: {
    descricao: "Chaque sujet devient une conversation à part — pratique pour une question qui ne doit pas se perdre au milieu du chat.",
    novoAssunto: "Nouveau sujet",
    vazio: "Aucun sujet pour l'instant. Lancez le premier et la conversation reste rangée dès le départ.",
    titulo: "Titre",
    doQueSeTrata: "De quoi s'agit-il ?",
    primeiraMensagem: "Premier message",
    conteDoCaso: "Racontez",
  },
};
