export const perfil = {
  carregando: "Chargement…",
  editar: "Modifier le profil",
  mensagem: "Message",
  abrirConversa: "Ouvrir la conversation",
  verCompleto: "Voir le profil complet",
  convidarParaServidor: "Inviter sur le serveur",
  semServidores: "Vous n'avez aucun serveur",
  conviteEnviado: "Invitation envoyée à {{nome}}.",
  moderador: "Ouvrir en vue modérateur",
  mais: "Plus",
  ignorar: "Ignorer",
  deixarDeIgnorar: "Ne plus ignorer",
  copiarId: "Copier l'ID de l'utilisateur",
  idCopiado: "ID copié.",
  conexoes: "Connexions",
  membroDesde: "Membre depuis",
  sobre: "À propos",
  cargosTitulo: "Rôles",
  visaoGeral: "Vue d'ensemble",
  amigosEmComum: "Amis en commun ({{quantidade}})",
  servidoresEmComum: "Serveurs en commun ({{quantidade}})",
  amizade: {
    amigo: "Ami",
    pedidoEnviado: "Demande d'ami envoyée",
    respondaAbaixo: "Vous a envoyé une demande — répondez ci-dessous",
    adicionar: "Ajouter en ami",
    teMandouPedido: "Vous a envoyé une demande d'ami",
    aceitar: "Accepter",
    desfazer: "Retirer des amis",
    desfazerTitulo: "Retirer {{nome}} de vos amis ?",
    desfazerDescricao: "Vous n'êtes plus amis. La conversation privée reste dans l'historique, et vous pourrez l'ajouter à nouveau plus tard.",
    bloquear: "Bloquer",
    bloquearTitulo: "Bloquer {{nome}} ?",
    bloquearDescricao: "Vous n'êtes plus amis, la conversation privée n'accepte plus de messages et cette personne ne peut plus vous envoyer de demande d'ami.",
    linkCopiado: "Vous n'êtes pas amis — le lien a été copié pour que vous l'envoyiez.",
  },
  recado: {
    escrever: "Écrire à @{{usuario}}",
    enviar: "Envoyer",
    enviada: "Message envoyé",
    falhou: "Impossible d'envoyer. Essayez depuis la conversation.",
  },
  cartao: {
    trocarFaixa: "Changer la bannière de la carte",
    trocarFaixaCurto: "Changer la bannière",
    trocarFoto: "Changer la photo de profil",
    trocarFotoCurto: "Changer la photo",
    suaEtiqueta: "Votre étiquette",
    editarEtiqueta: "Cliquez pour modifier votre étiquette",
    conteAlgo: "Dites-nous quelque chose sur vous",
    adicionarStatus: "Ajouter un statut",
    adicionarDescricao: "Cliquez pour ajouter une description",
    cargo: "Rôle",
    cargos: "Rôles",
    cargosCom: "Rôles — {{quantidade}}",
    tirarCargo: "Retirer le rôle {{cargo}}",
  },
  cargos: {
    adicionar: "Ajouter un rôle",
    procurar: "Rechercher un rôle",
  },
  etiqueta: {
    escolher: "Choisir l'étiquette de serveur",
    nenhuma: "Aucune étiquette de serveur",
    semEtiqueta: "Aucun de vos serveurs n'a d'étiquette",
  },
  emblemas: {
    doServidor: "Badges de ce serveur",
    limite: "Vous pouvez porter jusqu'à {{quantidade}} badges.",
  },
  nota: {
    vazia: "Cliquez pour noter quelque chose",
    rotulo: "Note (vous seul la voyez)",
    adicionar: "Ajouter une note (visible par toi seul)",
  },
  status: {
    titulo: "Statut",
    definir: "Définir votre statut",
    escolherEmoji: "Choisir un emoji",
    tirarEmoji: "Retirer l'emoji",
    oQuePensa: "À quoi pensez-vous ?",
    limparAgora: "Effacer le statut maintenant",
    naoLimpar: "Ne pas effacer",
    limpar30m: "Effacer dans 30 minutes",
    limpar1h: "Effacer dans 1 heure",
    limpar4h: "Effacer dans 4 heures",
    limparHoje: "Effacer aujourd'hui",
    limparAmanha: "Effacer demain",
    comHora: "{{prazo}} à {{hora}}",
  },
  presenca: {
    disponivel: "Disponible",
    ausente: "Absent",
    naoPerturbar: "Ne pas déranger",
    naoPerturbarDetalhe: "Vous ne recevez pas d'alerte pour les nouveaux messages",
    invisivel: "Invisible",
    invisivelDetalhe: "Vous apparaissez hors ligne pour les autres",
  },
  menu: {
    mudarDeConta: "Changer de compte",
    gerenciarContas: "Gérer les comptes",
  },
  editor: {
    decoracao: "Changer la décoration de l'avatar",
    naoSalvo: "N'oubliez pas d'enregistrer vos modifications !",
    principal: "Profil principal",
  },
};
