export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Paramètres du serveur",
  auditoria: {
    todasAsAcoes: "Toutes les actions",
    todosOsUsuarios: "Tous les utilisateurs",
    filtroMembros: "Membres",
    filtroCanais: "Salons",
    filtroEmojis: "Émojis",
    filtroServidor: "Serveur",
    titulo: "Journal d'audit",
    porUsuario: "Filtrer par utilisateur",
    porAcao: "Filtrer par action",
    vazio: "Rien d'enregistré pour l'instant avec ce filtre.",
    motivo: "Motif :",
  },
  banimentos: {
    titulo: "Liste des bannis du serveur",
    descricao: "Ceux qui sont ici ne reviennent pas, même avec une nouvelle invitation. Débannir rend l'accès immédiatement.",
    procurar: "Rechercher un banni par nom d'utilisateur",
    vazioTitulo: "Aucun banni",
    vazio: "Vous n'avez encore banni personne… mais si un jour il le faut, n'hésitez pas.",
    desbanir: "Débannir",
  },
  excluir: {
    tudoVai: "Tous les salons, messages et invitations de {{servidor}} seront supprimés pour les {{membros}} membres. Personne ne pourra les récupérer ensuite.",
    digite: "Tapez {{servidor}} pour confirmer",
    titulo: "Supprimer le serveur",
    aviso: "Ceci est irréversible.",
  },
  emblemas: {
    apagarDescricao: "Il est retiré à qui le porte. C'est irréversible.",
    titulo: "Badges",
    vazio: "Aucun badge pour l'instant.",
    novo: "Nouveau badge",
  },
  convites: {
    revogarTitulo: "Révoquer l'invitation ?",
    revogarAcao: "Révoquer",
    revogarDescricao: "Le lien {{codigo}} cesse de fonctionner immédiatement. Qui est déjà entré par lui reste sur le serveur.",
    titulo: "Invitations",
    descricao: "Tous les liens d'invitation actifs de ce serveur.",
    vazio: "Aucune invitation créée pour l'instant.",
    revogar: "Révoquer l'invitation",
  },
  integracoes: {
    opcionais: "username et avatar_url sont facultatifs et valent par message. La limite est de 5 messages toutes les 5 secondes.",
    apagarDescricao: "L'URL cesse de fonctionner immédiatement. Les messages déjà envoyés restent dans le salon.",
    titulo: "Intégrations",
    descricao: "Un webhook est une adresse qui publie dans un salon sans avoir besoin de compte. Pratique pour annoncer qu'un build est passé, qu'un ticket vient d'être ouvert, ou ce que vous voulez envoyer depuis un script.",
    novo: "Nouveau webhook",
    vazio: "Aucun webhook pour l'instant. Créez-en un et collez l'URL là où vous voulez que le message parte.",
    canal: "Salon",
    apagar: "Supprimer le webhook",
    comoUsar: "Comment s'en servir",
    comoUsarTexto: "Envoyez un POST en JSON :",
  },
  explorar: {
    titulo: "Explorer",
  },
  engajamento: {
    semCanal: "Aucun salon système",
    titulo: "Animation",
    descricao: "Ce que le serveur fait tout seul pour ne pas paraître vide quand quelqu'un de nouveau arrive.",
    sistema: "Messages système",
    boasVindas: "Envoyer un message de bienvenue quand quelqu'un arrive",
    sorteio: "Sans texte à vous en dessous, la phrase est tirée au sort — toujours la même, ça lasse vite.",
    canalDoSistema: "Salon des messages système",
    mensagem: "Message de bienvenue",
    deixeVazio: "Laissez vide pour tirer au sort parmi les phrases toutes prêtes",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Des filtres qui modèrent tout seuls, avant même que le message existe. Ceux qui administrent le serveur ne sont jamais filtrés — et les rôles exemptés passent directement.",
    palavras: {
      titulo: "Bloquer des mots personnalisés",
      descricao: "Votre liste de mots que personne ne peut écrire.",
    },
    mencoes: {
      titulo: "Bloquer le spam de mentions",
      descricao: "Bloque un message qui contient trop de mentions d'un coup.",
    },
    links: {
      titulo: "Bloquer les liens",
      descricao: "Retient toute adresse collée dans le chat.",
    },
    definir: "Configurer",
    nomeDaRegra: "Nom de la règle",
    bloqueadas: "Mots bloqués",
    digiteEnter: "Tapez et appuyez sur Entrée",
    comparacao: "La comparaison ignore les majuscules, les accents et la ponctuation — et ne prend pas un mot à l'intérieur d'un autre (« con » ne bloque pas « concert »).",
    aPartirDe: "Bloquer à partir de combien de mentions",
    oQueFazer: "Que faire",
    canalDoAlerta: "Salon de l'alerte",
    escolhaCanal: "Choisissez un salon",
    castigo: "Exclusion temporaire (minutes)",
    isentos: "Rôles exemptés",
    semCargos: "Aucun rôle créé pour l'instant.",
    salvarRegra: "Enregistrer la règle",
    apagar: "Supprimer la règle",
    excluirTitulo: "Supprimer cette règle AutoMod ?",
    excluirDescricao: "Le serveur cesse de filtrer avec elle immédiatement. Vous pouvez la recréer, mais la configuration actuelle est perdue.",
    excluirAcao: "Supprimer la règle",
  },
  cargos: {
    titulo: "Rôles",
    descricao: "Les rôles donnent un nom, une couleur et des pouvoirs. Qui est plus haut dans la liste commande à ceux d'en dessous — et personne ne touche à un rôle égal ou supérieur au sien.",
    criar: "Créer un rôle",
    vazio: "Aucun rôle pour l'instant.",
    abaExibicao: "Affichage",
    abaPermissoes: "Permissions",
    abaMembros: "Membres — {{quantos}}",
    everyone: "Vaut pour tout le monde sur le serveur. C'est la base sur laquelle les autres rôles s'ajoutent.",
    nomeDoCargo: "Nom du rôle",
    cor: "Couleur du rôle",
    corDica: "Colore le nom de qui a le rôle dans la liste des membres et dans le chat.",
    semCor: "Sans couleur",
    corPersonalizada: "Couleur personnalisée",
    estilo: "Style du nom",
    segundaCor: "Deuxième couleur",
    segundaCorDica: "Sans elle, le dégradé retombe sur une couleur unie — il ne disparaît pas.",
    limparSegundaCor: "Effacer la deuxième couleur",
    icone: "Icône",
    iconeDica: "Apparaît à côté du rôle sur la carte de profil de qui l'a.",
    exibirSeparado: "Afficher séparément des autres membres",
    exibirSeparadoDica: "Le rôle obtient sa propre section dans la liste des membres.",
    permitirMencionar: "Autoriser à mentionner ce rôle",
    permitirMencionarDica: "N'importe qui pourra notifier tous ceux qui ont le rôle.",
    semPoderDeConceder: "{{descricao}} (vous n'avez pas cette permission pour l'accorder)",
    adicionar: "Ajouter quelqu'un à ce rôle",
    tirar: "Retirer le rôle",
    semNinguem: "Personne n'a encore ce rôle.",
    apagar: "Supprimer le rôle",
    excluirTitulo: "Supprimer le rôle « {{nome}} » ?",
    excluirDescricao: "Qui a ce rôle perd tout ce qu'il donnait. C'est irréversible.",
    excluirAcao: "Supprimer le rôle",
  },
  membros: {
    procurar: "Rechercher par nom ou identifiant",
    membroDesde: "Membre depuis",
    vazio: "Personne trouvé.",
    acoesPara: "Actions pour {{nome}}",
    deCastigo: "d'exclusion",
    tirarCastigo: "Lever l'exclusion",
    castigo5min: "5 minutes",
    castigo1h: "1 heure",
    castigo1d: "1 jour",
    castigo1s: "1 semaine",
    expulsar: "Expulser",
    expulsarTitulo: "Expulser {{nome}} ?",
    expulsarDescricao: "quitte {{servidor}} immédiatement. Il peut revenir avec une invitation — expulser n'empêche pas le retour.",
    banir: "Bannir",
    banirTitulo: "Bannir {{nome}} ?",
    banirDescricao: "quitte {{servidor}} et ne peut pas revenir, même avec une invitation, tant qu'il n'est pas débanni.",
    motivo: "Motif (facultatif)",
    motivoDica: "Consigné dans le journal d'audit",
  },
  perfil: {
    titulo: "Profil du serveur",
    descricao: "C'est ainsi que votre serveur apparaît dans la liste et dans les liens d'invitation.",
    icone: "Icône",
    faixa: "Bannière du haut",
    nomeDoServidor: "Nom du serveur",
    campoDescricao: "Description",
    doQueE: "De quoi parle ce serveur ?",
    comprimido: "Compressé avant l'envoi : {{economia}}",
  },
  etiqueta: {
    titulo: "Étiquette du serveur",
    descricao: "Une étiquette de 4 lettres maximum qui apparaît à côté du nom de chaque membre — dans le chat et dans la liste des personnes. Ici c'est gratuit : sans boost, sans niveau.",
    escolhaNome: "Choisissez un nom",
    limite: "4 caractères maximum, lettres et chiffres.",
    escolhaInsignia: "Choisissez un insigne",
    voce: "Vous",
    fala1: "quelqu'un pour jouer ?",
    fala2: "regarde un peu mon étiquette !",
    fala3: "ouah, comment t'as eu ça",
  },
  expressoes: {
    comoUsar: "Ajoutez jusqu'à {{limite}} émojis que tout le monde peut utiliser sur ce serveur. Tapez :nom: dans le chat pour l'envoyer.",
    imagem: "Image",
    enviadoPor: "Envoyé par",
    semEmoji: "Aucun émoji pour l'instant.",
    figurinhas: "Autocollants",
    enviarFigurinha: "Envoyer un autocollant",
    nomeDaFigurinha: "Nom de l'autocollant",
    exemploFigurinha: "Ex. : câlin de chaton",
    figurinhaGrande: "L'autocollant dépasse {{limite}}.",
    deixaPraLa: "Laisse tomber",
    sons: "Panneau de sons",
    enviarSom: "Envoyer un son",
    nomeDoSom: "Nom du son",
    semSom: "Aucun son pour l'instant.",
    somGrande: "Le son dépasse {{limite}}.",
    emojiRelacionado: "Émoji associé",
    ouvir: "Écouter",
    ouvirAssim: "Écouter comme ça",
    volumeDe: "Volume de {{nome}}",
    volumeDica: "Vaut pour tout le monde sur le serveur. Chacun peut quand même baisser les sons rien que pour soi, dans le panneau de l'appel.",
    falhaEnvio: "Impossible d'envoyer le fichier.",
    excluirTitulo: "Supprimer {{tipo}} « {{nome}} » ?",
    excluirDescricao: "Il disparaît du serveur pour tout le monde. Les messages qui l'ont déjà utilisé restent tels quels.",
  },
  canal: {
    visaoGeral: "Vue d'ensemble",
    nome: "Nom du salon",
    topico: "Sujet du salon",
    topicoDica: "De quoi parle-t-on ici ?",
    modoLento: "Chaque personne n'envoie qu'un message par intervalle. Qui gère les messages ou les salons passe directement.",
    visibilidade: "Visibilité du contenu",
    padrao: "Par défaut",
    padraoDica: "Le contenu du salon est toujours visible.",
    spoiler: "Salon à spoilers",
    spoilerDica: "Marquez ce salon comme contenant des spoilers, pour que les révélations et les sujets lourds restent cachés jusqu'à ce que quelqu'un choisisse de les voir.",
    idade: "Salon réservé aux adultes",
    idadeDica: "Qui entre doit confirmer être majeur pour voir le contenu.",
    bitrateDica: "Dépasser 64 kbps peut gêner ceux qui ont une mauvaise connexion.",
    qualidadeDeVideo: "Qualité de la vidéo",
    automatica: "Automatique",
    limite: "Limite d'utilisateurs — {{valor}}",
    pessoas: "{{quantos}} personnes",
    semLimite: "sans limite",
    permissoesDescricao: "Ici vous changez ce qui vaut dans ce salon. Ce qui reste sur « hériter » continue de suivre le rôle.",
    excluir: {
      titulo: "Supprimer le salon",
      historico: "Tout l'historique de {{canal}} part avec lui, pour tout le monde.",
      digite: "Tapez {{canal}} pour confirmer",
    },
  },
  moderacao: {
    titulo: "Vue de modérateur",
    semPermissao: "Il vous faut la permission « Modérer les membres » pour voir ceci.",
    fecharEsc: "Fermer (Échap)",
    atividade: "Activité sur le serveur",
    mensagens: "Messages",
    links: "Liens",
    midia: "Médias",
    acoesNaAuditoria: "Actions dans le journal d'audit",
    moderacoesSofridas: "Modérations subies",
    permissoes: "Permissions ({{quantas}})",
    semPermissaoEspecial: "Aucune permission particulière.",
    conta: "Compte",
    entrouNoServidor: "A rejoint le serveur",
    contaCriadaEm: "Compte créé le",
    deCastigoAte: "Exclu jusqu'au",
    formaDeAdesao: "Comment il est arrivé",
    mensagem: "Message",
    castigo: "Exclusion temporaire",
    copiarId: "Copier l'ID",
    idCopiado: "ID copié.",
    adicionarCargo: "Ajouter un rôle",
    semCargos: "Aucun rôle créé",
    soEveryone: "Seulement @everyone.",
    voltar: "Retour",
    vazio: "Rien par ici.",
    cinquenta: "Affichage des 50 plus récents.",
    irParaMensagem: "Aller au message",
    precisaSerAmigo: "Vous devez être amis pour discuter.",
    expulsarDescricao: "Quitte le serveur immédiatement, mais peut revenir avec une invitation.",
    banirDescricao: "Quitte le serveur et ne peut pas revenir, même avec une invitation, tant qu'il n'est pas débanni.",
    castigarTitulo: "Exclure {{nome}} temporairement ?",
    castigoDescricao: "Tant que ça dure, il n'écrit ni ne parle dans aucun salon du serveur.",
    aplicarCastigo: "Appliquer l'exclusion",
    duracao: "Durée en minutes",
    informeDuracao: "Indiquez la durée en minutes.",
  },
  abas: {
    expressoes: "Expressions",
    pessoas: "Personnes",
    apps: "Applis",
    moderacao: "Modération",
    banimentos: "Bannis",
  },
};
