export const amizades = {
  ativosAgora: "Сейчас активны",
  procurando: "Смотрим, кто рядом…",
  tudoTranquilo: "Пока тихо…",
  tudoTranquiloDetalhe: "Когда вы или друг зайдёте в звонок, он появится здесь — и вы присоединитесь одним щелчком.",
  emVoz: "В голосовом",
  voce: "Вы",
  soVoce: "Только вы",
  pessoas: "{{quantas}} человек",
  voltarParaChamada: "Вернуться в звонок",
  entrarNaChamada: "Присоединиться",
  abrirCanal: "Открыть {{canal}} на {{servidor}}",
  mensagensDiretas: "Личные сообщения",
  encontreConversa: "Найти беседу",
  amigos: "Друзья",
  conversas: "Беседы",
  semConversas: "Бесед пока нет. Добавьте друга, чтобы начать.",
  semConversaComEsseNome: "Беседы с таким названием нет.",
  abrirMenu: "Открыть серверы и беседы",
  solicitacoes: "Запросы на переписку",
  pedidos: "Запросы",
  spam: "Спам",
  pedidosPendentes: "Ожидающие запросы",
  marcadosComoSpam: "Помечены как спам",
  aceitar: "Принять",
  ignorar: "Игнорировать",
  marcarSpam: "Пометить как спам",
  semPedidos: "Нет ожидающих запросов.",
  semPedidosDetalhe: "Тот, кто вам не друг, но состоит с вами на одном сервере, попадает сюда, не доходя до ваших бесед.",
  semSpam: "Ничего не помечено как спам.",
  semSpamDetalhe: "То, что отсеет фильтр спама, или то, что вы пометите сами, останется на этой вкладке.",
  umServidorEmComum: "1 общий сервер",
  servidoresEmComum: "Общих серверов: {{quantos}}",
  semServidoresEmComum: "Общих серверов нет",
};
