export const chamada = {
  conectando: "Подключение к звонку…",
  naoEntrou: "Не удалось войти в звонок",
  sair: "Выйти из звонка",
  sairDaVoz: "Выйти из голосового звонка",
  desconectar: "Отключиться",
  voltar: "Вернуться к звонку",
  voltarAosQuadros: "Вернуться к плиткам звонка",
  fecharChat: "Закрыть чат",
  mostrarChat: "Показать чат",
  convidar: "Пригласить в звонок",
  carregandoPrevia: "Загрузка превью…",
  maisOpcoes: "Ещё",
  deVideo: "Видеозвонок",
  deVoz: "Голосовой звонок",
  alguem: "Кто-то",
  volume: {
    entrada: "Громкость входа",
    saida: "Громкость выхода",
    live: "Громкость трансляции",
    liveComPorcento: "Громкость трансляции ({{porcento}}%)",
    liveSemSom: "Трансляция без звука",
  },
  aparelhos: {
    entrada: "Устройство входа",
    saida: "Устройство выхода",
    camera: "Камера",
    microfone: "Микрофон",
    saidaCurto: "Выход",
    oDoSistema: "Системное",
    aDoSistema: "Системная",
    semEscolhaDeSaida: "Этот браузер не даёт выбрать выход — решает система.",
    espelhar: "Отразить мою камеру",
    configEntrada: "Настройки входа",
    configSaida: "Настройки выхода",
    configCamera: "Настройки камеры",
    configAudioEVideo: "Настройки звука и видео",
  },
  tela: {
    compartilhar: "Показать экран",
    compartilharAcao: "Показать",
    cancelar: "Отмена",
    telas: "Экраны",
    janelas: "Окна",
    somDoComputador: "Взять звук компьютера",
    somDoSistema: "Взять звук системы",
    configCompartilhamento: "Настройки демонстрации",
    mostrarSemVideo: "Показывать тех, кто без видео",
    semFontes: "Система не вернула ни одного экрана или окна для показа.",
    pararDeCompartilhar: "Прекратить показ",
    encerrarTransmissao: "Завершить трансляцию",
  },
  live: {
    etiqueta: "В эфире",
    etiquetaMaiuscula: "В ЭФИРЕ",
    assistir: "Смотреть трансляцию",
    assistirPessoa: "Смотреть {{nome}}",
    pararDeAssistir: "Перестать смотреть",
  },
  membro: {
    mudarMeuApelido: "Сменить мой псевдоним",
    meuMicrofone: "Мой микрофон",
    ouvirChamada: "Слушать звонок",
    copiarMeuId: "Копировать мой ID",
    idCopiado: "ID скопирован.",
    mensagem: "Сообщение",
    silenciar: "Заглушить",
    alterarApelido: "Сменить псевдоним",
    cargos: "Роли",
    semCargo: "Роли не созданы",
    moverPara: "Переместить в",
    silenciarNoServidor: "Заглушить голос на сервере",
    desativarAudioNoServidor: "Отключить звук на сервере",
    desconectar: "Отключить",
    apelidoTitulo: "Ваш псевдоним на этом сервере",
    apelidoDeAlguem: "Псевдоним {{nome}}",
    apelidoCampo: "Псевдоним",
    apelidoDicaPropria: "Действует только здесь. Пустое поле вернёт ваше обычное имя.",
    apelidoDicaDeOutro: "Действует только на этом сервере. Оставьте пустым, чтобы вернуть исходное имя.",
  },
  detalhes: {
    abrir: "Детали голоса",
    titulo: "Детали Голоса",
    conexao: "Соединение",
    pingMedio: "Средний пинг",
    ultimoPing: "Последний пинг",
    perda: "Потеря отправленных пакетов",
    medindo: "Измеряем…",
    criptografado: "Зашифровано до сервера (DTLS-SRTP)",
    explicacao: "Выше 250 мс задержку слышно в разговоре — люди начинают перебивать друг друга. Потеря пакетов выше 10% делает голос роботизированным. В обоих случаях проблема почти всегда между вами и интернетом: попробуйте кабель вместо Wi-Fi или перезагрузите роутер.",
  },
  microfone: {
    bloqueado: "Микрофон заблокирован — вы только слушаете. Разрешите доступ в правах браузера.",
    bloqueadoNoMac: "macOS блокирует микрофон. Отметьте",
    caminhoNoMac: "Настройки системы → Конфиденциальность и безопасность → Микрофон",
    abrirAjustes: "Открыть настройки",
    vaiReabrir: "macOS попросит перезапустить приложение.",
    naoAbriu: "Не удалось открыть микрофон — вы только слушаете. Проверьте устройство в Настройки → Голос и видео.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS ещё не разрешил запись экрана. Без этого демонстрация выходит чёрной.",
    marque: "Отметьте",
    reabra: "в разделе «Запись экрана» и перезапустите приложение.",
    jaMarcado: "Если галочка уже стоит, разрешение устарело после последнего обновления: снимите её, поставьте снова и перезапустите приложение.",
  },
  ruido: {
    titulo: "Подавление шума",
    explicacao: "Уберите фоновый шум из своего голоса. Похлопайте или подвиньте клавиатуру, пока говорите — в звонке слышат только вас.",
    semSuporte: "Этот браузер не запускает продвинутое подавление. Остаётся встроенное в браузер, оно слабее.",
    aplicando: "Применяем к звонку…",
    faleParaTestar: "Говорите, чтобы проверить",
    verdeQuandoPassa: "Зелёный, когда голос проходит.",
    teOuvindo: "Вас слышат прямо сейчас.",
    feitoCom: "Сделано на",
    aquiNoAparelho: ", прямо на вашем устройстве",
    ajustes: "Настройки",
  },
  permissoes: {
    titulo: "Разрешения macOS",
    detalhe: "macOS спрашивает один раз, дальше это меняется только в его панели. Здесь видно, что действует, и можно решить, чего не хватает.",
    concedida: "Выдано",
    negada: "Отклонено",
    naoPedida: "Не запрошено",
    permitir: "Разрешить",
    abrirAjustes: "Открыть настройки",
    microfone: "Микрофон",
    microfoneDetalhe: "Говорить в звонках и проверять вход.",
    camera: "Камера",
    cameraDetalhe: "Включать видео в звонке.",
    tela: "Запись экрана",
    telaDetalhe: "Показывать экран и окна.",
    monitoramento: "Мониторинг входа",
    monitoramentoDetalhe: "Использовать push-to-talk, даже когда Gravaê в фоне.",
  },
  jaConectado: {
    titulo: "Вы уже в этом звонке",
    trazer: "Перенести звонок сюда",
    deixar: "Оставить как есть",
    detalhe: "При переносе сюда другая сторона выходит из звонка — ваш аккаунт находится в одном месте за раз.",
  },
};
