export const comum = {
  voltar: "Назад",
  agoraNao: "Не сейчас",
  erro: {
    tentarDeNovo: "Попробовать снова",
    recarregar: "Перезагрузить",
    copiarDetalhes: "Скопировать подробности",
    parteQuebrou: "Эта часть экрана сломалась.",
    titulo: "Gravaê споткнулся.",
    detalhe: "Что-то сломалось по дороге, и экран не смог отрисоваться. Ваша переписка не потерялась — всё лежит на сервере.",
  },
  conexao: {
    voltou: "Снова на связи",
    reconectando: "Переподключаюсь",
    tentativaSufixo: " · попытка {{numero}}",
    aSalvo: "Переписка в сохранности на сервере. Всё вернётся само, как только появится связь.",
  },
  avisoDoNavegador: {
    titulo: "Хотите получать уведомления о сообщениях?",
    detalhe: "Когда Gravaê за другим окном, он вас позовёт.",
  },
  atualizacao: {
    titulo: "Обновление",
    semAuto: "Эта версия приложения не умеет обновляться сама. Скачайте ниже свежий установщик и поставьте его поверх.",
    versaoAtual: "У вас версия {{versao}}.",
    instalando: "Устанавливается версия {{versao}}…",
    prontaVersao: "Версия {{versao}} готова к установке",
    baixandoVersao: "Загружается версия {{versao}}…",
    baixandoComProgresso: "Загружается версия {{versao}}… {{porcento}} %",
    saiuVersao: "Вышла версия {{versao}}",
    saiuVersaoClique: "Вышла версия {{versao}} — нажмите, чтобы скачать",
    instalarVersaoEReiniciar: "Установить версию {{versao}} и перезапустить",
    erroTenteDeNovo: "{{erro}} Нажмите, чтобы попробовать снова.",
    procurando: "Ищу…",
    emDia: "У вас всё свежее",
    vaiFechar: "Приложение закроется через мгновение.",
    comoInstala: "Приложение закрывается, меняет версию и открывается само. Если вы в звонке, то выйдете из него.",
    semServidor: "Не удалось связаться с сервером версий.",
    procuraSozinho: "Приложение проверяет само при запуске и каждые шесть часов.",
    instalandoReticencias: "Устанавливаю…",
    instalandoCurto: "Устанавливаю",
    baixandoCurto: "Загружаю",
    tentarDeNovo: "Попробовать снова",
    reiniciarAgora: "Перезапустить сейчас",
    instalarEReiniciar: "Установить и перезапустить",
    baixar: "Скачать",
    procurar: "Проверить",
    baixarApp: "Скачать приложение",
    ariaBotao: "Обновление приложения",
  },
  janela: {
    ajustarAltura: "Настроить высоту",
    redimensionar: "Изменить размер окна",
    ajustarLargura: "Настроить ширину",
  },
  dica: {
    rotulo: "Совет:",
    pularConfirmacao: "удерживайте Shift при щелчке, чтобы пропустить это подтверждение.",
  },
  cor: {
    pescar: "Взять цвет с экрана",
    hex: "Шестнадцатеричное значение",
  },
  imagem: {
    titulo: "Выберите изображение",
    enviar: "Отправить изображение",
    escolherGif: "Выбрать GIF",
    buscarGif: "Поиск GIF",
  },
  fonte: {
    rotulo: "Шрифт сообщения",
    padrao: "По умолчанию",
    comNome: "Шрифт сообщения — {{fonte}}",
  },
  recorte: {
    titulo: "Обрезать значок",
    detalhe: "Перетащите, чтобы выбрать нужную часть, и приблизьте ползунком. Значок везде в приложении круглый.",
    voltarAoComeco: "Вернуться к началу",
    usar: "Использовать эту обрезку",
  },
  mais: "Ещё",
  carregando: "Загрузка…",
  salvar: "Сохранить",
  salvando: "Сохранение…",
  descartar: "Отменить",
  redefinir: "Сбросить",
  naoSalvo: "У вас есть несохранённые изменения.",
  fechar: "Закрыть",
  criar: "Создать",
  nome: "Название",
  emoji: "Эмодзи",
  previa: "Предпросмотр",
  cancelar: "Отмена",
  enviar: "Отправить",
  apagar: "Удалить",
  excluir: "Удалить",
  remover: "Убрать",
  trocar: "Заменить",
};
