export const comum = {
  carregando: "Загрузка…",
  salvar: "Сохранить",
  salvando: "Сохранение…",
  descartar: "Отменить",
  redefinir: "Сбросить",
  naoSalvo: "У вас есть несохранённые изменения.",
  fechar: "Закрыть",
  criar: "Создать",
  nome: "Название",
  emoji: "Эмодзи",
  previa: "Предпросмотр",
  cancelar: "Отмена",
  enviar: "Отправить",
  apagar: "Удалить",
  excluir: "Удалить",
  remover: "Убрать",
  trocar: "Заменить",
};
