export const configuracoes = {
  efeitos: {
    titulo: "Эффекты указателя",
    detalhe: "След и искры поверх приложения. Приходят выключенными и гаснут сами, если вы просили меньше движения.",
    rastro: "След курсора",
    rastroDetalhe: "Линия, что идёт за указателем и тает позади.",
    faisca: "Искры при щелчке",
    faiscaDetalhe: "Короткие чёрточки, что разлетаются от места щелчка.",
    cor: "Цвет",
    espessura: "Толщина",
    comprimento: "Длина",
    tamanho: "Размер",
    quantidade: "Количество",
  },
  email: {
    verificarTitulo: "Подтвердите свою почту",
    verificarDetalhe: "Некоторые сообщества пускают писать только подтверждённых. Это один щелчок.",
    enviar: "Отправить ссылку",
    enviado: "Загляните в почту. Ссылка живёт сутки.",
    falhou: "Письмо отправить не удалось.",
    confirmado: "Почта подтверждена",
    confirmadoDetalhe: "Готово. Теперь вы пишете в любом сообществе, где это требуют.",
    linkIncompleto: "Ссылка неполная",
    linkIncompletoDetalhe: "В адресе не хватает кода. Откройте ссылку прямо из письма.",
    confirmando: "Подтверждаем…",
    expirou: "Эта ссылка уже использована или просрочена.",
    irParaOApp: "В приложение",
  },
  tema: {
    indisponivel: "Тема недоступна",
    indisponivelDetalhe: "Тот, кто её опубликовал, удалил её, или ссылка неверная.",
    indisponivelLinha: "Тема недоступна. Тот, кто её опубликовал, удалил её, или ссылка неверная.",
    importar: "Импортировать тему",
    importarCurto: "Импортировать",
    importarDetalhe: "Это заменит вашу нынешнюю тему. Отредактировать её можно позже: Настройки > Внешний вид > Студия тем.",
    porAutor: "автор: {{autor}}",
    umaCorTrocada: "заменён 1 цвет",
    coresTrocadas: "заменено цветов: {{quantas}}",
    avisoDeCss: "Эта тема несёт CSS своего автора, а CSS достаёт до любого уголка экрана. Импортируйте только у тех, кому доверяете.",
    soCores: "Эта тема меняет только цвета. Никакого стороннего CSS.",
    aplicar: "Применить",
    previaSemMotor: "В предпросмотре движок не работает. Установите, чтобы увидеть.",
    motorAnimado: "{{motor}}, с анимацией",
  },
  sair: "Выйти",
  versoes: {
    termos: "Условия использования",
    privacidade: "Политика конфиденциальности",
    copiar: "Нажмите, чтобы копировать",
    copiado: "Скопировано",
  },
  telas: {
    conta: "Мой аккаунт",
    privacidade: "Конфиденциальность",
    conexoes: "Подключения",
    voz: "Звук",
    video: "Видео",
    avisos: "Уведомления",
    aplicativos: "Приложения",
    aparencia: "Внешний вид",
    batePapo: "Чат",
    acessibilidade: "Доступность",
    idioma: "Язык",
    aplicativo: "Скачать приложение",
    atalhos: "Горячие клавиши",
    desktop: "Приложение для компьютера",
    avancado: "Дополнительно",
    servidor: "Сервер",
    comunicado: "Системное объявление",
    denuncias: "Жалобы",
    publicacoes: "Развёртывания",
  },
  grupos: {
    conta: "Аккаунт",
    app: "Настройки приложения",
    desenvolvedor: "Разработчик",
    administracao: "Администрирование",
  },
  secoes: {
    detalhesDeLogin: "Данные для входа",
    dispositivos: "Устройства",
    usuariosBloqueados: "Заблокированные пользователи",
    aplicativosAutorizados: "Авторизованные приложения",
    sessoes: "Сеансы",
    amigosEDms: "Друзья и личные сообщения",
    compartilhamentoDeAtividade: "Передача активности",
    visibilidadeDoPerfil: "Видимость профиля",
    exportarDados: "Экспорт данных",
    exclusaoDeDados: "Удаление данных",
    tema: "Тема",
    corDeDestaque: "Цвет акцента",
    interface: "Интерфейс",
    listaDeCanais: "Список каналов",
    zoomDoApp: "Масштаб приложения",
    escalaDaFonte: "Размер шрифта в чате",
    modoStreamer: "Приватность при трансляции",
    cursores: "Курсоры",
    movimento: "Движение",
    textoEmVoz: "Текст в речь",
    teclado: "Клавиатура",
    formatoDaHora: "Формат времени",
    idiomaDaInterface: "Язык интерфейса",
    dispositivosDeVoz: "Устройства",
    testeDoMicrofone: "Проверка микрофона",
    modoDeEntrada: "Режим ввода",
    sensibilidade: "Чувствительность ввода",
    qualidade: "Качество",
    camera: "Камера",
    transmissao: "Трансляция",
    exibicao: "Отображение",
    entrada: "Ввод",
    midia: "Медиа",
    geral: "Общие",
    preferenciaDeMencao: "Настройка упоминаний",
    sons: "Звуки",
  },
};
