export const configuracoes = {
  sair: "Выйти",
  versoes: {
    copiar: "Нажмите, чтобы копировать",
    copiado: "Скопировано",
  },
  telas: {
    conta: "Мой аккаунт",
    privacidade: "Конфиденциальность",
    conexoes: "Подключения",
    voz: "Звук",
    video: "Видео",
    avisos: "Уведомления",
    aplicativos: "Приложения",
    aparencia: "Внешний вид",
    batePapo: "Чат",
    acessibilidade: "Доступность",
    idioma: "Язык",
    aplicativo: "Скачать приложение",
    atalhos: "Горячие клавиши",
    servidor: "Сервер",
  },
  grupos: {
    conta: "Аккаунт",
    app: "Настройки приложения",
    desenvolvedor: "Разработчик",
    administracao: "Администрирование",
  },
  secoes: {
    detalhesDeLogin: "Данные для входа",
    dispositivos: "Устройства",
    usuariosBloqueados: "Заблокированные пользователи",
    aplicativosAutorizados: "Авторизованные приложения",
    sessoes: "Сеансы",
    amigosEDms: "Друзья и личные сообщения",
    compartilhamentoDeAtividade: "Передача активности",
    visibilidadeDoPerfil: "Видимость профиля",
    exportarDados: "Экспорт данных",
    exclusaoDeDados: "Удаление данных",
    tema: "Тема",
    corDeDestaque: "Цвет акцента",
    interface: "Интерфейс",
    listaDeCanais: "Список каналов",
    zoomDoApp: "Масштаб приложения",
    escalaDaFonte: "Размер шрифта в чате",
    modoStreamer: "Приватность при трансляции",
    movimento: "Движение",
    textoEmVoz: "Текст в речь",
    teclado: "Клавиатура",
    formatoDaHora: "Формат времени",
    idiomaDaInterface: "Язык интерфейса",
    dispositivosDeVoz: "Устройства",
    testeDoMicrofone: "Проверка микрофона",
    modoDeEntrada: "Режим ввода",
    sensibilidade: "Чувствительность ввода",
    qualidade: "Качество",
    camera: "Камера",
    transmissao: "Трансляция",
    exibicao: "Отображение",
    entrada: "Ввод",
    midia: "Медиа",
    geral: "Общие",
    preferenciaDeMencao: "Настройка упоминаний",
    sons: "Звуки",
  },
};
