export const conversa = {
  lista: {
    carregando: "Загрузка сообщений…",
    carregandoMais: "Загрузка…",
    verMais: "Прокрутите вверх, чтобы увидеть больше",
    semHistorico: "История недоступна",
    semHistoricoDetalhe: "У вашей роли нет прав читать историю канала #{{canal}}. Новые сообщения продолжат появляться, пока вы здесь.",
    boasVindas: "Добро пожаловать в #{{canal}}",
    boasVindasDetalhe: "Это начало канала #{{canal}}.",
  },
  data: {
    hoje: "Сегодня",
    ontem: "Вчера",
    hojeAs: "сегодня в {{hora}}",
    ontemAs: "вчера в {{hora}}",
  },
  digitando: {
    um: "{{nome}} печатает…",
    dois: "{{primeiro}} и {{segundo}} печатают…",
    varios: "{{quantidade}} человек печатают…",
  },
  mensagem: {
    usou: "использует",
    fixada: "закреплено",
    editado: "(изменено)",
    ignorada: "Сообщение от того, кого вы игнорируете.",
    mostrar: "Показать",
    escPara: "Esc, чтобы",
    cancelar: "отменить",
    enterParaSalvar: "Enter, чтобы сохранить",
    falhou: "Не отправлено. Попробовать снова",
    naoLidasDaqui: "Непрочитанные с этого места.",
    linkCopiado: "Ссылка скопирована.",
    idCopiado: "ID скопирован.",
    naoDeuParaCopiar: "Ваш браузер не разрешил копирование.",
    apagarTitulo: "Удалить сообщение?",
    apagarDescricao: "Оно исчезнет для всех на канале. Восстановить его нельзя.",
    apagarAcao: "Удалить",
    citacaoAnexo: "нажмите, чтобы увидеть вложение",
    citacaoSumiu: "Исходного сообщения здесь больше нет.",
    reagirCom: "Реакция {{emoji}} — удерживайте для супер-реакции",
    segureParaSuper: "{{emoji}} — удерживайте для супер-реакции",
  },
  acoes: {
    reagir: "Реакция",
    responder: "Ответить",
    encaminhar: "Переслать",
    favoritar: "Сохранить сообщение",
    tirarDosFavoritos: "Убрать из сохранённых",
    marcarNaoLida: "Отметить как непрочитанное",
    copiarLink: "Копировать ссылку на сообщение",
    copiarId: "Копировать ID сообщения",
    fixar: "Закрепить сообщение",
    desafixar: "Открепить",
    editar: "Изменить",
    apagar: "Удалить",
    mais: "Ещё",
    adicionarReacao: "Добавить реакцию",
    superReagirCom: "Супер-реакция {{emoji}}",
    fixarMensagem: "Закрепить сообщение",
    desafixarMensagem: "Открепить сообщение",
    editarMensagem: "Изменить сообщение",
    apagarMensagem: "Удалить сообщение",
  },
  mencao: {
    cargo: "Упоминание роли",
    pessoa: "Упоминание",
    alguem: "кто-то",
    cargoSemNome: "роль",
    here: "Уведомляет тех, кто онлайн",
    everyone: "Уведомляет весь сервер",
  },
  codigo: {
    copiar: "Копировать",
    copiado: "Скопировано",
    copiarAria: "Копировать код",
    copiadoAria: "Код скопирован",
  },
  caixa: {
    escrever: "Написать в #{{canal}}",
    escreverSemCanal: "Написать сообщение",
    semPermissao: "У вас нет прав отправлять сообщения в этом канале",
    solteParaAnexar: "Отпустите, чтобы прикрепить",
    respondendoPara: "Ответ для",
    vaiNotificar: "Человек получит уведомление",
    naoVaiNotificar: "Человек не получит уведомления",
    ligado: "вкл.",
    desligado: "выкл.",
    pararDeResponder: "Перестать отвечать",
    mais: "Ещё",
    enviarArquivo: "Отправить файл",
    criarEnquete: "Создать опрос",
    expressoes: "Эмодзи, GIF и стикеры",
    enviar: "Отправить",
    aguardandoEnvio: "Ждём загрузку",
    modoLento: "Медленный режим включён ({{tempo}})",
    modoLentoDica: "Медленный режим стоит на {{segundos}} с. Подождите, прежде чем отправить следующее сообщение.",
  },
  anexos: {
    enviando: "Загрузка…",
    modificar: "Изменить {{arquivo}}",
    remover: "Убрать {{arquivo}}",
    ver: "Посмотреть {{arquivo}}",
    mostrarSpoiler: "Показать спойлер: {{arquivo}}",
    spoiler: "спойлер",
    spoilerTitulo: "Спойлер",
    editarTitulo: "Изменить вложение",
    nomeDoArquivo: "Имя файла",
    descricao: "Описание альтернативного текста",
    descricaoDica: "Опишите этот файл для программ чтения с экрана",
    marcarSpoiler: "Отметить как спойлер",
    cancelar: "Отмена",
    salvar: "Сохранить",
  },
  cartao: {
    tocador: "Плеер",
    abrir: "Открыть {{destino}}",
    tocar: "Воспроизвести {{titulo}}",
    video: "видео",
    verImagem: "Посмотреть изображение",
  },
  enquete: {
    titulo: "Опрос",
    encerrada: "Опрос завершён",
    variasRespostas: "Опрос — несколько ответов",
    umVoto: "{{quantidade}} голос",
    votos: "{{quantidade}} голосов",
    umVotoNoTotal: "{{quantidade}} голос всего",
    votosNoTotal: "{{quantidade}} голосов всего",
    encerraEm: "завершится {{quando}}",
    encerrarAgora: "Завершить сейчас",
  },
  fixadas: {
    titulo: "Закреплённые сообщения",
    vazio: "В этом канале пока нет закреплённых сообщений.",
    desafixar: "Открепить",
    anexo: "(вложение)",
    enquete: "(опрос)",
    dicaRotulo: "СОВЕТ:",
    dica: "у кого есть право «Управление сообщениями», может закрепить прямо из меню сообщения.",
  },
  encaminhar: {
    titulo: "Переслать сообщение",
    paraOnde: "Куда?",
    semTexto: "(сообщение без текста)",
    nenhumLugar: "Нет места с таким названием.",
    canais: "Каналы",
    conversas: "Личные сообщения",
  },
};
