export const perfil = {
  carregando: "Загрузка…",
  editar: "Изменить профиль",
  mensagem: "Сообщение",
  abrirConversa: "Открыть переписку",
  verCompleto: "Открыть полный профиль",
  convidarParaServidor: "Пригласить на сервер",
  semServidores: "У вас нет серверов",
  conviteEnviado: "Приглашение отправлено {{nome}}.",
  moderador: "Открыть в режиме модератора",
  mais: "Ещё",
  ignorar: "Игнорировать",
  deixarDeIgnorar: "Больше не игнорировать",
  copiarId: "Копировать ID пользователя",
  idCopiado: "ID скопирован.",
  conexoes: "Подключения",
  membroDesde: "Участник с",
  sobre: "О себе",
  cargosTitulo: "Роли",
  visaoGeral: "Обзор",
  amigosEmComum: "Общие друзья ({{quantidade}})",
  servidoresEmComum: "Общие серверы ({{quantidade}})",
  amizade: {
    amigo: "Друг",
    pedidoEnviado: "Заявка в друзья отправлена",
    respondaAbaixo: "Отправил вам заявку — ответьте ниже",
    adicionar: "Добавить в друзья",
    teMandouPedido: "Отправил вам заявку в друзья",
    aceitar: "Принять",
    desfazer: "Удалить из друзей",
    desfazerTitulo: "Удалить {{nome}} из друзей?",
    desfazerDescricao: "Вы перестаёте быть друзьями. Личная переписка останется в истории, и позже вы сможете добавить его снова.",
    bloquear: "Заблокировать",
    bloquearTitulo: "Заблокировать {{nome}}?",
    bloquearDescricao: "Вы перестаёте быть друзьями, личная переписка перестаёт принимать сообщения, и он больше не сможет отправить вам заявку в друзья.",
    linkCopiado: "Вы не друзья — ссылка скопирована, отправьте её сами.",
  },
  recado: {
    escrever: "Написать @{{usuario}}",
    enviar: "Отправить",
    enviada: "Сообщение отправлено",
    falhou: "Не удалось отправить. Попробуйте из переписки.",
  },
  cartao: {
    trocarFaixa: "Сменить баннер карточки",
    trocarFaixaCurto: "Сменить баннер",
    trocarFoto: "Сменить фото профиля",
    trocarFotoCurto: "Сменить фото",
    suaEtiqueta: "Ваш ярлык",
    editarEtiqueta: "Нажмите, чтобы изменить ярлык",
    conteAlgo: "Расскажите о себе",
    adicionarStatus: "Добавить статус",
    adicionarDescricao: "Нажмите, чтобы добавить описание",
    cargo: "Роль",
    cargos: "Роли",
    cargosCom: "Роли — {{quantidade}}",
    tirarCargo: "Снять роль {{cargo}}",
  },
  cargos: {
    adicionar: "Добавить роль",
    procurar: "Найти роль",
  },
  etiqueta: {
    escolher: "Выбрать ярлык сервера",
    nenhuma: "Нет ярлыка сервера",
    semEtiqueta: "Ни у одного из ваших серверов нет ярлыка",
  },
  emblemas: {
    doServidor: "Значки этого сервера",
    limite: "Можно носить до {{quantidade}} значков.",
  },
  nota: {
    vazia: "Нажмите, чтобы записать заметку",
    rotulo: "Заметка (видите только вы)",
  },
  status: {
    titulo: "Статус",
    definir: "Задать статус",
    escolherEmoji: "Выбрать эмодзи",
    tirarEmoji: "Убрать эмодзи",
    oQuePensa: "О чём вы думаете?",
    limparAgora: "Очистить статус сейчас",
    naoLimpar: "Не очищать",
    limpar30m: "Очистить через 30 минут",
    limpar1h: "Очистить через 1 час",
    limpar4h: "Очистить через 4 часа",
    limparHoje: "Очистить сегодня",
    limparAmanha: "Очистить завтра",
    comHora: "{{prazo}} в {{hora}}",
  },
  presenca: {
    disponivel: "В сети",
    ausente: "Не на месте",
    naoPerturbar: "Не беспокоить",
    naoPerturbarDetalhe: "Вы не получаете уведомления о новых сообщениях",
    invisivel: "Невидимка",
    invisivelDetalhe: "Для других вы не в сети",
  },
  menu: {
    mudarDeConta: "Сменить аккаунт",
    gerenciarContas: "Управление аккаунтами",
  },
  editor: {
    decoracao: "Изменить украшение аватара",
    naoSalvo: "Не забудьте сохранить изменения!",
    principal: "Основной профиль",
  },
};
