export const amizades = {
  ativosAgora: "Dabar aktyvūs",
  procurando: "Žiūrime, kas čia…",
  tudoTranquilo: "Kol kas ramu…",
  tudoTranquiloDetalhe: "Kai tu ar draugas prisijungsite prie skambučio, jis pasirodys čia — ir prisijungsi vienu paspaudimu.",
  emVoz: "Balso kanale",
  voce: "Tu",
  soVoce: "Tik tu",
  pessoas: "{{quantas}} žmonių",
  voltarParaChamada: "Grįžti į skambutį",
  entrarNaChamada: "Prisijungti prie skambučio",
  abrirCanal: "Atidaryti {{canal}} serveryje {{servidor}}",
  mensagensDiretas: "Tiesioginės žinutės",
  encontreConversa: "Rasti pokalbį",
  amigos: "Draugai",
  conversas: "Pokalbiai",
  semConversas: "Kol kas pokalbių nėra. Pridėk draugą ir pradėk.",
  semConversaComEsseNome: "Nėra pokalbio tokiu pavadinimu.",
  abrirMenu: "Atidaryti serverius ir pokalbius",
  solicitacoes: "Žinučių prašymai",
  pedidos: "Prašymai",
  spam: "Šlamštas",
  pedidosPendentes: "Laukiantys prašymai",
  marcadosComoSpam: "Pažymėti kaip šlamštas",
  aceitar: "Priimti",
  ignorar: "Nepaisyti",
  marcarSpam: "Pažymėti kaip šlamštą",
  semPedidos: "Laukiančių prašymų nėra.",
  semPedidosDetalhe: "Tas, kuris nėra tavo draugas, bet yra su tavimi tame pačiame serveryje, patenka čia, nepasiekęs tavo pokalbių.",
  semSpam: "Niekas nepažymėta kaip šlamštas.",
  semSpamDetalhe: "Tai, ką atrenka šlamšto filtras, arba tai, ką pažymi pats, lieka šioje kortelėje.",
  umServidorEmComum: "1 bendras serveris",
  servidoresEmComum: "Bendrų serverių: {{quantos}}",
  semServidoresEmComum: "Bendrų serverių nėra",
};
