export const chamada = {
  conectando: "Jungiamasi prie skambučio…",
  naoEntrou: "Nepavyko prisijungti prie skambučio",
  sair: "Palikti skambutį",
  sairDaVoz: "Palikti balso skambutį",
  desconectar: "Atsijungti",
  voltar: "Grįžti į skambutį",
  voltarAosQuadros: "Grįžti į skambučio langelius",
  fecharChat: "Uždaryti pokalbį",
  carregandoPrevia: "Įkeliama peržiūra…",
  maisOpcoes: "Daugiau",
  deVideo: "Vaizdo skambutis",
  deVoz: "Balso skambutis",
  alguem: "Kažkas",
  volume: {
    entrada: "Įvesties garsumas",
    saida: "Išvesties garsumas",
    live: "Transliacijos garsumas",
    liveComPorcento: "Transliacijos garsumas ({{porcento}}%)",
    liveSemSom: "Transliacija be garso",
  },
  aparelhos: {
    entrada: "Įvesties įrenginys",
    saida: "Išvesties įrenginys",
    camera: "Kamera",
    microfone: "Mikrofonas",
    saidaCurto: "Išvestis",
    oDoSistema: "Sistemos",
    aDoSistema: "Sistemos",
    semEscolhaDeSaida: "Ši naršyklė neleidžia pasirinkti išvesties — sprendžia sistema.",
    espelhar: "Veidrodinė mano kamera",
    configEntrada: "Įvesties nustatymai",
    configSaida: "Išvesties nustatymai",
    configCamera: "Kameros nustatymai",
    configAudioEVideo: "Garso ir vaizdo nustatymai",
  },
  tela: {
    compartilhar: "Bendrinti ekraną",
    compartilharAcao: "Bendrinti",
    cancelar: "Atšaukti",
    telas: "Ekranai",
    janelas: "Langai",
    somDoComputador: "Paimti ir kompiuterio garsą",
    somDoSistema: "Paimti ir sistemos garsą",
    configCompartilhamento: "Bendrinimo nustatymai",
    mostrarSemVideo: "Rodyti tuos, kurie be vaizdo",
    semFontes: "Sistema negrąžino nė vieno ekrano ar lango bendrinti.",
    pararDeCompartilhar: "Nustoti bendrinti",
    encerrarTransmissao: "Baigti transliaciją",
  },
  live: {
    etiqueta: "Tiesiogiai",
    etiquetaMaiuscula: "TIESIOGIAI",
    assistir: "Žiūrėti transliaciją",
    assistirPessoa: "Žiūrėti {{nome}}",
    pararDeAssistir: "Nustoti žiūrėti",
  },
  membro: {
    mudarMeuApelido: "Keisti mano slapyvardį",
    meuMicrofone: "Mano mikrofonas",
    ouvirChamada: "Klausytis skambučio",
    copiarMeuId: "Kopijuoti mano ID",
    idCopiado: "ID nukopijuotas.",
    mensagem: "Žinutė",
    silenciar: "Nutildyti",
    alterarApelido: "Keisti slapyvardį",
    cargos: "Rolės",
    semCargo: "Nesukurta nė viena rolė",
    moverPara: "Perkelti į",
    silenciarNoServidor: "Nutildyti balsą serveryje",
    desativarAudioNoServidor: "Išjungti garsą serveryje",
    desconectar: "Atsijungti",
    apelidoTitulo: "Jūsų slapyvardis šiame serveryje",
    apelidoDeAlguem: "{{nome}} slapyvardis",
    apelidoCampo: "Slapyvardis",
    apelidoDicaPropria: "Galioja tik čia. Palikite tuščią, kad grįžtų įprastas jūsų vardas.",
    apelidoDicaDeOutro: "Galioja tik šiame serveryje. Palikite tuščią, kad grįžtų pradinis vardas.",
  },
  detalhes: {
    abrir: "Balso informacija",
    titulo: "Balso Informacija",
    conexao: "Ryšys",
    pingMedio: "Vidutinis ping",
    ultimoPing: "Paskutinis ping",
    perda: "Išsiųstų paketų praradimas",
    medindo: "Matuojama…",
    criptografado: "Šifruota iki serverio (DTLS-SRTP)",
    explicacao: "Virš 250 ms vėlavimas girdimas pokalbyje — žmonės pradeda kalbėti vienas per kitą. Paketų praradimas virš 10% balsą paverčia robotišku. Abiem atvejais problema beveik visada tarp jūsų ir interneto: pabandykite laidą vietoj Wi-Fi arba perkraukite maršruto parinktuvą.",
  },
  microfone: {
    bloqueado: "Mikrofonas užblokuotas — jūs tik klausotės. Leiskite prieigą naršyklės leidimuose.",
    bloqueadoNoMac: "macOS blokuoja mikrofoną. Pažymėkite",
    caminhoNoMac: "Sistemos nustatymai → Privatumas ir sauga → Mikrofonas",
    abrirAjustes: "Atidaryti nustatymus",
    vaiReabrir: "macOS paprašys iš naujo atidaryti programą.",
    naoAbriu: "Nepavyko atidaryti mikrofono — jūs tik klausotės. Patikrinkite įrenginį: Nustatymai → Balsas ir vaizdas.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS dar neleido įrašyti ekrano. Be to bendrinimas išeina juodas.",
    marque: "Pažymėkite",
    reabra: "skiltyje „Ekrano įrašymas“ ir iš naujo atidarykite programą.",
  },
  ruido: {
    titulo: "Triukšmo slopinimas",
    explicacao: "Pašalinkite foninį triukšmą iš savo balso. Pabandykite suploti ar pastumti klaviatūrą kalbėdami — skambutyje girdi tik jus.",
    semSuporte: "Ši naršyklė nepaleidžia išplėstinio slopinimo. Naršyklės savasis vis dar galioja, tik silpnesnis.",
    aplicando: "Taikoma skambučiui…",
    faleParaTestar: "Kalbėkite, kad išbandytumėte",
    verdeQuandoPassa: "Žalia, kai jūsų balsas praeina.",
    teOuvindo: "Jus girdi kaip tik dabar.",
    feitoCom: "Sukurta su",
    aquiNoAparelho: ", čia, jūsų įrenginyje",
    ajustes: "Nustatymai",
  },
  permissoes: {
    titulo: "macOS leidimai",
    detalhe: "macOS klausia tik kartą, o paskui tai keičiasi tik jo paties skydelyje. Čia matote, kas galioja, ir išsprendžiate, ko trūksta.",
    concedida: "Suteiktas",
    negada: "Atmestas",
    naoPedida: "Neprašytas",
    permitir: "Leisti",
    abrirAjustes: "Atidaryti nustatymus",
    microfone: "Mikrofonas",
    microfoneDetalhe: "Kalbėti skambučiuose ir tikrinti savo įvestį.",
    camera: "Kamera",
    cameraDetalhe: "Įjungti vaizdą skambutyje.",
    tela: "Ekrano įrašymas",
    telaDetalhe: "Bendrinti ekraną ir langus.",
    monitoramento: "Įvesties stebėjimas",
    monitoramentoDetalhe: "Naudoti spausk-ir-kalbėk net kai Gravaê veikia fone.",
  },
  jaConectado: {
    titulo: "Jūs jau esate šiame skambutyje",
    trazer: "Perkelti skambutį čia",
    deixar: "Palikti kaip yra",
    detalhe: "Perkėlus čia, kitas galas iškrenta iš skambučio — jūsų paskyra vienu metu būna vienoje vietoje.",
  },
};
