export const comum = {
  carregando: "Įkeliama…",
  salvar: "Išsaugoti",
  salvando: "Išsaugoma…",
  descartar: "Atmesti",
  redefinir: "Atstatyti",
  naoSalvo: "Turite neišsaugotų pakeitimų.",
  fechar: "Uždaryti",
  criar: "Sukurti",
  nome: "Pavadinimas",
  emoji: "Jaustukas",
  previa: "Peržiūra",
  cancelar: "Atšaukti",
  enviar: "Siųsti",
  apagar: "Ištrinti",
  excluir: "Ištrinti",
  remover: "Pašalinti",
  trocar: "Pakeisti",
};
