export const configuracoes = {
  efeitos: {
    titulo: "Žymeklio efektai",
    detalhe: "Pėdsakas ir kibirkštys, piešiami virš programėlės. Prasideda išjungti ir patys užgęsta, jei paprašėte mažiau judesio.",
    rastro: "Žymeklio pėdsakas",
    rastroDetalhe: "Linija, kuri seka žymeklį ir blėsta už jo.",
    faisca: "Kibirkštis spustelėjus",
    faiscaDetalhe: "Trumpi brūkšniai, išlekiantys iš spustelėjimo vietos.",
    cor: "Spalva",
    espessura: "Storis",
    comprimento: "Ilgis",
    tamanho: "Dydis",
    quantidade: "Kiekis",
  },
  email: {
    verificarTitulo: "Patvirtinkite savo el. paštą",
    verificarDetalhe: "Kai kurios bendruomenės leidžia rašyti tik patvirtinusiems. Užtenka spustelėti.",
    enviar: "Siųsti nuorodą",
    enviado: "Pažiūrėkite į gautuosius. Nuoroda galioja parą.",
    falhou: "Laiško išsiųsti nepavyko.",
    confirmado: "El. paštas patvirtintas",
    confirmadoDetalhe: "Padaryta. Dabar rašote bet kurioje bendruomenėje, kuri to prašo.",
    linkIncompleto: "Nepilna nuoroda",
    linkIncompletoDetalhe: "Adrese trūksta kodo. Atverkite nuorodą tiesiai iš laiško.",
    confirmando: "Tvirtinama…",
    expirou: "Ši nuoroda jau panaudota arba nebegalioja.",
    irParaOApp: "Į programėlę",
  },
  tema: {
    indisponivel: "Tema nepasiekiama",
    indisponivelDetalhe: "Ją paskelbęs žmogus ją ištrynė arba nuoroda klaidinga.",
    indisponivelLinha: "Tema nepasiekiama. Ją paskelbęs žmogus ją ištrynė arba nuoroda klaidinga.",
    importar: "Importuoti temą",
    importarCurto: "Importuoti",
    importarDetalhe: "Tai pakeis dabartinę jūsų temą. Vėliau ją galėsite redaguoti: Nustatymai > Išvaizda > Temų studija.",
    porAutor: "autorius {{autor}}",
    umaCorTrocada: "pakeista 1 spalva",
    coresTrocadas: "pakeistos {{quantas}} spalvos",
    avisoDeCss: "Ši tema atsineša savo autoriaus CSS, o CSS pasiekia kiekvieną ekrano kampą. Importuokite tik iš žmonių, kuriais pasitikite.",
    soCores: "Ši tema keičia tik spalvas. Jokio CSS iš šalies.",
    aplicar: "Taikyti",
    previaSemMotor: "Peržiūra variklio nepaleidžia. Įdiekite, kad pamatytumėte.",
    motorAnimado: "{{motor}} animuotas",
  },
  sair: "Atsijungti",
  versoes: {
    termos: "Paslaugų sąlygos",
    privacidade: "Privatumo politika",
    copiar: "Spustelėkite, kad nukopijuotumėte",
    copiado: "Nukopijuota",
  },
  telas: {
    conta: "Mano paskyra",
    privacidade: "Privatumas",
    conexoes: "Ryšiai",
    voz: "Garsas",
    video: "Vaizdas",
    avisos: "Pranešimai",
    aplicativos: "Programos",
    aparencia: "Išvaizda",
    batePapo: "Pokalbis",
    acessibilidade: "Prieinamumas",
    idioma: "Kalba",
    aplicativo: "Atsisiųsti programą",
    atalhos: "Spartieji klavišai",
    desktop: "Kompiuterio programa",
    avancado: "Išplėstiniai",
    servidor: "Serveris",
    comunicado: "Sistemos pranešimas",
    denuncias: "Pranešimai",
    publicacoes: "Diegimai",
  },
  grupos: {
    conta: "Paskyra",
    app: "Programos nustatymai",
    desenvolvedor: "Kūrėjas",
    administracao: "Administravimas",
  },
  secoes: {
    detalhesDeLogin: "Prisijungimo duomenys",
    dispositivos: "Įrenginiai",
    usuariosBloqueados: "Užblokuoti naudotojai",
    aplicativosAutorizados: "Įgaliotos programos",
    sessoes: "Seansai",
    amigosEDms: "Draugai ir asmeninės žinutės",
    compartilhamentoDeAtividade: "Veiklos bendrinimas",
    visibilidadeDoPerfil: "Profilio matomumas",
    exportarDados: "Eksportuoti duomenis",
    exclusaoDeDados: "Ištrinti duomenis",
    tema: "Tema",
    corDeDestaque: "Akcento spalva",
    interface: "Sąsaja",
    listaDeCanais: "Kanalų sąrašas",
    zoomDoApp: "Programos mastelis",
    escalaDaFonte: "Pokalbio šrifto dydis",
    modoStreamer: "Privatumas transliuojant",
    cursores: "Žymekliai",
    movimento: "Judesys",
    textoEmVoz: "Tekstas į kalbą",
    teclado: "Klaviatūra",
    formatoDaHora: "Laiko formatas",
    idiomaDaInterface: "Sąsajos kalba",
    dispositivosDeVoz: "Įrenginiai",
    testeDoMicrofone: "Mikrofono patikra",
    modoDeEntrada: "Įvesties režimas",
    sensibilidade: "Įvesties jautrumas",
    qualidade: "Kokybė",
    camera: "Kamera",
    transmissao: "Transliacija",
    exibicao: "Rodymas",
    entrada: "Įvestis",
    midia: "Medija",
    geral: "Bendra",
    preferenciaDeMencao: "Paminėjimų nuostata",
    sons: "Garsai",
  },
};
