export const configuracoes = {
  sair: "Atsijungti",
  versoes: {
    copiar: "Spustelėkite, kad nukopijuotumėte",
    copiado: "Nukopijuota",
  },
  telas: {
    conta: "Mano paskyra",
    privacidade: "Privatumas",
    conexoes: "Ryšiai",
    voz: "Garsas",
    video: "Vaizdas",
    avisos: "Pranešimai",
    aplicativos: "Programos",
    aparencia: "Išvaizda",
    batePapo: "Pokalbis",
    acessibilidade: "Prieinamumas",
    idioma: "Kalba",
    aplicativo: "Atsisiųsti programą",
    atalhos: "Spartieji klavišai",
    avancado: "Išplėstiniai",
    servidor: "Serveris",
  },
  grupos: {
    conta: "Paskyra",
    app: "Programos nustatymai",
    desenvolvedor: "Kūrėjas",
    administracao: "Administravimas",
  },
  secoes: {
    detalhesDeLogin: "Prisijungimo duomenys",
    dispositivos: "Įrenginiai",
    usuariosBloqueados: "Užblokuoti naudotojai",
    aplicativosAutorizados: "Įgaliotos programos",
    sessoes: "Seansai",
    amigosEDms: "Draugai ir asmeninės žinutės",
    compartilhamentoDeAtividade: "Veiklos bendrinimas",
    visibilidadeDoPerfil: "Profilio matomumas",
    exportarDados: "Eksportuoti duomenis",
    exclusaoDeDados: "Ištrinti duomenis",
    tema: "Tema",
    corDeDestaque: "Akcento spalva",
    interface: "Sąsaja",
    listaDeCanais: "Kanalų sąrašas",
    zoomDoApp: "Programos mastelis",
    escalaDaFonte: "Pokalbio šrifto dydis",
    modoStreamer: "Privatumas transliuojant",
    movimento: "Judesys",
    textoEmVoz: "Tekstas į kalbą",
    teclado: "Klaviatūra",
    formatoDaHora: "Laiko formatas",
    idiomaDaInterface: "Sąsajos kalba",
    dispositivosDeVoz: "Įrenginiai",
    testeDoMicrofone: "Mikrofono patikra",
    modoDeEntrada: "Įvesties režimas",
    sensibilidade: "Įvesties jautrumas",
    qualidade: "Kokybė",
    camera: "Kamera",
    transmissao: "Transliacija",
    exibicao: "Rodymas",
    entrada: "Įvestis",
    midia: "Medija",
    geral: "Bendra",
    preferenciaDeMencao: "Paminėjimų nuostata",
    sons: "Garsai",
  },
};
