export const conversa = {
  lista: {
    carregando: "Įkeliamos žinutės…",
    carregandoMais: "Įkeliama…",
    verMais: "Slinkite aukštyn, kad pamatytumėte daugiau",
    semHistorico: "Istorija nepasiekiama",
    semHistoricoDetalhe: "Jūsų rolė neturi teisės skaityti #{{canal}} istorijos. Naujos žinutės ir toliau rodomos, kol esate čia.",
    boasVindas: "Sveiki atvykę į #{{canal}}",
    boasVindasDetalhe: "Čia prasideda kanalas #{{canal}}.",
  },
  data: {
    hoje: "Šiandien",
    ontem: "Vakar",
    hojeAs: "šiandien {{hora}}",
    ontemAs: "vakar {{hora}}",
  },
  digitando: {
    um: "{{nome}} rašo…",
    dois: "{{primeiro}} ir {{segundo}} rašo…",
    varios: "{{quantidade}} žmonių rašo…",
  },
  mensagem: {
    usou: "panaudojo",
    fixada: "prisegta",
    editado: "(redaguota)",
    ignorada: "Žinutė nuo žmogaus, kurį ignoruojate.",
    mostrar: "Rodyti",
    escPara: "Esc, kad",
    cancelar: "atšauktumėte",
    enterParaSalvar: "Enter, kad išsaugotumėte",
    falhou: "Neišsiuntė. Bandyti dar kartą",
    naoLidasDaqui: "Neskaityta nuo čia.",
    linkCopiado: "Nuoroda nukopijuota.",
    idCopiado: "ID nukopijuotas.",
    naoDeuParaCopiar: "Jūsų naršyklė neleido kopijuoti.",
    apagarTitulo: "Ištrinti žinutę?",
    apagarDescricao: "Ji dings visiems kanale. Atkurti nepavyks.",
    apagarAcao: "Ištrinti",
    citacaoAnexo: "spustelėkite, kad pamatytumėte priedą",
    citacaoSumiu: "Pirminės žinutės čia nebėra.",
    reagirCom: "Reaguoti su {{emoji}} — palaikykite super reakcijai",
    segureParaSuper: "{{emoji}} — palaikykite super reakcijai",
  },
  acoes: {
    reagir: "Reaguoti",
    responder: "Atsakyti",
    encaminhar: "Persiųsti",
    favoritar: "Išsaugoti žinutę",
    tirarDosFavoritos: "Pašalinti iš išsaugotų",
    marcarNaoLida: "Pažymėti kaip neskaitytą",
    copiarLink: "Kopijuoti žinutės nuorodą",
    copiarId: "Kopijuoti žinutės ID",
    fixar: "Prisegti žinutę",
    desafixar: "Atsegti",
    editar: "Redaguoti",
    apagar: "Ištrinti",
    mais: "Daugiau",
    adicionarReacao: "Pridėti reakciją",
    superReagirCom: "Super reakcija su {{emoji}}",
    fixarMensagem: "Prisegti žinutę",
    desafixarMensagem: "Atsegti žinutę",
    editarMensagem: "Redaguoti žinutę",
    apagarMensagem: "Ištrinti žinutę",
  },
  mencao: {
    cargo: "Rolės paminėjimas",
    pessoa: "Paminėjimas",
    alguem: "kažkas",
    cargoSemNome: "rolė",
    here: "Praneša tiems, kurie prisijungę",
    everyone: "Praneša visam serveriui",
  },
  codigo: {
    copiar: "Kopijuoti",
    copiado: "Nukopijuota",
    copiarAria: "Kopijuoti kodą",
    copiadoAria: "Kodas nukopijuotas",
    recolher: "Suskleisti",
    expandir: "Išskleisti",
    verInteiro: "Peržiūrėti visą failą",
    maisOpcoes: "Daugiau parinkčių",
    baixar: "Atsisiųsti",
    recolherLinhas: "Suskleisti ({{linhas}} eil.)",
    expandirLinhas: "Išskleisti ({{linhas}} eil.)",
    mudarIdioma: "Keisti kalbą",
    procurarIdioma: "Ieškoti kalbos kodo…",
    nenhumIdioma: "Tokios kalbos nėra.",
    quebrarTexto: "Laužyti tekstą",
  },
  caixa: {
    escrever: "Rašykite kanale #{{canal}}",
    escreverSemCanal: "Parašykite žinutę",
    semPermissao: "Neturite teisės siųsti žinučių šiame kanale",
    solteParaAnexar: "Paleiskite, kad pridėtumėte",
    longaTitulo: "Žinutė per ilga…",
    longaDescricao: "Pasiekei {{limite}} simbolių ribą. Gali siųsti kaip failą.",
    enviarComoArquivo: "Siųsti kaip failą",
    respondendoPara: "Atsakymas",
    vaiNotificar: "Žmogus gaus pranešimą",
    naoVaiNotificar: "Žmogus negaus pranešimo",
    ligado: "įjungta",
    desligado: "išjungta",
    pararDeResponder: "Atsisakyti atsakymo",
    mais: "Daugiau",
    enviarArquivo: "Siųsti failą",
    criarEnquete: "Sukurti apklausą",
    expressoes: "Jaustukai, GIF ir lipdukai",
    enviar: "Siųsti",
    aguardandoEnvio: "Laukiama įkėlimo",
    modoLento: "Lėtas režimas įjungtas ({{tempo}})",
    modoLentoDica: "Lėtas režimas nustatytas į {{segundos}} s. Palaukite prieš siųsdami kitą žinutę.",
  },
  anexos: {
    enviando: "Įkeliama…",
    modificar: "Keisti {{arquivo}}",
    remover: "Pašalinti {{arquivo}}",
    ver: "Peržiūrėti {{arquivo}}",
    mostrarSpoiler: "Rodyti spoilerį: {{arquivo}}",
    spoiler: "spoileris",
    spoilerTitulo: "Spoileris",
    editarTitulo: "Redaguoti priedą",
    nomeDoArquivo: "Failo pavadinimas",
    descricao: "Alternatyvaus teksto aprašas",
    descricaoDica: "Aprašykite šį failą ekrano skaitytuvams",
    marcarSpoiler: "Pažymėti kaip spoilerį",
    cancelar: "Atšaukti",
    salvar: "Išsaugoti",
  },
  cartao: {
    tocador: "Grotuvas",
    abrir: "Atidaryti {{destino}}",
    tocar: "Groti {{titulo}}",
    video: "vaizdo įrašas",
    verImagem: "Peržiūrėti paveikslėlį",
  },
  enquete: {
    titulo: "Apklausa",
    encerrada: "Apklausa uždaryta",
    variasRespostas: "Apklausa — keli atsakymai",
    umVoto: "{{quantidade}} balsas",
    votos: "{{quantidade}} balsų",
    umVotoNoTotal: "iš viso {{quantidade}} balsas",
    votosNoTotal: "iš viso {{quantidade}} balsų",
    encerraEm: "baigiasi {{quando}}",
    encerrarAgora: "Uždaryti dabar",
  },
  fixadas: {
    titulo: "Prisegtos žinutės",
    vazio: "Šiame kanale kol kas nėra prisegtų žinučių.",
    desafixar: "Atsegti",
    anexo: "(priedas)",
    enquete: "(apklausa)",
    dicaRotulo: "PATARIMAS:",
    dica: "kas turi teisę „Tvarkyti žinutes“, gali prisegti tiesiai iš žinutės meniu.",
  },
  encaminhar: {
    titulo: "Persiųsti žinutę",
    paraOnde: "Kur?",
    semTexto: "(žinutė be teksto)",
    nenhumLugar: "Nėra vietos tokiu pavadinimu.",
    canais: "Kanalai",
    conversas: "Asmeninės žinutės",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Ieškoti Klipy",
    figurinha: "Lipdukas",
    buscarFigurinha: "Rask tobulą lipduką",
    buscarEmoji: "Rask tobulą jaustuką",
    buscarReacao: "Rask tobulą reakciją",
    adicionarEmoji: "Pridėti jaustuką",
    limparBusca: "Išvalyti paiešką",
  },
  busca: {
    fechar: "Uždaryti paiešką",
    procurando: "Ieškoma…",
    resultado: "{{quantos}} rezultatas",
    resultados: "{{quantos}} rezultatų",
    nadaCom: "Nieko su {{termo}} čia nėra.",
    soOsQuePodeLer: "Paieška žiūri tik į kanalus, kuriuos gali skaityti.",
  },
  entrada: {
    titulo: "Gauta",
    naoLidas: "Neskaityta",
    salvas: "Išsaugota",
    mencoes: "Paminėjimai",
    fimTitulo: "Pasiekei pabaigą",
    fimDetalhe: "Daugiau nėra ko skaityti. Kai ateis nauja žinutė, ji atsiras čia.",
    semSalvosTitulo: "Nieko neišsaugota",
    semSalvosDetalhe: "Laikyk Shift ir spustelėk žinutės žymę, kad ją išsaugotum ir perskaitytum vėliau.",
    tirarDosSalvos: "Pašalinti iš išsaugotų",
    semMencoesTitulo: "Paminėjimų dar nėra",
    semMencoesDetalhe: "Paminėjimai apie tave rodomi čia už paskutines 7 dienas.",
  },
  forum: {
    descricao: "Kiekviena tema tampa atskiru pokalbiu — gera klausimui, kuris neturi pasimesti šnekos viduryje.",
    novoAssunto: "Nauja tema",
    vazio: "Temų dar nėra. Pradėk pirmą, ir pokalbis nuo pradžios liks tvarkingas.",
    titulo: "Pavadinimas",
    doQueSeTrata: "Apie ką tai?",
    primeiraMensagem: "Pirma žinutė",
    conteDoCaso: "Papasakok",
  },
};
