export const perfil = {
  carregando: "Įkeliama…",
  editar: "Redaguoti profilį",
  mensagem: "Žinutė",
  abrirConversa: "Atverti pokalbį",
  verCompleto: "Peržiūrėti visą profilį",
  convidarParaServidor: "Pakviesti į serverį",
  semServidores: "Neturite serverių",
  conviteEnviado: "Kvietimas išsiųstas {{nome}}.",
  moderador: "Atverti moderatoriaus rodinyje",
  mais: "Daugiau",
  ignorar: "Ignoruoti",
  deixarDeIgnorar: "Nebeignoruoti",
  copiarId: "Kopijuoti naudotojo ID",
  idCopiado: "ID nukopijuotas.",
  conexoes: "Prisijungimai",
  membroDesde: "Narys nuo",
  sobre: "Apie",
  cargosTitulo: "Rolės",
  visaoGeral: "Apžvalga",
  amigosEmComum: "Bendri draugai ({{quantidade}})",
  servidoresEmComum: "Bendri serveriai ({{quantidade}})",
  amizade: {
    amigo: "Draugas",
    pedidoEnviado: "Draugystės užklausa išsiųsta",
    respondaAbaixo: "Atsiuntė jums užklausą — atsakykite žemiau",
    adicionar: "Pridėti draugą",
    teMandouPedido: "Atsiuntė jums draugystės užklausą",
    aceitar: "Priimti",
    desfazer: "Pašalinti iš draugų",
    desfazerTitulo: "Pašalinti {{nome}} iš jūsų draugų?",
    desfazerDescricao: "Nustosite būti draugais. Privatus pokalbis lieka istorijoje, o vėliau galėsite jį pridėti iš naujo.",
    bloquear: "Blokuoti",
    bloquearTitulo: "Blokuoti {{nome}}?",
    bloquearDescricao: "Nustosite būti draugais, privatus pokalbis nebepriims žinučių, o jis nebegalės atsiųsti jums draugystės užklausos.",
    linkCopiado: "Nesate draugai — nuoroda nukopijuota, kad išsiųstumėte patys.",
  },
  recado: {
    escrever: "Rašyti @{{usuario}}",
    enviar: "Siųsti",
    enviada: "Žinutė išsiųsta",
    falhou: "Nepavyko išsiųsti. Pabandykite iš pokalbio.",
  },
  cartao: {
    trocarFaixa: "Keisti kortelės antraštę",
    trocarFaixaCurto: "Keisti antraštę",
    trocarFoto: "Keisti profilio nuotrauką",
    trocarFotoCurto: "Keisti nuotrauką",
    suaEtiqueta: "Jūsų žyma",
    editarEtiqueta: "Spustelėkite, kad redaguotumėte žymą",
    conteAlgo: "Papasakokite ką nors apie save",
    adicionarStatus: "Pridėti būseną",
    adicionarDescricao: "Spustelėkite, kad pridėtumėte aprašymą",
    cargo: "Rolė",
    cargos: "Rolės",
    cargosCom: "Rolės — {{quantidade}}",
    tirarCargo: "Nuimti rolę {{cargo}}",
  },
  cargos: {
    adicionar: "Pridėti rolę",
    procurar: "Ieškoti rolės",
  },
  etiqueta: {
    escolher: "Pasirinkti serverio žymą",
    nenhuma: "Nėra serverio žymos",
    semEtiqueta: "Nė vienas jūsų serveris neturi žymos",
  },
  emblemas: {
    doServidor: "Šio serverio ženkleliai",
    limite: "Galite nešioti iki {{quantidade}} ženklelių.",
  },
  nota: {
    vazia: "Spustelėkite, kad ką nors užsirašytumėte",
    rotulo: "Užrašas (matote tik jūs)",
    adicionar: "Pridėti užrašą (matai tik tu)",
  },
  status: {
    titulo: "Būsena",
    definir: "Nustatykite savo būseną",
    escolherEmoji: "Pasirinkti jaustuką",
    tirarEmoji: "Nuimti jaustuką",
    oQuePensa: "Apie ką galvojate?",
    limparAgora: "Išvalyti būseną dabar",
    naoLimpar: "Nevalyti",
    limpar30m: "Išvalyti po 30 minučių",
    limpar1h: "Išvalyti po 1 valandos",
    limpar4h: "Išvalyti po 4 valandų",
    limparHoje: "Išvalyti šiandien",
    limparAmanha: "Išvalyti rytoj",
    comHora: "{{prazo}} {{hora}}",
  },
  presenca: {
    disponivel: "Prisijungęs",
    ausente: "Pasitraukęs",
    naoPerturbar: "Netrukdyti",
    naoPerturbarDetalhe: "Negaunate pranešimų apie naujas žinutes",
    invisivel: "Nematomas",
    invisivelDetalhe: "Kitiems atrodote atsijungęs",
  },
  menu: {
    mudarDeConta: "Keisti paskyrą",
    gerenciarContas: "Tvarkyti paskyras",
  },
  editor: {
    decoracao: "Keisti avataro papuošimą",
    naoSalvo: "Nepamirškite išsaugoti pakeitimų!",
    principal: "Pagrindinis profilis",
  },
};
