export const servidor = {
  titulo: "Serverio nustatymai",
  auditoria: {
    todasAsAcoes: "Visi veiksmai",
    todosOsUsuarios: "Visi naudotojai",
    filtroMembros: "Nariai",
    filtroCanais: "Kanalai",
    filtroEmojis: "Jaustukai",
    filtroServidor: "Serveris",
    titulo: "Veiksmų žurnalas",
    porUsuario: "Filtruoti pagal žmogų",
    porAcao: "Filtruoti pagal veiksmą",
    vazio: "Su šiuo filtru dar nieko neužfiksuota.",
    motivo: "Priežastis:",
  },
  banimentos: {
    titulo: "Serverio užblokuotųjų sąrašas",
    descricao: "Kas čia yra, nebeįeis nė su nauju pakvietimu. Atblokavus prieiga grąžinama iškart.",
    procurar: "Ieškoti blokavimų pagal naudotojo vardą",
    vazioTitulo: "Blokavimų nėra",
    vazio: "Dar nieko neužblokavai… bet jei prireiks, nedvejok.",
    desbanir: "Atblokuoti",
  },
  excluir: {
    tudoVai: "Visi serverio {{servidor}} kanalai, žinutės ir pakvietimai bus ištrinti {{membros}} nariams. Paskui niekas jų nebeatgaus.",
    digite: "Įrašyk {{servidor}}, kad patvirtintum",
    titulo: "Ištrinti serverį",
    aviso: "To atšaukti nebegalima.",
  },
  emblemas: {
    apagarDescricao: "Jis nukrenta nuo visų, kas jį nešioja. To atšaukti negalima.",
    titulo: "Ženkleliai",
    vazio: "Ženklelių dar nėra.",
    novo: "Naujas ženklelis",
  },
  convites: {
    revogarTitulo: "Atšaukti pakvietimą?",
    revogarAcao: "Atšaukti",
    revogarDescricao: "Nuoroda {{codigo}} iškart nustoja veikti. Kas per ją jau atėjo, lieka serveryje.",
    titulo: "Pakvietimai",
    descricao: "Visos aktyvios šio serverio pakvietimo nuorodos.",
    vazio: "Dar nesukurta nė vieno pakvietimo.",
    revogar: "Atšaukti pakvietimą",
  },
  integracoes: {
    opcionais: "username ir avatar_url nebūtini ir galioja žinutei. Riba — 5 žinutės per 5 sekundes.",
    apagarDescricao: "URL iškart nustoja veikti. Jau išsiųstos žinutės lieka kanale.",
    titulo: "Integracijos",
    descricao: "Webhook yra adresas, kuris rašo į kanalą be paskyros. Pravartu pranešti, kad kompiliavimas praėjo, kad kažkas atidarė užklausą, ar ką dar norėtum siųsti iš scenarijaus.",
    novo: "Naujas webhook",
    vazio: "Webhook dar nėra. Sukurk vieną ir įklijuok URL ten, iš kur nori, kad ateitų žinutė.",
    canal: "Kanalas",
    apagar: "Ištrinti webhook",
    comoUsar: "Kaip naudoti",
    comoUsarTexto: "Siųsk POST su JSON:",
  },
  engajamento: {
    semCanal: "Nėra sistemos kanalo",
    titulo: "Įsitraukimas",
    descricao: "Ką serveris daro pats, kad neatrodytų tuščias, kai ateina kas nors naujas.",
    sistema: "Sistemos žinutės",
    boasVindas: "Siųsti pasisveikinimą, kai kas nors prisijungia",
    sorteio: "Be savo teksto apačioje sakinys traukiamas atsitiktinai — tas pats greitai nusibosta.",
    canalDoSistema: "Sistemos žinučių kanalas",
    mensagem: "Pasisveikinimo žinutė",
    deixeVazio: "Palik tuščią, kad būtų traukiama iš paruoštų sakinių",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtrai, kurie moderuoja patys, dar prieš atsirandant žinutei. Serverio administratorius niekada nefiltruojamas — o atleistos rolės praeina tiesiai.",
    palavras: {
      titulo: "Blokuoti savus žodžius",
      descricao: "Tavo sąrašas žodžių, kurių niekas negali rašyti.",
    },
    mencoes: {
      titulo: "Blokuoti paminėjimų šlamštą",
      descricao: "Blokuoja žinutę su per daug paminėjimų iš karto.",
    },
    links: {
      titulo: "Blokuoti nuorodas",
      descricao: "Sulaiko bet kokį į pokalbį įklijuotą adresą.",
    },
    definir: "Nustatyti",
    nomeDaRegra: "Taisyklės pavadinimas",
    bloqueadas: "Blokuojami žodžiai",
    digiteEnter: "Įrašyk ir spausk Enter",
    comparacao: "Palyginimas nepaiso didžiųjų raidžių, diakritikų ir skyrybos — ir negaudo žodžio kito žodžio viduje.",
    aPartirDe: "Blokuoti nuo kiek paminėjimų",
    oQueFazer: "Ką daryti",
    canalDoAlerta: "Įspėjimo kanalas",
    escolhaCanal: "Pasirink kanalą",
    castigo: "Nutildymas (minutės)",
    isentos: "Atleistos rolės",
    semCargos: "Rolių dar nesukurta.",
    salvarRegra: "Išsaugoti taisyklę",
    apagar: "Ištrinti taisyklę",
    excluirTitulo: "Ištrinti šią AutoMod taisyklę?",
    excluirDescricao: "Serveris iškart nustos pagal ją filtruoti. Galima sukurti iš naujo, bet dabartiniai nustatymai dings.",
    excluirAcao: "Ištrinti taisyklę",
  },
  cargos: {
    titulo: "Rolės",
    descricao: "Rolės duoda vardą, spalvą ir galias. Kas aukščiau sąraše, tas viršesnis už esančius žemiau — ir niekas neliečia rolės, lygios savajai ar aukštesnės.",
    criar: "Sukurti rolę",
    vazio: "Rolių dar nėra.",
    abaExibicao: "Išvaizda",
    abaPermissoes: "Teisės",
    abaMembros: "Nariai — {{quantos}}",
    everyone: "Galioja visiems serveryje. Tai pagrindas, ant kurio dedasi kitos rolės.",
    nomeDoCargo: "Rolės pavadinimas",
    cor: "Rolės spalva",
    corDica: "Nuspalvina rolę turinčio vardą narių sąraše ir pokalbyje.",
    semCor: "Be spalvos",
    corPersonalizada: "Sava spalva",
    estilo: "Vardo stilius",
    segundaCor: "Antra spalva",
    segundaCorDica: "Be jos perėjimas virsta viena spalva — jis nedingsta.",
    limparSegundaCor: "Išvalyti antrą spalvą",
    icone: "Piktograma",
    iconeDica: "Rodoma šalia rolės ją turinčio profilio kortelėje.",
    exibirSeparado: "Rodyti atskirai nuo kitų narių",
    exibirSeparadoDica: "Rolė gauna savo skiltį narių sąraše.",
    permitirMencionar: "Leisti paminėti šią rolę",
    permitirMencionarDica: "Bet kas galės pranešti visiems, kurie turi šią rolę.",
    semPoderDeConceder: "{{descricao}} (neturi šios teisės, kad ją suteiktum)",
    adicionar: "Pridėti ką nors į šią rolę",
    tirar: "Nuimti rolę",
    semNinguem: "Šios rolės dar niekas neturi.",
    apagar: "Ištrinti rolę",
    excluirTitulo: "Ištrinti rolę „{{nome}}\"?",
    excluirDescricao: "Kas turi šią rolę, praranda viską, ką ji davė. To atšaukti negalima.",
    excluirAcao: "Ištrinti rolę",
  },
  membros: {
    procurar: "Ieškoti pagal vardą ar naudotojo vardą",
    membroDesde: "Narys nuo",
    vazio: "Nieko nerasta.",
    acoesPara: "Veiksmai: {{nome}}",
    deCastigo: "nutildymo",
    tirarCastigo: "Nuimti nutildymą",
    castigo5min: "5 minutės",
    castigo1h: "1 valanda",
    castigo1d: "1 diena",
    castigo1s: "1 savaitė",
    expulsar: "Išmesti",
    expulsarTitulo: "Išmesti {{nome}}?",
    expulsarDescricao: "iškart palieka {{servidor}}. Gali grįžti su pakvietimu — išmetimas netrukdo grįžti.",
    banir: "Užblokuoti",
    banirTitulo: "Užblokuoti {{nome}}?",
    banirDescricao: "palieka {{servidor}} ir negrįš net su pakvietimu, kol blokavimas nebus panaikintas.",
    motivo: "Priežastis (nebūtina)",
    motivoDica: "Lieka veiksmų žurnale",
  },
  perfil: {
    titulo: "Serverio profilis",
    descricao: "Taip tavo serveris atrodo sąraše ir pakvietimo nuorodose.",
    icone: "Piktograma",
    faixa: "Baneris viršuje",
    nomeDoServidor: "Serverio pavadinimas",
    campoDescricao: "Aprašymas",
    doQueE: "Apie ką šis serveris?",
    comprimido: "Suspausta prieš įkeliant: {{economia}}",
  },
  etiqueta: {
    titulo: "Serverio žyma",
    descricao: "Iki 4 raidžių žyma, kuri rodoma šalia kiekvieno nario vardo — pokalbyje ir žmonių sąraše. Čia ji nemokama: be papildymų, be lygių.",
    escolhaNome: "Pasirink pavadinimą",
    limite: "Ne daugiau kaip 4 simboliai, raidės ir skaičiai.",
    escolhaInsignia: "Pasirink ženklelį",
    voce: "Tu",
    fala1: "kas nors nori pažaisti?",
    fala2: "žvilgtelk į mano žymą!",
    fala3: "oho, kaip tu ją gavai",
  },
  expressoes: {
    comoUsar: "Pridėk iki {{limite}} jaustukų, kuriuos gali naudoti visi šiame serveryje. Parašyk :vardas: pokalbyje, kad išsiųstum.",
    imagem: "Paveikslėlis",
    enviadoPor: "Įkėlė",
    semEmoji: "Jaustukų dar nėra.",
    figurinhas: "Lipdukai",
    enviarFigurinha: "Įkelti lipduką",
    nomeDaFigurinha: "Lipduko pavadinimas",
    exemploFigurinha: "Pvz.: kačiuko apkabinimas",
    figurinhaGrande: "Lipdukas viršija {{limite}}.",
    deixaPraLa: "Nesvarbu",
    sons: "Garsų pultas",
    enviarSom: "Įkelti garsą",
    nomeDoSom: "Garso pavadinimas",
    semSom: "Garsų dar nėra.",
    somGrande: "Garsas viršija {{limite}}.",
    emojiRelacionado: "Susijęs jaustukas",
    ouvir: "Klausyti",
    ouvirAssim: "Klausyti taip",
    volumeDe: "{{nome}} garsumas",
    volumeDica: "Galioja visiems serveryje. Kiekvienas vis tiek gali patylinti garsus tik sau, skambučio pulte.",
    falhaEnvio: "Failo įkelti nepavyko.",
    excluirTitulo: "Ištrinti {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Dingsta iš serverio visiems. Žinutės, kuriose jis jau panaudotas, lieka kaip yra.",
  },
  canal: {
    visaoGeral: "Apžvalga",
    nome: "Kanalo pavadinimas",
    topico: "Kanalo tema",
    topicoDica: "Apie ką čia kalbama?",
    modoLento: "Kiekvienas siunčia tik vieną žinutę per intervalą. Kas tvarko žinutes ar kanalus, praeina tiesiai.",
    visibilidade: "Turinio matomumas",
    padrao: "Numatytasis",
    padraoDica: "Kanalo turinys visada matomas.",
    spoiler: "Kanalas su spoileriais",
    spoilerDica: "Pažymėk šį kanalą kaip turintį spoilerių, kad siužeto posūkiai ir sunkios temos liktų paslėpti, kol kas nors nuspręs pažiūrėti.",
    idade: "Kanalas su amžiaus riba",
    idadeDica: "Įėjęs turi patvirtinti, kad yra pilnametis, kad matytų turinį.",
    bitrateDica: "Virš 64 kbps gali trukdyti tiems, kurių ryšys prastas.",
    qualidadeDeVideo: "Vaizdo kokybė",
    automatica: "Automatinė",
    limite: "Naudotojų riba — {{valor}}",
    pessoas: "{{quantos}} žmonių",
    semLimite: "be ribos",
    permissoesDescricao: "Čia keiti tai, kas galioja šiame kanale. Kas lieka ties „paveldėti\", toliau seka rolę.",
    excluir: {
      titulo: "Ištrinti kanalą",
      historico: "Visa kanalo {{canal}} istorija dingsta kartu su juo, visiems.",
      digite: "Įrašyk {{canal}}, kad patvirtintum",
    },
  },
  moderacao: {
    titulo: "Moderatoriaus rodinys",
    semPermissao: "Kad tai matytum, reikia teisės „Moderuoti narius\".",
    fecharEsc: "Uždaryti (Esc)",
    atividade: "Veikla serveryje",
    mensagens: "Žinutės",
    links: "Nuorodos",
    midia: "Medija",
    acoesNaAuditoria: "Veiksmai žurnale",
    moderacoesSofridas: "Gautos priemonės",
    permissoes: "Teisės ({{quantas}})",
    semPermissaoEspecial: "Jokių ypatingų teisių.",
    conta: "Paskyra",
    entrouNoServidor: "Prisijungė prie serverio",
    contaCriadaEm: "Paskyra sukurta",
    deCastigoAte: "Nutildytas iki",
    formaDeAdesao: "Kaip pateko",
    mensagem: "Žinutė",
    castigo: "Nutildymas",
    copiarId: "Kopijuoti ID",
    idCopiado: "ID nukopijuotas.",
    adicionarCargo: "Pridėti rolę",
    semCargos: "Nesukurta nė viena rolė",
    soEveryone: "Tik @everyone.",
    voltar: "Atgal",
    vazio: "Čia nieko nėra.",
    cinquenta: "Rodomi 50 naujausių.",
    irParaMensagem: "Eiti į žinutę",
    precisaSerAmigo: "Kad kalbėtumėtės, turite būti draugai.",
    expulsarDescricao: "Iškart palieka serverį, bet gali grįžti su pakvietimu.",
    banirDescricao: "Palieka serverį ir negrįš net su pakvietimu, kol blokavimas nebus panaikintas.",
    castigarTitulo: "Nutildyti {{nome}}?",
    castigoDescricao: "Kol tęsiasi, nerašo ir nekalba jokiame serverio kanale.",
    aplicarCastigo: "Taikyti nutildymą",
    duracao: "Trukmė minutėmis",
    informeDuracao: "Nurodyk trukmę minutėmis.",
  },
  abas: {
    expressoes: "Išraiškos",
    pessoas: "Žmonės",
    apps: "Programėlės",
    moderacao: "Moderavimas",
    banimentos: "Blokavimai",
  },
};
