export const amizades = {
  ativosAgora: "Most aktív",
  procurando: "Nézzük, ki van itt…",
  tudoTranquilo: "Egyelőre csend van…",
  tudoTranquiloDetalhe: "Amikor te vagy egy barátod belép egy hívásba, itt jelenik meg — és egy kattintással csatlakozhatsz.",
  emVoz: "Hangcsatornán",
  voce: "Te",
  soVoce: "Csak te",
  pessoas: "{{quantas}} fő",
  voltarParaChamada: "Vissza a híváshoz",
  entrarNaChamada: "Csatlakozás a híváshoz",
  abrirCanal: "{{canal}} megnyitása itt: {{servidor}}",
  mensagensDiretas: "Közvetlen üzenetek",
  encontreConversa: "Beszélgetés keresése",
  amigos: "Barátok",
  conversas: "Beszélgetések",
  semConversas: "Még nincs beszélgetés. Adj hozzá egy barátot a kezdéshez.",
  semConversaComEsseNome: "Nincs ilyen nevű beszélgetés.",
  abrirMenu: "Szerverek és beszélgetések megnyitása",
  solicitacoes: "Üzenetkérelmek",
  pedidos: "Kérelmek",
  spam: "Spam",
  pedidosPendentes: "Függő kérelmek",
  marcadosComoSpam: "Spamként megjelölve",
  aceitar: "Elfogadás",
  ignorar: "Mellőzés",
  marcarSpam: "Megjelölés spamként",
  semPedidos: "Nincs várakozó kérelem.",
  semPedidosDetalhe: "Aki nem a barátod, de közös szerveren van veled, ide kerül, mielőtt elérné a beszélgetéseidet.",
  semSpam: "Semmi sincs spamként megjelölve.",
  semSpamDetalhe: "Amit a spamszűrő félretesz, vagy amit te jelölsz meg, ezen a fülön marad.",
  umServidorEmComum: "1 közös szerver",
  servidoresEmComum: "{{quantos}} közös szerver",
  semServidoresEmComum: "Nincs közös szerver",
};
