export const chamada = {
  conectando: "Csatlakozás a híváshoz…",
  naoEntrou: "Nem sikerült csatlakozni a híváshoz",
  sair: "Kilépés a hívásból",
  sairDaVoz: "Kilépés a hanghívásból",
  desconectar: "Lecsatlakozás",
  voltar: "Vissza a híváshoz",
  voltarAosQuadros: "Vissza a hívás csempéihez",
  fecharChat: "Csevegés bezárása",
  mostrarChat: "Csevegés megjelenítése",
  convidar: "Meghívás a hívásba",
  carregandoPrevia: "Előnézet betöltése…",
  maisOpcoes: "További lehetőségek",
  deVideo: "Videohívás",
  deVoz: "Hanghívás",
  alguem: "Valaki",
  volume: {
    entrada: "Bemeneti hangerő",
    saida: "Kimeneti hangerő",
    live: "Az élő adás hangereje",
    liveComPorcento: "Az élő adás hangereje ({{porcento}}%)",
    liveSemSom: "Élő adás némítva",
  },
  aparelhos: {
    entrada: "Bemeneti eszköz",
    saida: "Kimeneti eszköz",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Kimenet",
    oDoSistema: "A rendszeré",
    aDoSistema: "A rendszeré",
    semEscolhaDeSaida: "Ez a böngésző nem engedi kiválasztani a kimenetet — a rendszer dönt.",
    espelhar: "A kamerám tükrözése",
    configEntrada: "Bemenet beállításai",
    configSaida: "Kimenet beállításai",
    configCamera: "Kamera beállításai",
    configAudioEVideo: "Hang- és videobeállítások",
  },
  tela: {
    compartilhar: "Képernyő megosztása",
    compartilharAcao: "Megosztás",
    cancelar: "Mégse",
    telas: "Képernyők",
    janelas: "Ablakok",
    somDoComputador: "A számítógép hangja is menjen",
    somDoSistema: "A rendszer hangja is menjen",
    configCompartilhamento: "Megosztás beállításai",
    mostrarSemVideo: "A videó nélküliek mutatása",
    semFontes: "A rendszer egyetlen megosztható képernyőt vagy ablakot sem adott vissza.",
    pararDeCompartilhar: "Megosztás leállítása",
    encerrarTransmissao: "Az adás befejezése",
  },
  live: {
    etiqueta: "Élő",
    etiquetaMaiuscula: "ÉLŐ",
    assistir: "Az adás megtekintése",
    assistirPessoa: "{{nome}} megtekintése",
    pararDeAssistir: "Megtekintés abbahagyása",
  },
  membro: {
    mudarMeuApelido: "A becenevem módosítása",
    meuMicrofone: "A mikrofonom",
    ouvirChamada: "A hívás hallgatása",
    copiarMeuId: "Az azonosítóm másolása",
    idCopiado: "Azonosító másolva.",
    mensagem: "Üzenet",
    silenciar: "Némítás",
    alterarApelido: "Becenév módosítása",
    cargos: "Rangok",
    semCargo: "Nincs létrehozott rang",
    moverPara: "Áthelyezés ide",
    silenciarNoServidor: "Hang némítása a szerveren",
    desativarAudioNoServidor: "Hang kikapcsolása a szerveren",
    desconectar: "Lecsatlakozás",
    apelidoTitulo: "A beceneved ezen a szerveren",
    apelidoDeAlguem: "{{nome}} beceneve",
    apelidoCampo: "Becenév",
    apelidoDicaPropria: "Csak itt érvényes. Hagyd üresen, és visszatér a szokásos neved.",
    apelidoDicaDeOutro: "Csak ezen a szerveren érvényes. Hagyd üresen, hogy visszatérjen az eredeti név.",
  },
  detalhes: {
    abrir: "Hangrészletek",
    titulo: "Hangrészletek",
    conexao: "Kapcsolat",
    pingMedio: "Átlagos ping",
    ultimoPing: "Utolsó ping",
    perda: "Elküldött csomagok vesztesége",
    medindo: "Mérés…",
    criptografado: "A szerverig titkosítva (DTLS-SRTP)",
    explicacao: "250 ms fölött hallatszik a késés a beszélgetésben — az emberek egymás szavába vágnak. A 10% fölötti csomagvesztés robotossá teszi a hangot. Mindkét esetben a gond szinte mindig közted és az internet közt van: próbálj kábelt wifi helyett, vagy indítsd újra a routert.",
  },
  microfone: {
    bloqueado: "A mikrofon le van tiltva — csak hallgatsz. Engedélyezd a hozzáférést a böngésző jogosultságainál.",
    bloqueadoNoMac: "A macOS blokkolja a mikrofont. Pipáld ki:",
    caminhoNoMac: "Rendszerbeállítások → Adatvédelem és biztonság → Mikrofon",
    abrirAjustes: "Beállítások megnyitása",
    vaiReabrir: "A macOS meg fogja kérni, hogy nyisd meg újra az alkalmazást.",
    naoAbriu: "Nem sikerült megnyitni a mikrofont — csak hallgatsz. Ellenőrizd az eszközt a Beállítások → Hang és videó alatt.",
  },
  gravacaoDeTela: {
    bloqueada: "A macOS még nem engedélyezte a képernyőfelvételt. Enélkül a megosztás feketén jön ki.",
    marque: "Pipáld ki:",
    reabra: "a Képernyőfelvételnél, és nyisd meg újra az alkalmazást.",
    jaMarcado: "Ha már be van pipálva, az engedély elavult a legutóbbi frissítéskor: vedd ki a pipát, tedd vissza, és nyisd meg újra az alkalmazást.",
  },
  ruido: {
    titulo: "Zajszűrés",
    explicacao: "Vedd ki a háttérzajt a hangodból. Próbálj tapsolni vagy megmozdítani a billentyűzetet beszéd közben — a hívásban lévők csak téged hallanak.",
    semSuporte: "Ez a böngésző nem futtatja a fejlett szűrést. A böngésző sajátja továbbra is érvényes, csak gyengébb.",
    aplicando: "Alkalmazás a hívásra…",
    faleParaTestar: "Beszélj a teszteléshez",
    verdeQuandoPassa: "Zöld, amikor átmegy a hangod.",
    teOuvindo: "Épp most hallanak.",
    feitoCom: "Készült ezzel:",
    aquiNoAparelho: ", itt, a saját eszközödön",
    ajustes: "Beállítások",
  },
  permissoes: {
    titulo: "macOS-engedélyek",
    detalhe: "A macOS csak egyszer kérdez, utána már csak a saját paneljében változik. Itt látod, mi van érvényben, és megoldod, ami hiányzik.",
    concedida: "Megadva",
    negada: "Elutasítva",
    naoPedida: "Nem kérve",
    permitir: "Engedélyezés",
    abrirAjustes: "Beállítások megnyitása",
    microfone: "Mikrofon",
    microfoneDetalhe: "Beszéd a hívásokban és a bemenet tesztelése.",
    camera: "Kamera",
    cameraDetalhe: "A videó bekapcsolása a hívásban.",
    tela: "Képernyőfelvétel",
    telaDetalhe: "A képernyő és az ablakok megosztása.",
    monitoramento: "Bemenet figyelése",
    monitoramentoDetalhe: "A nyomd-és-beszélj használata akkor is, ha a Gravaê a háttérben van.",
  },
  jaConectado: {
    titulo: "Már bent vagy ebben a hívásban",
    trazer: "Hozd ide a hívást",
    deixar: "Hagyd, ahogy van",
    detalhe: "Ha idehozod, a másik vég kiesik a hívásból — a fiókod egyszerre egy helyen van.",
  },
};
