export const configuracoes = {
  sair: "Kijelentkezés",
  versoes: {
    copiar: "Kattints a másoláshoz",
    copiado: "Másolva",
  },
  telas: {
    conta: "Fiókom",
    privacidade: "Adatvédelem",
    conexoes: "Kapcsolatok",
    voz: "Hang",
    video: "Videó",
    avisos: "Értesítések",
    aplicativos: "Alkalmazások",
    aparencia: "Megjelenés",
    batePapo: "Csevegés",
    acessibilidade: "Kisegítő lehetőségek",
    idioma: "Nyelv",
    aplicativo: "Alkalmazás letöltése",
    atalhos: "Gyorsbillentyűk",
    avancado: "Speciális",
    servidor: "Kiszolgáló",
  },
  grupos: {
    conta: "Fiók",
    app: "Alkalmazás beállításai",
    desenvolvedor: "Fejlesztő",
    administracao: "Adminisztráció",
  },
  secoes: {
    detalhesDeLogin: "Bejelentkezési adatok",
    dispositivos: "Eszközök",
    usuariosBloqueados: "Letiltott felhasználók",
    aplicativosAutorizados: "Engedélyezett alkalmazások",
    sessoes: "Munkamenetek",
    amigosEDms: "Barátok és közvetlen üzenetek",
    compartilhamentoDeAtividade: "Tevékenység megosztása",
    visibilidadeDoPerfil: "Profil láthatósága",
    exportarDados: "Adatok exportálása",
    exclusaoDeDados: "Adatok törlése",
    tema: "Téma",
    corDeDestaque: "Kiemelőszín",
    interface: "Felület",
    listaDeCanais: "Csatornalista",
    zoomDoApp: "Az alkalmazás nagyítása",
    escalaDaFonte: "Csevegés betűmérete",
    modoStreamer: "Adatvédelem közvetítés közben",
    movimento: "Mozgás",
    textoEmVoz: "Szövegfelolvasás",
    teclado: "Billentyűzet",
    formatoDaHora: "Időformátum",
    idiomaDaInterface: "A felület nyelve",
    dispositivosDeVoz: "Eszközök",
    testeDoMicrofone: "Mikrofonteszt",
    modoDeEntrada: "Bemeneti mód",
    sensibilidade: "Bemeneti érzékenység",
    qualidade: "Minőség",
    camera: "Kamera",
    transmissao: "Közvetítés",
    exibicao: "Megjelenítés",
    entrada: "Bevitel",
    midia: "Média",
    geral: "Általános",
    preferenciaDeMencao: "Említési beállítás",
    sons: "Hangok",
  },
};
