export const configuracoes = {
  efeitos: {
    titulo: "Mutató hatásai",
    detalhe: "Csík és szikrák az alkalmazás fölé rajzolva. Kikapcsolva indulnak, és maguktól kimaradnak, ha kevesebb mozgást kértél.",
    rastro: "A mutató csíkja",
    rastroDetalhe: "Vonal, ami követi a mutatót, és mögötte elhalványul.",
    faisca: "Szikra kattintásra",
    faiscaDetalhe: "Rövid vonalak, amik a kattintás helyéről repülnek szét.",
    cor: "Szín",
    espessura: "Vastagság",
    comprimento: "Hossz",
    tamanho: "Méret",
    quantidade: "Mennyiség",
  },
  email: {
    verificarTitulo: "Erősítsd meg az e-mailed",
    verificarDetalhe: "Egyes közösségekben csak a megerősítettek írhatnak. Egy kattintás.",
    enviar: "Link küldése",
    enviado: "Nézd meg a postafiókot. A link egy napig él.",
    falhou: "Az e-mailt nem sikerült elküldeni.",
    confirmado: "E-mail megerősítve",
    confirmadoDetalhe: "Kész. Mostantól írhatsz bárhol, ahol ezt kérik.",
    linkIncompleto: "Hiányos hivatkozás",
    linkIncompletoDetalhe: "A címből hiányzik a kód. Nyisd meg a linket egyenesen az e-mailből.",
    confirmando: "Megerősítés…",
    expirou: "Ezt a hivatkozást már felhasználták, vagy lejárt.",
    irParaOApp: "Irány az alkalmazás",
  },
  tema: {
    indisponivel: "A téma nem érhető el",
    indisponivelDetalhe: "Aki közzétette, törölte, vagy hibás a hivatkozás.",
    indisponivelLinha: "A téma nem érhető el. Aki közzétette, törölte, vagy hibás a hivatkozás.",
    importar: "Téma importálása",
    importarCurto: "Importálás",
    importarDetalhe: "Ez lecseréli a mostani témádat. Utána a Beállítások > Megjelenés > Témastúdió alatt szerkesztheted.",
    porAutor: "készítette: {{autor}}",
    umaCorTrocada: "1 kicserélt szín",
    coresTrocadas: "{{quantas}} kicserélt szín",
    avisoDeCss: "Ez a téma a szerzője CSS-ét hozza magával, és a CSS a képernyő minden sarkába belenyúl. Csak olyantól importálj, akiben megbízol.",
    soCores: "Ez a téma csak színeket cserél. Semmi külső CSS.",
    aplicar: "Alkalmaz",
    previaSemMotor: "Az előnézet nem futtatja a motort. Telepítsd, hogy lásd.",
    motorAnimado: "{{motor}} animálva",
  },
  sair: "Kijelentkezés",
  versoes: {
    termos: "Szolgáltatási feltételek",
    privacidade: "Adatvédelmi irányelvek",
    copiar: "Kattints a másoláshoz",
    copiado: "Másolva",
  },
  telas: {
    conta: "Fiókom",
    privacidade: "Adatvédelem",
    conexoes: "Kapcsolatok",
    voz: "Hang",
    video: "Videó",
    avisos: "Értesítések",
    aplicativos: "Alkalmazások",
    aparencia: "Megjelenés",
    batePapo: "Csevegés",
    acessibilidade: "Kisegítő lehetőségek",
    idioma: "Nyelv",
    aplicativo: "Alkalmazás letöltése",
    atalhos: "Gyorsbillentyűk",
    desktop: "Asztali alkalmazás",
    avancado: "Speciális",
    servidor: "Kiszolgáló",
    comunicado: "Rendszerüzenet",
    denuncias: "Jelentések",
    publicacoes: "Telepítések",
  },
  grupos: {
    conta: "Fiók",
    app: "Alkalmazás beállításai",
    desenvolvedor: "Fejlesztő",
    administracao: "Adminisztráció",
  },
  secoes: {
    detalhesDeLogin: "Bejelentkezési adatok",
    dispositivos: "Eszközök",
    usuariosBloqueados: "Letiltott felhasználók",
    aplicativosAutorizados: "Engedélyezett alkalmazások",
    sessoes: "Munkamenetek",
    amigosEDms: "Barátok és közvetlen üzenetek",
    compartilhamentoDeAtividade: "Tevékenység megosztása",
    visibilidadeDoPerfil: "Profil láthatósága",
    exportarDados: "Adatok exportálása",
    exclusaoDeDados: "Adatok törlése",
    tema: "Téma",
    corDeDestaque: "Kiemelőszín",
    interface: "Felület",
    listaDeCanais: "Csatornalista",
    zoomDoApp: "Az alkalmazás nagyítása",
    escalaDaFonte: "Csevegés betűmérete",
    modoStreamer: "Adatvédelem közvetítés közben",
    cursores: "Kurzorok",
    movimento: "Mozgás",
    textoEmVoz: "Szövegfelolvasás",
    teclado: "Billentyűzet",
    formatoDaHora: "Időformátum",
    idiomaDaInterface: "A felület nyelve",
    dispositivosDeVoz: "Eszközök",
    testeDoMicrofone: "Mikrofonteszt",
    modoDeEntrada: "Bemeneti mód",
    sensibilidade: "Bemeneti érzékenység",
    qualidade: "Minőség",
    camera: "Kamera",
    transmissao: "Közvetítés",
    exibicao: "Megjelenítés",
    entrada: "Bevitel",
    midia: "Média",
    geral: "Általános",
    preferenciaDeMencao: "Említési beállítás",
    sons: "Hangok",
  },
};
