export const conversa = {
  acenar: {
    ilustracao: "Egy integető kis kéz",
    botao: "Integess neki: {{nome}}",
  },
  oficial: {
    titulo: "Ez a csatorna csak hivatalos híreknek van.",
    detalhe: "Soha nem kérjük a jelszavadat, sem a fiókod tokenjét.",
    saibaMais: "Tudj meg többet",
  },
  topico: {
    abrir: "A csatorna leírásának megtekintése",
  },
  previaDoLink: {
    carregando: "Nézem, mi van a hivatkozás mögött…",
    destino: "Ide visz: {{destino}}",
  },
  reacao: {
    carregando: "Nézem, ki reagált ezzel: {{emoji}}…",
    uma: "{{nome}} reagált ezzel: {{emoji}}",
    duas: "{{primeiro}} és {{segundo}} reagált ezzel: {{emoji}}",
    varias: "{{nomes}} és még {{quantos}} reagált ezzel: {{emoji}}",
    dicaSuper: "Tartsd nyomva a szuperreakcióhoz",
  },
  recado: {
    gravar: "Hangüzenet rögzítése",
    descartar: "Felvétel eldobása",
    mandar: "Felvétel küldése",
    semSuporte: "Ez a böngésző nem rögzít hangot.",
    semMicrofone: "Nincs hozzáférés a mikrofonhoz.",
  },
  lista: {
    carregando: "Üzenetek betöltése…",
    carregandoMais: "Betöltés…",
    verMais: "Görgess felfelé, ha többet szeretnél látni",
    semHistorico: "Az előzmények nem érhetők el",
    semHistoricoDetalhe: "A rangodnak nincs jogosultsága olvasni a(z) #{{canal}} előzményeit. Az új üzenetek továbbra is megjelennek, amíg itt vagy.",
    boasVindas: "Üdv a(z) #{{canal}} csatornán",
    boasVindasDetalhe: "Itt kezdődik a(z) #{{canal}} csatorna.",
  },
  data: {
    hoje: "Ma",
    ontem: "Tegnap",
    hojeAs: "ma {{hora}}",
    ontemAs: "tegnap {{hora}}",
  },
  digitando: {
    um: "{{nome}} éppen ír…",
    dois: "{{primeiro}} és {{segundo}} éppen ír…",
    varios: "{{quantidade}} ember éppen ír…",
  },
  mensagem: {
    usou: "használta:",
    fixada: "kitűzve",
    editado: "(szerkesztve)",
    ignorada: "Üzenet valakitől, akit figyelmen kívül hagysz.",
    mostrar: "Mutasd",
    escPara: "Esc a",
    cancelar: "megszakításhoz",
    enterParaSalvar: "Enter a mentéshez",
    naoLidasDaqui: "Innentől olvasatlan.",
    linkCopiado: "A hivatkozás másolva.",
    idCopiado: "Az azonosító másolva.",
    naoDeuParaCopiar: "A böngésződ nem engedte a másolást.",
    apagarTitulo: "Törlöd az üzenetet?",
    apagarDescricao: "Eltűnik mindenki elől a csatornán. Nem lehet visszaállítani.",
    apagarAcao: "Törlés",
    citacaoAnexo: "kattints a melléklet megtekintéséhez",
    citacaoSumiu: "Az eredeti üzenet már nincs itt.",
    encaminhadaDe: "Továbbítva innen:",
    irParaOriginal: "Ugrás az eredetire",
    bloqueadas: "{{quantas}} blokkolt üzenet",
    mostrarBloqueadas: "Mutat",
    esconderBloqueadas: "Elrejt",
    reagirCom: "Reagálj ezzel: {{emoji}} — tartsd nyomva a szuperreakcióhoz",
    segureParaSuper: "{{emoji}} — tartsd nyomva a szuperreakcióhoz",
  },
  imagem: {
    copiarImagem: "Kép másolása",
    baixarImagem: "Kép letöltése",
    copiarLinkDaImagem: "Kép hivatkozásának másolása",
    abrirLinkDaImagem: "Kép hivatkozásának megnyitása",
    maisAcoes: "További médiaműveletek",
    pesquisarImagem: "Kép keresése",
    copiarIdDoAnexo: "Melléklet azonosítójának másolása",
    girarEsquerda: "Forgatás balra",
    girarDireita: "Forgatás jobbra",
    ajustar: "Igazítás a képernyőhöz",
    ampliar: "Nagyítás",
    reduzir: "Kicsinyítés",
    imagemCopiada: "Kép másolva.",
    linkCopiado: "Hivatkozás másolva.",
    idCopiado: "Azonosító másolva.",
    naoDeuParaCopiar: "A képet nem sikerült másolni.",
  },

  acoes: {
    reagir: "Reagálás",
    responder: "Válasz",
    encaminhar: "Továbbítás",
    favoritar: "Üzenet mentése",
    tirarDosFavoritos: "Eltávolítás a mentettekből",
    marcarNaoLida: "Megjelölés olvasatlanként",
    copiarLink: "Az üzenet hivatkozásának másolása",
    copiarId: "Az üzenet azonosítójának másolása",
    fixar: "Üzenet kitűzése",
    desafixar: "Kitűzés visszavonása",
    editar: "Szerkesztés",
    apagar: "Törlés",
    mais: "Több",
    adicionarReacao: "Reakció hozzáadása",
    superReagirCom: "Szuperreakció ezzel: {{emoji}}",
    fixarMensagem: "Üzenet kitűzése",
    desafixarMensagem: "Üzenet kitűzésének visszavonása",
    editarMensagem: "Üzenet szerkesztése",
    apagarMensagem: "Üzenet törlése",
    denunciarMensagem: "Üzenet jelentése",
  },
  denuncia: {
    titulo: "Üzenet jelentése",
    descricao: "A jelentés a Gravaê csapatához kerül. Mondd el, mi történt.",
    de: "Feladó: {{nome}}",
    semTexto: "(nincs szöveg)",
    motivo: "Ok",
    detalhes: "Részletek (nem kötelező)",
    enviar: "Jelentés küldése",
    enviada: "Jelentés elküldve. Köszönjük.",
    motivos: {
      spam: "Spam vagy reklám",
      assedio: "Zaklatás vagy gyűlölet",
      conteudo: "Nem megfelelő tartalom",
      golpe: "Csalás",
      outro: "Egyéb",
    },
  },
  falha: {
    tentarDeNovo: "Újrapróbálom",
    erro: "Nem kézbesítve",
    semConexao: "Nem kézbesítve — nincs kapcsolatod",
    semAcesso: "Nem kézbesítve — ez a csatorna már nem érhető el neked",
    semPermissao: "Nem kézbesítve — ide nem írhatsz",
    castigo: "Nem kézbesítve — időkorláton vagy ezen a szerveren",
    modoLento: "Nem kézbesítve — a lassú mód még nem járt le",
    depressa: "Nem kézbesítve — túl gyorsan küldesz",
    automod: "Nem kézbesítve — az AutoMod blokkolta",
    recusada: "Nem kézbesítve — ez a beszélgetés nem fogad válaszokat",
    naoEntregue: "Nem kézbesítve — ez a személy nem fogad tőled üzenetet",
  },
  mencao: {
    cargo: "Rang említése",
    pessoa: "Említés",
    alguem: "valaki",
    cargoSemNome: "rang",
    here: "Értesíti azokat, akik elérhetők",
    everyone: "Értesíti az egész szervert",
  },
  codigo: {
    copiar: "Másolás",
    copiado: "Másolva",
    copiarAria: "A kód másolása",
    copiadoAria: "A kód másolva",
    recolher: "Összecsukás",
    expandir: "Kibontás",
    verInteiro: "Teljes fájl megtekintése",
    maisOpcoes: "További lehetőségek",
    baixar: "Letöltés",
    recolherLinhas: "Összecsukás ({{linhas}} sor)",
    expandirLinhas: "Kibontás ({{linhas}} sor)",
    mudarIdioma: "Nyelv módosítása",
    procurarIdioma: "Nyelvkód keresése…",
    nenhumIdioma: "Nincs ilyen nyelv.",
    quebrarTexto: "Sortörés",
  },
  caixa: {
    escrever: "Írj ide: #{{canal}}",
    escreverSemCanal: "Írj egy üzenetet",
    semPermissao: "Nincs jogosultságod üzenetet küldeni ebben a csatornában",
    solteParaAnexar: "Engedd el a csatoláshoz",
    longaTitulo: "Az üzeneted túl hosszú…",
    longaDescricao: "Elérted a {{limite}} karakteres korlátot. Elküldheted fájlként.",
    enviarComoArquivo: "Küldés fájlként",
    textoComoArquivo: "Szöveg küldése fájlként",
    arquivoGrandeTitulo: "A fájl túl nagy",
    arquivoGrandeDescricao: "A(z) „{{arquivo}}” túllépi a fájlonkénti {{limite}} MB-os korlátot.",
    respondendoPara: "Válasz neki:",
    vaiNotificar: "A személy értesítést kap",
    naoVaiNotificar: "A személy nem kap értesítést",
    ligado: "be",
    desligado: "ki",
    pararDeResponder: "Válasz elvetése",
    mais: "Több",
    enviarArquivo: "Fájl küldése",
    criarEnquete: "Szavazás létrehozása",
    expressoes: "Emodzsi, GIF és matricák",
    enviar: "Küldés",
    aguardandoEnvio: "Várakozás a feltöltésre",
    modoLento: "Lassú mód bekapcsolva ({{tempo}})",
    modoLentoDica: "A lassú mód {{segundos}} mp-re van állítva. Várj, mielőtt újabb üzenetet küldesz.",
  },
  anexos: {
    enviando: "Feltöltés…",
    modificar: "{{arquivo}} módosítása",
    verPrevia: "{{arquivo}} előnézete",
    excluirTitulo: "Melléklet törlése",
    excluirDescricao: "Törlöd a(z) „{{arquivo}}” fájlt? Nem vonható vissza, és eltűnik az üzenetből.",
    excluirAcao: "Melléklet törlése",
    excluirFalhou: "Nem sikerült törölni a mellékletet.",
    remover: "{{arquivo}} eltávolítása",
    ver: "{{arquivo}} megtekintése",
    mostrarSpoiler: "Spoiler megjelenítése: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Melléklet szerkesztése",
    nomeDoArquivo: "Fájlnév",
    descricao: "Az alternatív szöveg leírása",
    descricaoDica: "Írd le ezt a médiát a képernyőolvasóknak",
    marcarSpoiler: "Megjelölés spoilerként",
    cancelar: "Mégse",
    salvar: "Mentés",
  },
  cartao: {
    tocador: "Lejátszó",
    abrir: "{{destino}} megnyitása",
    tocar: "{{titulo}} lejátszása",
    video: "videó",
    verImagem: "Kép megtekintése",
  },
  enquete: {
    criar: "Szavazás készítése",
    pergunta: "Kérdés",
    exemplo: "Mit játsszunk ma?",
    respostas: "Válaszok",
    adicionarOpcao: "Válasz hozzáadása",
    removerOpcao: "Válasz eltávolítása",
    varias: "Több válasz is megengedett",
    variasDetalhe: "Enélkül az egyik válaszra adott szavazat leveszi a szavazatot az előzőről.",
    duracao: "Időtartam",
    umaHora: "1 óra",
    quatroHoras: "4 óra",
    oitoHoras: "8 óra",
    umDia: "1 nap",
    tresDias: "3 nap",
    umaSemana: "1 hét",
    ateEncerrar: "Amíg magam le nem zárom",
    titulo: "Szavazás",
    encerrada: "A szavazás lezárult",
    variasRespostas: "Szavazás — több válasz",
    umVoto: "{{quantidade}} szavazat",
    votos: "{{quantidade}} szavazat",
    umVotoNoTotal: "összesen {{quantidade}} szavazat",
    votosNoTotal: "összesen {{quantidade}} szavazat",
    encerraEm: "lezárul: {{quando}}",
    encerrarAgora: "Lezárás most",
  },
  fixadas: {
    titulo: "Kitűzött üzenetek",
    vazio: "Ebben a csatornában még nincs kitűzött üzenet.",
    desafixar: "Kitűzés visszavonása",
    anexo: "(melléklet)",
    enquete: "(szavazás)",
    dicaRotulo: "TIPP:",
    dica: "akinek megvan az „Üzenetek kezelése” jogosultsága, közvetlenül az üzenet menüjéből is kitűzhet.",
  },
  encaminhar: {
    titulo: "Üzenet továbbítása",
    paraOnde: "Hová?",
    semTexto: "(üzenet szöveg nélkül)",
    nenhumLugar: "Nincs ilyen nevű hely.",
    canais: "Csatornák",
    conversas: "Közvetlen üzenetek",
  },
  expressoes: {
    gifs: "GIF-ek",
    buscarGifs: "Keresés a Klipyn",
    figurinha: "Matrica",
    buscarFigurinha: "Találd meg a tökéletes matricát",
    buscarEmoji: "Találd meg a tökéletes emodzsit",
    buscarReacao: "Találd meg a tökéletes reakciót",
    adicionarEmoji: "Emodzsi hozzáadása",
    limparBusca: "Keresés törlése",
  },
  busca: {
    pesquisar: "Keresés",
    limpar: "Keresés törlése",
    filtros: "Keresési szűrők",
    escopo: {
      titulo: "Keresés hatóköre",
      servidor: "Jelenlegi közösség",
      canal: "Ez a beszélgetés",
      comunidades: "Minden közösség",
      dms: "Csak privát üzenetek",
      tudo: "Privát üzenetek és közösségek",
    },
    fechar: "Keresés bezárása",
    procurando: "Keresés…",
    resultado: "{{quantos}} találat",
    resultados: "{{quantos}} találat",
    nadaCom: "Semmi ezzel: {{termo}}.",
    soOsQuePodeLer: "A keresés csak azokat a csatornákat nézi, amiket olvashatsz.",
  },
  entrada: {
    semNome: "beszélgetés",
    anexo: "(melléklet)",
    titulo: "Beérkezett üzenetek",
    naoLidas: "Olvasatlan",
    salvas: "Mentett",
    mencoes: "Említések",
    fimTitulo: "A végére értél",
    fimDetalhe: "Nincs több olvasnivaló. Ha új üzenet jön, itt fog megjelenni.",
    semSalvosTitulo: "Nincs mentett elem",
    semSalvosDetalhe: "Tartsd a Shiftet, és kattints egy üzenet könyvjelzőjére, hogy megőrizd és később elolvasd.",
    tirarDosSalvos: "Kivétel a mentettekből",
    semMencoesTitulo: "Még nincs említés",
    semMencoesDetalhe: "A rád vonatkozó említések itt jelennek meg az elmúlt 7 napra.",
  },
  forum: {
    descricao: "Minden téma külön beszélgetéssé válik — jó az olyan kérdéshez, ami nem veszhet el a csevegés közepén.",
    novoAssunto: "Új téma",
    vazio: "Még nincsenek témák. Kezdd el az elsőt, és a beszélgetés az elejétől rendezett marad.",
    titulo: "Cím",
    doQueSeTrata: "Miről szól?",
    primeiraMensagem: "Első üzenet",
    conteDoCaso: "Mesélj róla",
  },
};
