export const conversa = {
  lista: {
    carregando: "Üzenetek betöltése…",
    carregandoMais: "Betöltés…",
    verMais: "Görgess felfelé, ha többet szeretnél látni",
    semHistorico: "Az előzmények nem érhetők el",
    semHistoricoDetalhe: "A rangodnak nincs jogosultsága olvasni a(z) #{{canal}} előzményeit. Az új üzenetek továbbra is megjelennek, amíg itt vagy.",
    boasVindas: "Üdv a(z) #{{canal}} csatornán",
    boasVindasDetalhe: "Itt kezdődik a(z) #{{canal}} csatorna.",
  },
  data: {
    hoje: "Ma",
    ontem: "Tegnap",
    hojeAs: "ma {{hora}}",
    ontemAs: "tegnap {{hora}}",
  },
  digitando: {
    um: "{{nome}} éppen ír…",
    dois: "{{primeiro}} és {{segundo}} éppen ír…",
    varios: "{{quantidade}} ember éppen ír…",
  },
  mensagem: {
    usou: "használta:",
    fixada: "kitűzve",
    editado: "(szerkesztve)",
    ignorada: "Üzenet valakitől, akit figyelmen kívül hagysz.",
    mostrar: "Mutasd",
    escPara: "Esc a",
    cancelar: "megszakításhoz",
    enterParaSalvar: "Enter a mentéshez",
    falhou: "Nem ment el. Próbáld újra",
    naoLidasDaqui: "Innentől olvasatlan.",
    linkCopiado: "A hivatkozás másolva.",
    idCopiado: "Az azonosító másolva.",
    naoDeuParaCopiar: "A böngésződ nem engedte a másolást.",
    apagarTitulo: "Törlöd az üzenetet?",
    apagarDescricao: "Eltűnik mindenki elől a csatornán. Nem lehet visszaállítani.",
    apagarAcao: "Törlés",
    citacaoAnexo: "kattints a melléklet megtekintéséhez",
    citacaoSumiu: "Az eredeti üzenet már nincs itt.",
    reagirCom: "Reagálj ezzel: {{emoji}} — tartsd nyomva a szuperreakcióhoz",
    segureParaSuper: "{{emoji}} — tartsd nyomva a szuperreakcióhoz",
  },
  acoes: {
    reagir: "Reagálás",
    responder: "Válasz",
    encaminhar: "Továbbítás",
    favoritar: "Üzenet mentése",
    tirarDosFavoritos: "Eltávolítás a mentettekből",
    marcarNaoLida: "Megjelölés olvasatlanként",
    copiarLink: "Az üzenet hivatkozásának másolása",
    copiarId: "Az üzenet azonosítójának másolása",
    fixar: "Üzenet kitűzése",
    desafixar: "Kitűzés visszavonása",
    editar: "Szerkesztés",
    apagar: "Törlés",
    mais: "Több",
    adicionarReacao: "Reakció hozzáadása",
    superReagirCom: "Szuperreakció ezzel: {{emoji}}",
    fixarMensagem: "Üzenet kitűzése",
    desafixarMensagem: "Üzenet kitűzésének visszavonása",
    editarMensagem: "Üzenet szerkesztése",
    apagarMensagem: "Üzenet törlése",
  },
  mencao: {
    cargo: "Rang említése",
    pessoa: "Említés",
    alguem: "valaki",
    cargoSemNome: "rang",
    here: "Értesíti azokat, akik elérhetők",
    everyone: "Értesíti az egész szervert",
  },
  codigo: {
    copiar: "Másolás",
    copiado: "Másolva",
    copiarAria: "A kód másolása",
    copiadoAria: "A kód másolva",
    recolher: "Összecsukás",
    expandir: "Kibontás",
    verInteiro: "Teljes fájl megtekintése",
    maisOpcoes: "További lehetőségek",
    baixar: "Letöltés",
    recolherLinhas: "Összecsukás ({{linhas}} sor)",
    expandirLinhas: "Kibontás ({{linhas}} sor)",
    mudarIdioma: "Nyelv módosítása",
    procurarIdioma: "Nyelvkód keresése…",
    nenhumIdioma: "Nincs ilyen nyelv.",
    quebrarTexto: "Sortörés",
  },
  caixa: {
    escrever: "Írj ide: #{{canal}}",
    escreverSemCanal: "Írj egy üzenetet",
    semPermissao: "Nincs jogosultságod üzenetet küldeni ebben a csatornában",
    solteParaAnexar: "Engedd el a csatoláshoz",
    respondendoPara: "Válasz neki:",
    vaiNotificar: "A személy értesítést kap",
    naoVaiNotificar: "A személy nem kap értesítést",
    ligado: "be",
    desligado: "ki",
    pararDeResponder: "Válasz elvetése",
    mais: "Több",
    enviarArquivo: "Fájl küldése",
    criarEnquete: "Szavazás létrehozása",
    expressoes: "Emodzsi, GIF és matricák",
    enviar: "Küldés",
    aguardandoEnvio: "Várakozás a feltöltésre",
    modoLento: "Lassú mód bekapcsolva ({{tempo}})",
    modoLentoDica: "A lassú mód {{segundos}} mp-re van állítva. Várj, mielőtt újabb üzenetet küldesz.",
  },
  anexos: {
    enviando: "Feltöltés…",
    modificar: "{{arquivo}} módosítása",
    remover: "{{arquivo}} eltávolítása",
    ver: "{{arquivo}} megtekintése",
    mostrarSpoiler: "Spoiler megjelenítése: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Melléklet szerkesztése",
    nomeDoArquivo: "Fájlnév",
    descricao: "Az alternatív szöveg leírása",
    descricaoDica: "Írd le ezt a médiát a képernyőolvasóknak",
    marcarSpoiler: "Megjelölés spoilerként",
    cancelar: "Mégse",
    salvar: "Mentés",
  },
  cartao: {
    tocador: "Lejátszó",
    abrir: "{{destino}} megnyitása",
    tocar: "{{titulo}} lejátszása",
    video: "videó",
    verImagem: "Kép megtekintése",
  },
  enquete: {
    titulo: "Szavazás",
    encerrada: "A szavazás lezárult",
    variasRespostas: "Szavazás — több válasz",
    umVoto: "{{quantidade}} szavazat",
    votos: "{{quantidade}} szavazat",
    umVotoNoTotal: "összesen {{quantidade}} szavazat",
    votosNoTotal: "összesen {{quantidade}} szavazat",
    encerraEm: "lezárul: {{quando}}",
    encerrarAgora: "Lezárás most",
  },
  fixadas: {
    titulo: "Kitűzött üzenetek",
    vazio: "Ebben a csatornában még nincs kitűzött üzenet.",
    desafixar: "Kitűzés visszavonása",
    anexo: "(melléklet)",
    enquete: "(szavazás)",
    dicaRotulo: "TIPP:",
    dica: "akinek megvan az „Üzenetek kezelése” jogosultsága, közvetlenül az üzenet menüjéből is kitűzhet.",
  },
  encaminhar: {
    titulo: "Üzenet továbbítása",
    paraOnde: "Hová?",
    semTexto: "(üzenet szöveg nélkül)",
    nenhumLugar: "Nincs ilyen nevű hely.",
    canais: "Csatornák",
    conversas: "Közvetlen üzenetek",
  },
  expressoes: {
    gifs: "GIF-ek",
    buscarGifs: "Keresés a Klipyn",
    figurinha: "Matrica",
    buscarFigurinha: "Találd meg a tökéletes matricát",
    buscarEmoji: "Találd meg a tökéletes emodzsit",
    buscarReacao: "Találd meg a tökéletes reakciót",
    adicionarEmoji: "Emodzsi hozzáadása",
    limparBusca: "Keresés törlése",
  },
  busca: {
    fechar: "Keresés bezárása",
    procurando: "Keresés…",
    resultado: "{{quantos}} találat",
    resultados: "{{quantos}} találat",
    nadaCom: "Semmi ezzel: {{termo}}.",
    soOsQuePodeLer: "A keresés csak azokat a csatornákat nézi, amiket olvashatsz.",
  },
  entrada: {
    titulo: "Beérkezett üzenetek",
    naoLidas: "Olvasatlan",
    salvas: "Mentett",
    mencoes: "Említések",
    fimTitulo: "A végére értél",
    fimDetalhe: "Nincs több olvasnivaló. Ha új üzenet jön, itt fog megjelenni.",
    semSalvosTitulo: "Nincs mentett elem",
    semSalvosDetalhe: "Tartsd a Shiftet, és kattints egy üzenet könyvjelzőjére, hogy megőrizd és később elolvasd.",
    tirarDosSalvos: "Kivétel a mentettekből",
    semMencoesTitulo: "Még nincs említés",
    semMencoesDetalhe: "A rád vonatkozó említések itt jelennek meg az elmúlt 7 napra.",
  },
  forum: {
    descricao: "Minden téma külön beszélgetéssé válik — jó az olyan kérdéshez, ami nem veszhet el a csevegés közepén.",
    novoAssunto: "Új téma",
    vazio: "Még nincsenek témák. Kezdd el az elsőt, és a beszélgetés az elejétől rendezett marad.",
    titulo: "Cím",
    doQueSeTrata: "Miről szól?",
    primeiraMensagem: "Első üzenet",
    conteDoCaso: "Mesélj róla",
  },
};
