export const perfil = {
  carregando: "Betöltés…",
  editar: "Profil szerkesztése",
  mensagem: "Üzenet",
  abrirConversa: "Beszélgetés megnyitása",
  verCompleto: "Teljes profil megtekintése",
  convidarParaServidor: "Meghívás a szerverre",
  semServidores: "Nincs szervered",
  conviteEnviado: "Meghívó elküldve neki: {{nome}}.",
  moderador: "Megnyitás moderátor nézetben",
  mais: "Több",
  ignorar: "Mellőzés",
  deixarDeIgnorar: "Mellőzés feloldása",
  copiarId: "Felhasználói azonosító másolása",
  idCopiado: "Azonosító másolva.",
  conexoes: "Kapcsolatok",
  membroDesde: "Tag ekkortól",
  sobre: "Névjegy",
  cargosTitulo: "Rangok",
  visaoGeral: "Áttekintés",
  amigosEmComum: "Közös barátok ({{quantidade}})",
  servidoresEmComum: "Közös szerverek ({{quantidade}})",
  amizade: {
    amigo: "Barát",
    pedidoEnviado: "Barátkérelem elküldve",
    respondaAbaixo: "Kérelmet küldött neked — válaszolj alább",
    adicionar: "Barát hozzáadása",
    teMandouPedido: "Barátkérelmet küldött neked",
    aceitar: "Elfogadás",
    desfazer: "Barátság megszüntetése",
    desfazerTitulo: "Eltávolítod {{nome}} felhasználót a barátaid közül?",
    desfazerDescricao: "Többé nem lesztek barátok. A privát beszélgetés megmarad az előzményekben, és később újra hozzáadhatod.",
    bloquear: "Letiltás",
    bloquearTitulo: "Letiltod {{nome}} felhasználót?",
    bloquearDescricao: "Többé nem lesztek barátok, a privát beszélgetés nem fogad több üzenetet, és nem küldhet neked újabb barátkérelmet.",
    linkCopiado: "Nem vagytok barátok — a linket kimásoltuk, hogy te küldhesd el.",
  },
  recado: {
    escrever: "Írj neki: @{{usuario}}",
    enviar: "Küldés",
    enviada: "Üzenet elküldve",
    falhou: "Nem sikerült elküldeni. Próbáld a beszélgetésből.",
  },
  cartao: {
    trocarFaixa: "Kártya fejlécképének cseréje",
    trocarFaixaCurto: "Fejléckép cseréje",
    trocarFoto: "Profilkép cseréje",
    trocarFotoCurto: "Kép cseréje",
    suaEtiqueta: "A címkéd",
    editarEtiqueta: "Kattints a címkéd szerkesztéséhez",
    conteAlgo: "Mesélj magadról valamit",
    adicionarStatus: "Állapot hozzáadása",
    adicionarDescricao: "Kattints a leírás hozzáadásához",
    cargo: "Rang",
    cargos: "Rangok",
    cargosCom: "Rangok — {{quantidade}}",
    tirarCargo: "{{cargo}} rang levétele",
  },
  cargos: {
    adicionar: "Rang hozzáadása",
    procurar: "Rang keresése",
  },
  etiqueta: {
    escolher: "Szervercímke választása",
    nenhuma: "Nincs szervercímke",
    semEtiqueta: "Egyik szerverednek sincs címkéje",
  },
  emblemas: {
    doServidor: "Ennek a szervernek a jelvényei",
    limite: "Legfeljebb {{quantidade}} jelvényt viselhetsz.",
  },
  nota: {
    vazia: "Kattints, ha fel akarsz jegyezni valamit",
    rotulo: "Jegyzet (csak te látod)",
    adicionar: "Jegyzet hozzáadása (csak te látod)",
  },
  status: {
    titulo: "Állapot",
    definir: "Állítsd be az állapotod",
    escolherEmoji: "Emodzsi választása",
    tirarEmoji: "Emodzsi eltávolítása",
    oQuePensa: "Mire gondolsz?",
    limparAgora: "Állapot törlése most",
    naoLimpar: "Ne törölje",
    limpar30m: "Törlés 30 perc múlva",
    limpar1h: "Törlés 1 óra múlva",
    limpar4h: "Törlés 4 óra múlva",
    limparHoje: "Törlés ma",
    limparAmanha: "Törlés holnap",
    comHora: "{{prazo}} — {{hora}}",
  },
  presenca: {
    disponivel: "Elérhető",
    ausente: "Távol",
    naoPerturbar: "Ne zavarjanak",
    naoPerturbarDetalhe: "Nem kapsz értesítést új üzenetről",
    invisivel: "Láthatatlan",
    invisivelDetalhe: "Másoknak offline-nak látszol",
  },
  menu: {
    mudarDeConta: "Fiókváltás",
    gerenciarContas: "Fiókok kezelése",
  },
  editor: {
    decoracao: "Avatárdísz cseréje",
    naoSalvo: "Ne felejtsd el menteni a módosításaidat!",
    principal: "Fő profil",
  },
};
