export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Szerverbeállítások",
  auditoria: {
    todasAsAcoes: "Minden művelet",
    todosOsUsuarios: "Minden felhasználó",
    filtroMembros: "Tagok",
    filtroCanais: "Csatornák",
    filtroEmojis: "Emodzsik",
    filtroServidor: "Szerver",
    titulo: "Naplózott műveletek",
    porUsuario: "Szűrés személyre",
    porAcao: "Szűrés műveletre",
    vazio: "Ezzel a szűrővel még semmi sincs naplózva.",
    motivo: "Indok:",
  },
  banimentos: {
    titulo: "A szerver kitiltási listája",
    descricao: "Aki itt van, új meghívóval sem jut be. A kitiltás feloldása azonnal visszaadja a hozzáférést.",
    procurar: "Kitiltottak keresése felhasználónév szerint",
    vazioTitulo: "Nincs kitiltás",
    vazio: "Még senkit sem tiltottál ki… de ha egyszer kell, ne habozz.",
    desbanir: "Kitiltás feloldása",
  },
  excluir: {
    tudoVai: "A(z) {{servidor}} összes csatornája, üzenete és meghívója törlődik a(z) {{membros}} tag számára. Utána senki nem tudja visszaszerezni.",
    digite: "Írd be: {{servidor}} a megerősítéshez",
    titulo: "Szerver törlése",
    aviso: "Ez nem vonható vissza.",
  },
  emblemas: {
    apagarDescricao: "Lekerül mindenkiről, aki viseli. Ez nem vonható vissza.",
    titulo: "Jelvények",
    vazio: "Még nincsenek jelvények.",
    novo: "Új jelvény",
  },
  convites: {
    revogarTitulo: "Visszavonod a meghívót?",
    revogarAcao: "Visszavonás",
    revogarDescricao: "A(z) {{codigo}} link azonnal működésképtelen lesz. Aki már belépett vele, a szerveren marad.",
    titulo: "Meghívók",
    descricao: "A szerver összes aktív meghívólinkje.",
    vazio: "Még nem készült meghívó.",
    revogar: "Meghívó visszavonása",
  },
  integracoes: {
    opcionais: "A username és az avatar_url nem kötelező, és üzenetenként érvényes. A korlát 5 üzenet 5 másodpercenként.",
    apagarDescricao: "Az URL azonnal működésképtelen lesz. Az általa már küldött üzenetek a csatornában maradnak.",
    titulo: "Integrációk",
    descricao: "A webhook egy cím, amely fiók nélkül ír egy csatornába. Jó arra, hogy jelezze, ha egy build lement, ha valaki hibajegyet nyitott, vagy bármi másra, amit szkriptből küldenél.",
    novo: "Új webhook",
    vazio: "Még nincs webhook. Hozz létre egyet, és illeszd be az URL-t oda, ahonnan az üzenetet várod.",
    canal: "Csatorna",
    apagar: "Webhook törlése",
    comoUsar: "Használat",
    comoUsarTexto: "Küldj egy POST-ot JSON-nal:",
  },
  engajamento: {
    semCanal: "Nincs rendszercsatorna",
    titulo: "Élénkítés",
    descricao: "Amit a szerver magától tesz, hogy ne tűnjön üresnek, amikor új ember érkezik.",
    sistema: "Rendszerüzenetek",
    boasVindas: "Üdvözlő üzenet küldése, amikor valaki belép",
    sorteio: "Ha nem írsz saját szöveget alá, a mondat sorsolva lesz — ugyanaz gyorsan megunható.",
    canalDoSistema: "Rendszerüzenetek csatornája",
    mensagem: "Üdvözlő üzenet",
    deixeVazio: "Hagyd üresen, hogy a kész mondatok közül sorsoljon",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Szűrők, amelyek maguktól moderálnak, még mielőtt az üzenet létezne. Aki a szervert kezeli, sosem kerül szűrésre — a felmentett rangok pedig átmennek.",
    palavras: {
      titulo: "Saját szavak tiltása",
      descricao: "A te listád azokról a szavakról, amiket senki sem írhat le.",
    },
    mencoes: {
      titulo: "Említésözön tiltása",
      descricao: "Blokkolja az egyszerre túl sok említést tartalmazó üzenetet.",
    },
    links: {
      titulo: "Linkek tiltása",
      descricao: "Megfogja a csevegésbe beillesztett bármely címet.",
    },
    definir: "Beállítás",
    nomeDaRegra: "A szabály neve",
    bloqueadas: "Tiltott szavak",
    digiteEnter: "Írd be és nyomj Entert",
    comparacao: "Az összevetés nem nézi a kis- és nagybetűt, az ékezetet és az írásjelet — és nem fog meg egy szót egy másikon belül.",
    aPartirDe: "Hány említéstől tiltson",
    oQueFazer: "Mit tegyen",
    canalDoAlerta: "Az értesítés csatornája",
    escolhaCanal: "Válassz csatornát",
    castigo: "Némítás (perc)",
    isentos: "Felmentett rangok",
    semCargos: "Még nem készült rang.",
    salvarRegra: "Szabály mentése",
    apagar: "Szabály törlése",
    excluirTitulo: "Törlöd ezt az AutoMod-szabályt?",
    excluirDescricao: "A szerver azonnal nem szűr többé eszerint. Létrehozhatod újra, de a mostani beállítás elvész.",
    excluirAcao: "Szabály törlése",
  },
  cargos: {
    titulo: "Rangok",
    descricao: "A rangok nevet, színt és jogokat adnak. Aki feljebb van a listán, az áll a lejjebbiek felett — és senki nem nyúl a sajátjával egyenlő vagy annál magasabb ranghoz.",
    criar: "Rang létrehozása",
    vazio: "Még nincsenek rangok.",
    abaExibicao: "Megjelenés",
    abaPermissoes: "Jogosultságok",
    abaMembros: "Tagok — {{quantos}}",
    everyone: "Mindenkire vonatkozik a szerveren. Ez az alap, amire a többi rang ráépül.",
    nomeDoCargo: "A rang neve",
    cor: "A rang színe",
    corDica: "Beszínezi a rangot viselő nevét a taglistában és a csevegésben.",
    semCor: "Szín nélkül",
    corPersonalizada: "Egyedi szín",
    estilo: "A név stílusa",
    segundaCor: "Második szín",
    segundaCorDica: "Nélküle az átmenet egyszínűre vált — nem tűnik el.",
    limparSegundaCor: "Második szín törlése",
    icone: "Ikon",
    iconeDica: "A rang mellett jelenik meg annak profilkártyáján, aki viseli.",
    exibirSeparado: "Megjelenítés a többi tagtól elkülönítve",
    exibirSeparadoDica: "A rang saját szakaszt kap a taglistában.",
    permitirMencionar: "Ennek a rangnak az említése engedélyezett",
    permitirMencionarDica: "Bárki értesítheti majd mindazokat, akik a rangot viselik.",
    semPoderDeConceder: "{{descricao}} (neked nincs meg ez a jogod, hogy megadd)",
    adicionar: "Valaki hozzáadása ehhez a ranghoz",
    tirar: "Rang elvétele",
    semNinguem: "Ezt a rangot még senki nem viseli.",
    apagar: "Rang törlése",
    excluirTitulo: "Törlöd a(z) „{{nome}}\" rangot?",
    excluirDescricao: "Aki ezt a rangot viseli, elveszít mindent, amit adott. Ez nem vonható vissza.",
    excluirAcao: "Rang törlése",
  },
  membros: {
    procurar: "Keresés név vagy felhasználónév szerint",
    membroDesde: "Tag ekkortól",
    vazio: "Nem található senki.",
    acoesPara: "{{nome}} műveletei",
    deCastigo: "némítás",
    tirarCastigo: "Némítás feloldása",
    castigo5min: "5 perc",
    castigo1h: "1 óra",
    castigo1d: "1 nap",
    castigo1s: "1 hét",
    expulsar: "Kirúgás",
    expulsarTitulo: "Kirúgod {{nome}}-t?",
    expulsarDescricao: "azonnal elhagyja: {{servidor}}. Meghívóval visszajöhet — a kirúgás nem akadályozza a visszatérést.",
    banir: "Kitiltás",
    banirTitulo: "Kitiltod {{nome}}-t?",
    banirDescricao: "elhagyja: {{servidor}}, és nem jöhet vissza, meghívóval sem, amíg a kitiltás fel nem oldódik.",
    motivo: "Indok (nem kötelező)",
    motivoDica: "Bekerül a naplóba",
  },
  perfil: {
    titulo: "Szerverprofil",
    descricao: "Így jelenik meg a szervered a listában és a meghívólinkekben.",
    icone: "Ikon",
    faixa: "Felső banner",
    nomeDoServidor: "A szerver neve",
    campoDescricao: "Leírás",
    doQueE: "Miről szól ez a szerver?",
    comprimido: "Feltöltés előtt tömörítve: {{economia}}",
  },
  etiqueta: {
    titulo: "Szervercímke",
    descricao: "Legfeljebb 4 betűs címke, ami minden tag neve mellett megjelenik — a csevegésben és a személyek listájában. Itt ingyenes: boost és szint nélkül.",
    escolhaNome: "Válassz nevet",
    limite: "Legfeljebb 4 karakter, betűk és számok.",
    escolhaInsignia: "Válassz jelvényt",
    voce: "Te",
    fala1: "van kedve valakinek játszani?",
    fala2: "nézd meg a címkémet!",
    fala3: "hűha, ezt honnan szerezted",
  },
  expressoes: {
    comoUsar: "Adj hozzá legfeljebb {{limite}} emodzsit, amit bárki használhat ezen a szerveren. Írd be a csevegésbe: :név:, és elküldöd.",
    imagem: "Kép",
    enviadoPor: "Feltöltötte",
    semEmoji: "Még nincsenek emodzsik.",
    figurinhas: "Matricák",
    enviarFigurinha: "Matrica feltöltése",
    nomeDaFigurinha: "A matrica neve",
    exemploFigurinha: "Pl.: cicaölelés",
    figurinhaGrande: "A matrica túllépi ezt: {{limite}}.",
    deixaPraLa: "Hagyjuk",
    sons: "Hangpanel",
    enviarSom: "Hang feltöltése",
    nomeDoSom: "A hang neve",
    semSom: "Még nincsenek hangok.",
    somGrande: "A hang túllépi ezt: {{limite}}.",
    emojiRelacionado: "Kapcsolódó emodzsi",
    ouvir: "Meghallgatás",
    ouvirAssim: "Így hallgasd meg",
    volumeDe: "{{nome}} hangereje",
    volumeDica: "Mindenkire vonatkozik a szerveren. Mindenki továbbra is lehalkíthatja a hangokat csak magának, a hívás paneljén.",
    falhaEnvio: "A fájlt nem sikerült feltölteni.",
    excluirTitulo: "Törlöd ezt: {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Mindenkinél eltűnik a szerverről. Az üzenetek, amelyek már használták, úgy maradnak, ahogy vannak.",
  },
  canal: {
    visaoGeral: "Áttekintés",
    nome: "A csatorna neve",
    topico: "A csatorna témája",
    topicoDica: "Miről beszélnek itt?",
    modoLento: "Mindenki csak egy üzenetet küld időközönként. Aki üzeneteket vagy csatornákat kezel, akadály nélkül átmegy.",
    visibilidade: "A tartalom láthatósága",
    padrao: "Alapértelmezett",
    padraoDica: "A csatorna tartalma mindig látszik.",
    spoiler: "Spoileres csatorna",
    spoilerDica: "Jelöld a csatornát spoileresként, hogy a fordulatok és a nehéz témák rejtve maradjanak, amíg valaki rá nem néz.",
    idade: "Korhatáros csatorna",
    idadeDica: "Aki belép, meg kell erősítenie, hogy nagykorú, hogy lássa a tartalmat.",
    bitrateDica: "64 kbps fölött zavarhatja azokat, akiknek rossz a netjük.",
    qualidadeDeVideo: "Videóminőség",
    automatica: "Automatikus",
    limite: "Felhasználói korlát — {{valor}}",
    pessoas: "{{quantos}} fő",
    semLimite: "nincs korlát",
    permissoesDescricao: "Itt módosítod, mi érvényes ebben a csatornában. Ami „öröklésen” marad, az továbbra is a rangot követi.",
    excluir: {
      titulo: "Csatorna törlése",
      historico: "A(z) {{canal}} teljes előzménye vele megy, mindenkinél.",
      digite: "Írd be: {{canal}} a megerősítéshez",
    },
  },
  moderacao: {
    titulo: "Moderátori nézet",
    semPermissao: "A „Tagok moderálása” jogosultság kell hozzá, hogy ezt lásd.",
    fecharEsc: "Bezárás (Esc)",
    atividade: "Tevékenység a szerveren",
    mensagens: "Üzenetek",
    links: "Linkek",
    midia: "Média",
    acoesNaAuditoria: "Naplózott műveletek",
    moderacoesSofridas: "Kapott moderálások",
    permissoes: "Jogosultságok ({{quantas}})",
    semPermissaoEspecial: "Nincs különleges jogosultság.",
    conta: "Fiók",
    entrouNoServidor: "Belépett a szerverre",
    contaCriadaEm: "Fiók létrehozva",
    deCastigoAte: "Némítva eddig",
    formaDeAdesao: "Hogyan lépett be",
    mensagem: "Üzenet",
    castigo: "Némítás",
    copiarId: "Azonosító másolása",
    idCopiado: "Azonosító másolva.",
    adicionarCargo: "Rang hozzáadása",
    semCargos: "Nincs létrehozott rang",
    soEveryone: "Csak @everyone.",
    voltar: "Vissza",
    vazio: "Itt nincs semmi.",
    cinquenta: "Az 50 legfrissebbet mutatom.",
    irParaMensagem: "Ugrás az üzenethez",
    precisaSerAmigo: "Barátoknak kell lennetek ahhoz, hogy beszélgessetek.",
    expulsarDescricao: "Azonnal elhagyja a szervert, de meghívóval visszajöhet.",
    banirDescricao: "Elhagyja a szervert, és meghívóval sem jöhet vissza, amíg a kitiltás fel nem oldódik.",
    castigarTitulo: "Elnémítod {{nome}}-t?",
    castigoDescricao: "Amíg tart, egyetlen csatornán sem ír és nem beszél a szerveren.",
    aplicarCastigo: "Némítás alkalmazása",
    duracao: "Időtartam percben",
    informeDuracao: "Add meg az időtartamot percben.",
  },
  abas: {
    expressoes: "Kifejezések",
    pessoas: "Emberek",
    apps: "Alkalmazások",
    moderacao: "Moderálás",
    banimentos: "Kitiltások",
  },
};
