export const servidor = {
  comunidade: {
    ativa: "A közösség nyitva van",
    ativaDesde: "Nyitva {{quando}} óta",
    membrosAgora: "{{quantos}} tag",
    criarParaMim: "Készíts nekem egyet",
    canalDeRegras: "Szabályzatcsatorna",
    canalDeRegrasDetalhe: "Itt vannak a szabályok, amiket mindenki elolvas, mielőtt megszólal.",
    canalDeAvisos: "A közösség hírcsatornája",
    canalDeAvisosDetalhe: "Ide küldjük, ami itt változik — csak azoknak, akik gazdálkodnak.",
    canalDeSeguranca: "Biztonsági riasztások csatornája",
    canalDeSegurancaDetalhe: "Ide kapja meg a moderálás, amit a szűrők elkaptak.",
    idiomaPrincipal: "Fő nyelv",
    idiomaPrincipalDetalhe: "Az a nyelv, amin a beszélgetés java folyik.",
    semIdioma: "Nincs kiválasztott nyelv",
    semCanal: "Nincs csatorna",
    finalTitulo: "Mindjárt kész",
    finalDetalhe: "Nyitás előtt nézd meg, mi változik az érkezőknek.",
    confereRegras: "Aki belép, először a szabályzatcsatornát látja.",
    confereEveryone: "Az @everyone és @here csak rangot viselőknek marad.",
    confereMencoes: "Mindenki egyszerre való megjelöléséhez ezután engedély kell.",
    concordo: "Egyetértek és értem",
    concordoDetalhe: "Megerősíted, hogy a közösség tartja magát az irányelveinkhez.",
    proximo: "Tovább",
    terminar: "Beállítás befejezése",
    visaoGeral: "Áttekintés",
    visaoGeralDetalhe: "A csatornák, amelyeken a közösség az érkezőkkel beszél.",
    seguranca: "Biztonság",
    segurancaDetalhe: "A fékek, amelyek visszatartják a kéretlen és a nehéz tartalmat.",
    habilitada: "A közösség bekapcsolva.",
    falhou: "A közösséget nem sikerült bekapcsolni.",
    titulo: "Közösség",
    ilustracao: "Szövegbuborékok",
    convite: "Közösséget építesz?",
    conviteDetalhe: "Alakítsd közösséggé, és megkapod egy nagy hely eszközeit: szabályzatcsatorna, tőlünk jövő hírek és maguktól moderáló szűrők.",
    contagem: "{{membros}} / {{minimo}} tag",
    faltam: "Még {{quantos}} kell a nyitáshoz.",
    prontoParaAbrir: "Már meg lehet nyitni.",
    habilitar: "Közösség bekapcsolása",
    vantagemCrescer: "Növekedés",
    vantagemCrescerDetalhe: "A közösség jelentkezhet a Felfedezésbe, így megtalálnak azok, akik a témát keresik.",
    vantagemModerar: "Moderálás",
    vantagemModerarDetalhe: "Ellenőrzött e-mail kérése, médiaszűrés és AutoMod, egy mozdulattal.",
    vantagemAvisos: "Naprakészség",
    vantagemAvisosDetalhe: "A változásokat elküldjük azoknak, akik itt gazdálkodnak — egy csak nektek szóló csatornába.",
    assistenteTitulo: "Állítsuk be a közösségedet.",
    passoSeguranca: "Biztonsági ellenőrzések",
    passoBasico: "Alapbeállítás",
    passoFinal: "Utolsó simítások",
    seguraTitulo: "Tartsd biztonságban a közösséget",
    seguraDetalhe: "A nagy közösség vonzza a kéretlen tartalmat. Ez a két fék alapból be van kapcsolva, később kikapcsolhatod.",
    emailVerificado: "Ellenőrzött e-mail kérése",
    emailVerificadoDetalhe: "Aki még nem erősítette meg az e-mailjét, nem ír. Akinek rangja van, átmegy.",
    filtroDeMidia: "Explicit média szűrése",
    filtroDeMidiaDetalhe: "A képek és videók elrejtve érkeznek, és csak akkor látszanak, ha valaki rájuk kattint.",
    basicoTitulo: "Készítsd elő az alapokat",
    basicoDetalhe: "Mondd meg, melyik csatornán vannak a szabályok, és hová menjenek a híreink. Ha nem választasz, mindkettőt létrehozom.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} parancs",
    previa: "Így néz ki a kártya",
    trocarIcone: "Ikon cseréje",
    tirarCapa: "Borítókép eltávolítása",
    heroComunidades: "Valahol épp arról beszélnek, amit szeretsz",
    heroComunidadesDetalhe: "Közösségek, amiket az itteniek nyitottak. Lépj be, olvasd, miről van szó, és maradj, ha bejön.",
    emDestaque: "Kiemelt",
    todasAsComunidades: "A többi",
    heroTitulo: "Mit vet be ma a társaságod?",
    heroDetalhe: "Botok zenéhez, játékhoz és moderáláshoz, olyan emberektől, akik szintén itt vannak. Válassz egyet, és besétál a szerveredre.",
    novidades: "Most érkeztek",
    todosOsApps: "A többi",
    lojaTitulo: "Az alkalmazás oldala",
    lojaDetalhe: "Ezt látja a Felfedezésben az, aki még nem ismeri.",
    capa: "Borítókép",
    capaDetalhe: "A széles kép az oldal tetején. Az 1280 × 720 jól áll neki.",
    trocarCapa: "Borítókép cseréje",
    categorias: "Kategóriák",
    categoriasDetalhe: "Legfeljebb {{quantas}}. Ezek mentén böngésznek a Felfedezésben.",
    idiomas: "Nyelvek",
    idiomasDetalhe: "Legfeljebb {{quantos}}. Milyen nyelveken válaszol az alkalmazás.",
    termos: "Felhasználási feltételek",
    politica: "Adatvédelmi tájékoztató",
    politicas: "Szabályzatok",
    servidorDeSuporte: "Támogatói szerver",
    servidorDeSuporteDetalhe: "Ide kerül, akinek segítség kell az alkalmazáshoz.",
    semServidor: "Egyik sem",
    emQuantosServidores: "Hány szerveren",
    categoria: {
      GAMES: "Játékok",
      MUSICA: "Zene",
      MODERACAO: "Moderálás",
      PRODUTIVIDADE: "Termelékenység",
      SOCIAL: "Közösségi",
      UTILIDADES: "Eszközök",
      ARTE_E_CRIACAO: "Művészet és alkotás",
      EDUCACAO: "Tanulás",
      OUTRA: "Egyéb",
    },
    appIndisponivel: "Az alkalmazás nem érhető el",
    voltarParaExplorar: "Vissza a Felfedezéshez",
    adicionarApp: "Alkalmazás hozzáadása",
    copiarLink: "Hivatkozás másolása",
    denunciarApp: "Alkalmazás jelentése",
    copiarIdDoApp: "Az alkalmazás azonosítójának másolása",
    visaoGeral: "Áttekintés",
    comandos: "Parancsok",
    permissoes: "Jogosultságok",
    semPermissoes: "Ez az alkalmazás semmilyen jogosultságot nem kér.",
    avisoDePermissoes: "Saját ranggal érkezik. A jogosultságokat utána a Közösség beállításai → Rangok alatt módosíthatod.",
    servidoresEmComum: "Közös közösségek",
    umServidorEmComum: "1 közösség",
    quantosServidoresEmComum: "{{quantos}} közösség",
    feitoPor: "Készítette",
    publicadoEm: "Közzétéve",
    denunciarNome: "{{nome}} jelentése",
    denunciaDetalhe: "A jelentés a Gravaê csapatához megy. Az alkalmazás készítője nem tudja meg, hogy te voltál.",
    denunciaFalhou: "A jelentést nem sikerült elküldeni.",
    umMembro: "1 tag",
    semDescricao: "Nincs leírás.",
    adicionar: "Hozzáadás",
    jaEstaAqui: "Már itt vagy",
    entrando: "Belépés…",
    entrar: "Belépés",
    comunidadePublica: "Nyilvános közösség",
    online: "{{quantos}} online",
    membros: "{{quantos}} tag",
    abrirComunidade: "Közösség megnyitása",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Szerverbeállítások",
  novasMensagens: "Új üzenetek",
  menu: {
    silenciar: "Közösség némítása",
    reativar: "Közösség némításának feloldása",
    porQuinze: "15 percre",
    porMeiaHora: "30 percre",
    porTresHoras: "3 órára",
    porTresDias: "3 napra",
    porUmaHora: "1 órára",
    porOitoHoras: "8 órára",
    porUmDia: "24 órára",
    ateReativar: "Amíg vissza nem kapcsolom",
    notificacoes: "Értesítési beállítások",
    padrao: "Alapértelmezett",
    todas: "Minden üzenet",
    soMencoes: "Csak említések",
    nada: "Semmi",
    ocultarSilenciados: "Némított csatornák elrejtése",
    denunciar: "Közösség jelentése",
    marcarLida: "Megjelölés olvasottként",
    convidar: "Tagok meghívása",
    editarPerfil: "Közösségi profil szerkesztése",
    configuracoes: "Közösség beállításai",
    sair: "Kilépés a közösségből",
    sairTitulo: "Kilépsz innen: {{nome}}?",
    sairDescricao: "A visszatéréshez új meghívó kell.",
    copiarId: "Közösség azonosítójának másolása",
    idCopiado: "Azonosító kimásolva.",
  },
  convite: {
    cartaoTitulo: "Meghívtak egy közösségbe",
    indisponivel: "A meghívó nem érhető el",
    indisponivelDetalhe: "Lejárt, elfogyott, vagy aki készítette, törölte.",
    entrar: "Belépés a közösségbe",
    chamado: "Meghívást kaptál ide:",
    aceitarComo: "Elfogadás mint {{nome}}",
    abrir: "Közösség megnyitása",
    recusar: "Nem, köszönöm",
  },
  pasta: {
    silenciarTodas: "Közösségek némítása",
    reativarTodas: "Közösségek némításának feloldása",
    mostrarSilenciados: "Némított csatornák mutatása",
    notificacoesDaComunidade: "Értesítési beállítások",
    silenciarEveryone: "@everyone és @here némítása",
    permitirEveryone: "@everyone és @here engedélyezése",
    silenciarCargos: "Rangemlítések némítása",
    permitirCargos: "Rangemlítések engedélyezése",
    dicaDaCor: "Írj egy színt (hex, rgb(), hsl() vagy név), vagy használd a választót.",
    mostrarIcone: "Ikon mutatása csukva",
    dicaDoIcone: "Csukva az ikont mutatja a szerverek helyett.",
    icone: "Mappa ikonja",
    excluir: "Mappa törlése",
    icones: {
      pasta: "Mappa",
      estrela: "Kedvenc",
      coracao: "Szív",
      salvar: "Mentés",
      jogo: "Kontroller",
      escudo: "Pajzs",
      nota: "Hangjegy",
    },
    marcarLida: "Mappa megjelölése olvasottként",
    configuracoes: "Mappa beállításai",
    desfazer: "Mappa feloldása",
    titulo: "Mappa",
    nome: "Név",
    semNome: "Nincs név",
    cor: "Szín",
    semCor: "Nincs szín",
    salvar: "Mentés",
  },
  denuncia: {
    titulo: "{{nome}} jelentése",
    descricao: "A jelentés a Gravaê csapatához kerül. Mondd el, mi történt.",
    motivo: "Ok",
    detalhes: "Részletek (nem kötelező)",
    enviar: "Jelentés küldése",
    enviada: "Jelentés elküldve. Köszönjük.",
    motivos: {
      spam: "Spam vagy reklám",
      assedio: "Zaklatás vagy gyűlölet",
      conteudo: "Nem megfelelő tartalom",
      golpe: "Csalás",
      outro: "Egyéb",
    },
  },
  selos: {
    verificada: "Ellenőrzött közösség",
    detectavel: "Felfedezhető közösség",
  },
  auditoria: {
    todasAsAcoes: "Minden művelet",
    todosOsUsuarios: "Minden felhasználó",
    filtroMembros: "Tagok",
    filtroCanais: "Csatornák",
    filtroEmojis: "Emodzsik",
    filtroServidor: "Szerver",
    titulo: "Naplózott műveletek",
    porUsuario: "Szűrés személyre",
    porAcao: "Szűrés műveletre",
    vazio: "Ezzel a szűrővel még semmi sincs naplózva.",
    motivo: "Indok:",
  },
  banimentos: {
    titulo: "A szerver kitiltási listája",
    descricao: "Aki itt van, új meghívóval sem jut be. A kitiltás feloldása azonnal visszaadja a hozzáférést.",
    procurar: "Kitiltottak keresése felhasználónév szerint",
    vazioTitulo: "Nincs kitiltás",
    vazio: "Még senkit sem tiltottál ki… de ha egyszer kell, ne habozz.",
    desbanir: "Kitiltás feloldása",
  },
  excluir: {
    tudoVai: "A(z) {{servidor}} összes csatornája, üzenete és meghívója törlődik a(z) {{membros}} tag számára. Utána senki nem tudja visszaszerezni.",
    digite: "Írd be: {{servidor}} a megerősítéshez",
    titulo: "Szerver törlése",
    aviso: "Ez nem vonható vissza.",
  },
  emblemas: {
    apagarDescricao: "Lekerül mindenkiről, aki viseli. Ez nem vonható vissza.",
    titulo: "Jelvények",
    vazio: "Még nincsenek jelvények.",
    novo: "Új jelvény",
  },
  convites: {
    revogarTitulo: "Visszavonod a meghívót?",
    revogarAcao: "Visszavonás",
    revogarDescricao: "A(z) {{codigo}} link azonnal működésképtelen lesz. Aki már belépett vele, a szerveren marad.",
    titulo: "Meghívók",
    descricao: "A szerver összes aktív meghívólinkje.",
    vazio: "Még nem készült meghívó.",
    revogar: "Meghívó visszavonása",
  },
  integracoes: {
    opcionais: "A username és az avatar_url nem kötelező, és üzenetenként érvényes. A korlát 5 üzenet 5 másodpercenként.",
    apagarDescricao: "Az URL azonnal működésképtelen lesz. Az általa már küldött üzenetek a csatornában maradnak.",
    titulo: "Integrációk",
    descricao: "A webhook egy cím, amely fiók nélkül ír egy csatornába. Jó arra, hogy jelezze, ha egy build lement, ha valaki hibajegyet nyitott, vagy bármi másra, amit szkriptből küldenél.",
    novo: "Új webhook",
    vazio: "Még nincs webhook. Hozz létre egyet, és illeszd be az URL-t oda, ahonnan az üzenetet várod.",
    canal: "Csatorna",
    apagar: "Webhook törlése",
    comoUsar: "Használat",
    comoUsarTexto: "Küldj egy POST-ot JSON-nal:",
  },
  explorar: {
    titulo: "Felfedezés",
  },
  engajamento: {
    semCanal: "Nincs rendszercsatorna",
    titulo: "Élénkítés",
    descricao: "Amit a szerver magától tesz, hogy ne tűnjön üresnek, amikor új ember érkezik.",
    sistema: "Rendszerüzenetek",
    boasVindas: "Üdvözlő üzenet küldése, amikor valaki belép",
    sorteio: "Ha nem írsz saját szöveget alá, a mondat sorsolva lesz — ugyanaz gyorsan megunható.",
    canalDoSistema: "Rendszerüzenetek csatornája",
    mensagem: "Üdvözlő üzenet",
    deixeVazio: "Hagyd üresen, hogy a kész mondatok közül sorsoljon",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Szűrők, amelyek maguktól moderálnak, még mielőtt az üzenet létezne. Aki a szervert kezeli, sosem kerül szűrésre — a felmentett rangok pedig átmennek.",
    palavras: {
      titulo: "Saját szavak tiltása",
      descricao: "A te listád azokról a szavakról, amiket senki sem írhat le.",
    },
    mencoes: {
      titulo: "Említésözön tiltása",
      descricao: "Blokkolja az egyszerre túl sok említést tartalmazó üzenetet.",
    },
    links: {
      titulo: "Linkek tiltása",
      descricao: "Megfogja a csevegésbe beillesztett bármely címet.",
    },
    definir: "Beállítás",
    nomeDaRegra: "A szabály neve",
    bloqueadas: "Tiltott szavak",
    digiteEnter: "Írd be és nyomj Entert",
    comparacao: "Az összevetés nem nézi a kis- és nagybetűt, az ékezetet és az írásjelet — és nem fog meg egy szót egy másikon belül.",
    aPartirDe: "Hány említéstől tiltson",
    oQueFazer: "Mit tegyen",
    canalDoAlerta: "Az értesítés csatornája",
    escolhaCanal: "Válassz csatornát",
    castigo: "Némítás (perc)",
    isentos: "Felmentett rangok",
    semCargos: "Még nem készült rang.",
    salvarRegra: "Szabály mentése",
    apagar: "Szabály törlése",
    excluirTitulo: "Törlöd ezt az AutoMod-szabályt?",
    excluirDescricao: "A szerver azonnal nem szűr többé eszerint. Létrehozhatod újra, de a mostani beállítás elvész.",
    excluirAcao: "Szabály törlése",
  },
  cargos: {
    titulo: "Rangok",
    descricao: "A rangok nevet, színt és jogokat adnak. Aki feljebb van a listán, az áll a lejjebbiek felett — és senki nem nyúl a sajátjával egyenlő vagy annál magasabb ranghoz.",
    criar: "Rang létrehozása",
    vazio: "Még nincsenek rangok.",
    abaExibicao: "Megjelenés",
    abaPermissoes: "Jogosultságok",
    abaMembros: "Tagok — {{quantos}}",
    everyone: "Mindenkire vonatkozik a szerveren. Ez az alap, amire a többi rang ráépül.",
    nomeDoCargo: "A rang neve",
    cor: "A rang színe",
    corDica: "Beszínezi a rangot viselő nevét a taglistában és a csevegésben.",
    semCor: "Szín nélkül",
    corPersonalizada: "Egyedi szín",
    estilo: "A név stílusa",
    segundaCor: "Második szín",
    segundaCorDica: "Nélküle az átmenet egyszínűre vált — nem tűnik el.",
    limparSegundaCor: "Második szín törlése",
    icone: "Ikon",
    iconeDica: "A rang mellett jelenik meg annak profilkártyáján, aki viseli.",
    exibirSeparado: "Megjelenítés a többi tagtól elkülönítve",
    exibirSeparadoDica: "A rang saját szakaszt kap a taglistában.",
    permitirMencionar: "Ennek a rangnak az említése engedélyezett",
    permitirMencionarDica: "Bárki értesítheti majd mindazokat, akik a rangot viselik.",
    semPoderDeConceder: "{{descricao}} (neked nincs meg ez a jogod, hogy megadd)",
    adicionar: "Valaki hozzáadása ehhez a ranghoz",
    tirar: "Rang elvétele",
    semNinguem: "Ezt a rangot még senki nem viseli.",
    apagar: "Rang törlése",
    excluirTitulo: "Törlöd a(z) „{{nome}}\" rangot?",
    excluirDescricao: "Aki ezt a rangot viseli, elveszít mindent, amit adott. Ez nem vonható vissza.",
    excluirAcao: "Rang törlése",
  },
  membros: {
    procurar: "Keresés név vagy felhasználónév szerint",
    membroDesde: "Tag ekkortól",
    vazio: "Nem található senki.",
    acoesPara: "{{nome}} műveletei",
    deCastigo: "némítás",
    tirarCastigo: "Némítás feloldása",
    castigo5min: "5 perc",
    castigo1h: "1 óra",
    castigo1d: "1 nap",
    castigo1s: "1 hét",
    expulsar: "Kirúgás",
    expulsarTitulo: "Kirúgod {{nome}}-t?",
    expulsarDescricao: "azonnal elhagyja: {{servidor}}. Meghívóval visszajöhet — a kirúgás nem akadályozza a visszatérést.",
    banir: "Kitiltás",
    banirTitulo: "Kitiltod {{nome}}-t?",
    banirDescricao: "elhagyja: {{servidor}}, és nem jöhet vissza, meghívóval sem, amíg a kitiltás fel nem oldódik.",
    motivo: "Indok (nem kötelező)",
    motivoDica: "Bekerül a naplóba",
  },
  perfil: {
    titulo: "Szerverprofil",
    descricao: "Így jelenik meg a szervered a listában és a meghívólinkekben.",
    icone: "Ikon",
    faixa: "Felső banner",
    nomeDoServidor: "A szerver neve",
    campoDescricao: "Leírás",
    doQueE: "Miről szól ez a szerver?",
    comprimido: "Feltöltés előtt tömörítve: {{economia}}",
  },
  etiqueta: {
    titulo: "Szervercímke",
    descricao: "Legfeljebb 4 betűs címke, ami minden tag neve mellett megjelenik — a csevegésben és a személyek listájában. Itt ingyenes: boost és szint nélkül.",
    escolhaNome: "Válassz nevet",
    limite: "Legfeljebb 4 karakter, betűk és számok.",
    escolhaInsignia: "Válassz jelvényt",
    voce: "Te",
    fala1: "van kedve valakinek játszani?",
    fala2: "nézd meg a címkémet!",
    fala3: "hűha, ezt honnan szerezted",
  },
  expressoes: {
    comoUsar: "Adj hozzá legfeljebb {{limite}} emodzsit, amit bárki használhat ezen a szerveren. Írd be a csevegésbe: :név:, és elküldöd.",
    imagem: "Kép",
    enviadoPor: "Feltöltötte",
    semEmoji: "Még nincsenek emodzsik.",
    figurinhas: "Matricák",
    enviarFigurinha: "Matrica feltöltése",
    nomeDaFigurinha: "A matrica neve",
    exemploFigurinha: "Pl.: cicaölelés",
    figurinhaGrande: "A matrica túllépi ezt: {{limite}}.",
    deixaPraLa: "Hagyjuk",
    sons: "Hangpanel",
    enviarSom: "Hang feltöltése",
    nomeDoSom: "A hang neve",
    semSom: "Még nincsenek hangok.",
    somGrande: "A hang túllépi ezt: {{limite}}.",
    emojiRelacionado: "Kapcsolódó emodzsi",
    ouvir: "Meghallgatás",
    ouvirAssim: "Így hallgasd meg",
    volumeDe: "{{nome}} hangereje",
    volumeDica: "Mindenkire vonatkozik a szerveren. Mindenki továbbra is lehalkíthatja a hangokat csak magának, a hívás paneljén.",
    falhaEnvio: "A fájlt nem sikerült feltölteni.",
    excluirTitulo: "Törlöd ezt: {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Mindenkinél eltűnik a szerverről. Az üzenetek, amelyek már használták, úgy maradnak, ahogy vannak.",
  },
  canal: {
    tipoLink: "Hivatkozás",
    tipoLinkDica: "Kifelé mutat egy címre, és a böngészőben nyílik meg",
    endereco: "Cím",
    enderecoDica: "Hová vezet ez a csatorna. https:// előtaggal kell kezdődnie",
    visaoGeral: "Áttekintés",
    nome: "A csatorna neve",
    topico: "A csatorna témája",
    topicoDica: "Miről beszélnek itt?",
    modoLento: "Mindenki csak egy üzenetet küld időközönként. Aki üzeneteket vagy csatornákat kezel, akadály nélkül átmegy.",
    visibilidade: "A tartalom láthatósága",
    padrao: "Alapértelmezett",
    padraoDica: "A csatorna tartalma mindig látszik.",
    spoiler: "Spoileres csatorna",
    spoilerDica: "Jelöld a csatornát spoileresként, hogy a fordulatok és a nehéz témák rejtve maradjanak, amíg valaki rá nem néz.",
    idade: "Korhatáros csatorna",
    idadeDica: "Aki belép, meg kell erősítenie, hogy nagykorú, hogy lássa a tartalmat.",
    bitrateDica: "64 kbps fölött zavarhatja azokat, akiknek rossz a netjük.",
    qualidadeDeVideo: "Videóminőség",
    automatica: "Automatikus",
    limite: "Felhasználói korlát — {{valor}}",
    pessoas: "{{quantos}} fő",
    semLimite: "nincs korlát",
    permissoesDescricao: "Itt módosítod, mi érvényes ebben a csatornában. Ami „öröklésen” marad, az továbbra is a rangot követi.",
    excluir: {
      titulo: "Csatorna törlése",
      historico: "A(z) {{canal}} teljes előzménye vele megy, mindenkinél.",
      digite: "Írd be: {{canal}} a megerősítéshez",
    },
  },
  moderacao: {
    titulo: "Moderátori nézet",
    semPermissao: "A „Tagok moderálása” jogosultság kell hozzá, hogy ezt lásd.",
    fecharEsc: "Bezárás (Esc)",
    atividade: "Tevékenység a szerveren",
    mensagens: "Üzenetek",
    links: "Linkek",
    midia: "Média",
    acoesNaAuditoria: "Naplózott műveletek",
    moderacoesSofridas: "Kapott moderálások",
    permissoes: "Jogosultságok ({{quantas}})",
    semPermissaoEspecial: "Nincs különleges jogosultság.",
    conta: "Fiók",
    entrouNoServidor: "Belépett a szerverre",
    contaCriadaEm: "Fiók létrehozva",
    deCastigoAte: "Némítva eddig",
    formaDeAdesao: "Hogyan lépett be",
    mensagem: "Üzenet",
    castigo: "Némítás",
    copiarId: "Azonosító másolása",
    idCopiado: "Azonosító másolva.",
    adicionarCargo: "Rang hozzáadása",
    semCargos: "Nincs létrehozott rang",
    soEveryone: "Csak @everyone.",
    voltar: "Vissza",
    vazio: "Itt nincs semmi.",
    cinquenta: "Az 50 legfrissebbet mutatom.",
    irParaMensagem: "Ugrás az üzenethez",
    precisaSerAmigo: "Barátoknak kell lennetek ahhoz, hogy beszélgessetek.",
    expulsarDescricao: "Azonnal elhagyja a szervert, de meghívóval visszajöhet.",
    banirDescricao: "Elhagyja a szervert, és meghívóval sem jöhet vissza, amíg a kitiltás fel nem oldódik.",
    castigarTitulo: "Elnémítod {{nome}}-t?",
    castigoDescricao: "Amíg tart, egyetlen csatornán sem ír és nem beszél a szerveren.",
    aplicarCastigo: "Némítás alkalmazása",
    duracao: "Időtartam percben",
    informeDuracao: "Add meg az időtartamot percben.",
  },
  abas: {
    pesquisar: "Keresés a beállításokban",
    semResultado: "Ilyen nevű nincs itt.",
    comunidade: "Közösség",
    expressoes: "Kifejezések",
    pessoas: "Emberek",
    apps: "Alkalmazások",
    moderacao: "Moderálás",
    banimentos: "Kitiltások",
  },
};
