export const amizades = {
  ativosAgora: "Activo ahora",
  procurando: "Viendo quién anda por ahí…",
  tudoTranquilo: "Todo tranquilo por ahora…",
  tudoTranquiloDetalhe: "Cuando vos o un amigo entren a una llamada, va a aparecer acá — y podés sumarte con un clic.",
  emVoz: "En voz",
  voce: "Vos",
  soVoce: "Solo vos",
  pessoas: "{{quantas}} personas",
  voltarParaChamada: "Volver a la llamada",
  entrarNaChamada: "Unirse a la llamada",
  abrirCanal: "Abrir {{canal}} en {{servidor}}",
  mensagensDiretas: "Mensajes directos",
  encontreConversa: "Buscá una conversación",
  amigos: "Amigos",
  conversas: "Conversaciones",
  semConversas: "Todavía no hay conversaciones. Agregá un amigo para empezar.",
  semConversaComEsseNome: "Ninguna conversación con ese nombre.",
  abrirMenu: "Abrir servidores y conversaciones",
  solicitacoes: "Solicitudes de mensajes",
  pedidos: "Solicitudes",
  spam: "Spam",
  pedidosPendentes: "Solicitudes pendientes",
  marcadosComoSpam: "Marcados como spam",
  aceitar: "Aceptar",
  ignorar: "Ignorar",
  marcarSpam: "Marcar como spam",
  semPedidos: "Ninguna solicitud esperando.",
  semPedidosDetalhe: "Quien no es tu amigo pero comparte un servidor con vos llega acá antes de entrar en tus conversaciones.",
  semSpam: "Nada marcado como spam.",
  semSpamDetalhe: "Lo que el filtro de spam aparte, o lo que marques, queda guardado en esta pestaña.",
  umServidorEmComum: "1 servidor en común",
  servidoresEmComum: "{{quantos}} servidores en común",
  semServidoresEmComum: "Sin servidores en común",
};
