export const comum = {
  carregando: "Cargando…",
  salvar: "Guardar",
  salvando: "Guardando…",
  descartar: "Descartar",
  redefinir: "Restablecer",
  naoSalvo: "Tienes cambios sin guardar.",
  fechar: "Cerrar",
  criar: "Crear",
  nome: "Nombre",
  emoji: "Emoji",
  previa: "Vista previa",
  cancelar: "Cancelar",
  enviar: "Enviar",
  apagar: "Borrar",
  excluir: "Eliminar",
  remover: "Quitar",
  trocar: "Cambiar",
};
