export const configuracoes = {
  efeitos: {
    titulo: "Efectos del puntero",
    detalhe: "Rastro y chispas dibujados encima de la aplicación. Vienen apagados y se apagan solos si pediste menos animación.",
    rastro: "Rastro del cursor",
    rastroDetalhe: "Una línea que sigue al puntero y se va borrando atrás.",
    faisca: "Chispa al hacer clic",
    faiscaDetalhe: "Líneas cortas que salen del punto donde hiciste clic.",
    cor: "Color",
    espessura: "Grosor",
    comprimento: "Largo",
    tamanho: "Tamaño",
    quantidade: "Cantidad",
  },
  email: {
    verificarTitulo: "Confirmá tu correo",
    verificarDetalhe: "Algunas comunidades solo dejan escribir a quien confirmó. Es un clic.",
    enviar: "Mandar el enlace",
    enviado: "Mirá la bandeja de entrada. El enlace dura un día.",
    falhou: "No se pudo mandar el correo.",
    confirmado: "Correo confirmado",
    confirmadoDetalhe: "Listo. Ya escribís en cualquier comunidad que lo pida.",
    linkIncompleto: "Enlace incompleto",
    linkIncompletoDetalhe: "Falta el código en la dirección. Abrí el enlace directo del correo.",
    confirmando: "Confirmando…",
    expirou: "Este enlace ya se usó o venció.",
    irParaOApp: "Ir a la aplicación",
  },
  tema: {
    indisponivel: "Tema no disponible",
    indisponivelDetalhe: "Quien lo publicó lo borró, o el enlace está mal.",
    indisponivelLinha: "Tema no disponible. Quien lo publicó lo borró, o el enlace está mal.",
    importar: "Importar tema",
    importarCurto: "Importar",
    importarDetalhe: "Esto reemplaza el tema que tenés ahora. Podés editarlo después en Configuración > Apariencia > Estudio de temas.",
    porAutor: "por {{autor}}",
    umaCorTrocada: "1 color cambiado",
    coresTrocadas: "{{quantas}} colores cambiados",
    avisoDeCss: "Este tema trae CSS de quien lo escribió, y el CSS toca cualquier rincón de la pantalla. Importá solo de gente en la que confiás.",
    soCores: "Este tema solo cambia colores. Nada de CSS de afuera.",
    aplicar: "Aplicar",
    previaSemMotor: "La vista previa no corre el motor. Instalalo para verlo.",
    motorAnimado: "{{motor}} animado",
  },
  sair: "Cerrar sesión",
  versoes: {
    termos: "Términos del servicio",
    privacidade: "Política de privacidad",
    copiar: "Haz clic para copiar",
    copiado: "Copiado",
  },
  telas: {
    conta: "Mi cuenta",
    privacidade: "Privacidad",
    conexoes: "Conexiones",
    voz: "Audio",
    video: "Video",
    avisos: "Notificaciones",
    aplicativos: "Aplicaciones",
    aparencia: "Apariencia",
    batePapo: "Chat",
    acessibilidade: "Accesibilidad",
    idioma: "Idioma",
    aplicativo: "Descargar la app",
    atalhos: "Atajos",
    desktop: "App de escritorio",
    avancado: "Avanzado",
    servidor: "Servidor",
    comunicado: "Comunicado del sistema",
    denuncias: "Denuncias",
    publicacoes: "Despliegues",
  },
  grupos: {
    conta: "Cuenta",
    app: "Ajustes de la app",
    desenvolvedor: "Desarrollador",
    administracao: "Administración",
  },
  secoes: {
    detalhesDeLogin: "Datos de acceso",
    dispositivos: "Dispositivos",
    usuariosBloqueados: "Usuarios bloqueados",
    aplicativosAutorizados: "Aplicaciones autorizadas",
    sessoes: "Sesiones",
    amigosEDms: "Amigos y mensajes directos",
    compartilhamentoDeAtividade: "Compartir actividad",
    visibilidadeDoPerfil: "Visibilidad del perfil",
    exportarDados: "Exportar datos",
    exclusaoDeDados: "Eliminar datos",
    tema: "Tema",
    corDeDestaque: "Color de acento",
    interface: "Interfaz",
    listaDeCanais: "Lista de canales",
    zoomDoApp: "Nivel de zoom de la app",
    escalaDaFonte: "Escala de la fuente del chat",
    modoStreamer: "Privacidad en transmisión",
    cursores: "Cursores",
    movimento: "Movimiento",
    textoEmVoz: "Texto a voz",
    teclado: "Teclado",
    formatoDaHora: "Formato de hora",
    idiomaDaInterface: "Idioma de la interfaz",
    dispositivosDeVoz: "Dispositivos",
    testeDoMicrofone: "Prueba del micrófono",
    modoDeEntrada: "Modo de entrada",
    sensibilidade: "Sensibilidad de entrada",
    qualidade: "Calidad",
    camera: "Cámara",
    transmissao: "Transmisión",
    exibicao: "Visualización",
    entrada: "Entrada",
    midia: "Medios",
    geral: "General",
    preferenciaDeMencao: "Preferencia de mención",
    sons: "Sonidos",
  },
};
