export const conversa = {
  lista: {
    carregando: "Cargando mensajes…",
    carregandoMais: "Cargando…",
    verMais: "Desplázate hacia arriba para ver más",
    semHistorico: "Historial no disponible",
    semHistoricoDetalhe: "Tu rol no tiene permiso para leer el historial de #{{canal}}. Los mensajes nuevos van a seguir apareciendo mientras estés aquí.",
    boasVindas: "Te damos la bienvenida a #{{canal}}",
    boasVindasDetalhe: "Este es el comienzo del canal #{{canal}}.",
  },
  data: {
    hoje: "Hoy",
    ontem: "Ayer",
    hojeAs: "hoy a las {{hora}}",
    ontemAs: "ayer a las {{hora}}",
  },
  digitando: {
    um: "{{nome}} está escribiendo…",
    dois: "{{primeiro}} y {{segundo}} están escribiendo…",
    varios: "{{quantidade}} personas están escribiendo…",
  },
  mensagem: {
    usou: "usó",
    fixada: "fijado",
    editado: "(editado)",
    ignorada: "Mensaje de alguien a quien ignoras.",
    mostrar: "Mostrar",
    escPara: "Esc para",
    cancelar: "cancelar",
    enterParaSalvar: "Enter para guardar",
    falhou: "No se envió. Inténtalo de nuevo",
    naoLidasDaqui: "Sin leer desde aquí.",
    linkCopiado: "Enlace copiado.",
    idCopiado: "ID copiado.",
    naoDeuParaCopiar: "Tu navegador no dejó copiar.",
    apagarTitulo: "¿Eliminar el mensaje?",
    apagarDescricao: "Desaparece para todo el canal. No se puede recuperar.",
    apagarAcao: "Eliminar",
    citacaoAnexo: "haz clic para ver el archivo adjunto",
    citacaoSumiu: "El mensaje original ya no está aquí.",
    reagirCom: "Reaccionar con {{emoji}} — mantén presionado para súper reaccionar",
    segureParaSuper: "{{emoji}} — mantén presionado para súper reaccionar",
  },
  acoes: {
    reagir: "Reaccionar",
    responder: "Responder",
    encaminhar: "Reenviar",
    favoritar: "Guardar mensaje",
    tirarDosFavoritos: "Quitar de guardados",
    marcarNaoLida: "Marcar como no leído",
    copiarLink: "Copiar el enlace del mensaje",
    copiarId: "Copiar el ID del mensaje",
    fixar: "Fijar mensaje",
    desafixar: "Dejar de fijar",
    editar: "Editar",
    apagar: "Eliminar",
    mais: "Más",
    adicionarReacao: "Agregar reacción",
    superReagirCom: "Súper reaccionar con {{emoji}}",
    fixarMensagem: "Fijar mensaje",
    desafixarMensagem: "Dejar de fijar el mensaje",
    editarMensagem: "Editar mensaje",
    apagarMensagem: "Eliminar mensaje",
  },
  mencao: {
    cargo: "Mención de rol",
    pessoa: "Mención",
    alguem: "alguien",
    cargoSemNome: "rol",
    here: "Avisa a quien esté en línea",
    everyone: "Avisa a todo el servidor",
  },
  codigo: {
    copiar: "Copiar",
    copiado: "Copiado",
    copiarAria: "Copiar el código",
    copiadoAria: "Código copiado",
    recolher: "Contraer",
    expandir: "Expandir",
    verInteiro: "Ver el archivo completo",
    maisOpcoes: "Más opciones",
    baixar: "Descargar",
    recolherLinhas: "Contraer ({{linhas}} líneas)",
    expandirLinhas: "Expandir ({{linhas}} líneas)",
    mudarIdioma: "Cambiar idioma",
    procurarIdioma: "Buscar código de idioma…",
    nenhumIdioma: "No hay ese idioma.",
    quebrarTexto: "Ajustar texto",
  },
  caixa: {
    escrever: "Escribe en #{{canal}}",
    escreverSemCanal: "Escribe un mensaje",
    semPermissao: "No tienes permiso para enviar mensajes en este canal",
    solteParaAnexar: "Suelta para adjuntar",
    respondendoPara: "Respondiendo a",
    vaiNotificar: "Se le va a notificar",
    naoVaiNotificar: "No se le va a notificar",
    ligado: "activado",
    desligado: "desactivado",
    pararDeResponder: "Dejar de responder",
    mais: "Más",
    enviarArquivo: "Enviar un archivo",
    criarEnquete: "Crear una encuesta",
    expressoes: "Emoji, GIF y stickers",
    enviar: "Enviar",
    aguardandoEnvio: "Esperando la subida",
    modoLento: "Modo lento activo ({{tempo}})",
    modoLentoDica: "El modo lento está en {{segundos}} s. Espera antes de enviar otro mensaje.",
  },
  anexos: {
    enviando: "Subiendo…",
    modificar: "Modificar {{arquivo}}",
    remover: "Quitar {{arquivo}}",
    ver: "Ver {{arquivo}}",
    mostrarSpoiler: "Mostrar spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Editar el archivo adjunto",
    nomeDoArquivo: "Nombre del archivo",
    descricao: "Descripción del texto alternativo",
    descricaoDica: "Describe este contenido para los lectores de pantalla",
    marcarSpoiler: "Marcar como spoiler",
    cancelar: "Cancelar",
    salvar: "Guardar",
  },
  cartao: {
    tocador: "Reproductor",
    abrir: "Abrir {{destino}}",
    tocar: "Reproducir {{titulo}}",
    video: "video",
    verImagem: "Ver la imagen",
  },
  enquete: {
    titulo: "Encuesta",
    encerrada: "Encuesta cerrada",
    variasRespostas: "Encuesta — varias respuestas",
    umVoto: "{{quantidade}} voto",
    votos: "{{quantidade}} votos",
    umVotoNoTotal: "{{quantidade}} voto en total",
    votosNoTotal: "{{quantidade}} votos en total",
    encerraEm: "cierra el {{quando}}",
    encerrarAgora: "Cerrar ahora",
  },
  fixadas: {
    titulo: "Mensajes fijados",
    vazio: "Este canal no tiene mensajes fijados… todavía.",
    desafixar: "Dejar de fijar",
    anexo: "(archivo adjunto)",
    enquete: "(encuesta)",
    dicaRotulo: "UN CONSEJO:",
    dica: "quien tenga el permiso «Administrar mensajes» puede fijar directamente desde el menú del mensaje.",
  },
  encaminhar: {
    titulo: "Reenviar el mensaje",
    paraOnde: "¿A dónde?",
    semTexto: "(mensaje sin texto)",
    nenhumLugar: "Ningún lugar con ese nombre.",
    canais: "Canales",
    conversas: "Mensajes directos",
  },
  expressoes: {
    gifs: "GIFs",
    buscarGifs: "Buscar en Klipy",
    figurinha: "Sticker",
    buscarFigurinha: "Encontrá el sticker perfecto",
    buscarEmoji: "Encontrá el emoji perfecto",
    buscarReacao: "Encontrá la reacción perfecta",
    adicionarEmoji: "Agregar emoji",
    limparBusca: "Limpiar la búsqueda",
  },
  busca: {
    fechar: "Cerrar la búsqueda",
    procurando: "Buscando…",
    resultado: "{{quantos}} resultado",
    resultados: "{{quantos}} resultados",
    nadaCom: "Nada con {{termo}} por acá.",
    soOsQuePodeLer: "La búsqueda solo mira los canales que podés leer.",
  },
  entrada: {
    titulo: "Bandeja de entrada",
    naoLidas: "Sin leer",
    salvas: "Guardadas",
    mencoes: "Menciones",
    fimTitulo: "Llegaste al final",
    fimDetalhe: "No queda nada por leer. Cuando llegue un mensaje nuevo, aparece acá.",
    semSalvosTitulo: "Ningún elemento guardado",
    semSalvosDetalhe: "Mantené Shift y hacé clic en el marcador de un mensaje para guardarlo y verlo después.",
    tirarDosSalvos: "Quitar de guardados",
    semMencoesTitulo: "Ninguna mención todavía",
    semMencoesDetalhe: "Las menciones a vos aparecen acá durante los últimos 7 días.",
  },
  forum: {
    descricao: "Cada tema se vuelve una conversación aparte — bueno para la duda que no puede perderse en medio de la charla.",
    novoAssunto: "Tema nuevo",
    vazio: "Todavía no hay temas. Empezá el primero y la conversación queda ordenada desde el principio.",
    titulo: "Título",
    doQueSeTrata: "¿De qué se trata?",
    primeiraMensagem: "Primer mensaje",
    conteDoCaso: "Contanos",
  },
};
