export const servidor = {
  comunidade: {
    ativa: "La comunidad está abierta",
    ativaDesde: "Abierta desde {{quando}}",
    membrosAgora: "{{quantos}} miembros",
    criarParaMim: "Creá uno por mí",
    canalDeRegras: "Canal de reglas",
    canalDeRegrasDetalhe: "Donde están las reglas que todos leen antes de hablar.",
    canalDeAvisos: "Canal de avisos de la comunidad",
    canalDeAvisosDetalhe: "Adonde mandamos lo que cambia acá, solo para quienes administran.",
    canalDeSeguranca: "Canal de alertas de seguridad",
    canalDeSegurancaDetalhe: "Donde la moderación recibe lo que agarraron los filtros.",
    idiomaPrincipal: "Idioma principal",
    idiomaPrincipalDetalhe: "El idioma en el que pasa la mayor parte de la charla.",
    semIdioma: "Ningún idioma elegido",
    semCanal: "Ningún canal",
    finalTitulo: "Ya casi",
    finalDetalhe: "Antes de abrir, mirá qué cambia para quien llega.",
    confereRegras: "Quien entra ve el canal de reglas antes que nada.",
    confereEveryone: "Solo quien tiene rol usa @everyone y @here.",
    confereMencoes: "Mencionar a todos de una pasa a pedir permiso.",
    concordo: "Estoy de acuerdo y entiendo",
    concordoDetalhe: "Confirmás que la comunidad cumple nuestras pautas.",
    proximo: "Siguiente",
    terminar: "Terminar la configuración",
    visaoGeral: "Vista general",
    visaoGeralDetalhe: "Los canales con los que la comunidad le habla a quien llega.",
    seguranca: "Seguridad",
    segurancaDetalhe: "Los frenos que aguantan el spam y el contenido pesado.",
    habilitada: "Comunidad habilitada.",
    falhou: "No se pudo habilitar la comunidad.",
    titulo: "Comunidad",
    ilustracao: "Globos de diálogo",
    convite: "¿Estás armando una comunidad?",
    conviteDetalhe: "Convertilo en comunidad para tener las herramientas de un lugar grande: canal de reglas, avisos nuestros y filtros que moderan solos.",
    contagem: "{{membros}} de {{minimo}} miembros",
    faltam: "Faltan {{quantos}} para abrir.",
    prontoParaAbrir: "Ya se puede abrir.",
    habilitar: "Habilitar comunidad",
    vantagemCrescer: "Crecer",
    vantagemCrescerDetalhe: "La comunidad puede postularse a Explorar, y quien busca el tema te encuentra.",
    vantagemModerar: "Moderar",
    vantagemModerarDetalhe: "Pedir correo verificado, filtrar medios y prender el AutoMod de una.",
    vantagemAvisos: "Estar al tanto",
    vantagemAvisosDetalhe: "Mandamos lo que cambia a quienes administran, en un canal solo de ustedes.",
    assistenteTitulo: "Vamos a armar tu comunidad.",
    passoSeguranca: "Chequeos de seguridad",
    passoBasico: "Preparación básica",
    passoFinal: "Toques finales",
    seguraTitulo: "Mantené la comunidad segura",
    seguraDetalhe: "Una comunidad grande atrae spam. Estos dos frenos vienen prendidos, y los apagás después si molestan.",
    emailVerificado: "Pedir correo verificado",
    emailVerificadoDetalhe: "Quien todavía no confirmó el correo no escribe. Quien tiene rol pasa derecho.",
    filtroDeMidia: "Filtrar medios explícitos",
    filtroDeMidiaDetalhe: "Las imágenes y los videos llegan tapados, y solo se ven cuando alguien elige mirar.",
    basicoTitulo: "Prepará lo básico",
    basicoDetalhe: "Decí en qué canal están las reglas y adónde van nuestros avisos. Sin canal elegido, los creo a los dos.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} comandos",
    previa: "Cómo queda la tarjeta",
    trocarIcone: "Cambiar el ícono",
    tirarCapa: "Sacar la portada",
    heroComunidades: "Hay gente hablando de lo que te gusta",
    heroComunidadesDetalhe: "Comunidades abiertas por gente que usa esto. Entrá, leé la charla y quedate si te gusta.",
    emDestaque: "Destacadas",
    todasAsComunidades: "Las demás",
    heroTitulo: "¿Qué va a usar tu banda hoy?",
    heroDetalhe: "Bots de música, de juegos y de moderación, hechos por gente que también anda por acá. Elegí uno y entra a tu servidor.",
    novidades: "Recién llegadas",
    todosOsApps: "Las demás",
    lojaTitulo: "Página de la aplicación",
    lojaDetalhe: "Es lo que aparece en Explorar para quien todavía no la conoce.",
    capa: "Portada",
    capaDetalhe: "La imagen ancha de arriba. 1280 × 720 le queda bien.",
    trocarCapa: "Cambiar portada",
    categorias: "Categorías",
    categoriasDetalhe: "Hasta {{quantas}}. Por ahí se navega en Explorar.",
    idiomas: "Idiomas",
    idiomasDetalhe: "Hasta {{quantos}}. En qué idiomas responde la aplicación.",
    termos: "Términos de uso",
    politica: "Política de privacidad",
    politicas: "Políticas",
    servidorDeSuporte: "Servidor de soporte",
    servidorDeSuporteDetalhe: "Adonde va quien necesite ayuda con la aplicación.",
    semServidor: "Ninguno",
    emQuantosServidores: "En cuántos servidores",
    categoria: {
      GAMES: "Juegos",
      MUSICA: "Música",
      MODERACAO: "Moderación",
      PRODUTIVIDADE: "Productividad",
      SOCIAL: "Social",
      UTILIDADES: "Utilidades",
      ARTE_E_CRIACAO: "Arte y creación",
      EDUCACAO: "Aprendizaje",
      OUTRA: "Otra",
    },
    appIndisponivel: "Aplicación no disponible",
    voltarParaExplorar: "Volver a Explorar",
    adicionarApp: "Agregar app",
    copiarLink: "Copiar el enlace",
    denunciarApp: "Denunciar la app",
    copiarIdDoApp: "Copiar el ID de la app",
    visaoGeral: "Resumen",
    comandos: "Comandos",
    permissoes: "Permisos",
    semPermissoes: "Esta app no pide ningún permiso.",
    avisoDePermissoes: "Entra con un rol propio. Podés cambiar esos permisos después, en Configuración de la comunidad → Roles.",
    servidoresEmComum: "Comunidades en común",
    umServidorEmComum: "1 comunidad",
    quantosServidoresEmComum: "{{quantos}} comunidades",
    feitoPor: "Hecha por",
    publicadoEm: "Publicada el",
    denunciarNome: "Denunciar {{nome}}",
    denunciaDetalhe: "La denuncia va al equipo de Gravaê. Quien hizo la app no se entera de que fuiste vos.",
    denunciaFalhou: "No se pudo enviar la denuncia.",
    umMembro: "1 miembro",
    semDescricao: "Sin descripción.",
    adicionar: "Agregar",
    jaEstaAqui: "Ya estás acá",
    entrando: "Entrando…",
    entrar: "Entrar",
    comunidadePublica: "Comunidad pública",
    online: "{{quantos}} en línea",
    membros: "{{quantos}} miembros",
    abrirComunidade: "Abrir la comunidad",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Configuración del servidor",
  novasMensagens: "Mensajes nuevos",
  menu: {
    silenciar: "Silenciar comunidad",
    reativar: "Reactivar comunidad",
    porQuinze: "Por 15 minutos",
    porMeiaHora: "Por 30 minutos",
    porTresHoras: "Por 3 horas",
    porTresDias: "Por 3 días",
    porUmaHora: "Por 1 hora",
    porOitoHoras: "Por 8 horas",
    porUmDia: "Por 24 horas",
    ateReativar: "Hasta que la reactive",
    notificacoes: "Configuración de notificaciones",
    padrao: "Usar el predeterminado",
    todas: "Todos los mensajes",
    soMencoes: "Solo menciones",
    nada: "Nada",
    ocultarSilenciados: "Ocultar canales silenciados",
    denunciar: "Denunciar comunidad",
    marcarLida: "Marcar como leído",
    convidar: "Invitar miembros",
    editarPerfil: "Editar perfil de la comunidad",
    configuracoes: "Configuración de la comunidad",
    sair: "Salir de la comunidad",
    sairTitulo: "¿Salir de {{nome}}?",
    sairDescricao: "Necesitarás una nueva invitación para volver.",
    copiarId: "Copiar ID de la comunidad",
    idCopiado: "ID copiado.",
  },
  convite: {
    cartaoTitulo: "Te invitaron a entrar a una comunidad",
    indisponivel: "Invitación no disponible",
    indisponivelDetalhe: "Venció, se agotó, o quien la creó la borró.",
    entrar: "Entrar a la comunidad",
    chamado: "Te invitaron a unirte a",
    aceitarComo: "Aceptar como {{nome}}",
    abrir: "Abrir comunidad",
    recusar: "No, gracias",
  },
  pasta: {
    silenciarTodas: "Silenciar comunidades",
    reativarTodas: "Reactivar comunidades",
    mostrarSilenciados: "Mostrar canales silenciados",
    notificacoesDaComunidade: "Configuración de notificaciones",
    silenciarEveryone: "Silenciar @everyone y @here",
    permitirEveryone: "Permitir @everyone y @here",
    silenciarCargos: "Silenciar menciones de rol",
    permitirCargos: "Permitir menciones de rol",
    dicaDaCor: "Escribe un color (hex, rgb(), hsl() o nombre) o usa el selector.",
    mostrarIcone: "Mostrar icono al cerrar",
    dicaDoIcone: "Cerrada, muestra el icono en vez de los servidores.",
    icone: "Icono de la carpeta",
    excluir: "Eliminar carpeta",
    icones: {
      pasta: "Carpeta",
      estrela: "Favorito",
      coracao: "Corazón",
      salvar: "Guardar",
      jogo: "Mando de juego",
      escudo: "Escudo",
      nota: "Nota musical",
    },
    marcarLida: "Marcar carpeta como leída",
    configuracoes: "Configuración de la carpeta",
    desfazer: "Deshacer carpeta",
    titulo: "Carpeta",
    nome: "Nombre",
    semNome: "Sin nombre",
    cor: "Color",
    semCor: "Sin color",
    salvar: "Guardar",
  },
  denuncia: {
    titulo: "Denunciar {{nome}}",
    descricao: "La denuncia va al equipo de Gravaê. Cuéntanos qué pasó.",
    motivo: "Motivo",
    detalhes: "Detalles (opcional)",
    enviar: "Enviar denuncia",
    enviada: "Denuncia enviada. Gracias.",
    motivos: {
      spam: "Spam o publicidad",
      assedio: "Acoso u odio",
      conteudo: "Contenido inapropiado",
      golpe: "Estafa o fraude",
      outro: "Otro",
    },
  },
  selos: {
    verificada: "Comunidad verificada",
    detectavel: "Comunidad detectable",
  },
  auditoria: {
    todasAsAcoes: "Todas las acciones",
    todosOsUsuarios: "Todos los usuarios",
    filtroMembros: "Miembros",
    filtroCanais: "Canales",
    filtroEmojis: "Emojis",
    filtroServidor: "Servidor",
    titulo: "Registro de auditoría",
    porUsuario: "Filtrar por usuario",
    porAcao: "Filtrar por acción",
    vazio: "Nada registrado todavía con este filtro.",
    motivo: "Motivo:",
  },
  banimentos: {
    titulo: "Lista de baneos del servidor",
    descricao: "Quien está acá no entra ni con una invitación nueva. Quitar el baneo devuelve el acceso al instante.",
    procurar: "Buscar baneos por nombre de usuario",
    vazioTitulo: "Sin baneos",
    vazio: "Todavía no baneaste a nadie… pero si algún día hace falta, no lo dudes.",
    desbanir: "Quitar el baneo",
  },
  excluir: {
    tudoVai: "Todos los canales, mensajes e invitaciones de {{servidor}} se borrarán para los {{membros}} miembros. Nadie podrá recuperarlos después.",
    digite: "Escribí {{servidor}} para confirmar",
    titulo: "Eliminar servidor",
    aviso: "Esto no se puede deshacer.",
  },
  emblemas: {
    apagarDescricao: "Se le quita a quien lo esté usando. No se puede deshacer.",
    titulo: "Insignias",
    vazio: "Todavía no hay insignias.",
    novo: "Nueva insignia",
  },
  convites: {
    revogarTitulo: "¿Revocar la invitación?",
    revogarAcao: "Revocar",
    revogarDescricao: "El enlace {{codigo}} deja de funcionar al instante. Quien ya entró por él sigue en el servidor.",
    titulo: "Invitaciones",
    descricao: "Todos los enlaces de invitación activos de este servidor.",
    vazio: "Todavía no se creó ninguna invitación.",
    revogar: "Revocar invitación",
  },
  integracoes: {
    opcionais: "username y avatar_url son opcionales y valen por mensaje. El límite es de 5 mensajes cada 5 segundos.",
    apagarDescricao: "La URL deja de funcionar al instante. Los mensajes que ya mandó siguen en el canal.",
    titulo: "Integraciones",
    descricao: "Un webhook es una dirección que publica en un canal sin necesitar cuenta. Sirve para avisar cuando pasa una compilación, cuando alguien abre un ticket, o lo que quieras mandar desde un script.",
    novo: "Nuevo webhook",
    vazio: "Todavía no hay webhooks. Creá uno y pegá la URL donde quieras que llegue el mensaje.",
    canal: "Canal",
    apagar: "Eliminar webhook",
    comoUsar: "Cómo se usa",
    comoUsarTexto: "Mandá un POST con JSON:",
  },
  explorar: {
    titulo: "Explorar",
  },
  engajamento: {
    semCanal: "Sin canal de sistema",
    titulo: "Participación",
    descricao: "Lo que el servidor hace solo para no parecer vacío cuando llega gente nueva.",
    sistema: "Mensajes del sistema",
    boasVindas: "Enviar un mensaje de bienvenida cuando alguien entre",
    sorteio: "Sin texto propio abajo, la frase se sortea — siempre la misma cansa rápido.",
    canalDoSistema: "Canal de mensajes del sistema",
    mensagem: "Mensaje de bienvenida",
    deixeVazio: "Dejalo vacío para sortear entre las frases hechas",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtros que moderan solos, antes de que el mensaje exista. Quien administra el servidor nunca es filtrado — y los roles exentos pasan directo.",
    palavras: {
      titulo: "Bloquear palabras personalizadas",
      descricao: "Tu lista de palabras que nadie puede escribir.",
    },
    mencoes: {
      titulo: "Bloquear spam de menciones",
      descricao: "Bloquea un mensaje con demasiadas menciones de golpe.",
    },
    links: {
      titulo: "Bloquear enlaces",
      descricao: "Retiene cualquier dirección pegada en el chat.",
    },
    definir: "Configurar",
    nomeDaRegra: "Nombre de la regla",
    bloqueadas: "Palabras bloqueadas",
    digiteEnter: "Escribí y apretá Enter",
    comparacao: "La comparación ignora mayúsculas, acentos y puntuación — y no toma una palabra dentro de otra (\"burro\" no bloquea \"burrocracia\").",
    aPartirDe: "Bloquear a partir de cuántas menciones",
    oQueFazer: "Qué hacer",
    canalDoAlerta: "Canal del aviso",
    escolhaCanal: "Elegí un canal",
    castigo: "Silencio temporal (minutos)",
    isentos: "Roles exentos",
    semCargos: "Todavía no hay roles creados.",
    salvarRegra: "Guardar regla",
    apagar: "Eliminar regla",
    excluirTitulo: "¿Eliminar esta regla de AutoMod?",
    excluirDescricao: "El servidor deja de filtrar por ella al instante. Podés crearla de nuevo, pero la configuración actual se pierde.",
    excluirAcao: "Eliminar regla",
  },
  cargos: {
    titulo: "Roles",
    descricao: "Los roles dan nombre, color y poderes. Quien está más arriba en la lista manda sobre quien está abajo — y nadie toca un rol igual o superior al suyo.",
    criar: "Crear rol",
    vazio: "Todavía no hay roles.",
    abaExibicao: "Apariencia",
    abaPermissoes: "Permisos",
    abaMembros: "Miembros — {{quantos}}",
    everyone: "Vale para todo el mundo en el servidor. Es la base sobre la que suman los demás roles.",
    nomeDoCargo: "Nombre del rol",
    cor: "Color del rol",
    corDica: "Pinta el nombre de quien tiene el rol en la lista de miembros y en el chat.",
    semCor: "Sin color",
    corPersonalizada: "Color personalizado",
    estilo: "Estilo del nombre",
    segundaCor: "Segundo color",
    segundaCorDica: "Sin él, el degradado pasa a color sólido — no desaparece.",
    limparSegundaCor: "Quitar el segundo color",
    icone: "Ícono",
    iconeDica: "Aparece junto al rol en la tarjeta de perfil de quien lo tiene.",
    exibirSeparado: "Mostrar separado de los demás miembros",
    exibirSeparadoDica: "El rol tiene su propia sección en la lista de miembros.",
    permitirMencionar: "Permitir mencionar este rol",
    permitirMencionarDica: "Cualquiera va a poder notificar a todos los que tengan el rol.",
    semPoderDeConceder: "{{descricao}} (no tenés este permiso para concederlo)",
    adicionar: "Agregar a alguien a este rol",
    tirar: "Quitar el rol",
    semNinguem: "Todavía nadie tiene este rol.",
    apagar: "Eliminar rol",
    excluirTitulo: "¿Eliminar el rol \"{{nome}}\"?",
    excluirDescricao: "Quien tenga este rol pierde todo lo que le daba. No se puede deshacer.",
    excluirAcao: "Eliminar rol",
  },
  membros: {
    procurar: "Buscar por nombre o usuario",
    membroDesde: "Miembro desde",
    vazio: "No se encontró a nadie.",
    acoesPara: "Acciones para {{nome}}",
    deCastigo: "de silencio",
    tirarCastigo: "Quitar el silencio",
    castigo5min: "5 minutos",
    castigo1h: "1 hora",
    castigo1d: "1 día",
    castigo1s: "1 semana",
    expulsar: "Expulsar",
    expulsarTitulo: "¿Expulsar a {{nome}}?",
    expulsarDescricao: "sale de {{servidor}} al instante. Puede volver con una invitación — expulsar no impide el regreso.",
    banir: "Banear",
    banirTitulo: "¿Banear a {{nome}}?",
    banirDescricao: "sale de {{servidor}} y no puede volver, ni con invitación, hasta que le saquen el baneo.",
    motivo: "Motivo (opcional)",
    motivoDica: "Queda registrado en la auditoría",
  },
  perfil: {
    titulo: "Perfil del servidor",
    descricao: "Así es como tu servidor aparece en la lista y en los enlaces de invitación.",
    icone: "Ícono",
    faixa: "Banner superior",
    nomeDoServidor: "Nombre del servidor",
    campoDescricao: "Descripción",
    doQueE: "¿De qué se trata este servidor?",
    comprimido: "Comprimido antes de subir: {{economia}}",
  },
  etiqueta: {
    titulo: "Etiqueta del servidor",
    descricao: "Una etiqueta de hasta 4 letras que aparece al lado del nombre de quien es miembro — en el chat y en la lista de personas. Acá es gratis: sin mejoras, sin niveles.",
    escolhaNome: "Elegí un nombre",
    limite: "Máximo 4 caracteres, letras y números.",
    escolhaInsignia: "Elegí una insignia",
    voce: "Vos",
    fala1: "¿alguien se prende a jugar?",
    fala2: "¡mirá mi etiqueta!",
    fala3: "uh, ¿cómo conseguiste eso?",
  },
  expressoes: {
    comoUsar: "Agregá hasta {{limite}} emojis que todos pueden usar en este servidor. Escribí :nombre: en el chat para mandarlo.",
    imagem: "Imagen",
    enviadoPor: "Subido por",
    semEmoji: "Todavía no hay emojis.",
    figurinhas: "Stickers",
    enviarFigurinha: "Subir sticker",
    nomeDaFigurinha: "Nombre del sticker",
    exemploFigurinha: "Ej.: abrazo de gatito",
    figurinhaGrande: "El sticker pasa de {{limite}}.",
    deixaPraLa: "Dejalo",
    sons: "Panel de sonidos",
    enviarSom: "Subir sonido",
    nomeDoSom: "Nombre del sonido",
    semSom: "Todavía no hay sonidos.",
    somGrande: "El sonido pasa de {{limite}}.",
    emojiRelacionado: "Emoji relacionado",
    ouvir: "Escuchar",
    ouvirAssim: "Escuchar así",
    volumeDe: "Volumen de {{nome}}",
    volumeDica: "Vale para todos en el servidor. Cada persona todavía puede bajar los sonidos solo para ella, en el panel de la llamada.",
    falhaEnvio: "No se pudo subir el archivo.",
    excluirTitulo: "¿Eliminar {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Desaparece del servidor para todos. Los mensajes que ya lo usaron quedan como están.",
  },
  canal: {
    tipoLink: "Enlace",
    tipoLinkDica: "Apunta a una dirección de afuera y abre en el navegador",
    endereco: "Dirección",
    enderecoDica: "Adónde lleva este canal. Tiene que empezar con https://",
    visaoGeral: "Vista general",
    nome: "Nombre del canal",
    topico: "Tema del canal",
    topicoDica: "¿De qué se habla acá?",
    modoLento: "Cada persona solo manda un mensaje por intervalo. Quien gestiona mensajes o canales pasa directo.",
    visibilidade: "Visibilidad del contenido",
    padrao: "Predeterminado",
    padraoDica: "El contenido del canal siempre está visible.",
    spoiler: "Canal de spoilers",
    spoilerDica: "Marcá este canal como con spoilers, para que los giros de guion y los temas pesados queden ocultos hasta que alguien elija verlos.",
    idade: "Canal con restricción de edad",
    idadeDica: "Quien entre tiene que confirmar que es mayor de edad para ver el contenido.",
    bitrateDica: "Pasar de 64 kbps puede molestar a quien tiene mala conexión.",
    qualidadeDeVideo: "Calidad del video",
    automatica: "Automática",
    limite: "Límite de usuarios — {{valor}}",
    pessoas: "{{quantos}} personas",
    semLimite: "sin límite",
    permissoesDescricao: "Acá cambiás lo que vale en este canal. Lo que quede en “heredar” sigue al rol.",
    excluir: {
      titulo: "Eliminar canal",
      historico: "Todo el historial de {{canal}} se va con él, para todo el mundo.",
      digite: "Escribí {{canal}} para confirmar",
    },
  },
  moderacao: {
    titulo: "Vista de moderador",
    semPermissao: "Necesitás el permiso “Moderar miembros” para ver esto.",
    fecharEsc: "Cerrar (Esc)",
    atividade: "Actividad en el servidor",
    mensagens: "Mensajes",
    links: "Enlaces",
    midia: "Multimedia",
    acoesNaAuditoria: "Acciones en la auditoría",
    moderacoesSofridas: "Moderaciones recibidas",
    permissoes: "Permisos ({{quantas}})",
    semPermissaoEspecial: "Ningún permiso especial.",
    conta: "Cuenta",
    entrouNoServidor: "Entró al servidor",
    contaCriadaEm: "Cuenta creada el",
    deCastigoAte: "Silenciado hasta",
    formaDeAdesao: "Cómo entró",
    mensagem: "Mensaje",
    castigo: "Silencio temporal",
    copiarId: "Copiar ID",
    idCopiado: "ID copiado.",
    adicionarCargo: "Agregar rol",
    semCargos: "Ningún rol creado",
    soEveryone: "Solo @everyone.",
    voltar: "Volver",
    vazio: "Nada por acá.",
    cinquenta: "Mostrando los 50 más recientes.",
    irParaMensagem: "Ir al mensaje",
    precisaSerAmigo: "Tienen que ser amigos para hablar.",
    expulsarDescricao: "Sale del servidor al instante, pero puede volver con una invitación.",
    banirDescricao: "Sale del servidor y no puede volver, ni con invitación, hasta que le saquen el baneo.",
    castigarTitulo: "¿Silenciar a {{nome}}?",
    castigoDescricao: "Mientras dure, no escribe ni habla en ningún canal del servidor.",
    aplicarCastigo: "Aplicar silencio",
    duracao: "Duración en minutos",
    informeDuracao: "Indicá la duración en minutos.",
  },
  abas: {
    pesquisar: "Buscar en la configuración",
    semResultado: "Acá no hay nada con ese nombre.",
    comunidade: "Comunidad",
    expressoes: "Expresiones",
    pessoas: "Personas",
    apps: "Apps",
    moderacao: "Moderación",
    banimentos: "Baneos",
  },
};
