export const amizades = {
  ativosAgora: "Активни сега",
  procurando: "Гледаме кой е наоколо…",
  tudoTranquilo: "Засега е тихо…",
  tudoTranquiloDetalhe: "Когато ти или приятел влезете в разговор, той ще се появи тук — и се включваш с едно щракване.",
  emVoz: "В гласов канал",
  voce: "Ти",
  soVoce: "Само ти",
  pessoas: "{{quantas}} души",
  voltarParaChamada: "Обратно към разговора",
  entrarNaChamada: "Влез в разговора",
  abrirCanal: "Отвори {{canal}} в {{servidor}}",
  mensagensDiretas: "Лични съобщения",
  encontreConversa: "Намери разговор",
  amigos: "Приятели",
  conversas: "Разговори",
  semConversas: "Още няма разговори. Добави приятел, за да започнеш.",
  semConversaComEsseNome: "Няма разговор с това име.",
  abrirMenu: "Отвори сървърите и разговорите",
  solicitacoes: "Заявки за съобщение",
  pedidos: "Заявки",
  spam: "Спам",
  pedidosPendentes: "Чакащи заявки",
  marcadosComoSpam: "Отбелязани като спам",
  aceitar: "Приеми",
  ignorar: "Игнорирай",
  marcarSpam: "Отбележи като спам",
  semPedidos: "Няма чакащи заявки.",
  semPedidosDetalhe: "Който не ти е приятел, но е с теб в общ сървър, стига дотук, преди да влезе в разговорите ти.",
  semSpam: "Нищо не е отбелязано като спам.",
  semSpamDetalhe: "Каквото филтърът за спам отдели или каквото ти отбележиш, остава в този раздел.",
  umServidorEmComum: "1 общ сървър",
  servidoresEmComum: "Общи сървъри: {{quantos}}",
  semServidoresEmComum: "Няма общи сървъри",
};
