export const comum = {
  carregando: "Зареждане…",
  salvar: "Запази",
  salvando: "Запазване…",
  descartar: "Отхвърли",
  redefinir: "Нулирай",
  naoSalvo: "Имаш незапазени промени.",
  fechar: "Затвори",
  criar: "Създай",
  nome: "Име",
  emoji: "Емоджи",
  previa: "Преглед",
  cancelar: "Отказ",
  enviar: "Изпрати",
  apagar: "Изтрий",
  excluir: "Изтрий",
  remover: "Премахни",
  trocar: "Смени",
};
