export const configuracoes = {
  sair: "Изход",
  versoes: {
    copiar: "Щракни, за да копираш",
    copiado: "Копирано",
  },
  telas: {
    conta: "Моят акаунт",
    privacidade: "Поверителност",
    conexoes: "Връзки",
    voz: "Звук",
    video: "Видео",
    avisos: "Известия",
    aplicativos: "Приложения",
    aparencia: "Външен вид",
    batePapo: "Чат",
    acessibilidade: "Достъпност",
    idioma: "Език",
    aplicativo: "Изтегли приложението",
    atalhos: "Клавишни комбинации",
    avancado: "Разширени",
    servidor: "Сървър",
  },
  grupos: {
    conta: "Акаунт",
    app: "Настройки на приложението",
    desenvolvedor: "Разработчик",
    administracao: "Администрация",
  },
  secoes: {
    detalhesDeLogin: "Данни за вход",
    dispositivos: "Устройства",
    usuariosBloqueados: "Блокирани потребители",
    aplicativosAutorizados: "Оторизирани приложения",
    sessoes: "Сесии",
    amigosEDms: "Приятели и лични съобщения",
    compartilhamentoDeAtividade: "Споделяне на активност",
    visibilidadeDoPerfil: "Видимост на профила",
    exportarDados: "Експортиране на данни",
    exclusaoDeDados: "Изтриване на данни",
    tema: "Тема",
    corDeDestaque: "Акцентен цвят",
    interface: "Интерфейс",
    listaDeCanais: "Списък с канали",
    zoomDoApp: "Ниво на мащабиране",
    escalaDaFonte: "Размер на шрифта в чата",
    modoStreamer: "Поверителност при излъчване",
    movimento: "Движение",
    textoEmVoz: "Текст в реч",
    teclado: "Клавиатура",
    formatoDaHora: "Формат на часа",
    idiomaDaInterface: "Език на интерфейса",
    dispositivosDeVoz: "Устройства",
    testeDoMicrofone: "Тест на микрофона",
    modoDeEntrada: "Режим на въвеждане",
    sensibilidade: "Чувствителност на входа",
    qualidade: "Качество",
    camera: "Камера",
    transmissao: "Излъчване",
    exibicao: "Показване",
    entrada: "Въвеждане",
    midia: "Медия",
    geral: "Общи",
    preferenciaDeMencao: "Предпочитание за споменавания",
    sons: "Звуци",
  },
};
