export const configuracoes = {
  efeitos: {
    titulo: "Ефекти на показалеца",
    detalhe: "Следа и искри, рисувани върху приложението. Идват изключени и изчезват сами, ако сте поискали по-малко движение.",
    rastro: "Следа на курсора",
    rastroDetalhe: "Черта, която следва показалеца и гасне зад него.",
    faisca: "Искри при щракване",
    faiscaDetalhe: "Къси чертички, които излитат от мястото на щракването.",
    cor: "Цвят",
    espessura: "Дебелина",
    comprimento: "Дължина",
    tamanho: "Размер",
    quantidade: "Брой",
  },
  email: {
    verificarTitulo: "Потвърдете имейла си",
    verificarDetalhe: "Някои общности пускат да пишат само потвърдените. Става с едно щракване.",
    enviar: "Изпрати връзката",
    enviado: "Погледнете входящата поща. Връзката важи един ден.",
    falhou: "Имейлът не можа да бъде изпратен.",
    confirmado: "Имейлът е потвърден",
    confirmadoDetalhe: "Готово. Вече пишете във всяка общност, която го изисква.",
    linkIncompleto: "Непълна връзка",
    linkIncompletoDetalhe: "Липсва кодът в адреса. Отворете връзката направо от имейла.",
    confirmando: "Потвърждава се…",
    expirou: "Тази връзка вече е използвана или е изтекла.",
    irParaOApp: "Към приложението",
  },
  tema: {
    indisponivel: "Темата не е достъпна",
    indisponivelDetalhe: "Този, който я публикува, я изтри, или връзката е грешна.",
    indisponivelLinha: "Темата не е достъпна. Този, който я публикува, я изтри, или връзката е грешна.",
    importar: "Внасяне на тема",
    importarCurto: "Внеси",
    importarDetalhe: "Това заменя темата, която имате сега. После може да я редактирате в Настройки > Външен вид > Ателие за теми.",
    porAutor: "от {{autor}}",
    umaCorTrocada: "1 сменен цвят",
    coresTrocadas: "{{quantas}} сменени цвята",
    avisoDeCss: "Тази тема носи CSS от автора си, а CSS пипа всяко ъгълче на екрана. Внасяйте само от хора, на които вярвате.",
    soCores: "Тази тема сменя само цветове. Никакъв външен CSS.",
    aplicar: "Приложи",
    previaSemMotor: "Прегледът не пуска двигателя. Инсталирайте, за да го видите.",
    motorAnimado: "{{motor}} с анимация",
  },
  sair: "Изход",
  versoes: {
    termos: "Условия за ползване",
    privacidade: "Политика за поверителност",
    copiar: "Щракни, за да копираш",
    copiado: "Копирано",
  },
  telas: {
    conta: "Моят акаунт",
    privacidade: "Поверителност",
    conexoes: "Връзки",
    voz: "Звук",
    video: "Видео",
    avisos: "Известия",
    aplicativos: "Приложения",
    aparencia: "Външен вид",
    batePapo: "Чат",
    acessibilidade: "Достъпност",
    idioma: "Език",
    aplicativo: "Изтегли приложението",
    atalhos: "Клавишни комбинации",
    desktop: "Приложение за компютър",
    avancado: "Разширени",
    servidor: "Сървър",
    comunicado: "Системно съобщение",
    denuncias: "Сигнали",
    publicacoes: "Публикации",
  },
  grupos: {
    conta: "Акаунт",
    app: "Настройки на приложението",
    desenvolvedor: "Разработчик",
    administracao: "Администрация",
  },
  secoes: {
    detalhesDeLogin: "Данни за вход",
    dispositivos: "Устройства",
    usuariosBloqueados: "Блокирани потребители",
    aplicativosAutorizados: "Оторизирани приложения",
    sessoes: "Сесии",
    amigosEDms: "Приятели и лични съобщения",
    compartilhamentoDeAtividade: "Споделяне на активност",
    visibilidadeDoPerfil: "Видимост на профила",
    exportarDados: "Експортиране на данни",
    exclusaoDeDados: "Изтриване на данни",
    tema: "Тема",
    corDeDestaque: "Акцентен цвят",
    interface: "Интерфейс",
    listaDeCanais: "Списък с канали",
    zoomDoApp: "Ниво на мащабиране",
    escalaDaFonte: "Размер на шрифта в чата",
    modoStreamer: "Поверителност при излъчване",
    cursores: "Курсори",
    movimento: "Движение",
    textoEmVoz: "Текст в реч",
    teclado: "Клавиатура",
    formatoDaHora: "Формат на часа",
    idiomaDaInterface: "Език на интерфейса",
    dispositivosDeVoz: "Устройства",
    testeDoMicrofone: "Тест на микрофона",
    modoDeEntrada: "Режим на въвеждане",
    sensibilidade: "Чувствителност на входа",
    qualidade: "Качество",
    camera: "Камера",
    transmissao: "Излъчване",
    exibicao: "Показване",
    entrada: "Въвеждане",
    midia: "Медия",
    geral: "Общи",
    preferenciaDeMencao: "Предпочитание за споменавания",
    sons: "Звуци",
  },
};
