export const conversa = {
  lista: {
    carregando: "Зареждане на съобщенията…",
    carregandoMais: "Зареждане…",
    verMais: "Превърти нагоре, за да видиш повече",
    semHistorico: "Историята не е достъпна",
    semHistoricoDetalhe: "Ролята ти няма право да чете историята на #{{canal}}. Новите съобщения ще продължат да се появяват, докато си тук.",
    boasVindas: "Добре дошъл в #{{canal}}",
    boasVindasDetalhe: "Това е началото на канала #{{canal}}.",
  },
  data: {
    hoje: "Днес",
    ontem: "Вчера",
    hojeAs: "днес в {{hora}}",
    ontemAs: "вчера в {{hora}}",
  },
  digitando: {
    um: "{{nome}} пише…",
    dois: "{{primeiro}} и {{segundo}} пишат…",
    varios: "{{quantidade}} души пишат…",
  },
  mensagem: {
    usou: "използва",
    fixada: "закачено",
    editado: "(редактирано)",
    ignorada: "Съобщение от някого, когото пренебрегваш.",
    mostrar: "Покажи",
    escPara: "Esc за",
    cancelar: "отказ",
    enterParaSalvar: "Enter за запазване",
    falhou: "Не беше изпратено. Опитай пак",
    naoLidasDaqui: "Непрочетени оттук.",
    linkCopiado: "Връзката е копирана.",
    idCopiado: "ID е копирано.",
    naoDeuParaCopiar: "Браузърът ти не разреши копиране.",
    apagarTitulo: "Да изтрия ли съобщението?",
    apagarDescricao: "Изчезва за всички в канала. Не може да се възстанови.",
    apagarAcao: "Изтрий",
    citacaoAnexo: "щракни, за да видиш прикачения файл",
    citacaoSumiu: "Първоначалното съобщение вече го няма.",
    reagirCom: "Реагирай с {{emoji}} — задръж за супер реакция",
    segureParaSuper: "{{emoji}} — задръж за супер реакция",
  },
  acoes: {
    reagir: "Реагирай",
    responder: "Отговори",
    encaminhar: "Препрати",
    favoritar: "Запази съобщението",
    tirarDosFavoritos: "Премахни от запазените",
    marcarNaoLida: "Отбележи като непрочетено",
    copiarLink: "Копирай връзката към съобщението",
    copiarId: "Копирай ID на съобщението",
    fixar: "Закачи съобщението",
    desafixar: "Откачи",
    editar: "Редактирай",
    apagar: "Изтрий",
    mais: "Още",
    adicionarReacao: "Добави реакция",
    superReagirCom: "Супер реакция с {{emoji}}",
    fixarMensagem: "Закачи съобщението",
    desafixarMensagem: "Откачи съобщението",
    editarMensagem: "Редактирай съобщението",
    apagarMensagem: "Изтрий съобщението",
  },
  mencao: {
    cargo: "Споменаване на роля",
    pessoa: "Споменаване",
    alguem: "някой",
    cargoSemNome: "роля",
    here: "Уведомява тези, които са онлайн",
    everyone: "Уведомява целия сървър",
  },
  codigo: {
    copiar: "Копирай",
    copiado: "Копирано",
    copiarAria: "Копирай кода",
    copiadoAria: "Кодът е копиран",
  },
  caixa: {
    escrever: "Пиши в #{{canal}}",
    escreverSemCanal: "Напиши съобщение",
    semPermissao: "Нямаш право да изпращаш съобщения в този канал",
    solteParaAnexar: "Пусни, за да прикачиш",
    respondendoPara: "Отговор до",
    vaiNotificar: "Човекът ще получи известие",
    naoVaiNotificar: "Човекът няма да получи известие",
    ligado: "вкл.",
    desligado: "изкл.",
    pararDeResponder: "Спри да отговаряш",
    mais: "Още",
    enviarArquivo: "Изпрати файл",
    criarEnquete: "Създай анкета",
    expressoes: "Емоджита, GIF-ове и стикери",
    enviar: "Изпрати",
    aguardandoEnvio: "Изчакване на качването",
    modoLento: "Бавният режим е включен ({{tempo}})",
    modoLentoDica: "Бавният режим е зададен на {{segundos}} сек. Изчакай, преди да изпратиш друго съобщение.",
  },
  anexos: {
    enviando: "Качване…",
    modificar: "Промени {{arquivo}}",
    remover: "Премахни {{arquivo}}",
    ver: "Виж {{arquivo}}",
    mostrarSpoiler: "Покажи спойлера: {{arquivo}}",
    spoiler: "спойлер",
    spoilerTitulo: "Спойлер",
    editarTitulo: "Редактирай прикачения файл",
    nomeDoArquivo: "Име на файла",
    descricao: "Описание на алтернативния текст",
    descricaoDica: "Опиши този файл за екранните четци",
    marcarSpoiler: "Отбележи като спойлер",
    cancelar: "Откажи",
    salvar: "Запази",
  },
  cartao: {
    tocador: "Плейър",
    abrir: "Отвори {{destino}}",
    tocar: "Пусни {{titulo}}",
    video: "видео",
    verImagem: "Виж изображението",
  },
  enquete: {
    titulo: "Анкета",
    encerrada: "Анкетата е затворена",
    variasRespostas: "Анкета — няколко отговора",
    umVoto: "{{quantidade}} глас",
    votos: "{{quantidade}} гласа",
    umVotoNoTotal: "{{quantidade}} глас общо",
    votosNoTotal: "{{quantidade}} гласа общо",
    encerraEm: "затваря на {{quando}}",
    encerrarAgora: "Затвори сега",
  },
  fixadas: {
    titulo: "Закачени съобщения",
    vazio: "Този канал няма закачени съобщения… засега.",
    desafixar: "Откачи",
    anexo: "(прикачен файл)",
    enquete: "(анкета)",
    dicaRotulo: "СЪВЕТ:",
    dica: "който има правото „Управление на съобщенията“, може да закачи направо от менюто на съобщението.",
  },
  encaminhar: {
    titulo: "Препрати съобщението",
    paraOnde: "Накъде?",
    semTexto: "(съобщение без текст)",
    nenhumLugar: "Няма място с това име.",
    canais: "Канали",
    conversas: "Лични съобщения",
  },
};
