export const conversa = {
  lista: {
    carregando: "Зареждане на съобщенията…",
    carregandoMais: "Зареждане…",
    verMais: "Превърти нагоре, за да видиш повече",
    semHistorico: "Историята не е достъпна",
    semHistoricoDetalhe: "Ролята ти няма право да чете историята на #{{canal}}. Новите съобщения ще продължат да се появяват, докато си тук.",
    boasVindas: "Добре дошъл в #{{canal}}",
    boasVindasDetalhe: "Това е началото на канала #{{canal}}.",
  },
  data: {
    hoje: "Днес",
    ontem: "Вчера",
    hojeAs: "днес в {{hora}}",
    ontemAs: "вчера в {{hora}}",
  },
  digitando: {
    um: "{{nome}} пише…",
    dois: "{{primeiro}} и {{segundo}} пишат…",
    varios: "{{quantidade}} души пишат…",
  },
  mensagem: {
    usou: "използва",
    fixada: "закачено",
    editado: "(редактирано)",
    ignorada: "Съобщение от някого, когото пренебрегваш.",
    mostrar: "Покажи",
    escPara: "Esc за",
    cancelar: "отказ",
    enterParaSalvar: "Enter за запазване",
    naoLidasDaqui: "Непрочетени оттук.",
    linkCopiado: "Връзката е копирана.",
    idCopiado: "ID е копирано.",
    naoDeuParaCopiar: "Браузърът ти не разреши копиране.",
    apagarTitulo: "Да изтрия ли съобщението?",
    apagarDescricao: "Изчезва за всички в канала. Не може да се възстанови.",
    apagarAcao: "Изтрий",
    citacaoAnexo: "щракни, за да видиш прикачения файл",
    citacaoSumiu: "Първоначалното съобщение вече го няма.",
    encaminhadaDe: "Препратено от",
    irParaOriginal: "Към оригинала",
    bloqueadas: "{{quantas}} блокирани съобщения",
    mostrarBloqueadas: "Покажи",
    esconderBloqueadas: "Скрий",
    reagirCom: "Реагирай с {{emoji}} — задръж за супер реакция",
    segureParaSuper: "{{emoji}} — задръж за супер реакция",
  },
  imagem: {
    copiarImagem: "Копирай изображението",
    baixarImagem: "Изтегли изображението",
    copiarLinkDaImagem: "Копирай връзката към изображението",
    abrirLinkDaImagem: "Отвори връзката към изображението",
    maisAcoes: "Още действия с медия",
    pesquisarImagem: "Търси изображението",
    copiarIdDoAnexo: "Копирай ID на прикачения файл",
    girarEsquerda: "Завърти наляво",
    girarDireita: "Завърти надясно",
    ajustar: "Побери в екрана",
    ampliar: "Увеличи",
    reduzir: "Намали",
    imagemCopiada: "Изображението е копирано.",
    linkCopiado: "Връзката е копирана.",
    idCopiado: "ID е копирано.",
    naoDeuParaCopiar: "Изображението не можа да се копира.",
  },

  acoes: {
    reagir: "Реагирай",
    responder: "Отговори",
    encaminhar: "Препрати",
    favoritar: "Запази съобщението",
    tirarDosFavoritos: "Премахни от запазените",
    marcarNaoLida: "Отбележи като непрочетено",
    copiarLink: "Копирай връзката към съобщението",
    copiarId: "Копирай ID на съобщението",
    fixar: "Закачи съобщението",
    desafixar: "Откачи",
    editar: "Редактирай",
    apagar: "Изтрий",
    mais: "Още",
    adicionarReacao: "Добави реакция",
    superReagirCom: "Супер реакция с {{emoji}}",
    fixarMensagem: "Закачи съобщението",
    desafixarMensagem: "Откачи съобщението",
    editarMensagem: "Редактирай съобщението",
    apagarMensagem: "Изтрий съобщението",
    denunciarMensagem: "Докладване на съобщението",
  },
  denuncia: {
    titulo: "Докладване на съобщението",
    descricao: "Докладът отива при екипа на Gravaê. Разкажи какво се случи.",
    de: "От {{nome}}",
    semTexto: "(без текст)",
    motivo: "Причина",
    detalhes: "Подробности (по избор)",
    enviar: "Изпрати доклад",
    enviada: "Докладът е изпратен. Благодарим.",
    motivos: {
      spam: "Спам или реклама",
      assedio: "Тормоз или омраза",
      conteudo: "Неподходящо съдържание",
      golpe: "Измама",
      outro: "Друго",
    },
  },
  falha: {
    tentarDeNovo: "Опитай пак",
    erro: "Не е доставено",
    semConexao: "Не е доставено — нямаш връзка",
    semAcesso: "Не е доставено — този канал вече не е достъпен за теб",
    semPermissao: "Не е доставено — не можеш да пишеш тук",
    castigo: "Не е доставено — в таймаут си в този сървър",
    modoLento: "Не е доставено — бавният режим още не е изтекъл",
    depressa: "Не е доставено — изпращаш твърде бързо",
    automod: "Не е доставено — AutoMod го блокира",
    recusada: "Не е доставено — този разговор не приема отговори",
    naoEntregue: "Не е доставено — този човек не приема съобщения от вас",
  },
  mencao: {
    cargo: "Споменаване на роля",
    pessoa: "Споменаване",
    alguem: "някой",
    cargoSemNome: "роля",
    here: "Уведомява тези, които са онлайн",
    everyone: "Уведомява целия сървър",
  },
  codigo: {
    copiar: "Копирай",
    copiado: "Копирано",
    copiarAria: "Копирай кода",
    copiadoAria: "Кодът е копиран",
    recolher: "Свий",
    expandir: "Разгъни",
    verInteiro: "Виж целия файл",
    maisOpcoes: "Още опции",
    baixar: "Изтегли",
    recolherLinhas: "Свий ({{linhas}} реда)",
    expandirLinhas: "Разгъни ({{linhas}} реда)",
    mudarIdioma: "Смяна на езика",
    procurarIdioma: "Търсене на език…",
    nenhumIdioma: "Няма такъв език.",
    quebrarTexto: "Пренасяне на текста",
  },
  caixa: {
    escrever: "Пиши в #{{canal}}",
    escreverSemCanal: "Напиши съобщение",
    semPermissao: "Нямаш право да изпращаш съобщения в този канал",
    solteParaAnexar: "Пусни, за да прикачиш",
    longaTitulo: "Съобщението е твърде дълго…",
    longaDescricao: "Достигна максимума от {{limite}} знака. Може да го изпратиш като файл.",
    enviarComoArquivo: "Изпрати като файл",
    textoComoArquivo: "Изпрати текста като файл",
    arquivoGrandeTitulo: "Файлът е твърде голям",
    arquivoGrandeDescricao: "„{{arquivo}}“ надхвърля лимита от {{limite}} MB на файл.",
    respondendoPara: "Отговор до",
    vaiNotificar: "Човекът ще получи известие",
    naoVaiNotificar: "Човекът няма да получи известие",
    ligado: "вкл.",
    desligado: "изкл.",
    pararDeResponder: "Спри да отговаряш",
    mais: "Още",
    enviarArquivo: "Изпрати файл",
    criarEnquete: "Създай анкета",
    expressoes: "Емоджита, GIF-ове и стикери",
    enviar: "Изпрати",
    aguardandoEnvio: "Изчакване на качването",
    modoLento: "Бавният режим е включен ({{tempo}})",
    modoLentoDica: "Бавният режим е зададен на {{segundos}} сек. Изчакай, преди да изпратиш друго съобщение.",
  },
  anexos: {
    enviando: "Качване…",
    modificar: "Промени {{arquivo}}",
    verPrevia: "Преглед на {{arquivo}}",
    excluirTitulo: "Изтриване на прикачения файл",
    excluirDescricao: "Да изтрия ли „{{arquivo}}“? Не може да се върне и файлът се маха от съобщението.",
    excluirAcao: "Изтрий файла",
    excluirFalhou: "Не можах да изтрия файла.",
    remover: "Премахни {{arquivo}}",
    ver: "Виж {{arquivo}}",
    mostrarSpoiler: "Покажи спойлера: {{arquivo}}",
    spoiler: "спойлер",
    spoilerTitulo: "Спойлер",
    editarTitulo: "Редактирай прикачения файл",
    nomeDoArquivo: "Име на файла",
    descricao: "Описание на алтернативния текст",
    descricaoDica: "Опиши този файл за екранните четци",
    marcarSpoiler: "Отбележи като спойлер",
    cancelar: "Откажи",
    salvar: "Запази",
  },
  cartao: {
    tocador: "Плейър",
    abrir: "Отвори {{destino}}",
    tocar: "Пусни {{titulo}}",
    video: "видео",
    verImagem: "Виж изображението",
  },
  enquete: {
    titulo: "Анкета",
    encerrada: "Анкетата е затворена",
    variasRespostas: "Анкета — няколко отговора",
    umVoto: "{{quantidade}} глас",
    votos: "{{quantidade}} гласа",
    umVotoNoTotal: "{{quantidade}} глас общо",
    votosNoTotal: "{{quantidade}} гласа общо",
    encerraEm: "затваря на {{quando}}",
    encerrarAgora: "Затвори сега",
  },
  fixadas: {
    titulo: "Закачени съобщения",
    vazio: "Този канал няма закачени съобщения… засега.",
    desafixar: "Откачи",
    anexo: "(прикачен файл)",
    enquete: "(анкета)",
    dicaRotulo: "СЪВЕТ:",
    dica: "който има правото „Управление на съобщенията“, може да закачи направо от менюто на съобщението.",
  },
  encaminhar: {
    titulo: "Препрати съобщението",
    paraOnde: "Накъде?",
    semTexto: "(съобщение без текст)",
    nenhumLugar: "Няма място с това име.",
    canais: "Канали",
    conversas: "Лични съобщения",
  },
  expressoes: {
    gifs: "GIF-ове",
    buscarGifs: "Търсене в Klipy",
    figurinha: "Стикер",
    buscarFigurinha: "Намери идеалния стикер",
    buscarEmoji: "Намери идеалното емоджи",
    buscarReacao: "Намери идеалната реакция",
    adicionarEmoji: "Добави емоджи",
    limparBusca: "Изчисти търсенето",
  },
  busca: {
    pesquisar: "Търсене",
    limpar: "Изчисти търсенето",
    filtros: "Филтри за търсене",
    escopo: {
      titulo: "Обхват на търсенето",
      servidor: "Текуща общност",
      canal: "Този разговор",
      comunidades: "Всички общности",
      dms: "Само лични съобщения",
      tudo: "Лични съобщения и общности",
    },
    fechar: "Затвори търсенето",
    procurando: "Търся…",
    resultado: "{{quantos}} резултат",
    resultados: "{{quantos}} резултата",
    nadaCom: "Нищо с {{termo}} тук.",
    soOsQuePodeLer: "Търсенето гледа само каналите, които можеш да четеш.",
  },
  entrada: {
    titulo: "Входящи",
    naoLidas: "Непрочетени",
    salvas: "Запазени",
    mencoes: "Споменавания",
    fimTitulo: "Стигна до края",
    fimDetalhe: "Няма какво повече да се чете. Когато дойде ново съобщение, ще се появи тук.",
    semSalvosTitulo: "Нищо запазено",
    semSalvosDetalhe: "Задръж Shift и щракни върху отметката на съобщение, за да го запазиш и прочетеш после.",
    tirarDosSalvos: "Премахни от запазените",
    semMencoesTitulo: "Още няма споменавания",
    semMencoesDetalhe: "Споменаванията на теб се появяват тук за последните 7 дни.",
  },
  forum: {
    descricao: "Всяка тема става отделен разговор — добре за въпрос, който не бива да се изгуби насред приказките.",
    novoAssunto: "Нова тема",
    vazio: "Още няма теми. Започни първата и разговорът остава подреден от самото начало.",
    titulo: "Заглавие",
    doQueSeTrata: "За какво става дума?",
    primeiraMensagem: "Първо съобщение",
    conteDoCaso: "Разкажи",
  },
};
