export const perfil = {
  carregando: "Зареждане…",
  editar: "Редактиране на профила",
  mensagem: "Съобщение",
  abrirConversa: "Отваряне на разговора",
  verCompleto: "Пълен профил",
  convidarParaServidor: "Покани в сървъра",
  semServidores: "Нямаш сървъри",
  conviteEnviado: "Поканата е изпратена до {{nome}}.",
  moderador: "Отваряне в изглед на модератор",
  mais: "Още",
  ignorar: "Пренебрегни",
  deixarDeIgnorar: "Спри да пренебрегваш",
  copiarId: "Копирай ID на потребителя",
  idCopiado: "ID е копирано.",
  conexoes: "Връзки",
  membroDesde: "Член от",
  sobre: "За мен",
  cargosTitulo: "Роли",
  visaoGeral: "Преглед",
  amigosEmComum: "Общи приятели ({{quantidade}})",
  servidoresEmComum: "Общи сървъри ({{quantidade}})",
  amizade: {
    amigo: "Приятел",
    pedidoEnviado: "Заявката за приятелство е изпратена",
    respondaAbaixo: "Изпрати ти заявка — отговори по-долу",
    adicionar: "Добави приятел",
    teMandouPedido: "Изпрати ти заявка за приятелство",
    aceitar: "Приеми",
    desfazer: "Премахни от приятели",
    desfazerTitulo: "Да премахна ли {{nome}} от приятелите ти?",
    desfazerDescricao: "Преставате да бъдете приятели. Личният разговор остава в историята и по-късно можеш да го добавиш отново.",
    bloquear: "Блокирай",
    bloquearTitulo: "Да блокирам ли {{nome}}?",
    bloquearDescricao: "Преставате да бъдете приятели, личният разговор спира да приема съобщения и той вече не може да ти изпрати заявка за приятелство.",
    linkCopiado: "Не сте приятели — връзката е копирана, за да я изпратиш ти.",
  },
  recado: {
    escrever: "Пиши на @{{usuario}}",
    enviar: "Изпрати",
    enviada: "Съобщението е изпратено",
    falhou: "Не успя да се изпрати. Опитай от разговора.",
  },
  cartao: {
    trocarFaixa: "Смени банера на картата",
    trocarFaixaCurto: "Смени банера",
    trocarFoto: "Смени профилната снимка",
    trocarFotoCurto: "Смени снимката",
    suaEtiqueta: "Твоят етикет",
    editarEtiqueta: "Щракни, за да редактираш етикета си",
    conteAlgo: "Разкажи нещо за себе си",
    adicionarStatus: "Добави състояние",
    adicionarDescricao: "Щракни, за да добавиш описание",
    cargo: "Роля",
    cargos: "Роли",
    cargosCom: "Роли — {{quantidade}}",
    tirarCargo: "Премахни ролята {{cargo}}",
  },
  cargos: {
    adicionar: "Добави роля",
    procurar: "Търси роля",
  },
  etiqueta: {
    escolher: "Избери етикет на сървъра",
    nenhuma: "Няма етикет на сървъра",
    semEtiqueta: "Никой от сървърите ти няма етикет",
  },
  emblemas: {
    doServidor: "Значки от този сървър",
    limite: "Можеш да носиш до {{quantidade}} значки.",
  },
  nota: {
    vazia: "Щракни, за да си запишеш нещо",
    rotulo: "Бележка (виждаш я само ти)",
    adicionar: "Добави бележка (само ти я виждаш)",
  },
  status: {
    titulo: "Състояние",
    definir: "Задай състоянието си",
    escolherEmoji: "Избери емоджи",
    tirarEmoji: "Премахни емоджито",
    oQuePensa: "За какво мислиш?",
    limparAgora: "Изчисти състоянието сега",
    naoLimpar: "Не изчиствай",
    limpar30m: "Изчисти след 30 минути",
    limpar1h: "Изчисти след 1 час",
    limpar4h: "Изчисти след 4 часа",
    limparHoje: "Изчисти днес",
    limparAmanha: "Изчисти утре",
    comHora: "{{prazo}} в {{hora}}",
  },
  presenca: {
    disponivel: "Достъпен",
    ausente: "Отсъства",
    naoPerturbar: "Не безпокойте",
    naoPerturbarDetalhe: "Не получаваш известие за нови съобщения",
    invisivel: "Невидим",
    invisivelDetalhe: "За другите изглеждаш офлайн",
  },
  menu: {
    mudarDeConta: "Смени акаунта",
    gerenciarContas: "Управление на акаунтите",
  },
  editor: {
    decoracao: "Смени украсата на аватара",
    naoSalvo: "Не забравяй да запазиш промените си!",
    principal: "Основен профил",
  },
};
