export const amizades = {
  ativosAgora: "Ενεργοί τώρα",
  procurando: "Βλέπουμε ποιος είναι εδώ…",
  tudoTranquilo: "Προς το παρόν ησυχία…",
  tudoTranquiloDetalhe: "Όταν εσύ ή ένας φίλος μπείτε σε κλήση, θα εμφανιστεί εδώ — και μπαίνεις με ένα κλικ.",
  emVoz: "Σε φωνητικό",
  voce: "Εσύ",
  soVoce: "Μόνο εσύ",
  pessoas: "{{quantas}} άτομα",
  voltarParaChamada: "Πίσω στην κλήση",
  entrarNaChamada: "Μπες στην κλήση",
  abrirCanal: "Άνοιγμα {{canal}} στο {{servidor}}",
  mensagensDiretas: "Απευθείας μηνύματα",
  encontreConversa: "Βρες μια συνομιλία",
  amigos: "Φίλοι",
  conversas: "Συνομιλίες",
  semConversas: "Καμία συνομιλία ακόμα. Πρόσθεσε έναν φίλο για να ξεκινήσεις.",
  semConversaComEsseNome: "Καμία συνομιλία με αυτό το όνομα.",
  abrirMenu: "Άνοιγμα διακομιστών και συνομιλιών",
  solicitacoes: "Αιτήματα μηνύματος",
  pedidos: "Αιτήματα",
  spam: "Ανεπιθύμητα",
  pedidosPendentes: "Αιτήματα σε αναμονή",
  marcadosComoSpam: "Σημειωμένα ως ανεπιθύμητα",
  aceitar: "Αποδοχή",
  ignorar: "Αγνόηση",
  marcarSpam: "Σήμανση ως ανεπιθύμητο",
  semPedidos: "Κανένα αίτημα σε αναμονή.",
  semPedidosDetalhe: "Όποιος δεν είναι φίλος σου αλλά μοιράζεται διακομιστή μαζί σου, καταλήγει εδώ πριν φτάσει στις συνομιλίες σου.",
  semSpam: "Τίποτα σημειωμένο ως ανεπιθύμητο.",
  semSpamDetalhe: "Ό,τι ξεχωρίσει το φίλτρο ανεπιθύμητων, ή ό,τι σημειώσεις εσύ, μένει σε αυτή την καρτέλα.",
  umServidorEmComum: "1 κοινός διακομιστής",
  servidoresEmComum: "{{quantos}} κοινοί διακομιστές",
  semServidoresEmComum: "Κανένας κοινός διακομιστής",
};
