export const configuracoes = {
  sair: "Αποσύνδεση",
  versoes: {
    copiar: "Κάνε κλικ για αντιγραφή",
    copiado: "Αντιγράφηκε",
  },
  telas: {
    conta: "Ο λογαριασμός μου",
    privacidade: "Απόρρητο",
    conexoes: "Συνδέσεις",
    voz: "Ήχος",
    video: "Βίντεο",
    avisos: "Ειδοποιήσεις",
    aplicativos: "Εφαρμογές",
    aparencia: "Εμφάνιση",
    batePapo: "Συνομιλία",
    acessibilidade: "Προσβασιμότητα",
    idioma: "Γλώσσα",
    aplicativo: "Λήψη της εφαρμογής",
    atalhos: "Συντομεύσεις",
    desktop: "Εφαρμογή υπολογιστή",
    avancado: "Για προχωρημένους",
    servidor: "Διακομιστής",
  },
  grupos: {
    conta: "Λογαριασμός",
    app: "Ρυθμίσεις εφαρμογής",
    desenvolvedor: "Προγραμματιστής",
    administracao: "Διαχείριση",
  },
  secoes: {
    detalhesDeLogin: "Στοιχεία σύνδεσης",
    dispositivos: "Συσκευές",
    usuariosBloqueados: "Αποκλεισμένοι χρήστες",
    aplicativosAutorizados: "Εξουσιοδοτημένες εφαρμογές",
    sessoes: "Συνεδρίες",
    amigosEDms: "Φίλοι και άμεσα μηνύματα",
    compartilhamentoDeAtividade: "Κοινή χρήση δραστηριότητας",
    visibilidadeDoPerfil: "Ορατότητα προφίλ",
    exportarDados: "Εξαγωγή δεδομένων",
    exclusaoDeDados: "Διαγραφή δεδομένων",
    tema: "Θέμα",
    corDeDestaque: "Χρώμα τονισμού",
    interface: "Διεπαφή",
    listaDeCanais: "Λίστα καναλιών",
    zoomDoApp: "Επίπεδο ζουμ της εφαρμογής",
    escalaDaFonte: "Μέγεθος γραμματοσειράς συνομιλίας",
    modoStreamer: "Απόρρητο κατά τη μετάδοση",
    movimento: "Κίνηση",
    textoEmVoz: "Κείμενο σε ομιλία",
    teclado: "Πληκτρολόγιο",
    formatoDaHora: "Μορφή ώρας",
    idiomaDaInterface: "Γλώσσα διεπαφής",
    dispositivosDeVoz: "Συσκευές",
    testeDoMicrofone: "Δοκιμή μικροφώνου",
    modoDeEntrada: "Λειτουργία εισόδου",
    sensibilidade: "Ευαισθησία εισόδου",
    qualidade: "Ποιότητα",
    camera: "Κάμερα",
    transmissao: "Μετάδοση",
    exibicao: "Προβολή",
    entrada: "Εισαγωγή",
    midia: "Πολυμέσα",
    geral: "Γενικά",
    preferenciaDeMencao: "Προτίμηση αναφορών",
    sons: "Ήχοι",
  },
};
