export const configuracoes = {
  efeitos: {
    titulo: "Εφέ του δείκτη",
    detalhe: "Ίχνος και σπίθες ζωγραφισμένα πάνω από την εφαρμογή. Ξεκινούν σβηστά και χάνονται μόνα τους αν ζητήσατε λιγότερη κίνηση.",
    rastro: "Ίχνος του δείκτη",
    rastroDetalhe: "Μια γραμμή που ακολουθεί τον δείκτη και ξεθωριάζει πίσω του.",
    faisca: "Σπίθες στο κλικ",
    faiscaDetalhe: "Κοντές γραμμές που πετάγονται από εκεί που πατήσατε.",
    cor: "Χρώμα",
    espessura: "Πάχος",
    comprimento: "Μήκος",
    tamanho: "Μέγεθος",
    quantidade: "Πλήθος",
  },
  email: {
    verificarTitulo: "Επιβεβαιώστε το email σας",
    verificarDetalhe: "Κάποιες κοινότητες αφήνουν να γράψουν μόνο όσους επιβεβαίωσαν. Θέλει ένα κλικ.",
    enviar: "Στείλε τον σύνδεσμο",
    enviado: "Δείτε τα εισερχόμενα. Ο σύνδεσμος κρατά μία μέρα.",
    falhou: "Δεν έγινε να σταλεί το email.",
    confirmado: "Το email επιβεβαιώθηκε",
    confirmadoDetalhe: "Έτοιμο. Τώρα γράφετε σε κάθε κοινότητα που το ζητά.",
    linkIncompleto: "Μισός σύνδεσμος",
    linkIncompletoDetalhe: "Λείπει ο κωδικός από τη διεύθυνση. Ανοίξτε τον σύνδεσμο απευθείας από το email.",
    confirmando: "Γίνεται επιβεβαίωση…",
    expirou: "Αυτός ο σύνδεσμος χρησιμοποιήθηκε ήδη ή έληξε.",
    irParaOApp: "Στην εφαρμογή",
  },
  tema: {
    indisponivel: "Το θέμα δεν είναι διαθέσιμο",
    indisponivelDetalhe: "Όποιος το δημοσίευσε το έσβησε, ή ο σύνδεσμος είναι λάθος.",
    indisponivelLinha: "Το θέμα δεν είναι διαθέσιμο. Όποιος το δημοσίευσε το έσβησε, ή ο σύνδεσμος είναι λάθος.",
    importar: "Εισαγωγή θέματος",
    importarCurto: "Εισαγωγή",
    importarDetalhe: "Αυτό αντικαθιστά το θέμα που έχετε τώρα. Μπορείτε να το επεξεργαστείτε μετά στις Ρυθμίσεις > Εμφάνιση > Στούντιο θεμάτων.",
    porAutor: "από {{autor}}",
    umaCorTrocada: "1 χρώμα αλλαγμένο",
    coresTrocadas: "{{quantas}} χρώματα αλλαγμένα",
    avisoDeCss: "Αυτό το θέμα φέρνει CSS από όποιον το έγραψε, και το CSS πιάνει κάθε γωνιά της οθόνης. Κάντε εισαγωγή μόνο από άτομα που εμπιστεύεστε.",
    soCores: "Αυτό το θέμα αλλάζει μόνο χρώματα. Καθόλου εξωτερικό CSS.",
    aplicar: "Εφαρμογή",
    previaSemMotor: "Η προεπισκόπηση δεν τρέχει τη μηχανή. Εγκαταστήστε το για να τη δείτε.",
    motorAnimado: "{{motor}} με κίνηση",
  },
  sair: "Αποσύνδεση",
  versoes: {
    termos: "Όροι χρήσης",
    privacidade: "Πολιτική απορρήτου",
    copiar: "Κάνε κλικ για αντιγραφή",
    copiado: "Αντιγράφηκε",
  },
  telas: {
    conta: "Ο λογαριασμός μου",
    privacidade: "Απόρρητο",
    conexoes: "Συνδέσεις",
    voz: "Ήχος",
    video: "Βίντεο",
    avisos: "Ειδοποιήσεις",
    aplicativos: "Εφαρμογές",
    aparencia: "Εμφάνιση",
    batePapo: "Συνομιλία",
    acessibilidade: "Προσβασιμότητα",
    idioma: "Γλώσσα",
    aplicativo: "Λήψη της εφαρμογής",
    atalhos: "Συντομεύσεις",
    desktop: "Εφαρμογή υπολογιστή",
    avancado: "Για προχωρημένους",
    servidor: "Διακομιστής",
    comunicado: "Ανακοίνωση συστήματος",
    denuncias: "Αναφορές",
    publicacoes: "Αναπτύξεις",
  },
  grupos: {
    conta: "Λογαριασμός",
    app: "Ρυθμίσεις εφαρμογής",
    desenvolvedor: "Προγραμματιστής",
    administracao: "Διαχείριση",
  },
  secoes: {
    detalhesDeLogin: "Στοιχεία σύνδεσης",
    dispositivos: "Συσκευές",
    usuariosBloqueados: "Αποκλεισμένοι χρήστες",
    aplicativosAutorizados: "Εξουσιοδοτημένες εφαρμογές",
    sessoes: "Συνεδρίες",
    amigosEDms: "Φίλοι και άμεσα μηνύματα",
    compartilhamentoDeAtividade: "Κοινή χρήση δραστηριότητας",
    visibilidadeDoPerfil: "Ορατότητα προφίλ",
    exportarDados: "Εξαγωγή δεδομένων",
    exclusaoDeDados: "Διαγραφή δεδομένων",
    tema: "Θέμα",
    corDeDestaque: "Χρώμα τονισμού",
    interface: "Διεπαφή",
    listaDeCanais: "Λίστα καναλιών",
    zoomDoApp: "Επίπεδο ζουμ της εφαρμογής",
    escalaDaFonte: "Μέγεθος γραμματοσειράς συνομιλίας",
    modoStreamer: "Απόρρητο κατά τη μετάδοση",
    cursores: "Δείκτες",
    movimento: "Κίνηση",
    textoEmVoz: "Κείμενο σε ομιλία",
    teclado: "Πληκτρολόγιο",
    formatoDaHora: "Μορφή ώρας",
    idiomaDaInterface: "Γλώσσα διεπαφής",
    dispositivosDeVoz: "Συσκευές",
    testeDoMicrofone: "Δοκιμή μικροφώνου",
    modoDeEntrada: "Λειτουργία εισόδου",
    sensibilidade: "Ευαισθησία εισόδου",
    qualidade: "Ποιότητα",
    camera: "Κάμερα",
    transmissao: "Μετάδοση",
    exibicao: "Προβολή",
    entrada: "Εισαγωγή",
    midia: "Πολυμέσα",
    geral: "Γενικά",
    preferenciaDeMencao: "Προτίμηση αναφορών",
    sons: "Ήχοι",
  },
};
