export const conversa = {
  lista: {
    carregando: "Φόρτωση μηνυμάτων…",
    carregandoMais: "Φόρτωση…",
    verMais: "Κύλισε προς τα πάνω για να δεις περισσότερα",
    semHistorico: "Το ιστορικό δεν είναι διαθέσιμο",
    semHistoricoDetalhe: "Ο ρόλος σου δεν έχει δικαίωμα να διαβάσει το ιστορικό του #{{canal}}. Τα νέα μηνύματα θα συνεχίσουν να εμφανίζονται όσο είσαι εδώ.",
    boasVindas: "Καλώς ήρθες στο #{{canal}}",
    boasVindasDetalhe: "Εδώ ξεκινά το κανάλι #{{canal}}.",
  },
  data: {
    hoje: "Σήμερα",
    ontem: "Χθες",
    hojeAs: "σήμερα στις {{hora}}",
    ontemAs: "χθες στις {{hora}}",
  },
  digitando: {
    um: "Ο/Η {{nome}} γράφει…",
    dois: "Ο/Η {{primeiro}} και ο/η {{segundo}} γράφουν…",
    varios: "{{quantidade}} άτομα γράφουν…",
  },
  mensagem: {
    usou: "χρησιμοποίησε",
    fixada: "καρφιτσωμένο",
    editado: "(επεξεργασμένο)",
    ignorada: "Μήνυμα από κάποιον που αγνοείς.",
    mostrar: "Εμφάνιση",
    escPara: "Esc για",
    cancelar: "ακύρωση",
    enterParaSalvar: "Enter για αποθήκευση",
    falhou: "Δεν στάλθηκε. Δοκίμασε ξανά",
    naoLidasDaqui: "Μη αναγνωσμένα από εδώ.",
    linkCopiado: "Ο σύνδεσμος αντιγράφηκε.",
    idCopiado: "Το ID αντιγράφηκε.",
    naoDeuParaCopiar: "Το πρόγραμμα περιήγησης δεν επέτρεψε την αντιγραφή.",
    apagarTitulo: "Διαγραφή μηνύματος;",
    apagarDescricao: "Εξαφανίζεται για όλους στο κανάλι. Δεν ανακτάται.",
    apagarAcao: "Διαγραφή",
    citacaoAnexo: "κάνε κλικ για να δεις το συνημμένο",
    citacaoSumiu: "Το αρχικό μήνυμα δεν είναι πια εδώ.",
    reagirCom: "Αντίδραση με {{emoji}} — κράτα πατημένο για σούπερ αντίδραση",
    segureParaSuper: "{{emoji}} — κράτα πατημένο για σούπερ αντίδραση",
  },
  acoes: {
    reagir: "Αντίδραση",
    responder: "Απάντηση",
    encaminhar: "Προώθηση",
    favoritar: "Αποθήκευση μηνύματος",
    tirarDosFavoritos: "Αφαίρεση από τα αποθηκευμένα",
    marcarNaoLida: "Σήμανση ως μη αναγνωσμένο",
    copiarLink: "Αντιγραφή συνδέσμου μηνύματος",
    copiarId: "Αντιγραφή ID μηνύματος",
    fixar: "Καρφίτσωμα μηνύματος",
    desafixar: "Ξεκαρφίτσωμα",
    editar: "Επεξεργασία",
    apagar: "Διαγραφή",
    mais: "Περισσότερα",
    adicionarReacao: "Προσθήκη αντίδρασης",
    superReagirCom: "Σούπερ αντίδραση με {{emoji}}",
    fixarMensagem: "Καρφίτσωμα μηνύματος",
    desafixarMensagem: "Ξεκαρφίτσωμα μηνύματος",
    editarMensagem: "Επεξεργασία μηνύματος",
    apagarMensagem: "Διαγραφή μηνύματος",
  },
  mencao: {
    cargo: "Αναφορά ρόλου",
    pessoa: "Αναφορά",
    alguem: "κάποιος",
    cargoSemNome: "ρόλος",
    here: "Ειδοποιεί όσους είναι συνδεδεμένοι",
    everyone: "Ειδοποιεί όλον τον διακομιστή",
  },
  codigo: {
    copiar: "Αντιγραφή",
    copiado: "Αντιγράφηκε",
    copiarAria: "Αντιγραφή του κώδικα",
    copiadoAria: "Ο κώδικας αντιγράφηκε",
    recolher: "Σύμπτυξη",
    expandir: "Ανάπτυξη",
    verInteiro: "Προβολή όλου του αρχείου",
    maisOpcoes: "Περισσότερες επιλογές",
    baixar: "Λήψη",
  },
  caixa: {
    escrever: "Γράψε στο #{{canal}}",
    escreverSemCanal: "Γράψε ένα μήνυμα",
    semPermissao: "Δεν έχεις δικαίωμα να στέλνεις μηνύματα σε αυτό το κανάλι",
    solteParaAnexar: "Άφησέ το για επισύναψη",
    respondendoPara: "Απάντηση σε",
    vaiNotificar: "Το άτομο θα ειδοποιηθεί",
    naoVaiNotificar: "Το άτομο δεν θα ειδοποιηθεί",
    ligado: "ενεργό",
    desligado: "ανενεργό",
    pararDeResponder: "Ακύρωση απάντησης",
    mais: "Περισσότερα",
    enviarArquivo: "Αποστολή αρχείου",
    criarEnquete: "Δημιουργία δημοσκόπησης",
    expressoes: "Emoji, GIF και αυτοκόλλητα",
    enviar: "Αποστολή",
    aguardandoEnvio: "Αναμονή για τη μεταφόρτωση",
    modoLento: "Αργή λειτουργία ενεργή ({{tempo}})",
    modoLentoDica: "Η αργή λειτουργία είναι στα {{segundos}} δευτ. Περίμενε πριν στείλεις άλλο μήνυμα.",
  },
  anexos: {
    enviando: "Μεταφόρτωση…",
    modificar: "Επεξεργασία {{arquivo}}",
    remover: "Αφαίρεση {{arquivo}}",
    ver: "Προβολή {{arquivo}}",
    mostrarSpoiler: "Εμφάνιση spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Επεξεργασία συνημμένου",
    nomeDoArquivo: "Όνομα αρχείου",
    descricao: "Περιγραφή εναλλακτικού κειμένου",
    descricaoDica: "Περίγραψε αυτό το αρχείο για τους αναγνώστες οθόνης",
    marcarSpoiler: "Σήμανση ως spoiler",
    cancelar: "Ακύρωση",
    salvar: "Αποθήκευση",
  },
  cartao: {
    tocador: "Αναπαραγωγέας",
    abrir: "Άνοιγμα {{destino}}",
    tocar: "Αναπαραγωγή {{titulo}}",
    video: "βίντεο",
    verImagem: "Προβολή εικόνας",
  },
  enquete: {
    titulo: "Δημοσκόπηση",
    encerrada: "Η δημοσκόπηση έκλεισε",
    variasRespostas: "Δημοσκόπηση — πολλές απαντήσεις",
    umVoto: "{{quantidade}} ψήφος",
    votos: "{{quantidade}} ψήφοι",
    umVotoNoTotal: "{{quantidade}} ψήφος συνολικά",
    votosNoTotal: "{{quantidade}} ψήφοι συνολικά",
    encerraEm: "κλείνει στις {{quando}}",
    encerrarAgora: "Κλείσε τώρα",
  },
  fixadas: {
    titulo: "Καρφιτσωμένα μηνύματα",
    vazio: "Αυτό το κανάλι δεν έχει καρφιτσωμένα μηνύματα… ακόμη.",
    desafixar: "Ξεκαρφίτσωμα",
    anexo: "(συνημμένο)",
    enquete: "(δημοσκόπηση)",
    dicaRotulo: "ΜΙΑ ΣΥΜΒΟΥΛΗ:",
    dica: "όποιος έχει το δικαίωμα «Διαχείριση μηνυμάτων» μπορεί να καρφιτσώσει απευθείας από το μενού του μηνύματος.",
  },
  encaminhar: {
    titulo: "Προώθηση μηνύματος",
    paraOnde: "Πού;",
    semTexto: "(μήνυμα χωρίς κείμενο)",
    nenhumLugar: "Δεν υπάρχει μέρος με αυτό το όνομα.",
    canais: "Κανάλια",
    conversas: "Προσωπικά μηνύματα",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Αναζήτηση στο Klipy",
    figurinha: "Αυτοκόλλητο",
    buscarFigurinha: "Βρες το τέλειο αυτοκόλλητο",
    buscarEmoji: "Βρες το τέλειο emoji",
    buscarReacao: "Βρες την τέλεια αντίδραση",
    adicionarEmoji: "Προσθήκη emoji",
    limparBusca: "Καθαρισμός αναζήτησης",
  },
  busca: {
    fechar: "Κλείσιμο αναζήτησης",
    procurando: "Ψάχνω…",
    resultado: "{{quantos}} αποτέλεσμα",
    resultados: "{{quantos}} αποτελέσματα",
    nadaCom: "Τίποτα με {{termo}} εδώ.",
    soOsQuePodeLer: "Η αναζήτηση κοιτάζει μόνο τα κανάλια που μπορείς να διαβάσεις.",
  },
  entrada: {
    titulo: "Εισερχόμενα",
    naoLidas: "Μη αναγνωσμένα",
    salvas: "Αποθηκευμένα",
    mencoes: "Αναφορές",
    fimTitulo: "Έφτασες στο τέλος",
    fimDetalhe: "Δεν έμεινε τίποτα για διάβασμα. Όταν έρθει νέο μήνυμα, θα εμφανιστεί εδώ.",
    semSalvosTitulo: "Κανένα αποθηκευμένο",
    semSalvosDetalhe: "Κράτα το Shift και κάνε κλικ στον σελιδοδείκτη ενός μηνύματος για να το κρατήσεις και να το δεις αργότερα.",
    tirarDosSalvos: "Αφαίρεση από τα αποθηκευμένα",
    semMencoesTitulo: "Καμία αναφορά ακόμη",
    semMencoesDetalhe: "Οι αναφορές σε σένα εμφανίζονται εδώ για τις τελευταίες 7 ημέρες.",
  },
  forum: {
    descricao: "Κάθε θέμα γίνεται ξεχωριστή συζήτηση — καλό για την απορία που δεν πρέπει να χαθεί μέσα στην κουβέντα.",
    novoAssunto: "Νέο θέμα",
    vazio: "Κανένα θέμα ακόμη. Ξεκίνα το πρώτο και η συζήτηση μένει τακτοποιημένη από την αρχή.",
    titulo: "Τίτλος",
    doQueSeTrata: "Για τι πρόκειται;",
    primeiraMensagem: "Πρώτο μήνυμα",
    conteDoCaso: "Πες την ιστορία",
  },
};
