export const perfil = {
  carregando: "Φόρτωση…",
  editar: "Επεξεργασία προφίλ",
  mensagem: "Μήνυμα",
  abrirConversa: "Άνοιγμα συνομιλίας",
  verCompleto: "Πλήρες προφίλ",
  convidarParaServidor: "Πρόσκληση στον διακομιστή",
  semServidores: "Δεν έχεις διακομιστές",
  conviteEnviado: "Η πρόσκληση στάλθηκε στον/στην {{nome}}.",
  moderador: "Άνοιγμα σε προβολή συντονιστή",
  mais: "Περισσότερα",
  ignorar: "Αγνόηση",
  deixarDeIgnorar: "Διακοπή αγνόησης",
  copiarId: "Αντιγραφή ID χρήστη",
  idCopiado: "Το ID αντιγράφηκε.",
  conexoes: "Συνδέσεις",
  membroDesde: "Μέλος από",
  sobre: "Σχετικά",
  cargosTitulo: "Ρόλοι",
  visaoGeral: "Επισκόπηση",
  amigosEmComum: "Κοινοί φίλοι ({{quantidade}})",
  servidoresEmComum: "Κοινοί διακομιστές ({{quantidade}})",
  amizade: {
    amigo: "Φίλος",
    pedidoEnviado: "Το αίτημα φιλίας στάλθηκε",
    respondaAbaixo: "Σου έστειλε αίτημα — απάντησε παρακάτω",
    adicionar: "Προσθήκη φίλου",
    teMandouPedido: "Σου έστειλε αίτημα φιλίας",
    aceitar: "Αποδοχή",
    desfazer: "Κατάργηση φιλίας",
    desfazerTitulo: "Να αφαιρεθεί ο/η {{nome}} από τους φίλους σου;",
    desfazerDescricao: "Παύετε να είστε φίλοι. Η ιδιωτική συνομιλία μένει στο ιστορικό, και μπορείς να τον προσθέσεις ξανά αργότερα.",
    bloquear: "Αποκλεισμός",
    bloquearTitulo: "Να αποκλειστεί ο/η {{nome}};",
    bloquearDescricao: "Παύετε να είστε φίλοι, η ιδιωτική συνομιλία σταματά να δέχεται μηνύματα και δεν μπορεί πλέον να σου στείλει αίτημα φιλίας.",
    linkCopiado: "Δεν είστε φίλοι — ο σύνδεσμος αντιγράφηκε για να τον στείλεις εσύ.",
  },
  recado: {
    escrever: "Γράψε στον/στην @{{usuario}}",
    enviar: "Αποστολή",
    enviada: "Το μήνυμα στάλθηκε",
    falhou: "Δεν στάλθηκε. Δοκίμασε από τη συνομιλία.",
  },
  cartao: {
    trocarFaixa: "Αλλαγή banner της κάρτας",
    trocarFaixaCurto: "Αλλαγή banner",
    trocarFoto: "Αλλαγή φωτογραφίας προφίλ",
    trocarFotoCurto: "Αλλαγή φωτογραφίας",
    suaEtiqueta: "Η ετικέτα σου",
    editarEtiqueta: "Κάνε κλικ για να επεξεργαστείς την ετικέτα σου",
    conteAlgo: "Πες μας κάτι για σένα",
    adicionarStatus: "Προσθήκη κατάστασης",
    adicionarDescricao: "Κάνε κλικ για να προσθέσεις περιγραφή",
    cargo: "Ρόλος",
    cargos: "Ρόλοι",
    cargosCom: "Ρόλοι — {{quantidade}}",
    tirarCargo: "Αφαίρεση του ρόλου {{cargo}}",
  },
  cargos: {
    adicionar: "Προσθήκη ρόλου",
    procurar: "Αναζήτηση ρόλου",
  },
  etiqueta: {
    escolher: "Επιλογή ετικέτας διακομιστή",
    nenhuma: "Καμία ετικέτα διακομιστή",
    semEtiqueta: "Κανένας από τους διακομιστές σου δεν έχει ετικέτα",
  },
  emblemas: {
    doServidor: "Διακριτικά αυτού του διακομιστή",
    limite: "Μπορείς να φοράς έως {{quantidade}} διακριτικά.",
  },
  nota: {
    vazia: "Κάνε κλικ για να σημειώσεις κάτι",
    rotulo: "Σημείωση (τη βλέπεις μόνο εσύ)",
  },
  status: {
    titulo: "Κατάσταση",
    definir: "Όρισε την κατάστασή σου",
    escolherEmoji: "Επιλογή emoji",
    tirarEmoji: "Αφαίρεση του emoji",
    oQuePensa: "Τι σκέφτεσαι;",
    limparAgora: "Καθαρισμός κατάστασης τώρα",
    naoLimpar: "Χωρίς καθαρισμό",
    limpar30m: "Καθαρισμός σε 30 λεπτά",
    limpar1h: "Καθαρισμός σε 1 ώρα",
    limpar4h: "Καθαρισμός σε 4 ώρες",
    limparHoje: "Καθαρισμός σήμερα",
    limparAmanha: "Καθαρισμός αύριο",
    comHora: "{{prazo}} στις {{hora}}",
  },
  presenca: {
    disponivel: "Διαθέσιμος",
    ausente: "Απών",
    naoPerturbar: "Μην ενοχλείτε",
    naoPerturbarDetalhe: "Δεν λαμβάνεις ειδοποίηση για νέα μηνύματα",
    invisivel: "Αόρατος",
    invisivelDetalhe: "Στους άλλους φαίνεσαι εκτός σύνδεσης",
  },
  menu: {
    mudarDeConta: "Αλλαγή λογαριασμού",
    gerenciarContas: "Διαχείριση λογαριασμών",
  },
  editor: {
    decoracao: "Αλλαγή διακόσμησης άβαταρ",
    naoSalvo: "Μην ξεχάσεις να αποθηκεύσεις τις αλλαγές σου!",
    principal: "Κύριο προφίλ",
  },
};
