export const amizades = {
  ativosAgora: "Sada aktivni",
  procurando: "Gledamo tko je tu…",
  tudoTranquilo: "Za sada je mirno…",
  tudoTranquiloDetalhe: "Kad se ti ili prijatelj uključite u poziv, pojavit će se ovdje — i pridružuješ se jednim klikom.",
  emVoz: "Na glasovnom",
  voce: "Ti",
  soVoce: "Samo ti",
  pessoas: "{{quantas}} osoba",
  voltarParaChamada: "Natrag na poziv",
  entrarNaChamada: "Pridruži se pozivu",
  abrirCanal: "Otvori {{canal}} na {{servidor}}",
  mensagensDiretas: "Izravne poruke",
  encontreConversa: "Pronađi razgovor",
  amigos: "Prijatelji",
  conversas: "Razgovori",
  semConversas: "Još nema razgovora. Dodaj prijatelja da počneš.",
  semConversaComEsseNome: "Nema razgovora s tim imenom.",
  abrirMenu: "Otvori poslužitelje i razgovore",
  solicitacoes: "Zahtjevi za poruku",
  pedidos: "Zahtjevi",
  spam: "Spam",
  pedidosPendentes: "Zahtjevi na čekanju",
  marcadosComoSpam: "Označeni kao spam",
  aceitar: "Prihvati",
  ignorar: "Zanemari",
  marcarSpam: "Označi kao spam",
  semPedidos: "Nema zahtjeva na čekanju.",
  semPedidosDetalhe: "Tko ti nije prijatelj, ali dijeli poslužitelj s tobom, stiže ovdje prije nego dođe do tvojih razgovora.",
  semSpam: "Ništa nije označeno kao spam.",
  semSpamDetalhe: "Ono što filtar spama izdvoji, ili što sam označiš, ostaje na ovoj kartici.",
  umServidorEmComum: "1 zajednički poslužitelj",
  servidoresEmComum: "Zajedničkih poslužitelja: {{quantos}}",
  semServidoresEmComum: "Nema zajedničkih poslužitelja",
};
