export const chamada = {
  conectando: "Povezivanje s pozivom…",
  naoEntrou: "Nije uspjelo pridruživanje pozivu",
  sair: "Napusti poziv",
  sairDaVoz: "Napusti glasovni poziv",
  desconectar: "Odspoji",
  voltar: "Natrag na poziv",
  voltarAosQuadros: "Natrag na pločice poziva",
  fecharChat: "Zatvori razgovor",
  mostrarChat: "Prikaži chat",
  convidar: "Pozovi u poziv",
  carregandoPrevia: "Učitavanje pretpregleda…",
  maisOpcoes: "Više opcija",
  deVideo: "Videopoziv",
  deVoz: "Glasovni poziv",
  alguem: "Netko",
  volume: {
    entrada: "Glasnoća ulaza",
    saida: "Glasnoća izlaza",
    live: "Glasnoća prijenosa",
    liveComPorcento: "Glasnoća prijenosa ({{porcento}}%)",
    liveSemSom: "Prijenos bez zvuka",
  },
  aparelhos: {
    entrada: "Ulazni uređaj",
    saida: "Izlazni uređaj",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Izlaz",
    oDoSistema: "Sustavski",
    aDoSistema: "Sustavska",
    semEscolhaDeSaida: "Ovaj preglednik ne dopušta odabir izlaza — odlučuje sustav.",
    espelhar: "Zrcali moju kameru",
    configEntrada: "Postavke ulaza",
    configSaida: "Postavke izlaza",
    configCamera: "Postavke kamere",
    configAudioEVideo: "Postavke zvuka i videa",
  },
  tela: {
    compartilhar: "Podijeli zaslon",
    compartilharAcao: "Podijeli",
    cancelar: "Odustani",
    telas: "Zasloni",
    janelas: "Prozori",
    somDoComputador: "Ponesi i zvuk računala",
    somDoSistema: "Ponesi i zvuk sustava",
    configCompartilhamento: "Postavke dijeljenja",
    mostrarSemVideo: "Prikaži one bez videa",
    semFontes: "Sustav nije vratio nijedan zaslon ni prozor za dijeljenje.",
    pararDeCompartilhar: "Prestani dijeliti",
    encerrarTransmissao: "Završi prijenos",
  },
  live: {
    etiqueta: "Uživo",
    etiquetaMaiuscula: "UŽIVO",
    assistir: "Gledaj prijenos",
    assistirPessoa: "Gledaj {{nome}}",
    pararDeAssistir: "Prestani gledati",
  },
  membro: {
    mudarMeuApelido: "Promijeni moj nadimak",
    meuMicrofone: "Moj mikrofon",
    ouvirChamada: "Slušaj poziv",
    copiarMeuId: "Kopiraj moj ID",
    idCopiado: "ID kopiran.",
    mensagem: "Poruka",
    silenciar: "Utišaj",
    alterarApelido: "Promijeni nadimak",
    cargos: "Uloge",
    semCargo: "Nijedna uloga nije stvorena",
    moverPara: "Premjesti u",
    silenciarNoServidor: "Utišaj glas na poslužitelju",
    desativarAudioNoServidor: "Isključi zvuk na poslužitelju",
    desconectar: "Odspoji",
    apelidoTitulo: "Tvoj nadimak na ovom poslužitelju",
    apelidoDeAlguem: "Nadimak korisnika {{nome}}",
    apelidoCampo: "Nadimak",
    apelidoDicaPropria: "Vrijedi samo ovdje. Ostavi prazno da se vrati tvoje uobičajeno ime.",
    apelidoDicaDeOutro: "Vrijedi samo na ovom poslužitelju. Ostavi prazno da se vrati izvorno ime.",
  },
  detalhes: {
    abrir: "Pojedinosti glasa",
    titulo: "Pojedinosti Glasa",
    conexao: "Veza",
    pingMedio: "Prosječni ping",
    ultimoPing: "Zadnji ping",
    perda: "Gubitak poslanih paketa",
    medindo: "Mjerenje…",
    criptografado: "Šifrirano sve do poslužitelja (DTLS-SRTP)",
    explicacao: "Iznad 250 ms kašnjenje se čuje u razgovoru — ljudi si počnu upadati u riječ. Gubitak paketa iznad 10% čini glas robotskim. U oba slučaja problem je gotovo uvijek između tebe i interneta: probaj kabel umjesto Wi-Fija ili ponovno pokreni usmjerivač.",
  },
  microfone: {
    bloqueado: "Mikrofon je blokiran — samo slušaš. Dopusti pristup u dopuštenjima preglednika.",
    bloqueadoNoMac: "macOS blokira mikrofon. Označi",
    caminhoNoMac: "Postavke sustava → Privatnost i sigurnost → Mikrofon",
    abrirAjustes: "Otvori postavke",
    vaiReabrir: "macOS će tražiti da ponovno otvoriš aplikaciju.",
    naoAbriu: "Mikrofon se nije otvorio — samo slušaš. Provjeri uređaj u Postavke → Glas i video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS još nije dopustio snimanje zaslona. Bez toga dijeljenje izlazi crno.",
    marque: "Označi",
    reabra: "u Snimanju zaslona i ponovno otvori aplikaciju.",
    jaMarcado: "Ako je već označeno, dopuštenje je zastarjelo pri zadnjem ažuriranju: odznači, označi ponovno i otvori aplikaciju iznova.",
  },
  ruido: {
    titulo: "Uklanjanje šuma",
    explicacao: "Ukloni pozadinski šum iz svog glasa. Probaj pljesnuti ili povući tipkovnicu dok govoriš — oni u pozivu čuju samo tebe.",
    semSuporte: "Ovaj preglednik ne pokreće napredno uklanjanje. Ono preglednikovo i dalje vrijedi, ali je slabije.",
    aplicando: "Primjenjuje se na poziv…",
    faleParaTestar: "Govori za test",
    verdeQuandoPassa: "Zeleno kad tvoj glas prolazi.",
    teOuvindo: "Upravo te čuju.",
    feitoCom: "Napravljeno s",
    aquiNoAparelho: ", ovdje na tvom uređaju",
    ajustes: "Postavke",
  },
  permissoes: {
    titulo: "macOS dopuštenja",
    detalhe: "macOS pita samo jednom, a poslije se to mijenja samo u njegovoj ploči. Ovdje vidiš što vrijedi i rješavaš ono što nedostaje.",
    concedida: "Odobreno",
    negada: "Odbijeno",
    naoPedida: "Nije zatraženo",
    permitir: "Dopusti",
    abrirAjustes: "Otvori postavke",
    microfone: "Mikrofon",
    microfoneDetalhe: "Govoriti u pozivima i testirati svoj ulaz.",
    camera: "Kamera",
    cameraDetalhe: "Uključiti video u pozivu.",
    tela: "Snimanje zaslona",
    telaDetalhe: "Dijeliti zaslon i prozore.",
    monitoramento: "Nadzor ulaza",
    monitoramentoDetalhe: "Koristiti pritisni-za-govor i kad je Gravaê u pozadini.",
  },
  jaConectado: {
    titulo: "Već si u ovom pozivu",
    trazer: "Prebaci poziv ovamo",
    deixar: "Ostavi kako jest",
    detalhe: "Prebaciš li ga ovamo, druga strana ispada iz poziva — tvoj račun je na jednom mjestu odjednom.",
  },
};
