export const comum = {
  carregando: "Učitavanje…",
  salvar: "Spremi",
  salvando: "Spremanje…",
  descartar: "Odbaci",
  redefinir: "Vrati",
  naoSalvo: "Imaš nespremljene promjene.",
  fechar: "Zatvori",
  criar: "Stvori",
  nome: "Naziv",
  emoji: "Emoji",
  previa: "Pregled",
  cancelar: "Odustani",
  enviar: "Pošalji",
  apagar: "Obriši",
  excluir: "Obriši",
  remover: "Ukloni",
  trocar: "Promijeni",
};
