export const configuracoes = {
  telas: {
    conta: "Moj račun",
    privacidade: "Privatnost",
    conexoes: "Veze",
    voz: "Zvuk",
    video: "Videozapis",
    avisos: "Obavijesti",
    aplicativos: "Aplikacije",
    aparencia: "Izgled",
    batePapo: "Chat",
    acessibilidade: "Pristupačnost",
    idioma: "Jezik",
    aplicativo: "Preuzmi aplikaciju",
    servidor: "Poslužitelj",
  },
  grupos: {
    conta: "Račun",
    app: "Postavke aplikacije",
    desenvolvedor: "Razvojni programer",
    administracao: "Administracija",
  },
  secoes: {
    detalhesDeLogin: "Podaci za prijavu",
    dispositivos: "Uređaji",
    usuariosBloqueados: "Blokirani korisnici",
    aplicativosAutorizados: "Ovlaštene aplikacije",
    sessoes: "Sesije",
    amigosEDms: "Prijatelji i izravne poruke",
    compartilhamentoDeAtividade: "Dijeljenje aktivnosti",
    visibilidadeDoPerfil: "Vidljivost profila",
    exportarDados: "Izvezi podatke",
    exclusaoDeDados: "Izbriši podatke",
    tema: "Tema",
    corDeDestaque: "Boja naglaska",
    interface: "Sučelje",
    listaDeCanais: "Popis kanala",
    zoomDoApp: "Razina zumiranja aplikacije",
    escalaDaFonte: "Veličina fonta chata",
    modoStreamer: "Privatnost pri emitiranju",
    movimento: "Kretanje",
    textoEmVoz: "Tekst u govor",
    teclado: "Tipkovnica",
    formatoDaHora: "Format vremena",
    idiomaDaInterface: "Jezik sučelja",
    dispositivosDeVoz: "Uređaji",
    testeDoMicrofone: "Test mikrofona",
    modoDeEntrada: "Način unosa",
    sensibilidade: "Osjetljivost unosa",
    qualidade: "Kvaliteta",
    camera: "Kamera",
    transmissao: "Emitiranje",
    exibicao: "Prikaz",
    entrada: "Unos",
    midia: "Mediji",
    geral: "Općenito",
    preferenciaDeMencao: "Postavke spominjanja",
    sons: "Zvukovi",
  },
};
