export const configuracoes = {
  efeitos: {
    titulo: "Efekti pokazivača",
    detalhe: "Trag i iskre crtaju se preko aplikacije. Dolaze isključeni i sami se gase ako si tražio manje animacije.",
    rastro: "Trag pokazivača",
    rastroDetalhe: "Crta koja prati pokazivač i blijedi iza njega.",
    faisca: "Iskre pri kliku",
    faiscaDetalhe: "Kratke crtice koje izlijeću s mjesta klika.",
    cor: "Boja",
    espessura: "Debljina",
    comprimento: "Duljina",
    tamanho: "Veličina",
    quantidade: "Količina",
  },
  email: {
    verificarTitulo: "Potvrdi svoj e-mail",
    verificarDetalhe: "Neke zajednice puštaju pisati samo one koji su potvrdili. Jedan klik.",
    enviar: "Pošalji poveznicu",
    enviado: "Pogledaj pristiglu poštu. Poveznica vrijedi jedan dan.",
    falhou: "E-mail nije bilo moguće poslati.",
    confirmado: "E-mail potvrđen",
    confirmadoDetalhe: "Gotovo. Sad pišeš u svakoj zajednici koja to traži.",
    linkIncompleto: "Nepotpuna poveznica",
    linkIncompletoDetalhe: "U adresi nedostaje kod. Otvori poveznicu izravno iz e-maila.",
    confirmando: "Potvrđuje se…",
    expirou: "Ova je poveznica već iskorištena ili joj je isteklo vrijeme.",
    irParaOApp: "Idi u aplikaciju",
  },
  tema: {
    indisponivel: "Tema nije dostupna",
    indisponivelDetalhe: "Onaj tko ju je objavio obrisao ju je, ili je poveznica kriva.",
    indisponivelLinha: "Tema nije dostupna. Onaj tko ju je objavio obrisao ju je, ili je poveznica kriva.",
    importar: "Uvezi temu",
    importarCurto: "Uvezi",
    importarDetalhe: "Ovo zamjenjuje temu koju sada imaš. Poslije je možeš urediti u Postavke > Izgled > Studio tema.",
    porAutor: "od {{autor}}",
    umaCorTrocada: "1 zamijenjena boja",
    coresTrocadas: "{{quantas}} zamijenjenih boja",
    avisoDeCss: "Ova tema nosi CSS onoga tko ju je napisao, a CSS dira svaki kutak zaslona. Uvozi samo od ljudi kojima vjeruješ.",
    soCores: "Ova tema mijenja samo boje. Nikakav vanjski CSS.",
    verCss: "Prikaži CSS",
    esconderCss: "Sakrij CSS",
    aplicar: "Primijeni",
    previaSemMotor: "Pretpregled ne pokreće motor. Instaliraj da ga vidiš.",
    motorAnimado: "{{motor}} animirano",
  },
  sair: "Odjava",
  versoes: {
    termos: "Uvjeti pružanja usluge",
    privacidade: "Pravila privatnosti",
    copiar: "Klikni za kopiranje",
    copiado: "Kopirano",
  },
  subscription: {
    seePlans: "Pogledaj planove",
    upgradeSubtitle: "Veća ograničenja i ekskluzivne značajke za pisanje, slanje datoteka i prijenos.",
    perMonth: "mjesečno",
    perYear: "godišnje",
    save: "Uštedite {{percent}} %",
    howToPay: "Kako želite platiti?",
    legal: "Povrat možete zatražiti u roku od 7 dana od plaćanja. Plaćanje obrađuje Stripe; nikad ne vidimo broj vaše kartice.",
    compare: "Besplatno ili Infinity",
    featureColumn: "Značajka",
    freeColumn: "Besplatno",
    messageRow: "Ograničenje znakova poruke",
    attachmentRow: "Veličina datoteke za slanje",
    screenRow: "Kvaliteta videa",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Već imate Infinity do {{date}}.",
    upsell: "Povećajte ograničenje uz Infinity",
    screenUpsell: "Bolja kvaliteta uz Infinity",
    free: "Koristite besplatni plan.",
    activeUntil: "Infinity aktivan do {{date}}.",
    renews: "Automatski se obnavlja {{date}}.",
    endsAt: "Pretplata je otkazana i završava {{date}}.",
    pastDue: "Posljednja naplata nije uspjela. Ažurirajte karticu da ne izgubite Infinity.",
    waiting: "Potvrđivanje plaćanja…",
    subscribe: "Pretplati se",
    monthly: "Mjesečno",
    yearly: "Godišnje",
    automatic: "Kartica",
    manage: "Upravljanje plaćanjem",
    refund: "Zatraži povrat",
    refundDetail: "Možete odustati u roku od 7 dana od plaćanja: {{amount}}, do {{date}}.",
    refundConfirm: "Zatražiti povrat?",
    refundConfirmDetail: "Novac se vraća istim načinom plaćanja, a Infinity odmah prestaje.",
    refunded: "Povrat zatražen.",
    unavailable: "Pretplata još nije dostupna.",
    success: "Plaćanje primljeno. Hvala!",
    canceled: "Plaćanje otkazano.",
    error: "Nešto nije u redu. Pokušajte ponovno.",
    no: "Ne",
    tagRow: "Vlastita korisnička oznaka",
    guildProfilesRow: "Profili po zajednici",
    badgeRow: "Značka profila",
    communitiesRow: "Zajednice",
    savedRow: "Spremljene poruke",
    animatedEmojiRow: "Animirani emojiji",
    expressionsRow: "Emojiji i naljepnice odasvud",
    animatedProfileRow: "Animirani avatari i banneri profila",
    earlyAccessRow: "Rani pristup novostima",
    themesRow: "Vlastite teme",
    pixOption: "Pix",
    pixHint: "Otvorite aplikaciju banke, odaberite Pix i skenirajte QR kod ili kopirajte kod.",
    pixQrAlt: "Pix QR kod",
    pixCopy: "Kopiraj Pix kod",
    pixCopied: "Pix kod kopiran",
    pixWaiting: "Čeka se plaćanje",
    pixExpiresIn: "istječe za {{time}}",
    pixExpired: "Ovaj Pix je istekao. Stvorite novi za nastavak.",
    pixNew: "Stvori novi Pix",
    pixPaid: "Pix primljen! Infinity je aktivan.",
    forMe: "Za mene",
    asGift: "Na poklon",
    buyGift: "Kupi poklon",
    giftReady: "Poklon je spreman! Kopiraj poveznicu i pošalji kome želiš.",
    giftClaimed: "Poklon iskorišten! Infinity je na tvom računu.",
    gifts: "Pokloni",
    giftsEmpty: "Još nisi kupio nijedan poklon.",
    giftCode: "Kod poklona",
    giftRedeem: "Iskoristi",
    giftCopyLink: "Kopiraj poveznicu",
    giftLinkCopied: "Poveznica kopirana",
    giftClaimedBy: "iskoristio {{name}}",
    giftHint: "Imaš kod poklona? Iskoristi ga ovdje. Kupljeni pokloni su ispod.",
    cardPaid: "Plaćanje odobreno! Vaš Infinity je aktivan.",
    payAmount: "Plati {{amount}}",
  },
  telas: {
    subscription: "Infinity",
    conta: "Moj račun",
    privacidade: "Privatnost",
    conexoes: "Veze",
    voz: "Zvuk",
    video: "Videozapis",
    avisos: "Obavijesti",
    aplicativos: "Aplikacije",
    aparencia: "Izgled",
    batePapo: "Chat",
    acessibilidade: "Pristupačnost",
    idioma: "Jezik",
    aplicativo: "Preuzmi aplikaciju",
    atalhos: "Prečaci",
    desktop: "Aplikacija za računalo",
    avancado: "Napredno",
    servidor: "Poslužitelj",
    comunicado: "Obavijest sustava",
    denuncias: "Prijave",
    publicacoes: "Postavljanja",
  },
  grupos: {
    conta: "Račun",
    app: "Postavke aplikacije",
    desenvolvedor: "Razvojni programer",
    administracao: "Administracija",
  },
  secoes: {
    detalhesDeLogin: "Podaci za prijavu",
    dispositivos: "Uređaji",
    usuariosBloqueados: "Blokirani korisnici",
    aplicativosAutorizados: "Ovlaštene aplikacije",
    sessoes: "Sesije",
    amigosEDms: "Prijatelji i izravne poruke",
    compartilhamentoDeAtividade: "Dijeljenje aktivnosti",
    visibilidadeDoPerfil: "Vidljivost profila",
    exportarDados: "Izvezi podatke",
    exclusaoDeDados: "Izbriši podatke",
    tema: "Tema",
    corDeDestaque: "Boja naglaska",
    interface: "Sučelje",
    listaDeCanais: "Popis kanala",
    zoomDoApp: "Razina zumiranja aplikacije",
    escalaDaFonte: "Veličina fonta chata",
    modoStreamer: "Privatnost pri emitiranju",
    cursores: "Pokazivači",
    movimento: "Kretanje",
    textoEmVoz: "Tekst u govor",
    teclado: "Tipkovnica",
    formatoDaHora: "Format vremena",
    idiomaDaInterface: "Jezik sučelja",
    dispositivosDeVoz: "Uređaji",
    testeDoMicrofone: "Test mikrofona",
    modoDeEntrada: "Način unosa",
    sensibilidade: "Osjetljivost unosa",
    qualidade: "Kvaliteta",
    camera: "Kamera",
    transmissao: "Emitiranje",
    exibicao: "Prikaz",
    entrada: "Unos",
    midia: "Mediji",
    geral: "Općenito",
    preferenciaDeMencao: "Postavke spominjanja",
    sons: "Zvukovi",
  },
};
