export const configuracoes = {
  efeitos: {
    titulo: "Efekti pokazivača",
    detalhe: "Trag i iskre crtaju se preko aplikacije. Dolaze isključeni i sami se gase ako si tražio manje animacije.",
    rastro: "Trag pokazivača",
    rastroDetalhe: "Crta koja prati pokazivač i blijedi iza njega.",
    faisca: "Iskre pri kliku",
    faiscaDetalhe: "Kratke crtice koje izlijeću s mjesta klika.",
    cor: "Boja",
    espessura: "Debljina",
    comprimento: "Duljina",
    tamanho: "Veličina",
    quantidade: "Količina",
  },
  email: {
    verificarTitulo: "Potvrdi svoj e-mail",
    verificarDetalhe: "Neke zajednice puštaju pisati samo one koji su potvrdili. Jedan klik.",
    enviar: "Pošalji poveznicu",
    enviado: "Pogledaj pristiglu poštu. Poveznica vrijedi jedan dan.",
    falhou: "E-mail nije bilo moguće poslati.",
    confirmado: "E-mail potvrđen",
    confirmadoDetalhe: "Gotovo. Sad pišeš u svakoj zajednici koja to traži.",
    linkIncompleto: "Nepotpuna poveznica",
    linkIncompletoDetalhe: "U adresi nedostaje kod. Otvori poveznicu izravno iz e-maila.",
    confirmando: "Potvrđuje se…",
    expirou: "Ova je poveznica već iskorištena ili joj je isteklo vrijeme.",
    irParaOApp: "Idi u aplikaciju",
  },
  tema: {
    indisponivel: "Tema nije dostupna",
    indisponivelDetalhe: "Onaj tko ju je objavio obrisao ju je, ili je poveznica kriva.",
    indisponivelLinha: "Tema nije dostupna. Onaj tko ju je objavio obrisao ju je, ili je poveznica kriva.",
    importar: "Uvezi temu",
    importarCurto: "Uvezi",
    importarDetalhe: "Ovo zamjenjuje temu koju sada imaš. Poslije je možeš urediti u Postavke > Izgled > Studio tema.",
    porAutor: "od {{autor}}",
    umaCorTrocada: "1 zamijenjena boja",
    coresTrocadas: "{{quantas}} zamijenjenih boja",
    avisoDeCss: "Ova tema nosi CSS onoga tko ju je napisao, a CSS dira svaki kutak zaslona. Uvozi samo od ljudi kojima vjeruješ.",
    soCores: "Ova tema mijenja samo boje. Nikakav vanjski CSS.",
    aplicar: "Primijeni",
    previaSemMotor: "Pretpregled ne pokreće motor. Instaliraj da ga vidiš.",
    motorAnimado: "{{motor}} animirano",
  },
  sair: "Odjava",
  versoes: {
    termos: "Uvjeti pružanja usluge",
    privacidade: "Pravila privatnosti",
    copiar: "Klikni za kopiranje",
    copiado: "Kopirano",
  },
  telas: {
    conta: "Moj račun",
    privacidade: "Privatnost",
    conexoes: "Veze",
    voz: "Zvuk",
    video: "Videozapis",
    avisos: "Obavijesti",
    aplicativos: "Aplikacije",
    aparencia: "Izgled",
    batePapo: "Chat",
    acessibilidade: "Pristupačnost",
    idioma: "Jezik",
    aplicativo: "Preuzmi aplikaciju",
    atalhos: "Prečaci",
    desktop: "Aplikacija za računalo",
    avancado: "Napredno",
    servidor: "Poslužitelj",
    comunicado: "Obavijest sustava",
    denuncias: "Prijave",
    publicacoes: "Postavljanja",
  },
  grupos: {
    conta: "Račun",
    app: "Postavke aplikacije",
    desenvolvedor: "Razvojni programer",
    administracao: "Administracija",
  },
  secoes: {
    detalhesDeLogin: "Podaci za prijavu",
    dispositivos: "Uređaji",
    usuariosBloqueados: "Blokirani korisnici",
    aplicativosAutorizados: "Ovlaštene aplikacije",
    sessoes: "Sesije",
    amigosEDms: "Prijatelji i izravne poruke",
    compartilhamentoDeAtividade: "Dijeljenje aktivnosti",
    visibilidadeDoPerfil: "Vidljivost profila",
    exportarDados: "Izvezi podatke",
    exclusaoDeDados: "Izbriši podatke",
    tema: "Tema",
    corDeDestaque: "Boja naglaska",
    interface: "Sučelje",
    listaDeCanais: "Popis kanala",
    zoomDoApp: "Razina zumiranja aplikacije",
    escalaDaFonte: "Veličina fonta chata",
    modoStreamer: "Privatnost pri emitiranju",
    cursores: "Pokazivači",
    movimento: "Kretanje",
    textoEmVoz: "Tekst u govor",
    teclado: "Tipkovnica",
    formatoDaHora: "Format vremena",
    idiomaDaInterface: "Jezik sučelja",
    dispositivosDeVoz: "Uređaji",
    testeDoMicrofone: "Test mikrofona",
    modoDeEntrada: "Način unosa",
    sensibilidade: "Osjetljivost unosa",
    qualidade: "Kvaliteta",
    camera: "Kamera",
    transmissao: "Emitiranje",
    exibicao: "Prikaz",
    entrada: "Unos",
    midia: "Mediji",
    geral: "Općenito",
    preferenciaDeMencao: "Postavke spominjanja",
    sons: "Zvukovi",
  },
};
