export const conversa = {
  lista: {
    carregando: "Učitavanje poruka…",
    carregandoMais: "Učitavanje…",
    verMais: "Pomakni se gore da vidiš više",
    semHistorico: "Povijest nije dostupna",
    semHistoricoDetalhe: "Tvoja uloga nema dopuštenje čitati povijest kanala #{{canal}}. Nove poruke i dalje će se pojavljivati dok si ovdje.",
    boasVindas: "Dobro došao na #{{canal}}",
    boasVindasDetalhe: "Ovo je početak kanala #{{canal}}.",
  },
  data: {
    hoje: "Danas",
    ontem: "Jučer",
    hojeAs: "danas u {{hora}}",
    ontemAs: "jučer u {{hora}}",
  },
  digitando: {
    um: "{{nome}} piše…",
    dois: "{{primeiro}} i {{segundo}} pišu…",
    varios: "{{quantidade}} osoba piše…",
  },
  mensagem: {
    usou: "upotrijebio je",
    fixada: "prikvačeno",
    editado: "(uređeno)",
    ignorada: "Poruka od nekoga koga ignoriraš.",
    mostrar: "Prikaži",
    escPara: "Esc za",
    cancelar: "odustajanje",
    enterParaSalvar: "Enter za spremanje",
    falhou: "Nije poslano. Pokušaj ponovno",
    naoLidasDaqui: "Nepročitano odavde.",
    linkCopiado: "Poveznica je kopirana.",
    idCopiado: "ID je kopiran.",
    naoDeuParaCopiar: "Tvoj preglednik nije dopustio kopiranje.",
    apagarTitulo: "Izbrisati poruku?",
    apagarDescricao: "Nestaje svima na kanalu. Ne može se vratiti.",
    apagarAcao: "Izbriši",
    citacaoAnexo: "klikni da vidiš privitak",
    citacaoSumiu: "Izvorne poruke više nema ovdje.",
    reagirCom: "Reagiraj s {{emoji}} — drži za super reakciju",
    segureParaSuper: "{{emoji}} — drži za super reakciju",
  },
  acoes: {
    reagir: "Reagiraj",
    responder: "Odgovori",
    encaminhar: "Proslijedi",
    favoritar: "Spremi poruku",
    tirarDosFavoritos: "Ukloni iz spremljenih",
    marcarNaoLida: "Označi kao nepročitano",
    copiarLink: "Kopiraj poveznicu poruke",
    copiarId: "Kopiraj ID poruke",
    fixar: "Prikvači poruku",
    desafixar: "Otkvači",
    editar: "Uredi",
    apagar: "Izbriši",
    mais: "Više",
    adicionarReacao: "Dodaj reakciju",
    superReagirCom: "Super reakcija s {{emoji}}",
    fixarMensagem: "Prikvači poruku",
    desafixarMensagem: "Otkvači poruku",
    editarMensagem: "Uredi poruku",
    apagarMensagem: "Izbriši poruku",
  },
  mencao: {
    cargo: "Spominjanje uloge",
    pessoa: "Spominjanje",
    alguem: "netko",
    cargoSemNome: "uloga",
    here: "Obavještava one koji su na mreži",
    everyone: "Obavještava cijeli poslužitelj",
  },
  codigo: {
    copiar: "Kopiraj",
    copiado: "Kopirano",
    copiarAria: "Kopiraj kôd",
    copiadoAria: "Kôd je kopiran",
    recolher: "Sažmi",
    expandir: "Proširi",
    verInteiro: "Prikaži cijelu datoteku",
    maisOpcoes: "Više opcija",
    baixar: "Preuzmi",
    recolherLinhas: "Sažmi ({{linhas}} redaka)",
    expandirLinhas: "Proširi ({{linhas}} redaka)",
    mudarIdioma: "Promijeni jezik",
    procurarIdioma: "Traži kôd jezika…",
    nenhumIdioma: "Nema takvog jezika.",
    quebrarTexto: "Prelomi tekst",
  },
  caixa: {
    escrever: "Piši u #{{canal}}",
    escreverSemCanal: "Napiši poruku",
    semPermissao: "Nemaš dopuštenje slati poruke na ovom kanalu",
    solteParaAnexar: "Pusti da priložiš",
    longaTitulo: "Poruka je predugačka…",
    longaDescricao: "Dosegao si granicu od {{limite}} znakova. Možeš je poslati kao datoteku.",
    enviarComoArquivo: "Pošalji kao datoteku",
    respondendoPara: "Odgovor za",
    vaiNotificar: "Osoba će dobiti obavijest",
    naoVaiNotificar: "Osoba neće dobiti obavijest",
    ligado: "uključeno",
    desligado: "isključeno",
    pararDeResponder: "Odustani od odgovora",
    mais: "Više",
    enviarArquivo: "Pošalji datoteku",
    criarEnquete: "Napravi anketu",
    expressoes: "Emoji, GIF-ovi i naljepnice",
    enviar: "Pošalji",
    aguardandoEnvio: "Čeka se prijenos",
    modoLento: "Spori način uključen ({{tempo}})",
    modoLentoDica: "Spori način postavljen je na {{segundos}} s. Pričekaj prije slanja sljedeće poruke.",
  },
  anexos: {
    enviando: "Prijenos…",
    modificar: "Uredi {{arquivo}}",
    remover: "Ukloni {{arquivo}}",
    ver: "Pogledaj {{arquivo}}",
    mostrarSpoiler: "Prikaži spojler: {{arquivo}}",
    spoiler: "spojler",
    spoilerTitulo: "Spojler",
    editarTitulo: "Uredi privitak",
    nomeDoArquivo: "Naziv datoteke",
    descricao: "Opis zamjenskog teksta",
    descricaoDica: "Opiši ovaj sadržaj za čitače zaslona",
    marcarSpoiler: "Označi kao spojler",
    cancelar: "Odustani",
    salvar: "Spremi",
  },
  cartao: {
    tocador: "Reproduktor",
    abrir: "Otvori {{destino}}",
    tocar: "Reproduciraj {{titulo}}",
    video: "videozapis",
    verImagem: "Pogledaj sliku",
  },
  enquete: {
    titulo: "Anketa",
    encerrada: "Anketa je zatvorena",
    variasRespostas: "Anketa — više odgovora",
    umVoto: "{{quantidade}} glas",
    votos: "{{quantidade}} glasova",
    umVotoNoTotal: "{{quantidade}} glas ukupno",
    votosNoTotal: "{{quantidade}} glasova ukupno",
    encerraEm: "zatvara se {{quando}}",
    encerrarAgora: "Zatvori sada",
  },
  fixadas: {
    titulo: "Prikvačene poruke",
    vazio: "Ovaj kanal nema prikvačenih poruka… zasad.",
    desafixar: "Otkvači",
    anexo: "(privitak)",
    enquete: "(anketa)",
    dicaRotulo: "SAVJET:",
    dica: "tko ima dopuštenje „Upravljanje porukama” može prikvačiti izravno iz izbornika poruke.",
  },
  encaminhar: {
    titulo: "Proslijedi poruku",
    paraOnde: "Kamo?",
    semTexto: "(poruka bez teksta)",
    nenhumLugar: "Nema mjesta s tim imenom.",
    canais: "Kanali",
    conversas: "Izravne poruke",
  },
  expressoes: {
    gifs: "GIF-ovi",
    buscarGifs: "Traži na Klipyju",
    figurinha: "Naljepnica",
    buscarFigurinha: "Nađi savršenu naljepnicu",
    buscarEmoji: "Nađi savršeni emoji",
    buscarReacao: "Nađi savršenu reakciju",
    adicionarEmoji: "Dodaj emoji",
    limparBusca: "Očisti pretragu",
  },
  busca: {
    fechar: "Zatvori pretragu",
    procurando: "Tražim…",
    resultado: "{{quantos}} rezultat",
    resultados: "{{quantos}} rezultata",
    nadaCom: "Ništa s {{termo}} ovdje.",
    soOsQuePodeLer: "Pretraga gleda samo kanale koje smiješ čitati.",
  },
  entrada: {
    titulo: "Pristigla pošta",
    naoLidas: "Nepročitano",
    salvas: "Spremljeno",
    mencoes: "Spominjanja",
    fimTitulo: "Došao si do kraja",
    fimDetalhe: "Nema više za čitanje. Kad stigne nova poruka, pojavit će se ovdje.",
    semSalvosTitulo: "Ništa spremljeno",
    semSalvosDetalhe: "Drži Shift i klikni oznaku poruke da je sačuvaš i pročitaš poslije.",
    tirarDosSalvos: "Ukloni iz spremljenih",
    semMencoesTitulo: "Još nema spominjanja",
    semMencoesDetalhe: "Spominjanja tebe pojavljuju se ovdje za zadnjih 7 dana.",
  },
  forum: {
    descricao: "Svaka tema postaje zaseban razgovor — dobro za pitanje koje se ne smije izgubiti usred čavrljanja.",
    novoAssunto: "Nova tema",
    vazio: "Još nema tema. Pokreni prvu i razgovor ostaje uredan od početka.",
    titulo: "Naslov",
    doQueSeTrata: "O čemu se radi?",
    primeiraMensagem: "Prva poruka",
    conteDoCaso: "Ispričaj",
  },
};
