export const perfil = {
  carregando: "Učitavanje…",
  editar: "Uredi profil",
  mensagem: "Poruka",
  abrirConversa: "Otvori razgovor",
  verCompleto: "Pogledaj cijeli profil",
  convidarParaServidor: "Pozovi na poslužitelj",
  semServidores: "Nemaš poslužitelja",
  conviteEnviado: "Pozivnica poslana korisniku {{nome}}.",
  moderador: "Otvori u prikazu moderatora",
  mais: "Više",
  ignorar: "Zanemari",
  deixarDeIgnorar: "Prestani zanemarivati",
  copiarId: "Kopiraj ID korisnika",
  idCopiado: "ID kopiran.",
  conexoes: "Veze",
  membroDesde: "Član od",
  sobre: "O meni",
  cargosTitulo: "Uloge",
  visaoGeral: "Pregled",
  amigosEmComum: "Zajednički prijatelji ({{quantidade}})",
  servidoresEmComum: "Zajednički poslužitelji ({{quantidade}})",
  amizade: {
    amigo: "Prijatelj",
    pedidoEnviado: "Zahtjev za prijateljstvo poslan",
    respondaAbaixo: "Poslao ti je zahtjev — odgovori ispod",
    adicionar: "Dodaj prijatelja",
    teMandouPedido: "Poslao ti je zahtjev za prijateljstvo",
    aceitar: "Prihvati",
    desfazer: "Ukloni prijatelja",
    desfazerTitulo: "Ukloniti {{nome}} iz tvojih prijatelja?",
    desfazerDescricao: "Prestajete biti prijatelji. Privatni razgovor ostaje u povijesti, a kasnije ga možeš ponovno dodati.",
    bloquear: "Blokiraj",
    bloquearTitulo: "Blokirati {{nome}}?",
    bloquearDescricao: "Prestajete biti prijatelji, privatni razgovor prestaje primati poruke, a on ti više ne može poslati zahtjev za prijateljstvo.",
    linkCopiado: "Niste prijatelji — poveznica je kopirana da mu je ti pošalješ.",
  },
  recado: {
    escrever: "Piši korisniku @{{usuario}}",
    enviar: "Pošalji",
    enviada: "Poruka poslana",
    falhou: "Nije se moglo poslati. Pokušaj iz razgovora.",
  },
  cartao: {
    trocarFaixa: "Promijeni natpis kartice",
    trocarFaixaCurto: "Promijeni natpis",
    trocarFoto: "Promijeni profilnu sliku",
    trocarFotoCurto: "Promijeni sliku",
    suaEtiqueta: "Tvoja oznaka",
    editarEtiqueta: "Klikni da urediš svoju oznaku",
    conteAlgo: "Reci nam nešto o sebi",
    adicionarStatus: "Dodaj status",
    adicionarDescricao: "Klikni da dodaš opis",
    cargo: "Uloga",
    cargos: "Uloge",
    cargosCom: "Uloge — {{quantidade}}",
    tirarCargo: "Ukloni ulogu {{cargo}}",
  },
  cargos: {
    adicionar: "Dodaj ulogu",
    procurar: "Traži ulogu",
  },
  etiqueta: {
    escolher: "Odaberi oznaku poslužitelja",
    nenhuma: "Nema oznake poslužitelja",
    semEtiqueta: "Nijedan tvoj poslužitelj nema oznaku",
  },
  emblemas: {
    doServidor: "Bedževi ovog poslužitelja",
    limite: "Možeš nositi do {{quantidade}} bedževa.",
  },
  nota: {
    vazia: "Klikni da nešto zapišeš",
    rotulo: "Bilješka (vidiš je samo ti)",
  },
  status: {
    titulo: "Status",
    definir: "Postavi svoj status",
    escolherEmoji: "Odaberi emoji",
    tirarEmoji: "Ukloni emoji",
    oQuePensa: "O čemu razmišljaš?",
    limparAgora: "Očisti status sada",
    naoLimpar: "Ne čisti",
    limpar30m: "Očisti za 30 minuta",
    limpar1h: "Očisti za 1 sat",
    limpar4h: "Očisti za 4 sata",
    limparHoje: "Očisti danas",
    limparAmanha: "Očisti sutra",
    comHora: "{{prazo}} u {{hora}}",
  },
  presenca: {
    disponivel: "Dostupan",
    ausente: "Odsutan",
    naoPerturbar: "Ne uznemiravaj",
    naoPerturbarDetalhe: "Ne dobivaš obavijest o novim porukama",
    invisivel: "Nevidljiv",
    invisivelDetalhe: "Drugima izgledaš izvan mreže",
  },
  menu: {
    mudarDeConta: "Promijeni račun",
    gerenciarContas: "Upravljaj računima",
  },
  editor: {
    decoracao: "Promijeni ukras avatara",
    naoSalvo: "Ne zaboravi spremiti promjene!",
    principal: "Glavni profil",
  },
};
