export const servidor = {
  titulo: "Postavke poslužitelja",
  auditoria: {
    titulo: "Zapisnik radnji",
    porUsuario: "Filtriraj po osobi",
    porAcao: "Filtriraj po radnji",
    vazio: "S ovim filtrom još ništa nije zabilježeno.",
    motivo: "Razlog:",
  },
  banimentos: {
    titulo: "Popis zabrana poslužitelja",
    descricao: "Tko je ovdje ne ulazi ni s novom pozivnicom. Ukidanje zabrane vraća pristup odmah.",
    procurar: "Traži zabrane po korisničkom imenu",
    vazioTitulo: "Nema zabrana",
    vazio: "Još nikoga nisi zabranio… ali ako i kad zatreba, ne oklijevaj.",
    desbanir: "Ukini zabranu",
  },
  excluir: {
    tudoVai: "Svi kanali, poruke i pozivnice poslužitelja {{servidor}} bit će obrisani za {{membros}} članova. Nitko ih poslije neće vratiti.",
    digite: "Upiši {{servidor}} za potvrdu",
    titulo: "Obriši poslužitelj",
    aviso: "Ovo se ne može poništiti.",
  },
  emblemas: {
    titulo: "Bedževi",
    vazio: "Još nema bedževa.",
    novo: "Novi bedž",
  },
  convites: {
    titulo: "Pozivnice",
    descricao: "Sve aktivne poveznice s pozivnicom ovog poslužitelja.",
    vazio: "Još nije stvorena nijedna pozivnica.",
    revogar: "Opozovi pozivnicu",
  },
  integracoes: {
    titulo: "Integracije",
    descricao: "Webhook je adresa koja objavljuje u kanalu bez potrebe za računom. Služi da javi kad build prođe, kad netko otvori prijavu, ili što god želiš poslati iz skripte.",
    novo: "Novi webhook",
    vazio: "Još nema webhookova. Stvori jedan i zalijepi URL ondje odakle želiš da poruka stiže.",
    canal: "Kanal",
    apagar: "Obriši webhook",
    comoUsar: "Kako se koristi",
    comoUsarTexto: "Pošalji POST s JSON-om. Format je isti kao Discordov, pa skripta koja već postoji radi bez promjena:",
  },
  engajamento: {
    titulo: "Uključenost",
    descricao: "Što poslužitelj radi sam da ne djeluje prazno kad dođe netko nov.",
    sistema: "Sustavne poruke",
    boasVindas: "Pošalji dobrodošlicu kad netko uđe",
    sorteio: "Bez vlastitog teksta ispod, rečenica se izvlači — uvijek ista brzo dosadi.",
    canalDoSistema: "Kanal sustavnih poruka",
    mensagem: "Poruka dobrodošlice",
    deixeVazio: "Ostavi prazno da se izvlači između gotovih rečenica",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtri koji moderiraju sami, prije nego poruka uopće nastane. Tko upravlja poslužiteljem nikad nije filtriran — a izuzete uloge prolaze ravno.",
    palavras: {
      titulo: "Blokiraj vlastite riječi",
      descricao: "Tvoj popis riječi koje nitko ne smije napisati.",
    },
    mencoes: {
      titulo: "Blokiraj spam spominjanjima",
      descricao: "Blokira poruku s previše spominjanja odjednom.",
    },
    links: {
      titulo: "Blokiraj poveznice",
      descricao: "Zadržava svaku adresu zalijepljenu u chat.",
    },
    definir: "Postavi",
    nomeDaRegra: "Naziv pravila",
    bloqueadas: "Blokirane riječi",
    digiteEnter: "Upiši i pritisni Enter",
    comparacao: "Usporedba zanemaruje velika slova, dijakritike i interpunkciju — i ne hvata riječ unutar druge.",
    aPartirDe: "Blokiraj od koliko spominjanja",
    oQueFazer: "Što učiniti",
    canalDoAlerta: "Kanal upozorenja",
    escolhaCanal: "Odaberi kanal",
    castigo: "Utišavanje (minute)",
    isentos: "Izuzete uloge",
    semCargos: "Još nije stvorena nijedna uloga.",
    salvarRegra: "Spremi pravilo",
    apagar: "Obriši pravilo",
    excluirTitulo: "Obrisati ovo AutoMod pravilo?",
    excluirDescricao: "Poslužitelj po njemu odmah prestaje filtrirati. Možeš ga ponovno stvoriti, ali trenutne postavke se gube.",
    excluirAcao: "Obriši pravilo",
  },
  cargos: {
    titulo: "Uloge",
    descricao: "Uloge daju ime, boju i ovlasti. Tko je više na popisu, nadređen je onima ispod — i nitko ne dira ulogu jednaku svojoj ili višu.",
    criar: "Stvori ulogu",
    vazio: "Još nema uloga.",
    abaExibicao: "Prikaz",
    abaPermissoes: "Ovlasti",
    abaMembros: "Članovi — {{quantos}}",
    everyone: "Vrijedi za sve na poslužitelju. To je osnova na koju se ostale uloge zbrajaju.",
    nomeDoCargo: "Naziv uloge",
    cor: "Boja uloge",
    corDica: "Boji ime onoga tko ima ulogu na popisu članova i u chatu.",
    semCor: "Bez boje",
    corPersonalizada: "Prilagođena boja",
    estilo: "Stil imena",
    segundaCor: "Druga boja",
    segundaCorDica: "Bez nje gradijent pada na punu boju — ne nestaje.",
    limparSegundaCor: "Očisti drugu boju",
    icone: "Ikona",
    iconeDica: "Pojavljuje se uz ulogu na profilnoj kartici onoga tko je ima.",
    exibirSeparado: "Prikaži odvojeno od ostalih članova",
    exibirSeparadoDica: "Uloga dobiva vlastiti odjeljak na popisu članova.",
    permitirMencionar: "Dopusti spominjanje ove uloge",
    permitirMencionarDica: "Bilo tko će moći obavijestiti sve koji imaju tu ulogu.",
    semPoderDeConceder: "{{descricao}} (nemaš ovu ovlast da je dodijeliš)",
    adicionar: "Dodaj nekoga u ovu ulogu",
    tirar: "Ukloni ulogu",
    semNinguem: "Ovu ulogu još nitko nema.",
    apagar: "Obriši ulogu",
    excluirTitulo: "Obrisati ulogu „{{nome}}\"?",
    excluirDescricao: "Tko ima ovu ulogu gubi sve što je davala. Ne može se poništiti.",
    excluirAcao: "Obriši ulogu",
  },
  membros: {
    procurar: "Traži po imenu ili korisničkom imenu",
    membroDesde: "Član od",
    vazio: "Nitko nije pronađen.",
    acoesPara: "Radnje za {{nome}}",
    deCastigo: "utišavanja",
    tirarCastigo: "Ukini utišavanje",
    castigo5min: "5 minuta",
    castigo1h: "1 sat",
    castigo1d: "1 dan",
    castigo1s: "1 tjedan",
    expulsar: "Izbaci",
    expulsarTitulo: "Izbaciti {{nome}}?",
    expulsarDescricao: "odmah napušta {{servidor}}. Može se vratiti s pozivnicom — izbacivanje ne sprječava povratak.",
    banir: "Zabrani",
    banirTitulo: "Zabraniti {{nome}}?",
    banirDescricao: "napušta {{servidor}} i ne može se vratiti, ni s pozivnicom, dok mu se zabrana ne ukine.",
    motivo: "Razlog (neobavezno)",
    motivoDica: "Ostaje zabilježeno u zapisniku",
  },
  perfil: {
    titulo: "Profil poslužitelja",
    descricao: "Ovako tvoj poslužitelj izgleda na popisu i u poveznicama s pozivnicom.",
    icone: "Ikona",
    faixa: "Baner na vrhu",
    nomeDoServidor: "Naziv poslužitelja",
    campoDescricao: "Opis",
    doQueE: "O čemu je ovaj poslužitelj?",
    comprimido: "Sažeto prije slanja: {{economia}}",
  },
  etiqueta: {
    titulo: "Oznaka poslužitelja",
    descricao: "Oznaka do 4 slova koja se pojavljuje uz ime svakog člana — u chatu i na popisu ljudi. Ovdje je besplatna: bez boostova, bez razina.",
    escolhaNome: "Odaberi naziv",
    limite: "Najviše 4 znaka, slova i brojevi.",
    escolhaInsignia: "Odaberi bedž",
    voce: "Ti",
    fala1: "ima li netko za igru?",
    fala2: "baci pogled na moju oznaku!",
    fala3: "opa, kako si to nabavio",
  },
  expressoes: {
    comoUsar: "Dodaj do {{limite}} emojija koje svi mogu koristiti na ovom poslužitelju. Upiši :ime: u chat da ga pošalješ.",
    imagem: "Slika",
    enviadoPor: "Poslao",
    semEmoji: "Još nema emojija.",
    figurinhas: "Naljepnice",
    enviarFigurinha: "Pošalji naljepnicu",
    nomeDaFigurinha: "Naziv naljepnice",
    exemploFigurinha: "Npr.: zagrljaj mačića",
    figurinhaGrande: "Naljepnica prelazi {{limite}}.",
    deixaPraLa: "Pusti",
    sons: "Ploča zvukova",
    enviarSom: "Pošalji zvuk",
    nomeDoSom: "Naziv zvuka",
    semSom: "Još nema zvukova.",
    somGrande: "Zvuk prelazi {{limite}}.",
    emojiRelacionado: "Povezani emoji",
    ouvir: "Poslušaj",
    ouvirAssim: "Poslušaj ovako",
    volumeDe: "Glasnoća {{nome}}",
    volumeDica: "Vrijedi za sve na poslužitelju. Svatko i dalje može stišati zvukove samo za sebe, u ploči poziva.",
    falhaEnvio: "Datoteku nije bilo moguće poslati.",
    excluirTitulo: "Obrisati {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Nestaje s poslužitelja svima. Poruke koje su ga već upotrijebile ostaju kakve jesu.",
  },
  canal: {
    visaoGeral: "Pregled",
    nome: "Naziv kanala",
    topico: "Tema kanala",
    topicoDica: "O čemu se ovdje priča?",
    modoLento: "Svatko šalje samo jednu poruku po intervalu. Tko upravlja porukama ili kanalima prolazi ravno.",
    visibilidade: "Vidljivost sadržaja",
    padrao: "Zadano",
    padraoDica: "Sadržaj kanala uvijek je vidljiv.",
    spoiler: "Kanal sa spojlerima",
    spoilerDica: "Označi ovaj kanal kao onaj sa spojlerima, da obrati i teške teme ostanu skriveni dok netko ne odluči pogledati.",
    idade: "Kanal s dobnim ograničenjem",
    idadeDica: "Tko uđe mora potvrditi punoljetnost da vidi sadržaj.",
    bitrateDica: "Iznad 64 kbps može smetati onima sa slabom vezom.",
    qualidadeDeVideo: "Kvaliteta videa",
    automatica: "Automatska",
    limite: "Ograničenje korisnika — {{valor}}",
    pessoas: "{{quantos}} ljudi",
    semLimite: "bez ograničenja",
    permissoesDescricao: "Ovdje mijenjaš što vrijedi u ovom kanalu. Što ostane na „naslijedi\" i dalje prati ulogu.",
    excluir: {
      titulo: "Obriši kanal",
      historico: "Cijela povijest kanala {{canal}} odlazi s njim, svima.",
      digite: "Upiši {{canal}} za potvrdu",
    },
  },
  moderacao: {
    titulo: "Pogled moderatora",
    semPermissao: "Treba ti ovlast „Moderiraj članove\" da ovo vidiš.",
    fecharEsc: "Zatvori (Esc)",
    atividade: "Aktivnost na poslužitelju",
    mensagens: "Poruke",
    links: "Poveznice",
    midia: "Mediji",
    acoesNaAuditoria: "Radnje u zapisniku",
    moderacoesSofridas: "Primljene mjere",
    permissoes: "Ovlasti ({{quantas}})",
    semPermissaoEspecial: "Nema posebnih ovlasti.",
    conta: "Račun",
    entrouNoServidor: "Ušao na poslužitelj",
    contaCriadaEm: "Račun stvoren",
    deCastigoAte: "Utišan do",
    formaDeAdesao: "Kako je ušao",
    mensagem: "Poruka",
    castigo: "Utišavanje",
    copiarId: "Kopiraj ID",
    idCopiado: "ID kopiran.",
    adicionarCargo: "Dodaj ulogu",
    semCargos: "Nijedna uloga nije stvorena",
    soEveryone: "Samo @everyone.",
    voltar: "Natrag",
    vazio: "Ovdje nema ničega.",
    cinquenta: "Prikazujem 50 najnovijih.",
    irParaMensagem: "Idi na poruku",
    precisaSerAmigo: "Morate biti prijatelji da biste razgovarali.",
    expulsarDescricao: "Odmah napušta poslužitelj, ali se može vratiti s pozivnicom.",
    banirDescricao: "Napušta poslužitelj i ne može se vratiti, ni s pozivnicom, dok mu se zabrana ne ukine.",
    castigarTitulo: "Utišati {{nome}}?",
    castigoDescricao: "Dok traje, ne piše niti govori ni u jednom kanalu poslužitelja.",
    aplicarCastigo: "Primijeni utišavanje",
    duracao: "Trajanje u minutama",
    informeDuracao: "Navedi trajanje u minutama.",
  },
};
