export const servidor = {
  comunidade: {
    ativa: "Zajednica je otvorena",
    ativaDesde: "Otvorena od {{quando}}",
    membrosAgora: "{{quantos}} članova",
    criarParaMim: "Napravi mi jedan",
    canalDeRegras: "Kanal s pravilima",
    canalDeRegrasDetalhe: "Mjesto s pravilima koja svatko pročita prije nego progovori.",
    canalDeAvisos: "Kanal s obavijestima zajednice",
    canalDeAvisosDetalhe: "Onamo šaljemo što se ovdje mijenja, samo za one koji vode.",
    canalDeSeguranca: "Kanal sa sigurnosnim upozorenjima",
    canalDeSegurancaDetalhe: "Ondje moderacija dobiva ono što su filtri uhvatili.",
    idiomaPrincipal: "Glavni jezik",
    idiomaPrincipalDetalhe: "Jezik na kojem se odvija najveći dio razgovora.",
    semIdioma: "Nijedan jezik nije odabran",
    semCanal: "Bez kanala",
    finalTitulo: "Skoro pa gotovo",
    finalDetalhe: "Prije otvaranja pogledaj što se mijenja onima koji dolaze.",
    confereRegras: "Tko uđe, prvo vidi kanal s pravilima.",
    confereEveryone: "@everyone i @here koriste samo oni s ulogom.",
    confereMencoes: "Spominjanje svih odjednom sada traži dopuštenje.",
    concordo: "Slažem se i razumijem",
    concordoDetalhe: "Potvrđuješ da zajednica poštuje naše smjernice.",
    proximo: "Dalje",
    terminar: "Završi postavljanje",
    visaoGeral: "Pregled",
    visaoGeralDetalhe: "Kanali kojima zajednica govori onima koji dolaze.",
    seguranca: "Sigurnost",
    segurancaDetalhe: "Kočnice koje zadržavaju neželjeno i teški sadržaj.",
    habilitada: "Zajednica je uključena.",
    falhou: "Zajednicu nije bilo moguće uključiti.",
    titulo: "Zajednica",
    ilustracao: "Oblačići govora",
    convite: "Gradiš zajednicu?",
    conviteDetalhe: "Pretvori ga u zajednicu i dobij alate za veliko mjesto: kanal s pravilima, obavijesti od nas i filtre koji sami moderiraju.",
    contagem: "{{membros}} od {{minimo}} članova",
    faltam: "Fali još {{quantos}} do otvaranja.",
    prontoParaAbrir: "Već se može otvoriti.",
    habilitar: "Uključi zajednicu",
    vantagemCrescer: "Rasti",
    vantagemCrescerDetalhe: "Zajednica se može prijaviti za Istraži, pa te nađu oni koji traže tu temu.",
    vantagemModerar: "Moderirati",
    vantagemModerarDetalhe: "Traži potvrđen e-mail, filtriraj medije i upali AutoMod odjednom.",
    vantagemAvisos: "Biti u toku",
    vantagemAvisosDetalhe: "Šaljemo što se mijenja onima koji vode mjesto, u kanal samo za vas.",
    assistenteTitulo: "Postavimo tvoju zajednicu.",
    passoSeguranca: "Sigurnosne provjere",
    passoBasico: "Osnovna priprema",
    passoFinal: "Završni detalji",
    seguraTitulo: "Čuvaj zajednicu sigurnom",
    seguraDetalhe: "Velika zajednica privlači neželjeno. Ove dvije kočnice uključene su od početka, a poslije ih možeš ugasiti.",
    emailVerificado: "Traži potvrđen e-mail",
    emailVerificadoDetalhe: "Tko još nije potvrdio e-mail, ne piše. Tko ima ulogu, prolazi.",
    filtroDeMidia: "Filtriraj eksplicitne medije",
    filtroDeMidiaDetalhe: "Slike i videi stižu skriveni i pokažu se tek kad ih netko odluči pogledati.",
    basicoTitulo: "Pripremi osnovno",
    basicoDetalhe: "Reci u kojem su kanalu pravila i kamo idu naše obavijesti. Bez odabranog kanala, izradit ću oba.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} naredbi",
    previa: "Kako kartica izgleda",
    trocarIcone: "Promijeni ikonu",
    tirarCapa: "Ukloni naslovnu",
    heroComunidades: "Netko upravo priča o onome što voliš",
    heroComunidadesDetalhe: "Zajednice koje su otvorili ljudi odavde. Uđi, pročitaj razgovor i ostani ako ti se svidi.",
    emDestaque: "Izdvojeno",
    todasAsComunidades: "Ostale",
    heroTitulo: "Što će vaša ekipa danas koristiti?",
    heroDetalhe: "Botovi za glazbu, igru i moderiranje, koje su napravili ljudi koji su i sami ovdje. Odaberi jednoga i ulazi na tvoj poslužitelj.",
    novidades: "Upravo stigle",
    todosOsApps: "Ostale",
    lojaTitulo: "Stranica aplikacije",
    lojaDetalhe: "To je ono što u Istraži vidi onaj tko je još ne poznaje.",
    capa: "Naslovna slika",
    capaDetalhe: "Široka slika na vrhu stranice. 1280 × 720 dobro sjeda.",
    trocarCapa: "Promijeni naslovnu",
    categorias: "Kategorije",
    categoriasDetalhe: "Najviše {{quantas}}. Po njima se pregledava u Istraži.",
    idiomas: "Jezici",
    idiomasDetalhe: "Najviše {{quantos}}. Na kojim jezicima aplikacija odgovara.",
    termos: "Uvjeti korištenja",
    politica: "Pravila privatnosti",
    politicas: "Pravila",
    servidorDeSuporte: "Poslužitelj podrške",
    servidorDeSuporteDetalhe: "Onamo ide tko treba pomoć s aplikacijom.",
    semServidor: "Nijedan",
    emQuantosServidores: "Na koliko poslužitelja",
    categoria: {
      GAMES: "Igre",
      MUSICA: "Glazba",
      MODERACAO: "Moderiranje",
      PRODUTIVIDADE: "Produktivnost",
      SOCIAL: "Društveno",
      UTILIDADES: "Alati",
      ARTE_E_CRIACAO: "Umjetnost i stvaranje",
      EDUCACAO: "Učenje",
      OUTRA: "Ostalo",
    },
    appIndisponivel: "Aplikacija nije dostupna",
    voltarParaExplorar: "Natrag na Istraži",
    adicionarApp: "Dodaj aplikaciju",
    copiarLink: "Kopiraj poveznicu",
    denunciarApp: "Prijavi aplikaciju",
    copiarIdDoApp: "Kopiraj ID aplikacije",
    visaoGeral: "Pregled",
    comandos: "Naredbe",
    permissoes: "Dopuštenja",
    semPermissoes: "Ova aplikacija ne traži nikakva dopuštenja.",
    avisoDePermissoes: "Ulazi s vlastitom ulogom. Dopuštenja poslije možeš promijeniti u Postavke zajednice → Uloge.",
    servidoresEmComum: "Zajedničke zajednice",
    umServidorEmComum: "1 zajednica",
    quantosServidoresEmComum: "Zajednica: {{quantos}}",
    feitoPor: "Napravio",
    publicadoEm: "Objavljeno",
    denunciarNome: "Prijavi {{nome}}",
    denunciaDetalhe: "Prijava ide timu Gravaêa. Onaj tko je napravio aplikaciju neće saznati da si to bio ti.",
    denunciaFalhou: "Prijava se nije mogla poslati.",
    umMembro: "1 član",
    semDescricao: "Bez opisa.",
    adicionar: "Dodaj",
    jaEstaAqui: "Već si ovdje",
    entrando: "Ulazim…",
    entrar: "Uđi",
    comunidadePublica: "Javna zajednica",
    online: "{{quantos}} na mreži",
    membros: "{{quantos}} članova",
    abrirComunidade: "Otvori zajednicu",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Postavke poslužitelja",
  novasMensagens: "Nove poruke",
  menu: {
    silenciar: "Utišaj zajednicu",
    reativar: "Uključi zajednicu",
    porQuinze: "Na 15 minuta",
    porMeiaHora: "Na 30 minuta",
    porTresHoras: "Na 3 sata",
    porTresDias: "Na 3 dana",
    porUmaHora: "Na 1 sat",
    porOitoHoras: "Na 8 sati",
    porUmDia: "Na 24 sata",
    ateReativar: "Dok je ponovno ne uključim",
    notificacoes: "Postavke obavijesti",
    padrao: "Zadano",
    todas: "Sve poruke",
    soMencoes: "Samo spominjanja",
    nada: "Ništa",
    ocultarSilenciados: "Sakrij utišane kanale",
    denunciar: "Prijavi zajednicu",
    marcarLida: "Označi kao pročitano",
    convidar: "Pozovi članove",
    editarPerfil: "Uredi profil zajednice",
    configuracoes: "Postavke zajednice",
    sair: "Napusti zajednicu",
    sairTitulo: "Napustiti {{nome}}?",
    sairDescricao: "Za povratak će ti trebati nova pozivnica.",
    copiarId: "Kopiraj ID zajednice",
    idCopiado: "ID kopiran.",
  },
  convite: {
    cartaoTitulo: "Pozvan si u zajednicu",
    indisponivel: "Pozivnica nije dostupna",
    indisponivelDetalhe: "Istekla je, potrošena je, ili ju je onaj tko ju je napravio obrisao.",
    entrar: "Uđi u zajednicu",
    chamado: "Pozvan(a) si da se pridružiš",
    aceitarComo: "Prihvati kao {{nome}}",
    abrir: "Otvori zajednicu",
    recusar: "Ne, hvala",
  },
  pasta: {
    silenciarTodas: "Utišaj zajednice",
    reativarTodas: "Uključi zajednice",
    mostrarSilenciados: "Prikaži utišane kanale",
    notificacoesDaComunidade: "Postavke obavijesti",
    silenciarEveryone: "Utišaj @everyone i @here",
    permitirEveryone: "Dopusti @everyone i @here",
    silenciarCargos: "Utišaj spominjanja uloga",
    permitirCargos: "Dopusti spominjanja uloga",
    dicaDaCor: "Upiši boju (hex, rgb(), hsl() ili naziv) ili koristi birač.",
    mostrarIcone: "Prikaži ikonu kad je zatvorena",
    dicaDoIcone: "Zatvorena prikazuje ikonu umjesto poslužitelja.",
    icone: "Ikona mape",
    excluir: "Izbriši mapu",
    icones: {
      pasta: "Mapa",
      estrela: "Favorit",
      coracao: "Srce",
      salvar: "Spremi",
      jogo: "Kontroler",
      escudo: "Štit",
      nota: "Nota",
    },
    marcarLida: "Označi mapu kao pročitanu",
    configuracoes: "Postavke mape",
    desfazer: "Rastavi mapu",
    titulo: "Mapa",
    nome: "Naziv",
    semNome: "Bez naziva",
    cor: "Boja",
    semCor: "Bez boje",
    salvar: "Spremi",
  },
  denuncia: {
    titulo: "Prijavi {{nome}}",
    descricao: "Prijava ide timu Gravaê. Reci nam što se dogodilo.",
    motivo: "Razlog",
    detalhes: "Detalji (neobavezno)",
    enviar: "Pošalji prijavu",
    enviada: "Prijava poslana. Hvala.",
    motivos: {
      spam: "Spam ili reklama",
      assedio: "Uznemiravanje ili mržnja",
      conteudo: "Neprimjeren sadržaj",
      golpe: "Prijevara",
      outro: "Ostalo",
    },
  },
  selos: {
    verificada: "Provjerena zajednica",
    detectavel: "Vidljiva zajednica",
  },
  auditoria: {
    todasAsAcoes: "Sve radnje",
    todosOsUsuarios: "Svi korisnici",
    filtroMembros: "Članovi",
    filtroCanais: "Kanali",
    filtroEmojis: "Emojiji",
    filtroServidor: "Poslužitelj",
    titulo: "Zapisnik radnji",
    porUsuario: "Filtriraj po osobi",
    porAcao: "Filtriraj po radnji",
    vazio: "S ovim filtrom još ništa nije zabilježeno.",
    motivo: "Razlog:",
  },
  banimentos: {
    titulo: "Popis zabrana poslužitelja",
    descricao: "Tko je ovdje ne ulazi ni s novom pozivnicom. Ukidanje zabrane vraća pristup odmah.",
    procurar: "Traži zabrane po korisničkom imenu",
    vazioTitulo: "Nema zabrana",
    vazio: "Još nikoga nisi zabranio… ali ako i kad zatreba, ne oklijevaj.",
    desbanir: "Ukini zabranu",
  },
  excluir: {
    tudoVai: "Svi kanali, poruke i pozivnice poslužitelja {{servidor}} bit će obrisani za {{membros}} članova. Nitko ih poslije neće vratiti.",
    digite: "Upiši {{servidor}} za potvrdu",
    titulo: "Obriši poslužitelj",
    aviso: "Ovo se ne može poništiti.",
  },
  emblemas: {
    apagarDescricao: "Skida se svakome tko ga nosi. Ne može se poništiti.",
    titulo: "Bedževi",
    vazio: "Još nema bedževa.",
    novo: "Novi bedž",
  },
  convites: {
    revogarTitulo: "Opozvati pozivnicu?",
    revogarAcao: "Opozovi",
    revogarDescricao: "Poveznica {{codigo}} odmah prestaje raditi. Tko je preko nje već ušao, ostaje na poslužitelju.",
    titulo: "Pozivnice",
    descricao: "Sve aktivne poveznice s pozivnicom ovog poslužitelja.",
    vazio: "Još nije stvorena nijedna pozivnica.",
    revogar: "Opozovi pozivnicu",
  },
  integracoes: {
    opcionais: "username i avatar_url nisu obavezni i vrijede po poruci. Ograničenje je 5 poruka svakih 5 sekundi.",
    apagarDescricao: "URL odmah prestaje raditi. Poruke koje je već poslao ostaju u kanalu.",
    titulo: "Integracije",
    descricao: "Webhook je adresa koja objavljuje u kanalu bez potrebe za računom. Služi da javi kad build prođe, kad netko otvori prijavu, ili što god želiš poslati iz skripte.",
    novo: "Novi webhook",
    vazio: "Još nema webhookova. Stvori jedan i zalijepi URL ondje odakle želiš da poruka stiže.",
    canal: "Kanal",
    apagar: "Obriši webhook",
    comoUsar: "Kako se koristi",
    comoUsarTexto: "Pošalji POST s JSON-om:",
  },
  explorar: {
    titulo: "Otkrivanje",
  },
  engajamento: {
    semCanal: "Bez sustavnog kanala",
    titulo: "Uključenost",
    descricao: "Što poslužitelj radi sam da ne djeluje prazno kad dođe netko nov.",
    sistema: "Sustavne poruke",
    boasVindas: "Pošalji dobrodošlicu kad netko uđe",
    sorteio: "Bez vlastitog teksta ispod, rečenica se izvlači — uvijek ista brzo dosadi.",
    canalDoSistema: "Kanal sustavnih poruka",
    mensagem: "Poruka dobrodošlice",
    deixeVazio: "Ostavi prazno da se izvlači između gotovih rečenica",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtri koji moderiraju sami, prije nego poruka uopće nastane. Tko upravlja poslužiteljem nikad nije filtriran — a izuzete uloge prolaze ravno.",
    palavras: {
      titulo: "Blokiraj vlastite riječi",
      descricao: "Tvoj popis riječi koje nitko ne smije napisati.",
    },
    mencoes: {
      titulo: "Blokiraj spam spominjanjima",
      descricao: "Blokira poruku s previše spominjanja odjednom.",
    },
    links: {
      titulo: "Blokiraj poveznice",
      descricao: "Zadržava svaku adresu zalijepljenu u chat.",
    },
    definir: "Postavi",
    nomeDaRegra: "Naziv pravila",
    bloqueadas: "Blokirane riječi",
    digiteEnter: "Upiši i pritisni Enter",
    comparacao: "Usporedba zanemaruje velika slova, dijakritike i interpunkciju — i ne hvata riječ unutar druge.",
    aPartirDe: "Blokiraj od koliko spominjanja",
    oQueFazer: "Što učiniti",
    canalDoAlerta: "Kanal upozorenja",
    escolhaCanal: "Odaberi kanal",
    castigo: "Utišavanje (minute)",
    isentos: "Izuzete uloge",
    semCargos: "Još nije stvorena nijedna uloga.",
    salvarRegra: "Spremi pravilo",
    apagar: "Obriši pravilo",
    excluirTitulo: "Obrisati ovo AutoMod pravilo?",
    excluirDescricao: "Poslužitelj po njemu odmah prestaje filtrirati. Možeš ga ponovno stvoriti, ali trenutne postavke se gube.",
    excluirAcao: "Obriši pravilo",
  },
  cargos: {
    titulo: "Uloge",
    descricao: "Uloge daju ime, boju i ovlasti. Tko je više na popisu, nadređen je onima ispod — i nitko ne dira ulogu jednaku svojoj ili višu.",
    criar: "Stvori ulogu",
    vazio: "Još nema uloga.",
    abaExibicao: "Prikaz",
    abaPermissoes: "Ovlasti",
    abaMembros: "Članovi — {{quantos}}",
    everyone: "Vrijedi za sve na poslužitelju. To je osnova na koju se ostale uloge zbrajaju.",
    nomeDoCargo: "Naziv uloge",
    cor: "Boja uloge",
    corDica: "Boji ime onoga tko ima ulogu na popisu članova i u chatu.",
    semCor: "Bez boje",
    corPersonalizada: "Prilagođena boja",
    estilo: "Stil imena",
    segundaCor: "Druga boja",
    segundaCorDica: "Bez nje gradijent pada na punu boju — ne nestaje.",
    limparSegundaCor: "Očisti drugu boju",
    icone: "Ikona",
    iconeDica: "Pojavljuje se uz ulogu na profilnoj kartici onoga tko je ima.",
    exibirSeparado: "Prikaži odvojeno od ostalih članova",
    exibirSeparadoDica: "Uloga dobiva vlastiti odjeljak na popisu članova.",
    permitirMencionar: "Dopusti spominjanje ove uloge",
    permitirMencionarDica: "Bilo tko će moći obavijestiti sve koji imaju tu ulogu.",
    semPoderDeConceder: "{{descricao}} (nemaš ovu ovlast da je dodijeliš)",
    adicionar: "Dodaj nekoga u ovu ulogu",
    tirar: "Ukloni ulogu",
    semNinguem: "Ovu ulogu još nitko nema.",
    apagar: "Obriši ulogu",
    excluirTitulo: "Obrisati ulogu „{{nome}}\"?",
    excluirDescricao: "Tko ima ovu ulogu gubi sve što je davala. Ne može se poništiti.",
    excluirAcao: "Obriši ulogu",
  },
  membros: {
    procurar: "Traži po imenu ili korisničkom imenu",
    membroDesde: "Član od",
    vazio: "Nitko nije pronađen.",
    acoesPara: "Radnje za {{nome}}",
    deCastigo: "utišavanja",
    tirarCastigo: "Ukini utišavanje",
    castigo5min: "5 minuta",
    castigo1h: "1 sat",
    castigo1d: "1 dan",
    castigo1s: "1 tjedan",
    expulsar: "Izbaci",
    expulsarTitulo: "Izbaciti {{nome}}?",
    expulsarDescricao: "odmah napušta {{servidor}}. Može se vratiti s pozivnicom — izbacivanje ne sprječava povratak.",
    banir: "Zabrani",
    banirTitulo: "Zabraniti {{nome}}?",
    banirDescricao: "napušta {{servidor}} i ne može se vratiti, ni s pozivnicom, dok mu se zabrana ne ukine.",
    motivo: "Razlog (neobavezno)",
    motivoDica: "Ostaje zabilježeno u zapisniku",
  },
  perfil: {
    titulo: "Profil poslužitelja",
    descricao: "Ovako tvoj poslužitelj izgleda na popisu i u poveznicama s pozivnicom.",
    icone: "Ikona",
    faixa: "Baner na vrhu",
    nomeDoServidor: "Naziv poslužitelja",
    campoDescricao: "Opis",
    doQueE: "O čemu je ovaj poslužitelj?",
    comprimido: "Sažeto prije slanja: {{economia}}",
  },
  etiqueta: {
    titulo: "Oznaka poslužitelja",
    descricao: "Oznaka do 4 slova koja se pojavljuje uz ime svakog člana — u chatu i na popisu ljudi. Ovdje je besplatna: bez boostova, bez razina.",
    escolhaNome: "Odaberi naziv",
    limite: "Najviše 4 znaka, slova i brojevi.",
    escolhaInsignia: "Odaberi bedž",
    voce: "Ti",
    fala1: "ima li netko za igru?",
    fala2: "baci pogled na moju oznaku!",
    fala3: "opa, kako si to nabavio",
  },
  expressoes: {
    comoUsar: "Dodaj do {{limite}} emojija koje svi mogu koristiti na ovom poslužitelju. Upiši :ime: u chat da ga pošalješ.",
    imagem: "Slika",
    enviadoPor: "Poslao",
    semEmoji: "Još nema emojija.",
    figurinhas: "Naljepnice",
    enviarFigurinha: "Pošalji naljepnicu",
    nomeDaFigurinha: "Naziv naljepnice",
    exemploFigurinha: "Npr.: zagrljaj mačića",
    figurinhaGrande: "Naljepnica prelazi {{limite}}.",
    deixaPraLa: "Pusti",
    sons: "Ploča zvukova",
    enviarSom: "Pošalji zvuk",
    nomeDoSom: "Naziv zvuka",
    semSom: "Još nema zvukova.",
    somGrande: "Zvuk prelazi {{limite}}.",
    emojiRelacionado: "Povezani emoji",
    ouvir: "Poslušaj",
    ouvirAssim: "Poslušaj ovako",
    volumeDe: "Glasnoća {{nome}}",
    volumeDica: "Vrijedi za sve na poslužitelju. Svatko i dalje može stišati zvukove samo za sebe, u ploči poziva.",
    falhaEnvio: "Datoteku nije bilo moguće poslati.",
    excluirTitulo: "Obrisati {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Nestaje s poslužitelja svima. Poruke koje su ga već upotrijebile ostaju kakve jesu.",
  },
  canal: {
    tipoLink: "Poveznica",
    tipoLinkDica: "Vodi na adresu izvana i otvara se u pregledniku",
    endereco: "Adresa",
    enderecoDica: "Kamo vodi ovaj kanal. Mora počinjati s https://",
    visaoGeral: "Pregled",
    nome: "Naziv kanala",
    topico: "Tema kanala",
    topicoDica: "O čemu se ovdje priča?",
    modoLento: "Svatko šalje samo jednu poruku po intervalu. Tko upravlja porukama ili kanalima prolazi ravno.",
    visibilidade: "Vidljivost sadržaja",
    padrao: "Zadano",
    padraoDica: "Sadržaj kanala uvijek je vidljiv.",
    spoiler: "Kanal sa spojlerima",
    spoilerDica: "Označi ovaj kanal kao onaj sa spojlerima, da obrati i teške teme ostanu skriveni dok netko ne odluči pogledati.",
    idade: "Kanal s dobnim ograničenjem",
    idadeDica: "Tko uđe mora potvrditi punoljetnost da vidi sadržaj.",
    bitrateDica: "Iznad 64 kbps može smetati onima sa slabom vezom.",
    qualidadeDeVideo: "Kvaliteta videa",
    automatica: "Automatska",
    limite: "Ograničenje korisnika — {{valor}}",
    pessoas: "{{quantos}} ljudi",
    semLimite: "bez ograničenja",
    permissoesDescricao: "Ovdje mijenjaš što vrijedi u ovom kanalu. Što ostane na „naslijedi\" i dalje prati ulogu.",
    excluir: {
      titulo: "Obriši kanal",
      historico: "Cijela povijest kanala {{canal}} odlazi s njim, svima.",
      digite: "Upiši {{canal}} za potvrdu",
    },
  },
  moderacao: {
    titulo: "Pogled moderatora",
    semPermissao: "Treba ti ovlast „Moderiraj članove\" da ovo vidiš.",
    fecharEsc: "Zatvori (Esc)",
    atividade: "Aktivnost na poslužitelju",
    mensagens: "Poruke",
    links: "Poveznice",
    midia: "Mediji",
    acoesNaAuditoria: "Radnje u zapisniku",
    moderacoesSofridas: "Primljene mjere",
    permissoes: "Ovlasti ({{quantas}})",
    semPermissaoEspecial: "Nema posebnih ovlasti.",
    conta: "Račun",
    entrouNoServidor: "Ušao na poslužitelj",
    contaCriadaEm: "Račun stvoren",
    deCastigoAte: "Utišan do",
    formaDeAdesao: "Kako je ušao",
    mensagem: "Poruka",
    castigo: "Utišavanje",
    copiarId: "Kopiraj ID",
    idCopiado: "ID kopiran.",
    adicionarCargo: "Dodaj ulogu",
    semCargos: "Nijedna uloga nije stvorena",
    soEveryone: "Samo @everyone.",
    voltar: "Natrag",
    vazio: "Ovdje nema ničega.",
    cinquenta: "Prikazujem 50 najnovijih.",
    irParaMensagem: "Idi na poruku",
    precisaSerAmigo: "Morate biti prijatelji da biste razgovarali.",
    expulsarDescricao: "Odmah napušta poslužitelj, ali se može vratiti s pozivnicom.",
    banirDescricao: "Napušta poslužitelj i ne može se vratiti, ni s pozivnicom, dok mu se zabrana ne ukine.",
    castigarTitulo: "Utišati {{nome}}?",
    castigoDescricao: "Dok traje, ne piše niti govori ni u jednom kanalu poslužitelja.",
    aplicarCastigo: "Primijeni utišavanje",
    duracao: "Trajanje u minutama",
    informeDuracao: "Navedi trajanje u minutama.",
  },
  abas: {
    pesquisar: "Pretraži postavke",
    semResultado: "Ovdje nema ničega s tim imenom.",
    comunidade: "Zajednica",
    expressoes: "Izrazi",
    pessoas: "Ljudi",
    apps: "Aplikacije",
    moderacao: "Moderacija",
    banimentos: "Zabrane",
  },
};
