export const amizades = {
  ativosAgora: "Activi acum",
  procurando: "Vedem cine e pe aici…",
  tudoTranquilo: "Deocamdată e liniște…",
  tudoTranquiloDetalhe: "Când tu sau un prieten intrați într-un apel, apare aici — și te alături cu un clic.",
  emVoz: "În vocal",
  voce: "Tu",
  soVoce: "Doar tu",
  pessoas: "{{quantas}} persoane",
  voltarParaChamada: "Înapoi la apel",
  entrarNaChamada: "Intră în apel",
  abrirCanal: "Deschide {{canal}} pe {{servidor}}",
  mensagensDiretas: "Mesaje directe",
  encontreConversa: "Găsește o conversație",
  amigos: "Prieteni",
  conversas: "Conversații",
  semConversas: "Încă nicio conversație. Adaugă un prieten ca să începi.",
  semConversaComEsseNome: "Nicio conversație cu numele acesta.",
  abrirMenu: "Deschide serverele și conversațiile",
  solicitacoes: "Cereri de mesaj",
  pedidos: "Cereri",
  spam: "Spam",
  pedidosPendentes: "Cereri în așteptare",
  marcadosComoSpam: "Marcate ca spam",
  aceitar: "Acceptă",
  ignorar: "Ignoră",
  marcarSpam: "Marchează ca spam",
  semPedidos: "Nicio cerere în așteptare.",
  semPedidosDetalhe: "Cine nu îți e prieten, dar are un server în comun cu tine, ajunge aici înainte să ajungă în conversațiile tale.",
  semSpam: "Nimic marcat ca spam.",
  semSpamDetalhe: "Ce separă filtrul de spam, sau ce marchezi tu, rămâne în această filă.",
  umServidorEmComum: "1 server în comun",
  servidoresEmComum: "{{quantos}} servere în comun",
  semServidoresEmComum: "Niciun server în comun",
};
