export const chamada = {
  conectando: "Se conectează la apel…",
  naoEntrou: "Nu s-a putut intra în apel",
  sair: "Ieși din apel",
  sairDaVoz: "Ieși din apelul vocal",
  desconectar: "Deconectează",
  voltar: "Înapoi la apel",
  voltarAosQuadros: "Înapoi la cadrele apelului",
  fecharChat: "Închide chatul",
  carregandoPrevia: "Se încarcă previzualizarea…",
  maisOpcoes: "Mai multe",
  deVideo: "Apel video",
  deVoz: "Apel vocal",
  alguem: "Cineva",
  volume: {
    entrada: "Volum de intrare",
    saida: "Volum de ieșire",
    live: "Volumul transmisiunii",
    liveComPorcento: "Volumul transmisiunii ({{porcento}}%)",
    liveSemSom: "Transmisiune fără sunet",
  },
  aparelhos: {
    entrada: "Dispozitiv de intrare",
    saida: "Dispozitiv de ieșire",
    camera: "Cameră",
    microfone: "Microfon",
    saidaCurto: "Ieșire",
    oDoSistema: "Cel al sistemului",
    aDoSistema: "Cea a sistemului",
    semEscolhaDeSaida: "Acest browser nu te lasă să alegi ieșirea — decide sistemul.",
    espelhar: "Oglindește camera mea",
    configEntrada: "Setări de intrare",
    configSaida: "Setări de ieșire",
    configCamera: "Setările camerei",
    configAudioEVideo: "Setări audio și video",
  },
  tela: {
    compartilhar: "Partajează ecranul",
    compartilharAcao: "Partajează",
    cancelar: "Anulează",
    telas: "Ecrane",
    janelas: "Ferestre",
    somDoComputador: "Ia și sunetul calculatorului",
    somDoSistema: "Ia și sunetul sistemului",
    configCompartilhamento: "Setări de partajare",
    mostrarSemVideo: "Arată-i pe cei fără video",
    semFontes: "Sistemul nu a returnat niciun ecran sau fereastră de partajat.",
    pararDeCompartilhar: "Oprește partajarea",
    encerrarTransmissao: "Încheie transmisiunea",
  },
  live: {
    etiqueta: "În direct",
    etiquetaMaiuscula: "ÎN DIRECT",
    assistir: "Vezi transmisiunea",
    assistirPessoa: "Vezi {{nome}}",
    pararDeAssistir: "Nu mai privi",
  },
  membro: {
    mudarMeuApelido: "Schimbă-mi porecla",
    meuMicrofone: "Microfonul meu",
    ouvirChamada: "Ascultă apelul",
    copiarMeuId: "Copiază ID-ul meu",
    idCopiado: "ID copiat.",
    mensagem: "Mesaj",
    silenciar: "Amuțește",
    alterarApelido: "Schimbă porecla",
    cargos: "Roluri",
    semCargo: "Niciun rol creat",
    moverPara: "Mută în",
    silenciarNoServidor: "Amuțește vocea pe server",
    desativarAudioNoServidor: "Dezactivează audio pe server",
    desconectar: "Deconectează",
    apelidoTitulo: "Porecla ta pe acest server",
    apelidoDeAlguem: "Porecla lui {{nome}}",
    apelidoCampo: "Poreclă",
    apelidoDicaPropria: "Valabilă doar aici. Lasă gol ca să revină numele tău obișnuit.",
    apelidoDicaDeOutro: "Valabilă doar pe acest server. Lasă gol ca să revii la numele original.",
  },
  detalhes: {
    abrir: "Detalii de voce",
    titulo: "Detalii de Voce",
    conexao: "Conexiune",
    pingMedio: "Ping mediu",
    ultimoPing: "Ultimul ping",
    perda: "Pierdere de pachete trimise",
    medindo: "Se măsoară…",
    criptografado: "Criptat până la server (DTLS-SRTP)",
    explicacao: "Peste 250 ms întârzierea se aude în conversație — lumea începe să vorbească unul peste altul. O pierdere de pachete peste 10% face vocea robotică. În ambele cazuri problema este aproape întotdeauna între tine și internet: încearcă un cablu în loc de Wi-Fi, sau repornește routerul.",
  },
  microfone: {
    bloqueado: "Microfon blocat — doar asculți. Permite accesul din permisiunile browserului.",
    bloqueadoNoMac: "macOS blochează microfonul. Bifează",
    caminhoNoMac: "Setări sistem → Confidențialitate și securitate → Microfon",
    abrirAjustes: "Deschide setările",
    vaiReabrir: "macOS îți va cere să redeschizi aplicația.",
    naoAbriu: "Nu s-a putut deschide microfonul — doar asculți. Verifică dispozitivul în Setări → Voce și video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS încă nu a permis înregistrarea ecranului. Fără ea, partajarea iese neagră.",
    marque: "Bifează",
    reabra: "la Înregistrarea ecranului și redeschide aplicația.",
    jaMarcado: "Dacă e deja bifat, permisiunea s-a învechit la ultima actualizare: debifează, bifează din nou și redeschide aplicația.",
  },
  ruido: {
    titulo: "Reducerea zgomotului",
    explicacao: "Scoate zgomotul de fundal din vocea ta. Încearcă să bați din palme sau să tragi tastatura în timp ce vorbești — cei din apel te aud doar pe tine.",
    semSuporte: "Acest browser nu rulează reducerea avansată. Rămâne valabilă cea a browserului, care e mai slabă.",
    aplicando: "Se aplică apelului…",
    faleParaTestar: "Vorbește ca să testezi",
    verdeQuandoPassa: "Verde când vocea ta trece.",
    teOuvindo: "Te aud chiar acum.",
    feitoCom: "Făcut cu",
    aquiNoAparelho: ", chiar aici pe dispozitivul tău",
    ajustes: "Setări",
  },
  permissoes: {
    titulo: "Permisiuni macOS",
    detalhe: "macOS întreabă o singură dată, iar apoi se schimbă doar din panoul lui. Aici vezi ce este în vigoare și rezolvi ce lipsește.",
    concedida: "Acordată",
    negada: "Refuzată",
    naoPedida: "Nesolicitată",
    permitir: "Permite",
    abrirAjustes: "Deschide setările",
    microfone: "Microfon",
    microfoneDetalhe: "Să vorbești în apeluri și să îți testezi intrarea.",
    camera: "Cameră",
    cameraDetalhe: "Să pornești video în apel.",
    tela: "Înregistrarea ecranului",
    telaDetalhe: "Să partajezi ecranul și ferestrele.",
    monitoramento: "Monitorizarea intrării",
    monitoramentoDetalhe: "Să folosești apasă-ca-să-vorbești chiar și cu Gravaê în fundal.",
  },
  jaConectado: {
    titulo: "Ești deja în acest apel",
    trazer: "Adu apelul aici",
    deixar: "Lasă-l așa cum e",
    detalhe: "Dacă îl aduci aici, celălalt capăt iese din apel — contul tău stă într-un singur loc odată.",
  },
};
