export const configuracoes = {
  efeitos: {
    titulo: "Efectele indicatorului",
    detalhe: "Urmă și scântei desenate peste aplicație. Pornesc oprite și se sting singure dacă ai cerut mai puțină mișcare.",
    rastro: "Urma cursorului",
    rastroDetalhe: "O linie care urmează indicatorul și se stinge în spate.",
    faisca: "Scântei la clic",
    faiscaDetalhe: "Liniuțe care pornesc din locul unde ai dat clic.",
    cor: "Culoare",
    espessura: "Grosime",
    comprimento: "Lungime",
    tamanho: "Mărime",
    quantidade: "Câte",
  },
  email: {
    verificarTitulo: "Confirmă-ți e-mailul",
    verificarDetalhe: "Unele comunități lasă să scrie doar pe cei care au confirmat. E un clic.",
    enviar: "Trimite legătura",
    enviado: "Uită-te în inbox. Legătura ține o zi.",
    falhou: "E-mailul nu a putut fi trimis.",
    confirmado: "E-mail confirmat",
    confirmadoDetalhe: "Gata. Acum scrii în orice comunitate care cere asta.",
    linkIncompleto: "Legătură incompletă",
    linkIncompletoDetalhe: "Lipsește codul din adresă. Deschide legătura direct din e-mail.",
    confirmando: "Se confirmă…",
    expirou: "Această legătură a fost deja folosită sau a expirat.",
    irParaOApp: "Mergi la aplicație",
  },
  tema: {
    indisponivel: "Tema nu e disponibilă",
    indisponivelDetalhe: "Cine a publicat-o a șters-o, ori linkul e greșit.",
    indisponivelLinha: "Tema nu e disponibilă. Cine a publicat-o a șters-o, ori linkul e greșit.",
    importar: "Importă tema",
    importarCurto: "Importă",
    importarDetalhe: "Asta înlocuiește tema pe care o ai acum. O poți edita după aceea în Setări > Aspect > Studio de teme.",
    porAutor: "de {{autor}}",
    umaCorTrocada: "1 culoare schimbată",
    coresTrocadas: "{{quantas}} culori schimbate",
    avisoDeCss: "Tema asta vine cu CSS de la cine a scris-o, iar CSS-ul ajunge în orice colț al ecranului. Importă doar de la oameni în care ai încredere.",
    soCores: "Tema asta schimbă doar culori. Niciun CSS din afară.",
    aplicar: "Aplică",
    previaSemMotor: "Previzualizarea nu rulează motorul. Instaleaz-o ca să-l vezi.",
    motorAnimado: "{{motor}} animat",
  },
  sair: "Deconectare",
  versoes: {
    termos: "Termenii serviciului",
    privacidade: "Politica de confidențialitate",
    copiar: "Dă clic ca să copiezi",
    copiado: "Copiat",
  },
  telas: {
    conta: "Contul meu",
    privacidade: "Confidențialitate",
    conexoes: "Conexiuni",
    voz: "Audio",
    video: "Video",
    avisos: "Notificări",
    aplicativos: "Aplicații",
    aparencia: "Aspect",
    batePapo: "Chat",
    acessibilidade: "Accesibilitate",
    idioma: "Limbă",
    aplicativo: "Descarcă aplicația",
    atalhos: "Scurtături",
    desktop: "Aplicație desktop",
    avancado: "Avansat",
    servidor: "Server",
    comunicado: "Anunț de sistem",
    denuncias: "Raportări",
    publicacoes: "Implementări",
  },
  grupos: {
    conta: "Cont",
    app: "Setările aplicației",
    desenvolvedor: "Dezvoltator",
    administracao: "Administrare",
  },
  secoes: {
    detalhesDeLogin: "Date de conectare",
    dispositivos: "Dispozitive",
    usuariosBloqueados: "Utilizatori blocați",
    aplicativosAutorizados: "Aplicații autorizate",
    sessoes: "Sesiuni",
    amigosEDms: "Prieteni și mesaje directe",
    compartilhamentoDeAtividade: "Partajarea activității",
    visibilidadeDoPerfil: "Vizibilitatea profilului",
    exportarDados: "Exportă datele",
    exclusaoDeDados: "Șterge datele",
    tema: "Temă",
    corDeDestaque: "Culoare de accent",
    interface: "Interfață",
    listaDeCanais: "Lista de canale",
    zoomDoApp: "Nivel de zoom al aplicației",
    escalaDaFonte: "Scara fontului din chat",
    modoStreamer: "Confidențialitate la transmisiune",
    cursores: "Cursoare",
    movimento: "Mișcare",
    textoEmVoz: "Text în vorbire",
    teclado: "Tastatură",
    formatoDaHora: "Formatul orei",
    idiomaDaInterface: "Limba interfeței",
    dispositivosDeVoz: "Dispozitive",
    testeDoMicrofone: "Testul microfonului",
    modoDeEntrada: "Mod de intrare",
    sensibilidade: "Sensibilitatea intrării",
    qualidade: "Calitate",
    camera: "Cameră",
    transmissao: "Transmisiune",
    exibicao: "Afișare",
    entrada: "Introducere",
    midia: "Media",
    geral: "General",
    preferenciaDeMencao: "Preferință de menționare",
    sons: "Sunete",
  },
};
