export const configuracoes = {
  sair: "Deconectare",
  versoes: {
    copiar: "Dă clic ca să copiezi",
    copiado: "Copiat",
  },
  telas: {
    conta: "Contul meu",
    privacidade: "Confidențialitate",
    conexoes: "Conexiuni",
    voz: "Audio",
    video: "Video",
    avisos: "Notificări",
    aplicativos: "Aplicații",
    aparencia: "Aspect",
    batePapo: "Chat",
    acessibilidade: "Accesibilitate",
    idioma: "Limbă",
    aplicativo: "Descarcă aplicația",
    atalhos: "Scurtături",
    servidor: "Server",
  },
  grupos: {
    conta: "Cont",
    app: "Setările aplicației",
    desenvolvedor: "Dezvoltator",
    administracao: "Administrare",
  },
  secoes: {
    detalhesDeLogin: "Date de conectare",
    dispositivos: "Dispozitive",
    usuariosBloqueados: "Utilizatori blocați",
    aplicativosAutorizados: "Aplicații autorizate",
    sessoes: "Sesiuni",
    amigosEDms: "Prieteni și mesaje directe",
    compartilhamentoDeAtividade: "Partajarea activității",
    visibilidadeDoPerfil: "Vizibilitatea profilului",
    exportarDados: "Exportă datele",
    exclusaoDeDados: "Șterge datele",
    tema: "Temă",
    corDeDestaque: "Culoare de accent",
    interface: "Interfață",
    listaDeCanais: "Lista de canale",
    zoomDoApp: "Nivel de zoom al aplicației",
    escalaDaFonte: "Scara fontului din chat",
    modoStreamer: "Confidențialitate la transmisiune",
    movimento: "Mișcare",
    textoEmVoz: "Text în vorbire",
    teclado: "Tastatură",
    formatoDaHora: "Formatul orei",
    idiomaDaInterface: "Limba interfeței",
    dispositivosDeVoz: "Dispozitive",
    testeDoMicrofone: "Testul microfonului",
    modoDeEntrada: "Mod de intrare",
    sensibilidade: "Sensibilitatea intrării",
    qualidade: "Calitate",
    camera: "Cameră",
    transmissao: "Transmisiune",
    exibicao: "Afișare",
    entrada: "Introducere",
    midia: "Media",
    geral: "General",
    preferenciaDeMencao: "Preferință de menționare",
    sons: "Sunete",
  },
};
