export const conversa = {
  lista: {
    carregando: "Se încarcă mesajele…",
    carregandoMais: "Se încarcă…",
    verMais: "Derulează în sus ca să vezi mai mult",
    semHistorico: "Istoricul nu este disponibil",
    semHistoricoDetalhe: "Rolul tău nu are permisiunea de a citi istoricul canalului #{{canal}}. Mesajele noi continuă să apară cât timp ești aici.",
    boasVindas: "Bine ai venit pe #{{canal}}",
    boasVindasDetalhe: "Aici începe canalul #{{canal}}.",
  },
  data: {
    hoje: "Azi",
    ontem: "Ieri",
    hojeAs: "azi la {{hora}}",
    ontemAs: "ieri la {{hora}}",
  },
  digitando: {
    um: "{{nome}} scrie…",
    dois: "{{primeiro}} și {{segundo}} scriu…",
    varios: "{{quantidade}} persoane scriu…",
  },
  mensagem: {
    usou: "a folosit",
    fixada: "fixat",
    editado: "(editat)",
    ignorada: "Mesaj de la cineva pe care îl ignori.",
    mostrar: "Arată",
    escPara: "Esc pentru a",
    cancelar: "anula",
    enterParaSalvar: "Enter pentru a salva",
    falhou: "Nu a fost trimis. Încearcă din nou",
    naoLidasDaqui: "Necitite de aici.",
    linkCopiado: "Linkul a fost copiat.",
    idCopiado: "ID-ul a fost copiat.",
    naoDeuParaCopiar: "Browserul tău nu a permis copierea.",
    apagarTitulo: "Ștergi mesajul?",
    apagarDescricao: "Dispare pentru toată lumea din canal. Nu se poate recupera.",
    apagarAcao: "Șterge",
    citacaoAnexo: "dă clic ca să vezi atașamentul",
    citacaoSumiu: "Mesajul original nu mai este aici.",
    reagirCom: "Reacționează cu {{emoji}} — ține apăsat pentru super reacție",
    segureParaSuper: "{{emoji}} — ține apăsat pentru super reacție",
  },
  acoes: {
    reagir: "Reacționează",
    responder: "Răspunde",
    encaminhar: "Redirecționează",
    favoritar: "Salvează mesajul",
    tirarDosFavoritos: "Scoate din salvate",
    marcarNaoLida: "Marchează ca necitit",
    copiarLink: "Copiază linkul mesajului",
    copiarId: "Copiază ID-ul mesajului",
    fixar: "Fixează mesajul",
    desafixar: "Anulează fixarea",
    editar: "Editează",
    apagar: "Șterge",
    mais: "Mai multe",
    adicionarReacao: "Adaugă o reacție",
    superReagirCom: "Super reacție cu {{emoji}}",
    fixarMensagem: "Fixează mesajul",
    desafixarMensagem: "Anulează fixarea mesajului",
    editarMensagem: "Editează mesajul",
    apagarMensagem: "Șterge mesajul",
  },
  mencao: {
    cargo: "Menționare de rol",
    pessoa: "Menționare",
    alguem: "cineva",
    cargoSemNome: "rol",
    here: "Anunță pe cine este online",
    everyone: "Anunță tot serverul",
  },
  codigo: {
    copiar: "Copiază",
    copiado: "Copiat",
    copiarAria: "Copiază codul",
    copiadoAria: "Codul a fost copiat",
  },
  caixa: {
    escrever: "Scrie în #{{canal}}",
    escreverSemCanal: "Scrie un mesaj",
    semPermissao: "Nu ai permisiunea de a trimite mesaje în acest canal",
    solteParaAnexar: "Eliberează ca să atașezi",
    respondendoPara: "Răspuns pentru",
    vaiNotificar: "Persoana va fi notificată",
    naoVaiNotificar: "Persoana nu va fi notificată",
    ligado: "pornit",
    desligado: "oprit",
    pararDeResponder: "Renunță la răspuns",
    mais: "Mai multe",
    enviarArquivo: "Trimite un fișier",
    criarEnquete: "Creează un sondaj",
    expressoes: "Emoji, GIF și abțibilduri",
    enviar: "Trimite",
    aguardandoEnvio: "Se așteaptă încărcarea",
    modoLento: "Mod lent activ ({{tempo}})",
    modoLentoDica: "Modul lent este setat la {{segundos}} s. Așteaptă înainte de a trimite alt mesaj.",
  },
  anexos: {
    enviando: "Se încarcă…",
    modificar: "Modifică {{arquivo}}",
    remover: "Elimină {{arquivo}}",
    ver: "Vezi {{arquivo}}",
    mostrarSpoiler: "Arată spoilerul: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Editează atașamentul",
    nomeDoArquivo: "Numele fișierului",
    descricao: "Descrierea textului alternativ",
    descricaoDica: "Descrie acest fișier pentru cititoarele de ecran",
    marcarSpoiler: "Marchează ca spoiler",
    cancelar: "Anulează",
    salvar: "Salvează",
  },
  cartao: {
    tocador: "Player",
    abrir: "Deschide {{destino}}",
    tocar: "Redă {{titulo}}",
    video: "videoclip",
    verImagem: "Vezi imaginea",
  },
  enquete: {
    titulo: "Sondaj",
    encerrada: "Sondaj închis",
    variasRespostas: "Sondaj — mai multe răspunsuri",
    umVoto: "{{quantidade}} vot",
    votos: "{{quantidade}} voturi",
    umVotoNoTotal: "{{quantidade}} vot în total",
    votosNoTotal: "{{quantidade}} voturi în total",
    encerraEm: "se închide pe {{quando}}",
    encerrarAgora: "Închide acum",
  },
  fixadas: {
    titulo: "Mesaje fixate",
    vazio: "Acest canal nu are mesaje fixate… deocamdată.",
    desafixar: "Anulează fixarea",
    anexo: "(atașament)",
    enquete: "(sondaj)",
    dicaRotulo: "UN PONT:",
    dica: "cine are permisiunea „Gestionarea mesajelor” poate fixa direct din meniul mesajului.",
  },
  encaminhar: {
    titulo: "Redirecționează mesajul",
    paraOnde: "Unde?",
    semTexto: "(mesaj fără text)",
    nenhumLugar: "Niciun loc cu acest nume.",
    canais: "Canale",
    conversas: "Mesaje directe",
  },
};
