export const perfil = {
  carregando: "Se încarcă…",
  editar: "Editează profilul",
  mensagem: "Mesaj",
  abrirConversa: "Deschide conversația",
  verCompleto: "Vezi profilul complet",
  convidarParaServidor: "Invită pe server",
  semServidores: "Nu ai niciun server",
  conviteEnviado: "Invitație trimisă către {{nome}}.",
  moderador: "Deschide în vizualizarea de moderator",
  mais: "Mai multe",
  ignorar: "Ignoră",
  deixarDeIgnorar: "Nu mai ignora",
  copiarId: "Copiază ID-ul utilizatorului",
  idCopiado: "ID copiat.",
  conexoes: "Conexiuni",
  membroDesde: "Membru din",
  sobre: "Despre",
  cargosTitulo: "Roluri",
  visaoGeral: "Prezentare generală",
  amigosEmComum: "Prieteni în comun ({{quantidade}})",
  servidoresEmComum: "Servere în comun ({{quantidade}})",
  amizade: {
    amigo: "Prieten",
    pedidoEnviado: "Cerere de prietenie trimisă",
    respondaAbaixo: "Ți-a trimis o cerere — răspunde mai jos",
    adicionar: "Adaugă prieten",
    teMandouPedido: "Ți-a trimis o cerere de prietenie",
    aceitar: "Acceptă",
    desfazer: "Șterge din prieteni",
    desfazerTitulo: "Ștergi {{nome}} dintre prietenii tăi?",
    desfazerDescricao: "Nu mai sunteți prieteni. Conversația privată rămâne în istoric și îl poți adăuga din nou mai târziu.",
    bloquear: "Blochează",
    bloquearTitulo: "Blochezi {{nome}}?",
    bloquearDescricao: "Nu mai sunteți prieteni, conversația privată nu mai acceptă mesaje, iar el nu îți mai poate trimite cerere de prietenie.",
    linkCopiado: "Nu sunteți prieteni — linkul a fost copiat ca să i-l trimiți tu.",
  },
  recado: {
    escrever: "Scrie-i lui @{{usuario}}",
    enviar: "Trimite",
    enviada: "Mesaj trimis",
    falhou: "Nu s-a putut trimite. Încearcă din conversație.",
  },
  cartao: {
    trocarFaixa: "Schimbă bannerul cardului",
    trocarFaixaCurto: "Schimbă bannerul",
    trocarFoto: "Schimbă poza de profil",
    trocarFotoCurto: "Schimbă poza",
    suaEtiqueta: "Eticheta ta",
    editarEtiqueta: "Dă clic ca să îți editezi eticheta",
    conteAlgo: "Spune-ne ceva despre tine",
    adicionarStatus: "Adaugă o stare",
    adicionarDescricao: "Dă clic ca să adaugi o descriere",
    cargo: "Rol",
    cargos: "Roluri",
    cargosCom: "Roluri — {{quantidade}}",
    tirarCargo: "Scoate rolul {{cargo}}",
  },
  cargos: {
    adicionar: "Adaugă rol",
    procurar: "Caută un rol",
  },
  etiqueta: {
    escolher: "Alege eticheta de server",
    nenhuma: "Nicio etichetă de server",
    semEtiqueta: "Niciunul dintre serverele tale nu are etichetă",
  },
  emblemas: {
    doServidor: "Insignele acestui server",
    limite: "Poți purta până la {{quantidade}} insigne.",
  },
  nota: {
    vazia: "Dă clic ca să notezi ceva",
    rotulo: "Notiță (o vezi doar tu)",
  },
  status: {
    titulo: "Stare",
    definir: "Setează-ți starea",
    escolherEmoji: "Alege emoji",
    tirarEmoji: "Scoate emoji-ul",
    oQuePensa: "La ce te gândești?",
    limparAgora: "Șterge starea acum",
    naoLimpar: "Nu șterge",
    limpar30m: "Șterge peste 30 de minute",
    limpar1h: "Șterge peste 1 oră",
    limpar4h: "Șterge peste 4 ore",
    limparHoje: "Șterge azi",
    limparAmanha: "Șterge mâine",
    comHora: "{{prazo}} la {{hora}}",
  },
  presenca: {
    disponivel: "Disponibil",
    ausente: "Plecat",
    naoPerturbar: "Nu deranja",
    naoPerturbarDetalhe: "Nu primești notificare pentru mesaje noi",
    invisivel: "Invizibil",
    invisivelDetalhe: "Pentru ceilalți apari offline",
  },
  menu: {
    mudarDeConta: "Schimbă contul",
    gerenciarContas: "Gestionează conturile",
  },
  editor: {
    decoracao: "Schimbă decorațiunea avatarului",
    naoSalvo: "Nu uita să îți salvezi modificările!",
    principal: "Profil principal",
  },
};
