export const servidor = {
  titulo: "Setările serverului",
  auditoria: {
    todasAsAcoes: "Toate acțiunile",
    todosOsUsuarios: "Toți utilizatorii",
    filtroMembros: "Membri",
    filtroCanais: "Canale",
    filtroEmojis: "Emoji",
    filtroServidor: "Server",
    titulo: "Jurnalul acțiunilor",
    porUsuario: "Filtrează după persoană",
    porAcao: "Filtrează după acțiune",
    vazio: "Încă nu s-a înregistrat nimic cu acest filtru.",
    motivo: "Motiv:",
  },
  banimentos: {
    titulo: "Lista de interdicții a serverului",
    descricao: "Cine e aici nu mai intră nici cu invitație nouă. Ridicarea interdicției redă accesul pe loc.",
    procurar: "Caută interdicții după nume de utilizator",
    vazioTitulo: "Fără interdicții",
    vazio: "Încă nu ai interzis pe nimeni… dar dacă și când va fi nevoie, nu ezita.",
    desbanir: "Ridică interdicția",
  },
  excluir: {
    tudoVai: "Toate canalele, mesajele și invitațiile din {{servidor}} vor fi șterse pentru cei {{membros}} membri. Nimeni nu le mai recuperează după aceea.",
    digite: "Scrie {{servidor}} ca să confirmi",
    titulo: "Șterge serverul",
    aviso: "Asta nu se poate anula.",
  },
  emblemas: {
    apagarDescricao: "Iese de la oricine îl poartă. Nu se poate anula.",
    titulo: "Insigne",
    vazio: "Încă nu există insigne.",
    novo: "Insignă nouă",
  },
  convites: {
    revogarTitulo: "Revoci invitația?",
    revogarAcao: "Revocă",
    revogarDescricao: "Linkul {{codigo}} încetează să funcționeze pe loc. Cine a intrat deja prin el rămâne pe server.",
    titulo: "Invitații",
    descricao: "Toate linkurile de invitație active ale acestui server.",
    vazio: "Încă nu s-a creat nicio invitație.",
    revogar: "Revocă invitația",
  },
  integracoes: {
    opcionais: "username și avatar_url sunt opționale și se aplică per mesaj. Limita e de 5 mesaje la fiecare 5 secunde.",
    apagarDescricao: "URL-ul încetează să funcționeze pe loc. Mesajele pe care le-a trimis deja rămân în canal.",
    titulo: "Integrări",
    descricao: "Un webhook e o adresă care postează într-un canal fără să aibă nevoie de cont. E util ca să anunțe că un build a trecut, că cineva a deschis un tichet, sau orice vrei să trimiți dintr-un script.",
    novo: "Webhook nou",
    vazio: "Încă nu există webhookuri. Creează unul și lipește URL-ul acolo de unde vrei să vină mesajul.",
    canal: "Canal",
    apagar: "Șterge webhookul",
    comoUsar: "Cum se folosește",
    comoUsarTexto: "Trimite un POST cu JSON. Formatul e același ca la Discord, așa că un script care există deja funcționează nemodificat:",
  },
  engajamento: {
    semCanal: "Fără canal de sistem",
    titulo: "Implicare",
    descricao: "Ce face serverul de unul singur ca să nu pară gol când vine cineva nou.",
    sistema: "Mesaje de sistem",
    boasVindas: "Trimite un mesaj de bun venit când intră cineva",
    sorteio: "Fără text propriu dedesubt, fraza se trage la sorți — mereu aceeași plictisește repede.",
    canalDoSistema: "Canalul mesajelor de sistem",
    mensagem: "Mesaj de bun venit",
    deixeVazio: "Lasă gol ca să se tragă la sorți dintre frazele gata făcute",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtre care moderează singure, înainte ca mesajul să existe. Cine administrează serverul nu e niciodată filtrat — iar rolurile scutite trec direct.",
    palavras: {
      titulo: "Blochează cuvinte personalizate",
      descricao: "Lista ta de cuvinte pe care nimeni nu le poate scrie.",
    },
    mencoes: {
      titulo: "Blochează spamul cu mențiuni",
      descricao: "Blochează un mesaj cu prea multe mențiuni deodată.",
    },
    links: {
      titulo: "Blochează linkurile",
      descricao: "Reține orice adresă lipită în chat.",
    },
    definir: "Configurează",
    nomeDaRegra: "Numele regulii",
    bloqueadas: "Cuvinte blocate",
    digiteEnter: "Scrie și apasă Enter",
    comparacao: "Comparația ignoră majusculele, diacriticele și punctuația — și nu prinde un cuvânt în interiorul altuia.",
    aPartirDe: "Blochează de la câte mențiuni",
    oQueFazer: "Ce să facă",
    canalDoAlerta: "Canalul alertei",
    escolhaCanal: "Alege un canal",
    castigo: "Restricție (minute)",
    isentos: "Roluri scutite",
    semCargos: "Încă nu a fost creat niciun rol.",
    salvarRegra: "Salvează regula",
    apagar: "Șterge regula",
    excluirTitulo: "Ștergi această regulă AutoMod?",
    excluirDescricao: "Serverul nu mai filtrează după ea pe loc. Poți să o creezi din nou, dar configurația actuală se pierde.",
    excluirAcao: "Șterge regula",
  },
  cargos: {
    titulo: "Roluri",
    descricao: "Rolurile dau nume, culoare și puteri. Cine e mai sus în listă comandă peste cei de dedesubt — și nimeni nu se atinge de un rol egal sau superior celui propriu.",
    criar: "Creează rol",
    vazio: "Încă nu există roluri.",
    abaExibicao: "Afișare",
    abaPermissoes: "Permisiuni",
    abaMembros: "Membri — {{quantos}}",
    everyone: "Se aplică tuturor de pe server. E baza peste care se adună celelalte roluri.",
    nomeDoCargo: "Numele rolului",
    cor: "Culoarea rolului",
    corDica: "Colorează numele celui care are rolul în lista de membri și în chat.",
    semCor: "Fără culoare",
    corPersonalizada: "Culoare personalizată",
    estilo: "Stilul numelui",
    segundaCor: "A doua culoare",
    segundaCorDica: "Fără ea, degradeul revine la culoare plină — nu dispare.",
    limparSegundaCor: "Șterge a doua culoare",
    icone: "Pictogramă",
    iconeDica: "Apare lângă rol pe cardul de profil al celui care îl are.",
    exibirSeparado: "Afișează separat de ceilalți membri",
    exibirSeparadoDica: "Rolul primește o secțiune proprie în lista de membri.",
    permitirMencionar: "Permite menționarea acestui rol",
    permitirMencionarDica: "Oricine va putea notifica pe toți cei care au rolul.",
    semPoderDeConceder: "{{descricao}} (nu ai această permisiune ca să o acorzi)",
    adicionar: "Adaugă pe cineva la acest rol",
    tirar: "Ia rolul",
    semNinguem: "Încă nu are nimeni acest rol.",
    apagar: "Șterge rolul",
    excluirTitulo: "Ștergi rolul „{{nome}}\"?",
    excluirDescricao: "Cine are acest rol pierde tot ce îi dădea. Nu se poate anula.",
    excluirAcao: "Șterge rolul",
  },
  membros: {
    procurar: "Caută după nume sau nume de utilizator",
    membroDesde: "Membru din",
    vazio: "Nu a fost găsit nimeni.",
    acoesPara: "Acțiuni pentru {{nome}}",
    deCastigo: "de restricție",
    tirarCastigo: "Ridică restricția",
    castigo5min: "5 minute",
    castigo1h: "1 oră",
    castigo1d: "1 zi",
    castigo1s: "1 săptămână",
    expulsar: "Dă afară",
    expulsarTitulo: "Îl dai afară pe {{nome}}?",
    expulsarDescricao: "pleacă din {{servidor}} pe loc. Poate reveni cu o invitație — darea afară nu împiedică întoarcerea.",
    banir: "Interzice",
    banirTitulo: "Îi interzici accesul lui {{nome}}?",
    banirDescricao: "pleacă din {{servidor}} și nu mai poate reveni, nici cu invitație, până nu i se ridică interdicția.",
    motivo: "Motiv (opțional)",
    motivoDica: "Rămâne în jurnalul acțiunilor",
  },
  perfil: {
    titulo: "Profilul serverului",
    descricao: "Așa apare serverul tău în listă și în linkurile de invitație.",
    icone: "Pictogramă",
    faixa: "Banner sus",
    nomeDoServidor: "Numele serverului",
    campoDescricao: "Descriere",
    doQueE: "Despre ce e serverul ăsta?",
    comprimido: "Comprimat înainte de încărcare: {{economia}}",
  },
  etiqueta: {
    titulo: "Eticheta serverului",
    descricao: "O etichetă de maximum 4 litere care apare lângă numele fiecărui membru — în chat și în lista de persoane. Aici e gratis: fără boost, fără niveluri.",
    escolhaNome: "Alege un nume",
    limite: "Maximum 4 caractere, litere și cifre.",
    escolhaInsignia: "Alege o insignă",
    voce: "Tu",
    fala1: "are cineva chef de un joc?",
    fala2: "aruncă un ochi la eticheta mea!",
    fala3: "uau, cum ai obținut-o",
  },
  expressoes: {
    comoUsar: "Adaugă până la {{limite}} emoji pe care oricine le poate folosi pe acest server. Scrie :nume: în chat ca să îl trimiți.",
    imagem: "Imagine",
    enviadoPor: "Încărcat de",
    semEmoji: "Încă nu există emoji.",
    figurinhas: "Autocolante",
    enviarFigurinha: "Încarcă autocolant",
    nomeDaFigurinha: "Numele autocolantului",
    exemploFigurinha: "Ex.: îmbrățișare de pisoi",
    figurinhaGrande: "Autocolantul depășește {{limite}}.",
    deixaPraLa: "Lasă",
    sons: "Panoul de sunete",
    enviarSom: "Încarcă sunet",
    nomeDoSom: "Numele sunetului",
    semSom: "Încă nu există sunete.",
    somGrande: "Sunetul depășește {{limite}}.",
    emojiRelacionado: "Emoji asociat",
    ouvir: "Ascultă",
    ouvirAssim: "Ascultă așa",
    volumeDe: "Volumul lui {{nome}}",
    volumeDica: "Se aplică tuturor de pe server. Fiecare poate totuși să dea sunetele mai încet doar pentru el, în panoul apelului.",
    falhaEnvio: "Fișierul nu a putut fi încărcat.",
    excluirTitulo: "Ștergi {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Dispare de pe server pentru toată lumea. Mesajele care l-au folosit deja rămân cum sunt.",
  },
  canal: {
    visaoGeral: "Prezentare generală",
    nome: "Numele canalului",
    topico: "Subiectul canalului",
    topicoDica: "Despre ce se vorbește aici?",
    modoLento: "Fiecare trimite un singur mesaj pe interval. Cine gestionează mesaje sau canale trece direct.",
    visibilidade: "Vizibilitatea conținutului",
    padrao: "Implicit",
    padraoDica: "Conținutul canalului e mereu vizibil.",
    spoiler: "Canal cu spoilere",
    spoilerDica: "Marchează acest canal ca având spoilere, ca răsturnările de situație și subiectele grele să rămână ascunse până alege cineva să le vadă.",
    idade: "Canal cu restricție de vârstă",
    idadeDica: "Cine intră trebuie să confirme că e major ca să vadă conținutul.",
    bitrateDica: "Peste 64 kbps poate deranja pe cine are internet slab.",
    qualidadeDeVideo: "Calitatea video",
    automatica: "Automată",
    limite: "Limită de utilizatori — {{valor}}",
    pessoas: "{{quantos}} persoane",
    semLimite: "fără limită",
    permissoesDescricao: "Aici schimbi ce se aplică în acest canal. Ce rămâne pe „moștenește” continuă să urmeze rolul.",
    excluir: {
      titulo: "Șterge canalul",
      historico: "Tot istoricul canalului {{canal}} pleacă odată cu el, pentru toată lumea.",
      digite: "Scrie {{canal}} ca să confirmi",
    },
  },
  moderacao: {
    titulo: "Vizualizare de moderator",
    semPermissao: "Ai nevoie de permisiunea „Moderează membrii” ca să vezi asta.",
    fecharEsc: "Închide (Esc)",
    atividade: "Activitate pe server",
    mensagens: "Mesaje",
    links: "Linkuri",
    midia: "Media",
    acoesNaAuditoria: "Acțiuni în jurnal",
    moderacoesSofridas: "Moderări primite",
    permissoes: "Permisiuni ({{quantas}})",
    semPermissaoEspecial: "Nicio permisiune specială.",
    conta: "Cont",
    entrouNoServidor: "A intrat pe server",
    contaCriadaEm: "Cont creat pe",
    deCastigoAte: "Restricționat până la",
    formaDeAdesao: "Cum a intrat",
    mensagem: "Mesaj",
    castigo: "Restricție",
    copiarId: "Copiază ID-ul",
    idCopiado: "ID copiat.",
    adicionarCargo: "Adaugă rol",
    semCargos: "Niciun rol creat",
    soEveryone: "Doar @everyone.",
    voltar: "Înapoi",
    vazio: "Nimic pe aici.",
    cinquenta: "Se arată cele mai recente 50.",
    irParaMensagem: "Mergi la mesaj",
    precisaSerAmigo: "Trebuie să fiți prieteni ca să vorbiți.",
    expulsarDescricao: "Pleacă de pe server pe loc, dar poate reveni cu o invitație.",
    banirDescricao: "Pleacă de pe server și nu mai poate reveni, nici cu invitație, până nu i se ridică interdicția.",
    castigarTitulo: "Îl restricționezi pe {{nome}}?",
    castigoDescricao: "Cât ține, nu scrie și nu vorbește în niciun canal al serverului.",
    aplicarCastigo: "Aplică restricția",
    duracao: "Durata în minute",
    informeDuracao: "Spune durata în minute.",
  },
  abas: {
    expressoes: "Expresii",
    pessoas: "Oameni",
    apps: "Aplicații",
    moderacao: "Moderare",
    banimentos: "Interdicții",
  },
};
