export const configuracoes = {
  telas: {
    conta: "Mi cuenta",
    privacidade: "Privacidad",
    conexoes: "Conexiones",
    voz: "Audio",
    video: "Video",
    avisos: "Notificaciones",
    aplicativos: "Aplicaciones",
    aparencia: "Apariencia",
    batePapo: "Chat",
    acessibilidade: "Accesibilidad",
    idioma: "Idioma",
    aplicativo: "Descargar la app",
    servidor: "Servidor",
  },
  grupos: {
    conta: "Cuenta",
    app: "Ajustes de la app",
    desenvolvedor: "Desarrollador",
    administracao: "Administración",
  },
  secoes: {
    detalhesDeLogin: "Datos de acceso",
    dispositivos: "Dispositivos",
    usuariosBloqueados: "Usuarios bloqueados",
    aplicativosAutorizados: "Aplicaciones autorizadas",
    sessoes: "Sesiones",
    amigosEDms: "Amigos y mensajes directos",
    compartilhamentoDeAtividade: "Compartir actividad",
    visibilidadeDoPerfil: "Visibilidad del perfil",
    exportarDados: "Exportar datos",
    exclusaoDeDados: "Eliminar datos",
    tema: "Tema",
    corDeDestaque: "Color de acento",
    interface: "Interfaz",
    listaDeCanais: "Lista de canales",
    zoomDoApp: "Nivel de zoom de la app",
    escalaDaFonte: "Escala de la fuente del chat",
    modoStreamer: "Privacidad en transmisión",
    movimento: "Movimiento",
    textoEmVoz: "Texto a voz",
    teclado: "Teclado",
    formatoDaHora: "Formato de hora",
    idiomaDaInterface: "Idioma de la interfaz",
    dispositivosDeVoz: "Dispositivos",
    testeDoMicrofone: "Prueba del micrófono",
    modoDeEntrada: "Modo de entrada",
    sensibilidade: "Sensibilidad de entrada",
    qualidade: "Calidad",
    camera: "Cámara",
    transmissao: "Transmisión",
    exibicao: "Visualización",
    entrada: "Entrada",
    midia: "Medios",
    geral: "General",
    preferenciaDeMencao: "Preferencia de mención",
    sons: "Sonidos",
  },
};
