export const amizades = {
  ativosAgora: "Aktive nu",
  procurando: "Ser efter hvem der er her…",
  tudoTranquilo: "Der er stille lige nu…",
  tudoTranquiloDetalhe: "Når du eller en ven går ind i et opkald, dukker det op her — og du kan hoppe med i ét klik.",
  emVoz: "I tale",
  voce: "Dig",
  soVoce: "Kun dig",
  pessoas: "{{quantas}} personer",
  voltarParaChamada: "Tilbage til opkaldet",
  entrarNaChamada: "Deltag i opkaldet",
  abrirCanal: "Åbn {{canal}} på {{servidor}}",
  mensagensDiretas: "Direkte beskeder",
  encontreConversa: "Find en samtale",
  amigos: "Venner",
  conversas: "Samtaler",
  semConversas: "Ingen samtaler endnu. Tilføj en ven for at komme i gang.",
  semConversaComEsseNome: "Ingen samtale med det navn.",
  abrirMenu: "Åbn servere og samtaler",
  solicitacoes: "Beskedanmodninger",
  pedidos: "Anmodninger",
  spam: "Spam",
  pedidosPendentes: "Ventende anmodninger",
  marcadosComoSpam: "Markeret som spam",
  aceitar: "Accepter",
  ignorar: "Ignorer",
  marcarSpam: "Markér som spam",
  semPedidos: "Ingen anmodninger venter.",
  semPedidosDetalhe: "Den der ikke er din ven, men deler en server med dig, lander her, før det når dine samtaler.",
  semSpam: "Intet markeret som spam.",
  semSpamDetalhe: "Det spamfilteret sorterer fra, eller det du selv markerer, bliver i denne fane.",
  umServidorEmComum: "1 fælles server",
  servidoresEmComum: "{{quantos}} fælles servere",
  semServidoresEmComum: "Ingen fælles servere",
};
