export const chamada = {
  conectando: "Opretter forbindelse til opkaldet…",
  naoEntrou: "Kunne ikke deltage i opkaldet",
  sair: "Forlad opkaldet",
  sairDaVoz: "Forlad taleopkaldet",
  desconectar: "Afbryd",
  voltar: "Tilbage til opkaldet",
  voltarAosQuadros: "Tilbage til opkaldsfelterne",
  fecharChat: "Luk chatten",
  carregandoPrevia: "Indlæser forhåndsvisningen…",
  maisOpcoes: "Flere muligheder",
  deVideo: "Videoopkald",
  deVoz: "Taleopkald",
  alguem: "Nogen",
  volume: {
    entrada: "Indgangslydstyrke",
    saida: "Udgangslydstyrke",
    live: "Udsendelsens lydstyrke",
    liveComPorcento: "Udsendelsens lydstyrke ({{porcento}} %)",
    liveSemSom: "Udsendelse uden lyd",
  },
  aparelhos: {
    entrada: "Inputenhed",
    saida: "Outputenhed",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Output",
    oDoSistema: "Systemets",
    aDoSistema: "Systemets",
    semEscolhaDeSaida: "Denne browser lader dig ikke vælge output — systemet bestemmer.",
    espelhar: "Spejlvend mit kamera",
    configEntrada: "Indstillinger for input",
    configSaida: "Indstillinger for output",
    configCamera: "Kameraindstillinger",
    configAudioEVideo: "Lyd- og videoindstillinger",
  },
  tela: {
    compartilhar: "Del skærm",
    compartilharAcao: "Del",
    cancelar: "Annullér",
    telas: "Skærme",
    janelas: "Vinduer",
    somDoComputador: "Tag computerens lyd med",
    somDoSistema: "Tag systemets lyd med",
    configCompartilhamento: "Delingsindstillinger",
    mostrarSemVideo: "Vis dem uden video",
    semFontes: "Systemet returnerede ingen skærm eller vindue at dele.",
    pararDeCompartilhar: "Stop delingen",
    encerrarTransmissao: "Afslut udsendelsen",
  },
  live: {
    etiqueta: "Live",
    etiquetaMaiuscula: "LIVE",
    assistir: "Se udsendelsen",
    assistirPessoa: "Se {{nome}}",
    pararDeAssistir: "Stop med at se",
  },
  membro: {
    mudarMeuApelido: "Skift mit kaldenavn",
    meuMicrofone: "Min mikrofon",
    ouvirChamada: "Lyt til opkaldet",
    copiarMeuId: "Kopiér mit ID",
    idCopiado: "ID kopieret.",
    mensagem: "Besked",
    silenciar: "Slå lyden fra",
    alterarApelido: "Skift kaldenavn",
    cargos: "Roller",
    semCargo: "Der er ikke oprettet nogen rolle",
    moverPara: "Flyt til",
    silenciarNoServidor: "Slå stemmen fra på serveren",
    desativarAudioNoServidor: "Slå lyden fra på serveren",
    desconectar: "Afbryd",
    apelidoTitulo: "Dit kaldenavn på denne server",
    apelidoDeAlguem: "Kaldenavn for {{nome}}",
    apelidoCampo: "Kaldenavn",
    apelidoDicaPropria: "Gælder kun her. Lad feltet stå tomt for at vende tilbage til dit sædvanlige navn.",
    apelidoDicaDeOutro: "Gælder kun på denne server. Lad feltet stå tomt for at vende tilbage til det oprindelige navn.",
  },
  detalhes: {
    abrir: "Stemmedetaljer",
    titulo: "Stemmedetaljer",
    conexao: "Forbindelse",
    pingMedio: "Gennemsnitligt ping",
    ultimoPing: "Seneste ping",
    perda: "Tab af sendte pakker",
    medindo: "Måler…",
    criptografado: "Krypteret hele vejen til serveren (DTLS-SRTP)",
    explicacao: "Over 250 ms kan man høre forsinkelsen i samtalen — folk begynder at tale i munden på hinanden. Pakketab over 10 % gør stemmen robotagtig. I begge tilfælde sidder problemet næsten altid mellem dig og internettet: prøv kabel i stedet for wi-fi, eller genstart routeren.",
  },
  microfone: {
    bloqueado: "Mikrofonen er blokeret — du lytter kun. Giv adgang i browserens tilladelser.",
    bloqueadoNoMac: "macOS blokerer mikrofonen. Sæt flueben ved",
    caminhoNoMac: "Systemindstillinger → Anonymitet og sikkerhed → Mikrofon",
    abrirAjustes: "Åbn indstillingerne",
    vaiReabrir: "macOS beder dig om at åbne appen igen.",
    naoAbriu: "Kunne ikke åbne mikrofonen — du lytter kun. Tjek enheden under Indstillinger → Stemme og video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS har ikke tilladt skærmoptagelse endnu. Uden det bliver delingen sort.",
    marque: "Sæt flueben ved",
    reabra: "under Skærmoptagelse, og åbn appen igen.",
  },
  ruido: {
    titulo: "Støjreduktion",
    explicacao: "Fjern baggrundsstøjen fra din stemme. Prøv at klappe eller trække tastaturet, mens du taler — de i opkaldet hører kun dig.",
    semSuporte: "Denne browser kører ikke den avancerede reduktion. Browserens egen gælder stadig, og den er svagere.",
    aplicando: "Anvender på opkaldet…",
    faleParaTestar: "Tal for at teste",
    verdeQuandoPassa: "Grøn når din stemme kommer igennem.",
    teOuvindo: "De hører dig lige nu.",
    feitoCom: "Lavet med",
    aquiNoAparelho: ", her på din egen enhed",
    ajustes: "Indstillinger",
  },
  permissoes: {
    titulo: "macOS-tilladelser",
    detalhe: "macOS spørger kun én gang, og derefter ændres det kun i dets eget panel. Her kan du se, hvad der gælder, og løse det, der mangler.",
    concedida: "Givet",
    negada: "Nægtet",
    naoPedida: "Ikke anmodet",
    permitir: "Tillad",
    abrirAjustes: "Åbn indstillinger",
    microfone: "Mikrofon",
    microfoneDetalhe: "Tale i opkald og teste dit input.",
    camera: "Kamera",
    cameraDetalhe: "Slå videoen til i opkaldet.",
    tela: "Skærmoptagelse",
    telaDetalhe: "Dele skærmen og vinduerne.",
    monitoramento: "Inputovervågning",
    monitoramentoDetalhe: "Bruge tryk-for-at-tale, også når Gravaê er i baggrunden.",
  },
  jaConectado: {
    titulo: "Du er allerede i dette opkald",
    trazer: "Hent opkaldet herover",
    deixar: "Lad det være",
    detalhe: "Henter du det herover, ryger den anden ende ud af opkaldet — din konto er ét sted ad gangen.",
  },
};
