export const configuracoes = {
  efeitos: {
    titulo: "Effekter for markøren",
    detalhe: "Spor og gnister tegnet oven på appen. De starter slukket og forsvinder af sig selv, hvis du har bedt om mindre bevægelse.",
    rastro: "Spor efter markøren",
    rastroDetalhe: "En streg der følger markøren og falmer bagude.",
    faisca: "Gnister ved klik",
    faiscaDetalhe: "Korte streger der spreder sig fra det sted, du klikkede.",
    cor: "Farve",
    espessura: "Tykkelse",
    comprimento: "Længde",
    tamanho: "Størrelse",
    quantidade: "Antal",
  },
  email: {
    verificarTitulo: "Bekræft din e-mail",
    verificarDetalhe: "Nogle fællesskaber lader kun de bekræftede skrive. Det tager ét klik.",
    enviar: "Send linket",
    enviado: "Kig i indbakken. Linket holder en dag.",
    falhou: "E-mailen kunne ikke sendes.",
    confirmado: "E-mail bekræftet",
    confirmadoDetalhe: "Så er den der. Nu kan du skrive i alle fællesskaber, der kræver det.",
    linkIncompleto: "Ufuldstændigt link",
    linkIncompletoDetalhe: "Koden mangler i adressen. Åbn linket direkte fra e-mailen.",
    confirmando: "Bekræfter…",
    expirou: "Linket er allerede brugt eller udløbet.",
    irParaOApp: "Gå til appen",
  },
  tema: {
    indisponivel: "Temaet er ikke tilgængeligt",
    indisponivelDetalhe: "Den, der udgav det, har slettet det, eller linket er forkert.",
    indisponivelLinha: "Temaet er ikke tilgængeligt. Den, der udgav det, har slettet det, eller linket er forkert.",
    importar: "Importér tema",
    importarCurto: "Importér",
    importarDetalhe: "Det erstatter det tema, du har nu. Du kan redigere det bagefter i Indstillinger > Udseende > Temastudie.",
    porAutor: "af {{autor}}",
    umaCorTrocada: "1 udskiftet farve",
    coresTrocadas: "{{quantas}} udskiftede farver",
    avisoDeCss: "Dette tema har CSS med fra den, der skrev det, og CSS rører hvert hjørne af skærmen. Importér kun fra folk, du stoler på.",
    soCores: "Dette tema skifter kun farver. Ingen CSS udefra.",
    aplicar: "Anvend",
    previaSemMotor: "Forhåndsvisningen kører ikke motoren. Installér for at se den.",
    motorAnimado: "{{motor}} animeret",
  },
  sair: "Log ud",
  versoes: {
    termos: "Servicevilkår",
    privacidade: "Privatlivspolitik",
    copiar: "Klik for at kopiere",
    copiado: "Kopieret",
  },
  telas: {
    conta: "Min konto",
    privacidade: "Privatliv",
    conexoes: "Forbindelser",
    voz: "Lyd",
    video: "Video",
    avisos: "Notifikationer",
    aplicativos: "Applikationer",
    aparencia: "Udseende",
    batePapo: "Chat",
    acessibilidade: "Tilgængelighed",
    idioma: "Sprog",
    aplicativo: "Hent appen",
    atalhos: "Genveje",
    desktop: "Skrivebordsapp",
    avancado: "Avanceret",
    servidor: "Server",
    comunicado: "Systemmeddelelse",
    denuncias: "Anmeldelser",
    publicacoes: "Udrulninger",
  },
  grupos: {
    conta: "Konto",
    app: "App-indstillinger",
    desenvolvedor: "Udvikler",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Loginoplysninger",
    dispositivos: "Enheder",
    usuariosBloqueados: "Blokerede brugere",
    aplicativosAutorizados: "Godkendte apps",
    sessoes: "Sessioner",
    amigosEDms: "Venner og direkte beskeder",
    compartilhamentoDeAtividade: "Aktivitetsdeling",
    visibilidadeDoPerfil: "Profilens synlighed",
    exportarDados: "Eksportér data",
    exclusaoDeDados: "Slet data",
    tema: "Tema",
    corDeDestaque: "Accentfarve",
    interface: "Grænseflade",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Appens zoomniveau",
    escalaDaFonte: "Skriftstørrelse i chatten",
    modoStreamer: "Streaming-privatliv",
    cursores: "Markører",
    movimento: "Bevægelse",
    textoEmVoz: "Tekst til tale",
    teclado: "Tastatur",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Grænsefladens sprog",
    dispositivosDeVoz: "Enheder",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inputtilstand",
    sensibilidade: "Inputfølsomhed",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Transmission",
    exibicao: "Visning",
    entrada: "Input",
    midia: "Medier",
    geral: "Generelt",
    preferenciaDeMencao: "Omtalepræference",
    sons: "Lyde",
  },
};
