export const configuracoes = {
  sair: "Log ud",
  versoes: {
    copiar: "Klik for at kopiere",
    copiado: "Kopieret",
  },
  telas: {
    conta: "Min konto",
    privacidade: "Privatliv",
    conexoes: "Forbindelser",
    voz: "Lyd",
    video: "Video",
    avisos: "Notifikationer",
    aplicativos: "Applikationer",
    aparencia: "Udseende",
    batePapo: "Chat",
    acessibilidade: "Tilgængelighed",
    idioma: "Sprog",
    aplicativo: "Hent appen",
    servidor: "Server",
  },
  grupos: {
    conta: "Konto",
    app: "App-indstillinger",
    desenvolvedor: "Udvikler",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Loginoplysninger",
    dispositivos: "Enheder",
    usuariosBloqueados: "Blokerede brugere",
    aplicativosAutorizados: "Godkendte apps",
    sessoes: "Sessioner",
    amigosEDms: "Venner og direkte beskeder",
    compartilhamentoDeAtividade: "Aktivitetsdeling",
    visibilidadeDoPerfil: "Profilens synlighed",
    exportarDados: "Eksportér data",
    exclusaoDeDados: "Slet data",
    tema: "Tema",
    corDeDestaque: "Accentfarve",
    interface: "Grænseflade",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Appens zoomniveau",
    escalaDaFonte: "Skriftstørrelse i chatten",
    modoStreamer: "Streaming-privatliv",
    movimento: "Bevægelse",
    textoEmVoz: "Tekst til tale",
    teclado: "Tastatur",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Grænsefladens sprog",
    dispositivosDeVoz: "Enheder",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inputtilstand",
    sensibilidade: "Inputfølsomhed",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Transmission",
    exibicao: "Visning",
    entrada: "Input",
    midia: "Medier",
    geral: "Generelt",
    preferenciaDeMencao: "Omtalepræference",
    sons: "Lyde",
  },
};
