export const configuracoes = {
  efeitos: {
    titulo: "Effekter for markøren",
    detalhe: "Spor og gnister tegnet oven på appen. De starter slukket og forsvinder af sig selv, hvis du har bedt om mindre bevægelse.",
    rastro: "Spor efter markøren",
    rastroDetalhe: "En streg der følger markøren og falmer bagude.",
    faisca: "Gnister ved klik",
    faiscaDetalhe: "Korte streger der spreder sig fra det sted, du klikkede.",
    cor: "Farve",
    espessura: "Tykkelse",
    comprimento: "Længde",
    tamanho: "Størrelse",
    quantidade: "Antal",
  },
  email: {
    verificarTitulo: "Bekræft din e-mail",
    verificarDetalhe: "Nogle fællesskaber lader kun de bekræftede skrive. Det tager ét klik.",
    enviar: "Send linket",
    enviado: "Kig i indbakken. Linket holder en dag.",
    falhou: "E-mailen kunne ikke sendes.",
    confirmado: "E-mail bekræftet",
    confirmadoDetalhe: "Så er den der. Nu kan du skrive i alle fællesskaber, der kræver det.",
    linkIncompleto: "Ufuldstændigt link",
    linkIncompletoDetalhe: "Koden mangler i adressen. Åbn linket direkte fra e-mailen.",
    confirmando: "Bekræfter…",
    expirou: "Linket er allerede brugt eller udløbet.",
    irParaOApp: "Gå til appen",
  },
  tema: {
    indisponivel: "Temaet er ikke tilgængeligt",
    indisponivelDetalhe: "Den, der udgav det, har slettet det, eller linket er forkert.",
    indisponivelLinha: "Temaet er ikke tilgængeligt. Den, der udgav det, har slettet det, eller linket er forkert.",
    importar: "Importér tema",
    importarCurto: "Importér",
    importarDetalhe: "Det erstatter det tema, du har nu. Du kan redigere det bagefter i Indstillinger > Udseende > Temastudie.",
    porAutor: "af {{autor}}",
    umaCorTrocada: "1 udskiftet farve",
    coresTrocadas: "{{quantas}} udskiftede farver",
    avisoDeCss: "Dette tema har CSS med fra den, der skrev det, og CSS rører hvert hjørne af skærmen. Importér kun fra folk, du stoler på.",
    soCores: "Dette tema skifter kun farver. Ingen CSS udefra.",
    verCss: "Vis CSS",
    esconderCss: "Skjul CSS",
    aplicar: "Anvend",
    previaSemMotor: "Forhåndsvisningen kører ikke motoren. Installér for at se den.",
    motorAnimado: "{{motor}} animeret",
  },
  sair: "Log ud",
  versoes: {
    termos: "Servicevilkår",
    privacidade: "Privatlivspolitik",
    copiar: "Klik for at kopiere",
    copiado: "Kopieret",
  },
  appColors: {
    title: "Appens farver",
    detail: "Vælg op til tre farver, så får hele appen den gradient.",
    locked: "Farveeditoren hører til {{plan}}.",
    color: "Farve {{number}}",
    addColor: "Tilføj farve",
    removeColor: "Fjern farve",
    surprise: "Overrask mig",
    direction: "Gradientens retning",
    intensity: "Intensitet",
    reset: "Nulstil",
  },
  subscription: {
    colorsRow: "Appens farveeditor",
    seePlans: "Se planer",
    upgradeSubtitle: "Højere grænser og eksklusive funktioner til at skrive, sende filer og streame.",
    perMonth: "om måneden",
    perYear: "om året",
    save: "Spar {{percent}} %",
    howToPay: "Hvordan vil du betale?",
    legal: "Du kan anmode om refusion inden for 7 dage efter betalingen. Betalingen håndteres af Stripe; vi ser aldrig dit kortnummer.",
    compare: "Gratis vs. Infinity",
    featureColumn: "Funktion",
    freeColumn: "Gratis",
    messageRow: "Tegngrænse pr. besked",
    attachmentRow: "Filstørrelse ved upload",
    screenRow: "Videokvalitet",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Du har allerede Infinity indtil {{date}}.",
    upsell: "Hæv grænsen med Infinity",
    screenUpsell: "Højere kvalitet med Infinity",
    free: "Du er på gratisplanen.",
    activeUntil: "Infinity aktiv indtil {{date}}.",
    renews: "Fornyes automatisk den {{date}}.",
    endsAt: "Abonnementet er opsagt og slutter den {{date}}.",
    pastDue: "Den seneste opkrævning mislykkedes. Opdater dit kort for at beholde Infinity.",
    waiting: "Bekræfter betalingen…",
    subscribe: "Abonner",
    monthly: "Månedlig",
    yearly: "Årlig",
    automatic: "Kort",
    manage: "Administrer betaling",
    refund: "Anmod om refusion",
    refundDetail: "Du kan fortryde inden for 7 dage efter betalingen: {{amount}}, indtil {{date}}.",
    refundConfirm: "Anmod om refusion?",
    refundConfirmDetail: "Pengene går tilbage til samme betalingsmetode, og Infinity stopper med det samme.",
    refunded: "Refusion anmodet.",
    unavailable: "Abonnementer er ikke tilgængelige endnu.",
    success: "Betaling modtaget. Tak!",
    canceled: "Betaling annulleret.",
    error: "Noget gik galt. Prøv igen.",
    no: "Nej",
    tagRow: "Eget brugertag",
    guildProfilesRow: "Profiler pr. fællesskab",
    badgeRow: "Profilmærke",
    communitiesRow: "Fællesskaber",
    savedRow: "Gemte beskeder",
    animatedEmojiRow: "Brug animerede emojis",
    expressionsRow: "Brug emojis og klistermærker overalt",
    animatedProfileRow: "Animerede avatarer og profilbannere",
    earlyAccessRow: "Tidlig adgang til nyheder",
    themesRow: "Egne temaer",
    pixOption: "Pix",
    pixHint: "Åbn din bankapp, vælg Pix og scan QR-koden eller brug kopiér og indsæt.",
    pixQrAlt: "Pix-QR-kode",
    pixCopy: "Kopiér Pix-kode",
    pixCopied: "Pix-kode kopieret",
    pixWaiting: "Venter på betaling",
    pixExpiresIn: "udløber om {{time}}",
    pixExpired: "Denne Pix er udløbet. Opret en ny for at fortsætte.",
    pixNew: "Opret ny Pix",
    pixPaid: "Pix modtaget! Dit Infinity er nu aktivt.",
    forMe: "Til mig",
    asGift: "Som gave",
    buyGift: "Køb gave",
    giftReady: "Gaven er klar! Kopiér linket og send det til hvem du vil.",
    giftClaimed: "Gaven er indløst! Infinity er på din konto.",
    gifts: "Gaver",
    giftsEmpty: "Du har ikke købt nogen gaver endnu.",
    giftCode: "Gavekode",
    giftRedeem: "Indløs",
    giftCopyLink: "Kopiér link",
    giftLinkCopied: "Link kopieret",
    giftClaimedBy: "indløst af {{name}}",
    giftHint: "Har du en gavekode? Indløs den her. Gaver, du har købt, står nedenfor.",
    cardPaid: "Betalingen blev godkendt! Dit Infinity er aktivt.",
    payAmount: "Betal {{amount}}",
    giftLinkTitle: "Du har fået en {{plan}}-gave!",
    giftLinkDetail: "Tryk på indløs, så lander dagene på din konto.",
    pageTitle: "Lås op for en verden af fordele med {{plan}}",
  },
  telas: {
    subscription: "Infinity",
    conta: "Min konto",
    privacidade: "Privatliv",
    conexoes: "Forbindelser",
    voz: "Lyd",
    video: "Video",
    avisos: "Notifikationer",
    aplicativos: "Applikationer",
    aparencia: "Udseende",
    batePapo: "Chat",
    acessibilidade: "Tilgængelighed",
    idioma: "Sprog",
    aplicativo: "Hent appen",
    atalhos: "Genveje",
    desktop: "Skrivebordsapp",
    avancado: "Avanceret",
    servidor: "Server",
    comunicado: "Systemmeddelelse",
    denuncias: "Anmeldelser",
    publicacoes: "Udrulninger",
  },
  grupos: {
    conta: "Konto",
    app: "App-indstillinger",
    desenvolvedor: "Udvikler",
    administracao: "Administration",
  },
  secoes: {
    coresDoApp: "Appens farver",
    detalhesDeLogin: "Loginoplysninger",
    dispositivos: "Enheder",
    usuariosBloqueados: "Blokerede brugere",
    aplicativosAutorizados: "Godkendte apps",
    sessoes: "Sessioner",
    amigosEDms: "Venner og direkte beskeder",
    compartilhamentoDeAtividade: "Aktivitetsdeling",
    visibilidadeDoPerfil: "Profilens synlighed",
    exportarDados: "Eksportér data",
    exclusaoDeDados: "Slet data",
    tema: "Tema",
    corDeDestaque: "Accentfarve",
    interface: "Grænseflade",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Appens zoomniveau",
    escalaDaFonte: "Skriftstørrelse i chatten",
    modoStreamer: "Streaming-privatliv",
    cursores: "Markører",
    movimento: "Bevægelse",
    textoEmVoz: "Tekst til tale",
    teclado: "Tastatur",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Grænsefladens sprog",
    dispositivosDeVoz: "Enheder",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inputtilstand",
    sensibilidade: "Inputfølsomhed",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Transmission",
    exibicao: "Visning",
    entrada: "Input",
    midia: "Medier",
    geral: "Generelt",
    preferenciaDeMencao: "Omtalepræference",
    sons: "Lyde",
  },
};
