export const conversa = {
  lista: {
    carregando: "Indlæser beskeder…",
    carregandoMais: "Indlæser…",
    verMais: "Rul op for at se mere",
    semHistorico: "Historikken er ikke tilgængelig",
    semHistoricoDetalhe: "Din rolle har ikke tilladelse til at læse historikken i #{{canal}}. Nye beskeder bliver ved med at dukke op, så længe du er her.",
    boasVindas: "Velkommen til #{{canal}}",
    boasVindasDetalhe: "Det er starten på kanalen #{{canal}}.",
  },
  data: {
    hoje: "I dag",
    ontem: "I går",
    hojeAs: "i dag kl. {{hora}}",
    ontemAs: "i går kl. {{hora}}",
  },
  digitando: {
    um: "{{nome}} skriver…",
    dois: "{{primeiro}} og {{segundo}} skriver…",
    varios: "{{quantidade}} personer skriver…",
  },
  mensagem: {
    usou: "brugte",
    fixada: "fastgjort",
    editado: "(redigeret)",
    ignorada: "Besked fra en, du ignorerer.",
    mostrar: "Vis",
    escPara: "Esc for at",
    cancelar: "annullere",
    enterParaSalvar: "Enter for at gemme",
    falhou: "Den blev ikke sendt. Prøv igen",
    naoLidasDaqui: "Ulæste herfra.",
    linkCopiado: "Linket er kopieret.",
    idCopiado: "ID er kopieret.",
    naoDeuParaCopiar: "Din browser tillod ikke kopiering.",
    apagarTitulo: "Slet beskeden?",
    apagarDescricao: "Den forsvinder for alle i kanalen. Den kan ikke hentes tilbage.",
    apagarAcao: "Slet",
    citacaoAnexo: "klik for at se vedhæftningen",
    citacaoSumiu: "Den oprindelige besked er her ikke længere.",
    reagirCom: "Reagér med {{emoji}} — hold nede for superreaktion",
    segureParaSuper: "{{emoji}} — hold nede for superreaktion",
  },
  acoes: {
    reagir: "Reagér",
    responder: "Svar",
    encaminhar: "Videresend",
    favoritar: "Gem beskeden",
    tirarDosFavoritos: "Fjern fra gemte",
    marcarNaoLida: "Markér som ulæst",
    copiarLink: "Kopiér linket til beskeden",
    copiarId: "Kopiér beskedens ID",
    fixar: "Fastgør beskeden",
    desafixar: "Frigør",
    editar: "Redigér",
    apagar: "Slet",
    mais: "Mere",
    adicionarReacao: "Tilføj reaktion",
    superReagirCom: "Superreagér med {{emoji}}",
    fixarMensagem: "Fastgør beskeden",
    desafixarMensagem: "Frigør beskeden",
    editarMensagem: "Redigér beskeden",
    apagarMensagem: "Slet beskeden",
  },
  mencao: {
    cargo: "Rolleomtale",
    pessoa: "Omtale",
    alguem: "nogen",
    cargoSemNome: "rolle",
    here: "Giver besked til dem, der er online",
    everyone: "Giver besked til hele serveren",
  },
  codigo: {
    copiar: "Kopiér",
    copiado: "Kopieret",
    copiarAria: "Kopiér koden",
    copiadoAria: "Koden er kopieret",
    recolher: "Skjul",
    expandir: "Udvid",
    verInteiro: "Se hele filen",
    maisOpcoes: "Flere muligheder",
    baixar: "Download",
    recolherLinhas: "Skjul ({{linhas}} linjer)",
    expandirLinhas: "Udvid ({{linhas}} linjer)",
    mudarIdioma: "Skift sprog",
    procurarIdioma: "Søg efter sprogkode…",
    nenhumIdioma: "Intet sprog fundet.",
    quebrarTexto: "Ombryd tekst",
  },
  caixa: {
    escrever: "Skriv i #{{canal}}",
    escreverSemCanal: "Skriv en besked",
    semPermissao: "Du har ikke tilladelse til at sende beskeder i denne kanal",
    solteParaAnexar: "Slip for at vedhæfte",
    longaTitulo: "Din besked er for lang…",
    longaDescricao: "Du har nået grænsen på {{limite}} tegn. Du kan sende den som fil.",
    enviarComoArquivo: "Send som fil",
    textoComoArquivo: "Send teksten som fil",
    arquivoGrandeTitulo: "Filen er for stor",
    arquivoGrandeDescricao: "”{{arquivo}}” overskrider grænsen på {{limite}} MB pr. fil.",
    respondendoPara: "Svar til",
    vaiNotificar: "Personen får en notifikation",
    naoVaiNotificar: "Personen får ingen notifikation",
    ligado: "til",
    desligado: "fra",
    pararDeResponder: "Stop med at svare",
    mais: "Mere",
    enviarArquivo: "Send en fil",
    criarEnquete: "Opret en afstemning",
    expressoes: "Emoji, GIF og klistermærker",
    enviar: "Send",
    aguardandoEnvio: "Venter på uploaden",
    modoLento: "Langsom tilstand aktiv ({{tempo}})",
    modoLentoDica: "Langsom tilstand er sat til {{segundos}} s. Vent, før du sender en ny besked.",
  },
  anexos: {
    enviando: "Uploader…",
    modificar: "Redigér {{arquivo}}",
    remover: "Fjern {{arquivo}}",
    ver: "Se {{arquivo}}",
    mostrarSpoiler: "Vis spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Redigér vedhæftningen",
    nomeDoArquivo: "Filnavn",
    descricao: "Beskrivelse af alternativ tekst",
    descricaoDica: "Beskriv dette medie for skærmlæsere",
    marcarSpoiler: "Markér som spoiler",
    cancelar: "Annullér",
    salvar: "Gem",
  },
  cartao: {
    tocador: "Afspiller",
    abrir: "Åbn {{destino}}",
    tocar: "Afspil {{titulo}}",
    video: "video",
    verImagem: "Se billedet",
  },
  enquete: {
    titulo: "Afstemning",
    encerrada: "Afstemningen er lukket",
    variasRespostas: "Afstemning — flere svar",
    umVoto: "{{quantidade}} stemme",
    votos: "{{quantidade}} stemmer",
    umVotoNoTotal: "{{quantidade}} stemme i alt",
    votosNoTotal: "{{quantidade}} stemmer i alt",
    encerraEm: "lukker {{quando}}",
    encerrarAgora: "Luk nu",
  },
  fixadas: {
    titulo: "Fastgjorte beskeder",
    vazio: "Denne kanal har ingen fastgjorte beskeder… endnu.",
    desafixar: "Frigør",
    anexo: "(vedhæftning)",
    enquete: "(afstemning)",
    dicaRotulo: "GODT AT VIDE:",
    dica: "den, der har tilladelsen “Administrér beskeder”, kan fastgøre direkte fra beskedmenuen.",
  },
  encaminhar: {
    titulo: "Videresend beskeden",
    paraOnde: "Hvorhen?",
    semTexto: "(besked uden tekst)",
    nenhumLugar: "Der er ingen steder med det navn.",
    canais: "Kanaler",
    conversas: "Direkte beskeder",
  },
  expressoes: {
    gifs: "Gif'er",
    buscarGifs: "Søg på Klipy",
    figurinha: "Klistermærke",
    buscarFigurinha: "Find det perfekte klistermærke",
    buscarEmoji: "Find den perfekte emoji",
    buscarReacao: "Find den perfekte reaktion",
    adicionarEmoji: "Tilføj emoji",
    limparBusca: "Ryd søgningen",
  },
  busca: {
    fechar: "Luk søgningen",
    procurando: "Søger…",
    resultado: "{{quantos}} resultat",
    resultados: "{{quantos}} resultater",
    nadaCom: "Ingenting med {{termo}} her.",
    soOsQuePodeLer: "Søgningen kigger kun i kanaler, du må læse.",
  },
  entrada: {
    titulo: "Indbakke",
    naoLidas: "Ulæste",
    salvas: "Gemte",
    mencoes: "Omtaler",
    fimTitulo: "Du er nået til enden",
    fimDetalhe: "Der er ikke mere at læse. Når der kommer en ny besked, dukker den op her.",
    semSalvosTitulo: "Ingenting gemt",
    semSalvosDetalhe: "Hold Skift nede, og klik på en beskeds bogmærke for at gemme den og læse den senere.",
    tirarDosSalvos: "Fjern fra gemte",
    semMencoesTitulo: "Ingen omtaler endnu",
    semMencoesDetalhe: "Omtaler af dig dukker op her for de sidste 7 dage.",
  },
  forum: {
    descricao: "Hvert emne bliver sin egen samtale — godt til spørgsmålet, der ikke må forsvinde midt i snakken.",
    novoAssunto: "Nyt emne",
    vazio: "Ingen emner endnu. Start det første, så bliver samtalen ordnet fra begyndelsen.",
    titulo: "Titel",
    doQueSeTrata: "Hvad handler det om?",
    primeiraMensagem: "Første besked",
    conteDoCaso: "Fortæl om det",
  },
};
