export const perfil = {
  carregando: "Indlæser…",
  editar: "Rediger profilen",
  mensagem: "Besked",
  abrirConversa: "Åbn samtalen",
  verCompleto: "Se hele profilen",
  convidarParaServidor: "Inviter til serveren",
  semServidores: "Du har ingen servere",
  conviteEnviado: "Invitation sendt til {{nome}}.",
  moderador: "Åbn i moderatorvisning",
  mais: "Mere",
  ignorar: "Ignorer",
  deixarDeIgnorar: "Stop med at ignorere",
  copiarId: "Kopiér bruger-ID",
  idCopiado: "ID kopieret.",
  conexoes: "Forbindelser",
  membroDesde: "Medlem siden",
  sobre: "Om",
  cargosTitulo: "Roller",
  visaoGeral: "Overblik",
  amigosEmComum: "Fælles venner ({{quantidade}})",
  servidoresEmComum: "Fælles servere ({{quantidade}})",
  amizade: {
    amigo: "Ven",
    pedidoEnviado: "Venneanmodning sendt",
    respondaAbaixo: "Sendte dig en anmodning — svar nedenfor",
    adicionar: "Tilføj ven",
    teMandouPedido: "Sendte dig en venneanmodning",
    aceitar: "Accepter",
    desfazer: "Fjern ven",
    desfazerTitulo: "Fjern {{nome}} fra dine venner?",
    desfazerDescricao: "I er ikke venner længere. Den private samtale bliver i historikken, og du kan tilføje personen igen senere.",
    bloquear: "Bloker",
    bloquearTitulo: "Bloker {{nome}}?",
    bloquearDescricao: "I er ikke venner længere, den private samtale tager ikke imod flere beskeder, og personen kan ikke sende dig en venneanmodning igen.",
    linkCopiado: "I er ikke venner — linket blev kopieret, så du kan sende det.",
  },
  recado: {
    escrever: "Skriv til @{{usuario}}",
    enviar: "Send",
    enviada: "Beskeden blev sendt",
    falhou: "Den kunne ikke sendes. Prøv fra samtalen.",
  },
  cartao: {
    trocarFaixa: "Skift kortets banner",
    trocarFaixaCurto: "Skift banner",
    trocarFoto: "Skift profilbillede",
    trocarFotoCurto: "Skift billede",
    suaEtiqueta: "Dit mærkat",
    editarEtiqueta: "Klik for at redigere dit mærkat",
    conteAlgo: "Fortæl noget om dig selv",
    adicionarStatus: "Tilføj en status",
    adicionarDescricao: "Klik for at tilføje en beskrivelse",
    cargo: "Rolle",
    cargos: "Roller",
    cargosCom: "Roller — {{quantidade}}",
    tirarCargo: "Fjern rollen {{cargo}}",
  },
  cargos: {
    adicionar: "Tilføj rolle",
    procurar: "Søg efter en rolle",
  },
  etiqueta: {
    escolher: "Vælg servermærkat",
    nenhuma: "Intet servermærkat",
    semEtiqueta: "Ingen af dine servere har et mærkat",
  },
  emblemas: {
    doServidor: "Emblemer fra denne server",
    limite: "Du kan bære op til {{quantidade}} emblemer.",
  },
  nota: {
    vazia: "Klik for at skrive en note",
    rotulo: "Note (kun du ser den)",
  },
  status: {
    titulo: "Status",
    definir: "Angiv din status",
    escolherEmoji: "Vælg emoji",
    tirarEmoji: "Fjern emojien",
    oQuePensa: "Hvad tænker du på?",
    limparAgora: "Ryd status nu",
    naoLimpar: "Ryd ikke",
    limpar30m: "Ryd om 30 minutter",
    limpar1h: "Ryd om 1 time",
    limpar4h: "Ryd om 4 timer",
    limparHoje: "Ryd i dag",
    limparAmanha: "Ryd i morgen",
    comHora: "{{prazo}} kl. {{hora}}",
  },
  presenca: {
    disponivel: "Tilgængelig",
    ausente: "Ikke til stede",
    naoPerturbar: "Forstyr ikke",
    naoPerturbarDetalhe: "Du får ingen besked om nye beskeder",
    invisivel: "Usynlig",
    invisivelDetalhe: "For andre ser du offline ud",
  },
  menu: {
    mudarDeConta: "Skift konto",
    gerenciarContas: "Administrer konti",
  },
  editor: {
    decoracao: "Skift avatardekorationen",
    naoSalvo: "Glem ikke at gemme dine ændringer!",
    principal: "Hovedprofil",
  },
};
