export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Serverindstillinger",
  auditoria: {
    todasAsAcoes: "Alle handlinger",
    todosOsUsuarios: "Alle brugere",
    filtroMembros: "Medlemmer",
    filtroCanais: "Kanaler",
    filtroEmojis: "Emojis",
    filtroServidor: "Server",
    titulo: "Handlingslog",
    porUsuario: "Filtrér på person",
    porAcao: "Filtrér på handling",
    vazio: "Der er ikke logget noget endnu med dette filter.",
    motivo: "Årsag:",
  },
  banimentos: {
    titulo: "Serverens bandlysningsliste",
    descricao: "Den, der står her, kommer ikke ind igen — heller ikke med en ny invitation. At ophæve bandlysningen giver adgangen tilbage med det samme.",
    procurar: "Søg bandlysninger på brugernavn",
    vazioTitulo: "Ingen bandlysninger",
    vazio: "Du har ikke bandlyst nogen endnu … men hvis og når det bliver nødvendigt, så tøv ikke.",
    desbanir: "Ophæv bandlysning",
  },
  excluir: {
    tudoVai: "Alle kanaler, beskeder og invitationer i {{servidor}} bliver slettet for de {{membros}} medlemmer. Bagefter kan ingen hente dem tilbage.",
    digite: "Skriv {{servidor}} for at bekræfte",
    titulo: "Slet server",
    aviso: "Det her kan ikke fortrydes.",
  },
  emblemas: {
    apagarDescricao: "Det ryger af alle, der bærer det. Det kan ikke fortrydes.",
    titulo: "Mærker",
    vazio: "Ingen mærker endnu.",
    novo: "Nyt mærke",
  },
  convites: {
    revogarTitulo: "Tilbagekald invitationen?",
    revogarAcao: "Tilbagekald",
    revogarDescricao: "Linket {{codigo}} holder op med at virke med det samme. Den, der allerede kom ind via det, bliver på serveren.",
    titulo: "Invitationer",
    descricao: "Alle aktive invitationslinks til denne server.",
    vazio: "Der er ikke oprettet nogen invitation endnu.",
    revogar: "Tilbagekald invitation",
  },
  integracoes: {
    opcionais: "username og avatar_url er valgfrie og gælder pr. besked. Grænsen er 5 beskeder hvert 5. sekund.",
    apagarDescricao: "URL'en holder op med at virke med det samme. De beskeder, den allerede sendte, bliver i kanalen.",
    titulo: "Integrationer",
    descricao: "En webhook er en adresse, der poster i en kanal uden at skulle have en konto. God til at melde, at et build gik igennem, at nogen har åbnet en sag, eller hvad du ellers vil sende fra et script.",
    novo: "Ny webhook",
    vazio: "Ingen webhooks endnu. Opret en, og indsæt URL'en der, hvor beskeden skal komme fra.",
    canal: "Kanal",
    apagar: "Slet webhook",
    comoUsar: "Sådan bruger du det",
    comoUsarTexto: "Send en POST med JSON:",
  },
  explorar: {
    titulo: "Udforsk",
  },
  engajamento: {
    semCanal: "Ingen systemkanal",
    titulo: "Engagement",
    descricao: "Hvad serveren gør af sig selv, så den ikke virker tom, når der kommer en ny.",
    sistema: "Systembeskeder",
    boasVindas: "Send en velkomstbesked, når nogen kommer ind",
    sorteio: "Uden din egen tekst nedenunder trækkes sætningen tilfældigt — den samme hver gang bliver hurtigt træls.",
    canalDoSistema: "Kanal til systembeskeder",
    mensagem: "Velkomstbesked",
    deixeVazio: "Lad stå tom for at trække blandt de færdige sætninger",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtre der modererer af sig selv, før beskeden overhovedet findes. Den, der administrerer serveren, bliver aldrig filtreret — og fritagne roller går lige igennem.",
    palavras: {
      titulo: "Bloker egne ord",
      descricao: "Din liste over ord, ingen må skrive.",
    },
    mencoes: {
      titulo: "Bloker omtale-spam",
      descricao: "Blokerer en besked med for mange omtaler på én gang.",
    },
    links: {
      titulo: "Bloker links",
      descricao: "Holder enhver adresse tilbage, der bliver indsat i chatten.",
    },
    definir: "Sæt op",
    nomeDaRegra: "Navn på reglen",
    bloqueadas: "Blokerede ord",
    digiteEnter: "Skriv og tryk Enter",
    comparacao: "Sammenligningen ser bort fra store bogstaver, accenter og tegnsætning — og tager ikke et ord inde i et andet.",
    aPartirDe: "Bloker fra hvor mange omtaler",
    oQueFazer: "Hvad der skal ske",
    canalDoAlerta: "Kanal til advarslen",
    escolhaCanal: "Vælg en kanal",
    castigo: "Udelukkelse (minutter)",
    isentos: "Fritagne roller",
    semCargos: "Der er ikke oprettet nogen roller endnu.",
    salvarRegra: "Gem regel",
    apagar: "Slet regel",
    excluirTitulo: "Slet denne AutoMod-regel?",
    excluirDescricao: "Serveren holder straks op med at filtrere efter den. Du kan oprette den igen, men den nuværende opsætning går tabt.",
    excluirAcao: "Slet regel",
  },
  cargos: {
    titulo: "Roller",
    descricao: "Roller giver navn, farve og magt. Den, der står højere på listen, bestemmer over dem nedenunder — og ingen rører en rolle, der er lig med eller højere end ens egen.",
    criar: "Opret rolle",
    vazio: "Ingen roller endnu.",
    abaExibicao: "Udseende",
    abaPermissoes: "Rettigheder",
    abaMembros: "Medlemmer — {{quantos}}",
    everyone: "Gælder alle på serveren. Det er grundlaget, de andre roller lægges oven på.",
    nomeDoCargo: "Navn på rollen",
    cor: "Farve på rollen",
    corDica: "Farver navnet på den, der har rollen, i medlemslisten og i chatten.",
    semCor: "Uden farve",
    corPersonalizada: "Egen farve",
    estilo: "Stil på navnet",
    segundaCor: "Anden farve",
    segundaCorDica: "Uden den falder overgangen tilbage til én farve — den forsvinder ikke.",
    limparSegundaCor: "Ryd anden farve",
    icone: "Ikon",
    iconeDica: "Vises ved siden af rollen på profilkortet hos den, der har den.",
    exibirSeparado: "Vis adskilt fra de andre medlemmer",
    exibirSeparadoDica: "Rollen får sin egen sektion i medlemslisten.",
    permitirMencionar: "Tillad at nævne denne rolle",
    permitirMencionarDica: "Alle vil kunne give besked til alle, der har rollen.",
    semPoderDeConceder: "{{descricao}} (du har ikke denne rettighed til at give den videre)",
    adicionar: "Føj nogen til denne rolle",
    tirar: "Tag rollen",
    semNinguem: "Ingen har denne rolle endnu.",
    apagar: "Slet rolle",
    excluirTitulo: "Slet rollen “{{nome}}”?",
    excluirDescricao: "Den, der har rollen, mister alt, den gav. Det kan ikke fortrydes.",
    excluirAcao: "Slet rolle",
  },
  membros: {
    procurar: "Søg på navn eller brugernavn",
    membroDesde: "Medlem siden",
    vazio: "Ingen fundet.",
    acoesPara: "Handlinger for {{nome}}",
    deCastigo: "udelukkelse",
    tirarCastigo: "Ophæv udelukkelsen",
    castigo5min: "5 minutter",
    castigo1h: "1 time",
    castigo1d: "1 dag",
    castigo1s: "1 uge",
    expulsar: "Smid ud",
    expulsarTitulo: "Smide {{nome}} ud?",
    expulsarDescricao: "forlader {{servidor}} med det samme. Kan komme tilbage med en invitation — at smide ud forhindrer ikke returen.",
    banir: "Bandlys",
    banirTitulo: "Bandlyse {{nome}}?",
    banirDescricao: "forlader {{servidor}} og kan ikke komme tilbage, heller ikke med en invitation, før bandlysningen ophæves.",
    motivo: "Årsag (valgfrit)",
    motivoDica: "Bliver stående i handlingsloggen",
  },
  perfil: {
    titulo: "Serverprofil",
    descricao: "Sådan vises din server i listen og i invitationslinks.",
    icone: "Ikon",
    faixa: "Banner øverst",
    nomeDoServidor: "Navn på serveren",
    campoDescricao: "Beskrivelse",
    doQueE: "Hvad handler denne server om?",
    comprimido: "Komprimeret før upload: {{economia}}",
  },
  etiqueta: {
    titulo: "Servertag",
    descricao: "En etiket på op til 4 bogstaver, der vises ved siden af navnet på hvert medlem — i chatten og i personlisten. Her er det gratis: uden boosts, uden niveauer.",
    escolhaNome: "Vælg et navn",
    limite: "Højst 4 tegn, bogstaver og tal.",
    escolhaInsignia: "Vælg et mærke",
    voce: "Dig",
    fala1: "er der nogen, der vil spille?",
    fala2: "tjek lige mit tag!",
    fala3: "hold da op, hvor har du fået det fra",
  },
  expressoes: {
    comoUsar: "Tilføj op til {{limite}} emojis, alle kan bruge på denne server. Skriv :navn: i chatten for at sende en.",
    imagem: "Billede",
    enviadoPor: "Uploadet af",
    semEmoji: "Ingen emojis endnu.",
    figurinhas: "Klistermærker",
    enviarFigurinha: "Upload klistermærke",
    nomeDaFigurinha: "Navn på klistermærket",
    exemploFigurinha: "F.eks.: killingekram",
    figurinhaGrande: "Klistermærket er større end {{limite}}.",
    deixaPraLa: "Glem det",
    sons: "Lydpanel",
    enviarSom: "Upload lyd",
    nomeDoSom: "Navn på lyden",
    semSom: "Ingen lyde endnu.",
    somGrande: "Lyden er større end {{limite}}.",
    emojiRelacionado: "Tilhørende emoji",
    ouvir: "Lyt",
    ouvirAssim: "Lyt sådan her",
    volumeDe: "Lydstyrke for {{nome}}",
    volumeDica: "Gælder alle på serveren. Hver enkelt kan stadig skrue ned for lydene kun for sig selv, i opkaldspanelet.",
    falhaEnvio: "Filen kunne ikke uploades.",
    excluirTitulo: "Slet {{tipo}} “{{nome}}”?",
    excluirDescricao: "Den forsvinder fra serveren for alle. Beskeder, der allerede brugte den, bliver stående, som de er.",
  },
  canal: {
    visaoGeral: "Overblik",
    nome: "Navn på kanalen",
    topico: "Emne for kanalen",
    topicoDica: "Hvad taler man om her?",
    modoLento: "Hver person sender kun én besked pr. interval. Den, der håndterer beskeder eller kanaler, går lige igennem.",
    visibilidade: "Indholdets synlighed",
    padrao: "Standard",
    padraoDica: "Kanalens indhold er altid synligt.",
    spoiler: "Spoilerkanal",
    spoilerDica: "Markér denne kanal som spoilerkanal, så drejninger og tunge emner forbliver skjult, indtil nogen vælger at se.",
    idade: "Aldersbegrænset kanal",
    idadeDica: "Den, der går ind, skal bekræfte at være myndig for at se indholdet.",
    bitrateDica: "Over 64 kbps kan genere dem med dårlig forbindelse.",
    qualidadeDeVideo: "Videokvalitet",
    automatica: "Automatisk",
    limite: "Brugergrænse — {{valor}}",
    pessoas: "{{quantos}} personer",
    semLimite: "uden grænse",
    permissoesDescricao: "Her ændrer du, hvad der gælder i denne kanal. Det, der bliver stående på “nedarv”, følger stadig rollen.",
    excluir: {
      titulo: "Slet kanal",
      historico: "Hele historikken for {{canal}} følger med, for alle.",
      digite: "Skriv {{canal}} for at bekræfte",
    },
  },
  moderacao: {
    titulo: "Moderatorvisning",
    semPermissao: "Du skal have rettigheden “Modererer medlemmer” for at se det her.",
    fecharEsc: "Luk (Esc)",
    atividade: "Aktivitet på serveren",
    mensagens: "Beskeder",
    links: "Links",
    midia: "Medier",
    acoesNaAuditoria: "Handlinger i handlingsloggen",
    moderacoesSofridas: "Modtaget moderering",
    permissoes: "Rettigheder ({{quantas}})",
    semPermissaoEspecial: "Ingen særlige rettigheder.",
    conta: "Konto",
    entrouNoServidor: "Kom med i serveren",
    contaCriadaEm: "Konto oprettet",
    deCastigoAte: "Udelukket indtil",
    formaDeAdesao: "Hvordan vedkommende kom ind",
    mensagem: "Besked",
    castigo: "Udelukkelse",
    copiarId: "Kopiér ID",
    idCopiado: "ID kopieret.",
    adicionarCargo: "Tilføj rolle",
    semCargos: "Ingen rolle oprettet",
    soEveryone: "Kun @everyone.",
    voltar: "Tilbage",
    vazio: "Ingenting her.",
    cinquenta: "Viser de 50 nyeste.",
    irParaMensagem: "Gå til beskeden",
    precisaSerAmigo: "I skal være venner for at snakke.",
    expulsarDescricao: "Forlader serveren med det samme, men kan komme tilbage med en invitation.",
    banirDescricao: "Forlader serveren og kan ikke komme tilbage, heller ikke med en invitation, før bandlysningen ophæves.",
    castigarTitulo: "Udeluk {{nome}} midlertidigt?",
    castigoDescricao: "Så længe det varer, skriver eller taler vedkommende ikke i nogen kanal på serveren.",
    aplicarCastigo: "Anvend udelukkelsen",
    duracao: "Varighed i minutter",
    informeDuracao: "Angiv varigheden i minutter.",
  },
  abas: {
    expressoes: "Udtryk",
    pessoas: "Folk",
    apps: "Apps",
    moderacao: "Moderation",
    banimentos: "Bandlysninger",
  },
};
