export const servidor = {
  comunidade: {
    ativa: "Fællesskabet er åbent",
    ativaDesde: "Åbent siden {{quando}}",
    membrosAgora: "{{quantos}} medlemmer",
    criarParaMim: "Lav en til mig",
    canalDeRegras: "Regelkanal",
    canalDeRegrasDetalhe: "Stedet med reglerne, som alle læser, før de skriver.",
    canalDeAvisos: "Kanal til beskeder til fællesskabet",
    canalDeAvisosDetalhe: "Herhen sender vi det, der ændrer sig — kun til dem, der styrer.",
    canalDeSeguranca: "Kanal til sikkerhedsvarsler",
    canalDeSegurancaDetalhe: "Her får moderationen det, filtrene har fanget.",
    idiomaPrincipal: "Hovedsprog",
    idiomaPrincipalDetalhe: "Det sprog, det meste af snakken foregår på.",
    semIdioma: "Intet sprog valgt",
    semCanal: "Ingen kanal",
    finalTitulo: "Næsten der",
    finalDetalhe: "Se, hvad der ændrer sig for dem, der kommer, før du åbner.",
    confereRegras: "Den, der kommer ind, ser regelkanalen først af alt.",
    confereEveryone: "Kun folk med en rolle bruger @everyone og @here.",
    confereMencoes: "At nævne alle på én gang kræver nu tilladelse.",
    concordo: "Jeg er enig og forstår",
    concordoDetalhe: "Du bekræfter, at fællesskabet følger husets retningslinjer.",
    proximo: "Videre",
    terminar: "Afslut opsætningen",
    visaoGeral: "Overblik",
    visaoGeralDetalhe: "De kanaler, fællesskabet taler til nye med.",
    seguranca: "Sikkerhed",
    segurancaDetalhe: "De bremser, der holder spam og hårdt indhold tilbage.",
    habilitada: "Fællesskabet er slået til.",
    falhou: "Fællesskabet kunne ikke slås til.",
    titulo: "Fællesskab",
    ilustracao: "Talebobler",
    convite: "Er du ved at bygge et fællesskab?",
    conviteDetalhe: "Gør det til et fællesskab og få værktøjerne til et stort sted: regelkanal, beskeder fra huset og filtre, der modererer af sig selv.",
    contagem: "{{membros}} af {{minimo}} medlemmer",
    faltam: "Der mangler {{quantos}}, før det kan åbne.",
    prontoParaAbrir: "Det kan åbne nu.",
    habilitar: "Slå fællesskab til",
    vantagemCrescer: "Vokse",
    vantagemCrescerDetalhe: "Fællesskabet kan søge om at komme i Udforsk, så folk finder jer på emnet.",
    vantagemModerar: "Moderere",
    vantagemModerarDetalhe: "Kræv bekræftet e-mail, filtrér medier og slå AutoMod til på én gang.",
    vantagemAvisos: "Følge med",
    vantagemAvisosDetalhe: "Huset sender det, der ændrer sig, til jer der styrer — i jeres egen kanal.",
    assistenteTitulo: "Lad os sætte dit fællesskab op.",
    passoSeguranca: "Sikkerhedstjek",
    passoBasico: "Grundlæggende opsætning",
    passoFinal: "Sidste finish",
    seguraTitulo: "Hold fællesskabet trygt",
    seguraDetalhe: "Store fællesskaber tiltrækker spam. De to bremser er slået til fra start, og du kan slukke dem senere.",
    emailVerificado: "Kræv bekræftet e-mail",
    emailVerificadoDetalhe: "Den, der ikke har bekræftet sin e-mail, skriver ikke. Folk med en rolle går fri.",
    filtroDeMidia: "Filtrér eksplicitte medier",
    filtroDeMidiaDetalhe: "Billeder og videoer kommer ind skjult og vises først, når nogen vælger at se dem.",
    basicoTitulo: "Klargør det basale",
    basicoDetalhe: "Sig, hvilken kanal reglerne står i, og hvor husets beskeder skal hen. Uden valgt kanal laver jeg dem begge.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} kommandoer",
    previa: "Sådan ser kortet ud",
    trocarIcone: "Skift ikonet",
    tirarCapa: "Fjern forsiden",
    heroComunidades: "Der er folk der snakker om det du kan lide",
    heroComunidadesDetalhe: "Fællesskaber åbnet af folk der bruger stedet. Gå ind, læs snakken, og bliv hvis du kan lide det.",
    emDestaque: "Fremhævede",
    todasAsComunidades: "De andre",
    heroTitulo: "Hvad skal flokken bruge i dag?",
    heroDetalhe: "Bots til musik, spil og moderation, lavet af folk der også er her. Vælg en, og den træder ind på serveren.",
    novidades: "Lige ankommet",
    todosOsApps: "De andre",
    lojaTitulo: "Appens side",
    lojaDetalhe: "Det er dette, folk ser i Udforsk, når de ikke kender den endnu.",
    capa: "Forside",
    capaDetalhe: "Det brede billede øverst på siden. 1280 × 720 klæder den.",
    trocarCapa: "Skift forside",
    categorias: "Kategorier",
    categoriasDetalhe: "Op til {{quantas}}. Det er dem, man bladrer efter i Udforsk.",
    idiomas: "Sprog",
    idiomasDetalhe: "Op til {{quantos}}. Hvilke sprog appen svarer på.",
    termos: "Vilkår for brug",
    politica: "Privatlivspolitik",
    politicas: "Politikker",
    servidorDeSuporte: "Supportserver",
    servidorDeSuporteDetalhe: "Hvor man havner, hvis man har brug for hjælp med appen.",
    semServidor: "Ingen",
    emQuantosServidores: "På hvor mange servere",
    categoria: {
      GAMES: "Spil",
      MUSICA: "Musik",
      MODERACAO: "Moderation",
      PRODUTIVIDADE: "Produktivitet",
      SOCIAL: "Socialt",
      UTILIDADES: "Værktøjer",
      ARTE_E_CRIACAO: "Kunst og kreativitet",
      EDUCACAO: "Læring",
      OUTRA: "Andet",
    },
    appIndisponivel: "Appen er ikke tilgængelig",
    voltarParaExplorar: "Tilbage til Udforsk",
    adicionarApp: "Tilføj app",
    copiarLink: "Kopiér linket",
    denunciarApp: "Anmeld appen",
    copiarIdDoApp: "Kopiér appens id",
    visaoGeral: "Overblik",
    comandos: "Kommandoer",
    permissoes: "Tilladelser",
    semPermissoes: "Denne app beder ikke om nogen tilladelser.",
    avisoDePermissoes: "Den kommer ind med sin egen rolle. Du kan ændre tilladelserne bagefter i Fællesskabsindstillinger → Roller.",
    servidoresEmComum: "Fælles fællesskaber",
    umServidorEmComum: "1 fællesskab",
    quantosServidoresEmComum: "{{quantos}} fællesskaber",
    feitoPor: "Lavet af",
    publicadoEm: "Udgivet den",
    denunciarNome: "Anmeld {{nome}}",
    denunciaDetalhe: "Anmeldelsen går til Gravaês team. Den, der lavede appen, får ikke at vide, at det var dig.",
    denunciaFalhou: "Anmeldelsen kunne ikke sendes.",
    umMembro: "1 medlem",
    semDescricao: "Ingen beskrivelse.",
    adicionar: "Tilføj",
    jaEstaAqui: "Du er her allerede",
    entrando: "Går ind…",
    entrar: "Gå ind",
    comunidadePublica: "Offentligt fællesskab",
    online: "{{quantos}} online",
    membros: "{{quantos}} medlemmer",
    abrirComunidade: "Åbn fællesskabet",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Serverindstillinger",
  novasMensagens: "Nye beskeder",
  menu: {
    silenciar: "Slå fællesskab fra",
    reativar: "Slå fællesskab til",
    porQuinze: "I 15 minutter",
    porMeiaHora: "I 30 minutter",
    porTresHoras: "I 3 timer",
    porTresDias: "I 3 dage",
    porUmaHora: "I 1 time",
    porOitoHoras: "I 8 timer",
    porUmDia: "I 24 timer",
    ateReativar: "Indtil jeg slår det til igen",
    notificacoes: "Notifikationsindstillinger",
    padrao: "Brug standard",
    todas: "Alle beskeder",
    soMencoes: "Kun omtaler",
    nada: "Intet",
    ocultarSilenciados: "Skjul lydløse kanaler",
    denunciar: "Anmeld fællesskab",
    marcarLida: "Markér som læst",
    convidar: "Inviter medlemmer",
    editarPerfil: "Rediger fællesskabets profil",
    configuracoes: "Fællesskabets indstillinger",
    sair: "Forlad fællesskabet",
    sairTitulo: "Forlad {{nome}}?",
    sairDescricao: "Du skal bruge en ny invitation for at komme tilbage.",
    copiarId: "Kopiér fællesskabets ID",
    idCopiado: "ID kopieret.",
  },
  convite: {
    cartaoTitulo: "Du er inviteret til et fællesskab",
    indisponivel: "Invitationen er ikke tilgængelig",
    indisponivelDetalhe: "Den er udløbet, brugt op, eller den, der lavede den, har slettet den.",
    entrar: "Gå ind i fællesskabet",
    chamado: "Du er inviteret til",
    aceitarComo: "Acceptér som {{nome}}",
    abrir: "Åbn fællesskabet",
    recusar: "Nej tak",
  },
  pasta: {
    silenciarTodas: "Slå fællesskaber fra",
    reativarTodas: "Slå fællesskaber til",
    mostrarSilenciados: "Vis lydløse kanaler",
    notificacoesDaComunidade: "Notifikationsindstillinger",
    silenciarEveryone: "Slå @everyone og @here fra",
    permitirEveryone: "Tillad @everyone og @here",
    silenciarCargos: "Slå rolleomtaler fra",
    permitirCargos: "Tillad rolleomtaler",
    dicaDaCor: "Skriv en farve (hex, rgb(), hsl() eller navn), eller brug vælgeren.",
    mostrarIcone: "Vis ikon når lukket",
    dicaDoIcone: "Lukket viser den ikonet i stedet for serverne.",
    icone: "Mappeikon",
    excluir: "Slet mappe",
    icones: {
      pasta: "Mappe",
      estrela: "Favorit",
      coracao: "Hjerte",
      salvar: "Gem",
      jogo: "Controller",
      escudo: "Skjold",
      nota: "Node",
    },
    marcarLida: "Markér mappe som læst",
    configuracoes: "Mappeindstillinger",
    desfazer: "Opløs mappe",
    titulo: "Mappe",
    nome: "Navn",
    semNome: "Uden navn",
    cor: "Farve",
    semCor: "Ingen farve",
    salvar: "Gem",
  },
  denuncia: {
    titulo: "Anmeld {{nome}}",
    descricao: "Anmeldelsen går til Gravaê-teamet. Fortæl hvad der skete.",
    motivo: "Årsag",
    detalhes: "Detaljer (valgfrit)",
    enviar: "Send anmeldelse",
    enviada: "Anmeldelse sendt. Tak.",
    motivos: {
      spam: "Spam eller reklame",
      assedio: "Chikane eller had",
      conteudo: "Upassende indhold",
      golpe: "Svindel",
      outro: "Andet",
    },
  },
  selos: {
    verificada: "Verificeret fællesskab",
    detectavel: "Synligt fællesskab",
  },
  auditoria: {
    todasAsAcoes: "Alle handlinger",
    todosOsUsuarios: "Alle brugere",
    filtroMembros: "Medlemmer",
    filtroCanais: "Kanaler",
    filtroEmojis: "Emojis",
    filtroServidor: "Server",
    titulo: "Handlingslog",
    porUsuario: "Filtrér på person",
    porAcao: "Filtrér på handling",
    vazio: "Der er ikke logget noget endnu med dette filter.",
    motivo: "Årsag:",
  },
  banimentos: {
    titulo: "Serverens bandlysningsliste",
    descricao: "Den, der står her, kommer ikke ind igen — heller ikke med en ny invitation. At ophæve bandlysningen giver adgangen tilbage med det samme.",
    procurar: "Søg bandlysninger på brugernavn",
    vazioTitulo: "Ingen bandlysninger",
    vazio: "Du har ikke bandlyst nogen endnu … men hvis og når det bliver nødvendigt, så tøv ikke.",
    desbanir: "Ophæv bandlysning",
  },
  excluir: {
    tudoVai: "Alle kanaler, beskeder og invitationer i {{servidor}} bliver slettet for de {{membros}} medlemmer. Bagefter kan ingen hente dem tilbage.",
    digite: "Skriv {{servidor}} for at bekræfte",
    titulo: "Slet server",
    aviso: "Det her kan ikke fortrydes.",
  },
  emblemas: {
    apagarDescricao: "Det ryger af alle, der bærer det. Det kan ikke fortrydes.",
    titulo: "Mærker",
    vazio: "Ingen mærker endnu.",
    novo: "Nyt mærke",
  },
  convites: {
    revogarTitulo: "Tilbagekald invitationen?",
    revogarAcao: "Tilbagekald",
    revogarDescricao: "Linket {{codigo}} holder op med at virke med det samme. Den, der allerede kom ind via det, bliver på serveren.",
    titulo: "Invitationer",
    descricao: "Alle aktive invitationslinks til denne server.",
    vazio: "Der er ikke oprettet nogen invitation endnu.",
    revogar: "Tilbagekald invitation",
  },
  integracoes: {
    opcionais: "username og avatar_url er valgfrie og gælder pr. besked. Grænsen er 5 beskeder hvert 5. sekund.",
    apagarDescricao: "URL'en holder op med at virke med det samme. De beskeder, den allerede sendte, bliver i kanalen.",
    titulo: "Integrationer",
    descricao: "En webhook er en adresse, der poster i en kanal uden at skulle have en konto. God til at melde, at et build gik igennem, at nogen har åbnet en sag, eller hvad du ellers vil sende fra et script.",
    novo: "Ny webhook",
    vazio: "Ingen webhooks endnu. Opret en, og indsæt URL'en der, hvor beskeden skal komme fra.",
    canal: "Kanal",
    apagar: "Slet webhook",
    comoUsar: "Sådan bruger du det",
    comoUsarTexto: "Send en POST med JSON:",
  },
  explorar: {
    titulo: "Udforsk",
  },
  engajamento: {
    semCanal: "Ingen systemkanal",
    titulo: "Engagement",
    descricao: "Hvad serveren gør af sig selv, så den ikke virker tom, når der kommer en ny.",
    sistema: "Systembeskeder",
    boasVindas: "Send en velkomstbesked, når nogen kommer ind",
    sorteio: "Uden din egen tekst nedenunder trækkes sætningen tilfældigt — den samme hver gang bliver hurtigt træls.",
    canalDoSistema: "Kanal til systembeskeder",
    mensagem: "Velkomstbesked",
    deixeVazio: "Lad stå tom for at trække blandt de færdige sætninger",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtre der modererer af sig selv, før beskeden overhovedet findes. Den, der administrerer serveren, bliver aldrig filtreret — og fritagne roller går lige igennem.",
    palavras: {
      titulo: "Bloker egne ord",
      descricao: "Din liste over ord, ingen må skrive.",
    },
    mencoes: {
      titulo: "Bloker omtale-spam",
      descricao: "Blokerer en besked med for mange omtaler på én gang.",
    },
    links: {
      titulo: "Bloker links",
      descricao: "Holder enhver adresse tilbage, der bliver indsat i chatten.",
    },
    definir: "Sæt op",
    nomeDaRegra: "Navn på reglen",
    bloqueadas: "Blokerede ord",
    digiteEnter: "Skriv og tryk Enter",
    comparacao: "Sammenligningen ser bort fra store bogstaver, accenter og tegnsætning — og tager ikke et ord inde i et andet.",
    aPartirDe: "Bloker fra hvor mange omtaler",
    oQueFazer: "Hvad der skal ske",
    canalDoAlerta: "Kanal til advarslen",
    escolhaCanal: "Vælg en kanal",
    castigo: "Udelukkelse (minutter)",
    isentos: "Fritagne roller",
    semCargos: "Der er ikke oprettet nogen roller endnu.",
    salvarRegra: "Gem regel",
    apagar: "Slet regel",
    excluirTitulo: "Slet denne AutoMod-regel?",
    excluirDescricao: "Serveren holder straks op med at filtrere efter den. Du kan oprette den igen, men den nuværende opsætning går tabt.",
    excluirAcao: "Slet regel",
  },
  cargos: {
    titulo: "Roller",
    descricao: "Roller giver navn, farve og magt. Den, der står højere på listen, bestemmer over dem nedenunder — og ingen rører en rolle, der er lig med eller højere end ens egen.",
    criar: "Opret rolle",
    vazio: "Ingen roller endnu.",
    abaExibicao: "Udseende",
    abaPermissoes: "Rettigheder",
    abaMembros: "Medlemmer — {{quantos}}",
    everyone: "Gælder alle på serveren. Det er grundlaget, de andre roller lægges oven på.",
    nomeDoCargo: "Navn på rollen",
    cor: "Farve på rollen",
    corDica: "Farver navnet på den, der har rollen, i medlemslisten og i chatten.",
    semCor: "Uden farve",
    corPersonalizada: "Egen farve",
    estilo: "Stil på navnet",
    segundaCor: "Anden farve",
    segundaCorDica: "Uden den falder overgangen tilbage til én farve — den forsvinder ikke.",
    limparSegundaCor: "Ryd anden farve",
    icone: "Ikon",
    iconeDica: "Vises ved siden af rollen på profilkortet hos den, der har den.",
    exibirSeparado: "Vis adskilt fra de andre medlemmer",
    exibirSeparadoDica: "Rollen får sin egen sektion i medlemslisten.",
    permitirMencionar: "Tillad at nævne denne rolle",
    permitirMencionarDica: "Alle vil kunne give besked til alle, der har rollen.",
    semPoderDeConceder: "{{descricao}} (du har ikke denne rettighed til at give den videre)",
    adicionar: "Føj nogen til denne rolle",
    tirar: "Tag rollen",
    semNinguem: "Ingen har denne rolle endnu.",
    apagar: "Slet rolle",
    excluirTitulo: "Slet rollen “{{nome}}”?",
    excluirDescricao: "Den, der har rollen, mister alt, den gav. Det kan ikke fortrydes.",
    excluirAcao: "Slet rolle",
  },
  membros: {
    procurar: "Søg på navn eller brugernavn",
    membroDesde: "Medlem siden",
    vazio: "Ingen fundet.",
    acoesPara: "Handlinger for {{nome}}",
    deCastigo: "udelukkelse",
    tirarCastigo: "Ophæv udelukkelsen",
    castigo5min: "5 minutter",
    castigo1h: "1 time",
    castigo1d: "1 dag",
    castigo1s: "1 uge",
    expulsar: "Smid ud",
    expulsarTitulo: "Smide {{nome}} ud?",
    expulsarDescricao: "forlader {{servidor}} med det samme. Kan komme tilbage med en invitation — at smide ud forhindrer ikke returen.",
    banir: "Bandlys",
    banirTitulo: "Bandlyse {{nome}}?",
    banirDescricao: "forlader {{servidor}} og kan ikke komme tilbage, heller ikke med en invitation, før bandlysningen ophæves.",
    motivo: "Årsag (valgfrit)",
    motivoDica: "Bliver stående i handlingsloggen",
  },
  perfil: {
    titulo: "Serverprofil",
    descricao: "Sådan vises din server i listen og i invitationslinks.",
    icone: "Ikon",
    faixa: "Banner øverst",
    nomeDoServidor: "Navn på serveren",
    campoDescricao: "Beskrivelse",
    doQueE: "Hvad handler denne server om?",
    comprimido: "Komprimeret før upload: {{economia}}",
  },
  etiqueta: {
    titulo: "Servertag",
    descricao: "En etiket på op til 4 bogstaver, der vises ved siden af navnet på hvert medlem — i chatten og i personlisten. Her er det gratis: uden boosts, uden niveauer.",
    escolhaNome: "Vælg et navn",
    limite: "Højst 4 tegn, bogstaver og tal.",
    escolhaInsignia: "Vælg et mærke",
    voce: "Dig",
    fala1: "er der nogen, der vil spille?",
    fala2: "tjek lige mit tag!",
    fala3: "hold da op, hvor har du fået det fra",
  },
  expressoes: {
    comoUsar: "Tilføj op til {{limite}} emojis, alle kan bruge på denne server. Skriv :navn: i chatten for at sende en.",
    imagem: "Billede",
    enviadoPor: "Uploadet af",
    semEmoji: "Ingen emojis endnu.",
    figurinhas: "Klistermærker",
    enviarFigurinha: "Upload klistermærke",
    nomeDaFigurinha: "Navn på klistermærket",
    exemploFigurinha: "F.eks.: killingekram",
    figurinhaGrande: "Klistermærket er større end {{limite}}.",
    deixaPraLa: "Glem det",
    sons: "Lydpanel",
    enviarSom: "Upload lyd",
    nomeDoSom: "Navn på lyden",
    semSom: "Ingen lyde endnu.",
    somGrande: "Lyden er større end {{limite}}.",
    emojiRelacionado: "Tilhørende emoji",
    ouvir: "Lyt",
    ouvirAssim: "Lyt sådan her",
    volumeDe: "Lydstyrke for {{nome}}",
    volumeDica: "Gælder alle på serveren. Hver enkelt kan stadig skrue ned for lydene kun for sig selv, i opkaldspanelet.",
    falhaEnvio: "Filen kunne ikke uploades.",
    excluirTitulo: "Slet {{tipo}} “{{nome}}”?",
    excluirDescricao: "Den forsvinder fra serveren for alle. Beskeder, der allerede brugte den, bliver stående, som de er.",
  },
  canal: {
    tipoLink: "Link",
    tipoLinkDica: "Peger på en adresse udenfor og åbner i browseren",
    endereco: "Adresse",
    enderecoDica: "Hvor kanalen fører hen. Den skal starte med https://",
    visaoGeral: "Overblik",
    nome: "Navn på kanalen",
    topico: "Emne for kanalen",
    topicoDica: "Hvad taler man om her?",
    modoLento: "Hver person sender kun én besked pr. interval. Den, der håndterer beskeder eller kanaler, går lige igennem.",
    visibilidade: "Indholdets synlighed",
    padrao: "Standard",
    padraoDica: "Kanalens indhold er altid synligt.",
    spoiler: "Spoilerkanal",
    spoilerDica: "Markér denne kanal som spoilerkanal, så drejninger og tunge emner forbliver skjult, indtil nogen vælger at se.",
    idade: "Aldersbegrænset kanal",
    idadeDica: "Den, der går ind, skal bekræfte at være myndig for at se indholdet.",
    bitrateDica: "Over 64 kbps kan genere dem med dårlig forbindelse.",
    qualidadeDeVideo: "Videokvalitet",
    automatica: "Automatisk",
    limite: "Brugergrænse — {{valor}}",
    pessoas: "{{quantos}} personer",
    semLimite: "uden grænse",
    permissoesDescricao: "Her ændrer du, hvad der gælder i denne kanal. Det, der bliver stående på “nedarv”, følger stadig rollen.",
    excluir: {
      titulo: "Slet kanal",
      historico: "Hele historikken for {{canal}} følger med, for alle.",
      digite: "Skriv {{canal}} for at bekræfte",
    },
  },
  moderacao: {
    titulo: "Moderatorvisning",
    semPermissao: "Du skal have rettigheden “Modererer medlemmer” for at se det her.",
    fecharEsc: "Luk (Esc)",
    atividade: "Aktivitet på serveren",
    mensagens: "Beskeder",
    links: "Links",
    midia: "Medier",
    acoesNaAuditoria: "Handlinger i handlingsloggen",
    moderacoesSofridas: "Modtaget moderering",
    permissoes: "Rettigheder ({{quantas}})",
    semPermissaoEspecial: "Ingen særlige rettigheder.",
    conta: "Konto",
    entrouNoServidor: "Kom med i serveren",
    contaCriadaEm: "Konto oprettet",
    deCastigoAte: "Udelukket indtil",
    formaDeAdesao: "Hvordan vedkommende kom ind",
    mensagem: "Besked",
    castigo: "Udelukkelse",
    copiarId: "Kopiér ID",
    idCopiado: "ID kopieret.",
    adicionarCargo: "Tilføj rolle",
    semCargos: "Ingen rolle oprettet",
    soEveryone: "Kun @everyone.",
    voltar: "Tilbage",
    vazio: "Ingenting her.",
    cinquenta: "Viser de 50 nyeste.",
    irParaMensagem: "Gå til beskeden",
    precisaSerAmigo: "I skal være venner for at snakke.",
    expulsarDescricao: "Forlader serveren med det samme, men kan komme tilbage med en invitation.",
    banirDescricao: "Forlader serveren og kan ikke komme tilbage, heller ikke med en invitation, før bandlysningen ophæves.",
    castigarTitulo: "Udeluk {{nome}} midlertidigt?",
    castigoDescricao: "Så længe det varer, skriver eller taler vedkommende ikke i nogen kanal på serveren.",
    aplicarCastigo: "Anvend udelukkelsen",
    duracao: "Varighed i minutter",
    informeDuracao: "Angiv varigheden i minutter.",
  },
  abas: {
    pesquisar: "Søg i indstillingerne",
    semResultado: "Der er ikke noget med det navn her.",
    comunidade: "Fællesskab",
    expressoes: "Udtryk",
    pessoas: "Folk",
    apps: "Apps",
    moderacao: "Moderation",
    banimentos: "Bandlysninger",
  },
};
