export const amizades = {
  ativosAgora: "Activo ahora",
  procurando: "Viendo quién anda por ahí…",
  tudoTranquilo: "Todo tranquilo por ahora…",
  tudoTranquiloDetalhe: "Cuando tú o un amigo entréis en una llamada, aparecerá aquí — y podrás unirte con un clic.",
  emVoz: "En voz",
  voce: "Tú",
  soVoce: "Solo tú",
  pessoas: "{{quantas}} personas",
  voltarParaChamada: "Volver a la llamada",
  entrarNaChamada: "Unirse a la llamada",
  abrirCanal: "Abrir {{canal}} en {{servidor}}",
  mensagensDiretas: "Mensajes directos",
  encontreConversa: "Busca una conversación",
  amigos: "Amigos",
  conversas: "Conversaciones",
  semConversas: "Todavía no hay conversaciones. Añade un amigo para empezar.",
  semConversaComEsseNome: "Ninguna conversación con ese nombre.",
  abrirMenu: "Abrir servidores y conversaciones",
  solicitacoes: "Solicitudes de mensajes",
  pedidos: "Solicitudes",
  spam: "Spam",
  pedidosPendentes: "Solicitudes pendientes",
  marcadosComoSpam: "Marcados como spam",
  aceitar: "Aceptar",
  ignorar: "Ignorar",
  marcarSpam: "Marcar como spam",
  semPedidos: "Ninguna solicitud esperando.",
  semPedidosDetalhe: "Quien no es tu amigo pero comparte un servidor contigo llega aquí antes de entrar en tus conversaciones.",
  semSpam: "Nada marcado como spam.",
  semSpamDetalhe: "Lo que el filtro de spam aparte, o lo que tú marques, se guarda en esta pestaña.",
  umServidorEmComum: "1 servidor en común",
  servidoresEmComum: "{{quantos}} servidores en común",
  semServidoresEmComum: "Sin servidores en común",
};
