export const chamada = {
  conectando: "Conectando a la llamada…",
  naoEntrou: "No se pudo entrar en la llamada",
  sair: "Salir de la llamada",
  sairDaVoz: "Salir de la llamada de voz",
  desconectar: "Desconectar",
  voltar: "Volver a la llamada",
  voltarAosQuadros: "Volver a los cuadros de la llamada",
  fecharChat: "Cerrar el chat",
  mostrarChat: "Mostrar el chat",
  convidar: "Invitar a la llamada",
  carregandoPrevia: "Cargando la vista previa…",
  maisOpcoes: "Más opciones",
  deVideo: "Videollamada",
  deVoz: "Llamada de voz",
  alguem: "Alguien",
  volume: {
    entrada: "Volumen de entrada",
    saida: "Volumen de salida",
    live: "Volumen de la retransmisión",
    liveComPorcento: "Volumen de la retransmisión ({{porcento}}%)",
    liveSemSom: "Retransmisión sin sonido",
  },
  aparelhos: {
    entrada: "Dispositivo de entrada",
    saida: "Dispositivo de salida",
    camera: "Cámara",
    microfone: "Micrófono",
    saidaCurto: "Salida",
    oDoSistema: "El del sistema",
    aDoSistema: "La del sistema",
    semEscolhaDeSaida: "Este navegador no deja elegir la salida — manda el sistema.",
    espelhar: "Reflejar mi cámara",
    configEntrada: "Ajustes de entrada",
    configSaida: "Ajustes de salida",
    configCamera: "Ajustes de la cámara",
    configAudioEVideo: "Ajustes de audio y vídeo",
  },
  tela: {
    compartilhar: "Compartir pantalla",
    compartilharAcao: "Compartir",
    cancelar: "Cancelar",
    telas: "Pantallas",
    janelas: "Ventanas",
    somDoComputador: "Llevar el sonido del ordenador",
    somDoSistema: "Llevar el sonido del sistema",
    configCompartilhamento: "Ajustes de compartición",
    mostrarSemVideo: "Mostrar a quien no tiene vídeo",
    semFontes: "El sistema no devolvió ninguna pantalla ni ventana para compartir.",
    pararDeCompartilhar: "Dejar de compartir",
    encerrarTransmissao: "Terminar la retransmisión",
  },
  live: {
    etiqueta: "En directo",
    etiquetaMaiuscula: "EN DIRECTO",
    assistir: "Ver la retransmisión",
    assistirPessoa: "Ver a {{nome}}",
    pararDeAssistir: "Dejar de ver",
  },
  membro: {
    mudarMeuApelido: "Cambiar mi apodo",
    meuMicrofone: "Mi micrófono",
    ouvirChamada: "Escuchar la llamada",
    copiarMeuId: "Copiar mi ID",
    idCopiado: "ID copiado.",
    mensagem: "Mensaje",
    silenciar: "Silenciar",
    alterarApelido: "Cambiar el apodo",
    cargos: "Roles",
    semCargo: "Ningún rol creado",
    moverPara: "Mover a",
    silenciarNoServidor: "Silenciar la voz en el servidor",
    desativarAudioNoServidor: "Desactivar el audio en el servidor",
    desconectar: "Desconectar",
    apelidoTitulo: "Tu apodo en este servidor",
    apelidoDeAlguem: "Apodo de {{nome}}",
    apelidoCampo: "Apodo",
    apelidoDicaPropria: "Solo vale aquí. En blanco, vuelve a valer tu nombre de siempre.",
    apelidoDicaDeOutro: "Solo vale en este servidor. Déjalo en blanco para volver al nombre original.",
  },
  detalhes: {
    abrir: "Detalles de voz",
    titulo: "Detalles de Voz",
    conexao: "Conexión",
    pingMedio: "Ping medio",
    ultimoPing: "Último ping",
    perda: "Pérdida de paquetes enviados",
    medindo: "Midiendo…",
    criptografado: "Cifrado hasta el servidor (DTLS-SRTP)",
    explicacao: "Por encima de 250 ms se nota el retraso en la conversación — la gente empieza a pisarse. Una pérdida de paquetes por encima del 10% deja la voz robótica. En los dos casos el problema casi siempre está entre tú y la conexión: prueba con cable en vez de Wi-Fi, o reinicia el router.",
  },
  microfone: {
    bloqueado: "Micrófono bloqueado — solo estás escuchando. Da acceso en los permisos del navegador.",
    bloqueadoNoMac: "macOS está bloqueando el micrófono. Marca",
    caminhoNoMac: "Ajustes del Sistema → Privacidad y Seguridad → Micrófono",
    abrirAjustes: "Abrir los ajustes",
    vaiReabrir: "macOS te pedirá que vuelvas a abrir la aplicación.",
    naoAbriu: "No se pudo abrir el micrófono — solo estás escuchando. Revisa el dispositivo en Ajustes → Voz y vídeo.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS aún no ha permitido la grabación de pantalla. Sin eso, lo compartido sale en negro.",
    marque: "Marca",
    reabra: "en Grabación de Pantalla y vuelve a abrir la aplicación.",
    jaMarcado: "Si ya está marcado, el permiso caducó en la última actualización: desmárcalo, márcalo otra vez y vuelve a abrir.",
  },
  ruido: {
    titulo: "Supresión de ruido",
    explicacao: "Quita el ruido de fondo de tu voz. Prueba a dar palmas o a arrastrar el teclado mientras hablas — quien está en la llamada solo te oye a ti.",
    semSuporte: "Este navegador no ejecuta la supresión avanzada. Sigue valiendo la del propio navegador, que es más floja.",
    aplicando: "Aplicando a la llamada…",
    faleParaTestar: "Habla para probar",
    verdeQuandoPassa: "Verde cuando tu voz pasa.",
    teOuvindo: "Te están oyendo ahora mismo.",
    feitoCom: "Hecho con",
    aquiNoAparelho: ", aquí en tu dispositivo",
    ajustes: "Ajustes",
  },
  permissoes: {
    titulo: "Permisos de macOS",
    detalhe: "macOS pregunta una sola vez, y después solo cambia desde su panel. Aquí puedes ver qué está vigente y resolver lo que falte.",
    concedida: "Concedido",
    negada: "Denegado",
    naoPedida: "No solicitado",
    permitir: "Permitir",
    abrirAjustes: "Abrir ajustes",
    microfone: "Micrófono",
    microfoneDetalhe: "Hablar en las llamadas y probar tu entrada.",
    camera: "Cámara",
    cameraDetalhe: "Encender el vídeo en la llamada.",
    tela: "Grabación de pantalla",
    telaDetalhe: "Compartir la pantalla y las ventanas.",
    monitoramento: "Monitorización de entrada",
    monitoramentoDetalhe: "Usar el pulsar para hablar incluso con Gravaê en segundo plano.",
  },
  jaConectado: {
    titulo: "Ya estás en esta llamada",
    trazer: "Traer la llamada aquí",
    deixar: "Dejarlo como está",
    detalhe: "Al traerla aquí, el otro lado sale de la llamada — tu cuenta está en un sitio cada vez.",
  },
};
