export const perfil = {
  carregando: "Cargando…",
  editar: "Editar perfil",
  mensagem: "Mensaje",
  abrirConversa: "Abrir conversación",
  verCompleto: "Ver el perfil completo",
  convidarParaServidor: "Invitar al servidor",
  semServidores: "No tienes servidores",
  conviteEnviado: "Invitación enviada a {{nome}}.",
  moderador: "Abrir en la vista de moderador",
  mais: "Más",
  ignorar: "Ignorar",
  deixarDeIgnorar: "Dejar de ignorar",
  copiarId: "Copiar el ID del usuario",
  idCopiado: "ID copiado.",
  conexoes: "Conexiones",
  membroDesde: "Miembro desde",
  sobre: "Acerca de",
  cargosTitulo: "Roles",
  visaoGeral: "Vista general",
  amigosEmComum: "Amigos en común ({{quantidade}})",
  servidoresEmComum: "Servidores en común ({{quantidade}})",
  amizade: {
    amigo: "Amigo",
    pedidoEnviado: "Solicitud de amistad enviada",
    respondaAbaixo: "Te envió una solicitud — respóndela abajo",
    adicionar: "Añadir amigo",
    teMandouPedido: "Te envió una solicitud de amistad",
    aceitar: "Aceptar",
    desfazer: "Eliminar de amigos",
    desfazerTitulo: "¿Eliminar a {{nome}} de tus amigos?",
    desfazerDescricao: "Dejáis de ser amigos. La conversación privada sigue en el historial, y puedes añadirlo de nuevo más tarde.",
    bloquear: "Bloquear",
    bloquearTitulo: "¿Bloquear a {{nome}}?",
    bloquearDescricao: "Dejáis de ser amigos, la conversación privada deja de aceptar mensajes y ya no puede enviarte solicitudes de amistad.",
    linkCopiado: "No sois amigos — el enlace se copió para que se lo mandes tú.",
  },
  recado: {
    escrever: "Escribe a @{{usuario}}",
    enviar: "Enviar",
    enviada: "Mensaje enviado",
    falhou: "No se pudo enviar. Inténtalo desde la conversación.",
  },
  cartao: {
    trocarFaixa: "Cambiar el banner de la tarjeta",
    trocarFaixaCurto: "Cambiar el banner",
    trocarFoto: "Cambiar la foto de perfil",
    trocarFotoCurto: "Cambiar la foto",
    suaEtiqueta: "Tu etiqueta",
    editarEtiqueta: "Haz clic para editar tu etiqueta",
    conteAlgo: "Cuéntanos algo sobre ti",
    adicionarStatus: "Añadir un estado",
    adicionarDescricao: "Haz clic para añadir una descripción",
    cargo: "Rol",
    cargos: "Roles",
    cargosCom: "Roles — {{quantidade}}",
    tirarCargo: "Quitar el rol {{cargo}}",
  },
  cargos: {
    adicionar: "Añadir rol",
    procurar: "Buscar un rol",
  },
  etiqueta: {
    escolher: "Elegir la etiqueta de servidor",
    nenhuma: "Ninguna etiqueta de servidor",
    semEtiqueta: "Ninguno de tus servidores tiene etiqueta",
  },
  emblemas: {
    doServidor: "Insignias de este servidor",
    limite: "Puedes llevar hasta {{quantidade}} insignias.",
  },
  nota: {
    vazia: "Haz clic para anotar algo",
    rotulo: "Nota (solo la ves tú)",
    adicionar: "Añadir nota (solo tú la ves)",
  },
  status: {
    titulo: "Estado",
    definir: "Definir tu estado",
    escolherEmoji: "Elegir emoji",
    tirarEmoji: "Quitar el emoji",
    oQuePensa: "¿En qué estás pensando?",
    limparAgora: "Borrar el estado ahora",
    naoLimpar: "No borrar",
    limpar30m: "Borrar en 30 minutos",
    limpar1h: "Borrar en 1 hora",
    limpar4h: "Borrar en 4 horas",
    limparHoje: "Borrar hoy",
    limparAmanha: "Borrar mañana",
    comHora: "{{prazo}} a las {{hora}}",
  },
  presenca: {
    disponivel: "Disponible",
    ausente: "Ausente",
    naoPerturbar: "No molestar",
    naoPerturbarDetalhe: "No recibes aviso de mensajes nuevos",
    invisivel: "Invisible",
    invisivelDetalhe: "Apareces desconectado para los demás",
  },
  menu: {
    mudarDeConta: "Cambiar de cuenta",
    gerenciarContas: "Gestionar cuentas",
  },
  editor: {
    decoracao: "Cambiar la decoración del avatar",
    naoSalvo: "¡No olvides guardar los cambios!",
    principal: "Perfil principal",
  },
};
