export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Ajustes del servidor",
  auditoria: {
    todasAsAcoes: "Todas las acciones",
    todosOsUsuarios: "Todos los usuarios",
    filtroMembros: "Miembros",
    filtroCanais: "Canales",
    filtroEmojis: "Emojis",
    filtroServidor: "Servidor",
    titulo: "Registro de auditoría",
    porUsuario: "Filtrar por usuario",
    porAcao: "Filtrar por acción",
    vazio: "Nada registrado todavía con este filtro.",
    motivo: "Motivo:",
  },
  banimentos: {
    titulo: "Lista de baneos del servidor",
    descricao: "Quien está aquí no entra ni con una invitación nueva. Quitar el baneo devuelve el acceso al instante.",
    procurar: "Buscar baneos por nombre de usuario",
    vazioTitulo: "Sin baneos",
    vazio: "Todavía no has baneado a nadie… pero si algún día hace falta, no lo dudes.",
    desbanir: "Quitar el baneo",
  },
  excluir: {
    tudoVai: "Todos los canales, mensajes e invitaciones de {{servidor}} se borrarán para los {{membros}} miembros. Nadie podrá recuperarlos después.",
    digite: "Escribe {{servidor}} para confirmar",
    titulo: "Eliminar servidor",
    aviso: "Esto no se puede deshacer.",
  },
  emblemas: {
    apagarDescricao: "Se le quita a quien lo esté usando. No se puede deshacer.",
    titulo: "Insignias",
    vazio: "Todavía no hay insignias.",
    novo: "Nueva insignia",
  },
  convites: {
    revogarTitulo: "¿Revocar la invitación?",
    revogarAcao: "Revocar",
    revogarDescricao: "El enlace {{codigo}} deja de funcionar al instante. Quien ya entró por él sigue en el servidor.",
    titulo: "Invitaciones",
    descricao: "Todos los enlaces de invitación activos de este servidor.",
    vazio: "Todavía no se ha creado ninguna invitación.",
    revogar: "Revocar invitación",
  },
  integracoes: {
    opcionais: "username y avatar_url son opcionales y valen por mensaje. El límite es de 5 mensajes cada 5 segundos.",
    apagarDescricao: "La URL deja de funcionar al instante. Los mensajes que ya mandó siguen en el canal.",
    titulo: "Integraciones",
    descricao: "Un webhook es una dirección que publica en un canal sin necesitar cuenta. Sirve para avisar cuando pasa una compilación, cuando alguien abre un ticket, o lo que quieras mandar desde un script.",
    novo: "Nuevo webhook",
    vazio: "Todavía no hay webhooks. Crea uno y pega la URL donde quieras que llegue el mensaje.",
    canal: "Canal",
    apagar: "Eliminar webhook",
    comoUsar: "Cómo se usa",
    comoUsarTexto: "Manda un POST con JSON:",
  },
  engajamento: {
    semCanal: "Sin canal de sistema",
    titulo: "Participación",
    descricao: "Lo que el servidor hace solo para no parecer vacío cuando llega gente nueva.",
    sistema: "Mensajes del sistema",
    boasVindas: "Enviar un mensaje de bienvenida cuando alguien entre",
    sorteio: "Sin texto propio abajo, la frase se sortea — siempre la misma cansa rápido.",
    canalDoSistema: "Canal de mensajes del sistema",
    mensagem: "Mensaje de bienvenida",
    deixeVazio: "Déjalo vacío para sortear entre las frases hechas",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtros que moderan solos, antes de que el mensaje exista. Quien administra el servidor nunca es filtrado — y los roles exentos pasan directos.",
    palavras: {
      titulo: "Bloquear palabras personalizadas",
      descricao: "Tu lista de palabras que nadie puede escribir.",
    },
    mencoes: {
      titulo: "Bloquear spam de menciones",
      descricao: "Bloquea un mensaje con demasiadas menciones de golpe.",
    },
    links: {
      titulo: "Bloquear enlaces",
      descricao: "Retiene cualquier dirección pegada en el chat.",
    },
    definir: "Configurar",
    nomeDaRegra: "Nombre de la regla",
    bloqueadas: "Palabras bloqueadas",
    digiteEnter: "Escribe y pulsa Enter",
    comparacao: "La comparación ignora mayúsculas, acentos y puntuación — y no coge una palabra dentro de otra (\"burro\" no bloquea \"burrocracia\").",
    aPartirDe: "Bloquear a partir de cuántas menciones",
    oQueFazer: "Qué hacer",
    canalDoAlerta: "Canal del aviso",
    escolhaCanal: "Elige un canal",
    castigo: "Silencio temporal (minutos)",
    isentos: "Roles exentos",
    semCargos: "Todavía no hay roles creados.",
    salvarRegra: "Guardar regla",
    apagar: "Eliminar regla",
    excluirTitulo: "¿Eliminar esta regla de AutoMod?",
    excluirDescricao: "El servidor deja de filtrar por ella al instante. Puedes crearla de nuevo, pero la configuración actual se pierde.",
    excluirAcao: "Eliminar regla",
  },
  cargos: {
    titulo: "Roles",
    descricao: "Los roles dan nombre, color y poderes. Quien está más arriba en la lista manda sobre quien está debajo — y nadie toca un rol igual o superior al suyo.",
    criar: "Crear rol",
    vazio: "Todavía no hay roles.",
    abaExibicao: "Apariencia",
    abaPermissoes: "Permisos",
    abaMembros: "Miembros — {{quantos}}",
    everyone: "Vale para todo el mundo en el servidor. Es la base sobre la que suman los demás roles.",
    nomeDoCargo: "Nombre del rol",
    cor: "Color del rol",
    corDica: "Pinta el nombre de quien tiene el rol en la lista de miembros y en el chat.",
    semCor: "Sin color",
    corPersonalizada: "Color personalizado",
    estilo: "Estilo del nombre",
    segundaCor: "Segundo color",
    segundaCorDica: "Sin él, el degradado pasa a color sólido — no desaparece.",
    limparSegundaCor: "Quitar el segundo color",
    icone: "Icono",
    iconeDica: "Aparece junto al rol en la tarjeta de perfil de quien lo tiene.",
    exibirSeparado: "Mostrar separado de los demás miembros",
    exibirSeparadoDica: "El rol tiene su propia sección en la lista de miembros.",
    permitirMencionar: "Permitir mencionar este rol",
    permitirMencionarDica: "Cualquiera podrá notificar a todo el mundo que tenga el rol.",
    semPoderDeConceder: "{{descricao}} (no tienes este permiso para concederlo)",
    adicionar: "Añadir a alguien a este rol",
    tirar: "Quitar el rol",
    semNinguem: "Todavía nadie tiene este rol.",
    apagar: "Eliminar rol",
    excluirTitulo: "¿Eliminar el rol \"{{nome}}\"?",
    excluirDescricao: "Quien tenga este rol pierde todo lo que le daba. No se puede deshacer.",
    excluirAcao: "Eliminar rol",
  },
  membros: {
    procurar: "Buscar por nombre o usuario",
    membroDesde: "Miembro desde",
    vazio: "No se ha encontrado a nadie.",
    acoesPara: "Acciones para {{nome}}",
    deCastigo: "de silencio",
    tirarCastigo: "Quitar el silencio",
    castigo5min: "5 minutos",
    castigo1h: "1 hora",
    castigo1d: "1 día",
    castigo1s: "1 semana",
    expulsar: "Expulsar",
    expulsarTitulo: "¿Expulsar a {{nome}}?",
    expulsarDescricao: "sale de {{servidor}} al instante. Puede volver con una invitación — expulsar no impide el regreso.",
    banir: "Banear",
    banirTitulo: "¿Banear a {{nome}}?",
    banirDescricao: "sale de {{servidor}} y no puede volver, ni con invitación, hasta que le quiten el baneo.",
    motivo: "Motivo (opcional)",
    motivoDica: "Queda registrado en la auditoría",
  },
  perfil: {
    titulo: "Perfil del servidor",
    descricao: "Así es como tu servidor aparece en la lista y en los enlaces de invitación.",
    icone: "Icono",
    faixa: "Banner superior",
    nomeDoServidor: "Nombre del servidor",
    campoDescricao: "Descripción",
    doQueE: "¿De qué va este servidor?",
    comprimido: "Comprimido antes de subir: {{economia}}",
  },
  etiqueta: {
    titulo: "Etiqueta del servidor",
    descricao: "Una etiqueta de hasta 4 letras que aparece junto al nombre de quien es miembro — en el chat y en la lista de personas. Aquí es gratis: sin mejoras, sin niveles.",
    escolhaNome: "Elige un nombre",
    limite: "Máximo 4 caracteres, letras y números.",
    escolhaInsignia: "Elige una insignia",
    voce: "Tú",
    fala1: "¿alguien se apunta a jugar?",
    fala2: "¡échale un ojo a mi etiqueta!",
    fala3: "hala, ¿cómo has conseguido eso?",
  },
  expressoes: {
    comoUsar: "Añade hasta {{limite}} emojis que todo el mundo puede usar en este servidor. Escribe :nombre: en el chat para mandarlo.",
    imagem: "Imagen",
    enviadoPor: "Subido por",
    semEmoji: "Todavía no hay emojis.",
    figurinhas: "Stickers",
    enviarFigurinha: "Subir sticker",
    nomeDaFigurinha: "Nombre del sticker",
    exemploFigurinha: "Ej.: abrazo de gatito",
    figurinhaGrande: "El sticker pasa de {{limite}}.",
    deixaPraLa: "Déjalo",
    sons: "Panel de sonidos",
    enviarSom: "Subir sonido",
    nomeDoSom: "Nombre del sonido",
    semSom: "Todavía no hay sonidos.",
    somGrande: "El sonido pasa de {{limite}}.",
    emojiRelacionado: "Emoji relacionado",
    ouvir: "Escuchar",
    ouvirAssim: "Escuchar así",
    volumeDe: "Volumen de {{nome}}",
    volumeDica: "Vale para todo el mundo del servidor. Cada persona todavía puede bajar los sonidos solo para ella, en el panel de la llamada.",
    falhaEnvio: "No se ha podido subir el archivo.",
    excluirTitulo: "¿Eliminar {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Desaparece del servidor para todo el mundo. Los mensajes que ya lo usaron se quedan como están.",
  },
  canal: {
    visaoGeral: "Vista general",
    nome: "Nombre del canal",
    topico: "Tema del canal",
    topicoDica: "¿De qué se habla aquí?",
    modoLento: "Cada persona solo manda un mensaje por intervalo. Quien gestiona mensajes o canales pasa directo.",
    visibilidade: "Visibilidad del contenido",
    padrao: "Predeterminado",
    padraoDica: "El contenido del canal siempre está visible.",
    spoiler: "Canal de spoilers",
    spoilerDica: "Marca este canal como con spoilers, para que los giros de guion y los temas duros queden ocultos hasta que alguien elija verlos.",
    idade: "Canal con restricción de edad",
    idadeDica: "Quien entre tiene que confirmar que es mayor de edad para ver el contenido.",
    bitrateDica: "Pasar de 64 kbps puede molestar a quien tiene mala conexión.",
    qualidadeDeVideo: "Calidad del vídeo",
    automatica: "Automática",
    limite: "Límite de usuarios — {{valor}}",
    pessoas: "{{quantos}} personas",
    semLimite: "sin límite",
    permissoesDescricao: "Aquí cambias lo que vale en este canal. Lo que quede en “heredar” sigue al rol.",
    excluir: {
      titulo: "Eliminar canal",
      historico: "Todo el historial de {{canal}} se va con él, para todo el mundo.",
      digite: "Escribe {{canal}} para confirmar",
    },
  },
  moderacao: {
    titulo: "Vista de moderador",
    semPermissao: "Necesitas el permiso “Moderar miembros” para ver esto.",
    fecharEsc: "Cerrar (Esc)",
    atividade: "Actividad en el servidor",
    mensagens: "Mensajes",
    links: "Enlaces",
    midia: "Multimedia",
    acoesNaAuditoria: "Acciones en la auditoría",
    moderacoesSofridas: "Moderaciones recibidas",
    permissoes: "Permisos ({{quantas}})",
    semPermissaoEspecial: "Ningún permiso especial.",
    conta: "Cuenta",
    entrouNoServidor: "Entró en el servidor",
    contaCriadaEm: "Cuenta creada el",
    deCastigoAte: "Silenciado hasta",
    formaDeAdesao: "Cómo entró",
    mensagem: "Mensaje",
    castigo: "Silencio temporal",
    copiarId: "Copiar ID",
    idCopiado: "ID copiado.",
    adicionarCargo: "Añadir rol",
    semCargos: "Ningún rol creado",
    soEveryone: "Solo @everyone.",
    voltar: "Volver",
    vazio: "Nada por aquí.",
    cinquenta: "Mostrando los 50 más recientes.",
    irParaMensagem: "Ir al mensaje",
    precisaSerAmigo: "Tenéis que ser amigos para hablar.",
    expulsarDescricao: "Sale del servidor al instante, pero puede volver con una invitación.",
    banirDescricao: "Sale del servidor y no puede volver, ni con invitación, hasta que le quiten el baneo.",
    castigarTitulo: "¿Silenciar a {{nome}}?",
    castigoDescricao: "Mientras dure, no escribe ni habla en ningún canal del servidor.",
    aplicarCastigo: "Aplicar silencio",
    duracao: "Duración en minutos",
    informeDuracao: "Indica la duración en minutos.",
  },
  abas: {
    expressoes: "Expresiones",
    pessoas: "Personas",
    apps: "Apps",
    moderacao: "Moderación",
    banimentos: "Baneos",
  },
};
