export const amizades = {
  ativosAgora: "Nu actief",
  procurando: "Kijken wie er is…",
  tudoTranquilo: "Even helemaal rustig…",
  tudoTranquiloDetalhe: "Als jij of een vriend een gesprek start, verschijnt het hier — en kun je met één klik meedoen.",
  emVoz: "In spraak",
  voce: "Jij",
  soVoce: "Alleen jij",
  pessoas: "{{quantas}} mensen",
  voltarParaChamada: "Terug naar het gesprek",
  entrarNaChamada: "Deelnemen aan gesprek",
  abrirCanal: "{{canal}} openen in {{servidor}}",
  mensagensDiretas: "Directe berichten",
  encontreConversa: "Zoek een gesprek",
  amigos: "Vrienden",
  conversas: "Gesprekken",
  semConversas: "Nog geen gesprekken. Voeg een vriend toe om te beginnen.",
  semConversaComEsseNome: "Geen gesprek met die naam.",
  abrirMenu: "Servers en gesprekken openen",
  solicitacoes: "Berichtverzoeken",
  pedidos: "Verzoeken",
  spam: "Spam",
  pedidosPendentes: "Openstaande verzoeken",
  marcadosComoSpam: "Als spam gemarkeerd",
  aceitar: "Accepteren",
  ignorar: "Negeren",
  marcarSpam: "Markeren als spam",
  semPedidos: "Geen verzoeken in de wacht.",
  semPedidosDetalhe: "Wie geen vriend is maar wel een server met je deelt, komt hier terecht voordat het je gesprekken bereikt.",
  semSpam: "Niets als spam gemarkeerd.",
  semSpamDetalhe: "Wat het spamfilter apart zet, of wat jij markeert, blijft in dit tabblad.",
  umServidorEmComum: "1 gedeelde server",
  servidoresEmComum: "{{quantos}} gedeelde servers",
  semServidoresEmComum: "Geen gedeelde servers",
};
