export const chamada = {
  conectando: "Verbinden met het gesprek…",
  naoEntrou: "Kon niet deelnemen aan het gesprek",
  sair: "Gesprek verlaten",
  sairDaVoz: "Spraakgesprek verlaten",
  desconectar: "Verbinding verbreken",
  voltar: "Terug naar het gesprek",
  voltarAosQuadros: "Terug naar de gespreksvakken",
  fecharChat: "Chat sluiten",
  mostrarChat: "Chat tonen",
  convidar: "Uitnodigen voor het gesprek",
  carregandoPrevia: "Voorbeeld laden…",
  maisOpcoes: "Meer opties",
  deVideo: "Videogesprek",
  deVoz: "Spraakgesprek",
  alguem: "Iemand",
  volume: {
    entrada: "Ingangsvolume",
    saida: "Uitgangsvolume",
    live: "Volume van de live",
    liveComPorcento: "Volume van de live ({{porcento}}%)",
    liveSemSom: "Live zonder geluid",
  },
  aparelhos: {
    entrada: "Invoerapparaat",
    saida: "Uitvoerapparaat",
    camera: "Camera",
    microfone: "Microfoon",
    saidaCurto: "Uitvoer",
    oDoSistema: "Die van het systeem",
    aDoSistema: "Die van het systeem",
    semEscolhaDeSaida: "Deze browser laat je de uitvoer niet kiezen — het systeem beslist.",
    espelhar: "Mijn camera spiegelen",
    configEntrada: "Invoerinstellingen",
    configSaida: "Uitvoerinstellingen",
    configCamera: "Camera-instellingen",
    configAudioEVideo: "Audio- en video-instellingen",
  },
  tela: {
    compartilhar: "Scherm delen",
    compartilharAcao: "Delen",
    cancelar: "Annuleren",
    telas: "Schermen",
    janelas: "Vensters",
    somDoComputador: "Het geluid van de computer meenemen",
    somDoSistema: "Het systeemgeluid meenemen",
    configCompartilhamento: "Deelinstellingen",
    mostrarSemVideo: "Mensen zonder video tonen",
    semFontes: "Het systeem gaf geen scherm of venster terug om te delen.",
    pararDeCompartilhar: "Stoppen met delen",
    encerrarTransmissao: "De uitzending beëindigen",
  },
  live: {
    etiqueta: "Live",
    etiquetaMaiuscula: "LIVE",
    assistir: "De uitzending bekijken",
    assistirPessoa: "{{nome}} bekijken",
    pararDeAssistir: "Stoppen met kijken",
  },
  membro: {
    mudarMeuApelido: "Mijn bijnaam wijzigen",
    meuMicrofone: "Mijn microfoon",
    ouvirChamada: "Naar het gesprek luisteren",
    copiarMeuId: "Mijn ID kopiëren",
    idCopiado: "ID gekopieerd.",
    mensagem: "Bericht",
    silenciar: "Dempen",
    alterarApelido: "Bijnaam wijzigen",
    cargos: "Rollen",
    semCargo: "Geen rol aangemaakt",
    moverPara: "Verplaatsen naar",
    silenciarNoServidor: "Stem dempen op de server",
    desativarAudioNoServidor: "Audio uitschakelen op de server",
    desconectar: "Verbinding verbreken",
    apelidoTitulo: "Jouw bijnaam op deze server",
    apelidoDeAlguem: "Bijnaam van {{nome}}",
    apelidoCampo: "Bijnaam",
    apelidoDicaPropria: "Geldt alleen hier. Laat het leeg om terug te gaan naar je gewone naam.",
    apelidoDicaDeOutro: "Geldt alleen op deze server. Laat het leeg om terug te gaan naar de oorspronkelijke naam.",
  },
  detalhes: {
    abrir: "Spraakdetails",
    titulo: "Spraakdetails",
    conexao: "Verbinding",
    pingMedio: "Gemiddelde ping",
    ultimoPing: "Laatste ping",
    perda: "Verlies van verzonden pakketten",
    medindo: "Meten…",
    criptografado: "Versleuteld tot aan de server (DTLS-SRTP)",
    explicacao: "Boven 250 ms merk je de vertraging in het gesprek — mensen gaan door elkaar praten. Pakketverlies boven 10% maakt de stem robotachtig. In beide gevallen zit het probleem bijna altijd tussen jou en het internet: probeer een kabel in plaats van wifi, of herstart de router.",
  },
  microfone: {
    bloqueado: "Microfoon geblokkeerd — je luistert alleen. Geef toegang in de browserrechten.",
    bloqueadoNoMac: "macOS blokkeert de microfoon. Vink",
    caminhoNoMac: "Systeeminstellingen → Privacy en beveiliging → Microfoon",
    abrirAjustes: "De instellingen openen",
    vaiReabrir: "macOS zal je vragen de app opnieuw te openen.",
    naoAbriu: "Kon de microfoon niet openen — je luistert alleen. Controleer het apparaat bij Instellingen → Spraak en video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS heeft schermopname nog niet toegestaan. Zonder dat komt het delen zwart uit.",
    marque: "Vink",
    reabra: "aan bij Schermopname en open de app opnieuw.",
    jaMarcado: "Staat het al aan, dan is de toestemming verouderd bij de laatste update: zet het uit, weer aan, en open opnieuw.",
  },
  ruido: {
    titulo: "Ruisonderdrukking",
    explicacao: "Haal het achtergrondgeluid uit je stem. Klap eens in je handen of schuif met het toetsenbord terwijl je praat — de mensen in het gesprek horen alleen jou.",
    semSuporte: "Deze browser draait de geavanceerde onderdrukking niet. Die van de browser zelf blijft gelden, en die is zwakker.",
    aplicando: "Toepassen op het gesprek…",
    faleParaTestar: "Praat om te testen",
    verdeQuandoPassa: "Groen als je stem doorkomt.",
    teOuvindo: "Ze horen je nu.",
    feitoCom: "Gemaakt met",
    aquiNoAparelho: ", hier op je eigen apparaat",
    ajustes: "Instellingen",
  },
  permissoes: {
    titulo: "macOS-machtigingen",
    detalhe: "macOS vraagt het maar één keer, en daarna verandert het alleen in zijn eigen paneel. Hier zie je wat er geldt en los je op wat ontbreekt.",
    concedida: "Verleend",
    negada: "Geweigerd",
    naoPedida: "Niet gevraagd",
    permitir: "Toestaan",
    abrirAjustes: "Instellingen openen",
    microfone: "Microfoon",
    microfoneDetalhe: "Praten in gesprekken en je invoer testen.",
    camera: "Camera",
    cameraDetalhe: "De video in het gesprek aanzetten.",
    tela: "Schermopname",
    telaDetalhe: "Het scherm en vensters delen.",
    monitoramento: "Invoermonitoring",
    monitoramentoDetalhe: "Push-to-talk gebruiken, ook met Gravaê op de achtergrond.",
  },
  jaConectado: {
    titulo: "Je zit al in dit gesprek",
    trazer: "Het gesprek hierheen halen",
    deixar: "Zo laten",
    detalhe: "Als je het hierheen haalt, valt de andere kant uit het gesprek — je account zit op één plek tegelijk.",
  },
};
