export const configuracoes = {
  sair: "Uitloggen",
  versoes: {
    copiar: "Klik om te kopiëren",
    copiado: "Gekopieerd",
  },
  telas: {
    conta: "Mijn account",
    privacidade: "Privacy",
    conexoes: "Verbindingen",
    voz: "Audio",
    video: "Video",
    avisos: "Meldingen",
    aplicativos: "Applicaties",
    aparencia: "Weergave",
    batePapo: "Chat",
    acessibilidade: "Toegankelijkheid",
    idioma: "Taal",
    aplicativo: "App downloaden",
    atalhos: "Sneltoetsen",
    servidor: "Server",
  },
  grupos: {
    conta: "Account",
    app: "App-instellingen",
    desenvolvedor: "Ontwikkelaar",
    administracao: "Beheer",
  },
  secoes: {
    detalhesDeLogin: "Inloggegevens",
    dispositivos: "Apparaten",
    usuariosBloqueados: "Geblokkeerde gebruikers",
    aplicativosAutorizados: "Geautoriseerde apps",
    sessoes: "Sessies",
    amigosEDms: "Vrienden en directe berichten",
    compartilhamentoDeAtividade: "Activiteit delen",
    visibilidadeDoPerfil: "Profielzichtbaarheid",
    exportarDados: "Gegevens exporteren",
    exclusaoDeDados: "Gegevens verwijderen",
    tema: "Thema",
    corDeDestaque: "Accentkleur",
    interface: "Interface",
    listaDeCanais: "Kanalenlijst",
    zoomDoApp: "Zoomniveau van de app",
    escalaDaFonte: "Lettergrootte in de chat",
    modoStreamer: "Streamingprivacy",
    movimento: "Beweging",
    textoEmVoz: "Tekst naar spraak",
    teclado: "Toetsenbord",
    formatoDaHora: "Tijdnotatie",
    idiomaDaInterface: "Taal van de interface",
    dispositivosDeVoz: "Apparaten",
    testeDoMicrofone: "Microfoontest",
    modoDeEntrada: "Invoermodus",
    sensibilidade: "Invoergevoeligheid",
    qualidade: "Kwaliteit",
    camera: "Camera",
    transmissao: "Uitzending",
    exibicao: "Weergave",
    entrada: "Invoer",
    midia: "Media",
    geral: "Algemeen",
    preferenciaDeMencao: "Vermeldingsvoorkeur",
    sons: "Geluiden",
  },
};
