export const configuracoes = {
  efeitos: {
    titulo: "Effecten van de aanwijzer",
    detalhe: "Een spoor en vonken over de app getekend. Ze beginnen uit en gaan vanzelf uit als je om minder beweging vroeg.",
    rastro: "Spoor van de aanwijzer",
    rastroDetalhe: "Een lijn die de aanwijzer volgt en erachter vervaagt.",
    faisca: "Vonk bij klikken",
    faiscaDetalhe: "Korte streepjes die wegschieten vanaf je klik.",
    cor: "Kleur",
    espessura: "Dikte",
    comprimento: "Lengte",
    tamanho: "Grootte",
    quantidade: "Aantal",
  },
  email: {
    verificarTitulo: "Bevestig je e-mailadres",
    verificarDetalhe: "Sommige community's laten alleen bevestigde mensen schrijven. Eén klik volstaat.",
    enviar: "Stuur de link",
    enviado: "Kijk in de inbox. De link houdt een dag stand.",
    falhou: "De e-mail kon niet verstuurd worden.",
    confirmado: "E-mailadres bevestigd",
    confirmadoDetalhe: "Klaar. Nu schrijf je in elke community die erom vraagt.",
    linkIncompleto: "Onvolledige link",
    linkIncompletoDetalhe: "De code ontbreekt in het adres. Open de link rechtstreeks uit de e-mail.",
    confirmando: "Bezig met bevestigen…",
    expirou: "Deze link is al gebruikt of verlopen.",
    irParaOApp: "Naar de app",
  },
  tema: {
    indisponivel: "Thema niet beschikbaar",
    indisponivelDetalhe: "Wie het publiceerde heeft het verwijderd, of de link klopt niet.",
    indisponivelLinha: "Thema niet beschikbaar. Wie het publiceerde heeft het verwijderd, of de link klopt niet.",
    importar: "Thema importeren",
    importarCurto: "Importeren",
    importarDetalhe: "Dit vervangt het thema dat je nu hebt. Je kunt het daarna aanpassen in Instellingen > Weergave > Themastudio.",
    porAutor: "door {{autor}}",
    umaCorTrocada: "1 kleur gewisseld",
    coresTrocadas: "{{quantas}} kleuren gewisseld",
    avisoDeCss: "Dit thema brengt CSS mee van wie het schreef, en CSS komt in elke hoek van het scherm. Importeer alleen van mensen die je vertrouwt.",
    soCores: "Dit thema wisselt alleen kleuren. Geen CSS van buiten.",
    aplicar: "Toepassen",
    previaSemMotor: "De voorbeeldweergave draait de motor niet. Installeer om hem te zien.",
    motorAnimado: "{{motor}} geanimeerd",
  },
  sair: "Uitloggen",
  versoes: {
    termos: "Servicevoorwaarden",
    privacidade: "Privacybeleid",
    copiar: "Klik om te kopiëren",
    copiado: "Gekopieerd",
  },
  telas: {
    conta: "Mijn account",
    privacidade: "Privacy",
    conexoes: "Verbindingen",
    voz: "Audio",
    video: "Video",
    avisos: "Meldingen",
    aplicativos: "Applicaties",
    aparencia: "Weergave",
    batePapo: "Chat",
    acessibilidade: "Toegankelijkheid",
    idioma: "Taal",
    aplicativo: "App downloaden",
    atalhos: "Sneltoetsen",
    desktop: "Desktop-app",
    avancado: "Geavanceerd",
    servidor: "Server",
    comunicado: "Systeemmededeling",
    denuncias: "Meldingen",
    publicacoes: "Implementaties",
  },
  grupos: {
    conta: "Account",
    app: "App-instellingen",
    desenvolvedor: "Ontwikkelaar",
    administracao: "Beheer",
  },
  secoes: {
    detalhesDeLogin: "Inloggegevens",
    dispositivos: "Apparaten",
    usuariosBloqueados: "Geblokkeerde gebruikers",
    aplicativosAutorizados: "Geautoriseerde apps",
    sessoes: "Sessies",
    amigosEDms: "Vrienden en directe berichten",
    compartilhamentoDeAtividade: "Activiteit delen",
    visibilidadeDoPerfil: "Profielzichtbaarheid",
    exportarDados: "Gegevens exporteren",
    exclusaoDeDados: "Gegevens verwijderen",
    tema: "Thema",
    corDeDestaque: "Accentkleur",
    interface: "Interface",
    listaDeCanais: "Kanalenlijst",
    zoomDoApp: "Zoomniveau van de app",
    escalaDaFonte: "Lettergrootte in de chat",
    modoStreamer: "Streamingprivacy",
    cursores: "Cursors",
    movimento: "Beweging",
    textoEmVoz: "Tekst naar spraak",
    teclado: "Toetsenbord",
    formatoDaHora: "Tijdnotatie",
    idiomaDaInterface: "Taal van de interface",
    dispositivosDeVoz: "Apparaten",
    testeDoMicrofone: "Microfoontest",
    modoDeEntrada: "Invoermodus",
    sensibilidade: "Invoergevoeligheid",
    qualidade: "Kwaliteit",
    camera: "Camera",
    transmissao: "Uitzending",
    exibicao: "Weergave",
    entrada: "Invoer",
    midia: "Media",
    geral: "Algemeen",
    preferenciaDeMencao: "Vermeldingsvoorkeur",
    sons: "Geluiden",
  },
};
