export const conversa = {
  lista: {
    carregando: "Berichten laden…",
    carregandoMais: "Laden…",
    verMais: "Scroll omhoog om meer te zien",
    semHistorico: "Geschiedenis niet beschikbaar",
    semHistoricoDetalhe: "Je rol heeft geen toestemming om de geschiedenis van #{{canal}} te lezen. Nieuwe berichten blijven verschijnen zolang je hier bent.",
    boasVindas: "Welkom bij #{{canal}}",
    boasVindasDetalhe: "Dit is het begin van het kanaal #{{canal}}.",
  },
  data: {
    hoje: "Vandaag",
    ontem: "Gisteren",
    hojeAs: "vandaag om {{hora}}",
    ontemAs: "gisteren om {{hora}}",
  },
  digitando: {
    um: "{{nome}} is aan het typen…",
    dois: "{{primeiro}} en {{segundo}} zijn aan het typen…",
    varios: "{{quantidade}} mensen zijn aan het typen…",
  },
  mensagem: {
    usou: "gebruikte",
    fixada: "vastgezet",
    editado: "(bewerkt)",
    ignorada: "Bericht van iemand die je negeert.",
    mostrar: "Tonen",
    escPara: "Esc om te",
    cancelar: "annuleren",
    enterParaSalvar: "Enter om op te slaan",
    naoLidasDaqui: "Vanaf hier ongelezen.",
    linkCopiado: "Link gekopieerd.",
    idCopiado: "ID gekopieerd.",
    naoDeuParaCopiar: "Je browser stond kopiëren niet toe.",
    apagarTitulo: "Bericht verwijderen?",
    apagarDescricao: "Het verdwijnt voor iedereen in het kanaal. Dit kan niet ongedaan worden gemaakt.",
    apagarAcao: "Verwijderen",
    citacaoAnexo: "klik om de bijlage te zien",
    citacaoSumiu: "Het oorspronkelijke bericht is er niet meer.",
    encaminhadaDe: "Doorgestuurd uit",
    irParaOriginal: "Naar origineel",
    bloqueadas: "{{quantas}} geblokkeerde berichten",
    mostrarBloqueadas: "Tonen",
    esconderBloqueadas: "Verbergen",
    reagirCom: "Reageer met {{emoji}} — houd ingedrukt om super te reageren",
    segureParaSuper: "{{emoji}} — houd ingedrukt om super te reageren",
  },
  imagem: {
    copiarImagem: "Afbeelding kopiëren",
    baixarImagem: "Afbeelding downloaden",
    copiarLinkDaImagem: "Afbeeldingslink kopiëren",
    abrirLinkDaImagem: "Afbeeldingslink openen",
    maisAcoes: "Meer media-acties",
    pesquisarImagem: "Afbeelding zoeken",
    copiarIdDoAnexo: "Bijlage-ID kopiëren",
    girarEsquerda: "Naar links draaien",
    girarDireita: "Naar rechts draaien",
    ajustar: "Aan scherm aanpassen",
    ampliar: "Inzoomen",
    reduzir: "Uitzoomen",
    imagemCopiada: "Afbeelding gekopieerd.",
    linkCopiado: "Link gekopieerd.",
    idCopiado: "ID gekopieerd.",
    naoDeuParaCopiar: "Kon de afbeelding niet kopiëren.",
  },

  acoes: {
    reagir: "Reageren",
    responder: "Beantwoorden",
    encaminhar: "Doorsturen",
    favoritar: "Bericht bewaren",
    tirarDosFavoritos: "Uit bewaarde verwijderen",
    marcarNaoLida: "Markeren als ongelezen",
    copiarLink: "Berichtlink kopiëren",
    copiarId: "Bericht-ID kopiëren",
    fixar: "Bericht vastzetten",
    desafixar: "Losmaken",
    editar: "Bewerken",
    apagar: "Verwijderen",
    mais: "Meer",
    adicionarReacao: "Reactie toevoegen",
    superReagirCom: "Super reageren met {{emoji}}",
    fixarMensagem: "Bericht vastzetten",
    desafixarMensagem: "Bericht losmaken",
    editarMensagem: "Bericht bewerken",
    apagarMensagem: "Bericht verwijderen",
    denunciarMensagem: "Bericht rapporteren",
  },
  denuncia: {
    titulo: "Bericht rapporteren",
    descricao: "De melding gaat naar het Gravaê-team. Vertel wat er is gebeurd.",
    de: "Van {{nome}}",
    semTexto: "(geen tekst)",
    motivo: "Reden",
    detalhes: "Details (optioneel)",
    enviar: "Melding versturen",
    enviada: "Melding verstuurd. Bedankt.",
    motivos: {
      spam: "Spam of reclame",
      assedio: "Intimidatie of haat",
      conteudo: "Ongepaste inhoud",
      golpe: "Oplichting of fraude",
      outro: "Anders",
    },
  },
  falha: {
    tentarDeNovo: "Opnieuw proberen",
    erro: "Niet bezorgd",
    semConexao: "Niet bezorgd — je hebt geen verbinding",
    semAcesso: "Niet bezorgd — dit kanaal is niet meer bereikbaar",
    semPermissao: "Niet bezorgd — je mag hier niet schrijven",
    castigo: "Niet bezorgd — je hebt een time-out op deze server",
    modoLento: "Niet bezorgd — de langzame modus is nog niet voorbij",
    depressa: "Niet bezorgd — je verstuurt te snel",
    automod: "Niet bezorgd — AutoMod heeft het geblokkeerd",
    recusada: "Niet bezorgd — dit gesprek accepteert geen antwoorden",
  },
  mencao: {
    cargo: "Rolvermelding",
    pessoa: "Vermelding",
    alguem: "iemand",
    cargoSemNome: "rol",
    here: "Waarschuwt iedereen die online is",
    everyone: "Waarschuwt de hele server",
  },
  codigo: {
    copiar: "Kopiëren",
    copiado: "Gekopieerd",
    copiarAria: "De code kopiëren",
    copiadoAria: "Code gekopieerd",
    recolher: "Inklappen",
    expandir: "Uitklappen",
    verInteiro: "Hele bestand bekijken",
    maisOpcoes: "Meer opties",
    baixar: "Downloaden",
    recolherLinhas: "Inklappen ({{linhas}} regels)",
    expandirLinhas: "Uitklappen ({{linhas}} regels)",
    mudarIdioma: "Taal wijzigen",
    procurarIdioma: "Zoek taalcode…",
    nenhumIdioma: "Geen taal gevonden.",
    quebrarTexto: "Tekstterugloop",
  },
  caixa: {
    escrever: "Schrijf in #{{canal}}",
    escreverSemCanal: "Schrijf een bericht",
    semPermissao: "Je hebt geen toestemming om berichten te sturen in dit kanaal",
    solteParaAnexar: "Loslaten om bij te voegen",
    longaTitulo: "Je bericht is te lang…",
    longaDescricao: "Je hebt de limiet van {{limite}} tekens bereikt. Stuur het als bestand.",
    enviarComoArquivo: "Als bestand versturen",
    textoComoArquivo: "Tekst als bestand versturen",
    arquivoGrandeTitulo: "Dit bestand is te groot",
    arquivoGrandeDescricao: "“{{arquivo}}” gaat over de limiet van {{limite}} MB per bestand.",
    respondendoPara: "Antwoord aan",
    vaiNotificar: "De persoon krijgt een melding",
    naoVaiNotificar: "De persoon krijgt geen melding",
    ligado: "aan",
    desligado: "uit",
    pararDeResponder: "Stoppen met antwoorden",
    mais: "Meer",
    enviarArquivo: "Een bestand sturen",
    criarEnquete: "Peiling maken",
    expressoes: "Emoji, GIF en stickers",
    enviar: "Verzenden",
    aguardandoEnvio: "Wachten op de upload",
    modoLento: "Langzame modus actief ({{tempo}})",
    modoLentoDica: "De langzame modus staat op {{segundos}} s. Wacht voordat je een volgend bericht stuurt.",
  },
  anexos: {
    enviando: "Uploaden…",
    modificar: "{{arquivo}} aanpassen",
    verPrevia: "{{arquivo}} bekijken",
    excluirTitulo: "Bijlage verwijderen",
    excluirDescricao: "“{{arquivo}}” verwijderen? Dit kan niet ongedaan worden gemaakt.",
    excluirAcao: "Bijlage verwijderen",
    excluirFalhou: "Kon de bijlage niet verwijderen.",
    remover: "{{arquivo}} verwijderen",
    ver: "{{arquivo}} bekijken",
    mostrarSpoiler: "Spoiler tonen: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Bijlage bewerken",
    nomeDoArquivo: "Bestandsnaam",
    descricao: "Beschrijving van de alt-tekst",
    descricaoDica: "Beschrijf dit medium voor schermlezers",
    marcarSpoiler: "Markeren als spoiler",
    cancelar: "Annuleren",
    salvar: "Opslaan",
  },
  cartao: {
    tocador: "Speler",
    abrir: "{{destino}} openen",
    tocar: "{{titulo}} afspelen",
    video: "video",
    verImagem: "Afbeelding bekijken",
  },
  enquete: {
    titulo: "Peiling",
    encerrada: "Peiling gesloten",
    variasRespostas: "Peiling — meerdere antwoorden",
    umVoto: "{{quantidade}} stem",
    votos: "{{quantidade}} stemmen",
    umVotoNoTotal: "{{quantidade}} stem in totaal",
    votosNoTotal: "{{quantidade}} stemmen in totaal",
    encerraEm: "sluit op {{quando}}",
    encerrarAgora: "Nu sluiten",
  },
  fixadas: {
    titulo: "Vastgezette berichten",
    vazio: "Dit kanaal heeft geen vastgezette berichten… nog niet.",
    desafixar: "Losmaken",
    anexo: "(bijlage)",
    enquete: "(peiling)",
    dicaRotulo: "TIP:",
    dica: "wie de rechten ‘Berichten beheren’ heeft, kan rechtstreeks vanuit het berichtmenu vastzetten.",
  },
  encaminhar: {
    titulo: "Bericht doorsturen",
    paraOnde: "Waarheen?",
    semTexto: "(bericht zonder tekst)",
    nenhumLugar: "Geen plek met die naam.",
    canais: "Kanalen",
    conversas: "Directe berichten",
  },
  expressoes: {
    gifs: "Gifs",
    buscarGifs: "Zoeken op Klipy",
    figurinha: "Sticker",
    buscarFigurinha: "Vind de perfecte sticker",
    buscarEmoji: "Vind de perfecte emoji",
    buscarReacao: "Vind de perfecte reactie",
    adicionarEmoji: "Emoji toevoegen",
    limparBusca: "Zoekopdracht wissen",
  },
  busca: {
    pesquisar: "Zoeken",
    limpar: "Zoekopdracht wissen",
    filtros: "Zoekfilters",
    escopo: {
      titulo: "Zoekbereik",
      servidor: "Huidige community",
      canal: "Dit gesprek",
      comunidades: "Alle communities",
      dms: "Alleen privéberichten",
      tudo: "Privéberichten en communities",
    },
    fechar: "Zoeken sluiten",
    procurando: "Zoeken…",
    resultado: "{{quantos}} resultaat",
    resultados: "{{quantos}} resultaten",
    nadaCom: "Niets met {{termo}} hier.",
    soOsQuePodeLer: "De zoekopdracht kijkt alleen in kanalen die je mag lezen.",
  },
  entrada: {
    titulo: "Postvak in",
    naoLidas: "Ongelezen",
    salvas: "Bewaard",
    mencoes: "Vermeldingen",
    fimTitulo: "Je bent bij het eind",
    fimDetalhe: "Er is niets meer te lezen. Als er een nieuw bericht komt, staat het hier.",
    semSalvosTitulo: "Niets bewaard",
    semSalvosDetalhe: "Houd Shift ingedrukt en klik op de bladwijzer van een bericht om het te bewaren en later te lezen.",
    tirarDosSalvos: "Uit bewaard halen",
    semMencoesTitulo: "Nog geen vermeldingen",
    semMencoesDetalhe: "Vermeldingen van jou staan hier voor de laatste 7 dagen.",
  },
  forum: {
    descricao: "Elk onderwerp wordt een apart gesprek — handig voor een vraag die niet verloren mag gaan midden in het geklets.",
    novoAssunto: "Nieuw onderwerp",
    vazio: "Nog geen onderwerpen. Begin het eerste en het gesprek blijft vanaf het begin geordend.",
    titulo: "Titel",
    doQueSeTrata: "Waar gaat het over?",
    primeiraMensagem: "Eerste bericht",
    conteDoCaso: "Vertel het",
  },
};
