export const perfil = {
  carregando: "Laden…",
  editar: "Profiel bewerken",
  mensagem: "Bericht",
  abrirConversa: "Gesprek openen",
  verCompleto: "Volledig profiel bekijken",
  convidarParaServidor: "Uitnodigen voor de server",
  semServidores: "Je hebt geen servers",
  conviteEnviado: "Uitnodiging naar {{nome}} gestuurd.",
  moderador: "Openen in moderatorweergave",
  mais: "Meer",
  ignorar: "Negeren",
  deixarDeIgnorar: "Niet meer negeren",
  copiarId: "Gebruikers-ID kopiëren",
  idCopiado: "ID gekopieerd.",
  conexoes: "Verbindingen",
  membroDesde: "Lid sinds",
  sobre: "Over",
  cargosTitulo: "Rollen",
  visaoGeral: "Overzicht",
  amigosEmComum: "Gedeelde vrienden ({{quantidade}})",
  servidoresEmComum: "Gedeelde servers ({{quantidade}})",
  amizade: {
    amigo: "Vriend",
    pedidoEnviado: "Vriendschapsverzoek verstuurd",
    respondaAbaixo: "Stuurde je een verzoek — reageer hieronder",
    adicionar: "Vriend toevoegen",
    teMandouPedido: "Stuurde je een vriendschapsverzoek",
    aceitar: "Accepteren",
    desfazer: "Vriendschap beëindigen",
    desfazerTitulo: "{{nome}} uit je vrienden verwijderen?",
    desfazerDescricao: "Jullie zijn geen vrienden meer. Het privégesprek blijft in de geschiedenis staan, en je kunt de persoon later opnieuw toevoegen.",
    bloquear: "Blokkeren",
    bloquearTitulo: "{{nome}} blokkeren?",
    bloquearDescricao: "Jullie zijn geen vrienden meer, het privégesprek accepteert geen berichten meer en deze persoon kan je geen vriendschapsverzoek meer sturen.",
    linkCopiado: "Jullie zijn geen vrienden — de link is gekopieerd zodat je hem kunt sturen.",
  },
  recado: {
    escrever: "Schrijf naar @{{usuario}}",
    enviar: "Verzenden",
    enviada: "Bericht verzonden",
    falhou: "Kon niet worden verzonden. Probeer het vanuit het gesprek.",
  },
  cartao: {
    trocarFaixa: "De kaartbanner wijzigen",
    trocarFaixaCurto: "De banner wijzigen",
    trocarFoto: "De profielfoto wijzigen",
    trocarFotoCurto: "De foto wijzigen",
    suaEtiqueta: "Jouw label",
    editarEtiqueta: "Klik om je label te bewerken",
    conteAlgo: "Vertel iets over jezelf",
    adicionarStatus: "Status toevoegen",
    adicionarDescricao: "Klik om een beschrijving toe te voegen",
    cargo: "Rol",
    cargos: "Rollen",
    cargosCom: "Rollen — {{quantidade}}",
    tirarCargo: "Rol {{cargo}} verwijderen",
  },
  cargos: {
    adicionar: "Rol toevoegen",
    procurar: "Zoek een rol",
  },
  etiqueta: {
    escolher: "Serverlabel kiezen",
    nenhuma: "Geen serverlabel",
    semEtiqueta: "Geen van je servers heeft een label",
  },
  emblemas: {
    doServidor: "Badges van deze server",
    limite: "Je kunt tot {{quantidade}} badges dragen.",
  },
  nota: {
    vazia: "Klik om iets te noteren",
    rotulo: "Notitie (alleen jij ziet die)",
    adicionar: "Notitie toevoegen (alleen jij ziet het)",
  },
  status: {
    titulo: "Status",
    definir: "Je status instellen",
    escolherEmoji: "Emoji kiezen",
    tirarEmoji: "Emoji verwijderen",
    oQuePensa: "Waar denk je aan?",
    limparAgora: "Status nu wissen",
    naoLimpar: "Niet wissen",
    limpar30m: "Over 30 minuten wissen",
    limpar1h: "Over 1 uur wissen",
    limpar4h: "Over 4 uur wissen",
    limparHoje: "Vandaag wissen",
    limparAmanha: "Morgen wissen",
    comHora: "{{prazo}} om {{hora}}",
  },
  presenca: {
    disponivel: "Beschikbaar",
    ausente: "Afwezig",
    naoPerturbar: "Niet storen",
    naoPerturbarDetalhe: "Je krijgt geen melding van nieuwe berichten",
    invisivel: "Onzichtbaar",
    invisivelDetalhe: "Je lijkt offline voor anderen",
  },
  menu: {
    mudarDeConta: "Van account wisselen",
    gerenciarContas: "Accounts beheren",
  },
  editor: {
    decoracao: "De avatardecoratie wijzigen",
    naoSalvo: "Vergeet niet je wijzigingen op te slaan!",
    principal: "Hoofdprofiel",
  },
};
