export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Serverinstellingen",
  auditoria: {
    todasAsAcoes: "Alle acties",
    todosOsUsuarios: "Alle gebruikers",
    filtroMembros: "Leden",
    filtroCanais: "Kanalen",
    filtroEmojis: "Emoji's",
    filtroServidor: "Server",
    titulo: "Auditlogboek",
    porUsuario: "Filteren op gebruiker",
    porAcao: "Filteren op actie",
    vazio: "Nog niets vastgelegd met dit filter.",
    motivo: "Reden:",
  },
  banimentos: {
    titulo: "Banlijst van de server",
    descricao: "Wie hier staat komt er niet meer in, ook niet met een nieuwe uitnodiging. Ontbannen geeft de toegang meteen terug.",
    procurar: "Bans zoeken op gebruikersnaam",
    vazioTitulo: "Geen bans",
    vazio: "Je hebt nog niemand verbannen… maar als het ooit nodig is, aarzel niet.",
    desbanir: "Ontbannen",
  },
  excluir: {
    tudoVai: "Alle kanalen, berichten en uitnodigingen van {{servidor}} worden verwijderd voor de {{membros}} leden. Niemand kan ze daarna terughalen.",
    digite: "Typ {{servidor}} om te bevestigen",
    titulo: "Server verwijderen",
    aviso: "Dit kan niet ongedaan worden gemaakt.",
  },
  emblemas: {
    apagarDescricao: "Het wordt afgenomen van iedereen die het draagt. Dit kan niet ongedaan worden gemaakt.",
    titulo: "Badges",
    vazio: "Nog geen badges.",
    novo: "Nieuwe badge",
  },
  convites: {
    revogarTitulo: "Uitnodiging intrekken?",
    revogarAcao: "Intrekken",
    revogarDescricao: "De link {{codigo}} werkt meteen niet meer. Wie er al mee binnenkwam blijft op de server.",
    titulo: "Uitnodigingen",
    descricao: "Alle actieve uitnodigingslinks van deze server.",
    vazio: "Nog geen uitnodiging aangemaakt.",
    revogar: "Uitnodiging intrekken",
  },
  integracoes: {
    opcionais: "username en avatar_url zijn optioneel en gelden per bericht. De limiet is 5 berichten per 5 seconden.",
    apagarDescricao: "De URL werkt meteen niet meer. De berichten die hij al stuurde blijven in het kanaal.",
    titulo: "Integraties",
    descricao: "Een webhook is een adres dat in een kanaal post zonder account. Handig om te melden dat een build geslaagd is, dat iemand een ticket opent, of wat je verder vanuit een script wilt sturen.",
    novo: "Nieuwe webhook",
    vazio: "Nog geen webhooks. Maak er een en plak de URL waar je het bericht vandaan wilt laten komen.",
    canal: "Kanaal",
    apagar: "Webhook verwijderen",
    comoUsar: "Zo gebruik je het",
    comoUsarTexto: "Stuur een POST met JSON:",
  },
  explorar: {
    titulo: "Ontdekken",
  },
  engajamento: {
    semCanal: "Geen systeemkanaal",
    titulo: "Betrokkenheid",
    descricao: "Wat de server uit zichzelf doet zodat het niet leeg aanvoelt als er iemand nieuw binnenkomt.",
    sistema: "Systeemberichten",
    boasVindas: "Een welkomstbericht sturen als iemand binnenkomt",
    sorteio: "Zonder eigen tekst hieronder wordt de zin geloot — steeds dezelfde gaat snel vervelen.",
    canalDoSistema: "Kanaal voor systeemberichten",
    mensagem: "Welkomstbericht",
    deixeVazio: "Laat leeg om te loten tussen de kant-en-klare zinnen",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filters die vanzelf modereren, nog voordat het bericht bestaat. Wie de server beheert wordt nooit gefilterd — en vrijgestelde rollen gaan er zo doorheen.",
    palavras: {
      titulo: "Eigen woorden blokkeren",
      descricao: "Jouw lijst met woorden die niemand mag schrijven.",
    },
    mencoes: {
      titulo: "Vermeldingsspam blokkeren",
      descricao: "Blokkeert een bericht met te veel vermeldingen tegelijk.",
    },
    links: {
      titulo: "Links blokkeren",
      descricao: "Houdt elk adres tegen dat in de chat geplakt wordt.",
    },
    definir: "Instellen",
    nomeDaRegra: "Naam van de regel",
    bloqueadas: "Geblokkeerde woorden",
    digiteEnter: "Typ en druk op Enter",
    comparacao: "De vergelijking negeert hoofdletters, accenten en leestekens — en pakt geen woord binnen een ander woord (\"kut\" blokkeert \"kutter\" niet als los woord).",
    aPartirDe: "Blokkeren vanaf hoeveel vermeldingen",
    oQueFazer: "Wat te doen",
    canalDoAlerta: "Kanaal voor de melding",
    escolhaCanal: "Kies een kanaal",
    castigo: "Time-out (minuten)",
    isentos: "Vrijgestelde rollen",
    semCargos: "Nog geen rollen aangemaakt.",
    salvarRegra: "Regel opslaan",
    apagar: "Regel verwijderen",
    excluirTitulo: "Deze AutoMod-regel verwijderen?",
    excluirDescricao: "De server filtert er meteen niet meer op. Je kunt hem opnieuw maken, maar de huidige instelling gaat verloren.",
    excluirAcao: "Regel verwijderen",
  },
  cargos: {
    titulo: "Rollen",
    descricao: "Rollen geven naam, kleur en macht. Wie hoger in de lijst staat gaat boven wie eronder staat — en niemand komt aan een rol gelijk aan of boven de eigen rol.",
    criar: "Rol aanmaken",
    vazio: "Nog geen rollen.",
    abaExibicao: "Weergave",
    abaPermissoes: "Rechten",
    abaMembros: "Leden — {{quantos}}",
    everyone: "Geldt voor iedereen op de server. Het is de basis waar de andere rollen bovenop komen.",
    nomeDoCargo: "Naam van de rol",
    cor: "Kleur van de rol",
    corDica: "Kleurt de naam van wie de rol heeft in de ledenlijst en in de chat.",
    semCor: "Zonder kleur",
    corPersonalizada: "Eigen kleur",
    estilo: "Stijl van de naam",
    segundaCor: "Tweede kleur",
    segundaCorDica: "Zonder die valt het verloop terug op één kleur — het verdwijnt niet.",
    limparSegundaCor: "Tweede kleur wissen",
    icone: "Pictogram",
    iconeDica: "Verschijnt naast de rol op de profielkaart van wie hem heeft.",
    exibirSeparado: "Apart van de andere leden tonen",
    exibirSeparadoDica: "De rol krijgt een eigen sectie in de ledenlijst.",
    permitirMencionar: "Deze rol mag vermeld worden",
    permitirMencionarDica: "Iedereen kan dan iedereen met die rol een melding sturen.",
    semPoderDeConceder: "{{descricao}} (jij hebt dit recht niet om het te geven)",
    adicionar: "Iemand aan deze rol toevoegen",
    tirar: "Rol afnemen",
    semNinguem: "Niemand heeft deze rol nog.",
    apagar: "Rol verwijderen",
    excluirTitulo: "De rol \"{{nome}}\" verwijderen?",
    excluirDescricao: "Wie deze rol heeft verliest alles wat hij gaf. Dit kan niet ongedaan worden gemaakt.",
    excluirAcao: "Rol verwijderen",
  },
  membros: {
    procurar: "Zoeken op naam of gebruikersnaam",
    membroDesde: "Lid sinds",
    vazio: "Niemand gevonden.",
    acoesPara: "Acties voor {{nome}}",
    deCastigo: "in time-out",
    tirarCastigo: "Time-out opheffen",
    castigo5min: "5 minuten",
    castigo1h: "1 uur",
    castigo1d: "1 dag",
    castigo1s: "1 week",
    expulsar: "Verwijderen uit server",
    expulsarTitulo: "{{nome}} eruit zetten?",
    expulsarDescricao: "verlaat {{servidor}} meteen. Kan terugkomen met een uitnodiging — eruit zetten houdt de terugkeer niet tegen.",
    banir: "Verbannen",
    banirTitulo: "{{nome}} verbannen?",
    banirDescricao: "verlaat {{servidor}} en kan niet terug, ook niet met een uitnodiging, tot de ban wordt opgeheven.",
    motivo: "Reden (optioneel)",
    motivoDica: "Wordt vastgelegd in het auditlogboek",
  },
  perfil: {
    titulo: "Serverprofiel",
    descricao: "Zo verschijnt je server in de lijst en in uitnodigingslinks.",
    icone: "Pictogram",
    faixa: "Banner bovenaan",
    nomeDoServidor: "Naam van de server",
    campoDescricao: "Beschrijving",
    doQueE: "Waar gaat deze server over?",
    comprimido: "Gecomprimeerd voor het uploaden: {{economia}}",
  },
  etiqueta: {
    titulo: "Servertag",
    descricao: "Een label van maximaal 4 letters dat naast de naam van elk lid verschijnt — in de chat en in de personenlijst. Hier is het gratis: geen boosts, geen levels.",
    escolhaNome: "Kies een naam",
    limite: "Maximaal 4 tekens, letters en cijfers.",
    escolhaInsignia: "Kies een insigne",
    voce: "Jij",
    fala1: "iemand zin om te gamen?",
    fala2: "kijk eens naar mijn tag!",
    fala3: "wow, hoe kom je daaraan",
  },
  expressoes: {
    comoUsar: "Voeg tot {{limite}} emoji's toe die iedereen op deze server kan gebruiken. Typ :naam: in de chat om er een te sturen.",
    imagem: "Afbeelding",
    enviadoPor: "Geüpload door",
    semEmoji: "Nog geen emoji's.",
    figurinhas: "Stickers",
    enviarFigurinha: "Sticker uploaden",
    nomeDaFigurinha: "Naam van de sticker",
    exemploFigurinha: "Bijv.: knuffelend katje",
    figurinhaGrande: "De sticker is groter dan {{limite}}.",
    deixaPraLa: "Laat maar",
    sons: "Geluidsbord",
    enviarSom: "Geluid uploaden",
    nomeDoSom: "Naam van het geluid",
    semSom: "Nog geen geluiden.",
    somGrande: "Het geluid is groter dan {{limite}}.",
    emojiRelacionado: "Bijbehorende emoji",
    ouvir: "Afspelen",
    ouvirAssim: "Zo afspelen",
    volumeDe: "Volume van {{nome}}",
    volumeDica: "Geldt voor iedereen op de server. Elke persoon kan de geluiden alsnog alleen voor zichzelf zachter zetten, in het gesprekspaneel.",
    falhaEnvio: "Het bestand kon niet geüpload worden.",
    excluirTitulo: "{{tipo}} \"{{nome}}\" verwijderen?",
    excluirDescricao: "Verdwijnt van de server voor iedereen. Berichten die het al gebruikten blijven zoals ze zijn.",
  },
  canal: {
    visaoGeral: "Overzicht",
    nome: "Naam van het kanaal",
    topico: "Onderwerp van het kanaal",
    topicoDica: "Waar gaat het hier over?",
    modoLento: "Elke persoon stuurt maar één bericht per interval. Wie berichten of kanalen beheert gaat er zo doorheen.",
    visibilidade: "Zichtbaarheid van de inhoud",
    padrao: "Standaard",
    padraoDica: "De inhoud van het kanaal is altijd zichtbaar.",
    spoiler: "Spoilerkanaal",
    spoilerDica: "Markeer dit kanaal als spoilerkanaal, zodat plotwendingen en zware onderwerpen verborgen blijven tot iemand ze wil zien.",
    idade: "Kanaal met leeftijdsgrens",
    idadeDica: "Wie binnenkomt moet bevestigen meerderjarig te zijn om de inhoud te zien.",
    bitrateDica: "Boven 64 kbps kan het hinderen voor wie een slechte verbinding heeft.",
    qualidadeDeVideo: "Videokwaliteit",
    automatica: "Automatisch",
    limite: "Gebruikerslimiet — {{valor}}",
    pessoas: "{{quantos}} personen",
    semLimite: "geen limiet",
    permissoesDescricao: "Hier verander je wat geldt in dit kanaal. Wat op “overerven” blijft staan volgt de rol.",
    excluir: {
      titulo: "Kanaal verwijderen",
      historico: "De hele geschiedenis van {{canal}} gaat mee, voor iedereen.",
      digite: "Typ {{canal}} om te bevestigen",
    },
  },
  moderacao: {
    titulo: "Moderatorweergave",
    semPermissao: "Je hebt de rechten “Leden modereren” nodig om dit te zien.",
    fecharEsc: "Sluiten (Esc)",
    atividade: "Activiteit op de server",
    mensagens: "Berichten",
    links: "Links",
    midia: "Media",
    acoesNaAuditoria: "Acties in het auditlogboek",
    moderacoesSofridas: "Ontvangen moderatie",
    permissoes: "Rechten ({{quantas}})",
    semPermissaoEspecial: "Geen bijzondere rechten.",
    conta: "Account",
    entrouNoServidor: "Lid geworden op",
    contaCriadaEm: "Account aangemaakt op",
    deCastigoAte: "In time-out tot",
    formaDeAdesao: "Hoe binnengekomen",
    mensagem: "Bericht",
    castigo: "Time-out",
    copiarId: "ID kopiëren",
    idCopiado: "ID gekopieerd.",
    adicionarCargo: "Rol toevoegen",
    semCargos: "Geen rol aangemaakt",
    soEveryone: "Alleen @everyone.",
    voltar: "Terug",
    vazio: "Hier is niets.",
    cinquenta: "De 50 meest recente worden getoond.",
    irParaMensagem: "Ga naar bericht",
    precisaSerAmigo: "Jullie moeten vrienden zijn om te praten.",
    expulsarDescricao: "Verlaat de server meteen, maar kan terugkomen met een uitnodiging.",
    banirDescricao: "Verlaat de server en kan niet terug, ook niet met een uitnodiging, tot de ban wordt opgeheven.",
    castigarTitulo: "{{nome}} een time-out geven?",
    castigoDescricao: "Zolang die duurt schrijft of spreekt de persoon in geen enkel kanaal van de server.",
    aplicarCastigo: "Time-out toepassen",
    duracao: "Duur in minuten",
    informeDuracao: "Geef de duur in minuten op.",
  },
  abas: {
    expressoes: "Expressies",
    pessoas: "Mensen",
    apps: "Apps",
    moderacao: "Moderatie",
    banimentos: "Bans",
  },
};
