export const amizades = {
  ativosAgora: "Şu an aktif",
  procurando: "Kimler var diye bakıyoruz…",
  tudoTranquilo: "Şimdilik ortalık sakin…",
  tudoTranquiloDetalhe: "Sen ya da bir arkadaşın bir aramaya katıldığında burada görünür — ve tek tıkla katılırsın.",
  emVoz: "Seste",
  voce: "Sen",
  soVoce: "Sadece sen",
  pessoas: "{{quantas}} kişi",
  voltarParaChamada: "Aramaya dön",
  entrarNaChamada: "Aramaya katıl",
  abrirCanal: "{{servidor}} sunucusunda {{canal}} kanalını aç",
  mensagensDiretas: "Doğrudan mesajlar",
  encontreConversa: "Bir sohbet bul",
  amigos: "Arkadaşlar",
  conversas: "Sohbetler",
  semConversas: "Henüz sohbet yok. Başlamak için bir arkadaş ekle.",
  semConversaComEsseNome: "Bu adda bir sohbet yok.",
  abrirMenu: "Sunucuları ve sohbetleri aç",
  solicitacoes: "Mesaj istekleri",
  pedidos: "İstekler",
  spam: "Spam",
  pedidosPendentes: "Bekleyen istekler",
  marcadosComoSpam: "Spam olarak işaretlendi",
  aceitar: "Kabul et",
  ignorar: "Yoksay",
  marcarSpam: "Spam olarak işaretle",
  semPedidos: "Bekleyen istek yok.",
  semPedidosDetalhe: "Arkadaşın olmayan ama seninle aynı sunucuda olan kişiler, sohbetlerine ulaşmadan önce buraya düşer.",
  semSpam: "Spam olarak işaretlenen bir şey yok.",
  semSpamDetalhe: "Spam filtresinin ayırdığı ya da senin işaretlediğin şeyler bu sekmede kalır.",
  umServidorEmComum: "1 ortak sunucu",
  servidoresEmComum: "{{quantos}} ortak sunucu",
  semServidoresEmComum: "Ortak sunucu yok",
};
