export const chamada = {
  conectando: "Aramaya bağlanılıyor…",
  naoEntrou: "Aramaya katılınamadı",
  sair: "Aramadan çık",
  sairDaVoz: "Sesli aramadan çık",
  desconectar: "Bağlantıyı kes",
  voltar: "Aramaya dön",
  voltarAosQuadros: "Arama karolarına dön",
  fecharChat: "Sohbeti kapat",
  carregandoPrevia: "Önizleme yükleniyor…",
  maisOpcoes: "Diğer seçenekler",
  deVideo: "Görüntülü arama",
  deVoz: "Sesli arama",
  alguem: "Biri",
  volume: {
    entrada: "Giriş ses düzeyi",
    saida: "Çıkış ses düzeyi",
    live: "Yayın ses düzeyi",
    liveComPorcento: "Yayın ses düzeyi (%{{porcento}})",
    liveSemSom: "Yayın sessiz",
  },
  aparelhos: {
    entrada: "Giriş aygıtı",
    saida: "Çıkış aygıtı",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Çıkış",
    oDoSistema: "Sistemdeki",
    aDoSistema: "Sistemdeki",
    semEscolhaDeSaida: "Bu tarayıcı çıkışı seçmene izin vermiyor — kararı sistem veriyor.",
    espelhar: "Kameramı aynala",
    configEntrada: "Giriş ayarları",
    configSaida: "Çıkış ayarları",
    configCamera: "Kamera ayarları",
    configAudioEVideo: "Ses ve görüntü ayarları",
  },
  tela: {
    compartilhar: "Ekran paylaş",
    compartilharAcao: "Paylaş",
    cancelar: "Vazgeç",
    telas: "Ekranlar",
    janelas: "Pencereler",
    somDoComputador: "Bilgisayarın sesini de al",
    somDoSistema: "Sistemin sesini de al",
    configCompartilhamento: "Paylaşım ayarları",
    mostrarSemVideo: "Görüntüsü olmayanları göster",
    semFontes: "Sistem paylaşılacak hiçbir ekran ya da pencere döndürmedi.",
    pararDeCompartilhar: "Paylaşımı durdur",
    encerrarTransmissao: "Yayını bitir",
  },
  live: {
    etiqueta: "Canlı",
    etiquetaMaiuscula: "CANLI",
    assistir: "Yayını izle",
    assistirPessoa: "{{nome}} kişisini izle",
    pararDeAssistir: "İzlemeyi bırak",
  },
  membro: {
    mudarMeuApelido: "Takma adımı değiştir",
    meuMicrofone: "Mikrofonum",
    ouvirChamada: "Aramayı dinle",
    copiarMeuId: "ID'mi kopyala",
    idCopiado: "ID kopyalandı.",
    mensagem: "Mesaj",
    silenciar: "Sustur",
    alterarApelido: "Takma adı değiştir",
    cargos: "Roller",
    semCargo: "Hiç rol oluşturulmamış",
    moverPara: "Şuraya taşı",
    silenciarNoServidor: "Sunucuda sesi sustur",
    desativarAudioNoServidor: "Sunucuda sesi kapat",
    desconectar: "Bağlantıyı kes",
    apelidoTitulo: "Bu sunucudaki takma adın",
    apelidoDeAlguem: "{{nome}} kişisinin takma adı",
    apelidoCampo: "Takma ad",
    apelidoDicaPropria: "Yalnızca burada geçerli. Boş bırakırsan her zamanki adın geri döner.",
    apelidoDicaDeOutro: "Yalnızca bu sunucuda geçerli. Özgün ada dönmek için boş bırak.",
  },
  detalhes: {
    abrir: "Ses ayrıntıları",
    titulo: "Ses Ayrıntıları",
    conexao: "Bağlantı",
    pingMedio: "Ortalama ping",
    ultimoPing: "Son ping",
    perda: "Gönderilen paket kaybı",
    medindo: "Ölçülüyor…",
    criptografado: "Sunucuya kadar şifreli (DTLS-SRTP)",
    explicacao: "250 ms'nin üstünde gecikme konuşmada fark edilir — insanlar birbirinin sözünü kesmeye başlar. %10'un üstünde paket kaybı sesi robotik yapar. İki durumda da sorun neredeyse her zaman seninle internet arasındadır: Wi-Fi yerine kablo dene ya da modemi yeniden başlat.",
  },
  microfone: {
    bloqueado: "Mikrofon engellendi — yalnızca dinliyorsun. Tarayıcı izinlerinden erişime izin ver.",
    bloqueadoNoMac: "macOS mikrofonu engelliyor. Şunu işaretle:",
    caminhoNoMac: "Sistem Ayarları → Gizlilik ve Güvenlik → Mikrofon",
    abrirAjustes: "Ayarları aç",
    vaiReabrir: "macOS uygulamayı yeniden açmanı isteyecek.",
    naoAbriu: "Mikrofon açılamadı — yalnızca dinliyorsun. Aygıtı Ayarlar → Ses ve görüntü bölümünde kontrol et.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS ekran kaydına henüz izin vermedi. O olmadan paylaşım siyah çıkar.",
    marque: "Şunu işaretle:",
    reabra: "Ekran Kaydı altında aç ve uygulamayı yeniden başlat.",
    jaMarcado: "Zaten işaretliyse, izin son güncellemede eskidi: işareti kaldır, yeniden işaretle ve uygulamayı yeniden aç.",
  },
  ruido: {
    titulo: "Gürültü engelleme",
    explicacao: "Sesindeki arka plan gürültüsünü çıkar. Konuşurken el çırpmayı ya da klavyeyi sürüklemeyi dene — aramadakiler yalnızca seni duyar.",
    semSuporte: "Bu tarayıcı gelişmiş engellemeyi çalıştırmıyor. Tarayıcının kendi engellemesi geçerli kalıyor, o daha zayıf.",
    aplicando: "Aramaya uygulanıyor…",
    faleParaTestar: "Test için konuş",
    verdeQuandoPassa: "Sesin geçtiğinde yeşile döner.",
    teOuvindo: "Şu anda seni duyuyorlar.",
    feitoCom: "Şununla yapıldı:",
    aquiNoAparelho: ", tam burada, senin cihazında",
    ajustes: "Ayarlar",
  },
  permissoes: {
    titulo: "macOS izinleri",
    detalhe: "macOS yalnızca bir kez sorar, sonrasında yalnızca kendi panelinden değişir. Burada neyin geçerli olduğunu görüp eksiği çözebilirsin.",
    concedida: "Verildi",
    negada: "Reddedildi",
    naoPedida: "İstenmedi",
    permitir: "İzin ver",
    abrirAjustes: "Ayarları aç",
    microfone: "Mikrofon",
    microfoneDetalhe: "Aramalarda konuşmak ve girişini test etmek.",
    camera: "Kamera",
    cameraDetalhe: "Aramada görüntüyü açmak.",
    tela: "Ekran kaydı",
    telaDetalhe: "Ekranı ve pencereleri paylaşmak.",
    monitoramento: "Giriş izleme",
    monitoramentoDetalhe: "Gravaê arka plandayken bile bas-konuş kullanmak.",
  },
  jaConectado: {
    titulo: "Bu aramada zaten varsın",
    trazer: "Aramayı buraya getir",
    deixar: "Olduğu gibi bırak",
    detalhe: "Buraya getirince diğer uç aramadan çıkar — hesabın bir seferde tek bir yerde olur.",
  },
};
