export const comum = {
  carregando: "Yükleniyor…",
  salvar: "Kaydet",
  salvando: "Kaydediliyor…",
  descartar: "Vazgeç",
  redefinir: "Sıfırla",
  naoSalvo: "Kaydedilmemiş değişikliklerin var.",
  fechar: "Kapat",
  criar: "Oluştur",
  nome: "Ad",
  emoji: "Emoji",
  previa: "Önizleme",
  cancelar: "Vazgeç",
  enviar: "Gönder",
  apagar: "Sil",
  excluir: "Sil",
  remover: "Kaldır",
  trocar: "Değiştir",
};
