export const configuracoes = {
  sair: "Çıkış yap",
  versoes: {
    copiar: "Kopyalamak için tıkla",
    copiado: "Kopyalandı",
  },
  telas: {
    conta: "Hesabım",
    privacidade: "Gizlilik",
    conexoes: "Bağlantılar",
    voz: "Ses",
    video: "Video",
    avisos: "Bildirimler",
    aplicativos: "Uygulamalar",
    aparencia: "Görünüm",
    batePapo: "Sohbet",
    acessibilidade: "Erişilebilirlik",
    idioma: "Dil",
    aplicativo: "Uygulamayı indir",
    servidor: "Sunucu",
  },
  grupos: {
    conta: "Hesap",
    app: "Uygulama ayarları",
    desenvolvedor: "Geliştirici",
    administracao: "Yönetim",
  },
  secoes: {
    detalhesDeLogin: "Giriş bilgileri",
    dispositivos: "Cihazlar",
    usuariosBloqueados: "Engellenen kullanıcılar",
    aplicativosAutorizados: "Yetkili uygulamalar",
    sessoes: "Oturumlar",
    amigosEDms: "Arkadaşlar ve doğrudan mesajlar",
    compartilhamentoDeAtividade: "Etkinlik paylaşımı",
    visibilidadeDoPerfil: "Profil görünürlüğü",
    exportarDados: "Verileri dışa aktar",
    exclusaoDeDados: "Verileri sil",
    tema: "Tema",
    corDeDestaque: "Vurgu rengi",
    interface: "Arayüz",
    listaDeCanais: "Kanal listesi",
    zoomDoApp: "Uygulama yakınlaştırma düzeyi",
    escalaDaFonte: "Sohbet yazı tipi ölçeği",
    modoStreamer: "Yayın gizliliği",
    movimento: "Hareket",
    textoEmVoz: "Metinden konuşmaya",
    teclado: "Klavye",
    formatoDaHora: "Saat biçimi",
    idiomaDaInterface: "Arayüz dili",
    dispositivosDeVoz: "Cihazlar",
    testeDoMicrofone: "Mikrofon testi",
    modoDeEntrada: "Giriş modu",
    sensibilidade: "Giriş hassasiyeti",
    qualidade: "Kalite",
    camera: "Kamera",
    transmissao: "Yayın",
    exibicao: "Görüntüleme",
    entrada: "Giriş",
    midia: "Medya",
    geral: "Genel",
    preferenciaDeMencao: "Bahsetme tercihi",
    sons: "Sesler",
  },
};
