export const configuracoes = {
  efeitos: {
    titulo: "İşaretçi efektleri",
    detalhe: "Uygulamanın üstüne çizilen iz ve kıvılcım. Kapalı gelirler ve daha az hareket istediysen kendiliğinden sönerler.",
    rastro: "İşaretçi izi",
    rastroDetalhe: "İşaretçiyi izleyen ve arkada solan bir çizgi.",
    faisca: "Tıklamada kıvılcım",
    faiscaDetalhe: "Tıkladığın noktadan fırlayan kısa çizgiler.",
    cor: "Renk",
    espessura: "Kalınlık",
    comprimento: "Uzunluk",
    tamanho: "Boyut",
    quantidade: "Adet",
  },
  email: {
    verificarTitulo: "E-postanı doğrula",
    verificarDetalhe: "Bazı topluluklar yalnızca doğrulayanların yazmasına izin verir. Tek tık yeter.",
    enviar: "Bağlantıyı yolla",
    enviado: "Gelen kutuna bak. Bağlantı bir gün geçerli.",
    falhou: "E-posta gönderilemedi.",
    confirmado: "E-posta doğrulandı",
    confirmadoDetalhe: "Tamamdır. Artık bunu isteyen her toplulukta yazabilirsin.",
    linkIncompleto: "Eksik bağlantı",
    linkIncompletoDetalhe: "Adreste kod eksik. Bağlantıyı doğrudan e-postadan aç.",
    confirmando: "Doğrulanıyor…",
    expirou: "Bu bağlantı kullanılmış ya da süresi geçmiş.",
    irParaOApp: "Uygulamaya git",
  },
  tema: {
    indisponivel: "Tema kullanılamıyor",
    indisponivelDetalhe: "Yayımlayan kişi sildi ya da bağlantı yanlış.",
    indisponivelLinha: "Tema kullanılamıyor. Yayımlayan kişi sildi ya da bağlantı yanlış.",
    importar: "Temayı içe aktar",
    importarCurto: "İçe aktar",
    importarDetalhe: "Bu, şu anki temanın yerine geçer. Sonrasında Ayarlar > Görünüm > Tema stüdyosu üzerinden düzenleyebilirsin.",
    porAutor: "{{autor}} tarafından",
    umaCorTrocada: "1 renk değişti",
    coresTrocadas: "{{quantas}} renk değişti",
    avisoDeCss: "Bu tema yazarının CSS'ini de getiriyor ve CSS ekranın her köşesine dokunur. Yalnızca güvendiğin kişilerden içe aktar.",
    soCores: "Bu tema sadece renkleri değiştiriyor. Dışarıdan CSS yok.",
    verCss: "CSS'i göster",
    esconderCss: "CSS'i gizle",
    aplicar: "Uygula",
    previaSemMotor: "Önizleme motoru çalıştırmaz. Görmek için kur.",
    motorAnimado: "{{motor}} animasyonlu",
  },
  sair: "Çıkış yap",
  versoes: {
    termos: "Hizmet şartları",
    privacidade: "Gizlilik politikası",
    copiar: "Kopyalamak için tıkla",
    copiado: "Kopyalandı",
  },
  subscription: {
    seePlans: "Planları gör",
    upgradeSubtitle: "Yazmak, dosya göndermek ve yayın yapmak için daha yüksek sınırlar ve özel özellikler.",
    perMonth: "aylık",
    perYear: "yıllık",
    save: "%{{percent}} tasarruf",
    howToPay: "Nasıl ödemek istersin?",
    legal: "Ödemeden sonraki 7 gün içinde iade isteyebilirsin. Ödeme Stripe tarafından işlenir; kart numaranı asla görmeyiz.",
    compare: "Ücretsiz ve Infinity",
    featureColumn: "Özellik",
    freeColumn: "Ücretsiz",
    messageRow: "Mesaj karakter sınırı",
    attachmentRow: "Gönderilen dosya boyutu",
    screenRow: "Video kalitesi",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Zaten {{date}} tarihine kadar Infinity'un var.",
    upsell: "Sınırı Infinity ile artır",
    screenUpsell: "Infinity ile daha yüksek kalite",
    free: "Ücretsiz plandasın.",
    activeUntil: "Infinity {{date}} tarihine kadar etkin.",
    renews: "{{date}} tarihinde otomatik yenilenir.",
    endsAt: "Abonelik iptal edildi, {{date}} tarihinde sona erecek.",
    pastDue: "Son ödeme alınamadı. Infinity'u kaybetmemek için kartını güncelle.",
    waiting: "Ödeme onaylanıyor…",
    subscribe: "Abone ol",
    monthly: "Aylık",
    yearly: "Yıllık",
    automatic: "Kart, otomatik yenilenir",
    pass: "Yalnızca dönemi öde (Pix veya kart)",
    manage: "Ödemeyi yönet",
    refund: "İade iste",
    refundDetail: "Ödemeden sonraki 7 gün içinde vazgeçebilirsin: {{amount}}, {{date}} tarihine kadar.",
    refundConfirm: "İade istensin mi?",
    refundConfirmDetail: "Para aynı ödeme yöntemine iade edilir ve Infinity hemen sona erer.",
    refunded: "İade istendi.",
    unavailable: "Abonelik henüz kullanılamıyor.",
    success: "Ödeme alındı. Teşekkürler!",
    canceled: "Ödeme iptal edildi.",
    error: "Bir sorun oluştu. Tekrar dene.",
    no: "Hayır",
    tagRow: "Özel kullanıcı etiketi",
    guildProfilesRow: "Topluluğa özel profiller",
    badgeRow: "Profil rozeti",
    communitiesRow: "Topluluklar",
    savedRow: "Kaydedilen mesajlar",
    animatedEmojiRow: "Hareketli emojiler",
    expressionsRow: "Her yerden emoji ve çıkartma",
    animatedProfileRow: "Hareketli avatar ve profil afişleri",
    earlyAccessRow: "Yeniliklere erken erişim",
    themesRow: "Özel temalar",
  },
  telas: {
    subscription: "Infinity",
    conta: "Hesabım",
    privacidade: "Gizlilik",
    conexoes: "Bağlantılar",
    voz: "Ses",
    video: "Video",
    avisos: "Bildirimler",
    aplicativos: "Uygulamalar",
    aparencia: "Görünüm",
    batePapo: "Sohbet",
    acessibilidade: "Erişilebilirlik",
    idioma: "Dil",
    aplicativo: "Uygulamayı indir",
    atalhos: "Kısayollar",
    desktop: "Masaüstü uygulaması",
    avancado: "Gelişmiş",
    servidor: "Sunucu",
    comunicado: "Sistem duyurusu",
    denuncias: "Şikayetler",
    publicacoes: "Dağıtımlar",
  },
  grupos: {
    conta: "Hesap",
    app: "Uygulama ayarları",
    desenvolvedor: "Geliştirici",
    administracao: "Yönetim",
  },
  secoes: {
    detalhesDeLogin: "Giriş bilgileri",
    dispositivos: "Cihazlar",
    usuariosBloqueados: "Engellenen kullanıcılar",
    aplicativosAutorizados: "Yetkili uygulamalar",
    sessoes: "Oturumlar",
    amigosEDms: "Arkadaşlar ve doğrudan mesajlar",
    compartilhamentoDeAtividade: "Etkinlik paylaşımı",
    visibilidadeDoPerfil: "Profil görünürlüğü",
    exportarDados: "Verileri dışa aktar",
    exclusaoDeDados: "Verileri sil",
    tema: "Tema",
    corDeDestaque: "Vurgu rengi",
    interface: "Arayüz",
    listaDeCanais: "Kanal listesi",
    zoomDoApp: "Uygulama yakınlaştırma düzeyi",
    escalaDaFonte: "Sohbet yazı tipi ölçeği",
    modoStreamer: "Yayın gizliliği",
    cursores: "İmleçler",
    movimento: "Hareket",
    textoEmVoz: "Metinden konuşmaya",
    teclado: "Klavye",
    formatoDaHora: "Saat biçimi",
    idiomaDaInterface: "Arayüz dili",
    dispositivosDeVoz: "Cihazlar",
    testeDoMicrofone: "Mikrofon testi",
    modoDeEntrada: "Giriş modu",
    sensibilidade: "Giriş hassasiyeti",
    qualidade: "Kalite",
    camera: "Kamera",
    transmissao: "Yayın",
    exibicao: "Görüntüleme",
    entrada: "Giriş",
    midia: "Medya",
    geral: "Genel",
    preferenciaDeMencao: "Bahsetme tercihi",
    sons: "Sesler",
  },
};
