export const conversa = {
  lista: {
    carregando: "Mesajlar yükleniyor…",
    carregandoMais: "Yükleniyor…",
    verMais: "Daha fazlası için yukarı kaydır",
    semHistorico: "Geçmiş kullanılamıyor",
    semHistoricoDetalhe: "Rolünün #{{canal}} kanalının geçmişini okuma izni yok. Sen buradayken yeni mesajlar görünmeye devam eder.",
    boasVindas: "#{{canal}} kanalına hoş geldin",
    boasVindasDetalhe: "Burası #{{canal}} kanalının başlangıcı.",
  },
  data: {
    hoje: "Bugün",
    ontem: "Dün",
    hojeAs: "bugün {{hora}}",
    ontemAs: "dün {{hora}}",
  },
  digitando: {
    um: "{{nome}} yazıyor…",
    dois: "{{primeiro}} ve {{segundo}} yazıyor…",
    varios: "{{quantidade}} kişi yazıyor…",
  },
  mensagem: {
    usou: "kullandı:",
    fixada: "sabitlendi",
    editado: "(düzenlendi)",
    ignorada: "Yok saydığın birinden gelen mesaj.",
    mostrar: "Göster",
    escPara: "Esc ile",
    cancelar: "vazgeç",
    enterParaSalvar: "Enter ile kaydet",
    falhou: "Gönderilemedi. Tekrar dene",
    naoLidasDaqui: "Buradan itibaren okunmadı.",
    linkCopiado: "Bağlantı kopyalandı.",
    idCopiado: "ID kopyalandı.",
    naoDeuParaCopiar: "Tarayıcın kopyalamaya izin vermedi.",
    apagarTitulo: "Mesaj silinsin mi?",
    apagarDescricao: "Kanaldaki herkesten kaybolur. Geri getirilemez.",
    apagarAcao: "Sil",
    citacaoAnexo: "eki görmek için tıkla",
    citacaoSumiu: "Özgün mesaj artık burada değil.",
    reagirCom: "{{emoji}} ile tepki ver — süper tepki için basılı tut",
    segureParaSuper: "{{emoji}} — süper tepki için basılı tut",
  },
  acoes: {
    reagir: "Tepki ver",
    responder: "Yanıtla",
    encaminhar: "İlet",
    favoritar: "Mesajı kaydet",
    tirarDosFavoritos: "Kayıtlılardan çıkar",
    marcarNaoLida: "Okunmadı olarak işaretle",
    copiarLink: "Mesaj bağlantısını kopyala",
    copiarId: "Mesaj ID'sini kopyala",
    fixar: "Mesajı sabitle",
    desafixar: "Sabitlemeyi kaldır",
    editar: "Düzenle",
    apagar: "Sil",
    mais: "Daha fazla",
    adicionarReacao: "Tepki ekle",
    superReagirCom: "{{emoji}} ile süper tepki",
    fixarMensagem: "Mesajı sabitle",
    desafixarMensagem: "Mesajın sabitlemesini kaldır",
    editarMensagem: "Mesajı düzenle",
    apagarMensagem: "Mesajı sil",
  },
  mencao: {
    cargo: "Rol bahsi",
    pessoa: "Bahsetme",
    alguem: "biri",
    cargoSemNome: "rol",
    here: "Çevrimiçi olanlara bildirir",
    everyone: "Tüm sunucuya bildirir",
  },
  codigo: {
    copiar: "Kopyala",
    copiado: "Kopyalandı",
    copiarAria: "Kodu kopyala",
    copiadoAria: "Kod kopyalandı",
  },
  caixa: {
    escrever: "#{{canal}} kanalına yaz",
    escreverSemCanal: "Bir mesaj yaz",
    semPermissao: "Bu kanala mesaj gönderme iznin yok",
    solteParaAnexar: "Eklemek için bırak",
    respondendoPara: "Şuna yanıt:",
    vaiNotificar: "Kişiye bildirim gider",
    naoVaiNotificar: "Kişiye bildirim gitmez",
    ligado: "açık",
    desligado: "kapalı",
    pararDeResponder: "Yanıtlamaktan vazgeç",
    mais: "Daha fazla",
    enviarArquivo: "Bir dosya gönder",
    criarEnquete: "Anket oluştur",
    expressoes: "Emoji, GIF ve çıkartmalar",
    enviar: "Gönder",
    aguardandoEnvio: "Yükleme bekleniyor",
    modoLento: "Yavaş mod açık ({{tempo}})",
    modoLentoDica: "Yavaş mod {{segundos}} sn olarak ayarlı. Başka bir mesaj göndermeden önce bekle.",
  },
  anexos: {
    enviando: "Yükleniyor…",
    modificar: "{{arquivo}} dosyasını düzenle",
    remover: "{{arquivo}} dosyasını kaldır",
    ver: "{{arquivo}} dosyasını görüntüle",
    mostrarSpoiler: "Spoiler'ı göster: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Eki düzenle",
    nomeDoArquivo: "Dosya adı",
    descricao: "Alternatif metin açıklaması",
    descricaoDica: "Bu içeriği ekran okuyucular için tarif et",
    marcarSpoiler: "Spoiler olarak işaretle",
    cancelar: "Vazgeç",
    salvar: "Kaydet",
  },
  cartao: {
    tocador: "Oynatıcı",
    abrir: "{{destino}} adresini aç",
    tocar: "{{titulo}} oynat",
    video: "video",
    verImagem: "Görseli görüntüle",
  },
  enquete: {
    titulo: "Anket",
    encerrada: "Anket kapandı",
    variasRespostas: "Anket — birden çok yanıt",
    umVoto: "{{quantidade}} oy",
    votos: "{{quantidade}} oy",
    umVotoNoTotal: "toplam {{quantidade}} oy",
    votosNoTotal: "toplam {{quantidade}} oy",
    encerraEm: "{{quando}} tarihinde kapanıyor",
    encerrarAgora: "Şimdi kapat",
  },
  fixadas: {
    titulo: "Sabitlenmiş mesajlar",
    vazio: "Bu kanalda henüz sabitlenmiş mesaj yok.",
    desafixar: "Sabitlemeyi kaldır",
    anexo: "(ek)",
    enquete: "(anket)",
    dicaRotulo: "İPUCU:",
    dica: "“Mesajları yönet” iznine sahip olan, mesaj menüsünden doğrudan sabitleyebilir.",
  },
  encaminhar: {
    titulo: "Mesajı ilet",
    paraOnde: "Nereye?",
    semTexto: "(metni olmayan mesaj)",
    nenhumLugar: "Bu adda bir yer yok.",
    canais: "Kanallar",
    conversas: "Direkt mesajlar",
  },
  expressoes: {
    gifs: "GIF'ler",
    buscarGifs: "Klipy'de ara",
    figurinha: "Çıkartma",
    buscarFigurinha: "Mükemmel çıkartmayı bul",
    buscarEmoji: "Mükemmel emojiyi bul",
    buscarReacao: "Mükemmel tepkiyi bul",
    adicionarEmoji: "Emoji ekle",
    limparBusca: "Aramayı temizle",
  },
  busca: {
    fechar: "Aramayı kapat",
    procurando: "Aranıyor…",
    resultado: "{{quantos}} sonuç",
    resultados: "{{quantos}} sonuç",
    nadaCom: "{{termo}} ile ilgili bir şey yok.",
    soOsQuePodeLer: "Arama yalnızca okuyabildiğin kanallara bakar.",
  },
  entrada: {
    titulo: "Gelen kutusu",
    naoLidas: "Okunmamış",
    salvas: "Kaydedilen",
    mencoes: "Bahsedilenler",
    fimTitulo: "Sona geldin",
    fimDetalhe: "Okunacak başka bir şey yok. Yeni mesaj geldiğinde burada görünür.",
    semSalvosTitulo: "Kaydedilen bir şey yok",
    semSalvosDetalhe: "Shift'e basılı tutup bir mesajın yer imine tıkla; böylece saklanır, sonra okursun.",
    tirarDosSalvos: "Kaydedilenlerden çıkar",
    semMencoesTitulo: "Henüz bahsedilme yok",
    semMencoesDetalhe: "Senden bahsedilenler son 7 gün için burada görünür.",
  },
  forum: {
    descricao: "Her konu ayrı bir sohbet olur — sohbetin ortasında kaybolmaması gereken soru için iyi.",
    novoAssunto: "Yeni konu",
    vazio: "Henüz konu yok. İlkini başlat, sohbet en baştan düzenli kalsın.",
    titulo: "Başlık",
    doQueSeTrata: "Konu ne?",
    primeiraMensagem: "İlk mesaj",
    conteDoCaso: "Anlat",
  },
};
