export const perfil = {
  carregando: "Yükleniyor…",
  editar: "Profili düzenle",
  mensagem: "Mesaj",
  abrirConversa: "Sohbeti aç",
  verCompleto: "Tam profili gör",
  convidarParaServidor: "Sunucuya davet et",
  semServidores: "Hiç sunucun yok",
  conviteEnviado: "{{nome}} kişisine davet gönderildi.",
  moderador: "Moderatör görünümünde aç",
  mais: "Daha fazla",
  ignorar: "Yok say",
  deixarDeIgnorar: "Yok saymayı bırak",
  copiarId: "Kullanıcı ID'sini kopyala",
  idCopiado: "ID kopyalandı.",
  conexoes: "Bağlantılar",
  membroDesde: "Üyelik başlangıcı",
  sobre: "Hakkında",
  cargosTitulo: "Roller",
  visaoGeral: "Genel bakış",
  amigosEmComum: "Ortak arkadaşlar ({{quantidade}})",
  servidoresEmComum: "Ortak sunucular ({{quantidade}})",
  amizade: {
    amigo: "Arkadaş",
    pedidoEnviado: "Arkadaşlık isteği gönderildi",
    respondaAbaixo: "Sana istek gönderdi — aşağıdan yanıtla",
    adicionar: "Arkadaş ekle",
    teMandouPedido: "Sana arkadaşlık isteği gönderdi",
    aceitar: "Kabul et",
    desfazer: "Arkadaşlıktan çıkar",
    desfazerTitulo: "{{nome}} arkadaşlarından çıkarılsın mı?",
    desfazerDescricao: "Artık arkadaş olmayacaksınız. Özel sohbet geçmişte kalır ve daha sonra tekrar ekleyebilirsin.",
    bloquear: "Engelle",
    bloquearTitulo: "{{nome}} engellensin mi?",
    bloquearDescricao: "Artık arkadaş olmayacaksınız, özel sohbet mesaj almayı bırakır ve bu kişi sana bir daha arkadaşlık isteği gönderemez.",
    linkCopiado: "Arkadaş değilsiniz — bağlantı kopyalandı, sen gönder.",
  },
  recado: {
    escrever: "@{{usuario}} kişisine yaz",
    enviar: "Gönder",
    enviada: "Mesaj gönderildi",
    falhou: "Gönderilemedi. Sohbetten dene.",
  },
  cartao: {
    trocarFaixa: "Kart afişini değiştir",
    trocarFaixaCurto: "Afişi değiştir",
    trocarFoto: "Profil fotoğrafını değiştir",
    trocarFotoCurto: "Fotoğrafı değiştir",
    suaEtiqueta: "Etiketin",
    editarEtiqueta: "Etiketini düzenlemek için tıkla",
    conteAlgo: "Kendinden biraz bahset",
    adicionarStatus: "Durum ekle",
    adicionarDescricao: "Açıklama eklemek için tıkla",
    cargo: "Rol",
    cargos: "Roller",
    cargosCom: "Roller — {{quantidade}}",
    tirarCargo: "{{cargo}} rolünü kaldır",
  },
  cargos: {
    adicionar: "Rol ekle",
    procurar: "Rol ara",
  },
  etiqueta: {
    escolher: "Sunucu etiketini seç",
    nenhuma: "Sunucu etiketi yok",
    semEtiqueta: "Sunucularının hiçbirinde etiket yok",
  },
  emblemas: {
    doServidor: "Bu sunucunun rozetleri",
    limite: "En fazla {{quantidade}} rozet takabilirsin.",
  },
  nota: {
    vazia: "Bir not almak için tıkla",
    rotulo: "Not (yalnızca sen görürsün)",
    adicionar: "Not ekle (sadece sen görürsün)",
  },
  status: {
    titulo: "Durum",
    definir: "Durumunu ayarla",
    escolherEmoji: "Emoji seç",
    tirarEmoji: "Emojiyi kaldır",
    oQuePensa: "Aklından ne geçiyor?",
    limparAgora: "Durumu şimdi temizle",
    naoLimpar: "Temizleme",
    limpar30m: "30 dakika sonra temizle",
    limpar1h: "1 saat sonra temizle",
    limpar4h: "4 saat sonra temizle",
    limparHoje: "Bugün temizle",
    limparAmanha: "Yarın temizle",
    comHora: "{{prazo}} — {{hora}}",
  },
  presenca: {
    disponivel: "Çevrimiçi",
    ausente: "Boşta",
    naoPerturbar: "Rahatsız etmeyin",
    naoPerturbarDetalhe: "Yeni mesaj bildirimi almazsın",
    invisivel: "Görünmez",
    invisivelDetalhe: "Diğerlerine çevrimdışı görünürsün",
  },
  menu: {
    mudarDeConta: "Hesap değiştir",
    gerenciarContas: "Hesapları yönet",
  },
  editor: {
    decoracao: "Avatar süslemesini değiştir",
    naoSalvo: "Değişikliklerini kaydetmeyi unutma!",
    principal: "Ana profil",
  },
};
