export const servidor = {
  comunidade: {
    ativa: "Topluluk açık",
    ativaDesde: "{{quando}} tarihinden beri açık",
    membrosAgora: "{{quantos}} üye",
    criarParaMim: "Benim için bir tane aç",
    canalDeRegras: "Kural kanalı",
    canalDeRegrasDetalhe: "Herkesin konuşmadan önce okuduğu kuralların durduğu yer.",
    canalDeAvisos: "Topluluk duyuruları kanalı",
    canalDeAvisosDetalhe: "Burada değişenleri oraya yolluyoruz, sadece yönetenler için.",
    canalDeSeguranca: "Güvenlik uyarıları kanalı",
    canalDeSegurancaDetalhe: "Filtrelerin yakaladığı şeyler denetime buradan düşer.",
    idiomaPrincipal: "Ana dil",
    idiomaPrincipalDetalhe: "Sohbetin büyük bölümünün geçtiği dil.",
    semIdioma: "Dil seçilmedi",
    semCanal: "Kanal yok",
    finalTitulo: "Neredeyse bitti",
    finalDetalhe: "Açmadan önce, gelenler için neyin değiştiğine bak.",
    confereRegras: "Katılan ilk olarak kural kanalını görür.",
    confereEveryone: "@everyone ve @here'ı yalnızca rolü olanlar kullanır.",
    confereMencoes: "Herkesi tek seferde anmak artık izin ister.",
    concordo: "Kabul ediyorum ve anlıyorum",
    concordoDetalhe: "Topluluğun kurallarımıza uyduğunu onaylıyorsun.",
    proximo: "İleri",
    terminar: "Kurulumu bitir",
    visaoGeral: "Genel görünüm",
    visaoGeralDetalhe: "Topluluğun yeni gelenlerle konuştuğu kanallar.",
    seguranca: "Güvenlik",
    segurancaDetalhe: "İstenmeyeni ve ağır içeriği tutan frenler.",
    habilitada: "Topluluk açıldı.",
    falhou: "Topluluk açılamadı.",
    titulo: "Topluluk",
    ilustracao: "Konuşma balonları",
    convite: "Bir topluluk mu kuruyorsun?",
    conviteDetalhe: "Topluluğa çevir ve büyük bir yerin araçlarını al: kural kanalı, bizden gelen duyurular ve kendi kendine denetleyen filtreler.",
    contagem: "{{minimo}} üyeden {{membros}} tanesi",
    faltam: "Açılması için {{quantos}} kişi daha lazım.",
    prontoParaAbrir: "Artık açılabilir.",
    habilitar: "Topluluğu aç",
    vantagemCrescer: "Büyümek",
    vantagemCrescerDetalhe: "Topluluk Keşfet'e başvurabilir, konuyu arayanlar sizi bulur.",
    vantagemModerar: "Denetlemek",
    vantagemModerarDetalhe: "Doğrulanmış e-posta iste, medyayı ele, AutoMod'u tek seferde aç.",
    vantagemAvisos: "Haberdar olmak",
    vantagemAvisosDetalhe: "Değişenleri burayı yönetenlere, size özel bir kanaldan yolluyoruz.",
    assistenteTitulo: "Topluluğunu kuralım.",
    passoSeguranca: "Güvenlik kontrolleri",
    passoBasico: "Temel hazırlık",
    passoFinal: "Son dokunuşlar",
    seguraTitulo: "Topluluğu güvende tut",
    seguraDetalhe: "Büyük topluluk istenmeyeni çeker. Bu iki fren baştan açık, sonradan kapatabilirsin.",
    emailVerificado: "Doğrulanmış e-posta iste",
    emailVerificadoDetalhe: "E-postasını doğrulamamış olan mesaj atamaz. Rolü olan doğrudan geçer.",
    filtroDeMidia: "Müstehcen medyayı ele",
    filtroDeMidiaDetalhe: "Görseller ve videolar örtülü gelir, ancak biri bakmayı seçince görünür.",
    basicoTitulo: "Temeli hazırla",
    basicoDetalhe: "Kuralların hangi kanalda olduğunu ve duyurularımızın nereye gideceğini söyle. Kanal seçilmezse ikisini de ben açarım.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} komut",
    previa: "Kart nasıl görünüyor",
    trocarIcone: "Simgeyi değiştir",
    tirarCapa: "Kapağı kaldır",
    heroComunidades: "Birileri tam da senin sevdiğin şeyi konuşuyor",
    heroComunidadesDetalhe: "Buranın insanlarının açtığı topluluklar. Gir, konuşulanı oku, hoşuna giderse kal.",
    emDestaque: "Öne çıkanlar",
    todasAsComunidades: "Geri kalanlar",
    heroTitulo: "Ekibin bugün ne kullanacak?",
    heroDetalhe: "Müzik, oyun ve denetim için botlar; hepsini burada olan insanlar yaptı. Birini seç, sunucuna girsin.",
    novidades: "Yeni geldi",
    todosOsApps: "Geri kalanlar",
    lojaTitulo: "Uygulamanın sayfası",
    lojaDetalhe: "Keşfet'te, onu henüz tanımayan bunu görür.",
    capa: "Kapak",
    capaDetalhe: "Sayfanın üstündeki geniş görsel. 1280 × 720 yakışır.",
    trocarCapa: "Kapağı değiştir",
    categorias: "Kategoriler",
    categoriasDetalhe: "En çok {{quantas}} tane. Keşfet'te bunlara göre gezilir.",
    idiomas: "Diller",
    idiomasDetalhe: "En çok {{quantos}} tane. Uygulamanın yanıt verdiği diller.",
    termos: "Kullanım koşulları",
    politica: "Gizlilik politikası",
    politicas: "Politikalar",
    servidorDeSuporte: "Destek sunucusu",
    servidorDeSuporteDetalhe: "Uygulamayla ilgili yardım gerekenin gittiği yer.",
    semServidor: "Hiçbiri",
    emQuantosServidores: "Kaç sunucuda",
    categoria: {
      GAMES: "Oyun",
      MUSICA: "Müzik",
      MODERACAO: "Denetim",
      PRODUTIVIDADE: "Üretkenlik",
      SOCIAL: "Sosyal",
      UTILIDADES: "Araçlar",
      ARTE_E_CRIACAO: "Sanat ve üretim",
      EDUCACAO: "Öğrenme",
      OUTRA: "Diğer",
    },
    appIndisponivel: "Uygulama kullanılamıyor",
    voltarParaExplorar: "Keşfet'e dön",
    adicionarApp: "Uygulamayı ekle",
    copiarLink: "Bağlantıyı kopyala",
    denunciarApp: "Uygulamayı bildir",
    copiarIdDoApp: "Uygulama kimliğini kopyala",
    visaoGeral: "Genel bakış",
    comandos: "Komutlar",
    permissoes: "İzinler",
    semPermissoes: "Bu uygulama hiçbir izin istemiyor.",
    avisoDePermissoes: "Kendi rolüyle giriyor. Bu izinleri sonradan Topluluk ayarları → Roller altından değiştirebilirsin.",
    servidoresEmComum: "Ortak topluluklar",
    umServidorEmComum: "1 topluluk",
    quantosServidoresEmComum: "{{quantos}} topluluk",
    feitoPor: "Yapan",
    publicadoEm: "Yayımlanma",
    denunciarNome: "{{nome}} uygulamasını bildir",
    denunciaDetalhe: "Bildirim Gravaê ekibine gider. Uygulamayı yapan kişi, bildirenin sen olduğunu öğrenmez.",
    denunciaFalhou: "Bildirim gönderilemedi.",
    umMembro: "1 üye",
    semDescricao: "Açıklama yok.",
    adicionar: "Ekle",
    jaEstaAqui: "Zaten buradasın",
    entrando: "Katılıyor…",
    entrar: "Katıl",
    comunidadePublica: "Herkese açık topluluk",
    online: "{{quantos}} çevrimiçi",
    membros: "{{quantos}} üye",
    abrirComunidade: "Topluluğu aç",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Sunucu ayarları",
  novasMensagens: "Yeni mesajlar",
  menu: {
    silenciar: "Topluluğu sessize al",
    reativar: "Topluluğun sesini aç",
    porQuinze: "15 dakika",
    porMeiaHora: "30 dakika",
    porTresHoras: "3 saat",
    porTresDias: "3 gün",
    porUmaHora: "1 saat",
    porOitoHoras: "8 saat",
    porUmDia: "24 saat",
    ateReativar: "Ben açana kadar",
    notificacoes: "Bildirim ayarları",
    padrao: "Varsayılanı kullan",
    todas: "Tüm mesajlar",
    soMencoes: "Yalnızca bahsetmeler",
    nada: "Hiçbiri",
    ocultarSilenciados: "Sessize alınan kanalları gizle",
    denunciar: "Topluluğu bildir",
    marcarLida: "Okundu olarak işaretle",
    convidar: "Üye davet et",
    editarPerfil: "Topluluk profilini düzenle",
    configuracoes: "Topluluk ayarları",
    sair: "Topluluktan ayrıl",
    sairTitulo: "{{nome}} topluluğundan ayrılsın mı?",
    sairDescricao: "Geri dönmek için yeni bir davet gerekecek.",
    copiarId: "Topluluk ID'sini kopyala",
    idCopiado: "ID kopyalandı.",
  },
  convite: {
    cartaoTitulo: "Bir topluluğa davet edildin",
    indisponivel: "Davet kullanılamıyor",
    indisponivelDetalhe: "Süresi doldu, hakkı bitti ya da oluşturan kişi sildi.",
    entrar: "Topluluğa katıl",
    chamado: "Şuraya davet edildin:",
    aceitarComo: "{{nome}} olarak kabul et",
    abrir: "Topluluğu aç",
    recusar: "Hayır, teşekkürler",
  },
  pasta: {
    silenciarTodas: "Toplulukları sessize al",
    reativarTodas: "Toplulukların sesini aç",
    mostrarSilenciados: "Sessize alınan kanalları göster",
    notificacoesDaComunidade: "Bildirim ayarları",
    silenciarEveryone: "@everyone ve @here sessize al",
    permitirEveryone: "@everyone ve @here izin ver",
    silenciarCargos: "Rol bahsetmelerini sessize al",
    permitirCargos: "Rol bahsetmelerine izin ver",
    dicaDaCor: "Bir renk yaz (hex, rgb(), hsl() veya ad) ya da seçiciyi kullan.",
    mostrarIcone: "Kapalıyken simgeyi göster",
    dicaDoIcone: "Kapalıyken içindeki sunucular yerine simgeyi gösterir.",
    icone: "Klasör simgesi",
    excluir: "Klasörü sil",
    icones: {
      pasta: "Klasör",
      estrela: "Favori",
      coracao: "Kalp",
      salvar: "Kaydet",
      jogo: "Oyun kolu",
      escudo: "Kalkan",
      nota: "Müzik notası",
    },
    marcarLida: "Klasörü okundu olarak işaretle",
    configuracoes: "Klasör ayarları",
    desfazer: "Klasörü dağıt",
    titulo: "Klasör",
    nome: "Ad",
    semNome: "Adsız",
    cor: "Renk",
    semCor: "Renksiz",
    salvar: "Kaydet",
  },
  denuncia: {
    titulo: "{{nome}} topluluğunu bildir",
    descricao: "Bildirim Gravaê ekibine gider. Ne olduğunu anlat.",
    motivo: "Sebep",
    detalhes: "Ayrıntılar (isteğe bağlı)",
    enviar: "Bildirimi gönder",
    enviada: "Bildirim gönderildi. Teşekkürler.",
    motivos: {
      spam: "Spam veya reklam",
      assedio: "Taciz veya nefret",
      conteudo: "Uygunsuz içerik",
      golpe: "Dolandırıcılık",
      outro: "Diğer",
    },
  },
  selos: {
    verificada: "Doğrulanmış topluluk",
    detectavel: "Keşfedilebilir topluluk",
  },
  auditoria: {
    todasAsAcoes: "Tüm işlemler",
    todosOsUsuarios: "Tüm kullanıcılar",
    filtroMembros: "Üyeler",
    filtroCanais: "Kanallar",
    filtroEmojis: "Emojiler",
    filtroServidor: "Sunucu",
    titulo: "Denetim kaydı",
    porUsuario: "Kişiye göre süz",
    porAcao: "İşleme göre süz",
    vazio: "Bu süzgeçle henüz hiçbir şey kaydedilmedi.",
    motivo: "Gerekçe:",
  },
  banimentos: {
    titulo: "Sunucunun yasak listesi",
    descricao: "Burada olan yeni davetle bile giremez. Yasağı kaldırmak erişimi anında geri verir.",
    procurar: "Yasakları kullanıcı adına göre ara",
    vazioTitulo: "Yasak yok",
    vazio: "Henüz kimseyi yasaklamadın… ama gerekirse çekinme.",
    desbanir: "Yasağı kaldır",
  },
  excluir: {
    tudoVai: "{{servidor}} sunucusundaki tüm kanallar, mesajlar ve davetler {{membros}} üye için silinecek. Sonrasında kimse geri getiremez.",
    digite: "Onaylamak için {{servidor}} yaz",
    titulo: "Sunucuyu sil",
    aviso: "Bu geri alınamaz.",
  },
  emblemas: {
    apagarDescricao: "Takan herkesten kalkar. Geri alınamaz.",
    titulo: "Rozetler",
    vazio: "Henüz rozet yok.",
    novo: "Yeni rozet",
  },
  convites: {
    revogarTitulo: "Davet iptal edilsin mi?",
    revogarAcao: "İptal et",
    revogarDescricao: "{{codigo}} bağlantısı hemen çalışmaz olur. Onunla zaten girmiş olan sunucuda kalır.",
    titulo: "Davetler",
    descricao: "Bu sunucunun tüm etkin davet bağlantıları.",
    vazio: "Henüz davet oluşturulmadı.",
    revogar: "Daveti iptal et",
  },
  integracoes: {
    opcionais: "username ve avatar_url isteğe bağlıdır ve mesaj başına geçerlidir. Sınır 5 saniyede 5 mesajdır.",
    apagarDescricao: "URL hemen çalışmaz olur. Zaten gönderdiği mesajlar kanalda kalır.",
    titulo: "Entegrasyonlar",
    descricao: "Webhook, hesap gerekmeden bir kanala yazan bir adrestir. Bir derleme geçtiğinde, biri kayıt açtığında ya da bir betikten göndermek istediğin her şeyi duyurmak için işe yarar.",
    novo: "Yeni webhook",
    vazio: "Henüz webhook yok. Bir tane oluştur ve URL'yi mesajın gelmesini istediğin yere yapıştır.",
    canal: "Kanal",
    apagar: "Webhook'u sil",
    comoUsar: "Nasıl kullanılır",
    comoUsarTexto: "JSON ile bir POST gönder:",
  },
  explorar: {
    titulo: "Keşfet",
  },
  engajamento: {
    semCanal: "Sistem kanalı yok",
    titulo: "Canlandırma",
    descricao: "Yeni biri geldiğinde boş görünmemesi için sunucunun kendi başına yaptıkları.",
    sistema: "Sistem mesajları",
    boasVindas: "Biri katıldığında karşılama mesajı gönder",
    sorteio: "Aşağıda kendi metnin olmazsa cümle kurayla seçilir — hep aynısı çabuk bıktırır.",
    canalDoSistema: "Sistem mesajları kanalı",
    mensagem: "Karşılama mesajı",
    deixeVazio: "Hazır cümleler arasından çekilsin diye boş bırak",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Mesaj daha var olmadan kendi başına denetleyen süzgeçler. Sunucuyu yönetenler asla süzülmez — muaf roller de doğrudan geçer.",
    palavras: {
      titulo: "Kendi kelimelerini engelle",
      descricao: "Kimsenin yazamayacağı kelimelerin listesi.",
    },
    mencoes: {
      titulo: "Etiket spamını engelle",
      descricao: "Bir seferde çok fazla etiket içeren mesajı engeller.",
    },
    links: {
      titulo: "Bağlantıları engelle",
      descricao: "Sohbete yapıştırılan her adresi tutar.",
    },
    definir: "Ayarla",
    nomeDaRegra: "Kuralın adı",
    bloqueadas: "Engellenen kelimeler",
    digiteEnter: "Yaz ve Enter'a bas",
    comparacao: "Karşılaştırma büyük harfi, aksanı ve noktalamayı yok sayar — ve bir kelimeyi başka bir kelimenin içinde yakalamaz.",
    aPartirDe: "Kaç etiketten itibaren engellensin",
    oQueFazer: "Ne yapılsın",
    canalDoAlerta: "Uyarı kanalı",
    escolhaCanal: "Bir kanal seç",
    castigo: "Susturma (dakika)",
    isentos: "Muaf roller",
    semCargos: "Henüz rol oluşturulmadı.",
    salvarRegra: "Kuralı kaydet",
    apagar: "Kuralı sil",
    excluirTitulo: "Bu AutoMod kuralı silinsin mi?",
    excluirDescricao: "Sunucu ona göre süzmeyi anında bırakır. Yeniden oluşturabilirsin ama şu anki ayar kaybolur.",
    excluirAcao: "Kuralı sil",
  },
  cargos: {
    titulo: "Roller",
    descricao: "Roller ad, renk ve yetki verir. Listede daha yukarıda olan aşağıdakilere hükmeder — ve kimse kendi rolüne eşit ya da ondan üstün bir role dokunamaz.",
    criar: "Rol oluştur",
    vazio: "Henüz rol yok.",
    abaExibicao: "Görünüm",
    abaPermissoes: "İzinler",
    abaMembros: "Üyeler — {{quantos}}",
    everyone: "Sunucudaki herkes için geçerli. Diğer rollerin üstüne eklendiği temel budur.",
    nomeDoCargo: "Rolün adı",
    cor: "Rolün rengi",
    corDica: "Rolü olan kişinin adını üye listesinde ve sohbette boyar.",
    semCor: "Renksiz",
    corPersonalizada: "Özel renk",
    estilo: "Ad biçimi",
    segundaCor: "İkinci renk",
    segundaCorDica: "O olmadan geçiş düz renge döner — kaybolmaz.",
    limparSegundaCor: "İkinci rengi temizle",
    icone: "Simge",
    iconeDica: "Rolü olan kişinin profil kartında rolün yanında görünür.",
    exibirSeparado: "Diğer üyelerden ayrı göster",
    exibirSeparadoDica: "Rol, üye listesinde kendi bölümünü alır.",
    permitirMencionar: "Bu rolün etiketlenmesine izin ver",
    permitirMencionarDica: "Herkes, o role sahip olan herkese bildirim gönderebilecek.",
    semPoderDeConceder: "{{descricao}} (bunu vermek için bu izne sahip değilsin)",
    adicionar: "Bu role birini ekle",
    tirar: "Rolü al",
    semNinguem: "Bu role henüz kimse sahip değil.",
    apagar: "Rolü sil",
    excluirTitulo: "„{{nome}}\" rolü silinsin mi?",
    excluirDescricao: "Bu role sahip olan, onun verdiği her şeyi kaybeder. Geri alınamaz.",
    excluirAcao: "Rolü sil",
  },
  membros: {
    procurar: "Ada veya kullanıcı adına göre ara",
    membroDesde: "Üyelik tarihi",
    vazio: "Kimse bulunamadı.",
    acoesPara: "{{nome}} için işlemler",
    deCastigo: "susturma",
    tirarCastigo: "Susturmayı kaldır",
    castigo5min: "5 dakika",
    castigo1h: "1 saat",
    castigo1d: "1 gün",
    castigo1s: "1 hafta",
    expulsar: "At",
    expulsarTitulo: "{{nome}} atılsın mı?",
    expulsarDescricao: "{{servidor}} sunucusundan hemen ayrılır. Davetle geri gelebilir — atmak dönüşü engellemez.",
    banir: "Yasakla",
    banirTitulo: "{{nome}} yasaklansın mı?",
    banirDescricao: "{{servidor}} sunucusundan ayrılır ve yasağı kalkana kadar davetle bile geri gelemez.",
    motivo: "Gerekçe (isteğe bağlı)",
    motivoDica: "Denetim kaydına işlenir",
  },
  perfil: {
    titulo: "Sunucu profili",
    descricao: "Sunucun listede ve davet bağlantılarında böyle görünür.",
    icone: "Simge",
    faixa: "Üstteki afiş",
    nomeDoServidor: "Sunucu adı",
    campoDescricao: "Açıklama",
    doQueE: "Bu sunucu ne hakkında?",
    comprimido: "Yüklemeden önce sıkıştırıldı: {{economia}}",
  },
  etiqueta: {
    titulo: "Sunucu etiketi",
    descricao: "Her üyenin adının yanında görünen en fazla 4 harflik bir etiket — sohbette ve kişi listesinde. Burada bedava: takviye yok, seviye yok.",
    escolhaNome: "Bir ad seç",
    limite: "En fazla 4 karakter, harf ve rakam.",
    escolhaInsignia: "Bir rozet seç",
    voce: "Sen",
    fala1: "oynamak isteyen var mı?",
    fala2: "şu etiketime bir bak!",
    fala3: "vay, bunu nasıl aldın",
  },
  expressoes: {
    comoUsar: "Bu sunucuda herkesin kullanabileceği en fazla {{limite}} emoji ekle. Göndermek için sohbete :ad: yaz.",
    imagem: "Görsel",
    enviadoPor: "Yükleyen",
    semEmoji: "Henüz emoji yok.",
    figurinhas: "Çıkartmalar",
    enviarFigurinha: "Çıkartma yükle",
    nomeDaFigurinha: "Çıkartmanın adı",
    exemploFigurinha: "Örn.: kedicik sarılması",
    figurinhaGrande: "Çıkartma {{limite}} sınırını aşıyor.",
    deixaPraLa: "Boş ver",
    sons: "Ses panosu",
    enviarSom: "Ses yükle",
    nomeDoSom: "Sesin adı",
    semSom: "Henüz ses yok.",
    somGrande: "Ses {{limite}} sınırını aşıyor.",
    emojiRelacionado: "İlgili emoji",
    ouvir: "Dinle",
    ouvirAssim: "Böyle dinle",
    volumeDe: "{{nome}} sesi",
    volumeDica: "Sunucudaki herkes için geçerli. Herkes yine de sesleri yalnızca kendisi için kısabilir, arama panelinden.",
    falhaEnvio: "Dosya yüklenemedi.",
    excluirTitulo: "{{tipo}} „{{nome}}\" silinsin mi?",
    excluirDescricao: "Sunucudan herkes için kaybolur. Onu daha önce kullanan mesajlar olduğu gibi kalır.",
  },
  canal: {
    tipoLink: "Bağlantı",
    tipoLinkDica: "Dışarıdaki bir adrese işaret eder ve tarayıcıda açılır",
    endereco: "Adres",
    enderecoDica: "Bu kanalın götürdüğü yer. https:// ile başlamalı",
    visaoGeral: "Genel bakış",
    nome: "Kanal adı",
    topico: "Kanal konusu",
    topicoDica: "Burada ne konuşuluyor?",
    modoLento: "Her kişi aralık başına yalnızca bir mesaj gönderir. Mesajları veya kanalları yöneten doğrudan geçer.",
    visibilidade: "İçeriğin görünürlüğü",
    padrao: "Varsayılan",
    padraoDica: "Kanalın içeriği her zaman görünür.",
    spoiler: "Spoiler kanalı",
    spoilerDica: "Bu kanalı spoiler içeriyor diye işaretle; böylece sürprizler ve ağır konular biri bakmayı seçene kadar gizli kalır.",
    idade: "Yaş sınırlı kanal",
    idadeDica: "Giren kişi içeriği görmek için reşit olduğunu onaylamak zorunda.",
    bitrateDica: "64 kbps üstü, bağlantısı kötü olanları rahatsız edebilir.",
    qualidadeDeVideo: "Video kalitesi",
    automatica: "Otomatik",
    limite: "Kullanıcı sınırı — {{valor}}",
    pessoas: "{{quantos}} kişi",
    semLimite: "sınırsız",
    permissoesDescricao: "Burada bu kanalda neyin geçerli olduğunu değiştirirsin. „Devral\"da kalan, rolü izlemeye devam eder.",
    excluir: {
      titulo: "Kanalı sil",
      historico: "{{canal}} kanalının tüm geçmişi onunla birlikte gider, herkes için.",
      digite: "Onaylamak için {{canal}} yaz",
    },
  },
  moderacao: {
    titulo: "Moderatör görünümü",
    semPermissao: "Bunu görmek için „Üyeleri denetle\" iznine ihtiyacın var.",
    fecharEsc: "Kapat (Esc)",
    atividade: "Sunucudaki etkinlik",
    mensagens: "Mesajlar",
    links: "Bağlantılar",
    midia: "Medya",
    acoesNaAuditoria: "Denetim kaydındaki işlemler",
    moderacoesSofridas: "Aldığı yaptırımlar",
    permissoes: "İzinler ({{quantas}})",
    semPermissaoEspecial: "Özel izin yok.",
    conta: "Hesap",
    entrouNoServidor: "Sunucuya katıldı",
    contaCriadaEm: "Hesap oluşturulma",
    deCastigoAte: "Şu ana kadar susturulmuş",
    formaDeAdesao: "Nasıl katıldı",
    mensagem: "Mesaj",
    castigo: "Susturma",
    copiarId: "Kimliği kopyala",
    idCopiado: "Kimlik kopyalandı.",
    adicionarCargo: "Rol ekle",
    semCargos: "Oluşturulmuş rol yok",
    soEveryone: "Yalnızca @everyone.",
    voltar: "Geri",
    vazio: "Burada bir şey yok.",
    cinquenta: "En yeni 50 tanesi gösteriliyor.",
    irParaMensagem: "Mesaja git",
    precisaSerAmigo: "Konuşmak için arkadaş olmanız gerekiyor.",
    expulsarDescricao: "Sunucudan hemen ayrılır ama davetle geri gelebilir.",
    banirDescricao: "Sunucudan ayrılır ve yasağı kalkana kadar davetle bile geri gelemez.",
    castigarTitulo: "{{nome}} susturulsun mu?",
    castigoDescricao: "Sürdüğü sürece sunucudaki hiçbir kanalda yazamaz ve konuşamaz.",
    aplicarCastigo: "Susturmayı uygula",
    duracao: "Dakika cinsinden süre",
    informeDuracao: "Süreyi dakika olarak gir.",
  },
  abas: {
    pesquisar: "Ayarlarda ara",
    semResultado: "Burada o adda bir şey yok.",
    comunidade: "Topluluk",
    expressoes: "İfadeler",
    pessoas: "Kişiler",
    apps: "Uygulamalar",
    moderacao: "Denetim",
    banimentos: "Yasaklar",
  },
};
