export const servidor = {
  titulo: "Sunucu ayarları",
  auditoria: {
    titulo: "Denetim kaydı",
    porUsuario: "Kişiye göre süz",
    porAcao: "İşleme göre süz",
    vazio: "Bu süzgeçle henüz hiçbir şey kaydedilmedi.",
    motivo: "Gerekçe:",
  },
  banimentos: {
    titulo: "Sunucunun yasak listesi",
    descricao: "Burada olan yeni davetle bile giremez. Yasağı kaldırmak erişimi anında geri verir.",
    procurar: "Yasakları kullanıcı adına göre ara",
    vazioTitulo: "Yasak yok",
    vazio: "Henüz kimseyi yasaklamadın… ama gerekirse çekinme.",
    desbanir: "Yasağı kaldır",
  },
  excluir: {
    titulo: "Sunucuyu sil",
    aviso: "Bu geri alınamaz.",
  },
  emblemas: {
    titulo: "Rozetler",
    vazio: "Henüz rozet yok.",
    novo: "Yeni rozet",
  },
  convites: {
    titulo: "Davetler",
    descricao: "Bu sunucunun tüm etkin davet bağlantıları.",
    vazio: "Henüz davet oluşturulmadı.",
    revogar: "Daveti iptal et",
  },
  integracoes: {
    titulo: "Entegrasyonlar",
    descricao: "Webhook, hesap gerekmeden bir kanala yazan bir adrestir. Bir derleme geçtiğinde, biri kayıt açtığında ya da bir betikten göndermek istediğin her şeyi duyurmak için işe yarar.",
    novo: "Yeni webhook",
    vazio: "Henüz webhook yok. Bir tane oluştur ve URL'yi mesajın gelmesini istediğin yere yapıştır.",
    canal: "Kanal",
    apagar: "Webhook'u sil",
    comoUsar: "Nasıl kullanılır",
    comoUsarTexto: "JSON ile bir POST gönder. Biçim Discord'unkiyle aynı, yani hâlihazırda var olan bir betik değişiklik olmadan çalışır:",
  },
  engajamento: {
    titulo: "Canlandırma",
    descricao: "Yeni biri geldiğinde boş görünmemesi için sunucunun kendi başına yaptıkları.",
    sistema: "Sistem mesajları",
    boasVindas: "Biri katıldığında karşılama mesajı gönder",
    sorteio: "Aşağıda kendi metnin olmazsa cümle kurayla seçilir — hep aynısı çabuk bıktırır.",
    canalDoSistema: "Sistem mesajları kanalı",
    mensagem: "Karşılama mesajı",
    deixeVazio: "Hazır cümleler arasından çekilsin diye boş bırak",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Mesaj daha var olmadan kendi başına denetleyen süzgeçler. Sunucuyu yönetenler asla süzülmez — muaf roller de doğrudan geçer.",
    palavras: {
      titulo: "Kendi kelimelerini engelle",
      descricao: "Kimsenin yazamayacağı kelimelerin listesi.",
    },
    mencoes: {
      titulo: "Etiket spamını engelle",
      descricao: "Bir seferde çok fazla etiket içeren mesajı engeller.",
    },
    links: {
      titulo: "Bağlantıları engelle",
      descricao: "Sohbete yapıştırılan her adresi tutar.",
    },
    definir: "Ayarla",
    nomeDaRegra: "Kuralın adı",
    bloqueadas: "Engellenen kelimeler",
    digiteEnter: "Yaz ve Enter'a bas",
    comparacao: "Karşılaştırma büyük harfi, aksanı ve noktalamayı yok sayar — ve bir kelimeyi başka bir kelimenin içinde yakalamaz.",
    aPartirDe: "Kaç etiketten itibaren engellensin",
    oQueFazer: "Ne yapılsın",
    canalDoAlerta: "Uyarı kanalı",
    escolhaCanal: "Bir kanal seç",
    castigo: "Susturma (dakika)",
    isentos: "Muaf roller",
    semCargos: "Henüz rol oluşturulmadı.",
    salvarRegra: "Kuralı kaydet",
    apagar: "Kuralı sil",
    excluirTitulo: "Bu AutoMod kuralı silinsin mi?",
    excluirDescricao: "Sunucu ona göre süzmeyi anında bırakır. Yeniden oluşturabilirsin ama şu anki ayar kaybolur.",
    excluirAcao: "Kuralı sil",
  },
  cargos: {
    titulo: "Roller",
    descricao: "Roller ad, renk ve yetki verir. Listede daha yukarıda olan aşağıdakilere hükmeder — ve kimse kendi rolüne eşit ya da ondan üstün bir role dokunamaz.",
    criar: "Rol oluştur",
    vazio: "Henüz rol yok.",
    abaExibicao: "Görünüm",
    abaPermissoes: "İzinler",
    abaMembros: "Üyeler — {{quantos}}",
    everyone: "Sunucudaki herkes için geçerli. Diğer rollerin üstüne eklendiği temel budur.",
    nomeDoCargo: "Rolün adı",
    cor: "Rolün rengi",
    corDica: "Rolü olan kişinin adını üye listesinde ve sohbette boyar.",
    semCor: "Renksiz",
    corPersonalizada: "Özel renk",
    estilo: "Ad biçimi",
    segundaCor: "İkinci renk",
    segundaCorDica: "O olmadan geçiş düz renge döner — kaybolmaz.",
    limparSegundaCor: "İkinci rengi temizle",
    icone: "Simge",
    iconeDica: "Rolü olan kişinin profil kartında rolün yanında görünür.",
    exibirSeparado: "Diğer üyelerden ayrı göster",
    exibirSeparadoDica: "Rol, üye listesinde kendi bölümünü alır.",
    permitirMencionar: "Bu rolün etiketlenmesine izin ver",
    permitirMencionarDica: "Herkes, o role sahip olan herkese bildirim gönderebilecek.",
    semPoderDeConceder: "{{descricao}} (bunu vermek için bu izne sahip değilsin)",
    adicionar: "Bu role birini ekle",
    tirar: "Rolü al",
    semNinguem: "Bu role henüz kimse sahip değil.",
    apagar: "Rolü sil",
    excluirTitulo: "„{{nome}}\" rolü silinsin mi?",
    excluirDescricao: "Bu role sahip olan, onun verdiği her şeyi kaybeder. Geri alınamaz.",
    excluirAcao: "Rolü sil",
  },
  membros: {
    procurar: "Ada veya kullanıcı adına göre ara",
    membroDesde: "Üyelik tarihi",
    vazio: "Kimse bulunamadı.",
    acoesPara: "{{nome}} için işlemler",
    deCastigo: "susturma",
    tirarCastigo: "Susturmayı kaldır",
    castigo5min: "5 dakika",
    castigo1h: "1 saat",
    castigo1d: "1 gün",
    castigo1s: "1 hafta",
    expulsar: "At",
    expulsarTitulo: "{{nome}} atılsın mı?",
    expulsarDescricao: "{{servidor}} sunucusundan hemen ayrılır. Davetle geri gelebilir — atmak dönüşü engellemez.",
    banir: "Yasakla",
    banirTitulo: "{{nome}} yasaklansın mı?",
    banirDescricao: "{{servidor}} sunucusundan ayrılır ve yasağı kalkana kadar davetle bile geri gelemez.",
    motivo: "Gerekçe (isteğe bağlı)",
    motivoDica: "Denetim kaydına işlenir",
  },
  perfil: {
    titulo: "Sunucu profili",
    descricao: "Sunucun listede ve davet bağlantılarında böyle görünür.",
    icone: "Simge",
    faixa: "Üstteki afiş",
    nomeDoServidor: "Sunucu adı",
    campoDescricao: "Açıklama",
    doQueE: "Bu sunucu ne hakkında?",
    comprimido: "Yüklemeden önce sıkıştırıldı: {{economia}}",
  },
  etiqueta: {
    titulo: "Sunucu etiketi",
    descricao: "Her üyenin adının yanında görünen en fazla 4 harflik bir etiket — sohbette ve kişi listesinde. Burada bedava: takviye yok, seviye yok.",
    escolhaNome: "Bir ad seç",
    limite: "En fazla 4 karakter, harf ve rakam.",
    escolhaInsignia: "Bir rozet seç",
    voce: "Sen",
    fala1: "oynamak isteyen var mı?",
    fala2: "şu etiketime bir bak!",
    fala3: "vay, bunu nasıl aldın",
  },
  expressoes: {
    comoUsar: "Bu sunucuda herkesin kullanabileceği en fazla {{limite}} emoji ekle. Göndermek için sohbete :ad: yaz.",
    imagem: "Görsel",
    enviadoPor: "Yükleyen",
    semEmoji: "Henüz emoji yok.",
    figurinhas: "Çıkartmalar",
    enviarFigurinha: "Çıkartma yükle",
    nomeDaFigurinha: "Çıkartmanın adı",
    exemploFigurinha: "Örn.: kedicik sarılması",
    figurinhaGrande: "Çıkartma {{limite}} sınırını aşıyor.",
    deixaPraLa: "Boş ver",
    sons: "Ses panosu",
    enviarSom: "Ses yükle",
    nomeDoSom: "Sesin adı",
    semSom: "Henüz ses yok.",
    somGrande: "Ses {{limite}} sınırını aşıyor.",
    emojiRelacionado: "İlgili emoji",
    ouvir: "Dinle",
    ouvirAssim: "Böyle dinle",
    volumeDe: "{{nome}} sesi",
    volumeDica: "Sunucudaki herkes için geçerli. Herkes yine de sesleri yalnızca kendisi için kısabilir, arama panelinden.",
    falhaEnvio: "Dosya yüklenemedi.",
    excluirTitulo: "{{tipo}} „{{nome}}\" silinsin mi?",
    excluirDescricao: "Sunucudan herkes için kaybolur. Onu daha önce kullanan mesajlar olduğu gibi kalır.",
  },
};
