export const amizades = {
  ativosAgora: "Jetzt aktiv",
  procurando: "Mal sehen, wer da ist…",
  tudoTranquilo: "Gerade ist alles ruhig…",
  tudoTranquiloDetalhe: "Wenn du oder ein Freund einem Anruf beitritt, erscheint er hier — und du kannst mit einem Klick dazukommen.",
  emVoz: "Im Sprachkanal",
  voce: "Du",
  soVoce: "Nur du",
  pessoas: "{{quantas}} Personen",
  voltarParaChamada: "Zurück zum Anruf",
  entrarNaChamada: "Anruf beitreten",
  abrirCanal: "{{canal}} in {{servidor}} öffnen",
  mensagensDiretas: "Direktnachrichten",
  encontreConversa: "Unterhaltung finden",
  amigos: "Freunde",
  conversas: "Unterhaltungen",
  semConversas: "Noch keine Unterhaltungen. Füge einen Freund hinzu, um zu starten.",
  semConversaComEsseNome: "Keine Unterhaltung mit diesem Namen.",
  abrirMenu: "Server und Unterhaltungen öffnen",
  solicitacoes: "Nachrichtenanfragen",
  pedidos: "Anfragen",
  spam: "Spam",
  pedidosPendentes: "Offene Anfragen",
  marcadosComoSpam: "Als Spam markiert",
  aceitar: "Annehmen",
  ignorar: "Ignorieren",
  marcarSpam: "Als Spam markieren",
  semPedidos: "Keine Anfragen offen.",
  semPedidosDetalhe: "Wer nicht dein Freund ist, aber einen Server mit dir teilt, landet hier, bevor er deine Unterhaltungen erreicht.",
  semSpam: "Nichts als Spam markiert.",
  semSpamDetalhe: "Was der Spamfilter aussortiert oder was du markierst, bleibt in diesem Tab.",
  umServidorEmComum: "1 gemeinsamer Server",
  servidoresEmComum: "{{quantos}} gemeinsame Server",
  semServidoresEmComum: "Keine gemeinsamen Server",
};
