export const chamada = {
  conectando: "Verbindung zum Anruf…",
  naoEntrou: "Beitritt zum Anruf fehlgeschlagen",
  sair: "Anruf verlassen",
  sairDaVoz: "Sprachanruf verlassen",
  desconectar: "Trennen",
  voltar: "Zurück zum Anruf",
  voltarAosQuadros: "Zurück zu den Anrufkacheln",
  fecharChat: "Chat schließen",
  carregandoPrevia: "Vorschau wird geladen…",
  maisOpcoes: "Mehr Optionen",
  deVideo: "Videoanruf",
  deVoz: "Sprachanruf",
  alguem: "Jemand",
  volume: {
    entrada: "Eingangslautstärke",
    saida: "Ausgangslautstärke",
    live: "Lautstärke des Livestreams",
    liveComPorcento: "Lautstärke des Livestreams ({{porcento}} %)",
    liveSemSom: "Livestream stumm",
  },
  aparelhos: {
    entrada: "Eingabegerät",
    saida: "Ausgabegerät",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Ausgabe",
    oDoSistema: "Das des Systems",
    aDoSistema: "Die des Systems",
    semEscolhaDeSaida: "Dieser Browser lässt die Ausgabe nicht wählen — das entscheidet das System.",
    espelhar: "Meine Kamera spiegeln",
    configEntrada: "Eingabeeinstellungen",
    configSaida: "Ausgabeeinstellungen",
    configCamera: "Kameraeinstellungen",
    configAudioEVideo: "Audio- und Videoeinstellungen",
  },
  tela: {
    compartilhar: "Bildschirm teilen",
    compartilharAcao: "Teilen",
    cancelar: "Abbrechen",
    telas: "Bildschirme",
    janelas: "Fenster",
    somDoComputador: "Computerton mitnehmen",
    somDoSistema: "Systemton mitnehmen",
    configCompartilhamento: "Freigabeeinstellungen",
    mostrarSemVideo: "Personen ohne Video anzeigen",
    semFontes: "Das System hat keinen Bildschirm und kein Fenster zum Teilen geliefert.",
    pararDeCompartilhar: "Teilen beenden",
    encerrarTransmissao: "Übertragung beenden",
  },
  live: {
    etiqueta: "Live",
    etiquetaMaiuscula: "LIVE",
    assistir: "Übertragung ansehen",
    assistirPessoa: "{{nome}} ansehen",
    pararDeAssistir: "Nicht mehr ansehen",
  },
  membro: {
    mudarMeuApelido: "Meinen Spitznamen ändern",
    meuMicrofone: "Mein Mikrofon",
    ouvirChamada: "Dem Anruf zuhören",
    copiarMeuId: "Meine ID kopieren",
    idCopiado: "ID kopiert.",
    mensagem: "Nachricht",
    silenciar: "Stummschalten",
    alterarApelido: "Spitznamen ändern",
    cargos: "Rollen",
    semCargo: "Keine Rolle erstellt",
    moverPara: "Verschieben nach",
    silenciarNoServidor: "Auf dem Server stummschalten",
    desativarAudioNoServidor: "Auf dem Server taub stellen",
    desconectar: "Trennen",
    apelidoTitulo: "Dein Spitzname auf diesem Server",
    apelidoDeAlguem: "Spitzname von {{nome}}",
    apelidoCampo: "Spitzname",
    apelidoDicaPropria: "Gilt nur hier. Leer lassen, dann gilt wieder dein üblicher Name.",
    apelidoDicaDeOutro: "Gilt nur auf diesem Server. Leer lassen, um zum ursprünglichen Namen zurückzukehren.",
  },
  detalhes: {
    abrir: "Sprachdetails",
    titulo: "Sprach-Details",
    conexao: "Verbindung",
    pingMedio: "Durchschnittlicher Ping",
    ultimoPing: "Letzter Ping",
    perda: "Verlust gesendeter Pakete",
    medindo: "Wird gemessen…",
    criptografado: "Bis zum Server verschlüsselt (DTLS-SRTP)",
    explicacao: "Über 250 ms merkt man die Verzögerung im Gespräch — die Leute reden sich gegenseitig ins Wort. Paketverlust über 10 % lässt die Stimme robotisch klingen. In beiden Fällen liegt das Problem fast immer zwischen dir und dem Internet: probier ein Kabel statt WLAN, oder starte den Router neu.",
  },
  microfone: {
    bloqueado: "Mikrofon blockiert — du hörst nur zu. Erlaube den Zugriff in den Browserberechtigungen.",
    bloqueadoNoMac: "macOS blockiert das Mikrofon. Setze den Haken bei",
    caminhoNoMac: "Systemeinstellungen → Datenschutz & Sicherheit → Mikrofon",
    abrirAjustes: "Einstellungen öffnen",
    vaiReabrir: "macOS wird dich bitten, die App neu zu öffnen.",
    naoAbriu: "Mikrofon konnte nicht geöffnet werden — du hörst nur zu. Prüfe das Gerät unter Einstellungen → Sprache und Video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS hat die Bildschirmaufnahme noch nicht erlaubt. Ohne sie kommt die Freigabe schwarz heraus.",
    marque: "Setze den Haken bei",
    reabra: "unter Bildschirmaufnahme und öffne die App neu.",
  },
  ruido: {
    titulo: "Rauschunterdrückung",
    explicacao: "Nimm das Hintergrundgeräusch aus deiner Stimme. Klatsch mal oder schieb die Tastatur, während du sprichst — die anderen im Anruf hören nur dich.",
    semSuporte: "Dieser Browser führt die erweiterte Unterdrückung nicht aus. Die des Browsers gilt weiterhin, und sie ist schwächer.",
    aplicando: "Wird auf den Anruf angewendet…",
    faleParaTestar: "Sprich zum Testen",
    verdeQuandoPassa: "Grün, wenn deine Stimme durchkommt.",
    teOuvindo: "Man hört dich gerade.",
    feitoCom: "Gemacht mit",
    aquiNoAparelho: ", hier auf deinem Gerät",
    ajustes: "Einstellungen",
  },
  permissoes: {
    titulo: "macOS-Berechtigungen",
    detalhe: "macOS fragt nur einmal, danach ändert sich das nur in dessen eigenem Bereich. Hier siehst du, was gilt, und löst, was fehlt.",
    concedida: "Erteilt",
    negada: "Verweigert",
    naoPedida: "Nicht angefragt",
    permitir: "Erlauben",
    abrirAjustes: "Einstellungen öffnen",
    microfone: "Mikrofon",
    microfoneDetalhe: "In Anrufen sprechen und deinen Eingang testen.",
    camera: "Kamera",
    cameraDetalhe: "Das Video im Anruf einschalten.",
    tela: "Bildschirmaufnahme",
    telaDetalhe: "Bildschirm und Fenster teilen.",
    monitoramento: "Eingabeüberwachung",
    monitoramentoDetalhe: "Push-to-Talk auch nutzen, wenn Gravaê im Hintergrund läuft.",
  },
  jaConectado: {
    titulo: "Du bist bereits in diesem Anruf",
    trazer: "Den Anruf hierher holen",
    deixar: "So lassen",
    detalhe: "Wenn du ihn hierher holst, fliegt die andere Seite aus dem Anruf — dein Konto ist immer nur an einem Ort.",
  },
};
