export const comum = {
  carregando: "Wird geladen…",
  salvar: "Speichern",
  salvando: "Wird gespeichert…",
  descartar: "Verwerfen",
  redefinir: "Zurücksetzen",
  naoSalvo: "Du hast ungespeicherte Änderungen.",
  fechar: "Schließen",
  criar: "Erstellen",
  nome: "Name",
  emoji: "Emoji",
  previa: "Vorschau",
  cancelar: "Abbrechen",
  enviar: "Senden",
  apagar: "Löschen",
  excluir: "Löschen",
  remover: "Entfernen",
  trocar: "Ändern",
};
