export const configuracoes = {
  sair: "Abmelden",
  versoes: {
    copiar: "Zum Kopieren klicken",
    copiado: "Kopiert",
  },
  telas: {
    conta: "Mein Konto",
    privacidade: "Privatsphäre",
    conexoes: "Verbindungen",
    voz: "Audio",
    video: "Video",
    avisos: "Benachrichtigungen",
    aplicativos: "Anwendungen",
    aparencia: "Erscheinungsbild",
    batePapo: "Chat",
    acessibilidade: "Barrierefreiheit",
    idioma: "Sprache",
    aplicativo: "App herunterladen",
    atalhos: "Tastenkürzel",
    desktop: "Desktop-App",
    avancado: "Erweitert",
    servidor: "Server",
  },
  grupos: {
    conta: "Konto",
    app: "App-Einstellungen",
    desenvolvedor: "Entwickler",
    administracao: "Verwaltung",
  },
  secoes: {
    detalhesDeLogin: "Anmeldedaten",
    dispositivos: "Geräte",
    usuariosBloqueados: "Blockierte Nutzer",
    aplicativosAutorizados: "Autorisierte Apps",
    sessoes: "Sitzungen",
    amigosEDms: "Freunde und Direktnachrichten",
    compartilhamentoDeAtividade: "Aktivitätsfreigabe",
    visibilidadeDoPerfil: "Profil-Sichtbarkeit",
    exportarDados: "Daten exportieren",
    exclusaoDeDados: "Daten löschen",
    tema: "Design",
    corDeDestaque: "Akzentfarbe",
    interface: "Oberfläche",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Zoomstufe der App",
    escalaDaFonte: "Schriftgröße im Chat",
    modoStreamer: "Streaming-Privatsphäre",
    movimento: "Bewegung",
    textoEmVoz: "Sprachausgabe",
    teclado: "Tastatur",
    formatoDaHora: "Zeitformat",
    idiomaDaInterface: "Sprache der Oberfläche",
    dispositivosDeVoz: "Geräte",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Eingabemodus",
    sensibilidade: "Eingabeempfindlichkeit",
    qualidade: "Qualität",
    camera: "Kamera",
    transmissao: "Übertragung",
    exibicao: "Anzeige",
    entrada: "Eingabe",
    midia: "Medien",
    geral: "Allgemein",
    preferenciaDeMencao: "Erwähnungseinstellung",
    sons: "Töne",
  },
};
