export const conversa = {
  lista: {
    carregando: "Nachrichten werden geladen…",
    carregandoMais: "Wird geladen…",
    verMais: "Nach oben scrollen, um mehr zu sehen",
    semHistorico: "Verlauf nicht verfügbar",
    semHistoricoDetalhe: "Deine Rolle darf den Verlauf von #{{canal}} nicht lesen. Neue Nachrichten erscheinen weiterhin, solange du hier bist.",
    boasVindas: "Willkommen in #{{canal}}",
    boasVindasDetalhe: "Das ist der Anfang des Kanals #{{canal}}.",
  },
  data: {
    hoje: "Heute",
    ontem: "Gestern",
    hojeAs: "heute um {{hora}}",
    ontemAs: "gestern um {{hora}}",
  },
  digitando: {
    um: "{{nome}} schreibt gerade…",
    dois: "{{primeiro}} und {{segundo}} schreiben gerade…",
    varios: "{{quantidade}} Personen schreiben gerade…",
  },
  mensagem: {
    usou: "hat benutzt",
    fixada: "angeheftet",
    editado: "(bearbeitet)",
    ignorada: "Nachricht von jemandem, den du ignorierst.",
    mostrar: "Anzeigen",
    escPara: "Esc zum",
    cancelar: "Abbrechen",
    enterParaSalvar: "Enter zum Speichern",
    falhou: "Wurde nicht gesendet. Erneut versuchen",
    naoLidasDaqui: "Ab hier ungelesen.",
    linkCopiado: "Link kopiert.",
    idCopiado: "ID kopiert.",
    naoDeuParaCopiar: "Dein Browser hat das Kopieren nicht erlaubt.",
    apagarTitulo: "Nachricht löschen?",
    apagarDescricao: "Sie verschwindet für alle im Kanal. Das lässt sich nicht rückgängig machen.",
    apagarAcao: "Löschen",
    citacaoAnexo: "klicken, um den Anhang zu sehen",
    citacaoSumiu: "Die ursprüngliche Nachricht ist nicht mehr da.",
    reagirCom: "Mit {{emoji}} reagieren — gedrückt halten für eine Super-Reaktion",
    segureParaSuper: "{{emoji}} — gedrückt halten für eine Super-Reaktion",
  },
  acoes: {
    reagir: "Reagieren",
    responder: "Antworten",
    encaminhar: "Weiterleiten",
    favoritar: "Nachricht merken",
    tirarDosFavoritos: "Aus den Gemerkten entfernen",
    marcarNaoLida: "Als ungelesen markieren",
    copiarLink: "Nachrichtenlink kopieren",
    copiarId: "Nachrichten-ID kopieren",
    fixar: "Nachricht anheften",
    desafixar: "Lösen",
    editar: "Bearbeiten",
    apagar: "Löschen",
    mais: "Mehr",
    adicionarReacao: "Reaktion hinzufügen",
    superReagirCom: "Super-Reaktion mit {{emoji}}",
    fixarMensagem: "Nachricht anheften",
    desafixarMensagem: "Nachricht lösen",
    editarMensagem: "Nachricht bearbeiten",
    apagarMensagem: "Nachricht löschen",
  },
  mencao: {
    cargo: "Rollenerwähnung",
    pessoa: "Erwähnung",
    alguem: "jemand",
    cargoSemNome: "Rolle",
    here: "Benachrichtigt alle, die online sind",
    everyone: "Benachrichtigt den ganzen Server",
  },
  codigo: {
    copiar: "Kopieren",
    copiado: "Kopiert",
    copiarAria: "Den Code kopieren",
    copiadoAria: "Code kopiert",
  },
  caixa: {
    escrever: "Schreibe in #{{canal}}",
    escreverSemCanal: "Nachricht schreiben",
    semPermissao: "Du darfst in diesem Kanal keine Nachrichten senden",
    solteParaAnexar: "Loslassen, um anzuhängen",
    respondendoPara: "Antwort an",
    vaiNotificar: "Die Person wird benachrichtigt",
    naoVaiNotificar: "Die Person wird nicht benachrichtigt",
    ligado: "an",
    desligado: "aus",
    pararDeResponder: "Antwort verwerfen",
    mais: "Mehr",
    enviarArquivo: "Eine Datei senden",
    criarEnquete: "Umfrage erstellen",
    expressoes: "Emoji, GIF und Sticker",
    enviar: "Senden",
    aguardandoEnvio: "Warten auf den Upload",
    modoLento: "Langsamer Modus aktiv ({{tempo}})",
    modoLentoDica: "Der langsame Modus steht auf {{segundos}} s. Warte, bevor du die nächste Nachricht sendest.",
  },
  anexos: {
    enviando: "Wird hochgeladen…",
    modificar: "{{arquivo}} bearbeiten",
    remover: "{{arquivo}} entfernen",
    ver: "{{arquivo}} ansehen",
    mostrarSpoiler: "Spoiler anzeigen: {{arquivo}}",
    spoiler: "Spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Anhang bearbeiten",
    nomeDoArquivo: "Dateiname",
    descricao: "Beschreibung des Alternativtexts",
    descricaoDica: "Beschreibe dieses Medium für Screenreader",
    marcarSpoiler: "Als Spoiler markieren",
    cancelar: "Abbrechen",
    salvar: "Speichern",
  },
  cartao: {
    tocador: "Player",
    abrir: "{{destino}} öffnen",
    tocar: "{{titulo}} abspielen",
    video: "Video",
    verImagem: "Bild ansehen",
  },
  enquete: {
    titulo: "Umfrage",
    encerrada: "Umfrage beendet",
    variasRespostas: "Umfrage — mehrere Antworten",
    umVoto: "{{quantidade}} Stimme",
    votos: "{{quantidade}} Stimmen",
    umVotoNoTotal: "{{quantidade}} Stimme insgesamt",
    votosNoTotal: "{{quantidade}} Stimmen insgesamt",
    encerraEm: "endet am {{quando}}",
    encerrarAgora: "Jetzt beenden",
  },
  fixadas: {
    titulo: "Angeheftete Nachrichten",
    vazio: "In diesem Kanal ist noch nichts angeheftet… bisher.",
    desafixar: "Lösen",
    anexo: "(Anhang)",
    enquete: "(Umfrage)",
    dicaRotulo: "TIPP:",
    dica: "wer die Berechtigung „Nachrichten verwalten“ hat, kann direkt aus dem Nachrichtenmenü anheften.",
  },
  encaminhar: {
    titulo: "Nachricht weiterleiten",
    paraOnde: "Wohin?",
    semTexto: "(Nachricht ohne Text)",
    nenhumLugar: "Kein Ort mit diesem Namen.",
    canais: "Kanäle",
    conversas: "Direktnachrichten",
  },
};
