export const perfil = {
  carregando: "Wird geladen…",
  editar: "Profil bearbeiten",
  mensagem: "Nachricht",
  abrirConversa: "Unterhaltung öffnen",
  verCompleto: "Vollständiges Profil ansehen",
  convidarParaServidor: "Auf den Server einladen",
  semServidores: "Du hast keine Server",
  conviteEnviado: "Einladung an {{nome}} gesendet.",
  moderador: "In der Moderatoransicht öffnen",
  mais: "Mehr",
  ignorar: "Ignorieren",
  deixarDeIgnorar: "Nicht mehr ignorieren",
  copiarId: "Benutzer-ID kopieren",
  idCopiado: "ID kopiert.",
  conexoes: "Verbindungen",
  membroDesde: "Mitglied seit",
  sobre: "Über mich",
  cargosTitulo: "Rollen",
  visaoGeral: "Übersicht",
  amigosEmComum: "Gemeinsame Freunde ({{quantidade}})",
  servidoresEmComum: "Gemeinsame Server ({{quantidade}})",
  amizade: {
    amigo: "Befreundet",
    pedidoEnviado: "Freundschaftsanfrage gesendet",
    respondaAbaixo: "Hat dir eine Anfrage geschickt — antworte unten",
    adicionar: "Freund hinzufügen",
    teMandouPedido: "Hat dir eine Freundschaftsanfrage geschickt",
    aceitar: "Annehmen",
    desfazer: "Freundschaft beenden",
    desfazerTitulo: "{{nome}} aus deinen Freunden entfernen?",
    desfazerDescricao: "Ihr seid nicht mehr befreundet. Die private Unterhaltung bleibt im Verlauf, und du kannst die Person später wieder hinzufügen.",
    bloquear: "Blockieren",
    bloquearTitulo: "{{nome}} blockieren?",
    bloquearDescricao: "Ihr seid nicht mehr befreundet, die private Unterhaltung nimmt keine Nachrichten mehr an und die Person kann dir keine Freundschaftsanfrage mehr schicken.",
    linkCopiado: "Ihr seid nicht befreundet — der Link wurde kopiert, damit du ihn schickst.",
  },
  recado: {
    escrever: "Schreib an @{{usuario}}",
    enviar: "Senden",
    enviada: "Nachricht gesendet",
    falhou: "Konnte nicht gesendet werden. Versuch es in der Unterhaltung.",
  },
  cartao: {
    trocarFaixa: "Kartenbanner ändern",
    trocarFaixaCurto: "Banner ändern",
    trocarFoto: "Profilbild ändern",
    trocarFotoCurto: "Bild ändern",
    suaEtiqueta: "Dein Namensschild",
    editarEtiqueta: "Zum Bearbeiten deines Namensschilds klicken",
    conteAlgo: "Erzähl etwas über dich",
    adicionarStatus: "Status hinzufügen",
    adicionarDescricao: "Zum Hinzufügen einer Beschreibung klicken",
    cargo: "Rolle",
    cargos: "Rollen",
    cargosCom: "Rollen — {{quantidade}}",
    tirarCargo: "Rolle {{cargo}} entfernen",
  },
  cargos: {
    adicionar: "Rolle hinzufügen",
    procurar: "Nach einer Rolle suchen",
  },
  etiqueta: {
    escolher: "Server-Namensschild wählen",
    nenhuma: "Kein Server-Namensschild",
    semEtiqueta: "Keiner deiner Server hat ein Namensschild",
  },
  emblemas: {
    doServidor: "Abzeichen dieses Servers",
    limite: "Du kannst bis zu {{quantidade}} Abzeichen tragen.",
  },
  nota: {
    vazia: "Zum Notieren klicken",
    rotulo: "Notiz (nur du siehst sie)",
    adicionar: "Notiz hinzufügen (nur für dich sichtbar)",
  },
  status: {
    titulo: "Status",
    definir: "Deinen Status festlegen",
    escolherEmoji: "Emoji wählen",
    tirarEmoji: "Emoji entfernen",
    oQuePensa: "Woran denkst du?",
    limparAgora: "Status jetzt löschen",
    naoLimpar: "Nicht löschen",
    limpar30m: "In 30 Minuten löschen",
    limpar1h: "In 1 Stunde löschen",
    limpar4h: "In 4 Stunden löschen",
    limparHoje: "Heute löschen",
    limparAmanha: "Morgen löschen",
    comHora: "{{prazo}} um {{hora}}",
  },
  presenca: {
    disponivel: "Verfügbar",
    ausente: "Abwesend",
    naoPerturbar: "Bitte nicht stören",
    naoPerturbarDetalhe: "Du bekommst keine Hinweise auf neue Nachrichten",
    invisivel: "Unsichtbar",
    invisivelDetalhe: "Für andere erscheinst du offline",
  },
  menu: {
    mudarDeConta: "Konto wechseln",
    gerenciarContas: "Konten verwalten",
  },
  editor: {
    decoracao: "Avatar-Dekoration ändern",
    naoSalvo: "Vergiss nicht, deine Änderungen zu speichern!",
    principal: "Hauptprofil",
  },
};
