export const servidor = {
  comunidade: {
    ativa: "Die Community ist offen",
    ativaDesde: "Offen seit {{quando}}",
    membrosAgora: "{{quantos}} Mitglieder",
    criarParaMim: "Einen für mich anlegen",
    canalDeRegras: "Regelkanal",
    canalDeRegrasDetalhe: "Der Ort mit den Regeln, die alle lesen, bevor sie schreiben.",
    canalDeAvisos: "Kanal für Community-Ansagen",
    canalDeAvisosDetalhe: "Dorthin schicken wir, was sich hier ändert — nur für die Verwaltung.",
    canalDeSeguranca: "Kanal für Sicherheitsmeldungen",
    canalDeSegurancaDetalhe: "Hier bekommt die Moderation, was die Filter aufgegriffen haben.",
    idiomaPrincipal: "Hauptsprache",
    idiomaPrincipalDetalhe: "Die Sprache, in der das meiste gesprochen wird.",
    semIdioma: "Keine Sprache gewählt",
    semCanal: "Kein Kanal",
    finalTitulo: "Fast geschafft",
    finalDetalhe: "Schau vor dem Öffnen, was sich für Neuankömmlinge ändert.",
    confereRegras: "Wer reinkommt, sieht zuerst den Regelkanal.",
    confereEveryone: "@everyone und @here nutzen nur Leute mit einer Rolle.",
    confereMencoes: "Alle auf einmal anzupingen braucht jetzt eine Erlaubnis.",
    concordo: "Ich stimme zu und verstehe",
    concordoDetalhe: "Du bestätigst, dass sich die Community an unsere Richtlinien hält.",
    proximo: "Weiter",
    terminar: "Einrichtung abschließen",
    visaoGeral: "Überblick",
    visaoGeralDetalhe: "Die Kanäle, über die die Community mit Neuen spricht.",
    seguranca: "Sicherheit",
    segurancaDetalhe: "Die Bremsen, die Spam und harte Inhalte aufhalten.",
    habilitada: "Community ist aktiv.",
    falhou: "Die Community ließ sich nicht aktivieren.",
    titulo: "Community",
    ilustracao: "Sprechblasen",
    convite: "Baust du eine Community auf?",
    conviteDetalhe: "Mach eine Community daraus und bekomm die Werkzeuge für einen großen Ort: Regelkanal, Ansagen von uns und Filter, die von selbst moderieren.",
    contagem: "{{membros}} von {{minimo}} Mitgliedern",
    faltam: "Es fehlen {{quantos}} bis zur Eröffnung.",
    prontoParaAbrir: "Es kann losgehen.",
    habilitar: "Community aktivieren",
    vantagemCrescer: "Wachsen",
    vantagemCrescerDetalhe: "Die Community kann sich für Entdecken bewerben, und wer das Thema sucht, findet euch.",
    vantagemModerar: "Moderieren",
    vantagemModerarDetalhe: "Bestätigte E-Mail verlangen, Medien filtern und AutoMod auf einen Schlag anschalten.",
    vantagemAvisos: "Bescheid wissen",
    vantagemAvisosDetalhe: "Wir schicken Änderungen an alle, die hier verwalten — in einen Kanal nur für euch.",
    assistenteTitulo: "Lass uns deine Community einrichten.",
    passoSeguranca: "Sicherheitsprüfungen",
    passoBasico: "Grundeinrichtung",
    passoFinal: "Letzter Schliff",
    seguraTitulo: "Halte die Community sicher",
    seguraDetalhe: "Große Communitys ziehen Spam an. Diese zwei Bremsen sind standardmäßig an; du kannst sie später ausschalten.",
    emailVerificado: "Bestätigte E-Mail verlangen",
    emailVerificadoDetalhe: "Wer seine E-Mail noch nicht bestätigt hat, schreibt nicht. Wer eine Rolle hat, kommt durch.",
    filtroDeMidia: "Explizite Medien filtern",
    filtroDeMidiaDetalhe: "Bilder und Videos kommen verdeckt an und zeigen sich erst, wenn jemand hinschauen will.",
    basicoTitulo: "Bereite das Nötigste vor",
    basicoDetalhe: "Sag, in welchem Kanal die Regeln stehen und wohin unsere Ansagen gehen. Ohne Auswahl lege ich beide an.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} Befehle",
    previa: "So sieht die Karte aus",
    trocarIcone: "Symbol wechseln",
    tirarCapa: "Titelbild entfernen",
    heroComunidades: "Irgendwo redet jemand über das, was du magst",
    heroComunidadesDetalhe: "Communitys, aufgemacht von Leuten, die hier unterwegs sind. Geh rein, lies mit, und bleib, wenn es dir gefällt.",
    emDestaque: "Hervorgehoben",
    todasAsComunidades: "Die übrigen",
    heroTitulo: "Was nimmt eure Truppe heute?",
    heroDetalhe: "Bots für Musik, Spiele und Moderation, gebaut von Leuten, die auch hier sind. Such einen aus, und er kommt auf den Server.",
    novidades: "Frisch dazugekommen",
    todosOsApps: "Die übrigen",
    lojaTitulo: "Seite der App",
    lojaDetalhe: "Das sieht in Entdecken, wer sie noch nicht kennt.",
    capa: "Titelbild",
    capaDetalhe: "Das breite Bild oben auf der Seite. 1280 × 720 passt gut.",
    trocarCapa: "Titelbild wechseln",
    categorias: "Kategorien",
    categoriasDetalhe: "Bis zu {{quantas}}. Danach wird in Entdecken gestöbert.",
    idiomas: "Sprachen",
    idiomasDetalhe: "Bis zu {{quantos}}. In welchen Sprachen die App antwortet.",
    termos: "Nutzungsbedingungen",
    politica: "Datenschutzerklärung",
    politicas: "Richtlinien",
    servidorDeSuporte: "Support-Server",
    servidorDeSuporteDetalhe: "Dorthin geht, wer Hilfe mit der App braucht.",
    semServidor: "Keiner",
    emQuantosServidores: "Auf wie vielen Servern",
    categoria: {
      GAMES: "Spiele",
      MUSICA: "Musik",
      MODERACAO: "Moderation",
      PRODUTIVIDADE: "Produktivität",
      SOCIAL: "Sozial",
      UTILIDADES: "Werkzeuge",
      ARTE_E_CRIACAO: "Kunst und Kreatives",
      EDUCACAO: "Bildung",
      OUTRA: "Sonstiges",
    },
    appIndisponivel: "App nicht verfügbar",
    voltarParaExplorar: "Zurück zu Entdecken",
    adicionarApp: "App hinzufügen",
    copiarLink: "Link kopieren",
    denunciarApp: "App melden",
    copiarIdDoApp: "App-ID kopieren",
    visaoGeral: "Überblick",
    comandos: "Befehle",
    permissoes: "Berechtigungen",
    semPermissoes: "Diese App verlangt keine Berechtigungen.",
    avisoDePermissoes: "Sie kommt mit einer eigenen Rolle. Die Berechtigungen kannst du danach in den Community-Einstellungen → Rollen ändern.",
    servidoresEmComum: "Gemeinsame Communitys",
    umServidorEmComum: "1 Community",
    quantosServidoresEmComum: "{{quantos}} Communitys",
    feitoPor: "Gemacht von",
    publicadoEm: "Veröffentlicht am",
    denunciarNome: "{{nome}} melden",
    denunciaDetalhe: "Die Meldung geht an das Gravaê-Team. Wer die App gemacht hat, erfährt nicht, dass du es warst.",
    denunciaFalhou: "Die Meldung konnte nicht gesendet werden.",
    umMembro: "1 Mitglied",
    semDescricao: "Keine Beschreibung.",
    adicionar: "Hinzufügen",
    jaEstaAqui: "Du bist schon hier",
    entrando: "Trete bei…",
    entrar: "Beitreten",
    comunidadePublica: "Öffentliche Community",
    online: "{{quantos}} online",
    membros: "{{quantos}} Mitglieder",
    abrirComunidade: "Community öffnen",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Servereinstellungen",
  novasMensagens: "Neue Nachrichten",
  menu: {
    silenciar: "Community stummschalten",
    reativar: "Community wieder aktivieren",
    porQuinze: "Für 15 Minuten",
    porMeiaHora: "Für 30 Minuten",
    porTresHoras: "Für 3 Stunden",
    porTresDias: "Für 3 Tage",
    porUmaHora: "Für 1 Stunde",
    porOitoHoras: "Für 8 Stunden",
    porUmDia: "Für 24 Stunden",
    ateReativar: "Bis ich es wieder einschalte",
    notificacoes: "Benachrichtigungseinstellungen",
    padrao: "Standard verwenden",
    todas: "Alle Nachrichten",
    soMencoes: "Nur Erwähnungen",
    nada: "Nichts",
    ocultarSilenciados: "Stummgeschaltete Kanäle ausblenden",
    denunciar: "Community melden",
    marcarLida: "Als gelesen markieren",
    convidar: "Mitglieder einladen",
    editarPerfil: "Community-Profil bearbeiten",
    configuracoes: "Community-Einstellungen",
    sair: "Community verlassen",
    sairTitulo: "{{nome}} verlassen?",
    sairDescricao: "Du brauchst eine neue Einladung, um zurückzukommen.",
    copiarId: "Community-ID kopieren",
    idCopiado: "ID kopiert.",
  },
  convite: {
    cartaoTitulo: "Du wurdest in eine Community eingeladen",
    indisponivel: "Einladung nicht verfügbar",
    indisponivelDetalhe: "Sie ist abgelaufen, aufgebraucht, oder wer sie erstellt hat, hat sie gelöscht.",
    entrar: "Der Community beitreten",
    chamado: "Du wurdest eingeladen zu",
    aceitarComo: "Als {{nome}} annehmen",
    abrir: "Community öffnen",
    recusar: "Nein, danke",
  },
  pasta: {
    silenciarTodas: "Communitys stummschalten",
    reativarTodas: "Communitys wieder aktivieren",
    mostrarSilenciados: "Stummgeschaltete Kanäle zeigen",
    notificacoesDaComunidade: "Benachrichtigungseinstellungen",
    silenciarEveryone: "@everyone und @here stummschalten",
    permitirEveryone: "@everyone und @here erlauben",
    silenciarCargos: "Rollenerwähnungen stummschalten",
    permitirCargos: "Rollenerwähnungen erlauben",
    dicaDaCor: "Schreibe eine Farbe (hex, rgb(), hsl() oder Name) oder nutze den Wähler.",
    mostrarIcone: "Symbol zeigen, wenn geschlossen",
    dicaDoIcone: "Geschlossen zeigt sie das Symbol statt der Server.",
    icone: "Ordnersymbol",
    excluir: "Ordner löschen",
    icones: {
      pasta: "Ordner",
      estrela: "Favorit",
      coracao: "Herz",
      salvar: "Speichern",
      jogo: "Gamepad",
      escudo: "Schild",
      nota: "Musiknote",
    },
    marcarLida: "Ordner als gelesen markieren",
    configuracoes: "Ordnereinstellungen",
    desfazer: "Ordner auflösen",
    titulo: "Ordner",
    nome: "Name",
    semNome: "Ohne Namen",
    cor: "Farbe",
    semCor: "Keine Farbe",
    salvar: "Speichern",
  },
  denuncia: {
    titulo: "{{nome}} melden",
    descricao: "Die Meldung geht an das Gravaê-Team. Erzähl uns, was passiert ist.",
    motivo: "Grund",
    detalhes: "Details (optional)",
    enviar: "Meldung senden",
    enviada: "Meldung gesendet. Danke.",
    motivos: {
      spam: "Spam oder Werbung",
      assedio: "Belästigung oder Hass",
      conteudo: "Unangemessener Inhalt",
      golpe: "Betrug",
      outro: "Sonstiges",
    },
  },
  selos: {
    verificada: "Verifizierte Community",
    detectavel: "Auffindbare Community",
  },
  auditoria: {
    todasAsAcoes: "Alle Aktionen",
    todosOsUsuarios: "Alle Personen",
    filtroMembros: "Mitglieder",
    filtroCanais: "Kanäle",
    filtroEmojis: "Emojis",
    filtroServidor: "Server",
    titulo: "Audit-Log",
    porUsuario: "Nach Person filtern",
    porAcao: "Nach Aktion filtern",
    vazio: "Mit diesem Filter ist noch nichts protokolliert.",
    motivo: "Grund:",
  },
  banimentos: {
    titulo: "Bannliste des Servers",
    descricao: "Wer hier steht, kommt auch mit neuer Einladung nicht rein. Entbannen gibt den Zugang sofort zurück.",
    procurar: "Banns nach Benutzernamen durchsuchen",
    vazioTitulo: "Keine Banns",
    vazio: "Du hast noch niemanden gebannt … aber falls es nötig wird, zögere nicht.",
    desbanir: "Entbannen",
  },
  excluir: {
    tudoVai: "Alle Kanäle, Nachrichten und Einladungen von {{servidor}} werden für die {{membros}} Mitglieder gelöscht. Danach kann sie niemand mehr zurückholen.",
    digite: "Tippe {{servidor}}, um zu bestätigen",
    titulo: "Server löschen",
    aviso: "Das lässt sich nicht rückgängig machen.",
  },
  emblemas: {
    apagarDescricao: "Es wird allen abgenommen, die es tragen. Das lässt sich nicht rückgängig machen.",
    titulo: "Abzeichen",
    vazio: "Noch keine Abzeichen.",
    novo: "Neues Abzeichen",
  },
  convites: {
    revogarTitulo: "Einladung widerrufen?",
    revogarAcao: "Widerrufen",
    revogarDescricao: "Der Link {{codigo}} funktioniert sofort nicht mehr. Wer schon darüber beigetreten ist, bleibt auf dem Server.",
    titulo: "Einladungen",
    descricao: "Alle aktiven Einladungslinks dieses Servers.",
    vazio: "Noch keine Einladung erstellt.",
    revogar: "Einladung widerrufen",
  },
  integracoes: {
    opcionais: "username und avatar_url sind optional und gelten pro Nachricht. Das Limit sind 5 Nachrichten alle 5 Sekunden.",
    apagarDescricao: "Die URL funktioniert sofort nicht mehr. Die bereits gesendeten Nachrichten bleiben im Kanal.",
    titulo: "Integrationen",
    descricao: "Ein Webhook ist eine Adresse, die in einen Kanal postet, ohne ein Konto zu brauchen. Praktisch, um zu melden, dass ein Build durchgelaufen ist, dass jemand ein Ticket aufgemacht hat, oder was du sonst aus einem Skript schicken willst.",
    novo: "Neuer Webhook",
    vazio: "Noch keine Webhooks. Erstell einen und füge die URL dort ein, wo die Nachricht herkommen soll.",
    canal: "Kanal",
    apagar: "Webhook löschen",
    comoUsar: "So geht's",
    comoUsarTexto: "Schick ein POST mit JSON:",
  },
  explorar: {
    titulo: "Entdecken",
  },
  engajamento: {
    semCanal: "Kein Systemkanal",
    titulo: "Belebung",
    descricao: "Was der Server von allein tut, damit er nicht leer wirkt, wenn jemand Neues kommt.",
    sistema: "Systemnachrichten",
    boasVindas: "Eine Willkommensnachricht schicken, wenn jemand beitritt",
    sorteio: "Ohne eigenen Text darunter wird der Satz ausgelost — immer derselbe nutzt sich schnell ab.",
    canalDoSistema: "Kanal für Systemnachrichten",
    mensagem: "Willkommensnachricht",
    deixeVazio: "Leer lassen, um aus den fertigen Sätzen auszulosen",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filter, die von allein moderieren, bevor die Nachricht überhaupt existiert. Wer den Server verwaltet, wird nie gefiltert — und ausgenommene Rollen gehen direkt durch.",
    palavras: {
      titulo: "Eigene Wörter blockieren",
      descricao: "Deine Liste von Wörtern, die niemand schreiben darf.",
    },
    mencoes: {
      titulo: "Erwähnungs-Spam blockieren",
      descricao: "Blockiert eine Nachricht mit zu vielen Erwähnungen auf einmal.",
    },
    links: {
      titulo: "Links blockieren",
      descricao: "Fängt jede im Chat eingefügte Adresse ab.",
    },
    definir: "Einrichten",
    nomeDaRegra: "Name der Regel",
    bloqueadas: "Blockierte Wörter",
    digiteEnter: "Tippen und Enter drücken",
    comparacao: "Der Vergleich ignoriert Groß- und Kleinschreibung, Akzente und Satzzeichen — und greift nicht bei einem Wort in einem anderen („Arsch\" blockiert nicht „Arschloch\"-freie Wörter wie „Marsch\").",
    aPartirDe: "Ab wie vielen Erwähnungen blockieren",
    oQueFazer: "Was tun",
    canalDoAlerta: "Kanal für den Hinweis",
    escolhaCanal: "Wähle einen Kanal",
    castigo: "Auszeit (Minuten)",
    isentos: "Ausgenommene Rollen",
    semCargos: "Noch keine Rollen erstellt.",
    salvarRegra: "Regel speichern",
    apagar: "Regel löschen",
    excluirTitulo: "Diese AutoMod-Regel löschen?",
    excluirDescricao: "Der Server filtert sofort nicht mehr danach. Du kannst sie neu anlegen, aber die aktuelle Einstellung geht verloren.",
    excluirAcao: "Regel löschen",
  },
  cargos: {
    titulo: "Rollen",
    descricao: "Rollen geben Namen, Farbe und Rechte. Wer weiter oben in der Liste steht, hat Vorrang vor denen darunter — und niemand fasst eine Rolle an, die gleich hoch oder höher als die eigene ist.",
    criar: "Rolle erstellen",
    vazio: "Noch keine Rollen.",
    abaExibicao: "Darstellung",
    abaPermissoes: "Berechtigungen",
    abaMembros: "Mitglieder — {{quantos}}",
    everyone: "Gilt für alle auf dem Server. Sie ist die Grundlage, auf der die anderen Rollen aufbauen.",
    nomeDoCargo: "Name der Rolle",
    cor: "Farbe der Rolle",
    corDica: "Färbt den Namen derer, die die Rolle haben, in der Mitgliederliste und im Chat.",
    semCor: "Ohne Farbe",
    corPersonalizada: "Eigene Farbe",
    estilo: "Namensstil",
    segundaCor: "Zweite Farbe",
    segundaCorDica: "Ohne sie fällt der Verlauf auf eine Volltonfarbe zurück — er verschwindet nicht.",
    limparSegundaCor: "Zweite Farbe löschen",
    icone: "Symbol",
    iconeDica: "Erscheint neben der Rolle auf der Profilkarte derer, die sie haben.",
    exibirSeparado: "Getrennt von den anderen Mitgliedern anzeigen",
    exibirSeparadoDica: "Die Rolle bekommt einen eigenen Abschnitt in der Mitgliederliste.",
    permitirMencionar: "Erwähnen dieser Rolle erlauben",
    permitirMencionarDica: "Jeder kann dann alle benachrichtigen, die die Rolle haben.",
    semPoderDeConceder: "{{descricao}} (du hast dieses Recht nicht, um es zu vergeben)",
    adicionar: "Jemanden zu dieser Rolle hinzufügen",
    tirar: "Rolle entziehen",
    semNinguem: "Noch niemand hat diese Rolle.",
    apagar: "Rolle löschen",
    excluirTitulo: "Die Rolle „{{nome}}\" löschen?",
    excluirDescricao: "Wer diese Rolle hat, verliert alles, was sie gab. Das lässt sich nicht rückgängig machen.",
    excluirAcao: "Rolle löschen",
  },
  membros: {
    procurar: "Nach Name oder Benutzername suchen",
    membroDesde: "Mitglied seit",
    vazio: "Niemanden gefunden.",
    acoesPara: "Aktionen für {{nome}}",
    deCastigo: "in Auszeit",
    tirarCastigo: "Auszeit beenden",
    castigo5min: "5 Minuten",
    castigo1h: "1 Stunde",
    castigo1d: "1 Tag",
    castigo1s: "1 Woche",
    expulsar: "Rauswerfen",
    expulsarTitulo: "{{nome}} rauswerfen?",
    expulsarDescricao: "verlässt {{servidor}} sofort. Kann mit einer Einladung wiederkommen — Rauswerfen verhindert die Rückkehr nicht.",
    banir: "Bannen",
    banirTitulo: "{{nome}} bannen?",
    banirDescricao: "verlässt {{servidor}} und kommt nicht zurück, auch nicht mit Einladung, bis der Bann aufgehoben wird.",
    motivo: "Grund (optional)",
    motivoDica: "Wird im Audit-Log festgehalten",
  },
  perfil: {
    titulo: "Serverprofil",
    descricao: "So erscheint dein Server in der Liste und in Einladungslinks.",
    icone: "Symbol",
    faixa: "Banner oben",
    nomeDoServidor: "Servername",
    campoDescricao: "Beschreibung",
    doQueE: "Worum geht es auf diesem Server?",
    comprimido: "Vor dem Hochladen komprimiert: {{economia}}",
  },
  etiqueta: {
    titulo: "Server-Tag",
    descricao: "Ein Kürzel aus bis zu 4 Buchstaben, das neben dem Namen jedes Mitglieds erscheint — im Chat und in der Personenliste. Hier ist es gratis: ohne Boost, ohne Level.",
    escolhaNome: "Wähle einen Namen",
    limite: "Höchstens 4 Zeichen, Buchstaben und Zahlen.",
    escolhaInsignia: "Wähle ein Abzeichen",
    voce: "Du",
    fala1: "hat jemand Lust zu zocken?",
    fala2: "schau dir mal mein Tag an!",
    fala3: "krass, wie hast du das bekommen",
  },
  expressoes: {
    comoUsar: "Füge bis zu {{limite}} Emojis hinzu, die alle auf diesem Server benutzen können. Tippe :name: im Chat, um eins zu schicken.",
    imagem: "Bild",
    enviadoPor: "Hochgeladen von",
    semEmoji: "Noch keine Emojis.",
    figurinhas: "Sticker",
    enviarFigurinha: "Sticker hochladen",
    nomeDaFigurinha: "Name des Stickers",
    exemploFigurinha: "Z. B. Kätzchen-Umarmung",
    figurinhaGrande: "Der Sticker ist größer als {{limite}}.",
    deixaPraLa: "Lass mal",
    sons: "Soundboard",
    enviarSom: "Sound hochladen",
    nomeDoSom: "Name des Sounds",
    semSom: "Noch keine Sounds.",
    somGrande: "Der Sound ist größer als {{limite}}.",
    emojiRelacionado: "Zugehöriges Emoji",
    ouvir: "Anhören",
    ouvirAssim: "So anhören",
    volumeDe: "Lautstärke von {{nome}}",
    volumeDica: "Gilt für alle auf dem Server. Jede Person kann die Sounds trotzdem nur für sich leiser stellen, im Anrufpanel.",
    falhaEnvio: "Datei konnte nicht hochgeladen werden.",
    excluirTitulo: "{{tipo}} „{{nome}}\" löschen?",
    excluirDescricao: "Verschwindet für alle vom Server. Nachrichten, die es schon benutzt haben, bleiben, wie sie sind.",
  },
  canal: {
    tipoLink: "Link",
    tipoLinkDica: "Zeigt auf eine Adresse draußen und öffnet im Browser",
    endereco: "Adresse",
    enderecoDica: "Wohin dieser Kanal führt. Muss mit https:// anfangen",
    visaoGeral: "Übersicht",
    nome: "Name des Kanals",
    topico: "Thema des Kanals",
    topicoDica: "Worum geht es hier?",
    modoLento: "Jede Person schickt nur eine Nachricht pro Intervall. Wer Nachrichten oder Kanäle verwaltet, geht direkt durch.",
    visibilidade: "Sichtbarkeit des Inhalts",
    padrao: "Standard",
    padraoDica: "Der Inhalt des Kanals ist immer sichtbar.",
    spoiler: "Spoiler-Kanal",
    spoilerDica: "Markiere diesen Kanal als Spoiler-Kanal, damit Wendungen und schwere Themen verborgen bleiben, bis jemand sie sehen will.",
    idade: "Kanal mit Altersbeschränkung",
    idadeDica: "Wer hereinkommt, muss bestätigen, volljährig zu sein, um den Inhalt zu sehen.",
    bitrateDica: "Über 64 kbps kann Leute mit schlechter Verbindung stören.",
    qualidadeDeVideo: "Videoqualität",
    automatica: "Automatisch",
    limite: "Nutzerlimit — {{valor}}",
    pessoas: "{{quantos}} Personen",
    semLimite: "ohne Limit",
    permissoesDescricao: "Hier änderst du, was in diesem Kanal gilt. Was auf „erben\" bleibt, folgt weiter der Rolle.",
    excluir: {
      titulo: "Kanal löschen",
      historico: "Der ganze Verlauf von {{canal}} geht mit — für alle.",
      digite: "Tippe {{canal}}, um zu bestätigen",
    },
  },
  moderacao: {
    titulo: "Moderatoransicht",
    semPermissao: "Du brauchst die Berechtigung „Mitglieder moderieren\", um das zu sehen.",
    fecharEsc: "Schließen (Esc)",
    atividade: "Aktivität auf dem Server",
    mensagens: "Nachrichten",
    links: "Links",
    midia: "Medien",
    acoesNaAuditoria: "Aktionen im Audit-Log",
    moderacoesSofridas: "Erhaltene Moderationen",
    permissoes: "Berechtigungen ({{quantas}})",
    semPermissaoEspecial: "Keine besonderen Berechtigungen.",
    conta: "Konto",
    entrouNoServidor: "Beigetreten am",
    contaCriadaEm: "Konto erstellt am",
    deCastigoAte: "In Auszeit bis",
    formaDeAdesao: "Wie beigetreten",
    mensagem: "Nachricht",
    castigo: "Auszeit",
    copiarId: "ID kopieren",
    idCopiado: "ID kopiert.",
    adicionarCargo: "Rolle hinzufügen",
    semCargos: "Keine Rolle erstellt",
    soEveryone: "Nur @everyone.",
    voltar: "Zurück",
    vazio: "Hier ist nichts.",
    cinquenta: "Zeigt die 50 neuesten.",
    irParaMensagem: "Zur Nachricht",
    precisaSerAmigo: "Ihr müsst befreundet sein, um zu schreiben.",
    expulsarDescricao: "Verlässt den Server sofort, kann aber mit einer Einladung wiederkommen.",
    banirDescricao: "Verlässt den Server und kommt nicht zurück, auch nicht mit Einladung, bis der Bann aufgehoben wird.",
    castigarTitulo: "{{nome}} eine Auszeit geben?",
    castigoDescricao: "Solange sie läuft, schreibt und spricht die Person in keinem Kanal des Servers.",
    aplicarCastigo: "Auszeit anwenden",
    duracao: "Dauer in Minuten",
    informeDuracao: "Gib die Dauer in Minuten an.",
  },
  abas: {
    pesquisar: "In den Einstellungen suchen",
    semResultado: "Hier gibt es nichts mit diesem Namen.",
    comunidade: "Community",
    expressoes: "Ausdrücke",
    pessoas: "Leute",
    apps: "Apps",
    moderacao: "Moderation",
    banimentos: "Banns",
  },
};
