export const servidor = {
  titulo: "Servereinstellungen",
  auditoria: {
    titulo: "Audit-Log",
    porUsuario: "Nach Person filtern",
    porAcao: "Nach Aktion filtern",
    vazio: "Mit diesem Filter ist noch nichts protokolliert.",
    motivo: "Grund:",
  },
  banimentos: {
    titulo: "Bannliste des Servers",
    descricao: "Wer hier steht, kommt auch mit neuer Einladung nicht rein. Entbannen gibt den Zugang sofort zurück.",
    procurar: "Banns nach Benutzernamen durchsuchen",
    vazioTitulo: "Keine Banns",
    vazio: "Du hast noch niemanden gebannt … aber falls es nötig wird, zögere nicht.",
    desbanir: "Entbannen",
  },
  excluir: {
    tudoVai: "Alle Kanäle, Nachrichten und Einladungen von {{servidor}} werden für die {{membros}} Mitglieder gelöscht. Danach kann sie niemand mehr zurückholen.",
    digite: "Tippe {{servidor}}, um zu bestätigen",
    titulo: "Server löschen",
    aviso: "Das lässt sich nicht rückgängig machen.",
  },
  emblemas: {
    titulo: "Abzeichen",
    vazio: "Noch keine Abzeichen.",
    novo: "Neues Abzeichen",
  },
  convites: {
    titulo: "Einladungen",
    descricao: "Alle aktiven Einladungslinks dieses Servers.",
    vazio: "Noch keine Einladung erstellt.",
    revogar: "Einladung widerrufen",
  },
  integracoes: {
    titulo: "Integrationen",
    descricao: "Ein Webhook ist eine Adresse, die in einen Kanal postet, ohne ein Konto zu brauchen. Praktisch, um zu melden, dass ein Build durchgelaufen ist, dass jemand ein Ticket aufgemacht hat, oder was du sonst aus einem Skript schicken willst.",
    novo: "Neuer Webhook",
    vazio: "Noch keine Webhooks. Erstell einen und füge die URL dort ein, wo die Nachricht herkommen soll.",
    canal: "Kanal",
    apagar: "Webhook löschen",
    comoUsar: "So geht's",
    comoUsarTexto: "Schick ein POST mit JSON. Das Format ist dasselbe wie bei Discord, ein Skript von dort funktioniert also unverändert:",
  },
  engajamento: {
    titulo: "Belebung",
    descricao: "Was der Server von allein tut, damit er nicht leer wirkt, wenn jemand Neues kommt.",
    sistema: "Systemnachrichten",
    boasVindas: "Eine Willkommensnachricht schicken, wenn jemand beitritt",
    sorteio: "Ohne eigenen Text darunter wird der Satz ausgelost — immer derselbe nutzt sich schnell ab.",
    canalDoSistema: "Kanal für Systemnachrichten",
    mensagem: "Willkommensnachricht",
    deixeVazio: "Leer lassen, um aus den fertigen Sätzen auszulosen",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filter, die von allein moderieren, bevor die Nachricht überhaupt existiert. Wer den Server verwaltet, wird nie gefiltert — und ausgenommene Rollen gehen direkt durch.",
    palavras: {
      titulo: "Eigene Wörter blockieren",
      descricao: "Deine Liste von Wörtern, die niemand schreiben darf.",
    },
    mencoes: {
      titulo: "Erwähnungs-Spam blockieren",
      descricao: "Blockiert eine Nachricht mit zu vielen Erwähnungen auf einmal.",
    },
    links: {
      titulo: "Links blockieren",
      descricao: "Fängt jede im Chat eingefügte Adresse ab.",
    },
    definir: "Einrichten",
    nomeDaRegra: "Name der Regel",
    bloqueadas: "Blockierte Wörter",
    digiteEnter: "Tippen und Enter drücken",
    comparacao: "Der Vergleich ignoriert Groß- und Kleinschreibung, Akzente und Satzzeichen — und greift nicht bei einem Wort in einem anderen („Arsch\" blockiert nicht „Arschloch\"-freie Wörter wie „Marsch\").",
    aPartirDe: "Ab wie vielen Erwähnungen blockieren",
    oQueFazer: "Was tun",
    canalDoAlerta: "Kanal für den Hinweis",
    escolhaCanal: "Wähle einen Kanal",
    castigo: "Auszeit (Minuten)",
    isentos: "Ausgenommene Rollen",
    semCargos: "Noch keine Rollen erstellt.",
    salvarRegra: "Regel speichern",
    apagar: "Regel löschen",
    excluirTitulo: "Diese AutoMod-Regel löschen?",
    excluirDescricao: "Der Server filtert sofort nicht mehr danach. Du kannst sie neu anlegen, aber die aktuelle Einstellung geht verloren.",
    excluirAcao: "Regel löschen",
  },
  cargos: {
    titulo: "Rollen",
    descricao: "Rollen geben Namen, Farbe und Rechte. Wer weiter oben in der Liste steht, hat Vorrang vor denen darunter — und niemand fasst eine Rolle an, die gleich hoch oder höher als die eigene ist.",
    criar: "Rolle erstellen",
    vazio: "Noch keine Rollen.",
    abaExibicao: "Darstellung",
    abaPermissoes: "Berechtigungen",
    abaMembros: "Mitglieder — {{quantos}}",
    everyone: "Gilt für alle auf dem Server. Sie ist die Grundlage, auf der die anderen Rollen aufbauen.",
    nomeDoCargo: "Name der Rolle",
    cor: "Farbe der Rolle",
    corDica: "Färbt den Namen derer, die die Rolle haben, in der Mitgliederliste und im Chat.",
    semCor: "Ohne Farbe",
    corPersonalizada: "Eigene Farbe",
    estilo: "Namensstil",
    segundaCor: "Zweite Farbe",
    segundaCorDica: "Ohne sie fällt der Verlauf auf eine Volltonfarbe zurück — er verschwindet nicht.",
    limparSegundaCor: "Zweite Farbe löschen",
    icone: "Symbol",
    iconeDica: "Erscheint neben der Rolle auf der Profilkarte derer, die sie haben.",
    exibirSeparado: "Getrennt von den anderen Mitgliedern anzeigen",
    exibirSeparadoDica: "Die Rolle bekommt einen eigenen Abschnitt in der Mitgliederliste.",
    permitirMencionar: "Erwähnen dieser Rolle erlauben",
    permitirMencionarDica: "Jeder kann dann alle benachrichtigen, die die Rolle haben.",
    semPoderDeConceder: "{{descricao}} (du hast dieses Recht nicht, um es zu vergeben)",
    adicionar: "Jemanden zu dieser Rolle hinzufügen",
    tirar: "Rolle entziehen",
    semNinguem: "Noch niemand hat diese Rolle.",
    apagar: "Rolle löschen",
    excluirTitulo: "Die Rolle „{{nome}}\" löschen?",
    excluirDescricao: "Wer diese Rolle hat, verliert alles, was sie gab. Das lässt sich nicht rückgängig machen.",
    excluirAcao: "Rolle löschen",
  },
  membros: {
    procurar: "Nach Name oder Benutzername suchen",
    membroDesde: "Mitglied seit",
    vazio: "Niemanden gefunden.",
    acoesPara: "Aktionen für {{nome}}",
    deCastigo: "in Auszeit",
    tirarCastigo: "Auszeit beenden",
    castigo5min: "5 Minuten",
    castigo1h: "1 Stunde",
    castigo1d: "1 Tag",
    castigo1s: "1 Woche",
    expulsar: "Rauswerfen",
    expulsarTitulo: "{{nome}} rauswerfen?",
    expulsarDescricao: "verlässt {{servidor}} sofort. Kann mit einer Einladung wiederkommen — Rauswerfen verhindert die Rückkehr nicht.",
    banir: "Bannen",
    banirTitulo: "{{nome}} bannen?",
    banirDescricao: "verlässt {{servidor}} und kommt nicht zurück, auch nicht mit Einladung, bis der Bann aufgehoben wird.",
    motivo: "Grund (optional)",
    motivoDica: "Wird im Audit-Log festgehalten",
  },
  perfil: {
    titulo: "Serverprofil",
    descricao: "So erscheint dein Server in der Liste und in Einladungslinks.",
    icone: "Symbol",
    faixa: "Banner oben",
    nomeDoServidor: "Servername",
    campoDescricao: "Beschreibung",
    doQueE: "Worum geht es auf diesem Server?",
    comprimido: "Vor dem Hochladen komprimiert: {{economia}}",
  },
  etiqueta: {
    titulo: "Server-Tag",
    descricao: "Ein Kürzel aus bis zu 4 Buchstaben, das neben dem Namen jedes Mitglieds erscheint — im Chat und in der Personenliste. Hier ist es gratis: ohne Boost, ohne Level.",
    escolhaNome: "Wähle einen Namen",
    limite: "Höchstens 4 Zeichen, Buchstaben und Zahlen.",
    escolhaInsignia: "Wähle ein Abzeichen",
    voce: "Du",
    fala1: "hat jemand Lust zu zocken?",
    fala2: "schau dir mal mein Tag an!",
    fala3: "krass, wie hast du das bekommen",
  },
  expressoes: {
    comoUsar: "Füge bis zu {{limite}} Emojis hinzu, die alle auf diesem Server benutzen können. Tippe :name: im Chat, um eins zu schicken.",
    imagem: "Bild",
    enviadoPor: "Hochgeladen von",
    semEmoji: "Noch keine Emojis.",
    figurinhas: "Sticker",
    enviarFigurinha: "Sticker hochladen",
    nomeDaFigurinha: "Name des Stickers",
    exemploFigurinha: "Z. B. Kätzchen-Umarmung",
    figurinhaGrande: "Der Sticker ist größer als {{limite}}.",
    deixaPraLa: "Lass mal",
    sons: "Soundboard",
    enviarSom: "Sound hochladen",
    nomeDoSom: "Name des Sounds",
    semSom: "Noch keine Sounds.",
    somGrande: "Der Sound ist größer als {{limite}}.",
    emojiRelacionado: "Zugehöriges Emoji",
    ouvir: "Anhören",
    ouvirAssim: "So anhören",
    volumeDe: "Lautstärke von {{nome}}",
    volumeDica: "Gilt für alle auf dem Server. Jede Person kann die Sounds trotzdem nur für sich leiser stellen, im Anrufpanel.",
    falhaEnvio: "Datei konnte nicht hochgeladen werden.",
    excluirTitulo: "{{tipo}} „{{nome}}\" löschen?",
    excluirDescricao: "Verschwindet für alle vom Server. Nachrichten, die es schon benutzt haben, bleiben, wie sie sind.",
  },
  canal: {
    visaoGeral: "Übersicht",
    nome: "Name des Kanals",
    topico: "Thema des Kanals",
    topicoDica: "Worum geht es hier?",
    modoLento: "Jede Person schickt nur eine Nachricht pro Intervall. Wer Nachrichten oder Kanäle verwaltet, geht direkt durch.",
    visibilidade: "Sichtbarkeit des Inhalts",
    padrao: "Standard",
    padraoDica: "Der Inhalt des Kanals ist immer sichtbar.",
    spoiler: "Spoiler-Kanal",
    spoilerDica: "Markiere diesen Kanal als Spoiler-Kanal, damit Wendungen und schwere Themen verborgen bleiben, bis jemand sie sehen will.",
    idade: "Kanal mit Altersbeschränkung",
    idadeDica: "Wer hereinkommt, muss bestätigen, volljährig zu sein, um den Inhalt zu sehen.",
    bitrateDica: "Über 64 kbps kann Leute mit schlechter Verbindung stören.",
    qualidadeDeVideo: "Videoqualität",
    automatica: "Automatisch",
    limite: "Nutzerlimit — {{valor}}",
    pessoas: "{{quantos}} Personen",
    semLimite: "ohne Limit",
    permissoesDescricao: "Hier änderst du, was in diesem Kanal gilt. Was auf „erben\" bleibt, folgt weiter der Rolle.",
    excluir: {
      titulo: "Kanal löschen",
      historico: "Der ganze Verlauf von {{canal}} geht mit — für alle.",
      digite: "Tippe {{canal}}, um zu bestätigen",
    },
  },
  moderacao: {
    titulo: "Moderatoransicht",
    semPermissao: "Du brauchst die Berechtigung „Mitglieder moderieren\", um das zu sehen.",
    fecharEsc: "Schließen (Esc)",
    atividade: "Aktivität auf dem Server",
    mensagens: "Nachrichten",
    links: "Links",
    midia: "Medien",
    acoesNaAuditoria: "Aktionen im Audit-Log",
    moderacoesSofridas: "Erhaltene Moderationen",
    permissoes: "Berechtigungen ({{quantas}})",
    semPermissaoEspecial: "Keine besonderen Berechtigungen.",
    conta: "Konto",
    entrouNoServidor: "Beigetreten am",
    contaCriadaEm: "Konto erstellt am",
    deCastigoAte: "In Auszeit bis",
    formaDeAdesao: "Wie beigetreten",
    mensagem: "Nachricht",
    castigo: "Auszeit",
    copiarId: "ID kopieren",
    idCopiado: "ID kopiert.",
    adicionarCargo: "Rolle hinzufügen",
    semCargos: "Keine Rolle erstellt",
    soEveryone: "Nur @everyone.",
    voltar: "Zurück",
    vazio: "Hier ist nichts.",
    cinquenta: "Zeigt die 50 neuesten.",
    irParaMensagem: "Zur Nachricht",
    precisaSerAmigo: "Ihr müsst befreundet sein, um zu schreiben.",
    expulsarDescricao: "Verlässt den Server sofort, kann aber mit einer Einladung wiederkommen.",
    banirDescricao: "Verlässt den Server und kommt nicht zurück, auch nicht mit Einladung, bis der Bann aufgehoben wird.",
    castigarTitulo: "{{nome}} eine Auszeit geben?",
    castigoDescricao: "Solange sie läuft, schreibt und spricht die Person in keinem Kanal des Servers.",
    aplicarCastigo: "Auszeit anwenden",
    duracao: "Dauer in Minuten",
    informeDuracao: "Gib die Dauer in Minuten an.",
  },
};
