export const chamada = {
  conectando: "Yhdistetään puheluun…",
  naoEntrou: "Puheluun ei päästy",
  sair: "Poistu puhelusta",
  sairDaVoz: "Poistu äänipuhelusta",
  desconectar: "Katkaise yhteys",
  voltar: "Takaisin puheluun",
  voltarAosQuadros: "Takaisin puhelun ruutuihin",
  fecharChat: "Sulje keskustelu",
  carregandoPrevia: "Ladataan esikatselua…",
  maisOpcoes: "Lisää",
  deVideo: "Videopuhelu",
  deVoz: "Äänipuhelu",
  alguem: "Joku",
  volume: {
    entrada: "Tulon äänenvoimakkuus",
    saida: "Lähdön äänenvoimakkuus",
    live: "Lähetyksen äänenvoimakkuus",
    liveComPorcento: "Lähetyksen äänenvoimakkuus ({{porcento}} %)",
    liveSemSom: "Lähetys mykistetty",
  },
  aparelhos: {
    entrada: "Tulolaite",
    saida: "Lähtölaite",
    camera: "Kamera",
    microfone: "Mikrofoni",
    saidaCurto: "Lähtö",
    oDoSistema: "Järjestelmän oletus",
    aDoSistema: "Järjestelmän oletus",
    semEscolhaDeSaida: "Tämä selain ei anna valita lähtöä — järjestelmä päättää.",
    espelhar: "Peilaa kamerani",
    configEntrada: "Tulon asetukset",
    configSaida: "Lähdön asetukset",
    configCamera: "Kameran asetukset",
    configAudioEVideo: "Äänen ja videon asetukset",
  },
  tela: {
    compartilhar: "Jaa näyttö",
    compartilharAcao: "Jaa",
    cancelar: "Peruuta",
    telas: "Näytöt",
    janelas: "Ikkunat",
    somDoComputador: "Ota tietokoneen ääni mukaan",
    somDoSistema: "Ota järjestelmän ääni mukaan",
    configCompartilhamento: "Jakamisen asetukset",
    mostrarSemVideo: "Näytä ne, joilla ei ole videota",
    semFontes: "Järjestelmä ei palauttanut yhtään näyttöä tai ikkunaa jaettavaksi.",
    pararDeCompartilhar: "Lopeta jakaminen",
    encerrarTransmissao: "Lopeta lähetys",
  },
  live: {
    etiqueta: "Suorana",
    etiquetaMaiuscula: "SUORANA",
    assistir: "Katso lähetystä",
    assistirPessoa: "Katso käyttäjää {{nome}}",
    pararDeAssistir: "Lopeta katsominen",
  },
  membro: {
    mudarMeuApelido: "Vaihda lempinimeni",
    meuMicrofone: "Mikrofonini",
    ouvirChamada: "Kuuntele puhelua",
    copiarMeuId: "Kopioi tunnisteeni",
    idCopiado: "Tunniste kopioitu.",
    mensagem: "Viesti",
    silenciar: "Mykistä",
    alterarApelido: "Vaihda lempinimi",
    cargos: "Roolit",
    semCargo: "Yhtään roolia ei ole luotu",
    moverPara: "Siirrä kohteeseen",
    silenciarNoServidor: "Mykistä ääni palvelimella",
    desativarAudioNoServidor: "Poista ääni käytöstä palvelimella",
    desconectar: "Katkaise yhteys",
    apelidoTitulo: "Lempinimesi tällä palvelimella",
    apelidoDeAlguem: "Käyttäjän {{nome}} lempinimi",
    apelidoCampo: "Lempinimi",
    apelidoDicaPropria: "Voimassa vain täällä. Jätä tyhjäksi, niin tavallinen nimesi palaa.",
    apelidoDicaDeOutro: "Voimassa vain tällä palvelimella. Jätä tyhjäksi palataksesi alkuperäiseen nimeen.",
  },
  detalhes: {
    abrir: "Äänen tiedot",
    titulo: "Äänen tiedot",
    conexao: "Yhteys",
    pingMedio: "Keskimääräinen ping",
    ultimoPing: "Viimeisin ping",
    perda: "Lähetettyjen pakettien häviö",
    medindo: "Mitataan…",
    criptografado: "Salattu palvelimelle asti (DTLS-SRTP)",
    explicacao: "Yli 250 ms:n viive kuuluu keskustelussa — ihmiset alkavat puhua toistensa päälle. Yli 10 %:n pakettihäviö tekee äänestä robottimaisen. Kummassakin tapauksessa ongelma on lähes aina sinun ja internetin välissä: kokeile kaapelia wifin sijaan tai käynnistä reititin uudelleen.",
  },
  microfone: {
    bloqueado: "Mikrofoni on estetty — kuuntelet vain. Salli käyttö selaimen käyttöoikeuksista.",
    bloqueadoNoMac: "macOS estää mikrofonin. Rastita",
    caminhoNoMac: "Järjestelmäasetukset → Tietosuoja ja turvallisuus → Mikrofoni",
    abrirAjustes: "Avaa asetukset",
    vaiReabrir: "macOS pyytää avaamaan sovelluksen uudelleen.",
    naoAbriu: "Mikrofonia ei voitu avata — kuuntelet vain. Tarkista laite kohdasta Asetukset → Ääni ja video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS ei ole vielä sallinut näytön tallennusta. Ilman sitä jako tulee mustana.",
    marque: "Rastita",
    reabra: "kohdassa Näytön tallennus ja avaa sovellus uudelleen.",
    jaMarcado: "Jos se on jo rastitettu, käyttöoikeus vanheni viime päivityksessä: poista rasti, laita se uudelleen ja avaa sovellus uudestaan.",
  },
  ruido: {
    titulo: "Melunvaimennus",
    explicacao: "Poista taustaääni äänestäsi. Kokeile taputtaa tai vetää näppäimistöä puhuessasi — puhelussa olevat kuulevat vain sinut.",
    semSuporte: "Tämä selain ei aja edistynyttä vaimennusta. Selaimen oma on yhä voimassa, ja se on heikompi.",
    aplicando: "Otetaan käyttöön puhelussa…",
    faleParaTestar: "Puhu testataksesi",
    verdeQuandoPassa: "Vihreä, kun äänesi menee läpi.",
    teOuvindo: "Sinut kuullaan juuri nyt.",
    feitoCom: "Tehty tekniikalla",
    aquiNoAparelho: ", täällä omalla laitteellasi",
    ajustes: "Asetukset",
  },
  permissoes: {
    titulo: "macOS-käyttöoikeudet",
    detalhe: "macOS kysyy vain kerran, ja sen jälkeen se muuttuu vain sen omassa paneelissa. Täällä näet, mikä on voimassa, ja ratkaiset puuttuvan.",
    concedida: "Myönnetty",
    negada: "Evätty",
    naoPedida: "Ei pyydetty",
    permitir: "Salli",
    abrirAjustes: "Avaa asetukset",
    microfone: "Mikrofoni",
    microfoneDetalhe: "Puhuminen puheluissa ja tulon testaaminen.",
    camera: "Kamera",
    cameraDetalhe: "Videon käynnistäminen puhelussa.",
    tela: "Näytön tallennus",
    telaDetalhe: "Näytön ja ikkunoiden jakaminen.",
    monitoramento: "Tulon valvonta",
    monitoramentoDetalhe: "Paina-ja-puhu myös silloin, kun Gravaê on taustalla.",
  },
  jaConectado: {
    titulo: "Olet jo tässä puhelussa",
    trazer: "Tuo puhelu tänne",
    deixar: "Anna olla",
    detalhe: "Jos tuot sen tänne, toinen pää putoaa puhelusta — tilisi on yhdessä paikassa kerrallaan.",
  },
};
