export const configuracoes = {
  efeitos: {
    titulo: "Osoittimen tehosteet",
    detalhe: "Jälki ja kipinät piirretään sovelluksen päälle. Ne alkavat pois päältä ja sammuvat itsestään, jos pyysit vähemmän liikettä.",
    rastro: "Osoittimen jälki",
    rastroDetalhe: "Viiva, joka seuraa osoitinta ja haalistuu takana.",
    faisca: "Kipinä napsautuksesta",
    faiscaDetalhe: "Lyhyitä viivoja, jotka lentävät napsautuskohdasta.",
    cor: "Väri",
    espessura: "Paksuus",
    comprimento: "Pituus",
    tamanho: "Koko",
    quantidade: "Määrä",
  },
  email: {
    verificarTitulo: "Vahvista sähköpostisi",
    verificarDetalhe: "Osa yhteisöistä päästää kirjoittamaan vain vahvistaneet. Yksi klikkaus riittää.",
    enviar: "Lähetä linkki",
    enviado: "Katso postilaatikkoa. Linkki kestää vuorokauden.",
    falhou: "Sähköpostia ei saatu lähetettyä.",
    confirmado: "Sähköposti vahvistettu",
    confirmadoDetalhe: "Valmista. Nyt kirjoitat jokaisessa yhteisössä, joka sitä vaatii.",
    linkIncompleto: "Vajaa linkki",
    linkIncompletoDetalhe: "Osoitteesta puuttuu koodi. Avaa linkki suoraan sähköpostista.",
    confirmando: "Vahvistetaan…",
    expirou: "Tämä linkki on jo käytetty tai vanhentunut.",
    irParaOApp: "Sovellukseen",
  },
  tema: {
    indisponivel: "Teema ei ole saatavilla",
    indisponivelDetalhe: "Julkaisija poisti sen, tai linkki on väärä.",
    indisponivelLinha: "Teema ei ole saatavilla. Julkaisija poisti sen, tai linkki on väärä.",
    importar: "Tuo teema",
    importarCurto: "Tuo",
    importarDetalhe: "Tämä korvaa nykyisen teemasi. Voit muokata sitä jälkeenpäin kohdassa Asetukset > Ulkoasu > Teemastudio.",
    porAutor: "tekijä {{autor}}",
    umaCorTrocada: "1 vaihdettu väri",
    coresTrocadas: "{{quantas}} vaihdettua väriä",
    avisoDeCss: "Tämä teema tuo mukanaan tekijänsä CSS:n, ja CSS ylettyy näytön joka nurkkaan. Tuo vain sellaisilta, joihin luotat.",
    soCores: "Tämä teema vaihtaa vain värit. Ei ulkopuolista CSS:ää.",
    aplicar: "Käytä",
    previaSemMotor: "Esikatselu ei aja moottoria. Asenna nähdäksesi sen.",
    motorAnimado: "{{motor}} animoituna",
  },
  sair: "Kirjaudu ulos",
  versoes: {
    termos: "Käyttöehdot",
    privacidade: "Tietosuojakäytäntö",
    copiar: "Kopioi napsauttamalla",
    copiado: "Kopioitu",
  },
  telas: {
    conta: "Oma tili",
    privacidade: "Yksityisyys",
    conexoes: "Yhteydet",
    voz: "Ääni",
    video: "Video",
    avisos: "Ilmoitukset",
    aplicativos: "Sovellukset",
    aparencia: "Ulkoasu",
    batePapo: "Keskustelu",
    acessibilidade: "Saavutettavuus",
    idioma: "Kieli",
    aplicativo: "Lataa sovellus",
    atalhos: "Pikanäppäimet",
    desktop: "Työpöytäsovellus",
    avancado: "Lisäasetukset",
    servidor: "Palvelin",
    comunicado: "Järjestelmätiedote",
    denuncias: "Raportit",
    publicacoes: "Julkaisut",
  },
  grupos: {
    conta: "Tili",
    app: "Sovelluksen asetukset",
    desenvolvedor: "Kehittäjä",
    administracao: "Hallinta",
  },
  secoes: {
    detalhesDeLogin: "Kirjautumistiedot",
    dispositivos: "Laitteet",
    usuariosBloqueados: "Estetyt käyttäjät",
    aplicativosAutorizados: "Valtuutetut sovellukset",
    sessoes: "Istunnot",
    amigosEDms: "Kaverit ja yksityisviestit",
    compartilhamentoDeAtividade: "Toiminnan jakaminen",
    visibilidadeDoPerfil: "Profiilin näkyvyys",
    exportarDados: "Vie tiedot",
    exclusaoDeDados: "Poista tiedot",
    tema: "Teema",
    corDeDestaque: "Korostusväri",
    interface: "Käyttöliittymä",
    listaDeCanais: "Kanavaluettelo",
    zoomDoApp: "Sovelluksen zoomaustaso",
    escalaDaFonte: "Keskustelun fonttikoko",
    modoStreamer: "Yksityisyys lähetyksessä",
    cursores: "Osoittimet",
    movimento: "Liike",
    textoEmVoz: "Teksti puheeksi",
    teclado: "Näppäimistö",
    formatoDaHora: "Ajan muoto",
    idiomaDaInterface: "Käyttöliittymän kieli",
    dispositivosDeVoz: "Laitteet",
    testeDoMicrofone: "Mikrofonitesti",
    modoDeEntrada: "Syöttötila",
    sensibilidade: "Syötön herkkyys",
    qualidade: "Laatu",
    camera: "Kamera",
    transmissao: "Lähetys",
    exibicao: "Näyttö",
    entrada: "Syöttö",
    midia: "Media",
    geral: "Yleiset",
    preferenciaDeMencao: "Mainintojen asetus",
    sons: "Äänet",
  },
};
