export const configuracoes = {
  efeitos: {
    titulo: "Osoittimen tehosteet",
    detalhe: "Jälki ja kipinät piirretään sovelluksen päälle. Ne alkavat pois päältä ja sammuvat itsestään, jos pyysit vähemmän liikettä.",
    rastro: "Osoittimen jälki",
    rastroDetalhe: "Viiva, joka seuraa osoitinta ja haalistuu takana.",
    faisca: "Kipinä napsautuksesta",
    faiscaDetalhe: "Lyhyitä viivoja, jotka lentävät napsautuskohdasta.",
    cor: "Väri",
    espessura: "Paksuus",
    comprimento: "Pituus",
    tamanho: "Koko",
    quantidade: "Määrä",
  },
  email: {
    verificarTitulo: "Vahvista sähköpostisi",
    verificarDetalhe: "Osa yhteisöistä päästää kirjoittamaan vain vahvistaneet. Yksi klikkaus riittää.",
    enviar: "Lähetä linkki",
    enviado: "Katso postilaatikkoa. Linkki kestää vuorokauden.",
    falhou: "Sähköpostia ei saatu lähetettyä.",
    confirmado: "Sähköposti vahvistettu",
    confirmadoDetalhe: "Valmista. Nyt kirjoitat jokaisessa yhteisössä, joka sitä vaatii.",
    linkIncompleto: "Vajaa linkki",
    linkIncompletoDetalhe: "Osoitteesta puuttuu koodi. Avaa linkki suoraan sähköpostista.",
    confirmando: "Vahvistetaan…",
    expirou: "Tämä linkki on jo käytetty tai vanhentunut.",
    irParaOApp: "Sovellukseen",
  },
  tema: {
    indisponivel: "Teema ei ole saatavilla",
    indisponivelDetalhe: "Julkaisija poisti sen, tai linkki on väärä.",
    indisponivelLinha: "Teema ei ole saatavilla. Julkaisija poisti sen, tai linkki on väärä.",
    importar: "Tuo teema",
    importarCurto: "Tuo",
    importarDetalhe: "Tämä korvaa nykyisen teemasi. Voit muokata sitä jälkeenpäin kohdassa Asetukset > Ulkoasu > Teemastudio.",
    porAutor: "tekijä {{autor}}",
    umaCorTrocada: "1 vaihdettu väri",
    coresTrocadas: "{{quantas}} vaihdettua väriä",
    avisoDeCss: "Tämä teema tuo mukanaan tekijänsä CSS:n, ja CSS ylettyy näytön joka nurkkaan. Tuo vain sellaisilta, joihin luotat.",
    soCores: "Tämä teema vaihtaa vain värit. Ei ulkopuolista CSS:ää.",
    verCss: "Näytä CSS",
    esconderCss: "Piilota CSS",
    aplicar: "Käytä",
    previaSemMotor: "Esikatselu ei aja moottoria. Asenna nähdäksesi sen.",
    motorAnimado: "{{motor}} animoituna",
  },
  sair: "Kirjaudu ulos",
  versoes: {
    termos: "Käyttöehdot",
    privacidade: "Tietosuojakäytäntö",
    copiar: "Kopioi napsauttamalla",
    copiado: "Kopioitu",
  },
  subscription: {
    seePlans: "Katso tilaukset",
    upgradeSubtitle: "Isommat rajat ja omat ominaisuudet kirjoittamiseen, tiedostoihin ja lähetyksiin.",
    perMonth: "kuukaudessa",
    perYear: "vuodessa",
    save: "Säästä {{percent}} %",
    howToPay: "Miten haluat maksaa?",
    legal: "Voit pyytää hyvitystä 7 päivän kuluessa maksusta. Maksun käsittelee Stripe; emme koskaan näe korttisi numeroa.",
    compare: "Ilmainen vs. Infinity",
    featureColumn: "Ominaisuus",
    freeColumn: "Ilmainen",
    messageRow: "Viestin merkkiraja",
    attachmentRow: "Lähetettävän tiedoston koko",
    screenRow: "Videon laatu",
    megabytesValue: "{{value}} Mt",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Sinulla on jo Infinity {{date}} asti.",
    upsell: "Nosta rajaa Infinityllä",
    screenUpsell: "Parempi laatu Infinityllä",
    free: "Käytät ilmaista tasoa.",
    activeUntil: "Infinity voimassa {{date}} asti.",
    renews: "Uusiutuu automaattisesti {{date}}.",
    endsAt: "Tilaus on peruttu ja päättyy {{date}}.",
    pastDue: "Viimeisin veloitus epäonnistui. Päivitä korttisi, jotta Infinity säilyy.",
    waiting: "Vahvistetaan maksua…",
    subscribe: "Tilaa",
    monthly: "Kuukausittain",
    yearly: "Vuosittain",
    automatic: "Kortti, uusiutuu automaattisesti",
    pass: "Maksa vain jakso (Pix tai kortti)",
    manage: "Hallitse maksua",
    refund: "Pyydä hyvitystä",
    refundDetail: "Voit perua 7 päivän kuluessa maksusta: {{amount}}, {{date}} asti.",
    refundConfirm: "Pyydetäänkö hyvitys?",
    refundConfirmDetail: "Rahat palautetaan samalle maksutavalle ja Infinity päättyy heti.",
    refunded: "Hyvitystä pyydetty.",
    unavailable: "Tilaukset eivät ole vielä saatavilla.",
    success: "Maksu vastaanotettu. Kiitos!",
    canceled: "Maksu peruttu.",
    error: "Jokin meni vikaan. Yritä uudelleen.",
    no: "Ei",
    tagRow: "Oma käyttäjätunniste",
    guildProfilesRow: "Yhteisökohtaiset profiilit",
    badgeRow: "Profiilimerkki",
    communitiesRow: "Yhteisöt",
    savedRow: "Tallennetut viestit",
    animatedEmojiRow: "Animoidut emojit",
    expressionsRow: "Emojit ja tarrat kaikkialla",
    animatedProfileRow: "Animoidut profiilikuvat ja bannerit",
    earlyAccessRow: "Uudet ominaisuudet ensimmäisenä",
    themesRow: "Omat teemat",
  },
  telas: {
    subscription: "Infinity",
    conta: "Oma tili",
    privacidade: "Yksityisyys",
    conexoes: "Yhteydet",
    voz: "Ääni",
    video: "Video",
    avisos: "Ilmoitukset",
    aplicativos: "Sovellukset",
    aparencia: "Ulkoasu",
    batePapo: "Keskustelu",
    acessibilidade: "Saavutettavuus",
    idioma: "Kieli",
    aplicativo: "Lataa sovellus",
    atalhos: "Pikanäppäimet",
    desktop: "Työpöytäsovellus",
    avancado: "Lisäasetukset",
    servidor: "Palvelin",
    comunicado: "Järjestelmätiedote",
    denuncias: "Raportit",
    publicacoes: "Julkaisut",
  },
  grupos: {
    conta: "Tili",
    app: "Sovelluksen asetukset",
    desenvolvedor: "Kehittäjä",
    administracao: "Hallinta",
  },
  secoes: {
    detalhesDeLogin: "Kirjautumistiedot",
    dispositivos: "Laitteet",
    usuariosBloqueados: "Estetyt käyttäjät",
    aplicativosAutorizados: "Valtuutetut sovellukset",
    sessoes: "Istunnot",
    amigosEDms: "Kaverit ja yksityisviestit",
    compartilhamentoDeAtividade: "Toiminnan jakaminen",
    visibilidadeDoPerfil: "Profiilin näkyvyys",
    exportarDados: "Vie tiedot",
    exclusaoDeDados: "Poista tiedot",
    tema: "Teema",
    corDeDestaque: "Korostusväri",
    interface: "Käyttöliittymä",
    listaDeCanais: "Kanavaluettelo",
    zoomDoApp: "Sovelluksen zoomaustaso",
    escalaDaFonte: "Keskustelun fonttikoko",
    modoStreamer: "Yksityisyys lähetyksessä",
    cursores: "Osoittimet",
    movimento: "Liike",
    textoEmVoz: "Teksti puheeksi",
    teclado: "Näppäimistö",
    formatoDaHora: "Ajan muoto",
    idiomaDaInterface: "Käyttöliittymän kieli",
    dispositivosDeVoz: "Laitteet",
    testeDoMicrofone: "Mikrofonitesti",
    modoDeEntrada: "Syöttötila",
    sensibilidade: "Syötön herkkyys",
    qualidade: "Laatu",
    camera: "Kamera",
    transmissao: "Lähetys",
    exibicao: "Näyttö",
    entrada: "Syöttö",
    midia: "Media",
    geral: "Yleiset",
    preferenciaDeMencao: "Mainintojen asetus",
    sons: "Äänet",
  },
};
