export const configuracoes = {
  telas: {
    conta: "Oma tili",
    privacidade: "Yksityisyys",
    conexoes: "Yhteydet",
    voz: "Ääni",
    video: "Video",
    avisos: "Ilmoitukset",
    aplicativos: "Sovellukset",
    aparencia: "Ulkoasu",
    batePapo: "Keskustelu",
    acessibilidade: "Saavutettavuus",
    idioma: "Kieli",
    aplicativo: "Lataa sovellus",
    servidor: "Palvelin",
  },
  grupos: {
    conta: "Tili",
    app: "Sovelluksen asetukset",
    desenvolvedor: "Kehittäjä",
    administracao: "Hallinta",
  },
  secoes: {
    detalhesDeLogin: "Kirjautumistiedot",
    dispositivos: "Laitteet",
    usuariosBloqueados: "Estetyt käyttäjät",
    aplicativosAutorizados: "Valtuutetut sovellukset",
    sessoes: "Istunnot",
    amigosEDms: "Kaverit ja yksityisviestit",
    compartilhamentoDeAtividade: "Toiminnan jakaminen",
    visibilidadeDoPerfil: "Profiilin näkyvyys",
    exportarDados: "Vie tiedot",
    exclusaoDeDados: "Poista tiedot",
    tema: "Teema",
    corDeDestaque: "Korostusväri",
    interface: "Käyttöliittymä",
    listaDeCanais: "Kanavaluettelo",
    zoomDoApp: "Sovelluksen zoomaustaso",
    escalaDaFonte: "Keskustelun fonttikoko",
    modoStreamer: "Yksityisyys lähetyksessä",
    movimento: "Liike",
    textoEmVoz: "Teksti puheeksi",
    teclado: "Näppäimistö",
    formatoDaHora: "Ajan muoto",
    idiomaDaInterface: "Käyttöliittymän kieli",
    dispositivosDeVoz: "Laitteet",
    testeDoMicrofone: "Mikrofonitesti",
    modoDeEntrada: "Syöttötila",
    sensibilidade: "Syötön herkkyys",
    qualidade: "Laatu",
    camera: "Kamera",
    transmissao: "Lähetys",
    exibicao: "Näyttö",
    entrada: "Syöttö",
    midia: "Media",
    geral: "Yleiset",
    preferenciaDeMencao: "Mainintojen asetus",
    sons: "Äänet",
  },
};
