export const conversa = {
  lista: {
    carregando: "Ladataan viestejä…",
    carregandoMais: "Ladataan…",
    verMais: "Vieritä ylös nähdäksesi lisää",
    semHistorico: "Historia ei ole käytettävissä",
    semHistoricoDetalhe: "Roolillasi ei ole oikeutta lukea kanavan #{{canal}} historiaa. Uudet viestit näkyvät edelleen, kun olet täällä.",
    boasVindas: "Tervetuloa kanavalle #{{canal}}",
    boasVindasDetalhe: "Tästä alkaa kanava #{{canal}}.",
  },
  data: {
    hoje: "Tänään",
    ontem: "Eilen",
    hojeAs: "tänään klo {{hora}}",
    ontemAs: "eilen klo {{hora}}",
  },
  digitando: {
    um: "{{nome}} kirjoittaa…",
    dois: "{{primeiro}} ja {{segundo}} kirjoittavat…",
    varios: "{{quantidade}} henkilöä kirjoittaa…",
  },
  mensagem: {
    usou: "käytti",
    fixada: "kiinnitetty",
    editado: "(muokattu)",
    ignorada: "Viesti henkilöltä, jonka jätät huomiotta.",
    mostrar: "Näytä",
    escPara: "Esc",
    cancelar: "peruu",
    enterParaSalvar: "Enter tallentaa",
    falhou: "Ei lähtenyt. Yritä uudelleen",
    naoLidasDaqui: "Lukemattomat tästä eteenpäin.",
    linkCopiado: "Linkki kopioitu.",
    idCopiado: "Tunnus kopioitu.",
    naoDeuParaCopiar: "Selaimesi ei sallinut kopiointia.",
    apagarTitulo: "Poistetaanko viesti?",
    apagarDescricao: "Se katoaa kaikilta kanavalla. Sitä ei saa takaisin.",
    apagarAcao: "Poista",
    citacaoAnexo: "napsauta nähdäksesi liitteen",
    citacaoSumiu: "Alkuperäistä viestiä ei enää ole täällä.",
    reagirCom: "Reagoi merkillä {{emoji}} — pidä pohjassa superreaktiota varten",
    segureParaSuper: "{{emoji}} — pidä pohjassa superreaktiota varten",
  },
  acoes: {
    reagir: "Reagoi",
    responder: "Vastaa",
    encaminhar: "Välitä",
    favoritar: "Tallenna viesti",
    tirarDosFavoritos: "Poista tallennetuista",
    marcarNaoLida: "Merkitse lukemattomaksi",
    copiarLink: "Kopioi viestin linkki",
    copiarId: "Kopioi viestin tunnus",
    fixar: "Kiinnitä viesti",
    desafixar: "Irrota",
    editar: "Muokkaa",
    apagar: "Poista",
    mais: "Lisää",
    adicionarReacao: "Lisää reaktio",
    superReagirCom: "Superreagoi merkillä {{emoji}}",
    fixarMensagem: "Kiinnitä viesti",
    desafixarMensagem: "Irrota viesti",
    editarMensagem: "Muokkaa viestiä",
    apagarMensagem: "Poista viesti",
  },
  mencao: {
    cargo: "Roolimaininta",
    pessoa: "Maininta",
    alguem: "joku",
    cargoSemNome: "rooli",
    here: "Ilmoittaa paikalla oleville",
    everyone: "Ilmoittaa koko palvelimelle",
  },
  codigo: {
    copiar: "Kopioi",
    copiado: "Kopioitu",
    copiarAria: "Kopioi koodi",
    copiadoAria: "Koodi kopioitu",
    recolher: "Tiivistä",
    expandir: "Laajenna",
    verInteiro: "Näytä koko tiedosto",
    maisOpcoes: "Lisää valintoja",
    baixar: "Lataa",
    recolherLinhas: "Tiivistä ({{linhas}} riviä)",
    expandirLinhas: "Laajenna ({{linhas}} riviä)",
    mudarIdioma: "Vaihda kieli",
    procurarIdioma: "Hae kielikoodia…",
    nenhumIdioma: "Kieltä ei löytynyt.",
    quebrarTexto: "Rivitä teksti",
  },
  caixa: {
    escrever: "Kirjoita kanavalle #{{canal}}",
    escreverSemCanal: "Kirjoita viesti",
    semPermissao: "Sinulla ei ole oikeutta lähettää viestejä tälle kanavalle",
    solteParaAnexar: "Pudota liittääksesi",
    longaTitulo: "Viestisi on liian pitkä…",
    longaDescricao: "Saavutit {{limite}} merkin rajan. Voit lähettää sen tiedostona.",
    enviarComoArquivo: "Lähetä tiedostona",
    respondendoPara: "Vastaus käyttäjälle",
    vaiNotificar: "Henkilö saa ilmoituksen",
    naoVaiNotificar: "Henkilö ei saa ilmoitusta",
    ligado: "päällä",
    desligado: "pois",
    pararDeResponder: "Lopeta vastaaminen",
    mais: "Lisää",
    enviarArquivo: "Lähetä tiedosto",
    criarEnquete: "Luo kysely",
    expressoes: "Emojit, GIFit ja tarrat",
    enviar: "Lähetä",
    aguardandoEnvio: "Odotetaan lähetystä",
    modoLento: "Hidas tila päällä ({{tempo}})",
    modoLentoDica: "Hidas tila on {{segundos}} s. Odota ennen seuraavan viestin lähettämistä.",
  },
  anexos: {
    enviando: "Lähetetään…",
    modificar: "Muokkaa tiedostoa {{arquivo}}",
    remover: "Poista {{arquivo}}",
    ver: "Näytä {{arquivo}}",
    mostrarSpoiler: "Näytä juonipaljastus: {{arquivo}}",
    spoiler: "juonipaljastus",
    spoilerTitulo: "Juonipaljastus",
    editarTitulo: "Muokkaa liitettä",
    nomeDoArquivo: "Tiedoston nimi",
    descricao: "Vaihtoehtoisen tekstin kuvaus",
    descricaoDica: "Kuvaile tämä media ruudunlukijoille",
    marcarSpoiler: "Merkitse juonipaljastukseksi",
    cancelar: "Peruuta",
    salvar: "Tallenna",
  },
  cartao: {
    tocador: "Soitin",
    abrir: "Avaa {{destino}}",
    tocar: "Toista {{titulo}}",
    video: "video",
    verImagem: "Näytä kuva",
  },
  enquete: {
    titulo: "Kysely",
    encerrada: "Kysely päättyi",
    variasRespostas: "Kysely — useita vastauksia",
    umVoto: "{{quantidade}} ääni",
    votos: "{{quantidade}} ääntä",
    umVotoNoTotal: "{{quantidade}} ääni yhteensä",
    votosNoTotal: "{{quantidade}} ääntä yhteensä",
    encerraEm: "päättyy {{quando}}",
    encerrarAgora: "Päätä nyt",
  },
  fixadas: {
    titulo: "Kiinnitetyt viestit",
    vazio: "Tällä kanavalla ei ole kiinnitettyjä viestejä… vielä.",
    desafixar: "Irrota",
    anexo: "(liite)",
    enquete: "(kysely)",
    dicaRotulo: "VINKKI:",
    dica: "kenellä on oikeus ”Hallitse viestejä”, voi kiinnittää suoraan viestin valikosta.",
  },
  encaminhar: {
    titulo: "Välitä viesti",
    paraOnde: "Minne?",
    semTexto: "(viesti ilman tekstiä)",
    nenhumLugar: "Ei tämännimistä paikkaa.",
    canais: "Kanavat",
    conversas: "Yksityisviestit",
  },
  expressoes: {
    gifs: "GIFit",
    buscarGifs: "Hae Klipystä",
    figurinha: "Tarra",
    buscarFigurinha: "Löydä täydellinen tarra",
    buscarEmoji: "Löydä täydellinen emoji",
    buscarReacao: "Löydä täydellinen reaktio",
    adicionarEmoji: "Lisää emoji",
    limparBusca: "Tyhjennä haku",
  },
  busca: {
    fechar: "Sulje haku",
    procurando: "Haetaan…",
    resultado: "{{quantos}} tulos",
    resultados: "{{quantos}} tulosta",
    nadaCom: "Ei mitään haulla {{termo}}.",
    soOsQuePodeLer: "Haku katsoo vain kanavia, joita saat lukea.",
  },
  entrada: {
    titulo: "Saapuneet",
    naoLidas: "Lukemattomat",
    salvas: "Tallennetut",
    mencoes: "Maininnat",
    fimTitulo: "Pääsit loppuun",
    fimDetalhe: "Luettavaa ei ole enää. Kun uusi viesti saapuu, se ilmestyy tähän.",
    semSalvosTitulo: "Ei tallennettuja",
    semSalvosDetalhe: "Pidä Vaihto pohjassa ja napsauta viestin kirjanmerkkiä, niin se säilyy ja voit lukea myöhemmin.",
    tirarDosSalvos: "Poista tallennetuista",
    semMencoesTitulo: "Ei vielä mainintoja",
    semMencoesDetalhe: "Sinua koskevat maininnat näkyvät tässä viimeisiltä 7 päivältä.",
  },
  forum: {
    descricao: "Jokaisesta aiheesta tulee oma keskustelunsa — hyvä kysymykselle, joka ei saa hukkua jutustelun keskelle.",
    novoAssunto: "Uusi aihe",
    vazio: "Ei vielä aiheita. Aloita ensimmäinen, niin keskustelu pysyy järjestyksessä alusta asti.",
    titulo: "Otsikko",
    doQueSeTrata: "Mistä on kyse?",
    primeiraMensagem: "Ensimmäinen viesti",
    conteDoCaso: "Kerro siitä",
  },
};
