export const perfil = {
  carregando: "Ladataan…",
  editar: "Muokkaa profiilia",
  mensagem: "Viesti",
  abrirConversa: "Avaa keskustelu",
  verCompleto: "Näytä koko profiili",
  convidarParaServidor: "Kutsu palvelimelle",
  semServidores: "Sinulla ei ole palvelimia",
  conviteEnviado: "Kutsu lähetetty käyttäjälle {{nome}}.",
  moderador: "Avaa valvojanäkymässä",
  mais: "Lisää",
  ignorar: "Sivuuta",
  deixarDeIgnorar: "Lopeta sivuuttaminen",
  copiarId: "Kopioi käyttäjätunniste",
  idCopiado: "Tunniste kopioitu.",
  conexoes: "Yhteydet",
  membroDesde: "Jäsen alkaen",
  sobre: "Tietoja",
  cargosTitulo: "Roolit",
  visaoGeral: "Yleiskatsaus",
  amigosEmComum: "Yhteiset kaverit ({{quantidade}})",
  servidoresEmComum: "Yhteiset palvelimet ({{quantidade}})",
  amizade: {
    amigo: "Kaveri",
    pedidoEnviado: "Kaveripyyntö lähetetty",
    respondaAbaixo: "Lähetti sinulle pyynnön — vastaa alla",
    adicionar: "Lisää kaveriksi",
    teMandouPedido: "Lähetti sinulle kaveripyynnön",
    aceitar: "Hyväksy",
    desfazer: "Poista kavereista",
    desfazerTitulo: "Poistetaanko {{nome}} kavereistasi?",
    desfazerDescricao: "Ette ole enää kavereita. Yksityiskeskustelu jää historiaan, ja voit lisätä hänet myöhemmin uudelleen.",
    bloquear: "Estä",
    bloquearTitulo: "Estetäänkö {{nome}}?",
    bloquearDescricao: "Ette ole enää kavereita, yksityiskeskustelu lakkaa ottamasta viestejä vastaan, eikä hän voi enää lähettää sinulle kaveripyyntöä.",
    linkCopiado: "Ette ole kavereita — linkki kopioitiin, jotta voit lähettää sen itse.",
  },
  recado: {
    escrever: "Kirjoita käyttäjälle @{{usuario}}",
    enviar: "Lähetä",
    enviada: "Viesti lähetetty",
    falhou: "Lähetys ei onnistunut. Kokeile keskustelusta.",
  },
  cartao: {
    trocarFaixa: "Vaihda kortin banneri",
    trocarFaixaCurto: "Vaihda banneri",
    trocarFoto: "Vaihda profiilikuva",
    trocarFotoCurto: "Vaihda kuva",
    suaEtiqueta: "Sinun merkkisi",
    editarEtiqueta: "Muokkaa merkkiäsi napsauttamalla",
    conteAlgo: "Kerro jotain itsestäsi",
    adicionarStatus: "Lisää tila",
    adicionarDescricao: "Lisää kuvaus napsauttamalla",
    cargo: "Rooli",
    cargos: "Roolit",
    cargosCom: "Roolit — {{quantidade}}",
    tirarCargo: "Poista rooli {{cargo}}",
  },
  cargos: {
    adicionar: "Lisää rooli",
    procurar: "Etsi roolia",
  },
  etiqueta: {
    escolher: "Valitse palvelinmerkki",
    nenhuma: "Ei palvelinmerkkiä",
    semEtiqueta: "Yhdelläkään palvelimellasi ei ole merkkiä",
  },
  emblemas: {
    doServidor: "Tämän palvelimen tunnukset",
    limite: "Voit pitää enintään {{quantidade}} tunnusta.",
  },
  nota: {
    vazia: "Kirjoita muistiinpano napsauttamalla",
    rotulo: "Muistiinpano (vain sinä näet sen)",
  },
  status: {
    titulo: "Tila",
    definir: "Aseta tilasi",
    escolherEmoji: "Valitse emoji",
    tirarEmoji: "Poista emoji",
    oQuePensa: "Mitä mietit?",
    limparAgora: "Tyhjennä tila nyt",
    naoLimpar: "Älä tyhjennä",
    limpar30m: "Tyhjennä 30 minuutin päästä",
    limpar1h: "Tyhjennä tunnin päästä",
    limpar4h: "Tyhjennä 4 tunnin päästä",
    limparHoje: "Tyhjennä tänään",
    limparAmanha: "Tyhjennä huomenna",
    comHora: "{{prazo}} klo {{hora}}",
  },
  presenca: {
    disponivel: "Paikalla",
    ausente: "Poissa",
    naoPerturbar: "Älä häiritse",
    naoPerturbarDetalhe: "Et saa ilmoitusta uusista viesteistä",
    invisivel: "Näkymätön",
    invisivelDetalhe: "Muille näytät olevan poissa",
  },
  menu: {
    mudarDeConta: "Vaihda tiliä",
    gerenciarContas: "Hallitse tilejä",
  },
  editor: {
    decoracao: "Vaihda avatarin koristetta",
    naoSalvo: "Muista tallentaa muutoksesi!",
    principal: "Pääprofiili",
  },
};
