export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Palvelimen asetukset",
  auditoria: {
    todasAsAcoes: "Kaikki toiminnot",
    todosOsUsuarios: "Kaikki käyttäjät",
    filtroMembros: "Jäsenet",
    filtroCanais: "Kanavat",
    filtroEmojis: "Emojit",
    filtroServidor: "Palvelin",
    titulo: "Toimintaloki",
    porUsuario: "Suodata henkilön mukaan",
    porAcao: "Suodata toiminnon mukaan",
    vazio: "Tällä suodattimella ei ole vielä kirjattu mitään.",
    motivo: "Syy:",
  },
  banimentos: {
    titulo: "Palvelimen porttikieltolista",
    descricao: "Täällä oleva ei pääse takaisin edes uudella kutsulla. Porttikiellon poisto palauttaa pääsyn heti.",
    procurar: "Etsi porttikieltoja käyttäjänimellä",
    vazioTitulo: "Ei porttikieltoja",
    vazio: "Et ole vielä antanut kenellekään porttikieltoa… mutta jos ja kun tarvitset, älä epäröi.",
    desbanir: "Poista porttikielto",
  },
  excluir: {
    tudoVai: "Kaikki palvelimen {{servidor}} kanavat, viestit ja kutsut poistetaan {{membros}} jäseneltä. Sen jälkeen kukaan ei saa niitä takaisin.",
    digite: "Kirjoita {{servidor}} vahvistaaksesi",
    titulo: "Poista palvelin",
    aviso: "Tätä ei voi perua.",
  },
  emblemas: {
    apagarDescricao: "Se lähtee jokaiselta, joka sitä käyttää. Tätä ei voi perua.",
    titulo: "Merkit",
    vazio: "Ei vielä merkkejä.",
    novo: "Uusi merkki",
  },
  convites: {
    revogarTitulo: "Perutaanko kutsu?",
    revogarAcao: "Peru",
    revogarDescricao: "Linkki {{codigo}} lakkaa toimimasta heti. Se, joka jo liittyi sen kautta, pysyy palvelimella.",
    titulo: "Kutsut",
    descricao: "Kaikki tämän palvelimen voimassa olevat kutsulinkit.",
    vazio: "Yhtään kutsua ei ole vielä luotu.",
    revogar: "Peru kutsu",
  },
  integracoes: {
    opcionais: "username ja avatar_url ovat valinnaisia ja koskevat viestiä. Raja on 5 viestiä 5 sekunnissa.",
    apagarDescricao: "URL lakkaa toimimasta heti. Jo lähetetyt viestit jäävät kanavalle.",
    titulo: "Integraatiot",
    descricao: "Webhook on osoite, joka kirjoittaa kanavalle ilman tiliä. Kätevä ilmoittamaan, että käännös meni läpi, että joku avasi tiketin, tai mitä ikinä haluat lähettää skriptistä.",
    novo: "Uusi webhook",
    vazio: "Ei vielä webhookeja. Luo yksi ja liitä URL sinne, mistä haluat viestin tulevan.",
    canal: "Kanava",
    apagar: "Poista webhook",
    comoUsar: "Näin sitä käytetään",
    comoUsarTexto: "Lähetä POST JSONilla:",
  },
  engajamento: {
    semCanal: "Ei järjestelmäkanavaa",
    titulo: "Aktiivisuus",
    descricao: "Mitä palvelin tekee itsekseen, ettei se tuntuisi tyhjältä, kun joku uusi saapuu.",
    sistema: "Järjestelmäviestit",
    boasVindas: "Lähetä tervetuloviesti, kun joku liittyy",
    sorteio: "Ilman omaa tekstiä alla lause arvotaan — sama joka kerta puuduttaa nopeasti.",
    canalDoSistema: "Järjestelmäviestien kanava",
    mensagem: "Tervetuloviesti",
    deixeVazio: "Jätä tyhjäksi, niin arvotaan valmiista lauseista",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Suodattimet, jotka moderoivat itsekseen, ennen kuin viesti edes on olemassa. Palvelinta hallinnoivaa ei suodateta koskaan — ja vapautetut roolit menevät suoraan läpi.",
    palavras: {
      titulo: "Estä omat sanat",
      descricao: "Sinun listasi sanoista, joita kukaan ei saa kirjoittaa.",
    },
    mencoes: {
      titulo: "Estä mainintaroskaposti",
      descricao: "Estää viestin, jossa on liian monta mainintaa kerralla.",
    },
    links: {
      titulo: "Estä linkit",
      descricao: "Pysäyttää jokaisen keskusteluun liitetyn osoitteen.",
    },
    definir: "Määritä",
    nomeDaRegra: "Säännön nimi",
    bloqueadas: "Estetyt sanat",
    digiteEnter: "Kirjoita ja paina Enter",
    comparacao: "Vertailu ei välitä isoista kirjaimista, aksenteista eikä välimerkeistä — eikä nappaa sanaa toisen sanan sisältä.",
    aPartirDe: "Estä kuinka monesta maininnasta alkaen",
    oQueFazer: "Mitä tehdään",
    canalDoAlerta: "Ilmoituksen kanava",
    escolhaCanal: "Valitse kanava",
    castigo: "Hiljennys (minuuttia)",
    isentos: "Vapautetut roolit",
    semCargos: "Rooleja ei ole vielä luotu.",
    salvarRegra: "Tallenna sääntö",
    apagar: "Poista sääntö",
    excluirTitulo: "Poistetaanko tämä AutoMod-sääntö?",
    excluirDescricao: "Palvelin lakkaa heti suodattamasta sen mukaan. Voit luoda sen uudelleen, mutta nykyiset asetukset katoavat.",
    excluirAcao: "Poista sääntö",
  },
  cargos: {
    titulo: "Roolit",
    descricao: "Roolit antavat nimen, värin ja valtuudet. Listalla ylempänä oleva määrää alempien yli — eikä kukaan koske omaa vastaavaan tai korkeampaan rooliin.",
    criar: "Luo rooli",
    vazio: "Ei vielä rooleja.",
    abaExibicao: "Ulkoasu",
    abaPermissoes: "Oikeudet",
    abaMembros: "Jäsenet — {{quantos}}",
    everyone: "Koskee kaikkia palvelimella. Se on perusta, jonka päälle muut roolit lisätään.",
    nomeDoCargo: "Roolin nimi",
    cor: "Roolin väri",
    corDica: "Värittää roolin haltijan nimen jäsenlistassa ja keskustelussa.",
    semCor: "Ei väriä",
    corPersonalizada: "Oma väri",
    estilo: "Nimen tyyli",
    segundaCor: "Toinen väri",
    segundaCorDica: "Ilman sitä liukuväri palaa yhteen väriin — se ei katoa.",
    limparSegundaCor: "Tyhjennä toinen väri",
    icone: "Kuvake",
    iconeDica: "Näkyy roolin vieressä sen haltijan profiilikortissa.",
    exibirSeparado: "Näytä erillään muista jäsenistä",
    exibirSeparadoDica: "Rooli saa oman osionsa jäsenlistaan.",
    permitirMencionar: "Salli tämän roolin mainitseminen",
    permitirMencionarDica: "Kuka tahansa voi silloin ilmoittaa kaikille, joilla on rooli.",
    semPoderDeConceder: "{{descricao}} (sinulla ei ole tätä oikeutta, jotta voisit myöntää sen)",
    adicionar: "Lisää joku tähän rooliin",
    tirar: "Ota rooli pois",
    semNinguem: "Kellään ei ole vielä tätä roolia.",
    apagar: "Poista rooli",
    excluirTitulo: "Poistetaanko rooli ”{{nome}}”?",
    excluirDescricao: "Roolin haltija menettää kaiken, mitä se antoi. Tätä ei voi perua.",
    excluirAcao: "Poista rooli",
  },
  membros: {
    procurar: "Hae nimellä tai käyttäjänimellä",
    membroDesde: "Jäsen alkaen",
    vazio: "Ketään ei löytynyt.",
    acoesPara: "Toiminnot: {{nome}}",
    deCastigo: "hiljennystä",
    tirarCastigo: "Poista hiljennys",
    castigo5min: "5 minuuttia",
    castigo1h: "1 tunti",
    castigo1d: "1 päivä",
    castigo1s: "1 viikko",
    expulsar: "Potki pois",
    expulsarTitulo: "Potkitaanko {{nome}} pois?",
    expulsarDescricao: "poistuu palvelimelta {{servidor}} heti. Voi palata kutsulla — potkiminen ei estä paluuta.",
    banir: "Anna porttikielto",
    banirTitulo: "Annetaanko {{nome}}lle porttikielto?",
    banirDescricao: "poistuu palvelimelta {{servidor}} eikä pääse takaisin edes kutsulla, ennen kuin porttikielto poistetaan.",
    motivo: "Syy (valinnainen)",
    motivoDica: "Jää toimintolokiin",
  },
  perfil: {
    titulo: "Palvelimen profiili",
    descricao: "Näin palvelimesi näkyy listassa ja kutsulinkeissä.",
    icone: "Kuvake",
    faixa: "Yläbanneri",
    nomeDoServidor: "Palvelimen nimi",
    campoDescricao: "Kuvaus",
    doQueE: "Mistä tämä palvelin kertoo?",
    comprimido: "Pakattu ennen lähetystä: {{economia}}",
  },
  etiqueta: {
    titulo: "Palvelimen tunniste",
    descricao: "Enintään 4 kirjaimen tunniste, joka näkyy jokaisen jäsenen nimen vieressä — keskustelussa ja henkilölistassa. Täällä se on ilmainen: ei boosteja, ei tasoja.",
    escolhaNome: "Valitse nimi",
    limite: "Enintään 4 merkkiä, kirjaimia ja numeroita.",
    escolhaInsignia: "Valitse merkki",
    voce: "Sinä",
    fala1: "onko kukaan pelaamassa?",
    fala2: "katso mun tunnistetta!",
    fala3: "oho, mistä sait ton",
  },
  expressoes: {
    comoUsar: "Lisää enintään {{limite}} emojia, joita kaikki voivat käyttää tällä palvelimella. Kirjoita :nimi: keskusteluun lähettääksesi.",
    imagem: "Kuva",
    enviadoPor: "Lähettäjä",
    semEmoji: "Ei vielä emojeja.",
    figurinhas: "Tarrat",
    enviarFigurinha: "Lähetä tarra",
    nomeDaFigurinha: "Tarran nimi",
    exemploFigurinha: "Esim.: kissanpennun halaus",
    figurinhaGrande: "Tarra ylittää {{limite}}.",
    deixaPraLa: "Anna olla",
    sons: "Äänipaneeli",
    enviarSom: "Lähetä ääni",
    nomeDoSom: "Äänen nimi",
    semSom: "Ei vielä ääniä.",
    somGrande: "Ääni ylittää {{limite}}.",
    emojiRelacionado: "Liittyvä emoji",
    ouvir: "Kuuntele",
    ouvirAssim: "Kuuntele näin",
    volumeDe: "Äänenvoimakkuus: {{nome}}",
    volumeDica: "Koskee kaikkia palvelimella. Jokainen voi silti hiljentää äänet vain itselleen puhelupaneelista.",
    falhaEnvio: "Tiedostoa ei voitu lähettää.",
    excluirTitulo: "Poistetaanko {{tipo}} ”{{nome}}”?",
    excluirDescricao: "Se katoaa palvelimelta kaikilta. Viestit, jotka jo käyttivät sitä, säilyvät sellaisinaan.",
  },
  canal: {
    visaoGeral: "Yleiskatsaus",
    nome: "Kanavan nimi",
    topico: "Kanavan aihe",
    topicoDica: "Mistä täällä puhutaan?",
    modoLento: "Jokainen lähettää vain yhden viestin aikaväliä kohden. Kuka tahansa, joka hallinnoi viestejä tai kanavia, menee suoraan läpi.",
    visibilidade: "Sisällön näkyvyys",
    padrao: "Oletus",
    padraoDica: "Kanavan sisältö näkyy aina.",
    spoiler: "Spoilerikanava",
    spoilerDica: "Merkitse tämä kanava spoilereita sisältäväksi, jotta juonenkäänteet ja raskaat aiheet pysyvät piilossa, kunnes joku valitsee katsoa.",
    idade: "Ikärajoitettu kanava",
    idadeDica: "Sisään tulevan on vahvistettava olevansa täysi-ikäinen nähdäkseen sisällön.",
    bitrateDica: "Yli 64 kbps voi haitata niitä, joilla on huono yhteys.",
    qualidadeDeVideo: "Videon laatu",
    automatica: "Automaattinen",
    limite: "Käyttäjäraja — {{valor}}",
    pessoas: "{{quantos}} henkilöä",
    semLimite: "ei rajaa",
    permissoesDescricao: "Täällä muutat, mikä pätee tällä kanavalla. Se, mikä jää ”peri”-asentoon, seuraa edelleen roolia.",
    excluir: {
      titulo: "Poista kanava",
      historico: "Koko kanavan {{canal}} historia lähtee mukana, kaikilta.",
      digite: "Kirjoita {{canal}} vahvistaaksesi",
    },
  },
  moderacao: {
    titulo: "Valvojan näkymä",
    semPermissao: "Tarvitset oikeuden ”Valvo jäseniä” nähdäksesi tämän.",
    fecharEsc: "Sulje (Esc)",
    atividade: "Toiminta palvelimella",
    mensagens: "Viestit",
    links: "Linkit",
    midia: "Media",
    acoesNaAuditoria: "Toiminnot lokissa",
    moderacoesSofridas: "Saadut toimenpiteet",
    permissoes: "Oikeudet ({{quantas}})",
    semPermissaoEspecial: "Ei erityisoikeuksia.",
    conta: "Tili",
    entrouNoServidor: "Liittyi palvelimelle",
    contaCriadaEm: "Tili luotu",
    deCastigoAte: "Hiljennetty asti",
    formaDeAdesao: "Miten pääsi sisään",
    mensagem: "Viesti",
    castigo: "Hiljennys",
    copiarId: "Kopioi tunnus",
    idCopiado: "Tunnus kopioitu.",
    adicionarCargo: "Lisää rooli",
    semCargos: "Yhtään roolia ei ole luotu",
    soEveryone: "Vain @everyone.",
    voltar: "Takaisin",
    vazio: "Täällä ei ole mitään.",
    cinquenta: "Näytetään 50 uusinta.",
    irParaMensagem: "Siirry viestiin",
    precisaSerAmigo: "Teidän on oltava kavereita voidaksenne jutella.",
    expulsarDescricao: "Poistuu palvelimelta heti, mutta voi palata kutsulla.",
    banirDescricao: "Poistuu palvelimelta eikä pääse takaisin edes kutsulla, ennen kuin porttikielto poistetaan.",
    castigarTitulo: "Hiljennetäänkö {{nome}}?",
    castigoDescricao: "Niin kauan kuin se kestää, hän ei kirjoita eikä puhu millään palvelimen kanavalla.",
    aplicarCastigo: "Käytä hiljennystä",
    duracao: "Kesto minuutteina",
    informeDuracao: "Anna kesto minuutteina.",
  },
  abas: {
    expressoes: "Ilmaisut",
    pessoas: "Ihmiset",
    apps: "Sovellukset",
    moderacao: "Valvonta",
    banimentos: "Porttikiellot",
  },
};
