export const amizades = {
  ativosAgora: "アクティブ",
  procurando: "だれがいるか確認中…",
  tudoTranquilo: "今のところ静かです…",
  tudoTranquiloDetalhe: "あなたか友だちが通話に入ると、ここに表示されます。ワンクリックで参加できます。",
  emVoz: "ボイス中",
  voce: "あなた",
  soVoce: "あなただけ",
  pessoas: "{{quantas}}人",
  voltarParaChamada: "通話に戻る",
  entrarNaChamada: "通話に参加",
  abrirCanal: "{{servidor}} の {{canal}} を開く",
  mensagensDiretas: "ダイレクトメッセージ",
  encontreConversa: "会話を探す",
  amigos: "フレンド",
  conversas: "会話",
  semConversas: "まだ会話がありません。フレンドを追加して始めましょう。",
  semConversaComEsseNome: "その名前の会話はありません。",
  abrirMenu: "サーバーと会話を開く",
  solicitacoes: "メッセージリクエスト",
  pedidos: "リクエスト",
  spam: "スパム",
  pedidosPendentes: "保留中のリクエスト",
  marcadosComoSpam: "スパムとして マーク済み",
  aceitar: "承認",
  ignorar: "無視",
  marcarSpam: "スパムにする",
  semPedidos: "保留中のリクエストはありません。",
  semPedidosDetalhe: "フレンドではないけれど同じサーバーにいる人は、あなたの会話に届く前にここに入ります。",
  semSpam: "スパムにしたものはありません。",
  semSpamDetalhe: "スパムフィルターが分けたもの、またはあなたがマークしたものは、このタブに残ります。",
  umServidorEmComum: "共通サーバー 1つ",
  servidoresEmComum: "共通サーバー {{quantos}}つ",
  semServidoresEmComum: "共通のサーバーなし",
};
