export const chamada = {
  conectando: "通話に接続しています…",
  naoEntrou: "通話に参加できませんでした",
  sair: "通話から退出",
  sairDaVoz: "ボイス通話から退出",
  desconectar: "切断",
  voltar: "通話に戻る",
  voltarAosQuadros: "通話のタイルに戻る",
  fecharChat: "チャットを閉じる",
  carregandoPrevia: "プレビューを読み込んでいます…",
  maisOpcoes: "その他の操作",
  deVideo: "ビデオ通話",
  deVoz: "ボイス通話",
  alguem: "だれか",
  volume: {
    entrada: "入力音量",
    saida: "出力音量",
    live: "配信の音量",
    liveComPorcento: "配信の音量（{{porcento}}%）",
    liveSemSom: "配信をミュート",
  },
  aparelhos: {
    entrada: "入力デバイス",
    saida: "出力デバイス",
    camera: "カメラ",
    microfone: "マイク",
    saidaCurto: "出力",
    oDoSistema: "システムの設定",
    aDoSistema: "システムの設定",
    semEscolhaDeSaida: "このブラウザーでは出力を選べません — 決めるのはシステムです。",
    espelhar: "自分のカメラを左右反転",
    configEntrada: "入力の設定",
    configSaida: "出力の設定",
    configCamera: "カメラの設定",
    configAudioEVideo: "音声とビデオの設定",
  },
  tela: {
    compartilhar: "画面を共有",
    compartilharAcao: "共有",
    cancelar: "キャンセル",
    telas: "画面",
    janelas: "ウインドウ",
    somDoComputador: "パソコンの音も一緒に送る",
    somDoSistema: "システムの音も一緒に送る",
    configCompartilhamento: "共有の設定",
    mostrarSemVideo: "ビデオを出していない人も表示",
    semFontes: "共有できる画面もウインドウもシステムから返ってきませんでした。",
    pararDeCompartilhar: "共有をやめる",
    encerrarTransmissao: "配信を終了",
  },
  live: {
    etiqueta: "ライブ",
    etiquetaMaiuscula: "ライブ",
    assistir: "配信を見る",
    assistirPessoa: "{{nome}} を見る",
    pararDeAssistir: "見るのをやめる",
  },
  membro: {
    mudarMeuApelido: "自分のニックネームを変更",
    meuMicrofone: "自分のマイク",
    ouvirChamada: "通話を聞く",
    copiarMeuId: "自分の ID をコピー",
    idCopiado: "ID をコピーしました。",
    mensagem: "メッセージ",
    silenciar: "ミュート",
    alterarApelido: "ニックネームを変更",
    cargos: "ロール",
    semCargo: "ロールがありません",
    moverPara: "移動先",
    silenciarNoServidor: "サーバーで発言をミュート",
    desativarAudioNoServidor: "サーバーで音声を無効化",
    desconectar: "切断",
    apelidoTitulo: "このサーバーでのあなたのニックネーム",
    apelidoDeAlguem: "{{nome}} のニックネーム",
    apelidoCampo: "ニックネーム",
    apelidoDicaPropria: "ここだけで有効です。空にすると、いつもの名前に戻ります。",
    apelidoDicaDeOutro: "このサーバーだけで有効です。空にすると元の名前に戻ります。",
  },
  detalhes: {
    abrir: "音声の詳細",
    titulo: "音声の詳細",
    conexao: "接続",
    pingMedio: "平均 ping",
    ultimoPing: "直近の ping",
    perda: "送信パケットの損失",
    medindo: "計測中…",
    criptografado: "サーバーまで暗号化（DTLS-SRTP）",
    explicacao: "250 ms を超えると会話の遅れが分かるようになり、話がかぶり始めます。パケット損失が 10% を超えると声がロボットのようになります。どちらも原因はたいてい自分とインターネットの間にあります。Wi-Fi ではなく有線を試すか、ルーターを再起動してください。",
  },
  microfone: {
    bloqueado: "マイクがブロックされています — 聞くだけの状態です。ブラウザーの権限で許可してください。",
    bloqueadoNoMac: "macOS がマイクをブロックしています。",
    caminhoNoMac: "システム設定 → プライバシーとセキュリティ → マイク",
    abrirAjustes: "設定を開く",
    vaiReabrir: "macOS からアプリの再起動を求められます。",
    naoAbriu: "マイクを開けませんでした — 聞くだけの状態です。設定 → 音声とビデオ でデバイスを確認してください。",
  },
  gravacaoDeTela: {
    bloqueada: "macOS がまだ画面収録を許可していません。許可がないと共有は真っ黒になります。",
    marque: "次にチェックを入れてください:",
    reabra: "「画面収録」で有効にして、アプリを開き直してください。",
  },
  ruido: {
    titulo: "ノイズ抑制",
    explicacao: "声から背景の音を取り除きます。話しながら手をたたいたり、キーボードを動かしたりしてみてください — 通話中の人にはあなたの声だけが届きます。",
    semSuporte: "このブラウザーは高度な抑制を動かせません。ブラウザー自身のものは効きますが、そちらは弱めです。",
    aplicando: "通話に適用しています…",
    faleParaTestar: "話してみてください",
    verdeQuandoPassa: "声が通ると緑になります。",
    teOuvindo: "いま聞こえています。",
    feitoCom: "使用技術:",
    aquiNoAparelho: "、この端末の中だけで処理しています",
    ajustes: "設定",
  },
  permissoes: {
    titulo: "macOS の権限",
    detalhe: "macOS が尋ねるのは一度きりで、あとは macOS の設定でしか変わりません。ここでは何が有効かを確認して、足りないものを解決できます。",
    concedida: "許可済み",
    negada: "拒否",
    naoPedida: "未確認",
    permitir: "許可する",
    abrirAjustes: "設定を開く",
    microfone: "マイク",
    microfoneDetalhe: "通話で話し、入力をテストします。",
    camera: "カメラ",
    cameraDetalhe: "通話でビデオを入にします。",
    tela: "画面収録",
    telaDetalhe: "画面とウインドウを共有します。",
    monitoramento: "入力モニタリング",
    monitoramentoDetalhe: "Gravaê がバックグラウンドでもプッシュトゥトークを使えます。",
  },
  jaConectado: {
    titulo: "すでにこの通話に参加しています",
    trazer: "通話をこちらへ移す",
    deixar: "このままにする",
    detalhe: "こちらへ移すと、もう一方は通話から外れます — アカウントは同時に 1 か所だけです。",
  },
};
