export const comum = {
  carregando: "読み込み中…",
  salvar: "保存",
  salvando: "保存中…",
  descartar: "破棄",
  redefinir: "リセット",
  naoSalvo: "保存していない変更があります。",
  fechar: "閉じる",
  criar: "作成",
  nome: "名前",
  emoji: "絵文字",
  previa: "プレビュー",
  cancelar: "キャンセル",
  enviar: "送信",
  apagar: "削除",
  excluir: "削除",
  remover: "外す",
  trocar: "変更",
};
