export const configuracoes = {
  sair: "ログアウト",
  versoes: {
    copiar: "クリックでコピー",
    copiado: "コピーしました",
  },
  telas: {
    conta: "アカウント",
    privacidade: "プライバシー",
    conexoes: "連携",
    voz: "オーディオ",
    video: "ビデオ",
    avisos: "通知",
    aplicativos: "アプリケーション",
    aparencia: "外観",
    batePapo: "チャット",
    acessibilidade: "アクセシビリティ",
    idioma: "言語",
    aplicativo: "アプリを入手",
    atalhos: "ショートカット",
    desktop: "デスクトップアプリ",
    avancado: "詳細設定",
    servidor: "サーバー",
  },
  grupos: {
    conta: "アカウント",
    app: "アプリの設定",
    desenvolvedor: "開発者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "ログイン情報",
    dispositivos: "デバイス",
    usuariosBloqueados: "ブロックしたユーザー",
    aplicativosAutorizados: "認証済みアプリ",
    sessoes: "セッション",
    amigosEDms: "フレンドとダイレクトメッセージ",
    compartilhamentoDeAtividade: "アクティビティの共有",
    visibilidadeDoPerfil: "プロフィールの公開範囲",
    exportarDados: "データをエクスポート",
    exclusaoDeDados: "データを削除",
    tema: "テーマ",
    corDeDestaque: "アクセントカラー",
    interface: "インターフェース",
    listaDeCanais: "チャンネル一覧",
    zoomDoApp: "アプリの拡大率",
    escalaDaFonte: "チャットの文字サイズ",
    modoStreamer: "配信時のプライバシー",
    movimento: "モーション",
    textoEmVoz: "テキスト読み上げ",
    teclado: "キーボード",
    formatoDaHora: "時刻の表示形式",
    idiomaDaInterface: "表示言語",
    dispositivosDeVoz: "デバイス",
    testeDoMicrofone: "マイクのテスト",
    modoDeEntrada: "入力モード",
    sensibilidade: "入力感度",
    qualidade: "品質",
    camera: "カメラ",
    transmissao: "配信",
    exibicao: "表示",
    entrada: "入力",
    midia: "メディア",
    geral: "全般",
    preferenciaDeMencao: "メンションの設定",
    sons: "サウンド",
  },
};
