export const configuracoes = {
  efeitos: {
    titulo: "ポインターの効果",
    detalhe: "画面の上に描く軌跡と火花です。最初は切ってあり、動きを控える設定にしていれば自分で消えます。",
    rastro: "ポインターの軌跡",
    rastroDetalhe: "ポインターを追い、後ろから薄れていく線です。",
    faisca: "クリックの火花",
    faiscaDetalhe: "押した場所から飛び出す短い線です。",
    cor: "色",
    espessura: "太さ",
    comprimento: "長さ",
    tamanho: "大きさ",
    quantidade: "数",
  },
  email: {
    verificarTitulo: "メールアドレスを確認してください",
    verificarDetalhe: "確認済みの人しか書き込めないコミュニティがあります。ひと押しで済みます。",
    enviar: "リンクを送る",
    enviado: "受信箱をご覧ください。リンクは一日もちます。",
    falhou: "メールを送れませんでした。",
    confirmado: "メールを確認しました",
    confirmadoDetalhe: "これで完了です。確認を求めるコミュニティでも書き込めます。",
    linkIncompleto: "リンクが欠けています",
    linkIncompletoDetalhe: "アドレスにコードがありません。メールのリンクをそのまま開いてください。",
    confirmando: "確認しています…",
    expirou: "このリンクは使用済みか、期限が切れています。",
    irParaOApp: "アプリへ",
  },
  tema: {
    indisponivel: "テーマを開けません",
    indisponivelDetalhe: "公開した人が削除したか、リンクが違います。",
    indisponivelLinha: "テーマを開けません。公開した人が削除したか、リンクが違います。",
    importar: "テーマを取り込む",
    importarCurto: "取り込む",
    importarDetalhe: "今のテーマを置き換えます。あとから 設定 > 外観 > テーマスタジオ で編集できます。",
    porAutor: "作者: {{autor}}",
    umaCorTrocada: "1 色を変更",
    coresTrocadas: "{{quantas}} 色を変更",
    avisoDeCss: "このテーマには作者の CSS が入っており、CSS は画面のどこにでも手が届きます。信頼できる人のものだけを取り込んでください。",
    soCores: "このテーマは色だけを変えます。外部の CSS はありません。",
    verCss: "CSS を表示",
    esconderCss: "CSS を隠す",
    aplicar: "適用",
    previaSemMotor: "プレビューではエンジンが動きません。入れると見られます。",
    motorAnimado: "{{motor}}（アニメーション）",
  },
  sair: "ログアウト",
  versoes: {
    termos: "利用規約",
    privacidade: "プライバシーポリシー",
    copiar: "クリックでコピー",
    copiado: "コピーしました",
  },
  subscription: {
    seePlans: "プランを見る",
    upgradeSubtitle: "文章、ファイル送信、配信の上限が広がり、限定機能も使えます。",
    perMonth: "/月",
    perYear: "/年",
    save: "{{percent}}%お得",
    howToPay: "お支払い方法を選んでください",
    legal: "支払いから7日以内なら返金をリクエストできます。お支払いはStripeが処理し、カード番号が当社に見えることはありません。",
    compare: "無料とInfinity",
    featureColumn: "機能",
    freeColumn: "無料",
    messageRow: "メッセージの文字数上限",
    attachmentRow: "送信できるファイルサイズ",
    screenRow: "動画の画質",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}}・{{fps}} fps",
    alreadyPremium: "Infinityは{{date}}まで有効です。",
    upsell: "Infinityで上限を広げる",
    screenUpsell: "Infinityで画質を上げる",
    free: "無料プランを利用中です。",
    activeUntil: "Infinityは{{date}}まで有効です。",
    renews: "{{date}}に自動更新されます。",
    endsAt: "サブスクリプションは解約済みで、{{date}}に終了します。",
    pastDue: "前回の請求に失敗しました。Infinityを失わないようカードを更新してください。",
    waiting: "支払いを確認しています…",
    subscribe: "登録する",
    monthly: "月額",
    yearly: "年額",
    automatic: "カード（自動更新）",
    manage: "支払いを管理",
    refund: "返金をリクエスト",
    refundDetail: "支払いから7日以内なら取り消せます：{{amount}}、{{date}}まで。",
    refundConfirm: "返金をリクエストしますか？",
    refundConfirmDetail: "同じ支払い方法に返金され、Infinityはすぐに終了します。",
    refunded: "返金をリクエストしました。",
    unavailable: "サブスクリプションはまだ利用できません。",
    success: "お支払いを受け付けました。ありがとうございます！",
    canceled: "お支払いはキャンセルされました。",
    error: "うまくいきませんでした。もう一度お試しください。",
    no: "なし",
    tagRow: "カスタムユーザータグ",
    guildProfilesRow: "コミュニティごとのプロフィール",
    badgeRow: "プロフィールバッジ",
    communitiesRow: "コミュニティ",
    savedRow: "保存したメッセージ",
    animatedEmojiRow: "アニメーション絵文字",
    expressionsRow: "どこでも絵文字とスタンプ",
    animatedProfileRow: "アニメーションアバターとバナー",
    earlyAccessRow: "新機能の先行アクセス",
    themesRow: "カスタムテーマ",
    pixOption: "Pix（今回の期間のみ）",
    pixHint: "銀行アプリでPixを選び、QRコードを読み取るかコードをコピーして貼り付けてください。",
    pixQrAlt: "PixのQRコード",
    pixCopy: "Pixコードをコピー",
    pixCopied: "Pixコードをコピーしました",
    pixWaiting: "お支払いを待っています",
    pixExpiresIn: "あと{{time}}で期限切れ",
    pixExpired: "このPixは期限切れです。続けるには新しく発行してください。",
    pixNew: "Pixを再発行",
    pixPaid: "Pixを受け取りました！Infinityが有効になりました。",
    forMe: "自分用",
    asGift: "ギフト",
    buyGift: "ギフトを購入",
    giftReady: "ギフトの準備ができました！リンクをコピーして渡したい人に送ってください。",
    giftClaimed: "ギフトを受け取りました！Infinityがアカウントに追加されました。",
    gifts: "ギフト",
    giftsEmpty: "まだギフトを購入していません。",
    giftCode: "ギフトコード",
    giftRedeem: "受け取る",
    giftCopyLink: "リンクをコピー",
    giftLinkCopied: "リンクをコピーしました",
    giftClaimedBy: "{{name}}が受け取りました",
    giftHint: "ギフトコードをお持ちですか？ここで受け取れます。購入したギフトは下に表示されます。",
  },
  telas: {
    subscription: "Infinity",
    conta: "アカウント",
    privacidade: "プライバシー",
    conexoes: "連携",
    voz: "オーディオ",
    video: "ビデオ",
    avisos: "通知",
    aplicativos: "アプリケーション",
    aparencia: "外観",
    batePapo: "チャット",
    acessibilidade: "アクセシビリティ",
    idioma: "言語",
    aplicativo: "アプリを入手",
    atalhos: "ショートカット",
    desktop: "デスクトップアプリ",
    avancado: "詳細設定",
    servidor: "サーバー",
    comunicado: "システムのお知らせ",
    denuncias: "通報",
    publicacoes: "デプロイ",
  },
  grupos: {
    conta: "アカウント",
    app: "アプリの設定",
    desenvolvedor: "開発者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "ログイン情報",
    dispositivos: "デバイス",
    usuariosBloqueados: "ブロックしたユーザー",
    aplicativosAutorizados: "認証済みアプリ",
    sessoes: "セッション",
    amigosEDms: "フレンドとダイレクトメッセージ",
    compartilhamentoDeAtividade: "アクティビティの共有",
    visibilidadeDoPerfil: "プロフィールの公開範囲",
    exportarDados: "データをエクスポート",
    exclusaoDeDados: "データを削除",
    tema: "テーマ",
    corDeDestaque: "アクセントカラー",
    interface: "インターフェース",
    listaDeCanais: "チャンネル一覧",
    zoomDoApp: "アプリの拡大率",
    escalaDaFonte: "チャットの文字サイズ",
    modoStreamer: "配信時のプライバシー",
    cursores: "カーソル",
    movimento: "モーション",
    textoEmVoz: "テキスト読み上げ",
    teclado: "キーボード",
    formatoDaHora: "時刻の表示形式",
    idiomaDaInterface: "表示言語",
    dispositivosDeVoz: "デバイス",
    testeDoMicrofone: "マイクのテスト",
    modoDeEntrada: "入力モード",
    sensibilidade: "入力感度",
    qualidade: "品質",
    camera: "カメラ",
    transmissao: "配信",
    exibicao: "表示",
    entrada: "入力",
    midia: "メディア",
    geral: "全般",
    preferenciaDeMencao: "メンションの設定",
    sons: "サウンド",
  },
};
