export const configuracoes = {
  efeitos: {
    titulo: "ポインターの効果",
    detalhe: "画面の上に描く軌跡と火花です。最初は切ってあり、動きを控える設定にしていれば自分で消えます。",
    rastro: "ポインターの軌跡",
    rastroDetalhe: "ポインターを追い、後ろから薄れていく線です。",
    faisca: "クリックの火花",
    faiscaDetalhe: "押した場所から飛び出す短い線です。",
    cor: "色",
    espessura: "太さ",
    comprimento: "長さ",
    tamanho: "大きさ",
    quantidade: "数",
  },
  email: {
    verificarTitulo: "メールアドレスを確認してください",
    verificarDetalhe: "確認済みの人しか書き込めないコミュニティがあります。ひと押しで済みます。",
    enviar: "リンクを送る",
    enviado: "受信箱をご覧ください。リンクは一日もちます。",
    falhou: "メールを送れませんでした。",
    confirmado: "メールを確認しました",
    confirmadoDetalhe: "これで完了です。確認を求めるコミュニティでも書き込めます。",
    linkIncompleto: "リンクが欠けています",
    linkIncompletoDetalhe: "アドレスにコードがありません。メールのリンクをそのまま開いてください。",
    confirmando: "確認しています…",
    expirou: "このリンクは使用済みか、期限が切れています。",
    irParaOApp: "アプリへ",
  },
  tema: {
    indisponivel: "テーマを開けません",
    indisponivelDetalhe: "公開した人が削除したか、リンクが違います。",
    indisponivelLinha: "テーマを開けません。公開した人が削除したか、リンクが違います。",
    importar: "テーマを取り込む",
    importarCurto: "取り込む",
    importarDetalhe: "今のテーマを置き換えます。あとから 設定 > 外観 > テーマスタジオ で編集できます。",
    porAutor: "作者: {{autor}}",
    umaCorTrocada: "1 色を変更",
    coresTrocadas: "{{quantas}} 色を変更",
    avisoDeCss: "このテーマには作者の CSS が入っており、CSS は画面のどこにでも手が届きます。信頼できる人のものだけを取り込んでください。",
    soCores: "このテーマは色だけを変えます。外部の CSS はありません。",
    aplicar: "適用",
    previaSemMotor: "プレビューではエンジンが動きません。入れると見られます。",
    motorAnimado: "{{motor}}（アニメーション）",
  },
  sair: "ログアウト",
  versoes: {
    termos: "利用規約",
    privacidade: "プライバシーポリシー",
    copiar: "クリックでコピー",
    copiado: "コピーしました",
  },
  telas: {
    conta: "アカウント",
    privacidade: "プライバシー",
    conexoes: "連携",
    voz: "オーディオ",
    video: "ビデオ",
    avisos: "通知",
    aplicativos: "アプリケーション",
    aparencia: "外観",
    batePapo: "チャット",
    acessibilidade: "アクセシビリティ",
    idioma: "言語",
    aplicativo: "アプリを入手",
    atalhos: "ショートカット",
    desktop: "デスクトップアプリ",
    avancado: "詳細設定",
    servidor: "サーバー",
    comunicado: "システムのお知らせ",
    denuncias: "通報",
    publicacoes: "デプロイ",
  },
  grupos: {
    conta: "アカウント",
    app: "アプリの設定",
    desenvolvedor: "開発者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "ログイン情報",
    dispositivos: "デバイス",
    usuariosBloqueados: "ブロックしたユーザー",
    aplicativosAutorizados: "認証済みアプリ",
    sessoes: "セッション",
    amigosEDms: "フレンドとダイレクトメッセージ",
    compartilhamentoDeAtividade: "アクティビティの共有",
    visibilidadeDoPerfil: "プロフィールの公開範囲",
    exportarDados: "データをエクスポート",
    exclusaoDeDados: "データを削除",
    tema: "テーマ",
    corDeDestaque: "アクセントカラー",
    interface: "インターフェース",
    listaDeCanais: "チャンネル一覧",
    zoomDoApp: "アプリの拡大率",
    escalaDaFonte: "チャットの文字サイズ",
    modoStreamer: "配信時のプライバシー",
    cursores: "カーソル",
    movimento: "モーション",
    textoEmVoz: "テキスト読み上げ",
    teclado: "キーボード",
    formatoDaHora: "時刻の表示形式",
    idiomaDaInterface: "表示言語",
    dispositivosDeVoz: "デバイス",
    testeDoMicrofone: "マイクのテスト",
    modoDeEntrada: "入力モード",
    sensibilidade: "入力感度",
    qualidade: "品質",
    camera: "カメラ",
    transmissao: "配信",
    exibicao: "表示",
    entrada: "入力",
    midia: "メディア",
    geral: "全般",
    preferenciaDeMencao: "メンションの設定",
    sons: "サウンド",
  },
};
