export const conversa = {
  lista: {
    carregando: "メッセージを読み込んでいます…",
    carregandoMais: "読み込み中…",
    verMais: "上にスクロールするともっと見られます",
    semHistorico: "履歴を表示できません",
    semHistoricoDetalhe: "あなたのロールには #{{canal}} の履歴を読む権限がありません。ここにいる間は新しいメッセージが表示され続けます。",
    boasVindas: "#{{canal}} へようこそ",
    boasVindasDetalhe: "ここが #{{canal}} チャンネルの始まりです。",
  },
  data: {
    hoje: "今日",
    ontem: "昨日",
    hojeAs: "今日 {{hora}}",
    ontemAs: "昨日 {{hora}}",
  },
  digitando: {
    um: "{{nome}} が入力中…",
    dois: "{{primeiro}} と {{segundo}} が入力中…",
    varios: "{{quantidade}} 人が入力中…",
  },
  mensagem: {
    usou: "が使用",
    fixada: "ピン留め済み",
    editado: "(編集済み)",
    ignorada: "ミュートしている相手からのメッセージです。",
    mostrar: "表示",
    escPara: "Esc で",
    cancelar: "キャンセル",
    enterParaSalvar: "Enter で保存",
    falhou: "送信できませんでした。もう一度試す",
    naoLidasDaqui: "ここから未読にしました。",
    linkCopiado: "リンクをコピーしました。",
    idCopiado: "ID をコピーしました。",
    naoDeuParaCopiar: "ブラウザがコピーを許可しませんでした。",
    apagarTitulo: "メッセージを削除しますか？",
    apagarDescricao: "チャンネルの全員から消えます。元に戻せません。",
    apagarAcao: "削除",
    citacaoAnexo: "クリックして添付ファイルを見る",
    citacaoSumiu: "元のメッセージはもうありません。",
    reagirCom: "{{emoji}} でリアクション — 長押しでスーパーリアクション",
    segureParaSuper: "{{emoji}} — 長押しでスーパーリアクション",
  },
  acoes: {
    reagir: "リアクション",
    responder: "返信",
    encaminhar: "転送",
    favoritar: "メッセージを保存",
    tirarDosFavoritos: "保存から外す",
    marcarNaoLida: "未読にする",
    copiarLink: "メッセージのリンクをコピー",
    copiarId: "メッセージ ID をコピー",
    fixar: "メッセージをピン留め",
    desafixar: "ピン留めを外す",
    editar: "編集",
    apagar: "削除",
    mais: "その他",
    adicionarReacao: "リアクションを追加",
    superReagirCom: "{{emoji}} でスーパーリアクション",
    fixarMensagem: "メッセージをピン留め",
    desafixarMensagem: "メッセージのピン留めを外す",
    editarMensagem: "メッセージを編集",
    apagarMensagem: "メッセージを削除",
  },
  mencao: {
    cargo: "ロールのメンション",
    pessoa: "メンション",
    alguem: "だれか",
    cargoSemNome: "ロール",
    here: "オンラインの人に通知します",
    everyone: "サーバー全員に通知します",
  },
  codigo: {
    copiar: "コピー",
    copiado: "コピーしました",
    copiarAria: "コードをコピー",
    copiadoAria: "コードをコピーしました",
    recolher: "折りたたむ",
    expandir: "展開",
    verInteiro: "ファイル全体を表示",
    maisOpcoes: "その他の操作",
    baixar: "ダウンロード",
    recolherLinhas: "折りたたむ（{{linhas}} 行）",
    expandirLinhas: "展開（{{linhas}} 行）",
    mudarIdioma: "言語を変更",
    procurarIdioma: "言語コードを検索…",
    nenhumIdioma: "該当する言語がありません。",
    quebrarTexto: "テキストを折り返す",
  },
  caixa: {
    escrever: "#{{canal}} にメッセージを送信",
    escreverSemCanal: "メッセージを送信",
    semPermissao: "このチャンネルにメッセージを送る権限がありません",
    solteParaAnexar: "ドロップで添付",
    respondendoPara: "返信先",
    vaiNotificar: "相手に通知されます",
    naoVaiNotificar: "相手に通知されません",
    ligado: "オン",
    desligado: "オフ",
    pararDeResponder: "返信をやめる",
    mais: "その他",
    enviarArquivo: "ファイルを送る",
    criarEnquete: "アンケートを作る",
    expressoes: "絵文字・GIF・スタンプ",
    enviar: "送信",
    aguardandoEnvio: "アップロードを待っています",
    modoLento: "低速モード中（{{tempo}}）",
    modoLentoDica: "低速モードは {{segundos}} 秒に設定されています。次のメッセージまで待ってください。",
  },
  anexos: {
    enviando: "アップロード中…",
    modificar: "{{arquivo}} を編集",
    remover: "{{arquivo}} を外す",
    ver: "{{arquivo}} を見る",
    mostrarSpoiler: "ネタバレを表示：{{arquivo}}",
    spoiler: "ネタバレ",
    spoilerTitulo: "ネタバレ",
    editarTitulo: "添付ファイルを編集",
    nomeDoArquivo: "ファイル名",
    descricao: "代替テキストの説明",
    descricaoDica: "スクリーンリーダー向けにこのメディアを説明してください",
    marcarSpoiler: "ネタバレとして扱う",
    cancelar: "キャンセル",
    salvar: "保存",
  },
  cartao: {
    tocador: "プレーヤー",
    abrir: "{{destino}} を開く",
    tocar: "{{titulo}} を再生",
    video: "動画",
    verImagem: "画像を見る",
  },
  enquete: {
    titulo: "アンケート",
    encerrada: "アンケート終了",
    variasRespostas: "アンケート — 複数回答",
    umVoto: "{{quantidade}} 票",
    votos: "{{quantidade}} 票",
    umVotoNoTotal: "合計 {{quantidade}} 票",
    votosNoTotal: "合計 {{quantidade}} 票",
    encerraEm: "{{quando}} に終了",
    encerrarAgora: "今すぐ終了",
  },
  fixadas: {
    titulo: "ピン留めされたメッセージ",
    vazio: "このチャンネルにはまだピン留めされたメッセージがありません。",
    desafixar: "ピン留めを外す",
    anexo: "（添付ファイル）",
    enquete: "（アンケート）",
    dicaRotulo: "ヒント：",
    dica: "「メッセージの管理」権限があれば、メッセージのメニューから直接ピン留めできます。",
  },
  encaminhar: {
    titulo: "メッセージを転送",
    paraOnde: "どこへ？",
    semTexto: "（本文のないメッセージ）",
    nenhumLugar: "その名前の場所はありません。",
    canais: "チャンネル",
    conversas: "ダイレクトメッセージ",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Klipy で検索",
    figurinha: "スタンプ",
    buscarFigurinha: "ぴったりのスタンプを探す",
    buscarEmoji: "ぴったりの絵文字を探す",
    buscarReacao: "ぴったりのリアクションを探す",
    adicionarEmoji: "絵文字を追加",
    limparBusca: "検索を消す",
  },
  busca: {
    fechar: "検索を閉じる",
    procurando: "検索中…",
    resultado: "{{quantos}} 件",
    resultados: "{{quantos}} 件",
    nadaCom: "{{termo}} に合うものはここにありません。",
    soOsQuePodeLer: "検索は、あなたが読めるチャンネルだけを見ます。",
  },
  entrada: {
    titulo: "受信箱",
    naoLidas: "未読",
    salvas: "保存済み",
    mencoes: "メンション",
    fimTitulo: "最後まで来ました",
    fimDetalhe: "読むものはもうありません。新しいメッセージが届いたら、ここに出ます。",
    semSalvosTitulo: "保存したものはありません",
    semSalvosDetalhe: "Shift を押しながらメッセージのしおりを押すと、取っておいてあとで読めます。",
    tirarDosSalvos: "保存から外す",
    semMencoesTitulo: "メンションはまだありません",
    semMencoesDetalhe: "あなたへのメンションが、直近 7 日ぶんここに出ます。",
  },
  forum: {
    descricao: "話題ごとに別の会話になります。おしゃべりの途中で埋もれては困る質問に向いています。",
    novoAssunto: "新しい話題",
    vazio: "まだ話題がありません。最初のひとつを始めれば、会話は最初から整ったままです。",
    titulo: "タイトル",
    doQueSeTrata: "どんな話ですか？",
    primeiraMensagem: "最初のメッセージ",
    conteDoCaso: "くわしく書いてください",
  },
};
