export const perfil = {
  carregando: "読み込み中…",
  editar: "プロフィールを編集",
  mensagem: "メッセージ",
  abrirConversa: "会話を開く",
  verCompleto: "プロフィール全体を見る",
  convidarParaServidor: "サーバーに招待",
  semServidores: "サーバーがありません",
  conviteEnviado: "{{nome}} さんに招待を送りました。",
  moderador: "モデレーター表示で開く",
  mais: "その他",
  ignorar: "ミュート",
  deixarDeIgnorar: "ミュートを解除",
  copiarId: "ユーザー ID をコピー",
  idCopiado: "ID をコピーしました。",
  conexoes: "接続",
  membroDesde: "メンバー登録日",
  sobre: "自己紹介",
  cargosTitulo: "ロール",
  visaoGeral: "概要",
  amigosEmComum: "共通のフレンド（{{quantidade}}）",
  servidoresEmComum: "共通のサーバー（{{quantidade}}）",
  amizade: {
    amigo: "フレンド",
    pedidoEnviado: "フレンド申請を送信済み",
    respondaAbaixo: "申請が届いています — 下で返答してください",
    adicionar: "フレンドに追加",
    teMandouPedido: "フレンド申請が届きました",
    aceitar: "承認",
    desfazer: "フレンドを解除",
    desfazerTitulo: "{{nome}} さんをフレンドから外しますか？",
    desfazerDescricao: "フレンドではなくなります。ダイレクトメッセージは履歴に残り、あとでまた追加できます。",
    bloquear: "ブロック",
    bloquearTitulo: "{{nome}} さんをブロックしますか？",
    bloquearDescricao: "フレンドではなくなり、ダイレクトメッセージは受け付けなくなり、相手はフレンド申請を送れなくなります。",
    linkCopiado: "フレンドではありません — リンクをコピーしたので、自分で送ってください。",
  },
  recado: {
    escrever: "@{{usuario}} さんにメッセージ",
    enviar: "送信",
    enviada: "メッセージを送信しました",
    falhou: "送信できませんでした。会話から試してください。",
  },
  cartao: {
    trocarFaixa: "カードのバナーを変更",
    trocarFaixaCurto: "バナーを変更",
    trocarFoto: "プロフィール画像を変更",
    trocarFotoCurto: "画像を変更",
    suaEtiqueta: "あなたのタグ",
    editarEtiqueta: "クリックしてタグを編集",
    conteAlgo: "自分のことを書いてください",
    adicionarStatus: "ステータスを追加",
    adicionarDescricao: "クリックして説明を追加",
    cargo: "ロール",
    cargos: "ロール",
    cargosCom: "ロール — {{quantidade}}",
    tirarCargo: "ロール「{{cargo}}」を外す",
  },
  cargos: {
    adicionar: "ロールを追加",
    procurar: "ロールを検索",
  },
  etiqueta: {
    escolher: "サーバータグを選ぶ",
    nenhuma: "サーバータグなし",
    semEtiqueta: "タグがあるサーバーはありません",
  },
  emblemas: {
    doServidor: "このサーバーのバッジ",
    limite: "バッジは {{quantidade}} 個まで付けられます。",
  },
  nota: {
    vazia: "クリックしてメモを書く",
    rotulo: "メモ（自分だけが見られます）",
  },
  status: {
    titulo: "ステータス",
    definir: "ステータスを設定",
    escolherEmoji: "絵文字を選ぶ",
    tirarEmoji: "絵文字を外す",
    oQuePensa: "いま何を考えていますか？",
    limparAgora: "今すぐステータスを消す",
    naoLimpar: "消さない",
    limpar30m: "30 分後に消す",
    limpar1h: "1 時間後に消す",
    limpar4h: "4 時間後に消す",
    limparHoje: "今日中に消す",
    limparAmanha: "明日消す",
    comHora: "{{prazo}}（{{hora}}）",
  },
  presenca: {
    disponivel: "オンライン",
    ausente: "退席中",
    naoPerturbar: "取り込み中",
    naoPerturbarDetalhe: "新しいメッセージの通知は届きません",
    invisivel: "オフライン表示",
    invisivelDetalhe: "ほかの人にはオフラインに見えます",
  },
  menu: {
    mudarDeConta: "アカウントを切り替え",
    gerenciarContas: "アカウントを管理",
  },
  editor: {
    decoracao: "アバターの装飾を変更",
    naoSalvo: "変更の保存をお忘れなく！",
    principal: "メインプロフィール",
  },
};
