export const servidor = {
  titulo: "サーバー設定",
  auditoria: {
    titulo: "監査ログ",
    porUsuario: "人で絞り込む",
    porAcao: "操作で絞り込む",
    vazio: "この絞り込みではまだ何も記録されていません。",
    motivo: "理由：",
  },
  banimentos: {
    titulo: "サーバーのBANリスト",
    descricao: "ここにいる人は新しい招待でも戻れません。BANを解除すればすぐにアクセスが戻ります。",
    procurar: "ユーザー名でBANを検索",
    vazioTitulo: "BANはありません",
    vazio: "まだ誰もBANしていません…でも必要になったら、ためらわずに。",
    desbanir: "BANを解除",
  },
  excluir: {
    titulo: "サーバーを削除",
    aviso: "これは取り消せません。",
  },
  emblemas: {
    titulo: "バッジ",
    vazio: "バッジはまだありません。",
    novo: "新しいバッジ",
  },
  convites: {
    titulo: "招待",
    descricao: "このサーバーの有効な招待リンクすべて。",
    vazio: "招待はまだ作られていません。",
    revogar: "招待を取り消す",
  },
  integracoes: {
    titulo: "連携",
    descricao: "Webhook はアカウントなしでチャンネルに投稿できるアドレスです。ビルドが通ったとき、誰かが問い合わせを開いたとき、あるいはスクリプトから送りたい何かを知らせるのに使えます。",
    novo: "新しい Webhook",
    vazio: "Webhook はまだありません。ひとつ作って、メッセージの発信元にしたい場所に URL を貼ってください。",
    canal: "チャンネル",
    apagar: "Webhook を削除",
    comoUsar: "使い方",
    comoUsarTexto: "JSON を付けて POST を送ってください。形式は Discord と同じなので、すでにあるスクリプトがそのまま動きます：",
  },
  engajamento: {
    titulo: "にぎわい",
    descricao: "新しい人が来たとき空っぽに見えないよう、サーバーが自分でやること。",
    sistema: "システムメッセージ",
    boasVindas: "誰かが参加したら歓迎メッセージを送る",
    sorteio: "下に自分の文章がない場合、文はランダムに選ばれます — 同じ文ばかりだとすぐ飽きます。",
    canalDoSistema: "システムメッセージのチャンネル",
    mensagem: "歓迎メッセージ",
    deixeVazio: "空のままにすると、用意された文から抽選します",
  },
  automod: {
    titulo: "自動モデレーション",
    descricao: "メッセージが存在する前から、勝手に見張ってくれるフィルターです。サーバーを管理する人は決してフィルターされず、除外ロールもそのまま通ります。",
    palavras: {
      titulo: "自分で決めた単語をブロック",
      descricao: "誰も書けない単語のリスト。",
    },
    mencoes: {
      titulo: "メンション連投をブロック",
      descricao: "一度にメンションが多すぎるメッセージをブロックします。",
    },
    links: {
      titulo: "リンクをブロック",
      descricao: "チャットに貼られたアドレスをすべて止めます。",
    },
    definir: "設定する",
    nomeDaRegra: "ルールの名前",
    bloqueadas: "ブロックする単語",
    digiteEnter: "入力して Enter を押してください",
    comparacao: "照合は大文字・小文字、アクセント、句読点を無視します — そして単語の中の単語は拾いません。",
    aPartirDe: "何回のメンションからブロックするか",
    oQueFazer: "どうするか",
    canalDoAlerta: "通知するチャンネル",
    escolhaCanal: "チャンネルを選ぶ",
    castigo: "タイムアウト（分）",
    isentos: "除外するロール",
    semCargos: "まだロールが作られていません。",
    salvarRegra: "ルールを保存",
    apagar: "ルールを削除",
    excluirTitulo: "この自動モデレーションのルールを削除しますか？",
    excluirDescricao: "サーバーはすぐにこのルールでの絞り込みをやめます。作り直せますが、今の設定は失われます。",
    excluirAcao: "ルールを削除",
  },
  cargos: {
    titulo: "ロール",
    descricao: "ロールは名前と色と権限を与えます。リストで上にいる人が下の人より強く、自分と同じか上のロールには誰も手を出せません。",
    criar: "ロールを作る",
    vazio: "まだロールがありません。",
    abaExibicao: "表示",
    abaPermissoes: "権限",
    abaMembros: "メンバー — {{quantos}}",
    everyone: "サーバーの全員に効きます。ほかのロールはこの上に積み重なります。",
    nomeDoCargo: "ロールの名前",
    cor: "ロールの色",
    corDica: "そのロールを持つ人の名前を、メンバー一覧とチャットで色付けします。",
    semCor: "色なし",
    corPersonalizada: "好きな色",
    estilo: "名前のスタイル",
    segundaCor: "2 つめの色",
    segundaCorDica: "これがないとグラデーションは単色に戻ります — 消えるわけではありません。",
    limparSegundaCor: "2 つめの色を消す",
    icone: "アイコン",
    iconeDica: "そのロールを持つ人のプロフィールカードで、ロールの横に出ます。",
    exibirSeparado: "ほかのメンバーと分けて表示",
    exibirSeparadoDica: "そのロールはメンバー一覧に自分の区画を持ちます。",
    permitirMencionar: "このロールへのメンションを許可",
    permitirMencionarDica: "誰でも、そのロールを持つ全員に通知できるようになります。",
    semPoderDeConceder: "{{descricao}}（あなたにはこの権限を与える権限がありません）",
    adicionar: "このロールに誰かを追加",
    tirar: "ロールを外す",
    semNinguem: "このロールを持つ人はまだいません。",
    apagar: "ロールを削除",
    excluirTitulo: "ロール「{{nome}}」を削除しますか？",
    excluirDescricao: "このロールを持つ人は、それが与えていたものをすべて失います。取り消せません。",
    excluirAcao: "ロールを削除",
  },
  membros: {
    procurar: "名前かユーザー名で検索",
    membroDesde: "参加日",
    vazio: "誰も見つかりません。",
    acoesPara: "{{nome}} の操作",
    deCastigo: "タイムアウト中",
    tirarCastigo: "タイムアウトを解除",
    castigo5min: "5 分",
    castigo1h: "1 時間",
    castigo1d: "1 日",
    castigo1s: "1 週間",
    expulsar: "追い出す",
    expulsarTitulo: "{{nome}} を追い出しますか？",
    expulsarDescricao: "はすぐに {{servidor}} から抜けます。招待があれば戻れます — 追い出しても復帰は防げません。",
    banir: "BANする",
    banirTitulo: "{{nome}} を BAN しますか？",
    banirDescricao: "は {{servidor}} から抜け、BAN が解除されるまで招待があっても戻れません。",
    motivo: "理由（任意）",
    motivoDica: "監査ログに残ります",
  },
  perfil: {
    titulo: "サーバープロフィール",
    descricao: "一覧や招待リンクでは、あなたのサーバーはこう表示されます。",
    icone: "アイコン",
    faixa: "上部のバナー",
    nomeDoServidor: "サーバー名",
    campoDescricao: "説明",
    doQueE: "このサーバーは何のためのもの？",
    comprimido: "アップロード前に圧縮：{{economia}}",
  },
  etiqueta: {
    titulo: "サーバータグ",
    descricao: "メンバーの名前の横に出る、最大 4 文字の札です — チャットでも人の一覧でも。ここでは無料：ブーストもレベルも要りません。",
    escolhaNome: "名前を選ぶ",
    limite: "最大 4 文字、英数字。",
    escolhaInsignia: "バッジを選ぶ",
    voce: "あなた",
    fala1: "誰か遊ばない？",
    fala2: "私のタグ見て！",
    fala3: "うわ、どうやって手に入れたの",
  },
  expressoes: {
    comoUsar: "このサーバーの全員が使える絵文字を最大 {{limite}} 個まで追加できます。送るにはチャットで :名前: と入力してください。",
    imagem: "画像",
    enviadoPor: "アップロードした人",
    semEmoji: "まだ絵文字がありません。",
    figurinhas: "スタンプ",
    enviarFigurinha: "スタンプをアップロード",
    nomeDaFigurinha: "スタンプの名前",
    exemploFigurinha: "例：子猫のハグ",
    figurinhaGrande: "スタンプが {{limite}} を超えています。",
    deixaPraLa: "やめておく",
    sons: "サウンドボード",
    enviarSom: "サウンドをアップロード",
    nomeDoSom: "サウンドの名前",
    semSom: "まだサウンドがありません。",
    somGrande: "サウンドが {{limite}} を超えています。",
    emojiRelacionado: "関連する絵文字",
    ouvir: "再生",
    ouvirAssim: "この音量で再生",
    volumeDe: "{{nome}} の音量",
    volumeDica: "サーバーの全員に効きます。それでも各自、通話のパネルで自分の分だけ音を下げられます。",
    falhaEnvio: "ファイルをアップロードできませんでした。",
    excluirTitulo: "{{tipo}}「{{nome}}」を削除しますか？",
    excluirDescricao: "全員のサーバーから消えます。すでに使われたメッセージはそのまま残ります。",
  },
};
