export const servidor = {
  titulo: "サーバー設定",
  auditoria: {
    todasAsAcoes: "すべての操作",
    todosOsUsuarios: "すべての人",
    filtroMembros: "メンバー",
    filtroCanais: "チャンネル",
    filtroEmojis: "絵文字",
    filtroServidor: "サーバー",
    titulo: "監査ログ",
    porUsuario: "人で絞り込む",
    porAcao: "操作で絞り込む",
    vazio: "この絞り込みではまだ何も記録されていません。",
    motivo: "理由：",
  },
  banimentos: {
    titulo: "サーバーのBANリスト",
    descricao: "ここにいる人は新しい招待でも戻れません。BANを解除すればすぐにアクセスが戻ります。",
    procurar: "ユーザー名でBANを検索",
    vazioTitulo: "BANはありません",
    vazio: "まだ誰もBANしていません…でも必要になったら、ためらわずに。",
    desbanir: "BANを解除",
  },
  excluir: {
    tudoVai: "{{servidor}} のチャンネル、メッセージ、招待はすべて {{membros}} 人のメンバーから削除されます。あとから誰も元に戻せません。",
    digite: "確認のため {{servidor}} と入力してください",
    titulo: "サーバーを削除",
    aviso: "これは取り消せません。",
  },
  emblemas: {
    apagarDescricao: "着けている人みんなから外れます。取り消せません。",
    titulo: "バッジ",
    vazio: "バッジはまだありません。",
    novo: "新しいバッジ",
  },
  convites: {
    revogarTitulo: "招待を取り消しますか？",
    revogarAcao: "取り消す",
    revogarDescricao: "リンク {{codigo}} はすぐ使えなくなります。すでにそこから入った人はサーバーに残ります。",
    titulo: "招待",
    descricao: "このサーバーの有効な招待リンクすべて。",
    vazio: "招待はまだ作られていません。",
    revogar: "招待を取り消す",
  },
  integracoes: {
    opcionais: "username と avatar_url は任意で、メッセージごとに効きます。上限は 5 秒あたり 5 件です。",
    apagarDescricao: "URL はすぐ使えなくなります。すでに送られたメッセージはチャンネルに残ります。",
    titulo: "連携",
    descricao: "Webhook はアカウントなしでチャンネルに投稿できるアドレスです。ビルドが通ったとき、誰かが問い合わせを開いたとき、あるいはスクリプトから送りたい何かを知らせるのに使えます。",
    novo: "新しい Webhook",
    vazio: "Webhook はまだありません。ひとつ作って、メッセージの発信元にしたい場所に URL を貼ってください。",
    canal: "チャンネル",
    apagar: "Webhook を削除",
    comoUsar: "使い方",
    comoUsarTexto: "JSON を付けて POST を送ってください。形式は Discord と同じなので、すでにあるスクリプトがそのまま動きます：",
  },
  engajamento: {
    semCanal: "システムチャンネルなし",
    titulo: "にぎわい",
    descricao: "新しい人が来たとき空っぽに見えないよう、サーバーが自分でやること。",
    sistema: "システムメッセージ",
    boasVindas: "誰かが参加したら歓迎メッセージを送る",
    sorteio: "下に自分の文章がない場合、文はランダムに選ばれます — 同じ文ばかりだとすぐ飽きます。",
    canalDoSistema: "システムメッセージのチャンネル",
    mensagem: "歓迎メッセージ",
    deixeVazio: "空のままにすると、用意された文から抽選します",
  },
  automod: {
    titulo: "自動モデレーション",
    descricao: "メッセージが存在する前から、勝手に見張ってくれるフィルターです。サーバーを管理する人は決してフィルターされず、除外ロールもそのまま通ります。",
    palavras: {
      titulo: "自分で決めた単語をブロック",
      descricao: "誰も書けない単語のリスト。",
    },
    mencoes: {
      titulo: "メンション連投をブロック",
      descricao: "一度にメンションが多すぎるメッセージをブロックします。",
    },
    links: {
      titulo: "リンクをブロック",
      descricao: "チャットに貼られたアドレスをすべて止めます。",
    },
    definir: "設定する",
    nomeDaRegra: "ルールの名前",
    bloqueadas: "ブロックする単語",
    digiteEnter: "入力して Enter を押してください",
    comparacao: "照合は大文字・小文字、アクセント、句読点を無視します — そして単語の中の単語は拾いません。",
    aPartirDe: "何回のメンションからブロックするか",
    oQueFazer: "どうするか",
    canalDoAlerta: "通知するチャンネル",
    escolhaCanal: "チャンネルを選ぶ",
    castigo: "タイムアウト（分）",
    isentos: "除外するロール",
    semCargos: "まだロールが作られていません。",
    salvarRegra: "ルールを保存",
    apagar: "ルールを削除",
    excluirTitulo: "この自動モデレーションのルールを削除しますか？",
    excluirDescricao: "サーバーはすぐにこのルールでの絞り込みをやめます。作り直せますが、今の設定は失われます。",
    excluirAcao: "ルールを削除",
  },
  cargos: {
    titulo: "ロール",
    descricao: "ロールは名前と色と権限を与えます。リストで上にいる人が下の人より強く、自分と同じか上のロールには誰も手を出せません。",
    criar: "ロールを作る",
    vazio: "まだロールがありません。",
    abaExibicao: "表示",
    abaPermissoes: "権限",
    abaMembros: "メンバー — {{quantos}}",
    everyone: "サーバーの全員に効きます。ほかのロールはこの上に積み重なります。",
    nomeDoCargo: "ロールの名前",
    cor: "ロールの色",
    corDica: "そのロールを持つ人の名前を、メンバー一覧とチャットで色付けします。",
    semCor: "色なし",
    corPersonalizada: "好きな色",
    estilo: "名前のスタイル",
    segundaCor: "2 つめの色",
    segundaCorDica: "これがないとグラデーションは単色に戻ります — 消えるわけではありません。",
    limparSegundaCor: "2 つめの色を消す",
    icone: "アイコン",
    iconeDica: "そのロールを持つ人のプロフィールカードで、ロールの横に出ます。",
    exibirSeparado: "ほかのメンバーと分けて表示",
    exibirSeparadoDica: "そのロールはメンバー一覧に自分の区画を持ちます。",
    permitirMencionar: "このロールへのメンションを許可",
    permitirMencionarDica: "誰でも、そのロールを持つ全員に通知できるようになります。",
    semPoderDeConceder: "{{descricao}}（あなたにはこの権限を与える権限がありません）",
    adicionar: "このロールに誰かを追加",
    tirar: "ロールを外す",
    semNinguem: "このロールを持つ人はまだいません。",
    apagar: "ロールを削除",
    excluirTitulo: "ロール「{{nome}}」を削除しますか？",
    excluirDescricao: "このロールを持つ人は、それが与えていたものをすべて失います。取り消せません。",
    excluirAcao: "ロールを削除",
  },
  membros: {
    procurar: "名前かユーザー名で検索",
    membroDesde: "参加日",
    vazio: "誰も見つかりません。",
    acoesPara: "{{nome}} の操作",
    deCastigo: "タイムアウト中",
    tirarCastigo: "タイムアウトを解除",
    castigo5min: "5 分",
    castigo1h: "1 時間",
    castigo1d: "1 日",
    castigo1s: "1 週間",
    expulsar: "追い出す",
    expulsarTitulo: "{{nome}} を追い出しますか？",
    expulsarDescricao: "はすぐに {{servidor}} から抜けます。招待があれば戻れます — 追い出しても復帰は防げません。",
    banir: "BANする",
    banirTitulo: "{{nome}} を BAN しますか？",
    banirDescricao: "は {{servidor}} から抜け、BAN が解除されるまで招待があっても戻れません。",
    motivo: "理由（任意）",
    motivoDica: "監査ログに残ります",
  },
  perfil: {
    titulo: "サーバープロフィール",
    descricao: "一覧や招待リンクでは、あなたのサーバーはこう表示されます。",
    icone: "アイコン",
    faixa: "上部のバナー",
    nomeDoServidor: "サーバー名",
    campoDescricao: "説明",
    doQueE: "このサーバーは何のためのもの？",
    comprimido: "アップロード前に圧縮：{{economia}}",
  },
  etiqueta: {
    titulo: "サーバータグ",
    descricao: "メンバーの名前の横に出る、最大 4 文字の札です — チャットでも人の一覧でも。ここでは無料：ブーストもレベルも要りません。",
    escolhaNome: "名前を選ぶ",
    limite: "最大 4 文字、英数字。",
    escolhaInsignia: "バッジを選ぶ",
    voce: "あなた",
    fala1: "誰か遊ばない？",
    fala2: "私のタグ見て！",
    fala3: "うわ、どうやって手に入れたの",
  },
  expressoes: {
    comoUsar: "このサーバーの全員が使える絵文字を最大 {{limite}} 個まで追加できます。送るにはチャットで :名前: と入力してください。",
    imagem: "画像",
    enviadoPor: "アップロードした人",
    semEmoji: "まだ絵文字がありません。",
    figurinhas: "スタンプ",
    enviarFigurinha: "スタンプをアップロード",
    nomeDaFigurinha: "スタンプの名前",
    exemploFigurinha: "例：子猫のハグ",
    figurinhaGrande: "スタンプが {{limite}} を超えています。",
    deixaPraLa: "やめておく",
    sons: "サウンドボード",
    enviarSom: "サウンドをアップロード",
    nomeDoSom: "サウンドの名前",
    semSom: "まだサウンドがありません。",
    somGrande: "サウンドが {{limite}} を超えています。",
    emojiRelacionado: "関連する絵文字",
    ouvir: "再生",
    ouvirAssim: "この音量で再生",
    volumeDe: "{{nome}} の音量",
    volumeDica: "サーバーの全員に効きます。それでも各自、通話のパネルで自分の分だけ音を下げられます。",
    falhaEnvio: "ファイルをアップロードできませんでした。",
    excluirTitulo: "{{tipo}}「{{nome}}」を削除しますか？",
    excluirDescricao: "全員のサーバーから消えます。すでに使われたメッセージはそのまま残ります。",
  },
  canal: {
    visaoGeral: "概要",
    nome: "チャンネル名",
    topico: "チャンネルの話題",
    topicoDica: "ここでは何の話をしますか？",
    modoLento: "一定の間隔につき、ひとり一件だけ送れます。メッセージやチャンネルを管理する人はそのまま通ります。",
    visibilidade: "内容の見え方",
    padrao: "既定",
    padraoDica: "チャンネルの内容はいつでも見えます。",
    spoiler: "ネタバレのチャンネル",
    spoilerDica: "このチャンネルをネタバレありとして印を付けると、展開や重い話題は誰かが見ると決めるまで隠れたままになります。",
    idade: "年齢制限のあるチャンネル",
    idadeDica: "入る人は、内容を見るために成人であることを確認する必要があります。",
    bitrateDica: "64 kbps を超えると、回線が弱い人のじゃまになることがあります。",
    qualidadeDeVideo: "映像の品質",
    automatica: "自動",
    limite: "人数の上限 — {{valor}}",
    pessoas: "{{quantos}} 人",
    semLimite: "上限なし",
    permissoesDescricao: "ここでは、このチャンネルで何が通用するかを変えます。「継承」のままのものは、引き続きロールに従います。",
    excluir: {
      titulo: "チャンネルを削除",
      historico: "{{canal}} の履歴はまるごと一緒に消えます。全員から。",
      digite: "確認のため {{canal}} と入力してください",
    },
  },
  moderacao: {
    titulo: "モデレーター表示",
    semPermissao: "これを見るには「メンバーのモデレート」の権限が必要です。",
    fecharEsc: "閉じる（Esc）",
    atividade: "サーバーでの活動",
    mensagens: "メッセージ",
    links: "リンク",
    midia: "メディア",
    acoesNaAuditoria: "監査ログの操作",
    moderacoesSofridas: "受けた処分",
    permissoes: "権限（{{quantas}}）",
    semPermissaoEspecial: "特別な権限はありません。",
    conta: "アカウント",
    entrouNoServidor: "サーバーに参加",
    contaCriadaEm: "アカウント作成日",
    deCastigoAte: "タイムアウト終了",
    formaDeAdesao: "参加の経緯",
    mensagem: "メッセージ",
    castigo: "タイムアウト",
    copiarId: "IDをコピー",
    idCopiado: "IDをコピーしました。",
    adicionarCargo: "ロールを追加",
    semCargos: "ロールが作られていません",
    soEveryone: "@everyone だけ。",
    voltar: "戻る",
    vazio: "ここには何もありません。",
    cinquenta: "新しい順に 50 件を表示しています。",
    irParaMensagem: "メッセージへ移動",
    precisaSerAmigo: "会話するには友だちになる必要があります。",
    expulsarDescricao: "すぐサーバーから抜けますが、招待があれば戻れます。",
    banirDescricao: "サーバーから抜け、BAN が解除されるまで招待があっても戻れません。",
    castigarTitulo: "{{nome}} をタイムアウトしますか？",
    castigoDescricao: "その間は、サーバーのどのチャンネルでも書くことも話すこともできません。",
    aplicarCastigo: "タイムアウトを適用",
    duracao: "分単位の長さ",
    informeDuracao: "分単位で長さを入れてください。",
  },
  abas: {
    expressoes: "表現",
    pessoas: "人",
    apps: "アプリ",
    moderacao: "モデレーション",
    banimentos: "BAN",
  },
};
