export const amizades = {
  ativosAgora: "Зараз активні",
  procurando: "Дивимось, хто поруч…",
  tudoTranquilo: "Поки тихо…",
  tudoTranquiloDetalhe: "Коли ви або друг зайдете в дзвінок, він з'явиться тут — і ви приєднаєтесь одним кліком.",
  emVoz: "У голосовому",
  voce: "Ви",
  soVoce: "Тільки ви",
  pessoas: "{{quantas}} осіб",
  voltarParaChamada: "Повернутися до дзвінка",
  entrarNaChamada: "Приєднатися",
  abrirCanal: "Відкрити {{canal}} на {{servidor}}",
  mensagensDiretas: "Особисті повідомлення",
  encontreConversa: "Знайти розмову",
  amigos: "Друзі",
  conversas: "Розмови",
  semConversas: "Розмов поки немає. Додайте друга, щоб почати.",
  semConversaComEsseNome: "Немає розмови з такою назвою.",
  abrirMenu: "Відкрити сервери та розмови",
  solicitacoes: "Запити на листування",
  pedidos: "Запити",
  spam: "Спам",
  pedidosPendentes: "Запити, що очікують",
  marcadosComoSpam: "Позначені як спам",
  aceitar: "Прийняти",
  ignorar: "Ігнорувати",
  marcarSpam: "Позначити як спам",
  semPedidos: "Немає запитів в очікуванні.",
  semPedidosDetalhe: "Той, хто вам не друг, але перебуває з вами на одному сервері, потрапляє сюди, не доходячи до ваших розмов.",
  semSpam: "Нічого не позначено як спам.",
  semSpamDetalhe: "Те, що відсіє фільтр спаму, або те, що позначите ви, залишиться на цій вкладці.",
  umServidorEmComum: "1 спільний сервер",
  servidoresEmComum: "Спільних серверів: {{quantos}}",
  semServidoresEmComum: "Спільних серверів немає",
};
