export const chamada = {
  conectando: "Підключення до дзвінка…",
  naoEntrou: "Не вдалося увійти в дзвінок",
  sair: "Вийти з дзвінка",
  sairDaVoz: "Вийти з голосового дзвінка",
  desconectar: "Відключитися",
  voltar: "Повернутися до дзвінка",
  voltarAosQuadros: "Повернутися до плиток дзвінка",
  fecharChat: "Закрити чат",
  carregandoPrevia: "Завантаження попереднього перегляду…",
  maisOpcoes: "Ще",
  deVideo: "Відеодзвінок",
  deVoz: "Голосовий дзвінок",
  alguem: "Хтось",
  volume: {
    entrada: "Гучність входу",
    saida: "Гучність виходу",
    live: "Гучність трансляції",
    liveComPorcento: "Гучність трансляції ({{porcento}}%)",
    liveSemSom: "Трансляція без звуку",
  },
  aparelhos: {
    entrada: "Пристрій входу",
    saida: "Пристрій виходу",
    camera: "Камера",
    microfone: "Мікрофон",
    saidaCurto: "Вихід",
    oDoSistema: "Системний",
    aDoSistema: "Системна",
    semEscolhaDeSaida: "Цей браузер не дає вибрати вихід — вирішує система.",
    espelhar: "Віддзеркалити мою камеру",
    configEntrada: "Налаштування входу",
    configSaida: "Налаштування виходу",
    configCamera: "Налаштування камери",
    configAudioEVideo: "Налаштування звуку та відео",
  },
  tela: {
    compartilhar: "Показати екран",
    compartilharAcao: "Показати",
    cancelar: "Скасувати",
    telas: "Екрани",
    janelas: "Вікна",
    somDoComputador: "Взяти звук комп’ютера",
    somDoSistema: "Взяти звук системи",
    configCompartilhamento: "Налаштування показу",
    mostrarSemVideo: "Показувати тих, хто без відео",
    semFontes: "Система не повернула жодного екрана чи вікна для показу.",
    pararDeCompartilhar: "Припинити показ",
    encerrarTransmissao: "Завершити трансляцію",
  },
  live: {
    etiqueta: "У прямому ефірі",
    etiquetaMaiuscula: "У ПРЯМОМУ ЕФІРІ",
    assistir: "Дивитися трансляцію",
    assistirPessoa: "Дивитися {{nome}}",
    pararDeAssistir: "Припинити дивитися",
  },
  membro: {
    mudarMeuApelido: "Змінити мій псевдонім",
    meuMicrofone: "Мій мікрофон",
    ouvirChamada: "Слухати дзвінок",
    copiarMeuId: "Копіювати мій ID",
    idCopiado: "ID скопійовано.",
    mensagem: "Повідомлення",
    silenciar: "Заглушити",
    alterarApelido: "Змінити псевдонім",
    cargos: "Ролі",
    semCargo: "Ролей не створено",
    moverPara: "Перемістити до",
    silenciarNoServidor: "Заглушити голос на сервері",
    desativarAudioNoServidor: "Вимкнути звук на сервері",
    desconectar: "Відключити",
    apelidoTitulo: "Ваш псевдонім на цьому сервері",
    apelidoDeAlguem: "Псевдонім {{nome}}",
    apelidoCampo: "Псевдонім",
    apelidoDicaPropria: "Діє тільки тут. Порожнє поле поверне ваше звичайне ім’я.",
    apelidoDicaDeOutro: "Діє тільки на цьому сервері. Залиште порожнім, щоб повернути початкове ім’я.",
  },
  detalhes: {
    abrir: "Деталі голосу",
    titulo: "Деталі Голосу",
    conexao: "З’єднання",
    pingMedio: "Середній пінг",
    ultimoPing: "Останній пінг",
    perda: "Втрата надісланих пакетів",
    medindo: "Вимірюємо…",
    criptografado: "Зашифровано до сервера (DTLS-SRTP)",
    explicacao: "Вище 250 мс затримку чути в розмові — люди починають перебивати одне одного. Втрата пакетів вище 10% робить голос роботизованим. В обох випадках проблема майже завжди між вами та інтернетом: спробуйте кабель замість Wi-Fi або перезапустіть роутер.",
  },
  microfone: {
    bloqueado: "Мікрофон заблоковано — ви лише слухаєте. Дозвольте доступ у правах браузера.",
    bloqueadoNoMac: "macOS блокує мікрофон. Позначте",
    caminhoNoMac: "Системні параметри → Конфіденційність і безпека → Мікрофон",
    abrirAjustes: "Відкрити параметри",
    vaiReabrir: "macOS попросить перезапустити застосунок.",
    naoAbriu: "Не вдалося відкрити мікрофон — ви лише слухаєте. Перевірте пристрій у Налаштування → Голос і відео.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS ще не дозволив запис екрана. Без цього показ виходить чорним.",
    marque: "Позначте",
    reabra: "у розділі «Запис екрана» і перезапустіть застосунок.",
    jaMarcado: "Якщо позначку вже поставлено, дозвіл застарів після останнього оновлення: зніміть її, поставте знову та перезапустіть застосунок.",
  },
  ruido: {
    titulo: "Придушення шуму",
    explicacao: "Приберіть фоновий шум зі свого голосу. Поплескайте або посуньте клавіатуру, поки говорите — у дзвінку чують лише вас.",
    semSuporte: "Цей браузер не запускає просунуте придушення. Лишається вбудоване в браузер, воно слабше.",
    aplicando: "Застосовуємо до дзвінка…",
    faleParaTestar: "Говоріть, щоб перевірити",
    verdeQuandoPassa: "Зелений, коли голос проходить.",
    teOuvindo: "Вас чують просто зараз.",
    feitoCom: "Зроблено на",
    aquiNoAparelho: ", просто на вашому пристрої",
    ajustes: "Налаштування",
  },
  permissoes: {
    titulo: "Дозволи macOS",
    detalhe: "macOS питає один раз, далі це змінюється лише в його панелі. Тут видно, що діє, і можна вирішити, чого бракує.",
    concedida: "Надано",
    negada: "Відхилено",
    naoPedida: "Не запитано",
    permitir: "Дозволити",
    abrirAjustes: "Відкрити параметри",
    microfone: "Мікрофон",
    microfoneDetalhe: "Говорити в дзвінках і перевіряти вхід.",
    camera: "Камера",
    cameraDetalhe: "Вмикати відео в дзвінку.",
    tela: "Запис екрана",
    telaDetalhe: "Показувати екран і вікна.",
    monitoramento: "Моніторинг входу",
    monitoramentoDetalhe: "Використовувати push-to-talk, навіть коли Gravaê у фоні.",
  },
  jaConectado: {
    titulo: "Ви вже в цьому дзвінку",
    trazer: "Перенести дзвінок сюди",
    deixar: "Залишити як є",
    detalhe: "При перенесенні сюди інша сторона виходить із дзвінка — ваш акаунт перебуває в одному місці за раз.",
  },
};
