export const comum = {
  carregando: "Завантаження…",
  salvar: "Зберегти",
  salvando: "Збереження…",
  descartar: "Скасувати",
  redefinir: "Скинути",
  naoSalvo: "У вас є незбережені зміни.",
  fechar: "Закрити",
  criar: "Створити",
  nome: "Назва",
  emoji: "Емодзі",
  previa: "Перегляд",
  cancelar: "Скасувати",
  enviar: "Надіслати",
  apagar: "Видалити",
  excluir: "Видалити",
  remover: "Прибрати",
  trocar: "Змінити",
};
