export const configuracoes = {
  efeitos: {
    titulo: "Ефекти вказівника",
    detalhe: "Слід та іскри, намальовані поверх застосунку. Приходять вимкненими й гаснуть самі, якщо ви просили менше руху.",
    rastro: "Слід курсора",
    rastroDetalhe: "Лінія, що йде за вказівником і тане позаду.",
    faisca: "Іскри при клацанні",
    faiscaDetalhe: "Короткі рисочки, що розлітаються з місця клацання.",
    cor: "Колір",
    espessura: "Товщина",
    comprimento: "Довжина",
    tamanho: "Розмір",
    quantidade: "Кількість",
  },
  email: {
    verificarTitulo: "Підтвердьте свою пошту",
    verificarDetalhe: "Деякі спільноти пускають писати лише підтверджених. Це один клац.",
    enviar: "Надіслати посилання",
    enviado: "Загляньте до пошти. Посилання живе добу.",
    falhou: "Листа надіслати не вдалося.",
    confirmado: "Пошту підтверджено",
    confirmadoDetalhe: "Готово. Тепер ви пишете в будь-якій спільноті, що цього вимагає.",
    linkIncompleto: "Посилання неповне",
    linkIncompletoDetalhe: "В адресі бракує коду. Відкрийте посилання просто з листа.",
    confirmando: "Підтверджуємо…",
    expirou: "Це посилання вже використали або воно протермінувалося.",
    irParaOApp: "До застосунку",
  },
  tema: {
    indisponivel: "Тема недоступна",
    indisponivelDetalhe: "Той, хто її опублікував, видалив її, або посилання хибне.",
    indisponivelLinha: "Тема недоступна. Той, хто її опублікував, видалив її, або посилання хибне.",
    importar: "Імпортувати тему",
    importarCurto: "Імпортувати",
    importarDetalhe: "Це замінить тему, яку ви маєте зараз. Відредагувати її можна потім: Налаштування > Вигляд > Студія тем.",
    porAutor: "автор: {{autor}}",
    umaCorTrocada: "замінено 1 колір",
    coresTrocadas: "замінено кольорів: {{quantas}}",
    avisoDeCss: "Ця тема несе CSS свого автора, а CSS дістає до будь-якого куточка екрана. Імпортуйте лише від людей, яким довіряєте.",
    soCores: "Ця тема міняє тільки кольори. Жодного стороннього CSS.",
    aplicar: "Застосувати",
    previaSemMotor: "У перегляді рушій не працює. Установіть, щоб побачити.",
    motorAnimado: "{{motor}}, з анімацією",
  },
  sair: "Вийти",
  versoes: {
    termos: "Умови надання послуг",
    privacidade: "Політика конфіденційності",
    copiar: "Натисніть, щоб копіювати",
    copiado: "Скопійовано",
  },
  telas: {
    conta: "Мій обліковий запис",
    privacidade: "Конфіденційність",
    conexoes: "Підключення",
    voz: "Звук",
    video: "Відео",
    avisos: "Сповіщення",
    aplicativos: "Застосунки",
    aparencia: "Вигляд",
    batePapo: "Чат",
    acessibilidade: "Доступність",
    idioma: "Мова",
    aplicativo: "Завантажити застосунок",
    atalhos: "Гарячі клавіші",
    desktop: "Застосунок для комп’ютера",
    avancado: "Додатково",
    servidor: "Сервер",
    comunicado: "Системне оголошення",
    denuncias: "Скарги",
    publicacoes: "Розгортання",
  },
  grupos: {
    conta: "Обліковий запис",
    app: "Налаштування застосунку",
    desenvolvedor: "Розробник",
    administracao: "Адміністрування",
  },
  secoes: {
    detalhesDeLogin: "Дані для входу",
    dispositivos: "Пристрої",
    usuariosBloqueados: "Заблоковані користувачі",
    aplicativosAutorizados: "Авторизовані застосунки",
    sessoes: "Сеанси",
    amigosEDms: "Друзі та особисті повідомлення",
    compartilhamentoDeAtividade: "Поширення активності",
    visibilidadeDoPerfil: "Видимість профілю",
    exportarDados: "Експорт даних",
    exclusaoDeDados: "Видалення даних",
    tema: "Тема",
    corDeDestaque: "Колір акценту",
    interface: "Інтерфейс",
    listaDeCanais: "Список каналів",
    zoomDoApp: "Масштаб застосунку",
    escalaDaFonte: "Розмір шрифту в чаті",
    modoStreamer: "Приватність під час трансляції",
    cursores: "Курсори",
    movimento: "Рух",
    textoEmVoz: "Текст у мовлення",
    teclado: "Клавіатура",
    formatoDaHora: "Формат часу",
    idiomaDaInterface: "Мова інтерфейсу",
    dispositivosDeVoz: "Пристрої",
    testeDoMicrofone: "Перевірка мікрофона",
    modoDeEntrada: "Режим введення",
    sensibilidade: "Чутливість введення",
    qualidade: "Якість",
    camera: "Камера",
    transmissao: "Трансляція",
    exibicao: "Відображення",
    entrada: "Введення",
    midia: "Медіа",
    geral: "Загальні",
    preferenciaDeMencao: "Налаштування згадок",
    sons: "Звуки",
  },
};
