export const configuracoes = {
  telas: {
    conta: "Мій обліковий запис",
    privacidade: "Конфіденційність",
    conexoes: "Підключення",
    voz: "Звук",
    video: "Відео",
    avisos: "Сповіщення",
    aplicativos: "Застосунки",
    aparencia: "Вигляд",
    batePapo: "Чат",
    acessibilidade: "Доступність",
    idioma: "Мова",
    aplicativo: "Завантажити застосунок",
    servidor: "Сервер",
  },
  grupos: {
    conta: "Обліковий запис",
    app: "Налаштування застосунку",
    desenvolvedor: "Розробник",
    administracao: "Адміністрування",
  },
  secoes: {
    detalhesDeLogin: "Дані для входу",
    dispositivos: "Пристрої",
    usuariosBloqueados: "Заблоковані користувачі",
    aplicativosAutorizados: "Авторизовані застосунки",
    sessoes: "Сеанси",
    amigosEDms: "Друзі та особисті повідомлення",
    compartilhamentoDeAtividade: "Поширення активності",
    visibilidadeDoPerfil: "Видимість профілю",
    exportarDados: "Експорт даних",
    exclusaoDeDados: "Видалення даних",
    tema: "Тема",
    corDeDestaque: "Колір акценту",
    interface: "Інтерфейс",
    listaDeCanais: "Список каналів",
    zoomDoApp: "Масштаб застосунку",
    escalaDaFonte: "Розмір шрифту в чаті",
    modoStreamer: "Приватність під час трансляції",
    movimento: "Рух",
    textoEmVoz: "Текст у мовлення",
    teclado: "Клавіатура",
    formatoDaHora: "Формат часу",
    idiomaDaInterface: "Мова інтерфейсу",
    dispositivosDeVoz: "Пристрої",
    testeDoMicrofone: "Перевірка мікрофона",
    modoDeEntrada: "Режим введення",
    sensibilidade: "Чутливість введення",
    qualidade: "Якість",
    camera: "Камера",
    transmissao: "Трансляція",
    exibicao: "Відображення",
    entrada: "Введення",
    midia: "Медіа",
    geral: "Загальні",
    preferenciaDeMencao: "Налаштування згадок",
    sons: "Звуки",
  },
};
