export const conversa = {
  lista: {
    carregando: "Завантаження повідомлень…",
    carregandoMais: "Завантаження…",
    verMais: "Прокрутіть угору, щоб побачити більше",
    semHistorico: "Історія недоступна",
    semHistoricoDetalhe: "У вашої ролі немає дозволу читати історію каналу #{{canal}}. Нові повідомлення й далі з’являтимуться, поки ви тут.",
    boasVindas: "Вітаємо в #{{canal}}",
    boasVindasDetalhe: "Це початок каналу #{{canal}}.",
  },
  data: {
    hoje: "Сьогодні",
    ontem: "Учора",
    hojeAs: "сьогодні о {{hora}}",
    ontemAs: "учора о {{hora}}",
  },
  digitando: {
    um: "{{nome}} пише…",
    dois: "{{primeiro}} і {{segundo}} пишуть…",
    varios: "{{quantidade}} людей пишуть…",
  },
  mensagem: {
    usou: "використовує",
    fixada: "закріплено",
    editado: "(змінено)",
    ignorada: "Повідомлення від того, кого ви ігноруєте.",
    mostrar: "Показати",
    escPara: "Esc, щоб",
    cancelar: "скасувати",
    enterParaSalvar: "Enter, щоб зберегти",
    falhou: "Не надіслано. Спробувати ще раз",
    naoLidasDaqui: "Непрочитані з цього місця.",
    linkCopiado: "Посилання скопійовано.",
    idCopiado: "ID скопійовано.",
    naoDeuParaCopiar: "Ваш браузер не дозволив скопіювати.",
    apagarTitulo: "Видалити повідомлення?",
    apagarDescricao: "Воно зникне для всіх на каналі. Відновити його не вийде.",
    apagarAcao: "Видалити",
    citacaoAnexo: "натисніть, щоб побачити вкладення",
    citacaoSumiu: "Початкового повідомлення тут уже немає.",
    reagirCom: "Реакція {{emoji}} — утримуйте для супер-реакції",
    segureParaSuper: "{{emoji}} — утримуйте для супер-реакції",
  },
  acoes: {
    reagir: "Реакція",
    responder: "Відповісти",
    encaminhar: "Переслати",
    favoritar: "Зберегти повідомлення",
    tirarDosFavoritos: "Прибрати зі збережених",
    marcarNaoLida: "Позначити як непрочитане",
    copiarLink: "Копіювати посилання на повідомлення",
    copiarId: "Копіювати ID повідомлення",
    fixar: "Закріпити повідомлення",
    desafixar: "Відкріпити",
    editar: "Змінити",
    apagar: "Видалити",
    mais: "Ще",
    adicionarReacao: "Додати реакцію",
    superReagirCom: "Супер-реакція {{emoji}}",
    fixarMensagem: "Закріпити повідомлення",
    desafixarMensagem: "Відкріпити повідомлення",
    editarMensagem: "Змінити повідомлення",
    apagarMensagem: "Видалити повідомлення",
  },
  mencao: {
    cargo: "Згадка ролі",
    pessoa: "Згадка",
    alguem: "хтось",
    cargoSemNome: "роль",
    here: "Сповіщає тих, хто онлайн",
    everyone: "Сповіщає весь сервер",
  },
  codigo: {
    copiar: "Копіювати",
    copiado: "Скопійовано",
    copiarAria: "Копіювати код",
    copiadoAria: "Код скопійовано",
    recolher: "Згорнути",
    expandir: "Розгорнути",
    verInteiro: "Показати весь файл",
    maisOpcoes: "Більше опцій",
    baixar: "Завантажити",
    recolherLinhas: "Згорнути ({{linhas}} рядків)",
    expandirLinhas: "Розгорнути ({{linhas}} рядків)",
    mudarIdioma: "Змінити мову",
    procurarIdioma: "Пошук коду мови…",
    nenhumIdioma: "Такої мови немає.",
    quebrarTexto: "Переносити текст",
  },
  caixa: {
    escrever: "Написати в #{{canal}}",
    escreverSemCanal: "Написати повідомлення",
    semPermissao: "У вас немає дозволу надсилати повідомлення в цьому каналі",
    solteParaAnexar: "Відпустіть, щоб прикріпити",
    longaTitulo: "Повідомлення надто довге…",
    longaDescricao: "Ти досяг межі у {{limite}} символів. Можна надіслати файлом.",
    enviarComoArquivo: "Надіслати файлом",
    respondendoPara: "Відповідь для",
    vaiNotificar: "Людина отримає сповіщення",
    naoVaiNotificar: "Людина не отримає сповіщення",
    ligado: "увімк.",
    desligado: "вимк.",
    pararDeResponder: "Перестати відповідати",
    mais: "Ще",
    enviarArquivo: "Надіслати файл",
    criarEnquete: "Створити опитування",
    expressoes: "Емодзі, GIF і наліпки",
    enviar: "Надіслати",
    aguardandoEnvio: "Чекаємо на завантаження",
    modoLento: "Повільний режим увімкнено ({{tempo}})",
    modoLentoDica: "Повільний режим стоїть на {{segundos}} с. Зачекайте, перш ніж надіслати наступне повідомлення.",
  },
  anexos: {
    enviando: "Завантаження…",
    modificar: "Змінити {{arquivo}}",
    remover: "Прибрати {{arquivo}}",
    ver: "Переглянути {{arquivo}}",
    mostrarSpoiler: "Показати спойлер: {{arquivo}}",
    spoiler: "спойлер",
    spoilerTitulo: "Спойлер",
    editarTitulo: "Змінити вкладення",
    nomeDoArquivo: "Назва файлу",
    descricao: "Опис альтернативного тексту",
    descricaoDica: "Опишіть цей файл для програм читання з екрана",
    marcarSpoiler: "Позначити як спойлер",
    cancelar: "Скасувати",
    salvar: "Зберегти",
  },
  cartao: {
    tocador: "Програвач",
    abrir: "Відкрити {{destino}}",
    tocar: "Відтворити {{titulo}}",
    video: "відео",
    verImagem: "Переглянути зображення",
  },
  enquete: {
    titulo: "Опитування",
    encerrada: "Опитування завершено",
    variasRespostas: "Опитування — кілька відповідей",
    umVoto: "{{quantidade}} голос",
    votos: "{{quantidade}} голосів",
    umVotoNoTotal: "{{quantidade}} голос загалом",
    votosNoTotal: "{{quantidade}} голосів загалом",
    encerraEm: "завершиться {{quando}}",
    encerrarAgora: "Завершити зараз",
  },
  fixadas: {
    titulo: "Закріплені повідомлення",
    vazio: "У цьому каналі поки немає закріплених повідомлень.",
    desafixar: "Відкріпити",
    anexo: "(вкладення)",
    enquete: "(опитування)",
    dicaRotulo: "ПОРАДА:",
    dica: "хто має право «Керування повідомленнями», може закріпити просто з меню повідомлення.",
  },
  encaminhar: {
    titulo: "Переслати повідомлення",
    paraOnde: "Куди?",
    semTexto: "(повідомлення без тексту)",
    nenhumLugar: "Немає місця з такою назвою.",
    canais: "Канали",
    conversas: "Особисті повідомлення",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Шукати в Klipy",
    figurinha: "Наліпка",
    buscarFigurinha: "Знайдіть ідеальну наліпку",
    buscarEmoji: "Знайдіть ідеальне емодзі",
    buscarReacao: "Знайдіть ідеальну реакцію",
    adicionarEmoji: "Додати емодзі",
    limparBusca: "Очистити пошук",
  },
  busca: {
    fechar: "Закрити пошук",
    procurando: "Шукаю…",
    resultado: "{{quantos}} результат",
    resultados: "{{quantos}} результатів",
    nadaCom: "Нічого з {{termo}} тут немає.",
    soOsQuePodeLer: "Пошук дивиться лише в канали, які ви можете читати.",
  },
  entrada: {
    titulo: "Вхідні",
    naoLidas: "Непрочитані",
    salvas: "Збережені",
    mencoes: "Згадки",
    fimTitulo: "Ви дійшли до кінця",
    fimDetalhe: "Читати більше нічого. Коли надійде нове повідомлення, воно з'явиться тут.",
    semSalvosTitulo: "Нічого не збережено",
    semSalvosDetalhe: "Утримуйте Shift і натисніть на закладку повідомлення, щоб зберегти його й прочитати згодом.",
    tirarDosSalvos: "Прибрати зі збережених",
    semMencoesTitulo: "Згадок поки немає",
    semMencoesDetalhe: "Згадки про вас з'являються тут за останні 7 днів.",
  },
  forum: {
    descricao: "Кожна тема стає окремою розмовою — зручно для питання, яке не має загубитися серед балачки.",
    novoAssunto: "Нова тема",
    vazio: "Тем поки немає. Почніть першу, і розмова з самого початку лишиться впорядкованою.",
    titulo: "Заголовок",
    doQueSeTrata: "Про що це?",
    primeiraMensagem: "Перше повідомлення",
    conteDoCaso: "Розкажіть",
  },
};
