export const perfil = {
  carregando: "Завантаження…",
  editar: "Змінити профіль",
  mensagem: "Повідомлення",
  abrirConversa: "Відкрити листування",
  verCompleto: "Відкрити повний профіль",
  convidarParaServidor: "Запросити на сервер",
  semServidores: "У вас немає серверів",
  conviteEnviado: "Запрошення надіслано {{nome}}.",
  moderador: "Відкрити в режимі модератора",
  mais: "Ще",
  ignorar: "Ігнорувати",
  deixarDeIgnorar: "Більше не ігнорувати",
  copiarId: "Копіювати ID користувача",
  idCopiado: "ID скопійовано.",
  conexoes: "Підключення",
  membroDesde: "Учасник від",
  sobre: "Про себе",
  cargosTitulo: "Ролі",
  visaoGeral: "Огляд",
  amigosEmComum: "Спільні друзі ({{quantidade}})",
  servidoresEmComum: "Спільні сервери ({{quantidade}})",
  amizade: {
    amigo: "Друг",
    pedidoEnviado: "Запит у друзі надіслано",
    respondaAbaixo: "Надіслав вам запит — дайте відповідь нижче",
    adicionar: "Додати в друзі",
    teMandouPedido: "Надіслав вам запит у друзі",
    aceitar: "Прийняти",
    desfazer: "Видалити з друзів",
    desfazerTitulo: "Видалити {{nome}} з друзів?",
    desfazerDescricao: "Ви перестаєте бути друзями. Особисте листування лишається в історії, і згодом ви зможете додати його знову.",
    bloquear: "Заблокувати",
    bloquearTitulo: "Заблокувати {{nome}}?",
    bloquearDescricao: "Ви перестаєте бути друзями, особисте листування перестає приймати повідомлення, і він більше не зможе надіслати вам запит у друзі.",
    linkCopiado: "Ви не друзі — посилання скопійовано, надішліть його самі.",
  },
  recado: {
    escrever: "Написати @{{usuario}}",
    enviar: "Надіслати",
    enviada: "Повідомлення надіслано",
    falhou: "Не вдалося надіслати. Спробуйте з листування.",
  },
  cartao: {
    trocarFaixa: "Змінити банер картки",
    trocarFaixaCurto: "Змінити банер",
    trocarFoto: "Змінити фото профілю",
    trocarFotoCurto: "Змінити фото",
    suaEtiqueta: "Ваша позначка",
    editarEtiqueta: "Натисніть, щоб змінити позначку",
    conteAlgo: "Розкажіть про себе",
    adicionarStatus: "Додати статус",
    adicionarDescricao: "Натисніть, щоб додати опис",
    cargo: "Роль",
    cargos: "Ролі",
    cargosCom: "Ролі — {{quantidade}}",
    tirarCargo: "Зняти роль {{cargo}}",
  },
  cargos: {
    adicionar: "Додати роль",
    procurar: "Знайти роль",
  },
  etiqueta: {
    escolher: "Вибрати позначку сервера",
    nenhuma: "Немає позначки сервера",
    semEtiqueta: "Жоден із ваших серверів не має позначки",
  },
  emblemas: {
    doServidor: "Значки цього сервера",
    limite: "Можна носити до {{quantidade}} значків.",
  },
  nota: {
    vazia: "Натисніть, щоб записати нотатку",
    rotulo: "Нотатка (бачите тільки ви)",
  },
  status: {
    titulo: "Статус",
    definir: "Задати статус",
    escolherEmoji: "Вибрати емодзі",
    tirarEmoji: "Прибрати емодзі",
    oQuePensa: "Про що ви думаєте?",
    limparAgora: "Очистити статус зараз",
    naoLimpar: "Не очищати",
    limpar30m: "Очистити за 30 хвилин",
    limpar1h: "Очистити за 1 годину",
    limpar4h: "Очистити за 4 години",
    limparHoje: "Очистити сьогодні",
    limparAmanha: "Очистити завтра",
    comHora: "{{prazo}} о {{hora}}",
  },
  presenca: {
    disponivel: "У мережі",
    ausente: "Відійшов",
    naoPerturbar: "Не турбувати",
    naoPerturbarDetalhe: "Ви не отримуєте сповіщень про нові повідомлення",
    invisivel: "Невидимий",
    invisivelDetalhe: "Для інших ви не в мережі",
  },
  menu: {
    mudarDeConta: "Змінити акаунт",
    gerenciarContas: "Керування акаунтами",
  },
  editor: {
    decoracao: "Змінити прикрасу аватара",
    naoSalvo: "Не забудьте зберегти зміни!",
    principal: "Основний профіль",
  },
};
