export const servidor = {
  comunidade: {
    ativa: "Спільнота відкрита",
    ativaDesde: "Відкрита з {{quando}}",
    membrosAgora: "{{quantos}} учасників",
    criarParaMim: "Створіть за мене",
    canalDeRegras: "Канал правил",
    canalDeRegrasDetalhe: "Місце, де лежать правила, які всі читають, перш ніж писати.",
    canalDeAvisos: "Канал оголошень спільноти",
    canalDeAvisosDetalhe: "Туди ми надсилаємо те, що тут змінюється, — лише для тих, хто керує.",
    canalDeSeguranca: "Канал сповіщень безпеки",
    canalDeSegurancaDetalhe: "Туди модерація отримує те, що спіймали фільтри.",
    idiomaPrincipal: "Основна мова",
    idiomaPrincipalDetalhe: "Мова, якою точиться більша частина розмови.",
    semIdioma: "Мову не обрано",
    semCanal: "Без каналу",
    finalTitulo: "Майже готово",
    finalDetalhe: "Перед відкриттям погляньте, що змінюється для тих, хто приходить.",
    confereRegras: "Хто заходить, найперше бачить канал правил.",
    confereEveryone: "@everyone і @here користуються тільки ті, хто має роль.",
    confereMencoes: "Покликати всіх одразу тепер можна лише з дозволом.",
    concordo: "Погоджуюсь і розумію",
    concordoDetalhe: "Ви підтверджуєте, що спільнота дотримується наших правил.",
    proximo: "Далі",
    terminar: "Завершити налаштування",
    visaoGeral: "Загальний огляд",
    visaoGeralDetalhe: "Канали, якими спільнота говорить із новачками.",
    seguranca: "Безпека",
    segurancaDetalhe: "Гальма, що тримають спам і важкий вміст.",
    habilitada: "Спільноту ввімкнено.",
    falhou: "Не вдалося ввімкнути спільноту.",
    titulo: "Спільнота",
    ilustracao: "Хмаринки мовлення",
    convite: "Ви збираєте спільноту?",
    conviteDetalhe: "Перетворіть його на спільноту й отримайте інструменти великого місця: канал правил, оголошення від нас і фільтри, що стежать самі.",
    contagem: "{{membros}} із {{minimo}} учасників",
    faltam: "До відкриття бракує {{quantos}}.",
    prontoParaAbrir: "Уже можна відкривати.",
    habilitar: "Увімкнути спільноту",
    vantagemCrescer: "Рости",
    vantagemCrescerDetalhe: "Спільнота може подати заявку в «Огляд», і ті, хто шукає тему, вас знайдуть.",
    vantagemModerar: "Стежити",
    vantagemModerarDetalhe: "Вимагати підтверджену пошту, фільтрувати медіа й увімкнути AutoMod разом.",
    vantagemAvisos: "Бути в курсі",
    vantagemAvisosDetalhe: "Ми надсилаємо зміни тим, хто тут порядкує, — у канал тільки для вас.",
    assistenteTitulo: "Налаштуймо вашу спільноту.",
    passoSeguranca: "Перевірки безпеки",
    passoBasico: "Базове налаштування",
    passoFinal: "Останні штрихи",
    seguraTitulo: "Тримайте спільноту в безпеці",
    seguraDetalhe: "Велика спільнота притягує спам. Ці два гальма ввімкнені одразу, згодом їх можна зняти.",
    emailVerificado: "Вимагати підтверджену пошту",
    emailVerificadoDetalhe: "Хто ще не підтвердив пошту, той не пише. Хто має роль — проходить.",
    filtroDeMidia: "Фільтрувати відверті медіа",
    filtroDeMidiaDetalhe: "Зображення та відео надходять прихованими й показуються лише тому, хто вирішить подивитися.",
    basicoTitulo: "Підготуйте основу",
    basicoDetalhe: "Скажіть, у якому каналі правила й куди йдуть наші оголошення. Без вибору я створю обидва.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} команд",
    previa: "Який вигляд має картка",
    trocarIcone: "Змінити піктограму",
    tirarCapa: "Прибрати обкладинку",
    heroComunidades: "Хтось саме зараз говорить про те, що вам до душі",
    heroComunidadesDetalhe: "Спільноти, які відкрили тутешні люди. Зайдіть, почитайте розмову й лишайтеся, якщо сподобається.",
    emDestaque: "На видноті",
    todasAsComunidades: "Решта",
    heroTitulo: "Чим ваша компанія скористається сьогодні?",
    heroDetalhe: "Боти для музики, ігор і модерації, зроблені тими, хто теж тут. Оберіть одного — і він зайде на ваш сервер.",
    novidades: "Щойно з’явилися",
    todosOsApps: "Решта",
    lojaTitulo: "Сторінка застосунку",
    lojaDetalhe: "Це бачить в «Огляді» той, хто з ним ще не знайомий.",
    capa: "Обкладинка",
    capaDetalhe: "Широке зображення вгорі сторінки. 1280 × 720 сидить добре.",
    trocarCapa: "Змінити обкладинку",
    categorias: "Категорії",
    categoriasDetalhe: "До {{quantas}}. За ними й гортають «Огляд».",
    idiomas: "Мови",
    idiomasDetalhe: "До {{quantos}}. Якими мовами застосунок відповідає.",
    termos: "Умови користування",
    politica: "Політика приватності",
    politicas: "Документи",
    servidorDeSuporte: "Сервер підтримки",
    servidorDeSuporteDetalhe: "Туди йде той, кому потрібна допомога із застосунком.",
    semServidor: "Немає",
    emQuantosServidores: "На скількох серверах",
    categoria: {
      GAMES: "Ігри",
      MUSICA: "Музика",
      MODERACAO: "Модерація",
      PRODUTIVIDADE: "Продуктивність",
      SOCIAL: "Спілкування",
      UTILIDADES: "Інструменти",
      ARTE_E_CRIACAO: "Мистецтво і творчість",
      EDUCACAO: "Навчання",
      OUTRA: "Інше",
    },
    appIndisponivel: "Застосунок недоступний",
    voltarParaExplorar: "Назад до «Огляду»",
    adicionarApp: "Додати застосунок",
    copiarLink: "Скопіювати посилання",
    denunciarApp: "Поскаржитися на застосунок",
    copiarIdDoApp: "Скопіювати ID застосунку",
    visaoGeral: "Огляд",
    comandos: "Команди",
    permissoes: "Права",
    semPermissoes: "Цей застосунок не просить жодних прав.",
    avisoDePermissoes: "Він заходить із власною роллю. Права можна змінити потім: Налаштування спільноти → Ролі.",
    servidoresEmComum: "Спільні спільноти",
    umServidorEmComum: "1 спільнота",
    quantosServidoresEmComum: "спільнот: {{quantos}}",
    feitoPor: "Автор",
    publicadoEm: "Опубліковано",
    denunciarNome: "Поскаржитися на {{nome}}",
    denunciaDetalhe: "Скарга йде команді Gravaê. Автор застосунку не дізнається, що це були ви.",
    denunciaFalhou: "Не вдалося надіслати скаргу.",
    umMembro: "1 учасник",
    semDescricao: "Без опису.",
    adicionar: "Додати",
    jaEstaAqui: "Ви вже тут",
    entrando: "Заходжу…",
    entrar: "Приєднатися",
    comunidadePublica: "Публічна спільнота",
    online: "{{quantos}} у мережі",
    membros: "учасників: {{quantos}}",
    abrirComunidade: "Відкрити спільноту",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Налаштування сервера",
  novasMensagens: "Нові повідомлення",
  menu: {
    silenciar: "Вимкнути звук спільноти",
    reativar: "Увімкнути звук спільноти",
    porQuinze: "На 15 хвилин",
    porMeiaHora: "На 30 хвилин",
    porTresHoras: "На 3 години",
    porTresDias: "На 3 дні",
    porUmaHora: "На 1 годину",
    porOitoHoras: "На 8 годин",
    porUmDia: "На 24 години",
    ateReativar: "Поки не ввімкну",
    notificacoes: "Налаштування сповіщень",
    padrao: "За замовчуванням",
    todas: "Усі повідомлення",
    soMencoes: "Лише згадки",
    nada: "Нічого",
    ocultarSilenciados: "Сховати вимкнені канали",
    denunciar: "Поскаржитися на спільноту",
    marcarLida: "Позначити як прочитане",
    convidar: "Запросити учасників",
    editarPerfil: "Редагувати профіль спільноти",
    configuracoes: "Налаштування спільноти",
    sair: "Вийти зі спільноти",
    sairTitulo: "Вийти з {{nome}}?",
    sairDescricao: "Щоб повернутися, знадобиться нове запрошення.",
    copiarId: "Копіювати ID спільноти",
    idCopiado: "ID скопійовано.",
  },
  convite: {
    cartaoTitulo: "Вас запросили до спільноти",
    indisponivel: "Запрошення недоступне",
    indisponivelDetalhe: "Воно застаріло, вичерпалося, або той, хто його створив, видалив його.",
    entrar: "Увійти до спільноти",
    chamado: "Вас запросили приєднатися до",
    aceitarComo: "Прийняти як {{nome}}",
    abrir: "Відкрити спільноту",
    recusar: "Ні, дякую",
  },
  pasta: {
    silenciarTodas: "Вимкнути звук спільнот",
    reativarTodas: "Увімкнути звук спільнот",
    mostrarSilenciados: "Показати вимкнені канали",
    notificacoesDaComunidade: "Налаштування сповіщень",
    silenciarEveryone: "Вимкнути @everyone і @here",
    permitirEveryone: "Дозволити @everyone і @here",
    silenciarCargos: "Вимкнути згадки ролей",
    permitirCargos: "Дозволити згадки ролей",
    dicaDaCor: "Введіть колір (hex, rgb(), hsl() або назву) чи виберіть.",
    mostrarIcone: "Показувати значок у закритому вигляді",
    dicaDoIcone: "Закрита показує значок замість серверів.",
    icone: "Значок папки",
    excluir: "Видалити папку",
    icones: {
      pasta: "Папка",
      estrela: "Обране",
      coracao: "Серце",
      salvar: "Зберегти",
      jogo: "Геймпад",
      escudo: "Щит",
      nota: "Нота",
    },
    marcarLida: "Позначити папку як прочитану",
    configuracoes: "Налаштування папки",
    desfazer: "Розгрупувати папку",
    titulo: "Папка",
    nome: "Назва",
    semNome: "Без назви",
    cor: "Колір",
    semCor: "Без кольору",
    salvar: "Зберегти",
  },
  denuncia: {
    titulo: "Поскаржитися на {{nome}}",
    descricao: "Скарга надходить команді Gravaê. Розкажіть, що сталося.",
    motivo: "Причина",
    detalhes: "Подробиці (необов’язково)",
    enviar: "Надіслати скаргу",
    enviada: "Скаргу надіслано. Дякуємо.",
    motivos: {
      spam: "Спам або реклама",
      assedio: "Цькування або ненависть",
      conteudo: "Неприйнятний вміст",
      golpe: "Шахрайство",
      outro: "Інше",
    },
  },
  selos: {
    verificada: "Перевірена спільнота",
    detectavel: "Спільнота, яку можна знайти",
  },
  auditoria: {
    todasAsAcoes: "Усі дії",
    todosOsUsuarios: "Усі користувачі",
    filtroMembros: "Учасники",
    filtroCanais: "Канали",
    filtroEmojis: "Емодзі",
    filtroServidor: "Сервер",
    titulo: "Журнал дій",
    porUsuario: "Фільтр за людиною",
    porAcao: "Фільтр за дією",
    vazio: "З цим фільтром поки нічого не записано.",
    motivo: "Причина:",
  },
  banimentos: {
    titulo: "Список банів сервера",
    descricao: "Хто тут — не повернеться навіть за новим запрошенням. Розбан повертає доступ одразу.",
    procurar: "Шукати бани за іменем користувача",
    vazioTitulo: "Банів немає",
    vazio: "Ви ще нікого не забанили… але якщо знадобиться, не вагайтеся.",
    desbanir: "Розбанити",
  },
  excluir: {
    tudoVai: "Усі канали, повідомлення та запрошення сервера {{servidor}} буде видалено в {{membros}} учасників. Повернути їх потім ніхто не зможе.",
    digite: "Введіть {{servidor}}, щоб підтвердити",
    titulo: "Видалити сервер",
    aviso: "Це не можна скасувати.",
  },
  emblemas: {
    apagarDescricao: "Він знімається з усіх, хто його носить. Скасувати не можна.",
    titulo: "Значки",
    vazio: "Значків поки немає.",
    novo: "Новий значок",
  },
  convites: {
    revogarTitulo: "Відкликати запрошення?",
    revogarAcao: "Відкликати",
    revogarDescricao: "Посилання {{codigo}} перестає працювати одразу. Хто вже зайшов за ним, лишається на сервері.",
    titulo: "Запрошення",
    descricao: "Усі активні посилання-запрошення цього сервера.",
    vazio: "Запрошень поки не створено.",
    revogar: "Відкликати запрошення",
  },
  integracoes: {
    opcionais: "username і avatar_url необов'язкові й діють на повідомлення. Обмеження — 5 повідомлень за 5 секунд.",
    apagarDescricao: "URL перестає працювати одразу. Уже надіслані повідомлення лишаються в каналі.",
    titulo: "Інтеграції",
    descricao: "Вебхук — це адреса, що пише в канал без облікового запису. Знадобиться, щоб повідомити про вдалу збірку, про нове звернення чи про будь-що, що ви надсилаєте зі скрипта.",
    novo: "Новий вебхук",
    vazio: "Вебхуків поки немає. Створіть один і вставте URL туди, звідки має приходити повідомлення.",
    canal: "Канал",
    apagar: "Видалити вебхук",
    comoUsar: "Як користуватися",
    comoUsarTexto: "Надішліть POST із JSON:",
  },
  explorar: {
    titulo: "Огляд",
  },
  engajamento: {
    semCanal: "Без системного каналу",
    titulo: "Залучення",
    descricao: "Що сервер робить сам, щоб не виглядати порожнім, коли приходить новачок.",
    sistema: "Системні повідомлення",
    boasVindas: "Надсилати вітання, коли хтось заходить",
    sorteio: "Без власного тексту нижче фраза вибирається випадково — та сама швидко набридає.",
    canalDoSistema: "Канал системних повідомлень",
    mensagem: "Вітальне повідомлення",
    deixeVazio: "Залиште порожнім, щоб вибирати з готових фраз",
  },
  automod: {
    titulo: "Автомодерація",
    descricao: "Фільтри, що модерують самі, ще до того як повідомлення з'явиться. Того, хто керує сервером, вони не чіпають — а ролі-винятки проходять наскрізь.",
    palavras: {
      titulo: "Блокувати власні слова",
      descricao: "Ваш список слів, які нікому не можна писати.",
    },
    mencoes: {
      titulo: "Блокувати спам згадками",
      descricao: "Блокує повідомлення із забагатьма згадками одразу.",
    },
    links: {
      titulo: "Блокувати посилання",
      descricao: "Затримує будь-яку адресу, вставлену в чат.",
    },
    definir: "Налаштувати",
    nomeDaRegra: "Назва правила",
    bloqueadas: "Заборонені слова",
    digiteEnter: "Введіть і натисніть Enter",
    comparacao: "Порівняння не зважає на регістр, діакритику та розділові знаки — і не ловить слово всередині іншого.",
    aPartirDe: "Блокувати починаючи зі скількох згадок",
    oQueFazer: "Що робити",
    canalDoAlerta: "Канал сповіщення",
    escolhaCanal: "Оберіть канал",
    castigo: "Тайм-аут (хвилини)",
    isentos: "Ролі-винятки",
    semCargos: "Ролей ще не створено.",
    salvarRegra: "Зберегти правило",
    apagar: "Видалити правило",
    excluirTitulo: "Видалити це правило автомодерації?",
    excluirDescricao: "Сервер одразу перестане фільтрувати за ним. Створити наново можна, але поточні налаштування зникнуть.",
    excluirAcao: "Видалити правило",
  },
  cargos: {
    titulo: "Ролі",
    descricao: "Ролі дають ім'я, колір і повноваження. Хто вище в списку — той головніший за тих, хто нижче, і ніхто не чіпає роль, рівну своїй або вищу.",
    criar: "Створити роль",
    vazio: "Ролей ще немає.",
    abaExibicao: "Вигляд",
    abaPermissoes: "Права",
    abaMembros: "Учасники — {{quantos}}",
    everyone: "Діє на всіх на сервері. Це основа, поверх якої складаються інші ролі.",
    nomeDoCargo: "Назва ролі",
    cor: "Колір ролі",
    corDica: "Фарбує ім'я тих, хто має роль, у списку учасників і в чаті.",
    semCor: "Без кольору",
    corPersonalizada: "Власний колір",
    estilo: "Стиль імені",
    segundaCor: "Другий колір",
    segundaCorDica: "Без нього градієнт стає суцільним кольором — він не зникає.",
    limparSegundaCor: "Очистити другий колір",
    icone: "Значок",
    iconeDica: "З'являється поруч із роллю в картці профілю того, хто її має.",
    exibirSeparado: "Показувати окремо від інших учасників",
    exibirSeparadoDica: "Роль отримує власний розділ у списку учасників.",
    permitirMencionar: "Дозволити згадувати цю роль",
    permitirMencionarDica: "Будь-хто зможе сповістити всіх, хто має цю роль.",
    semPoderDeConceder: "{{descricao}} (у вас немає цього права, щоб його надати)",
    adicionar: "Додати когось до цієї ролі",
    tirar: "Зняти роль",
    semNinguem: "Цієї ролі ще ні в кого немає.",
    apagar: "Видалити роль",
    excluirTitulo: "Видалити роль «{{nome}}»?",
    excluirDescricao: "Той, хто має цю роль, втратить усе, що вона давала. Скасувати не можна.",
    excluirAcao: "Видалити роль",
  },
  membros: {
    procurar: "Шукати за іменем або ніком",
    membroDesde: "Учасник з",
    vazio: "Нікого не знайдено.",
    acoesPara: "Дії для {{nome}}",
    deCastigo: "тайм-ауту",
    tirarCastigo: "Зняти тайм-аут",
    castigo5min: "5 хвилин",
    castigo1h: "1 година",
    castigo1d: "1 день",
    castigo1s: "1 тиждень",
    expulsar: "Вигнати",
    expulsarTitulo: "Вигнати {{nome}}?",
    expulsarDescricao: "залишає {{servidor}} одразу. Може повернутися за запрошенням — виключення не заважає поверненню.",
    banir: "Заблокувати",
    banirTitulo: "Заблокувати {{nome}}?",
    banirDescricao: "залишає {{servidor}} і не повернеться навіть за запрошенням, доки блокування не знімуть.",
    motivo: "Причина (необов'язково)",
    motivoDica: "Залишиться в журналі дій",
  },
  perfil: {
    titulo: "Профіль сервера",
    descricao: "Так ваш сервер виглядає у списку та в посиланнях-запрошеннях.",
    icone: "Значок",
    faixa: "Банер угорі",
    nomeDoServidor: "Назва сервера",
    campoDescricao: "Опис",
    doQueE: "Про що цей сервер?",
    comprimido: "Стиснуто перед завантаженням: {{economia}}",
  },
  etiqueta: {
    titulo: "Мітка сервера",
    descricao: "Мітка до 4 літер, що з'являється поруч з іменем кожного учасника — у чаті й у списку людей. Тут вона безкоштовна: без бустів, без рівнів.",
    escolhaNome: "Оберіть назву",
    limite: "Не більше 4 символів, літери й цифри.",
    escolhaInsignia: "Оберіть значок",
    voce: "Ви",
    fala1: "хтось хоче пограти?",
    fala2: "глянь на мою мітку!",
    fala3: "ого, як ти це дістав",
  },
  expressoes: {
    comoUsar: "Додайте до {{limite}} емодзі, якими зможуть користуватися всі на цьому сервері. Напишіть :ім'я: у чаті, щоб надіслати.",
    imagem: "Зображення",
    enviadoPor: "Завантажив",
    semEmoji: "Емодзі ще немає.",
    figurinhas: "Наліпки",
    enviarFigurinha: "Завантажити наліпку",
    nomeDaFigurinha: "Назва наліпки",
    exemploFigurinha: "Напр.: обіймашки кошеняти",
    figurinhaGrande: "Наліпка більша за {{limite}}.",
    deixaPraLa: "Не треба",
    sons: "Панель звуків",
    enviarSom: "Завантажити звук",
    nomeDoSom: "Назва звуку",
    semSom: "Звуків ще немає.",
    somGrande: "Звук більший за {{limite}}.",
    emojiRelacionado: "Пов'язане емодзі",
    ouvir: "Прослухати",
    ouvirAssim: "Прослухати так",
    volumeDe: "Гучність {{nome}}",
    volumeDica: "Діє на всіх на сервері. Кожен усе одно може стишити звуки лише для себе, у панелі дзвінка.",
    falhaEnvio: "Не вдалося завантажити файл.",
    excluirTitulo: "Видалити {{tipo}} «{{nome}}»?",
    excluirDescricao: "Зникає із сервера в усіх. Повідомлення, де його вже вжито, лишаються як є.",
  },
  canal: {
    tipoLink: "Посилання",
    tipoLinkDica: "Веде на зовнішню адресу й відкривається у браузері",
    endereco: "Адреса",
    enderecoDica: "Куди веде цей канал. Має починатися з https://",
    visaoGeral: "Огляд",
    nome: "Назва каналу",
    topico: "Тема каналу",
    topicoDica: "Про що тут говорять?",
    modoLento: "Кожен надсилає лише одне повідомлення за проміжок. Хто керує повідомленнями чи каналами, проходить без затримки.",
    visibilidade: "Видимість вмісту",
    padrao: "За замовчуванням",
    padraoDica: "Вміст каналу завжди видно.",
    spoiler: "Канал зі спойлерами",
    spoilerDica: "Позначте канал як такий, що містить спойлери, щоб повороти сюжету й важкі теми лишалися прихованими, доки хтось не вирішить подивитися.",
    idade: "Канал з віковим обмеженням",
    idadeDica: "Хто заходить, має підтвердити повноліття, щоб побачити вміст.",
    bitrateDica: "Понад 64 кбіт/с може заважати тим, у кого поганий інтернет.",
    qualidadeDeVideo: "Якість відео",
    automatica: "Автоматично",
    limite: "Обмеження учасників — {{valor}}",
    pessoas: "{{quantos}} осіб",
    semLimite: "без обмеження",
    permissoesDescricao: "Тут ви змінюєте те, що діє в цьому каналі. Що лишилося на «успадкувати», далі йде за роллю.",
    excluir: {
      titulo: "Видалити канал",
      historico: "Уся історія каналу {{canal}} зникає разом із ним, у всіх.",
      digite: "Введіть {{canal}}, щоб підтвердити",
    },
  },
  moderacao: {
    titulo: "Погляд модератора",
    semPermissao: "Потрібне право «Модерувати учасників», щоб це побачити.",
    fecharEsc: "Закрити (Esc)",
    atividade: "Активність на сервері",
    mensagens: "Повідомлення",
    links: "Посилання",
    midia: "Медіа",
    acoesNaAuditoria: "Дії в журналі",
    moderacoesSofridas: "Отримані покарання",
    permissoes: "Права ({{quantas}})",
    semPermissaoEspecial: "Особливих прав немає.",
    conta: "Обліковий запис",
    entrouNoServidor: "Зайшов на сервер",
    contaCriadaEm: "Обліковий запис створено",
    deCastigoAte: "У тайм-ауті до",
    formaDeAdesao: "Як потрапив",
    mensagem: "Повідомлення",
    castigo: "Тайм-аут",
    copiarId: "Копіювати ID",
    idCopiado: "ID скопійовано.",
    adicionarCargo: "Додати роль",
    semCargos: "Ролей не створено",
    soEveryone: "Лише @everyone.",
    voltar: "Назад",
    vazio: "Тут нічого немає.",
    cinquenta: "Показано 50 найновіших.",
    irParaMensagem: "Перейти до повідомлення",
    precisaSerAmigo: "Щоб спілкуватися, ви маєте бути друзями.",
    expulsarDescricao: "Залишає сервер одразу, але може повернутися за запрошенням.",
    banirDescricao: "Залишає сервер і не повернеться навіть за запрошенням, доки блокування не знімуть.",
    castigarTitulo: "Дати тайм-аут {{nome}}?",
    castigoDescricao: "Поки він триває, людина не пише й не говорить у жодному каналі сервера.",
    aplicarCastigo: "Застосувати тайм-аут",
    duracao: "Тривалість у хвилинах",
    informeDuracao: "Вкажіть тривалість у хвилинах.",
  },
  abas: {
    pesquisar: "Пошук у налаштуваннях",
    semResultado: "Тут немає нічого з такою назвою.",
    comunidade: "Спільнота",
    expressoes: "Вирази",
    pessoas: "Люди",
    apps: "Застосунки",
    moderacao: "Модерація",
    banimentos: "Блокування",
  },
};
