export const amizades = {
  ativosAgora: "Aktive nå",
  procurando: "Ser hvem som er her…",
  tudoTranquilo: "Det er stille akkurat nå…",
  tudoTranquiloDetalhe: "Når du eller en venn blir med i en samtale, dukker den opp her — og du kan hoppe inn med ett klikk.",
  emVoz: "I tale",
  voce: "Du",
  soVoce: "Bare du",
  pessoas: "{{quantas}} personer",
  voltarParaChamada: "Tilbake til samtalen",
  entrarNaChamada: "Bli med i samtalen",
  abrirCanal: "Åpne {{canal}} på {{servidor}}",
  mensagensDiretas: "Direktemeldinger",
  encontreConversa: "Finn en samtale",
  amigos: "Venner",
  conversas: "Samtaler",
  semConversas: "Ingen samtaler ennå. Legg til en venn for å komme i gang.",
  semConversaComEsseNome: "Ingen samtale med det navnet.",
  abrirMenu: "Åpne servere og samtaler",
  solicitacoes: "Meldingsforespørsler",
  pedidos: "Forespørsler",
  spam: "Spam",
  pedidosPendentes: "Ventende forespørsler",
  marcadosComoSpam: "Merket som spam",
  aceitar: "Godta",
  ignorar: "Ignorer",
  marcarSpam: "Merk som spam",
  semPedidos: "Ingen forespørsler venter.",
  semPedidosDetalhe: "Den som ikke er vennen din, men deler en server med deg, havner her før det når samtalene dine.",
  semSpam: "Ingenting merket som spam.",
  semSpamDetalhe: "Det spamfilteret siler ut, eller det du merker selv, blir i denne fanen.",
  umServidorEmComum: "1 felles server",
  servidoresEmComum: "{{quantos}} felles servere",
  semServidoresEmComum: "Ingen felles servere",
};
