export const chamada = {
  conectando: "Kobler til samtalen…",
  naoEntrou: "Kunne ikke bli med i samtalen",
  sair: "Forlat samtalen",
  sairDaVoz: "Forlat talesamtalen",
  desconectar: "Koble fra",
  voltar: "Tilbake til samtalen",
  voltarAosQuadros: "Tilbake til samtalerutene",
  fecharChat: "Lukk chatten",
  carregandoPrevia: "Laster forhåndsvisningen…",
  maisOpcoes: "Flere valg",
  deVideo: "Videosamtale",
  deVoz: "Talesamtale",
  alguem: "Noen",
  volume: {
    entrada: "Inngangsvolum",
    saida: "Utgangsvolum",
    live: "Volum på sendingen",
    liveComPorcento: "Volum på sendingen ({{porcento}} %)",
    liveSemSom: "Sending uten lyd",
  },
  aparelhos: {
    entrada: "Inndataenhet",
    saida: "Utdataenhet",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Utgang",
    oDoSistema: "Systemets",
    aDoSistema: "Systemets",
    semEscolhaDeSaida: "Denne nettleseren lar deg ikke velge utgang — systemet bestemmer.",
    espelhar: "Speil kameraet mitt",
    configEntrada: "Innstillinger for inngang",
    configSaida: "Innstillinger for utgang",
    configCamera: "Kamerainnstillinger",
    configAudioEVideo: "Lyd- og videoinnstillinger",
  },
  tela: {
    compartilhar: "Del skjerm",
    compartilharAcao: "Del",
    cancelar: "Avbryt",
    telas: "Skjermer",
    janelas: "Vinduer",
    somDoComputador: "Ta med lyden fra maskinen",
    somDoSistema: "Ta med lyden fra systemet",
    configCompartilhamento: "Delingsinnstillinger",
    mostrarSemVideo: "Vis dem uten video",
    semFontes: "Systemet returnerte ingen skjerm eller vindu å dele.",
    pararDeCompartilhar: "Slutt å dele",
    encerrarTransmissao: "Avslutt sendingen",
  },
  live: {
    etiqueta: "Direkte",
    etiquetaMaiuscula: "DIREKTE",
    assistir: "Se sendingen",
    assistirPessoa: "Se {{nome}}",
    pararDeAssistir: "Slutt å se",
  },
  membro: {
    mudarMeuApelido: "Endre kallenavnet mitt",
    meuMicrofone: "Mikrofonen min",
    ouvirChamada: "Hør på samtalen",
    copiarMeuId: "Kopier ID-en min",
    idCopiado: "ID kopiert.",
    mensagem: "Melding",
    silenciar: "Demp",
    alterarApelido: "Endre kallenavn",
    cargos: "Roller",
    semCargo: "Ingen rolle er opprettet",
    moverPara: "Flytt til",
    silenciarNoServidor: "Demp stemmen på serveren",
    desativarAudioNoServidor: "Slå av lyden på serveren",
    desconectar: "Koble fra",
    apelidoTitulo: "Kallenavnet ditt på denne serveren",
    apelidoDeAlguem: "Kallenavn for {{nome}}",
    apelidoCampo: "Kallenavn",
    apelidoDicaPropria: "Gjelder bare her. La feltet stå tomt for å gå tilbake til det vanlige navnet ditt.",
    apelidoDicaDeOutro: "Gjelder bare på denne serveren. La feltet stå tomt for å gå tilbake til det opprinnelige navnet.",
  },
  detalhes: {
    abrir: "Taledetaljer",
    titulo: "Taledetaljer",
    conexao: "Tilkobling",
    pingMedio: "Gjennomsnittlig ping",
    ultimoPing: "Siste ping",
    perda: "Tap av sendte pakker",
    medindo: "Måler…",
    criptografado: "Kryptert helt fram til serveren (DTLS-SRTP)",
    explicacao: "Over 250 ms merkes forsinkelsen i samtalen — folk begynner å snakke i munnen på hverandre. Pakketap over 10 % gjør stemmen robotaktig. I begge tilfeller ligger problemet nesten alltid mellom deg og internett: prøv kabel i stedet for wifi, eller start ruteren på nytt.",
  },
  microfone: {
    bloqueado: "Mikrofonen er blokkert — du bare hører på. Gi tilgang i nettleserens tillatelser.",
    bloqueadoNoMac: "macOS blokkerer mikrofonen. Kryss av for",
    caminhoNoMac: "Systeminnstillinger → Personvern og sikkerhet → Mikrofon",
    abrirAjustes: "Åpne innstillingene",
    vaiReabrir: "macOS vil be deg åpne appen på nytt.",
    naoAbriu: "Kunne ikke åpne mikrofonen — du bare hører på. Sjekk enheten under Innstillinger → Tale og video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS har ikke tillatt skjermopptak ennå. Uten det blir delingen svart.",
    marque: "Kryss av for",
    reabra: "under Skjermopptak og åpne appen på nytt.",
    jaMarcado: "Hvis det allerede er krysset av, ble tillatelsen utdatert ved siste oppdatering: fjern krysset, sett det på nytt og åpne appen igjen.",
  },
  ruido: {
    titulo: "Støyreduksjon",
    explicacao: "Ta bakgrunnsstøyen ut av stemmen din. Prøv å klappe eller dra tastaturet mens du snakker — de i samtalen hører bare deg.",
    semSuporte: "Denne nettleseren kjører ikke den avanserte reduksjonen. Nettleserens egen gjelder fortsatt, og den er svakere.",
    aplicando: "Bruker på samtalen…",
    faleParaTestar: "Snakk for å teste",
    verdeQuandoPassa: "Grønt når stemmen din kommer gjennom.",
    teOuvindo: "De hører deg nå.",
    feitoCom: "Laget med",
    aquiNoAparelho: ", her på din egen enhet",
    ajustes: "Innstillinger",
  },
  permissoes: {
    titulo: "macOS-tillatelser",
    detalhe: "macOS spør bare én gang, og etterpå endres det bare i dets eget panel. Her ser du hva som gjelder, og løser det som mangler.",
    concedida: "Gitt",
    negada: "Avslått",
    naoPedida: "Ikke bedt om",
    permitir: "Tillat",
    abrirAjustes: "Åpne innstillinger",
    microfone: "Mikrofon",
    microfoneDetalhe: "Snakke i samtaler og teste inngangen din.",
    camera: "Kamera",
    cameraDetalhe: "Slå på videoen i samtalen.",
    tela: "Skjermopptak",
    telaDetalhe: "Dele skjermen og vinduene.",
    monitoramento: "Inngangsovervåking",
    monitoramentoDetalhe: "Bruke trykk-for-å-snakke selv med Gravaê i bakgrunnen.",
  },
  jaConectado: {
    titulo: "Du er allerede i denne samtalen",
    trazer: "Hent samtalen hit",
    deixar: "La det være",
    detalhe: "Henter du den hit, faller den andre enden ut av samtalen — kontoen din er ett sted om gangen.",
  },
};
