export const comum = {
  carregando: "Laster…",
  salvar: "Lagre",
  salvando: "Lagrer…",
  descartar: "Forkast",
  redefinir: "Tilbakestill",
  naoSalvo: "Du har ulagrede endringer.",
  fechar: "Lukk",
  criar: "Opprett",
  nome: "Navn",
  emoji: "Emoji",
  previa: "Forhåndsvisning",
  cancelar: "Avbryt",
  enviar: "Send",
  apagar: "Slett",
  excluir: "Slett",
  remover: "Fjern",
  trocar: "Bytt",
};
