export const configuracoes = {
  efeitos: {
    titulo: "Effekter for pekeren",
    detalhe: "Spor og gnister tegnet oppå appen. De starter av, og slår seg av selv om du ba om mindre bevegelse.",
    rastro: "Spor etter pekeren",
    rastroDetalhe: "En strek som følger pekeren og falmer bak.",
    faisca: "Gnist ved klikk",
    faiscaDetalhe: "Korte streker som spretter ut fra der du klikket.",
    cor: "Farge",
    espessura: "Tykkelse",
    comprimento: "Lengde",
    tamanho: "Størrelse",
    quantidade: "Antall",
  },
  email: {
    verificarTitulo: "Bekreft e-posten din",
    verificarDetalhe: "Noen fellesskap lar bare de bekreftede skrive. Det tar ett klikk.",
    enviar: "Send lenken",
    enviado: "Se i innboksen. Lenken holder en dag.",
    falhou: "E-posten lot seg ikke sende.",
    confirmado: "E-post bekreftet",
    confirmadoDetalhe: "Ferdig. Nå skriver du i alle fellesskap som krever det.",
    linkIncompleto: "Ufullstendig lenke",
    linkIncompletoDetalhe: "Koden mangler i adressen. Åpne lenken rett fra e-posten.",
    confirmando: "Bekrefter…",
    expirou: "Denne lenken er allerede brukt eller utløpt.",
    irParaOApp: "Gå til appen",
  },
  tema: {
    indisponivel: "Temaet er ikke tilgjengelig",
    indisponivelDetalhe: "Den som la det ut har slettet det, eller lenken er feil.",
    indisponivelLinha: "Temaet er ikke tilgjengelig. Den som la det ut har slettet det, eller lenken er feil.",
    importar: "Importer tema",
    importarCurto: "Importer",
    importarDetalhe: "Dette bytter ut temaet du har nå. Du kan redigere det etterpå i Innstillinger > Utseende > Temastudio.",
    porAutor: "av {{autor}}",
    umaCorTrocada: "1 farge byttet",
    coresTrocadas: "{{quantas}} farger byttet",
    avisoDeCss: "Dette temaet har med seg CSS fra den som skrev det, og CSS når hver krok av skjermen. Importer bare fra folk du stoler på.",
    soCores: "Dette temaet bytter bare farger. Ingen CSS utenfra.",
    aplicar: "Bruk",
    previaSemMotor: "Forhåndsvisningen kjører ikke motoren. Installer for å se den.",
    motorAnimado: "{{motor}} animert",
  },
  sair: "Logg ut",
  versoes: {
    termos: "Vilkår for bruk",
    privacidade: "Personvernerklæring",
    copiar: "Klikk for å kopiere",
    copiado: "Kopiert",
  },
  telas: {
    conta: "Min konto",
    privacidade: "Personvern",
    conexoes: "Tilkoblinger",
    voz: "Lyd",
    video: "Video",
    avisos: "Varsler",
    aplicativos: "Applikasjoner",
    aparencia: "Utseende",
    batePapo: "Chat",
    acessibilidade: "Tilgjengelighet",
    idioma: "Språk",
    aplicativo: "Last ned appen",
    atalhos: "Snarveier",
    desktop: "Skrivebordsapp",
    avancado: "Avansert",
    servidor: "Server",
    comunicado: "Systemmelding",
    denuncias: "Rapporter",
    publicacoes: "Utrullinger",
  },
  grupos: {
    conta: "Konto",
    app: "App-innstillinger",
    desenvolvedor: "Utvikler",
    administracao: "Administrasjon",
  },
  secoes: {
    detalhesDeLogin: "Innloggingsdetaljer",
    dispositivos: "Enheter",
    usuariosBloqueados: "Blokkerte brukere",
    aplicativosAutorizados: "Autoriserte apper",
    sessoes: "Økter",
    amigosEDms: "Venner og direktemeldinger",
    compartilhamentoDeAtividade: "Aktivitetsdeling",
    visibilidadeDoPerfil: "Profilens synlighet",
    exportarDados: "Eksporter data",
    exclusaoDeDados: "Slett data",
    tema: "Tema",
    corDeDestaque: "Aksentfarge",
    interface: "Grensesnitt",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Appens zoomnivå",
    escalaDaFonte: "Skriftstørrelse i chatten",
    modoStreamer: "Personvern under strømming",
    cursores: "Markører",
    movimento: "Bevegelse",
    textoEmVoz: "Tekst til tale",
    teclado: "Tastatur",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Grensesnittets språk",
    dispositivosDeVoz: "Enheter",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inndatamodus",
    sensibilidade: "Inndatafølsomhet",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Sending",
    exibicao: "Visning",
    entrada: "Inndata",
    midia: "Medier",
    geral: "Generelt",
    preferenciaDeMencao: "Omtalepreferanse",
    sons: "Lyder",
  },
};
