export const configuracoes = {
  telas: {
    conta: "Min konto",
    privacidade: "Personvern",
    conexoes: "Tilkoblinger",
    voz: "Lyd",
    video: "Video",
    avisos: "Varsler",
    aplicativos: "Applikasjoner",
    aparencia: "Utseende",
    batePapo: "Chat",
    acessibilidade: "Tilgjengelighet",
    idioma: "Språk",
    aplicativo: "Last ned appen",
    servidor: "Server",
  },
  grupos: {
    conta: "Konto",
    app: "App-innstillinger",
    desenvolvedor: "Utvikler",
    administracao: "Administrasjon",
  },
  secoes: {
    detalhesDeLogin: "Innloggingsdetaljer",
    dispositivos: "Enheter",
    usuariosBloqueados: "Blokkerte brukere",
    aplicativosAutorizados: "Autoriserte apper",
    sessoes: "Økter",
    amigosEDms: "Venner og direktemeldinger",
    compartilhamentoDeAtividade: "Aktivitetsdeling",
    visibilidadeDoPerfil: "Profilens synlighet",
    exportarDados: "Eksporter data",
    exclusaoDeDados: "Slett data",
    tema: "Tema",
    corDeDestaque: "Aksentfarge",
    interface: "Grensesnitt",
    listaDeCanais: "Kanalliste",
    zoomDoApp: "Appens zoomnivå",
    escalaDaFonte: "Skriftstørrelse i chatten",
    modoStreamer: "Personvern under strømming",
    movimento: "Bevegelse",
    textoEmVoz: "Tekst til tale",
    teclado: "Tastatur",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Grensesnittets språk",
    dispositivosDeVoz: "Enheter",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inndatamodus",
    sensibilidade: "Inndatafølsomhet",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Sending",
    exibicao: "Visning",
    entrada: "Inndata",
    midia: "Medier",
    geral: "Generelt",
    preferenciaDeMencao: "Omtalepreferanse",
    sons: "Lyder",
  },
};
