export const conversa = {
  lista: {
    carregando: "Laster meldinger…",
    carregandoMais: "Laster…",
    verMais: "Bla oppover for å se mer",
    semHistorico: "Historikken er ikke tilgjengelig",
    semHistoricoDetalhe: "Rollen din har ikke tillatelse til å lese historikken i #{{canal}}. Nye meldinger fortsetter å dukke opp så lenge du er her.",
    boasVindas: "Velkommen til #{{canal}}",
    boasVindasDetalhe: "Dette er starten på kanalen #{{canal}}.",
  },
  data: {
    hoje: "I dag",
    ontem: "I går",
    hojeAs: "i dag kl. {{hora}}",
    ontemAs: "i går kl. {{hora}}",
  },
  digitando: {
    um: "{{nome}} skriver…",
    dois: "{{primeiro}} og {{segundo}} skriver…",
    varios: "{{quantidade}} personer skriver…",
  },
  mensagem: {
    usou: "brukte",
    fixada: "festet",
    editado: "(redigert)",
    ignorada: "Melding fra noen du ignorerer.",
    mostrar: "Vis",
    escPara: "Esc for å",
    cancelar: "avbryte",
    enterParaSalvar: "Enter for å lagre",
    falhou: "Den ble ikke sendt. Prøv igjen",
    naoLidasDaqui: "Uleste herfra.",
    linkCopiado: "Lenken er kopiert.",
    idCopiado: "ID er kopiert.",
    naoDeuParaCopiar: "Nettleseren din tillot ikke kopiering.",
    apagarTitulo: "Slette meldingen?",
    apagarDescricao: "Den forsvinner for alle i kanalen. Den kan ikke hentes tilbake.",
    apagarAcao: "Slett",
    citacaoAnexo: "klikk for å se vedlegget",
    citacaoSumiu: "Den opprinnelige meldingen er ikke her lenger.",
    reagirCom: "Reager med {{emoji}} — hold inne for superreaksjon",
    segureParaSuper: "{{emoji}} — hold inne for superreaksjon",
  },
  acoes: {
    reagir: "Reager",
    responder: "Svar",
    encaminhar: "Videresend",
    favoritar: "Lagre meldingen",
    tirarDosFavoritos: "Fjern fra lagrede",
    marcarNaoLida: "Merk som ulest",
    copiarLink: "Kopier lenken til meldingen",
    copiarId: "Kopier meldingens ID",
    fixar: "Fest meldingen",
    desafixar: "Løsne",
    editar: "Rediger",
    apagar: "Slett",
    mais: "Mer",
    adicionarReacao: "Legg til reaksjon",
    superReagirCom: "Superreager med {{emoji}}",
    fixarMensagem: "Fest meldingen",
    desafixarMensagem: "Løsne meldingen",
    editarMensagem: "Rediger meldingen",
    apagarMensagem: "Slett meldingen",
  },
  mencao: {
    cargo: "Rolleomtale",
    pessoa: "Omtale",
    alguem: "noen",
    cargoSemNome: "rolle",
    here: "Varsler dem som er tilkoblet",
    everyone: "Varsler hele serveren",
  },
  codigo: {
    copiar: "Kopier",
    copiado: "Kopiert",
    copiarAria: "Kopier koden",
    copiadoAria: "Koden er kopiert",
  },
  caixa: {
    escrever: "Skriv i #{{canal}}",
    escreverSemCanal: "Skriv en melding",
    semPermissao: "Du har ikke tillatelse til å sende meldinger i denne kanalen",
    solteParaAnexar: "Slipp for å legge ved",
    respondendoPara: "Svar til",
    vaiNotificar: "Personen får varsel",
    naoVaiNotificar: "Personen får ikke varsel",
    ligado: "på",
    desligado: "av",
    pararDeResponder: "Slutt å svare",
    mais: "Mer",
    enviarArquivo: "Send en fil",
    criarEnquete: "Lag en avstemning",
    expressoes: "Emoji, GIF og klistremerker",
    enviar: "Send",
    aguardandoEnvio: "Venter på opplastingen",
    modoLento: "Sakte modus på ({{tempo}})",
    modoLentoDica: "Sakte modus er satt til {{segundos}} s. Vent før du sender neste melding.",
  },
  anexos: {
    enviando: "Laster opp…",
    modificar: "Endre {{arquivo}}",
    remover: "Fjern {{arquivo}}",
    ver: "Se {{arquivo}}",
    mostrarSpoiler: "Vis spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Rediger vedlegget",
    nomeDoArquivo: "Filnavn",
    descricao: "Beskrivelse av alternativ tekst",
    descricaoDica: "Beskriv dette mediet for skjermlesere",
    marcarSpoiler: "Merk som spoiler",
    cancelar: "Avbryt",
    salvar: "Lagre",
  },
  cartao: {
    tocador: "Spiller",
    abrir: "Åpne {{destino}}",
    tocar: "Spill av {{titulo}}",
    video: "video",
    verImagem: "Se bildet",
  },
  enquete: {
    titulo: "Avstemning",
    encerrada: "Avstemningen er lukket",
    variasRespostas: "Avstemning — flere svar",
    umVoto: "{{quantidade}} stemme",
    votos: "{{quantidade}} stemmer",
    umVotoNoTotal: "{{quantidade}} stemme totalt",
    votosNoTotal: "{{quantidade}} stemmer totalt",
    encerraEm: "lukkes {{quando}}",
    encerrarAgora: "Lukk nå",
  },
  fixadas: {
    titulo: "Festede meldinger",
    vazio: "Denne kanalen har ingen festede meldinger… ennå.",
    desafixar: "Løsne",
    anexo: "(vedlegg)",
    enquete: "(avstemning)",
    dicaRotulo: "TIPS:",
    dica: "den som har tillatelsen «Administrere meldinger», kan feste direkte fra meldingsmenyen.",
  },
  encaminhar: {
    titulo: "Videresend meldingen",
    paraOnde: "Hvor?",
    semTexto: "(melding uten tekst)",
    nenhumLugar: "Ingen steder med det navnet.",
    canais: "Kanaler",
    conversas: "Direktemeldinger",
  },
};
