export const conversa = {
  acenar: {
    ilustracao: "En liten hånd som vinker",
    botao: "Vink til {{nome}}",
  },
  oficial: {
    titulo: "Denne kanalen er bare for offisielle meldinger.",
    detalhe: "Vi spør aldri om passordet ditt eller kontoens token.",
    saibaMais: "Les mer",
  },
  topico: {
    abrir: "Se beskrivelsen av kanalen",
  },
  previaDoLink: {
    carregando: "Ser hva som ligger bak lenken…",
    destino: "Går til {{destino}}",
  },
  reacao: {
    carregando: "Ser hvem som reagerte med {{emoji}}…",
    uma: "{{nome}} reagerte med {{emoji}}",
    duas: "{{primeiro}} og {{segundo}} reagerte med {{emoji}}",
    varias: "{{nomes}} og {{quantos}} til reagerte med {{emoji}}",
    dicaSuper: "Hold inne for superreaksjon",
  },
  recado: {
    gravar: "Ta opp en talemelding",
    descartar: "Forkast opptaket",
    mandar: "Send opptaket",
    semSuporte: "Denne nettleseren tar ikke opp lyd.",
    semMicrofone: "Ingen tilgang til mikrofonen.",
  },
  lista: {
    carregando: "Laster meldinger…",
    carregandoMais: "Laster…",
    verMais: "Bla oppover for å se mer",
    semHistorico: "Historikken er ikke tilgjengelig",
    semHistoricoDetalhe: "Rollen din har ikke tillatelse til å lese historikken i #{{canal}}. Nye meldinger fortsetter å dukke opp så lenge du er her.",
    boasVindas: "Velkommen til #{{canal}}",
    boasVindasDetalhe: "Dette er starten på kanalen #{{canal}}.",
  },
  data: {
    hoje: "I dag",
    ontem: "I går",
    hojeAs: "i dag kl. {{hora}}",
    ontemAs: "i går kl. {{hora}}",
  },
  digitando: {
    um: "{{nome}} skriver…",
    dois: "{{primeiro}} og {{segundo}} skriver…",
    varios: "{{quantidade}} personer skriver…",
  },
  mensagem: {
    usou: "brukte",
    fixada: "festet",
    editado: "(redigert)",
    ignorada: "Melding fra noen du ignorerer.",
    mostrar: "Vis",
    escPara: "Esc for å",
    cancelar: "avbryte",
    enterParaSalvar: "Enter for å lagre",
    naoLidasDaqui: "Uleste herfra.",
    linkCopiado: "Lenken er kopiert.",
    idCopiado: "ID er kopiert.",
    naoDeuParaCopiar: "Nettleseren din tillot ikke kopiering.",
    apagarTitulo: "Slette meldingen?",
    apagarDescricao: "Den forsvinner for alle i kanalen. Den kan ikke hentes tilbake.",
    apagarAcao: "Slett",
    citacaoAnexo: "klikk for å se vedlegget",
    citacaoSumiu: "Den opprinnelige meldingen er ikke her lenger.",
    encaminhadaDe: "Videresendt fra",
    irParaOriginal: "Gå til original",
    bloqueadas: "{{quantas}} blokkerte meldinger",
    mostrarBloqueadas: "Vis",
    esconderBloqueadas: "Skjul",
    reagirCom: "Reager med {{emoji}} — hold inne for superreaksjon",
    segureParaSuper: "{{emoji}} — hold inne for superreaksjon",
  },
  imagem: {
    copiarImagem: "Kopier bilde",
    baixarImagem: "Last ned bilde",
    copiarLinkDaImagem: "Kopier bildelenke",
    abrirLinkDaImagem: "Åpne bildelenke",
    maisAcoes: "Flere mediehandlinger",
    pesquisarImagem: "Søk etter bilde",
    copiarIdDoAnexo: "Kopier vedlegg-id",
    girarEsquerda: "Roter til venstre",
    girarDireita: "Roter til høyre",
    ajustar: "Tilpass til skjermen",
    ampliar: "Zoom inn",
    reduzir: "Zoom ut",
    imagemCopiada: "Bildet kopiert.",
    linkCopiado: "Lenken kopiert.",
    idCopiado: "Id kopiert.",
    naoDeuParaCopiar: "Kunne ikke kopiere bildet.",
  },

  acoes: {
    reagir: "Reager",
    responder: "Svar",
    encaminhar: "Videresend",
    favoritar: "Lagre meldingen",
    tirarDosFavoritos: "Fjern fra lagrede",
    marcarNaoLida: "Merk som ulest",
    copiarLink: "Kopier lenken til meldingen",
    copiarId: "Kopier meldingens ID",
    fixar: "Fest meldingen",
    desafixar: "Løsne",
    editar: "Rediger",
    apagar: "Slett",
    mais: "Mer",
    adicionarReacao: "Legg til reaksjon",
    superReagirCom: "Superreager med {{emoji}}",
    fixarMensagem: "Fest meldingen",
    desafixarMensagem: "Løsne meldingen",
    editarMensagem: "Rediger meldingen",
    apagarMensagem: "Slett meldingen",
    denunciarMensagem: "Rapporter meldingen",
  },
  denuncia: {
    titulo: "Rapporter meldingen",
    descricao: "Rapporten går til Gravaê-teamet. Fortell hva som skjedde.",
    de: "Fra {{nome}}",
    semTexto: "(ingen tekst)",
    motivo: "Årsak",
    detalhes: "Detaljer (valgfritt)",
    enviar: "Send rapport",
    enviada: "Rapport sendt. Takk.",
    motivos: {
      spam: "Spam eller reklame",
      assedio: "Trakassering eller hat",
      conteudo: "Upassende innhold",
      golpe: "Svindel",
      outro: "Annet",
    },
  },
  falha: {
    tentarDeNovo: "Prøv igjen",
    erro: "Ikke levert",
    semConexao: "Ikke levert — du har ingen tilkobling",
    semAcesso: "Ikke levert — denne kanalen er ikke lenger innen rekkevidde",
    semPermissao: "Ikke levert — du kan ikke skrive her",
    castigo: "Ikke levert — du har utestengelse på denne serveren",
    modoLento: "Ikke levert — sakte modus er ikke over ennå",
    depressa: "Ikke levert — du sender for raskt",
    automod: "Ikke levert — AutoMod blokkerte den",
    recusada: "Ikke levert — denne samtalen tar ikke imot svar",
    naoEntregue: "Ikke levert — denne personen tar ikke imot meldinger fra deg",
  },
  mencao: {
    cargo: "Rolleomtale",
    pessoa: "Omtale",
    alguem: "noen",
    cargoSemNome: "rolle",
    here: "Varsler dem som er tilkoblet",
    everyone: "Varsler hele serveren",
  },
  codigo: {
    copiar: "Kopier",
    copiado: "Kopiert",
    copiarAria: "Kopier koden",
    copiadoAria: "Koden er kopiert",
    recolher: "Skjul",
    expandir: "Utvid",
    verInteiro: "Se hele filen",
    maisOpcoes: "Flere valg",
    baixar: "Last ned",
    recolherLinhas: "Skjul ({{linhas}} linjer)",
    expandirLinhas: "Utvid ({{linhas}} linjer)",
    mudarIdioma: "Bytt språk",
    procurarIdioma: "Søk etter språkkode…",
    nenhumIdioma: "Fant ingen språk.",
    quebrarTexto: "Bryt tekst",
  },
  caixa: {
    escrever: "Skriv i #{{canal}}",
    escreverSemCanal: "Skriv en melding",
    semPermissao: "Du har ikke tillatelse til å sende meldinger i denne kanalen",
    solteParaAnexar: "Slipp for å legge ved",
    longaTitulo: "Meldingen din er for lang…",
    longaDescricao: "Du har nådd grensen på {{limite}} tegn. Du kan sende den som fil.",
    enviarComoArquivo: "Send som fil",
    textoComoArquivo: "Send teksten som fil",
    arquivoGrandeTitulo: "Filen er for stor",
    arquivoGrandeDescricao: "«{{arquivo}}» overskrider grensen på {{limite}} MB per fil.",
    respondendoPara: "Svar til",
    vaiNotificar: "Personen får varsel",
    naoVaiNotificar: "Personen får ikke varsel",
    ligado: "på",
    desligado: "av",
    pararDeResponder: "Slutt å svare",
    mais: "Mer",
    enviarArquivo: "Send en fil",
    criarEnquete: "Lag en avstemning",
    expressoes: "Emoji, GIF og klistremerker",
    enviar: "Send",
    aguardandoEnvio: "Venter på opplastingen",
    modoLento: "Sakte modus på ({{tempo}})",
    modoLentoDica: "Sakte modus er satt til {{segundos}} s. Vent før du sender neste melding.",
  },
  anexos: {
    enviando: "Laster opp…",
    modificar: "Endre {{arquivo}}",
    verPrevia: "Forhåndsvis {{arquivo}}",
    excluirTitulo: "Slett vedlegget",
    excluirDescricao: "Slette «{{arquivo}}»? Det kan ikke angres, og det fjernes fra meldingen.",
    excluirAcao: "Slett vedlegget",
    excluirFalhou: "Klarte ikke å slette vedlegget.",
    remover: "Fjern {{arquivo}}",
    ver: "Se {{arquivo}}",
    mostrarSpoiler: "Vis spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Rediger vedlegget",
    nomeDoArquivo: "Filnavn",
    descricao: "Beskrivelse av alternativ tekst",
    descricaoDica: "Beskriv dette mediet for skjermlesere",
    marcarSpoiler: "Merk som spoiler",
    cancelar: "Avbryt",
    salvar: "Lagre",
  },
  cartao: {
    tocador: "Spiller",
    abrir: "Åpne {{destino}}",
    tocar: "Spill av {{titulo}}",
    video: "video",
    verImagem: "Se bildet",
  },
  enquete: {
    criar: "Lag en avstemning",
    pergunta: "Spørsmål",
    exemplo: "Hva spiller vi i dag?",
    respostas: "Svar",
    adicionarOpcao: "Legg til svar",
    removerOpcao: "Fjern svar",
    varias: "Tillat mer enn ett svar",
    variasDetalhe: "Uten dette tar en stemme på ett svar stemmen bort fra det forrige.",
    duracao: "Varighet",
    umaHora: "1 time",
    quatroHoras: "4 timer",
    oitoHoras: "8 timer",
    umDia: "1 dag",
    tresDias: "3 dager",
    umaSemana: "1 uke",
    ateEncerrar: "Til jeg lukker den",
    titulo: "Avstemning",
    encerrada: "Avstemningen er lukket",
    variasRespostas: "Avstemning — flere svar",
    umVoto: "{{quantidade}} stemme",
    votos: "{{quantidade}} stemmer",
    umVotoNoTotal: "{{quantidade}} stemme totalt",
    votosNoTotal: "{{quantidade}} stemmer totalt",
    encerraEm: "lukkes {{quando}}",
    encerrarAgora: "Lukk nå",
  },
  fixadas: {
    titulo: "Festede meldinger",
    vazio: "Denne kanalen har ingen festede meldinger… ennå.",
    desafixar: "Løsne",
    anexo: "(vedlegg)",
    enquete: "(avstemning)",
    dicaRotulo: "TIPS:",
    dica: "den som har tillatelsen «Administrere meldinger», kan feste direkte fra meldingsmenyen.",
  },
  encaminhar: {
    titulo: "Videresend meldingen",
    paraOnde: "Hvor?",
    semTexto: "(melding uten tekst)",
    nenhumLugar: "Ingen steder med det navnet.",
    canais: "Kanaler",
    conversas: "Direktemeldinger",
  },
  expressoes: {
    gifs: "Gif-er",
    buscarGifs: "Søk på Klipy",
    figurinha: "Klistremerke",
    buscarFigurinha: "Finn det perfekte klistremerket",
    buscarEmoji: "Finn den perfekte emojien",
    buscarReacao: "Finn den perfekte reaksjonen",
    adicionarEmoji: "Legg til emoji",
    limparBusca: "Tøm søket",
  },
  busca: {
    pesquisar: "Søk",
    limpar: "Tøm søk",
    filtros: "Søkefiltre",
    escopo: {
      titulo: "Søkeområde",
      servidor: "Nåværende fellesskap",
      canal: "Denne samtalen",
      comunidades: "Alle fellesskap",
      dms: "Bare direktemeldinger",
      tudo: "Direktemeldinger og fellesskap",
    },
    fechar: "Lukk søket",
    procurando: "Søker…",
    resultado: "{{quantos}} treff",
    resultados: "{{quantos}} treff",
    nadaCom: "Ingenting med {{termo}} her.",
    soOsQuePodeLer: "Søket ser bare i kanaler du får lese.",
  },
  entrada: {
    semNome: "samtale",
    anexo: "(vedlegg)",
    titulo: "Innboks",
    naoLidas: "Uleste",
    salvas: "Lagret",
    mencoes: "Omtaler",
    fimTitulo: "Du har kommet til slutten",
    fimDetalhe: "Det er ingenting igjen å lese. Når en ny melding kommer, dukker den opp her.",
    semSalvosTitulo: "Ingenting lagret",
    semSalvosDetalhe: "Hold Skift og klikk på bokmerket til en melding for å ta vare på den og lese senere.",
    tirarDosSalvos: "Fjern fra lagrede",
    semMencoesTitulo: "Ingen omtaler ennå",
    semMencoesDetalhe: "Omtaler av deg dukker opp her for de siste 7 dagene.",
  },
  forum: {
    descricao: "Hvert tema blir en egen samtale — greit for spørsmålet som ikke må forsvinne midt i praten.",
    novoAssunto: "Nytt tema",
    vazio: "Ingen tema ennå. Start det første, så holder samtalen seg ryddig fra begynnelsen.",
    titulo: "Tittel",
    doQueSeTrata: "Hva handler det om?",
    primeiraMensagem: "Første melding",
    conteDoCaso: "Fortell",
  },
};
