export const perfil = {
  carregando: "Laster…",
  editar: "Rediger profilen",
  mensagem: "Melding",
  abrirConversa: "Åpne samtalen",
  verCompleto: "Se hele profilen",
  convidarParaServidor: "Inviter til serveren",
  semServidores: "Du har ingen servere",
  conviteEnviado: "Invitasjon sendt til {{nome}}.",
  moderador: "Åpne i moderatorvisning",
  mais: "Mer",
  ignorar: "Ignorer",
  deixarDeIgnorar: "Slutt å ignorere",
  copiarId: "Kopier bruker-ID",
  idCopiado: "ID kopiert.",
  conexoes: "Tilkoblinger",
  membroDesde: "Medlem siden",
  sobre: "Om",
  cargosTitulo: "Roller",
  visaoGeral: "Oversikt",
  amigosEmComum: "Felles venner ({{quantidade}})",
  servidoresEmComum: "Felles servere ({{quantidade}})",
  amizade: {
    amigo: "Venn",
    pedidoEnviado: "Venneforespørsel sendt",
    respondaAbaixo: "Sendte deg en forespørsel — svar nedenfor",
    adicionar: "Legg til venn",
    teMandouPedido: "Sendte deg en venneforespørsel",
    aceitar: "Godta",
    desfazer: "Fjern venn",
    desfazerTitulo: "Fjerne {{nome}} fra vennene dine?",
    desfazerDescricao: "Dere er ikke venner lenger. Den private samtalen blir liggende i historikken, og du kan legge personen til igjen senere.",
    bloquear: "Blokker",
    bloquearTitulo: "Blokkere {{nome}}?",
    bloquearDescricao: "Dere er ikke venner lenger, den private samtalen tar ikke imot flere meldinger, og personen kan ikke sende deg en venneforespørsel igjen.",
    linkCopiado: "Dere er ikke venner — lenken ble kopiert, så du kan sende den.",
  },
  recado: {
    escrever: "Skriv til @{{usuario}}",
    enviar: "Send",
    enviada: "Meldingen ble sendt",
    falhou: "Den kunne ikke sendes. Prøv fra samtalen.",
  },
  cartao: {
    trocarFaixa: "Bytt bannerbildet på kortet",
    trocarFaixaCurto: "Bytt banner",
    trocarFoto: "Bytt profilbilde",
    trocarFotoCurto: "Bytt bilde",
    suaEtiqueta: "Etiketten din",
    editarEtiqueta: "Klikk for å redigere etiketten",
    conteAlgo: "Fortell noe om deg selv",
    adicionarStatus: "Legg til en status",
    adicionarDescricao: "Klikk for å legge til en beskrivelse",
    cargo: "Rolle",
    cargos: "Roller",
    cargosCom: "Roller — {{quantidade}}",
    tirarCargo: "Fjern rollen {{cargo}}",
  },
  cargos: {
    adicionar: "Legg til rolle",
    procurar: "Søk etter en rolle",
  },
  etiqueta: {
    escolher: "Velg serveretikett",
    nenhuma: "Ingen serveretikett",
    semEtiqueta: "Ingen av serverne dine har en etikett",
  },
  emblemas: {
    doServidor: "Merker fra denne serveren",
    limite: "Du kan bære opptil {{quantidade}} merker.",
  },
  nota: {
    vazia: "Klikk for å skrive et notat",
    rotulo: "Notat (bare du ser det)",
  },
  status: {
    titulo: "Status",
    definir: "Angi statusen din",
    escolherEmoji: "Velg emoji",
    tirarEmoji: "Fjern emojien",
    oQuePensa: "Hva tenker du på?",
    limparAgora: "Tøm statusen nå",
    naoLimpar: "Ikke tøm",
    limpar30m: "Tøm om 30 minutter",
    limpar1h: "Tøm om 1 time",
    limpar4h: "Tøm om 4 timer",
    limparHoje: "Tøm i dag",
    limparAmanha: "Tøm i morgen",
    comHora: "{{prazo}} kl. {{hora}}",
  },
  presenca: {
    disponivel: "Tilgjengelig",
    ausente: "Borte",
    naoPerturbar: "Ikke forstyrr",
    naoPerturbarDetalhe: "Du får ingen varsel om nye meldinger",
    invisivel: "Usynlig",
    invisivelDetalhe: "For andre ser du frakoblet ut",
  },
  menu: {
    mudarDeConta: "Bytt konto",
    gerenciarContas: "Administrer kontoer",
  },
  editor: {
    decoracao: "Bytt avatardekorasjonen",
    naoSalvo: "Ikke glem å lagre endringene dine!",
    principal: "Hovedprofil",
  },
};
