export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Serverinnstillinger",
  auditoria: {
    todasAsAcoes: "Alle handlinger",
    todosOsUsuarios: "Alle brukere",
    filtroMembros: "Medlemmer",
    filtroCanais: "Kanaler",
    filtroEmojis: "Emojier",
    filtroServidor: "Server",
    titulo: "Hendelseslogg",
    porUsuario: "Filtrer på person",
    porAcao: "Filtrer på handling",
    vazio: "Ingenting logget ennå med dette filteret.",
    motivo: "Grunn:",
  },
  banimentos: {
    titulo: "Serverens utestengingsliste",
    descricao: "Den som står her kommer ikke inn igjen, ikke engang med ny invitasjon. Å oppheve utestengingen gir tilgangen tilbake med en gang.",
    procurar: "Søk i utestenginger på brukernavn",
    vazioTitulo: "Ingen utestenginger",
    vazio: "Du har ikke utestengt noen ennå … men om og når det trengs, ikke nøl.",
    desbanir: "Opphev utestenging",
  },
  excluir: {
    tudoVai: "Alle kanaler, meldinger og invitasjoner i {{servidor}} slettes for de {{membros}} medlemmene. Ingen kan hente dem tilbake etterpå.",
    digite: "Skriv {{servidor}} for å bekrefte",
    titulo: "Slett server",
    aviso: "Dette kan ikke angres.",
  },
  emblemas: {
    apagarDescricao: "Det forsvinner fra alle som bruker det. Dette kan ikke angres.",
    titulo: "Merker",
    vazio: "Ingen merker ennå.",
    novo: "Nytt merke",
  },
  convites: {
    revogarTitulo: "Trekke tilbake invitasjonen?",
    revogarAcao: "Trekk tilbake",
    revogarDescricao: "Lenken {{codigo}} slutter å virke med en gang. Den som allerede ble med via den blir værende på serveren.",
    titulo: "Invitasjoner",
    descricao: "Alle aktive invitasjonslenker for denne serveren.",
    vazio: "Ingen invitasjon er laget ennå.",
    revogar: "Trekk tilbake invitasjon",
  },
  integracoes: {
    opcionais: "username og avatar_url er valgfrie og gjelder per melding. Grensen er 5 meldinger hvert 5. sekund.",
    apagarDescricao: "URL-en slutter å virke med en gang. Meldingene den allerede sendte blir stående i kanalen.",
    titulo: "Integrasjoner",
    descricao: "En webhook er en adresse som poster i en kanal uten å trenge konto. Nyttig for å melde at et bygg gikk gjennom, at noen åpnet en sak, eller hva du nå vil sende fra et skript.",
    novo: "Ny webhook",
    vazio: "Ingen webhooker ennå. Lag en og lim inn URL-en der du vil at meldingen skal komme fra.",
    canal: "Kanal",
    apagar: "Slett webhook",
    comoUsar: "Slik bruker du det",
    comoUsarTexto: "Send en POST med JSON:",
  },
  explorar: {
    titulo: "Utforsk",
  },
  engajamento: {
    semCanal: "Ingen systemkanal",
    titulo: "Engasjement",
    descricao: "Hva serveren gjør av seg selv så den ikke virker tom når noen ny kommer.",
    sistema: "Systemmeldinger",
    boasVindas: "Send en velkomstmelding når noen blir med",
    sorteio: "Uten egen tekst under trekkes setningen tilfeldig — den samme hver gang blir fort kjedelig.",
    canalDoSistema: "Kanal for systemmeldinger",
    mensagem: "Velkomstmelding",
    deixeVazio: "La stå tom for å trekke blant de ferdige setningene",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtre som modererer av seg selv, før meldingen i det hele tatt finnes. Den som administrerer serveren blir aldri filtrert — og unntatte roller går rett gjennom.",
    palavras: {
      titulo: "Blokker egne ord",
      descricao: "Din liste over ord ingen får skrive.",
    },
    mencoes: {
      titulo: "Blokker omtale-spam",
      descricao: "Blokkerer en melding med for mange omtaler på én gang.",
    },
    links: {
      titulo: "Blokker lenker",
      descricao: "Holder tilbake enhver adresse som limes inn i praten.",
    },
    definir: "Sett opp",
    nomeDaRegra: "Navn på regelen",
    bloqueadas: "Blokkerte ord",
    digiteEnter: "Skriv og trykk Enter",
    comparacao: "Sammenligningen ser bort fra store bokstaver, aksenter og tegnsetting — og tar ikke et ord inne i et annet.",
    aPartirDe: "Blokker fra hvor mange omtaler",
    oQueFazer: "Hva som skal skje",
    canalDoAlerta: "Kanal for varselet",
    escolhaCanal: "Velg en kanal",
    castigo: "Utestengelse (minutter)",
    isentos: "Unntatte roller",
    semCargos: "Ingen roller er laget ennå.",
    salvarRegra: "Lagre regel",
    apagar: "Slett regel",
    excluirTitulo: "Slette denne AutoMod-regelen?",
    excluirDescricao: "Serveren slutter å filtrere etter den med en gang. Du kan lage den på nytt, men det nåværende oppsettet går tapt.",
    excluirAcao: "Slett regel",
  },
  cargos: {
    titulo: "Roller",
    descricao: "Roller gir navn, farge og makt. Den som står høyere på lista bestemmer over dem under — og ingen rører en rolle som er lik eller høyere enn sin egen.",
    criar: "Lag rolle",
    vazio: "Ingen roller ennå.",
    abaExibicao: "Utseende",
    abaPermissoes: "Rettigheter",
    abaMembros: "Medlemmer — {{quantos}}",
    everyone: "Gjelder alle på serveren. Det er grunnlaget de andre rollene legges oppå.",
    nomeDoCargo: "Navn på rollen",
    cor: "Farge på rollen",
    corDica: "Farger navnet til den som har rollen i medlemslista og i praten.",
    semCor: "Uten farge",
    corPersonalizada: "Egen farge",
    estilo: "Stil på navnet",
    segundaCor: "Andre farge",
    segundaCorDica: "Uten den faller overgangen tilbake til én farge — den forsvinner ikke.",
    limparSegundaCor: "Fjern andre farge",
    icone: "Ikon",
    iconeDica: "Vises ved siden av rollen på profilkortet til den som har den.",
    exibirSeparado: "Vis atskilt fra de andre medlemmene",
    exibirSeparadoDica: "Rollen får sin egen del i medlemslista.",
    permitirMencionar: "Tillat å nevne denne rollen",
    permitirMencionarDica: "Hvem som helst kan da varsle alle som har rollen.",
    semPoderDeConceder: "{{descricao}} (du har ikke denne rettigheten til å gi den bort)",
    adicionar: "Legg noen til denne rollen",
    tirar: "Ta bort rollen",
    semNinguem: "Ingen har denne rollen ennå.",
    apagar: "Slett rolle",
    excluirTitulo: "Slette rollen «{{nome}}»?",
    excluirDescricao: "Den som har rollen mister alt den ga. Dette kan ikke angres.",
    excluirAcao: "Slett rolle",
  },
  membros: {
    procurar: "Søk på navn eller brukernavn",
    membroDesde: "Medlem siden",
    vazio: "Ingen funnet.",
    acoesPara: "Handlinger for {{nome}}",
    deCastigo: "utestengelse",
    tirarCastigo: "Opphev utestengelsen",
    castigo5min: "5 minutter",
    castigo1h: "1 time",
    castigo1d: "1 dag",
    castigo1s: "1 uke",
    expulsar: "Kast ut",
    expulsarTitulo: "Kaste ut {{nome}}?",
    expulsarDescricao: "forlater {{servidor}} med en gang. Kan komme tilbake med en invitasjon — å kaste ut hindrer ikke returen.",
    banir: "Utesteng",
    banirTitulo: "Utestenge {{nome}}?",
    banirDescricao: "forlater {{servidor}} og kan ikke komme tilbake, ikke engang med invitasjon, før utestengingen oppheves.",
    motivo: "Grunn (valgfritt)",
    motivoDica: "Blir stående i hendelsesloggen",
  },
  perfil: {
    titulo: "Serverprofil",
    descricao: "Slik vises serveren din i lista og i invitasjonslenker.",
    icone: "Ikon",
    faixa: "Banner øverst",
    nomeDoServidor: "Navn på serveren",
    campoDescricao: "Beskrivelse",
    doQueE: "Hva handler denne serveren om?",
    comprimido: "Komprimert før opplasting: {{economia}}",
  },
  etiqueta: {
    titulo: "Servertagg",
    descricao: "En merkelapp på inntil 4 bokstaver som vises ved siden av navnet til hvert medlem — i praten og i personlista. Her er den gratis: uten boost, uten nivåer.",
    escolhaNome: "Velg et navn",
    limite: "Høyst 4 tegn, bokstaver og tall.",
    escolhaInsignia: "Velg et merke",
    voce: "Du",
    fala1: "noen som vil spille?",
    fala2: "sjekk taggen min!",
    fala3: "oi, hvor fikk du tak i den",
  },
  expressoes: {
    comoUsar: "Legg til inntil {{limite}} emojier som alle kan bruke på denne serveren. Skriv :navn: i praten for å sende en.",
    imagem: "Bilde",
    enviadoPor: "Lastet opp av",
    semEmoji: "Ingen emojier ennå.",
    figurinhas: "Klistremerker",
    enviarFigurinha: "Last opp klistremerke",
    nomeDaFigurinha: "Navn på klistremerket",
    exemploFigurinha: "F.eks.: kattungeklem",
    figurinhaGrande: "Klistremerket er større enn {{limite}}.",
    deixaPraLa: "Glem det",
    sons: "Lydpanel",
    enviarSom: "Last opp lyd",
    nomeDoSom: "Navn på lyden",
    semSom: "Ingen lyder ennå.",
    somGrande: "Lyden er større enn {{limite}}.",
    emojiRelacionado: "Tilhørende emoji",
    ouvir: "Hør",
    ouvirAssim: "Hør den slik",
    volumeDe: "Volum for {{nome}}",
    volumeDica: "Gjelder alle på serveren. Hver enkelt kan likevel skru ned lydene bare for seg selv, i samtalepanelet.",
    falhaEnvio: "Fila kunne ikke lastes opp.",
    excluirTitulo: "Slette {{tipo}} «{{nome}}»?",
    excluirDescricao: "Den forsvinner fra serveren for alle. Meldinger som allerede brukte den blir stående som de er.",
  },
  canal: {
    visaoGeral: "Oversikt",
    nome: "Navn på kanalen",
    topico: "Tema for kanalen",
    topicoDica: "Hva snakker man om her?",
    modoLento: "Hver person sender bare én melding per intervall. Den som håndterer meldinger eller kanaler går rett gjennom.",
    visibilidade: "Synlighet for innholdet",
    padrao: "Standard",
    padraoDica: "Innholdet i kanalen er alltid synlig.",
    spoiler: "Spoilerkanal",
    spoilerDica: "Merk denne kanalen som spoilerkanal, så vendinger og tunge tema blir skjult til noen velger å se.",
    idade: "Aldersbegrenset kanal",
    idadeDica: "Den som går inn må bekrefte at hen er myndig for å se innholdet.",
    bitrateDica: "Over 64 kbps kan plage dem med dårlig forbindelse.",
    qualidadeDeVideo: "Videokvalitet",
    automatica: "Automatisk",
    limite: "Brukergrense — {{valor}}",
    pessoas: "{{quantos}} personer",
    semLimite: "uten grense",
    permissoesDescricao: "Her endrer du hva som gjelder i denne kanalen. Det som står igjen på «arv» følger fortsatt rollen.",
    excluir: {
      titulo: "Slett kanal",
      historico: "Hele historikken til {{canal}} følger med, for alle.",
      digite: "Skriv {{canal}} for å bekrefte",
    },
  },
  moderacao: {
    titulo: "Moderatorvisning",
    semPermissao: "Du trenger tillatelsen «Moderer medlemmer» for å se dette.",
    fecharEsc: "Lukk (Esc)",
    atividade: "Aktivitet på serveren",
    mensagens: "Meldinger",
    links: "Lenker",
    midia: "Medier",
    acoesNaAuditoria: "Handlinger i hendelsesloggen",
    moderacoesSofridas: "Mottatt moderering",
    permissoes: "Rettigheter ({{quantas}})",
    semPermissaoEspecial: "Ingen spesielle rettigheter.",
    conta: "Konto",
    entrouNoServidor: "Ble med i serveren",
    contaCriadaEm: "Konto opprettet",
    deCastigoAte: "Utestengt til",
    formaDeAdesao: "Hvordan hen kom inn",
    mensagem: "Melding",
    castigo: "Utestengelse",
    copiarId: "Kopier ID",
    idCopiado: "ID kopiert.",
    adicionarCargo: "Legg til rolle",
    semCargos: "Ingen rolle laget",
    soEveryone: "Bare @everyone.",
    voltar: "Tilbake",
    vazio: "Ingenting her.",
    cinquenta: "Viser de 50 nyeste.",
    irParaMensagem: "Gå til meldingen",
    precisaSerAmigo: "Dere må være venner for å prate.",
    expulsarDescricao: "Forlater serveren med en gang, men kan komme tilbake med en invitasjon.",
    banirDescricao: "Forlater serveren og kan ikke komme tilbake, ikke engang med invitasjon, før utestengingen oppheves.",
    castigarTitulo: "Utesteng {{nome}} midlertidig?",
    castigoDescricao: "Så lenge den varer skriver eller snakker hen ikke i noen kanal på serveren.",
    aplicarCastigo: "Bruk utestengelsen",
    duracao: "Varighet i minutter",
    informeDuracao: "Oppgi varigheten i minutter.",
  },
  abas: {
    expressoes: "Uttrykk",
    pessoas: "Folk",
    apps: "Apper",
    moderacao: "Moderering",
    banimentos: "Utestengelser",
  },
};
