export const chamada = {
  conectando: "Connecting to the call…",
  naoEntrou: "Could not join the call",
  sair: "Leave the call",
  sairDaVoz: "Leave the voice call",
  desconectar: "Disconnect",
  voltar: "Back to the call",
  voltarAosQuadros: "Back to the call tiles",
  fecharChat: "Close chat",
  carregandoPrevia: "Loading the preview…",
  maisOpcoes: "More options",
  deVideo: "Video call",
  deVoz: "Voice call",
  alguem: "Someone",
  volume: {
    entrada: "Input volume",
    saida: "Output volume",
    live: "Live volume",
    liveComPorcento: "Live volume ({{porcento}}%)",
    liveSemSom: "Live muted",
  },
  aparelhos: {
    entrada: "Input device",
    saida: "Output device",
    camera: "Camera",
    microfone: "Microphone",
    saidaCurto: "Output",
    oDoSistema: "The system default",
    aDoSistema: "The system default",
    semEscolhaDeSaida: "This browser does not let you pick the output — the system decides.",
    espelhar: "Mirror my camera",
    configEntrada: "Input settings",
    configSaida: "Output settings",
    configCamera: "Camera settings",
    configAudioEVideo: "Audio and video settings",
  },
  tela: {
    compartilhar: "Share screen",
    compartilharAcao: "Share",
    cancelar: "Cancel",
    telas: "Screens",
    janelas: "Windows",
    somDoComputador: "Bring the computer audio along",
    somDoSistema: "Bring the system audio along",
    configCompartilhamento: "Sharing settings",
    mostrarSemVideo: "Show people without video",
    semFontes: "The system returned no screen or window to share.",
    pararDeCompartilhar: "Stop sharing",
    encerrarTransmissao: "End the broadcast",
  },
  live: {
    etiqueta: "Live",
    etiquetaMaiuscula: "LIVE",
    assistir: "Watch the broadcast",
    assistirPessoa: "Watch {{nome}}",
    pararDeAssistir: "Stop watching",
  },
  membro: {
    mudarMeuApelido: "Change my nickname",
    meuMicrofone: "My microphone",
    ouvirChamada: "Listen to the call",
    copiarMeuId: "Copy my ID",
    idCopiado: "ID copied.",
    mensagem: "Message",
    silenciar: "Mute",
    alterarApelido: "Change nickname",
    cargos: "Roles",
    semCargo: "No role created",
    moverPara: "Move to",
    silenciarNoServidor: "Server mute",
    desativarAudioNoServidor: "Server deafen",
    desconectar: "Disconnect",
    apelidoTitulo: "Your nickname on this server",
    apelidoDeAlguem: "{{nome}}'s nickname",
    apelidoCampo: "Nickname",
    apelidoDicaPropria: "Only here. Leave it empty to go back to your usual name.",
    apelidoDicaDeOutro: "Only on this server. Leave it empty to go back to the original name.",
  },
  detalhes: {
    abrir: "Voice details",
    titulo: "Voice Details",
    conexao: "Connection",
    pingMedio: "Average ping",
    ultimoPing: "Last ping",
    perda: "Sent packet loss",
    medindo: "Measuring…",
    criptografado: "Encrypted to the server (DTLS-SRTP)",
    explicacao: "Above 250 ms the delay becomes noticeable and people start talking over each other. Packet loss above 10% makes the voice robotic. In both cases the problem is almost always between you and the internet: try a cable instead of Wi-Fi, or restart the router.",
  },
  microfone: {
    bloqueado: "Microphone blocked — you are listening only. Allow access in the browser permissions.",
    bloqueadoNoMac: "macOS is blocking the microphone. Tick",
    caminhoNoMac: "System Settings → Privacy & Security → Microphone",
    abrirAjustes: "Open the settings",
    vaiReabrir: "macOS will ask you to reopen the app.",
    naoAbriu: "Could not open the microphone — you are listening only. Check the device in Settings → Voice and video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS has not allowed screen recording yet. Without it the share comes out black.",
    marque: "Tick",
    reabra: "under Screen Recording and reopen the app.",
  },
  ruido: {
    titulo: "Noise suppression",
    explicacao: "Take the background noise out of your voice. Try clapping or dragging the keyboard while you talk — the people in the call only hear you.",
    semSuporte: "This browser does not run the advanced suppression. The browser's own one still applies, and it is weaker.",
    aplicando: "Applying to the call…",
    faleParaTestar: "Speak to test",
    verdeQuandoPassa: "Green when your voice gets through.",
    teOuvindo: "They can hear you right now.",
    feitoCom: "Made with",
    aquiNoAparelho: ", right here on your device",
    ajustes: "Settings",
  },
  permissoes: {
    titulo: "macOS permissions",
    detalhe: "macOS asks only once, and after that it only changes in its own panel. Here you can see what's in effect and fix what's missing.",
    concedida: "Granted",
    negada: "Denied",
    naoPedida: "Not requested",
    permitir: "Allow",
    abrirAjustes: "Open settings",
    microfone: "Microphone",
    microfoneDetalhe: "Talking in calls and testing your input.",
    camera: "Camera",
    cameraDetalhe: "Turning the video on in a call.",
    tela: "Screen recording",
    telaDetalhe: "Sharing the screen and windows.",
    monitoramento: "Input monitoring",
    monitoramentoDetalhe: "Using push-to-talk even with Gravaê in the background.",
  },
  jaConectado: {
    titulo: "You are already in this call",
    trazer: "Bring the call here",
    deixar: "Leave it as it is",
    detalhe: "Bringing it here drops the other end from the call — your account stays in one place at a time.",
  },
};
