export const comum = {
  carregando: "Loading…",
  salvar: "Save",
  salvando: "Saving…",
  descartar: "Discard",
  redefinir: "Reset",
  naoSalvo: "You have unsaved changes.",
  fechar: "Close",
  criar: "Create",
  nome: "Name",
  emoji: "Emoji",
  previa: "Preview",
  cancelar: "Cancel",
  enviar: "Send",
  apagar: "Delete",
  excluir: "Delete",
  remover: "Remove",
  trocar: "Change",
};
