export const amizades = {
  ativosAgora: "Attivi ora",
  procurando: "Vediamo chi c'è in giro…",
  tudoTranquilo: "Tutto tranquillo per ora…",
  tudoTranquiloDetalhe: "Quando tu o un amico entrate in una chiamata, comparirà qui — e potrai unirti con un clic.",
  emVoz: "In vocale",
  voce: "Tu",
  soVoce: "Solo tu",
  pessoas: "{{quantas}} persone",
  voltarParaChamada: "Torna alla chiamata",
  entrarNaChamada: "Entra nella chiamata",
  abrirCanal: "Apri {{canal}} in {{servidor}}",
  mensagensDiretas: "Messaggi diretti",
  encontreConversa: "Trova una conversazione",
  amigos: "Amici",
  conversas: "Conversazioni",
  semConversas: "Ancora nessuna conversazione. Aggiungi un amico per iniziare.",
  semConversaComEsseNome: "Nessuna conversazione con quel nome.",
  abrirMenu: "Apri server e conversazioni",
  solicitacoes: "Richieste di messaggio",
  pedidos: "Richieste",
  spam: "Spam",
  pedidosPendentes: "Richieste in sospeso",
  marcadosComoSpam: "Segnati come spam",
  aceitar: "Accetta",
  ignorar: "Ignora",
  marcarSpam: "Segna come spam",
  semPedidos: "Nessuna richiesta in attesa.",
  semPedidosDetalhe: "Chi non è tuo amico ma condivide un server con te finisce qui prima di arrivare alle tue conversazioni.",
  semSpam: "Niente segnato come spam.",
  semSpamDetalhe: "Quello che il filtro antispam mette da parte, o quello che segni tu, resta in questa scheda.",
  umServidorEmComum: "1 server in comune",
  servidoresEmComum: "{{quantos}} server in comune",
  semServidoresEmComum: "Nessun server in comune",
};
