export const chamada = {
  conectando: "Connessione alla chiamata…",
  naoEntrou: "Non è stato possibile entrare nella chiamata",
  sair: "Esci dalla chiamata",
  sairDaVoz: "Esci dalla chiamata vocale",
  desconectar: "Disconnetti",
  voltar: "Torna alla chiamata",
  voltarAosQuadros: "Torna ai riquadri della chiamata",
  fecharChat: "Chiudi la chat",
  carregandoPrevia: "Caricamento dell'anteprima…",
  maisOpcoes: "Altre opzioni",
  deVideo: "Videochiamata",
  deVoz: "Chiamata vocale",
  alguem: "Qualcuno",
  volume: {
    entrada: "Volume d'ingresso",
    saida: "Volume d'uscita",
    live: "Volume della diretta",
    liveComPorcento: "Volume della diretta ({{porcento}}%)",
    liveSemSom: "Diretta senza audio",
  },
  aparelhos: {
    entrada: "Dispositivo d'ingresso",
    saida: "Dispositivo d'uscita",
    camera: "Fotocamera",
    microfone: "Microfono",
    saidaCurto: "Uscita",
    oDoSistema: "Quello di sistema",
    aDoSistema: "Quella di sistema",
    semEscolhaDeSaida: "Questo browser non lascia scegliere l'uscita — decide il sistema.",
    espelhar: "Rifletti la mia fotocamera",
    configEntrada: "Impostazioni d'ingresso",
    configSaida: "Impostazioni d'uscita",
    configCamera: "Impostazioni della fotocamera",
    configAudioEVideo: "Impostazioni audio e video",
  },
  tela: {
    compartilhar: "Condividi lo schermo",
    compartilharAcao: "Condividi",
    cancelar: "Annulla",
    telas: "Schermi",
    janelas: "Finestre",
    somDoComputador: "Porta anche l'audio del computer",
    somDoSistema: "Porta anche l'audio di sistema",
    configCompartilhamento: "Impostazioni di condivisione",
    mostrarSemVideo: "Mostra chi è senza video",
    semFontes: "Il sistema non ha restituito nessuno schermo o finestra da condividere.",
    pararDeCompartilhar: "Smetti di condividere",
    encerrarTransmissao: "Termina la diretta",
  },
  live: {
    etiqueta: "In diretta",
    etiquetaMaiuscula: "IN DIRETTA",
    assistir: "Guarda la diretta",
    assistirPessoa: "Guarda {{nome}}",
    pararDeAssistir: "Smetti di guardare",
  },
  membro: {
    mudarMeuApelido: "Cambia il mio soprannome",
    meuMicrofone: "Il mio microfono",
    ouvirChamada: "Ascolta la chiamata",
    copiarMeuId: "Copia il mio ID",
    idCopiado: "ID copiato.",
    mensagem: "Messaggio",
    silenciar: "Silenzia",
    alterarApelido: "Cambia soprannome",
    cargos: "Ruoli",
    semCargo: "Nessun ruolo creato",
    moverPara: "Sposta in",
    silenciarNoServidor: "Silenzia la voce sul server",
    desativarAudioNoServidor: "Disattiva l'audio sul server",
    desconectar: "Disconnetti",
    apelidoTitulo: "Il tuo soprannome su questo server",
    apelidoDeAlguem: "Soprannome di {{nome}}",
    apelidoCampo: "Soprannome",
    apelidoDicaPropria: "Vale solo qui. In bianco, torna a valere il tuo nome di sempre.",
    apelidoDicaDeOutro: "Vale solo su questo server. Lascialo in bianco per tornare al nome originale.",
  },
  detalhes: {
    abrir: "Dettagli della voce",
    titulo: "Dettagli della Voce",
    conexao: "Connessione",
    pingMedio: "Ping medio",
    ultimoPing: "Ultimo ping",
    perda: "Perdita di pacchetti inviati",
    medindo: "Misurazione…",
    criptografado: "Cifrato fino al server (DTLS-SRTP)",
    explicacao: "Sopra i 250 ms il ritardo si sente e le persone iniziano a sovrapporsi. Una perdita di pacchetti sopra il 10% rende la voce robotica. In entrambi i casi il problema è quasi sempre tra te e la rete: prova il cavo invece del Wi-Fi, o riavvia il router.",
  },
  microfone: {
    bloqueado: "Microfono bloccato — stai solo ascoltando. Concedi l'accesso nei permessi del browser.",
    bloqueadoNoMac: "macOS sta bloccando il microfono. Spunta",
    caminhoNoMac: "Impostazioni di Sistema → Privacy e sicurezza → Microfono",
    abrirAjustes: "Apri le impostazioni",
    vaiReabrir: "macOS ti chiederà di riaprire l'applicazione.",
    naoAbriu: "Non è stato possibile aprire il microfono — stai solo ascoltando. Controlla il dispositivo in Impostazioni → Voce e video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS non ha ancora autorizzato la registrazione dello schermo. Senza, la condivisione esce nera.",
    marque: "Spunta",
    reabra: "in Registrazione schermo e riapri l'applicazione.",
  },
  ruido: {
    titulo: "Soppressione del rumore",
    explicacao: "Togli il rumore di fondo dalla tua voce. Prova a battere le mani o a trascinare la tastiera mentre parli — chi è in chiamata sente solo te.",
    semSuporte: "Questo browser non esegue la soppressione avanzata. Resta valida quella del browser stesso, che è più debole.",
    aplicando: "Applicazione alla chiamata…",
    faleParaTestar: "Parla per provare",
    verdeQuandoPassa: "Verde quando la tua voce passa.",
    teOuvindo: "Ti stanno sentendo adesso.",
    feitoCom: "Fatto con",
    aquiNoAparelho: ", qui sul tuo dispositivo",
    ajustes: "Impostazioni",
  },
  permissoes: {
    titulo: "Permessi di macOS",
    detalhe: "macOS chiede una volta sola, e poi cambia solo dal suo pannello. Qui vedi cosa vale e risolvi quello che manca.",
    concedida: "Concesso",
    negada: "Negato",
    naoPedida: "Non richiesto",
    permitir: "Consenti",
    abrirAjustes: "Apri le impostazioni",
    microfone: "Microfono",
    microfoneDetalhe: "Parlare nelle chiamate e provare il tuo ingresso.",
    camera: "Fotocamera",
    cameraDetalhe: "Accendere il video nella chiamata.",
    tela: "Registrazione schermo",
    telaDetalhe: "Condividere lo schermo e le finestre.",
    monitoramento: "Monitoraggio dell'ingresso",
    monitoramentoDetalhe: "Usare il push-to-talk anche con Gravaê in secondo piano.",
  },
  jaConectado: {
    titulo: "Sei già in questa chiamata",
    trazer: "Porta la chiamata qui",
    deixar: "Lascia com'è",
    detalhe: "Portandola qui, l'altro capo esce dalla chiamata — il tuo account sta in un posto per volta.",
  },
};
