export const configuracoes = {
  efeitos: {
    titulo: "Effetti del puntatore",
    detalhe: "Scia e scintille disegnate sopra l'applicazione. Partono spente e si spengono da sole se hai chiesto meno animazione.",
    rastro: "Scia del cursore",
    rastroDetalhe: "Una linea che segue il puntatore e sfuma dietro.",
    faisca: "Scintilla al clic",
    faiscaDetalhe: "Trattini che partono dal punto in cui hai cliccato.",
    cor: "Colore",
    espessura: "Spessore",
    comprimento: "Lunghezza",
    tamanho: "Dimensione",
    quantidade: "Quantità",
  },
  email: {
    verificarTitulo: "Conferma la tua email",
    verificarDetalhe: "Certe comunità lasciano scrivere solo a chi ha confermato. Basta un clic.",
    enviar: "Manda il link",
    enviado: "Guarda la posta in arrivo. Il link dura un giorno.",
    falhou: "Non è stato possibile mandare l'email.",
    confirmado: "Email confermata",
    confirmadoDetalhe: "Fatto. Ora scrivi in qualunque comunità lo richieda.",
    linkIncompleto: "Link incompleto",
    linkIncompletoDetalhe: "Nell'indirizzo manca il codice. Apri il link direttamente dall'email.",
    confirmando: "Conferma in corso…",
    expirou: "Questo link è già stato usato o è scaduto.",
    irParaOApp: "Vai all'applicazione",
  },
  tema: {
    indisponivel: "Tema non disponibile",
    indisponivelDetalhe: "Chi l'ha pubblicato l'ha cancellato, oppure il link è sbagliato.",
    indisponivelLinha: "Tema non disponibile. Chi l'ha pubblicato l'ha cancellato, oppure il link è sbagliato.",
    importar: "Importa il tema",
    importarCurto: "Importa",
    importarDetalhe: "Questo sostituisce il tema che hai ora. Potrai modificarlo dopo in Impostazioni > Aspetto > Studio dei temi.",
    porAutor: "di {{autor}}",
    umaCorTrocada: "1 colore cambiato",
    coresTrocadas: "{{quantas}} colori cambiati",
    avisoDeCss: "Questo tema porta con sé il CSS di chi l'ha scritto, e il CSS tocca ogni angolo dello schermo. Importa solo da persone di cui ti fidi.",
    soCores: "Questo tema cambia solo i colori. Nessun CSS da fuori.",
    aplicar: "Applica",
    previaSemMotor: "L'anteprima non esegue il motore. Installalo per vederlo.",
    motorAnimado: "{{motor}} animato",
  },
  sair: "Esci",
  versoes: {
    termos: "Termini di servizio",
    privacidade: "Informativa sulla privacy",
    copiar: "Clicca per copiare",
    copiado: "Copiato",
  },
  telas: {
    conta: "Il mio account",
    privacidade: "Privacy",
    conexoes: "Connessioni",
    voz: "Audio",
    video: "Video",
    avisos: "Notifiche",
    aplicativos: "Applicazioni",
    aparencia: "Aspetto",
    batePapo: "Chat",
    acessibilidade: "Accessibilità",
    idioma: "Lingua",
    aplicativo: "Scarica l'app",
    atalhos: "Scorciatoie",
    desktop: "App desktop",
    avancado: "Avanzate",
    servidor: "Server",
    comunicado: "Comunicato di sistema",
    denuncias: "Segnalazioni",
    publicacoes: "Distribuzioni",
  },
  grupos: {
    conta: "Account",
    app: "Impostazioni dell'app",
    desenvolvedor: "Sviluppatore",
    administracao: "Amministrazione",
  },
  secoes: {
    detalhesDeLogin: "Dati di accesso",
    dispositivos: "Dispositivi",
    usuariosBloqueados: "Utenti bloccati",
    aplicativosAutorizados: "App autorizzate",
    sessoes: "Sessioni",
    amigosEDms: "Amici e messaggi diretti",
    compartilhamentoDeAtividade: "Condivisione attività",
    visibilidadeDoPerfil: "Visibilità del profilo",
    exportarDados: "Esporta dati",
    exclusaoDeDados: "Elimina dati",
    tema: "Tema",
    corDeDestaque: "Colore d'accento",
    interface: "Interfaccia",
    listaDeCanais: "Elenco dei canali",
    zoomDoApp: "Livello di zoom dell'app",
    escalaDaFonte: "Scala del carattere della chat",
    modoStreamer: "Privacy in streaming",
    cursores: "Cursori",
    movimento: "Movimento",
    textoEmVoz: "Sintesi vocale",
    teclado: "Tastiera",
    formatoDaHora: "Formato dell'ora",
    idiomaDaInterface: "Lingua dell'interfaccia",
    dispositivosDeVoz: "Dispositivi",
    testeDoMicrofone: "Test del microfono",
    modoDeEntrada: "Modalità di ingresso",
    sensibilidade: "Sensibilità d'ingresso",
    qualidade: "Qualità",
    camera: "Fotocamera",
    transmissao: "Trasmissione",
    exibicao: "Visualizzazione",
    entrada: "Immissione",
    midia: "Media",
    geral: "Generale",
    preferenciaDeMencao: "Preferenza di menzione",
    sons: "Suoni",
  },
};
