export const configuracoes = {
  telas: {
    conta: "Il mio account",
    privacidade: "Privacy",
    conexoes: "Connessioni",
    voz: "Audio",
    video: "Video",
    avisos: "Notifiche",
    aplicativos: "Applicazioni",
    aparencia: "Aspetto",
    batePapo: "Chat",
    acessibilidade: "Accessibilità",
    idioma: "Lingua",
    aplicativo: "Scarica l'app",
    servidor: "Server",
  },
  grupos: {
    conta: "Account",
    app: "Impostazioni dell'app",
    desenvolvedor: "Sviluppatore",
    administracao: "Amministrazione",
  },
  secoes: {
    detalhesDeLogin: "Dati di accesso",
    dispositivos: "Dispositivi",
    usuariosBloqueados: "Utenti bloccati",
    aplicativosAutorizados: "App autorizzate",
    sessoes: "Sessioni",
    amigosEDms: "Amici e messaggi diretti",
    compartilhamentoDeAtividade: "Condivisione attività",
    visibilidadeDoPerfil: "Visibilità del profilo",
    exportarDados: "Esporta dati",
    exclusaoDeDados: "Elimina dati",
    tema: "Tema",
    corDeDestaque: "Colore d'accento",
    interface: "Interfaccia",
    listaDeCanais: "Elenco dei canali",
    zoomDoApp: "Livello di zoom dell'app",
    escalaDaFonte: "Scala del carattere della chat",
    modoStreamer: "Privacy in streaming",
    movimento: "Movimento",
    textoEmVoz: "Sintesi vocale",
    teclado: "Tastiera",
    formatoDaHora: "Formato dell'ora",
    idiomaDaInterface: "Lingua dell'interfaccia",
    dispositivosDeVoz: "Dispositivi",
    testeDoMicrofone: "Test del microfono",
    modoDeEntrada: "Modalità di ingresso",
    sensibilidade: "Sensibilità d'ingresso",
    qualidade: "Qualità",
    camera: "Fotocamera",
    transmissao: "Trasmissione",
    exibicao: "Visualizzazione",
    entrada: "Immissione",
    midia: "Media",
    geral: "Generale",
    preferenciaDeMencao: "Preferenza di menzione",
    sons: "Suoni",
  },
};
