export const configuracoes = {
  efeitos: {
    titulo: "Effetti del puntatore",
    detalhe: "Scia e scintille disegnate sopra l'applicazione. Partono spente e si spengono da sole se hai chiesto meno animazione.",
    rastro: "Scia del cursore",
    rastroDetalhe: "Una linea che segue il puntatore e sfuma dietro.",
    faisca: "Scintilla al clic",
    faiscaDetalhe: "Trattini che partono dal punto in cui hai cliccato.",
    cor: "Colore",
    espessura: "Spessore",
    comprimento: "Lunghezza",
    tamanho: "Dimensione",
    quantidade: "Quantità",
  },
  email: {
    verificarTitulo: "Conferma la tua email",
    verificarDetalhe: "Certe comunità lasciano scrivere solo a chi ha confermato. Basta un clic.",
    enviar: "Manda il link",
    enviado: "Guarda la posta in arrivo. Il link dura un giorno.",
    falhou: "Non è stato possibile mandare l'email.",
    confirmado: "Email confermata",
    confirmadoDetalhe: "Fatto. Ora scrivi in qualunque comunità lo richieda.",
    linkIncompleto: "Link incompleto",
    linkIncompletoDetalhe: "Nell'indirizzo manca il codice. Apri il link direttamente dall'email.",
    confirmando: "Conferma in corso…",
    expirou: "Questo link è già stato usato o è scaduto.",
    irParaOApp: "Vai all'applicazione",
  },
  tema: {
    indisponivel: "Tema non disponibile",
    indisponivelDetalhe: "Chi l'ha pubblicato l'ha cancellato, oppure il link è sbagliato.",
    indisponivelLinha: "Tema non disponibile. Chi l'ha pubblicato l'ha cancellato, oppure il link è sbagliato.",
    importar: "Importa il tema",
    importarCurto: "Importa",
    importarDetalhe: "Questo sostituisce il tema che hai ora. Potrai modificarlo dopo in Impostazioni > Aspetto > Studio dei temi.",
    porAutor: "di {{autor}}",
    umaCorTrocada: "1 colore cambiato",
    coresTrocadas: "{{quantas}} colori cambiati",
    avisoDeCss: "Questo tema porta con sé il CSS di chi l'ha scritto, e il CSS tocca ogni angolo dello schermo. Importa solo da persone di cui ti fidi.",
    soCores: "Questo tema cambia solo i colori. Nessun CSS da fuori.",
    verCss: "Mostra il CSS",
    esconderCss: "Nascondi il CSS",
    aplicar: "Applica",
    previaSemMotor: "L'anteprima non esegue il motore. Installalo per vederlo.",
    motorAnimado: "{{motor}} animato",
  },
  sair: "Esci",
  versoes: {
    termos: "Termini di servizio",
    privacidade: "Informativa sulla privacy",
    copiar: "Clicca per copiare",
    copiado: "Copiato",
  },
  subscription: {
    seePlans: "Vedi i piani",
    upgradeSubtitle: "Limiti più alti e funzioni esclusive per scrivere, inviare file e trasmettere.",
    perMonth: "al mese",
    perYear: "all'anno",
    save: "Risparmia il {{percent}}%",
    howToPay: "Come vuoi pagare?",
    legal: "Puoi chiedere il rimborso entro 7 giorni dal pagamento. Il pagamento è gestito da Stripe; non vediamo mai il numero della tua carta.",
    compare: "Gratis vs Infinity",
    featureColumn: "Funzione",
    freeColumn: "Gratis",
    messageRow: "Limite di caratteri del messaggio",
    attachmentRow: "Dimensione file da inviare",
    screenRow: "Qualità video",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Hai già Infinity fino al {{date}}.",
    upsell: "Aumenta il limite con Infinity",
    screenUpsell: "Più qualità con Infinity",
    free: "Sei nel piano gratuito.",
    activeUntil: "Infinity attivo fino al {{date}}.",
    renews: "Si rinnova automaticamente il {{date}}.",
    endsAt: "L'abbonamento è stato annullato e termina il {{date}}.",
    pastDue: "L'ultimo addebito non è andato a buon fine. Aggiorna la carta per non perdere il Infinity.",
    waiting: "Conferma del pagamento…",
    subscribe: "Abbonati",
    monthly: "Mensile",
    yearly: "Annuale",
    automatic: "Carta, rinnovo automatico",
    manage: "Gestisci pagamento",
    refund: "Richiedi rimborso",
    refundDetail: "Puoi recedere entro 7 giorni dal pagamento: {{amount}}, fino al {{date}}.",
    refundConfirm: "Richiedere il rimborso?",
    refundConfirmDetail: "Il denaro torna sullo stesso metodo di pagamento e il Infinity termina subito.",
    refunded: "Rimborso richiesto.",
    unavailable: "L'abbonamento non è ancora disponibile.",
    success: "Pagamento ricevuto. Grazie!",
    canceled: "Pagamento annullato.",
    error: "Qualcosa è andato storto. Riprova.",
    no: "No",
    tagRow: "Tag utente personalizzato",
    guildProfilesRow: "Profili per community",
    badgeRow: "Badge del profilo",
    communitiesRow: "Community",
    savedRow: "Messaggi salvati",
    animatedEmojiRow: "Usa emoji animate",
    expressionsRow: "Accesso globale a emoji e sticker",
    animatedProfileRow: "Avatar e banner del profilo animati",
    earlyAccessRow: "Accesso anticipato alle novità",
    themesRow: "Temi personalizzati",
    pixOption: "Pix, solo questo periodo",
    pixHint: "Apri l'app della banca, scegli Pix e scansiona il QR code o usa copia e incolla.",
    pixQrAlt: "QR code Pix",
    pixCopy: "Copia codice Pix",
    pixCopied: "Codice Pix copiato",
    pixWaiting: "In attesa del pagamento",
    pixExpiresIn: "scade tra {{time}}",
    pixExpired: "Questo Pix è scaduto. Generane un altro per continuare.",
    pixNew: "Genera un altro Pix",
    pixPaid: "Pix ricevuto! Il tuo Infinity è attivo.",
    forMe: "Per me",
    asGift: "Come regalo",
    buyGift: "Compra regalo",
    giftReady: "Regalo pronto! Copia il link e mandalo a chi vuoi.",
    giftClaimed: "Regalo riscattato! Infinity è sul tuo account.",
    gifts: "Regali",
    giftsEmpty: "Non hai ancora comprato nessun regalo.",
    giftCode: "Codice del regalo",
    giftRedeem: "Riscatta",
    giftCopyLink: "Copia link",
    giftLinkCopied: "Link copiato",
    giftClaimedBy: "riscattato da {{name}}",
    giftHint: "Hai un codice regalo? Riscattalo qui. I regali comprati sono qui sotto.",
  },
  telas: {
    subscription: "Infinity",
    conta: "Il mio account",
    privacidade: "Privacy",
    conexoes: "Connessioni",
    voz: "Audio",
    video: "Video",
    avisos: "Notifiche",
    aplicativos: "Applicazioni",
    aparencia: "Aspetto",
    batePapo: "Chat",
    acessibilidade: "Accessibilità",
    idioma: "Lingua",
    aplicativo: "Scarica l'app",
    atalhos: "Scorciatoie",
    desktop: "App desktop",
    avancado: "Avanzate",
    servidor: "Server",
    comunicado: "Comunicato di sistema",
    denuncias: "Segnalazioni",
    publicacoes: "Distribuzioni",
  },
  grupos: {
    conta: "Account",
    app: "Impostazioni dell'app",
    desenvolvedor: "Sviluppatore",
    administracao: "Amministrazione",
  },
  secoes: {
    detalhesDeLogin: "Dati di accesso",
    dispositivos: "Dispositivi",
    usuariosBloqueados: "Utenti bloccati",
    aplicativosAutorizados: "App autorizzate",
    sessoes: "Sessioni",
    amigosEDms: "Amici e messaggi diretti",
    compartilhamentoDeAtividade: "Condivisione attività",
    visibilidadeDoPerfil: "Visibilità del profilo",
    exportarDados: "Esporta dati",
    exclusaoDeDados: "Elimina dati",
    tema: "Tema",
    corDeDestaque: "Colore d'accento",
    interface: "Interfaccia",
    listaDeCanais: "Elenco dei canali",
    zoomDoApp: "Livello di zoom dell'app",
    escalaDaFonte: "Scala del carattere della chat",
    modoStreamer: "Privacy in streaming",
    cursores: "Cursori",
    movimento: "Movimento",
    textoEmVoz: "Sintesi vocale",
    teclado: "Tastiera",
    formatoDaHora: "Formato dell'ora",
    idiomaDaInterface: "Lingua dell'interfaccia",
    dispositivosDeVoz: "Dispositivi",
    testeDoMicrofone: "Test del microfono",
    modoDeEntrada: "Modalità di ingresso",
    sensibilidade: "Sensibilità d'ingresso",
    qualidade: "Qualità",
    camera: "Fotocamera",
    transmissao: "Trasmissione",
    exibicao: "Visualizzazione",
    entrada: "Immissione",
    midia: "Media",
    geral: "Generale",
    preferenciaDeMencao: "Preferenza di menzione",
    sons: "Suoni",
  },
};
