export const conversa = {
  lista: {
    carregando: "Caricamento dei messaggi…",
    carregandoMais: "Caricamento…",
    verMais: "Scorri verso l'alto per vedere altro",
    semHistorico: "Cronologia non disponibile",
    semHistoricoDetalhe: "Il tuo ruolo non ha il permesso di leggere la cronologia di #{{canal}}. I messaggi nuovi continuano ad apparire finché sei qui.",
    boasVindas: "Benvenuto in #{{canal}}",
    boasVindasDetalhe: "Questo è l'inizio del canale #{{canal}}.",
  },
  data: {
    hoje: "Oggi",
    ontem: "Ieri",
    hojeAs: "oggi alle {{hora}}",
    ontemAs: "ieri alle {{hora}}",
  },
  digitando: {
    um: "{{nome}} sta scrivendo…",
    dois: "{{primeiro}} e {{segundo}} stanno scrivendo…",
    varios: "{{quantidade}} persone stanno scrivendo…",
  },
  mensagem: {
    usou: "ha usato",
    fixada: "fissato",
    editado: "(modificato)",
    ignorada: "Messaggio di una persona che ignori.",
    mostrar: "Mostra",
    escPara: "Esc per",
    cancelar: "annullare",
    enterParaSalvar: "Invio per salvare",
    falhou: "Non è stato inviato. Riprova",
    naoLidasDaqui: "Non letti da qui in poi.",
    linkCopiado: "Link copiato.",
    idCopiado: "ID copiato.",
    naoDeuParaCopiar: "Il tuo browser non ha permesso la copia.",
    apagarTitulo: "Eliminare il messaggio?",
    apagarDescricao: "Sparisce per tutto il canale. Non si può recuperare.",
    apagarAcao: "Elimina",
    citacaoAnexo: "clicca per vedere l'allegato",
    citacaoSumiu: "Il messaggio originale non è più qui.",
    reagirCom: "Reagisci con {{emoji}} — tieni premuto per super reagire",
    segureParaSuper: "{{emoji}} — tieni premuto per super reagire",
  },
  acoes: {
    reagir: "Reagisci",
    responder: "Rispondi",
    encaminhar: "Inoltra",
    favoritar: "Salva il messaggio",
    tirarDosFavoritos: "Togli dai salvati",
    marcarNaoLida: "Segna come non letto",
    copiarLink: "Copia il link del messaggio",
    copiarId: "Copia l'ID del messaggio",
    fixar: "Fissa il messaggio",
    desafixar: "Rimuovi dai fissati",
    editar: "Modifica",
    apagar: "Elimina",
    mais: "Altro",
    adicionarReacao: "Aggiungi una reazione",
    superReagirCom: "Super reagisci con {{emoji}}",
    fixarMensagem: "Fissa il messaggio",
    desafixarMensagem: "Rimuovi il messaggio dai fissati",
    editarMensagem: "Modifica il messaggio",
    apagarMensagem: "Elimina il messaggio",
  },
  mencao: {
    cargo: "Menzione di ruolo",
    pessoa: "Menzione",
    alguem: "qualcuno",
    cargoSemNome: "ruolo",
    here: "Avvisa chi è online",
    everyone: "Avvisa tutto il server",
  },
  codigo: {
    copiar: "Copia",
    copiado: "Copiato",
    copiarAria: "Copia il codice",
    copiadoAria: "Codice copiato",
    recolher: "Comprimi",
    expandir: "Espandi",
    verInteiro: "Vedi tutto il file",
    maisOpcoes: "Altre opzioni",
    baixar: "Scarica",
    recolherLinhas: "Comprimi ({{linhas}} righe)",
    expandirLinhas: "Espandi ({{linhas}} righe)",
    mudarIdioma: "Cambia linguaggio",
    procurarIdioma: "Cerca codice linguaggio…",
    nenhumIdioma: "Nessun linguaggio.",
    quebrarTexto: "A capo automatico",
  },
  caixa: {
    escrever: "Scrivi in #{{canal}}",
    escreverSemCanal: "Scrivi un messaggio",
    semPermissao: "Non hai il permesso di inviare messaggi in questo canale",
    solteParaAnexar: "Rilascia per allegare",
    longaTitulo: "Il messaggio è troppo lungo…",
    longaDescricao: "Hai raggiunto il limite di {{limite}} caratteri. Puoi inviarlo come file.",
    enviarComoArquivo: "Invia come file",
    arquivoGrandeTitulo: "Il file è troppo grande",
    arquivoGrandeDescricao: "«{{arquivo}}» supera il limite di {{limite}} MB per file.",
    respondendoPara: "In risposta a",
    vaiNotificar: "La persona verrà avvisata",
    naoVaiNotificar: "La persona non verrà avvisata",
    ligado: "attivo",
    desligado: "disattivo",
    pararDeResponder: "Smetti di rispondere",
    mais: "Altro",
    enviarArquivo: "Invia un file",
    criarEnquete: "Crea un sondaggio",
    expressoes: "Emoji, GIF e adesivi",
    enviar: "Invia",
    aguardandoEnvio: "In attesa del caricamento",
    modoLento: "Modalità lenta attiva ({{tempo}})",
    modoLentoDica: "La modalità lenta è impostata su {{segundos}} s. Aspetta prima di inviare un altro messaggio.",
  },
  anexos: {
    enviando: "Caricamento…",
    modificar: "Modifica {{arquivo}}",
    remover: "Rimuovi {{arquivo}}",
    ver: "Vedi {{arquivo}}",
    mostrarSpoiler: "Mostra lo spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Modifica l'allegato",
    nomeDoArquivo: "Nome del file",
    descricao: "Descrizione del testo alternativo",
    descricaoDica: "Descrivi questo contenuto per i lettori di schermo",
    marcarSpoiler: "Segna come spoiler",
    cancelar: "Annulla",
    salvar: "Salva",
  },
  cartao: {
    tocador: "Riproduttore",
    abrir: "Apri {{destino}}",
    tocar: "Riproduci {{titulo}}",
    video: "video",
    verImagem: "Vedi l'immagine",
  },
  enquete: {
    titulo: "Sondaggio",
    encerrada: "Sondaggio chiuso",
    variasRespostas: "Sondaggio — più risposte",
    umVoto: "{{quantidade}} voto",
    votos: "{{quantidade}} voti",
    umVotoNoTotal: "{{quantidade}} voto in totale",
    votosNoTotal: "{{quantidade}} voti in totale",
    encerraEm: "si chiude il {{quando}}",
    encerrarAgora: "Chiudi adesso",
  },
  fixadas: {
    titulo: "Messaggi fissati",
    vazio: "Questo canale non ha messaggi fissati… per ora.",
    desafixar: "Rimuovi dai fissati",
    anexo: "(allegato)",
    enquete: "(sondaggio)",
    dicaRotulo: "UN CONSIGLIO:",
    dica: "chi ha il permesso «Gestire i messaggi» può fissare direttamente dal menu del messaggio.",
  },
  encaminhar: {
    titulo: "Inoltra il messaggio",
    paraOnde: "Dove?",
    semTexto: "(messaggio senza testo)",
    nenhumLugar: "Nessun posto con questo nome.",
    canais: "Canali",
    conversas: "Messaggi diretti",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Cerca su Klipy",
    figurinha: "Sticker",
    buscarFigurinha: "Trova lo sticker perfetto",
    buscarEmoji: "Trova l'emoji perfetta",
    buscarReacao: "Trova la reazione perfetta",
    adicionarEmoji: "Aggiungi emoji",
    limparBusca: "Pulisci la ricerca",
  },
  busca: {
    fechar: "Chiudi la ricerca",
    procurando: "Sto cercando…",
    resultado: "{{quantos}} risultato",
    resultados: "{{quantos}} risultati",
    nadaCom: "Niente con {{termo}} da queste parti.",
    soOsQuePodeLer: "La ricerca guarda solo i canali che puoi leggere.",
  },
  entrada: {
    titulo: "Posta in arrivo",
    naoLidas: "Non lette",
    salvas: "Salvate",
    mencoes: "Menzioni",
    fimTitulo: "Sei arrivato in fondo",
    fimDetalhe: "Non c'è più niente da leggere. Quando arriva un messaggio nuovo, compare qui.",
    semSalvosTitulo: "Nessun elemento salvato",
    semSalvosDetalhe: "Tieni premuto Shift e clicca il segnalibro di un messaggio per tenerlo e leggerlo dopo.",
    tirarDosSalvos: "Togli dai salvati",
    semMencoesTitulo: "Ancora nessuna menzione",
    semMencoesDetalhe: "Le menzioni a te compaiono qui per gli ultimi 7 giorni.",
  },
  forum: {
    descricao: "Ogni argomento diventa una conversazione a parte — comodo per il dubbio che non deve perdersi in mezzo alla chiacchierata.",
    novoAssunto: "Nuovo argomento",
    vazio: "Ancora nessun argomento. Comincia il primo e la conversazione resta ordinata fin dall'inizio.",
    titulo: "Titolo",
    doQueSeTrata: "Di cosa si tratta?",
    primeiraMensagem: "Primo messaggio",
    conteDoCaso: "Racconta",
  },
};
