export const perfil = {
  carregando: "Caricamento…",
  editar: "Modifica profilo",
  mensagem: "Messaggio",
  abrirConversa: "Apri la conversazione",
  verCompleto: "Vedi il profilo completo",
  convidarParaServidor: "Invita nel server",
  semServidores: "Non hai server",
  conviteEnviado: "Invito inviato a {{nome}}.",
  moderador: "Apri nella vista moderatore",
  mais: "Altro",
  ignorar: "Ignora",
  deixarDeIgnorar: "Smetti di ignorare",
  copiarId: "Copia l'ID dell'utente",
  idCopiado: "ID copiato.",
  conexoes: "Connessioni",
  membroDesde: "Membro dal",
  sobre: "Informazioni",
  cargosTitulo: "Ruoli",
  visaoGeral: "Panoramica",
  amigosEmComum: "Amici in comune ({{quantidade}})",
  servidoresEmComum: "Server in comune ({{quantidade}})",
  amizade: {
    amigo: "Amico",
    pedidoEnviado: "Richiesta di amicizia inviata",
    respondaAbaixo: "Ti ha mandato una richiesta — rispondi qui sotto",
    adicionar: "Aggiungi agli amici",
    teMandouPedido: "Ti ha mandato una richiesta di amicizia",
    aceitar: "Accetta",
    desfazer: "Rimuovi dagli amici",
    desfazerTitulo: "Rimuovere {{nome}} dai tuoi amici?",
    desfazerDescricao: "Non sarete più amici. La conversazione privata resta nella cronologia, e potrai aggiungerlo di nuovo più avanti.",
    bloquear: "Blocca",
    bloquearTitulo: "Bloccare {{nome}}?",
    bloquearDescricao: "Non sarete più amici, la conversazione privata smette di accettare messaggi e questa persona non potrà più mandarti richieste di amicizia.",
    linkCopiado: "Non siete amici — il link è stato copiato perché tu glielo mandi.",
  },
  recado: {
    escrever: "Scrivi a @{{usuario}}",
    enviar: "Invia",
    enviada: "Messaggio inviato",
    falhou: "Non è stato possibile inviarlo. Prova dalla conversazione.",
  },
  cartao: {
    trocarFaixa: "Cambia il banner della scheda",
    trocarFaixaCurto: "Cambia il banner",
    trocarFoto: "Cambia la foto del profilo",
    trocarFotoCurto: "Cambia la foto",
    suaEtiqueta: "La tua etichetta",
    editarEtiqueta: "Clicca per modificare la tua etichetta",
    conteAlgo: "Raccontaci qualcosa di te",
    adicionarStatus: "Aggiungi uno stato",
    adicionarDescricao: "Clicca per aggiungere una descrizione",
    cargo: "Ruolo",
    cargos: "Ruoli",
    cargosCom: "Ruoli — {{quantidade}}",
    tirarCargo: "Togli il ruolo {{cargo}}",
  },
  cargos: {
    adicionar: "Aggiungi ruolo",
    procurar: "Cerca un ruolo",
  },
  etiqueta: {
    escolher: "Scegli l'etichetta del server",
    nenhuma: "Nessuna etichetta del server",
    semEtiqueta: "Nessuno dei tuoi server ha un'etichetta",
  },
  emblemas: {
    doServidor: "Distintivi di questo server",
    limite: "Puoi indossare fino a {{quantidade}} distintivi.",
  },
  nota: {
    vazia: "Clicca per annotare qualcosa",
    rotulo: "Nota (la vedi solo tu)",
  },
  status: {
    titulo: "Stato",
    definir: "Imposta il tuo stato",
    escolherEmoji: "Scegli emoji",
    tirarEmoji: "Togli l'emoji",
    oQuePensa: "A cosa stai pensando?",
    limparAgora: "Cancella lo stato adesso",
    naoLimpar: "Non cancellare",
    limpar30m: "Cancella tra 30 minuti",
    limpar1h: "Cancella tra 1 ora",
    limpar4h: "Cancella tra 4 ore",
    limparHoje: "Cancella oggi",
    limparAmanha: "Cancella domani",
    comHora: "{{prazo}} alle {{hora}}",
  },
  presenca: {
    disponivel: "Disponibile",
    ausente: "Assente",
    naoPerturbar: "Non disturbare",
    naoPerturbarDetalhe: "Non ricevi avvisi per i messaggi nuovi",
    invisivel: "Invisibile",
    invisivelDetalhe: "Appari offline agli altri",
  },
  menu: {
    mudarDeConta: "Cambia account",
    gerenciarContas: "Gestisci gli account",
  },
  editor: {
    decoracao: "Cambia la decorazione dell'avatar",
    naoSalvo: "Non dimenticare di salvare le modifiche!",
    principal: "Profilo principale",
  },
};
