export const servidor = {
  titulo: "Impostazioni del server",
  auditoria: {
    titulo: "Registro delle azioni",
    porUsuario: "Filtra per utente",
    porAcao: "Filtra per azione",
    vazio: "Ancora nulla registrato con questo filtro.",
    motivo: "Motivo:",
  },
  banimentos: {
    titulo: "Elenco dei banditi del server",
    descricao: "Chi è qui non rientra nemmeno con un invito nuovo. Togliere il ban restituisce l'accesso all'istante.",
    procurar: "Cerca ban per nome utente",
    vazioTitulo: "Nessun ban",
    vazio: "Non hai ancora bandito nessuno… ma se e quando servirà, non esitare.",
    desbanir: "Togli il ban",
  },
  excluir: {
    tudoVai: "Tutti i canali, i messaggi e gli inviti di {{servidor}} saranno cancellati per i {{membros}} membri. Nessuno potrà recuperarli dopo.",
    digite: "Scrivi {{servidor}} per confermare",
    titulo: "Elimina il server",
    aviso: "Non si può tornare indietro.",
  },
  emblemas: {
    titulo: "Distintivi",
    vazio: "Ancora nessun distintivo.",
    novo: "Nuovo distintivo",
  },
  convites: {
    titulo: "Inviti",
    descricao: "Tutti i link d'invito attivi di questo server.",
    vazio: "Ancora nessun invito creato.",
    revogar: "Revoca l'invito",
  },
  integracoes: {
    titulo: "Integrazioni",
    descricao: "Un webhook è un indirizzo che pubblica in un canale senza bisogno di un account. Serve per avvisare quando una build passa, quando qualcuno apre un ticket, o qualunque cosa tu voglia mandare da uno script.",
    novo: "Nuovo webhook",
    vazio: "Ancora nessun webhook. Creane uno e incolla l'URL dove vuoi che arrivi il messaggio.",
    canal: "Canale",
    apagar: "Elimina il webhook",
    comoUsar: "Come si usa",
    comoUsarTexto: "Manda un POST con JSON. Il formato è lo stesso di Discord, quindi uno script che esiste già funziona senza modifiche:",
  },
  engajamento: {
    titulo: "Coinvolgimento",
    descricao: "Quello che il server fa da solo per non sembrare vuoto quando arriva gente nuova.",
    sistema: "Messaggi di sistema",
    boasVindas: "Manda un messaggio di benvenuto quando qualcuno entra",
    sorteio: "Senza un testo tuo qui sotto la frase viene sorteggiata — sempre la stessa stanca in fretta.",
    canalDoSistema: "Canale dei messaggi di sistema",
    mensagem: "Messaggio di benvenuto",
    deixeVazio: "Lascia vuoto per sorteggiare tra le frasi già pronte",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtri che moderano da soli, prima ancora che il messaggio esista. Chi amministra il server non viene mai filtrato — e i ruoli esenti passano dritti.",
    palavras: {
      titulo: "Blocca parole personalizzate",
      descricao: "La tua lista di parole che nessuno può scrivere.",
    },
    mencoes: {
      titulo: "Blocca lo spam di menzioni",
      descricao: "Blocca un messaggio con troppe menzioni in una volta.",
    },
    links: {
      titulo: "Blocca i link",
      descricao: "Trattiene qualsiasi indirizzo incollato in chat.",
    },
    definir: "Configura",
    nomeDaRegra: "Nome della regola",
    bloqueadas: "Parole bloccate",
    digiteEnter: "Scrivi e premi Invio",
    comparacao: "Il confronto ignora maiuscole, accenti e punteggiatura — e non prende una parola dentro un'altra (\"burro\" non blocca \"burrocrazia\").",
    aPartirDe: "Blocca a partire da quante menzioni",
    oQueFazer: "Cosa fare",
    canalDoAlerta: "Canale dell'avviso",
    escolhaCanal: "Scegli un canale",
    castigo: "Silenziamento (minuti)",
    isentos: "Ruoli esenti",
    semCargos: "Nessun ruolo creato finora.",
    salvarRegra: "Salva regola",
    apagar: "Elimina regola",
    excluirTitulo: "Eliminare questa regola di AutoMod?",
    excluirDescricao: "Il server smette di filtrare con essa all'istante. Puoi ricrearla, ma la configurazione attuale va persa.",
    excluirAcao: "Elimina regola",
  },
  cargos: {
    titulo: "Ruoli",
    descricao: "I ruoli danno nome, colore e poteri. Chi sta più in alto nella lista comanda su chi sta sotto — e nessuno tocca un ruolo pari o superiore al proprio.",
    criar: "Crea ruolo",
    vazio: "Ancora nessun ruolo.",
    abaExibicao: "Aspetto",
    abaPermissoes: "Permessi",
    abaMembros: "Membri — {{quantos}}",
    everyone: "Vale per tutti nel server. È la base su cui gli altri ruoli si sommano.",
    nomeDoCargo: "Nome del ruolo",
    cor: "Colore del ruolo",
    corDica: "Colora il nome di chi ha il ruolo nella lista dei membri e in chat.",
    semCor: "Senza colore",
    corPersonalizada: "Colore personalizzato",
    estilo: "Stile del nome",
    segundaCor: "Secondo colore",
    segundaCorDica: "Senza di esso la sfumatura torna a un colore pieno — non sparisce.",
    limparSegundaCor: "Togli il secondo colore",
    icone: "Icona",
    iconeDica: "Appare accanto al ruolo nella scheda profilo di chi ce l'ha.",
    exibirSeparado: "Mostra separato dagli altri membri",
    exibirSeparadoDica: "Il ruolo ottiene una sezione propria nella lista dei membri.",
    permitirMencionar: "Permetti di menzionare questo ruolo",
    permitirMencionarDica: "Chiunque potrà notificare tutti quelli che hanno il ruolo.",
    semPoderDeConceder: "{{descricao}} (non hai questo permesso per concederlo)",
    adicionar: "Aggiungi qualcuno a questo ruolo",
    tirar: "Togli il ruolo",
    semNinguem: "Ancora nessuno ha questo ruolo.",
    apagar: "Elimina ruolo",
    excluirTitulo: "Eliminare il ruolo \"{{nome}}\"?",
    excluirDescricao: "Chi ha questo ruolo perde tutto ciò che dava. Non si può tornare indietro.",
    excluirAcao: "Elimina ruolo",
  },
  membros: {
    procurar: "Cerca per nome o nome utente",
    membroDesde: "Membro dal",
    vazio: "Nessuno trovato.",
    acoesPara: "Azioni per {{nome}}",
    deCastigo: "di silenziamento",
    tirarCastigo: "Togli il silenziamento",
    castigo5min: "5 minuti",
    castigo1h: "1 ora",
    castigo1d: "1 giorno",
    castigo1s: "1 settimana",
    expulsar: "Espelli",
    expulsarTitulo: "Espellere {{nome}}?",
    expulsarDescricao: "esce da {{servidor}} all'istante. Può rientrare con un invito — espellere non impedisce il ritorno.",
    banir: "Banna",
    banirTitulo: "Bannare {{nome}}?",
    banirDescricao: "esce da {{servidor}} e non può tornare, nemmeno con un invito, finché non viene sbannato.",
    motivo: "Motivo (facoltativo)",
    motivoDica: "Resta registrato nel log",
  },
  perfil: {
    titulo: "Profilo del server",
    descricao: "È così che il tuo server appare nella lista e nei link d'invito.",
    icone: "Icona",
    faixa: "Banner in alto",
    nomeDoServidor: "Nome del server",
    campoDescricao: "Descrizione",
    doQueE: "Di cosa parla questo server?",
    comprimido: "Compresso prima del caricamento: {{economia}}",
  },
  etiqueta: {
    titulo: "Tag del server",
    descricao: "Un'etichetta di massimo 4 lettere che appare accanto al nome di chi è membro — in chat e nella lista delle persone. Qui è gratis: senza boost, senza livelli.",
    escolhaNome: "Scegli un nome",
    limite: "Massimo 4 caratteri, lettere e numeri.",
    escolhaInsignia: "Scegli un distintivo",
    voce: "Tu",
    fala1: "qualcuno per giocare?",
    fala2: "dai un'occhiata al mio tag!",
    fala3: "caspita, come l'hai preso",
  },
  expressoes: {
    comoUsar: "Aggiungi fino a {{limite}} emoji che tutti possono usare in questo server. Scrivi :nome: in chat per mandarlo.",
    imagem: "Immagine",
    enviadoPor: "Caricato da",
    semEmoji: "Ancora nessun emoji.",
    figurinhas: "Sticker",
    enviarFigurinha: "Carica sticker",
    nomeDaFigurinha: "Nome dello sticker",
    exemploFigurinha: "Es.: abbraccio di gattino",
    figurinhaGrande: "Lo sticker supera {{limite}}.",
    deixaPraLa: "Lascia stare",
    sons: "Pannello dei suoni",
    enviarSom: "Carica suono",
    nomeDoSom: "Nome del suono",
    semSom: "Ancora nessun suono.",
    somGrande: "Il suono supera {{limite}}.",
    emojiRelacionado: "Emoji collegato",
    ouvir: "Ascolta",
    ouvirAssim: "Ascolta così",
    volumeDe: "Volume di {{nome}}",
    volumeDica: "Vale per tutti nel server. Ogni persona può comunque abbassare i suoni solo per sé, nel pannello della chiamata.",
    falhaEnvio: "Non è stato possibile caricare il file.",
    excluirTitulo: "Eliminare {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Sparisce dal server per tutti. I messaggi che l'hanno già usato restano come sono.",
  },
  canal: {
    visaoGeral: "Panoramica",
    nome: "Nome del canale",
    topico: "Argomento del canale",
    topicoDica: "Di cosa si parla qui?",
    modoLento: "Ogni persona manda un solo messaggio per intervallo. Chi gestisce messaggi o canali passa dritto.",
    visibilidade: "Visibilità del contenuto",
    padrao: "Predefinito",
    padraoDica: "Il contenuto del canale è sempre visibile.",
    spoiler: "Canale con spoiler",
    spoilerDica: "Segna questo canale come contenente spoiler, così i colpi di scena e i temi pesanti restano nascosti finché qualcuno non sceglie di vederli.",
    idade: "Canale con limite d'età",
    idadeDica: "Chi entra deve confermare di essere maggiorenne per vedere il contenuto.",
    bitrateDica: "Superare i 64 kbps può dare fastidio a chi ha una connessione scarsa.",
    qualidadeDeVideo: "Qualità del video",
    automatica: "Automatica",
    limite: "Limite di utenti — {{valor}}",
    pessoas: "{{quantos}} persone",
    semLimite: "senza limite",
    permissoesDescricao: "Qui cambi ciò che vale in questo canale. Quello che resta su “eredita” continua a seguire il ruolo.",
    excluir: {
      titulo: "Elimina canale",
      historico: "Tutta la cronologia di {{canal}} se ne va con lui, per tutti.",
      digite: "Scrivi {{canal}} per confermare",
    },
  },
  moderacao: {
    titulo: "Vista da moderatore",
    semPermissao: "Ti serve il permesso “Moderare i membri” per vedere questo.",
    fecharEsc: "Chiudi (Esc)",
    atividade: "Attività nel server",
    mensagens: "Messaggi",
    links: "Link",
    midia: "Media",
    acoesNaAuditoria: "Azioni nel registro",
    moderacoesSofridas: "Moderazioni subite",
    permissoes: "Permessi ({{quantas}})",
    semPermissaoEspecial: "Nessun permesso speciale.",
    conta: "Account",
    entrouNoServidor: "Entrato nel server",
    contaCriadaEm: "Account creato il",
    deCastigoAte: "Silenziato fino al",
    formaDeAdesao: "Come è entrato",
    mensagem: "Messaggio",
    castigo: "Silenziamento",
    copiarId: "Copia ID",
    idCopiado: "ID copiato.",
    adicionarCargo: "Aggiungi ruolo",
    semCargos: "Nessun ruolo creato",
    soEveryone: "Solo @everyone.",
    voltar: "Indietro",
    vazio: "Qui non c'è nulla.",
    cinquenta: "Mostro i 50 più recenti.",
    irParaMensagem: "Vai al messaggio",
    precisaSerAmigo: "Dovete essere amici per parlare.",
    expulsarDescricao: "Esce dal server all'istante, ma può tornare con un invito.",
    banirDescricao: "Esce dal server e non può tornare, nemmeno con un invito, finché non viene sbannato.",
    castigarTitulo: "Silenziare {{nome}}?",
    castigoDescricao: "Finché dura, non scrive né parla in nessun canale del server.",
    aplicarCastigo: "Applica il silenziamento",
    duracao: "Durata in minuti",
    informeDuracao: "Indica la durata in minuti.",
  },
};
