export const amizades = {
  ativosAgora: "Aktywni teraz",
  procurando: "Sprawdzamy, kto jest w pobliżu…",
  tudoTranquilo: "Na razie jest cicho…",
  tudoTranquiloDetalhe: "Gdy ty albo znajomy dołączycie do rozmowy, pojawi się tutaj — i dołączysz jednym kliknięciem.",
  emVoz: "Na głosowym",
  voce: "Ty",
  soVoce: "Tylko ty",
  pessoas: "{{quantas}} osób",
  voltarParaChamada: "Wróć do rozmowy",
  entrarNaChamada: "Dołącz do rozmowy",
  abrirCanal: "Otwórz {{canal}} na {{servidor}}",
  mensagensDiretas: "Wiadomości prywatne",
  encontreConversa: "Znajdź rozmowę",
  amigos: "Znajomi",
  conversas: "Rozmowy",
  semConversas: "Jeszcze żadnych rozmów. Dodaj znajomego, żeby zacząć.",
  semConversaComEsseNome: "Brak rozmowy o tej nazwie.",
  abrirMenu: "Otwórz serwery i rozmowy",
  solicitacoes: "Prośby o wiadomość",
  pedidos: "Prośby",
  spam: "Spam",
  pedidosPendentes: "Oczekujące prośby",
  marcadosComoSpam: "Oznaczone jako spam",
  aceitar: "Akceptuj",
  ignorar: "Ignoruj",
  marcarSpam: "Oznacz jako spam",
  semPedidos: "Brak oczekujących próśb.",
  semPedidosDetalhe: "Kto nie jest twoim znajomym, ale dzieli z tobą serwer, trafia tutaj, zanim dotrze do twoich rozmów.",
  semSpam: "Nic nie oznaczono jako spam.",
  semSpamDetalhe: "To, co odsieje filtr spamu, albo to, co sam oznaczysz, zostaje w tej zakładce.",
  umServidorEmComum: "1 wspólny serwer",
  servidoresEmComum: "Wspólne serwery: {{quantos}}",
  semServidoresEmComum: "Brak wspólnych serwerów",
};
