export const chamada = {
  conectando: "Łączenie z rozmową…",
  naoEntrou: "Nie udało się dołączyć do rozmowy",
  sair: "Opuść rozmowę",
  sairDaVoz: "Opuść rozmowę głosową",
  desconectar: "Rozłącz",
  voltar: "Wróć do rozmowy",
  voltarAosQuadros: "Wróć do kafelków rozmowy",
  fecharChat: "Zamknij czat",
  carregandoPrevia: "Wczytywanie podglądu…",
  maisOpcoes: "Więcej opcji",
  deVideo: "Rozmowa wideo",
  deVoz: "Rozmowa głosowa",
  alguem: "Ktoś",
  volume: {
    entrada: "Głośność wejścia",
    saida: "Głośność wyjścia",
    live: "Głośność transmisji",
    liveComPorcento: "Głośność transmisji ({{porcento}}%)",
    liveSemSom: "Transmisja bez dźwięku",
  },
  aparelhos: {
    entrada: "Urządzenie wejściowe",
    saida: "Urządzenie wyjściowe",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Wyjście",
    oDoSistema: "Systemowe",
    aDoSistema: "Systemowa",
    semEscolhaDeSaida: "Ta przeglądarka nie pozwala wybrać wyjścia — decyduje system.",
    espelhar: "Odbij moją kamerę",
    configEntrada: "Ustawienia wejścia",
    configSaida: "Ustawienia wyjścia",
    configCamera: "Ustawienia kamery",
    configAudioEVideo: "Ustawienia dźwięku i obrazu",
  },
  tela: {
    compartilhar: "Udostępnij ekran",
    compartilharAcao: "Udostępnij",
    cancelar: "Anuluj",
    telas: "Ekrany",
    janelas: "Okna",
    somDoComputador: "Zabierz dźwięk komputera",
    somDoSistema: "Zabierz dźwięk systemu",
    configCompartilhamento: "Ustawienia udostępniania",
    mostrarSemVideo: "Pokazuj osoby bez obrazu",
    semFontes: "System nie zwrócił żadnego ekranu ani okna do udostępnienia.",
    pararDeCompartilhar: "Przestań udostępniać",
    encerrarTransmissao: "Zakończ transmisję",
  },
  live: {
    etiqueta: "Na żywo",
    etiquetaMaiuscula: "NA ŻYWO",
    assistir: "Oglądaj transmisję",
    assistirPessoa: "Oglądaj {{nome}}",
    pararDeAssistir: "Przestań oglądać",
  },
  membro: {
    mudarMeuApelido: "Zmień mój pseudonim",
    meuMicrofone: "Mój mikrofon",
    ouvirChamada: "Słuchaj rozmowy",
    copiarMeuId: "Kopiuj moje ID",
    idCopiado: "Skopiowano ID.",
    mensagem: "Wiadomość",
    silenciar: "Wycisz",
    alterarApelido: "Zmień pseudonim",
    cargos: "Role",
    semCargo: "Nie utworzono żadnej roli",
    moverPara: "Przenieś do",
    silenciarNoServidor: "Wycisz głos na serwerze",
    desativarAudioNoServidor: "Wyłącz dźwięk na serwerze",
    desconectar: "Rozłącz",
    apelidoTitulo: "Twój pseudonim na tym serwerze",
    apelidoDeAlguem: "Pseudonim: {{nome}}",
    apelidoCampo: "Pseudonim",
    apelidoDicaPropria: "Obowiązuje tylko tutaj. Puste pole przywraca Twoje zwykłe imię.",
    apelidoDicaDeOutro: "Obowiązuje tylko na tym serwerze. Zostaw puste, żeby wrócić do pierwotnej nazwy.",
  },
  detalhes: {
    abrir: "Szczegóły głosu",
    titulo: "Szczegóły Głosu",
    conexao: "Połączenie",
    pingMedio: "Średni ping",
    ultimoPing: "Ostatni ping",
    perda: "Utrata wysłanych pakietów",
    medindo: "Mierzenie…",
    criptografado: "Szyfrowane do serwera (DTLS-SRTP)",
    explicacao: "Powyżej 250 ms opóźnienie słychać w rozmowie — ludzie zaczynają sobie przerywać. Utrata pakietów powyżej 10% sprawia, że głos brzmi robotycznie. W obu przypadkach problem prawie zawsze jest między Tobą a internetem: spróbuj kabla zamiast Wi-Fi albo zrestartuj router.",
  },
  microfone: {
    bloqueado: "Mikrofon zablokowany — tylko słuchasz. Zezwól na dostęp w uprawnieniach przeglądarki.",
    bloqueadoNoMac: "macOS blokuje mikrofon. Zaznacz",
    caminhoNoMac: "Ustawienia systemowe → Prywatność i ochrona → Mikrofon",
    abrirAjustes: "Otwórz ustawienia",
    vaiReabrir: "macOS poprosi o ponowne otwarcie aplikacji.",
    naoAbriu: "Nie udało się otworzyć mikrofonu — tylko słuchasz. Sprawdź urządzenie w Ustawienia → Głos i obraz.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS jeszcze nie zezwolił na nagrywanie ekranu. Bez tego udostępnianie wychodzi czarne.",
    marque: "Zaznacz",
    reabra: "w Nagrywanie ekranu i otwórz aplikację ponownie.",
  },
  ruido: {
    titulo: "Redukcja szumów",
    explicacao: "Usuń szum tła ze swojego głosu. Spróbuj klasnąć albo przesunąć klawiaturę podczas mówienia — osoby w rozmowie słyszą tylko Ciebie.",
    semSuporte: "Ta przeglądarka nie uruchamia zaawansowanej redukcji. Nadal działa ta wbudowana w przeglądarkę, tylko słabsza.",
    aplicando: "Stosowanie w rozmowie…",
    faleParaTestar: "Mów, żeby przetestować",
    verdeQuandoPassa: "Zielony, gdy Twój głos przechodzi.",
    teOuvindo: "Właśnie Cię słyszą.",
    feitoCom: "Zrobione z",
    aquiNoAparelho: ", tutaj na Twoim urządzeniu",
    ajustes: "Ustawienia",
  },
  permissoes: {
    titulo: "Uprawnienia macOS",
    detalhe: "macOS pyta tylko raz, a potem zmienia się to wyłącznie w jego panelu. Tutaj widać, co obowiązuje, i można naprawić to, czego brakuje.",
    concedida: "Przyznane",
    negada: "Odmówione",
    naoPedida: "Nie zażądano",
    permitir: "Zezwól",
    abrirAjustes: "Otwórz ustawienia",
    microfone: "Mikrofon",
    microfoneDetalhe: "Mówienie w rozmowach i testowanie wejścia.",
    camera: "Kamera",
    cameraDetalhe: "Włączanie obrazu w rozmowie.",
    tela: "Nagrywanie ekranu",
    telaDetalhe: "Udostępnianie ekranu i okien.",
    monitoramento: "Monitorowanie wejścia",
    monitoramentoDetalhe: "Używanie push-to-talk nawet z Gravaê w tle.",
  },
  jaConectado: {
    titulo: "Jesteś już w tej rozmowie",
    trazer: "Przenieś rozmowę tutaj",
    deixar: "Zostaw jak jest",
    detalhe: "Po przeniesieniu tutaj druga strona wypada z rozmowy — Twoje konto jest w jednym miejscu naraz.",
  },
};
