export const comum = {
  carregando: "Wczytywanie…",
  salvar: "Zapisz",
  salvando: "Zapisywanie…",
  descartar: "Odrzuć",
  redefinir: "Przywróć",
  naoSalvo: "Masz niezapisane zmiany.",
  fechar: "Zamknij",
  criar: "Utwórz",
  nome: "Nazwa",
  emoji: "Emoji",
  previa: "Podgląd",
  cancelar: "Anuluj",
  enviar: "Wyślij",
  apagar: "Usuń",
  excluir: "Usuń",
  remover: "Usuń",
  trocar: "Zmień",
};
