export const configuracoes = {
  sair: "Wyloguj się",
  versoes: {
    copiar: "Kliknij, aby skopiować",
    copiado: "Skopiowano",
  },
  telas: {
    conta: "Moje konto",
    privacidade: "Prywatność",
    conexoes: "Połączenia",
    voz: "Dźwięk",
    video: "Wideo",
    avisos: "Powiadomienia",
    aplicativos: "Aplikacje",
    aparencia: "Wygląd",
    batePapo: "Czat",
    acessibilidade: "Dostępność",
    idioma: "Język",
    aplicativo: "Pobierz aplikację",
    atalhos: "Skróty klawiszowe",
    avancado: "Zaawansowane",
    servidor: "Serwer",
  },
  grupos: {
    conta: "Konto",
    app: "Ustawienia aplikacji",
    desenvolvedor: "Deweloper",
    administracao: "Administracja",
  },
  secoes: {
    detalhesDeLogin: "Dane logowania",
    dispositivos: "Urządzenia",
    usuariosBloqueados: "Zablokowani użytkownicy",
    aplicativosAutorizados: "Autoryzowane aplikacje",
    sessoes: "Sesje",
    amigosEDms: "Znajomi i wiadomości prywatne",
    compartilhamentoDeAtividade: "Udostępnianie aktywności",
    visibilidadeDoPerfil: "Widoczność profilu",
    exportarDados: "Eksportuj dane",
    exclusaoDeDados: "Usuń dane",
    tema: "Motyw",
    corDeDestaque: "Kolor akcentu",
    interface: "Interfejs",
    listaDeCanais: "Lista kanałów",
    zoomDoApp: "Poziom powiększenia aplikacji",
    escalaDaFonte: "Rozmiar czcionki czatu",
    modoStreamer: "Prywatność podczas transmisji",
    movimento: "Ruch",
    textoEmVoz: "Zamiana tekstu na mowę",
    teclado: "Klawiatura",
    formatoDaHora: "Format godziny",
    idiomaDaInterface: "Język interfejsu",
    dispositivosDeVoz: "Urządzenia",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Tryb wejścia",
    sensibilidade: "Czułość wejścia",
    qualidade: "Jakość",
    camera: "Kamera",
    transmissao: "Transmisja",
    exibicao: "Wyświetlanie",
    entrada: "Wprowadzanie",
    midia: "Multimedia",
    geral: "Ogólne",
    preferenciaDeMencao: "Preferencje wzmianek",
    sons: "Dźwięki",
  },
};
