export const configuracoes = {
  efeitos: {
    titulo: "Efekty wskaźnika",
    detalhe: "Smuga i iskry rysowane na wierzchu aplikacji. Startują wyłączone i same gasną, jeśli poprosiłeś o mniej ruchu.",
    rastro: "Smuga kursora",
    rastroDetalhe: "Kreska, która idzie za wskaźnikiem i blednie z tyłu.",
    faisca: "Iskry przy kliknięciu",
    faiscaDetalhe: "Krótkie kreski wylatujące z miejsca kliknięcia.",
    cor: "Kolor",
    espessura: "Grubość",
    comprimento: "Długość",
    tamanho: "Rozmiar",
    quantidade: "Liczba",
  },
  email: {
    verificarTitulo: "Potwierdź swój e-mail",
    verificarDetalhe: "Część społeczności pozwala pisać tylko potwierdzonym. To jedno kliknięcie.",
    enviar: "Wyślij odnośnik",
    enviado: "Zajrzyj do skrzynki. Odnośnik działa przez dobę.",
    falhou: "Nie udało się wysłać wiadomości.",
    confirmado: "E-mail potwierdzony",
    confirmadoDetalhe: "Gotowe. Piszesz już w każdej społeczności, która tego wymaga.",
    linkIncompleto: "Niepełny odnośnik",
    linkIncompletoDetalhe: "W adresie brakuje kodu. Otwórz odnośnik prosto z wiadomości.",
    confirmando: "Potwierdzanie…",
    expirou: "Ten odnośnik został już użyty albo stracił ważność.",
    irParaOApp: "Przejdź do aplikacji",
  },
  tema: {
    indisponivel: "Motyw niedostępny",
    indisponivelDetalhe: "Ten, kto go opublikował, usunął go, albo odnośnik jest zły.",
    indisponivelLinha: "Motyw niedostępny. Ten, kto go opublikował, usunął go, albo odnośnik jest zły.",
    importar: "Zaimportuj motyw",
    importarCurto: "Zaimportuj",
    importarDetalhe: "To zastąpi motyw, który masz teraz. Potem możesz go zmienić w Ustawienia > Wygląd > Studio motywów.",
    porAutor: "autor: {{autor}}",
    umaCorTrocada: "1 zmieniony kolor",
    coresTrocadas: "zmienione kolory: {{quantas}}",
    avisoDeCss: "Ten motyw niesie CSS od swojego autora, a CSS sięga każdego zakątka ekranu. Importuj tylko od ludzi, którym ufasz.",
    soCores: "Ten motyw zmienia tylko kolory. Żadnego CSS z zewnątrz.",
    aplicar: "Zastosuj",
    previaSemMotor: "Podgląd nie uruchamia silnika. Zainstaluj, żeby go zobaczyć.",
    motorAnimado: "{{motor}} animowany",
  },
  sair: "Wyloguj się",
  versoes: {
    termos: "Warunki korzystania",
    privacidade: "Polityka prywatności",
    copiar: "Kliknij, aby skopiować",
    copiado: "Skopiowano",
  },
  telas: {
    conta: "Moje konto",
    privacidade: "Prywatność",
    conexoes: "Połączenia",
    voz: "Dźwięk",
    video: "Wideo",
    avisos: "Powiadomienia",
    aplicativos: "Aplikacje",
    aparencia: "Wygląd",
    batePapo: "Czat",
    acessibilidade: "Dostępność",
    idioma: "Język",
    aplicativo: "Pobierz aplikację",
    atalhos: "Skróty klawiszowe",
    desktop: "Aplikacja na komputer",
    avancado: "Zaawansowane",
    servidor: "Serwer",
    comunicado: "Komunikat systemowy",
    denuncias: "Zgłoszenia",
    publicacoes: "Wdrożenia",
  },
  grupos: {
    conta: "Konto",
    app: "Ustawienia aplikacji",
    desenvolvedor: "Deweloper",
    administracao: "Administracja",
  },
  secoes: {
    detalhesDeLogin: "Dane logowania",
    dispositivos: "Urządzenia",
    usuariosBloqueados: "Zablokowani użytkownicy",
    aplicativosAutorizados: "Autoryzowane aplikacje",
    sessoes: "Sesje",
    amigosEDms: "Znajomi i wiadomości prywatne",
    compartilhamentoDeAtividade: "Udostępnianie aktywności",
    visibilidadeDoPerfil: "Widoczność profilu",
    exportarDados: "Eksportuj dane",
    exclusaoDeDados: "Usuń dane",
    tema: "Motyw",
    corDeDestaque: "Kolor akcentu",
    interface: "Interfejs",
    listaDeCanais: "Lista kanałów",
    zoomDoApp: "Poziom powiększenia aplikacji",
    escalaDaFonte: "Rozmiar czcionki czatu",
    modoStreamer: "Prywatność podczas transmisji",
    cursores: "Kursory",
    movimento: "Ruch",
    textoEmVoz: "Zamiana tekstu na mowę",
    teclado: "Klawiatura",
    formatoDaHora: "Format godziny",
    idiomaDaInterface: "Język interfejsu",
    dispositivosDeVoz: "Urządzenia",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Tryb wejścia",
    sensibilidade: "Czułość wejścia",
    qualidade: "Jakość",
    camera: "Kamera",
    transmissao: "Transmisja",
    exibicao: "Wyświetlanie",
    entrada: "Wprowadzanie",
    midia: "Multimedia",
    geral: "Ogólne",
    preferenciaDeMencao: "Preferencje wzmianek",
    sons: "Dźwięki",
  },
};
