export const conversa = {
  lista: {
    carregando: "Wczytywanie wiadomości…",
    carregandoMais: "Wczytywanie…",
    verMais: "Przewiń w górę, aby zobaczyć więcej",
    semHistorico: "Historia niedostępna",
    semHistoricoDetalhe: "Twoja rola nie ma uprawnień do czytania historii kanału #{{canal}}. Nowe wiadomości nadal będą się pojawiać, dopóki tu jesteś.",
    boasVindas: "Witamy na #{{canal}}",
    boasVindasDetalhe: "To początek kanału #{{canal}}.",
  },
  data: {
    hoje: "Dzisiaj",
    ontem: "Wczoraj",
    hojeAs: "dzisiaj o {{hora}}",
    ontemAs: "wczoraj o {{hora}}",
  },
  digitando: {
    um: "{{nome}} pisze…",
    dois: "{{primeiro}} i {{segundo}} piszą…",
    varios: "{{quantidade}} osób pisze…",
  },
  mensagem: {
    usou: "użył(a)",
    fixada: "przypięta",
    editado: "(edytowano)",
    ignorada: "Wiadomość od osoby, którą ignorujesz.",
    mostrar: "Pokaż",
    escPara: "Esc, aby",
    cancelar: "anulować",
    enterParaSalvar: "Enter, aby zapisać",
    falhou: "Nie została wysłana. Spróbuj ponownie",
    naoLidasDaqui: "Nieprzeczytane od tego miejsca.",
    linkCopiado: "Skopiowano link.",
    idCopiado: "Skopiowano ID.",
    naoDeuParaCopiar: "Twoja przeglądarka nie pozwoliła skopiować.",
    apagarTitulo: "Usunąć wiadomość?",
    apagarDescricao: "Zniknie dla wszystkich na kanale. Nie da się jej odzyskać.",
    apagarAcao: "Usuń",
    citacaoAnexo: "kliknij, aby zobaczyć załącznik",
    citacaoSumiu: "Oryginalnej wiadomości już tu nie ma.",
    reagirCom: "Zareaguj emoji {{emoji}} — przytrzymaj, aby super zareagować",
    segureParaSuper: "{{emoji}} — przytrzymaj, aby super zareagować",
  },
  acoes: {
    reagir: "Zareaguj",
    responder: "Odpowiedz",
    encaminhar: "Przekaż dalej",
    favoritar: "Zapisz wiadomość",
    tirarDosFavoritos: "Usuń z zapisanych",
    marcarNaoLida: "Oznacz jako nieprzeczytaną",
    copiarLink: "Kopiuj link do wiadomości",
    copiarId: "Kopiuj ID wiadomości",
    fixar: "Przypnij wiadomość",
    desafixar: "Odepnij",
    editar: "Edytuj",
    apagar: "Usuń",
    mais: "Więcej",
    adicionarReacao: "Dodaj reakcję",
    superReagirCom: "Super reakcja z {{emoji}}",
    fixarMensagem: "Przypnij wiadomość",
    desafixarMensagem: "Odepnij wiadomość",
    editarMensagem: "Edytuj wiadomość",
    apagarMensagem: "Usuń wiadomość",
  },
  mencao: {
    cargo: "Wzmianka o roli",
    pessoa: "Wzmianka",
    alguem: "ktoś",
    cargoSemNome: "rola",
    here: "Powiadamia osoby, które są online",
    everyone: "Powiadamia cały serwer",
  },
  codigo: {
    copiar: "Kopiuj",
    copiado: "Skopiowano",
    copiarAria: "Kopiuj kod",
    copiadoAria: "Skopiowano kod",
    recolher: "Zwiń",
    expandir: "Rozwiń",
    verInteiro: "Zobacz cały plik",
    maisOpcoes: "Więcej opcji",
    baixar: "Pobierz",
    recolherLinhas: "Zwiń ({{linhas}} wierszy)",
    expandirLinhas: "Rozwiń ({{linhas}} wierszy)",
    mudarIdioma: "Zmień język",
    procurarIdioma: "Szukaj kodu języka…",
    nenhumIdioma: "Nie ma takiego języka.",
    quebrarTexto: "Zawijaj tekst",
  },
  caixa: {
    escrever: "Napisz na #{{canal}}",
    escreverSemCanal: "Napisz wiadomość",
    semPermissao: "Nie masz uprawnień do wysyłania wiadomości na tym kanale",
    solteParaAnexar: "Upuść, aby załączyć",
    longaTitulo: "Wiadomość jest za długa…",
    longaDescricao: "Osiągnąłeś limit {{limite}} znaków. Możesz wysłać ją jako plik.",
    enviarComoArquivo: "Wyślij jako plik",
    textoComoArquivo: "Wyślij tekst jako plik",
    arquivoGrandeTitulo: "Plik jest za duży",
    arquivoGrandeDescricao: "„{{arquivo}}” przekracza limit {{limite}} MB na plik.",
    respondendoPara: "Odpowiedź do",
    vaiNotificar: "Ta osoba dostanie powiadomienie",
    naoVaiNotificar: "Ta osoba nie dostanie powiadomienia",
    ligado: "włączone",
    desligado: "wyłączone",
    pararDeResponder: "Przestań odpowiadać",
    mais: "Więcej",
    enviarArquivo: "Wyślij plik",
    criarEnquete: "Utwórz ankietę",
    expressoes: "Emoji, GIF-y i naklejki",
    enviar: "Wyślij",
    aguardandoEnvio: "Czekam na przesłanie",
    modoLento: "Tryb powolny włączony ({{tempo}})",
    modoLentoDica: "Tryb powolny ustawiono na {{segundos}} s. Poczekaj przed wysłaniem kolejnej wiadomości.",
  },
  anexos: {
    enviando: "Przesyłanie…",
    modificar: "Zmień {{arquivo}}",
    remover: "Usuń {{arquivo}}",
    ver: "Zobacz {{arquivo}}",
    mostrarSpoiler: "Pokaż spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Edytuj załącznik",
    nomeDoArquivo: "Nazwa pliku",
    descricao: "Opis tekstu alternatywnego",
    descricaoDica: "Opisz ten materiał dla czytników ekranu",
    marcarSpoiler: "Oznacz jako spoiler",
    cancelar: "Anuluj",
    salvar: "Zapisz",
  },
  cartao: {
    tocador: "Odtwarzacz",
    abrir: "Otwórz {{destino}}",
    tocar: "Odtwórz {{titulo}}",
    video: "wideo",
    verImagem: "Zobacz obraz",
  },
  enquete: {
    titulo: "Ankieta",
    encerrada: "Ankieta zakończona",
    variasRespostas: "Ankieta — wiele odpowiedzi",
    umVoto: "{{quantidade}} głos",
    votos: "{{quantidade}} głosów",
    umVotoNoTotal: "{{quantidade}} głos łącznie",
    votosNoTotal: "{{quantidade}} głosów łącznie",
    encerraEm: "kończy się {{quando}}",
    encerrarAgora: "Zakończ teraz",
  },
  fixadas: {
    titulo: "Przypięte wiadomości",
    vazio: "Ten kanał nie ma przypiętych wiadomości… na razie.",
    desafixar: "Odepnij",
    anexo: "(załącznik)",
    enquete: "(ankieta)",
    dicaRotulo: "PODPOWIEDŹ:",
    dica: "kto ma uprawnienie „Zarządzanie wiadomościami”, może przypiąć prosto z menu wiadomości.",
  },
  encaminhar: {
    titulo: "Przekaż wiadomość",
    paraOnde: "Dokąd?",
    semTexto: "(wiadomość bez tekstu)",
    nenhumLugar: "Nie ma miejsca o tej nazwie.",
    canais: "Kanały",
    conversas: "Wiadomości prywatne",
  },
  expressoes: {
    gifs: "GIF-y",
    buscarGifs: "Szukaj w Klipy",
    figurinha: "Naklejka",
    buscarFigurinha: "Znajdź idealną naklejkę",
    buscarEmoji: "Znajdź idealne emoji",
    buscarReacao: "Znajdź idealną reakcję",
    adicionarEmoji: "Dodaj emoji",
    limparBusca: "Wyczyść wyszukiwanie",
  },
  busca: {
    fechar: "Zamknij wyszukiwanie",
    procurando: "Szukam…",
    resultado: "{{quantos}} wynik",
    resultados: "{{quantos}} wyników",
    nadaCom: "Nic z {{termo}} tutaj.",
    soOsQuePodeLer: "Wyszukiwanie zagląda tylko do kanałów, które możesz czytać.",
  },
  entrada: {
    titulo: "Skrzynka odbiorcza",
    naoLidas: "Nieprzeczytane",
    salvas: "Zapisane",
    mencoes: "Wzmianki",
    fimTitulo: "Dotarłeś do końca",
    fimDetalhe: "Nie ma już nic do przeczytania. Gdy przyjdzie nowa wiadomość, pojawi się tutaj.",
    semSalvosTitulo: "Nic nie zapisano",
    semSalvosDetalhe: "Przytrzymaj Shift i kliknij zakładkę wiadomości, żeby ją zachować i przeczytać później.",
    tirarDosSalvos: "Usuń z zapisanych",
    semMencoesTitulo: "Jeszcze żadnych wzmianek",
    semMencoesDetalhe: "Wzmianki o tobie pojawiają się tutaj przez ostatnie 7 dni.",
  },
  forum: {
    descricao: "Każdy temat staje się osobną rozmową — dobre na pytanie, które nie może zginąć w środku pogawędki.",
    novoAssunto: "Nowy temat",
    vazio: "Nie ma jeszcze tematów. Zacznij pierwszy, a rozmowa od początku zostanie uporządkowana.",
    titulo: "Tytuł",
    doQueSeTrata: "O co chodzi?",
    primeiraMensagem: "Pierwsza wiadomość",
    conteDoCaso: "Opowiedz",
  },
};
