export const perfil = {
  carregando: "Wczytywanie…",
  editar: "Edytuj profil",
  mensagem: "Wiadomość",
  abrirConversa: "Otwórz rozmowę",
  verCompleto: "Zobacz pełny profil",
  convidarParaServidor: "Zaproś na serwer",
  semServidores: "Nie masz serwerów",
  conviteEnviado: "Zaproszenie wysłane do {{nome}}.",
  moderador: "Otwórz w widoku moderatora",
  mais: "Więcej",
  ignorar: "Ignoruj",
  deixarDeIgnorar: "Przestań ignorować",
  copiarId: "Kopiuj ID użytkownika",
  idCopiado: "Skopiowano ID.",
  conexoes: "Połączenia",
  membroDesde: "Członek od",
  sobre: "O mnie",
  cargosTitulo: "Role",
  visaoGeral: "Przegląd",
  amigosEmComum: "Wspólni znajomi ({{quantidade}})",
  servidoresEmComum: "Wspólne serwery ({{quantidade}})",
  amizade: {
    amigo: "Znajomy",
    pedidoEnviado: "Zaproszenie do znajomych wysłane",
    respondaAbaixo: "Wysłał(a) Ci zaproszenie — odpowiedz poniżej",
    adicionar: "Dodaj do znajomych",
    teMandouPedido: "Wysłał(a) Ci zaproszenie do znajomych",
    aceitar: "Akceptuj",
    desfazer: "Usuń ze znajomych",
    desfazerTitulo: "Usunąć {{nome}} ze znajomych?",
    desfazerDescricao: "Przestajecie być znajomymi. Prywatna rozmowa zostaje w historii, a później możesz dodać tę osobę ponownie.",
    bloquear: "Zablokuj",
    bloquearTitulo: "Zablokować {{nome}}?",
    bloquearDescricao: "Przestajecie być znajomymi, prywatna rozmowa przestaje przyjmować wiadomości, a ta osoba nie może już wysłać Ci zaproszenia.",
    linkCopiado: "Nie jesteście znajomymi — link został skopiowany, żebyś mógł go wysłać.",
  },
  recado: {
    escrever: "Napisz do @{{usuario}}",
    enviar: "Wyślij",
    enviada: "Wiadomość wysłana",
    falhou: "Nie udało się wysłać. Spróbuj z poziomu rozmowy.",
  },
  cartao: {
    trocarFaixa: "Zmień baner karty",
    trocarFaixaCurto: "Zmień baner",
    trocarFoto: "Zmień zdjęcie profilowe",
    trocarFotoCurto: "Zmień zdjęcie",
    suaEtiqueta: "Twoja etykieta",
    editarEtiqueta: "Kliknij, aby edytować etykietę",
    conteAlgo: "Napisz coś o sobie",
    adicionarStatus: "Dodaj status",
    adicionarDescricao: "Kliknij, aby dodać opis",
    cargo: "Rola",
    cargos: "Role",
    cargosCom: "Role — {{quantidade}}",
    tirarCargo: "Usuń rolę {{cargo}}",
  },
  cargos: {
    adicionar: "Dodaj rolę",
    procurar: "Szukaj roli",
  },
  etiqueta: {
    escolher: "Wybierz etykietę serwera",
    nenhuma: "Brak etykiety serwera",
    semEtiqueta: "Żaden z Twoich serwerów nie ma etykiety",
  },
  emblemas: {
    doServidor: "Odznaki z tego serwera",
    limite: "Możesz nosić do {{quantidade}} odznak.",
  },
  nota: {
    vazia: "Kliknij, aby coś zanotować",
    rotulo: "Notatka (widzisz ją tylko Ty)",
    adicionar: "Dodaj notatkę (widzisz tylko ty)",
  },
  status: {
    titulo: "Status",
    definir: "Ustaw swój status",
    escolherEmoji: "Wybierz emoji",
    tirarEmoji: "Usuń emoji",
    oQuePensa: "O czym myślisz?",
    limparAgora: "Wyczyść status teraz",
    naoLimpar: "Nie czyść",
    limpar30m: "Wyczyść za 30 minut",
    limpar1h: "Wyczyść za 1 godzinę",
    limpar4h: "Wyczyść za 4 godziny",
    limparHoje: "Wyczyść dzisiaj",
    limparAmanha: "Wyczyść jutro",
    comHora: "{{prazo}} o {{hora}}",
  },
  presenca: {
    disponivel: "Dostępny",
    ausente: "Zaraz wracam",
    naoPerturbar: "Nie przeszkadzać",
    naoPerturbarDetalhe: "Nie dostajesz powiadomień o nowych wiadomościach",
    invisivel: "Niewidoczny",
    invisivelDetalhe: "Dla innych wyglądasz na offline",
  },
  menu: {
    mudarDeConta: "Zmień konto",
    gerenciarContas: "Zarządzaj kontami",
  },
  editor: {
    decoracao: "Zmień dekorację awatara",
    naoSalvo: "Nie zapomnij zapisać zmian!",
    principal: "Profil główny",
  },
};
