export const servidor = {
  titulo: "Ustawienia serwera",
  auditoria: {
    titulo: "Dziennik zdarzeń",
    porUsuario: "Filtruj po osobie",
    porAcao: "Filtruj po działaniu",
    vazio: "Nic jeszcze nie zapisano z tym filtrem.",
    motivo: "Powód:",
  },
  banimentos: {
    titulo: "Lista banów serwera",
    descricao: "Kto tu jest, nie wróci nawet z nowym zaproszeniem. Zdjęcie bana od razu przywraca dostęp.",
    procurar: "Szukaj banów po nazwie użytkownika",
    vazioTitulo: "Brak banów",
    vazio: "Nikogo jeszcze nie zbanowałeś… ale gdy zajdzie potrzeba, nie wahaj się.",
    desbanir: "Zdejmij bana",
  },
  excluir: {
    titulo: "Usuń serwer",
    aviso: "Tego nie da się cofnąć.",
  },
  emblemas: {
    titulo: "Odznaki",
    vazio: "Jeszcze nie ma odznak.",
    novo: "Nowa odznaka",
  },
  convites: {
    titulo: "Zaproszenia",
    descricao: "Wszystkie aktywne linki zapraszające tego serwera.",
    vazio: "Nie utworzono jeszcze żadnego zaproszenia.",
    revogar: "Unieważnij zaproszenie",
  },
  integracoes: {
    titulo: "Integracje",
    descricao: "Webhook to adres, który pisze na kanale bez potrzeby posiadania konta. Przydaje się, by ogłosić, że build przeszedł, że ktoś otworzył zgłoszenie, albo cokolwiek chcesz wysłać ze skryptu.",
    novo: "Nowy webhook",
    vazio: "Nie ma jeszcze webhooków. Utwórz jeden i wklej URL tam, skąd ma przychodzić wiadomość.",
    canal: "Kanał",
    apagar: "Usuń webhook",
    comoUsar: "Jak używać",
    comoUsarTexto: "Wyślij POST z JSON-em. Format jest taki sam jak w Discordzie, więc skrypt, który już gdzieś istnieje, zadziała bez zmian:",
  },
  engajamento: {
    titulo: "Zaangażowanie",
    descricao: "Co serwer robi sam, żeby nie wyglądał pusto, gdy przychodzi ktoś nowy.",
    sistema: "Wiadomości systemowe",
    boasVindas: "Wyślij powitanie, gdy ktoś dołączy",
    sorteio: "Bez własnego tekstu poniżej zdanie jest losowane — wciąż to samo szybko się nudzi.",
    canalDoSistema: "Kanał wiadomości systemowych",
    mensagem: "Wiadomość powitalna",
    deixeVazio: "Zostaw puste, by losować spośród gotowych zdań",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtry, które moderują same, zanim wiadomość w ogóle powstanie. Kto zarządza serwerem, nigdy nie jest filtrowany — a role zwolnione przechodzą bez przeszkód.",
    palavras: {
      titulo: "Blokuj własne słowa",
      descricao: "Twoja lista słów, których nikt nie może napisać.",
    },
    mencoes: {
      titulo: "Blokuj spam wzmianek",
      descricao: "Blokuje wiadomość ze zbyt wieloma wzmiankami naraz.",
    },
    links: {
      titulo: "Blokuj linki",
      descricao: "Zatrzymuje każdy adres wklejony na czacie.",
    },
    definir: "Ustaw",
    nomeDaRegra: "Nazwa reguły",
    bloqueadas: "Zablokowane słowa",
    digiteEnter: "Wpisz i naciśnij Enter",
    comparacao: "Porównanie pomija wielkość liter, znaki diakrytyczne i interpunkcję — i nie łapie słowa wewnątrz innego.",
    aPartirDe: "Blokuj od ilu wzmianek",
    oQueFazer: "Co zrobić",
    canalDoAlerta: "Kanał powiadomienia",
    escolhaCanal: "Wybierz kanał",
    castigo: "Wyciszenie (minuty)",
    isentos: "Role zwolnione",
    semCargos: "Nie utworzono jeszcze żadnej roli.",
    salvarRegra: "Zapisz regułę",
    apagar: "Usuń regułę",
    excluirTitulo: "Usunąć tę regułę AutoModa?",
    excluirDescricao: "Serwer natychmiast przestaje po niej filtrować. Można ją utworzyć od nowa, ale obecne ustawienia przepadną.",
    excluirAcao: "Usuń regułę",
  },
  cargos: {
    titulo: "Role",
    descricao: "Role dają nazwę, kolor i uprawnienia. Kto stoi wyżej na liście, rządzi tymi niżej — i nikt nie rusza roli równej własnej ani wyższej.",
    criar: "Utwórz rolę",
    vazio: "Nie ma jeszcze ról.",
    abaExibicao: "Wygląd",
    abaPermissoes: "Uprawnienia",
    abaMembros: "Członkowie — {{quantos}}",
    everyone: "Dotyczy wszystkich na serwerze. To podstawa, na której dokładają się pozostałe role.",
    nomeDoCargo: "Nazwa roli",
    cor: "Kolor roli",
    corDica: "Koloruje nazwę osoby z tą rolą na liście członków i na czacie.",
    semCor: "Bez koloru",
    corPersonalizada: "Własny kolor",
    estilo: "Styl nazwy",
    segundaCor: "Drugi kolor",
    segundaCorDica: "Bez niego gradient wraca do jednolitego koloru — nie znika.",
    limparSegundaCor: "Wyczyść drugi kolor",
    icone: "Ikona",
    iconeDica: "Pojawia się obok roli na karcie profilu osoby, która ją ma.",
    exibirSeparado: "Pokazuj oddzielnie od pozostałych członków",
    exibirSeparadoDica: "Rola dostaje własną sekcję na liście członków.",
    permitirMencionar: "Pozwól wspominać tę rolę",
    permitirMencionarDica: "Każdy będzie mógł powiadomić wszystkich, którzy mają tę rolę.",
    semPoderDeConceder: "{{descricao}} (nie masz tego uprawnienia, by je nadać)",
    adicionar: "Dodaj kogoś do tej roli",
    tirar: "Odbierz rolę",
    semNinguem: "Nikt jeszcze nie ma tej roli.",
    apagar: "Usuń rolę",
    excluirTitulo: "Usunąć rolę „{{nome}}\"?",
    excluirDescricao: "Kto ma tę rolę, traci wszystko, co ona dawała. Tego nie da się cofnąć.",
    excluirAcao: "Usuń rolę",
  },
  membros: {
    procurar: "Szukaj po nazwie lub nazwie użytkownika",
    membroDesde: "Członek od",
    vazio: "Nikogo nie znaleziono.",
    acoesPara: "Działania dla {{nome}}",
    deCastigo: "wyciszenia",
    tirarCastigo: "Zdejmij wyciszenie",
    castigo5min: "5 minut",
    castigo1h: "1 godzina",
    castigo1d: "1 dzień",
    castigo1s: "1 tydzień",
    expulsar: "Wyrzuć",
    expulsarTitulo: "Wyrzucić {{nome}}?",
    expulsarDescricao: "opuszcza {{servidor}} natychmiast. Może wrócić z zaproszeniem — wyrzucenie nie blokuje powrotu.",
    banir: "Zbanuj",
    banirTitulo: "Zbanować {{nome}}?",
    banirDescricao: "opuszcza {{servidor}} i nie wróci, nawet z zaproszeniem, dopóki ban nie zostanie zdjęty.",
    motivo: "Powód (opcjonalnie)",
    motivoDica: "Zapisuje się w dzienniku",
  },
  perfil: {
    titulo: "Profil serwera",
    descricao: "Tak twój serwer wygląda na liście i w linkach zapraszających.",
    icone: "Ikona",
    faixa: "Baner na górze",
    nomeDoServidor: "Nazwa serwera",
    campoDescricao: "Opis",
    doQueE: "O czym jest ten serwer?",
    comprimido: "Skompresowano przed wysłaniem: {{economia}}",
  },
  etiqueta: {
    titulo: "Tag serwera",
    descricao: "Etykieta do 4 liter, która pojawia się obok nazwy każdego członka — na czacie i na liście osób. Tutaj jest za darmo: bez ulepszeń, bez poziomów.",
    escolhaNome: "Wybierz nazwę",
    limite: "Maksymalnie 4 znaki, litery i cyfry.",
    escolhaInsignia: "Wybierz odznakę",
    voce: "Ty",
    fala1: "ktoś chętny na granie?",
    fala2: "zerknij na mój tag!",
    fala3: "o kurczę, jak to zdobyłeś",
  },
  expressoes: {
    comoUsar: "Dodaj do {{limite}} emoji, których każdy może używać na tym serwerze. Wpisz :nazwa: na czacie, żeby je wysłać.",
    imagem: "Obraz",
    enviadoPor: "Wysłane przez",
    semEmoji: "Nie ma jeszcze emoji.",
    figurinhas: "Naklejki",
    enviarFigurinha: "Wyślij naklejkę",
    nomeDaFigurinha: "Nazwa naklejki",
    exemploFigurinha: "Np. przytulanka kotka",
    figurinhaGrande: "Naklejka przekracza {{limite}}.",
    deixaPraLa: "Nieważne",
    sons: "Panel dźwięków",
    enviarSom: "Wyślij dźwięk",
    nomeDoSom: "Nazwa dźwięku",
    semSom: "Nie ma jeszcze dźwięków.",
    somGrande: "Dźwięk przekracza {{limite}}.",
    emojiRelacionado: "Powiązane emoji",
    ouvir: "Odtwórz",
    ouvirAssim: "Odtwórz tak",
    volumeDe: "Głośność {{nome}}",
    volumeDica: "Dotyczy wszystkich na serwerze. Każda osoba i tak może ściszyć dźwięki tylko dla siebie, w panelu rozmowy.",
    falhaEnvio: "Nie udało się wysłać pliku.",
    excluirTitulo: "Usunąć {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Znika z serwera dla wszystkich. Wiadomości, które już go użyły, zostają bez zmian.",
  },
};
