export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Ustawienia serwera",
  auditoria: {
    todasAsAcoes: "Wszystkie działania",
    todosOsUsuarios: "Wszyscy użytkownicy",
    filtroMembros: "Członkowie",
    filtroCanais: "Kanały",
    filtroEmojis: "Emoji",
    filtroServidor: "Serwer",
    titulo: "Dziennik zdarzeń",
    porUsuario: "Filtruj po osobie",
    porAcao: "Filtruj po działaniu",
    vazio: "Nic jeszcze nie zapisano z tym filtrem.",
    motivo: "Powód:",
  },
  banimentos: {
    titulo: "Lista banów serwera",
    descricao: "Kto tu jest, nie wróci nawet z nowym zaproszeniem. Zdjęcie bana od razu przywraca dostęp.",
    procurar: "Szukaj banów po nazwie użytkownika",
    vazioTitulo: "Brak banów",
    vazio: "Nikogo jeszcze nie zbanowałeś… ale gdy zajdzie potrzeba, nie wahaj się.",
    desbanir: "Zdejmij bana",
  },
  excluir: {
    tudoVai: "Wszystkie kanały, wiadomości i zaproszenia serwera {{servidor}} zostaną usunięte dla {{membros}} członków. Nikt ich potem nie odzyska.",
    digite: "Wpisz {{servidor}}, aby potwierdzić",
    titulo: "Usuń serwer",
    aviso: "Tego nie da się cofnąć.",
  },
  emblemas: {
    apagarDescricao: "Znika u każdego, kto go nosi. Tego nie da się cofnąć.",
    titulo: "Odznaki",
    vazio: "Jeszcze nie ma odznak.",
    novo: "Nowa odznaka",
  },
  convites: {
    revogarTitulo: "Unieważnić zaproszenie?",
    revogarAcao: "Unieważnij",
    revogarDescricao: "Link {{codigo}} przestaje działać natychmiast. Kto już wszedł przez niego, zostaje na serwerze.",
    titulo: "Zaproszenia",
    descricao: "Wszystkie aktywne linki zapraszające tego serwera.",
    vazio: "Nie utworzono jeszcze żadnego zaproszenia.",
    revogar: "Unieważnij zaproszenie",
  },
  integracoes: {
    opcionais: "username i avatar_url są opcjonalne i działają na wiadomość. Limit to 5 wiadomości na 5 sekund.",
    apagarDescricao: "URL przestaje działać natychmiast. Wiadomości, które już wysłał, zostają na kanale.",
    titulo: "Integracje",
    descricao: "Webhook to adres, który pisze na kanale bez potrzeby posiadania konta. Przydaje się, by ogłosić, że build przeszedł, że ktoś otworzył zgłoszenie, albo cokolwiek chcesz wysłać ze skryptu.",
    novo: "Nowy webhook",
    vazio: "Nie ma jeszcze webhooków. Utwórz jeden i wklej URL tam, skąd ma przychodzić wiadomość.",
    canal: "Kanał",
    apagar: "Usuń webhook",
    comoUsar: "Jak używać",
    comoUsarTexto: "Wyślij POST z JSON-em:",
  },
  explorar: {
    titulo: "Odkrywaj",
  },
  engajamento: {
    semCanal: "Bez kanału systemowego",
    titulo: "Zaangażowanie",
    descricao: "Co serwer robi sam, żeby nie wyglądał pusto, gdy przychodzi ktoś nowy.",
    sistema: "Wiadomości systemowe",
    boasVindas: "Wyślij powitanie, gdy ktoś dołączy",
    sorteio: "Bez własnego tekstu poniżej zdanie jest losowane — wciąż to samo szybko się nudzi.",
    canalDoSistema: "Kanał wiadomości systemowych",
    mensagem: "Wiadomość powitalna",
    deixeVazio: "Zostaw puste, by losować spośród gotowych zdań",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtry, które moderują same, zanim wiadomość w ogóle powstanie. Kto zarządza serwerem, nigdy nie jest filtrowany — a role zwolnione przechodzą bez przeszkód.",
    palavras: {
      titulo: "Blokuj własne słowa",
      descricao: "Twoja lista słów, których nikt nie może napisać.",
    },
    mencoes: {
      titulo: "Blokuj spam wzmianek",
      descricao: "Blokuje wiadomość ze zbyt wieloma wzmiankami naraz.",
    },
    links: {
      titulo: "Blokuj linki",
      descricao: "Zatrzymuje każdy adres wklejony na czacie.",
    },
    definir: "Ustaw",
    nomeDaRegra: "Nazwa reguły",
    bloqueadas: "Zablokowane słowa",
    digiteEnter: "Wpisz i naciśnij Enter",
    comparacao: "Porównanie pomija wielkość liter, znaki diakrytyczne i interpunkcję — i nie łapie słowa wewnątrz innego.",
    aPartirDe: "Blokuj od ilu wzmianek",
    oQueFazer: "Co zrobić",
    canalDoAlerta: "Kanał powiadomienia",
    escolhaCanal: "Wybierz kanał",
    castigo: "Wyciszenie (minuty)",
    isentos: "Role zwolnione",
    semCargos: "Nie utworzono jeszcze żadnej roli.",
    salvarRegra: "Zapisz regułę",
    apagar: "Usuń regułę",
    excluirTitulo: "Usunąć tę regułę AutoModa?",
    excluirDescricao: "Serwer natychmiast przestaje po niej filtrować. Można ją utworzyć od nowa, ale obecne ustawienia przepadną.",
    excluirAcao: "Usuń regułę",
  },
  cargos: {
    titulo: "Role",
    descricao: "Role dają nazwę, kolor i uprawnienia. Kto stoi wyżej na liście, rządzi tymi niżej — i nikt nie rusza roli równej własnej ani wyższej.",
    criar: "Utwórz rolę",
    vazio: "Nie ma jeszcze ról.",
    abaExibicao: "Wygląd",
    abaPermissoes: "Uprawnienia",
    abaMembros: "Członkowie — {{quantos}}",
    everyone: "Dotyczy wszystkich na serwerze. To podstawa, na której dokładają się pozostałe role.",
    nomeDoCargo: "Nazwa roli",
    cor: "Kolor roli",
    corDica: "Koloruje nazwę osoby z tą rolą na liście członków i na czacie.",
    semCor: "Bez koloru",
    corPersonalizada: "Własny kolor",
    estilo: "Styl nazwy",
    segundaCor: "Drugi kolor",
    segundaCorDica: "Bez niego gradient wraca do jednolitego koloru — nie znika.",
    limparSegundaCor: "Wyczyść drugi kolor",
    icone: "Ikona",
    iconeDica: "Pojawia się obok roli na karcie profilu osoby, która ją ma.",
    exibirSeparado: "Pokazuj oddzielnie od pozostałych członków",
    exibirSeparadoDica: "Rola dostaje własną sekcję na liście członków.",
    permitirMencionar: "Pozwól wspominać tę rolę",
    permitirMencionarDica: "Każdy będzie mógł powiadomić wszystkich, którzy mają tę rolę.",
    semPoderDeConceder: "{{descricao}} (nie masz tego uprawnienia, by je nadać)",
    adicionar: "Dodaj kogoś do tej roli",
    tirar: "Odbierz rolę",
    semNinguem: "Nikt jeszcze nie ma tej roli.",
    apagar: "Usuń rolę",
    excluirTitulo: "Usunąć rolę „{{nome}}\"?",
    excluirDescricao: "Kto ma tę rolę, traci wszystko, co ona dawała. Tego nie da się cofnąć.",
    excluirAcao: "Usuń rolę",
  },
  membros: {
    procurar: "Szukaj po nazwie lub nazwie użytkownika",
    membroDesde: "Członek od",
    vazio: "Nikogo nie znaleziono.",
    acoesPara: "Działania dla {{nome}}",
    deCastigo: "wyciszenia",
    tirarCastigo: "Zdejmij wyciszenie",
    castigo5min: "5 minut",
    castigo1h: "1 godzina",
    castigo1d: "1 dzień",
    castigo1s: "1 tydzień",
    expulsar: "Wyrzuć",
    expulsarTitulo: "Wyrzucić {{nome}}?",
    expulsarDescricao: "opuszcza {{servidor}} natychmiast. Może wrócić z zaproszeniem — wyrzucenie nie blokuje powrotu.",
    banir: "Zbanuj",
    banirTitulo: "Zbanować {{nome}}?",
    banirDescricao: "opuszcza {{servidor}} i nie wróci, nawet z zaproszeniem, dopóki ban nie zostanie zdjęty.",
    motivo: "Powód (opcjonalnie)",
    motivoDica: "Zapisuje się w dzienniku",
  },
  perfil: {
    titulo: "Profil serwera",
    descricao: "Tak twój serwer wygląda na liście i w linkach zapraszających.",
    icone: "Ikona",
    faixa: "Baner na górze",
    nomeDoServidor: "Nazwa serwera",
    campoDescricao: "Opis",
    doQueE: "O czym jest ten serwer?",
    comprimido: "Skompresowano przed wysłaniem: {{economia}}",
  },
  etiqueta: {
    titulo: "Tag serwera",
    descricao: "Etykieta do 4 liter, która pojawia się obok nazwy każdego członka — na czacie i na liście osób. Tutaj jest za darmo: bez ulepszeń, bez poziomów.",
    escolhaNome: "Wybierz nazwę",
    limite: "Maksymalnie 4 znaki, litery i cyfry.",
    escolhaInsignia: "Wybierz odznakę",
    voce: "Ty",
    fala1: "ktoś chętny na granie?",
    fala2: "zerknij na mój tag!",
    fala3: "o kurczę, jak to zdobyłeś",
  },
  expressoes: {
    comoUsar: "Dodaj do {{limite}} emoji, których każdy może używać na tym serwerze. Wpisz :nazwa: na czacie, żeby je wysłać.",
    imagem: "Obraz",
    enviadoPor: "Wysłane przez",
    semEmoji: "Nie ma jeszcze emoji.",
    figurinhas: "Naklejki",
    enviarFigurinha: "Wyślij naklejkę",
    nomeDaFigurinha: "Nazwa naklejki",
    exemploFigurinha: "Np. przytulanka kotka",
    figurinhaGrande: "Naklejka przekracza {{limite}}.",
    deixaPraLa: "Nieważne",
    sons: "Panel dźwięków",
    enviarSom: "Wyślij dźwięk",
    nomeDoSom: "Nazwa dźwięku",
    semSom: "Nie ma jeszcze dźwięków.",
    somGrande: "Dźwięk przekracza {{limite}}.",
    emojiRelacionado: "Powiązane emoji",
    ouvir: "Odtwórz",
    ouvirAssim: "Odtwórz tak",
    volumeDe: "Głośność {{nome}}",
    volumeDica: "Dotyczy wszystkich na serwerze. Każda osoba i tak może ściszyć dźwięki tylko dla siebie, w panelu rozmowy.",
    falhaEnvio: "Nie udało się wysłać pliku.",
    excluirTitulo: "Usunąć {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Znika z serwera dla wszystkich. Wiadomości, które już go użyły, zostają bez zmian.",
  },
  canal: {
    visaoGeral: "Przegląd",
    nome: "Nazwa kanału",
    topico: "Temat kanału",
    topicoDica: "O czym się tu mówi?",
    modoLento: "Każda osoba wysyła tylko jedną wiadomość na przedział. Kto zarządza wiadomościami lub kanałami, przechodzi bez ograniczeń.",
    visibilidade: "Widoczność treści",
    padrao: "Domyślnie",
    padraoDica: "Treść kanału jest zawsze widoczna.",
    spoiler: "Kanał ze spoilerami",
    spoilerDica: "Oznacz ten kanał jako zawierający spoilery, żeby zwroty akcji i ciężkie tematy pozostały ukryte, dopóki ktoś nie zdecyduje się spojrzeć.",
    idade: "Kanał z ograniczeniem wieku",
    idadeDica: "Kto wejdzie, musi potwierdzić pełnoletność, żeby zobaczyć treść.",
    bitrateDica: "Powyżej 64 kbps może przeszkadzać osobom ze słabym łączem.",
    qualidadeDeVideo: "Jakość wideo",
    automatica: "Automatyczna",
    limite: "Limit użytkowników — {{valor}}",
    pessoas: "{{quantos}} osób",
    semLimite: "bez limitu",
    permissoesDescricao: "Tutaj zmieniasz to, co obowiązuje na tym kanale. Co zostanie na „dziedzicz”, dalej idzie za rolą.",
    excluir: {
      titulo: "Usuń kanał",
      historico: "Cała historia kanału {{canal}} znika razem z nim, dla wszystkich.",
      digite: "Wpisz {{canal}}, aby potwierdzić",
    },
  },
  moderacao: {
    titulo: "Widok moderatora",
    semPermissao: "Potrzebujesz uprawnienia „Moderowanie członków”, żeby to zobaczyć.",
    fecharEsc: "Zamknij (Esc)",
    atividade: "Aktywność na serwerze",
    mensagens: "Wiadomości",
    links: "Linki",
    midia: "Media",
    acoesNaAuditoria: "Działania w dzienniku",
    moderacoesSofridas: "Otrzymane moderacje",
    permissoes: "Uprawnienia ({{quantas}})",
    semPermissaoEspecial: "Brak specjalnych uprawnień.",
    conta: "Konto",
    entrouNoServidor: "Dołączył do serwera",
    contaCriadaEm: "Konto utworzone",
    deCastigoAte: "Wyciszony do",
    formaDeAdesao: "Jak dołączył",
    mensagem: "Wiadomość",
    castigo: "Wyciszenie",
    copiarId: "Kopiuj ID",
    idCopiado: "Skopiowano ID.",
    adicionarCargo: "Dodaj rolę",
    semCargos: "Nie utworzono roli",
    soEveryone: "Tylko @everyone.",
    voltar: "Wróć",
    vazio: "Nic tu nie ma.",
    cinquenta: "Pokazuję 50 najnowszych.",
    irParaMensagem: "Przejdź do wiadomości",
    precisaSerAmigo: "Musicie być znajomymi, żeby rozmawiać.",
    expulsarDescricao: "Opuszcza serwer natychmiast, ale może wrócić z zaproszeniem.",
    banirDescricao: "Opuszcza serwer i nie wróci, nawet z zaproszeniem, dopóki ban nie zostanie zdjęty.",
    castigarTitulo: "Wyciszyć {{nome}}?",
    castigoDescricao: "Dopóki trwa, nie pisze ani nie mówi na żadnym kanale serwera.",
    aplicarCastigo: "Zastosuj wyciszenie",
    duracao: "Czas w minutach",
    informeDuracao: "Podaj czas w minutach.",
  },
  abas: {
    expressoes: "Wyrażenia",
    pessoas: "Ludzie",
    apps: "Aplikacje",
    moderacao: "Moderacja",
    banimentos: "Bany",
  },
};
