export const amizades = {
  ativosAgora: "פעילים עכשיו",
  procurando: "בודקים מי נמצא…",
  tudoTranquilo: "הכול שקט כרגע…",
  tudoTranquiloDetalhe: "כשאתה או חבר תצטרפו לשיחה, היא תופיע כאן — ותוכל להצטרף בלחיצה אחת.",
  emVoz: "בשיחה קולית",
  voce: "אתה",
  soVoce: "רק אתה",
  pessoas: "{{quantas}} אנשים",
  voltarParaChamada: "חזרה לשיחה",
  entrarNaChamada: "הצטרפות לשיחה",
  abrirCanal: "פתיחת {{canal}} ב־{{servidor}}",
  mensagensDiretas: "הודעות ישירות",
  encontreConversa: "מצא שיחה",
  amigos: "חברים",
  conversas: "שיחות",
  semConversas: "עדיין אין שיחות. הוסף חבר כדי להתחיל.",
  semConversaComEsseNome: "אין שיחה בשם הזה.",
  abrirMenu: "פתיחת שרתים ושיחות",
  solicitacoes: "בקשות הודעה",
  pedidos: "בקשות",
  spam: "ספאם",
  pedidosPendentes: "בקשות ממתינות",
  marcadosComoSpam: "סומנו כספאם",
  aceitar: "אישור",
  ignorar: "התעלמות",
  marcarSpam: "סימון כספאם",
  semPedidos: "אין בקשות ממתינות.",
  semPedidosDetalhe: "מי שאינו חבר שלך אך חולק איתך שרת מגיע לכאן לפני שהוא מגיע לשיחות שלך.",
  semSpam: "שום דבר לא סומן כספאם.",
  semSpamDetalhe: "מה שמסנן הספאם מפריד, או מה שאתה מסמן, נשאר בלשונית הזו.",
  umServidorEmComum: "שרת משותף אחד",
  servidoresEmComum: "{{quantos}} שרתים משותפים",
  semServidoresEmComum: "אין שרתים משותפים",
};
