export const chamada = {
  conectando: "מתחבר לשיחה…",
  naoEntrou: "לא הצלחנו להצטרף לשיחה",
  sair: "יציאה מהשיחה",
  sairDaVoz: "יציאה משיחת הקול",
  desconectar: "ניתוק",
  voltar: "חזרה לשיחה",
  voltarAosQuadros: "חזרה למשבצות השיחה",
  fecharChat: "סגירת הצ׳אט",
  mostrarChat: "הצגת הצ׳אט",
  convidar: "הזמנה לשיחה",
  carregandoPrevia: "טוען תצוגה מקדימה…",
  maisOpcoes: "אפשרויות נוספות",
  deVideo: "שיחת וידאו",
  deVoz: "שיחת קול",
  alguem: "מישהו",
  volume: {
    entrada: "עוצמת קלט",
    saida: "עוצמת פלט",
    live: "עוצמת השידור",
    liveComPorcento: "עוצמת השידור ({{porcento}}%)",
    liveSemSom: "שידור ללא קול",
  },
  aparelhos: {
    entrada: "התקן קלט",
    saida: "התקן פלט",
    camera: "מצלמה",
    microfone: "מיקרופון",
    saidaCurto: "פלט",
    oDoSistema: "זה של המערכת",
    aDoSistema: "זו של המערכת",
    semEscolhaDeSaida: "הדפדפן הזה לא נותן לבחור פלט — המערכת מחליטה.",
    espelhar: "היפוך המצלמה שלי",
    configEntrada: "הגדרות קלט",
    configSaida: "הגדרות פלט",
    configCamera: "הגדרות המצלמה",
    configAudioEVideo: "הגדרות שמע ווידאו",
  },
  tela: {
    compartilhar: "שיתוף מסך",
    compartilharAcao: "שיתוף",
    cancelar: "ביטול",
    telas: "מסכים",
    janelas: "חלונות",
    somDoComputador: "לקחת גם את קול המחשב",
    somDoSistema: "לקחת גם את קול המערכת",
    configCompartilhamento: "הגדרות שיתוף",
    mostrarSemVideo: "הצגת מי שבלי וידאו",
    semFontes: "המערכת לא החזירה שום מסך או חלון לשיתוף.",
    pararDeCompartilhar: "הפסקת השיתוף",
    encerrarTransmissao: "סיום השידור",
  },
  live: {
    etiqueta: "בשידור חי",
    etiquetaMaiuscula: "בשידור חי",
    assistir: "צפייה בשידור",
    assistirPessoa: "צפייה ב{{nome}}",
    pararDeAssistir: "הפסקת הצפייה",
  },
  membro: {
    mudarMeuApelido: "שינוי הכינוי שלי",
    meuMicrofone: "המיקרופון שלי",
    ouvirChamada: "האזנה לשיחה",
    copiarMeuId: "העתקת המזהה שלי",
    idCopiado: "המזהה הועתק.",
    mensagem: "הודעה",
    silenciar: "השתקה",
    alterarApelido: "שינוי הכינוי",
    cargos: "תפקידים",
    semCargo: "לא נוצר אף תפקיד",
    moverPara: "העברה אל",
    silenciarNoServidor: "השתקת הקול בשרת",
    desativarAudioNoServidor: "ביטול השמע בשרת",
    desconectar: "ניתוק",
    apelidoTitulo: "הכינוי שלך בשרת הזה",
    apelidoDeAlguem: "הכינוי של {{nome}}",
    apelidoCampo: "כינוי",
    apelidoDicaPropria: "תקף רק כאן. השאירו ריק כדי לחזור לשם הרגיל שלכם.",
    apelidoDicaDeOutro: "תקף רק בשרת הזה. השאירו ריק כדי לחזור לשם המקורי.",
  },
  detalhes: {
    abrir: "פרטי הקול",
    titulo: "פרטי הקול",
    conexao: "חיבור",
    pingMedio: "פינג ממוצע",
    ultimoPing: "פינג אחרון",
    perda: "אובדן חבילות שנשלחו",
    medindo: "מודד…",
    criptografado: "מוצפן עד לשרת (DTLS-SRTP)",
    explicacao: "מעל 250 מילישניות מרגישים את ההשהיה בשיחה — אנשים מתחילים לדבר אחד על השני. אובדן חבילות מעל 10% הופך את הקול לרובוטי. בשני המקרים הבעיה כמעט תמיד בינך לבין האינטרנט: נסה כבל במקום Wi-Fi, או להפעיל מחדש את הנתב.",
  },
  microfone: {
    bloqueado: "המיקרופון חסום — אתם רק מאזינים. אפשרו גישה בהרשאות הדפדפן.",
    bloqueadoNoMac: "macOS חוסם את המיקרופון. סמנו את",
    caminhoNoMac: "הגדרות מערכת ← פרטיות ואבטחה ← מיקרופון",
    abrirAjustes: "פתיחת ההגדרות",
    vaiReabrir: "macOS יבקש לפתוח מחדש את היישום.",
    naoAbriu: "לא הצלחנו לפתוח את המיקרופון — אתם רק מאזינים. בדקו את ההתקן בהגדרות ← קול ווידאו.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS עוד לא אישר הקלטת מסך. בלי זה השיתוף יוצא שחור.",
    marque: "סמנו את",
    reabra: "תחת «הקלטת מסך» ופתחו מחדש את היישום.",
    jaMarcado: "אם זה כבר מסומן, ההרשאה התיישנה בעדכון האחרון: בטלו את הסימון, סמנו שוב ופתחו מחדש.",
  },
  ruido: {
    titulo: "הפחתת רעש",
    explicacao: "הוציאו את רעש הרקע מהקול שלכם. נסו למחוא כפיים או להזיז את המקלדת תוך כדי דיבור — בשיחה שומעים רק אתכם.",
    semSuporte: "הדפדפן הזה לא מריץ את ההפחתה המתקדמת. זו של הדפדפן עצמו עדיין פועלת, והיא חלשה יותר.",
    aplicando: "מחיל על השיחה…",
    faleParaTestar: "דברו כדי לבדוק",
    verdeQuandoPassa: "ירוק כשהקול שלכם עובר.",
    teOuvindo: "שומעים אתכם עכשיו.",
    feitoCom: "עשוי עם",
    aquiNoAparelho: "‏, כאן על המכשיר שלכם",
    ajustes: "הגדרות",
  },
  permissoes: {
    titulo: "הרשאות macOS",
    detalhe: "macOS שואל פעם אחת בלבד, ואחר כך זה משתנה רק בלוח שלו. כאן רואים מה תקף ופותרים את מה שחסר.",
    concedida: "ניתנה",
    negada: "נדחתה",
    naoPedida: "לא התבקשה",
    permitir: "אישור",
    abrirAjustes: "פתיחת ההגדרות",
    microfone: "מיקרופון",
    microfoneDetalhe: "לדבר בשיחות ולבדוק את הקלט.",
    camera: "מצלמה",
    cameraDetalhe: "להדליק את הווידאו בשיחה.",
    tela: "הקלטת מסך",
    telaDetalhe: "לשתף את המסך והחלונות.",
    monitoramento: "ניטור קלט",
    monitoramentoDetalhe: "להשתמש בלחץ-כדי-לדבר גם כש‑Gravaê ברקע.",
  },
  jaConectado: {
    titulo: "אתם כבר בשיחה הזו",
    trazer: "להעביר את השיחה לכאן",
    deixar: "להשאיר כמו שזה",
    detalhe: "אם תעבירו לכאן, הצד השני יוצא מהשיחה — החשבון שלכם נמצא במקום אחד בכל רגע.",
  },
};
