export const comum = {
  carregando: "טוען…",
  salvar: "שמור",
  salvando: "שומר…",
  descartar: "בטל",
  redefinir: "אפס",
  naoSalvo: "יש לך שינויים שלא נשמרו.",
  fechar: "סגירה",
  criar: "יצירה",
  nome: "שם",
  emoji: "אימוג'י",
  previa: "תצוגה מקדימה",
  cancelar: "ביטול",
  enviar: "שליחה",
  apagar: "מחיקה",
  excluir: "מחיקה",
  remover: "הסרה",
  trocar: "החלפה",
};
