export const configuracoes = {
  sair: "התנתקות",
  versoes: {
    copiar: "לחץ כדי להעתיק",
    copiado: "הועתק",
  },
  telas: {
    conta: "החשבון שלי",
    privacidade: "פרטיות",
    conexoes: "חיבורים",
    voz: "שמע",
    video: "וידאו",
    avisos: "התראות",
    aplicativos: "יישומים",
    aparencia: "מראה",
    batePapo: "צ'אט",
    acessibilidade: "נגישות",
    idioma: "שפה",
    aplicativo: "הורדת האפליקציה",
    atalhos: "קיצורי מקלדת",
    servidor: "שרת",
  },
  grupos: {
    conta: "חשבון",
    app: "הגדרות האפליקציה",
    desenvolvedor: "מפתח",
    administracao: "ניהול",
  },
  secoes: {
    detalhesDeLogin: "פרטי כניסה",
    dispositivos: "מכשירים",
    usuariosBloqueados: "משתמשים חסומים",
    aplicativosAutorizados: "אפליקציות מורשות",
    sessoes: "הפעלות",
    amigosEDms: "חברים והודעות ישירות",
    compartilhamentoDeAtividade: "שיתוף פעילות",
    visibilidadeDoPerfil: "נראות הפרופיל",
    exportarDados: "ייצוא נתונים",
    exclusaoDeDados: "מחיקת נתונים",
    tema: "ערכת נושא",
    corDeDestaque: "צבע הדגשה",
    interface: "ממשק",
    listaDeCanais: "רשימת ערוצים",
    zoomDoApp: "רמת הזום של האפליקציה",
    escalaDaFonte: "גודל הגופן בצ'אט",
    modoStreamer: "פרטיות בשידור",
    movimento: "תנועה",
    textoEmVoz: "טקסט לדיבור",
    teclado: "מקלדת",
    formatoDaHora: "תבנית שעה",
    idiomaDaInterface: "שפת הממשק",
    dispositivosDeVoz: "מכשירים",
    testeDoMicrofone: "בדיקת מיקרופון",
    modoDeEntrada: "מצב קלט",
    sensibilidade: "רגישות הקלט",
    qualidade: "איכות",
    camera: "מצלמה",
    transmissao: "שידור",
    exibicao: "תצוגה",
    entrada: "קלט",
    midia: "מדיה",
    geral: "כללי",
    preferenciaDeMencao: "העדפת אזכורים",
    sons: "צלילים",
  },
};
