export const configuracoes = {
  efeitos: {
    titulo: "אפקטים של הסמן",
    detalhe: "שובל וניצוצות שמצוירים מעל היישום. מתחילים כבויים, ונכבים מעצמם אם ביקשתם פחות תנועה.",
    rastro: "שובל הסמן",
    rastroDetalhe: "קו שעוקב אחרי הסמן ודועך מאחוריו.",
    faisca: "ניצוץ בלחיצה",
    faiscaDetalhe: "קווים קצרים שיוצאים מהנקודה שלחצתם בה.",
    cor: "צבע",
    espessura: "עובי",
    comprimento: "אורך",
    tamanho: "גודל",
    quantidade: "כמות",
  },
  email: {
    verificarTitulo: "אשרו את האימייל שלכם",
    verificarDetalhe: "יש קהילות שנותנות לכתוב רק למי שאישר. זה לחיצה אחת.",
    enviar: "שליחת הקישור",
    enviado: "הציצו בתיבה. הקישור תקף ליום.",
    falhou: "לא הצלחנו לשלוח את האימייל.",
    confirmado: "האימייל אושר",
    confirmadoDetalhe: "זהו. עכשיו אפשר לכתוב בכל קהילה שדורשת את זה.",
    linkIncompleto: "קישור חלקי",
    linkIncompletoDetalhe: "חסר הקוד בכתובת. פתחו את הקישור ישירות מהאימייל.",
    confirmando: "מאשרים…",
    expirou: "הקישור הזה כבר נוצל או שפג תוקפו.",
    irParaOApp: "לאפליקציה",
  },
  tema: {
    indisponivel: "ערכת הנושא לא זמינה",
    indisponivelDetalhe: "מי שפרסם אותה מחק אותה, או שהקישור שגוי.",
    indisponivelLinha: "ערכת הנושא לא זמינה. מי שפרסם אותה מחק אותה, או שהקישור שגוי.",
    importar: "ייבוא ערכת נושא",
    importarCurto: "ייבוא",
    importarDetalhe: "זה מחליף את ערכת הנושא שיש לכם עכשיו. אפשר לערוך אותה אחר כך בהגדרות > מראה > אולפן ערכות הנושא.",
    porAutor: "מאת {{autor}}",
    umaCorTrocada: "צבע אחד הוחלף",
    coresTrocadas: "{{quantas}} צבעים הוחלפו",
    avisoDeCss: "ערכת הנושא הזו מביאה CSS ממי שכתב אותה, ו‑CSS נוגע בכל פינה במסך. ייבאו רק מאנשים שאתם סומכים עליהם.",
    soCores: "ערכת הנושא הזו מחליפה צבעים בלבד. בלי CSS מבחוץ.",
    aplicar: "החלה",
    previaSemMotor: "התצוגה המקדימה לא מריצה את המנוע. התקינו כדי לראות.",
    motorAnimado: "{{motor}} מונפש",
  },
  sair: "התנתקות",
  versoes: {
    termos: "תנאי השירות",
    privacidade: "מדיניות הפרטיות",
    copiar: "לחץ כדי להעתיק",
    copiado: "הועתק",
  },
  telas: {
    conta: "החשבון שלי",
    privacidade: "פרטיות",
    conexoes: "חיבורים",
    voz: "שמע",
    video: "וידאו",
    avisos: "התראות",
    aplicativos: "יישומים",
    aparencia: "מראה",
    batePapo: "צ'אט",
    acessibilidade: "נגישות",
    idioma: "שפה",
    aplicativo: "הורדת האפליקציה",
    atalhos: "קיצורי מקלדת",
    desktop: "אפליקציית שולחן עבודה",
    avancado: "מתקדם",
    servidor: "שרת",
    comunicado: "הודעת מערכת",
    denuncias: "דיווחים",
    publicacoes: "פריסות",
  },
  grupos: {
    conta: "חשבון",
    app: "הגדרות האפליקציה",
    desenvolvedor: "מפתח",
    administracao: "ניהול",
  },
  secoes: {
    detalhesDeLogin: "פרטי כניסה",
    dispositivos: "מכשירים",
    usuariosBloqueados: "משתמשים חסומים",
    aplicativosAutorizados: "אפליקציות מורשות",
    sessoes: "הפעלות",
    amigosEDms: "חברים והודעות ישירות",
    compartilhamentoDeAtividade: "שיתוף פעילות",
    visibilidadeDoPerfil: "נראות הפרופיל",
    exportarDados: "ייצוא נתונים",
    exclusaoDeDados: "מחיקת נתונים",
    tema: "ערכת נושא",
    corDeDestaque: "צבע הדגשה",
    interface: "ממשק",
    listaDeCanais: "רשימת ערוצים",
    zoomDoApp: "רמת הזום של האפליקציה",
    escalaDaFonte: "גודל הגופן בצ'אט",
    modoStreamer: "פרטיות בשידור",
    cursores: "סמנים",
    movimento: "תנועה",
    textoEmVoz: "טקסט לדיבור",
    teclado: "מקלדת",
    formatoDaHora: "תבנית שעה",
    idiomaDaInterface: "שפת הממשק",
    dispositivosDeVoz: "מכשירים",
    testeDoMicrofone: "בדיקת מיקרופון",
    modoDeEntrada: "מצב קלט",
    sensibilidade: "רגישות הקלט",
    qualidade: "איכות",
    camera: "מצלמה",
    transmissao: "שידור",
    exibicao: "תצוגה",
    entrada: "קלט",
    midia: "מדיה",
    geral: "כללי",
    preferenciaDeMencao: "העדפת אזכורים",
    sons: "צלילים",
  },
};
