export const conversa = {
  lista: {
    carregando: "טוען הודעות…",
    carregandoMais: "טוען…",
    verMais: "גללו למעלה כדי לראות עוד",
    semHistorico: "ההיסטוריה אינה זמינה",
    semHistoricoDetalhe: "לתפקיד שלך אין הרשאה לקרוא את ההיסטוריה של ‎#{{canal}}‎. הודעות חדשות ימשיכו להופיע כל עוד אתם כאן.",
    boasVindas: "ברוכים הבאים ל‑‎#{{canal}}‎",
    boasVindasDetalhe: "זו ההתחלה של הערוץ ‎#{{canal}}‎.",
  },
  data: {
    hoje: "היום",
    ontem: "אתמול",
    hojeAs: "היום ב־{{hora}}",
    ontemAs: "אתמול ב־{{hora}}",
  },
  digitando: {
    um: "{{nome}} מקליד…",
    dois: "{{primeiro}} ו{{segundo}} מקלידים…",
    varios: "{{quantidade}} אנשים מקלידים…",
  },
  mensagem: {
    usou: "השתמש ב",
    fixada: "מוצמדת",
    editado: "(נערך)",
    ignorada: "הודעה ממישהו שאתם מתעלמים ממנו.",
    mostrar: "הצג",
    escPara: "Esc כדי",
    cancelar: "לבטל",
    enterParaSalvar: "Enter כדי לשמור",
    falhou: "לא נשלחה. נסו שוב",
    naoLidasDaqui: "לא נקראו מכאן.",
    linkCopiado: "הקישור הועתק.",
    idCopiado: "המזהה הועתק.",
    naoDeuParaCopiar: "הדפדפן שלכם לא אפשר להעתיק.",
    apagarTitulo: "למחוק את ההודעה?",
    apagarDescricao: "היא נעלמת מכל מי שבערוץ. אי אפשר לשחזר אותה.",
    apagarAcao: "מחק",
    citacaoAnexo: "לחצו כדי לראות את הקובץ המצורף",
    citacaoSumiu: "ההודעה המקורית כבר לא כאן.",
    reagirCom: "הגיבו עם {{emoji}} — החזיקו לתגובת־על",
    segureParaSuper: "{{emoji}} — החזיקו לתגובת־על",
  },
  acoes: {
    reagir: "הגב",
    responder: "השב",
    encaminhar: "העבר",
    favoritar: "שמור את ההודעה",
    tirarDosFavoritos: "הסר מהשמורות",
    marcarNaoLida: "סמן כלא נקראה",
    copiarLink: "העתק את קישור ההודעה",
    copiarId: "העתק את מזהה ההודעה",
    fixar: "הצמד את ההודעה",
    desafixar: "בטל הצמדה",
    editar: "ערוך",
    apagar: "מחק",
    mais: "עוד",
    adicionarReacao: "הוסף תגובה",
    superReagirCom: "תגובת־על עם {{emoji}}",
    fixarMensagem: "הצמד את ההודעה",
    desafixarMensagem: "בטל את הצמדת ההודעה",
    editarMensagem: "ערוך את ההודעה",
    apagarMensagem: "מחק את ההודעה",
  },
  mencao: {
    cargo: "אזכור של תפקיד",
    pessoa: "אזכור",
    alguem: "מישהו",
    cargoSemNome: "תפקיד",
    here: "מתריע למי שמחובר",
    everyone: "מתריע לכל השרת",
  },
  codigo: {
    copiar: "העתק",
    copiado: "הועתק",
    copiarAria: "העתק את הקוד",
    copiadoAria: "הקוד הועתק",
    recolher: "כווץ",
    expandir: "הרחב",
    verInteiro: "הצג את כל הקובץ",
    maisOpcoes: "אפשרויות נוספות",
    baixar: "הורדה",
    recolherLinhas: "כווץ ({{linhas}} שורות)",
    expandirLinhas: "הרחב ({{linhas}} שורות)",
    mudarIdioma: "שינוי שפה",
    procurarIdioma: "חיפוש קוד שפה…",
    nenhumIdioma: "לא נמצאה שפה.",
    quebrarTexto: "גלישת טקסט",
  },
  caixa: {
    escrever: "כתבו ב‑‎#{{canal}}‎",
    escreverSemCanal: "כתבו הודעה",
    semPermissao: "אין לכם הרשאה לשלוח הודעות בערוץ הזה",
    solteParaAnexar: "שחררו כדי לצרף",
    longaTitulo: "ההודעה ארוכה מדי…",
    longaDescricao: "הגעת למגבלה של {{limite}} תווים. אפשר לשלוח כקובץ.",
    enviarComoArquivo: "שליחה כקובץ",
    textoComoArquivo: "שליחת הטקסט כקובץ",
    arquivoGrandeTitulo: "הקובץ גדול מדי",
    arquivoGrandeDescricao: "„{{arquivo}}” חורג ממגבלת {{limite}} MB לקובץ.",
    respondendoPara: "בתגובה ל",
    vaiNotificar: "האדם יקבל התראה",
    naoVaiNotificar: "האדם לא יקבל התראה",
    ligado: "פועל",
    desligado: "כבוי",
    pararDeResponder: "בטלו את התגובה",
    mais: "עוד",
    enviarArquivo: "שלחו קובץ",
    criarEnquete: "צרו סקר",
    expressoes: "אימוג׳י, GIF ומדבקות",
    enviar: "שלח",
    aguardandoEnvio: "ממתין להעלאה",
    modoLento: "מצב איטי פעיל ({{tempo}})",
    modoLentoDica: "המצב האיטי מוגדר ל‑{{segundos}} שניות. המתינו לפני שליחת הודעה נוספת.",
  },
  anexos: {
    enviando: "מעלה…",
    modificar: "ערוך את {{arquivo}}",
    remover: "הסר את {{arquivo}}",
    ver: "הצג את {{arquivo}}",
    mostrarSpoiler: "הצג ספוילר: {{arquivo}}",
    spoiler: "ספוילר",
    spoilerTitulo: "ספוילר",
    editarTitulo: "עריכת הקובץ המצורף",
    nomeDoArquivo: "שם הקובץ",
    descricao: "תיאור הטקסט החלופי",
    descricaoDica: "תארו את המדיה הזו לקוראי מסך",
    marcarSpoiler: "סמן כספוילר",
    cancelar: "ביטול",
    salvar: "שמור",
  },
  cartao: {
    tocador: "נגן",
    abrir: "פתח את {{destino}}",
    tocar: "נגן את {{titulo}}",
    video: "וידאו",
    verImagem: "הצג את התמונה",
  },
  enquete: {
    titulo: "סקר",
    encerrada: "הסקר נסגר",
    variasRespostas: "סקר — כמה תשובות",
    umVoto: "{{quantidade}} קול",
    votos: "{{quantidade}} קולות",
    umVotoNoTotal: "{{quantidade}} קול בסך הכול",
    votosNoTotal: "{{quantidade}} קולות בסך הכול",
    encerraEm: "נסגר ב־{{quando}}",
    encerrarAgora: "סגור עכשיו",
  },
  fixadas: {
    titulo: "הודעות מוצמדות",
    vazio: "בערוץ הזה אין הודעות מוצמדות… בינתיים.",
    desafixar: "בטל הצמדה",
    anexo: "(קובץ מצורף)",
    enquete: "(סקר)",
    dicaRotulo: "טיפ:",
    dica: "מי שיש לו את ההרשאה «ניהול הודעות» יכול להצמיד ישירות מתפריט ההודעה.",
  },
  encaminhar: {
    titulo: "העברת ההודעה",
    paraOnde: "לאן?",
    semTexto: "(הודעה בלי טקסט)",
    nenhumLugar: "אין מקום בשם הזה.",
    canais: "ערוצים",
    conversas: "הודעות פרטיות",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "חיפוש ב-Klipy",
    figurinha: "מדבקה",
    buscarFigurinha: "מצא את המדבקה המושלמת",
    buscarEmoji: "מצא את האימוג׳י המושלם",
    buscarReacao: "מצא את התגובה המושלמת",
    adicionarEmoji: "הוספת אימוג׳י",
    limparBusca: "ניקוי החיפוש",
  },
  busca: {
    fechar: "סגירת החיפוש",
    procurando: "מחפש…",
    resultado: "{{quantos}} תוצאה",
    resultados: "{{quantos}} תוצאות",
    nadaCom: "אין כלום עם {{termo}} כאן.",
    soOsQuePodeLer: "החיפוש מסתכל רק בערוצים שמותר לך לקרוא.",
  },
  entrada: {
    titulo: "תיבת דואר נכנס",
    naoLidas: "לא נקראו",
    salvas: "שמורות",
    mencoes: "אזכורים",
    fimTitulo: "הגעת לסוף",
    fimDetalhe: "אין יותר מה לקרוא. כשתגיע הודעה חדשה, היא תופיע כאן.",
    semSalvosTitulo: "אין פריטים שמורים",
    semSalvosDetalhe: "החזק Shift ולחץ על הסימנייה של הודעה כדי לשמור אותה ולקרוא אחר כך.",
    tirarDosSalvos: "הסרה מהשמורות",
    semMencoesTitulo: "עדיין אין אזכורים",
    semMencoesDetalhe: "אזכורים שלך מופיעים כאן עבור 7 הימים האחרונים.",
  },
  forum: {
    descricao: "כל נושא הופך לשיחה נפרדת — טוב לשאלה שאסור לה ללכת לאיבוד באמצע הפטפוט.",
    novoAssunto: "נושא חדש",
    vazio: "עדיין אין נושאים. התחל את הראשון והשיחה תישאר מסודרת מההתחלה.",
    titulo: "כותרת",
    doQueSeTrata: "על מה מדובר?",
    primeiraMensagem: "הודעה ראשונה",
    conteDoCaso: "ספר על זה",
  },
};
