export const perfil = {
  carregando: "טוען…",
  editar: "עריכת פרופיל",
  mensagem: "הודעה",
  abrirConversa: "פתיחת השיחה",
  verCompleto: "הצגת הפרופיל המלא",
  convidarParaServidor: "הזמנה לשרת",
  semServidores: "אין לך שרתים",
  conviteEnviado: "ההזמנה נשלחה אל {{nome}}.",
  moderador: "פתיחה בתצוגת מנחה",
  mais: "עוד",
  ignorar: "התעלמות",
  deixarDeIgnorar: "ביטול ההתעלמות",
  copiarId: "העתקת מזהה המשתמש",
  idCopiado: "המזהה הועתק.",
  conexoes: "חיבורים",
  membroDesde: "חבר מאז",
  sobre: "אודות",
  cargosTitulo: "תפקידים",
  visaoGeral: "סקירה",
  amigosEmComum: "חברים משותפים ({{quantidade}})",
  servidoresEmComum: "שרתים משותפים ({{quantidade}})",
  amizade: {
    amigo: "חבר",
    pedidoEnviado: "בקשת חברות נשלחה",
    respondaAbaixo: "שלח לך בקשה — השב למטה",
    adicionar: "הוספת חבר",
    teMandouPedido: "שלח לך בקשת חברות",
    aceitar: "אישור",
    desfazer: "הסרה מהחברים",
    desfazerTitulo: "להסיר את {{nome}} מהחברים שלך?",
    desfazerDescricao: "אתם מפסיקים להיות חברים. השיחה הפרטית נשארת בהיסטוריה, ותוכל להוסיף אותו שוב מאוחר יותר.",
    bloquear: "חסימה",
    bloquearTitulo: "לחסום את {{nome}}?",
    bloquearDescricao: "אתם מפסיקים להיות חברים, השיחה הפרטית מפסיקה לקבל הודעות, והוא לא יוכל לשלוח לך בקשת חברות.",
    linkCopiado: "אתם לא חברים — הקישור הועתק כדי שתשלח אותו בעצמך.",
  },
  recado: {
    escrever: "כתוב אל ‎@{{usuario}}‎",
    enviar: "שלח",
    enviada: "ההודעה נשלחה",
    falhou: "לא הצלחנו לשלוח. נסה מתוך השיחה.",
  },
  cartao: {
    trocarFaixa: "החלפת הכרזה של הכרטיס",
    trocarFaixaCurto: "החלפת הכרזה",
    trocarFoto: "החלפת תמונת הפרופיל",
    trocarFotoCurto: "החלפת התמונה",
    suaEtiqueta: "התג שלך",
    editarEtiqueta: "לחץ כדי לערוך את התג",
    conteAlgo: "ספר לנו משהו על עצמך",
    adicionarStatus: "הוספת סטטוס",
    adicionarDescricao: "לחץ כדי להוסיף תיאור",
    cargo: "תפקיד",
    cargos: "תפקידים",
    cargosCom: "תפקידים — {{quantidade}}",
    tirarCargo: "הסרת התפקיד {{cargo}}",
  },
  cargos: {
    adicionar: "הוספת תפקיד",
    procurar: "חיפוש תפקיד",
  },
  etiqueta: {
    escolher: "בחירת תג השרת",
    nenhuma: "אין תג שרת",
    semEtiqueta: "לאף אחד מהשרתים שלך אין תג",
  },
  emblemas: {
    doServidor: "תגי הכבוד של השרת הזה",
    limite: "אפשר לענוד עד {{quantidade}} תגים.",
  },
  nota: {
    vazia: "לחץ כדי לרשום משהו",
    rotulo: "הערה (רק אתה רואה)",
  },
  status: {
    titulo: "סטטוס",
    definir: "הגדרת הסטטוס שלך",
    escolherEmoji: "בחירת אימוג׳י",
    tirarEmoji: "הסרת האימוג׳י",
    oQuePensa: "על מה אתה חושב?",
    limparAgora: "ניקוי הסטטוס עכשיו",
    naoLimpar: "לא לנקות",
    limpar30m: "ניקוי בעוד 30 דקות",
    limpar1h: "ניקוי בעוד שעה",
    limpar4h: "ניקוי בעוד 4 שעות",
    limparHoje: "ניקוי היום",
    limparAmanha: "ניקוי מחר",
    comHora: "{{prazo}} ב־{{hora}}",
  },
  presenca: {
    disponivel: "זמין",
    ausente: "לא נמצא",
    naoPerturbar: "נא לא להפריע",
    naoPerturbarDetalhe: "אינך מקבל התראה על הודעות חדשות",
    invisivel: "בלתי נראה",
    invisivelDetalhe: "לאחרים אתה נראה לא מחובר",
  },
  menu: {
    mudarDeConta: "החלפת חשבון",
    gerenciarContas: "ניהול חשבונות",
  },
  editor: {
    decoracao: "החלפת קישוט האווטאר",
    naoSalvo: "אל תשכח לשמור את השינויים!",
    principal: "הפרופיל הראשי",
  },
};
