export const servidor = {
  titulo: "הגדרות השרת",
  auditoria: {
    titulo: "יומן הפעולות",
    porUsuario: "סינון לפי אדם",
    porAcao: "סינון לפי פעולה",
    vazio: "עדיין לא נרשם דבר עם הסינון הזה.",
    motivo: "סיבה:",
  },
  banimentos: {
    titulo: "רשימת החסומים בשרת",
    descricao: "מי שכאן לא נכנס שוב, גם לא עם הזמנה חדשה. הסרת החסימה מחזירה את הגישה מיד.",
    procurar: "חיפוש חסימות לפי שם משתמש",
    vazioTitulo: "אין חסימות",
    vazio: "עדיין לא חסמת אף אחד… אבל אם וכשיהיה צורך, אל תהסס.",
    desbanir: "הסרת חסימה",
  },
  excluir: {
    tudoVai: "כל הערוצים, ההודעות וההזמנות של {{servidor}} יימחקו עבור {{membros}} החברים. אחר כך אף אחד לא יוכל לשחזר אותם.",
    digite: "הקלד {{servidor}} כדי לאשר",
    titulo: "מחיקת השרת",
    aviso: "אי אפשר לבטל את זה.",
  },
  emblemas: {
    titulo: "תגים",
    vazio: "עדיין אין תגים.",
    novo: "תג חדש",
  },
  convites: {
    titulo: "הזמנות",
    descricao: "כל קישורי ההזמנה הפעילים של השרת הזה.",
    vazio: "עדיין לא נוצרה שום הזמנה.",
    revogar: "ביטול ההזמנה",
  },
  integracoes: {
    titulo: "אינטגרציות",
    descricao: "וובהוק הוא כתובת שמפרסמת בערוץ בלי צורך בחשבון. שימושי כדי להודיע שבנייה עברה, שמישהו פתח פנייה, או כל מה שתרצה לשלוח מסקריפט.",
    novo: "וובהוק חדש",
    vazio: "עדיין אין וובהוקים. צור אחד והדבק את הכתובת במקום שממנו תרצה שההודעה תגיע.",
    canal: "ערוץ",
    apagar: "מחיקת הוובהוק",
    comoUsar: "איך משתמשים",
    comoUsarTexto: "שלח POST עם JSON. הפורמט זהה לזה של Discord, כך שסקריפט שכבר קיים עובד בלי שינוי:",
  },
  engajamento: {
    titulo: "מעורבות",
    descricao: "מה שהשרת עושה לבד כדי לא להיראות ריק כשמגיע מישהו חדש.",
    sistema: "הודעות מערכת",
    boasVindas: "שליחת הודעת ברוכים הבאים כשמישהו נכנס",
    sorteio: "בלי טקסט משלך למטה, המשפט נבחר בהגרלה — אותו אחד תמיד נמאס מהר.",
    canalDoSistema: "ערוץ הודעות המערכת",
    mensagem: "הודעת ברוכים הבאים",
    deixeVazio: "השאר ריק כדי להגריל מבין המשפטים המוכנים",
  },
  automod: {
    titulo: "מודרציה אוטומטית",
    descricao: "מסננים שמנהלים בעצמם, עוד לפני שההודעה קיימת. מי שמנהל את השרת לעולם לא מסונן — ותפקידים פטורים עוברים ישר.",
    palavras: {
      titulo: "חסימת מילים משלך",
      descricao: "הרשימה שלך של מילים שאף אחד לא יכול לכתוב.",
    },
    mencoes: {
      titulo: "חסימת ספאם אזכורים",
      descricao: "חוסם הודעה עם יותר מדי אזכורים בבת אחת.",
    },
    links: {
      titulo: "חסימת קישורים",
      descricao: "עוצר כל כתובת שמודבקת בצ׳אט.",
    },
    definir: "הגדרה",
    nomeDaRegra: "שם הכלל",
    bloqueadas: "מילים חסומות",
    digiteEnter: "הקלד ולחץ Enter",
    comparacao: "ההשוואה מתעלמת מאותיות גדולות, סימני ניקוד ופיסוק — ולא תופסת מילה בתוך מילה אחרת.",
    aPartirDe: "לחסום מכמה אזכורים",
    oQueFazer: "מה לעשות",
    canalDoAlerta: "ערוץ ההתראה",
    escolhaCanal: "בחר ערוץ",
    castigo: "השתקה (דקות)",
    isentos: "תפקידים פטורים",
    semCargos: "עדיין לא נוצרו תפקידים.",
    salvarRegra: "שמירת הכלל",
    apagar: "מחיקת הכלל",
    excluirTitulo: "למחוק את כלל המודרציה הזה?",
    excluirDescricao: "השרת מפסיק לסנן לפיו מיד. אפשר ליצור אותו מחדש, אבל ההגדרה הנוכחית תאבד.",
    excluirAcao: "מחיקת הכלל",
  },
  cargos: {
    titulo: "תפקידים",
    descricao: "תפקידים נותנים שם, צבע וסמכויות. מי שגבוה יותר ברשימה שולט בנמצאים מתחתיו — ואף אחד לא נוגע בתפקיד שווה לשלו או גבוה ממנו.",
    criar: "יצירת תפקיד",
    vazio: "עדיין אין תפקידים.",
    abaExibicao: "תצוגה",
    abaPermissoes: "הרשאות",
    abaMembros: "חברים — {{quantos}}",
    everyone: "חל על כולם בשרת. זה הבסיס שעליו נערמים שאר התפקידים.",
    nomeDoCargo: "שם התפקיד",
    cor: "צבע התפקיד",
    corDica: "צובע את שמו של בעל התפקיד ברשימת החברים ובצ׳אט.",
    semCor: "ללא צבע",
    corPersonalizada: "צבע מותאם",
    estilo: "סגנון השם",
    segundaCor: "צבע שני",
    segundaCorDica: "בלעדיו המעבר חוזר לצבע אחיד — הוא לא נעלם.",
    limparSegundaCor: "ניקוי הצבע השני",
    icone: "סמל",
    iconeDica: "מופיע ליד התפקיד בכרטיס הפרופיל של מי שיש לו אותו.",
    exibirSeparado: "הצגה בנפרד משאר החברים",
    exibirSeparadoDica: "התפקיד מקבל מדור משלו ברשימת החברים.",
    permitirMencionar: "לאפשר אזכור של התפקיד הזה",
    permitirMencionarDica: "כל אחד יוכל להתריע לכל מי שיש לו את התפקיד.",
    semPoderDeConceder: "{{descricao}} (אין לך את ההרשאה הזו כדי להעניק אותה)",
    adicionar: "הוספת מישהו לתפקיד הזה",
    tirar: "הסרת התפקיד",
    semNinguem: "עדיין לאף אחד אין את התפקיד הזה.",
    apagar: "מחיקת תפקיד",
    excluirTitulo: "למחוק את התפקיד \"{{nome}}\"?",
    excluirDescricao: "מי שיש לו את התפקיד מאבד כל מה שהוא העניק. אי אפשר לבטל.",
    excluirAcao: "מחיקת תפקיד",
  },
  membros: {
    procurar: "חיפוש לפי שם או שם משתמש",
    membroDesde: "חבר מאז",
    vazio: "לא נמצא אף אחד.",
    acoesPara: "פעולות עבור {{nome}}",
    deCastigo: "השתקה",
    tirarCastigo: "הסרת ההשתקה",
    castigo5min: "5 דקות",
    castigo1h: "שעה",
    castigo1d: "יום",
    castigo1s: "שבוע",
    expulsar: "העפה",
    expulsarTitulo: "להעיף את {{nome}}?",
    expulsarDescricao: "עוזב את {{servidor}} מיד. יכול לחזור עם הזמנה — העפה לא מונעת חזרה.",
    banir: "חסימה",
    banirTitulo: "לחסום את {{nome}}?",
    banirDescricao: "עוזב את {{servidor}} ולא יכול לחזור, גם לא עם הזמנה, עד שהחסימה תוסר.",
    motivo: "סיבה (לא חובה)",
    motivoDica: "נרשם ביומן הפעולות",
  },
  perfil: {
    titulo: "פרופיל השרת",
    descricao: "ככה השרת שלך מופיע ברשימה ובקישורי ההזמנה.",
    icone: "סמל",
    faixa: "באנר עליון",
    nomeDoServidor: "שם השרת",
    campoDescricao: "תיאור",
    doQueE: "על מה השרת הזה?",
    comprimido: "נדחס לפני ההעלאה: {{economia}}",
  },
  etiqueta: {
    titulo: "תג השרת",
    descricao: "תווית של עד 4 אותיות שמופיעה ליד שמו של כל חבר — בצ׳אט וברשימת האנשים. כאן זה בחינם: בלי בוסטים, בלי רמות.",
    escolhaNome: "בחר שם",
    limite: "עד 4 תווים, אותיות ומספרים.",
    escolhaInsignia: "בחר עיטור",
    voce: "אתה",
    fala1: "מישהו בעניין של משחק?",
    fala2: "תראה את התג שלי!",
    fala3: "ואו, איך השגת את זה",
  },
  expressoes: {
    comoUsar: "הוסף עד {{limite}} אימוג׳ים שכולם יכולים להשתמש בהם בשרת הזה. כתוב :שם: בצ׳אט כדי לשלוח.",
    imagem: "תמונה",
    enviadoPor: "הועלה על ידי",
    semEmoji: "עדיין אין אימוג׳ים.",
    figurinhas: "מדבקות",
    enviarFigurinha: "העלאת מדבקה",
    nomeDaFigurinha: "שם המדבקה",
    exemploFigurinha: "לדוגמה: חיבוק של גור חתולים",
    figurinhaGrande: "המדבקה עוברת את {{limite}}.",
    deixaPraLa: "עזוב",
    sons: "לוח צלילים",
    enviarSom: "העלאת צליל",
    nomeDoSom: "שם הצליל",
    semSom: "עדיין אין צלילים.",
    somGrande: "הצליל עובר את {{limite}}.",
    emojiRelacionado: "אימוג׳י קשור",
    ouvir: "האזנה",
    ouvirAssim: "להאזין ככה",
    volumeDe: "עוצמת {{nome}}",
    volumeDica: "חל על כולם בשרת. כל אחד עדיין יכול להנמיך את הצלילים רק לעצמו, בלוח השיחה.",
    falhaEnvio: "לא הצלחנו להעלות את הקובץ.",
    excluirTitulo: "למחוק {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "נעלם מהשרת לכולם. ההודעות שכבר השתמשו בו נשארות כמו שהן.",
  },
  canal: {
    visaoGeral: "סקירה",
    nome: "שם הערוץ",
    topico: "נושא הערוץ",
    topicoDica: "על מה מדברים כאן?",
    modoLento: "כל אחד שולח רק הודעה אחת לכל מרווח. מי שמנהל הודעות או ערוצים עובר ישר.",
    visibilidade: "נראות התוכן",
    padrao: "ברירת מחדל",
    padraoDica: "התוכן של הערוץ תמיד גלוי.",
    spoiler: "ערוץ ספוילרים",
    spoilerDica: "סמן את הערוץ הזה כמכיל ספוילרים, כדי שתפניות עלילה ונושאים כבדים יישארו מוסתרים עד שמישהו יבחר להסתכל.",
    idade: "ערוץ עם הגבלת גיל",
    idadeDica: "מי שנכנס צריך לאשר שהוא בגיר כדי לראות את התוכן.",
    bitrateDica: "מעל 64 kbps עלול להפריע למי שיש לו חיבור גרוע.",
    qualidadeDeVideo: "איכות הווידאו",
    automatica: "אוטומטית",
    limite: "מגבלת משתמשים — {{valor}}",
    pessoas: "{{quantos}} אנשים",
    semLimite: "ללא מגבלה",
    permissoesDescricao: "כאן אתה משנה מה תקף בערוץ הזה. מה שנשאר על ״ירושה״ ממשיך לעקוב אחרי התפקיד.",
    excluir: {
      titulo: "מחיקת ערוץ",
      historico: "כל ההיסטוריה של {{canal}} הולכת איתו, לכולם.",
      digite: "הקלד {{canal}} כדי לאשר",
    },
  },
  moderacao: {
    titulo: "תצוגת מנחה",
    semPermissao: "אתה צריך את ההרשאה ״ניהול חברים״ כדי לראות את זה.",
    fecharEsc: "סגירה (Esc)",
    atividade: "פעילות בשרת",
    mensagens: "הודעות",
    links: "קישורים",
    midia: "מדיה",
    acoesNaAuditoria: "פעולות ביומן",
    moderacoesSofridas: "אמצעים שננקטו",
    permissoes: "הרשאות ({{quantas}})",
    semPermissaoEspecial: "אין הרשאות מיוחדות.",
    conta: "חשבון",
    entrouNoServidor: "הצטרף לשרת",
    contaCriadaEm: "החשבון נוצר ב",
    deCastigoAte: "מושתק עד",
    formaDeAdesao: "איך הצטרף",
    mensagem: "הודעה",
    castigo: "השתקה",
    copiarId: "העתקת מזהה",
    idCopiado: "המזהה הועתק.",
    adicionarCargo: "הוספת תפקיד",
    semCargos: "לא נוצר אף תפקיד",
    soEveryone: "רק @everyone.",
    voltar: "חזרה",
    vazio: "אין כאן כלום.",
    cinquenta: "מוצגות 50 האחרונות.",
    irParaMensagem: "מעבר להודעה",
    precisaSerAmigo: "אתם צריכים להיות חברים כדי לדבר.",
    expulsarDescricao: "עוזב את השרת מיד, אבל יכול לחזור עם הזמנה.",
    banirDescricao: "עוזב את השרת ולא יכול לחזור, גם לא עם הזמנה, עד שהחסימה תוסר.",
    castigarTitulo: "להשתיק את {{nome}}?",
    castigoDescricao: "כל עוד זה נמשך, הוא לא כותב ולא מדבר באף ערוץ בשרת.",
    aplicarCastigo: "החלת ההשתקה",
    duracao: "משך בדקות",
    informeDuracao: "ציין את המשך בדקות.",
  },
};
