export const amizades = {
  ativosAgora: "Aktiva nu",
  procurando: "Kollar vilka som är här…",
  tudoTranquilo: "Det är lugnt just nu…",
  tudoTranquiloDetalhe: "När du eller en vän går med i ett samtal dyker det upp här — och du hoppar in med ett klick.",
  emVoz: "I röstkanal",
  voce: "Du",
  soVoce: "Bara du",
  pessoas: "{{quantas}} personer",
  voltarParaChamada: "Tillbaka till samtalet",
  entrarNaChamada: "Gå med i samtalet",
  abrirCanal: "Öppna {{canal}} på {{servidor}}",
  mensagensDiretas: "Direktmeddelanden",
  encontreConversa: "Hitta en konversation",
  amigos: "Vänner",
  conversas: "Konversationer",
  semConversas: "Inga konversationer än. Lägg till en vän för att komma igång.",
  semConversaComEsseNome: "Ingen konversation med det namnet.",
  abrirMenu: "Öppna servrar och konversationer",
  solicitacoes: "Meddelandeförfrågningar",
  pedidos: "Förfrågningar",
  spam: "Skräppost",
  pedidosPendentes: "Väntande förfrågningar",
  marcadosComoSpam: "Markerade som skräppost",
  aceitar: "Acceptera",
  ignorar: "Ignorera",
  marcarSpam: "Markera som skräppost",
  semPedidos: "Inga förfrågningar väntar.",
  semPedidosDetalhe: "Den som inte är din vän men delar en server med dig hamnar här innan det når dina konversationer.",
  semSpam: "Inget markerat som skräppost.",
  semSpamDetalhe: "Det skräppostfiltret sorterar bort, eller det du markerar själv, stannar i den här fliken.",
  umServidorEmComum: "1 gemensam server",
  servidoresEmComum: "{{quantos}} gemensamma servrar",
  semServidoresEmComum: "Inga gemensamma servrar",
};
