export const chamada = {
  conectando: "Ansluter till samtalet…",
  naoEntrou: "Det gick inte att gå med i samtalet",
  sair: "Lämna samtalet",
  sairDaVoz: "Lämna röstsamtalet",
  desconectar: "Koppla från",
  voltar: "Tillbaka till samtalet",
  voltarAosQuadros: "Tillbaka till samtalsrutorna",
  fecharChat: "Stäng chatten",
  carregandoPrevia: "Läser in förhandsvisningen…",
  maisOpcoes: "Fler alternativ",
  deVideo: "Videosamtal",
  deVoz: "Röstsamtal",
  alguem: "Någon",
  volume: {
    entrada: "Ingångsvolym",
    saida: "Utgångsvolym",
    live: "Sändningens volym",
    liveComPorcento: "Sändningens volym ({{porcento}} %)",
    liveSemSom: "Sändning utan ljud",
  },
  aparelhos: {
    entrada: "Ingångsenhet",
    saida: "Utgångsenhet",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Utgång",
    oDoSistema: "Systemets",
    aDoSistema: "Systemets",
    semEscolhaDeSaida: "Den här webbläsaren låter dig inte välja utgång — systemet bestämmer.",
    espelhar: "Spegla min kamera",
    configEntrada: "Ingångsinställningar",
    configSaida: "Utgångsinställningar",
    configCamera: "Kamerainställningar",
    configAudioEVideo: "Ljud- och videoinställningar",
  },
  tela: {
    compartilhar: "Dela skärm",
    compartilharAcao: "Dela",
    cancelar: "Avbryt",
    telas: "Skärmar",
    janelas: "Fönster",
    somDoComputador: "Ta med datorns ljud",
    somDoSistema: "Ta med systemets ljud",
    configCompartilhamento: "Delningsinställningar",
    mostrarSemVideo: "Visa de som är utan video",
    semFontes: "Systemet returnerade ingen skärm eller något fönster att dela.",
    pararDeCompartilhar: "Sluta dela",
    encerrarTransmissao: "Avsluta sändningen",
  },
  live: {
    etiqueta: "Live",
    etiquetaMaiuscula: "LIVE",
    assistir: "Titta på sändningen",
    assistirPessoa: "Titta på {{nome}}",
    pararDeAssistir: "Sluta titta",
  },
  membro: {
    mudarMeuApelido: "Byt mitt smeknamn",
    meuMicrofone: "Min mikrofon",
    ouvirChamada: "Lyssna på samtalet",
    copiarMeuId: "Kopiera mitt ID",
    idCopiado: "ID kopierat.",
    mensagem: "Meddelande",
    silenciar: "Tysta",
    alterarApelido: "Byt smeknamn",
    cargos: "Roller",
    semCargo: "Ingen roll skapad",
    moverPara: "Flytta till",
    silenciarNoServidor: "Tysta rösten på servern",
    desativarAudioNoServidor: "Stäng av ljudet på servern",
    desconectar: "Koppla från",
    apelidoTitulo: "Ditt smeknamn på den här servern",
    apelidoDeAlguem: "Smeknamn för {{nome}}",
    apelidoCampo: "Smeknamn",
    apelidoDicaPropria: "Gäller bara här. Lämna tomt för att gå tillbaka till ditt vanliga namn.",
    apelidoDicaDeOutro: "Gäller bara på den här servern. Lämna tomt för att gå tillbaka till originalnamnet.",
  },
  detalhes: {
    abrir: "Röstdetaljer",
    titulo: "Röstdetaljer",
    conexao: "Anslutning",
    pingMedio: "Genomsnittlig ping",
    ultimoPing: "Senaste ping",
    perda: "Förlust av skickade paket",
    medindo: "Mäter…",
    criptografado: "Krypterat fram till servern (DTLS-SRTP)",
    explicacao: "Över 250 ms märks fördröjningen i samtalet — folk börjar prata i mun på varandra. Paketförlust över 10 % gör rösten robotaktig. I båda fallen sitter problemet nästan alltid mellan dig och internet: prova kabel i stället för wifi, eller starta om routern.",
  },
  microfone: {
    bloqueado: "Mikrofonen är blockerad — du bara lyssnar. Ge åtkomst i webbläsarens behörigheter.",
    bloqueadoNoMac: "macOS blockerar mikrofonen. Kryssa i",
    caminhoNoMac: "Systeminställningar → Integritet och säkerhet → Mikrofon",
    abrirAjustes: "Öppna inställningarna",
    vaiReabrir: "macOS kommer att be dig öppna appen igen.",
    naoAbriu: "Det gick inte att öppna mikrofonen — du bara lyssnar. Kontrollera enheten under Inställningar → Röst och video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS har inte tillåtit skärminspelning än. Utan det blir delningen svart.",
    marque: "Kryssa i",
    reabra: "under Skärminspelning och öppna appen igen.",
    jaMarcado: "Om det redan är ikryssat har behörigheten blivit inaktuell vid senaste uppdateringen: kryssa ur, kryssa i igen och öppna appen på nytt.",
  },
  ruido: {
    titulo: "Brusreducering",
    explicacao: "Ta bort bakgrundsljudet ur din röst. Prova att klappa händerna eller dra tangentbordet medan du pratar — de i samtalet hör bara dig.",
    semSuporte: "Den här webbläsaren kör inte den avancerade reduceringen. Webbläsarens egen gäller fortfarande, och den är svagare.",
    aplicando: "Tillämpar på samtalet…",
    faleParaTestar: "Prata för att testa",
    verdeQuandoPassa: "Grönt när din röst går fram.",
    teOuvindo: "De hör dig just nu.",
    feitoCom: "Gjord med",
    aquiNoAparelho: ", här på din egen enhet",
    ajustes: "Inställningar",
  },
  permissoes: {
    titulo: "macOS-behörigheter",
    detalhe: "macOS frågar bara en gång, och sedan ändras det bara i dess egen panel. Här ser du vad som gäller och löser det som saknas.",
    concedida: "Beviljad",
    negada: "Nekad",
    naoPedida: "Inte begärd",
    permitir: "Tillåt",
    abrirAjustes: "Öppna inställningar",
    microfone: "Mikrofon",
    microfoneDetalhe: "Prata i samtal och testa din ingång.",
    camera: "Kamera",
    cameraDetalhe: "Slå på videon i samtalet.",
    tela: "Skärminspelning",
    telaDetalhe: "Dela skärmen och fönstren.",
    monitoramento: "Ingångsövervakning",
    monitoramentoDetalhe: "Använda tryck-för-att-prata även med Gravaê i bakgrunden.",
  },
  jaConectado: {
    titulo: "Du är redan i det här samtalet",
    trazer: "Hämta hit samtalet",
    deixar: "Låt det vara",
    detalhe: "Om du hämtar hit det åker andra änden ur samtalet — ditt konto är på ett ställe i taget.",
  },
};
