export const comum = {
  carregando: "Läser in…",
  salvar: "Spara",
  salvando: "Sparar…",
  descartar: "Släng",
  redefinir: "Återställ",
  naoSalvo: "Du har osparade ändringar.",
  fechar: "Stäng",
  criar: "Skapa",
  nome: "Namn",
  emoji: "Emoji",
  previa: "Förhandsvisning",
  cancelar: "Avbryt",
  enviar: "Skicka",
  apagar: "Radera",
  excluir: "Radera",
  remover: "Ta bort",
  trocar: "Byt",
};
