export const configuracoes = {
  efeitos: {
    titulo: "Effekter för pekaren",
    detalhe: "Ett spår och gnistor ritade ovanpå appen. De börjar avstängda och slår av sig själva om du bad om mindre rörelse.",
    rastro: "Pekarens spår",
    rastroDetalhe: "En linje som följer pekaren och bleknar bakom.",
    faisca: "Gnista vid klick",
    faiscaDetalhe: "Korta streck som far ut från där du klickade.",
    cor: "Färg",
    espessura: "Tjocklek",
    comprimento: "Längd",
    tamanho: "Storlek",
    quantidade: "Antal",
  },
  email: {
    verificarTitulo: "Bekräfta din e-post",
    verificarDetalhe: "En del gemenskaper låter bara de bekräftade skriva. Det tar ett klick.",
    enviar: "Skicka länken",
    enviado: "Titta i inkorgen. Länken håller ett dygn.",
    falhou: "E-posten gick inte att skicka.",
    confirmado: "E-posten är bekräftad",
    confirmadoDetalhe: "Klart. Nu skriver du i varje gemenskap som kräver det.",
    linkIncompleto: "Ofullständig länk",
    linkIncompletoDetalhe: "Koden saknas i adressen. Öppna länken direkt från e-posten.",
    confirmando: "Bekräftar…",
    expirou: "Den här länken är redan använd eller har gått ut.",
    irParaOApp: "Till appen",
  },
  tema: {
    indisponivel: "Temat är inte tillgängligt",
    indisponivelDetalhe: "Den som publicerade det har tagit bort det, eller så är länken fel.",
    indisponivelLinha: "Temat är inte tillgängligt. Den som publicerade det har tagit bort det, eller så är länken fel.",
    importar: "Importera tema",
    importarCurto: "Importera",
    importarDetalhe: "Det här ersätter temat du har nu. Du kan redigera det efteråt i Inställningar > Utseende > Temastudio.",
    porAutor: "av {{autor}}",
    umaCorTrocada: "1 färg utbytt",
    coresTrocadas: "{{quantas}} färger utbytta",
    avisoDeCss: "Det här temat bär med sig CSS från den som skrev det, och CSS når varje hörn av skärmen. Importera bara från folk du litar på.",
    soCores: "Det här temat byter bara färger. Ingen CSS utifrån.",
    aplicar: "Använd",
    previaSemMotor: "Förhandsvisningen kör inte motorn. Installera för att se den.",
    motorAnimado: "{{motor}} animerad",
  },
  sair: "Logga ut",
  versoes: {
    termos: "Användarvillkor",
    privacidade: "Integritetspolicy",
    copiar: "Klicka för att kopiera",
    copiado: "Kopierat",
  },
  telas: {
    conta: "Mitt konto",
    privacidade: "Integritet",
    conexoes: "Anslutningar",
    voz: "Ljud",
    video: "Video",
    avisos: "Aviseringar",
    aplicativos: "Applikationer",
    aparencia: "Utseende",
    batePapo: "Chatt",
    acessibilidade: "Tillgänglighet",
    idioma: "Språk",
    aplicativo: "Ladda ner appen",
    atalhos: "Kortkommandon",
    desktop: "Skrivbordsapp",
    avancado: "Avancerat",
    servidor: "Server",
    comunicado: "Systemmeddelande",
    denuncias: "Rapporter",
    publicacoes: "Distributioner",
  },
  grupos: {
    conta: "Konto",
    app: "Appinställningar",
    desenvolvedor: "Utvecklare",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Inloggningsuppgifter",
    dispositivos: "Enheter",
    usuariosBloqueados: "Blockerade användare",
    aplicativosAutorizados: "Auktoriserade appar",
    sessoes: "Sessioner",
    amigosEDms: "Vänner och direktmeddelanden",
    compartilhamentoDeAtividade: "Aktivitetsdelning",
    visibilidadeDoPerfil: "Profilens synlighet",
    exportarDados: "Exportera data",
    exclusaoDeDados: "Radera data",
    tema: "Tema",
    corDeDestaque: "Accentfärg",
    interface: "Gränssnitt",
    listaDeCanais: "Kanallista",
    zoomDoApp: "Appens zoomnivå",
    escalaDaFonte: "Teckenstorlek i chatten",
    modoStreamer: "Integritet vid strömning",
    cursores: "Markörer",
    movimento: "Rörelse",
    textoEmVoz: "Text till tal",
    teclado: "Tangentbord",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Gränssnittets språk",
    dispositivosDeVoz: "Enheter",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inmatningsläge",
    sensibilidade: "Inmatningskänslighet",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Sändning",
    exibicao: "Visning",
    entrada: "Inmatning",
    midia: "Media",
    geral: "Allmänt",
    preferenciaDeMencao: "Omnämnandeinställning",
    sons: "Ljud",
  },
};
