export const configuracoes = {
  sair: "Logga ut",
  versoes: {
    copiar: "Klicka för att kopiera",
    copiado: "Kopierat",
  },
  telas: {
    conta: "Mitt konto",
    privacidade: "Integritet",
    conexoes: "Anslutningar",
    voz: "Ljud",
    video: "Video",
    avisos: "Aviseringar",
    aplicativos: "Applikationer",
    aparencia: "Utseende",
    batePapo: "Chatt",
    acessibilidade: "Tillgänglighet",
    idioma: "Språk",
    aplicativo: "Ladda ner appen",
    atalhos: "Kortkommandon",
    avancado: "Avancerat",
    servidor: "Server",
  },
  grupos: {
    conta: "Konto",
    app: "Appinställningar",
    desenvolvedor: "Utvecklare",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Inloggningsuppgifter",
    dispositivos: "Enheter",
    usuariosBloqueados: "Blockerade användare",
    aplicativosAutorizados: "Auktoriserade appar",
    sessoes: "Sessioner",
    amigosEDms: "Vänner och direktmeddelanden",
    compartilhamentoDeAtividade: "Aktivitetsdelning",
    visibilidadeDoPerfil: "Profilens synlighet",
    exportarDados: "Exportera data",
    exclusaoDeDados: "Radera data",
    tema: "Tema",
    corDeDestaque: "Accentfärg",
    interface: "Gränssnitt",
    listaDeCanais: "Kanallista",
    zoomDoApp: "Appens zoomnivå",
    escalaDaFonte: "Teckenstorlek i chatten",
    modoStreamer: "Integritet vid strömning",
    movimento: "Rörelse",
    textoEmVoz: "Text till tal",
    teclado: "Tangentbord",
    formatoDaHora: "Tidsformat",
    idiomaDaInterface: "Gränssnittets språk",
    dispositivosDeVoz: "Enheter",
    testeDoMicrofone: "Mikrofontest",
    modoDeEntrada: "Inmatningsläge",
    sensibilidade: "Inmatningskänslighet",
    qualidade: "Kvalitet",
    camera: "Kamera",
    transmissao: "Sändning",
    exibicao: "Visning",
    entrada: "Inmatning",
    midia: "Media",
    geral: "Allmänt",
    preferenciaDeMencao: "Omnämnandeinställning",
    sons: "Ljud",
  },
};
