export const conversa = {
  lista: {
    carregando: "Läser in meddelanden…",
    carregandoMais: "Läser in…",
    verMais: "Skrolla uppåt för att se mer",
    semHistorico: "Historiken är inte tillgänglig",
    semHistoricoDetalhe: "Din roll har inte behörighet att läsa historiken i #{{canal}}. Nya meddelanden fortsätter att dyka upp så länge du är här.",
    boasVindas: "Välkommen till #{{canal}}",
    boasVindasDetalhe: "Det här är början på kanalen #{{canal}}.",
  },
  data: {
    hoje: "I dag",
    ontem: "I går",
    hojeAs: "i dag kl. {{hora}}",
    ontemAs: "i går kl. {{hora}}",
  },
  digitando: {
    um: "{{nome}} skriver…",
    dois: "{{primeiro}} och {{segundo}} skriver…",
    varios: "{{quantidade}} personer skriver…",
  },
  mensagem: {
    usou: "använde",
    fixada: "fäst",
    editado: "(redigerat)",
    ignorada: "Meddelande från någon du ignorerar.",
    mostrar: "Visa",
    escPara: "Esc för att",
    cancelar: "avbryta",
    enterParaSalvar: "Enter för att spara",
    falhou: "Det skickades inte. Försök igen",
    naoLidasDaqui: "Olästa härifrån.",
    linkCopiado: "Länken kopierades.",
    idCopiado: "ID kopierades.",
    naoDeuParaCopiar: "Din webbläsare tillät inte kopiering.",
    apagarTitulo: "Radera meddelandet?",
    apagarDescricao: "Det försvinner för alla i kanalen. Det går inte att få tillbaka.",
    apagarAcao: "Radera",
    citacaoAnexo: "klicka för att se bilagan",
    citacaoSumiu: "Ursprungsmeddelandet finns inte kvar.",
    reagirCom: "Reagera med {{emoji}} — håll ned för superreaktion",
    segureParaSuper: "{{emoji}} — håll ned för superreaktion",
  },
  acoes: {
    reagir: "Reagera",
    responder: "Svara",
    encaminhar: "Vidarebefordra",
    favoritar: "Spara meddelandet",
    tirarDosFavoritos: "Ta bort från sparade",
    marcarNaoLida: "Markera som oläst",
    copiarLink: "Kopiera länken till meddelandet",
    copiarId: "Kopiera meddelandets ID",
    fixar: "Fäst meddelandet",
    desafixar: "Lossa",
    editar: "Redigera",
    apagar: "Radera",
    mais: "Mer",
    adicionarReacao: "Lägg till reaktion",
    superReagirCom: "Superreagera med {{emoji}}",
    fixarMensagem: "Fäst meddelandet",
    desafixarMensagem: "Lossa meddelandet",
    editarMensagem: "Redigera meddelandet",
    apagarMensagem: "Radera meddelandet",
  },
  mencao: {
    cargo: "Rollomnämnande",
    pessoa: "Omnämnande",
    alguem: "någon",
    cargoSemNome: "roll",
    here: "Meddelar alla som är online",
    everyone: "Meddelar hela servern",
  },
  codigo: {
    copiar: "Kopiera",
    copiado: "Kopierat",
    copiarAria: "Kopiera koden",
    copiadoAria: "Koden kopierades",
    recolher: "Fäll ihop",
    expandir: "Expandera",
    verInteiro: "Visa hela filen",
    maisOpcoes: "Fler alternativ",
    baixar: "Ladda ner",
  },
  caixa: {
    escrever: "Skriv i #{{canal}}",
    escreverSemCanal: "Skriv ett meddelande",
    semPermissao: "Du har inte behörighet att skicka meddelanden i den här kanalen",
    solteParaAnexar: "Släpp för att bifoga",
    respondendoPara: "Svar till",
    vaiNotificar: "Personen får en avisering",
    naoVaiNotificar: "Personen får ingen avisering",
    ligado: "på",
    desligado: "av",
    pararDeResponder: "Sluta svara",
    mais: "Mer",
    enviarArquivo: "Skicka en fil",
    criarEnquete: "Skapa en omröstning",
    expressoes: "Emoji, GIF och dekaler",
    enviar: "Skicka",
    aguardandoEnvio: "Väntar på uppladdningen",
    modoLento: "Långsamt läge på ({{tempo}})",
    modoLentoDica: "Det långsamma läget är satt till {{segundos}} s. Vänta innan du skickar nästa meddelande.",
  },
  anexos: {
    enviando: "Laddar upp…",
    modificar: "Ändra {{arquivo}}",
    remover: "Ta bort {{arquivo}}",
    ver: "Visa {{arquivo}}",
    mostrarSpoiler: "Visa spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Redigera bilagan",
    nomeDoArquivo: "Filnamn",
    descricao: "Beskrivning av alternativtexten",
    descricaoDica: "Beskriv det här mediet för skärmläsare",
    marcarSpoiler: "Markera som spoiler",
    cancelar: "Avbryt",
    salvar: "Spara",
  },
  cartao: {
    tocador: "Spelare",
    abrir: "Öppna {{destino}}",
    tocar: "Spela {{titulo}}",
    video: "video",
    verImagem: "Visa bilden",
  },
  enquete: {
    titulo: "Omröstning",
    encerrada: "Omröstningen är stängd",
    variasRespostas: "Omröstning — flera svar",
    umVoto: "{{quantidade}} röst",
    votos: "{{quantidade}} röster",
    umVotoNoTotal: "{{quantidade}} röst totalt",
    votosNoTotal: "{{quantidade}} röster totalt",
    encerraEm: "stänger {{quando}}",
    encerrarAgora: "Stäng nu",
  },
  fixadas: {
    titulo: "Fästa meddelanden",
    vazio: "Den här kanalen har inga fästa meddelanden… än.",
    desafixar: "Lossa",
    anexo: "(bilaga)",
    enquete: "(omröstning)",
    dicaRotulo: "TIPS:",
    dica: "den som har behörigheten ”Hantera meddelanden” kan fästa direkt från meddelandemenyn.",
  },
  encaminhar: {
    titulo: "Vidarebefordra meddelandet",
    paraOnde: "Vart?",
    semTexto: "(meddelande utan text)",
    nenhumLugar: "Ingen plats med det namnet.",
    canais: "Kanaler",
    conversas: "Direktmeddelanden",
  },
  expressoes: {
    gifs: "Gifar",
    buscarGifs: "Sök på Klipy",
    figurinha: "Dekal",
    buscarFigurinha: "Hitta den perfekta dekalen",
    buscarEmoji: "Hitta den perfekta emojin",
    buscarReacao: "Hitta den perfekta reaktionen",
    adicionarEmoji: "Lägg till emoji",
    limparBusca: "Rensa sökningen",
  },
  busca: {
    fechar: "Stäng sökningen",
    procurando: "Söker…",
    resultado: "{{quantos}} träff",
    resultados: "{{quantos}} träffar",
    nadaCom: "Inget med {{termo}} här.",
    soOsQuePodeLer: "Sökningen tittar bara i kanaler du får läsa.",
  },
  entrada: {
    titulo: "Inkorg",
    naoLidas: "Olästa",
    salvas: "Sparade",
    mencoes: "Omnämnanden",
    fimTitulo: "Du har kommit till slutet",
    fimDetalhe: "Det finns inget kvar att läsa. När ett nytt meddelande kommer dyker det upp här.",
    semSalvosTitulo: "Inget sparat",
    semSalvosDetalhe: "Håll ned Skift och klicka på ett meddelandes bokmärke för att spara det och läsa senare.",
    tirarDosSalvos: "Ta bort från sparade",
    semMencoesTitulo: "Inga omnämnanden än",
    semMencoesDetalhe: "Omnämnanden av dig dyker upp här för de senaste 7 dagarna.",
  },
  forum: {
    descricao: "Varje ämne blir ett eget samtal — bra för frågan som inte får försvinna mitt i snacket.",
    novoAssunto: "Nytt ämne",
    vazio: "Inga ämnen än. Starta det första så håller sig samtalet ordnat från början.",
    titulo: "Titel",
    doQueSeTrata: "Vad handlar det om?",
    primeiraMensagem: "Första meddelandet",
    conteDoCaso: "Berätta",
  },
};
