export const perfil = {
  carregando: "Läser in…",
  editar: "Redigera profilen",
  mensagem: "Meddelande",
  abrirConversa: "Öppna samtalet",
  verCompleto: "Se hela profilen",
  convidarParaServidor: "Bjud in till servern",
  semServidores: "Du har inga servrar",
  conviteEnviado: "Inbjudan skickad till {{nome}}.",
  moderador: "Öppna i moderatorvyn",
  mais: "Mer",
  ignorar: "Ignorera",
  deixarDeIgnorar: "Sluta ignorera",
  copiarId: "Kopiera användar-ID",
  idCopiado: "ID kopierat.",
  conexoes: "Anslutningar",
  membroDesde: "Medlem sedan",
  sobre: "Om",
  cargosTitulo: "Roller",
  visaoGeral: "Översikt",
  amigosEmComum: "Gemensamma vänner ({{quantidade}})",
  servidoresEmComum: "Gemensamma servrar ({{quantidade}})",
  amizade: {
    amigo: "Vän",
    pedidoEnviado: "Vänförfrågan skickad",
    respondaAbaixo: "Skickade dig en förfrågan — svara nedan",
    adicionar: "Lägg till vän",
    teMandouPedido: "Skickade dig en vänförfrågan",
    aceitar: "Acceptera",
    desfazer: "Ta bort vän",
    desfazerTitulo: "Ta bort {{nome}} från dina vänner?",
    desfazerDescricao: "Ni är inte längre vänner. Det privata samtalet finns kvar i historiken, och du kan lägga till personen igen senare.",
    bloquear: "Blockera",
    bloquearTitulo: "Blockera {{nome}}?",
    bloquearDescricao: "Ni är inte längre vänner, det privata samtalet tar inte emot fler meddelanden och personen kan inte skicka dig en vänförfrågan igen.",
    linkCopiado: "Ni är inte vänner — länken kopierades så att du kan skicka den.",
  },
  recado: {
    escrever: "Skriv till @{{usuario}}",
    enviar: "Skicka",
    enviada: "Meddelandet skickades",
    falhou: "Det gick inte att skicka. Försök från samtalet.",
  },
  cartao: {
    trocarFaixa: "Byt kortets banderoll",
    trocarFaixaCurto: "Byt banderoll",
    trocarFoto: "Byt profilbild",
    trocarFotoCurto: "Byt bild",
    suaEtiqueta: "Din etikett",
    editarEtiqueta: "Klicka för att redigera din etikett",
    conteAlgo: "Berätta något om dig själv",
    adicionarStatus: "Lägg till en status",
    adicionarDescricao: "Klicka för att lägga till en beskrivning",
    cargo: "Roll",
    cargos: "Roller",
    cargosCom: "Roller — {{quantidade}}",
    tirarCargo: "Ta bort rollen {{cargo}}",
  },
  cargos: {
    adicionar: "Lägg till roll",
    procurar: "Sök efter en roll",
  },
  etiqueta: {
    escolher: "Välj serveretikett",
    nenhuma: "Ingen serveretikett",
    semEtiqueta: "Ingen av dina servrar har en etikett",
  },
  emblemas: {
    doServidor: "Märken från den här servern",
    limite: "Du kan bära upp till {{quantidade}} märken.",
  },
  nota: {
    vazia: "Klicka för att anteckna något",
    rotulo: "Anteckning (bara du ser den)",
    adicionar: "Lägg till anteckning (bara du ser den)",
  },
  status: {
    titulo: "Status",
    definir: "Ange din status",
    escolherEmoji: "Välj emoji",
    tirarEmoji: "Ta bort emojin",
    oQuePensa: "Vad tänker du på?",
    limparAgora: "Rensa statusen nu",
    naoLimpar: "Rensa inte",
    limpar30m: "Rensa om 30 minuter",
    limpar1h: "Rensa om 1 timme",
    limpar4h: "Rensa om 4 timmar",
    limparHoje: "Rensa idag",
    limparAmanha: "Rensa imorgon",
    comHora: "{{prazo}} kl. {{hora}}",
  },
  presenca: {
    disponivel: "Tillgänglig",
    ausente: "Frånvarande",
    naoPerturbar: "Stör ej",
    naoPerturbarDetalhe: "Du får ingen avisering om nya meddelanden",
    invisivel: "Osynlig",
    invisivelDetalhe: "För andra ser du offline ut",
  },
  menu: {
    mudarDeConta: "Byt konto",
    gerenciarContas: "Hantera konton",
  },
  editor: {
    decoracao: "Byt avatardekoration",
    naoSalvo: "Glöm inte att spara dina ändringar!",
    principal: "Huvudprofil",
  },
};
