export const servidor = {
  comunidade: {
    ativa: "Gemenskapen är öppen",
    ativaDesde: "Öppen sedan {{quando}}",
    membrosAgora: "{{quantos}} medlemmar",
    criarParaMim: "Skapa en åt mig",
    canalDeRegras: "Regelkanal",
    canalDeRegrasDetalhe: "Platsen där reglerna ligger, de som alla läser innan de säger något.",
    canalDeAvisos: "Kanal för meddelanden till gemenskapen",
    canalDeAvisosDetalhe: "Dit skickar vi det som ändras här, bara till dem som styr.",
    canalDeSeguranca: "Kanal för säkerhetsvarningar",
    canalDeSegurancaDetalhe: "Där får moderationen det som filtren fångat.",
    idiomaPrincipal: "Huvudspråk",
    idiomaPrincipalDetalhe: "Språket som det mesta av snacket sker på.",
    semIdioma: "Inget språk valt",
    semCanal: "Ingen kanal",
    finalTitulo: "Nästan klart",
    finalDetalhe: "Titta på vad som ändras för dem som kommer, innan du öppnar.",
    confereRegras: "Den som kommer in ser regelkanalen först av allt.",
    confereEveryone: "Bara de med en roll använder @everyone och @here.",
    confereMencoes: "Att nämna alla på en gång kräver nu behörighet.",
    concordo: "Jag godkänner och förstår",
    concordoDetalhe: "Du intygar att gemenskapen följer våra riktlinjer.",
    proximo: "Vidare",
    terminar: "Avsluta uppsättningen",
    visaoGeral: "Överblick",
    visaoGeralDetalhe: "Kanalerna som gemenskapen talar till nykomlingar genom.",
    seguranca: "Säkerhet",
    segurancaDetalhe: "Bromsarna som håller tillbaka skräp och tungt innehåll.",
    habilitada: "Gemenskapen är påslagen.",
    falhou: "Gemenskapen gick inte att slå på.",
    titulo: "Gemenskap",
    ilustracao: "Pratbubblor",
    convite: "Bygger du en gemenskap?",
    conviteDetalhe: "Gör den till en gemenskap och få verktygen för ett stort ställe: regelkanal, meddelanden från oss och filter som sköter sig själva.",
    contagem: "{{membros}} av {{minimo}} medlemmar",
    faltam: "Det fattas {{quantos}} innan den kan öppna.",
    prontoParaAbrir: "Den kan öppna nu.",
    habilitar: "Slå på gemenskap",
    vantagemCrescer: "Växa",
    vantagemCrescerDetalhe: "Gemenskapen kan söka till Utforska, så de som letar efter ämnet hittar er.",
    vantagemModerar: "Moderera",
    vantagemModerarDetalhe: "Kräv verifierad e-post, filtrera media och slå på AutoMod på en gång.",
    vantagemAvisos: "Hålla koll",
    vantagemAvisosDetalhe: "Vi skickar det som ändras till dem som styr stället, i en kanal bara för er.",
    assistenteTitulo: "Låt oss sätta upp din gemenskap.",
    passoSeguranca: "Säkerhetskontroller",
    passoBasico: "Grundinställningar",
    passoFinal: "Sista handen",
    seguraTitulo: "Håll gemenskapen trygg",
    seguraDetalhe: "En stor gemenskap drar till sig skräp. De här två bromsarna är på från start, och du kan slå av dem sedan.",
    emailVerificado: "Kräv verifierad e-post",
    emailVerificadoDetalhe: "Den som inte bekräftat sin e-post skriver inte. Den med en roll går rakt igenom.",
    filtroDeMidia: "Filtrera explicit media",
    filtroDeMidiaDetalhe: "Bilder och videor kommer in dolda och visas först när någon väljer att titta.",
    basicoTitulo: "Gör i ordning grunden",
    basicoDetalhe: "Säg i vilken kanal reglerna står och vart våra meddelanden ska. Utan vald kanal skapar jag båda.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} kommandon",
    previa: "Så ser kortet ut",
    trocarIcone: "Byt ikonen",
    tirarCapa: "Ta bort omslaget",
    heroComunidades: "Någon pratar just nu om det du gillar",
    heroComunidadesDetalhe: "Gemenskaper öppnade av folk härifrån. Kliv in, läs snacket, och stanna om du gillar det.",
    emDestaque: "I fokus",
    todasAsComunidades: "De övriga",
    heroTitulo: "Vad ska gänget använda i dag?",
    heroDetalhe: "Bottar för musik, spel och moderering, byggda av folk som är här de med. Välj en, så kliver den in på din server.",
    novidades: "Nyss anlända",
    todosOsApps: "De övriga",
    lojaTitulo: "Appens sida",
    lojaDetalhe: "Det här ser den i Utforska som inte känner till den än.",
    capa: "Omslag",
    capaDetalhe: "Den breda bilden högst upp. 1280 × 720 sitter fint.",
    trocarCapa: "Byt omslag",
    categorias: "Kategorier",
    categoriasDetalhe: "Högst {{quantas}}. Det är efter dem man bläddrar i Utforska.",
    idiomas: "Språk",
    idiomasDetalhe: "Högst {{quantos}}. Vilka språk appen svarar på.",
    termos: "Användarvillkor",
    politica: "Integritetspolicy",
    politicas: "Villkor",
    servidorDeSuporte: "Supportserver",
    servidorDeSuporteDetalhe: "Dit hamnar den som behöver hjälp med appen.",
    semServidor: "Ingen",
    emQuantosServidores: "På hur många servrar",
    categoria: {
      GAMES: "Spel",
      MUSICA: "Musik",
      MODERACAO: "Moderering",
      PRODUTIVIDADE: "Produktivitet",
      SOCIAL: "Socialt",
      UTILIDADES: "Verktyg",
      ARTE_E_CRIACAO: "Konst och skapande",
      EDUCACAO: "Lärande",
      OUTRA: "Annat",
    },
    appIndisponivel: "Appen är inte tillgänglig",
    voltarParaExplorar: "Tillbaka till Utforska",
    adicionarApp: "Lägg till appen",
    copiarLink: "Kopiera länken",
    denunciarApp: "Anmäl appen",
    copiarIdDoApp: "Kopiera appens id",
    visaoGeral: "Översikt",
    comandos: "Kommandon",
    permissoes: "Behörigheter",
    semPermissoes: "Den här appen ber inte om några behörigheter.",
    avisoDePermissoes: "Den kommer in med en egen roll. Behörigheterna kan du ändra efteråt i Gemenskapens inställningar → Roller.",
    servidoresEmComum: "Gemensamma gemenskaper",
    umServidorEmComum: "1 gemenskap",
    quantosServidoresEmComum: "{{quantos}} gemenskaper",
    feitoPor: "Gjord av",
    publicadoEm: "Publicerad",
    denunciarNome: "Anmäl {{nome}}",
    denunciaDetalhe: "Anmälan går till Gravaês team. Den som gjorde appen får inte veta att det var du.",
    denunciaFalhou: "Anmälan kunde inte skickas.",
    umMembro: "1 medlem",
    semDescricao: "Ingen beskrivning.",
    adicionar: "Lägg till",
    jaEstaAqui: "Du är redan här",
    entrando: "Går med…",
    entrar: "Gå med",
    comunidadePublica: "Öppen gemenskap",
    online: "{{quantos}} online",
    membros: "{{quantos}} medlemmar",
    abrirComunidade: "Öppna gemenskapen",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Serverinställningar",
  novasMensagens: "Nya meddelanden",
  menu: {
    silenciar: "Tysta community",
    reativar: "Slå på community",
    porQuinze: "I 15 minuter",
    porMeiaHora: "I 30 minuter",
    porTresHoras: "I 3 timmar",
    porTresDias: "I 3 dagar",
    porUmaHora: "I 1 timme",
    porOitoHoras: "I 8 timmar",
    porUmDia: "I 24 timmar",
    ateReativar: "Tills jag slår på igen",
    notificacoes: "Aviseringsinställningar",
    padrao: "Använd standard",
    todas: "Alla meddelanden",
    soMencoes: "Bara omnämnanden",
    nada: "Inget",
    ocultarSilenciados: "Dölj tystade kanaler",
    denunciar: "Anmäl community",
    marcarLida: "Markera som läst",
    convidar: "Bjud in medlemmar",
    editarPerfil: "Redigera communityns profil",
    configuracoes: "Communityns inställningar",
    sair: "Lämna communityn",
    sairTitulo: "Lämna {{nome}}?",
    sairDescricao: "Du behöver en ny inbjudan för att komma tillbaka.",
    copiarId: "Kopiera communityns ID",
    idCopiado: "ID kopierat.",
  },
  convite: {
    cartaoTitulo: "Du är inbjuden till en gemenskap",
    indisponivel: "Inbjudan är inte tillgänglig",
    indisponivelDetalhe: "Den har gått ut, tagit slut, eller så har den som skapade den tagit bort den.",
    entrar: "Gå med i gemenskapen",
    chamado: "Du har blivit inbjuden till",
    aceitarComo: "Acceptera som {{nome}}",
    abrir: "Öppna communityn",
    recusar: "Nej tack",
  },
  pasta: {
    silenciarTodas: "Tysta communityn",
    reativarTodas: "Slå på communityn",
    mostrarSilenciados: "Visa tystade kanaler",
    notificacoesDaComunidade: "Aviseringsinställningar",
    silenciarEveryone: "Tysta @everyone och @here",
    permitirEveryone: "Tillåt @everyone och @here",
    silenciarCargos: "Tysta rollomnämnanden",
    permitirCargos: "Tillåt rollomnämnanden",
    dicaDaCor: "Skriv en färg (hex, rgb(), hsl() eller namn) eller använd väljaren.",
    mostrarIcone: "Visa ikon när stängd",
    dicaDoIcone: "Stängd visar den ikonen i stället för servrarna.",
    icone: "Mappikon",
    excluir: "Ta bort mapp",
    icones: {
      pasta: "Mapp",
      estrela: "Favorit",
      coracao: "Hjärta",
      salvar: "Spara",
      jogo: "Handkontroll",
      escudo: "Sköld",
      nota: "Not",
    },
    marcarLida: "Markera mapp som läst",
    configuracoes: "Mappinställningar",
    desfazer: "Upplös mapp",
    titulo: "Mapp",
    nome: "Namn",
    semNome: "Utan namn",
    cor: "Färg",
    semCor: "Ingen färg",
    salvar: "Spara",
  },
  denuncia: {
    titulo: "Anmäl {{nome}}",
    descricao: "Anmälan går till Gravaê-teamet. Berätta vad som hände.",
    motivo: "Anledning",
    detalhes: "Detaljer (valfritt)",
    enviar: "Skicka anmälan",
    enviada: "Anmälan skickad. Tack.",
    motivos: {
      spam: "Skräppost eller reklam",
      assedio: "Trakasserier eller hat",
      conteudo: "Olämpligt innehåll",
      golpe: "Bedrägeri",
      outro: "Annat",
    },
  },
  selos: {
    verificada: "Verifierad community",
    detectavel: "Upptäckbar community",
  },
  auditoria: {
    todasAsAcoes: "Alla åtgärder",
    todosOsUsuarios: "Alla användare",
    filtroMembros: "Medlemmar",
    filtroCanais: "Kanaler",
    filtroEmojis: "Emojier",
    filtroServidor: "Server",
    titulo: "Händelselogg",
    porUsuario: "Filtrera på person",
    porAcao: "Filtrera på åtgärd",
    vazio: "Inget loggat än med det här filtret.",
    motivo: "Orsak:",
  },
  banimentos: {
    titulo: "Serverns bannlista",
    descricao: "Den som står här kommer inte in igen, inte ens med en ny inbjudan. Att häva bannlysningen ger tillbaka åtkomsten direkt.",
    procurar: "Sök bannlysningar på användarnamn",
    vazioTitulo: "Inga bannlysningar",
    vazio: "Du har inte bannlyst någon än… men om och när det behövs, tveka inte.",
    desbanir: "Häv bannlysning",
  },
  excluir: {
    tudoVai: "Alla kanaler, meddelanden och inbjudningar i {{servidor}} raderas för de {{membros}} medlemmarna. Ingen kan få tillbaka dem efteråt.",
    digite: "Skriv {{servidor}} för att bekräfta",
    titulo: "Radera server",
    aviso: "Det här går inte att ångra.",
  },
  emblemas: {
    apagarDescricao: "Det försvinner från alla som bär det. Det går inte att ångra.",
    titulo: "Märken",
    vazio: "Inga märken än.",
    novo: "Nytt märke",
  },
  convites: {
    revogarTitulo: "Återkalla inbjudan?",
    revogarAcao: "Återkalla",
    revogarDescricao: "Länken {{codigo}} slutar fungera direkt. Den som redan gått med via den stannar på servern.",
    titulo: "Inbjudningar",
    descricao: "Alla aktiva inbjudningslänkar för den här servern.",
    vazio: "Ingen inbjudan har skapats än.",
    revogar: "Återkalla inbjudan",
  },
  integracoes: {
    opcionais: "username och avatar_url är valfria och gäller per meddelande. Gränsen är 5 meddelanden var femte sekund.",
    apagarDescricao: "URL:en slutar fungera direkt. Meddelandena den redan skickat står kvar i kanalen.",
    titulo: "Integrationer",
    descricao: "En webhook är en adress som postar i en kanal utan att behöva ett konto. Bra för att meddela att ett bygge gick igenom, att någon öppnat ett ärende, eller vad du nu vill skicka från ett skript.",
    novo: "Ny webhook",
    vazio: "Inga webhookar än. Skapa en och klistra in URL:en där du vill att meddelandet ska komma ifrån.",
    canal: "Kanal",
    apagar: "Radera webhook",
    comoUsar: "Så använder du det",
    comoUsarTexto: "Skicka en POST med JSON:",
  },
  explorar: {
    titulo: "Utforska",
  },
  engajamento: {
    semCanal: "Ingen systemkanal",
    titulo: "Engagemang",
    descricao: "Vad servern gör på egen hand så att den inte känns tom när någon ny kommer.",
    sistema: "Systemmeddelanden",
    boasVindas: "Skicka ett välkomstmeddelande när någon går med",
    sorteio: "Utan egen text nedanför lottas meningen fram — samma varje gång tröttnar man snabbt på.",
    canalDoSistema: "Kanal för systemmeddelanden",
    mensagem: "Välkomstmeddelande",
    deixeVazio: "Lämna tomt för att lotta bland de färdiga meningarna",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filter som modererar av sig själva, innan meddelandet ens finns. Den som administrerar servern filtreras aldrig — och undantagna roller går rakt igenom.",
    palavras: {
      titulo: "Blockera egna ord",
      descricao: "Din lista med ord som ingen får skriva.",
    },
    mencoes: {
      titulo: "Blockera omnämnandespam",
      descricao: "Blockerar ett meddelande med för många omnämnanden på en gång.",
    },
    links: {
      titulo: "Blockera länkar",
      descricao: "Håller tillbaka varje adress som klistras in i chatten.",
    },
    definir: "Ställ in",
    nomeDaRegra: "Regelns namn",
    bloqueadas: "Blockerade ord",
    digiteEnter: "Skriv och tryck Enter",
    comparacao: "Jämförelsen struntar i versaler, accenter och skiljetecken — och tar inte ett ord inuti ett annat.",
    aPartirDe: "Blockera från hur många omnämnanden",
    oQueFazer: "Vad som ska hända",
    canalDoAlerta: "Kanal för varningen",
    escolhaCanal: "Välj en kanal",
    castigo: "Tystnad (minuter)",
    isentos: "Undantagna roller",
    semCargos: "Inga roller har skapats än.",
    salvarRegra: "Spara regel",
    apagar: "Radera regel",
    excluirTitulo: "Radera den här AutoMod-regeln?",
    excluirDescricao: "Servern slutar filtrera efter den direkt. Du kan skapa den igen, men den nuvarande inställningen går förlorad.",
    excluirAcao: "Radera regel",
  },
  cargos: {
    titulo: "Roller",
    descricao: "Roller ger namn, färg och befogenheter. Den som står högre i listan bestämmer över dem under — och ingen rör en roll som är lika hög eller högre än den egna.",
    criar: "Skapa roll",
    vazio: "Inga roller än.",
    abaExibicao: "Utseende",
    abaPermissoes: "Behörigheter",
    abaMembros: "Medlemmar — {{quantos}}",
    everyone: "Gäller alla på servern. Det är grunden som de andra rollerna läggs ovanpå.",
    nomeDoCargo: "Rollens namn",
    cor: "Rollens färg",
    corDica: "Färgar namnet på den som har rollen i medlemslistan och i chatten.",
    semCor: "Utan färg",
    corPersonalizada: "Egen färg",
    estilo: "Namnets stil",
    segundaCor: "Andra färgen",
    segundaCorDica: "Utan den faller övergången tillbaka till en enda färg — den försvinner inte.",
    limparSegundaCor: "Rensa andra färgen",
    icone: "Ikon",
    iconeDica: "Visas bredvid rollen på profilkortet hos den som har den.",
    exibirSeparado: "Visa separat från övriga medlemmar",
    exibirSeparadoDica: "Rollen får en egen sektion i medlemslistan.",
    permitirMencionar: "Tillåt att den här rollen nämns",
    permitirMencionarDica: "Vem som helst kommer att kunna avisera alla som har rollen.",
    semPoderDeConceder: "{{descricao}} (du har inte den här behörigheten att ge bort)",
    adicionar: "Lägg till någon i den här rollen",
    tirar: "Ta bort rollen",
    semNinguem: "Ingen har den här rollen än.",
    apagar: "Radera roll",
    excluirTitulo: "Radera rollen ”{{nome}}”?",
    excluirDescricao: "Den som har rollen förlorar allt den gav. Det går inte att ångra.",
    excluirAcao: "Radera roll",
  },
  membros: {
    procurar: "Sök på namn eller användarnamn",
    membroDesde: "Medlem sedan",
    vazio: "Ingen hittades.",
    acoesPara: "Åtgärder för {{nome}}",
    deCastigo: "tystnad",
    tirarCastigo: "Häv tystnaden",
    castigo5min: "5 minuter",
    castigo1h: "1 timme",
    castigo1d: "1 dag",
    castigo1s: "1 vecka",
    expulsar: "Sparka ut",
    expulsarTitulo: "Sparka ut {{nome}}?",
    expulsarDescricao: "lämnar {{servidor}} direkt. Kan komma tillbaka med en inbjudan — att sparka ut hindrar inte återkomsten.",
    banir: "Bannlys",
    banirTitulo: "Bannlysa {{nome}}?",
    banirDescricao: "lämnar {{servidor}} och kan inte komma tillbaka, inte ens med en inbjudan, förrän bannlysningen hävs.",
    motivo: "Orsak (valfritt)",
    motivoDica: "Registreras i händelseloggen",
  },
  perfil: {
    titulo: "Serverprofil",
    descricao: "Så här visas din server i listan och i inbjudningslänkar.",
    icone: "Ikon",
    faixa: "Banner högst upp",
    nomeDoServidor: "Serverns namn",
    campoDescricao: "Beskrivning",
    doQueE: "Vad handlar den här servern om?",
    comprimido: "Komprimerad före uppladdning: {{economia}}",
  },
  etiqueta: {
    titulo: "Servertagg",
    descricao: "En etikett på högst 4 bokstäver som visas bredvid namnet på varje medlem — i chatten och i personlistan. Här är den gratis: utan boostar, utan nivåer.",
    escolhaNome: "Välj ett namn",
    limite: "Högst 4 tecken, bokstäver och siffror.",
    escolhaInsignia: "Välj ett märke",
    voce: "Du",
    fala1: "någon som vill spela?",
    fala2: "kolla in min tagg!",
    fala3: "oj, hur fick du tag på den",
  },
  expressoes: {
    comoUsar: "Lägg till upp till {{limite}} emojier som alla kan använda på den här servern. Skriv :namn: i chatten för att skicka en.",
    imagem: "Bild",
    enviadoPor: "Uppladdad av",
    semEmoji: "Inga emojier än.",
    figurinhas: "Dekaler",
    enviarFigurinha: "Ladda upp dekal",
    nomeDaFigurinha: "Dekalens namn",
    exemploFigurinha: "T.ex.: kattungekram",
    figurinhaGrande: "Dekalen är större än {{limite}}.",
    deixaPraLa: "Strunt i det",
    sons: "Ljudpanel",
    enviarSom: "Ladda upp ljud",
    nomeDoSom: "Ljudets namn",
    semSom: "Inga ljud än.",
    somGrande: "Ljudet är större än {{limite}}.",
    emojiRelacionado: "Tillhörande emoji",
    ouvir: "Lyssna",
    ouvirAssim: "Lyssna så här",
    volumeDe: "Volym för {{nome}}",
    volumeDica: "Gäller alla på servern. Var och en kan ändå sänka ljuden bara för sig själv, i samtalspanelen.",
    falhaEnvio: "Filen kunde inte laddas upp.",
    excluirTitulo: "Radera {{tipo}} ”{{nome}}”?",
    excluirDescricao: "Den försvinner från servern för alla. Meddelanden som redan använt den står kvar som de är.",
  },
  canal: {
    tipoLink: "Länk",
    tipoLinkDica: "Pekar mot en adress utanför och öppnas i webbläsaren",
    endereco: "Adress",
    enderecoDica: "Dit den här kanalen leder. Måste börja med https://",
    visaoGeral: "Översikt",
    nome: "Kanalens namn",
    topico: "Kanalens ämne",
    topicoDica: "Vad pratar man om här?",
    modoLento: "Varje person skickar bara ett meddelande per intervall. Den som hanterar meddelanden eller kanaler går rakt igenom.",
    visibilidade: "Innehållets synlighet",
    padrao: "Standard",
    padraoDica: "Kanalens innehåll syns alltid.",
    spoiler: "Spoilerkanal",
    spoilerDica: "Markera den här kanalen som spoilerkanal, så att vändningar och tunga ämnen förblir dolda tills någon väljer att titta.",
    idade: "Åldersbegränsad kanal",
    idadeDica: "Den som går in måste bekräfta att hen är myndig för att se innehållet.",
    bitrateDica: "Över 64 kbps kan störa dem med dålig uppkoppling.",
    qualidadeDeVideo: "Videokvalitet",
    automatica: "Automatisk",
    limite: "Användargräns — {{valor}}",
    pessoas: "{{quantos}} personer",
    semLimite: "ingen gräns",
    permissoesDescricao: "Här ändrar du vad som gäller i den här kanalen. Det som står kvar på ”ärv” följer fortfarande rollen.",
    excluir: {
      titulo: "Radera kanal",
      historico: "Hela historiken för {{canal}} följer med, för alla.",
      digite: "Skriv {{canal}} för att bekräfta",
    },
  },
  moderacao: {
    titulo: "Moderatorvy",
    semPermissao: "Du behöver behörigheten ”Moderera medlemmar” för att se det här.",
    fecharEsc: "Stäng (Esc)",
    atividade: "Aktivitet på servern",
    mensagens: "Meddelanden",
    links: "Länkar",
    midia: "Media",
    acoesNaAuditoria: "Åtgärder i händelseloggen",
    moderacoesSofridas: "Mottagen moderering",
    permissoes: "Behörigheter ({{quantas}})",
    semPermissaoEspecial: "Inga särskilda behörigheter.",
    conta: "Konto",
    entrouNoServidor: "Gick med i servern",
    contaCriadaEm: "Konto skapat",
    deCastigoAte: "Tystad till",
    formaDeAdesao: "Hur hen kom in",
    mensagem: "Meddelande",
    castigo: "Tystnad",
    copiarId: "Kopiera ID",
    idCopiado: "ID kopierat.",
    adicionarCargo: "Lägg till roll",
    semCargos: "Ingen roll skapad",
    soEveryone: "Bara @everyone.",
    voltar: "Tillbaka",
    vazio: "Inget här.",
    cinquenta: "Visar de 50 senaste.",
    irParaMensagem: "Gå till meddelandet",
    precisaSerAmigo: "Ni måste vara vänner för att prata.",
    expulsarDescricao: "Lämnar servern direkt, men kan komma tillbaka med en inbjudan.",
    banirDescricao: "Lämnar servern och kan inte komma tillbaka, inte ens med en inbjudan, förrän bannlysningen hävs.",
    castigarTitulo: "Tysta {{nome}}?",
    castigoDescricao: "Så länge det varar skriver eller talar hen inte i någon kanal på servern.",
    aplicarCastigo: "Tillämpa tystnad",
    duracao: "Längd i minuter",
    informeDuracao: "Ange längden i minuter.",
  },
  abas: {
    pesquisar: "Sök i inställningarna",
    semResultado: "Ingenting här med det namnet.",
    comunidade: "Gemenskap",
    expressoes: "Uttryck",
    pessoas: "Personer",
    apps: "Appar",
    moderacao: "Moderering",
    banimentos: "Bannlysningar",
  },
};
