export const amizades = {
  ativosAgora: "Právě aktivní",
  procurando: "Koukáme, kdo je tu…",
  tudoTranquilo: "Zatím je klid…",
  tudoTranquiloDetalhe: "Až se ty nebo kamarád připojíte k hovoru, objeví se tady — a přidáš se jedním kliknutím.",
  emVoz: "V hlasovém",
  voce: "Ty",
  soVoce: "Jenom ty",
  pessoas: "{{quantas}} lidí",
  voltarParaChamada: "Zpět do hovoru",
  entrarNaChamada: "Připojit se k hovoru",
  abrirCanal: "Otevřít {{canal}} na {{servidor}}",
  mensagensDiretas: "Přímé zprávy",
  encontreConversa: "Najít konverzaci",
  amigos: "Přátelé",
  conversas: "Konverzace",
  semConversas: "Zatím žádné konverzace. Přidej kamaráda a začni.",
  semConversaComEsseNome: "Žádná konverzace s tímhle názvem.",
  abrirMenu: "Otevřít servery a konverzace",
  solicitacoes: "Žádosti o zprávu",
  pedidos: "Žádosti",
  spam: "Spam",
  pedidosPendentes: "Čekající žádosti",
  marcadosComoSpam: "Označené jako spam",
  aceitar: "Přijmout",
  ignorar: "Ignorovat",
  marcarSpam: "Označit jako spam",
  semPedidos: "Žádné čekající žádosti.",
  semPedidosDetalhe: "Kdo není tvůj kamarád, ale je s tebou na stejném serveru, skončí tady dřív, než se dostane do tvých konverzací.",
  semSpam: "Nic není označené jako spam.",
  semSpamDetalhe: "Co odchytí filtr spamu nebo co označíš sám, zůstane na téhle záložce.",
  umServidorEmComum: "1 společný server",
  servidoresEmComum: "Společné servery: {{quantos}}",
  semServidoresEmComum: "Žádné společné servery",
};
