export const chamada = {
  conectando: "Připojování k hovoru…",
  naoEntrou: "Nepodařilo se připojit k hovoru",
  sair: "Opustit hovor",
  sairDaVoz: "Opustit hlasový hovor",
  desconectar: "Odpojit",
  voltar: "Zpět do hovoru",
  voltarAosQuadros: "Zpět na dlaždice hovoru",
  fecharChat: "Zavřít chat",
  carregandoPrevia: "Načítání náhledu…",
  maisOpcoes: "Další možnosti",
  deVideo: "Videohovor",
  deVoz: "Hlasový hovor",
  alguem: "Někdo",
  volume: {
    entrada: "Hlasitost vstupu",
    saida: "Hlasitost výstupu",
    live: "Hlasitost přenosu",
    liveComPorcento: "Hlasitost přenosu ({{porcento}} %)",
    liveSemSom: "Přenos bez zvuku",
  },
  aparelhos: {
    entrada: "Vstupní zařízení",
    saida: "Výstupní zařízení",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Výstup",
    oDoSistema: "Systémové",
    aDoSistema: "Systémová",
    semEscolhaDeSaida: "Tenhle prohlížeč nedovolí vybrat výstup — rozhoduje systém.",
    espelhar: "Zrcadlit moji kameru",
    configEntrada: "Nastavení vstupu",
    configSaida: "Nastavení výstupu",
    configCamera: "Nastavení kamery",
    configAudioEVideo: "Nastavení zvuku a videa",
  },
  tela: {
    compartilhar: "Sdílet obrazovku",
    compartilharAcao: "Sdílet",
    cancelar: "Zrušit",
    telas: "Obrazovky",
    janelas: "Okna",
    somDoComputador: "Vzít i zvuk počítače",
    somDoSistema: "Vzít i zvuk systému",
    configCompartilhamento: "Nastavení sdílení",
    mostrarSemVideo: "Zobrazovat ty bez videa",
    semFontes: "Systém nevrátil žádnou obrazovku ani okno ke sdílení.",
    pararDeCompartilhar: "Přestat sdílet",
    encerrarTransmissao: "Ukončit přenos",
  },
  live: {
    etiqueta: "Živě",
    etiquetaMaiuscula: "ŽIVĚ",
    assistir: "Sledovat přenos",
    assistirPessoa: "Sledovat {{nome}}",
    pararDeAssistir: "Přestat sledovat",
  },
  membro: {
    mudarMeuApelido: "Změnit moji přezdívku",
    meuMicrofone: "Můj mikrofon",
    ouvirChamada: "Poslouchat hovor",
    copiarMeuId: "Kopírovat moje ID",
    idCopiado: "ID zkopírováno.",
    mensagem: "Zpráva",
    silenciar: "Ztlumit",
    alterarApelido: "Změnit přezdívku",
    cargos: "Role",
    semCargo: "Žádná role nevytvořena",
    moverPara: "Přesunout do",
    silenciarNoServidor: "Ztlumit hlas na serveru",
    desativarAudioNoServidor: "Vypnout zvuk na serveru",
    desconectar: "Odpojit",
    apelidoTitulo: "Tvoje přezdívka na tomto serveru",
    apelidoDeAlguem: "Přezdívka: {{nome}}",
    apelidoCampo: "Přezdívka",
    apelidoDicaPropria: "Platí jen tady. Prázdné pole vrátí tvoje běžné jméno.",
    apelidoDicaDeOutro: "Platí jen na tomto serveru. Nech prázdné, ať se vrátí původní jméno.",
  },
  detalhes: {
    abrir: "Podrobnosti hlasu",
    titulo: "Podrobnosti Hlasu",
    conexao: "Připojení",
    pingMedio: "Průměrný ping",
    ultimoPing: "Poslední ping",
    perda: "Ztráta odeslaných paketů",
    medindo: "Měříme…",
    criptografado: "Šifrováno až k serveru (DTLS-SRTP)",
    explicacao: "Nad 250 ms je zpoždění v hovoru slyšet — lidé si začnou skákat do řeči. Ztráta paketů nad 10 % udělá z hlasu robota. V obou případech je problém skoro vždy mezi tebou a internetem: zkus kabel místo Wi-Fi, nebo restartuj router.",
  },
  microfone: {
    bloqueado: "Mikrofon zablokovaný — jenom posloucháš. Povol přístup v oprávněních prohlížeče.",
    bloqueadoNoMac: "macOS blokuje mikrofon. Zaškrtni",
    caminhoNoMac: "Nastavení systému → Soukromí a zabezpečení → Mikrofon",
    abrirAjustes: "Otevřít nastavení",
    vaiReabrir: "macOS požádá o znovuotevření aplikace.",
    naoAbriu: "Nepodařilo se otevřít mikrofon — jenom posloucháš. Zkontroluj zařízení v Nastavení → Hlas a video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS zatím nepovolil nahrávání obrazovky. Bez toho vyjde sdílení černé.",
    marque: "Zaškrtni",
    reabra: "v Nahrávání obrazovky a otevři aplikaci znovu.",
    jaMarcado: "Pokud už je zaškrtnuto, oprávnění zastaralo při poslední aktualizaci: odškrtni, zaškrtni znovu a otevři aplikaci znovu.",
  },
  ruido: {
    titulo: "Potlačení šumu",
    explicacao: "Odeber ze svého hlasu hluk z pozadí. Zkus zatleskat nebo posunout klávesnici, když mluvíš — lidi v hovoru slyší jenom tebe.",
    semSuporte: "Tenhle prohlížeč pokročilé potlačení nespustí. Pořád platí to prohlížečové, ale je slabší.",
    aplicando: "Aplikuje se na hovor…",
    faleParaTestar: "Mluv pro test",
    verdeQuandoPassa: "Zeleně, když tvůj hlas projde.",
    teOuvindo: "Právě tě slyší.",
    feitoCom: "Vyrobeno s",
    aquiNoAparelho: ", tady na tvém zařízení",
    ajustes: "Nastavení",
  },
  permissoes: {
    titulo: "Oprávnění macOS",
    detalhe: "macOS se ptá jen jednou a pak se to mění jen v jeho panelu. Tady vidíš, co platí, a vyřešíš, co chybí.",
    concedida: "Uděleno",
    negada: "Zamítnuto",
    naoPedida: "Nevyžádáno",
    permitir: "Povolit",
    abrirAjustes: "Otevřít nastavení",
    microfone: "Mikrofon",
    microfoneDetalhe: "Mluvit v hovorech a testovat svůj vstup.",
    camera: "Kamera",
    cameraDetalhe: "Zapnout video v hovoru.",
    tela: "Nahrávání obrazovky",
    telaDetalhe: "Sdílet obrazovku a okna.",
    monitoramento: "Sledování vstupu",
    monitoramentoDetalhe: "Používat push-to-talk i s Gravaê na pozadí.",
  },
  jaConectado: {
    titulo: "V tomhle hovoru už jsi",
    trazer: "Přenést hovor sem",
    deixar: "Nechat, jak je",
    detalhe: "Když ho přeneseš sem, druhý konec z hovoru vypadne — tvůj účet je vždycky jen na jednom místě.",
  },
};
