export const comum = {
  carregando: "Načítání…",
  salvar: "Uložit",
  salvando: "Ukládání…",
  descartar: "Zahodit",
  redefinir: "Obnovit",
  naoSalvo: "Máš neuložené změny.",
  fechar: "Zavřít",
  criar: "Vytvořit",
  nome: "Název",
  emoji: "Emoji",
  previa: "Náhled",
  cancelar: "Zrušit",
  enviar: "Odeslat",
  apagar: "Smazat",
  excluir: "Smazat",
  remover: "Odebrat",
  trocar: "Změnit",
};
