export const configuracoes = {
  sair: "Odhlásit se",
  versoes: {
    copiar: "Klikni pro kopírování",
    copiado: "Zkopírováno",
  },
  telas: {
    conta: "Můj účet",
    privacidade: "Soukromí",
    conexoes: "Připojení",
    voz: "Zvuk",
    video: "Video",
    avisos: "Oznámení",
    aplicativos: "Aplikace",
    aparencia: "Vzhled",
    batePapo: "Chat",
    acessibilidade: "Přístupnost",
    idioma: "Jazyk",
    aplicativo: "Stáhnout aplikaci",
    atalhos: "Klávesové zkratky",
    desktop: "Aplikace pro počítač",
    avancado: "Pokročilé",
    servidor: "Server",
  },
  grupos: {
    conta: "Účet",
    app: "Nastavení aplikace",
    desenvolvedor: "Vývojář",
    administracao: "Správa",
  },
  secoes: {
    detalhesDeLogin: "Přihlašovací údaje",
    dispositivos: "Zařízení",
    usuariosBloqueados: "Blokovaní uživatelé",
    aplicativosAutorizados: "Autorizované aplikace",
    sessoes: "Relace",
    amigosEDms: "Přátelé a přímé zprávy",
    compartilhamentoDeAtividade: "Sdílení aktivity",
    visibilidadeDoPerfil: "Viditelnost profilu",
    exportarDados: "Exportovat data",
    exclusaoDeDados: "Smazat data",
    tema: "Motiv",
    corDeDestaque: "Barva zvýraznění",
    interface: "Rozhraní",
    listaDeCanais: "Seznam kanálů",
    zoomDoApp: "Úroveň přiblížení aplikace",
    escalaDaFonte: "Velikost písma chatu",
    modoStreamer: "Soukromí při vysílání",
    movimento: "Pohyb",
    textoEmVoz: "Převod textu na řeč",
    teclado: "Klávesnice",
    formatoDaHora: "Formát času",
    idiomaDaInterface: "Jazyk rozhraní",
    dispositivosDeVoz: "Zařízení",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Režim vstupu",
    sensibilidade: "Citlivost vstupu",
    qualidade: "Kvalita",
    camera: "Kamera",
    transmissao: "Vysílání",
    exibicao: "Zobrazení",
    entrada: "Zadávání",
    midia: "Média",
    geral: "Obecné",
    preferenciaDeMencao: "Předvolba zmínek",
    sons: "Zvuky",
  },
};
