export const configuracoes = {
  efeitos: {
    titulo: "Efekty ukazatele",
    detalhe: "Stopa a jiskry kreslené přes aplikaci. Přicházejí vypnuté a samy zmizí, když jste si řekli o méně pohybu.",
    rastro: "Stopa kurzoru",
    rastroDetalhe: "Čára, která jde za ukazatelem a vzadu bledne.",
    faisca: "Jiskry při kliknutí",
    faiscaDetalhe: "Krátké čárky vyletující z místa, kam jste klikli.",
    cor: "Barva",
    espessura: "Tloušťka",
    comprimento: "Délka",
    tamanho: "Velikost",
    quantidade: "Počet",
  },
  email: {
    verificarTitulo: "Potvrďte svůj e-mail",
    verificarDetalhe: "Některé komunity nechají psát jen potvrzené. Je to na jedno kliknutí.",
    enviar: "Poslat odkaz",
    enviado: "Mrkněte do schránky. Odkaz platí jeden den.",
    falhou: "E-mail se nepodařilo odeslat.",
    confirmado: "E-mail potvrzen",
    confirmadoDetalhe: "Hotovo. Teď píšete i tam, kde to komunita vyžaduje.",
    linkIncompleto: "Neúplný odkaz",
    linkIncompletoDetalhe: "V adrese chybí kód. Otevřete odkaz přímo z e-mailu.",
    confirmando: "Potvrzuje se…",
    expirou: "Tento odkaz už byl použit nebo mu vypršela platnost.",
    irParaOApp: "Přejít do aplikace",
  },
  tema: {
    indisponivel: "Motiv není dostupný",
    indisponivelDetalhe: "Ten, kdo ho zveřejnil, ho smazal, nebo je odkaz špatně.",
    indisponivelLinha: "Motiv není dostupný. Ten, kdo ho zveřejnil, ho smazal, nebo je odkaz špatně.",
    importar: "Importovat motiv",
    importarCurto: "Importovat",
    importarDetalhe: "Tímto nahradíte motiv, který máte teď. Upravit ho můžete později v Nastavení > Vzhled > Studio motivů.",
    porAutor: "od {{autor}}",
    umaCorTrocada: "1 vyměněná barva",
    coresTrocadas: "{{quantas}} vyměněných barev",
    avisoDeCss: "Tenhle motiv nese CSS od svého autora a CSS sahá do každého kouta obrazovky. Importujte jen od lidí, kterým věříte.",
    soCores: "Tenhle motiv mění jen barvy. Žádné cizí CSS.",
    verCss: "Zobrazit CSS",
    esconderCss: "Skrýt CSS",
    aplicar: "Použít",
    previaSemMotor: "Náhled motor nespouští. Nainstalujte si ho, ať ho uvidíte.",
    motorAnimado: "{{motor}} animovaný",
  },
  sair: "Odhlásit se",
  versoes: {
    termos: "Podmínky služby",
    privacidade: "Zásady ochrany soukromí",
    copiar: "Klikni pro kopírování",
    copiado: "Zkopírováno",
  },
  subscription: {
    seePlans: "Zobrazit tarify",
    upgradeSubtitle: "Vyšší limity a exkluzivní funkce pro psaní, posílání souborů a vysílání.",
    perMonth: "měsíčně",
    perYear: "ročně",
    save: "Ušetříte {{percent}} %",
    howToPay: "Jak chcete zaplatit?",
    legal: "O vrácení peněz můžete požádat do 7 dnů od platby. Platbu zpracovává Stripe; číslo vaší karty nikdy nevidíme.",
    compare: "Zdarma vs. Infinity",
    featureColumn: "Funkce",
    freeColumn: "Zdarma",
    messageRow: "Limit znaků zprávy",
    attachmentRow: "Velikost odesílaného souboru",
    screenRow: "Kvalita videa",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "Infinity už máte do {{date}}.",
    upsell: "Zvýšit limit s Infinity",
    screenUpsell: "Vyšší kvalita s Infinity",
    free: "Máte bezplatný tarif.",
    activeUntil: "Infinity aktivní do {{date}}.",
    renews: "Automaticky se obnoví {{date}}.",
    endsAt: "Předplatné bylo zrušeno a končí {{date}}.",
    pastDue: "Poslední platba se nezdařila. Aktualizujte kartu, abyste o Infinity nepřišli.",
    waiting: "Potvrzování platby…",
    subscribe: "Předplatit",
    monthly: "Měsíčně",
    yearly: "Ročně",
    automatic: "Karta, obnovuje se automaticky",
    pass: "Zaplatit jen období (Pix nebo karta)",
    manage: "Spravovat platbu",
    refund: "Požádat o vrácení peněz",
    refundDetail: "Můžete odstoupit do 7 dnů od platby: {{amount}}, do {{date}}.",
    refundConfirm: "Požádat o vrácení peněz?",
    refundConfirmDetail: "Peníze se vrátí stejným způsobem platby a Infinity hned skončí.",
    refunded: "Žádost o vrácení odeslána.",
    unavailable: "Předplatné zatím není k dispozici.",
    success: "Platba přijata. Děkujeme!",
    canceled: "Platba zrušena.",
    error: "Něco se nepovedlo. Zkuste to znovu.",
    no: "Ne",
    tagRow: "Vlastní uživatelský štítek",
    guildProfilesRow: "Profily pro komunity",
    badgeRow: "Odznak profilu",
    communitiesRow: "Komunity",
    savedRow: "Uložené zprávy",
    animatedEmojiRow: "Animované emoji",
    expressionsRow: "Emoji a nálepky odkudkoli",
    animatedProfileRow: "Animované avatary a bannery profilu",
    earlyAccessRow: "Předběžný přístup k novinkám",
    themesRow: "Vlastní motivy",
  },
  telas: {
    subscription: "Infinity",
    conta: "Můj účet",
    privacidade: "Soukromí",
    conexoes: "Připojení",
    voz: "Zvuk",
    video: "Video",
    avisos: "Oznámení",
    aplicativos: "Aplikace",
    aparencia: "Vzhled",
    batePapo: "Chat",
    acessibilidade: "Přístupnost",
    idioma: "Jazyk",
    aplicativo: "Stáhnout aplikaci",
    atalhos: "Klávesové zkratky",
    desktop: "Aplikace pro počítač",
    avancado: "Pokročilé",
    servidor: "Server",
    comunicado: "Systémové oznámení",
    denuncias: "Nahlášení",
    publicacoes: "Nasazení",
  },
  grupos: {
    conta: "Účet",
    app: "Nastavení aplikace",
    desenvolvedor: "Vývojář",
    administracao: "Správa",
  },
  secoes: {
    detalhesDeLogin: "Přihlašovací údaje",
    dispositivos: "Zařízení",
    usuariosBloqueados: "Blokovaní uživatelé",
    aplicativosAutorizados: "Autorizované aplikace",
    sessoes: "Relace",
    amigosEDms: "Přátelé a přímé zprávy",
    compartilhamentoDeAtividade: "Sdílení aktivity",
    visibilidadeDoPerfil: "Viditelnost profilu",
    exportarDados: "Exportovat data",
    exclusaoDeDados: "Smazat data",
    tema: "Motiv",
    corDeDestaque: "Barva zvýraznění",
    interface: "Rozhraní",
    listaDeCanais: "Seznam kanálů",
    zoomDoApp: "Úroveň přiblížení aplikace",
    escalaDaFonte: "Velikost písma chatu",
    modoStreamer: "Soukromí při vysílání",
    cursores: "Kurzory",
    movimento: "Pohyb",
    textoEmVoz: "Převod textu na řeč",
    teclado: "Klávesnice",
    formatoDaHora: "Formát času",
    idiomaDaInterface: "Jazyk rozhraní",
    dispositivosDeVoz: "Zařízení",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Režim vstupu",
    sensibilidade: "Citlivost vstupu",
    qualidade: "Kvalita",
    camera: "Kamera",
    transmissao: "Vysílání",
    exibicao: "Zobrazení",
    entrada: "Zadávání",
    midia: "Média",
    geral: "Obecné",
    preferenciaDeMencao: "Předvolba zmínek",
    sons: "Zvuky",
  },
};
