export const configuracoes = {
  efeitos: {
    titulo: "Efekty ukazatele",
    detalhe: "Stopa a jiskry kreslené přes aplikaci. Přicházejí vypnuté a samy zmizí, když jste si řekli o méně pohybu.",
    rastro: "Stopa kurzoru",
    rastroDetalhe: "Čára, která jde za ukazatelem a vzadu bledne.",
    faisca: "Jiskry při kliknutí",
    faiscaDetalhe: "Krátké čárky vyletující z místa, kam jste klikli.",
    cor: "Barva",
    espessura: "Tloušťka",
    comprimento: "Délka",
    tamanho: "Velikost",
    quantidade: "Počet",
  },
  email: {
    verificarTitulo: "Potvrďte svůj e-mail",
    verificarDetalhe: "Některé komunity nechají psát jen potvrzené. Je to na jedno kliknutí.",
    enviar: "Poslat odkaz",
    enviado: "Mrkněte do schránky. Odkaz platí jeden den.",
    falhou: "E-mail se nepodařilo odeslat.",
    confirmado: "E-mail potvrzen",
    confirmadoDetalhe: "Hotovo. Teď píšete i tam, kde to komunita vyžaduje.",
    linkIncompleto: "Neúplný odkaz",
    linkIncompletoDetalhe: "V adrese chybí kód. Otevřete odkaz přímo z e-mailu.",
    confirmando: "Potvrzuje se…",
    expirou: "Tento odkaz už byl použit nebo mu vypršela platnost.",
    irParaOApp: "Přejít do aplikace",
  },
  tema: {
    indisponivel: "Motiv není dostupný",
    indisponivelDetalhe: "Ten, kdo ho zveřejnil, ho smazal, nebo je odkaz špatně.",
    indisponivelLinha: "Motiv není dostupný. Ten, kdo ho zveřejnil, ho smazal, nebo je odkaz špatně.",
    importar: "Importovat motiv",
    importarCurto: "Importovat",
    importarDetalhe: "Tímto nahradíte motiv, který máte teď. Upravit ho můžete později v Nastavení > Vzhled > Studio motivů.",
    porAutor: "od {{autor}}",
    umaCorTrocada: "1 vyměněná barva",
    coresTrocadas: "{{quantas}} vyměněných barev",
    avisoDeCss: "Tenhle motiv nese CSS od svého autora a CSS sahá do každého kouta obrazovky. Importujte jen od lidí, kterým věříte.",
    soCores: "Tenhle motiv mění jen barvy. Žádné cizí CSS.",
    aplicar: "Použít",
    previaSemMotor: "Náhled motor nespouští. Nainstalujte si ho, ať ho uvidíte.",
    motorAnimado: "{{motor}} animovaný",
  },
  sair: "Odhlásit se",
  versoes: {
    termos: "Podmínky služby",
    privacidade: "Zásady ochrany soukromí",
    copiar: "Klikni pro kopírování",
    copiado: "Zkopírováno",
  },
  telas: {
    conta: "Můj účet",
    privacidade: "Soukromí",
    conexoes: "Připojení",
    voz: "Zvuk",
    video: "Video",
    avisos: "Oznámení",
    aplicativos: "Aplikace",
    aparencia: "Vzhled",
    batePapo: "Chat",
    acessibilidade: "Přístupnost",
    idioma: "Jazyk",
    aplicativo: "Stáhnout aplikaci",
    atalhos: "Klávesové zkratky",
    desktop: "Aplikace pro počítač",
    avancado: "Pokročilé",
    servidor: "Server",
    comunicado: "Systémové oznámení",
    denuncias: "Nahlášení",
    publicacoes: "Nasazení",
  },
  grupos: {
    conta: "Účet",
    app: "Nastavení aplikace",
    desenvolvedor: "Vývojář",
    administracao: "Správa",
  },
  secoes: {
    detalhesDeLogin: "Přihlašovací údaje",
    dispositivos: "Zařízení",
    usuariosBloqueados: "Blokovaní uživatelé",
    aplicativosAutorizados: "Autorizované aplikace",
    sessoes: "Relace",
    amigosEDms: "Přátelé a přímé zprávy",
    compartilhamentoDeAtividade: "Sdílení aktivity",
    visibilidadeDoPerfil: "Viditelnost profilu",
    exportarDados: "Exportovat data",
    exclusaoDeDados: "Smazat data",
    tema: "Motiv",
    corDeDestaque: "Barva zvýraznění",
    interface: "Rozhraní",
    listaDeCanais: "Seznam kanálů",
    zoomDoApp: "Úroveň přiblížení aplikace",
    escalaDaFonte: "Velikost písma chatu",
    modoStreamer: "Soukromí při vysílání",
    cursores: "Kurzory",
    movimento: "Pohyb",
    textoEmVoz: "Převod textu na řeč",
    teclado: "Klávesnice",
    formatoDaHora: "Formát času",
    idiomaDaInterface: "Jazyk rozhraní",
    dispositivosDeVoz: "Zařízení",
    testeDoMicrofone: "Test mikrofonu",
    modoDeEntrada: "Režim vstupu",
    sensibilidade: "Citlivost vstupu",
    qualidade: "Kvalita",
    camera: "Kamera",
    transmissao: "Vysílání",
    exibicao: "Zobrazení",
    entrada: "Zadávání",
    midia: "Média",
    geral: "Obecné",
    preferenciaDeMencao: "Předvolba zmínek",
    sons: "Zvuky",
  },
};
