export const conversa = {
  lista: {
    carregando: "Načítání zpráv…",
    carregandoMais: "Načítání…",
    verMais: "Posuňte nahoru, ať uvidíte víc",
    semHistorico: "Historie není dostupná",
    semHistoricoDetalhe: "Tvoje role nemá oprávnění číst historii kanálu #{{canal}}. Nové zprávy se budou objevovat dál, dokud jsi tady.",
    boasVindas: "Vítej na #{{canal}}",
    boasVindasDetalhe: "Tohle je začátek kanálu #{{canal}}.",
  },
  data: {
    hoje: "Dnes",
    ontem: "Včera",
    hojeAs: "dnes v {{hora}}",
    ontemAs: "včera v {{hora}}",
  },
  digitando: {
    um: "{{nome}} píše…",
    dois: "{{primeiro}} a {{segundo}} píšou…",
    varios: "{{quantidade}} lidí píše…",
  },
  mensagem: {
    usou: "použil(a)",
    fixada: "připnuto",
    editado: "(upraveno)",
    ignorada: "Zpráva od někoho, koho ignoruješ.",
    mostrar: "Zobrazit",
    escPara: "Esc pro",
    cancelar: "zrušení",
    enterParaSalvar: "Enter pro uložení",
    falhou: "Neodeslalo se. Zkusit znovu",
    naoLidasDaqui: "Nepřečtené odsud.",
    linkCopiado: "Odkaz zkopírován.",
    idCopiado: "ID zkopírováno.",
    naoDeuParaCopiar: "Tvůj prohlížeč kopírování nepovolil.",
    apagarTitulo: "Smazat zprávu?",
    apagarDescricao: "Zmizí všem v kanálu. Nedá se obnovit.",
    apagarAcao: "Smazat",
    citacaoAnexo: "klikni, ať uvidíš přílohu",
    citacaoSumiu: "Původní zpráva už tu není.",
    reagirCom: "Reagovat pomocí {{emoji}} — podrž pro super reakci",
    segureParaSuper: "{{emoji}} — podrž pro super reakci",
  },
  acoes: {
    reagir: "Reagovat",
    responder: "Odpovědět",
    encaminhar: "Přeposlat",
    favoritar: "Uložit zprávu",
    tirarDosFavoritos: "Odebrat z uložených",
    marcarNaoLida: "Označit jako nepřečtené",
    copiarLink: "Kopírovat odkaz na zprávu",
    copiarId: "Kopírovat ID zprávy",
    fixar: "Připnout zprávu",
    desafixar: "Odepnout",
    editar: "Upravit",
    apagar: "Smazat",
    mais: "Více",
    adicionarReacao: "Přidat reakci",
    superReagirCom: "Super reakce pomocí {{emoji}}",
    fixarMensagem: "Připnout zprávu",
    desafixarMensagem: "Odepnout zprávu",
    editarMensagem: "Upravit zprávu",
    apagarMensagem: "Smazat zprávu",
  },
  mencao: {
    cargo: "Zmínka role",
    pessoa: "Zmínka",
    alguem: "někdo",
    cargoSemNome: "role",
    here: "Upozorní ty, kdo jsou online",
    everyone: "Upozorní celý server",
  },
  codigo: {
    copiar: "Kopírovat",
    copiado: "Zkopírováno",
    copiarAria: "Kopírovat kód",
    copiadoAria: "Kód zkopírován",
    recolher: "Sbalit",
    expandir: "Rozbalit",
    verInteiro: "Zobrazit celý soubor",
    maisOpcoes: "Další možnosti",
    baixar: "Stáhnout",
    recolherLinhas: "Sbalit ({{linhas}} řádků)",
    expandirLinhas: "Rozbalit ({{linhas}} řádků)",
    mudarIdioma: "Změnit jazyk",
    procurarIdioma: "Hledat kód jazyka…",
    nenhumIdioma: "Žádný takový jazyk.",
    quebrarTexto: "Zalamovat text",
  },
  caixa: {
    escrever: "Napiš na #{{canal}}",
    escreverSemCanal: "Napiš zprávu",
    semPermissao: "Nemáš oprávnění posílat zprávy v tomto kanálu",
    solteParaAnexar: "Pusť pro přiložení",
    longaTitulo: "Zpráva je příliš dlouhá…",
    longaDescricao: "Dosáhl jsi limitu {{limite}} znaků. Můžeš ji poslat jako soubor.",
    enviarComoArquivo: "Poslat jako soubor",
    textoComoArquivo: "Poslat text jako soubor",
    arquivoGrandeTitulo: "Soubor je příliš velký",
    arquivoGrandeDescricao: "„{{arquivo}}“ překračuje limit {{limite}} MB na soubor.",
    respondendoPara: "Odpověď pro",
    vaiNotificar: "Dostane upozornění",
    naoVaiNotificar: "Upozornění nedostane",
    ligado: "zapnuto",
    desligado: "vypnuto",
    pararDeResponder: "Přestat odpovídat",
    mais: "Více",
    enviarArquivo: "Poslat soubor",
    criarEnquete: "Vytvořit anketu",
    expressoes: "Emoji, GIFy a samolepky",
    enviar: "Odeslat",
    aguardandoEnvio: "Čeká se na nahrání",
    modoLento: "Pomalý režim zapnutý ({{tempo}})",
    modoLentoDica: "Pomalý režim je nastavený na {{segundos}} s. Počkej, než pošleš další zprávu.",
  },
  anexos: {
    enviando: "Nahrávání…",
    modificar: "Upravit {{arquivo}}",
    verPrevia: "Náhled {{arquivo}}",
    excluirTitulo: "Smazat přílohu",
    excluirDescricao: "Smazat „{{arquivo}}“? Nejde to vrátit a příloha zmizí z této zprávy.",
    excluirAcao: "Smazat přílohu",
    excluirFalhou: "Přílohu se nepodařilo smazat.",
    remover: "Odebrat {{arquivo}}",
    ver: "Zobrazit {{arquivo}}",
    mostrarSpoiler: "Zobrazit spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Upravit přílohu",
    nomeDoArquivo: "Název souboru",
    descricao: "Popis alternativního textu",
    descricaoDica: "Popiš tento obsah pro čtečky obrazovky",
    marcarSpoiler: "Označit jako spoiler",
    cancelar: "Zrušit",
    salvar: "Uložit",
  },
  cartao: {
    tocador: "Přehrávač",
    abrir: "Otevřít {{destino}}",
    tocar: "Přehrát {{titulo}}",
    video: "video",
    verImagem: "Zobrazit obrázek",
  },
  enquete: {
    titulo: "Anketa",
    encerrada: "Anketa uzavřena",
    variasRespostas: "Anketa — více odpovědí",
    umVoto: "{{quantidade}} hlas",
    votos: "{{quantidade}} hlasů",
    umVotoNoTotal: "{{quantidade}} hlas celkem",
    votosNoTotal: "{{quantidade}} hlasů celkem",
    encerraEm: "končí {{quando}}",
    encerrarAgora: "Uzavřít teď",
  },
  fixadas: {
    titulo: "Připnuté zprávy",
    vazio: "Tenhle kanál nemá připnuté zprávy… zatím.",
    desafixar: "Odepnout",
    anexo: "(příloha)",
    enquete: "(anketa)",
    dicaRotulo: "TIP:",
    dica: "kdo má oprávnění „Spravovat zprávy“, může připnout přímo z nabídky zprávy.",
  },
  encaminhar: {
    titulo: "Přeposlat zprávu",
    paraOnde: "Kam?",
    semTexto: "(zpráva bez textu)",
    nenhumLugar: "Žádné místo s tímhle názvem.",
    canais: "Kanály",
    conversas: "Přímé zprávy",
  },
  expressoes: {
    gifs: "GIFy",
    buscarGifs: "Hledat v Klipy",
    figurinha: "Samolepka",
    buscarFigurinha: "Najdi dokonalou samolepku",
    buscarEmoji: "Najdi dokonalé emoji",
    buscarReacao: "Najdi dokonalou reakci",
    adicionarEmoji: "Přidat emoji",
    limparBusca: "Vymazat hledání",
  },
  busca: {
    fechar: "Zavřít hledání",
    procurando: "Hledám…",
    resultado: "{{quantos}} výsledek",
    resultados: "{{quantos}} výsledků",
    nadaCom: "Nic s {{termo}} tady není.",
    soOsQuePodeLer: "Hledání se dívá jen do kanálů, které můžeš číst.",
  },
  entrada: {
    titulo: "Doručená pošta",
    naoLidas: "Nepřečtené",
    salvas: "Uložené",
    mencoes: "Zmínky",
    fimTitulo: "Došel jsi na konec",
    fimDetalhe: "Nic dalšího ke čtení. Až přijde nová zpráva, objeví se tady.",
    semSalvosTitulo: "Nic uloženého",
    semSalvosDetalhe: "Podrž Shift a klikni na záložku zprávy, aby sis ji nechal a přečetl později.",
    tirarDosSalvos: "Odebrat z uložených",
    semMencoesTitulo: "Zatím žádné zmínky",
    semMencoesDetalhe: "Zmínky o tobě se tu objevují za posledních 7 dní.",
  },
  forum: {
    descricao: "Každé téma se stane vlastním rozhovorem — dobré na dotaz, který se nesmí ztratit uprostřed povídání.",
    novoAssunto: "Nové téma",
    vazio: "Zatím žádná témata. Začni první a rozhovor zůstane uspořádaný od začátku.",
    titulo: "Název",
    doQueSeTrata: "O co jde?",
    primeiraMensagem: "První zpráva",
    conteDoCaso: "Popiš to",
  },
};
