export const perfil = {
  carregando: "Načítání…",
  editar: "Upravit profil",
  mensagem: "Zpráva",
  abrirConversa: "Otevřít konverzaci",
  verCompleto: "Zobrazit celý profil",
  convidarParaServidor: "Pozvat na server",
  semServidores: "Nemáš žádné servery",
  conviteEnviado: "Pozvánka odeslána uživateli {{nome}}.",
  moderador: "Otevřít v zobrazení moderátora",
  mais: "Více",
  ignorar: "Ignorovat",
  deixarDeIgnorar: "Přestat ignorovat",
  copiarId: "Kopírovat ID uživatele",
  idCopiado: "ID zkopírováno.",
  conexoes: "Připojení",
  membroDesde: "Členem od",
  sobre: "O mně",
  cargosTitulo: "Role",
  visaoGeral: "Přehled",
  amigosEmComum: "Společní přátelé ({{quantidade}})",
  servidoresEmComum: "Společné servery ({{quantidade}})",
  amizade: {
    amigo: "Přítel",
    pedidoEnviado: "Žádost o přátelství odeslána",
    respondaAbaixo: "Poslal ti žádost — odpověz níže",
    adicionar: "Přidat mezi přátele",
    teMandouPedido: "Poslal ti žádost o přátelství",
    aceitar: "Přijmout",
    desfazer: "Zrušit přátelství",
    desfazerTitulo: "Odebrat {{nome}} z přátel?",
    desfazerDescricao: "Přestanete být přátelé. Soukromá konverzace zůstane v historii a později ho můžeš přidat znovu.",
    bloquear: "Zablokovat",
    bloquearTitulo: "Zablokovat {{nome}}?",
    bloquearDescricao: "Přestanete být přátelé, soukromá konverzace přestane přijímat zprávy a tento člověk ti už nemůže poslat žádost o přátelství.",
    linkCopiado: "Nejste přátelé — odkaz byl zkopírován, abys mu ho poslal.",
  },
  recado: {
    escrever: "Napiš @{{usuario}}",
    enviar: "Odeslat",
    enviada: "Zpráva odeslána",
    falhou: "Nepodařilo se odeslat. Zkus to z konverzace.",
  },
  cartao: {
    trocarFaixa: "Změnit banner karty",
    trocarFaixaCurto: "Změnit banner",
    trocarFoto: "Změnit profilovou fotku",
    trocarFotoCurto: "Změnit fotku",
    suaEtiqueta: "Tvůj štítek",
    editarEtiqueta: "Klikni pro úpravu štítku",
    conteAlgo: "Napiš něco o sobě",
    adicionarStatus: "Přidat stav",
    adicionarDescricao: "Klikni pro přidání popisu",
    cargo: "Role",
    cargos: "Role",
    cargosCom: "Role — {{quantidade}}",
    tirarCargo: "Odebrat roli {{cargo}}",
  },
  cargos: {
    adicionar: "Přidat roli",
    procurar: "Hledat roli",
  },
  etiqueta: {
    escolher: "Vybrat štítek serveru",
    nenhuma: "Žádný štítek serveru",
    semEtiqueta: "Žádný z tvých serverů nemá štítek",
  },
  emblemas: {
    doServidor: "Odznaky z tohoto serveru",
    limite: "Můžeš nosit až {{quantidade}} odznaků.",
  },
  nota: {
    vazia: "Klikni a poznamenej si něco",
    rotulo: "Poznámka (vidíš ji jen ty)",
  },
  status: {
    titulo: "Stav",
    definir: "Nastavit svůj stav",
    escolherEmoji: "Vybrat emoji",
    tirarEmoji: "Odebrat emoji",
    oQuePensa: "Na co myslíš?",
    limparAgora: "Vymazat stav teď",
    naoLimpar: "Nemazat",
    limpar30m: "Vymazat za 30 minut",
    limpar1h: "Vymazat za 1 hodinu",
    limpar4h: "Vymazat za 4 hodiny",
    limparHoje: "Vymazat dnes",
    limparAmanha: "Vymazat zítra",
    comHora: "{{prazo}} v {{hora}}",
  },
  presenca: {
    disponivel: "Dostupný",
    ausente: "Nepřítomen",
    naoPerturbar: "Nerušit",
    naoPerturbarDetalhe: "Nedostáváš upozornění na nové zprávy",
    invisivel: "Neviditelný",
    invisivelDetalhe: "Ostatním se jevíš offline",
  },
  menu: {
    mudarDeConta: "Přepnout účet",
    gerenciarContas: "Spravovat účty",
  },
  editor: {
    decoracao: "Změnit dekoraci avatara",
    naoSalvo: "Nezapomeň uložit změny!",
    principal: "Hlavní profil",
  },
};
