export const servidor = {
  comunidade: {
    ativa: "Komunita je otevřená",
    ativaDesde: "Otevřená od {{quando}}",
    membrosAgora: "{{quantos}} členů",
    criarParaMim: "Vytvořit za mě",
    canalDeRegras: "Kanál s pravidly",
    canalDeRegrasDetalhe: "Místo s pravidly, která si každý přečte, než začne psát.",
    canalDeAvisos: "Kanál s oznámeními komunity",
    canalDeAvisosDetalhe: "Sem posíláme, co se tu mění — jen pro ty, kdo spravují.",
    canalDeSeguranca: "Kanál s bezpečnostními upozorněními",
    canalDeSegurancaDetalhe: "Sem dostane moderace to, co filtry zachytily.",
    idiomaPrincipal: "Hlavní jazyk",
    idiomaPrincipalDetalhe: "Jazyk, ve kterém probíhá většina hovoru.",
    semIdioma: "Žádný vybraný jazyk",
    semCanal: "Žádný kanál",
    finalTitulo: "Skoro hotovo",
    finalDetalhe: "Než otevřete, podívejte se, co se mění pro nově příchozí.",
    confereRegras: "Kdo přijde, vidí nejdřív kanál s pravidly.",
    confereEveryone: "@everyone a @here používají jen lidé s rolí.",
    confereMencoes: "Označit všechny naráz nově vyžaduje oprávnění.",
    concordo: "Souhlasím a rozumím",
    concordoDetalhe: "Potvrzujete, že se komunita drží pravidel platformy.",
    proximo: "Dál",
    terminar: "Dokončit nastavení",
    visaoGeral: "Přehled",
    visaoGeralDetalhe: "Kanály, kterými komunita mluví s nově příchozími.",
    seguranca: "Bezpečnost",
    segurancaDetalhe: "Brzdy, které drží spam a těžký obsah.",
    habilitada: "Komunita je zapnutá.",
    falhou: "Komunitu se nepodařilo zapnout.",
    titulo: "Komunita",
    ilustracao: "Bubliny s řečí",
    convite: "Stavíte komunitu?",
    conviteDetalhe: "Udělejte z něj komunitu a získáte nástroje pro velké místo: kanál s pravidly, oznámení od nás a filtry, které moderují samy.",
    contagem: "{{membros}} z {{minimo}} členů",
    faltam: "Chybí {{quantos}} k otevření.",
    prontoParaAbrir: "Už to jde otevřít.",
    habilitar: "Zapnout komunitu",
    vantagemCrescer: "Růst",
    vantagemCrescerDetalhe: "Komunita se může přihlásit do Objevovat a lidé hledající vaše téma vás najdou.",
    vantagemModerar: "Moderovat",
    vantagemModerarDetalhe: "Vyžadovat ověřený e-mail, filtrovat média a zapnout AutoMod naráz.",
    vantagemAvisos: "Vědět o změnách",
    vantagemAvisosDetalhe: "Posíláme, co se mění, těm, kdo tu spravují — do kanálu jen pro vás.",
    assistenteTitulo: "Pojďme nastavit vaši komunitu.",
    passoSeguranca: "Bezpečnostní kontroly",
    passoBasico: "Základní příprava",
    passoFinal: "Poslední úpravy",
    seguraTitulo: "Udržte komunitu v bezpečí",
    seguraDetalhe: "Velká komunita láká spam. Tyto dvě brzdy jsou zapnuté; později je můžete vypnout, kdyby překážely.",
    emailVerificado: "Vyžadovat ověřený e-mail",
    emailVerificadoDetalhe: "Kdo si ještě nepotvrdil e-mail, nepíše. Lidé s rolí projdou.",
    filtroDeMidia: "Filtrovat explicitní média",
    filtroDeMidiaDetalhe: "Obrázky a videa přicházejí schované a ukážou se, až když si je někdo rozklikne.",
    basicoTitulo: "Připravte základ",
    basicoDetalhe: "Řekněte, ve kterém kanálu jsou pravidla a kam mají chodit naše oznámení. Bez vybraného kanálu oba vytvořím.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} příkazů",
    previa: "Jak karta vypadá",
    trocarIcone: "Změnit ikonu",
    tirarCapa: "Odebrat obálku",
    heroComunidades: "Někdo si právě povídá o tom, co máte rádi",
    heroComunidadesDetalhe: "Komunity, které založili lidé odsud. Vejděte, přečtěte si, o čem se mluví, a zůstaňte, jestli se vám to sedne.",
    emDestaque: "Vybrané",
    todasAsComunidades: "Ty ostatní",
    heroTitulo: "Co dneska vaše parta použije?",
    heroDetalhe: "Boti na hudbu, hraní a moderování, od lidí, co jsou tu s vámi. Vyberte si a bot vejde na server.",
    novidades: "Právě dorazily",
    todosOsApps: "Ty ostatní",
    lojaTitulo: "Stránka aplikace",
    lojaDetalhe: "Tohle uvidí v Objevovat ten, kdo ji ještě nezná.",
    capa: "Obálka",
    capaDetalhe: "Široký obrázek nahoře na stránce. 1280 × 720 sedne.",
    trocarCapa: "Změnit obálku",
    categorias: "Kategorie",
    categoriasDetalhe: "Až {{quantas}}. Podle nich se v Objevovat prochází.",
    idiomas: "Jazyky",
    idiomasDetalhe: "Až {{quantos}}. V jakých jazycích aplikace odpovídá.",
    termos: "Podmínky použití",
    politica: "Zásady soukromí",
    politicas: "Zásady",
    servidorDeSuporte: "Server podpory",
    servidorDeSuporteDetalhe: "Kam míří ten, kdo potřebuje s aplikací pomoct.",
    semServidor: "Žádný",
    emQuantosServidores: "Na kolika serverech",
    categoria: {
      GAMES: "Hry",
      MUSICA: "Hudba",
      MODERACAO: "Moderování",
      PRODUTIVIDADE: "Produktivita",
      SOCIAL: "Sociální",
      UTILIDADES: "Nástroje",
      ARTE_E_CRIACAO: "Umění a tvorba",
      EDUCACAO: "Vzdělávání",
      OUTRA: "Jiné",
    },
    appIndisponivel: "Aplikace není dostupná",
    voltarParaExplorar: "Zpět na Objevovat",
    adicionarApp: "Přidat aplikaci",
    copiarLink: "Zkopírovat odkaz",
    denunciarApp: "Nahlásit aplikaci",
    copiarIdDoApp: "Zkopírovat ID aplikace",
    visaoGeral: "Přehled",
    comandos: "Příkazy",
    permissoes: "Oprávnění",
    semPermissoes: "Tato aplikace nežádá o žádná oprávnění.",
    avisoDePermissoes: "Přichází s vlastní rolí. Oprávnění můžete změnit později v Nastavení komunity → Role.",
    servidoresEmComum: "Společné komunity",
    umServidorEmComum: "1 komunita",
    quantosServidoresEmComum: "Komunit: {{quantos}}",
    feitoPor: "Vytvořil",
    publicadoEm: "Zveřejněno",
    denunciarNome: "Nahlásit {{nome}}",
    denunciaDetalhe: "Hlášení jde týmu Gravaê. Autor aplikace se nedozví, že jste to byli vy.",
    denunciaFalhou: "Hlášení se nepodařilo odeslat.",
    umMembro: "1 člen",
    semDescricao: "Bez popisu.",
    adicionar: "Přidat",
    jaEstaAqui: "Už jste tady",
    entrando: "Vstupuji…",
    entrar: "Vstoupit",
    comunidadePublica: "Veřejná komunita",
    online: "{{quantos}} online",
    membros: "{{quantos}} členů",
    abrirComunidade: "Otevřít komunitu",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Nastavení serveru",
  novasMensagens: "Nové zprávy",
  menu: {
    silenciar: "Ztlumit komunitu",
    reativar: "Zapnout komunitu",
    porQuinze: "Na 15 minut",
    porMeiaHora: "Na 30 minut",
    porTresHoras: "Na 3 hodiny",
    porTresDias: "Na 3 dny",
    porUmaHora: "Na 1 hodinu",
    porOitoHoras: "Na 8 hodin",
    porUmDia: "Na 24 hodin",
    ateReativar: "Dokud to nezapnu",
    notificacoes: "Nastavení oznámení",
    padrao: "Použít výchozí",
    todas: "Všechny zprávy",
    soMencoes: "Jen zmínky",
    nada: "Nic",
    ocultarSilenciados: "Skrýt ztlumené kanály",
    denunciar: "Nahlásit komunitu",
    marcarLida: "Označit jako přečtené",
    convidar: "Pozvat členy",
    editarPerfil: "Upravit profil komunity",
    configuracoes: "Nastavení komunity",
    sair: "Opustit komunitu",
    sairTitulo: "Opustit {{nome}}?",
    sairDescricao: "K návratu budeš potřebovat novou pozvánku.",
    copiarId: "Kopírovat ID komunity",
    idCopiado: "ID zkopírováno.",
  },
  convite: {
    cartaoTitulo: "Máte pozvánku do komunity",
    indisponivel: "Pozvánka není dostupná",
    indisponivelDetalhe: "Vypršela, došla, nebo ji ten, kdo ji vytvořil, smazal.",
    entrar: "Vstoupit do komunity",
    chamado: "Máš pozvánku do",
    aceitarComo: "Přijmout jako {{nome}}",
    abrir: "Otevřít komunitu",
    recusar: "Ne, díky",
  },
  pasta: {
    silenciarTodas: "Ztlumit komunity",
    reativarTodas: "Zapnout komunity",
    mostrarSilenciados: "Zobrazit ztlumené kanály",
    notificacoesDaComunidade: "Nastavení oznámení",
    silenciarEveryone: "Ztlumit @everyone a @here",
    permitirEveryone: "Povolit @everyone a @here",
    silenciarCargos: "Ztlumit zmínky rolí",
    permitirCargos: "Povolit zmínky rolí",
    dicaDaCor: "Napiš barvu (hex, rgb(), hsl() nebo název) nebo použij výběr.",
    mostrarIcone: "Zobrazit ikonu po zavření",
    dicaDoIcone: "Zavřená ukazuje ikonu místo serverů uvnitř.",
    icone: "Ikona složky",
    excluir: "Smazat složku",
    icones: {
      pasta: "Složka",
      estrela: "Oblíbené",
      coracao: "Srdce",
      salvar: "Uložit",
      jogo: "Ovladač",
      escudo: "Štít",
      nota: "Nota",
    },
    marcarLida: "Označit složku jako přečtenou",
    configuracoes: "Nastavení složky",
    desfazer: "Zrušit složku",
    titulo: "Složka",
    nome: "Název",
    semNome: "Bez názvu",
    cor: "Barva",
    semCor: "Bez barvy",
    salvar: "Uložit",
  },
  denuncia: {
    titulo: "Nahlásit {{nome}}",
    descricao: "Hlášení jde týmu Gravaê. Popiš, co se stalo.",
    motivo: "Důvod",
    detalhes: "Podrobnosti (nepovinné)",
    enviar: "Odeslat hlášení",
    enviada: "Hlášení odesláno. Díky.",
    motivos: {
      spam: "Spam nebo reklama",
      assedio: "Obtěžování nebo nenávist",
      conteudo: "Nevhodný obsah",
      golpe: "Podvod",
      outro: "Jiné",
    },
  },
  selos: {
    verificada: "Ověřená komunita",
    detectavel: "Objevitelná komunita",
  },
  auditoria: {
    todasAsAcoes: "Všechny akce",
    todosOsUsuarios: "Všichni uživatelé",
    filtroMembros: "Členové",
    filtroCanais: "Kanály",
    filtroEmojis: "Emoji",
    filtroServidor: "Server",
    titulo: "Záznam akcí",
    porUsuario: "Filtrovat podle člověka",
    porAcao: "Filtrovat podle akce",
    vazio: "S tímto filtrem zatím nic nezaznamenáno.",
    motivo: "Důvod:",
  },
  banimentos: {
    titulo: "Seznam banů serveru",
    descricao: "Kdo je tady, nedostane se zpět ani s novou pozvánkou. Odbanování vrátí přístup okamžitě.",
    procurar: "Hledat bany podle uživatelského jména",
    vazioTitulo: "Žádné bany",
    vazio: "Ještě jsi nikoho nezabanoval… ale až to bude potřeba, neváhej.",
    desbanir: "Odbanovat",
  },
  excluir: {
    tudoVai: "Všechny kanály, zprávy a pozvánky serveru {{servidor}} budou smazány pro {{membros}} členů. Nikdo je pak nevrátí.",
    digite: "Napiš {{servidor}} pro potvrzení",
    titulo: "Smazat server",
    aviso: "Tohle nejde vzít zpět.",
  },
  emblemas: {
    apagarDescricao: "Zmizí každému, kdo ho nosí. Nejde to vrátit.",
    titulo: "Odznaky",
    vazio: "Zatím žádné odznaky.",
    novo: "Nový odznak",
  },
  convites: {
    revogarTitulo: "Zrušit pozvánku?",
    revogarAcao: "Zrušit",
    revogarDescricao: "Odkaz {{codigo}} okamžitě přestane fungovat. Kdo přes něj už přišel, na serveru zůstává.",
    titulo: "Pozvánky",
    descricao: "Všechny aktivní pozvánkové odkazy tohoto serveru.",
    vazio: "Zatím nebyla vytvořena žádná pozvánka.",
    revogar: "Zrušit pozvánku",
  },
  integracoes: {
    opcionais: "username a avatar_url jsou nepovinné a platí na zprávu. Limit je 5 zpráv za 5 sekund.",
    apagarDescricao: "URL okamžitě přestane fungovat. Zprávy, které už poslal, v kanálu zůstávají.",
    titulo: "Integrace",
    descricao: "Webhook je adresa, která píše do kanálu bez potřeby účtu. Hodí se oznámit, že build prošel, že někdo otevřel ticket, nebo cokoli chceš poslat ze skriptu.",
    novo: "Nový webhook",
    vazio: "Zatím žádné webhooky. Vytvoř jeden a vlož URL tam, odkud má zpráva přicházet.",
    canal: "Kanál",
    apagar: "Smazat webhook",
    comoUsar: "Jak na to",
    comoUsarTexto: "Pošli POST s JSON:",
  },
  explorar: {
    titulo: "Objevovat",
  },
  engajamento: {
    semCanal: "Bez systémového kanálu",
    titulo: "Zapojení",
    descricao: "Co server dělá sám, aby nepůsobil prázdně, když přijde někdo nový.",
    sistema: "Systémové zprávy",
    boasVindas: "Poslat uvítání, když někdo přijde",
    sorteio: "Bez vlastního textu níž se věta losuje — pořád stejná rychle omrzí.",
    canalDoSistema: "Kanál systémových zpráv",
    mensagem: "Uvítací zpráva",
    deixeVazio: "Nech prázdné, ať se losuje z hotových vět",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtry, které moderují samy, ještě než zpráva vznikne. Kdo spravuje server, nikdy filtrován není — a osvobozené role projdou rovnou.",
    palavras: {
      titulo: "Blokovat vlastní slova",
      descricao: "Tvůj seznam slov, která nikdo nesmí napsat.",
    },
    mencoes: {
      titulo: "Blokovat spam zmínkami",
      descricao: "Zablokuje zprávu s příliš mnoha zmínkami najednou.",
    },
    links: {
      titulo: "Blokovat odkazy",
      descricao: "Zadrží každou adresu vloženou do chatu.",
    },
    definir: "Nastavit",
    nomeDaRegra: "Název pravidla",
    bloqueadas: "Blokovaná slova",
    digiteEnter: "Napiš a stiskni Enter",
    comparacao: "Porovnání ignoruje velikost písmen, diakritiku a interpunkci — a nechytá slovo uvnitř jiného.",
    aPartirDe: "Blokovat od kolika zmínek",
    oQueFazer: "Co udělat",
    canalDoAlerta: "Kanál upozornění",
    escolhaCanal: "Vyber kanál",
    castigo: "Umlčení (minuty)",
    isentos: "Osvobozené role",
    semCargos: "Zatím nebyla vytvořena žádná role.",
    salvarRegra: "Uložit pravidlo",
    apagar: "Smazat pravidlo",
    excluirTitulo: "Smazat toto pravidlo AutoModu?",
    excluirDescricao: "Server podle něj okamžitě přestane filtrovat. Vytvořit ho jde znovu, ale současné nastavení se ztratí.",
    excluirAcao: "Smazat pravidlo",
  },
  cargos: {
    titulo: "Role",
    descricao: "Role dávají jméno, barvu a pravomoci. Kdo je výš v seznamu, velí těm níž — a nikdo nesahá na roli stejnou nebo vyšší, než má sám.",
    criar: "Vytvořit roli",
    vazio: "Zatím žádné role.",
    abaExibicao: "Vzhled",
    abaPermissoes: "Oprávnění",
    abaMembros: "Členové — {{quantos}}",
    everyone: "Platí pro všechny na serveru. Je to základ, na který se ostatní role přičítají.",
    nomeDoCargo: "Název role",
    cor: "Barva role",
    corDica: "Obarví jméno toho, kdo roli má, v seznamu členů a v chatu.",
    semCor: "Bez barvy",
    corPersonalizada: "Vlastní barva",
    estilo: "Styl jména",
    segundaCor: "Druhá barva",
    segundaCorDica: "Bez ní se přechod vrátí k jedné barvě — nezmizí.",
    limparSegundaCor: "Vymazat druhou barvu",
    icone: "Ikona",
    iconeDica: "Objeví se vedle role na kartě profilu toho, kdo ji má.",
    exibirSeparado: "Zobrazovat odděleně od ostatních členů",
    exibirSeparadoDica: "Role dostane vlastní sekci v seznamu členů.",
    permitirMencionar: "Povolit zmiňování této role",
    permitirMencionarDica: "Kdokoli bude moct upozornit všechny, kdo tu roli mají.",
    semPoderDeConceder: "{{descricao}} (tohle oprávnění nemáš, abys ho udělil)",
    adicionar: "Přidat někoho do této role",
    tirar: "Odebrat roli",
    semNinguem: "Tuhle roli zatím nikdo nemá.",
    apagar: "Smazat roli",
    excluirTitulo: "Smazat roli „{{nome}}\"?",
    excluirDescricao: "Kdo tuhle roli má, přijde o všechno, co dávala. Nejde to vrátit.",
    excluirAcao: "Smazat roli",
  },
  membros: {
    procurar: "Hledat podle jména nebo uživatelského jména",
    membroDesde: "Členem od",
    vazio: "Nikdo nenalezen.",
    acoesPara: "Akce pro {{nome}}",
    deCastigo: "umlčení",
    tirarCastigo: "Zrušit umlčení",
    castigo5min: "5 minut",
    castigo1h: "1 hodina",
    castigo1d: "1 den",
    castigo1s: "1 týden",
    expulsar: "Vyhodit",
    expulsarTitulo: "Vyhodit {{nome}}?",
    expulsarDescricao: "okamžitě opouští {{servidor}}. Může se vrátit s pozvánkou — vyhození návrat nebrání.",
    banir: "Zabanovat",
    banirTitulo: "Zabanovat {{nome}}?",
    banirDescricao: "opouští {{servidor}} a nevrátí se ani s pozvánkou, dokud mu ban nesundáš.",
    motivo: "Důvod (nepovinné)",
    motivoDica: "Zůstane v záznamu akcí",
  },
  perfil: {
    titulo: "Profil serveru",
    descricao: "Takhle se tvůj server ukazuje v seznamu a v pozvánkových odkazech.",
    icone: "Ikona",
    faixa: "Banner nahoře",
    nomeDoServidor: "Název serveru",
    campoDescricao: "Popis",
    doQueE: "O čem tenhle server je?",
    comprimido: "Zkomprimováno před nahráním: {{economia}}",
  },
  etiqueta: {
    titulo: "Značka serveru",
    descricao: "Štítek do 4 písmen, který se ukazuje vedle jména každého člena — v chatu i v seznamu lidí. Tady je zdarma: bez boostů, bez úrovní.",
    escolhaNome: "Vyber název",
    limite: "Nejvýš 4 znaky, písmena a čísla.",
    escolhaInsignia: "Vyber odznak",
    voce: "Ty",
    fala1: "má někdo chuť hrát?",
    fala2: "mrkni na moji značku!",
    fala3: "ty jo, jak jsi to sehnal",
  },
  expressoes: {
    comoUsar: "Přidej až {{limite}} emoji, které může používat každý na tomhle serveru. Napiš :jméno: do chatu a pošleš ho.",
    imagem: "Obrázek",
    enviadoPor: "Nahrál",
    semEmoji: "Zatím žádná emoji.",
    figurinhas: "Samolepky",
    enviarFigurinha: "Nahrát samolepku",
    nomeDaFigurinha: "Název samolepky",
    exemploFigurinha: "Např.: kočičí objetí",
    figurinhaGrande: "Samolepka přesahuje {{limite}}.",
    deixaPraLa: "Nech to být",
    sons: "Panel zvuků",
    enviarSom: "Nahrát zvuk",
    nomeDoSom: "Název zvuku",
    semSom: "Zatím žádné zvuky.",
    somGrande: "Zvuk přesahuje {{limite}}.",
    emojiRelacionado: "Související emoji",
    ouvir: "Přehrát",
    ouvirAssim: "Přehrát takhle",
    volumeDe: "Hlasitost {{nome}}",
    volumeDica: "Platí pro všechny na serveru. Každý si stejně může zvuky ztlumit jen pro sebe, v panelu hovoru.",
    falhaEnvio: "Soubor se nepodařilo nahrát.",
    excluirTitulo: "Smazat {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Zmizí ze serveru všem. Zprávy, které ho už použily, zůstanou, jak jsou.",
  },
  canal: {
    tipoLink: "Odkaz",
    tipoLinkDica: "Míří na adresu venku a otevře se v prohlížeči",
    endereco: "Adresa",
    enderecoDica: "Kam tento kanál vede. Musí začínat na https://",
    visaoGeral: "Přehled",
    nome: "Název kanálu",
    topico: "Téma kanálu",
    topicoDica: "O čem se tu mluví?",
    modoLento: "Každý pošle jen jednu zprávu za interval. Kdo spravuje zprávy nebo kanály, projde rovnou.",
    visibilidade: "Viditelnost obsahu",
    padrao: "Výchozí",
    padraoDica: "Obsah kanálu je vždycky vidět.",
    spoiler: "Kanál se spoilery",
    spoilerDica: "Označ tenhle kanál jako se spoilery, aby zvraty a těžká témata zůstala schovaná, dokud se na ně někdo nechce podívat.",
    idade: "Kanál s věkovým omezením",
    idadeDica: "Kdo vejde, musí potvrdit plnoletost, aby obsah viděl.",
    bitrateDica: "Nad 64 kbps to může vadit lidem se špatným připojením.",
    qualidadeDeVideo: "Kvalita videa",
    automatica: "Automatická",
    limite: "Limit uživatelů — {{valor}}",
    pessoas: "{{quantos}} lidí",
    semLimite: "bez limitu",
    permissoesDescricao: "Tady měníš, co platí v tomhle kanálu. Co zůstane na „zdědit\", dál sleduje roli.",
    excluir: {
      titulo: "Smazat kanál",
      historico: "Celá historie kanálu {{canal}} jde s ním, všem.",
      digite: "Napiš {{canal}} pro potvrzení",
    },
  },
  moderacao: {
    titulo: "Pohled moderátora",
    semPermissao: "Potřebuješ oprávnění „Moderovat členy\", abys tohle viděl.",
    fecharEsc: "Zavřít (Esc)",
    atividade: "Aktivita na serveru",
    mensagens: "Zprávy",
    links: "Odkazy",
    midia: "Média",
    acoesNaAuditoria: "Akce v záznamu",
    moderacoesSofridas: "Obdržené moderace",
    permissoes: "Oprávnění ({{quantas}})",
    semPermissaoEspecial: "Žádná zvláštní oprávnění.",
    conta: "Účet",
    entrouNoServidor: "Přišel na server",
    contaCriadaEm: "Účet vytvořen",
    deCastigoAte: "Umlčen do",
    formaDeAdesao: "Jak se dostal dovnitř",
    mensagem: "Zpráva",
    castigo: "Umlčení",
    copiarId: "Kopírovat ID",
    idCopiado: "ID zkopírováno.",
    adicionarCargo: "Přidat roli",
    semCargos: "Žádná role nevytvořena",
    soEveryone: "Jen @everyone.",
    voltar: "Zpět",
    vazio: "Tady nic není.",
    cinquenta: "Zobrazuji 50 nejnovějších.",
    irParaMensagem: "Přejít na zprávu",
    precisaSerAmigo: "Abyste si psali, musíte být přátelé.",
    expulsarDescricao: "Okamžitě opouští server, ale může se vrátit s pozvánkou.",
    banirDescricao: "Opouští server a nevrátí se ani s pozvánkou, dokud mu ban nesundáš.",
    castigarTitulo: "Umlčet {{nome}}?",
    castigoDescricao: "Dokud trvá, nepíše ani nemluví v žádném kanálu serveru.",
    aplicarCastigo: "Použít umlčení",
    duracao: "Délka v minutách",
    informeDuracao: "Zadej délku v minutách.",
  },
  abas: {
    pesquisar: "Hledat v nastavení",
    semResultado: "Nic s tímhle názvem tu není.",
    comunidade: "Komunita",
    expressoes: "Výrazy",
    pessoas: "Lidé",
    apps: "Aplikace",
    moderacao: "Moderace",
    banimentos: "Bany",
  },
};
