export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Nastavení serveru",
  auditoria: {
    todasAsAcoes: "Všechny akce",
    todosOsUsuarios: "Všichni uživatelé",
    filtroMembros: "Členové",
    filtroCanais: "Kanály",
    filtroEmojis: "Emoji",
    filtroServidor: "Server",
    titulo: "Záznam akcí",
    porUsuario: "Filtrovat podle člověka",
    porAcao: "Filtrovat podle akce",
    vazio: "S tímto filtrem zatím nic nezaznamenáno.",
    motivo: "Důvod:",
  },
  banimentos: {
    titulo: "Seznam banů serveru",
    descricao: "Kdo je tady, nedostane se zpět ani s novou pozvánkou. Odbanování vrátí přístup okamžitě.",
    procurar: "Hledat bany podle uživatelského jména",
    vazioTitulo: "Žádné bany",
    vazio: "Ještě jsi nikoho nezabanoval… ale až to bude potřeba, neváhej.",
    desbanir: "Odbanovat",
  },
  excluir: {
    tudoVai: "Všechny kanály, zprávy a pozvánky serveru {{servidor}} budou smazány pro {{membros}} členů. Nikdo je pak nevrátí.",
    digite: "Napiš {{servidor}} pro potvrzení",
    titulo: "Smazat server",
    aviso: "Tohle nejde vzít zpět.",
  },
  emblemas: {
    apagarDescricao: "Zmizí každému, kdo ho nosí. Nejde to vrátit.",
    titulo: "Odznaky",
    vazio: "Zatím žádné odznaky.",
    novo: "Nový odznak",
  },
  convites: {
    revogarTitulo: "Zrušit pozvánku?",
    revogarAcao: "Zrušit",
    revogarDescricao: "Odkaz {{codigo}} okamžitě přestane fungovat. Kdo přes něj už přišel, na serveru zůstává.",
    titulo: "Pozvánky",
    descricao: "Všechny aktivní pozvánkové odkazy tohoto serveru.",
    vazio: "Zatím nebyla vytvořena žádná pozvánka.",
    revogar: "Zrušit pozvánku",
  },
  integracoes: {
    opcionais: "username a avatar_url jsou nepovinné a platí na zprávu. Limit je 5 zpráv za 5 sekund.",
    apagarDescricao: "URL okamžitě přestane fungovat. Zprávy, které už poslal, v kanálu zůstávají.",
    titulo: "Integrace",
    descricao: "Webhook je adresa, která píše do kanálu bez potřeby účtu. Hodí se oznámit, že build prošel, že někdo otevřel ticket, nebo cokoli chceš poslat ze skriptu.",
    novo: "Nový webhook",
    vazio: "Zatím žádné webhooky. Vytvoř jeden a vlož URL tam, odkud má zpráva přicházet.",
    canal: "Kanál",
    apagar: "Smazat webhook",
    comoUsar: "Jak na to",
    comoUsarTexto: "Pošli POST s JSON:",
  },
  explorar: {
    titulo: "Objevovat",
  },
  engajamento: {
    semCanal: "Bez systémového kanálu",
    titulo: "Zapojení",
    descricao: "Co server dělá sám, aby nepůsobil prázdně, když přijde někdo nový.",
    sistema: "Systémové zprávy",
    boasVindas: "Poslat uvítání, když někdo přijde",
    sorteio: "Bez vlastního textu níž se věta losuje — pořád stejná rychle omrzí.",
    canalDoSistema: "Kanál systémových zpráv",
    mensagem: "Uvítací zpráva",
    deixeVazio: "Nech prázdné, ať se losuje z hotových vět",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filtry, které moderují samy, ještě než zpráva vznikne. Kdo spravuje server, nikdy filtrován není — a osvobozené role projdou rovnou.",
    palavras: {
      titulo: "Blokovat vlastní slova",
      descricao: "Tvůj seznam slov, která nikdo nesmí napsat.",
    },
    mencoes: {
      titulo: "Blokovat spam zmínkami",
      descricao: "Zablokuje zprávu s příliš mnoha zmínkami najednou.",
    },
    links: {
      titulo: "Blokovat odkazy",
      descricao: "Zadrží každou adresu vloženou do chatu.",
    },
    definir: "Nastavit",
    nomeDaRegra: "Název pravidla",
    bloqueadas: "Blokovaná slova",
    digiteEnter: "Napiš a stiskni Enter",
    comparacao: "Porovnání ignoruje velikost písmen, diakritiku a interpunkci — a nechytá slovo uvnitř jiného.",
    aPartirDe: "Blokovat od kolika zmínek",
    oQueFazer: "Co udělat",
    canalDoAlerta: "Kanál upozornění",
    escolhaCanal: "Vyber kanál",
    castigo: "Umlčení (minuty)",
    isentos: "Osvobozené role",
    semCargos: "Zatím nebyla vytvořena žádná role.",
    salvarRegra: "Uložit pravidlo",
    apagar: "Smazat pravidlo",
    excluirTitulo: "Smazat toto pravidlo AutoModu?",
    excluirDescricao: "Server podle něj okamžitě přestane filtrovat. Vytvořit ho jde znovu, ale současné nastavení se ztratí.",
    excluirAcao: "Smazat pravidlo",
  },
  cargos: {
    titulo: "Role",
    descricao: "Role dávají jméno, barvu a pravomoci. Kdo je výš v seznamu, velí těm níž — a nikdo nesahá na roli stejnou nebo vyšší, než má sám.",
    criar: "Vytvořit roli",
    vazio: "Zatím žádné role.",
    abaExibicao: "Vzhled",
    abaPermissoes: "Oprávnění",
    abaMembros: "Členové — {{quantos}}",
    everyone: "Platí pro všechny na serveru. Je to základ, na který se ostatní role přičítají.",
    nomeDoCargo: "Název role",
    cor: "Barva role",
    corDica: "Obarví jméno toho, kdo roli má, v seznamu členů a v chatu.",
    semCor: "Bez barvy",
    corPersonalizada: "Vlastní barva",
    estilo: "Styl jména",
    segundaCor: "Druhá barva",
    segundaCorDica: "Bez ní se přechod vrátí k jedné barvě — nezmizí.",
    limparSegundaCor: "Vymazat druhou barvu",
    icone: "Ikona",
    iconeDica: "Objeví se vedle role na kartě profilu toho, kdo ji má.",
    exibirSeparado: "Zobrazovat odděleně od ostatních členů",
    exibirSeparadoDica: "Role dostane vlastní sekci v seznamu členů.",
    permitirMencionar: "Povolit zmiňování této role",
    permitirMencionarDica: "Kdokoli bude moct upozornit všechny, kdo tu roli mají.",
    semPoderDeConceder: "{{descricao}} (tohle oprávnění nemáš, abys ho udělil)",
    adicionar: "Přidat někoho do této role",
    tirar: "Odebrat roli",
    semNinguem: "Tuhle roli zatím nikdo nemá.",
    apagar: "Smazat roli",
    excluirTitulo: "Smazat roli „{{nome}}\"?",
    excluirDescricao: "Kdo tuhle roli má, přijde o všechno, co dávala. Nejde to vrátit.",
    excluirAcao: "Smazat roli",
  },
  membros: {
    procurar: "Hledat podle jména nebo uživatelského jména",
    membroDesde: "Členem od",
    vazio: "Nikdo nenalezen.",
    acoesPara: "Akce pro {{nome}}",
    deCastigo: "umlčení",
    tirarCastigo: "Zrušit umlčení",
    castigo5min: "5 minut",
    castigo1h: "1 hodina",
    castigo1d: "1 den",
    castigo1s: "1 týden",
    expulsar: "Vyhodit",
    expulsarTitulo: "Vyhodit {{nome}}?",
    expulsarDescricao: "okamžitě opouští {{servidor}}. Může se vrátit s pozvánkou — vyhození návrat nebrání.",
    banir: "Zabanovat",
    banirTitulo: "Zabanovat {{nome}}?",
    banirDescricao: "opouští {{servidor}} a nevrátí se ani s pozvánkou, dokud mu ban nesundáš.",
    motivo: "Důvod (nepovinné)",
    motivoDica: "Zůstane v záznamu akcí",
  },
  perfil: {
    titulo: "Profil serveru",
    descricao: "Takhle se tvůj server ukazuje v seznamu a v pozvánkových odkazech.",
    icone: "Ikona",
    faixa: "Banner nahoře",
    nomeDoServidor: "Název serveru",
    campoDescricao: "Popis",
    doQueE: "O čem tenhle server je?",
    comprimido: "Zkomprimováno před nahráním: {{economia}}",
  },
  etiqueta: {
    titulo: "Značka serveru",
    descricao: "Štítek do 4 písmen, který se ukazuje vedle jména každého člena — v chatu i v seznamu lidí. Tady je zdarma: bez boostů, bez úrovní.",
    escolhaNome: "Vyber název",
    limite: "Nejvýš 4 znaky, písmena a čísla.",
    escolhaInsignia: "Vyber odznak",
    voce: "Ty",
    fala1: "má někdo chuť hrát?",
    fala2: "mrkni na moji značku!",
    fala3: "ty jo, jak jsi to sehnal",
  },
  expressoes: {
    comoUsar: "Přidej až {{limite}} emoji, které může používat každý na tomhle serveru. Napiš :jméno: do chatu a pošleš ho.",
    imagem: "Obrázek",
    enviadoPor: "Nahrál",
    semEmoji: "Zatím žádná emoji.",
    figurinhas: "Samolepky",
    enviarFigurinha: "Nahrát samolepku",
    nomeDaFigurinha: "Název samolepky",
    exemploFigurinha: "Např.: kočičí objetí",
    figurinhaGrande: "Samolepka přesahuje {{limite}}.",
    deixaPraLa: "Nech to být",
    sons: "Panel zvuků",
    enviarSom: "Nahrát zvuk",
    nomeDoSom: "Název zvuku",
    semSom: "Zatím žádné zvuky.",
    somGrande: "Zvuk přesahuje {{limite}}.",
    emojiRelacionado: "Související emoji",
    ouvir: "Přehrát",
    ouvirAssim: "Přehrát takhle",
    volumeDe: "Hlasitost {{nome}}",
    volumeDica: "Platí pro všechny na serveru. Každý si stejně může zvuky ztlumit jen pro sebe, v panelu hovoru.",
    falhaEnvio: "Soubor se nepodařilo nahrát.",
    excluirTitulo: "Smazat {{tipo}} „{{nome}}\"?",
    excluirDescricao: "Zmizí ze serveru všem. Zprávy, které ho už použily, zůstanou, jak jsou.",
  },
  canal: {
    visaoGeral: "Přehled",
    nome: "Název kanálu",
    topico: "Téma kanálu",
    topicoDica: "O čem se tu mluví?",
    modoLento: "Každý pošle jen jednu zprávu za interval. Kdo spravuje zprávy nebo kanály, projde rovnou.",
    visibilidade: "Viditelnost obsahu",
    padrao: "Výchozí",
    padraoDica: "Obsah kanálu je vždycky vidět.",
    spoiler: "Kanál se spoilery",
    spoilerDica: "Označ tenhle kanál jako se spoilery, aby zvraty a těžká témata zůstala schovaná, dokud se na ně někdo nechce podívat.",
    idade: "Kanál s věkovým omezením",
    idadeDica: "Kdo vejde, musí potvrdit plnoletost, aby obsah viděl.",
    bitrateDica: "Nad 64 kbps to může vadit lidem se špatným připojením.",
    qualidadeDeVideo: "Kvalita videa",
    automatica: "Automatická",
    limite: "Limit uživatelů — {{valor}}",
    pessoas: "{{quantos}} lidí",
    semLimite: "bez limitu",
    permissoesDescricao: "Tady měníš, co platí v tomhle kanálu. Co zůstane na „zdědit\", dál sleduje roli.",
    excluir: {
      titulo: "Smazat kanál",
      historico: "Celá historie kanálu {{canal}} jde s ním, všem.",
      digite: "Napiš {{canal}} pro potvrzení",
    },
  },
  moderacao: {
    titulo: "Pohled moderátora",
    semPermissao: "Potřebuješ oprávnění „Moderovat členy\", abys tohle viděl.",
    fecharEsc: "Zavřít (Esc)",
    atividade: "Aktivita na serveru",
    mensagens: "Zprávy",
    links: "Odkazy",
    midia: "Média",
    acoesNaAuditoria: "Akce v záznamu",
    moderacoesSofridas: "Obdržené moderace",
    permissoes: "Oprávnění ({{quantas}})",
    semPermissaoEspecial: "Žádná zvláštní oprávnění.",
    conta: "Účet",
    entrouNoServidor: "Přišel na server",
    contaCriadaEm: "Účet vytvořen",
    deCastigoAte: "Umlčen do",
    formaDeAdesao: "Jak se dostal dovnitř",
    mensagem: "Zpráva",
    castigo: "Umlčení",
    copiarId: "Kopírovat ID",
    idCopiado: "ID zkopírováno.",
    adicionarCargo: "Přidat roli",
    semCargos: "Žádná role nevytvořena",
    soEveryone: "Jen @everyone.",
    voltar: "Zpět",
    vazio: "Tady nic není.",
    cinquenta: "Zobrazuji 50 nejnovějších.",
    irParaMensagem: "Přejít na zprávu",
    precisaSerAmigo: "Abyste si psali, musíte být přátelé.",
    expulsarDescricao: "Okamžitě opouští server, ale může se vrátit s pozvánkou.",
    banirDescricao: "Opouští server a nevrátí se ani s pozvánkou, dokud mu ban nesundáš.",
    castigarTitulo: "Umlčet {{nome}}?",
    castigoDescricao: "Dokud trvá, nepíše ani nemluví v žádném kanálu serveru.",
    aplicarCastigo: "Použít umlčení",
    duracao: "Délka v minutách",
    informeDuracao: "Zadej délku v minutách.",
  },
  abas: {
    expressoes: "Výrazy",
    pessoas: "Lidé",
    apps: "Aplikace",
    moderacao: "Moderace",
    banimentos: "Bany",
  },
};
