export const amizades = {
  ativosAgora: "Aktif sekarang",
  procurando: "Melihat siapa yang ada…",
  tudoTranquilo: "Untuk sekarang sepi…",
  tudoTranquiloDetalhe: "Saat kamu atau teman masuk ke panggilan, itu muncul di sini — dan kamu bisa ikut dengan satu klik.",
  emVoz: "Di suara",
  voce: "Kamu",
  soVoce: "Hanya kamu",
  pessoas: "{{quantas}} orang",
  voltarParaChamada: "Kembali ke panggilan",
  entrarNaChamada: "Gabung panggilan",
  abrirCanal: "Buka {{canal}} di {{servidor}}",
  mensagensDiretas: "Pesan langsung",
  encontreConversa: "Cari percakapan",
  amigos: "Teman",
  conversas: "Percakapan",
  semConversas: "Belum ada percakapan. Tambahkan teman untuk mulai.",
  semConversaComEsseNome: "Tidak ada percakapan dengan nama itu.",
  abrirMenu: "Buka server dan percakapan",
  solicitacoes: "Permintaan pesan",
  pedidos: "Permintaan",
  spam: "Spam",
  pedidosPendentes: "Permintaan tertunda",
  marcadosComoSpam: "Ditandai sebagai spam",
  aceitar: "Terima",
  ignorar: "Abaikan",
  marcarSpam: "Tandai sebagai spam",
  semPedidos: "Tidak ada permintaan menunggu.",
  semPedidosDetalhe: "Orang yang bukan temanmu tapi satu server denganmu mendarat di sini sebelum sampai ke percakapanmu.",
  semSpam: "Tidak ada yang ditandai sebagai spam.",
  semSpamDetalhe: "Apa yang disaring filter spam, atau yang kamu tandai sendiri, tetap di tab ini.",
  umServidorEmComum: "1 server bersama",
  servidoresEmComum: "{{quantos}} server bersama",
  semServidoresEmComum: "Tidak ada server bersama",
};
