export const chamada = {
  conectando: "Menyambung ke panggilan…",
  naoEntrou: "Tidak bisa bergabung ke panggilan",
  sair: "Keluar dari panggilan",
  sairDaVoz: "Keluar dari panggilan suara",
  desconectar: "Putuskan",
  voltar: "Kembali ke panggilan",
  voltarAosQuadros: "Kembali ke kotak panggilan",
  fecharChat: "Tutup obrolan",
  carregandoPrevia: "Memuat pratinjau…",
  maisOpcoes: "Opsi lain",
  deVideo: "Panggilan video",
  deVoz: "Panggilan suara",
  alguem: "Seseorang",
  volume: {
    entrada: "Volume masukan",
    saida: "Volume keluaran",
    live: "Volume siaran",
    liveComPorcento: "Volume siaran ({{porcento}}%)",
    liveSemSom: "Siaran tanpa suara",
  },
  aparelhos: {
    entrada: "Perangkat masukan",
    saida: "Perangkat keluaran",
    camera: "Kamera",
    microfone: "Mikrofon",
    saidaCurto: "Keluaran",
    oDoSistema: "Bawaan sistem",
    aDoSistema: "Bawaan sistem",
    semEscolhaDeSaida: "Peramban ini tidak membiarkanmu memilih keluaran — sistem yang menentukan.",
    espelhar: "Cerminkan kameraku",
    configEntrada: "Pengaturan masukan",
    configSaida: "Pengaturan keluaran",
    configCamera: "Pengaturan kamera",
    configAudioEVideo: "Pengaturan audio dan video",
  },
  tela: {
    compartilhar: "Bagikan layar",
    compartilharAcao: "Bagikan",
    cancelar: "Batal",
    telas: "Layar",
    janelas: "Jendela",
    somDoComputador: "Bawa juga suara komputer",
    somDoSistema: "Bawa juga suara sistem",
    configCompartilhamento: "Pengaturan berbagi",
    mostrarSemVideo: "Tampilkan yang tanpa video",
    semFontes: "Sistem tidak mengembalikan satu pun layar atau jendela untuk dibagikan.",
    pararDeCompartilhar: "Berhenti berbagi",
    encerrarTransmissao: "Akhiri siaran",
  },
  live: {
    etiqueta: "Siaran langsung",
    etiquetaMaiuscula: "SIARAN LANGSUNG",
    assistir: "Tonton siaran",
    assistirPessoa: "Tonton {{nome}}",
    pararDeAssistir: "Berhenti menonton",
  },
  membro: {
    mudarMeuApelido: "Ubah nama panggilanku",
    meuMicrofone: "Mikrofonku",
    ouvirChamada: "Dengarkan panggilan",
    copiarMeuId: "Salin ID-ku",
    idCopiado: "ID disalin.",
    mensagem: "Pesan",
    silenciar: "Bisukan",
    alterarApelido: "Ubah nama panggilan",
    cargos: "Peran",
    semCargo: "Belum ada peran dibuat",
    moverPara: "Pindahkan ke",
    silenciarNoServidor: "Bisukan suara di server",
    desativarAudioNoServidor: "Matikan audio di server",
    desconectar: "Putuskan",
    apelidoTitulo: "Nama panggilanmu di server ini",
    apelidoDeAlguem: "Nama panggilan {{nome}}",
    apelidoCampo: "Nama panggilan",
    apelidoDicaPropria: "Hanya berlaku di sini. Kosongkan untuk kembali ke namamu yang biasa.",
    apelidoDicaDeOutro: "Hanya berlaku di server ini. Kosongkan untuk kembali ke nama asli.",
  },
  detalhes: {
    abrir: "Detail suara",
    titulo: "Detail Suara",
    conexao: "Koneksi",
    pingMedio: "Ping rata-rata",
    ultimoPing: "Ping terakhir",
    perda: "Kehilangan paket terkirim",
    medindo: "Mengukur…",
    criptografado: "Terenkripsi sampai server (DTLS-SRTP)",
    explicacao: "Di atas 250 ms jeda mulai terasa dalam percakapan — orang-orang saling memotong. Kehilangan paket di atas 10% membuat suara terdengar seperti robot. Pada keduanya, masalahnya hampir selalu antara kamu dan internet: coba kabel alih-alih Wi-Fi, atau nyalakan ulang router.",
  },
  microfone: {
    bloqueado: "Mikrofon diblokir — kamu hanya mendengarkan. Izinkan akses di izin peramban.",
    bloqueadoNoMac: "macOS memblokir mikrofon. Centang",
    caminhoNoMac: "Pengaturan Sistem → Privasi & Keamanan → Mikrofon",
    abrirAjustes: "Buka pengaturan",
    vaiReabrir: "macOS akan meminta kamu membuka ulang aplikasinya.",
    naoAbriu: "Mikrofon tidak bisa dibuka — kamu hanya mendengarkan. Periksa perangkat di Pengaturan → Suara dan video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS belum mengizinkan perekaman layar. Tanpa itu, hasil berbaginya hitam.",
    marque: "Centang",
    reabra: "di Perekaman Layar lalu buka ulang aplikasinya.",
  },
  ruido: {
    titulo: "Peredam bising",
    explicacao: "Buang suara latar dari suaramu. Coba bertepuk tangan atau menggeser papan ketik sambil bicara — orang di panggilan hanya mendengar kamu.",
    semSuporte: "Peramban ini tidak menjalankan peredam lanjutan. Peredam bawaan peramban tetap berlaku, dan itu lebih lemah.",
    aplicando: "Menerapkan ke panggilan…",
    faleParaTestar: "Bicaralah untuk menguji",
    verdeQuandoPassa: "Hijau saat suaramu lewat.",
    teOuvindo: "Mereka mendengarmu sekarang.",
    feitoCom: "Dibuat dengan",
    aquiNoAparelho: ", di perangkatmu sendiri",
    ajustes: "Pengaturan",
  },
  permissoes: {
    titulo: "Izin macOS",
    detalhe: "macOS bertanya sekali saja, dan setelah itu hanya berubah di panelnya sendiri. Di sini kamu bisa melihat apa yang berlaku dan membereskan yang kurang.",
    concedida: "Diberikan",
    negada: "Ditolak",
    naoPedida: "Belum diminta",
    permitir: "Izinkan",
    abrirAjustes: "Buka pengaturan",
    microfone: "Mikrofon",
    microfoneDetalhe: "Berbicara di panggilan dan menguji masukanmu.",
    camera: "Kamera",
    cameraDetalhe: "Menyalakan video di panggilan.",
    tela: "Perekaman layar",
    telaDetalhe: "Membagikan layar dan jendela.",
    monitoramento: "Pemantauan masukan",
    monitoramentoDetalhe: "Memakai tekan-untuk-bicara meski Gravaê ada di latar belakang.",
  },
  jaConectado: {
    titulo: "Kamu sudah ada di panggilan ini",
    trazer: "Bawa panggilan ke sini",
    deixar: "Biarkan apa adanya",
    detalhe: "Kalau dibawa ke sini, ujung yang lain keluar dari panggilan — akunmu ada di satu tempat pada satu waktu.",
  },
};
