export const comum = {
  carregando: "Memuat…",
  salvar: "Simpan",
  salvando: "Menyimpan…",
  descartar: "Buang",
  redefinir: "Atur ulang",
  naoSalvo: "Kamu punya perubahan yang belum disimpan.",
  fechar: "Tutup",
  criar: "Buat",
  nome: "Nama",
  emoji: "Emoji",
  previa: "Pratinjau",
  cancelar: "Batal",
  enviar: "Kirim",
  apagar: "Hapus",
  excluir: "Hapus",
  remover: "Singkirkan",
  trocar: "Ganti",
};
