export const comum = {
  voltar: "Kembali",
  agoraNao: "Nanti saja",
  erro: {
    tentarDeNovo: "Coba lagi",
    recarregar: "Muat ulang",
    copiarDetalhes: "Salin rinciannya",
    parteQuebrou: "Bagian layar ini rusak.",
    titulo: "Gravaê tersandung.",
    detalhe: "Ada yang rusak di tengah jalan dan layar tidak berhasil digambar. Percakapanmu tidak hilang — semuanya ada di server.",
  },
  conexao: {
    voltou: "Tersambung lagi",
    reconectando: "Menyambung ulang",
    tentativaSufixo: " · percobaan {{numero}}",
    aSalvo: "Percakapan aman di server. Semuanya kembali sendiri begitu koneksi pulih.",
  },
  avisoDoNavegador: {
    titulo: "Mau diberi tahu soal pesan?",
    detalhe: "Saat Gravaê ada di balik jendela lain, dia akan memanggilmu.",
  },
  atualizacao: {
    titulo: "Pembaruan",
    semAuto: "Versi aplikasi ini tidak bisa memperbarui dirinya sendiri. Unduh pemasang terbaru di bawah dan pasang menimpanya.",
    versaoAtual: "Kamu memakai versi {{versao}}.",
    instalando: "Memasang versi {{versao}}…",
    prontaVersao: "Versi {{versao}} siap dipasang",
    baixandoVersao: "Mengunduh versi {{versao}}…",
    baixandoComProgresso: "Mengunduh versi {{versao}}… {{porcento}}%",
    saiuVersao: "Versi {{versao}} sudah rilis",
    saiuVersaoClique: "Versi {{versao}} sudah rilis — klik untuk mengunduh",
    instalarVersaoEReiniciar: "Pasang versi {{versao}} lalu mulai ulang",
    erroTenteDeNovo: "{{erro}} Klik untuk mencoba lagi.",
    procurando: "Mencari…",
    emDia: "Kamu sudah paling baru",
    vaiFechar: "Aplikasi akan menutup sebentar lagi.",
    comoInstala: "Aplikasi menutup, menukar versi, dan membuka lagi sendiri. Kamu akan keluar dari panggilan yang sedang berjalan.",
    semServidor: "Saya tidak berhasil menghubungi server versi.",
    procuraSozinho: "Aplikasi memeriksa sendiri saat dibuka dan setiap enam jam.",
    instalandoReticencias: "Memasang…",
    instalandoCurto: "Memasang",
    baixandoCurto: "Mengunduh",
    tentarDeNovo: "Coba lagi",
    reiniciarAgora: "Mulai ulang sekarang",
    instalarEReiniciar: "Pasang dan mulai ulang",
    baixar: "Unduh",
    procurar: "Periksa",
    baixarApp: "Unduh aplikasinya",
    ariaBotao: "Pembaruan aplikasi",
  },
  janela: {
    ajustarAltura: "Sesuaikan tinggi",
    redimensionar: "Ubah ukuran jendela",
    ajustarLargura: "Sesuaikan lebar",
  },
  dica: {
    rotulo: "Tips:",
    pularConfirmacao: "tahan Shift saat mengeklik untuk melewati konfirmasi ini.",
  },
  cor: {
    pescar: "Ambil warna dari layar",
    hex: "Nilai heksadesimal",
  },
  imagem: {
    titulo: "Pilih gambar",
    enviar: "Kirim gambar",
    escolherGif: "Pilih GIF",
    buscarGif: "Cari GIF",
  },
  fonte: {
    rotulo: "Font pesan",
    padrao: "Bawaan",
    comNome: "Font pesan — {{fonte}}",
  },
  recorte: {
    titulo: "Pangkas ikon",
    detalhe: "Seret untuk memilih bagiannya dan pakai penggeser untuk memperbesar. Ikon tampil bulat di seluruh aplikasi.",
    voltarAoComeco: "Kembali ke awal",
    usar: "Pakai pangkasan ini",
  },
  mais: "Lainnya",
  carregando: "Memuat…",
  salvar: "Simpan",
  salvando: "Menyimpan…",
  descartar: "Buang",
  redefinir: "Atur ulang",
  naoSalvo: "Kamu punya perubahan yang belum disimpan.",
  fechar: "Tutup",
  criar: "Buat",
  nome: "Nama",
  emoji: "Emoji",
  previa: "Pratinjau",
  cancelar: "Batal",
  enviar: "Kirim",
  apagar: "Hapus",
  excluir: "Hapus",
  remover: "Singkirkan",
  trocar: "Ganti",
};
