export const configuracoes = {
  sair: "Keluar",
  versoes: {
    copiar: "Klik untuk menyalin",
    copiado: "Disalin",
  },
  telas: {
    conta: "Akun saya",
    privacidade: "Privasi",
    conexoes: "Koneksi",
    voz: "Audio",
    video: "Video",
    avisos: "Notifikasi",
    aplicativos: "Aplikasi",
    aparencia: "Tampilan",
    batePapo: "Obrolan",
    acessibilidade: "Aksesibilitas",
    idioma: "Bahasa",
    aplicativo: "Unduh aplikasi",
    atalhos: "Pintasan",
    avancado: "Lanjutan",
    servidor: "Server",
  },
  grupos: {
    conta: "Akun",
    app: "Pengaturan aplikasi",
    desenvolvedor: "Pengembang",
    administracao: "Administrasi",
  },
  secoes: {
    detalhesDeLogin: "Detail masuk",
    dispositivos: "Perangkat",
    usuariosBloqueados: "Pengguna diblokir",
    aplicativosAutorizados: "Aplikasi resmi",
    sessoes: "Sesi",
    amigosEDms: "Teman dan pesan langsung",
    compartilhamentoDeAtividade: "Berbagi aktivitas",
    visibilidadeDoPerfil: "Visibilitas profil",
    exportarDados: "Ekspor data",
    exclusaoDeDados: "Hapus data",
    tema: "Tema",
    corDeDestaque: "Warna aksen",
    interface: "Antarmuka",
    listaDeCanais: "Daftar kanal",
    zoomDoApp: "Tingkat zoom aplikasi",
    escalaDaFonte: "Ukuran font obrolan",
    modoStreamer: "Privasi saat siaran",
    movimento: "Gerakan",
    textoEmVoz: "Teks ke ucapan",
    teclado: "Papan ketik",
    formatoDaHora: "Format waktu",
    idiomaDaInterface: "Bahasa antarmuka",
    dispositivosDeVoz: "Perangkat",
    testeDoMicrofone: "Uji mikrofon",
    modoDeEntrada: "Mode masukan",
    sensibilidade: "Sensitivitas masukan",
    qualidade: "Kualitas",
    camera: "Kamera",
    transmissao: "Siaran",
    exibicao: "Tampilan",
    entrada: "Masukan",
    midia: "Media",
    geral: "Umum",
    preferenciaDeMencao: "Preferensi sebutan",
    sons: "Suara",
  },
};
