export const conversa = {
  lista: {
    carregando: "Memuat pesan…",
    carregandoMais: "Memuat…",
    verMais: "Gulir ke atas untuk melihat lebih banyak",
    semHistorico: "Riwayat tidak tersedia",
    semHistoricoDetalhe: "Peranmu tidak punya izin membaca riwayat #{{canal}}. Pesan baru tetap muncul selama kamu di sini.",
    boasVindas: "Selamat datang di #{{canal}}",
    boasVindasDetalhe: "Ini awal kanal #{{canal}}.",
  },
  data: {
    hoje: "Hari ini",
    ontem: "Kemarin",
    hojeAs: "hari ini pukul {{hora}}",
    ontemAs: "kemarin pukul {{hora}}",
  },
  digitando: {
    um: "{{nome}} sedang mengetik…",
    dois: "{{primeiro}} dan {{segundo}} sedang mengetik…",
    varios: "{{quantidade}} orang sedang mengetik…",
  },
  mensagem: {
    usou: "memakai",
    fixada: "disematkan",
    editado: "(diedit)",
    ignorada: "Pesan dari orang yang kamu abaikan.",
    mostrar: "Tampilkan",
    escPara: "Esc untuk",
    cancelar: "batal",
    enterParaSalvar: "Enter untuk menyimpan",
    falhou: "Tidak terkirim. Coba lagi",
    naoLidasDaqui: "Belum dibaca mulai dari sini.",
    linkCopiado: "Tautan disalin.",
    idCopiado: "ID disalin.",
    naoDeuParaCopiar: "Peramban kamu tidak mengizinkan penyalinan.",
    apagarTitulo: "Hapus pesan?",
    apagarDescricao: "Pesan hilang untuk semua orang di kanal. Tidak bisa dikembalikan.",
    apagarAcao: "Hapus",
    citacaoAnexo: "klik untuk melihat lampiran",
    citacaoSumiu: "Pesan aslinya sudah tidak ada di sini.",
    reagirCom: "Beri reaksi {{emoji}} — tahan untuk super reaksi",
    segureParaSuper: "{{emoji}} — tahan untuk super reaksi",
  },
  acoes: {
    reagir: "Beri reaksi",
    responder: "Balas",
    encaminhar: "Teruskan",
    favoritar: "Simpan pesan",
    tirarDosFavoritos: "Keluarkan dari simpanan",
    marcarNaoLida: "Tandai belum dibaca",
    copiarLink: "Salin tautan pesan",
    copiarId: "Salin ID pesan",
    fixar: "Sematkan pesan",
    desafixar: "Lepas sematan",
    editar: "Edit",
    apagar: "Hapus",
    mais: "Lainnya",
    adicionarReacao: "Tambah reaksi",
    superReagirCom: "Super reaksi dengan {{emoji}}",
    fixarMensagem: "Sematkan pesan",
    desafixarMensagem: "Lepas sematan pesan",
    editarMensagem: "Edit pesan",
    apagarMensagem: "Hapus pesan",
  },
  mencao: {
    cargo: "Sebutan peran",
    pessoa: "Sebutan",
    alguem: "seseorang",
    cargoSemNome: "peran",
    here: "Memberi tahu yang sedang online",
    everyone: "Memberi tahu seluruh server",
  },
  codigo: {
    copiar: "Salin",
    copiado: "Disalin",
    copiarAria: "Salin kodenya",
    copiadoAria: "Kode disalin",
    recolher: "Ciutkan",
    expandir: "Perluas",
    verInteiro: "Lihat seluruh berkas",
    maisOpcoes: "Opsi lainnya",
    baixar: "Unduh",
    recolherLinhas: "Ciutkan ({{linhas}} baris)",
    expandirLinhas: "Perluas ({{linhas}} baris)",
    mudarIdioma: "Ubah bahasa",
    procurarIdioma: "Cari kode bahasa…",
    nenhumIdioma: "Bahasa tidak ditemukan.",
    quebrarTexto: "Bungkus teks",
  },
  caixa: {
    escrever: "Tulis di #{{canal}}",
    escreverSemCanal: "Tulis pesan",
    semPermissao: "Kamu tidak punya izin mengirim pesan di kanal ini",
    solteParaAnexar: "Lepaskan untuk melampirkan",
    longaTitulo: "Pesanmu terlalu panjang…",
    longaDescricao: "Kamu mencapai batas {{limite}} karakter. Kirim saja sebagai berkas.",
    enviarComoArquivo: "Kirim sebagai berkas",
    respondendoPara: "Membalas",
    vaiNotificar: "Orangnya akan diberi tahu",
    naoVaiNotificar: "Orangnya tidak akan diberi tahu",
    ligado: "aktif",
    desligado: "nonaktif",
    pararDeResponder: "Batalkan balasan",
    mais: "Lainnya",
    enviarArquivo: "Kirim berkas",
    criarEnquete: "Buat jajak pendapat",
    expressoes: "Emoji, GIF, dan stiker",
    enviar: "Kirim",
    aguardandoEnvio: "Menunggu unggahan",
    modoLento: "Mode lambat aktif ({{tempo}})",
    modoLentoDica: "Mode lambat disetel ke {{segundos}} dtk. Tunggu sebelum mengirim pesan berikutnya.",
  },
  anexos: {
    enviando: "Mengunggah…",
    modificar: "Ubah {{arquivo}}",
    remover: "Hapus {{arquivo}}",
    ver: "Lihat {{arquivo}}",
    mostrarSpoiler: "Tampilkan spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Edit lampiran",
    nomeDoArquivo: "Nama berkas",
    descricao: "Deskripsi teks alternatif",
    descricaoDica: "Jelaskan media ini untuk pembaca layar",
    marcarSpoiler: "Tandai sebagai spoiler",
    cancelar: "Batal",
    salvar: "Simpan",
  },
  cartao: {
    tocador: "Pemutar",
    abrir: "Buka {{destino}}",
    tocar: "Putar {{titulo}}",
    video: "video",
    verImagem: "Lihat gambar",
  },
  enquete: {
    titulo: "Jajak pendapat",
    encerrada: "Jajak pendapat ditutup",
    variasRespostas: "Jajak pendapat — banyak jawaban",
    umVoto: "{{quantidade}} suara",
    votos: "{{quantidade}} suara",
    umVotoNoTotal: "total {{quantidade}} suara",
    votosNoTotal: "total {{quantidade}} suara",
    encerraEm: "ditutup {{quando}}",
    encerrarAgora: "Tutup sekarang",
  },
  fixadas: {
    titulo: "Pesan yang disematkan",
    vazio: "Kanal ini belum punya pesan yang disematkan.",
    desafixar: "Lepas sematan",
    anexo: "(lampiran)",
    enquete: "(jajak pendapat)",
    dicaRotulo: "TIPS:",
    dica: "siapa pun yang punya izin “Kelola pesan” bisa menyematkan langsung dari menu pesan.",
  },
  encaminhar: {
    titulo: "Teruskan pesan",
    paraOnde: "Ke mana?",
    semTexto: "(pesan tanpa teks)",
    nenhumLugar: "Tidak ada tempat dengan nama itu.",
    canais: "Kanal",
    conversas: "Pesan langsung",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Cari di Klipy",
    figurinha: "Stiker",
    buscarFigurinha: "Temukan stiker yang pas",
    buscarEmoji: "Temukan emoji yang pas",
    buscarReacao: "Temukan reaksi yang pas",
    adicionarEmoji: "Tambah emoji",
    limparBusca: "Bersihkan pencarian",
  },
  busca: {
    fechar: "Tutup pencarian",
    procurando: "Mencari…",
    resultado: "{{quantos}} hasil",
    resultados: "{{quantos}} hasil",
    nadaCom: "Tidak ada apa-apa soal {{termo}} di sini.",
    soOsQuePodeLer: "Pencarian hanya melihat kanal yang boleh kamu baca.",
  },
  entrada: {
    titulo: "Kotak masuk",
    naoLidas: "Belum dibaca",
    salvas: "Tersimpan",
    mencoes: "Sebutan",
    fimTitulo: "Kamu sudah sampai ujung",
    fimDetalhe: "Tidak ada lagi yang perlu dibaca. Kalau ada pesan baru, akan muncul di sini.",
    semSalvosTitulo: "Tidak ada yang tersimpan",
    semSalvosDetalhe: "Tahan Shift lalu klik penanda sebuah pesan untuk menyimpannya dan membacanya nanti.",
    tirarDosSalvos: "Keluarkan dari tersimpan",
    semMencoesTitulo: "Belum ada sebutan",
    semMencoesDetalhe: "Sebutan untukmu muncul di sini untuk 7 hari terakhir.",
  },
  forum: {
    descricao: "Tiap topik jadi percakapan tersendiri — cocok untuk pertanyaan yang tak boleh hilang di tengah obrolan.",
    novoAssunto: "Topik baru",
    vazio: "Belum ada topik. Mulai yang pertama dan percakapan tetap rapi sejak awal.",
    titulo: "Judul",
    doQueSeTrata: "Soal apa ini?",
    primeiraMensagem: "Pesan pertama",
    conteDoCaso: "Ceritakan",
  },
};
