export const perfil = {
  carregando: "Memuat…",
  editar: "Edit profil",
  mensagem: "Pesan",
  abrirConversa: "Buka percakapan",
  verCompleto: "Lihat profil lengkap",
  convidarParaServidor: "Undang ke server",
  semServidores: "Kamu belum punya server",
  conviteEnviado: "Undangan dikirim ke {{nome}}.",
  moderador: "Buka di tampilan moderator",
  mais: "Lainnya",
  ignorar: "Abaikan",
  deixarDeIgnorar: "Berhenti mengabaikan",
  copiarId: "Salin ID pengguna",
  idCopiado: "ID disalin.",
  conexoes: "Koneksi",
  membroDesde: "Anggota sejak",
  sobre: "Tentang",
  cargosTitulo: "Peran",
  visaoGeral: "Ringkasan",
  amigosEmComum: "Teman bersama ({{quantidade}})",
  servidoresEmComum: "Server bersama ({{quantidade}})",
  amizade: {
    amigo: "Teman",
    pedidoEnviado: "Permintaan pertemanan terkirim",
    respondaAbaixo: "Mengirimimu permintaan — jawab di bawah",
    adicionar: "Tambah teman",
    teMandouPedido: "Mengirimimu permintaan pertemanan",
    aceitar: "Terima",
    desfazer: "Hapus pertemanan",
    desfazerTitulo: "Hapus {{nome}} dari temanmu?",
    desfazerDescricao: "Kalian tidak berteman lagi. Percakapan pribadi tetap ada di riwayat, dan nanti kamu bisa menambahkannya lagi.",
    bloquear: "Blokir",
    bloquearTitulo: "Blokir {{nome}}?",
    bloquearDescricao: "Kalian tidak berteman lagi, percakapan pribadi berhenti menerima pesan, dan dia tidak bisa lagi mengirimimu permintaan pertemanan.",
    linkCopiado: "Kalian bukan teman — tautannya sudah disalin supaya kamu yang mengirim.",
  },
  recado: {
    escrever: "Tulis ke @{{usuario}}",
    enviar: "Kirim",
    enviada: "Pesan terkirim",
    falhou: "Tidak terkirim. Coba dari percakapan.",
  },
  cartao: {
    trocarFaixa: "Ganti banner kartu",
    trocarFaixaCurto: "Ganti banner",
    trocarFoto: "Ganti foto profil",
    trocarFotoCurto: "Ganti foto",
    suaEtiqueta: "Tagmu",
    editarEtiqueta: "Klik untuk mengedit tagmu",
    conteAlgo: "Ceritakan sesuatu tentang dirimu",
    adicionarStatus: "Tambah status",
    adicionarDescricao: "Klik untuk menambah deskripsi",
    cargo: "Peran",
    cargos: "Peran",
    cargosCom: "Peran — {{quantidade}}",
    tirarCargo: "Lepas peran {{cargo}}",
  },
  cargos: {
    adicionar: "Tambah peran",
    procurar: "Cari peran",
  },
  etiqueta: {
    escolher: "Pilih tag server",
    nenhuma: "Tidak ada tag server",
    semEtiqueta: "Tidak ada server-mu yang punya tag",
  },
  emblemas: {
    doServidor: "Lencana dari server ini",
    limite: "Kamu bisa memakai sampai {{quantidade}} lencana.",
  },
  nota: {
    vazia: "Klik untuk mencatat sesuatu",
    rotulo: "Catatan (hanya kamu yang lihat)",
  },
  status: {
    titulo: "Status",
    definir: "Atur statusmu",
    escolherEmoji: "Pilih emoji",
    tirarEmoji: "Lepas emoji",
    oQuePensa: "Sedang memikirkan apa?",
    limparAgora: "Hapus status sekarang",
    naoLimpar: "Jangan hapus",
    limpar30m: "Hapus dalam 30 menit",
    limpar1h: "Hapus dalam 1 jam",
    limpar4h: "Hapus dalam 4 jam",
    limparHoje: "Hapus hari ini",
    limparAmanha: "Hapus besok",
    comHora: "{{prazo}} pukul {{hora}}",
  },
  presenca: {
    disponivel: "Tersedia",
    ausente: "Tidak di tempat",
    naoPerturbar: "Jangan ganggu",
    naoPerturbarDetalhe: "Kamu tidak menerima pemberitahuan pesan baru",
    invisivel: "Tak terlihat",
    invisivelDetalhe: "Bagi yang lain kamu tampak luring",
  },
  menu: {
    mudarDeConta: "Ganti akun",
    gerenciarContas: "Kelola akun",
  },
  editor: {
    decoracao: "Ganti hiasan avatar",
    naoSalvo: "Jangan lupa simpan perubahanmu!",
    principal: "Profil utama",
  },
};
