export const servidor = {
  comunidade: {
    ativa: "Komunitas sudah terbuka",
    ativaDesde: "Terbuka sejak {{quando}}",
    membrosAgora: "{{quantos}} anggota",
    criarParaMim: "Buatkan satu untuk saya",
    canalDeRegras: "Kanal aturan",
    canalDeRegrasDetalhe: "Tempat aturan berada, yang dibaca semua orang sebelum bicara.",
    canalDeAvisos: "Kanal pengumuman komunitas",
    canalDeAvisosDetalhe: "Ke sana kami kirim apa yang berubah di sini, hanya untuk yang mengelola.",
    canalDeSeguranca: "Kanal peringatan keamanan",
    canalDeSegurancaDetalhe: "Tempat moderasi menerima apa yang ditangkap penyaring.",
    idiomaPrincipal: "Bahasa utama",
    idiomaPrincipalDetalhe: "Bahasa yang dipakai untuk sebagian besar obrolan.",
    semIdioma: "Belum ada bahasa dipilih",
    semCanal: "Tanpa kanal",
    finalTitulo: "Sedikit lagi",
    finalDetalhe: "Sebelum dibuka, lihat apa yang berubah bagi yang datang.",
    confereRegras: "Yang bergabung melihat kanal aturan sebelum yang lain.",
    confereEveryone: "Hanya yang punya peran memakai @everyone dan @here.",
    confereMencoes: "Menyebut semua orang sekaligus kini butuh izin.",
    concordo: "Saya setuju dan paham",
    concordoDetalhe: "Kamu memastikan komunitas mengikuti pedoman kami.",
    proximo: "Lanjut",
    terminar: "Selesaikan penyiapan",
    visaoGeral: "Ringkasan",
    visaoGeralDetalhe: "Kanal yang dipakai komunitas untuk bicara ke pendatang.",
    seguranca: "Keamanan",
    segurancaDetalhe: "Rem yang menahan spam dan konten berat.",
    habilitada: "Komunitas sudah aktif.",
    falhou: "Komunitas tidak bisa diaktifkan.",
    titulo: "Komunitas",
    ilustracao: "Balon percakapan",
    convite: "Kamu sedang membangun komunitas?",
    conviteDetalhe: "Jadikan komunitas untuk mendapat perkakas tempat besar: kanal aturan, pengumuman dari kami, dan penyaring yang bekerja sendiri.",
    contagem: "{{membros}} dari {{minimo}} anggota",
    faltam: "Kurang {{quantos}} lagi untuk dibuka.",
    prontoParaAbrir: "Sudah bisa dibuka.",
    habilitar: "Aktifkan komunitas",
    vantagemCrescer: "Tumbuh",
    vantagemCrescerDetalhe: "Komunitas bisa mendaftar ke Jelajahi, jadi orang yang mencari topiknya menemukanmu.",
    vantagemModerar: "Memoderasi",
    vantagemModerarDetalhe: "Wajibkan surel terverifikasi, saring media, dan nyalakan AutoMod sekaligus.",
    vantagemAvisos: "Tetap tahu",
    vantagemAvisosDetalhe: "Kami kirim apa yang berubah ke yang mengelola, di kanal khusus kalian.",
    assistenteTitulo: "Ayo siapkan komunitasmu.",
    passoSeguranca: "Pemeriksaan keamanan",
    passoBasico: "Persiapan dasar",
    passoFinal: "Sentuhan akhir",
    seguraTitulo: "Jaga komunitas tetap aman",
    seguraDetalhe: "Komunitas besar menarik spam. Dua rem ini menyala dari awal, dan bisa kamu matikan nanti kalau mengganggu.",
    emailVerificado: "Wajibkan surel terverifikasi",
    emailVerificadoDetalhe: "Yang belum mengonfirmasi surel tidak bisa mengirim pesan. Yang punya peran lewat langsung.",
    filtroDeMidia: "Saring media eksplisit",
    filtroDeMidiaDetalhe: "Gambar dan video datang dalam keadaan tertutup, dan baru tampil kalau ada yang memilih melihat.",
    basicoTitulo: "Siapkan yang dasar",
    basicoDetalhe: "Sebutkan kanal mana yang memuat aturan dan ke mana pengumuman kami pergi. Tanpa pilihan, saya buat keduanya.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} perintah",
    previa: "Tampilan kartunya",
    trocarIcone: "Ganti ikon",
    tirarCapa: "Hapus sampul",
    heroComunidades: "Ada yang sedang membicarakan hal yang kamu suka",
    heroComunidadesDetalhe: "Komunitas yang dibuka orang-orang di sini. Masuklah, baca obrolannya, dan tinggal kalau cocok.",
    emDestaque: "Pilihan",
    todasAsComunidades: "Sisanya",
    heroTitulo: "Hari ini rombonganmu mau pakai apa?",
    heroDetalhe: "Bot untuk musik, gim, dan moderasi, dibuat oleh orang-orang yang juga ada di sini. Pilih satu dan dia masuk ke servermu.",
    novidades: "Baru datang",
    todosOsApps: "Sisanya",
    lojaTitulo: "Halaman aplikasi",
    lojaDetalhe: "Inilah yang muncul di Jelajahi bagi yang belum mengenalnya.",
    capa: "Sampul",
    capaDetalhe: "Gambar lebar di bagian atas halaman. 1280 × 720 pas.",
    trocarCapa: "Ganti sampul",
    categorias: "Kategori",
    categoriasDetalhe: "Paling banyak {{quantas}}. Lewat inilah orang menelusuri Jelajahi.",
    idiomas: "Bahasa",
    idiomasDetalhe: "Paling banyak {{quantos}}. Dalam bahasa apa aplikasi menjawab.",
    termos: "Ketentuan penggunaan",
    politica: "Kebijakan privasi",
    politicas: "Kebijakan",
    servidorDeSuporte: "Server dukungan",
    servidorDeSuporteDetalhe: "Ke sanalah yang butuh bantuan soal aplikasi ini pergi.",
    semServidor: "Tidak ada",
    emQuantosServidores: "Di berapa server",
    categoria: {
      GAMES: "Gim",
      MUSICA: "Musik",
      MODERACAO: "Moderasi",
      PRODUTIVIDADE: "Produktivitas",
      SOCIAL: "Sosial",
      UTILIDADES: "Perkakas",
      ARTE_E_CRIACAO: "Seni dan kreasi",
      EDUCACAO: "Belajar",
      OUTRA: "Lainnya",
    },
    appIndisponivel: "Aplikasi tidak tersedia",
    voltarParaExplorar: "Kembali ke Jelajahi",
    adicionarApp: "Tambahkan aplikasi",
    copiarLink: "Salin tautannya",
    denunciarApp: "Laporkan aplikasinya",
    copiarIdDoApp: "Salin ID aplikasi",
    visaoGeral: "Ringkasan",
    comandos: "Perintah",
    permissoes: "Izin",
    semPermissoes: "Aplikasi ini tidak meminta izin apa pun.",
    avisoDePermissoes: "Ia masuk dengan perannya sendiri. Izin itu bisa diubah nanti di Pengaturan komunitas → Peran.",
    servidoresEmComum: "Komunitas yang sama",
    umServidorEmComum: "1 komunitas",
    quantosServidoresEmComum: "{{quantos}} komunitas",
    feitoPor: "Dibuat oleh",
    publicadoEm: "Diterbitkan pada",
    denunciarNome: "Laporkan {{nome}}",
    denunciaDetalhe: "Laporan masuk ke tim Gravaê. Pembuat aplikasinya tidak diberi tahu bahwa itu kamu.",
    denunciaFalhou: "Laporan tidak bisa dikirim.",
    umMembro: "1 anggota",
    semDescricao: "Tanpa deskripsi.",
    adicionar: "Tambahkan",
    jaEstaAqui: "Kamu sudah di sini",
    entrando: "Bergabung…",
    entrar: "Gabung",
    comunidadePublica: "Komunitas publik",
    online: "{{quantos}} online",
    membros: "{{quantos}} anggota",
    abrirComunidade: "Buka komunitasnya",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Pengaturan server",
  novasMensagens: "Pesan baru",
  menu: {
    silenciar: "Bisukan komunitas",
    reativar: "Bunyikan komunitas",
    porQuinze: "Selama 15 menit",
    porMeiaHora: "Selama 30 menit",
    porTresHoras: "Selama 3 jam",
    porTresDias: "Selama 3 hari",
    porUmaHora: "Selama 1 jam",
    porOitoHoras: "Selama 8 jam",
    porUmDia: "Selama 24 jam",
    ateReativar: "Sampai saya aktifkan lagi",
    notificacoes: "Pengaturan notifikasi",
    padrao: "Ikuti bawaan",
    todas: "Semua pesan",
    soMencoes: "Hanya sebutan",
    nada: "Tidak ada",
    ocultarSilenciados: "Sembunyikan kanal yang dibisukan",
    denunciar: "Laporkan komunitas",
    marcarLida: "Tandai sudah dibaca",
    convidar: "Undang anggota",
    editarPerfil: "Edit profil komunitas",
    configuracoes: "Pengaturan komunitas",
    sair: "Keluar dari komunitas",
    sairTitulo: "Keluar dari {{nome}}?",
    sairDescricao: "Kamu perlu undangan baru untuk kembali.",
    copiarId: "Salin ID komunitas",
    idCopiado: "ID disalin.",
  },
  convite: {
    cartaoTitulo: "Kamu diundang bergabung ke sebuah komunitas",
    indisponivel: "Undangan tidak tersedia",
    indisponivelDetalhe: "Sudah kedaluwarsa, sudah habis, atau dihapus oleh yang membuatnya.",
    entrar: "Gabung ke komunitas",
    chamado: "Kamu diundang untuk bergabung ke",
    aceitarComo: "Terima sebagai {{nome}}",
    abrir: "Buka komunitas",
    recusar: "Tidak, terima kasih",
  },
  pasta: {
    silenciarTodas: "Bisukan komunitas",
    reativarTodas: "Bunyikan komunitas",
    mostrarSilenciados: "Tampilkan kanal yang dibisukan",
    notificacoesDaComunidade: "Pengaturan notifikasi",
    silenciarEveryone: "Bisukan @everyone dan @here",
    permitirEveryone: "Izinkan @everyone dan @here",
    silenciarCargos: "Bisukan sebutan peran",
    permitirCargos: "Izinkan sebutan peran",
    dicaDaCor: "Tulis warna (hex, rgb(), hsl() atau nama) atau pakai pemilih.",
    mostrarIcone: "Tampilkan ikon saat tertutup",
    dicaDoIcone: "Saat tertutup, menampilkan ikon alih-alih server di dalamnya.",
    icone: "Ikon folder",
    excluir: "Hapus folder",
    icones: {
      pasta: "Folder",
      estrela: "Favorit",
      coracao: "Hati",
      salvar: "Simpan",
      jogo: "Stik game",
      escudo: "Perisai",
      nota: "Not musik",
    },
    marcarLida: "Tandai folder sudah dibaca",
    configuracoes: "Pengaturan folder",
    desfazer: "Bubarkan folder",
    titulo: "Folder",
    nome: "Nama",
    semNome: "Tanpa nama",
    cor: "Warna",
    semCor: "Tanpa warna",
    salvar: "Simpan",
  },
  denuncia: {
    titulo: "Laporkan {{nome}}",
    descricao: "Laporan dikirim ke tim Gravaê. Ceritakan apa yang terjadi.",
    motivo: "Alasan",
    detalhes: "Detail (opsional)",
    enviar: "Kirim laporan",
    enviada: "Laporan terkirim. Terima kasih.",
    motivos: {
      spam: "Spam atau iklan",
      assedio: "Pelecehan atau kebencian",
      conteudo: "Konten tidak pantas",
      golpe: "Penipuan",
      outro: "Lainnya",
    },
  },
  selos: {
    verificada: "Komunitas terverifikasi",
    detectavel: "Komunitas dapat ditemukan",
  },
  auditoria: {
    todasAsAcoes: "Semua tindakan",
    todosOsUsuarios: "Semua pengguna",
    filtroMembros: "Anggota",
    filtroCanais: "Kanal",
    filtroEmojis: "Emoji",
    filtroServidor: "Server",
    titulo: "Log tindakan",
    porUsuario: "Saring berdasarkan orang",
    porAcao: "Saring berdasarkan tindakan",
    vazio: "Belum ada yang tercatat dengan saringan ini.",
    motivo: "Alasan:",
  },
  banimentos: {
    titulo: "Daftar cekal server",
    descricao: "Yang ada di sini tidak bisa masuk lagi, bahkan dengan undangan baru. Mencabut cekal mengembalikan akses seketika.",
    procurar: "Cari cekal berdasarkan nama pengguna",
    vazioTitulo: "Tidak ada cekal",
    vazio: "Kamu belum mencekal siapa pun… tapi kalau suatu saat perlu, jangan ragu.",
    desbanir: "Cabut cekal",
  },
  excluir: {
    tudoVai: "Semua kanal, pesan, dan undangan {{servidor}} akan dihapus untuk {{membros}} anggota. Setelah itu tak seorang pun bisa mengembalikannya.",
    digite: "Ketik {{servidor}} untuk mengonfirmasi",
    titulo: "Hapus server",
    aviso: "Ini tidak bisa dibatalkan.",
  },
  emblemas: {
    apagarDescricao: "Lencananya lepas dari siapa pun yang memakainya. Ini tidak bisa dibatalkan.",
    titulo: "Lencana",
    vazio: "Belum ada lencana.",
    novo: "Lencana baru",
  },
  convites: {
    revogarTitulo: "Cabut undangan?",
    revogarAcao: "Cabut",
    revogarDescricao: "Tautan {{codigo}} langsung berhenti bekerja. Yang sudah masuk lewat tautan itu tetap di server.",
    titulo: "Undangan",
    descricao: "Semua tautan undangan aktif server ini.",
    vazio: "Belum ada undangan yang dibuat.",
    revogar: "Cabut undangan",
  },
  integracoes: {
    opcionais: "username dan avatar_url bersifat opsional dan berlaku per pesan. Batasnya 5 pesan tiap 5 detik.",
    apagarDescricao: "URL-nya langsung berhenti bekerja. Pesan yang sudah dikirimnya tetap ada di kanal.",
    titulo: "Integrasi",
    descricao: "Webhook adalah alamat yang memposting ke sebuah kanal tanpa perlu akun. Berguna untuk mengabari bahwa build lolos, ada yang membuka tiket, atau apa pun yang ingin kamu kirim dari skrip.",
    novo: "Webhook baru",
    vazio: "Belum ada webhook. Buat satu dan tempel URL-nya di tempat kamu ingin pesannya berasal.",
    canal: "Kanal",
    apagar: "Hapus webhook",
    comoUsar: "Cara memakai",
    comoUsarTexto: "Kirim POST berisi JSON:",
  },
  explorar: {
    titulo: "Jelajahi",
  },
  engajamento: {
    semCanal: "Tanpa kanal sistem",
    titulo: "Keterlibatan",
    descricao: "Apa yang server lakukan sendiri agar tidak terasa kosong saat ada orang baru datang.",
    sistema: "Pesan sistem",
    boasVindas: "Kirim pesan selamat datang saat ada yang bergabung",
    sorteio: "Tanpa teksmu sendiri di bawah, kalimatnya diundi — yang itu-itu saja cepat membosankan.",
    canalDoSistema: "Kanal pesan sistem",
    mensagem: "Pesan selamat datang",
    deixeVazio: "Biarkan kosong untuk mengundi dari kalimat yang sudah ada",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filter yang memoderasi sendiri, bahkan sebelum pesannya ada. Yang mengelola server tidak pernah difilter — dan peran yang dikecualikan lewat begitu saja.",
    palavras: {
      titulo: "Blokir kata milikmu",
      descricao: "Daftar katamu yang tidak boleh ditulis siapa pun.",
    },
    mencoes: {
      titulo: "Blokir spam sebutan",
      descricao: "Memblokir pesan dengan terlalu banyak sebutan sekaligus.",
    },
    links: {
      titulo: "Blokir tautan",
      descricao: "Menahan setiap alamat yang ditempel di obrolan.",
    },
    definir: "Atur",
    nomeDaRegra: "Nama aturan",
    bloqueadas: "Kata yang diblokir",
    digiteEnter: "Ketik lalu tekan Enter",
    comparacao: "Pencocokan mengabaikan huruf besar, aksen, dan tanda baca — dan tidak menangkap kata di dalam kata lain.",
    aPartirDe: "Blokir mulai dari berapa sebutan",
    oQueFazer: "Apa yang dilakukan",
    canalDoAlerta: "Kanal peringatan",
    escolhaCanal: "Pilih kanal",
    castigo: "Bungkam (menit)",
    isentos: "Peran yang dikecualikan",
    semCargos: "Belum ada peran yang dibuat.",
    salvarRegra: "Simpan aturan",
    apagar: "Hapus aturan",
    excluirTitulo: "Hapus aturan AutoMod ini?",
    excluirDescricao: "Server langsung berhenti menyaring dengannya. Bisa dibuat lagi, tapi pengaturan yang sekarang hilang.",
    excluirAcao: "Hapus aturan",
  },
  cargos: {
    titulo: "Peran",
    descricao: "Peran memberi nama, warna, dan kuasa. Yang lebih tinggi di daftar berkuasa atas yang di bawah — dan tak seorang pun menyentuh peran setara atau di atas miliknya.",
    criar: "Buat peran",
    vazio: "Belum ada peran.",
    abaExibicao: "Tampilan",
    abaPermissoes: "Izin",
    abaMembros: "Anggota — {{quantos}}",
    everyone: "Berlaku untuk semua orang di server. Ini dasar yang ditumpuki peran lain.",
    nomeDoCargo: "Nama peran",
    cor: "Warna peran",
    corDica: "Mewarnai nama pemilik peran di daftar anggota dan di obrolan.",
    semCor: "Tanpa warna",
    corPersonalizada: "Warna khusus",
    estilo: "Gaya nama",
    segundaCor: "Warna kedua",
    segundaCorDica: "Tanpa itu gradasinya kembali jadi satu warna — tidak hilang.",
    limparSegundaCor: "Bersihkan warna kedua",
    icone: "Ikon",
    iconeDica: "Muncul di samping peran pada kartu profil pemiliknya.",
    exibirSeparado: "Tampilkan terpisah dari anggota lain",
    exibirSeparadoDica: "Peran mendapat bagiannya sendiri di daftar anggota.",
    permitirMencionar: "Izinkan menyebut peran ini",
    permitirMencionarDica: "Siapa pun nanti bisa memberi tahu semua yang punya peran itu.",
    semPoderDeConceder: "{{descricao}} (kamu tidak punya izin ini untuk memberikannya)",
    adicionar: "Tambahkan seseorang ke peran ini",
    tirar: "Cabut peran",
    semNinguem: "Belum ada yang punya peran ini.",
    apagar: "Hapus peran",
    excluirTitulo: "Hapus peran \"{{nome}}\"?",
    excluirDescricao: "Yang punya peran ini kehilangan semua yang diberikannya. Tidak bisa dibatalkan.",
    excluirAcao: "Hapus peran",
  },
  membros: {
    procurar: "Cari berdasarkan nama atau nama pengguna",
    membroDesde: "Anggota sejak",
    vazio: "Tidak ada yang ditemukan.",
    acoesPara: "Tindakan untuk {{nome}}",
    deCastigo: "dibungkam",
    tirarCastigo: "Cabut pembungkaman",
    castigo5min: "5 menit",
    castigo1h: "1 jam",
    castigo1d: "1 hari",
    castigo1s: "1 minggu",
    expulsar: "Keluarkan",
    expulsarTitulo: "Keluarkan {{nome}}?",
    expulsarDescricao: "meninggalkan {{servidor}} seketika. Bisa kembali dengan undangan — mengeluarkan tidak menghalangi kepulangan.",
    banir: "Cekal",
    banirTitulo: "Cekal {{nome}}?",
    banirDescricao: "meninggalkan {{servidor}} dan tidak bisa kembali, bahkan dengan undangan, sampai cekalnya dicabut.",
    motivo: "Alasan (opsional)",
    motivoDica: "Tercatat di log tindakan",
  },
  perfil: {
    titulo: "Profil server",
    descricao: "Beginilah servermu tampil di daftar dan di tautan undangan.",
    icone: "Ikon",
    faixa: "Banner atas",
    nomeDoServidor: "Nama server",
    campoDescricao: "Deskripsi",
    doQueE: "Server ini tentang apa?",
    comprimido: "Dikompres sebelum diunggah: {{economia}}",
  },
  etiqueta: {
    titulo: "Tag server",
    descricao: "Label maksimal 4 huruf yang muncul di samping nama setiap anggota — di obrolan dan di daftar orang. Di sini gratis: tanpa boost, tanpa level.",
    escolhaNome: "Pilih nama",
    limite: "Maksimal 4 karakter, huruf dan angka.",
    escolhaInsignia: "Pilih lencana",
    voce: "Kamu",
    fala1: "ada yang mau main?",
    fala2: "lihat tag-ku dong!",
    fala3: "wah, dapat dari mana itu",
  },
  expressoes: {
    comoUsar: "Tambahkan hingga {{limite}} emoji yang bisa dipakai semua orang di server ini. Ketik :nama: di obrolan untuk mengirimnya.",
    imagem: "Gambar",
    enviadoPor: "Diunggah oleh",
    semEmoji: "Belum ada emoji.",
    figurinhas: "Stiker",
    enviarFigurinha: "Unggah stiker",
    nomeDaFigurinha: "Nama stiker",
    exemploFigurinha: "Mis.: pelukan anak kucing",
    figurinhaGrande: "Stikernya melebihi {{limite}}.",
    deixaPraLa: "Sudahlah",
    sons: "Papan suara",
    enviarSom: "Unggah suara",
    nomeDoSom: "Nama suara",
    semSom: "Belum ada suara.",
    somGrande: "Suaranya melebihi {{limite}}.",
    emojiRelacionado: "Emoji terkait",
    ouvir: "Dengar",
    ouvirAssim: "Dengar begini",
    volumeDe: "Volume {{nome}}",
    volumeDica: "Berlaku untuk semua orang di server. Tiap orang tetap bisa mengecilkan suaranya hanya untuk dirinya, di panel panggilan.",
    falhaEnvio: "Berkas tidak bisa diunggah.",
    excluirTitulo: "Hapus {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Hilang dari server untuk semua orang. Pesan yang sudah memakainya tetap seperti apa adanya.",
  },
  canal: {
    tipoLink: "Tautan",
    tipoLinkDica: "Menunjuk ke alamat di luar dan terbuka di peramban",
    endereco: "Alamat",
    enderecoDica: "Ke mana kanal ini menuju. Harus diawali https://",
    visaoGeral: "Ikhtisar",
    nome: "Nama kanal",
    topico: "Topik kanal",
    topicoDica: "Di sini membicarakan apa?",
    modoLento: "Tiap orang hanya mengirim satu pesan per selang. Yang mengelola pesan atau kanal lewat begitu saja.",
    visibilidade: "Keterlihatan konten",
    padrao: "Bawaan",
    padraoDica: "Konten kanal selalu terlihat.",
    spoiler: "Kanal spoiler",
    spoilerDica: "Tandai kanal ini sebagai berisi spoiler, supaya kejutan alur dan topik berat tetap tersembunyi sampai ada yang memilih melihat.",
    idade: "Kanal dengan batasan usia",
    idadeDica: "Yang masuk harus mengonfirmasi sudah cukup umur untuk melihat kontennya.",
    bitrateDica: "Di atas 64 kbps bisa mengganggu yang koneksinya buruk.",
    qualidadeDeVideo: "Kualitas video",
    automatica: "Otomatis",
    limite: "Batas pengguna — {{valor}}",
    pessoas: "{{quantos}} orang",
    semLimite: "tanpa batas",
    permissoesDescricao: "Di sini kamu mengubah apa yang berlaku di kanal ini. Yang tetap di “warisi” terus mengikuti peran.",
    excluir: {
      titulo: "Hapus kanal",
      historico: "Seluruh riwayat {{canal}} ikut hilang, untuk semua orang.",
      digite: "Ketik {{canal}} untuk mengonfirmasi",
    },
  },
  moderacao: {
    titulo: "Tampilan moderator",
    semPermissao: "Kamu butuh izin “Moderasi anggota” untuk melihat ini.",
    fecharEsc: "Tutup (Esc)",
    atividade: "Aktivitas di server",
    mensagens: "Pesan",
    links: "Tautan",
    midia: "Media",
    acoesNaAuditoria: "Tindakan di log",
    moderacoesSofridas: "Moderasi yang diterima",
    permissoes: "Izin ({{quantas}})",
    semPermissaoEspecial: "Tidak ada izin khusus.",
    conta: "Akun",
    entrouNoServidor: "Bergabung ke server",
    contaCriadaEm: "Akun dibuat pada",
    deCastigoAte: "Dibungkam sampai",
    formaDeAdesao: "Cara bergabung",
    mensagem: "Pesan",
    castigo: "Pembungkaman",
    copiarId: "Salin ID",
    idCopiado: "ID disalin.",
    adicionarCargo: "Tambah peran",
    semCargos: "Belum ada peran dibuat",
    soEveryone: "Hanya @everyone.",
    voltar: "Kembali",
    vazio: "Tidak ada apa-apa di sini.",
    cinquenta: "Menampilkan 50 terbaru.",
    irParaMensagem: "Ke pesan",
    precisaSerAmigo: "Kalian harus berteman dulu untuk mengobrol.",
    expulsarDescricao: "Meninggalkan server seketika, tapi bisa kembali dengan undangan.",
    banirDescricao: "Meninggalkan server dan tidak bisa kembali, bahkan dengan undangan, sampai cekalnya dicabut.",
    castigarTitulo: "Bungkam {{nome}}?",
    castigoDescricao: "Selama berlaku, dia tidak menulis maupun bicara di kanal mana pun di server.",
    aplicarCastigo: "Terapkan pembungkaman",
    duracao: "Durasi dalam menit",
    informeDuracao: "Sebutkan durasinya dalam menit.",
  },
  abas: {
    pesquisar: "Cari di pengaturan",
    semResultado: "Tidak ada yang bernama itu di sini.",
    comunidade: "Komunitas",
    expressoes: "Ekspresi",
    pessoas: "Orang",
    apps: "Aplikasi",
    moderacao: "Moderasi",
    banimentos: "Cekal",
  },
};
