export const servidor = {
  titulo: "Pengaturan server",
  auditoria: {
    titulo: "Log tindakan",
    porUsuario: "Saring berdasarkan orang",
    porAcao: "Saring berdasarkan tindakan",
    vazio: "Belum ada yang tercatat dengan saringan ini.",
    motivo: "Alasan:",
  },
  banimentos: {
    titulo: "Daftar cekal server",
    descricao: "Yang ada di sini tidak bisa masuk lagi, bahkan dengan undangan baru. Mencabut cekal mengembalikan akses seketika.",
    procurar: "Cari cekal berdasarkan nama pengguna",
    vazioTitulo: "Tidak ada cekal",
    vazio: "Kamu belum mencekal siapa pun… tapi kalau suatu saat perlu, jangan ragu.",
    desbanir: "Cabut cekal",
  },
  excluir: {
    titulo: "Hapus server",
    aviso: "Ini tidak bisa dibatalkan.",
  },
  emblemas: {
    titulo: "Lencana",
    vazio: "Belum ada lencana.",
    novo: "Lencana baru",
  },
  convites: {
    titulo: "Undangan",
    descricao: "Semua tautan undangan aktif server ini.",
    vazio: "Belum ada undangan yang dibuat.",
    revogar: "Cabut undangan",
  },
  integracoes: {
    titulo: "Integrasi",
    descricao: "Webhook adalah alamat yang memposting ke sebuah kanal tanpa perlu akun. Berguna untuk mengabari bahwa build lolos, ada yang membuka tiket, atau apa pun yang ingin kamu kirim dari skrip.",
    novo: "Webhook baru",
    vazio: "Belum ada webhook. Buat satu dan tempel URL-nya di tempat kamu ingin pesannya berasal.",
    canal: "Kanal",
    apagar: "Hapus webhook",
    comoUsar: "Cara memakai",
    comoUsarTexto: "Kirim POST berisi JSON. Formatnya sama dengan Discord, jadi skrip yang sudah ada berjalan tanpa diubah:",
  },
  engajamento: {
    titulo: "Keterlibatan",
    descricao: "Apa yang server lakukan sendiri agar tidak terasa kosong saat ada orang baru datang.",
    sistema: "Pesan sistem",
    boasVindas: "Kirim pesan selamat datang saat ada yang bergabung",
    sorteio: "Tanpa teksmu sendiri di bawah, kalimatnya diundi — yang itu-itu saja cepat membosankan.",
    canalDoSistema: "Kanal pesan sistem",
    mensagem: "Pesan selamat datang",
    deixeVazio: "Biarkan kosong untuk mengundi dari kalimat yang sudah ada",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filter yang memoderasi sendiri, bahkan sebelum pesannya ada. Yang mengelola server tidak pernah difilter — dan peran yang dikecualikan lewat begitu saja.",
    palavras: {
      titulo: "Blokir kata milikmu",
      descricao: "Daftar katamu yang tidak boleh ditulis siapa pun.",
    },
    mencoes: {
      titulo: "Blokir spam sebutan",
      descricao: "Memblokir pesan dengan terlalu banyak sebutan sekaligus.",
    },
    links: {
      titulo: "Blokir tautan",
      descricao: "Menahan setiap alamat yang ditempel di obrolan.",
    },
    definir: "Atur",
    nomeDaRegra: "Nama aturan",
    bloqueadas: "Kata yang diblokir",
    digiteEnter: "Ketik lalu tekan Enter",
    comparacao: "Pencocokan mengabaikan huruf besar, aksen, dan tanda baca — dan tidak menangkap kata di dalam kata lain.",
    aPartirDe: "Blokir mulai dari berapa sebutan",
    oQueFazer: "Apa yang dilakukan",
    canalDoAlerta: "Kanal peringatan",
    escolhaCanal: "Pilih kanal",
    castigo: "Bungkam (menit)",
    isentos: "Peran yang dikecualikan",
    semCargos: "Belum ada peran yang dibuat.",
    salvarRegra: "Simpan aturan",
    apagar: "Hapus aturan",
    excluirTitulo: "Hapus aturan AutoMod ini?",
    excluirDescricao: "Server langsung berhenti menyaring dengannya. Bisa dibuat lagi, tapi pengaturan yang sekarang hilang.",
    excluirAcao: "Hapus aturan",
  },
  cargos: {
    titulo: "Peran",
    descricao: "Peran memberi nama, warna, dan kuasa. Yang lebih tinggi di daftar berkuasa atas yang di bawah — dan tak seorang pun menyentuh peran setara atau di atas miliknya.",
    criar: "Buat peran",
    vazio: "Belum ada peran.",
    abaExibicao: "Tampilan",
    abaPermissoes: "Izin",
    abaMembros: "Anggota — {{quantos}}",
    everyone: "Berlaku untuk semua orang di server. Ini dasar yang ditumpuki peran lain.",
    nomeDoCargo: "Nama peran",
    cor: "Warna peran",
    corDica: "Mewarnai nama pemilik peran di daftar anggota dan di obrolan.",
    semCor: "Tanpa warna",
    corPersonalizada: "Warna khusus",
    estilo: "Gaya nama",
    segundaCor: "Warna kedua",
    segundaCorDica: "Tanpa itu gradasinya kembali jadi satu warna — tidak hilang.",
    limparSegundaCor: "Bersihkan warna kedua",
    icone: "Ikon",
    iconeDica: "Muncul di samping peran pada kartu profil pemiliknya.",
    exibirSeparado: "Tampilkan terpisah dari anggota lain",
    exibirSeparadoDica: "Peran mendapat bagiannya sendiri di daftar anggota.",
    permitirMencionar: "Izinkan menyebut peran ini",
    permitirMencionarDica: "Siapa pun nanti bisa memberi tahu semua yang punya peran itu.",
    semPoderDeConceder: "{{descricao}} (kamu tidak punya izin ini untuk memberikannya)",
    adicionar: "Tambahkan seseorang ke peran ini",
    tirar: "Cabut peran",
    semNinguem: "Belum ada yang punya peran ini.",
    apagar: "Hapus peran",
    excluirTitulo: "Hapus peran \"{{nome}}\"?",
    excluirDescricao: "Yang punya peran ini kehilangan semua yang diberikannya. Tidak bisa dibatalkan.",
    excluirAcao: "Hapus peran",
  },
  membros: {
    procurar: "Cari berdasarkan nama atau nama pengguna",
    membroDesde: "Anggota sejak",
    vazio: "Tidak ada yang ditemukan.",
    acoesPara: "Tindakan untuk {{nome}}",
    deCastigo: "dibungkam",
    tirarCastigo: "Cabut pembungkaman",
    castigo5min: "5 menit",
    castigo1h: "1 jam",
    castigo1d: "1 hari",
    castigo1s: "1 minggu",
    expulsar: "Keluarkan",
    expulsarTitulo: "Keluarkan {{nome}}?",
    expulsarDescricao: "meninggalkan {{servidor}} seketika. Bisa kembali dengan undangan — mengeluarkan tidak menghalangi kepulangan.",
    banir: "Cekal",
    banirTitulo: "Cekal {{nome}}?",
    banirDescricao: "meninggalkan {{servidor}} dan tidak bisa kembali, bahkan dengan undangan, sampai cekalnya dicabut.",
    motivo: "Alasan (opsional)",
    motivoDica: "Tercatat di log tindakan",
  },
  perfil: {
    titulo: "Profil server",
    descricao: "Beginilah servermu tampil di daftar dan di tautan undangan.",
    icone: "Ikon",
    faixa: "Banner atas",
    nomeDoServidor: "Nama server",
    campoDescricao: "Deskripsi",
    doQueE: "Server ini tentang apa?",
    comprimido: "Dikompres sebelum diunggah: {{economia}}",
  },
  etiqueta: {
    titulo: "Tag server",
    descricao: "Label maksimal 4 huruf yang muncul di samping nama setiap anggota — di obrolan dan di daftar orang. Di sini gratis: tanpa boost, tanpa level.",
    escolhaNome: "Pilih nama",
    limite: "Maksimal 4 karakter, huruf dan angka.",
    escolhaInsignia: "Pilih lencana",
    voce: "Kamu",
    fala1: "ada yang mau main?",
    fala2: "lihat tag-ku dong!",
    fala3: "wah, dapat dari mana itu",
  },
  expressoes: {
    comoUsar: "Tambahkan hingga {{limite}} emoji yang bisa dipakai semua orang di server ini. Ketik :nama: di obrolan untuk mengirimnya.",
    imagem: "Gambar",
    enviadoPor: "Diunggah oleh",
    semEmoji: "Belum ada emoji.",
    figurinhas: "Stiker",
    enviarFigurinha: "Unggah stiker",
    nomeDaFigurinha: "Nama stiker",
    exemploFigurinha: "Mis.: pelukan anak kucing",
    figurinhaGrande: "Stikernya melebihi {{limite}}.",
    deixaPraLa: "Sudahlah",
    sons: "Papan suara",
    enviarSom: "Unggah suara",
    nomeDoSom: "Nama suara",
    semSom: "Belum ada suara.",
    somGrande: "Suaranya melebihi {{limite}}.",
    emojiRelacionado: "Emoji terkait",
    ouvir: "Dengar",
    ouvirAssim: "Dengar begini",
    volumeDe: "Volume {{nome}}",
    volumeDica: "Berlaku untuk semua orang di server. Tiap orang tetap bisa mengecilkan suaranya hanya untuk dirinya, di panel panggilan.",
    falhaEnvio: "Berkas tidak bisa diunggah.",
    excluirTitulo: "Hapus {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Hilang dari server untuk semua orang. Pesan yang sudah memakainya tetap seperti apa adanya.",
  },
};
