export const amizades = {
  ativosAgora: "지금 활동 중",
  procurando: "누가 있는지 보는 중…",
  tudoTranquilo: "지금은 조용합니다…",
  tudoTranquiloDetalhe: "당신이나 친구가 통화에 참여하면 여기에 표시되고, 한 번의 클릭으로 함께할 수 있습니다.",
  emVoz: "음성 중",
  voce: "당신",
  soVoce: "당신뿐",
  pessoas: "{{quantas}}명",
  voltarParaChamada: "통화로 돌아가기",
  entrarNaChamada: "통화 참여",
  abrirCanal: "{{servidor}}의 {{canal}} 열기",
  mensagensDiretas: "다이렉트 메시지",
  encontreConversa: "대화 찾기",
  amigos: "친구",
  conversas: "대화",
  semConversas: "아직 대화가 없습니다. 친구를 추가해 시작하세요.",
  semConversaComEsseNome: "그런 이름의 대화가 없습니다.",
  abrirMenu: "서버와 대화 열기",
  solicitacoes: "메시지 요청",
  pedidos: "요청",
  spam: "스팸",
  pedidosPendentes: "대기 중인 요청",
  marcadosComoSpam: "스팸으로 표시됨",
  aceitar: "수락",
  ignorar: "무시",
  marcarSpam: "스팸으로 표시",
  semPedidos: "대기 중인 요청이 없습니다.",
  semPedidosDetalhe: "친구는 아니지만 같은 서버에 있는 사람은 당신의 대화에 닿기 전에 여기로 옵니다.",
  semSpam: "스팸으로 표시된 것이 없습니다.",
  semSpamDetalhe: "스팸 필터가 걸러낸 것, 또는 직접 표시한 것은 이 탭에 남습니다.",
  umServidorEmComum: "공통 서버 1개",
  servidoresEmComum: "공통 서버 {{quantos}}개",
  semServidoresEmComum: "공통 서버 없음",
};
