export const chamada = {
  conectando: "통화에 연결하는 중…",
  naoEntrou: "통화에 참여하지 못했습니다",
  sair: "통화 나가기",
  sairDaVoz: "음성 통화 나가기",
  desconectar: "연결 끊기",
  voltar: "통화로 돌아가기",
  voltarAosQuadros: "통화 타일로 돌아가기",
  fecharChat: "채팅 닫기",
  carregandoPrevia: "미리보기를 불러오는 중…",
  maisOpcoes: "더 보기",
  deVideo: "영상 통화",
  deVoz: "음성 통화",
  alguem: "누군가",
  volume: {
    entrada: "입력 음량",
    saida: "출력 음량",
    live: "라이브 음량",
    liveComPorcento: "라이브 음량 ({{porcento}}%)",
    liveSemSom: "라이브 음소거",
  },
  aparelhos: {
    entrada: "입력 장치",
    saida: "출력 장치",
    camera: "카메라",
    microfone: "마이크",
    saidaCurto: "출력",
    oDoSistema: "시스템 설정",
    aDoSistema: "시스템 설정",
    semEscolhaDeSaida: "이 브라우저에서는 출력을 고를 수 없습니다 — 시스템이 정합니다.",
    espelhar: "내 카메라 좌우 반전",
    configEntrada: "입력 설정",
    configSaida: "출력 설정",
    configCamera: "카메라 설정",
    configAudioEVideo: "오디오 및 비디오 설정",
  },
  tela: {
    compartilhar: "화면 공유",
    compartilharAcao: "공유",
    cancelar: "취소",
    telas: "화면",
    janelas: "창",
    somDoComputador: "컴퓨터 소리도 같이 보내기",
    somDoSistema: "시스템 소리도 같이 보내기",
    configCompartilhamento: "공유 설정",
    mostrarSemVideo: "영상 없는 사람도 표시",
    semFontes: "공유할 화면이나 창을 시스템이 돌려주지 않았습니다.",
    pararDeCompartilhar: "공유 중지",
    encerrarTransmissao: "방송 종료",
  },
  live: {
    etiqueta: "라이브",
    etiquetaMaiuscula: "라이브",
    assistir: "방송 보기",
    assistirPessoa: "{{nome}} 보기",
    pararDeAssistir: "그만 보기",
  },
  membro: {
    mudarMeuApelido: "내 별명 바꾸기",
    meuMicrofone: "내 마이크",
    ouvirChamada: "통화 듣기",
    copiarMeuId: "내 ID 복사",
    idCopiado: "ID를 복사했습니다.",
    mensagem: "메시지",
    silenciar: "음소거",
    alterarApelido: "별명 바꾸기",
    cargos: "역할",
    semCargo: "만들어진 역할이 없습니다",
    moverPara: "이동",
    silenciarNoServidor: "서버에서 음성 음소거",
    desativarAudioNoServidor: "서버에서 오디오 끄기",
    desconectar: "연결 끊기",
    apelidoTitulo: "이 서버에서의 내 별명",
    apelidoDeAlguem: "{{nome}} 님의 별명",
    apelidoCampo: "별명",
    apelidoDicaPropria: "여기서만 적용됩니다. 비워 두면 평소 이름으로 돌아갑니다.",
    apelidoDicaDeOutro: "이 서버에서만 적용됩니다. 비워 두면 원래 이름으로 돌아갑니다.",
  },
  detalhes: {
    abrir: "음성 세부 정보",
    titulo: "음성 세부 정보",
    conexao: "연결",
    pingMedio: "평균 핑",
    ultimoPing: "마지막 핑",
    perda: "보낸 패킷 손실",
    medindo: "측정 중…",
    criptografado: "서버까지 암호화됨 (DTLS-SRTP)",
    explicacao: "250ms를 넘으면 대화에서 지연이 느껴지고 말이 겹치기 시작합니다. 패킷 손실이 10%를 넘으면 목소리가 로봇처럼 들립니다. 두 경우 모두 문제는 거의 항상 나와 인터넷 사이에 있습니다. Wi-Fi 대신 유선을 써 보거나 공유기를 다시 켜 보세요.",
  },
  microfone: {
    bloqueado: "마이크가 차단되었습니다 — 듣기만 하고 있습니다. 브라우저 권한에서 접근을 허용하세요.",
    bloqueadoNoMac: "macOS가 마이크를 막고 있습니다. 다음을 체크하세요:",
    caminhoNoMac: "시스템 설정 → 개인정보 보호 및 보안 → 마이크",
    abrirAjustes: "설정 열기",
    vaiReabrir: "macOS가 앱을 다시 열라고 요청합니다.",
    naoAbriu: "마이크를 열지 못했습니다 — 듣기만 하고 있습니다. 설정 → 음성 및 비디오에서 장치를 확인하세요.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS가 아직 화면 기록을 허용하지 않았습니다. 허용하지 않으면 공유 화면이 검게 나옵니다.",
    marque: "다음을 체크하세요:",
    reabra: "화면 기록에서 켜고 앱을 다시 여세요.",
  },
  ruido: {
    titulo: "소음 억제",
    explicacao: "목소리에서 배경 소음을 없앱니다. 말하면서 손뼉을 치거나 키보드를 밀어 보세요 — 통화 중인 사람에게는 목소리만 들립니다.",
    semSuporte: "이 브라우저는 고급 억제를 실행하지 못합니다. 브라우저 자체 기능은 그대로 적용되지만 더 약합니다.",
    aplicando: "통화에 적용하는 중…",
    faleParaTestar: "말해서 확인해 보세요",
    verdeQuandoPassa: "목소리가 지나가면 초록색이 됩니다.",
    teOuvindo: "지금 들리고 있습니다.",
    feitoCom: "사용 기술:",
    aquiNoAparelho: "· 이 기기 안에서만 처리합니다",
    ajustes: "설정",
  },
  permissoes: {
    titulo: "macOS 권한",
    detalhe: "macOS는 한 번만 묻고, 그 뒤로는 macOS 설정에서만 바뀝니다. 여기서 무엇이 적용 중인지 보고 빠진 것을 해결할 수 있습니다.",
    concedida: "허용됨",
    negada: "거부됨",
    naoPedida: "요청하지 않음",
    permitir: "허용",
    abrirAjustes: "설정 열기",
    microfone: "마이크",
    microfoneDetalhe: "통화에서 말하고 입력을 테스트합니다.",
    camera: "카메라",
    cameraDetalhe: "통화에서 영상을 켭니다.",
    tela: "화면 기록",
    telaDetalhe: "화면과 창을 공유합니다.",
    monitoramento: "입력 모니터링",
    monitoramentoDetalhe: "Gravaê가 백그라운드에 있어도 푸시투토크를 사용합니다.",
  },
  jaConectado: {
    titulo: "이미 이 통화에 참여 중입니다",
    trazer: "통화를 여기로 가져오기",
    deixar: "그대로 두기",
    detalhe: "여기로 가져오면 다른 쪽은 통화에서 나갑니다 — 계정은 한 번에 한 곳에만 있습니다.",
  },
};
