export const comum = {
  carregando: "불러오는 중…",
  salvar: "저장",
  salvando: "저장 중…",
  descartar: "취소",
  redefinir: "초기화",
  naoSalvo: "저장하지 않은 변경 사항이 있습니다.",
  fechar: "닫기",
  criar: "만들기",
  nome: "이름",
  emoji: "이모지",
  previa: "미리 보기",
  cancelar: "취소",
  enviar: "보내기",
  apagar: "삭제",
  excluir: "삭제",
  remover: "빼기",
  trocar: "바꾸기",
};
