export const configuracoes = {
  sair: "로그아웃",
  versoes: {
    copiar: "클릭해서 복사",
    copiado: "복사됨",
  },
  telas: {
    conta: "내 계정",
    privacidade: "개인정보",
    conexoes: "연결",
    voz: "오디오",
    video: "비디오",
    avisos: "알림",
    aplicativos: "애플리케이션",
    aparencia: "모양",
    batePapo: "채팅",
    acessibilidade: "접근성",
    idioma: "언어",
    aplicativo: "앱 받기",
    atalhos: "단축키",
    servidor: "서버",
  },
  grupos: {
    conta: "계정",
    app: "앱 설정",
    desenvolvedor: "개발자",
    administracao: "관리",
  },
  secoes: {
    detalhesDeLogin: "로그인 정보",
    dispositivos: "기기",
    usuariosBloqueados: "차단한 사용자",
    aplicativosAutorizados: "승인된 앱",
    sessoes: "세션",
    amigosEDms: "친구 및 다이렉트 메시지",
    compartilhamentoDeAtividade: "활동 공유",
    visibilidadeDoPerfil: "프로필 공개 범위",
    exportarDados: "데이터 내보내기",
    exclusaoDeDados: "데이터 삭제",
    tema: "테마",
    corDeDestaque: "강조 색상",
    interface: "인터페이스",
    listaDeCanais: "채널 목록",
    zoomDoApp: "앱 확대 수준",
    escalaDaFonte: "채팅 글꼴 크기",
    modoStreamer: "방송 개인정보",
    movimento: "모션",
    textoEmVoz: "텍스트 음성 변환",
    teclado: "키보드",
    formatoDaHora: "시간 형식",
    idiomaDaInterface: "인터페이스 언어",
    dispositivosDeVoz: "기기",
    testeDoMicrofone: "마이크 테스트",
    modoDeEntrada: "입력 모드",
    sensibilidade: "입력 감도",
    qualidade: "품질",
    camera: "카메라",
    transmissao: "방송",
    exibicao: "표시",
    entrada: "입력",
    midia: "미디어",
    geral: "일반",
    preferenciaDeMencao: "멘션 설정",
    sons: "소리",
  },
};
