export const configuracoes = {
  efeitos: {
    titulo: "포인터 효과",
    detalhe: "화면 위에 그려지는 자취와 불꽃입니다. 처음엔 꺼져 있고, 움직임을 줄여 달라고 했다면 알아서 꺼집니다.",
    rastro: "커서 자취",
    rastroDetalhe: "포인터를 따라오며 뒤에서 옅어지는 선입니다.",
    faisca: "클릭 불꽃",
    faiscaDetalhe: "누른 자리에서 튀어 나가는 짧은 선입니다.",
    cor: "색",
    espessura: "굵기",
    comprimento: "길이",
    tamanho: "크기",
    quantidade: "개수",
  },
  email: {
    verificarTitulo: "이메일을 확인해 주세요",
    verificarDetalhe: "확인한 사람만 글을 쓸 수 있는 커뮤니티가 있습니다. 한 번만 누르면 됩니다.",
    enviar: "링크 보내기",
    enviado: "받은 편지함을 보세요. 링크는 하루 동안 유효합니다.",
    falhou: "이메일을 보내지 못했습니다.",
    confirmado: "이메일을 확인했습니다",
    confirmadoDetalhe: "끝났습니다. 이제 확인을 요구하는 커뮤니티에서도 글을 씁니다.",
    linkIncompleto: "주소가 잘렸습니다",
    linkIncompletoDetalhe: "주소에 코드가 없습니다. 이메일의 링크를 바로 열어 주세요.",
    confirmando: "확인하는 중…",
    expirou: "이 링크는 이미 썼거나 기한이 지났습니다.",
    irParaOApp: "앱으로 가기",
  },
  tema: {
    indisponivel: "테마를 열 수 없습니다",
    indisponivelDetalhe: "올린 사람이 지웠거나, 링크가 잘못됐습니다.",
    indisponivelLinha: "테마를 열 수 없습니다. 올린 사람이 지웠거나, 링크가 잘못됐습니다.",
    importar: "테마 가져오기",
    importarCurto: "가져오기",
    importarDetalhe: "지금 쓰는 테마를 대체합니다. 나중에 설정 > 모양 > 테마 스튜디오에서 고칠 수 있습니다.",
    porAutor: "만든이 {{autor}}",
    umaCorTrocada: "색 1개 교체",
    coresTrocadas: "색 {{quantas}}개 교체",
    avisoDeCss: "이 테마에는 만든 사람의 CSS가 들어 있고, CSS는 화면 구석구석에 손을 댑니다. 믿을 만한 사람의 것만 가져오세요.",
    soCores: "이 테마는 색만 바꿉니다. 외부 CSS는 없습니다.",
    verCss: "CSS 보기",
    esconderCss: "CSS 숨기기",
    aplicar: "적용",
    previaSemMotor: "미리보기에서는 엔진이 돌지 않습니다. 설치하면 볼 수 있습니다.",
    motorAnimado: "{{motor}} 애니메이션",
  },
  sair: "로그아웃",
  versoes: {
    termos: "서비스 약관",
    privacidade: "개인정보 처리방침",
    copiar: "클릭해서 복사",
    copiado: "복사됨",
  },
  subscription: {
    seePlans: "플랜 보기",
    upgradeSubtitle: "글쓰기, 파일 전송, 방송 한도가 커지고 전용 기능을 쓸 수 있어요.",
    perMonth: "월",
    perYear: "년",
    save: "{{percent}}% 절약",
    howToPay: "어떻게 결제할까요?",
    legal: "결제 후 7일 이내에 환불을 요청할 수 있습니다. 결제는 Stripe가 처리하며 저희는 카드 번호를 절대 볼 수 없습니다.",
    compare: "무료 vs Infinity",
    featureColumn: "기능",
    freeColumn: "무료",
    messageRow: "메시지 글자 수 한도",
    attachmentRow: "전송 파일 크기",
    screenRow: "동영상 화질",
    megabytesValue: "{{value}}MB",
    screenValue: "{{resolution}} · {{fps}}fps",
    alreadyPremium: "이미 {{date}}까지 Infinity를 이용 중입니다.",
    upsell: "Infinity로 한도 늘리기",
    screenUpsell: "Infinity로 더 높은 화질",
    free: "무료 플랜을 사용 중입니다.",
    activeUntil: "Infinity가 {{date}}까지 활성화되어 있습니다.",
    renews: "{{date}}에 자동으로 갱신됩니다.",
    endsAt: "구독이 취소되었으며 {{date}}에 종료됩니다.",
    pastDue: "최근 결제에 실패했습니다. Infinity를 유지하려면 카드를 업데이트하세요.",
    waiting: "결제를 확인하는 중…",
    subscribe: "구독하기",
    monthly: "월간",
    yearly: "연간",
    automatic: "카드, 자동 갱신",
    pass: "기간만 결제 (Pix 또는 카드)",
    manage: "결제 관리",
    refund: "환불 요청",
    refundDetail: "결제 후 7일 이내에 취소할 수 있습니다: {{amount}}, {{date}}까지.",
    refundConfirm: "환불을 요청할까요?",
    refundConfirmDetail: "같은 결제 수단으로 환불되며 Infinity는 즉시 종료됩니다.",
    refunded: "환불을 요청했습니다.",
    unavailable: "구독은 아직 이용할 수 없습니다.",
    success: "결제가 완료되었습니다. 감사합니다!",
    canceled: "결제가 취소되었습니다.",
    error: "문제가 발생했습니다. 다시 시도하세요.",
    no: "없음",
    tagRow: "사용자 지정 태그",
    guildProfilesRow: "커뮤니티별 프로필",
    badgeRow: "프로필 배지",
    communitiesRow: "커뮤니티",
    savedRow: "저장한 메시지",
    animatedEmojiRow: "움직이는 이모지",
    expressionsRow: "어디서나 이모지와 스티커",
    animatedProfileRow: "움직이는 아바타와 배너",
    earlyAccessRow: "새 기능 미리 사용",
    themesRow: "사용자 지정 테마",
  },
  telas: {
    subscription: "Infinity",
    conta: "내 계정",
    privacidade: "개인정보",
    conexoes: "연결",
    voz: "오디오",
    video: "비디오",
    avisos: "알림",
    aplicativos: "애플리케이션",
    aparencia: "모양",
    batePapo: "채팅",
    acessibilidade: "접근성",
    idioma: "언어",
    aplicativo: "앱 받기",
    atalhos: "단축키",
    desktop: "데스크톱 앱",
    avancado: "고급",
    servidor: "서버",
    comunicado: "시스템 공지",
    denuncias: "신고",
    publicacoes: "배포",
  },
  grupos: {
    conta: "계정",
    app: "앱 설정",
    desenvolvedor: "개발자",
    administracao: "관리",
  },
  secoes: {
    detalhesDeLogin: "로그인 정보",
    dispositivos: "기기",
    usuariosBloqueados: "차단한 사용자",
    aplicativosAutorizados: "승인된 앱",
    sessoes: "세션",
    amigosEDms: "친구 및 다이렉트 메시지",
    compartilhamentoDeAtividade: "활동 공유",
    visibilidadeDoPerfil: "프로필 공개 범위",
    exportarDados: "데이터 내보내기",
    exclusaoDeDados: "데이터 삭제",
    tema: "테마",
    corDeDestaque: "강조 색상",
    interface: "인터페이스",
    listaDeCanais: "채널 목록",
    zoomDoApp: "앱 확대 수준",
    escalaDaFonte: "채팅 글꼴 크기",
    modoStreamer: "방송 개인정보",
    cursores: "커서",
    movimento: "모션",
    textoEmVoz: "텍스트 음성 변환",
    teclado: "키보드",
    formatoDaHora: "시간 형식",
    idiomaDaInterface: "인터페이스 언어",
    dispositivosDeVoz: "기기",
    testeDoMicrofone: "마이크 테스트",
    modoDeEntrada: "입력 모드",
    sensibilidade: "입력 감도",
    qualidade: "품질",
    camera: "카메라",
    transmissao: "방송",
    exibicao: "표시",
    entrada: "입력",
    midia: "미디어",
    geral: "일반",
    preferenciaDeMencao: "멘션 설정",
    sons: "소리",
  },
};
