export const conversa = {
  lista: {
    carregando: "메시지를 불러오는 중…",
    carregandoMais: "불러오는 중…",
    verMais: "위로 스크롤하면 더 볼 수 있어요",
    semHistorico: "기록을 볼 수 없음",
    semHistoricoDetalhe: "당신의 역할에는 #{{canal}} 기록을 읽을 권한이 없습니다. 여기 있는 동안 새 메시지는 계속 표시됩니다.",
    boasVindas: "#{{canal}} 채널에 오신 걸 환영해요",
    boasVindasDetalhe: "여기가 #{{canal}} 채널의 시작입니다.",
  },
  data: {
    hoje: "오늘",
    ontem: "어제",
    hojeAs: "오늘 {{hora}}",
    ontemAs: "어제 {{hora}}",
  },
  digitando: {
    um: "{{nome}} 님이 입력 중…",
    dois: "{{primeiro}} 님과 {{segundo}} 님이 입력 중…",
    varios: "{{quantidade}}명이 입력 중…",
  },
  mensagem: {
    usou: "사용함",
    fixada: "고정됨",
    editado: "(수정됨)",
    ignorada: "차단한 사람이 보낸 메시지입니다.",
    mostrar: "보기",
    escPara: "Esc로",
    cancelar: "취소",
    enterParaSalvar: "Enter로 저장",
    falhou: "보내지 못했습니다. 다시 시도",
    naoLidasDaqui: "여기부터 읽지 않음으로 표시했습니다.",
    linkCopiado: "링크를 복사했습니다.",
    idCopiado: "ID를 복사했습니다.",
    naoDeuParaCopiar: "브라우저가 복사를 허용하지 않았습니다.",
    apagarTitulo: "메시지를 삭제할까요?",
    apagarDescricao: "채널의 모두에게서 사라집니다. 되돌릴 수 없습니다.",
    apagarAcao: "삭제",
    citacaoAnexo: "클릭하면 첨부 파일을 볼 수 있어요",
    citacaoSumiu: "원래 메시지는 더 이상 여기 없습니다.",
    reagirCom: "{{emoji}}(으)로 반응 — 길게 누르면 슈퍼 반응",
    segureParaSuper: "{{emoji}} — 길게 누르면 슈퍼 반응",
  },
  acoes: {
    reagir: "반응",
    responder: "답장",
    encaminhar: "전달",
    favoritar: "메시지 저장",
    tirarDosFavoritos: "저장에서 빼기",
    marcarNaoLida: "읽지 않음으로 표시",
    copiarLink: "메시지 링크 복사",
    copiarId: "메시지 ID 복사",
    fixar: "메시지 고정",
    desafixar: "고정 해제",
    editar: "수정",
    apagar: "삭제",
    mais: "더 보기",
    adicionarReacao: "반응 추가",
    superReagirCom: "{{emoji}}(으)로 슈퍼 반응",
    fixarMensagem: "메시지 고정",
    desafixarMensagem: "메시지 고정 해제",
    editarMensagem: "메시지 수정",
    apagarMensagem: "메시지 삭제",
  },
  mencao: {
    cargo: "역할 멘션",
    pessoa: "멘션",
    alguem: "누군가",
    cargoSemNome: "역할",
    here: "온라인인 사람에게 알립니다",
    everyone: "서버 전체에 알립니다",
  },
  codigo: {
    copiar: "복사",
    copiado: "복사됨",
    copiarAria: "코드 복사",
    copiadoAria: "코드를 복사했습니다",
    recolher: "접기",
    expandir: "펼치기",
    verInteiro: "파일 전체 보기",
    maisOpcoes: "더 보기",
    baixar: "다운로드",
    recolherLinhas: "접기 ({{linhas}}줄)",
    expandirLinhas: "펼치기 ({{linhas}}줄)",
    mudarIdioma: "언어 변경",
    procurarIdioma: "언어 코드 검색…",
    nenhumIdioma: "해당 언어가 없습니다.",
    quebrarTexto: "텍스트 줄바꿈",
  },
  caixa: {
    escrever: "#{{canal}}에 메시지 보내기",
    escreverSemCanal: "메시지 보내기",
    semPermissao: "이 채널에 메시지를 보낼 권한이 없습니다",
    solteParaAnexar: "놓으면 첨부됩니다",
    longaTitulo: "메시지가 너무 깁니다…",
    longaDescricao: "{{limite}}자 제한에 도달했습니다. 파일로 보낼 수 있습니다.",
    enviarComoArquivo: "파일로 보내기",
    textoComoArquivo: "텍스트를 파일로 보내기",
    arquivoGrandeTitulo: "파일이 너무 큽니다",
    arquivoGrandeDescricao: "“{{arquivo}}”은(는) 파일당 {{limite}}MB 제한을 넘습니다.",
    respondendoPara: "답장 대상",
    vaiNotificar: "상대에게 알림이 갑니다",
    naoVaiNotificar: "상대에게 알림이 가지 않습니다",
    ligado: "켜짐",
    desligado: "꺼짐",
    pararDeResponder: "답장 그만두기",
    mais: "더 보기",
    enviarArquivo: "파일 보내기",
    criarEnquete: "투표 만들기",
    expressoes: "이모지, GIF, 스티커",
    enviar: "보내기",
    aguardandoEnvio: "업로드를 기다리는 중",
    modoLento: "저속 모드 켜짐 ({{tempo}})",
    modoLentoDica: "저속 모드가 {{segundos}}초로 설정되어 있습니다. 다음 메시지를 보내기 전에 기다려 주세요.",
  },
  anexos: {
    enviando: "업로드 중…",
    modificar: "{{arquivo}} 수정",
    remover: "{{arquivo}} 제거",
    ver: "{{arquivo}} 보기",
    mostrarSpoiler: "스포일러 보기: {{arquivo}}",
    spoiler: "스포일러",
    spoilerTitulo: "스포일러",
    editarTitulo: "첨부 파일 수정",
    nomeDoArquivo: "파일 이름",
    descricao: "대체 텍스트 설명",
    descricaoDica: "스크린 리더를 위해 이 미디어를 설명해 주세요",
    marcarSpoiler: "스포일러로 표시",
    cancelar: "취소",
    salvar: "저장",
  },
  cartao: {
    tocador: "플레이어",
    abrir: "{{destino}} 열기",
    tocar: "{{titulo}} 재생",
    video: "영상",
    verImagem: "이미지 보기",
  },
  enquete: {
    titulo: "투표",
    encerrada: "투표 종료됨",
    variasRespostas: "투표 — 복수 응답",
    umVoto: "{{quantidade}}표",
    votos: "{{quantidade}}표",
    umVotoNoTotal: "총 {{quantidade}}표",
    votosNoTotal: "총 {{quantidade}}표",
    encerraEm: "{{quando}}에 종료",
    encerrarAgora: "지금 종료",
  },
  fixadas: {
    titulo: "고정된 메시지",
    vazio: "이 채널에는 아직 고정된 메시지가 없습니다.",
    desafixar: "고정 해제",
    anexo: "(첨부 파일)",
    enquete: "(투표)",
    dicaRotulo: "팁:",
    dica: "‘메시지 관리’ 권한이 있으면 메시지 메뉴에서 바로 고정할 수 있습니다.",
  },
  encaminhar: {
    titulo: "메시지 전달",
    paraOnde: "어디로 보낼까요?",
    semTexto: "(내용 없는 메시지)",
    nenhumLugar: "그런 이름의 곳이 없습니다.",
    canais: "채널",
    conversas: "다이렉트 메시지",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Klipy에서 검색",
    figurinha: "스티커",
    buscarFigurinha: "딱 맞는 스티커 찾기",
    buscarEmoji: "딱 맞는 이모지 찾기",
    buscarReacao: "딱 맞는 반응 찾기",
    adicionarEmoji: "이모지 추가",
    limparBusca: "검색 지우기",
  },
  busca: {
    fechar: "검색 닫기",
    procurando: "찾는 중…",
    resultado: "{{quantos}}개 결과",
    resultados: "{{quantos}}개 결과",
    nadaCom: "{{termo}}에 해당하는 게 없습니다.",
    soOsQuePodeLer: "검색은 당신이 읽을 수 있는 채널만 봅니다.",
  },
  entrada: {
    titulo: "받은 편지함",
    naoLidas: "읽지 않음",
    salvas: "저장됨",
    mencoes: "멘션",
    fimTitulo: "끝까지 왔습니다",
    fimDetalhe: "더 읽을 것이 없습니다. 새 메시지가 오면 여기에 나타납니다.",
    semSalvosTitulo: "저장한 항목 없음",
    semSalvosDetalhe: "Shift를 누른 채 메시지의 책갈피를 누르면 보관해 두었다가 나중에 읽을 수 있습니다.",
    tirarDosSalvos: "저장에서 빼기",
    semMencoesTitulo: "아직 멘션 없음",
    semMencoesDetalhe: "당신을 향한 멘션이 최근 7일치로 여기에 나타납니다.",
  },
  forum: {
    descricao: "주제마다 별도의 대화가 됩니다 — 잡담 중간에 묻히면 안 되는 질문에 좋습니다.",
    novoAssunto: "새 주제",
    vazio: "아직 주제가 없습니다. 첫 번째를 시작하면 대화가 처음부터 정리된 채로 남습니다.",
    titulo: "제목",
    doQueSeTrata: "무엇에 대한 건가요?",
    primeiraMensagem: "첫 메시지",
    conteDoCaso: "자세히 적어 주세요",
  },
};
