export const perfil = {
  carregando: "불러오는 중…",
  editar: "프로필 수정",
  mensagem: "메시지",
  abrirConversa: "대화 열기",
  verCompleto: "전체 프로필 보기",
  convidarParaServidor: "서버에 초대",
  semServidores: "서버가 없습니다",
  conviteEnviado: "{{nome}} 님에게 초대를 보냈습니다.",
  moderador: "관리자 보기로 열기",
  mais: "더 보기",
  ignorar: "차단",
  deixarDeIgnorar: "차단 해제",
  copiarId: "사용자 ID 복사",
  idCopiado: "ID를 복사했습니다.",
  conexoes: "연결",
  membroDesde: "가입일",
  sobre: "소개",
  cargosTitulo: "역할",
  visaoGeral: "개요",
  amigosEmComum: "함께 아는 친구 ({{quantidade}})",
  servidoresEmComum: "함께 있는 서버 ({{quantidade}})",
  amizade: {
    amigo: "친구",
    pedidoEnviado: "친구 요청 보냄",
    respondaAbaixo: "요청을 보냈어요 — 아래에서 답해 주세요",
    adicionar: "친구 추가",
    teMandouPedido: "친구 요청을 보냈습니다",
    aceitar: "수락",
    desfazer: "친구 삭제",
    desfazerTitulo: "{{nome}} 님을 친구에서 삭제할까요?",
    desfazerDescricao: "더 이상 친구가 아니게 됩니다. 개인 대화는 기록에 남고, 나중에 다시 추가할 수 있습니다.",
    bloquear: "차단",
    bloquearTitulo: "{{nome}} 님을 차단할까요?",
    bloquearDescricao: "더 이상 친구가 아니게 되고, 개인 대화는 메시지를 받지 않으며, 상대는 친구 요청을 보낼 수 없게 됩니다.",
    linkCopiado: "친구가 아닙니다 — 링크를 복사했으니 직접 보내세요.",
  },
  recado: {
    escrever: "@{{usuario}} 님에게 메시지",
    enviar: "보내기",
    enviada: "메시지를 보냈습니다",
    falhou: "보내지 못했습니다. 대화에서 다시 시도해 주세요.",
  },
  cartao: {
    trocarFaixa: "카드 배너 바꾸기",
    trocarFaixaCurto: "배너 바꾸기",
    trocarFoto: "프로필 사진 바꾸기",
    trocarFotoCurto: "사진 바꾸기",
    suaEtiqueta: "내 태그",
    editarEtiqueta: "클릭해서 태그를 수정하세요",
    conteAlgo: "자신에 대해 알려 주세요",
    adicionarStatus: "상태 추가",
    adicionarDescricao: "클릭해서 설명을 추가하세요",
    cargo: "역할",
    cargos: "역할",
    cargosCom: "역할 — {{quantidade}}",
    tirarCargo: "{{cargo}} 역할 빼기",
  },
  cargos: {
    adicionar: "역할 추가",
    procurar: "역할 검색",
  },
  etiqueta: {
    escolher: "서버 태그 선택",
    nenhuma: "서버 태그 없음",
    semEtiqueta: "태그가 있는 서버가 없습니다",
  },
  emblemas: {
    doServidor: "이 서버의 배지",
    limite: "배지는 {{quantidade}}개까지 달 수 있습니다.",
  },
  nota: {
    vazia: "클릭해서 메모를 남기세요",
    rotulo: "메모 (나만 볼 수 있음)",
    adicionar: "메모 추가 (나만 볼 수 있음)",
  },
  status: {
    titulo: "상태",
    definir: "상태 설정",
    escolherEmoji: "이모지 선택",
    tirarEmoji: "이모지 빼기",
    oQuePensa: "무슨 생각을 하고 있나요?",
    limparAgora: "지금 상태 지우기",
    naoLimpar: "지우지 않음",
    limpar30m: "30분 뒤 지우기",
    limpar1h: "1시간 뒤 지우기",
    limpar4h: "4시간 뒤 지우기",
    limparHoje: "오늘 지우기",
    limparAmanha: "내일 지우기",
    comHora: "{{prazo}} {{hora}}",
  },
  presenca: {
    disponivel: "온라인",
    ausente: "자리 비움",
    naoPerturbar: "방해 금지",
    naoPerturbarDetalhe: "새 메시지 알림을 받지 않습니다",
    invisivel: "오프라인 표시",
    invisivelDetalhe: "다른 사람에게 오프라인으로 보입니다",
  },
  menu: {
    mudarDeConta: "계정 전환",
    gerenciarContas: "계정 관리",
  },
  editor: {
    decoracao: "아바타 장식 바꾸기",
    naoSalvo: "변경 사항 저장을 잊지 마세요!",
    principal: "기본 프로필",
  },
};
