export const servidor = {
  comunidade: {
    ativa: "커뮤니티가 열려 있습니다",
    ativaDesde: "{{quando}}부터 공개",
    membrosAgora: "{{quantos}}명",
    criarParaMim: "대신 만들어 주세요",
    canalDeRegras: "규칙 채널",
    canalDeRegrasDetalhe: "말하기 전에 모두가 읽는 규칙이 놓이는 곳입니다.",
    canalDeAvisos: "커뮤니티 소식 채널",
    canalDeAvisosDetalhe: "여기서 바뀐 것을 보내는 곳이고, 운영하는 사람만 봅니다.",
    canalDeSeguranca: "보안 알림 채널",
    canalDeSegurancaDetalhe: "필터가 걸러낸 것을 관리진이 받아 보는 곳입니다.",
    idiomaPrincipal: "주 언어",
    idiomaPrincipalDetalhe: "대화 대부분이 오가는 언어입니다.",
    semIdioma: "고른 언어 없음",
    semCanal: "채널 없음",
    finalTitulo: "거의 다 됐어요",
    finalDetalhe: "열기 전에, 들어오는 사람에게 무엇이 달라지는지 보세요.",
    confereRegras: "들어온 사람은 규칙 채널을 가장 먼저 봅니다.",
    confereEveryone: "@everyone과 @here는 역할이 있는 사람만 씁니다.",
    confereMencoes: "모두를 한 번에 부르려면 이제 권한이 필요합니다.",
    concordo: "동의하고 이해합니다",
    concordoDetalhe: "이 커뮤니티가 우리 지침을 지킨다는 것을 확인합니다.",
    proximo: "다음",
    terminar: "설정 마치기",
    visaoGeral: "한눈에 보기",
    visaoGeralDetalhe: "커뮤니티가 새로 온 사람에게 말을 거는 채널입니다.",
    seguranca: "보안",
    segurancaDetalhe: "스팸과 무거운 내용을 막아 두는 제동입니다.",
    habilitada: "커뮤니티를 켰습니다.",
    falhou: "커뮤니티를 켜지 못했습니다.",
    titulo: "커뮤니티",
    ilustracao: "말풍선",
    convite: "커뮤니티를 만들고 계신가요?",
    conviteDetalhe: "커뮤니티로 바꾸면 큰 공간을 돌보는 도구가 생깁니다. 규칙 채널, 저희가 보내는 소식, 그리고 알아서 걸러 주는 필터입니다.",
    contagem: "{{minimo}}명 중 {{membros}}명",
    faltam: "열려면 {{quantos}}명 더 필요합니다.",
    prontoParaAbrir: "이제 열 수 있습니다.",
    habilitar: "커뮤니티 켜기",
    vantagemCrescer: "키우기",
    vantagemCrescerDetalhe: "커뮤니티는 탐색에 신청할 수 있고, 그 주제를 찾는 사람이 여러분을 찾습니다.",
    vantagemModerar: "관리하기",
    vantagemModerarDetalhe: "이메일 인증 요구, 미디어 걸러내기, AutoMod 켜기를 한 번에.",
    vantagemAvisos: "소식 받기",
    vantagemAvisosDetalhe: "바뀌는 것을 운영하는 분들께, 여러분만의 채널로 보냅니다.",
    assistenteTitulo: "커뮤니티를 준비해 봅시다.",
    passoSeguranca: "안전 점검",
    passoBasico: "기본 준비",
    passoFinal: "마무리",
    seguraTitulo: "커뮤니티를 안전하게",
    seguraDetalhe: "큰 커뮤니티는 스팸을 부릅니다. 이 두 제동은 처음부터 켜져 있고, 거슬리면 나중에 끄면 됩니다.",
    emailVerificado: "인증된 이메일 요구",
    emailVerificadoDetalhe: "이메일을 아직 확인하지 않은 사람은 글을 못 씁니다. 역할이 있는 사람은 그대로 통과합니다.",
    filtroDeMidia: "노골적인 미디어 걸러내기",
    filtroDeMidiaDetalhe: "사진과 영상은 가려진 채로 도착하고, 보겠다고 누른 사람에게만 보입니다.",
    basicoTitulo: "기본부터 갖추기",
    basicoDetalhe: "규칙이 있는 채널과 소식이 갈 곳을 정해 주세요. 고르지 않으면 둘 다 제가 만듭니다.",
  },
  descoberta: {
    quantosComandos: "명령 {{quantos}}개",
    previa: "카드가 보이는 모습",
    trocarIcone: "아이콘 바꾸기",
    tirarCapa: "표지 없애기",
    heroComunidades: "누군가 지금 당신이 좋아하는 걸 이야기하고 있어요",
    heroComunidadesDetalhe: "여기 사람들이 직접 연 커뮤니티입니다. 들어가서 오가는 이야기를 읽고, 마음에 들면 머무세요.",
    emDestaque: "눈에 띄는 곳",
    todasAsComunidades: "나머지",
    heroTitulo: "오늘 여러분 무리는 뭘 써 볼까요?",
    heroDetalhe: "음악, 게임, 관리용 봇을 여기 있는 사람들이 직접 만들었습니다. 하나 고르면 바로 서버로 들어옵니다.",
    novidades: "막 들어왔어요",
    todosOsApps: "나머지",
    lojaTitulo: "앱 페이지",
    lojaDetalhe: "아직 모르는 사람이 탐색에서 보는 화면입니다.",
    capa: "표지 이미지",
    capaDetalhe: "페이지 맨 위의 넓은 이미지입니다. 1280 × 720이 잘 맞습니다.",
    trocarCapa: "표지 바꾸기",
    categorias: "분류",
    categoriasDetalhe: "최대 {{quantas}}개. 탐색에서는 이걸 따라 둘러봅니다.",
    idiomas: "언어",
    idiomasDetalhe: "최대 {{quantos}}개. 앱이 응답하는 언어입니다.",
    termos: "이용 약관",
    politica: "개인정보 처리방침",
    politicas: "약관",
    servidorDeSuporte: "지원 서버",
    servidorDeSuporteDetalhe: "앱 때문에 도움이 필요한 사람이 찾아가는 곳입니다.",
    semServidor: "없음",
    emQuantosServidores: "들어가 있는 서버 수",
    categoria: {
      GAMES: "게임",
      MUSICA: "음악",
      MODERACAO: "관리",
      PRODUTIVIDADE: "생산성",
      SOCIAL: "소셜",
      UTILIDADES: "도구",
      ARTE_E_CRIACAO: "예술과 창작",
      EDUCACAO: "배움",
      OUTRA: "기타",
    },
    appIndisponivel: "앱을 열 수 없습니다",
    voltarParaExplorar: "탐색으로 돌아가기",
    adicionarApp: "앱 추가",
    copiarLink: "링크 복사",
    denunciarApp: "앱 신고",
    copiarIdDoApp: "앱 ID 복사",
    visaoGeral: "개요",
    comandos: "명령어",
    permissoes: "권한",
    semPermissoes: "이 앱은 아무 권한도 요구하지 않습니다.",
    avisoDePermissoes: "자기 역할을 가지고 들어옵니다. 권한은 나중에 커뮤니티 설정 → 역할에서 바꿀 수 있습니다.",
    servidoresEmComum: "함께 있는 커뮤니티",
    umServidorEmComum: "커뮤니티 1개",
    quantosServidoresEmComum: "커뮤니티 {{quantos}}개",
    feitoPor: "만든이",
    publicadoEm: "공개일",
    denunciarNome: "{{nome}} 신고",
    denunciaDetalhe: "신고는 Gravaê 팀에 전달됩니다. 앱을 만든 사람에게 신고자가 누구인지 알려지지 않습니다.",
    denunciaFalhou: "신고를 보내지 못했습니다.",
    umMembro: "멤버 1명",
    semDescricao: "설명이 없습니다.",
    adicionar: "추가",
    jaEstaAqui: "이미 들어와 있습니다",
    entrando: "참여하는 중…",
    entrar: "참여",
    comunidadePublica: "공개 커뮤니티",
    online: "온라인 {{quantos}}",
    membros: "멤버 {{quantos}}",
    abrirComunidade: "커뮤니티 열기",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "서버 설정",
  novasMensagens: "새 메시지",
  menu: {
    silenciar: "커뮤니티 음소거",
    reativar: "커뮤니티 음소거 해제",
    porQuinze: "15분 동안",
    porMeiaHora: "30분 동안",
    porTresHoras: "3시간 동안",
    porTresDias: "3일 동안",
    porUmaHora: "1시간 동안",
    porOitoHoras: "8시간 동안",
    porUmDia: "24시간 동안",
    ateReativar: "다시 켤 때까지",
    notificacoes: "알림 설정",
    padrao: "기본값 사용",
    todas: "모든 메시지",
    soMencoes: "멘션만",
    nada: "없음",
    ocultarSilenciados: "음소거된 채널 숨기기",
    denunciar: "커뮤니티 신고",
    marcarLida: "읽음으로 표시",
    convidar: "멤버 초대",
    editarPerfil: "커뮤니티 프로필 편집",
    configuracoes: "커뮤니티 설정",
    sair: "커뮤니티 나가기",
    sairTitulo: "{{nome}}에서 나갈까요?",
    sairDescricao: "돌아오려면 새 초대가 필요해요.",
    copiarId: "커뮤니티 ID 복사",
    idCopiado: "ID를 복사했어요.",
  },
  convite: {
    cartaoTitulo: "커뮤니티 초대를 받았습니다",
    indisponivel: "초대를 쓸 수 없습니다",
    indisponivelDetalhe: "기한이 지났거나, 다 소진됐거나, 만든 사람이 지웠습니다.",
    entrar: "커뮤니티 참여",
    chamado: "초대받았어요:",
    aceitarComo: "{{nome}}(으)로 수락",
    abrir: "커뮤니티 열기",
    recusar: "아니요, 괜찮아요",
  },
  pasta: {
    silenciarTodas: "커뮤니티 음소거",
    reativarTodas: "커뮤니티 음소거 해제",
    mostrarSilenciados: "음소거된 채널 표시",
    notificacoesDaComunidade: "알림 설정",
    silenciarEveryone: "@everyone과 @here 음소거",
    permitirEveryone: "@everyone과 @here 허용",
    silenciarCargos: "역할 멘션 음소거",
    permitirCargos: "역할 멘션 허용",
    dicaDaCor: "색을 입력(hex, rgb(), hsl(), 이름)하거나 선택하세요.",
    mostrarIcone: "닫혔을 때 아이콘 표시",
    dicaDoIcone: "닫히면 안의 서버 대신 아이콘을 보여줘요.",
    icone: "폴더 아이콘",
    excluir: "폴더 삭제",
    icones: {
      pasta: "폴더",
      estrela: "즐겨찾기",
      coracao: "하트",
      salvar: "저장",
      jogo: "게임 패드",
      escudo: "방패",
      nota: "음표",
    },
    marcarLida: "폴더를 읽음으로 표시",
    configuracoes: "폴더 설정",
    desfazer: "폴더 해제",
    titulo: "폴더",
    nome: "이름",
    semNome: "이름 없음",
    cor: "색상",
    semCor: "색상 없음",
    salvar: "저장",
  },
  denuncia: {
    titulo: "{{nome}} 신고",
    descricao: "신고는 Gravaê 팀에 전달됩니다. 무슨 일이 있었는지 알려주세요.",
    motivo: "사유",
    detalhes: "세부 내용 (선택)",
    enviar: "신고 보내기",
    enviada: "신고를 보냈어요. 감사합니다.",
    motivos: {
      spam: "스팸 또는 광고",
      assedio: "괴롭힘 또는 혐오",
      conteudo: "부적절한 콘텐츠",
      golpe: "사기",
      outro: "기타",
    },
  },
  selos: {
    verificada: "인증된 커뮤니티",
    detectavel: "검색 가능한 커뮤니티",
  },
  auditoria: {
    todasAsAcoes: "모든 작업",
    todosOsUsuarios: "모든 사용자",
    filtroMembros: "멤버",
    filtroCanais: "채널",
    filtroEmojis: "이모지",
    filtroServidor: "서버",
    titulo: "감사 기록",
    porUsuario: "사람으로 거르기",
    porAcao: "동작으로 거르기",
    vazio: "이 필터로는 아직 기록된 것이 없습니다.",
    motivo: "사유:",
  },
  banimentos: {
    titulo: "서버 차단 목록",
    descricao: "여기 있는 사람은 새 초대로도 다시 들어오지 못합니다. 차단을 풀면 바로 접근이 돌아옵니다.",
    procurar: "사용자 이름으로 차단 검색",
    vazioTitulo: "차단 없음",
    vazio: "아직 아무도 차단하지 않았습니다… 하지만 필요할 때가 오면 망설이지 마세요.",
    desbanir: "차단 해제",
  },
  excluir: {
    tudoVai: "{{servidor}}의 모든 채널과 메시지, 초대가 {{membros}}명의 멤버에게서 삭제됩니다. 이후에는 아무도 되돌릴 수 없습니다.",
    digite: "확인하려면 {{servidor}}을(를) 입력하세요",
    titulo: "서버 삭제",
    aviso: "되돌릴 수 없습니다.",
  },
  emblemas: {
    apagarDescricao: "달고 있는 모두에게서 사라집니다. 되돌릴 수 없습니다.",
    titulo: "배지",
    vazio: "아직 배지가 없습니다.",
    novo: "새 배지",
  },
  convites: {
    revogarTitulo: "초대를 취소할까요?",
    revogarAcao: "취소",
    revogarDescricao: "링크 {{codigo}}은(는) 바로 작동을 멈춥니다. 이미 그 링크로 들어온 사람은 서버에 남습니다.",
    titulo: "초대",
    descricao: "이 서버의 유효한 초대 링크 전부.",
    vazio: "아직 만든 초대가 없습니다.",
    revogar: "초대 취소",
  },
  integracoes: {
    opcionais: "username과 avatar_url은 선택이며 메시지마다 적용됩니다. 한도는 5초에 5개입니다.",
    apagarDescricao: "URL이 바로 작동을 멈춥니다. 이미 보낸 메시지는 채널에 남습니다.",
    titulo: "연동",
    descricao: "웹훅은 계정 없이도 채널에 글을 올리는 주소입니다. 빌드가 통과했을 때, 누군가 문의를 열었을 때, 또는 스크립트에서 보내고 싶은 무엇이든 알리는 데 씁니다.",
    novo: "새 웹훅",
    vazio: "아직 웹훅이 없습니다. 하나 만들고 메시지가 오길 원하는 곳에 URL을 붙여넣으세요.",
    canal: "채널",
    apagar: "웹훅 삭제",
    comoUsar: "사용법",
    comoUsarTexto: "JSON으로 POST를 보내세요:",
  },
  explorar: {
    titulo: "탐색",
  },
  engajamento: {
    semCanal: "시스템 채널 없음",
    titulo: "활기",
    descricao: "새로운 사람이 왔을 때 비어 보이지 않도록 서버가 알아서 하는 일.",
    sistema: "시스템 메시지",
    boasVindas: "누군가 들어오면 환영 메시지 보내기",
    sorteio: "아래에 직접 쓴 문구가 없으면 문장이 무작위로 뽑힙니다 — 늘 같은 문장은 금세 질립니다.",
    canalDoSistema: "시스템 메시지 채널",
    mensagem: "환영 메시지",
    deixeVazio: "준비된 문장 중에서 뽑으려면 비워 두세요",
  },
  automod: {
    titulo: "자동 관리",
    descricao: "메시지가 생기기도 전에 알아서 관리하는 필터입니다. 서버를 관리하는 사람은 절대 걸리지 않고, 면제된 역할도 그대로 통과합니다.",
    palavras: {
      titulo: "직접 정한 단어 차단",
      descricao: "아무도 쓸 수 없는 단어 목록.",
    },
    mencoes: {
      titulo: "멘션 도배 차단",
      descricao: "한 번에 멘션이 너무 많은 메시지를 차단합니다.",
    },
    links: {
      titulo: "링크 차단",
      descricao: "채팅에 붙여넣은 주소를 모두 막습니다.",
    },
    definir: "설정",
    nomeDaRegra: "규칙 이름",
    bloqueadas: "차단할 단어",
    digiteEnter: "입력하고 Enter를 누르세요",
    comparacao: "비교는 대소문자, 발음 기호, 문장부호를 무시합니다 — 그리고 단어 안의 단어는 잡지 않습니다.",
    aPartirDe: "몇 번의 멘션부터 차단할지",
    oQueFazer: "무엇을 할지",
    canalDoAlerta: "알림 채널",
    escolhaCanal: "채널을 고르세요",
    castigo: "타임아웃(분)",
    isentos: "면제 역할",
    semCargos: "아직 만든 역할이 없습니다.",
    salvarRegra: "규칙 저장",
    apagar: "규칙 삭제",
    excluirTitulo: "이 자동 관리 규칙을 삭제할까요?",
    excluirDescricao: "서버가 즉시 이 규칙으로 거르지 않게 됩니다. 다시 만들 수 있지만 지금 설정은 사라집니다.",
    excluirAcao: "규칙 삭제",
  },
  cargos: {
    titulo: "역할",
    descricao: "역할은 이름과 색과 권한을 줍니다. 목록에서 위에 있는 쪽이 아래를 다스리고, 자기와 같거나 위의 역할은 아무도 손대지 못합니다.",
    criar: "역할 만들기",
    vazio: "아직 역할이 없습니다.",
    abaExibicao: "표시",
    abaPermissoes: "권한",
    abaMembros: "멤버 — {{quantos}}",
    everyone: "서버의 모두에게 적용됩니다. 다른 역할이 그 위에 쌓이는 바탕입니다.",
    nomeDoCargo: "역할 이름",
    cor: "역할 색",
    corDica: "역할을 가진 사람의 이름을 멤버 목록과 채팅에서 칠합니다.",
    semCor: "색 없음",
    corPersonalizada: "직접 고른 색",
    estilo: "이름 스타일",
    segundaCor: "두 번째 색",
    segundaCorDica: "없으면 그러데이션이 단색으로 돌아갑니다 — 사라지지는 않습니다.",
    limparSegundaCor: "두 번째 색 지우기",
    icone: "아이콘",
    iconeDica: "역할을 가진 사람의 프로필 카드에서 역할 옆에 나옵니다.",
    exibirSeparado: "다른 멤버와 따로 표시",
    exibirSeparadoDica: "역할이 멤버 목록에서 자기 구역을 갖습니다.",
    permitirMencionar: "이 역할을 멘션할 수 있게 허용",
    permitirMencionarDica: "누구나 그 역할을 가진 모두에게 알림을 보낼 수 있게 됩니다.",
    semPoderDeConceder: "{{descricao}} (당신에게는 이 권한을 줄 권한이 없습니다)",
    adicionar: "이 역할에 누군가 추가",
    tirar: "역할 빼기",
    semNinguem: "아직 이 역할을 가진 사람이 없습니다.",
    apagar: "역할 삭제",
    excluirTitulo: "역할 \"{{nome}}\"을(를) 삭제할까요?",
    excluirDescricao: "이 역할을 가진 사람은 그것이 주던 것을 모두 잃습니다. 되돌릴 수 없습니다.",
    excluirAcao: "역할 삭제",
  },
  membros: {
    procurar: "이름이나 사용자 이름으로 검색",
    membroDesde: "가입일",
    vazio: "아무도 찾지 못했습니다.",
    acoesPara: "{{nome}}에 대한 작업",
    deCastigo: "타임아웃",
    tirarCastigo: "타임아웃 해제",
    castigo5min: "5분",
    castigo1h: "1시간",
    castigo1d: "1일",
    castigo1s: "1주",
    expulsar: "내보내기",
    expulsarTitulo: "{{nome}}을(를) 내보낼까요?",
    expulsarDescricao: "은(는) 바로 {{servidor}}에서 나갑니다. 초대가 있으면 돌아올 수 있습니다 — 내보내기는 복귀를 막지 않습니다.",
    banir: "차단",
    banirTitulo: "{{nome}}을(를) 차단할까요?",
    banirDescricao: "은(는) {{servidor}}에서 나가고, 차단이 풀릴 때까지 초대가 있어도 돌아올 수 없습니다.",
    motivo: "사유(선택)",
    motivoDica: "감사 기록에 남습니다",
  },
  perfil: {
    titulo: "서버 프로필",
    descricao: "목록과 초대 링크에서 당신의 서버는 이렇게 보입니다.",
    icone: "아이콘",
    faixa: "상단 배너",
    nomeDoServidor: "서버 이름",
    campoDescricao: "설명",
    doQueE: "이 서버는 무엇에 관한 곳인가요?",
    comprimido: "업로드 전 압축: {{economia}}",
  },
  etiqueta: {
    titulo: "서버 태그",
    descricao: "모든 멤버의 이름 옆에 나오는 최대 4글자 꼬리표입니다 — 채팅에서도, 사람 목록에서도. 여기서는 무료입니다: 부스트도 레벨도 없이.",
    escolhaNome: "이름을 고르세요",
    limite: "최대 4자, 문자와 숫자.",
    escolhaInsignia: "배지를 고르세요",
    voce: "당신",
    fala1: "게임할 사람?",
    fala2: "내 태그 좀 봐!",
    fala3: "오, 그거 어디서 났어",
  },
  expressoes: {
    comoUsar: "이 서버에서 누구나 쓸 수 있는 이모지를 최대 {{limite}}개까지 추가하세요. 보내려면 채팅에 :이름: 이라고 입력하세요.",
    imagem: "이미지",
    enviadoPor: "올린 사람",
    semEmoji: "아직 이모지가 없습니다.",
    figurinhas: "스티커",
    enviarFigurinha: "스티커 올리기",
    nomeDaFigurinha: "스티커 이름",
    exemploFigurinha: "예: 아기 고양이 포옹",
    figurinhaGrande: "스티커가 {{limite}}을(를) 넘습니다.",
    deixaPraLa: "됐어요",
    sons: "사운드보드",
    enviarSom: "사운드 올리기",
    nomeDoSom: "사운드 이름",
    semSom: "아직 사운드가 없습니다.",
    somGrande: "사운드가 {{limite}}을(를) 넘습니다.",
    emojiRelacionado: "관련 이모지",
    ouvir: "듣기",
    ouvirAssim: "이렇게 듣기",
    volumeDe: "{{nome}}의 음량",
    volumeDica: "서버의 모두에게 적용됩니다. 그래도 각자 통화 패널에서 자기에게만 소리를 줄일 수 있습니다.",
    falhaEnvio: "파일을 올리지 못했습니다.",
    excluirTitulo: "{{tipo}} \"{{nome}}\"을(를) 삭제할까요?",
    excluirDescricao: "모두의 서버에서 사라집니다. 이미 사용한 메시지는 그대로 남습니다.",
  },
  canal: {
    tipoLink: "링크",
    tipoLinkDica: "바깥 주소를 가리키고 브라우저에서 열립니다",
    endereco: "주소",
    enderecoDica: "이 채널이 데려가는 곳입니다. https:// 로 시작해야 합니다",
    visaoGeral: "개요",
    nome: "채널 이름",
    topico: "채널 주제",
    topicoDica: "여기서는 무슨 이야기를 하나요?",
    modoLento: "한 사람이 간격당 메시지 하나만 보냅니다. 메시지나 채널을 관리하는 사람은 그대로 통과합니다.",
    visibilidade: "콘텐츠 표시",
    padrao: "기본",
    padraoDica: "채널의 내용은 항상 보입니다.",
    spoiler: "스포일러 채널",
    spoilerDica: "이 채널을 스포일러가 있는 채널로 표시하면, 반전과 무거운 주제가 누군가 보기로 할 때까지 가려집니다.",
    idade: "연령 제한 채널",
    idadeDica: "들어오는 사람은 내용을 보려면 성인임을 확인해야 합니다.",
    bitrateDica: "64 kbps를 넘기면 인터넷이 나쁜 사람에게 방해가 될 수 있습니다.",
    qualidadeDeVideo: "영상 품질",
    automatica: "자동",
    limite: "인원 제한 — {{valor}}",
    pessoas: "{{quantos}}명",
    semLimite: "제한 없음",
    permissoesDescricao: "여기서 이 채널에 적용되는 것을 바꿉니다. “상속”에 남은 것은 계속 역할을 따릅니다.",
    excluir: {
      titulo: "채널 삭제",
      historico: "{{canal}}의 기록 전부가 함께 사라집니다. 모두에게서.",
      digite: "확인하려면 {{canal}}을(를) 입력하세요",
    },
  },
  moderacao: {
    titulo: "모더레이터 보기",
    semPermissao: "이걸 보려면 “멤버 관리” 권한이 필요합니다.",
    fecharEsc: "닫기(Esc)",
    atividade: "서버에서의 활동",
    mensagens: "메시지",
    links: "링크",
    midia: "미디어",
    acoesNaAuditoria: "감사 기록의 작업",
    moderacoesSofridas: "받은 조치",
    permissoes: "권한 ({{quantas}})",
    semPermissaoEspecial: "특별한 권한 없음.",
    conta: "계정",
    entrouNoServidor: "서버 가입",
    contaCriadaEm: "계정 생성일",
    deCastigoAte: "타임아웃 종료",
    formaDeAdesao: "어떻게 들어왔는지",
    mensagem: "메시지",
    castigo: "타임아웃",
    copiarId: "ID 복사",
    idCopiado: "ID를 복사했습니다.",
    adicionarCargo: "역할 추가",
    semCargos: "만든 역할 없음",
    soEveryone: "@everyone뿐입니다.",
    voltar: "뒤로",
    vazio: "여기엔 아무것도 없습니다.",
    cinquenta: "최신 50개를 보여 줍니다.",
    irParaMensagem: "메시지로 이동",
    precisaSerAmigo: "대화하려면 서로 친구여야 합니다.",
    expulsarDescricao: "서버에서 바로 나가지만, 초대가 있으면 돌아올 수 있습니다.",
    banirDescricao: "서버에서 나가고, 차단이 풀릴 때까지 초대가 있어도 돌아올 수 없습니다.",
    castigarTitulo: "{{nome}}에게 타임아웃을 줄까요?",
    castigoDescricao: "지속되는 동안에는 서버의 어느 채널에서도 쓰거나 말할 수 없습니다.",
    aplicarCastigo: "타임아웃 적용",
    duracao: "분 단위 시간",
    informeDuracao: "분 단위로 시간을 입력하세요.",
  },
  abas: {
    pesquisar: "설정에서 찾기",
    semResultado: "그런 이름은 여기 없습니다.",
    comunidade: "커뮤니티",
    expressoes: "표현",
    pessoas: "사람",
    apps: "앱",
    moderacao: "관리",
    banimentos: "차단",
  },
};
