export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "서버 설정",
  auditoria: {
    todasAsAcoes: "모든 작업",
    todosOsUsuarios: "모든 사용자",
    filtroMembros: "멤버",
    filtroCanais: "채널",
    filtroEmojis: "이모지",
    filtroServidor: "서버",
    titulo: "감사 기록",
    porUsuario: "사람으로 거르기",
    porAcao: "동작으로 거르기",
    vazio: "이 필터로는 아직 기록된 것이 없습니다.",
    motivo: "사유:",
  },
  banimentos: {
    titulo: "서버 차단 목록",
    descricao: "여기 있는 사람은 새 초대로도 다시 들어오지 못합니다. 차단을 풀면 바로 접근이 돌아옵니다.",
    procurar: "사용자 이름으로 차단 검색",
    vazioTitulo: "차단 없음",
    vazio: "아직 아무도 차단하지 않았습니다… 하지만 필요할 때가 오면 망설이지 마세요.",
    desbanir: "차단 해제",
  },
  excluir: {
    tudoVai: "{{servidor}}의 모든 채널과 메시지, 초대가 {{membros}}명의 멤버에게서 삭제됩니다. 이후에는 아무도 되돌릴 수 없습니다.",
    digite: "확인하려면 {{servidor}}을(를) 입력하세요",
    titulo: "서버 삭제",
    aviso: "되돌릴 수 없습니다.",
  },
  emblemas: {
    apagarDescricao: "달고 있는 모두에게서 사라집니다. 되돌릴 수 없습니다.",
    titulo: "배지",
    vazio: "아직 배지가 없습니다.",
    novo: "새 배지",
  },
  convites: {
    revogarTitulo: "초대를 취소할까요?",
    revogarAcao: "취소",
    revogarDescricao: "링크 {{codigo}}은(는) 바로 작동을 멈춥니다. 이미 그 링크로 들어온 사람은 서버에 남습니다.",
    titulo: "초대",
    descricao: "이 서버의 유효한 초대 링크 전부.",
    vazio: "아직 만든 초대가 없습니다.",
    revogar: "초대 취소",
  },
  integracoes: {
    opcionais: "username과 avatar_url은 선택이며 메시지마다 적용됩니다. 한도는 5초에 5개입니다.",
    apagarDescricao: "URL이 바로 작동을 멈춥니다. 이미 보낸 메시지는 채널에 남습니다.",
    titulo: "연동",
    descricao: "웹훅은 계정 없이도 채널에 글을 올리는 주소입니다. 빌드가 통과했을 때, 누군가 문의를 열었을 때, 또는 스크립트에서 보내고 싶은 무엇이든 알리는 데 씁니다.",
    novo: "새 웹훅",
    vazio: "아직 웹훅이 없습니다. 하나 만들고 메시지가 오길 원하는 곳에 URL을 붙여넣으세요.",
    canal: "채널",
    apagar: "웹훅 삭제",
    comoUsar: "사용법",
    comoUsarTexto: "JSON으로 POST를 보내세요:",
  },
  engajamento: {
    semCanal: "시스템 채널 없음",
    titulo: "활기",
    descricao: "새로운 사람이 왔을 때 비어 보이지 않도록 서버가 알아서 하는 일.",
    sistema: "시스템 메시지",
    boasVindas: "누군가 들어오면 환영 메시지 보내기",
    sorteio: "아래에 직접 쓴 문구가 없으면 문장이 무작위로 뽑힙니다 — 늘 같은 문장은 금세 질립니다.",
    canalDoSistema: "시스템 메시지 채널",
    mensagem: "환영 메시지",
    deixeVazio: "준비된 문장 중에서 뽑으려면 비워 두세요",
  },
  automod: {
    titulo: "자동 관리",
    descricao: "메시지가 생기기도 전에 알아서 관리하는 필터입니다. 서버를 관리하는 사람은 절대 걸리지 않고, 면제된 역할도 그대로 통과합니다.",
    palavras: {
      titulo: "직접 정한 단어 차단",
      descricao: "아무도 쓸 수 없는 단어 목록.",
    },
    mencoes: {
      titulo: "멘션 도배 차단",
      descricao: "한 번에 멘션이 너무 많은 메시지를 차단합니다.",
    },
    links: {
      titulo: "링크 차단",
      descricao: "채팅에 붙여넣은 주소를 모두 막습니다.",
    },
    definir: "설정",
    nomeDaRegra: "규칙 이름",
    bloqueadas: "차단할 단어",
    digiteEnter: "입력하고 Enter를 누르세요",
    comparacao: "비교는 대소문자, 발음 기호, 문장부호를 무시합니다 — 그리고 단어 안의 단어는 잡지 않습니다.",
    aPartirDe: "몇 번의 멘션부터 차단할지",
    oQueFazer: "무엇을 할지",
    canalDoAlerta: "알림 채널",
    escolhaCanal: "채널을 고르세요",
    castigo: "타임아웃(분)",
    isentos: "면제 역할",
    semCargos: "아직 만든 역할이 없습니다.",
    salvarRegra: "규칙 저장",
    apagar: "규칙 삭제",
    excluirTitulo: "이 자동 관리 규칙을 삭제할까요?",
    excluirDescricao: "서버가 즉시 이 규칙으로 거르지 않게 됩니다. 다시 만들 수 있지만 지금 설정은 사라집니다.",
    excluirAcao: "규칙 삭제",
  },
  cargos: {
    titulo: "역할",
    descricao: "역할은 이름과 색과 권한을 줍니다. 목록에서 위에 있는 쪽이 아래를 다스리고, 자기와 같거나 위의 역할은 아무도 손대지 못합니다.",
    criar: "역할 만들기",
    vazio: "아직 역할이 없습니다.",
    abaExibicao: "표시",
    abaPermissoes: "권한",
    abaMembros: "멤버 — {{quantos}}",
    everyone: "서버의 모두에게 적용됩니다. 다른 역할이 그 위에 쌓이는 바탕입니다.",
    nomeDoCargo: "역할 이름",
    cor: "역할 색",
    corDica: "역할을 가진 사람의 이름을 멤버 목록과 채팅에서 칠합니다.",
    semCor: "색 없음",
    corPersonalizada: "직접 고른 색",
    estilo: "이름 스타일",
    segundaCor: "두 번째 색",
    segundaCorDica: "없으면 그러데이션이 단색으로 돌아갑니다 — 사라지지는 않습니다.",
    limparSegundaCor: "두 번째 색 지우기",
    icone: "아이콘",
    iconeDica: "역할을 가진 사람의 프로필 카드에서 역할 옆에 나옵니다.",
    exibirSeparado: "다른 멤버와 따로 표시",
    exibirSeparadoDica: "역할이 멤버 목록에서 자기 구역을 갖습니다.",
    permitirMencionar: "이 역할을 멘션할 수 있게 허용",
    permitirMencionarDica: "누구나 그 역할을 가진 모두에게 알림을 보낼 수 있게 됩니다.",
    semPoderDeConceder: "{{descricao}} (당신에게는 이 권한을 줄 권한이 없습니다)",
    adicionar: "이 역할에 누군가 추가",
    tirar: "역할 빼기",
    semNinguem: "아직 이 역할을 가진 사람이 없습니다.",
    apagar: "역할 삭제",
    excluirTitulo: "역할 \"{{nome}}\"을(를) 삭제할까요?",
    excluirDescricao: "이 역할을 가진 사람은 그것이 주던 것을 모두 잃습니다. 되돌릴 수 없습니다.",
    excluirAcao: "역할 삭제",
  },
  membros: {
    procurar: "이름이나 사용자 이름으로 검색",
    membroDesde: "가입일",
    vazio: "아무도 찾지 못했습니다.",
    acoesPara: "{{nome}}에 대한 작업",
    deCastigo: "타임아웃",
    tirarCastigo: "타임아웃 해제",
    castigo5min: "5분",
    castigo1h: "1시간",
    castigo1d: "1일",
    castigo1s: "1주",
    expulsar: "내보내기",
    expulsarTitulo: "{{nome}}을(를) 내보낼까요?",
    expulsarDescricao: "은(는) 바로 {{servidor}}에서 나갑니다. 초대가 있으면 돌아올 수 있습니다 — 내보내기는 복귀를 막지 않습니다.",
    banir: "차단",
    banirTitulo: "{{nome}}을(를) 차단할까요?",
    banirDescricao: "은(는) {{servidor}}에서 나가고, 차단이 풀릴 때까지 초대가 있어도 돌아올 수 없습니다.",
    motivo: "사유(선택)",
    motivoDica: "감사 기록에 남습니다",
  },
  perfil: {
    titulo: "서버 프로필",
    descricao: "목록과 초대 링크에서 당신의 서버는 이렇게 보입니다.",
    icone: "아이콘",
    faixa: "상단 배너",
    nomeDoServidor: "서버 이름",
    campoDescricao: "설명",
    doQueE: "이 서버는 무엇에 관한 곳인가요?",
    comprimido: "업로드 전 압축: {{economia}}",
  },
  etiqueta: {
    titulo: "서버 태그",
    descricao: "모든 멤버의 이름 옆에 나오는 최대 4글자 꼬리표입니다 — 채팅에서도, 사람 목록에서도. 여기서는 무료입니다: 부스트도 레벨도 없이.",
    escolhaNome: "이름을 고르세요",
    limite: "최대 4자, 문자와 숫자.",
    escolhaInsignia: "배지를 고르세요",
    voce: "당신",
    fala1: "게임할 사람?",
    fala2: "내 태그 좀 봐!",
    fala3: "오, 그거 어디서 났어",
  },
  expressoes: {
    comoUsar: "이 서버에서 누구나 쓸 수 있는 이모지를 최대 {{limite}}개까지 추가하세요. 보내려면 채팅에 :이름: 이라고 입력하세요.",
    imagem: "이미지",
    enviadoPor: "올린 사람",
    semEmoji: "아직 이모지가 없습니다.",
    figurinhas: "스티커",
    enviarFigurinha: "스티커 올리기",
    nomeDaFigurinha: "스티커 이름",
    exemploFigurinha: "예: 아기 고양이 포옹",
    figurinhaGrande: "스티커가 {{limite}}을(를) 넘습니다.",
    deixaPraLa: "됐어요",
    sons: "사운드보드",
    enviarSom: "사운드 올리기",
    nomeDoSom: "사운드 이름",
    semSom: "아직 사운드가 없습니다.",
    somGrande: "사운드가 {{limite}}을(를) 넘습니다.",
    emojiRelacionado: "관련 이모지",
    ouvir: "듣기",
    ouvirAssim: "이렇게 듣기",
    volumeDe: "{{nome}}의 음량",
    volumeDica: "서버의 모두에게 적용됩니다. 그래도 각자 통화 패널에서 자기에게만 소리를 줄일 수 있습니다.",
    falhaEnvio: "파일을 올리지 못했습니다.",
    excluirTitulo: "{{tipo}} \"{{nome}}\"을(를) 삭제할까요?",
    excluirDescricao: "모두의 서버에서 사라집니다. 이미 사용한 메시지는 그대로 남습니다.",
  },
  canal: {
    visaoGeral: "개요",
    nome: "채널 이름",
    topico: "채널 주제",
    topicoDica: "여기서는 무슨 이야기를 하나요?",
    modoLento: "한 사람이 간격당 메시지 하나만 보냅니다. 메시지나 채널을 관리하는 사람은 그대로 통과합니다.",
    visibilidade: "콘텐츠 표시",
    padrao: "기본",
    padraoDica: "채널의 내용은 항상 보입니다.",
    spoiler: "스포일러 채널",
    spoilerDica: "이 채널을 스포일러가 있는 채널로 표시하면, 반전과 무거운 주제가 누군가 보기로 할 때까지 가려집니다.",
    idade: "연령 제한 채널",
    idadeDica: "들어오는 사람은 내용을 보려면 성인임을 확인해야 합니다.",
    bitrateDica: "64 kbps를 넘기면 인터넷이 나쁜 사람에게 방해가 될 수 있습니다.",
    qualidadeDeVideo: "영상 품질",
    automatica: "자동",
    limite: "인원 제한 — {{valor}}",
    pessoas: "{{quantos}}명",
    semLimite: "제한 없음",
    permissoesDescricao: "여기서 이 채널에 적용되는 것을 바꿉니다. “상속”에 남은 것은 계속 역할을 따릅니다.",
    excluir: {
      titulo: "채널 삭제",
      historico: "{{canal}}의 기록 전부가 함께 사라집니다. 모두에게서.",
      digite: "확인하려면 {{canal}}을(를) 입력하세요",
    },
  },
  moderacao: {
    titulo: "모더레이터 보기",
    semPermissao: "이걸 보려면 “멤버 관리” 권한이 필요합니다.",
    fecharEsc: "닫기(Esc)",
    atividade: "서버에서의 활동",
    mensagens: "메시지",
    links: "링크",
    midia: "미디어",
    acoesNaAuditoria: "감사 기록의 작업",
    moderacoesSofridas: "받은 조치",
    permissoes: "권한 ({{quantas}})",
    semPermissaoEspecial: "특별한 권한 없음.",
    conta: "계정",
    entrouNoServidor: "서버 가입",
    contaCriadaEm: "계정 생성일",
    deCastigoAte: "타임아웃 종료",
    formaDeAdesao: "어떻게 들어왔는지",
    mensagem: "메시지",
    castigo: "타임아웃",
    copiarId: "ID 복사",
    idCopiado: "ID를 복사했습니다.",
    adicionarCargo: "역할 추가",
    semCargos: "만든 역할 없음",
    soEveryone: "@everyone뿐입니다.",
    voltar: "뒤로",
    vazio: "여기엔 아무것도 없습니다.",
    cinquenta: "최신 50개를 보여 줍니다.",
    irParaMensagem: "메시지로 이동",
    precisaSerAmigo: "대화하려면 서로 친구여야 합니다.",
    expulsarDescricao: "서버에서 바로 나가지만, 초대가 있으면 돌아올 수 있습니다.",
    banirDescricao: "서버에서 나가고, 차단이 풀릴 때까지 초대가 있어도 돌아올 수 없습니다.",
    castigarTitulo: "{{nome}}에게 타임아웃을 줄까요?",
    castigoDescricao: "지속되는 동안에는 서버의 어느 채널에서도 쓰거나 말할 수 없습니다.",
    aplicarCastigo: "타임아웃 적용",
    duracao: "분 단위 시간",
    informeDuracao: "분 단위로 시간을 입력하세요.",
  },
  abas: {
    expressoes: "표현",
    pessoas: "사람",
    apps: "앱",
    moderacao: "관리",
    banimentos: "차단",
  },
};
