export const amizades = {
  ativosAgora: "当前活跃",
  procurando: "看看谁在…",
  tudoTranquilo: "暂时很安静…",
  tudoTranquiloDetalhe: "当你或朋友加入通话时，会显示在这里，一键就能加入。",
  emVoz: "语音中",
  voce: "你",
  soVoce: "只有你",
  pessoas: "{{quantas}} 人",
  voltarParaChamada: "回到通话",
  entrarNaChamada: "加入通话",
  abrirCanal: "在 {{servidor}} 打开 {{canal}}",
  mensagensDiretas: "私信",
  encontreConversa: "查找会话",
  amigos: "好友",
  conversas: "会话",
  semConversas: "还没有会话。添加一个好友开始吧。",
  semConversaComEsseNome: "没有这个名字的会话。",
  abrirMenu: "打开服务器和会话",
  solicitacoes: "消息请求",
  pedidos: "请求",
  spam: "垃圾",
  pedidosPendentes: "待处理请求",
  marcadosComoSpam: "已标记为垃圾",
  aceitar: "接受",
  ignorar: "忽略",
  marcarSpam: "标记为垃圾",
  semPedidos: "没有待处理的请求。",
  semPedidosDetalhe: "不是你好友但与你共处一个服务器的人，会先到这里，再进入你的会话。",
  semSpam: "没有标记为垃圾的内容。",
  semSpamDetalhe: "垃圾过滤器挑出来的，或你自己标记的，都留在这个标签里。",
  umServidorEmComum: "1 个共同服务器",
  servidoresEmComum: "{{quantos}} 个共同服务器",
  semServidoresEmComum: "没有共同服务器",
};
