export const chamada = {
  conectando: "正在连接通话…",
  naoEntrou: "没能加入通话",
  sair: "离开通话",
  sairDaVoz: "离开语音通话",
  desconectar: "断开连接",
  voltar: "回到通话",
  voltarAosQuadros: "回到通话画面",
  fecharChat: "关闭聊天",
  carregandoPrevia: "正在加载预览…",
  maisOpcoes: "更多选项",
  deVideo: "视频通话",
  deVoz: "语音通话",
  alguem: "某人",
  volume: {
    entrada: "输入音量",
    saida: "输出音量",
    live: "直播音量",
    liveComPorcento: "直播音量（{{porcento}}%）",
    liveSemSom: "直播已静音",
  },
  aparelhos: {
    entrada: "输入设备",
    saida: "输出设备",
    camera: "摄像头",
    microfone: "麦克风",
    saidaCurto: "输出",
    oDoSistema: "跟随系统",
    aDoSistema: "跟随系统",
    semEscolhaDeSaida: "这个浏览器不让选择输出 — 由系统决定。",
    espelhar: "镜像我的摄像头",
    configEntrada: "输入设置",
    configSaida: "输出设置",
    configCamera: "摄像头设置",
    configAudioEVideo: "音视频设置",
  },
  tela: {
    compartilhar: "共享屏幕",
    compartilharAcao: "共享",
    cancelar: "取消",
    telas: "屏幕",
    janelas: "窗口",
    somDoComputador: "把电脑的声音一起带上",
    somDoSistema: "把系统的声音一起带上",
    configCompartilhamento: "共享设置",
    mostrarSemVideo: "显示没开视频的人",
    semFontes: "系统没有返回任何可共享的屏幕或窗口。",
    pararDeCompartilhar: "停止共享",
    encerrarTransmissao: "结束直播",
  },
  live: {
    etiqueta: "直播中",
    etiquetaMaiuscula: "直播中",
    assistir: "观看直播",
    assistirPessoa: "观看 {{nome}}",
    pararDeAssistir: "停止观看",
  },
  membro: {
    mudarMeuApelido: "修改我的昵称",
    meuMicrofone: "我的麦克风",
    ouvirChamada: "收听通话",
    copiarMeuId: "复制我的 ID",
    idCopiado: "ID 已复制。",
    mensagem: "消息",
    silenciar: "静音",
    alterarApelido: "修改昵称",
    cargos: "身份组",
    semCargo: "还没有创建身份组",
    moverPara: "移动到",
    silenciarNoServidor: "在服务器中静音语音",
    desativarAudioNoServidor: "在服务器中关闭音频",
    desconectar: "断开连接",
    apelidoTitulo: "你在这个服务器的昵称",
    apelidoDeAlguem: "{{nome}} 的昵称",
    apelidoCampo: "昵称",
    apelidoDicaPropria: "只在这里生效。留空就恢复成你平常的名字。",
    apelidoDicaDeOutro: "只在这个服务器生效。留空即可恢复原来的名字。",
  },
  detalhes: {
    abrir: "语音详情",
    titulo: "语音详情",
    conexao: "连接",
    pingMedio: "平均延迟",
    ultimoPing: "最近延迟",
    perda: "发送丢包",
    medindo: "测量中…",
    criptografado: "到服务器为止加密（DTLS-SRTP）",
    explicacao: "超过 250 毫秒就能听出对话的延迟，大家会开始抢话。丢包超过 10% 会让声音变得机械。这两种情况的问题几乎都出在你和网络之间：试试用网线代替 Wi-Fi，或者重启路由器。",
  },
  microfone: {
    bloqueado: "麦克风被阻止 — 你只能听。请在浏览器权限里允许访问。",
    bloqueadoNoMac: "macOS 正在阻止麦克风。请勾选",
    caminhoNoMac: "系统设置 → 隐私与安全性 → 麦克风",
    abrirAjustes: "打开设置",
    vaiReabrir: "macOS 会要求你重新打开应用。",
    naoAbriu: "没能打开麦克风 — 你只能听。请在 设置 → 语音和视频 里检查设备。",
  },
  gravacaoDeTela: {
    bloqueada: "macOS 还没有允许屏幕录制。没有它，共享出来是黑的。",
    marque: "请勾选",
    reabra: "在“屏幕录制”里打开，然后重新打开应用。",
  },
  ruido: {
    titulo: "降噪",
    explicacao: "把背景噪音从你的声音里去掉。说话时试着拍拍手或者拖动键盘 — 通话里的人只会听到你。",
    semSuporte: "这个浏览器跑不了高级降噪。浏览器自带的仍然有效，只是更弱一些。",
    aplicando: "正在应用到通话…",
    faleParaTestar: "说话来测试",
    verdeQuandoPassa: "声音通过时会变绿。",
    teOuvindo: "现在他们听得到你。",
    feitoCom: "技术来自",
    aquiNoAparelho: "，就在你的设备上",
    ajustes: "设置",
  },
  permissoes: {
    titulo: "macOS 权限",
    detalhe: "macOS 只问一次，之后只能在它自己的面板里改。这里可以看到当前生效的情况，并解决缺少的部分。",
    concedida: "已授予",
    negada: "已拒绝",
    naoPedida: "未请求",
    permitir: "允许",
    abrirAjustes: "打开设置",
    microfone: "麦克风",
    microfoneDetalhe: "在通话中说话，并测试你的输入。",
    camera: "摄像头",
    cameraDetalhe: "在通话中打开视频。",
    tela: "屏幕录制",
    telaDetalhe: "共享屏幕和窗口。",
    monitoramento: "输入监听",
    monitoramentoDetalhe: "即使 Gravaê 在后台也能使用按键通话。",
  },
  jaConectado: {
    titulo: "你已经在这个通话里了",
    trazer: "把通话转到这里",
    deixar: "保持原样",
    detalhe: "转到这里后，另一端会退出通话 — 你的账号一次只在一个地方。",
  },
};
