export const configuracoes = {
  efeitos: {
    titulo: "指针效果",
    detalhe: "画在界面上层的拖尾和火花。默认关着，你要求减少动效时它们会自己退场。",
    rastro: "光标拖尾",
    rastroDetalhe: "跟着指针跑、在后面渐渐淡掉的一条线。",
    faisca: "点击火花",
    faiscaDetalhe: "从你点下去的地方甩出来的短线。",
    cor: "颜色",
    espessura: "粗细",
    comprimento: "长度",
    tamanho: "大小",
    quantidade: "数量",
  },
  email: {
    verificarTitulo: "确认你的邮箱",
    verificarDetalhe: "有些社区只让确认过的人发言。点一下就好。",
    enviar: "发送链接",
    enviado: "去收件箱看看。链接一天内有效。",
    falhou: "邮件没能发出去。",
    confirmado: "邮箱已确认",
    confirmadoDetalhe: "好了。凡是要求这一步的社区，你现在都能发言。",
    linkIncompleto: "链接不完整",
    linkIncompletoDetalhe: "地址里少了验证码。请直接从邮件里打开链接。",
    confirmando: "确认中…",
    expirou: "这个链接已经用过，或者过期了。",
    irParaOApp: "前往应用",
  },
  tema: {
    indisponivel: "主题不可用",
    indisponivelDetalhe: "发布的人删掉了，或者链接错了。",
    indisponivelLinha: "主题不可用。发布的人删掉了，或者链接错了。",
    importar: "导入主题",
    importarCurto: "导入",
    importarDetalhe: "这会替换你现在的主题。之后可以在 设置 > 外观 > 主题工作室 里修改。",
    porAutor: "作者 {{autor}}",
    umaCorTrocada: "换了 1 种颜色",
    coresTrocadas: "换了 {{quantas}} 种颜色",
    avisoDeCss: "这个主题带着作者写的 CSS，而 CSS 能碰到屏幕的每个角落。只从你信得过的人那里导入。",
    soCores: "这个主题只换颜色，没有外来的 CSS。",
    aplicar: "应用",
    previaSemMotor: "预览不会跑引擎，装上才看得到。",
    motorAnimado: "{{motor}} 动态",
  },
  sair: "退出登录",
  versoes: {
    termos: "服务条款",
    privacidade: "隐私政策",
    copiar: "点击复制",
    copiado: "已复制",
  },
  telas: {
    conta: "我的账号",
    privacidade: "隐私",
    conexoes: "连接",
    voz: "音频",
    video: "视频",
    avisos: "通知",
    aplicativos: "应用程序",
    aparencia: "外观",
    batePapo: "聊天",
    acessibilidade: "无障碍",
    idioma: "语言",
    aplicativo: "下载应用",
    atalhos: "快捷键",
    desktop: "桌面应用",
    avancado: "高级",
    servidor: "服务器",
    comunicado: "系统公告",
    denuncias: "举报",
    publicacoes: "部署",
  },
  grupos: {
    conta: "账号",
    app: "应用设置",
    desenvolvedor: "开发者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "登录信息",
    dispositivos: "设备",
    usuariosBloqueados: "已屏蔽的用户",
    aplicativosAutorizados: "已授权的应用",
    sessoes: "会话",
    amigosEDms: "好友与私信",
    compartilhamentoDeAtividade: "活动共享",
    visibilidadeDoPerfil: "个人资料可见性",
    exportarDados: "导出数据",
    exclusaoDeDados: "删除数据",
    tema: "主题",
    corDeDestaque: "强调色",
    interface: "界面",
    listaDeCanais: "频道列表",
    zoomDoApp: "应用缩放级别",
    escalaDaFonte: "聊天字体大小",
    modoStreamer: "直播隐私",
    cursores: "光标",
    movimento: "动效",
    textoEmVoz: "文字转语音",
    teclado: "键盘",
    formatoDaHora: "时间格式",
    idiomaDaInterface: "界面语言",
    dispositivosDeVoz: "设备",
    testeDoMicrofone: "麦克风测试",
    modoDeEntrada: "输入模式",
    sensibilidade: "输入灵敏度",
    qualidade: "画质",
    camera: "摄像头",
    transmissao: "推流",
    exibicao: "显示",
    entrada: "输入",
    midia: "媒体",
    geral: "常规",
    preferenciaDeMencao: "提及偏好",
    sons: "声音",
  },
};
