export const configuracoes = {
  sair: "退出登录",
  versoes: {
    copiar: "点击复制",
    copiado: "已复制",
  },
  telas: {
    conta: "我的账号",
    privacidade: "隐私",
    conexoes: "连接",
    voz: "音频",
    video: "视频",
    avisos: "通知",
    aplicativos: "应用程序",
    aparencia: "外观",
    batePapo: "聊天",
    acessibilidade: "无障碍",
    idioma: "语言",
    aplicativo: "下载应用",
    atalhos: "快捷键",
    servidor: "服务器",
  },
  grupos: {
    conta: "账号",
    app: "应用设置",
    desenvolvedor: "开发者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "登录信息",
    dispositivos: "设备",
    usuariosBloqueados: "已屏蔽的用户",
    aplicativosAutorizados: "已授权的应用",
    sessoes: "会话",
    amigosEDms: "好友与私信",
    compartilhamentoDeAtividade: "活动共享",
    visibilidadeDoPerfil: "个人资料可见性",
    exportarDados: "导出数据",
    exclusaoDeDados: "删除数据",
    tema: "主题",
    corDeDestaque: "强调色",
    interface: "界面",
    listaDeCanais: "频道列表",
    zoomDoApp: "应用缩放级别",
    escalaDaFonte: "聊天字体大小",
    modoStreamer: "直播隐私",
    movimento: "动效",
    textoEmVoz: "文字转语音",
    teclado: "键盘",
    formatoDaHora: "时间格式",
    idiomaDaInterface: "界面语言",
    dispositivosDeVoz: "设备",
    testeDoMicrofone: "麦克风测试",
    modoDeEntrada: "输入模式",
    sensibilidade: "输入灵敏度",
    qualidade: "画质",
    camera: "摄像头",
    transmissao: "推流",
    exibicao: "显示",
    entrada: "输入",
    midia: "媒体",
    geral: "常规",
    preferenciaDeMencao: "提及偏好",
    sons: "声音",
  },
};
