export const conversa = {
  lista: {
    carregando: "正在加载消息…",
    carregandoMais: "加载中…",
    verMais: "向上滚动查看更多",
    semHistorico: "无法查看历史记录",
    semHistoricoDetalhe: "你的角色没有读取 #{{canal}} 历史记录的权限。你在这里期间，新消息仍会正常出现。",
    boasVindas: "欢迎来到 #{{canal}}",
    boasVindasDetalhe: "这里是 #{{canal}} 频道的开始。",
  },
  data: {
    hoje: "今天",
    ontem: "昨天",
    hojeAs: "今天 {{hora}}",
    ontemAs: "昨天 {{hora}}",
  },
  digitando: {
    um: "{{nome}} 正在输入…",
    dois: "{{primeiro}} 和 {{segundo}} 正在输入…",
    varios: "{{quantidade}} 人正在输入…",
  },
  mensagem: {
    usou: "使用了",
    fixada: "已置顶",
    editado: "(已编辑)",
    ignorada: "来自你已忽略的人的消息。",
    mostrar: "显示",
    escPara: "按 Esc",
    cancelar: "取消",
    enterParaSalvar: "按 Enter 保存",
    falhou: "没有发送成功。重试",
    naoLidasDaqui: "已标记为从这里开始未读。",
    linkCopiado: "链接已复制。",
    idCopiado: "ID 已复制。",
    naoDeuParaCopiar: "你的浏览器不允许复制。",
    apagarTitulo: "删除这条消息？",
    apagarDescricao: "它会对频道里的所有人消失，无法恢复。",
    apagarAcao: "删除",
    citacaoAnexo: "点击查看附件",
    citacaoSumiu: "原始消息已经不在了。",
    reagirCom: "用 {{emoji}} 回应 — 长按可超级回应",
    segureParaSuper: "{{emoji}} — 长按可超级回应",
  },
  acoes: {
    reagir: "回应",
    responder: "回复",
    encaminhar: "转发",
    favoritar: "收藏消息",
    tirarDosFavoritos: "取消收藏",
    marcarNaoLida: "标记为未读",
    copiarLink: "复制消息链接",
    copiarId: "复制消息 ID",
    fixar: "置顶消息",
    desafixar: "取消置顶",
    editar: "编辑",
    apagar: "删除",
    mais: "更多",
    adicionarReacao: "添加回应",
    superReagirCom: "用 {{emoji}} 超级回应",
    fixarMensagem: "置顶消息",
    desafixarMensagem: "取消置顶消息",
    editarMensagem: "编辑消息",
    apagarMensagem: "删除消息",
  },
  mencao: {
    cargo: "身份组提及",
    pessoa: "提及",
    alguem: "某人",
    cargoSemNome: "身份组",
    here: "通知在线的人",
    everyone: "通知整个服务器",
  },
  codigo: {
    copiar: "复制",
    copiado: "已复制",
    copiarAria: "复制代码",
    copiadoAria: "代码已复制",
    recolher: "收起",
    expandir: "展开",
    verInteiro: "查看完整文件",
    maisOpcoes: "更多选项",
    baixar: "下载",
    recolherLinhas: "收起（{{linhas}} 行）",
    expandirLinhas: "展开（{{linhas}} 行）",
    mudarIdioma: "更改语言",
    procurarIdioma: "搜索语言代码…",
    nenhumIdioma: "没有这个语言。",
    quebrarTexto: "自动换行",
  },
  caixa: {
    escrever: "在 #{{canal}} 中发消息",
    escreverSemCanal: "发消息",
    semPermissao: "你没有在这个频道发送消息的权限",
    solteParaAnexar: "松开以添加附件",
    longaTitulo: "消息太长了…",
    longaDescricao: "已达到 {{limite}} 字符的上限，可以作为文件发送。",
    enviarComoArquivo: "作为文件发送",
    textoComoArquivo: "将文本作为文件发送",
    arquivoGrandeTitulo: "文件太大了",
    arquivoGrandeDescricao: "“{{arquivo}}”超过了每个文件 {{limite}} MB 的上限。",
    respondendoPara: "正在回复",
    vaiNotificar: "对方会收到通知",
    naoVaiNotificar: "对方不会收到通知",
    ligado: "开",
    desligado: "关",
    pararDeResponder: "取消回复",
    mais: "更多",
    enviarArquivo: "发送文件",
    criarEnquete: "创建投票",
    expressoes: "表情、GIF 和贴纸",
    enviar: "发送",
    aguardandoEnvio: "正在等待上传",
    modoLento: "慢速模式已开启（{{tempo}}）",
    modoLentoDica: "慢速模式设为 {{segundos}} 秒。请等待后再发下一条消息。",
  },
  anexos: {
    enviando: "上传中…",
    modificar: "修改 {{arquivo}}",
    verPrevia: "预览 {{arquivo}}",
    excluirTitulo: "删除附件",
    excluirDescricao: "删除“{{arquivo}}”？无法撤销，它会从这条消息中消失。",
    excluirAcao: "删除附件",
    excluirFalhou: "无法删除附件。",
    remover: "移除 {{arquivo}}",
    ver: "查看 {{arquivo}}",
    mostrarSpoiler: "显示剧透：{{arquivo}}",
    spoiler: "剧透",
    spoilerTitulo: "剧透",
    editarTitulo: "编辑附件",
    nomeDoArquivo: "文件名",
    descricao: "替代文本说明",
    descricaoDica: "为屏幕阅读器描述这个媒体文件",
    marcarSpoiler: "标记为剧透",
    cancelar: "取消",
    salvar: "保存",
  },
  cartao: {
    tocador: "播放器",
    abrir: "打开 {{destino}}",
    tocar: "播放 {{titulo}}",
    video: "视频",
    verImagem: "查看图片",
  },
  enquete: {
    titulo: "投票",
    encerrada: "投票已结束",
    variasRespostas: "投票 — 可多选",
    umVoto: "{{quantidade}} 票",
    votos: "{{quantidade}} 票",
    umVotoNoTotal: "共 {{quantidade}} 票",
    votosNoTotal: "共 {{quantidade}} 票",
    encerraEm: "{{quando}} 结束",
    encerrarAgora: "立即结束",
  },
  fixadas: {
    titulo: "已置顶的消息",
    vazio: "这个频道还没有置顶消息。",
    desafixar: "取消置顶",
    anexo: "（附件）",
    enquete: "（投票）",
    dicaRotulo: "小提示：",
    dica: "拥有“管理消息”权限的人，可以直接从消息菜单置顶。",
  },
  encaminhar: {
    titulo: "转发消息",
    paraOnde: "转发到哪里？",
    semTexto: "（没有文字的消息）",
    nenhumLugar: "没有叫这个名字的地方。",
    canais: "频道",
    conversas: "私信",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "在 Klipy 中搜索",
    figurinha: "贴纸",
    buscarFigurinha: "找到合适的贴纸",
    buscarEmoji: "找到合适的表情",
    buscarReacao: "找到合适的回应",
    adicionarEmoji: "添加表情",
    limparBusca: "清除搜索",
  },
  busca: {
    fechar: "关闭搜索",
    procurando: "搜索中…",
    resultado: "{{quantos}} 条结果",
    resultados: "{{quantos}} 条结果",
    nadaCom: "这里没有和 {{termo}} 有关的内容。",
    soOsQuePodeLer: "搜索只查看你能读取的频道。",
  },
  entrada: {
    titulo: "收件箱",
    naoLidas: "未读",
    salvas: "已保存",
    mencoes: "提及",
    fimTitulo: "你已经看到底了",
    fimDetalhe: "没有可读的了。有新消息时会出现在这里。",
    semSalvosTitulo: "没有保存的内容",
    semSalvosDetalhe: "按住 Shift 点击消息的书签，就能留着以后看。",
    tirarDosSalvos: "从已保存中移除",
    semMencoesTitulo: "还没有提及",
    semMencoesDetalhe: "提到你的内容会在这里保留最近 7 天。",
  },
  forum: {
    descricao: "每个话题都会成为单独的对话——适合那种不该淹没在闲聊里的问题。",
    novoAssunto: "新话题",
    vazio: "还没有话题。开个头，对话从一开始就是整齐的。",
    titulo: "标题",
    doQueSeTrata: "关于什么？",
    primeiraMensagem: "第一条消息",
    conteDoCaso: "说说看",
  },
};
