export const perfil = {
  carregando: "正在加载…",
  editar: "编辑资料",
  mensagem: "发消息",
  abrirConversa: "打开会话",
  verCompleto: "查看完整资料",
  convidarParaServidor: "邀请到服务器",
  semServidores: "你还没有服务器",
  conviteEnviado: "已向 {{nome}} 发送邀请。",
  moderador: "以管理员视图打开",
  mais: "更多",
  ignorar: "忽略",
  deixarDeIgnorar: "取消忽略",
  copiarId: "复制用户 ID",
  idCopiado: "ID 已复制。",
  conexoes: "连接",
  membroDesde: "加入于",
  sobre: "关于",
  cargosTitulo: "身份组",
  visaoGeral: "总览",
  amigosEmComum: "共同好友（{{quantidade}}）",
  servidoresEmComum: "共同服务器（{{quantidade}}）",
  amizade: {
    amigo: "好友",
    pedidoEnviado: "已发送好友申请",
    respondaAbaixo: "给你发了申请 — 在下面回应",
    adicionar: "添加好友",
    teMandouPedido: "给你发了好友申请",
    aceitar: "接受",
    desfazer: "解除好友",
    desfazerTitulo: "把 {{nome}} 从好友中移除？",
    desfazerDescricao: "你们不再是好友。私聊会留在历史记录里，之后还可以再加回来。",
    bloquear: "屏蔽",
    bloquearTitulo: "屏蔽 {{nome}}？",
    bloquearDescricao: "你们不再是好友，私聊不再接收消息，对方也无法再给你发好友申请。",
    linkCopiado: "你们不是好友 — 链接已复制，你自己发给对方吧。",
  },
  recado: {
    escrever: "给 @{{usuario}} 发消息",
    enviar: "发送",
    enviada: "消息已发送",
    falhou: "没能发送。试试从会话里发。",
  },
  cartao: {
    trocarFaixa: "更换卡片横幅",
    trocarFaixaCurto: "更换横幅",
    trocarFoto: "更换头像",
    trocarFotoCurto: "更换图片",
    suaEtiqueta: "你的标签",
    editarEtiqueta: "点击编辑你的标签",
    conteAlgo: "说说你自己",
    adicionarStatus: "添加状态",
    adicionarDescricao: "点击添加简介",
    cargo: "身份组",
    cargos: "身份组",
    cargosCom: "身份组 — {{quantidade}}",
    tirarCargo: "移除身份组 {{cargo}}",
  },
  cargos: {
    adicionar: "添加身份组",
    procurar: "搜索身份组",
  },
  etiqueta: {
    escolher: "选择服务器标签",
    nenhuma: "没有服务器标签",
    semEtiqueta: "你的服务器都没有标签",
  },
  emblemas: {
    doServidor: "这个服务器的徽章",
    limite: "最多可以佩戴 {{quantidade}} 个徽章。",
  },
  nota: {
    vazia: "点击记点东西",
    rotulo: "备注（只有你能看到）",
  },
  status: {
    titulo: "状态",
    definir: "设置你的状态",
    escolherEmoji: "选择表情",
    tirarEmoji: "移除表情",
    oQuePensa: "在想些什么？",
    limparAgora: "立刻清除状态",
    naoLimpar: "不清除",
    limpar30m: "30 分钟后清除",
    limpar1h: "1 小时后清除",
    limpar4h: "4 小时后清除",
    limparHoje: "今天清除",
    limparAmanha: "明天清除",
    comHora: "{{prazo}} {{hora}}",
  },
  presenca: {
    disponivel: "在线",
    ausente: "离开",
    naoPerturbar: "请勿打扰",
    naoPerturbarDetalhe: "你不会收到新消息提醒",
    invisivel: "隐身",
    invisivelDetalhe: "在别人看来你处于离线",
  },
  menu: {
    mudarDeConta: "切换账号",
    gerenciarContas: "管理账号",
  },
  editor: {
    decoracao: "更换头像装饰",
    naoSalvo: "别忘了保存你的修改！",
    principal: "主资料",
  },
};
