export const servidor = {
  titulo: "服务器设置",
  auditoria: {
    titulo: "审计日志",
    porUsuario: "按人筛选",
    porAcao: "按操作筛选",
    vazio: "此筛选条件下还没有任何记录。",
    motivo: "原因：",
  },
  banimentos: {
    titulo: "服务器封禁名单",
    descricao: "名单上的人即使拿到新邀请也进不来。解除封禁会立刻恢复访问。",
    procurar: "按用户名搜索封禁",
    vazioTitulo: "没有封禁",
    vazio: "你还没封禁过任何人……但真需要的时候，别犹豫。",
    desbanir: "解除封禁",
  },
  excluir: {
    titulo: "删除服务器",
    aviso: "此操作无法撤销。",
  },
  emblemas: {
    titulo: "徽章",
    vazio: "还没有徽章。",
    novo: "新徽章",
  },
  convites: {
    titulo: "邀请",
    descricao: "该服务器所有有效的邀请链接。",
    vazio: "还没有创建任何邀请。",
    revogar: "撤销邀请",
  },
  integracoes: {
    titulo: "集成",
    descricao: "Webhook 是一个无需账号就能向频道发消息的地址。适合用来通报构建通过、有人开了工单，或任何你想从脚本里发出的内容。",
    novo: "新建 Webhook",
    vazio: "还没有 Webhook。创建一个，把 URL 贴到你希望消息来源的地方。",
    canal: "频道",
    apagar: "删除 Webhook",
    comoUsar: "怎么用",
    comoUsarTexto: "发送带 JSON 的 POST。格式与 Discord 相同，所以现成的脚本无需改动即可使用：",
  },
  engajamento: {
    titulo: "活跃度",
    descricao: "新人到来时，服务器自己做点什么才不会显得冷清。",
    sistema: "系统消息",
    boasVindas: "有人加入时发送欢迎消息",
    sorteio: "下面不写自己的文案时，句子会随机抽选——总是同一句很快就腻了。",
    canalDoSistema: "系统消息频道",
    mensagem: "欢迎消息",
    deixeVazio: "留空则从现成的句子中抽选",
  },
  automod: {
    titulo: "自动管理",
    descricao: "在消息还没出现之前就自己动手的过滤器。管理服务器的人从不会被过滤——豁免身份组也直接放行。",
    palavras: {
      titulo: "屏蔽自定义词",
      descricao: "你自己列的、谁都不能写的词。",
    },
    mencoes: {
      titulo: "屏蔽提及刷屏",
      descricao: "屏蔽一次提及太多人的消息。",
    },
    links: {
      titulo: "屏蔽链接",
      descricao: "拦下任何粘贴到聊天里的地址。",
    },
    definir: "设置",
    nomeDaRegra: "规则名称",
    bloqueadas: "被屏蔽的词",
    digiteEnter: "输入后按 Enter",
    comparacao: "比对会忽略大小写、变音符号和标点——也不会抓词中之词。",
    aPartirDe: "从多少次提及开始屏蔽",
    oQueFazer: "要做什么",
    canalDoAlerta: "提醒频道",
    escolhaCanal: "选一个频道",
    castigo: "禁言（分钟）",
    isentos: "豁免身份组",
    semCargos: "还没有创建身份组。",
    salvarRegra: "保存规则",
    apagar: "删除规则",
    excluirTitulo: "删除这条自动管理规则？",
    excluirDescricao: "服务器会立刻停止按它过滤。可以重新创建，但当前配置会丢失。",
    excluirAcao: "删除规则",
  },
  cargos: {
    titulo: "身份组",
    descricao: "身份组给的是名字、颜色和权限。在列表里越靠上，越管得住下面的人——谁也动不了与自己同级或更高的身份组。",
    criar: "创建身份组",
    vazio: "还没有身份组。",
    abaExibicao: "显示",
    abaPermissoes: "权限",
    abaMembros: "成员 — {{quantos}}",
    everyone: "对服务器上所有人生效。其他身份组都叠在它上面。",
    nomeDoCargo: "身份组名称",
    cor: "身份组颜色",
    corDica: "在成员列表和聊天里给拥有该身份组的人上色。",
    semCor: "不上色",
    corPersonalizada: "自定义颜色",
    estilo: "名字样式",
    segundaCor: "第二种颜色",
    segundaCorDica: "没有它，渐变会退回纯色——不会消失。",
    limparSegundaCor: "清除第二种颜色",
    icone: "图标",
    iconeDica: "出现在拥有者个人资料卡上，身份组旁边。",
    exibirSeparado: "与其他成员分开显示",
    exibirSeparadoDica: "该身份组在成员列表里会有自己的分区。",
    permitirMencionar: "允许提及此身份组",
    permitirMencionarDica: "任何人都能提醒所有拥有该身份组的人。",
    semPoderDeConceder: "{{descricao}}（你没有这项权限，因此无法授予）",
    adicionar: "把某人加入该身份组",
    tirar: "移除身份组",
    semNinguem: "还没有人拥有这个身份组。",
    apagar: "删除身份组",
    excluirTitulo: "删除身份组“{{nome}}”？",
    excluirDescricao: "拥有这个身份组的人会失去它带来的一切。无法撤销。",
    excluirAcao: "删除身份组",
  },
  membros: {
    procurar: "按名称或用户名搜索",
    membroDesde: "加入于",
    vazio: "没有找到任何人。",
    acoesPara: "对 {{nome}} 的操作",
    deCastigo: "禁言",
    tirarCastigo: "解除禁言",
    castigo5min: "5 分钟",
    castigo1h: "1 小时",
    castigo1d: "1 天",
    castigo1s: "1 周",
    expulsar: "踢出",
    expulsarTitulo: "踢出 {{nome}}？",
    expulsarDescricao: "会立刻离开 {{servidor}}。凭邀请可以回来——踢出并不阻止返回。",
    banir: "封禁",
    banirTitulo: "封禁 {{nome}}？",
    banirDescricao: "会离开 {{servidor}}，在解封之前即使有邀请也回不来。",
    motivo: "理由（可选）",
    motivoDica: "会记入审计日志",
  },
  perfil: {
    titulo: "服务器资料",
    descricao: "你的服务器在列表和邀请链接里就是这样显示的。",
    icone: "图标",
    faixa: "顶部横幅",
    nomeDoServidor: "服务器名称",
    campoDescricao: "简介",
    doQueE: "这个服务器是做什么的？",
    comprimido: "上传前已压缩：{{economia}}",
  },
  etiqueta: {
    titulo: "服务器标签",
    descricao: "一个最多 4 个字的标签，出现在每位成员的名字旁边——聊天里和人员列表里都有。这里免费：不用加成，也不用等级。",
    escolhaNome: "取一个名字",
    limite: "最多 4 个字符，字母和数字。",
    escolhaInsignia: "选一个徽章",
    voce: "你",
    fala1: "有人一起玩吗？",
    fala2: "看看我的标签！",
    fala3: "哇，这你哪来的",
  },
  expressoes: {
    comoUsar: "最多添加 {{limite}} 个本服务器所有人都能用的表情。在聊天里输入 :名称: 就能发送。",
    imagem: "图片",
    enviadoPor: "上传者",
    semEmoji: "还没有表情。",
    figurinhas: "贴纸",
    enviarFigurinha: "上传贴纸",
    nomeDaFigurinha: "贴纸名称",
    exemploFigurinha: "例：小猫抱抱",
    figurinhaGrande: "贴纸超过 {{limite}}。",
    deixaPraLa: "算了",
    sons: "音效板",
    enviarSom: "上传音效",
    nomeDoSom: "音效名称",
    semSom: "还没有音效。",
    somGrande: "音效超过 {{limite}}。",
    emojiRelacionado: "关联表情",
    ouvir: "试听",
    ouvirAssim: "按这个音量听",
    volumeDe: "{{nome}} 的音量",
    volumeDica: "对服务器上所有人生效。每个人仍可以在通话面板里只为自己调小声音。",
    falhaEnvio: "文件上传失败。",
    excluirTitulo: "删除{{tipo}}“{{nome}}”？",
    excluirDescricao: "会从所有人的服务器上消失。已经用过它的消息保持原样。",
  },
};
