export const servidor = {
  comunidade: {
    ativa: "社区已经开放",
    ativaDesde: "自 {{quando}} 起开放",
    membrosAgora: "{{quantos}} 名成员",
    criarParaMim: "帮我建一个",
    canalDeRegras: "规则频道",
    canalDeRegrasDetalhe: "放规则的地方，大家开口之前都会先看一遍。",
    canalDeAvisos: "社区公告频道",
    canalDeAvisosDetalhe: "我们把这里的变动发到这个频道，只有管理的人看得到。",
    canalDeSeguranca: "安全提醒频道",
    canalDeSegurancaDetalhe: "过滤器拦下来的东西，管理团队在这里收到。",
    idiomaPrincipal: "主要语言",
    idiomaPrincipalDetalhe: "大部分对话所用的语言。",
    semIdioma: "未选语言",
    semCanal: "没有频道",
    finalTitulo: "就快好了",
    finalDetalhe: "开之前，看看对新来的人有哪些改变。",
    confereRegras: "进来的人最先看到规则频道。",
    confereEveryone: "只有带身份组的人才能用 @everyone 和 @here。",
    confereMencoes: "一次叫上所有人，从此需要权限。",
    concordo: "我同意并已了解",
    concordoDetalhe: "你确认这个社区会遵守我们的准则。",
    proximo: "下一步",
    terminar: "完成设置",
    visaoGeral: "总览",
    visaoGeralDetalhe: "社区用来跟新人说话的频道。",
    seguranca: "安全",
    segurancaDetalhe: "挡住垃圾信息和重口味内容的闸。",
    habilitada: "社区已开启。",
    falhou: "社区没能开启。",
    titulo: "社区",
    ilustracao: "对话气泡",
    convite: "你在搭建一个社区吗？",
    conviteDetalhe: "转成社区，就能拿到管理大地方的工具：规则频道、我们发的公告，以及会自己把关的过滤器。",
    contagem: "{{minimo}} 人中的 {{membros}} 人",
    faltam: "还差 {{quantos}} 人才能开。",
    prontoParaAbrir: "现在就能开了。",
    habilitar: "开启社区",
    vantagemCrescer: "长大",
    vantagemCrescerDetalhe: "社区可以申请进入「发现」，找这个主题的人就能找到你们。",
    vantagemModerar: "把关",
    vantagemModerarDetalhe: "要求验证邮箱、过滤媒体、开启 AutoMod，一次搞定。",
    vantagemAvisos: "掌握动态",
    vantagemAvisosDetalhe: "我们把变动发给管理这里的人，放在只属于你们的频道里。",
    assistenteTitulo: "来把你的社区搭起来。",
    passoSeguranca: "安全检查",
    passoBasico: "基础准备",
    passoFinal: "最后收尾",
    seguraTitulo: "让社区保持安全",
    seguraDetalhe: "大社区容易招来垃圾信息。这两道闸默认打开，之后觉得碍事再关也行。",
    emailVerificado: "要求验证过的邮箱",
    emailVerificadoDetalhe: "还没验证邮箱的人发不了消息。有身份组的人直接放行。",
    filtroDeMidia: "过滤露骨内容",
    filtroDeMidiaDetalhe: "图片和视频进来时是遮住的，有人点了才显示。",
    basicoTitulo: "把基础备好",
    basicoDetalhe: "说明规则放在哪个频道，我们的公告发到哪里。没选的话，两个我都建。",
  },
  descoberta: {
    quantosComandos: "{{quantos}} 个命令",
    previa: "卡片长这样",
    trocarIcone: "换图标",
    tirarCapa: "去掉封面",
    heroComunidades: "有人正在聊你喜欢的东西",
    heroComunidadesDetalhe: "这些社区都是这里的人自己开的。进去看看聊什么，合得来就留下。",
    emDestaque: "精选",
    todasAsComunidades: "其余的",
    heroTitulo: "今天你们这帮人想用点什么？",
    heroDetalhe: "音乐、游戏、管理的机器人，都是这里的人自己做的。挑一个，它就进你的服务器。",
    novidades: "刚到的",
    todosOsApps: "其余的",
    lojaTitulo: "应用页面",
    lojaDetalhe: "还不认识它的人，在「发现」里看到的就是这些。",
    capa: "封面图",
    capaDetalhe: "页面顶上的宽图。1280 × 720 正合适。",
    trocarCapa: "换封面",
    categorias: "分类",
    categoriasDetalhe: "最多 {{quantas}} 个。大家在「发现」里就是照这个逛的。",
    idiomas: "语言",
    idiomasDetalhe: "最多 {{quantos}} 个。应用用哪些语言回话。",
    termos: "使用条款",
    politica: "隐私政策",
    politicas: "条款",
    servidorDeSuporte: "支持服务器",
    servidorDeSuporteDetalhe: "用应用遇到麻烦的人，往这里去。",
    semServidor: "不设",
    emQuantosServidores: "在多少个服务器里",
    categoria: {
      GAMES: "游戏",
      MUSICA: "音乐",
      MODERACAO: "管理",
      PRODUTIVIDADE: "效率",
      SOCIAL: "社交",
      UTILIDADES: "工具",
      ARTE_E_CRIACAO: "艺术与创作",
      EDUCACAO: "学习",
      OUTRA: "其他",
    },
    appIndisponivel: "应用不可用",
    voltarParaExplorar: "回到发现",
    adicionarApp: "添加应用",
    copiarLink: "复制链接",
    denunciarApp: "举报这个应用",
    copiarIdDoApp: "复制应用 ID",
    visaoGeral: "概览",
    comandos: "命令",
    permissoes: "权限",
    semPermissoes: "这个应用不要求任何权限。",
    avisoDePermissoes: "它会带着自己的身份组进来。这些权限之后可以在 社区设置 → 身份组 里改。",
    servidoresEmComum: "共同的社区",
    umServidorEmComum: "1 个社区",
    quantosServidoresEmComum: "{{quantos}} 个社区",
    feitoPor: "作者",
    publicadoEm: "发布于",
    denunciarNome: "举报 {{nome}}",
    denunciaDetalhe: "举报会送到 Gravaê 团队。做这个应用的人不会知道是你举报的。",
    denunciaFalhou: "举报没能送出。",
    umMembro: "1 位成员",
    semDescricao: "没有介绍。",
    adicionar: "添加",
    jaEstaAqui: "你已经在这里了",
    entrando: "正在加入…",
    entrar: "加入",
    comunidadePublica: "公开社区",
    online: "{{quantos}} 在线",
    membros: "{{quantos}} 位成员",
    abrirComunidade: "打开社区",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "服务器设置",
  novasMensagens: "新消息",
  menu: {
    silenciar: "静音社区",
    reativar: "取消静音社区",
    porQuinze: "15 分钟",
    porMeiaHora: "30 分钟",
    porTresHoras: "3 小时",
    porTresDias: "3 天",
    porUmaHora: "1 小时",
    porOitoHoras: "8 小时",
    porUmDia: "24 小时",
    ateReativar: "直到我重新开启",
    notificacoes: "通知设置",
    padrao: "使用默认",
    todas: "所有消息",
    soMencoes: "仅提及",
    nada: "无",
    ocultarSilenciados: "隐藏已静音的频道",
    denunciar: "举报社区",
    marcarLida: "标记为已读",
    convidar: "邀请成员",
    editarPerfil: "编辑社区资料",
    configuracoes: "社区设置",
    sair: "退出社区",
    sairTitulo: "退出 {{nome}}？",
    sairDescricao: "想回来需要新的邀请。",
    copiarId: "复制社区 ID",
    idCopiado: "已复制 ID。",
  },
  convite: {
    cartaoTitulo: "有人邀请你加入一个社区",
    indisponivel: "邀请不可用",
    indisponivelDetalhe: "已过期、已用完，或者创建的人删掉了。",
    entrar: "加入社区",
    chamado: "你受邀加入",
    aceitarComo: "以 {{nome}} 的身份接受",
    abrir: "打开社区",
    recusar: "不用了，谢谢",
  },
  pasta: {
    silenciarTodas: "静音社区",
    reativarTodas: "取消静音社区",
    mostrarSilenciados: "显示已静音的频道",
    notificacoesDaComunidade: "通知设置",
    silenciarEveryone: "静音 @everyone 和 @here",
    permitirEveryone: "允许 @everyone 和 @here",
    silenciarCargos: "静音身份组提及",
    permitirCargos: "允许身份组提及",
    dicaDaCor: "输入颜色（hex、rgb()、hsl() 或名称）或使用选择器。",
    mostrarIcone: "关闭时显示图标",
    dicaDoIcone: "关闭时显示图标，而不是里面的服务器。",
    icone: "文件夹图标",
    excluir: "删除文件夹",
    icones: {
      pasta: "文件夹",
      estrela: "收藏",
      coracao: "爱心",
      salvar: "保存",
      jogo: "游戏手柄",
      escudo: "盾牌",
      nota: "音符",
    },
    marcarLida: "将文件夹标记为已读",
    configuracoes: "文件夹设置",
    desfazer: "解散文件夹",
    titulo: "文件夹",
    nome: "名称",
    semNome: "未命名",
    cor: "颜色",
    semCor: "无颜色",
    salvar: "保存",
  },
  denuncia: {
    titulo: "举报 {{nome}}",
    descricao: "举报将发送给 Gravaê 团队。请告诉我们发生了什么。",
    motivo: "原因",
    detalhes: "详情（可选）",
    enviar: "发送举报",
    enviada: "举报已发送。谢谢。",
    motivos: {
      spam: "垃圾信息或广告",
      assedio: "骚扰或仇恨",
      conteudo: "不当内容",
      golpe: "诈骗",
      outro: "其他",
    },
  },
  selos: {
    verificada: "已验证社区",
    detectavel: "可发现社区",
  },
  auditoria: {
    todasAsAcoes: "所有操作",
    todosOsUsuarios: "所有用户",
    filtroMembros: "成员",
    filtroCanais: "频道",
    filtroEmojis: "表情",
    filtroServidor: "服务器",
    titulo: "审计日志",
    porUsuario: "按人筛选",
    porAcao: "按操作筛选",
    vazio: "此筛选条件下还没有任何记录。",
    motivo: "原因：",
  },
  banimentos: {
    titulo: "服务器封禁名单",
    descricao: "名单上的人即使拿到新邀请也进不来。解除封禁会立刻恢复访问。",
    procurar: "按用户名搜索封禁",
    vazioTitulo: "没有封禁",
    vazio: "你还没封禁过任何人……但真需要的时候，别犹豫。",
    desbanir: "解除封禁",
  },
  excluir: {
    tudoVai: "{{servidor}} 的所有频道、消息和邀请都会为 {{membros}} 名成员删除。此后谁也找不回来。",
    digite: "输入 {{servidor}} 以确认",
    titulo: "删除服务器",
    aviso: "此操作无法撤销。",
  },
  emblemas: {
    apagarDescricao: "它会从佩戴的每个人身上消失。无法撤销。",
    titulo: "徽章",
    vazio: "还没有徽章。",
    novo: "新徽章",
  },
  convites: {
    revogarTitulo: "撤销该邀请？",
    revogarAcao: "撤销",
    revogarDescricao: "链接 {{codigo}} 会立刻失效。已经通过它加入的人仍留在服务器。",
    titulo: "邀请",
    descricao: "该服务器所有有效的邀请链接。",
    vazio: "还没有创建任何邀请。",
    revogar: "撤销邀请",
  },
  integracoes: {
    opcionais: "username 和 avatar_url 是可选的，按消息生效。限制为每 5 秒 5 条。",
    apagarDescricao: "该 URL 会立刻失效。它已经发出的消息仍留在频道里。",
    titulo: "集成",
    descricao: "Webhook 是一个无需账号就能向频道发消息的地址。适合用来通报构建通过、有人开了工单，或任何你想从脚本里发出的内容。",
    novo: "新建 Webhook",
    vazio: "还没有 Webhook。创建一个，把 URL 贴到你希望消息来源的地方。",
    canal: "频道",
    apagar: "删除 Webhook",
    comoUsar: "怎么用",
    comoUsarTexto: "发送带 JSON 的 POST：",
  },
  explorar: {
    titulo: "发现",
  },
  engajamento: {
    semCanal: "没有系统频道",
    titulo: "活跃度",
    descricao: "新人到来时，服务器自己做点什么才不会显得冷清。",
    sistema: "系统消息",
    boasVindas: "有人加入时发送欢迎消息",
    sorteio: "下面不写自己的文案时，句子会随机抽选——总是同一句很快就腻了。",
    canalDoSistema: "系统消息频道",
    mensagem: "欢迎消息",
    deixeVazio: "留空则从现成的句子中抽选",
  },
  automod: {
    titulo: "自动管理",
    descricao: "在消息还没出现之前就自己动手的过滤器。管理服务器的人从不会被过滤——豁免身份组也直接放行。",
    palavras: {
      titulo: "屏蔽自定义词",
      descricao: "你自己列的、谁都不能写的词。",
    },
    mencoes: {
      titulo: "屏蔽提及刷屏",
      descricao: "屏蔽一次提及太多人的消息。",
    },
    links: {
      titulo: "屏蔽链接",
      descricao: "拦下任何粘贴到聊天里的地址。",
    },
    definir: "设置",
    nomeDaRegra: "规则名称",
    bloqueadas: "被屏蔽的词",
    digiteEnter: "输入后按 Enter",
    comparacao: "比对会忽略大小写、变音符号和标点——也不会抓词中之词。",
    aPartirDe: "从多少次提及开始屏蔽",
    oQueFazer: "要做什么",
    canalDoAlerta: "提醒频道",
    escolhaCanal: "选一个频道",
    castigo: "禁言（分钟）",
    isentos: "豁免身份组",
    semCargos: "还没有创建身份组。",
    salvarRegra: "保存规则",
    apagar: "删除规则",
    excluirTitulo: "删除这条自动管理规则？",
    excluirDescricao: "服务器会立刻停止按它过滤。可以重新创建，但当前配置会丢失。",
    excluirAcao: "删除规则",
  },
  cargos: {
    titulo: "身份组",
    descricao: "身份组给的是名字、颜色和权限。在列表里越靠上，越管得住下面的人——谁也动不了与自己同级或更高的身份组。",
    criar: "创建身份组",
    vazio: "还没有身份组。",
    abaExibicao: "显示",
    abaPermissoes: "权限",
    abaMembros: "成员 — {{quantos}}",
    everyone: "对服务器上所有人生效。其他身份组都叠在它上面。",
    nomeDoCargo: "身份组名称",
    cor: "身份组颜色",
    corDica: "在成员列表和聊天里给拥有该身份组的人上色。",
    semCor: "不上色",
    corPersonalizada: "自定义颜色",
    estilo: "名字样式",
    segundaCor: "第二种颜色",
    segundaCorDica: "没有它，渐变会退回纯色——不会消失。",
    limparSegundaCor: "清除第二种颜色",
    icone: "图标",
    iconeDica: "出现在拥有者个人资料卡上，身份组旁边。",
    exibirSeparado: "与其他成员分开显示",
    exibirSeparadoDica: "该身份组在成员列表里会有自己的分区。",
    permitirMencionar: "允许提及此身份组",
    permitirMencionarDica: "任何人都能提醒所有拥有该身份组的人。",
    semPoderDeConceder: "{{descricao}}（你没有这项权限，因此无法授予）",
    adicionar: "把某人加入该身份组",
    tirar: "移除身份组",
    semNinguem: "还没有人拥有这个身份组。",
    apagar: "删除身份组",
    excluirTitulo: "删除身份组“{{nome}}”？",
    excluirDescricao: "拥有这个身份组的人会失去它带来的一切。无法撤销。",
    excluirAcao: "删除身份组",
  },
  membros: {
    procurar: "按名称或用户名搜索",
    membroDesde: "加入于",
    vazio: "没有找到任何人。",
    acoesPara: "对 {{nome}} 的操作",
    deCastigo: "禁言",
    tirarCastigo: "解除禁言",
    castigo5min: "5 分钟",
    castigo1h: "1 小时",
    castigo1d: "1 天",
    castigo1s: "1 周",
    expulsar: "踢出",
    expulsarTitulo: "踢出 {{nome}}？",
    expulsarDescricao: "会立刻离开 {{servidor}}。凭邀请可以回来——踢出并不阻止返回。",
    banir: "封禁",
    banirTitulo: "封禁 {{nome}}？",
    banirDescricao: "会离开 {{servidor}}，在解封之前即使有邀请也回不来。",
    motivo: "理由（可选）",
    motivoDica: "会记入审计日志",
  },
  perfil: {
    titulo: "服务器资料",
    descricao: "你的服务器在列表和邀请链接里就是这样显示的。",
    icone: "图标",
    faixa: "顶部横幅",
    nomeDoServidor: "服务器名称",
    campoDescricao: "简介",
    doQueE: "这个服务器是做什么的？",
    comprimido: "上传前已压缩：{{economia}}",
  },
  etiqueta: {
    titulo: "服务器标签",
    descricao: "一个最多 4 个字的标签，出现在每位成员的名字旁边——聊天里和人员列表里都有。这里免费：不用加成，也不用等级。",
    escolhaNome: "取一个名字",
    limite: "最多 4 个字符，字母和数字。",
    escolhaInsignia: "选一个徽章",
    voce: "你",
    fala1: "有人一起玩吗？",
    fala2: "看看我的标签！",
    fala3: "哇，这你哪来的",
  },
  expressoes: {
    comoUsar: "最多添加 {{limite}} 个本服务器所有人都能用的表情。在聊天里输入 :名称: 就能发送。",
    imagem: "图片",
    enviadoPor: "上传者",
    semEmoji: "还没有表情。",
    figurinhas: "贴纸",
    enviarFigurinha: "上传贴纸",
    nomeDaFigurinha: "贴纸名称",
    exemploFigurinha: "例：小猫抱抱",
    figurinhaGrande: "贴纸超过 {{limite}}。",
    deixaPraLa: "算了",
    sons: "音效板",
    enviarSom: "上传音效",
    nomeDoSom: "音效名称",
    semSom: "还没有音效。",
    somGrande: "音效超过 {{limite}}。",
    emojiRelacionado: "关联表情",
    ouvir: "试听",
    ouvirAssim: "按这个音量听",
    volumeDe: "{{nome}} 的音量",
    volumeDica: "对服务器上所有人生效。每个人仍可以在通话面板里只为自己调小声音。",
    falhaEnvio: "文件上传失败。",
    excluirTitulo: "删除{{tipo}}“{{nome}}”？",
    excluirDescricao: "会从所有人的服务器上消失。已经用过它的消息保持原样。",
  },
  canal: {
    tipoLink: "链接",
    tipoLinkDica: "指向外部地址，在浏览器里打开",
    endereco: "地址",
    enderecoDica: "这个频道通向哪里。必须以 https:// 开头",
    visaoGeral: "概览",
    nome: "频道名称",
    topico: "频道主题",
    topicoDica: "这里聊些什么？",
    modoLento: "每人每个间隔只发一条消息。管理消息或频道的人直接通过。",
    visibilidade: "内容可见性",
    padrao: "默认",
    padraoDica: "频道内容始终可见。",
    spoiler: "剧透频道",
    spoilerDica: "把这个频道标为含剧透，让反转和沉重的话题保持隐藏，直到有人选择查看。",
    idade: "年龄限制频道",
    idadeDica: "进入的人须确认已成年才能看到内容。",
    bitrateDica: "超过 64 kbps 可能会影响网络较差的人。",
    qualidadeDeVideo: "视频画质",
    automatica: "自动",
    limite: "人数上限 — {{valor}}",
    pessoas: "{{quantos}} 人",
    semLimite: "不限",
    permissoesDescricao: "在这里你改的是本频道内生效的规则。留在“继承”的仍然跟随身份组。",
    excluir: {
      titulo: "删除频道",
      historico: "{{canal}} 的全部历史一并消失，对所有人。",
      digite: "输入 {{canal}} 以确认",
    },
  },
  moderacao: {
    titulo: "管理员视图",
    semPermissao: "需要“管理成员”权限才能查看。",
    fecharEsc: "关闭（Esc）",
    atividade: "在服务器上的活动",
    mensagens: "消息",
    links: "链接",
    midia: "媒体",
    acoesNaAuditoria: "审计日志中的操作",
    moderacoesSofridas: "受到的处理",
    permissoes: "权限（{{quantas}}）",
    semPermissaoEspecial: "没有特殊权限。",
    conta: "账号",
    entrouNoServidor: "加入服务器",
    contaCriadaEm: "账号创建于",
    deCastigoAte: "禁言至",
    formaDeAdesao: "如何加入",
    mensagem: "消息",
    castigo: "禁言",
    copiarId: "复制 ID",
    idCopiado: "已复制 ID。",
    adicionarCargo: "添加身份组",
    semCargos: "尚未创建身份组",
    soEveryone: "只有 @everyone。",
    voltar: "返回",
    vazio: "这里什么都没有。",
    cinquenta: "显示最新的 50 条。",
    irParaMensagem: "前往消息",
    precisaSerAmigo: "你们要先成为好友才能聊天。",
    expulsarDescricao: "立刻离开服务器，但可以凭邀请回来。",
    banirDescricao: "离开服务器，且在解封之前即使有邀请也回不来。",
    castigarTitulo: "将 {{nome}} 禁言？",
    castigoDescricao: "在此期间，他在服务器的任何频道都不能发言或说话。",
    aplicarCastigo: "应用禁言",
    duracao: "时长（分钟）",
    informeDuracao: "请填写时长（分钟）。",
  },
  abas: {
    pesquisar: "在设置里搜索",
    semResultado: "这里没有叫这个名字的。",
    comunidade: "社区",
    expressoes: "表情",
    pessoas: "人员",
    apps: "应用",
    moderacao: "管理",
    banimentos: "封禁",
  },
};
