export const amizades = {
  ativosAgora: "Đang hoạt động",
  procurando: "Xem ai đang ở đây…",
  tudoTranquilo: "Hiện giờ đang yên ắng…",
  tudoTranquiloDetalhe: "Khi bạn hoặc một người bạn vào cuộc gọi, nó sẽ hiện ở đây — và bạn tham gia chỉ với một cú nhấp.",
  emVoz: "Đang trong thoại",
  voce: "Bạn",
  soVoce: "Chỉ mình bạn",
  pessoas: "{{quantas}} người",
  voltarParaChamada: "Quay lại cuộc gọi",
  entrarNaChamada: "Tham gia cuộc gọi",
  abrirCanal: "Mở {{canal}} trong {{servidor}}",
  mensagensDiretas: "Tin nhắn trực tiếp",
  encontreConversa: "Tìm một cuộc trò chuyện",
  amigos: "Bạn bè",
  conversas: "Cuộc trò chuyện",
  semConversas: "Chưa có cuộc trò chuyện nào. Thêm một người bạn để bắt đầu.",
  semConversaComEsseNome: "Không có cuộc trò chuyện nào tên đó.",
  abrirMenu: "Mở máy chủ và cuộc trò chuyện",
  solicitacoes: "Yêu cầu nhắn tin",
  pedidos: "Yêu cầu",
  spam: "Spam",
  pedidosPendentes: "Yêu cầu đang chờ",
  marcadosComoSpam: "Đã đánh dấu là spam",
  aceitar: "Chấp nhận",
  ignorar: "Bỏ qua",
  marcarSpam: "Đánh dấu spam",
  semPedidos: "Không có yêu cầu nào đang chờ.",
  semPedidosDetalhe: "Người không phải bạn bè nhưng chung máy chủ với bạn sẽ đến đây trước khi vào các cuộc trò chuyện của bạn.",
  semSpam: "Không có gì bị đánh dấu là spam.",
  semSpamDetalhe: "Những gì bộ lọc spam tách ra, hoặc những gì bạn tự đánh dấu, sẽ nằm trong thẻ này.",
  umServidorEmComum: "1 máy chủ chung",
  servidoresEmComum: "{{quantos}} máy chủ chung",
  semServidoresEmComum: "Không có máy chủ chung",
};
