export const chamada = {
  conectando: "Đang kết nối cuộc gọi…",
  naoEntrou: "Không vào được cuộc gọi",
  sair: "Rời cuộc gọi",
  sairDaVoz: "Rời cuộc gọi thoại",
  desconectar: "Ngắt kết nối",
  voltar: "Quay lại cuộc gọi",
  voltarAosQuadros: "Quay lại các ô của cuộc gọi",
  fecharChat: "Đóng trò chuyện",
  carregandoPrevia: "Đang tải bản xem trước…",
  maisOpcoes: "Thêm tuỳ chọn",
  deVideo: "Cuộc gọi video",
  deVoz: "Cuộc gọi thoại",
  alguem: "Ai đó",
  volume: {
    entrada: "Âm lượng đầu vào",
    saida: "Âm lượng đầu ra",
    live: "Âm lượng buổi phát",
    liveComPorcento: "Âm lượng buổi phát ({{porcento}}%)",
    liveSemSom: "Buổi phát đã tắt tiếng",
  },
  aparelhos: {
    entrada: "Thiết bị đầu vào",
    saida: "Thiết bị đầu ra",
    camera: "Máy ảnh",
    microfone: "Micrô",
    saidaCurto: "Đầu ra",
    oDoSistema: "Theo hệ thống",
    aDoSistema: "Theo hệ thống",
    semEscolhaDeSaida: "Trình duyệt này không cho chọn đầu ra — hệ thống quyết định.",
    espelhar: "Lật gương máy ảnh của tôi",
    configEntrada: "Cài đặt đầu vào",
    configSaida: "Cài đặt đầu ra",
    configCamera: "Cài đặt máy ảnh",
    configAudioEVideo: "Cài đặt âm thanh và video",
  },
  tela: {
    compartilhar: "Chia sẻ màn hình",
    compartilharAcao: "Chia sẻ",
    cancelar: "Huỷ",
    telas: "Màn hình",
    janelas: "Cửa sổ",
    somDoComputador: "Mang theo cả tiếng máy tính",
    somDoSistema: "Mang theo cả tiếng hệ thống",
    configCompartilhamento: "Cài đặt chia sẻ",
    mostrarSemVideo: "Hiện cả người không bật video",
    semFontes: "Hệ thống không trả về màn hình hay cửa sổ nào để chia sẻ.",
    pararDeCompartilhar: "Ngừng chia sẻ",
    encerrarTransmissao: "Kết thúc buổi phát",
  },
  live: {
    etiqueta: "Trực tiếp",
    etiquetaMaiuscula: "TRỰC TIẾP",
    assistir: "Xem buổi phát",
    assistirPessoa: "Xem {{nome}}",
    pararDeAssistir: "Ngừng xem",
  },
  membro: {
    mudarMeuApelido: "Đổi biệt danh của tôi",
    meuMicrofone: "Micrô của tôi",
    ouvirChamada: "Nghe cuộc gọi",
    copiarMeuId: "Sao chép ID của tôi",
    idCopiado: "Đã sao chép ID.",
    mensagem: "Nhắn tin",
    silenciar: "Tắt tiếng",
    alterarApelido: "Đổi biệt danh",
    cargos: "Vai trò",
    semCargo: "Chưa tạo vai trò nào",
    moverPara: "Chuyển tới",
    silenciarNoServidor: "Tắt tiếng nói trên máy chủ",
    desativarAudioNoServidor: "Tắt âm thanh trên máy chủ",
    desconectar: "Ngắt kết nối",
    apelidoTitulo: "Biệt danh của bạn trên máy chủ này",
    apelidoDeAlguem: "Biệt danh của {{nome}}",
    apelidoCampo: "Biệt danh",
    apelidoDicaPropria: "Chỉ áp dụng ở đây. Để trống thì tên thường ngày của bạn quay lại.",
    apelidoDicaDeOutro: "Chỉ áp dụng trên máy chủ này. Để trống để quay lại tên gốc.",
  },
  detalhes: {
    abrir: "Chi tiết thoại",
    titulo: "Chi tiết Thoại",
    conexao: "Kết nối",
    pingMedio: "Ping trung bình",
    ultimoPing: "Ping gần nhất",
    perda: "Mất gói đã gửi",
    medindo: "Đang đo…",
    criptografado: "Mã hoá tới tận máy chủ (DTLS-SRTP)",
    explicacao: "Trên 250 ms là nghe rõ độ trễ trong cuộc trò chuyện — mọi người bắt đầu nói chồng lên nhau. Mất gói trên 10% khiến giọng nghe như robot. Cả hai trường hợp, vấn đề gần như luôn nằm giữa bạn và internet: thử dùng dây thay cho Wi-Fi, hoặc khởi động lại bộ định tuyến.",
  },
  microfone: {
    bloqueado: "Micrô bị chặn — bạn chỉ đang nghe. Hãy cho phép truy cập trong quyền của trình duyệt.",
    bloqueadoNoMac: "macOS đang chặn micrô. Hãy tích",
    caminhoNoMac: "Cài đặt Hệ thống → Quyền riêng tư & Bảo mật → Micrô",
    abrirAjustes: "Mở cài đặt",
    vaiReabrir: "macOS sẽ yêu cầu bạn mở lại ứng dụng.",
    naoAbriu: "Không mở được micrô — bạn chỉ đang nghe. Kiểm tra thiết bị ở Cài đặt → Thoại và video.",
  },
  gravacaoDeTela: {
    bloqueada: "macOS chưa cho phép ghi màn hình. Không có nó thì màn hình chia sẻ ra đen.",
    marque: "Hãy tích",
    reabra: "trong mục Ghi Màn hình rồi mở lại ứng dụng.",
    jaMarcado: "Nếu đã tích rồi thì quyền đã cũ đi từ lần cập nhật trước: bỏ tích, tích lại rồi mở lại ứng dụng.",
  },
  ruido: {
    titulo: "Khử tiếng ồn",
    explicacao: "Bỏ tiếng ồn nền khỏi giọng bạn. Thử vỗ tay hoặc kéo bàn phím khi đang nói — người trong cuộc gọi chỉ nghe thấy bạn.",
    semSuporte: "Trình duyệt này không chạy được bộ khử nâng cao. Bộ khử của chính trình duyệt vẫn hoạt động, nhưng yếu hơn.",
    aplicando: "Đang áp dụng cho cuộc gọi…",
    faleParaTestar: "Nói để thử",
    verdeQuandoPassa: "Xanh khi giọng bạn đi qua.",
    teOuvindo: "Họ đang nghe thấy bạn.",
    feitoCom: "Làm bằng",
    aquiNoAparelho: ", ngay trên thiết bị của bạn",
    ajustes: "Cài đặt",
  },
  permissoes: {
    titulo: "Quyền của macOS",
    detalhe: "macOS chỉ hỏi một lần, sau đó chỉ đổi được trong bảng của chính nó. Ở đây bạn xem cái gì đang có hiệu lực và xử lý cái còn thiếu.",
    concedida: "Đã cấp",
    negada: "Bị từ chối",
    naoPedida: "Chưa yêu cầu",
    permitir: "Cho phép",
    abrirAjustes: "Mở cài đặt",
    microfone: "Micrô",
    microfoneDetalhe: "Nói trong cuộc gọi và thử đầu vào của bạn.",
    camera: "Máy ảnh",
    cameraDetalhe: "Bật video trong cuộc gọi.",
    tela: "Ghi màn hình",
    telaDetalhe: "Chia sẻ màn hình và cửa sổ.",
    monitoramento: "Giám sát đầu vào",
    monitoramentoDetalhe: "Dùng nhấn-để-nói ngay cả khi Gravaê ở nền.",
  },
  jaConectado: {
    titulo: "Bạn đã ở trong cuộc gọi này rồi",
    trazer: "Mang cuộc gọi về đây",
    deixar: "Cứ để nguyên",
    detalhe: "Mang về đây thì đầu bên kia rời cuộc gọi — tài khoản của bạn chỉ ở một nơi mỗi lúc.",
  },
};
