export const comum = {
  carregando: "Đang tải…",
  salvar: "Lưu",
  salvando: "Đang lưu…",
  descartar: "Bỏ",
  redefinir: "Đặt lại",
  naoSalvo: "Bạn có thay đổi chưa lưu.",
  fechar: "Đóng",
  criar: "Tạo",
  nome: "Tên",
  emoji: "Biểu tượng cảm xúc",
  previa: "Xem trước",
  cancelar: "Hủy",
  enviar: "Gửi",
  apagar: "Xóa",
  excluir: "Xóa",
  remover: "Gỡ",
  trocar: "Đổi",
};
