export const configuracoes = {
  efeitos: {
    titulo: "Hiệu ứng con trỏ",
    detalhe: "Vệt và tia được vẽ đè lên ứng dụng. Ban đầu tắt, và tự tắt nếu bạn đã xin bớt chuyển động.",
    rastro: "Vệt con trỏ",
    rastroDetalhe: "Một đường đi theo con trỏ rồi nhạt dần phía sau.",
    faisca: "Tia khi bấm",
    faiscaDetalhe: "Những nét ngắn bắn ra từ chỗ bạn bấm.",
    cor: "Màu",
    espessura: "Độ dày",
    comprimento: "Độ dài",
    tamanho: "Cỡ",
    quantidade: "Số lượng",
  },
  email: {
    verificarTitulo: "Xác nhận email của bạn",
    verificarDetalhe: "Vài cộng đồng chỉ cho người đã xác nhận lên tiếng. Chỉ một cú nhấp.",
    enviar: "Gửi liên kết",
    enviado: "Xem hộp thư đến. Liên kết dùng được trong một ngày.",
    falhou: "Không gửi được email.",
    confirmado: "Đã xác nhận email",
    confirmadoDetalhe: "Xong rồi. Giờ bạn nhắn được ở mọi cộng đồng có yêu cầu này.",
    linkIncompleto: "Liên kết bị thiếu",
    linkIncompletoDetalhe: "Địa chỉ thiếu mã. Hãy mở liên kết thẳng từ email.",
    confirmando: "Đang xác nhận…",
    expirou: "Liên kết này đã dùng rồi hoặc đã hết hạn.",
    irParaOApp: "Vào ứng dụng",
  },
  tema: {
    indisponivel: "Không dùng được chủ đề này",
    indisponivelDetalhe: "Người đăng đã xoá, hoặc liên kết bị sai.",
    indisponivelLinha: "Không dùng được chủ đề này. Người đăng đã xoá, hoặc liên kết bị sai.",
    importar: "Nhập chủ đề",
    importarCurto: "Nhập",
    importarDetalhe: "Việc này thay thế chủ đề bạn đang dùng. Bạn có thể sửa sau ở Cài đặt > Giao diện > Xưởng chủ đề.",
    porAutor: "bởi {{autor}}",
    umaCorTrocada: "đổi 1 màu",
    coresTrocadas: "đổi {{quantas}} màu",
    avisoDeCss: "Chủ đề này mang theo CSS của người viết, mà CSS chạm tới mọi ngóc ngách của màn hình. Chỉ nhập từ người bạn tin tưởng.",
    soCores: "Chủ đề này chỉ đổi màu. Không có CSS từ bên ngoài.",
    aplicar: "Áp dụng",
    previaSemMotor: "Bản xem trước không chạy engine. Cài vào mới thấy được.",
    motorAnimado: "{{motor}} có hoạt ảnh",
  },
  sair: "Đăng xuất",
  versoes: {
    termos: "Điều khoản dịch vụ",
    privacidade: "Chính sách quyền riêng tư",
    copiar: "Nhấn để sao chép",
    copiado: "Đã sao chép",
  },
  telas: {
    conta: "Tài khoản của tôi",
    privacidade: "Quyền riêng tư",
    conexoes: "Kết nối",
    voz: "Âm thanh",
    video: "Video",
    avisos: "Thông báo",
    aplicativos: "Ứng dụng",
    aparencia: "Giao diện",
    batePapo: "Trò chuyện",
    acessibilidade: "Trợ năng",
    idioma: "Ngôn ngữ",
    aplicativo: "Tải ứng dụng",
    atalhos: "Phím tắt",
    desktop: "Ứng dụng máy tính",
    avancado: "Nâng cao",
    servidor: "Máy chủ",
    comunicado: "Thông báo hệ thống",
    denuncias: "Báo cáo",
    publicacoes: "Triển khai",
  },
  grupos: {
    conta: "Tài khoản",
    app: "Cài đặt ứng dụng",
    desenvolvedor: "Nhà phát triển",
    administracao: "Quản trị",
  },
  secoes: {
    detalhesDeLogin: "Thông tin đăng nhập",
    dispositivos: "Thiết bị",
    usuariosBloqueados: "Người dùng bị chặn",
    aplicativosAutorizados: "Ứng dụng đã ủy quyền",
    sessoes: "Phiên đăng nhập",
    amigosEDms: "Bạn bè và tin nhắn riêng",
    compartilhamentoDeAtividade: "Chia sẻ hoạt động",
    visibilidadeDoPerfil: "Hiển thị hồ sơ",
    exportarDados: "Xuất dữ liệu",
    exclusaoDeDados: "Xóa dữ liệu",
    tema: "Chủ đề",
    corDeDestaque: "Màu nhấn",
    interface: "Giao diện",
    listaDeCanais: "Danh sách kênh",
    zoomDoApp: "Mức thu phóng của ứng dụng",
    escalaDaFonte: "Cỡ chữ trong trò chuyện",
    modoStreamer: "Quyền riêng tư khi phát trực tiếp",
    cursores: "Con trỏ",
    movimento: "Chuyển động",
    textoEmVoz: "Chuyển văn bản thành giọng nói",
    teclado: "Bàn phím",
    formatoDaHora: "Định dạng giờ",
    idiomaDaInterface: "Ngôn ngữ giao diện",
    dispositivosDeVoz: "Thiết bị",
    testeDoMicrofone: "Kiểm tra micrô",
    modoDeEntrada: "Chế độ đầu vào",
    sensibilidade: "Độ nhạy đầu vào",
    qualidade: "Chất lượng",
    camera: "Máy ảnh",
    transmissao: "Phát trực tiếp",
    exibicao: "Hiển thị",
    entrada: "Nhập liệu",
    midia: "Đa phương tiện",
    geral: "Chung",
    preferenciaDeMencao: "Tùy chọn nhắc đến",
    sons: "Âm thanh",
  },
};
