export const configuracoes = {
  telas: {
    conta: "Tài khoản của tôi",
    privacidade: "Quyền riêng tư",
    conexoes: "Kết nối",
    voz: "Âm thanh",
    video: "Video",
    avisos: "Thông báo",
    aplicativos: "Ứng dụng",
    aparencia: "Giao diện",
    batePapo: "Trò chuyện",
    acessibilidade: "Trợ năng",
    idioma: "Ngôn ngữ",
    aplicativo: "Tải ứng dụng",
    servidor: "Máy chủ",
  },
  grupos: {
    conta: "Tài khoản",
    app: "Cài đặt ứng dụng",
    desenvolvedor: "Nhà phát triển",
    administracao: "Quản trị",
  },
  secoes: {
    detalhesDeLogin: "Thông tin đăng nhập",
    dispositivos: "Thiết bị",
    usuariosBloqueados: "Người dùng bị chặn",
    aplicativosAutorizados: "Ứng dụng đã ủy quyền",
    sessoes: "Phiên đăng nhập",
    amigosEDms: "Bạn bè và tin nhắn riêng",
    compartilhamentoDeAtividade: "Chia sẻ hoạt động",
    visibilidadeDoPerfil: "Hiển thị hồ sơ",
    exportarDados: "Xuất dữ liệu",
    exclusaoDeDados: "Xóa dữ liệu",
    tema: "Chủ đề",
    corDeDestaque: "Màu nhấn",
    interface: "Giao diện",
    listaDeCanais: "Danh sách kênh",
    zoomDoApp: "Mức thu phóng của ứng dụng",
    escalaDaFonte: "Cỡ chữ trong trò chuyện",
    modoStreamer: "Quyền riêng tư khi phát trực tiếp",
    movimento: "Chuyển động",
    textoEmVoz: "Chuyển văn bản thành giọng nói",
    teclado: "Bàn phím",
    formatoDaHora: "Định dạng giờ",
    idiomaDaInterface: "Ngôn ngữ giao diện",
    dispositivosDeVoz: "Thiết bị",
    testeDoMicrofone: "Kiểm tra micrô",
    modoDeEntrada: "Chế độ đầu vào",
    sensibilidade: "Độ nhạy đầu vào",
    qualidade: "Chất lượng",
    camera: "Máy ảnh",
    transmissao: "Phát trực tiếp",
    exibicao: "Hiển thị",
    entrada: "Nhập liệu",
    midia: "Đa phương tiện",
    geral: "Chung",
    preferenciaDeMencao: "Tùy chọn nhắc đến",
    sons: "Âm thanh",
  },
};
