export const conversa = {
  acenar: {
    ilustracao: "Một bàn tay nhỏ đang vẫy",
    botao: "Vẫy chào {{nome}}",
  },
  oficial: {
    titulo: "Kênh này chỉ dành cho thông báo chính thức.",
    detalhe: "Chúng tôi không bao giờ hỏi mật khẩu hay mã tài khoản của bạn.",
    saibaMais: "Tìm hiểu thêm",
  },
  topico: {
    abrir: "Xem mô tả kênh",
  },
  previaDoLink: {
    carregando: "Đang xem trong liên kết có gì…",
    destino: "Dẫn tới {{destino}}",
  },
  reacao: {
    carregando: "Đang xem ai đã thả {{emoji}}…",
    uma: "{{nome}} đã thả {{emoji}}",
    duas: "{{primeiro}} và {{segundo}} đã thả {{emoji}}",
    varias: "{{nomes}} và {{quantos}} người nữa đã thả {{emoji}}",
    dicaSuper: "Giữ để thả siêu cảm xúc",
  },
  recado: {
    gravar: "Ghi âm một lời nhắn",
    descartar: "Bỏ bản ghi",
    mandar: "Gửi bản ghi",
    semSuporte: "Trình duyệt này không ghi âm được.",
    semMicrofone: "Không truy cập được micro.",
  },
  lista: {
    carregando: "Đang tải tin nhắn…",
    carregandoMais: "Đang tải…",
    verMais: "Cuộn lên để xem thêm",
    semHistorico: "Không xem được lịch sử",
    semHistoricoDetalhe: "Vai trò của bạn không có quyền đọc lịch sử của #{{canal}}. Tin nhắn mới vẫn hiện ra khi bạn còn ở đây.",
    boasVindas: "Chào mừng đến #{{canal}}",
    boasVindasDetalhe: "Đây là khởi đầu của kênh #{{canal}}.",
  },
  data: {
    hoje: "Hôm nay",
    ontem: "Hôm qua",
    hojeAs: "hôm nay lúc {{hora}}",
    ontemAs: "hôm qua lúc {{hora}}",
  },
  digitando: {
    um: "{{nome}} đang nhập…",
    dois: "{{primeiro}} và {{segundo}} đang nhập…",
    varios: "{{quantidade}} người đang nhập…",
  },
  mensagem: {
    usou: "đã dùng",
    fixada: "đã ghim",
    editado: "(đã sửa)",
    ignorada: "Tin nhắn từ người bạn đang phớt lờ.",
    mostrar: "Hiện",
    escPara: "Esc để",
    cancelar: "huỷ",
    enterParaSalvar: "Enter để lưu",
    naoLidasDaqui: "Chưa đọc từ đây.",
    linkCopiado: "Đã sao chép liên kết.",
    idCopiado: "Đã sao chép ID.",
    naoDeuParaCopiar: "Trình duyệt của bạn không cho sao chép.",
    apagarTitulo: "Xoá tin nhắn?",
    apagarDescricao: "Tin nhắn sẽ biến mất với mọi người trong kênh và không khôi phục được.",
    apagarAcao: "Xoá",
    citacaoAnexo: "nhấn để xem tệp đính kèm",
    citacaoSumiu: "Tin nhắn gốc không còn ở đây nữa.",
    encaminhadaDe: "Chuyển tiếp từ",
    irParaOriginal: "Đến tin gốc",
    bloqueadas: "{{quantas}} tin nhắn bị chặn",
    mostrarBloqueadas: "Hiện",
    esconderBloqueadas: "Ẩn",
    reagirCom: "Bày tỏ bằng {{emoji}} — giữ để siêu bày tỏ",
    segureParaSuper: "{{emoji}} — giữ để siêu bày tỏ",
  },
  imagem: {
    copiarImagem: "Sao chép ảnh",
    baixarImagem: "Tải ảnh xuống",
    copiarLinkDaImagem: "Sao chép liên kết ảnh",
    abrirLinkDaImagem: "Mở liên kết ảnh",
    maisAcoes: "Thêm thao tác media",
    pesquisarImagem: "Tìm ảnh",
    copiarIdDoAnexo: "Sao chép ID tệp đính kèm",
    girarEsquerda: "Xoay trái",
    girarDireita: "Xoay phải",
    ajustar: "Vừa màn hình",
    ampliar: "Phóng to",
    reduzir: "Thu nhỏ",
    imagemCopiada: "Đã sao chép ảnh.",
    linkCopiado: "Đã sao chép liên kết.",
    idCopiado: "Đã sao chép ID.",
    naoDeuParaCopiar: "Không sao chép được ảnh.",
  },

  acoes: {
    reagir: "Bày tỏ",
    responder: "Trả lời",
    encaminhar: "Chuyển tiếp",
    favoritar: "Lưu tin nhắn",
    tirarDosFavoritos: "Bỏ khỏi mục đã lưu",
    marcarNaoLida: "Đánh dấu chưa đọc",
    copiarLink: "Sao chép liên kết tin nhắn",
    copiarId: "Sao chép ID tin nhắn",
    fixar: "Ghim tin nhắn",
    desafixar: "Bỏ ghim",
    editar: "Sửa",
    apagar: "Xoá",
    mais: "Thêm",
    adicionarReacao: "Thêm biểu cảm",
    superReagirCom: "Siêu bày tỏ bằng {{emoji}}",
    fixarMensagem: "Ghim tin nhắn",
    desafixarMensagem: "Bỏ ghim tin nhắn",
    editarMensagem: "Sửa tin nhắn",
    apagarMensagem: "Xoá tin nhắn",
    denunciarMensagem: "Báo cáo tin nhắn",
  },
  denuncia: {
    titulo: "Báo cáo tin nhắn",
    descricao: "Báo cáo được gửi đến đội Gravaê. Hãy kể điều gì đã xảy ra.",
    de: "Từ {{nome}}",
    semTexto: "(không có nội dung)",
    motivo: "Lý do",
    detalhes: "Chi tiết (tùy chọn)",
    enviar: "Gửi báo cáo",
    enviada: "Đã gửi báo cáo. Cảm ơn bạn.",
    motivos: {
      spam: "Spam hoặc quảng cáo",
      assedio: "Quấy rối hoặc thù ghét",
      conteudo: "Nội dung không phù hợp",
      golpe: "Lừa đảo",
      outro: "Khác",
    },
  },
  falha: {
    tentarDeNovo: "Thử lại",
    erro: "Chưa gửi được",
    semConexao: "Chưa gửi được — bạn không có kết nối",
    semAcesso: "Chưa gửi được — kênh này không còn trong tầm với của bạn",
    semPermissao: "Chưa gửi được — bạn không thể viết ở đây",
    castigo: "Chưa gửi được — bạn đang bị tạm khóa ở máy chủ này",
    modoLento: "Chưa gửi được — chế độ chậm chưa hết",
    depressa: "Chưa gửi được — bạn gửi quá nhanh",
    automod: "Chưa gửi được — AutoMod đã chặn",
    recusada: "Chưa gửi được — cuộc trò chuyện này không nhận trả lời",
    naoEntregue: "Không gửi được — người này không nhận tin nhắn từ bạn",
  },
  mencao: {
    cargo: "Nhắc đến vai trò",
    pessoa: "Nhắc đến",
    alguem: "ai đó",
    cargoSemNome: "vai trò",
    here: "Báo cho những người đang trực tuyến",
    everyone: "Báo cho cả máy chủ",
  },
  codigo: {
    copiar: "Sao chép",
    copiado: "Đã sao chép",
    copiarAria: "Sao chép mã",
    copiadoAria: "Đã sao chép mã",
    recolher: "Thu gọn",
    expandir: "Mở rộng",
    verInteiro: "Xem toàn bộ tệp",
    maisOpcoes: "Tùy chọn khác",
    baixar: "Tải xuống",
    recolherLinhas: "Thu gọn ({{linhas}} dòng)",
    expandirLinhas: "Mở rộng ({{linhas}} dòng)",
    mudarIdioma: "Đổi ngôn ngữ",
    procurarIdioma: "Tìm mã ngôn ngữ…",
    nenhumIdioma: "Không có ngôn ngữ nào.",
    quebrarTexto: "Ngắt dòng văn bản",
  },
  caixa: {
    escrever: "Nhắn trong #{{canal}}",
    escreverSemCanal: "Viết tin nhắn",
    semPermissao: "Bạn không có quyền gửi tin nhắn trong kênh này",
    solteParaAnexar: "Thả để đính kèm",
    longaTitulo: "Tin nhắn của bạn quá dài…",
    longaDescricao: "Bạn đã chạm giới hạn {{limite}} ký tự. Có thể gửi dưới dạng tệp.",
    enviarComoArquivo: "Gửi dưới dạng tệp",
    textoComoArquivo: "Gửi văn bản dưới dạng tệp",
    arquivoGrandeTitulo: "Tệp quá lớn",
    arquivoGrandeDescricao: "“{{arquivo}}” vượt giới hạn {{limite}} MB mỗi tệp.",
    respondendoPara: "Trả lời",
    vaiNotificar: "Người đó sẽ nhận được thông báo",
    naoVaiNotificar: "Người đó sẽ không nhận được thông báo",
    ligado: "bật",
    desligado: "tắt",
    pararDeResponder: "Bỏ trả lời",
    mais: "Thêm",
    enviarArquivo: "Gửi một tệp",
    criarEnquete: "Tạo bình chọn",
    expressoes: "Emoji, GIF và nhãn dán",
    enviar: "Gửi",
    aguardandoEnvio: "Đang chờ tải lên",
    modoLento: "Chế độ chậm đang bật ({{tempo}})",
    modoLentoDica: "Chế độ chậm đặt ở {{segundos}} giây. Hãy chờ trước khi gửi tin nhắn tiếp theo.",
  },
  anexos: {
    enviando: "Đang tải lên…",
    modificar: "Sửa {{arquivo}}",
    verPrevia: "Xem trước {{arquivo}}",
    excluirTitulo: "Xóa tệp đính kèm",
    excluirDescricao: "Xóa “{{arquivo}}”? Không thể hoàn tác và tệp sẽ biến khỏi tin nhắn này.",
    excluirAcao: "Xóa tệp đính kèm",
    excluirFalhou: "Không xóa được tệp đính kèm.",
    remover: "Bỏ {{arquivo}}",
    ver: "Xem {{arquivo}}",
    mostrarSpoiler: "Hiện tiết lộ: {{arquivo}}",
    spoiler: "tiết lộ",
    spoilerTitulo: "Tiết lộ",
    editarTitulo: "Sửa tệp đính kèm",
    nomeDoArquivo: "Tên tệp",
    descricao: "Mô tả văn bản thay thế",
    descricaoDica: "Mô tả nội dung này cho trình đọc màn hình",
    marcarSpoiler: "Đánh dấu là tiết lộ",
    cancelar: "Huỷ",
    salvar: "Lưu",
  },
  cartao: {
    tocador: "Trình phát",
    abrir: "Mở {{destino}}",
    tocar: "Phát {{titulo}}",
    video: "video",
    verImagem: "Xem ảnh",
  },
  enquete: {
    criar: "Tạo bình chọn",
    pergunta: "Câu hỏi",
    exemplo: "Hôm nay chơi gì đây?",
    respostas: "Câu trả lời",
    adicionarOpcao: "Thêm lựa chọn",
    removerOpcao: "Bỏ lựa chọn",
    varias: "Cho phép chọn nhiều đáp án",
    variasDetalhe: "Không bật thì bỏ phiếu cho một lựa chọn sẽ rút phiếu khỏi lựa chọn trước.",
    duracao: "Thời hạn",
    umaHora: "1 giờ",
    quatroHoras: "4 giờ",
    oitoHoras: "8 giờ",
    umDia: "1 ngày",
    tresDias: "3 ngày",
    umaSemana: "1 tuần",
    ateEncerrar: "Đến khi tôi tự đóng",
    titulo: "Bình chọn",
    encerrada: "Bình chọn đã đóng",
    variasRespostas: "Bình chọn — nhiều câu trả lời",
    umVoto: "{{quantidade}} phiếu",
    votos: "{{quantidade}} phiếu",
    umVotoNoTotal: "tổng cộng {{quantidade}} phiếu",
    votosNoTotal: "tổng cộng {{quantidade}} phiếu",
    encerraEm: "đóng vào {{quando}}",
    encerrarAgora: "Đóng ngay",
  },
  fixadas: {
    titulo: "Tin nhắn đã ghim",
    vazio: "Kênh này chưa có tin nhắn nào được ghim.",
    desafixar: "Bỏ ghim",
    anexo: "(tệp đính kèm)",
    enquete: "(bình chọn)",
    dicaRotulo: "MẸO:",
    dica: "ai có quyền “Quản lý tin nhắn” đều ghim được ngay từ trình đơn của tin nhắn.",
  },
  encaminhar: {
    titulo: "Chuyển tiếp tin nhắn",
    paraOnde: "Gửi tới đâu?",
    semTexto: "(tin nhắn không có chữ)",
    nenhumLugar: "Không có nơi nào tên như vậy.",
    canais: "Kênh",
    conversas: "Tin nhắn riêng",
  },
  expressoes: {
    gifs: "Ảnh GIF",
    buscarGifs: "Tìm trên Klipy",
    figurinha: "Nhãn dán",
    buscarFigurinha: "Tìm nhãn dán ưng ý",
    buscarEmoji: "Tìm emoji ưng ý",
    buscarReacao: "Tìm biểu cảm ưng ý",
    adicionarEmoji: "Thêm emoji",
    limparBusca: "Xóa nội dung tìm",
  },
  busca: {
    pesquisar: "Tìm kiếm",
    limpar: "Xóa tìm kiếm",
    filtros: "Bộ lọc tìm kiếm",
    escopo: {
      titulo: "Phạm vi tìm kiếm",
      servidor: "Cộng đồng hiện tại",
      canal: "Cuộc trò chuyện này",
      comunidades: "Tất cả cộng đồng",
      dms: "Chỉ tin nhắn riêng",
      tudo: "Tin nhắn riêng và cộng đồng",
    },
    fechar: "Đóng tìm kiếm",
    procurando: "Đang tìm…",
    resultado: "{{quantos}} kết quả",
    resultados: "{{quantos}} kết quả",
    nadaCom: "Không có gì với {{termo}} ở đây.",
    soOsQuePodeLer: "Tìm kiếm chỉ nhìn vào những kênh bạn được đọc.",
  },
  entrada: {
    semNome: "cuộc trò chuyện",
    anexo: "(tệp đính kèm)",
    titulo: "Hộp thư đến",
    naoLidas: "Chưa đọc",
    salvas: "Đã lưu",
    mencoes: "Nhắc tên",
    fimTitulo: "Bạn đã tới cuối",
    fimDetalhe: "Không còn gì để đọc. Khi có tin nhắn mới, nó sẽ hiện ở đây.",
    semSalvosTitulo: "Chưa lưu gì cả",
    semSalvosDetalhe: "Giữ Shift và bấm vào dấu trang của một tin nhắn để giữ lại và đọc sau.",
    tirarDosSalvos: "Bỏ khỏi mục đã lưu",
    semMencoesTitulo: "Chưa có lượt nhắc nào",
    semMencoesDetalhe: "Những lượt nhắc tên bạn hiện ở đây trong 7 ngày gần nhất.",
  },
  forum: {
    descricao: "Mỗi chủ đề thành một cuộc trò chuyện riêng — hợp với câu hỏi không được để lạc giữa cuộc tán gẫu.",
    novoAssunto: "Chủ đề mới",
    vazio: "Chưa có chủ đề nào. Mở cái đầu tiên và cuộc trò chuyện gọn gàng ngay từ đầu.",
    titulo: "Tiêu đề",
    doQueSeTrata: "Về chuyện gì?",
    primeiraMensagem: "Tin nhắn đầu tiên",
    conteDoCaso: "Kể đi",
  },
};
