export const conversa = {
  lista: {
    carregando: "Đang tải tin nhắn…",
    carregandoMais: "Đang tải…",
    verMais: "Cuộn lên để xem thêm",
    semHistorico: "Không xem được lịch sử",
    semHistoricoDetalhe: "Vai trò của bạn không có quyền đọc lịch sử của #{{canal}}. Tin nhắn mới vẫn hiện ra khi bạn còn ở đây.",
    boasVindas: "Chào mừng đến #{{canal}}",
    boasVindasDetalhe: "Đây là khởi đầu của kênh #{{canal}}.",
  },
  data: {
    hoje: "Hôm nay",
    ontem: "Hôm qua",
    hojeAs: "hôm nay lúc {{hora}}",
    ontemAs: "hôm qua lúc {{hora}}",
  },
  digitando: {
    um: "{{nome}} đang nhập…",
    dois: "{{primeiro}} và {{segundo}} đang nhập…",
    varios: "{{quantidade}} người đang nhập…",
  },
  mensagem: {
    usou: "đã dùng",
    fixada: "đã ghim",
    editado: "(đã sửa)",
    ignorada: "Tin nhắn từ người bạn đang phớt lờ.",
    mostrar: "Hiện",
    escPara: "Esc để",
    cancelar: "huỷ",
    enterParaSalvar: "Enter để lưu",
    falhou: "Chưa gửi được. Thử lại",
    naoLidasDaqui: "Chưa đọc từ đây.",
    linkCopiado: "Đã sao chép liên kết.",
    idCopiado: "Đã sao chép ID.",
    naoDeuParaCopiar: "Trình duyệt của bạn không cho sao chép.",
    apagarTitulo: "Xoá tin nhắn?",
    apagarDescricao: "Tin nhắn sẽ biến mất với mọi người trong kênh và không khôi phục được.",
    apagarAcao: "Xoá",
    citacaoAnexo: "nhấn để xem tệp đính kèm",
    citacaoSumiu: "Tin nhắn gốc không còn ở đây nữa.",
    reagirCom: "Bày tỏ bằng {{emoji}} — giữ để siêu bày tỏ",
    segureParaSuper: "{{emoji}} — giữ để siêu bày tỏ",
  },
  acoes: {
    reagir: "Bày tỏ",
    responder: "Trả lời",
    encaminhar: "Chuyển tiếp",
    favoritar: "Lưu tin nhắn",
    tirarDosFavoritos: "Bỏ khỏi mục đã lưu",
    marcarNaoLida: "Đánh dấu chưa đọc",
    copiarLink: "Sao chép liên kết tin nhắn",
    copiarId: "Sao chép ID tin nhắn",
    fixar: "Ghim tin nhắn",
    desafixar: "Bỏ ghim",
    editar: "Sửa",
    apagar: "Xoá",
    mais: "Thêm",
    adicionarReacao: "Thêm biểu cảm",
    superReagirCom: "Siêu bày tỏ bằng {{emoji}}",
    fixarMensagem: "Ghim tin nhắn",
    desafixarMensagem: "Bỏ ghim tin nhắn",
    editarMensagem: "Sửa tin nhắn",
    apagarMensagem: "Xoá tin nhắn",
  },
  mencao: {
    cargo: "Nhắc đến vai trò",
    pessoa: "Nhắc đến",
    alguem: "ai đó",
    cargoSemNome: "vai trò",
    here: "Báo cho những người đang trực tuyến",
    everyone: "Báo cho cả máy chủ",
  },
  codigo: {
    copiar: "Sao chép",
    copiado: "Đã sao chép",
    copiarAria: "Sao chép mã",
    copiadoAria: "Đã sao chép mã",
    recolher: "Thu gọn",
    expandir: "Mở rộng",
    verInteiro: "Xem toàn bộ tệp",
    maisOpcoes: "Tùy chọn khác",
    baixar: "Tải xuống",
    recolherLinhas: "Thu gọn ({{linhas}} dòng)",
    expandirLinhas: "Mở rộng ({{linhas}} dòng)",
    mudarIdioma: "Đổi ngôn ngữ",
    procurarIdioma: "Tìm mã ngôn ngữ…",
    nenhumIdioma: "Không có ngôn ngữ nào.",
    quebrarTexto: "Ngắt dòng văn bản",
  },
  caixa: {
    escrever: "Nhắn trong #{{canal}}",
    escreverSemCanal: "Viết tin nhắn",
    semPermissao: "Bạn không có quyền gửi tin nhắn trong kênh này",
    solteParaAnexar: "Thả để đính kèm",
    longaTitulo: "Tin nhắn của bạn quá dài…",
    longaDescricao: "Bạn đã chạm giới hạn {{limite}} ký tự. Có thể gửi dưới dạng tệp.",
    enviarComoArquivo: "Gửi dưới dạng tệp",
    textoComoArquivo: "Gửi văn bản dưới dạng tệp",
    arquivoGrandeTitulo: "Tệp quá lớn",
    arquivoGrandeDescricao: "“{{arquivo}}” vượt giới hạn {{limite}} MB mỗi tệp.",
    respondendoPara: "Trả lời",
    vaiNotificar: "Người đó sẽ nhận được thông báo",
    naoVaiNotificar: "Người đó sẽ không nhận được thông báo",
    ligado: "bật",
    desligado: "tắt",
    pararDeResponder: "Bỏ trả lời",
    mais: "Thêm",
    enviarArquivo: "Gửi một tệp",
    criarEnquete: "Tạo bình chọn",
    expressoes: "Emoji, GIF và nhãn dán",
    enviar: "Gửi",
    aguardandoEnvio: "Đang chờ tải lên",
    modoLento: "Chế độ chậm đang bật ({{tempo}})",
    modoLentoDica: "Chế độ chậm đặt ở {{segundos}} giây. Hãy chờ trước khi gửi tin nhắn tiếp theo.",
  },
  anexos: {
    enviando: "Đang tải lên…",
    modificar: "Sửa {{arquivo}}",
    remover: "Bỏ {{arquivo}}",
    ver: "Xem {{arquivo}}",
    mostrarSpoiler: "Hiện tiết lộ: {{arquivo}}",
    spoiler: "tiết lộ",
    spoilerTitulo: "Tiết lộ",
    editarTitulo: "Sửa tệp đính kèm",
    nomeDoArquivo: "Tên tệp",
    descricao: "Mô tả văn bản thay thế",
    descricaoDica: "Mô tả nội dung này cho trình đọc màn hình",
    marcarSpoiler: "Đánh dấu là tiết lộ",
    cancelar: "Huỷ",
    salvar: "Lưu",
  },
  cartao: {
    tocador: "Trình phát",
    abrir: "Mở {{destino}}",
    tocar: "Phát {{titulo}}",
    video: "video",
    verImagem: "Xem ảnh",
  },
  enquete: {
    titulo: "Bình chọn",
    encerrada: "Bình chọn đã đóng",
    variasRespostas: "Bình chọn — nhiều câu trả lời",
    umVoto: "{{quantidade}} phiếu",
    votos: "{{quantidade}} phiếu",
    umVotoNoTotal: "tổng cộng {{quantidade}} phiếu",
    votosNoTotal: "tổng cộng {{quantidade}} phiếu",
    encerraEm: "đóng vào {{quando}}",
    encerrarAgora: "Đóng ngay",
  },
  fixadas: {
    titulo: "Tin nhắn đã ghim",
    vazio: "Kênh này chưa có tin nhắn nào được ghim.",
    desafixar: "Bỏ ghim",
    anexo: "(tệp đính kèm)",
    enquete: "(bình chọn)",
    dicaRotulo: "MẸO:",
    dica: "ai có quyền “Quản lý tin nhắn” đều ghim được ngay từ trình đơn của tin nhắn.",
  },
  encaminhar: {
    titulo: "Chuyển tiếp tin nhắn",
    paraOnde: "Gửi tới đâu?",
    semTexto: "(tin nhắn không có chữ)",
    nenhumLugar: "Không có nơi nào tên như vậy.",
    canais: "Kênh",
    conversas: "Tin nhắn riêng",
  },
  expressoes: {
    gifs: "Ảnh GIF",
    buscarGifs: "Tìm trên Klipy",
    figurinha: "Nhãn dán",
    buscarFigurinha: "Tìm nhãn dán ưng ý",
    buscarEmoji: "Tìm emoji ưng ý",
    buscarReacao: "Tìm biểu cảm ưng ý",
    adicionarEmoji: "Thêm emoji",
    limparBusca: "Xóa nội dung tìm",
  },
  busca: {
    fechar: "Đóng tìm kiếm",
    procurando: "Đang tìm…",
    resultado: "{{quantos}} kết quả",
    resultados: "{{quantos}} kết quả",
    nadaCom: "Không có gì với {{termo}} ở đây.",
    soOsQuePodeLer: "Tìm kiếm chỉ nhìn vào những kênh bạn được đọc.",
  },
  entrada: {
    titulo: "Hộp thư đến",
    naoLidas: "Chưa đọc",
    salvas: "Đã lưu",
    mencoes: "Nhắc tên",
    fimTitulo: "Bạn đã tới cuối",
    fimDetalhe: "Không còn gì để đọc. Khi có tin nhắn mới, nó sẽ hiện ở đây.",
    semSalvosTitulo: "Chưa lưu gì cả",
    semSalvosDetalhe: "Giữ Shift và bấm vào dấu trang của một tin nhắn để giữ lại và đọc sau.",
    tirarDosSalvos: "Bỏ khỏi mục đã lưu",
    semMencoesTitulo: "Chưa có lượt nhắc nào",
    semMencoesDetalhe: "Những lượt nhắc tên bạn hiện ở đây trong 7 ngày gần nhất.",
  },
  forum: {
    descricao: "Mỗi chủ đề thành một cuộc trò chuyện riêng — hợp với câu hỏi không được để lạc giữa cuộc tán gẫu.",
    novoAssunto: "Chủ đề mới",
    vazio: "Chưa có chủ đề nào. Mở cái đầu tiên và cuộc trò chuyện gọn gàng ngay từ đầu.",
    titulo: "Tiêu đề",
    doQueSeTrata: "Về chuyện gì?",
    primeiraMensagem: "Tin nhắn đầu tiên",
    conteDoCaso: "Kể đi",
  },
};
