export const perfil = {
  carregando: "Đang tải…",
  editar: "Sửa hồ sơ",
  mensagem: "Nhắn tin",
  abrirConversa: "Mở cuộc trò chuyện",
  verCompleto: "Xem hồ sơ đầy đủ",
  convidarParaServidor: "Mời vào máy chủ",
  semServidores: "Bạn chưa có máy chủ nào",
  conviteEnviado: "Đã gửi lời mời tới {{nome}}.",
  moderador: "Mở ở chế độ kiểm duyệt",
  mais: "Thêm",
  ignorar: "Phớt lờ",
  deixarDeIgnorar: "Bỏ phớt lờ",
  copiarId: "Sao chép ID người dùng",
  idCopiado: "Đã sao chép ID.",
  conexoes: "Kết nối",
  membroDesde: "Thành viên từ",
  sobre: "Giới thiệu",
  cargosTitulo: "Vai trò",
  visaoGeral: "Tổng quan",
  amigosEmComum: "Bạn chung ({{quantidade}})",
  servidoresEmComum: "Máy chủ chung ({{quantidade}})",
  amizade: {
    amigo: "Bạn bè",
    pedidoEnviado: "Đã gửi lời mời kết bạn",
    respondaAbaixo: "Đã gửi cho bạn lời mời — trả lời bên dưới",
    adicionar: "Thêm bạn",
    teMandouPedido: "Đã gửi cho bạn lời mời kết bạn",
    aceitar: "Chấp nhận",
    desfazer: "Huỷ kết bạn",
    desfazerTitulo: "Xoá {{nome}} khỏi danh sách bạn bè?",
    desfazerDescricao: "Hai bạn sẽ không còn là bạn bè. Cuộc trò chuyện riêng vẫn nằm trong lịch sử, và sau này bạn có thể thêm lại.",
    bloquear: "Chặn",
    bloquearTitulo: "Chặn {{nome}}?",
    bloquearDescricao: "Hai bạn sẽ không còn là bạn bè, cuộc trò chuyện riêng ngừng nhận tin nhắn, và người đó không thể gửi lời mời kết bạn cho bạn nữa.",
    linkCopiado: "Hai bạn không phải bạn bè — liên kết đã được sao chép để bạn tự gửi.",
  },
  recado: {
    escrever: "Nhắn cho @{{usuario}}",
    enviar: "Gửi",
    enviada: "Đã gửi tin nhắn",
    falhou: "Không gửi được. Thử từ cuộc trò chuyện.",
  },
  cartao: {
    trocarFaixa: "Đổi ảnh bìa của thẻ",
    trocarFaixaCurto: "Đổi ảnh bìa",
    trocarFoto: "Đổi ảnh đại diện",
    trocarFotoCurto: "Đổi ảnh",
    suaEtiqueta: "Nhãn của bạn",
    editarEtiqueta: "Nhấn để sửa nhãn của bạn",
    conteAlgo: "Kể gì đó về bạn đi",
    adicionarStatus: "Thêm trạng thái",
    adicionarDescricao: "Nhấn để thêm mô tả",
    cargo: "Vai trò",
    cargos: "Vai trò",
    cargosCom: "Vai trò — {{quantidade}}",
    tirarCargo: "Bỏ vai trò {{cargo}}",
  },
  cargos: {
    adicionar: "Thêm vai trò",
    procurar: "Tìm vai trò",
  },
  etiqueta: {
    escolher: "Chọn nhãn máy chủ",
    nenhuma: "Không có nhãn máy chủ",
    semEtiqueta: "Không máy chủ nào của bạn có nhãn",
  },
  emblemas: {
    doServidor: "Huy hiệu của máy chủ này",
    limite: "Bạn có thể đeo tối đa {{quantidade}} huy hiệu.",
  },
  nota: {
    vazia: "Nhấn để ghi lại điều gì đó",
    rotulo: "Ghi chú (chỉ mình bạn thấy)",
  },
  status: {
    titulo: "Trạng thái",
    definir: "Đặt trạng thái của bạn",
    escolherEmoji: "Chọn emoji",
    tirarEmoji: "Bỏ emoji",
    oQuePensa: "Bạn đang nghĩ gì?",
    limparAgora: "Xoá trạng thái ngay",
    naoLimpar: "Không xoá",
    limpar30m: "Xoá sau 30 phút",
    limpar1h: "Xoá sau 1 giờ",
    limpar4h: "Xoá sau 4 giờ",
    limparHoje: "Xoá hôm nay",
    limparAmanha: "Xoá ngày mai",
    comHora: "{{prazo}} lúc {{hora}}",
  },
  presenca: {
    disponivel: "Đang hoạt động",
    ausente: "Vắng mặt",
    naoPerturbar: "Đừng làm phiền",
    naoPerturbarDetalhe: "Bạn không nhận thông báo tin nhắn mới",
    invisivel: "Ẩn danh",
    invisivelDetalhe: "Người khác thấy bạn ngoại tuyến",
  },
  menu: {
    mudarDeConta: "Đổi tài khoản",
    gerenciarContas: "Quản lý tài khoản",
  },
  editor: {
    decoracao: "Đổi trang trí ảnh đại diện",
    naoSalvo: "Đừng quên lưu thay đổi của bạn!",
    principal: "Hồ sơ chính",
  },
};
