export const servidor = {
  comunidade: {
    ativa: "Cộng đồng đã mở",
    ativaDesde: "Mở từ {{quando}}",
    membrosAgora: "{{quantos}} thành viên",
    criarParaMim: "Tạo giúp tôi một cái",
    canalDeRegras: "Kênh nội quy",
    canalDeRegrasDetalhe: "Nơi đặt nội quy mà ai cũng đọc trước khi lên tiếng.",
    canalDeAvisos: "Kênh thông báo của cộng đồng",
    canalDeAvisosDetalhe: "Nơi chúng tôi gửi những gì thay đổi ở đây, chỉ dành cho người quản lý.",
    canalDeSeguranca: "Kênh cảnh báo an toàn",
    canalDeSegurancaDetalhe: "Nơi ban điều hành nhận những gì bộ lọc bắt được.",
    idiomaPrincipal: "Ngôn ngữ chính",
    idiomaPrincipalDetalhe: "Ngôn ngữ mà phần lớn cuộc trò chuyện diễn ra.",
    semIdioma: "Chưa chọn ngôn ngữ",
    semCanal: "Không có kênh",
    finalTitulo: "Sắp xong rồi",
    finalDetalhe: "Trước khi mở, hãy xem điều gì đổi khác với người mới vào.",
    confereRegras: "Ai vào cũng thấy kênh nội quy trước tiên.",
    confereEveryone: "Chỉ người có vai trò mới dùng @everyone và @here.",
    confereMencoes: "Nhắc cả nhà cùng lúc từ nay phải xin phép.",
    concordo: "Tôi đồng ý và đã hiểu",
    concordoDetalhe: "Bạn xác nhận cộng đồng này theo đúng nguyên tắc của chúng tôi.",
    proximo: "Tiếp",
    terminar: "Kết thúc thiết lập",
    visaoGeral: "Nhìn chung",
    visaoGeralDetalhe: "Những kênh mà cộng đồng dùng để nói với người mới.",
    seguranca: "An toàn",
    segurancaDetalhe: "Những cái phanh giữ lại spam và nội dung nặng.",
    habilitada: "Đã bật cộng đồng.",
    falhou: "Không bật được cộng đồng.",
    titulo: "Cộng đồng",
    ilustracao: "Bong bóng thoại",
    convite: "Bạn đang gây dựng một cộng đồng?",
    conviteDetalhe: "Biến nó thành cộng đồng để có bộ công cụ của một nơi lớn: kênh nội quy, thông báo từ chúng tôi, và bộ lọc tự trông chừng.",
    contagem: "{{membros}} trên {{minimo}} thành viên",
    faltam: "Còn thiếu {{quantos}} nữa là mở được.",
    prontoParaAbrir: "Mở được rồi.",
    habilitar: "Bật cộng đồng",
    vantagemCrescer: "Lớn lên",
    vantagemCrescerDetalhe: "Cộng đồng có thể xin vào mục Khám phá, ai tìm chủ đề đó sẽ thấy bạn.",
    vantagemModerar: "Trông chừng",
    vantagemModerarDetalhe: "Bắt buộc email đã xác minh, lọc nội dung và bật AutoMod cùng lúc.",
    vantagemAvisos: "Nắm tin",
    vantagemAvisosDetalhe: "Chúng tôi gửi những thay đổi tới người quản lý, trong một kênh của riêng bạn.",
    assistenteTitulo: "Cùng dựng cộng đồng của bạn nào.",
    passoSeguranca: "Kiểm tra an toàn",
    passoBasico: "Chuẩn bị cơ bản",
    passoFinal: "Hoàn thiện",
    seguraTitulo: "Giữ cộng đồng an toàn",
    seguraDetalhe: "Cộng đồng lớn hay hút spam. Hai cái phanh này bật sẵn, và bạn tắt sau nếu thấy vướng.",
    emailVerificado: "Bắt buộc email đã xác minh",
    emailVerificadoDetalhe: "Ai chưa xác minh email thì chưa nhắn được. Người có vai trò đi thẳng.",
    filtroDeMidia: "Lọc nội dung nhạy cảm",
    filtroDeMidiaDetalhe: "Ảnh và video tới trong trạng thái che đi, chỉ hiện ra khi có người chọn xem.",
    basicoTitulo: "Chuẩn bị phần nền",
    basicoDetalhe: "Cho biết nội quy nằm ở kênh nào và thông báo của chúng tôi đi đâu. Không chọn thì tôi tạo cả hai.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} lệnh",
    previa: "Thẻ trông thế nào",
    trocarIcone: "Đổi biểu tượng",
    tirarCapa: "Bỏ ảnh bìa",
    heroComunidades: "Có người đang nói về đúng thứ bạn thích",
    heroComunidadesDetalhe: "Cộng đồng do chính người ở đây mở ra. Ghé vào, đọc câu chuyện, thấy hợp thì ở lại.",
    emDestaque: "Nổi bật",
    todasAsComunidades: "Số còn lại",
    heroTitulo: "Hôm nay nhóm bạn sẽ dùng gì?",
    heroDetalhe: "Bot cho âm nhạc, trò chơi và trông chừng, do chính những người ở đây làm ra. Chọn một cái, nó vào máy chủ của bạn.",
    novidades: "Vừa mới tới",
    todosOsApps: "Số còn lại",
    lojaTitulo: "Trang của ứng dụng",
    lojaDetalhe: "Đây là những gì hiện ra ở mục Khám phá với người chưa biết tới nó.",
    capa: "Ảnh bìa",
    capaDetalhe: "Ảnh rộng ở đầu trang. Cỡ 1280 × 720 là vừa.",
    trocarCapa: "Đổi ảnh bìa",
    categorias: "Danh mục",
    categoriasDetalhe: "Tối đa {{quantas}}. Người ta lướt mục Khám phá theo những cái này.",
    idiomas: "Ngôn ngữ",
    idiomasDetalhe: "Tối đa {{quantos}}. Ứng dụng trả lời bằng những ngôn ngữ nào.",
    termos: "Điều khoản sử dụng",
    politica: "Chính sách riêng tư",
    politicas: "Chính sách",
    servidorDeSuporte: "Máy chủ hỗ trợ",
    servidorDeSuporteDetalhe: "Nơi ai cần giúp về ứng dụng sẽ tìm đến.",
    semServidor: "Không có",
    emQuantosServidores: "Có mặt ở bao nhiêu máy chủ",
    categoria: {
      GAMES: "Trò chơi",
      MUSICA: "Âm nhạc",
      MODERACAO: "Trông chừng",
      PRODUTIVIDADE: "Năng suất",
      SOCIAL: "Xã hội",
      UTILIDADES: "Tiện ích",
      ARTE_E_CRIACAO: "Nghệ thuật và sáng tạo",
      EDUCACAO: "Học tập",
      OUTRA: "Khác",
    },
    appIndisponivel: "Không dùng được ứng dụng này",
    voltarParaExplorar: "Về lại Khám phá",
    adicionarApp: "Thêm ứng dụng",
    copiarLink: "Sao chép liên kết",
    denunciarApp: "Báo cáo ứng dụng",
    copiarIdDoApp: "Sao chép ID ứng dụng",
    visaoGeral: "Tổng quan",
    comandos: "Lệnh",
    permissoes: "Quyền",
    semPermissoes: "Ứng dụng này không xin quyền nào.",
    avisoDePermissoes: "Nó vào với vai trò riêng. Bạn có thể đổi các quyền này sau, ở Cài đặt cộng đồng → Vai trò.",
    servidoresEmComum: "Cộng đồng chung",
    umServidorEmComum: "1 cộng đồng",
    quantosServidoresEmComum: "{{quantos}} cộng đồng",
    feitoPor: "Người làm",
    publicadoEm: "Đăng ngày",
    denunciarNome: "Báo cáo {{nome}}",
    denunciaDetalhe: "Báo cáo được gửi tới đội Gravaê. Người làm ứng dụng sẽ không biết là bạn.",
    denunciaFalhou: "Không gửi được báo cáo.",
    umMembro: "1 thành viên",
    semDescricao: "Không có mô tả.",
    adicionar: "Thêm",
    jaEstaAqui: "Bạn đã ở đây rồi",
    entrando: "Đang vào…",
    entrar: "Tham gia",
    comunidadePublica: "Cộng đồng công khai",
    online: "{{quantos}} trực tuyến",
    membros: "{{quantos}} thành viên",
    abrirComunidade: "Mở cộng đồng",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Cài đặt máy chủ",
  novasMensagens: "Tin nhắn mới",
  menu: {
    silenciar: "Tắt tiếng cộng đồng",
    reativar: "Bật tiếng cộng đồng",
    porQuinze: "Trong 15 phút",
    porMeiaHora: "Trong 30 phút",
    porTresHoras: "Trong 3 giờ",
    porTresDias: "Trong 3 ngày",
    porUmaHora: "Trong 1 giờ",
    porOitoHoras: "Trong 8 giờ",
    porUmDia: "Trong 24 giờ",
    ateReativar: "Cho đến khi tôi bật lại",
    notificacoes: "Cài đặt thông báo",
    padrao: "Theo mặc định",
    todas: "Tất cả tin nhắn",
    soMencoes: "Chỉ khi được nhắc",
    nada: "Không",
    ocultarSilenciados: "Ẩn kênh đã tắt tiếng",
    denunciar: "Báo cáo cộng đồng",
    marcarLida: "Đánh dấu đã đọc",
    convidar: "Mời thành viên",
    editarPerfil: "Chỉnh sửa hồ sơ cộng đồng",
    configuracoes: "Cài đặt cộng đồng",
    sair: "Rời cộng đồng",
    sairTitulo: "Rời {{nome}}?",
    sairDescricao: "Bạn sẽ cần lời mời mới để quay lại.",
    copiarId: "Sao chép ID cộng đồng",
    idCopiado: "Đã sao chép ID.",
  },
  convite: {
    cartaoTitulo: "Bạn được mời vào một cộng đồng",
    indisponivel: "Không dùng được lời mời này",
    indisponivelDetalhe: "Nó đã hết hạn, hết lượt, hoặc người tạo đã xoá.",
    entrar: "Vào cộng đồng",
    chamado: "Bạn được mời tham gia",
    aceitarComo: "Chấp nhận với tên {{nome}}",
    abrir: "Mở cộng đồng",
    recusar: "Không, cảm ơn",
  },
  pasta: {
    silenciarTodas: "Tắt tiếng cộng đồng",
    reativarTodas: "Bật tiếng cộng đồng",
    mostrarSilenciados: "Hiện kênh đã tắt tiếng",
    notificacoesDaComunidade: "Cài đặt thông báo",
    silenciarEveryone: "Tắt tiếng @everyone và @here",
    permitirEveryone: "Cho phép @everyone và @here",
    silenciarCargos: "Tắt tiếng nhắc vai trò",
    permitirCargos: "Cho phép nhắc vai trò",
    dicaDaCor: "Nhập màu (hex, rgb(), hsl() hoặc tên) hoặc dùng bộ chọn.",
    mostrarIcone: "Hiện biểu tượng khi đóng",
    dicaDoIcone: "Khi đóng, hiện biểu tượng thay cho các máy chủ bên trong.",
    icone: "Biểu tượng thư mục",
    excluir: "Xóa thư mục",
    icones: {
      pasta: "Thư mục",
      estrela: "Yêu thích",
      coracao: "Trái tim",
      salvar: "Lưu",
      jogo: "Tay cầm chơi game",
      escudo: "Khiên",
      nota: "Nốt nhạc",
    },
    marcarLida: "Đánh dấu thư mục đã đọc",
    configuracoes: "Cài đặt thư mục",
    desfazer: "Bỏ nhóm thư mục",
    titulo: "Thư mục",
    nome: "Tên",
    semNome: "Không tên",
    cor: "Màu",
    semCor: "Không màu",
    salvar: "Lưu",
  },
  denuncia: {
    titulo: "Báo cáo {{nome}}",
    descricao: "Báo cáo được gửi đến đội Gravaê. Hãy kể điều gì đã xảy ra.",
    motivo: "Lý do",
    detalhes: "Chi tiết (tùy chọn)",
    enviar: "Gửi báo cáo",
    enviada: "Đã gửi báo cáo. Cảm ơn bạn.",
    motivos: {
      spam: "Spam hoặc quảng cáo",
      assedio: "Quấy rối hoặc thù ghét",
      conteudo: "Nội dung không phù hợp",
      golpe: "Lừa đảo",
      outro: "Khác",
    },
  },
  selos: {
    verificada: "Cộng đồng đã xác minh",
    detectavel: "Cộng đồng có thể khám phá",
  },
  auditoria: {
    todasAsAcoes: "Mọi hành động",
    todosOsUsuarios: "Mọi người dùng",
    filtroMembros: "Thành viên",
    filtroCanais: "Kênh",
    filtroEmojis: "Emoji",
    filtroServidor: "Máy chủ",
    titulo: "Nhật ký hoạt động",
    porUsuario: "Lọc theo người",
    porAcao: "Lọc theo hành động",
    vazio: "Chưa có gì được ghi lại với bộ lọc này.",
    motivo: "Lý do:",
  },
  banimentos: {
    titulo: "Danh sách cấm của máy chủ",
    descricao: "Ai ở đây thì không vào lại được, kể cả có lời mời mới. Bỏ cấm là trả lại quyền vào ngay.",
    procurar: "Tìm lệnh cấm theo tên người dùng",
    vazioTitulo: "Không có ai bị cấm",
    vazio: "Bạn chưa cấm ai… nhưng nếu có lúc cần, đừng ngần ngại.",
    desbanir: "Bỏ cấm",
  },
  excluir: {
    tudoVai: "Mọi kênh, tin nhắn và lời mời của {{servidor}} sẽ bị xóa với {{membros}} thành viên. Sau đó không ai lấy lại được.",
    digite: "Gõ {{servidor}} để xác nhận",
    titulo: "Xóa máy chủ",
    aviso: "Việc này không thể hoàn tác.",
  },
  emblemas: {
    apagarDescricao: "Nó rời khỏi tất cả những ai đang đeo. Không thể hoàn tác.",
    titulo: "Huy hiệu",
    vazio: "Chưa có huy hiệu nào.",
    novo: "Huy hiệu mới",
  },
  convites: {
    revogarTitulo: "Thu hồi lời mời?",
    revogarAcao: "Thu hồi",
    revogarDescricao: "Liên kết {{codigo}} ngừng hoạt động ngay. Ai đã vào bằng nó thì vẫn ở lại máy chủ.",
    titulo: "Lời mời",
    descricao: "Tất cả liên kết mời đang hoạt động của máy chủ này.",
    vazio: "Chưa tạo lời mời nào.",
    revogar: "Thu hồi lời mời",
  },
  integracoes: {
    opcionais: "username và avatar_url là tùy chọn và áp dụng cho từng tin nhắn. Giới hạn là 5 tin nhắn mỗi 5 giây.",
    apagarDescricao: "URL ngừng hoạt động ngay. Những tin nhắn nó đã gửi vẫn ở trong kênh.",
    titulo: "Tích hợp",
    descricao: "Webhook là một địa chỉ đăng bài vào kênh mà không cần tài khoản. Tiện để báo khi bản dựng chạy xong, khi ai đó mở phiếu, hay bất cứ thứ gì bạn muốn gửi từ một script.",
    novo: "Webhook mới",
    vazio: "Chưa có webhook nào. Tạo một cái và dán URL vào nơi bạn muốn tin nhắn đi ra.",
    canal: "Kênh",
    apagar: "Xóa webhook",
    comoUsar: "Cách dùng",
    comoUsarTexto: "Gửi một POST kèm JSON:",
  },
  explorar: {
    titulo: "Khám phá",
  },
  engajamento: {
    semCanal: "Không có kênh hệ thống",
    titulo: "Sức sống",
    descricao: "Những gì máy chủ tự làm để không trông trống trải khi có người mới đến.",
    sistema: "Tin nhắn hệ thống",
    boasVindas: "Gửi lời chào khi có người tham gia",
    sorteio: "Không có chữ của bạn ở dưới thì câu sẽ được bốc ngẫu nhiên — cùng một câu mãi thì mau chán.",
    canalDoSistema: "Kênh tin nhắn hệ thống",
    mensagem: "Lời chào mừng",
    deixeVazio: "Để trống để bốc trong những câu có sẵn",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Bộ lọc tự kiểm duyệt, trước cả khi tin nhắn tồn tại. Người quản trị máy chủ không bao giờ bị lọc — và các vai trò được miễn thì đi thẳng qua.",
    palavras: {
      titulo: "Chặn từ của bạn",
      descricao: "Danh sách từ mà không ai được viết.",
    },
    mencoes: {
      titulo: "Chặn spam nhắc tên",
      descricao: "Chặn tin nhắn có quá nhiều lượt nhắc tên cùng lúc.",
    },
    links: {
      titulo: "Chặn liên kết",
      descricao: "Giữ lại mọi địa chỉ dán vào khung chat.",
    },
    definir: "Thiết lập",
    nomeDaRegra: "Tên quy tắc",
    bloqueadas: "Từ bị chặn",
    digiteEnter: "Gõ rồi nhấn Enter",
    comparacao: "Việc so khớp bỏ qua chữ hoa, dấu và dấu câu — và không bắt một từ nằm trong từ khác.",
    aPartirDe: "Chặn từ bao nhiêu lượt nhắc",
    oQueFazer: "Làm gì",
    canalDoAlerta: "Kênh cảnh báo",
    escolhaCanal: "Chọn một kênh",
    castigo: "Cấm nói (phút)",
    isentos: "Vai trò được miễn",
    semCargos: "Chưa tạo vai trò nào.",
    salvarRegra: "Lưu quy tắc",
    apagar: "Xóa quy tắc",
    excluirTitulo: "Xóa quy tắc AutoMod này?",
    excluirDescricao: "Máy chủ ngừng lọc theo nó ngay lập tức. Bạn có thể tạo lại, nhưng thiết lập hiện tại sẽ mất.",
    excluirAcao: "Xóa quy tắc",
  },
  cargos: {
    titulo: "Vai trò",
    descricao: "Vai trò cho tên, màu và quyền. Ai ở cao hơn trong danh sách thì trên những người bên dưới — và không ai đụng vào vai trò ngang hoặc trên vai trò của mình.",
    criar: "Tạo vai trò",
    vazio: "Chưa có vai trò nào.",
    abaExibicao: "Hiển thị",
    abaPermissoes: "Quyền",
    abaMembros: "Thành viên — {{quantos}}",
    everyone: "Áp dụng cho mọi người trên máy chủ. Đây là nền để các vai trò khác cộng thêm lên.",
    nomeDoCargo: "Tên vai trò",
    cor: "Màu vai trò",
    corDica: "Tô màu tên người có vai trò trong danh sách thành viên và trong chat.",
    semCor: "Không màu",
    corPersonalizada: "Màu tùy chỉnh",
    estilo: "Kiểu tên",
    segundaCor: "Màu thứ hai",
    segundaCorDica: "Không có nó, dải màu trở về một màu đặc — nó không biến mất.",
    limparSegundaCor: "Xóa màu thứ hai",
    icone: "Biểu tượng",
    iconeDica: "Hiện cạnh vai trò trên thẻ hồ sơ của người có nó.",
    exibirSeparado: "Hiển thị tách khỏi các thành viên khác",
    exibirSeparadoDica: "Vai trò có mục riêng trong danh sách thành viên.",
    permitirMencionar: "Cho phép nhắc vai trò này",
    permitirMencionarDica: "Ai cũng sẽ có thể báo cho tất cả những người có vai trò này.",
    semPoderDeConceder: "{{descricao}} (bạn không có quyền này để trao nó)",
    adicionar: "Thêm ai đó vào vai trò này",
    tirar: "Gỡ vai trò",
    semNinguem: "Chưa ai có vai trò này.",
    apagar: "Xóa vai trò",
    excluirTitulo: "Xóa vai trò \"{{nome}}\"?",
    excluirDescricao: "Người có vai trò này mất tất cả những gì nó cho. Không thể hoàn tác.",
    excluirAcao: "Xóa vai trò",
  },
  membros: {
    procurar: "Tìm theo tên hoặc tên người dùng",
    membroDesde: "Thành viên từ",
    vazio: "Không tìm thấy ai.",
    acoesPara: "Hành động cho {{nome}}",
    deCastigo: "cấm nói",
    tirarCastigo: "Bỏ cấm nói",
    castigo5min: "5 phút",
    castigo1h: "1 giờ",
    castigo1d: "1 ngày",
    castigo1s: "1 tuần",
    expulsar: "Đuổi",
    expulsarTitulo: "Đuổi {{nome}}?",
    expulsarDescricao: "rời {{servidor}} ngay lập tức. Có thể quay lại bằng lời mời — đuổi không chặn việc quay lại.",
    banir: "Cấm",
    banirTitulo: "Cấm {{nome}}?",
    banirDescricao: "rời {{servidor}} và không quay lại được, kể cả có lời mời, cho tới khi được gỡ cấm.",
    motivo: "Lý do (không bắt buộc)",
    motivoDica: "Được ghi vào nhật ký hoạt động",
  },
  perfil: {
    titulo: "Hồ sơ máy chủ",
    descricao: "Máy chủ của bạn hiện ra như thế này trong danh sách và trong liên kết mời.",
    icone: "Biểu tượng",
    faixa: "Băng-rôn trên cùng",
    nomeDoServidor: "Tên máy chủ",
    campoDescricao: "Mô tả",
    doQueE: "Máy chủ này về chuyện gì?",
    comprimido: "Đã nén trước khi tải lên: {{economia}}",
  },
  etiqueta: {
    titulo: "Thẻ máy chủ",
    descricao: "Một nhãn tối đa 4 chữ hiện cạnh tên của mỗi thành viên — trong chat và trong danh sách người. Ở đây nó miễn phí: không boost, không cấp bậc.",
    escolhaNome: "Chọn một tên",
    limite: "Tối đa 4 ký tự, chữ và số.",
    escolhaInsignia: "Chọn một huy hiệu",
    voce: "Bạn",
    fala1: "có ai chơi không?",
    fala2: "ngó cái thẻ của tôi này!",
    fala3: "ồ, lấy đâu ra vậy",
  },
  expressoes: {
    comoUsar: "Thêm tối đa {{limite}} emoji mà mọi người trên máy chủ này đều dùng được. Gõ :tên: trong chat để gửi.",
    imagem: "Hình ảnh",
    enviadoPor: "Được tải lên bởi",
    semEmoji: "Chưa có emoji nào.",
    figurinhas: "Nhãn dán",
    enviarFigurinha: "Tải nhãn dán lên",
    nomeDaFigurinha: "Tên nhãn dán",
    exemploFigurinha: "Ví dụ: mèo con ôm nhau",
    figurinhaGrande: "Nhãn dán vượt {{limite}}.",
    deixaPraLa: "Thôi bỏ đi",
    sons: "Bảng âm thanh",
    enviarSom: "Tải âm thanh lên",
    nomeDoSom: "Tên âm thanh",
    semSom: "Chưa có âm thanh nào.",
    somGrande: "Âm thanh vượt {{limite}}.",
    emojiRelacionado: "Emoji liên quan",
    ouvir: "Nghe",
    ouvirAssim: "Nghe như vầy",
    volumeDe: "Âm lượng của {{nome}}",
    volumeDica: "Áp dụng cho mọi người trên máy chủ. Mỗi người vẫn có thể hạ âm thanh chỉ cho riêng mình, trong bảng cuộc gọi.",
    falhaEnvio: "Không tải được tệp lên.",
    excluirTitulo: "Xóa {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Nó biến mất khỏi máy chủ với tất cả mọi người. Những tin nhắn đã dùng nó vẫn giữ nguyên.",
  },
  canal: {
    tipoLink: "Liên kết",
    tipoLinkDica: "Trỏ tới một địa chỉ bên ngoài và mở trong trình duyệt",
    endereco: "Địa chỉ",
    enderecoDica: "Kênh này dẫn tới đâu. Phải bắt đầu bằng https://",
    visaoGeral: "Tổng quan",
    nome: "Tên kênh",
    topico: "Chủ đề kênh",
    topicoDica: "Ở đây nói về chuyện gì?",
    modoLento: "Mỗi người chỉ gửi một tin nhắn trong mỗi khoảng. Ai quản lý tin nhắn hoặc kênh thì đi thẳng qua.",
    visibilidade: "Khả năng thấy nội dung",
    padrao: "Mặc định",
    padraoDica: "Nội dung của kênh luôn hiện.",
    spoiler: "Kênh có tiết lộ nội dung",
    spoilerDica: "Đánh dấu kênh này là có tiết lộ nội dung, để những cú twist và chủ đề nặng vẫn ẩn cho tới khi ai đó chọn xem.",
    idade: "Kênh giới hạn độ tuổi",
    idadeDica: "Ai vào phải xác nhận đã đủ tuổi mới thấy nội dung.",
    bitrateDica: "Vượt 64 kbps có thể làm phiền người có mạng yếu.",
    qualidadeDeVideo: "Chất lượng video",
    automatica: "Tự động",
    limite: "Giới hạn người dùng — {{valor}}",
    pessoas: "{{quantos}} người",
    semLimite: "không giới hạn",
    permissoesDescricao: "Ở đây bạn đổi những gì áp dụng trong kênh này. Cái nào để ở “kế thừa” thì vẫn theo vai trò.",
    excluir: {
      titulo: "Xóa kênh",
      historico: "Toàn bộ lịch sử của {{canal}} đi theo nó, với tất cả mọi người.",
      digite: "Gõ {{canal}} để xác nhận",
    },
  },
  moderacao: {
    titulo: "Chế độ xem của người kiểm duyệt",
    semPermissao: "Bạn cần quyền “Kiểm duyệt thành viên” để thấy phần này.",
    fecharEsc: "Đóng (Esc)",
    atividade: "Hoạt động trên máy chủ",
    mensagens: "Tin nhắn",
    links: "Liên kết",
    midia: "Đa phương tiện",
    acoesNaAuditoria: "Hành động trong nhật ký",
    moderacoesSofridas: "Đã bị xử lý",
    permissoes: "Quyền ({{quantas}})",
    semPermissaoEspecial: "Không có quyền đặc biệt nào.",
    conta: "Tài khoản",
    entrouNoServidor: "Vào máy chủ",
    contaCriadaEm: "Tài khoản tạo ngày",
    deCastigoAte: "Bị cấm nói đến",
    formaDeAdesao: "Vào bằng cách nào",
    mensagem: "Tin nhắn",
    castigo: "Cấm nói",
    copiarId: "Sao chép ID",
    idCopiado: "Đã sao chép ID.",
    adicionarCargo: "Thêm vai trò",
    semCargos: "Chưa tạo vai trò nào",
    soEveryone: "Chỉ @everyone.",
    voltar: "Quay lại",
    vazio: "Chẳng có gì ở đây.",
    cinquenta: "Đang hiện 50 cái mới nhất.",
    irParaMensagem: "Tới tin nhắn",
    precisaSerAmigo: "Hai bạn phải là bạn bè thì mới nói chuyện được.",
    expulsarDescricao: "Rời máy chủ ngay, nhưng có thể quay lại bằng lời mời.",
    banirDescricao: "Rời máy chủ và không quay lại được, kể cả có lời mời, cho tới khi được gỡ cấm.",
    castigarTitulo: "Cấm nói {{nome}}?",
    castigoDescricao: "Trong lúc còn hiệu lực, người đó không viết cũng không nói ở bất kỳ kênh nào của máy chủ.",
    aplicarCastigo: "Áp dụng cấm nói",
    duracao: "Thời lượng tính bằng phút",
    informeDuracao: "Cho biết thời lượng tính bằng phút.",
  },
  abas: {
    pesquisar: "Tìm trong cài đặt",
    semResultado: "Ở đây không có gì tên như vậy.",
    comunidade: "Cộng đồng",
    expressoes: "Biểu đạt",
    pessoas: "Mọi người",
    apps: "Ứng dụng",
    moderacao: "Kiểm duyệt",
    banimentos: "Cấm",
  },
};
