export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Cài đặt máy chủ",
  auditoria: {
    todasAsAcoes: "Mọi hành động",
    todosOsUsuarios: "Mọi người dùng",
    filtroMembros: "Thành viên",
    filtroCanais: "Kênh",
    filtroEmojis: "Emoji",
    filtroServidor: "Máy chủ",
    titulo: "Nhật ký hoạt động",
    porUsuario: "Lọc theo người",
    porAcao: "Lọc theo hành động",
    vazio: "Chưa có gì được ghi lại với bộ lọc này.",
    motivo: "Lý do:",
  },
  banimentos: {
    titulo: "Danh sách cấm của máy chủ",
    descricao: "Ai ở đây thì không vào lại được, kể cả có lời mời mới. Bỏ cấm là trả lại quyền vào ngay.",
    procurar: "Tìm lệnh cấm theo tên người dùng",
    vazioTitulo: "Không có ai bị cấm",
    vazio: "Bạn chưa cấm ai… nhưng nếu có lúc cần, đừng ngần ngại.",
    desbanir: "Bỏ cấm",
  },
  excluir: {
    tudoVai: "Mọi kênh, tin nhắn và lời mời của {{servidor}} sẽ bị xóa với {{membros}} thành viên. Sau đó không ai lấy lại được.",
    digite: "Gõ {{servidor}} để xác nhận",
    titulo: "Xóa máy chủ",
    aviso: "Việc này không thể hoàn tác.",
  },
  emblemas: {
    apagarDescricao: "Nó rời khỏi tất cả những ai đang đeo. Không thể hoàn tác.",
    titulo: "Huy hiệu",
    vazio: "Chưa có huy hiệu nào.",
    novo: "Huy hiệu mới",
  },
  convites: {
    revogarTitulo: "Thu hồi lời mời?",
    revogarAcao: "Thu hồi",
    revogarDescricao: "Liên kết {{codigo}} ngừng hoạt động ngay. Ai đã vào bằng nó thì vẫn ở lại máy chủ.",
    titulo: "Lời mời",
    descricao: "Tất cả liên kết mời đang hoạt động của máy chủ này.",
    vazio: "Chưa tạo lời mời nào.",
    revogar: "Thu hồi lời mời",
  },
  integracoes: {
    opcionais: "username và avatar_url là tùy chọn và áp dụng cho từng tin nhắn. Giới hạn là 5 tin nhắn mỗi 5 giây.",
    apagarDescricao: "URL ngừng hoạt động ngay. Những tin nhắn nó đã gửi vẫn ở trong kênh.",
    titulo: "Tích hợp",
    descricao: "Webhook là một địa chỉ đăng bài vào kênh mà không cần tài khoản. Tiện để báo khi bản dựng chạy xong, khi ai đó mở phiếu, hay bất cứ thứ gì bạn muốn gửi từ một script.",
    novo: "Webhook mới",
    vazio: "Chưa có webhook nào. Tạo một cái và dán URL vào nơi bạn muốn tin nhắn đi ra.",
    canal: "Kênh",
    apagar: "Xóa webhook",
    comoUsar: "Cách dùng",
    comoUsarTexto: "Gửi một POST kèm JSON:",
  },
  explorar: {
    titulo: "Khám phá",
  },
  engajamento: {
    semCanal: "Không có kênh hệ thống",
    titulo: "Sức sống",
    descricao: "Những gì máy chủ tự làm để không trông trống trải khi có người mới đến.",
    sistema: "Tin nhắn hệ thống",
    boasVindas: "Gửi lời chào khi có người tham gia",
    sorteio: "Không có chữ của bạn ở dưới thì câu sẽ được bốc ngẫu nhiên — cùng một câu mãi thì mau chán.",
    canalDoSistema: "Kênh tin nhắn hệ thống",
    mensagem: "Lời chào mừng",
    deixeVazio: "Để trống để bốc trong những câu có sẵn",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Bộ lọc tự kiểm duyệt, trước cả khi tin nhắn tồn tại. Người quản trị máy chủ không bao giờ bị lọc — và các vai trò được miễn thì đi thẳng qua.",
    palavras: {
      titulo: "Chặn từ của bạn",
      descricao: "Danh sách từ mà không ai được viết.",
    },
    mencoes: {
      titulo: "Chặn spam nhắc tên",
      descricao: "Chặn tin nhắn có quá nhiều lượt nhắc tên cùng lúc.",
    },
    links: {
      titulo: "Chặn liên kết",
      descricao: "Giữ lại mọi địa chỉ dán vào khung chat.",
    },
    definir: "Thiết lập",
    nomeDaRegra: "Tên quy tắc",
    bloqueadas: "Từ bị chặn",
    digiteEnter: "Gõ rồi nhấn Enter",
    comparacao: "Việc so khớp bỏ qua chữ hoa, dấu và dấu câu — và không bắt một từ nằm trong từ khác.",
    aPartirDe: "Chặn từ bao nhiêu lượt nhắc",
    oQueFazer: "Làm gì",
    canalDoAlerta: "Kênh cảnh báo",
    escolhaCanal: "Chọn một kênh",
    castigo: "Cấm nói (phút)",
    isentos: "Vai trò được miễn",
    semCargos: "Chưa tạo vai trò nào.",
    salvarRegra: "Lưu quy tắc",
    apagar: "Xóa quy tắc",
    excluirTitulo: "Xóa quy tắc AutoMod này?",
    excluirDescricao: "Máy chủ ngừng lọc theo nó ngay lập tức. Bạn có thể tạo lại, nhưng thiết lập hiện tại sẽ mất.",
    excluirAcao: "Xóa quy tắc",
  },
  cargos: {
    titulo: "Vai trò",
    descricao: "Vai trò cho tên, màu và quyền. Ai ở cao hơn trong danh sách thì trên những người bên dưới — và không ai đụng vào vai trò ngang hoặc trên vai trò của mình.",
    criar: "Tạo vai trò",
    vazio: "Chưa có vai trò nào.",
    abaExibicao: "Hiển thị",
    abaPermissoes: "Quyền",
    abaMembros: "Thành viên — {{quantos}}",
    everyone: "Áp dụng cho mọi người trên máy chủ. Đây là nền để các vai trò khác cộng thêm lên.",
    nomeDoCargo: "Tên vai trò",
    cor: "Màu vai trò",
    corDica: "Tô màu tên người có vai trò trong danh sách thành viên và trong chat.",
    semCor: "Không màu",
    corPersonalizada: "Màu tùy chỉnh",
    estilo: "Kiểu tên",
    segundaCor: "Màu thứ hai",
    segundaCorDica: "Không có nó, dải màu trở về một màu đặc — nó không biến mất.",
    limparSegundaCor: "Xóa màu thứ hai",
    icone: "Biểu tượng",
    iconeDica: "Hiện cạnh vai trò trên thẻ hồ sơ của người có nó.",
    exibirSeparado: "Hiển thị tách khỏi các thành viên khác",
    exibirSeparadoDica: "Vai trò có mục riêng trong danh sách thành viên.",
    permitirMencionar: "Cho phép nhắc vai trò này",
    permitirMencionarDica: "Ai cũng sẽ có thể báo cho tất cả những người có vai trò này.",
    semPoderDeConceder: "{{descricao}} (bạn không có quyền này để trao nó)",
    adicionar: "Thêm ai đó vào vai trò này",
    tirar: "Gỡ vai trò",
    semNinguem: "Chưa ai có vai trò này.",
    apagar: "Xóa vai trò",
    excluirTitulo: "Xóa vai trò \"{{nome}}\"?",
    excluirDescricao: "Người có vai trò này mất tất cả những gì nó cho. Không thể hoàn tác.",
    excluirAcao: "Xóa vai trò",
  },
  membros: {
    procurar: "Tìm theo tên hoặc tên người dùng",
    membroDesde: "Thành viên từ",
    vazio: "Không tìm thấy ai.",
    acoesPara: "Hành động cho {{nome}}",
    deCastigo: "cấm nói",
    tirarCastigo: "Bỏ cấm nói",
    castigo5min: "5 phút",
    castigo1h: "1 giờ",
    castigo1d: "1 ngày",
    castigo1s: "1 tuần",
    expulsar: "Đuổi",
    expulsarTitulo: "Đuổi {{nome}}?",
    expulsarDescricao: "rời {{servidor}} ngay lập tức. Có thể quay lại bằng lời mời — đuổi không chặn việc quay lại.",
    banir: "Cấm",
    banirTitulo: "Cấm {{nome}}?",
    banirDescricao: "rời {{servidor}} và không quay lại được, kể cả có lời mời, cho tới khi được gỡ cấm.",
    motivo: "Lý do (không bắt buộc)",
    motivoDica: "Được ghi vào nhật ký hoạt động",
  },
  perfil: {
    titulo: "Hồ sơ máy chủ",
    descricao: "Máy chủ của bạn hiện ra như thế này trong danh sách và trong liên kết mời.",
    icone: "Biểu tượng",
    faixa: "Băng-rôn trên cùng",
    nomeDoServidor: "Tên máy chủ",
    campoDescricao: "Mô tả",
    doQueE: "Máy chủ này về chuyện gì?",
    comprimido: "Đã nén trước khi tải lên: {{economia}}",
  },
  etiqueta: {
    titulo: "Thẻ máy chủ",
    descricao: "Một nhãn tối đa 4 chữ hiện cạnh tên của mỗi thành viên — trong chat và trong danh sách người. Ở đây nó miễn phí: không boost, không cấp bậc.",
    escolhaNome: "Chọn một tên",
    limite: "Tối đa 4 ký tự, chữ và số.",
    escolhaInsignia: "Chọn một huy hiệu",
    voce: "Bạn",
    fala1: "có ai chơi không?",
    fala2: "ngó cái thẻ của tôi này!",
    fala3: "ồ, lấy đâu ra vậy",
  },
  expressoes: {
    comoUsar: "Thêm tối đa {{limite}} emoji mà mọi người trên máy chủ này đều dùng được. Gõ :tên: trong chat để gửi.",
    imagem: "Hình ảnh",
    enviadoPor: "Được tải lên bởi",
    semEmoji: "Chưa có emoji nào.",
    figurinhas: "Nhãn dán",
    enviarFigurinha: "Tải nhãn dán lên",
    nomeDaFigurinha: "Tên nhãn dán",
    exemploFigurinha: "Ví dụ: mèo con ôm nhau",
    figurinhaGrande: "Nhãn dán vượt {{limite}}.",
    deixaPraLa: "Thôi bỏ đi",
    sons: "Bảng âm thanh",
    enviarSom: "Tải âm thanh lên",
    nomeDoSom: "Tên âm thanh",
    semSom: "Chưa có âm thanh nào.",
    somGrande: "Âm thanh vượt {{limite}}.",
    emojiRelacionado: "Emoji liên quan",
    ouvir: "Nghe",
    ouvirAssim: "Nghe như vầy",
    volumeDe: "Âm lượng của {{nome}}",
    volumeDica: "Áp dụng cho mọi người trên máy chủ. Mỗi người vẫn có thể hạ âm thanh chỉ cho riêng mình, trong bảng cuộc gọi.",
    falhaEnvio: "Không tải được tệp lên.",
    excluirTitulo: "Xóa {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "Nó biến mất khỏi máy chủ với tất cả mọi người. Những tin nhắn đã dùng nó vẫn giữ nguyên.",
  },
  canal: {
    visaoGeral: "Tổng quan",
    nome: "Tên kênh",
    topico: "Chủ đề kênh",
    topicoDica: "Ở đây nói về chuyện gì?",
    modoLento: "Mỗi người chỉ gửi một tin nhắn trong mỗi khoảng. Ai quản lý tin nhắn hoặc kênh thì đi thẳng qua.",
    visibilidade: "Khả năng thấy nội dung",
    padrao: "Mặc định",
    padraoDica: "Nội dung của kênh luôn hiện.",
    spoiler: "Kênh có tiết lộ nội dung",
    spoilerDica: "Đánh dấu kênh này là có tiết lộ nội dung, để những cú twist và chủ đề nặng vẫn ẩn cho tới khi ai đó chọn xem.",
    idade: "Kênh giới hạn độ tuổi",
    idadeDica: "Ai vào phải xác nhận đã đủ tuổi mới thấy nội dung.",
    bitrateDica: "Vượt 64 kbps có thể làm phiền người có mạng yếu.",
    qualidadeDeVideo: "Chất lượng video",
    automatica: "Tự động",
    limite: "Giới hạn người dùng — {{valor}}",
    pessoas: "{{quantos}} người",
    semLimite: "không giới hạn",
    permissoesDescricao: "Ở đây bạn đổi những gì áp dụng trong kênh này. Cái nào để ở “kế thừa” thì vẫn theo vai trò.",
    excluir: {
      titulo: "Xóa kênh",
      historico: "Toàn bộ lịch sử của {{canal}} đi theo nó, với tất cả mọi người.",
      digite: "Gõ {{canal}} để xác nhận",
    },
  },
  moderacao: {
    titulo: "Chế độ xem của người kiểm duyệt",
    semPermissao: "Bạn cần quyền “Kiểm duyệt thành viên” để thấy phần này.",
    fecharEsc: "Đóng (Esc)",
    atividade: "Hoạt động trên máy chủ",
    mensagens: "Tin nhắn",
    links: "Liên kết",
    midia: "Đa phương tiện",
    acoesNaAuditoria: "Hành động trong nhật ký",
    moderacoesSofridas: "Đã bị xử lý",
    permissoes: "Quyền ({{quantas}})",
    semPermissaoEspecial: "Không có quyền đặc biệt nào.",
    conta: "Tài khoản",
    entrouNoServidor: "Vào máy chủ",
    contaCriadaEm: "Tài khoản tạo ngày",
    deCastigoAte: "Bị cấm nói đến",
    formaDeAdesao: "Vào bằng cách nào",
    mensagem: "Tin nhắn",
    castigo: "Cấm nói",
    copiarId: "Sao chép ID",
    idCopiado: "Đã sao chép ID.",
    adicionarCargo: "Thêm vai trò",
    semCargos: "Chưa tạo vai trò nào",
    soEveryone: "Chỉ @everyone.",
    voltar: "Quay lại",
    vazio: "Chẳng có gì ở đây.",
    cinquenta: "Đang hiện 50 cái mới nhất.",
    irParaMensagem: "Tới tin nhắn",
    precisaSerAmigo: "Hai bạn phải là bạn bè thì mới nói chuyện được.",
    expulsarDescricao: "Rời máy chủ ngay, nhưng có thể quay lại bằng lời mời.",
    banirDescricao: "Rời máy chủ và không quay lại được, kể cả có lời mời, cho tới khi được gỡ cấm.",
    castigarTitulo: "Cấm nói {{nome}}?",
    castigoDescricao: "Trong lúc còn hiệu lực, người đó không viết cũng không nói ở bất kỳ kênh nào của máy chủ.",
    aplicarCastigo: "Áp dụng cấm nói",
    duracao: "Thời lượng tính bằng phút",
    informeDuracao: "Cho biết thời lượng tính bằng phút.",
  },
  abas: {
    expressoes: "Biểu đạt",
    pessoas: "Mọi người",
    apps: "Ứng dụng",
    moderacao: "Kiểm duyệt",
    banimentos: "Cấm",
  },
};
