export const amizades = {
  ativosAgora: "ใช้งานอยู่ตอนนี้",
  procurando: "กำลังดูว่าใครอยู่บ้าง…",
  tudoTranquilo: "ตอนนี้เงียบอยู่…",
  tudoTranquiloDetalhe: "เมื่อคุณหรือเพื่อนเข้าร่วมสาย มันจะขึ้นตรงนี้ — และคุณเข้าร่วมได้ด้วยคลิกเดียว",
  emVoz: "อยู่ในห้องเสียง",
  voce: "คุณ",
  soVoce: "มีแค่คุณ",
  pessoas: "{{quantas}} คน",
  voltarParaChamada: "กลับไปที่สาย",
  entrarNaChamada: "เข้าร่วมสาย",
  abrirCanal: "เปิด {{canal}} ใน {{servidor}}",
  mensagensDiretas: "ข้อความส่วนตัว",
  encontreConversa: "ค้นหาการสนทนา",
  amigos: "เพื่อน",
  conversas: "การสนทนา",
  semConversas: "ยังไม่มีการสนทนา เพิ่มเพื่อนเพื่อเริ่มต้น",
  semConversaComEsseNome: "ไม่มีการสนทนาชื่อนั้น",
  abrirMenu: "เปิดเซิร์ฟเวอร์และการสนทนา",
  solicitacoes: "คำขอส่งข้อความ",
  pedidos: "คำขอ",
  spam: "สแปม",
  pedidosPendentes: "คำขอที่รออยู่",
  marcadosComoSpam: "ทำเครื่องหมายว่าสแปม",
  aceitar: "ยอมรับ",
  ignorar: "เพิกเฉย",
  marcarSpam: "ทำเครื่องหมายว่าสแปม",
  semPedidos: "ไม่มีคำขอรออยู่",
  semPedidosDetalhe: "คนที่ไม่ใช่เพื่อนคุณแต่อยู่เซิร์ฟเวอร์เดียวกันจะมาอยู่ตรงนี้ก่อนถึงการสนทนาของคุณ",
  semSpam: "ไม่มีอะไรถูกทำเครื่องหมายว่าสแปม",
  semSpamDetalhe: "สิ่งที่ตัวกรองสแปมคัดออก หรือสิ่งที่คุณทำเครื่องหมายเอง จะเก็บอยู่ในแท็บนี้",
  umServidorEmComum: "มีเซิร์ฟเวอร์ร่วมกัน 1 แห่ง",
  servidoresEmComum: "มีเซิร์ฟเวอร์ร่วมกัน {{quantos}} แห่ง",
  semServidoresEmComum: "ไม่มีเซิร์ฟเวอร์ร่วมกัน",
};
