export const chamada = {
  conectando: "กำลังเชื่อมต่อกับสาย…",
  naoEntrou: "เข้าร่วมสายไม่สำเร็จ",
  sair: "ออกจากสาย",
  sairDaVoz: "ออกจากสายเสียง",
  desconectar: "ตัดการเชื่อมต่อ",
  voltar: "กลับไปที่สาย",
  voltarAosQuadros: "กลับไปที่ช่องของสาย",
  fecharChat: "ปิดแชท",
  carregandoPrevia: "กำลังโหลดตัวอย่าง…",
  maisOpcoes: "ตัวเลือกเพิ่มเติม",
  deVideo: "สายวิดีโอ",
  deVoz: "สายเสียง",
  alguem: "ใครบางคน",
  volume: {
    entrada: "ระดับเสียงเข้า",
    saida: "ระดับเสียงออก",
    live: "ระดับเสียงไลฟ์",
    liveComPorcento: "ระดับเสียงไลฟ์ ({{porcento}}%)",
    liveSemSom: "ไลฟ์ปิดเสียง",
  },
  aparelhos: {
    entrada: "อุปกรณ์รับเสียง",
    saida: "อุปกรณ์ส่งเสียง",
    camera: "กล้อง",
    microfone: "ไมโครโฟน",
    saidaCurto: "เสียงออก",
    oDoSistema: "ตามระบบ",
    aDoSistema: "ตามระบบ",
    semEscolhaDeSaida: "เบราว์เซอร์นี้ไม่ให้เลือกเสียงออก — ระบบเป็นคนตัดสิน",
    espelhar: "กลับด้านกล้องของฉัน",
    configEntrada: "ตั้งค่าเสียงเข้า",
    configSaida: "ตั้งค่าเสียงออก",
    configCamera: "ตั้งค่ากล้อง",
    configAudioEVideo: "ตั้งค่าเสียงและวิดีโอ",
  },
  tela: {
    compartilhar: "แชร์หน้าจอ",
    compartilharAcao: "แชร์",
    cancelar: "ยกเลิก",
    telas: "หน้าจอ",
    janelas: "หน้าต่าง",
    somDoComputador: "เอาเสียงคอมพิวเตอร์ไปด้วย",
    somDoSistema: "เอาเสียงระบบไปด้วย",
    configCompartilhamento: "ตั้งค่าการแชร์",
    mostrarSemVideo: "แสดงคนที่ไม่ได้เปิดวิดีโอ",
    semFontes: "ระบบไม่ได้ส่งหน้าจอหรือหน้าต่างใดมาให้แชร์",
    pararDeCompartilhar: "หยุดแชร์",
    encerrarTransmissao: "จบการถ่ายทอด",
  },
  live: {
    etiqueta: "ไลฟ์",
    etiquetaMaiuscula: "ไลฟ์",
    assistir: "ดูการถ่ายทอด",
    assistirPessoa: "ดู {{nome}}",
    pararDeAssistir: "หยุดดู",
  },
  membro: {
    mudarMeuApelido: "เปลี่ยนชื่อเล่นของฉัน",
    meuMicrofone: "ไมโครโฟนของฉัน",
    ouvirChamada: "ฟังสาย",
    copiarMeuId: "คัดลอก ID ของฉัน",
    idCopiado: "คัดลอก ID แล้ว",
    mensagem: "ข้อความ",
    silenciar: "ปิดเสียง",
    alterarApelido: "เปลี่ยนชื่อเล่น",
    cargos: "บทบาท",
    semCargo: "ยังไม่ได้สร้างบทบาท",
    moverPara: "ย้ายไปที่",
    silenciarNoServidor: "ปิดเสียงพูดในเซิร์ฟเวอร์",
    desativarAudioNoServidor: "ปิดเสียงในเซิร์ฟเวอร์",
    desconectar: "ตัดการเชื่อมต่อ",
    apelidoTitulo: "ชื่อเล่นของคุณในเซิร์ฟเวอร์นี้",
    apelidoDeAlguem: "ชื่อเล่นของ {{nome}}",
    apelidoCampo: "ชื่อเล่น",
    apelidoDicaPropria: "ใช้ได้เฉพาะที่นี่ เว้นว่างไว้จะกลับไปใช้ชื่อปกติของคุณ",
    apelidoDicaDeOutro: "ใช้ได้เฉพาะเซิร์ฟเวอร์นี้ เว้นว่างไว้เพื่อกลับไปใช้ชื่อเดิม",
  },
  detalhes: {
    abrir: "รายละเอียดเสียง",
    titulo: "รายละเอียดเสียง",
    conexao: "การเชื่อมต่อ",
    pingMedio: "ping เฉลี่ย",
    ultimoPing: "ping ล่าสุด",
    perda: "การสูญหายของแพ็กเก็ตที่ส่ง",
    medindo: "กำลังวัด…",
    criptografado: "เข้ารหัสจนถึงเซิร์ฟเวอร์ (DTLS-SRTP)",
    explicacao: "เกิน 250 ms จะรู้สึกถึงความหน่วงในบทสนทนา — คนจะเริ่มพูดทับกัน แพ็กเก็ตหายเกิน 10% ทำให้เสียงเหมือนหุ่นยนต์ ทั้งสองกรณีปัญหามักอยู่ระหว่างคุณกับอินเทอร์เน็ต ลองใช้สายแทน Wi-Fi หรือรีสตาร์ทเราเตอร์",
  },
  microfone: {
    bloqueado: "ไมโครโฟนถูกบล็อก — คุณกำลังฟังอย่างเดียว อนุญาตการเข้าถึงในสิทธิ์ของเบราว์เซอร์",
    bloqueadoNoMac: "macOS กำลังบล็อกไมโครโฟน ให้ติ๊ก",
    caminhoNoMac: "การตั้งค่าระบบ → ความเป็นส่วนตัวและความปลอดภัย → ไมโครโฟน",
    abrirAjustes: "เปิดการตั้งค่า",
    vaiReabrir: "macOS จะขอให้เปิดแอปใหม่",
    naoAbriu: "เปิดไมโครโฟนไม่ได้ — คุณกำลังฟังอย่างเดียว ตรวจสอบอุปกรณ์ที่ การตั้งค่า → เสียงและวิดีโอ",
  },
  gravacaoDeTela: {
    bloqueada: "macOS ยังไม่อนุญาตให้บันทึกหน้าจอ ถ้าไม่มีสิทธิ์นี้ หน้าจอที่แชร์จะออกมาดำ",
    marque: "ให้ติ๊ก",
    reabra: "ใน “การบันทึกหน้าจอ” แล้วเปิดแอปใหม่",
    jaMarcado: "ถ้าติ๊กไว้แล้ว แปลว่าสิทธิ์หมดอายุตอนอัปเดตครั้งล่าสุด ให้เอาติ๊กออก ติ๊กใหม่ แล้วเปิดแอปอีกครั้ง",
  },
  ruido: {
    titulo: "การลดเสียงรบกวน",
    explicacao: "เอาเสียงรบกวนรอบข้างออกจากเสียงคุณ ลองตบมือหรือลากคีย์บอร์ดขณะพูด — คนในสายจะได้ยินแค่คุณ",
    semSuporte: "เบราว์เซอร์นี้ใช้การลดเสียงขั้นสูงไม่ได้ ของเบราว์เซอร์เองยังทำงานอยู่ แต่อ่อนกว่า",
    aplicando: "กำลังใช้กับสาย…",
    faleParaTestar: "พูดเพื่อทดสอบ",
    verdeQuandoPassa: "เป็นสีเขียวเมื่อเสียงของคุณผ่าน",
    teOuvindo: "ตอนนี้เขาได้ยินคุณแล้ว",
    feitoCom: "สร้างด้วย",
    aquiNoAparelho: "· ในเครื่องของคุณเอง",
    ajustes: "ตั้งค่า",
  },
  permissoes: {
    titulo: "สิทธิ์ของ macOS",
    detalhe: "macOS ถามครั้งเดียว หลังจากนั้นเปลี่ยนได้เฉพาะในแผงของมันเอง ที่นี่ดูได้ว่าอะไรมีผลอยู่ และแก้สิ่งที่ขาด",
    concedida: "อนุญาตแล้ว",
    negada: "ปฏิเสธ",
    naoPedida: "ยังไม่ได้ขอ",
    permitir: "อนุญาต",
    abrirAjustes: "เปิดการตั้งค่า",
    microfone: "ไมโครโฟน",
    microfoneDetalhe: "พูดในสายและทดสอบเสียงเข้าของคุณ",
    camera: "กล้อง",
    cameraDetalhe: "เปิดวิดีโอในสาย",
    tela: "การบันทึกหน้าจอ",
    telaDetalhe: "แชร์หน้าจอและหน้าต่าง",
    monitoramento: "การมอนิเตอร์เสียงเข้า",
    monitoramentoDetalhe: "ใช้กดเพื่อพูดได้แม้ Gravaê อยู่เบื้องหลัง",
  },
  jaConectado: {
    titulo: "คุณอยู่ในสายนี้อยู่แล้ว",
    trazer: "ย้ายสายมาที่นี่",
    deixar: "ปล่อยไว้อย่างเดิม",
    detalhe: "ถ้าย้ายมาที่นี่ อีกฝั่งจะหลุดออกจากสาย — บัญชีของคุณอยู่ได้ทีละที่เดียว",
  },
};
