export const comum = {
  carregando: "กำลังโหลด…",
  salvar: "บันทึก",
  salvando: "กำลังบันทึก…",
  descartar: "ทิ้ง",
  redefinir: "รีเซ็ต",
  naoSalvo: "คุณมีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก",
  fechar: "ปิด",
  criar: "สร้าง",
  nome: "ชื่อ",
  emoji: "อีโมจิ",
  previa: "ตัวอย่าง",
  cancelar: "ยกเลิก",
  enviar: "ส่ง",
  apagar: "ลบ",
  excluir: "ลบ",
  remover: "เอาออก",
  trocar: "เปลี่ยน",
};
