export const configuracoes = {
  efeitos: {
    titulo: "เอฟเฟกต์ของตัวชี้",
    detalhe: "เส้นตามและประกายที่วาดทับบนแอป เริ่มต้นปิดไว้ และดับเองถ้าคุณขอให้เคลื่อนไหวน้อยลง",
    rastro: "เส้นตามเคอร์เซอร์",
    rastroDetalhe: "เส้นที่วิ่งตามตัวชี้แล้วจางหายด้านหลัง",
    faisca: "ประกายตอนคลิก",
    faiscaDetalhe: "เส้นสั้น ๆ ที่พุ่งออกจากจุดที่คุณคลิก",
    cor: "สี",
    espessura: "ความหนา",
    comprimento: "ความยาว",
    tamanho: "ขนาด",
    quantidade: "จำนวน",
  },
  email: {
    verificarTitulo: "ยืนยันอีเมลของคุณ",
    verificarDetalhe: "บางชุมชนให้เฉพาะคนที่ยืนยันแล้วพูดได้ กดครั้งเดียวก็เสร็จ",
    enviar: "ส่งลิงก์",
    enviado: "ดูในกล่องจดหมาย ลิงก์ใช้ได้หนึ่งวัน",
    falhou: "ส่งอีเมลไม่ได้",
    confirmado: "ยืนยันอีเมลแล้ว",
    confirmadoDetalhe: "เรียบร้อย ตอนนี้พูดได้ในทุกชุมชนที่ขอสิ่งนี้",
    linkIncompleto: "ลิงก์ไม่ครบ",
    linkIncompletoDetalhe: "ที่อยู่ขาดรหัส เปิดลิงก์จากในอีเมลโดยตรง",
    confirmando: "กำลังยืนยัน…",
    expirou: "ลิงก์นี้ถูกใช้ไปแล้วหรือหมดอายุ",
    irParaOApp: "ไปที่แอป",
  },
  tema: {
    indisponivel: "ใช้ธีมนี้ไม่ได้",
    indisponivelDetalhe: "คนที่เผยแพร่ลบไปแล้ว หรือลิงก์ผิด",
    indisponivelLinha: "ใช้ธีมนี้ไม่ได้ คนที่เผยแพร่ลบไปแล้ว หรือลิงก์ผิด",
    importar: "นำเข้าธีม",
    importarCurto: "นำเข้า",
    importarDetalhe: "การทำแบบนี้จะแทนที่ธีมที่คุณใช้อยู่ แก้ไขทีหลังได้ที่ การตั้งค่า > รูปลักษณ์ > สตูดิโอธีม",
    porAutor: "โดย {{autor}}",
    umaCorTrocada: "เปลี่ยนสี 1 สี",
    coresTrocadas: "เปลี่ยนสี {{quantas}} สี",
    avisoDeCss: "ธีมนี้พก CSS ของคนเขียนมาด้วย และ CSS แตะได้ทุกซอกทุกมุมของหน้าจอ นำเข้าเฉพาะจากคนที่คุณไว้ใจเท่านั้น",
    soCores: "ธีมนี้เปลี่ยนแค่สี ไม่มี CSS จากข้างนอก",
    aplicar: "ใช้",
    previaSemMotor: "ตัวอย่างไม่ได้รันเอนจิน ติดตั้งก่อนจึงจะเห็น",
    motorAnimado: "{{motor}} แบบเคลื่อนไหว",
  },
  sair: "ออกจากระบบ",
  versoes: {
    termos: "ข้อกำหนดในการให้บริการ",
    privacidade: "นโยบายความเป็นส่วนตัว",
    copiar: "คลิกเพื่อคัดลอก",
    copiado: "คัดลอกแล้ว",
  },
  telas: {
    conta: "บัญชีของฉัน",
    privacidade: "ความเป็นส่วนตัว",
    conexoes: "การเชื่อมต่อ",
    voz: "เสียง",
    video: "วิดีโอ",
    avisos: "การแจ้งเตือน",
    aplicativos: "แอปพลิเคชัน",
    aparencia: "รูปลักษณ์",
    batePapo: "แชท",
    acessibilidade: "การเข้าถึง",
    idioma: "ภาษา",
    aplicativo: "ดาวน์โหลดแอป",
    atalhos: "ทางลัด",
    desktop: "แอปเดสก์ท็อป",
    avancado: "ขั้นสูง",
    servidor: "เซิร์ฟเวอร์",
    comunicado: "ประกาศจากระบบ",
    denuncias: "รายงาน",
    publicacoes: "การปรับใช้",
  },
  grupos: {
    conta: "บัญชี",
    app: "การตั้งค่าแอป",
    desenvolvedor: "นักพัฒนา",
    administracao: "การดูแลระบบ",
  },
  secoes: {
    detalhesDeLogin: "ข้อมูลเข้าสู่ระบบ",
    dispositivos: "อุปกรณ์",
    usuariosBloqueados: "ผู้ใช้ที่ถูกบล็อก",
    aplicativosAutorizados: "แอปที่ได้รับอนุญาต",
    sessoes: "เซสชัน",
    amigosEDms: "เพื่อนและข้อความส่วนตัว",
    compartilhamentoDeAtividade: "การแชร์กิจกรรม",
    visibilidadeDoPerfil: "การมองเห็นโปรไฟล์",
    exportarDados: "ส่งออกข้อมูล",
    exclusaoDeDados: "ลบข้อมูล",
    tema: "ธีม",
    corDeDestaque: "สีเน้น",
    interface: "อินเทอร์เฟซ",
    listaDeCanais: "รายการช่อง",
    zoomDoApp: "ระดับการซูมของแอป",
    escalaDaFonte: "ขนาดตัวอักษรในแชท",
    modoStreamer: "ความเป็นส่วนตัวขณะสตรีม",
    cursores: "เคอร์เซอร์",
    movimento: "การเคลื่อนไหว",
    textoEmVoz: "ข้อความเป็นเสียง",
    teclado: "แป้นพิมพ์",
    formatoDaHora: "รูปแบบเวลา",
    idiomaDaInterface: "ภาษาของอินเทอร์เฟซ",
    dispositivosDeVoz: "อุปกรณ์",
    testeDoMicrofone: "ทดสอบไมโครโฟน",
    modoDeEntrada: "โหมดอินพุต",
    sensibilidade: "ความไวของอินพุต",
    qualidade: "คุณภาพ",
    camera: "กล้อง",
    transmissao: "การถ่ายทอด",
    exibicao: "การแสดงผล",
    entrada: "การป้อนข้อมูล",
    midia: "สื่อ",
    geral: "ทั่วไป",
    preferenciaDeMencao: "การตั้งค่าการกล่าวถึง",
    sons: "เสียง",
  },
};
