export const conversa = {
  lista: {
    carregando: "กำลังโหลดข้อความ…",
    carregandoMais: "กำลังโหลด…",
    verMais: "เลื่อนขึ้นเพื่อดูเพิ่มเติม",
    semHistorico: "ดูประวัติไม่ได้",
    semHistoricoDetalhe: "บทบาทของคุณไม่มีสิทธิ์อ่านประวัติของ #{{canal}} ข้อความใหม่จะยังปรากฏต่อไปตราบใดที่คุณอยู่ที่นี่",
    boasVindas: "ยินดีต้อนรับสู่ #{{canal}}",
    boasVindasDetalhe: "นี่คือจุดเริ่มต้นของช่อง #{{canal}}",
  },
  data: {
    hoje: "วันนี้",
    ontem: "เมื่อวาน",
    hojeAs: "วันนี้ {{hora}} น.",
    ontemAs: "เมื่อวาน {{hora}} น.",
  },
  digitando: {
    um: "{{nome}} กำลังพิมพ์…",
    dois: "{{primeiro}} และ {{segundo}} กำลังพิมพ์…",
    varios: "{{quantidade}} คนกำลังพิมพ์…",
  },
  mensagem: {
    usou: "ใช้",
    fixada: "ปักหมุดแล้ว",
    editado: "(แก้ไขแล้ว)",
    ignorada: "ข้อความจากคนที่คุณเพิกเฉย",
    mostrar: "แสดง",
    escPara: "กด Esc เพื่อ",
    cancelar: "ยกเลิก",
    enterParaSalvar: "กด Enter เพื่อบันทึก",
    falhou: "ส่งไม่สำเร็จ ลองอีกครั้ง",
    naoLidasDaqui: "ทำเครื่องหมายยังไม่อ่านตั้งแต่ตรงนี้",
    linkCopiado: "คัดลอกลิงก์แล้ว",
    idCopiado: "คัดลอก ID แล้ว",
    naoDeuParaCopiar: "เบราว์เซอร์ของคุณไม่อนุญาตให้คัดลอก",
    apagarTitulo: "ลบข้อความไหม",
    apagarDescricao: "ข้อความจะหายไปจากทุกคนในช่อง และกู้คืนไม่ได้",
    apagarAcao: "ลบ",
    citacaoAnexo: "คลิกเพื่อดูไฟล์แนบ",
    citacaoSumiu: "ข้อความต้นฉบับไม่อยู่ที่นี่แล้ว",
    reagirCom: "แสดงความรู้สึกด้วย {{emoji}} — กดค้างเพื่อซูเปอร์รีแอ็กชัน",
    segureParaSuper: "{{emoji}} — กดค้างเพื่อซูเปอร์รีแอ็กชัน",
  },
  acoes: {
    reagir: "แสดงความรู้สึก",
    responder: "ตอบกลับ",
    encaminhar: "ส่งต่อ",
    favoritar: "บันทึกข้อความ",
    tirarDosFavoritos: "เอาออกจากที่บันทึกไว้",
    marcarNaoLida: "ทำเครื่องหมายว่ายังไม่อ่าน",
    copiarLink: "คัดลอกลิงก์ข้อความ",
    copiarId: "คัดลอก ID ข้อความ",
    fixar: "ปักหมุดข้อความ",
    desafixar: "เลิกปักหมุด",
    editar: "แก้ไข",
    apagar: "ลบ",
    mais: "เพิ่มเติม",
    adicionarReacao: "เพิ่มความรู้สึก",
    superReagirCom: "ซูเปอร์รีแอ็กชันด้วย {{emoji}}",
    fixarMensagem: "ปักหมุดข้อความ",
    desafixarMensagem: "เลิกปักหมุดข้อความ",
    editarMensagem: "แก้ไขข้อความ",
    apagarMensagem: "ลบข้อความ",
  },
  mencao: {
    cargo: "การกล่าวถึงบทบาท",
    pessoa: "การกล่าวถึง",
    alguem: "ใครบางคน",
    cargoSemNome: "บทบาท",
    here: "แจ้งเตือนคนที่ออนไลน์อยู่",
    everyone: "แจ้งเตือนทั้งเซิร์ฟเวอร์",
  },
  codigo: {
    copiar: "คัดลอก",
    copiado: "คัดลอกแล้ว",
    copiarAria: "คัดลอกโค้ด",
    copiadoAria: "คัดลอกโค้ดแล้ว",
    recolher: "ย่อ",
    expandir: "ขยาย",
    verInteiro: "ดูทั้งไฟล์",
    maisOpcoes: "ตัวเลือกเพิ่มเติม",
    baixar: "ดาวน์โหลด",
  },
  caixa: {
    escrever: "เขียนใน #{{canal}}",
    escreverSemCanal: "เขียนข้อความ",
    semPermissao: "คุณไม่มีสิทธิ์ส่งข้อความในช่องนี้",
    solteParaAnexar: "ปล่อยเพื่อแนบไฟล์",
    respondendoPara: "ตอบกลับถึง",
    vaiNotificar: "อีกฝ่ายจะได้รับการแจ้งเตือน",
    naoVaiNotificar: "อีกฝ่ายจะไม่ได้รับการแจ้งเตือน",
    ligado: "เปิด",
    desligado: "ปิด",
    pararDeResponder: "ยกเลิกการตอบกลับ",
    mais: "เพิ่มเติม",
    enviarArquivo: "ส่งไฟล์",
    criarEnquete: "สร้างโพล",
    expressoes: "อีโมจิ GIF และสติกเกอร์",
    enviar: "ส่ง",
    aguardandoEnvio: "กำลังรอการอัปโหลด",
    modoLento: "โหมดช้าเปิดอยู่ ({{tempo}})",
    modoLentoDica: "โหมดช้าตั้งไว้ที่ {{segundos}} วินาที รอสักครู่ก่อนส่งข้อความถัดไป",
  },
  anexos: {
    enviando: "กำลังอัปโหลด…",
    modificar: "แก้ไข {{arquivo}}",
    remover: "เอา {{arquivo}} ออก",
    ver: "ดู {{arquivo}}",
    mostrarSpoiler: "แสดงสปอยล์: {{arquivo}}",
    spoiler: "สปอยล์",
    spoilerTitulo: "สปอยล์",
    editarTitulo: "แก้ไขไฟล์แนบ",
    nomeDoArquivo: "ชื่อไฟล์",
    descricao: "คำอธิบายข้อความแทน",
    descricaoDica: "อธิบายสื่อนี้สำหรับโปรแกรมอ่านหน้าจอ",
    marcarSpoiler: "ทำเครื่องหมายว่าเป็นสปอยล์",
    cancelar: "ยกเลิก",
    salvar: "บันทึก",
  },
  cartao: {
    tocador: "ตัวเล่น",
    abrir: "เปิด {{destino}}",
    tocar: "เล่น {{titulo}}",
    video: "วิดีโอ",
    verImagem: "ดูรูปภาพ",
  },
  enquete: {
    titulo: "โพล",
    encerrada: "โพลปิดแล้ว",
    variasRespostas: "โพล — ตอบได้หลายข้อ",
    umVoto: "{{quantidade}} คะแนน",
    votos: "{{quantidade}} คะแนน",
    umVotoNoTotal: "รวม {{quantidade}} คะแนน",
    votosNoTotal: "รวม {{quantidade}} คะแนน",
    encerraEm: "ปิด {{quando}}",
    encerrarAgora: "ปิดตอนนี้",
  },
  fixadas: {
    titulo: "ข้อความที่ปักหมุด",
    vazio: "ช่องนี้ยังไม่มีข้อความที่ปักหมุด",
    desafixar: "เลิกปักหมุด",
    anexo: "(ไฟล์แนบ)",
    enquete: "(โพล)",
    dicaRotulo: "เกร็ดน่ารู้:",
    dica: "ใครที่มีสิทธิ์ “จัดการข้อความ” ปักหมุดได้จากเมนูของข้อความโดยตรง",
  },
  encaminhar: {
    titulo: "ส่งต่อข้อความ",
    paraOnde: "ส่งไปที่ไหน",
    semTexto: "(ข้อความที่ไม่มีตัวอักษร)",
    nenhumLugar: "ไม่มีที่ชื่อนี้",
    canais: "ช่อง",
    conversas: "ข้อความส่วนตัว",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "ค้นใน Klipy",
    figurinha: "สติกเกอร์",
    buscarFigurinha: "หาสติกเกอร์ที่ใช่",
    buscarEmoji: "หาอีโมจิที่ใช่",
    buscarReacao: "หารีแอกชันที่ใช่",
    adicionarEmoji: "เพิ่มอีโมจิ",
    limparBusca: "ล้างการค้นหา",
  },
  busca: {
    fechar: "ปิดการค้นหา",
    procurando: "กำลังค้นหา…",
    resultado: "{{quantos}} รายการ",
    resultados: "{{quantos}} รายการ",
    nadaCom: "ไม่มีอะไรเกี่ยวกับ {{termo}} ตรงนี้",
    soOsQuePodeLer: "การค้นหาจะดูเฉพาะช่องที่คุณอ่านได้",
  },
  entrada: {
    titulo: "กล่องข้อความ",
    naoLidas: "ยังไม่อ่าน",
    salvas: "ที่บันทึกไว้",
    mencoes: "การกล่าวถึง",
    fimTitulo: "คุณมาถึงท้ายแล้ว",
    fimDetalhe: "ไม่เหลืออะไรให้อ่าน เมื่อมีข้อความใหม่มาถึง มันจะขึ้นตรงนี้",
    semSalvosTitulo: "ไม่มีรายการที่บันทึกไว้",
    semSalvosDetalhe: "กด Shift ค้างแล้วคลิกที่หมุดของข้อความ เพื่อเก็บไว้อ่านทีหลัง",
    tirarDosSalvos: "เอาออกจากที่บันทึกไว้",
    semMencoesTitulo: "ยังไม่มีการกล่าวถึง",
    semMencoesDetalhe: "การกล่าวถึงคุณจะขึ้นตรงนี้ย้อนหลัง 7 วัน",
  },
  forum: {
    descricao: "แต่ละหัวข้อกลายเป็นบทสนทนาแยกกัน — ดีสำหรับคำถามที่ไม่ควรหายไปกลางวงคุย",
    novoAssunto: "หัวข้อใหม่",
    vazio: "ยังไม่มีหัวข้อ เริ่มอันแรกแล้วบทสนทนาจะเป็นระเบียบตั้งแต่ต้น",
    titulo: "ชื่อเรื่อง",
    doQueSeTrata: "เรื่องอะไร",
    primeiraMensagem: "ข้อความแรก",
    conteDoCaso: "เล่าให้ฟัง",
  },
};
