export const perfil = {
  carregando: "กำลังโหลด…",
  editar: "แก้ไขโปรไฟล์",
  mensagem: "ข้อความ",
  abrirConversa: "เปิดการสนทนา",
  verCompleto: "ดูโปรไฟล์เต็ม",
  convidarParaServidor: "เชิญเข้าเซิร์ฟเวอร์",
  semServidores: "คุณยังไม่มีเซิร์ฟเวอร์",
  conviteEnviado: "ส่งคำเชิญให้ {{nome}} แล้ว",
  moderador: "เปิดในมุมมองผู้ดูแล",
  mais: "เพิ่มเติม",
  ignorar: "เพิกเฉย",
  deixarDeIgnorar: "เลิกเพิกเฉย",
  copiarId: "คัดลอก ID ผู้ใช้",
  idCopiado: "คัดลอก ID แล้ว",
  conexoes: "การเชื่อมต่อ",
  membroDesde: "เป็นสมาชิกตั้งแต่",
  sobre: "เกี่ยวกับ",
  cargosTitulo: "บทบาท",
  visaoGeral: "ภาพรวม",
  amigosEmComum: "เพื่อนร่วมกัน ({{quantidade}})",
  servidoresEmComum: "เซิร์ฟเวอร์ร่วมกัน ({{quantidade}})",
  amizade: {
    amigo: "เพื่อน",
    pedidoEnviado: "ส่งคำขอเป็นเพื่อนแล้ว",
    respondaAbaixo: "ส่งคำขอมาหาคุณ — ตอบด้านล่าง",
    adicionar: "เพิ่มเพื่อน",
    teMandouPedido: "ส่งคำขอเป็นเพื่อนมาหาคุณ",
    aceitar: "ยอมรับ",
    desfazer: "ลบออกจากเพื่อน",
    desfazerTitulo: "ลบ {{nome}} ออกจากเพื่อนของคุณไหม",
    desfazerDescricao: "คุณทั้งคู่จะไม่เป็นเพื่อนกันอีก ข้อความส่วนตัวยังอยู่ในประวัติ และคุณเพิ่มเขากลับมาได้ภายหลัง",
    bloquear: "บล็อก",
    bloquearTitulo: "บล็อก {{nome}} ไหม",
    bloquearDescricao: "คุณทั้งคู่จะไม่เป็นเพื่อนกันอีก ข้อความส่วนตัวจะไม่รับข้อความ และเขาจะส่งคำขอเป็นเพื่อนหาคุณไม่ได้อีก",
    linkCopiado: "คุณทั้งคู่ไม่ได้เป็นเพื่อนกัน — คัดลอกลิงก์ไว้แล้ว ส่งเองได้เลย",
  },
  recado: {
    escrever: "เขียนถึง @{{usuario}}",
    enviar: "ส่ง",
    enviada: "ส่งข้อความแล้ว",
    falhou: "ส่งไม่สำเร็จ ลองจากหน้าสนทนา",
  },
  cartao: {
    trocarFaixa: "เปลี่ยนแบนเนอร์ของการ์ด",
    trocarFaixaCurto: "เปลี่ยนแบนเนอร์",
    trocarFoto: "เปลี่ยนรูปโปรไฟล์",
    trocarFotoCurto: "เปลี่ยนรูป",
    suaEtiqueta: "แท็กของคุณ",
    editarEtiqueta: "คลิกเพื่อแก้ไขแท็กของคุณ",
    conteAlgo: "เล่าอะไรเกี่ยวกับตัวคุณหน่อย",
    adicionarStatus: "เพิ่มสถานะ",
    adicionarDescricao: "คลิกเพื่อเพิ่มคำอธิบาย",
    cargo: "บทบาท",
    cargos: "บทบาท",
    cargosCom: "บทบาท — {{quantidade}}",
    tirarCargo: "เอาบทบาท {{cargo}} ออก",
  },
  cargos: {
    adicionar: "เพิ่มบทบาท",
    procurar: "ค้นหาบทบาท",
  },
  etiqueta: {
    escolher: "เลือกแท็กเซิร์ฟเวอร์",
    nenhuma: "ไม่มีแท็กเซิร์ฟเวอร์",
    semEtiqueta: "ไม่มีเซิร์ฟเวอร์ไหนของคุณที่มีแท็ก",
  },
  emblemas: {
    doServidor: "เหรียญตราของเซิร์ฟเวอร์นี้",
    limite: "คุณติดเหรียญตราได้สูงสุด {{quantidade}} อัน",
  },
  nota: {
    vazia: "คลิกเพื่อจดอะไรสักอย่าง",
    rotulo: "บันทึก (เห็นคนเดียว)",
  },
  status: {
    titulo: "สถานะ",
    definir: "ตั้งสถานะของคุณ",
    escolherEmoji: "เลือกอีโมจิ",
    tirarEmoji: "เอาอีโมจิออก",
    oQuePensa: "กำลังคิดอะไรอยู่",
    limparAgora: "ล้างสถานะตอนนี้",
    naoLimpar: "ไม่ต้องล้าง",
    limpar30m: "ล้างใน 30 นาที",
    limpar1h: "ล้างใน 1 ชั่วโมง",
    limpar4h: "ล้างใน 4 ชั่วโมง",
    limparHoje: "ล้างวันนี้",
    limparAmanha: "ล้างพรุ่งนี้",
    comHora: "{{prazo}} {{hora}} น.",
  },
  presenca: {
    disponivel: "ว่าง",
    ausente: "ไม่อยู่",
    naoPerturbar: "ห้ามรบกวน",
    naoPerturbarDetalhe: "คุณจะไม่ได้รับแจ้งเตือนข้อความใหม่",
    invisivel: "ล่องหน",
    invisivelDetalhe: "คนอื่นจะเห็นคุณออฟไลน์",
  },
  menu: {
    mudarDeConta: "สลับบัญชี",
    gerenciarContas: "จัดการบัญชี",
  },
  editor: {
    decoracao: "เปลี่ยนของตกแต่งรูปโปรไฟล์",
    naoSalvo: "อย่าลืมบันทึกการเปลี่ยนแปลง",
    principal: "โปรไฟล์หลัก",
  },
};
