export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "ตั้งค่าเซิร์ฟเวอร์",
  auditoria: {
    todasAsAcoes: "ทุกการกระทำ",
    todosOsUsuarios: "ผู้ใช้ทั้งหมด",
    filtroMembros: "สมาชิก",
    filtroCanais: "ช่อง",
    filtroEmojis: "อีโมจิ",
    filtroServidor: "เซิร์ฟเวอร์",
    titulo: "บันทึกการกระทำ",
    porUsuario: "กรองตามคน",
    porAcao: "กรองตามการกระทำ",
    vazio: "ยังไม่มีอะไรถูกบันทึกด้วยตัวกรองนี้",
    motivo: "เหตุผล:",
  },
  banimentos: {
    titulo: "รายชื่อผู้ถูกแบนของเซิร์ฟเวอร์",
    descricao: "คนที่อยู่ตรงนี้กลับเข้ามาไม่ได้ แม้จะมีคำเชิญใหม่ การปลดแบนคืนสิทธิ์เข้าถึงทันที",
    procurar: "ค้นหาการแบนด้วยชื่อผู้ใช้",
    vazioTitulo: "ไม่มีการแบน",
    vazio: "คุณยังไม่ได้แบนใคร… แต่ถ้าวันไหนจำเป็น อย่าลังเล",
    desbanir: "ปลดแบน",
  },
  excluir: {
    tudoVai: "ทุกช่อง ข้อความ และคำเชิญของ {{servidor}} จะถูกลบสำหรับสมาชิก {{membros}} คน หลังจากนั้นไม่มีใครกู้คืนได้",
    digite: "พิมพ์ {{servidor}} เพื่อยืนยัน",
    titulo: "ลบเซิร์ฟเวอร์",
    aviso: "ย้อนกลับไม่ได้",
  },
  emblemas: {
    apagarDescricao: "มันจะหลุดจากทุกคนที่ใช้อยู่ ย้อนกลับไม่ได้",
    titulo: "ตรา",
    vazio: "ยังไม่มีตรา",
    novo: "ตราใหม่",
  },
  convites: {
    revogarTitulo: "เพิกถอนคำเชิญไหม",
    revogarAcao: "เพิกถอน",
    revogarDescricao: "ลิงก์ {{codigo}} จะใช้ไม่ได้ทันที คนที่เข้ามาด้วยลิงก์นี้แล้วยังอยู่ในเซิร์ฟเวอร์",
    titulo: "คำเชิญ",
    descricao: "ลิงก์คำเชิญที่ใช้งานอยู่ทั้งหมดของเซิร์ฟเวอร์นี้",
    vazio: "ยังไม่ได้สร้างคำเชิญ",
    revogar: "เพิกถอนคำเชิญ",
  },
  integracoes: {
    opcionais: "username และ avatar_url ไม่บังคับ และมีผลต่อข้อความแต่ละอัน ขีดจำกัดคือ 5 ข้อความทุก 5 วินาที",
    apagarDescricao: "URL จะใช้ไม่ได้ทันที ข้อความที่ส่งไปแล้วยังอยู่ในช่อง",
    titulo: "การเชื่อมต่อ",
    descricao: "เว็บฮุคคือที่อยู่ที่โพสต์ลงช่องได้โดยไม่ต้องมีบัญชี ใช้บอกว่าบิลด์ผ่าน มีคนเปิดเรื่องแจ้ง หรืออะไรก็ตามที่คุณอยากส่งจากสคริปต์",
    novo: "เว็บฮุคใหม่",
    vazio: "ยังไม่มีเว็บฮุค สร้างสักอันแล้ววาง URL ไว้ตรงที่คุณอยากให้ข้อความมาจาก",
    canal: "ช่อง",
    apagar: "ลบเว็บฮุค",
    comoUsar: "วิธีใช้",
    comoUsarTexto: "ส่ง POST เป็น JSON:",
  },
  engajamento: {
    semCanal: "ไม่มีช่องระบบ",
    titulo: "ความมีชีวิตชีวา",
    descricao: "สิ่งที่เซิร์ฟเวอร์ทำเองเพื่อไม่ให้ดูว่างเปล่าตอนมีคนใหม่เข้ามา",
    sistema: "ข้อความระบบ",
    boasVindas: "ส่งข้อความต้อนรับเมื่อมีคนเข้าร่วม",
    sorteio: "ถ้าไม่มีข้อความของคุณด้านล่าง ประโยคจะถูกสุ่ม — ประโยคเดิมซ้ำ ๆ เบื่อเร็ว",
    canalDoSistema: "ช่องข้อความระบบ",
    mensagem: "ข้อความต้อนรับ",
    deixeVazio: "เว้นว่างไว้เพื่อสุ่มจากประโยคสำเร็จรูป",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "ตัวกรองที่ดูแลเอง ก่อนที่ข้อความจะเกิดขึ้นด้วยซ้ำ คนที่ดูแลเซิร์ฟเวอร์ไม่เคยถูกกรอง — และบทบาทที่ได้รับยกเว้นก็ผ่านไปตรง ๆ",
    palavras: {
      titulo: "บล็อกคำของคุณเอง",
      descricao: "รายการคำที่ไม่มีใครเขียนได้",
    },
    mencoes: {
      titulo: "บล็อกสแปมการกล่าวถึง",
      descricao: "บล็อกข้อความที่มีการกล่าวถึงมากเกินไปในครั้งเดียว",
    },
    links: {
      titulo: "บล็อกลิงก์",
      descricao: "กันทุกที่อยู่ที่วางลงในแชท",
    },
    definir: "ตั้งค่า",
    nomeDaRegra: "ชื่อกฎ",
    bloqueadas: "คำที่บล็อก",
    digiteEnter: "พิมพ์แล้วกด Enter",
    comparacao: "การเทียบไม่สนตัวพิมพ์ใหญ่ วรรณยุกต์ และเครื่องหมายวรรคตอน — และไม่จับคำที่อยู่ในคำอื่น",
    aPartirDe: "บล็อกตั้งแต่กี่การกล่าวถึง",
    oQueFazer: "ให้ทำอะไร",
    canalDoAlerta: "ช่องแจ้งเตือน",
    escolhaCanal: "เลือกช่อง",
    castigo: "ปิดเสียง (นาที)",
    isentos: "บทบาทที่ยกเว้น",
    semCargos: "ยังไม่ได้สร้างบทบาท",
    salvarRegra: "บันทึกกฎ",
    apagar: "ลบกฎ",
    excluirTitulo: "ลบกฎ AutoMod นี้ไหม",
    excluirDescricao: "เซิร์ฟเวอร์จะหยุดกรองตามกฎนี้ทันที สร้างใหม่ได้ แต่การตั้งค่าปัจจุบันจะหายไป",
    excluirAcao: "ลบกฎ",
  },
  cargos: {
    titulo: "บทบาท",
    descricao: "บทบาทให้ชื่อ สี และอำนาจ ใครอยู่สูงกว่าในรายการก็เหนือกว่าคนที่อยู่ต่ำกว่า — และไม่มีใครแตะบทบาทที่เท่าหรือสูงกว่าของตัวเอง",
    criar: "สร้างบทบาท",
    vazio: "ยังไม่มีบทบาท",
    abaExibicao: "การแสดงผล",
    abaPermissoes: "สิทธิ์",
    abaMembros: "สมาชิก — {{quantos}}",
    everyone: "ใช้กับทุกคนในเซิร์ฟเวอร์ เป็นฐานที่บทบาทอื่นซ้อนทับ",
    nomeDoCargo: "ชื่อบทบาท",
    cor: "สีของบทบาท",
    corDica: "ระบายสีชื่อคนที่มีบทบาทนี้ในรายชื่อสมาชิกและในแชท",
    semCor: "ไม่มีสี",
    corPersonalizada: "สีกำหนดเอง",
    estilo: "สไตล์ของชื่อ",
    segundaCor: "สีที่สอง",
    segundaCorDica: "ถ้าไม่มี ไล่สีจะกลายเป็นสีเดียว — ไม่ได้หายไป",
    limparSegundaCor: "ล้างสีที่สอง",
    icone: "ไอคอน",
    iconeDica: "ปรากฏข้างบทบาทในการ์ดโปรไฟล์ของคนที่มี",
    exibirSeparado: "แสดงแยกจากสมาชิกคนอื่น",
    exibirSeparadoDica: "บทบาทจะได้ส่วนของตัวเองในรายชื่อสมาชิก",
    permitirMencionar: "อนุญาตให้กล่าวถึงบทบาทนี้",
    permitirMencionarDica: "ใครก็ได้จะแจ้งเตือนทุกคนที่มีบทบาทนี้ได้",
    semPoderDeConceder: "{{descricao}} (คุณไม่มีสิทธิ์นี้ที่จะให้)",
    adicionar: "เพิ่มใครสักคนเข้าบทบาทนี้",
    tirar: "เอาบทบาทออก",
    semNinguem: "ยังไม่มีใครมีบทบาทนี้",
    apagar: "ลบบทบาท",
    excluirTitulo: "ลบบทบาท \"{{nome}}\" ไหม",
    excluirDescricao: "คนที่มีบทบาทนี้จะเสียทุกอย่างที่ได้จากมัน ย้อนกลับไม่ได้",
    excluirAcao: "ลบบทบาท",
  },
  membros: {
    procurar: "ค้นด้วยชื่อหรือชื่อผู้ใช้",
    membroDesde: "เป็นสมาชิกตั้งแต่",
    vazio: "ไม่พบใคร",
    acoesPara: "การกระทำสำหรับ {{nome}}",
    deCastigo: "ปิดเสียง",
    tirarCastigo: "ยกเลิกการปิดเสียง",
    castigo5min: "5 นาที",
    castigo1h: "1 ชั่วโมง",
    castigo1d: "1 วัน",
    castigo1s: "1 สัปดาห์",
    expulsar: "เตะออก",
    expulsarTitulo: "เตะ {{nome}} ออกไหม",
    expulsarDescricao: "ออกจาก {{servidor}} ทันที กลับมาได้ด้วยคำเชิญ — การเตะไม่ได้กันการกลับมา",
    banir: "แบน",
    banirTitulo: "แบน {{nome}} ไหม",
    banirDescricao: "ออกจาก {{servidor}} และกลับมาไม่ได้ แม้จะมีคำเชิญ จนกว่าจะปลดแบน",
    motivo: "เหตุผล (ไม่บังคับ)",
    motivoDica: "ถูกบันทึกในบันทึกการกระทำ",
  },
  perfil: {
    titulo: "โปรไฟล์เซิร์ฟเวอร์",
    descricao: "เซิร์ฟเวอร์ของคุณปรากฏแบบนี้ในรายการและในลิงก์คำเชิญ",
    icone: "ไอคอน",
    faixa: "แบนเนอร์ด้านบน",
    nomeDoServidor: "ชื่อเซิร์ฟเวอร์",
    campoDescricao: "คำอธิบาย",
    doQueE: "เซิร์ฟเวอร์นี้เกี่ยวกับอะไร",
    comprimido: "บีบอัดก่อนอัปโหลด: {{economia}}",
  },
  etiqueta: {
    titulo: "แท็กเซิร์ฟเวอร์",
    descricao: "ป้ายไม่เกิน 4 ตัวอักษรที่ปรากฏข้างชื่อของสมาชิกทุกคน — ในแชทและในรายชื่อคน ที่นี่ฟรี: ไม่มีบูสต์ ไม่มีระดับ",
    escolhaNome: "เลือกชื่อ",
    limite: "ไม่เกิน 4 ตัวอักษร ตัวอักษรและตัวเลข",
    escolhaInsignia: "เลือกตรา",
    voce: "คุณ",
    fala1: "มีใครอยากเล่นไหม",
    fala2: "ดูแท็กของเราสิ",
    fala3: "โห ได้มายังไงเนี่ย",
  },
  expressoes: {
    comoUsar: "เพิ่มอีโมจิได้ถึง {{limite}} ตัวที่ทุกคนใช้ได้ในเซิร์ฟเวอร์นี้ พิมพ์ :ชื่อ: ในแชทเพื่อส่ง",
    imagem: "รูปภาพ",
    enviadoPor: "อัปโหลดโดย",
    semEmoji: "ยังไม่มีอีโมจิ",
    figurinhas: "สติกเกอร์",
    enviarFigurinha: "อัปโหลดสติกเกอร์",
    nomeDaFigurinha: "ชื่อสติกเกอร์",
    exemploFigurinha: "เช่น กอดลูกแมว",
    figurinhaGrande: "สติกเกอร์เกิน {{limite}}",
    deixaPraLa: "ช่างเถอะ",
    sons: "แผงเสียง",
    enviarSom: "อัปโหลดเสียง",
    nomeDoSom: "ชื่อเสียง",
    semSom: "ยังไม่มีเสียง",
    somGrande: "เสียงเกิน {{limite}}",
    emojiRelacionado: "อีโมจิที่เกี่ยวข้อง",
    ouvir: "ฟัง",
    ouvirAssim: "ฟังแบบนี้",
    volumeDe: "ระดับเสียงของ {{nome}}",
    volumeDica: "ใช้กับทุกคนในเซิร์ฟเวอร์ แต่ละคนยังลดเสียงเฉพาะของตัวเองได้ในแผงของสาย",
    falhaEnvio: "อัปโหลดไฟล์ไม่สำเร็จ",
    excluirTitulo: "ลบ {{tipo}} \"{{nome}}\" ไหม",
    excluirDescricao: "หายไปจากเซิร์ฟเวอร์สำหรับทุกคน ข้อความที่เคยใช้ไปแล้วยังคงอยู่เหมือนเดิม",
  },
  canal: {
    visaoGeral: "ภาพรวม",
    nome: "ชื่อช่อง",
    topico: "หัวข้อของช่อง",
    topicoDica: "ที่นี่คุยเรื่องอะไรกัน",
    modoLento: "แต่ละคนส่งได้ข้อความเดียวต่อช่วงเวลา ใครที่จัดการข้อความหรือช่องผ่านไปได้เลย",
    visibilidade: "การมองเห็นเนื้อหา",
    padrao: "ค่าเริ่มต้น",
    padraoDica: "เนื้อหาของช่องมองเห็นได้เสมอ",
    spoiler: "ช่องสปอยล์",
    spoilerDica: "ทำเครื่องหมายว่าช่องนี้มีสปอยล์ เพื่อให้จุดหักมุมและเรื่องหนัก ๆ ถูกซ่อนไว้จนกว่าจะมีคนเลือกดู",
    idade: "ช่องจำกัดอายุ",
    idadeDica: "คนที่เข้ามาต้องยืนยันว่าบรรลุนิติภาวะจึงจะเห็นเนื้อหา",
    bitrateDica: "เกิน 64 kbps อาจรบกวนคนที่เน็ตไม่ดี",
    qualidadeDeVideo: "คุณภาพวิดีโอ",
    automatica: "อัตโนมัติ",
    limite: "จำกัดผู้ใช้ — {{valor}}",
    pessoas: "{{quantos}} คน",
    semLimite: "ไม่จำกัด",
    permissoesDescricao: "ที่นี่คุณเปลี่ยนสิ่งที่ใช้ในช่องนี้ อะไรที่ค้างไว้ที่ “สืบทอด” ก็ยังตามบทบาทต่อไป",
    excluir: {
      titulo: "ลบช่อง",
      historico: "ประวัติทั้งหมดของ {{canal}} ไปด้วยกัน สำหรับทุกคน",
      digite: "พิมพ์ {{canal}} เพื่อยืนยัน",
    },
  },
  moderacao: {
    titulo: "มุมมองผู้ดูแล",
    semPermissao: "คุณต้องมีสิทธิ์ “ดูแลสมาชิก” จึงจะเห็นสิ่งนี้",
    fecharEsc: "ปิด (Esc)",
    atividade: "กิจกรรมในเซิร์ฟเวอร์",
    mensagens: "ข้อความ",
    links: "ลิงก์",
    midia: "สื่อ",
    acoesNaAuditoria: "การกระทำในบันทึก",
    moderacoesSofridas: "การลงโทษที่ได้รับ",
    permissoes: "สิทธิ์ ({{quantas}})",
    semPermissaoEspecial: "ไม่มีสิทธิ์พิเศษ",
    conta: "บัญชี",
    entrouNoServidor: "เข้าเซิร์ฟเวอร์เมื่อ",
    contaCriadaEm: "สร้างบัญชีเมื่อ",
    deCastigoAte: "ปิดเสียงจนถึง",
    formaDeAdesao: "เข้ามาได้อย่างไร",
    mensagem: "ข้อความ",
    castigo: "ปิดเสียง",
    copiarId: "คัดลอก ID",
    idCopiado: "คัดลอก ID แล้ว",
    adicionarCargo: "เพิ่มบทบาท",
    semCargos: "ยังไม่ได้สร้างบทบาท",
    soEveryone: "เฉพาะ @everyone",
    voltar: "กลับ",
    vazio: "ไม่มีอะไรตรงนี้",
    cinquenta: "แสดง 50 รายการล่าสุด",
    irParaMensagem: "ไปที่ข้อความ",
    precisaSerAmigo: "พวกคุณต้องเป็นเพื่อนกันก่อนจึงจะคุยได้",
    expulsarDescricao: "ออกจากเซิร์ฟเวอร์ทันที แต่กลับมาได้ด้วยคำเชิญ",
    banirDescricao: "ออกจากเซิร์ฟเวอร์และกลับมาไม่ได้ แม้จะมีคำเชิญ จนกว่าจะปลดแบน",
    castigarTitulo: "ปิดเสียง {{nome}} ไหม",
    castigoDescricao: "ตราบที่ยังอยู่ จะเขียนหรือพูดในช่องไหนของเซิร์ฟเวอร์ก็ไม่ได้",
    aplicarCastigo: "ใช้การปิดเสียง",
    duracao: "ระยะเวลาเป็นนาที",
    informeDuracao: "ระบุระยะเวลาเป็นนาที",
  },
  abas: {
    expressoes: "การแสดงออก",
    pessoas: "ผู้คน",
    apps: "แอป",
    moderacao: "การดูแล",
    banimentos: "การแบน",
  },
};
