export const amizades = {
  ativosAgora: "目前活躍",
  procurando: "看看誰在…",
  tudoTranquilo: "暫時很安靜…",
  tudoTranquiloDetalhe: "當你或朋友加入通話時，會顯示在這裡，一鍵就能加入。",
  emVoz: "語音中",
  voce: "你",
  soVoce: "只有你",
  pessoas: "{{quantas}} 人",
  voltarParaChamada: "回到通話",
  entrarNaChamada: "加入通話",
  abrirCanal: "在 {{servidor}} 開啟 {{canal}}",
  mensagensDiretas: "私訊",
  encontreConversa: "尋找對話",
  amigos: "好友",
  conversas: "對話",
  semConversas: "還沒有對話。加個好友開始吧。",
  semConversaComEsseNome: "沒有這個名字的對話。",
  abrirMenu: "開啟伺服器和對話",
  solicitacoes: "訊息請求",
  pedidos: "請求",
  spam: "垃圾",
  pedidosPendentes: "待處理請求",
  marcadosComoSpam: "已標記為垃圾",
  aceitar: "接受",
  ignorar: "忽略",
  marcarSpam: "標記為垃圾",
  semPedidos: "沒有待處理的請求。",
  semPedidosDetalhe: "不是你好友但與你在同一伺服器的人，會先到這裡，再進入你的對話。",
  semSpam: "沒有標記為垃圾的內容。",
  semSpamDetalhe: "垃圾過濾器挑出來的，或你自己標記的，都留在這個分頁裡。",
  umServidorEmComum: "1 個共同伺服器",
  servidoresEmComum: "{{quantos}} 個共同伺服器",
  semServidoresEmComum: "沒有共同伺服器",
};
