export const chamada = {
  conectando: "正在連線到通話…",
  naoEntrou: "沒能加入通話",
  sair: "離開通話",
  sairDaVoz: "離開語音通話",
  desconectar: "中斷連線",
  voltar: "回到通話",
  voltarAosQuadros: "回到通話畫面",
  fecharChat: "關閉聊天",
  carregandoPrevia: "正在載入預覽…",
  maisOpcoes: "更多選項",
  deVideo: "視訊通話",
  deVoz: "語音通話",
  alguem: "某人",
  volume: {
    entrada: "輸入音量",
    saida: "輸出音量",
    live: "直播音量",
    liveComPorcento: "直播音量（{{porcento}}%）",
    liveSemSom: "直播已靜音",
  },
  aparelhos: {
    entrada: "輸入裝置",
    saida: "輸出裝置",
    camera: "攝影機",
    microfone: "麥克風",
    saidaCurto: "輸出",
    oDoSistema: "跟隨系統",
    aDoSistema: "跟隨系統",
    semEscolhaDeSaida: "這個瀏覽器不讓你選輸出 — 由系統決定。",
    espelhar: "鏡像我的攝影機",
    configEntrada: "輸入設定",
    configSaida: "輸出設定",
    configCamera: "攝影機設定",
    configAudioEVideo: "音訊與視訊設定",
  },
  tela: {
    compartilhar: "分享螢幕",
    compartilharAcao: "分享",
    cancelar: "取消",
    telas: "螢幕",
    janelas: "視窗",
    somDoComputador: "把電腦的聲音一起帶上",
    somDoSistema: "把系統的聲音一起帶上",
    configCompartilhamento: "分享設定",
    mostrarSemVideo: "顯示沒開視訊的人",
    semFontes: "系統沒有回傳任何可分享的螢幕或視窗。",
    pararDeCompartilhar: "停止分享",
    encerrarTransmissao: "結束直播",
  },
  live: {
    etiqueta: "直播中",
    etiquetaMaiuscula: "直播中",
    assistir: "觀看直播",
    assistirPessoa: "觀看 {{nome}}",
    pararDeAssistir: "停止觀看",
  },
  membro: {
    mudarMeuApelido: "修改我的暱稱",
    meuMicrofone: "我的麥克風",
    ouvirChamada: "收聽通話",
    copiarMeuId: "複製我的 ID",
    idCopiado: "已複製 ID。",
    mensagem: "訊息",
    silenciar: "靜音",
    alterarApelido: "修改暱稱",
    cargos: "身分組",
    semCargo: "還沒有建立身分組",
    moverPara: "移動到",
    silenciarNoServidor: "在伺服器中靜音語音",
    desativarAudioNoServidor: "在伺服器中關閉音訊",
    desconectar: "中斷連線",
    apelidoTitulo: "你在這個伺服器的暱稱",
    apelidoDeAlguem: "{{nome}} 的暱稱",
    apelidoCampo: "暱稱",
    apelidoDicaPropria: "只在這裡生效。留空就恢復成你平常的名字。",
    apelidoDicaDeOutro: "只在這個伺服器生效。留空即可恢復原本的名字。",
  },
  detalhes: {
    abrir: "語音詳情",
    titulo: "語音詳情",
    conexao: "連線",
    pingMedio: "平均延遲",
    ultimoPing: "最近延遲",
    perda: "傳送封包遺失",
    medindo: "測量中…",
    criptografado: "加密到伺服器為止（DTLS-SRTP）",
    explicacao: "超過 250 毫秒就聽得出對話的延遲，大家會開始搶話。封包遺失超過 10% 會讓聲音變得機械。這兩種情況的問題幾乎都出在你和網路之間：試試用網路線代替 Wi-Fi，或者重開路由器。",
  },
  microfone: {
    bloqueado: "麥克風被封鎖 — 你只能聽。請在瀏覽器權限裡允許存取。",
    bloqueadoNoMac: "macOS 正在封鎖麥克風。請勾選",
    caminhoNoMac: "系統設定 → 隱私權與安全性 → 麥克風",
    abrirAjustes: "開啟設定",
    vaiReabrir: "macOS 會要求你重新開啟應用程式。",
    naoAbriu: "沒能開啟麥克風 — 你只能聽。請在 設定 → 語音與視訊 裡檢查裝置。",
  },
  gravacaoDeTela: {
    bloqueada: "macOS 還沒有允許螢幕錄製。沒有它，分享出來是黑的。",
    marque: "請勾選",
    reabra: "在「螢幕錄製」裡打開，然後重新開啟應用程式。",
  },
  ruido: {
    titulo: "降噪",
    explicacao: "把背景噪音從你的聲音裡去掉。說話時試著拍拍手或拖動鍵盤 — 通話裡的人只會聽到你。",
    semSuporte: "這個瀏覽器跑不了進階降噪。瀏覽器內建的仍然有效，只是比較弱。",
    aplicando: "正在套用到通話…",
    faleParaTestar: "說話來測試",
    verdeQuandoPassa: "聲音通過時會變綠。",
    teOuvindo: "現在他們聽得到你。",
    feitoCom: "技術來自",
    aquiNoAparelho: "，就在你的裝置上",
    ajustes: "設定",
  },
  permissoes: {
    titulo: "macOS 權限",
    detalhe: "macOS 只問一次，之後只能在它自己的面板裡改。這裡可以看到目前生效的狀況，並解決缺少的部分。",
    concedida: "已授予",
    negada: "已拒絕",
    naoPedida: "未請求",
    permitir: "允許",
    abrirAjustes: "開啟設定",
    microfone: "麥克風",
    microfoneDetalhe: "在通話中說話，並測試你的輸入。",
    camera: "攝影機",
    cameraDetalhe: "在通話中開啟視訊。",
    tela: "螢幕錄製",
    telaDetalhe: "分享螢幕和視窗。",
    monitoramento: "輸入監聽",
    monitoramentoDetalhe: "即使 Gravaê 在背景也能使用按鍵通話。",
  },
  jaConectado: {
    titulo: "你已經在這個通話裡了",
    trazer: "把通話轉到這裡",
    deixar: "維持原樣",
    detalhe: "轉到這裡後，另一端會退出通話 — 你的帳號一次只在一個地方。",
  },
};
