export const comum = {
  carregando: "載入中…",
  salvar: "儲存",
  salvando: "正在儲存…",
  descartar: "捨棄",
  redefinir: "重設",
  naoSalvo: "你有尚未儲存的變更。",
  fechar: "關閉",
  criar: "建立",
  nome: "名稱",
  emoji: "表情符號",
  previa: "預覽",
  cancelar: "取消",
  enviar: "傳送",
  apagar: "刪除",
  excluir: "刪除",
  remover: "移除",
  trocar: "更換",
};
