export const configuracoes = {
  efeitos: {
    titulo: "指標效果",
    detalhe: "畫在介面上層的拖尾和火花。預設關著，你要求減少動效時它們會自己退場。",
    rastro: "游標拖尾",
    rastroDetalhe: "跟著指標跑、在後面漸漸淡掉的一條線。",
    faisca: "點擊火花",
    faiscaDetalhe: "從你點下去的地方甩出來的短線。",
    cor: "顏色",
    espessura: "粗細",
    comprimento: "長度",
    tamanho: "大小",
    quantidade: "數量",
  },
  email: {
    verificarTitulo: "確認你的信箱",
    verificarDetalhe: "有些社群只讓確認過的人發言。點一下就好。",
    enviar: "發送連結",
    enviado: "去收件匣看看。連結一天內有效。",
    falhou: "郵件沒能寄出去。",
    confirmado: "信箱已確認",
    confirmadoDetalhe: "好了。凡是要求這一步的社群，你現在都能發言。",
    linkIncompleto: "連結不完整",
    linkIncompletoDetalhe: "網址裡少了驗證碼。請直接從郵件裡開啟連結。",
    confirmando: "確認中…",
    expirou: "這個連結已經用過，或者過期了。",
    irParaOApp: "前往應用",
  },
  tema: {
    indisponivel: "主題無法使用",
    indisponivelDetalhe: "發布的人刪掉了，或者連結錯了。",
    indisponivelLinha: "主題無法使用。發布的人刪掉了，或者連結錯了。",
    importar: "匯入主題",
    importarCurto: "匯入",
    importarDetalhe: "這會取代你現在的主題。之後可以在 設定 > 外觀 > 主題工作室 裡修改。",
    porAutor: "作者 {{autor}}",
    umaCorTrocada: "換了 1 種顏色",
    coresTrocadas: "換了 {{quantas}} 種顏色",
    avisoDeCss: "這個主題帶著作者寫的 CSS，而 CSS 能碰到畫面的每個角落。只從你信得過的人那裡匯入。",
    soCores: "這個主題只換顏色，沒有外來的 CSS。",
    aplicar: "套用",
    previaSemMotor: "預覽不會跑引擎，裝上才看得到。",
    motorAnimado: "{{motor}} 動態",
  },
  sair: "登出",
  versoes: {
    termos: "服務條款",
    privacidade: "隱私政策",
    copiar: "點一下複製",
    copiado: "已複製",
  },
  telas: {
    conta: "我的帳號",
    privacidade: "隱私",
    conexoes: "連結",
    voz: "音訊",
    video: "視訊",
    avisos: "通知",
    aplicativos: "應用程式",
    aparencia: "外觀",
    batePapo: "聊天",
    acessibilidade: "無障礙",
    idioma: "語言",
    aplicativo: "下載應用程式",
    atalhos: "快捷鍵",
    desktop: "桌面應用程式",
    avancado: "進階",
    servidor: "伺服器",
    comunicado: "系統公告",
    denuncias: "檢舉",
    publicacoes: "部署",
  },
  grupos: {
    conta: "帳號",
    app: "應用程式設定",
    desenvolvedor: "開發者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "登入資訊",
    dispositivos: "裝置",
    usuariosBloqueados: "已封鎖的使用者",
    aplicativosAutorizados: "已授權的應用程式",
    sessoes: "工作階段",
    amigosEDms: "好友與私訊",
    compartilhamentoDeAtividade: "活動分享",
    visibilidadeDoPerfil: "個人檔案可見度",
    exportarDados: "匯出資料",
    exclusaoDeDados: "刪除資料",
    tema: "主題",
    corDeDestaque: "強調色",
    interface: "介面",
    listaDeCanais: "頻道清單",
    zoomDoApp: "應用程式縮放層級",
    escalaDaFonte: "聊天字型大小",
    modoStreamer: "直播隱私",
    cursores: "游標",
    movimento: "動態效果",
    textoEmVoz: "文字轉語音",
    teclado: "鍵盤",
    formatoDaHora: "時間格式",
    idiomaDaInterface: "介面語言",
    dispositivosDeVoz: "裝置",
    testeDoMicrofone: "麥克風測試",
    modoDeEntrada: "輸入模式",
    sensibilidade: "輸入靈敏度",
    qualidade: "品質",
    camera: "攝影機",
    transmissao: "直播",
    exibicao: "顯示",
    entrada: "輸入",
    midia: "媒體",
    geral: "一般",
    preferenciaDeMencao: "提及偏好",
    sons: "音效",
  },
};
