export const configuracoes = {
  efeitos: {
    titulo: "指標效果",
    detalhe: "畫在介面上層的拖尾和火花。預設關著，你要求減少動效時它們會自己退場。",
    rastro: "游標拖尾",
    rastroDetalhe: "跟著指標跑、在後面漸漸淡掉的一條線。",
    faisca: "點擊火花",
    faiscaDetalhe: "從你點下去的地方甩出來的短線。",
    cor: "顏色",
    espessura: "粗細",
    comprimento: "長度",
    tamanho: "大小",
    quantidade: "數量",
  },
  email: {
    verificarTitulo: "確認你的信箱",
    verificarDetalhe: "有些社群只讓確認過的人發言。點一下就好。",
    enviar: "發送連結",
    enviado: "去收件匣看看。連結一天內有效。",
    falhou: "郵件沒能寄出去。",
    confirmado: "信箱已確認",
    confirmadoDetalhe: "好了。凡是要求這一步的社群，你現在都能發言。",
    linkIncompleto: "連結不完整",
    linkIncompletoDetalhe: "網址裡少了驗證碼。請直接從郵件裡開啟連結。",
    confirmando: "確認中…",
    expirou: "這個連結已經用過，或者過期了。",
    irParaOApp: "前往應用",
  },
  tema: {
    indisponivel: "主題無法使用",
    indisponivelDetalhe: "發布的人刪掉了，或者連結錯了。",
    indisponivelLinha: "主題無法使用。發布的人刪掉了，或者連結錯了。",
    importar: "匯入主題",
    importarCurto: "匯入",
    importarDetalhe: "這會取代你現在的主題。之後可以在 設定 > 外觀 > 主題工作室 裡修改。",
    porAutor: "作者 {{autor}}",
    umaCorTrocada: "換了 1 種顏色",
    coresTrocadas: "換了 {{quantas}} 種顏色",
    avisoDeCss: "這個主題帶著作者寫的 CSS，而 CSS 能碰到畫面的每個角落。只從你信得過的人那裡匯入。",
    soCores: "這個主題只換顏色，沒有外來的 CSS。",
    verCss: "檢視 CSS",
    esconderCss: "隱藏 CSS",
    aplicar: "套用",
    previaSemMotor: "預覽不會跑引擎，裝上才看得到。",
    motorAnimado: "{{motor}} 動態",
  },
  sair: "登出",
  versoes: {
    termos: "服務條款",
    privacidade: "隱私政策",
    copiar: "點一下複製",
    copiado: "已複製",
  },
  subscription: {
    seePlans: "查看方案",
    upgradeSubtitle: "寫訊息、傳檔案和直播都有更高上限與專屬功能。",
    perMonth: "每月",
    perYear: "每年",
    save: "省 {{percent}}%",
    howToPay: "你想怎麼付款？",
    legal: "付款後 7 天內可申請退款。付款由 Stripe 處理，我們永遠看不到你的卡號。",
    compare: "免費 vs Infinity",
    featureColumn: "功能",
    freeColumn: "免費",
    messageRow: "訊息字數上限",
    attachmentRow: "可傳送的檔案大小",
    screenRow: "影片畫質",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "你的 Infinity 有效至 {{date}}。",
    upsell: "用 Infinity 提高上限",
    screenUpsell: "用 Infinity 獲得更高畫質",
    free: "你正在使用免費方案。",
    activeUntil: "Infinity 有效至 {{date}}。",
    renews: "將於 {{date}} 自動續訂。",
    endsAt: "訂閱已取消，將於 {{date}} 結束。",
    pastDue: "上次扣款失敗。請更新卡片以免失去Infinity。",
    waiting: "正在確認付款…",
    subscribe: "訂閱",
    monthly: "按月",
    yearly: "按年",
    automatic: "卡片",
    manage: "管理付款",
    refund: "申請退款",
    refundDetail: "付款後 7 天內可以撤銷：{{amount}}，截至 {{date}}。",
    refundConfirm: "要申請退款嗎？",
    refundConfirmDetail: "款項會退回原付款方式，Infinity 會立即結束。",
    refunded: "已申請退款。",
    unavailable: "訂閱尚未開放。",
    success: "已收到付款，謝謝！",
    canceled: "付款已取消。",
    error: "發生錯誤，請再試一次。",
    no: "否",
    tagRow: "自訂使用者標籤",
    guildProfilesRow: "依社群設定的個人檔案",
    badgeRow: "個人檔案徽章",
    communitiesRow: "社群",
    savedRow: "已儲存的訊息",
    animatedEmojiRow: "動態表情",
    expressionsRow: "隨處使用表情和貼圖",
    animatedProfileRow: "動態頭像和橫幅",
    earlyAccessRow: "搶先體驗新功能",
    themesRow: "自訂主題",
    pixOption: "Pix",
    pixHint: "打開銀行 App，選擇 Pix，掃描 QR code 或複製貼上代碼。",
    pixQrAlt: "Pix QR code",
    pixCopy: "複製 Pix 代碼",
    pixCopied: "已複製 Pix 代碼",
    pixWaiting: "等待付款",
    pixExpiresIn: "{{time}} 後到期",
    pixExpired: "這筆 Pix 已到期，請重新產生後繼續。",
    pixNew: "重新產生 Pix",
    pixPaid: "已收到 Pix！你的 Infinity 已啟用。",
    forMe: "給自己",
    asGift: "當作禮物",
    buyGift: "購買禮物",
    giftReady: "禮物已就緒！複製連結傳給你想送的人。",
    giftClaimed: "禮物已兌換！Infinity 已加入你的帳號。",
    gifts: "禮物",
    giftsEmpty: "你還沒有購買過禮物。",
    giftCode: "禮物碼",
    giftRedeem: "兌換",
    giftCopyLink: "複製連結",
    giftLinkCopied: "已複製連結",
    giftClaimedBy: "由 {{name}} 兌換",
    giftHint: "有禮物碼嗎？在這裡兌換。你購買的禮物顯示在下方。",
    cardPaid: "付款成功！你的 Infinity 已啟用。",
    payAmount: "支付 {{amount}}",
    giftLinkTitle: "你收到了一份 {{plan}} 禮物！",
    giftLinkDetail: "點擊兌換，天數就會加到你的帳號。",
    pageTitle: "用 {{plan}} 解鎖更多特權",
  },
  telas: {
    subscription: "Infinity",
    conta: "我的帳號",
    privacidade: "隱私",
    conexoes: "連結",
    voz: "音訊",
    video: "視訊",
    avisos: "通知",
    aplicativos: "應用程式",
    aparencia: "外觀",
    batePapo: "聊天",
    acessibilidade: "無障礙",
    idioma: "語言",
    aplicativo: "下載應用程式",
    atalhos: "快捷鍵",
    desktop: "桌面應用程式",
    avancado: "進階",
    servidor: "伺服器",
    comunicado: "系統公告",
    denuncias: "檢舉",
    publicacoes: "部署",
  },
  grupos: {
    conta: "帳號",
    app: "應用程式設定",
    desenvolvedor: "開發者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "登入資訊",
    dispositivos: "裝置",
    usuariosBloqueados: "已封鎖的使用者",
    aplicativosAutorizados: "已授權的應用程式",
    sessoes: "工作階段",
    amigosEDms: "好友與私訊",
    compartilhamentoDeAtividade: "活動分享",
    visibilidadeDoPerfil: "個人檔案可見度",
    exportarDados: "匯出資料",
    exclusaoDeDados: "刪除資料",
    tema: "主題",
    corDeDestaque: "強調色",
    interface: "介面",
    listaDeCanais: "頻道清單",
    zoomDoApp: "應用程式縮放層級",
    escalaDaFonte: "聊天字型大小",
    modoStreamer: "直播隱私",
    cursores: "游標",
    movimento: "動態效果",
    textoEmVoz: "文字轉語音",
    teclado: "鍵盤",
    formatoDaHora: "時間格式",
    idiomaDaInterface: "介面語言",
    dispositivosDeVoz: "裝置",
    testeDoMicrofone: "麥克風測試",
    modoDeEntrada: "輸入模式",
    sensibilidade: "輸入靈敏度",
    qualidade: "品質",
    camera: "攝影機",
    transmissao: "直播",
    exibicao: "顯示",
    entrada: "輸入",
    midia: "媒體",
    geral: "一般",
    preferenciaDeMencao: "提及偏好",
    sons: "音效",
  },
};
