export const configuracoes = {
  sair: "登出",
  versoes: {
    copiar: "點一下複製",
    copiado: "已複製",
  },
  telas: {
    conta: "我的帳號",
    privacidade: "隱私",
    conexoes: "連結",
    voz: "音訊",
    video: "視訊",
    avisos: "通知",
    aplicativos: "應用程式",
    aparencia: "外觀",
    batePapo: "聊天",
    acessibilidade: "無障礙",
    idioma: "語言",
    aplicativo: "下載應用程式",
    atalhos: "快捷鍵",
    servidor: "伺服器",
  },
  grupos: {
    conta: "帳號",
    app: "應用程式設定",
    desenvolvedor: "開發者",
    administracao: "管理",
  },
  secoes: {
    detalhesDeLogin: "登入資訊",
    dispositivos: "裝置",
    usuariosBloqueados: "已封鎖的使用者",
    aplicativosAutorizados: "已授權的應用程式",
    sessoes: "工作階段",
    amigosEDms: "好友與私訊",
    compartilhamentoDeAtividade: "活動分享",
    visibilidadeDoPerfil: "個人檔案可見度",
    exportarDados: "匯出資料",
    exclusaoDeDados: "刪除資料",
    tema: "主題",
    corDeDestaque: "強調色",
    interface: "介面",
    listaDeCanais: "頻道清單",
    zoomDoApp: "應用程式縮放層級",
    escalaDaFonte: "聊天字型大小",
    modoStreamer: "直播隱私",
    movimento: "動態效果",
    textoEmVoz: "文字轉語音",
    teclado: "鍵盤",
    formatoDaHora: "時間格式",
    idiomaDaInterface: "介面語言",
    dispositivosDeVoz: "裝置",
    testeDoMicrofone: "麥克風測試",
    modoDeEntrada: "輸入模式",
    sensibilidade: "輸入靈敏度",
    qualidade: "品質",
    camera: "攝影機",
    transmissao: "直播",
    exibicao: "顯示",
    entrada: "輸入",
    midia: "媒體",
    geral: "一般",
    preferenciaDeMencao: "提及偏好",
    sons: "音效",
  },
};
