export const conversa = {
  lista: {
    carregando: "正在載入訊息…",
    carregandoMais: "載入中…",
    verMais: "往上捲動可看更多",
    semHistorico: "無法查看歷史紀錄",
    semHistoricoDetalhe: "你的身分組沒有讀取 #{{canal}} 歷史紀錄的權限。你在這裡的期間，新訊息仍會正常出現。",
    boasVindas: "歡迎來到 #{{canal}}",
    boasVindasDetalhe: "這裡是 #{{canal}} 頻道的開始。",
  },
  data: {
    hoje: "今天",
    ontem: "昨天",
    hojeAs: "今天 {{hora}}",
    ontemAs: "昨天 {{hora}}",
  },
  digitando: {
    um: "{{nome}} 正在輸入…",
    dois: "{{primeiro}} 和 {{segundo}} 正在輸入…",
    varios: "{{quantidade}} 人正在輸入…",
  },
  mensagem: {
    usou: "使用了",
    fixada: "已置頂",
    editado: "(已編輯)",
    ignorada: "來自你已忽略的人的訊息。",
    mostrar: "顯示",
    escPara: "按 Esc",
    cancelar: "取消",
    enterParaSalvar: "按 Enter 儲存",
    falhou: "沒有送出。重試",
    naoLidasDaqui: "已標記為從這裡開始未讀。",
    linkCopiado: "已複製連結。",
    idCopiado: "已複製 ID。",
    naoDeuParaCopiar: "你的瀏覽器不允許複製。",
    apagarTitulo: "刪除這則訊息？",
    apagarDescricao: "它會對頻道裡的所有人消失，無法復原。",
    apagarAcao: "刪除",
    citacaoAnexo: "點一下查看附件",
    citacaoSumiu: "原始訊息已經不在了。",
    reagirCom: "用 {{emoji}} 回應 — 長按可超級回應",
    segureParaSuper: "{{emoji}} — 長按可超級回應",
  },
  acoes: {
    reagir: "回應",
    responder: "回覆",
    encaminhar: "轉發",
    favoritar: "收藏訊息",
    tirarDosFavoritos: "取消收藏",
    marcarNaoLida: "標記為未讀",
    copiarLink: "複製訊息連結",
    copiarId: "複製訊息 ID",
    fixar: "置頂訊息",
    desafixar: "取消置頂",
    editar: "編輯",
    apagar: "刪除",
    mais: "更多",
    adicionarReacao: "新增回應",
    superReagirCom: "用 {{emoji}} 超級回應",
    fixarMensagem: "置頂訊息",
    desafixarMensagem: "取消置頂訊息",
    editarMensagem: "編輯訊息",
    apagarMensagem: "刪除訊息",
  },
  mencao: {
    cargo: "身分組提及",
    pessoa: "提及",
    alguem: "某人",
    cargoSemNome: "身分組",
    here: "通知在線的人",
    everyone: "通知整個伺服器",
  },
  codigo: {
    copiar: "複製",
    copiado: "已複製",
    copiarAria: "複製程式碼",
    copiadoAria: "已複製程式碼",
  },
  caixa: {
    escrever: "在 #{{canal}} 中傳訊息",
    escreverSemCanal: "傳訊息",
    semPermissao: "你沒有在這個頻道傳送訊息的權限",
    solteParaAnexar: "放開以附加檔案",
    respondendoPara: "正在回覆",
    vaiNotificar: "對方會收到通知",
    naoVaiNotificar: "對方不會收到通知",
    ligado: "開",
    desligado: "關",
    pararDeResponder: "取消回覆",
    mais: "更多",
    enviarArquivo: "傳送檔案",
    criarEnquete: "建立投票",
    expressoes: "表情符號、GIF 和貼圖",
    enviar: "傳送",
    aguardandoEnvio: "正在等待上傳",
    modoLento: "慢速模式已開啟（{{tempo}}）",
    modoLentoDica: "慢速模式設為 {{segundos}} 秒。請等待後再傳下一則訊息。",
  },
  anexos: {
    enviando: "上傳中…",
    modificar: "修改 {{arquivo}}",
    remover: "移除 {{arquivo}}",
    ver: "查看 {{arquivo}}",
    mostrarSpoiler: "顯示劇透：{{arquivo}}",
    spoiler: "劇透",
    spoilerTitulo: "劇透",
    editarTitulo: "編輯附件",
    nomeDoArquivo: "檔案名稱",
    descricao: "替代文字說明",
    descricaoDica: "為螢幕閱讀器描述這個媒體檔案",
    marcarSpoiler: "標記為劇透",
    cancelar: "取消",
    salvar: "儲存",
  },
  cartao: {
    tocador: "播放器",
    abrir: "開啟 {{destino}}",
    tocar: "播放 {{titulo}}",
    video: "影片",
    verImagem: "查看圖片",
  },
  enquete: {
    titulo: "投票",
    encerrada: "投票已結束",
    variasRespostas: "投票 — 可複選",
    umVoto: "{{quantidade}} 票",
    votos: "{{quantidade}} 票",
    umVotoNoTotal: "共 {{quantidade}} 票",
    votosNoTotal: "共 {{quantidade}} 票",
    encerraEm: "{{quando}} 結束",
    encerrarAgora: "立刻結束",
  },
  fixadas: {
    titulo: "已置頂的訊息",
    vazio: "這個頻道還沒有置頂訊息。",
    desafixar: "取消置頂",
    anexo: "（附件）",
    enquete: "（投票）",
    dicaRotulo: "小提示：",
    dica: "擁有「管理訊息」權限的人，可以直接從訊息選單置頂。",
  },
  encaminhar: {
    titulo: "轉發訊息",
    paraOnde: "轉發到哪裡？",
    semTexto: "（沒有文字的訊息）",
    nenhumLugar: "沒有叫這個名字的地方。",
    canais: "頻道",
    conversas: "私訊",
  },
};
