export const perfil = {
  carregando: "正在載入…",
  editar: "編輯個人資料",
  mensagem: "傳訊息",
  abrirConversa: "開啟對話",
  verCompleto: "查看完整資料",
  convidarParaServidor: "邀請到伺服器",
  semServidores: "你還沒有伺服器",
  conviteEnviado: "已向 {{nome}} 發送邀請。",
  moderador: "以管理員檢視開啟",
  mais: "更多",
  ignorar: "忽略",
  deixarDeIgnorar: "取消忽略",
  copiarId: "複製使用者 ID",
  idCopiado: "已複製 ID。",
  conexoes: "連結",
  membroDesde: "加入於",
  sobre: "關於",
  cargosTitulo: "身分組",
  visaoGeral: "總覽",
  amigosEmComum: "共同好友（{{quantidade}}）",
  servidoresEmComum: "共同伺服器（{{quantidade}}）",
  amizade: {
    amigo: "好友",
    pedidoEnviado: "已送出好友邀請",
    respondaAbaixo: "傳了邀請給你 — 在下面回應",
    adicionar: "加為好友",
    teMandouPedido: "傳了好友邀請給你",
    aceitar: "接受",
    desfazer: "解除好友",
    desfazerTitulo: "要把 {{nome}} 從好友中移除嗎？",
    desfazerDescricao: "你們不再是好友。私訊會留在紀錄裡，之後還可以再加回來。",
    bloquear: "封鎖",
    bloquearTitulo: "要封鎖 {{nome}} 嗎？",
    bloquearDescricao: "你們不再是好友，私訊不再接收訊息，對方也無法再傳好友邀請給你。",
    linkCopiado: "你們不是好友 — 連結已複製，你自己傳給對方吧。",
  },
  recado: {
    escrever: "傳訊息給 @{{usuario}}",
    enviar: "傳送",
    enviada: "訊息已送出",
    falhou: "沒能送出。試試從對話裡傳。",
  },
  cartao: {
    trocarFaixa: "更換卡片橫幅",
    trocarFaixaCurto: "更換橫幅",
    trocarFoto: "更換大頭貼",
    trocarFotoCurto: "更換圖片",
    suaEtiqueta: "你的標籤",
    editarEtiqueta: "點一下編輯你的標籤",
    conteAlgo: "說說你自己",
    adicionarStatus: "新增狀態",
    adicionarDescricao: "點一下新增簡介",
    cargo: "身分組",
    cargos: "身分組",
    cargosCom: "身分組 — {{quantidade}}",
    tirarCargo: "移除身分組 {{cargo}}",
  },
  cargos: {
    adicionar: "新增身分組",
    procurar: "搜尋身分組",
  },
  etiqueta: {
    escolher: "選擇伺服器標籤",
    nenhuma: "沒有伺服器標籤",
    semEtiqueta: "你的伺服器都沒有標籤",
  },
  emblemas: {
    doServidor: "這個伺服器的徽章",
    limite: "最多可以配戴 {{quantidade}} 個徽章。",
  },
  nota: {
    vazia: "點一下記點東西",
    rotulo: "備註（只有你看得到）",
    adicionar: "新增備註（只有你看得到）",
  },
  status: {
    titulo: "狀態",
    definir: "設定你的狀態",
    escolherEmoji: "選擇表情",
    tirarEmoji: "移除表情",
    oQuePensa: "在想些什麼？",
    limparAgora: "立刻清除狀態",
    naoLimpar: "不清除",
    limpar30m: "30 分鐘後清除",
    limpar1h: "1 小時後清除",
    limpar4h: "4 小時後清除",
    limparHoje: "今天清除",
    limparAmanha: "明天清除",
    comHora: "{{prazo}} {{hora}}",
  },
  presenca: {
    disponivel: "上線",
    ausente: "離開",
    naoPerturbar: "請勿打擾",
    naoPerturbarDetalhe: "你不會收到新訊息提醒",
    invisivel: "隱形",
    invisivelDetalhe: "在別人看來你處於離線",
  },
  menu: {
    mudarDeConta: "切換帳號",
    gerenciarContas: "管理帳號",
  },
  editor: {
    decoracao: "更換頭像裝飾",
    naoSalvo: "別忘了儲存你的變更！",
    principal: "主要個人資料",
  },
};
