export const servidor = {
  comunidade: {
    ativa: "社群已經開放",
    ativaDesde: "自 {{quando}} 起開放",
    membrosAgora: "{{quantos}} 名成員",
    criarParaMim: "幫我建一個",
    canalDeRegras: "規則頻道",
    canalDeRegrasDetalhe: "放規則的地方，大家開口之前都會先看一遍。",
    canalDeAvisos: "社群公告頻道",
    canalDeAvisosDetalhe: "我們把這裡的變動發到這個頻道，只有管理的人看得到。",
    canalDeSeguranca: "安全提醒頻道",
    canalDeSegurancaDetalhe: "過濾器攔下來的東西，管理團隊在這裡收到。",
    idiomaPrincipal: "主要語言",
    idiomaPrincipalDetalhe: "大部分對話所用的語言。",
    semIdioma: "未選語言",
    semCanal: "沒有頻道",
    finalTitulo: "就快好了",
    finalDetalhe: "開之前，看看對新來的人有哪些改變。",
    confereRegras: "進來的人最先看到規則頻道。",
    confereEveryone: "只有帶身分組的人才能用 @everyone 和 @here。",
    confereMencoes: "一次叫上所有人，從此需要權限。",
    concordo: "我同意並已了解",
    concordoDetalhe: "你確認這個社群會遵守我們的準則。",
    proximo: "下一步",
    terminar: "完成設定",
    visaoGeral: "總覽",
    visaoGeralDetalhe: "社群用來跟新人說話的頻道。",
    seguranca: "安全",
    segurancaDetalhe: "擋住垃圾訊息和重口味內容的閘。",
    habilitada: "社群已開啟。",
    falhou: "社群沒能開啟。",
    titulo: "社群",
    ilustracao: "對話氣泡",
    convite: "你在打造一個社群嗎？",
    conviteDetalhe: "轉成社群，就能拿到管理大地方的工具：規則頻道、我們發的公告，以及會自己把關的過濾器。",
    contagem: "{{minimo}} 人中的 {{membros}} 人",
    faltam: "還差 {{quantos}} 人才能開。",
    prontoParaAbrir: "現在就能開了。",
    habilitar: "開啟社群",
    vantagemCrescer: "長大",
    vantagemCrescerDetalhe: "社群可以申請進入「探索」，找這個主題的人就能找到你們。",
    vantagemModerar: "把關",
    vantagemModerarDetalhe: "要求驗證信箱、過濾媒體、開啟 AutoMod，一次搞定。",
    vantagemAvisos: "掌握動態",
    vantagemAvisosDetalhe: "我們把變動發給管理這裡的人，放在只屬於你們的頻道裡。",
    assistenteTitulo: "來把你的社群搭起來。",
    passoSeguranca: "安全檢查",
    passoBasico: "基礎準備",
    passoFinal: "最後收尾",
    seguraTitulo: "讓社群保持安全",
    seguraDetalhe: "大社群容易招來垃圾訊息。這兩道閘預設打開，之後覺得礙事再關也行。",
    emailVerificado: "要求驗證過的信箱",
    emailVerificadoDetalhe: "還沒驗證信箱的人發不了訊息。有身分組的人直接放行。",
    filtroDeMidia: "過濾露骨內容",
    filtroDeMidiaDetalhe: "圖片和影片進來時是遮住的，有人點了才顯示。",
    basicoTitulo: "把基礎備好",
    basicoDetalhe: "說明規則放在哪個頻道，我們的公告發到哪裡。沒選的話，兩個我都建。",
  },
  descoberta: {
    quantosComandos: "{{quantos}} 個指令",
    previa: "卡片長這樣",
    trocarIcone: "換圖示",
    tirarCapa: "去掉封面",
    heroComunidades: "有人正在聊你喜歡的東西",
    heroComunidadesDetalhe: "這些社群都是這裡的人自己開的。進去看看聊什麼，合得來就留下。",
    emDestaque: "精選",
    todasAsComunidades: "其餘的",
    heroTitulo: "今天你們這幫人想用點什麼？",
    heroDetalhe: "音樂、遊戲、管理的機器人，都是這裡的人自己做的。挑一個，它就進你的伺服器。",
    novidades: "剛到的",
    todosOsApps: "其餘的",
    lojaTitulo: "應用頁面",
    lojaDetalhe: "還不認識它的人，在「探索」裡看到的就是這些。",
    capa: "封面圖",
    capaDetalhe: "頁面頂上的寬圖。1280 × 720 正合適。",
    trocarCapa: "換封面",
    categorias: "分類",
    categoriasDetalhe: "最多 {{quantas}} 個。大家在「探索」裡就是照這個逛的。",
    idiomas: "語言",
    idiomasDetalhe: "最多 {{quantos}} 個。應用用哪些語言回話。",
    termos: "使用條款",
    politica: "隱私政策",
    politicas: "條款",
    servidorDeSuporte: "支援伺服器",
    servidorDeSuporteDetalhe: "用應用遇到麻煩的人，往這裡去。",
    semServidor: "不設",
    emQuantosServidores: "在多少個伺服器裡",
    categoria: {
      GAMES: "遊戲",
      MUSICA: "音樂",
      MODERACAO: "管理",
      PRODUTIVIDADE: "效率",
      SOCIAL: "社交",
      UTILIDADES: "工具",
      ARTE_E_CRIACAO: "藝術與創作",
      EDUCACAO: "學習",
      OUTRA: "其他",
    },
    appIndisponivel: "應用程式無法使用",
    voltarParaExplorar: "回到探索",
    adicionarApp: "新增應用程式",
    copiarLink: "複製連結",
    denunciarApp: "檢舉這個應用程式",
    copiarIdDoApp: "複製應用程式 ID",
    visaoGeral: "概覽",
    comandos: "指令",
    permissoes: "權限",
    semPermissoes: "這個應用程式不要求任何權限。",
    avisoDePermissoes: "它會帶著自己的身分組進來。這些權限之後可以在 社群設定 → 身分組 裡改。",
    servidoresEmComum: "共同的社群",
    umServidorEmComum: "1 個社群",
    quantosServidoresEmComum: "{{quantos}} 個社群",
    feitoPor: "作者",
    publicadoEm: "發布於",
    denunciarNome: "檢舉 {{nome}}",
    denunciaDetalhe: "檢舉會送到 Gravaê 團隊。做這個應用程式的人不會知道是你檢舉的。",
    denunciaFalhou: "檢舉沒能送出。",
    umMembro: "1 位成員",
    semDescricao: "沒有介紹。",
    adicionar: "新增",
    jaEstaAqui: "你已經在這裡了",
    entrando: "正在加入…",
    entrar: "加入",
    comunidadePublica: "公開社群",
    online: "{{quantos}} 在線",
    membros: "{{quantos}} 位成員",
    abrirComunidade: "開啟社群",
  },
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "伺服器設定",
  novasMensagens: "新訊息",
  menu: {
    silenciar: "靜音社群",
    reativar: "取消靜音社群",
    porQuinze: "15 分鐘",
    porMeiaHora: "30 分鐘",
    porTresHoras: "3 小時",
    porTresDias: "3 天",
    porUmaHora: "1 小時",
    porOitoHoras: "8 小時",
    porUmDia: "24 小時",
    ateReativar: "直到我重新開啟",
    notificacoes: "通知設定",
    padrao: "使用預設",
    todas: "所有訊息",
    soMencoes: "僅提及",
    nada: "無",
    ocultarSilenciados: "隱藏已靜音的頻道",
    denunciar: "檢舉社群",
    marcarLida: "標示為已讀",
    convidar: "邀請成員",
    editarPerfil: "編輯社群資料",
    configuracoes: "社群設定",
    sair: "離開社群",
    sairTitulo: "離開 {{nome}}？",
    sairDescricao: "想回來需要新的邀請。",
    copiarId: "複製社群 ID",
    idCopiado: "已複製 ID。",
  },
  convite: {
    cartaoTitulo: "有人邀請你加入一個社群",
    indisponivel: "邀請無法使用",
    indisponivelDetalhe: "已過期、已用完，或者建立的人刪掉了。",
    entrar: "加入社群",
    chamado: "你受邀加入",
    aceitarComo: "以 {{nome}} 的身分接受",
    abrir: "開啟社群",
    recusar: "不用了，謝謝",
  },
  pasta: {
    silenciarTodas: "靜音社群",
    reativarTodas: "取消靜音社群",
    mostrarSilenciados: "顯示已靜音的頻道",
    notificacoesDaComunidade: "通知設定",
    silenciarEveryone: "靜音 @everyone 和 @here",
    permitirEveryone: "允許 @everyone 和 @here",
    silenciarCargos: "靜音身分組提及",
    permitirCargos: "允許身分組提及",
    dicaDaCor: "輸入顏色（hex、rgb()、hsl() 或名稱）或使用選擇器。",
    mostrarIcone: "關閉時顯示圖示",
    dicaDoIcone: "關閉時顯示圖示，而不是裡面的伺服器。",
    icone: "資料夾圖示",
    excluir: "刪除資料夾",
    icones: {
      pasta: "資料夾",
      estrela: "收藏",
      coracao: "愛心",
      salvar: "儲存",
      jogo: "遊戲手把",
      escudo: "盾牌",
      nota: "音符",
    },
    marcarLida: "將資料夾標示為已讀",
    configuracoes: "資料夾設定",
    desfazer: "解散資料夾",
    titulo: "資料夾",
    nome: "名稱",
    semNome: "未命名",
    cor: "顏色",
    semCor: "無顏色",
    salvar: "儲存",
  },
  denuncia: {
    titulo: "檢舉 {{nome}}",
    descricao: "檢舉會送給 Gravaê 團隊。請告訴我們發生了什麼。",
    motivo: "原因",
    detalhes: "詳情（選填）",
    enviar: "送出檢舉",
    enviada: "已送出檢舉。謝謝。",
    motivos: {
      spam: "垃圾訊息或廣告",
      assedio: "騷擾或仇恨",
      conteudo: "不當內容",
      golpe: "詐騙",
      outro: "其他",
    },
  },
  selos: {
    verificada: "已驗證社群",
    detectavel: "可探索社群",
  },
  auditoria: {
    todasAsAcoes: "所有操作",
    todosOsUsuarios: "所有使用者",
    filtroMembros: "成員",
    filtroCanais: "頻道",
    filtroEmojis: "表情",
    filtroServidor: "伺服器",
    titulo: "稽核紀錄",
    porUsuario: "依人篩選",
    porAcao: "依動作篩選",
    vazio: "此篩選條件下還沒有任何紀錄。",
    motivo: "原因：",
  },
  banimentos: {
    titulo: "伺服器封鎖名單",
    descricao: "名單上的人即使拿到新邀請也進不來。解除封鎖會立刻恢復存取。",
    procurar: "以使用者名稱搜尋封鎖",
    vazioTitulo: "沒有封鎖",
    vazio: "你還沒封鎖過任何人……但真需要時，別猶豫。",
    desbanir: "解除封鎖",
  },
  excluir: {
    tudoVai: "{{servidor}} 的所有頻道、訊息和邀請都會為 {{membros}} 位成員刪除。此後誰也找不回來。",
    digite: "輸入 {{servidor}} 以確認",
    titulo: "刪除伺服器",
    aviso: "此動作無法復原。",
  },
  emblemas: {
    apagarDescricao: "它會從配戴的每個人身上消失。無法復原。",
    titulo: "徽章",
    vazio: "還沒有徽章。",
    novo: "新徽章",
  },
  convites: {
    revogarTitulo: "撤銷這個邀請？",
    revogarAcao: "撤銷",
    revogarDescricao: "連結 {{codigo}} 會立刻失效。已經透過它加入的人仍留在伺服器。",
    titulo: "邀請",
    descricao: "此伺服器所有有效的邀請連結。",
    vazio: "還沒有建立任何邀請。",
    revogar: "撤銷邀請",
  },
  integracoes: {
    opcionais: "username 和 avatar_url 是選填的，按訊息生效。限制為每 5 秒 5 則。",
    apagarDescricao: "該 URL 會立刻失效。它已經發出的訊息仍留在頻道裡。",
    titulo: "整合",
    descricao: "Webhook 是一個不需帳號就能向頻道發訊的位址。適合用來通報建置通過、有人開了工單，或任何你想從腳本送出的內容。",
    novo: "新增 Webhook",
    vazio: "還沒有 Webhook。建立一個，把 URL 貼到你希望訊息來源的地方。",
    canal: "頻道",
    apagar: "刪除 Webhook",
    comoUsar: "怎麼用",
    comoUsarTexto: "送出帶 JSON 的 POST：",
  },
  explorar: {
    titulo: "探索",
  },
  engajamento: {
    semCanal: "沒有系統頻道",
    titulo: "活躍度",
    descricao: "有新人來時，伺服器自己做點什麼才不會顯得冷清。",
    sistema: "系統訊息",
    boasVindas: "有人加入時傳送歡迎訊息",
    sorteio: "下面沒有自己的文案時，句子會隨機抽選——老是同一句很快就膩了。",
    canalDoSistema: "系統訊息頻道",
    mensagem: "歡迎訊息",
    deixeVazio: "留空則從現成的句子中抽選",
  },
  automod: {
    titulo: "自動管理",
    descricao: "在訊息還沒出現之前就自己動手的過濾器。管理伺服器的人從不會被過濾——豁免身分組也直接放行。",
    palavras: {
      titulo: "封鎖自訂字詞",
      descricao: "你自己列的、誰都不能寫的字詞。",
    },
    mencoes: {
      titulo: "封鎖提及洗版",
      descricao: "封鎖一次提及太多人的訊息。",
    },
    links: {
      titulo: "封鎖連結",
      descricao: "攔下任何貼到聊天裡的網址。",
    },
    definir: "設定",
    nomeDaRegra: "規則名稱",
    bloqueadas: "被封鎖的字詞",
    digiteEnter: "輸入後按 Enter",
    comparacao: "比對會忽略大小寫、變音符號和標點——也不會抓詞中之詞。",
    aPartirDe: "從幾次提及開始封鎖",
    oQueFazer: "要做什麼",
    canalDoAlerta: "提醒頻道",
    escolhaCanal: "選一個頻道",
    castigo: "禁言（分鐘）",
    isentos: "豁免身分組",
    semCargos: "還沒有建立身分組。",
    salvarRegra: "儲存規則",
    apagar: "刪除規則",
    excluirTitulo: "刪除這條自動管理規則？",
    excluirDescricao: "伺服器會立刻停止依它過濾。可以重新建立，但目前的設定會遺失。",
    excluirAcao: "刪除規則",
  },
  cargos: {
    titulo: "身分組",
    descricao: "身分組給的是名字、顏色和權限。在清單裡越靠上，越管得住下面的人——誰也動不了與自己同級或更高的身分組。",
    criar: "建立身分組",
    vazio: "還沒有身分組。",
    abaExibicao: "顯示",
    abaPermissoes: "權限",
    abaMembros: "成員 — {{quantos}}",
    everyone: "對伺服器上所有人生效。其他身分組都疊在它上面。",
    nomeDoCargo: "身分組名稱",
    cor: "身分組顏色",
    corDica: "在成員清單和聊天裡替擁有該身分組的人上色。",
    semCor: "不上色",
    corPersonalizada: "自訂顏色",
    estilo: "名字樣式",
    segundaCor: "第二個顏色",
    segundaCorDica: "沒有它，漸層會退回純色——不會消失。",
    limparSegundaCor: "清除第二個顏色",
    icone: "圖示",
    iconeDica: "出現在擁有者個人資料卡上，身分組旁邊。",
    exibirSeparado: "與其他成員分開顯示",
    exibirSeparadoDica: "該身分組在成員清單裡會有自己的區塊。",
    permitirMencionar: "允許提及此身分組",
    permitirMencionarDica: "任何人都能通知所有擁有該身分組的人。",
    semPoderDeConceder: "{{descricao}}（你沒有這項權限，因此無法授予）",
    adicionar: "把某人加入這個身分組",
    tirar: "移除身分組",
    semNinguem: "還沒有人擁有這個身分組。",
    apagar: "刪除身分組",
    excluirTitulo: "刪除身分組「{{nome}}」？",
    excluirDescricao: "擁有這個身分組的人會失去它帶來的一切。無法復原。",
    excluirAcao: "刪除身分組",
  },
  membros: {
    procurar: "以名稱或使用者名稱搜尋",
    membroDesde: "加入於",
    vazio: "找不到任何人。",
    acoesPara: "對 {{nome}} 的操作",
    deCastigo: "禁言",
    tirarCastigo: "解除禁言",
    castigo5min: "5 分鐘",
    castigo1h: "1 小時",
    castigo1d: "1 天",
    castigo1s: "1 週",
    expulsar: "踢出",
    expulsarTitulo: "踢出 {{nome}}？",
    expulsarDescricao: "會立刻離開 {{servidor}}。憑邀請可以回來——踢出並不阻止返回。",
    banir: "封鎖",
    banirTitulo: "封鎖 {{nome}}？",
    banirDescricao: "會離開 {{servidor}}，在解除封鎖之前即使有邀請也回不來。",
    motivo: "理由（選填）",
    motivoDica: "會記入稽核紀錄",
  },
  perfil: {
    titulo: "伺服器資料",
    descricao: "你的伺服器在清單和邀請連結裡就是這樣顯示的。",
    icone: "圖示",
    faixa: "頂部橫幅",
    nomeDoServidor: "伺服器名稱",
    campoDescricao: "簡介",
    doQueE: "這個伺服器是做什麼的？",
    comprimido: "上傳前已壓縮：{{economia}}",
  },
  etiqueta: {
    titulo: "伺服器標籤",
    descricao: "一個最多 4 個字的標籤，出現在每位成員的名字旁邊——聊天裡和人員清單裡都有。這裡免費：不用加成，也不用等級。",
    escolhaNome: "取一個名字",
    limite: "最多 4 個字元，字母和數字。",
    escolhaInsignia: "選一個徽章",
    voce: "你",
    fala1: "有人要一起玩嗎？",
    fala2: "看看我的標籤！",
    fala3: "哇，這你哪來的",
  },
  expressoes: {
    comoUsar: "最多新增 {{limite}} 個本伺服器所有人都能用的表情。在聊天裡輸入 :名稱: 就能傳送。",
    imagem: "圖片",
    enviadoPor: "上傳者",
    semEmoji: "還沒有表情。",
    figurinhas: "貼圖",
    enviarFigurinha: "上傳貼圖",
    nomeDaFigurinha: "貼圖名稱",
    exemploFigurinha: "例：小貓抱抱",
    figurinhaGrande: "貼圖超過 {{limite}}。",
    deixaPraLa: "算了",
    sons: "音效板",
    enviarSom: "上傳音效",
    nomeDoSom: "音效名稱",
    semSom: "還沒有音效。",
    somGrande: "音效超過 {{limite}}。",
    emojiRelacionado: "相關表情",
    ouvir: "試聽",
    ouvirAssim: "用這個音量聽",
    volumeDe: "{{nome}} 的音量",
    volumeDica: "對伺服器上所有人生效。每個人仍可以在通話面板裡只為自己調小聲音。",
    falhaEnvio: "檔案上傳失敗。",
    excluirTitulo: "刪除{{tipo}}「{{nome}}」？",
    excluirDescricao: "會從所有人的伺服器上消失。已經用過它的訊息維持原樣。",
  },
  canal: {
    tipoLink: "連結",
    tipoLinkDica: "指向外部網址，在瀏覽器裡開啟",
    endereco: "網址",
    enderecoDica: "這個頻道通向哪裡。必須以 https:// 開頭",
    visaoGeral: "總覽",
    nome: "頻道名稱",
    topico: "頻道主題",
    topicoDica: "這裡聊些什麼？",
    modoLento: "每人每個間隔只發一則訊息。管理訊息或頻道的人直接通過。",
    visibilidade: "內容可見度",
    padrao: "預設",
    padraoDica: "頻道內容一直看得到。",
    spoiler: "劇透頻道",
    spoilerDica: "把這個頻道標為含劇透，讓轉折和沉重的話題保持隱藏，直到有人選擇查看。",
    idade: "年齡限制頻道",
    idadeDica: "進入的人須確認已成年才能看到內容。",
    bitrateDica: "超過 64 kbps 可能會影響網路較差的人。",
    qualidadeDeVideo: "影片畫質",
    automatica: "自動",
    limite: "人數上限 — {{valor}}",
    pessoas: "{{quantos}} 人",
    semLimite: "不限",
    permissoesDescricao: "在這裡你改的是本頻道內生效的規則。留在「繼承」的仍然跟隨身分組。",
    excluir: {
      titulo: "刪除頻道",
      historico: "{{canal}} 的全部歷史一併消失，對所有人。",
      digite: "輸入 {{canal}} 以確認",
    },
  },
  moderacao: {
    titulo: "管理員檢視",
    semPermissao: "需要「管理成員」權限才能查看。",
    fecharEsc: "關閉（Esc）",
    atividade: "在伺服器上的活動",
    mensagens: "訊息",
    links: "連結",
    midia: "媒體",
    acoesNaAuditoria: "稽核紀錄中的操作",
    moderacoesSofridas: "受到的處置",
    permissoes: "權限（{{quantas}}）",
    semPermissaoEspecial: "沒有特殊權限。",
    conta: "帳號",
    entrouNoServidor: "加入伺服器",
    contaCriadaEm: "帳號建立於",
    deCastigoAte: "禁言至",
    formaDeAdesao: "如何加入",
    mensagem: "訊息",
    castigo: "禁言",
    copiarId: "複製 ID",
    idCopiado: "已複製 ID。",
    adicionarCargo: "新增身分組",
    semCargos: "尚未建立身分組",
    soEveryone: "只有 @everyone。",
    voltar: "返回",
    vazio: "這裡什麼都沒有。",
    cinquenta: "顯示最新的 50 則。",
    irParaMensagem: "前往訊息",
    precisaSerAmigo: "你們要先成為好友才能聊天。",
    expulsarDescricao: "立刻離開伺服器，但可以憑邀請回來。",
    banirDescricao: "離開伺服器，且在解除封鎖之前即使有邀請也回不來。",
    castigarTitulo: "將 {{nome}} 禁言？",
    castigoDescricao: "在此期間，他在伺服器的任何頻道都不能發言或說話。",
    aplicarCastigo: "套用禁言",
    duracao: "時長（分鐘）",
    informeDuracao: "請填寫時長（分鐘）。",
  },
  abas: {
    pesquisar: "在設定裡搜尋",
    semResultado: "這裡沒有叫這個名字的。",
    comunidade: "社群",
    expressoes: "表情",
    pessoas: "人員",
    apps: "應用程式",
    moderacao: "管理",
    banimentos: "封鎖",
  },
};
