export const servidor = {
  titulo: "伺服器設定",
  auditoria: {
    todasAsAcoes: "所有操作",
    todosOsUsuarios: "所有使用者",
    filtroMembros: "成員",
    filtroCanais: "頻道",
    filtroEmojis: "表情",
    filtroServidor: "伺服器",
    titulo: "稽核紀錄",
    porUsuario: "依人篩選",
    porAcao: "依動作篩選",
    vazio: "此篩選條件下還沒有任何紀錄。",
    motivo: "原因：",
  },
  banimentos: {
    titulo: "伺服器封鎖名單",
    descricao: "名單上的人即使拿到新邀請也進不來。解除封鎖會立刻恢復存取。",
    procurar: "以使用者名稱搜尋封鎖",
    vazioTitulo: "沒有封鎖",
    vazio: "你還沒封鎖過任何人……但真需要時，別猶豫。",
    desbanir: "解除封鎖",
  },
  excluir: {
    tudoVai: "{{servidor}} 的所有頻道、訊息和邀請都會為 {{membros}} 位成員刪除。此後誰也找不回來。",
    digite: "輸入 {{servidor}} 以確認",
    titulo: "刪除伺服器",
    aviso: "此動作無法復原。",
  },
  emblemas: {
    apagarDescricao: "它會從配戴的每個人身上消失。無法復原。",
    titulo: "徽章",
    vazio: "還沒有徽章。",
    novo: "新徽章",
  },
  convites: {
    revogarTitulo: "撤銷這個邀請？",
    revogarAcao: "撤銷",
    revogarDescricao: "連結 {{codigo}} 會立刻失效。已經透過它加入的人仍留在伺服器。",
    titulo: "邀請",
    descricao: "此伺服器所有有效的邀請連結。",
    vazio: "還沒有建立任何邀請。",
    revogar: "撤銷邀請",
  },
  integracoes: {
    opcionais: "username 和 avatar_url 是選填的，按訊息生效。限制為每 5 秒 5 則。",
    apagarDescricao: "該 URL 會立刻失效。它已經發出的訊息仍留在頻道裡。",
    titulo: "整合",
    descricao: "Webhook 是一個不需帳號就能向頻道發訊的位址。適合用來通報建置通過、有人開了工單，或任何你想從腳本送出的內容。",
    novo: "新增 Webhook",
    vazio: "還沒有 Webhook。建立一個，把 URL 貼到你希望訊息來源的地方。",
    canal: "頻道",
    apagar: "刪除 Webhook",
    comoUsar: "怎麼用",
    comoUsarTexto: "送出帶 JSON 的 POST。格式與 Discord 相同，因此現成的腳本不必修改即可使用：",
  },
  engajamento: {
    semCanal: "沒有系統頻道",
    titulo: "活躍度",
    descricao: "有新人來時，伺服器自己做點什麼才不會顯得冷清。",
    sistema: "系統訊息",
    boasVindas: "有人加入時傳送歡迎訊息",
    sorteio: "下面沒有自己的文案時，句子會隨機抽選——老是同一句很快就膩了。",
    canalDoSistema: "系統訊息頻道",
    mensagem: "歡迎訊息",
    deixeVazio: "留空則從現成的句子中抽選",
  },
  automod: {
    titulo: "自動管理",
    descricao: "在訊息還沒出現之前就自己動手的過濾器。管理伺服器的人從不會被過濾——豁免身分組也直接放行。",
    palavras: {
      titulo: "封鎖自訂字詞",
      descricao: "你自己列的、誰都不能寫的字詞。",
    },
    mencoes: {
      titulo: "封鎖提及洗版",
      descricao: "封鎖一次提及太多人的訊息。",
    },
    links: {
      titulo: "封鎖連結",
      descricao: "攔下任何貼到聊天裡的網址。",
    },
    definir: "設定",
    nomeDaRegra: "規則名稱",
    bloqueadas: "被封鎖的字詞",
    digiteEnter: "輸入後按 Enter",
    comparacao: "比對會忽略大小寫、變音符號和標點——也不會抓詞中之詞。",
    aPartirDe: "從幾次提及開始封鎖",
    oQueFazer: "要做什麼",
    canalDoAlerta: "提醒頻道",
    escolhaCanal: "選一個頻道",
    castigo: "禁言（分鐘）",
    isentos: "豁免身分組",
    semCargos: "還沒有建立身分組。",
    salvarRegra: "儲存規則",
    apagar: "刪除規則",
    excluirTitulo: "刪除這條自動管理規則？",
    excluirDescricao: "伺服器會立刻停止依它過濾。可以重新建立，但目前的設定會遺失。",
    excluirAcao: "刪除規則",
  },
  cargos: {
    titulo: "身分組",
    descricao: "身分組給的是名字、顏色和權限。在清單裡越靠上，越管得住下面的人——誰也動不了與自己同級或更高的身分組。",
    criar: "建立身分組",
    vazio: "還沒有身分組。",
    abaExibicao: "顯示",
    abaPermissoes: "權限",
    abaMembros: "成員 — {{quantos}}",
    everyone: "對伺服器上所有人生效。其他身分組都疊在它上面。",
    nomeDoCargo: "身分組名稱",
    cor: "身分組顏色",
    corDica: "在成員清單和聊天裡替擁有該身分組的人上色。",
    semCor: "不上色",
    corPersonalizada: "自訂顏色",
    estilo: "名字樣式",
    segundaCor: "第二個顏色",
    segundaCorDica: "沒有它，漸層會退回純色——不會消失。",
    limparSegundaCor: "清除第二個顏色",
    icone: "圖示",
    iconeDica: "出現在擁有者個人資料卡上，身分組旁邊。",
    exibirSeparado: "與其他成員分開顯示",
    exibirSeparadoDica: "該身分組在成員清單裡會有自己的區塊。",
    permitirMencionar: "允許提及此身分組",
    permitirMencionarDica: "任何人都能通知所有擁有該身分組的人。",
    semPoderDeConceder: "{{descricao}}（你沒有這項權限，因此無法授予）",
    adicionar: "把某人加入這個身分組",
    tirar: "移除身分組",
    semNinguem: "還沒有人擁有這個身分組。",
    apagar: "刪除身分組",
    excluirTitulo: "刪除身分組「{{nome}}」？",
    excluirDescricao: "擁有這個身分組的人會失去它帶來的一切。無法復原。",
    excluirAcao: "刪除身分組",
  },
  membros: {
    procurar: "以名稱或使用者名稱搜尋",
    membroDesde: "加入於",
    vazio: "找不到任何人。",
    acoesPara: "對 {{nome}} 的操作",
    deCastigo: "禁言",
    tirarCastigo: "解除禁言",
    castigo5min: "5 分鐘",
    castigo1h: "1 小時",
    castigo1d: "1 天",
    castigo1s: "1 週",
    expulsar: "踢出",
    expulsarTitulo: "踢出 {{nome}}？",
    expulsarDescricao: "會立刻離開 {{servidor}}。憑邀請可以回來——踢出並不阻止返回。",
    banir: "封鎖",
    banirTitulo: "封鎖 {{nome}}？",
    banirDescricao: "會離開 {{servidor}}，在解除封鎖之前即使有邀請也回不來。",
    motivo: "理由（選填）",
    motivoDica: "會記入稽核紀錄",
  },
  perfil: {
    titulo: "伺服器資料",
    descricao: "你的伺服器在清單和邀請連結裡就是這樣顯示的。",
    icone: "圖示",
    faixa: "頂部橫幅",
    nomeDoServidor: "伺服器名稱",
    campoDescricao: "簡介",
    doQueE: "這個伺服器是做什麼的？",
    comprimido: "上傳前已壓縮：{{economia}}",
  },
  etiqueta: {
    titulo: "伺服器標籤",
    descricao: "一個最多 4 個字的標籤，出現在每位成員的名字旁邊——聊天裡和人員清單裡都有。這裡免費：不用加成，也不用等級。",
    escolhaNome: "取一個名字",
    limite: "最多 4 個字元，字母和數字。",
    escolhaInsignia: "選一個徽章",
    voce: "你",
    fala1: "有人要一起玩嗎？",
    fala2: "看看我的標籤！",
    fala3: "哇，這你哪來的",
  },
  expressoes: {
    comoUsar: "最多新增 {{limite}} 個本伺服器所有人都能用的表情。在聊天裡輸入 :名稱: 就能傳送。",
    imagem: "圖片",
    enviadoPor: "上傳者",
    semEmoji: "還沒有表情。",
    figurinhas: "貼圖",
    enviarFigurinha: "上傳貼圖",
    nomeDaFigurinha: "貼圖名稱",
    exemploFigurinha: "例：小貓抱抱",
    figurinhaGrande: "貼圖超過 {{limite}}。",
    deixaPraLa: "算了",
    sons: "音效板",
    enviarSom: "上傳音效",
    nomeDoSom: "音效名稱",
    semSom: "還沒有音效。",
    somGrande: "音效超過 {{limite}}。",
    emojiRelacionado: "相關表情",
    ouvir: "試聽",
    ouvirAssim: "用這個音量聽",
    volumeDe: "{{nome}} 的音量",
    volumeDica: "對伺服器上所有人生效。每個人仍可以在通話面板裡只為自己調小聲音。",
    falhaEnvio: "檔案上傳失敗。",
    excluirTitulo: "刪除{{tipo}}「{{nome}}」？",
    excluirDescricao: "會從所有人的伺服器上消失。已經用過它的訊息維持原樣。",
  },
  canal: {
    visaoGeral: "總覽",
    nome: "頻道名稱",
    topico: "頻道主題",
    topicoDica: "這裡聊些什麼？",
    modoLento: "每人每個間隔只發一則訊息。管理訊息或頻道的人直接通過。",
    visibilidade: "內容可見度",
    padrao: "預設",
    padraoDica: "頻道內容一直看得到。",
    spoiler: "劇透頻道",
    spoilerDica: "把這個頻道標為含劇透，讓轉折和沉重的話題保持隱藏，直到有人選擇查看。",
    idade: "年齡限制頻道",
    idadeDica: "進入的人須確認已成年才能看到內容。",
    bitrateDica: "超過 64 kbps 可能會影響網路較差的人。",
    qualidadeDeVideo: "影片畫質",
    automatica: "自動",
    limite: "人數上限 — {{valor}}",
    pessoas: "{{quantos}} 人",
    semLimite: "不限",
    permissoesDescricao: "在這裡你改的是本頻道內生效的規則。留在「繼承」的仍然跟隨身分組。",
    excluir: {
      titulo: "刪除頻道",
      historico: "{{canal}} 的全部歷史一併消失，對所有人。",
      digite: "輸入 {{canal}} 以確認",
    },
  },
  moderacao: {
    titulo: "管理員檢視",
    semPermissao: "需要「管理成員」權限才能查看。",
    fecharEsc: "關閉（Esc）",
    atividade: "在伺服器上的活動",
    mensagens: "訊息",
    links: "連結",
    midia: "媒體",
    acoesNaAuditoria: "稽核紀錄中的操作",
    moderacoesSofridas: "受到的處置",
    permissoes: "權限（{{quantas}}）",
    semPermissaoEspecial: "沒有特殊權限。",
    conta: "帳號",
    entrouNoServidor: "加入伺服器",
    contaCriadaEm: "帳號建立於",
    deCastigoAte: "禁言至",
    formaDeAdesao: "如何加入",
    mensagem: "訊息",
    castigo: "禁言",
    copiarId: "複製 ID",
    idCopiado: "已複製 ID。",
    adicionarCargo: "新增身分組",
    semCargos: "尚未建立身分組",
    soEveryone: "只有 @everyone。",
    voltar: "返回",
    vazio: "這裡什麼都沒有。",
    cinquenta: "顯示最新的 50 則。",
    irParaMensagem: "前往訊息",
    precisaSerAmigo: "你們要先成為好友才能聊天。",
    expulsarDescricao: "立刻離開伺服器，但可以憑邀請回來。",
    banirDescricao: "離開伺服器，且在解除封鎖之前即使有邀請也回不來。",
    castigarTitulo: "將 {{nome}} 禁言？",
    castigoDescricao: "在此期間，他在伺服器的任何頻道都不能發言或說話。",
    aplicarCastigo: "套用禁言",
    duracao: "時長（分鐘）",
    informeDuracao: "請填寫時長（分鐘）。",
  },
  abas: {
    expressoes: "表情",
    pessoas: "人員",
    apps: "應用程式",
    moderacao: "管理",
    banimentos: "封鎖",
  },
};
