
export const comum = {
  carregando: "Carregando…",
  salvar: "Salvar",
  salvando: "Salvando…",
  descartar: "Descartar",
  redefinir: "Redefinir",
  naoSalvo: "Você tem alterações não salvas.",
  fechar: "Fechar",
  criar: "Criar",
  nome: "Nome",
  emoji: "Emoji",
  previa: "Prévia",
  cancelar: "Cancelar",
  enviar: "Enviar",
  apagar: "Apagar",
  excluir: "Excluir",
  remover: "Remover",
  trocar: "Trocar",
};
