
export const configuracoes = {
  efeitos: {
    titulo: "Efeitos do ponteiro",
    detalhe: "Rastro e faísca desenhados por cima do app. Nascem desligados, e somem sozinhos se você pediu menos animação.",
    rastro: "Rastro do cursor",
    rastroDetalhe: "Um risco que segue o ponteiro e vai apagando atrás.",
    faisca: "Faísca ao clicar",
    faiscaDetalhe: "Riscos curtos que saem do ponto onde você clicou.",
    cor: "Cor",
    espessura: "Espessura",
    comprimento: "Comprimento",
    tamanho: "Tamanho",
    quantidade: "Quantidade",
  },
  email: {
    verificarTitulo: "Confirme o seu e-mail",
    verificarDetalhe: "Algumas comunidades só deixam falar quem confirmou. Leva um clique.",
    enviar: "Mandar o link",
    enviado: "Olhe a caixa de entrada. O link vale por um dia.",
    falhou: "Não deu para mandar o e-mail.",
    confirmado: "E-mail confirmado",
    confirmadoDetalhe: "Pronto. Agora você fala em qualquer comunidade que exija isso.",
    linkIncompleto: "Link incompleto",
    linkIncompletoDetalhe: "Falta o código no endereço. Abra o link direto do e-mail.",
    confirmando: "Confirmando…",
    expirou: "Este link já foi usado ou passou da validade.",
    irParaOApp: "Ir para o aplicativo",
  },
  tema: {
    indisponivel: "Tema indisponível",
    indisponivelDetalhe: "Quem publicou apagou, ou o link está errado.",
    indisponivelLinha: "Tema indisponível. Quem publicou apagou, ou o link está errado.",
    importar: "Importar tema",
    importarCurto: "Importar",
    importarDetalhe: "Isso substitui o tema que você tem agora. Dá para editar depois em Configurações > Aparência > Estúdio de temas.",
    porAutor: "por {{autor}}",
    umaCorTrocada: "1 cor trocada",
    coresTrocadas: "{{quantas}} cores trocadas",
    avisoDeCss: "Este tema traz CSS de quem escreveu, e CSS mexe em qualquer canto da tela. Só importe de gente em quem você confia.",
    soCores: "Este tema só troca cores. Nada de CSS de fora.",
    aplicar: "Aplicar",
    previaSemMotor: "A prévia não roda o motor. Instale para ver.",
    motorAnimado: "{{motor}} animado",
  },
  sair: "Sair",
  versoes: {
    termos: "Termos de serviço",
    privacidade: "Política de privacidade",
    copiar: "Clique para copiar",
    copiado: "Copiado",
  },
  telas: {
    conta: "Minha conta",
    privacidade: "Privacidade",
    conexoes: "Conexões",
    voz: "Áudio",
    video: "Vídeo",
    avisos: "Notificações",
    aplicativos: "Aplicativos",
    aparencia: "Aparência",
    batePapo: "Bate-papo",
    acessibilidade: "Acessibilidade",
    idioma: "Idioma",
    aplicativo: "Baixar o app",
    atalhos: "Atalhos",
    desktop: "Aplicativo desktop",
    avancado: "Avançado",
    servidor: "Servidor",
    comunicado: "Comunicado do sistema",
    denuncias: "Denúncias",
    publicacoes: "Publicações",
  },
  grupos: {
    conta: "Conta",
    app: "Configurações do app",
    desenvolvedor: "Desenvolvedor",
    administracao: "Administração",
  },
  secoes: {
    detalhesDeLogin: "Detalhes de login",
    dispositivos: "Dispositivos",
    usuariosBloqueados: "Usuários bloqueados",
    aplicativosAutorizados: "Aplicativos autorizados",
    sessoes: "Sessões",
    amigosEDms: "Amigos e mensagens diretas",
    compartilhamentoDeAtividade: "Compartilhamento de atividade",
    visibilidadeDoPerfil: "Visibilidade do perfil",
    exportarDados: "Exportar dados",
    exclusaoDeDados: "Exclusão de dados",
    tema: "Tema",
    corDeDestaque: "Cor de destaque",
    interface: "Interface",
    listaDeCanais: "Lista de canais",
    zoomDoApp: "Nível de zoom do app",
    escalaDaFonte: "Escala da fonte do chat",
    modoStreamer: "Privacidade de transmissão",
    cursores: "Cursores",
    movimento: "Movimento",
    textoEmVoz: "Texto em voz",
    teclado: "Teclado",
    formatoDaHora: "Formato da hora",
    idiomaDaInterface: "Idioma da interface",
    dispositivosDeVoz: "Dispositivos",
    testeDoMicrofone: "Teste do microfone",
    modoDeEntrada: "Modo de entrada",
    sensibilidade: "Sensibilidade de entrada",
    qualidade: "Qualidade",
    camera: "Câmera",
    transmissao: "Transmissão",
    exibicao: "Exibição",
    entrada: "Entrada",
    midia: "Mídia",
    geral: "Geral",
    preferenciaDeMencao: "Preferência de menção",
    sons: "Sons",
  },
};
