/// As telas das configurações e os títulos que a lateral desenha. É o primeiro
/// pedaço traduzido porque é o mais denso de texto e o mais fácil de conferir:
/// dá pra ver as treze telas de uma vez trocando o idioma.
export const configuracoes = {
  telas: {
    conta: "Minha conta",
    privacidade: "Privacidade",
    conexoes: "Conexões",
    voz: "Áudio",
    video: "Vídeo",
    avisos: "Notificações",
    aplicativos: "Aplicativos",
    aparencia: "Aparência",
    batePapo: "Bate-papo",
    acessibilidade: "Acessibilidade",
    idioma: "Idioma",
    aplicativo: "Baixar o app",
    servidor: "Servidor",
  },
  grupos: {
    conta: "Conta",
    app: "Configurações do app",
    desenvolvedor: "Desenvolvedor",
    administracao: "Administração",
  },
  secoes: {
    detalhesDeLogin: "Detalhes de login",
    dispositivos: "Dispositivos",
    usuariosBloqueados: "Usuários bloqueados",
    aplicativosAutorizados: "Aplicativos autorizados",
    sessoes: "Sessões",
    amigosEDms: "Amigos e mensagens diretas",
    compartilhamentoDeAtividade: "Compartilhamento de atividade",
    visibilidadeDoPerfil: "Visibilidade do perfil",
    exportarDados: "Exportar dados",
    exclusaoDeDados: "Exclusão de dados",
    tema: "Tema",
    corDeDestaque: "Cor de destaque",
    interface: "Interface",
    listaDeCanais: "Lista de canais",
    zoomDoApp: "Nível de zoom do app",
    escalaDaFonte: "Escala da fonte do chat",
    modoStreamer: "Privacidade de transmissão",
    movimento: "Movimento",
    textoEmVoz: "Texto em voz",
    teclado: "Teclado",
    formatoDaHora: "Formato da hora",
    idiomaDaInterface: "Idioma da interface",
    dispositivosDeVoz: "Dispositivos",
    testeDoMicrofone: "Teste do microfone",
    modoDeEntrada: "Modo de entrada",
    sensibilidade: "Sensibilidade de entrada",
    qualidade: "Qualidade",
    camera: "Câmera",
    transmissao: "Transmissão",
    exibicao: "Exibição",
    entrada: "Entrada",
    midia: "Mídia",
    geral: "Geral",
    preferenciaDeMencao: "Preferência de menção",
    sons: "Sons",
  },
};
