
export const conversa = {
  acenar: {
    ilustracao: "Uma mãozinha acenando",
    botao: "Acenar para {{nome}}",
  },
  oficial: {
    titulo: "Este canal é só para avisos oficiais do Gravaê.",
    detalhe: "Nunca pedimos a sua senha nem o token da sua conta.",
    saibaMais: "Saiba mais",
  },
  topico: {
    abrir: "Ver a descrição do canal",
  },
  previaDoLink: {
    carregando: "Vendo o que tem no link…",
    destino: "Vai para {{destino}}",
  },
  reacao: {
    carregando: "Vendo quem reagiu com {{emoji}}…",
    uma: "{{nome}} reagiu com {{emoji}}",
    duas: "{{primeiro}} e {{segundo}} reagiram com {{emoji}}",
    varias: "{{nomes}} e mais {{quantos}} reagiram com {{emoji}}",
    dicaSuper: "Segure para super reagir",
  },
  recado: {
    gravar: "Gravar um recado",
    descartar: "Descartar o recado",
    mandar: "Mandar o recado",
    semSuporte: "Este navegador não grava áudio.",
    semMicrofone: "Sem acesso ao microfone.",
  },
  lista: {
    carregando: "Carregando mensagens…",
    carregandoMais: "Carregando…",
    verMais: "Role para cima para ver mais",
    semHistorico: "Histórico indisponível",
    semHistoricoDetalhe:
      "Seu cargo não tem permissão para ler o histórico de #{{canal}}. As mensagens novas continuam aparecendo enquanto você estiver aqui.",
    boasVindas: "Bem-vindo a #{{canal}}",
    boasVindasDetalhe: "Este é o começo do canal #{{canal}}.",
  },
  data: {
    hoje: "Hoje",
    ontem: "Ontem",
    hojeAs: "hoje às {{hora}}",
    ontemAs: "ontem às {{hora}}",
  },
  digitando: {
    um: "{{nome}} está digitando…",
    dois: "{{primeiro}} e {{segundo}} estão digitando…",
    varios: "{{quantidade}} pessoas estão digitando…",
  },
  mensagem: {
    usou: "usou",
    fixada: "fixada",
    editado: "(editado)",
    ignorada: "Mensagem de alguém que você ignora.",
    mostrar: "Mostrar",
    escPara: "Esc para",
    cancelar: "cancelar",
    enterParaSalvar: "Enter para salvar",
    naoLidasDaqui: "Não lidas a partir daqui.",
    linkCopiado: "Link copiado.",
    idCopiado: "ID copiado.",
    naoDeuParaCopiar: "Seu navegador não deixou copiar.",
    apagarTitulo: "Apagar mensagem?",
    apagarDescricao: "Ela some para todo mundo do canal. Não dá pra recuperar.",
    apagarAcao: "Apagar",
    citacaoAnexo: "clique para ver o anexo",
    citacaoSumiu: "A mensagem original não está mais aqui.",
    encaminhadaDe: "Encaminhada de",
    irParaOriginal: "Ir para a original",
    bloqueadas: "{{quantas}} mensagens bloqueadas",
    mostrarBloqueadas: "Mostrar",
    esconderBloqueadas: "Esconder",
    reagirCom: "Reagir com {{emoji}} — segure para super reagir",
    segureParaSuper: "{{emoji}} — segure para super reagir",
  },
  imagem: {
    copiarImagem: "Copiar imagem",
    baixarImagem: "Baixar imagem",
    copiarLinkDaImagem: "Copiar link da imagem",
    abrirLinkDaImagem: "Abrir link da imagem",
    maisAcoes: "Mais ações de mídia",
    pesquisarImagem: "Pesquisar imagem",
    copiarIdDoAnexo: "Copiar ID do anexo",
    girarEsquerda: "Girar à esquerda",
    girarDireita: "Girar à direita",
    ajustar: "Ajustar à tela",
    ampliar: "Ampliar",
    reduzir: "Reduzir",
    imagemCopiada: "Imagem copiada.",
    linkCopiado: "Link copiado.",
    idCopiado: "ID copiado.",
    naoDeuParaCopiar: "Não deu para copiar a imagem.",
  },

  acoes: {
    reagir: "Reagir",
    responder: "Responder",
    encaminhar: "Encaminhar",
    favoritar: "Favoritar mensagem",
    tirarDosFavoritos: "Tirar dos favoritos",
    marcarNaoLida: "Marcar como não lida",
    copiarLink: "Copiar link da mensagem",
    copiarId: "Copiar ID da mensagem",
    fixar: "Fixar mensagem",
    desafixar: "Desafixar",
    editar: "Editar",
    apagar: "Apagar",
    mais: "Mais",
    adicionarReacao: "Adicionar reação",
    superReagirCom: "Super reagir com {{emoji}}",
    fixarMensagem: "Fixar mensagem",
    desafixarMensagem: "Desafixar mensagem",
    editarMensagem: "Editar mensagem",
    apagarMensagem: "Apagar mensagem",
    denunciarMensagem: "Denunciar mensagem",
  },
  denuncia: {
    titulo: "Denunciar mensagem",
    descricao: "A denúncia vai para a equipe do Gravaê. Conte o que aconteceu.",
    de: "De {{nome}}",
    semTexto: "(sem texto)",
    motivo: "Motivo",
    detalhes: "Detalhes (opcional)",
    enviar: "Enviar denúncia",
    enviada: "Denúncia enviada. Obrigado.",
    motivos: {
      spam: "Spam ou propaganda",
      assedio: "Assédio ou ódio",
      conteudo: "Conteúdo impróprio",
      golpe: "Golpe ou fraude",
      outro: "Outro",
    },
  },
  falha: {
    tentarDeNovo: "Tentar de novo",
    erro: "Não foi entregue",
    semConexao: "Não foi entregue — você está sem conexão",
    semAcesso: "Não foi entregue — este canal não está mais ao seu alcance",
    semPermissao: "Não foi entregue — você não pode escrever aqui",
    castigo: "Não foi entregue — você está de castigo neste servidor",
    modoLento: "Não foi entregue — o modo lento ainda não liberou",
    depressa: "Não foi entregue — você está mandando rápido demais",
    automod: "Não foi entregue — o AutoMod bloqueou",
    recusada: "Não foi entregue — esta conversa não aceita resposta",
    naoEntregue: "Não foi entregue — essa pessoa não recebe mensagens suas",
  },
  mencao: {
    cargo: "Menção de cargo",
    pessoa: "Menção",
    alguem: "alguém",
    cargoSemNome: "cargo",
    here: "Notifica quem está online",
    everyone: "Notifica o servidor",
  },
  codigo: {
    copiar: "Copiar",
    copiado: "Copiado",
    copiarAria: "Copiar o código",
    copiadoAria: "Código copiado",
    recolher: "Recolher",
    expandir: "Expandir",
    verInteiro: "Ver o arquivo inteiro",
    maisOpcoes: "Mais opções",
    baixar: "Baixar",
    recolherLinhas: "Recolher ({{linhas}} linhas)",
    expandirLinhas: "Expandir ({{linhas}} linhas)",
    mudarIdioma: "Mudar idioma",
    procurarIdioma: "Pesquisar código de idioma…",
    nenhumIdioma: "Nenhum idioma com esse nome.",
    quebrarTexto: "Quebrar texto",
  },
  caixa: {
    escrever: "Conversar em #{{canal}}",
    escreverSemCanal: "Conversar",
    semPermissao: "Você não tem permissão para enviar mensagens neste canal",
    solteParaAnexar: "Solte para anexar",
    longaTitulo: "Sua mensagem é muito longa…",
    longaDescricao: "Você chegou ao limite de {{limite}} caracteres. Dá pra mandar como arquivo.",
    enviarComoArquivo: "Enviar como arquivo",
    textoComoArquivo: "Enviar o texto como arquivo",
    arquivoGrandeTitulo: "Esse arquivo é grande demais",
    arquivoGrandeDescricao: "“{{arquivo}}” passa do limite de {{limite}} MB por arquivo.",
    respondendoPara: "Respondendo para",
    vaiNotificar: "A pessoa vai ser notificada",
    naoVaiNotificar: "A pessoa não vai ser notificada",
    ligado: "ligado",
    desligado: "desligado",
    pararDeResponder: "Parar de responder",
    mais: "Mais",
    enviarArquivo: "Enviar um arquivo",
    criarEnquete: "Criar enquete",
    expressoes: "Emoji, GIF e figurinhas",
    enviar: "Enviar",
    aguardandoEnvio: "Aguardando o upload",
    modoLento: "Modo lento ativo ({{tempo}})",
    modoLentoDica:
      "O modo lento está definido como {{segundos}}s. Aguarde antes de enviar outra mensagem.",
  },
  anexos: {
    enviando: "Enviando…",
    modificar: "Modificar {{arquivo}}",
    verPrevia: "Ver {{arquivo}}",
    excluirTitulo: "Excluir anexo",
    excluirDescricao: "Apagar “{{arquivo}}”? Não dá para desfazer, e ele sai desta mensagem.",
    excluirAcao: "Excluir anexo",
    excluirFalhou: "Não consegui apagar o anexo.",
    remover: "Remover {{arquivo}}",
    ver: "Ver {{arquivo}}",
    mostrarSpoiler: "Mostrar spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Editar anexo",
    nomeDoArquivo: "Nome do arquivo",
    descricao: "Descrição do texto alternativo",
    descricaoDica: "Descreva esta mídia para leitores de tela",
    marcarSpoiler: "Marcar como spoiler",
    cancelar: "Cancelar",
    salvar: "Salvar",
  },
  cartao: {
    tocador: "Tocador",
    abrir: "Abrir {{destino}}",
    tocar: "Tocar {{titulo}}",
    video: "vídeo",
    verImagem: "Ver imagem",
  },
  enquete: {
    criar: "Criar enquete",
    pergunta: "Pergunta",
    exemplo: "O que a gente joga hoje?",
    respostas: "Respostas",
    adicionarOpcao: "Adicionar opção",
    removerOpcao: "Remover opção",
    varias: "Permitir mais de uma resposta",
    variasDetalhe: "Sem isto, votar numa opção tira o voto da anterior.",
    duracao: "Duração",
    umaHora: "1 hora",
    quatroHoras: "4 horas",
    oitoHoras: "8 horas",
    umDia: "1 dia",
    tresDias: "3 dias",
    umaSemana: "1 semana",
    ateEncerrar: "Até eu encerrar",
    titulo: "Enquete",
    encerrada: "Enquete encerrada",
    variasRespostas: "Enquete — várias respostas",
    umVoto: "{{quantidade}} voto",
    votos: "{{quantidade}} votos",
    umVotoNoTotal: "{{quantidade}} voto no total",
    votosNoTotal: "{{quantidade}} votos no total",
    encerraEm: "encerra {{quando}}",
    encerrarAgora: "Encerrar agora",
  },
  fixadas: {
    titulo: "Mensagens fixadas",
    vazio: "Este canal não tem mensagens fixadas… por enquanto.",
    desafixar: "Desafixar",
    anexo: "(anexo)",
    enquete: "(enquete)",
    dicaRotulo: "FICA A DICA:",
    dica: "quem tem a permissão “Gerenciar mensagens” pode fixar direto no menu da mensagem.",
  },
  encaminhar: {
    titulo: "Encaminhar mensagem",
    paraOnde: "Para onde?",
    semTexto: "(mensagem sem texto)",
    nenhumLugar: "Nenhum lugar com esse nome.",
    canais: "Canais",
    conversas: "Conversas",
  },

  expressoes: {
    gifs: "GIFs",
    buscarGifs: "Buscar Klipy",
    figurinha: "Figurinha",
    buscarFigurinha: "Encontre a figurinha perfeita",
    buscarEmoji: "Encontre o emoji perfeito",
    buscarReacao: "Encontre a reação perfeita",
    adicionarEmoji: "Adicionar emoji",
    limparBusca: "Limpar a busca",
  },

  busca: {

    pesquisar: "Pesquisar mensagens",

    limpar: "Limpar a busca",

    filtros: "Filtros de busca",

    escopo: {

      titulo: "Escopo da pesquisa",

      servidor: "Comunidade atual",

      canal: "Esta conversa",

      comunidades: "Todas as comunidades",

      dms: "Apenas as DMs",

      tudo: "DMs e comunidades",

    },
    fechar: "Fechar a busca",
    procurando: "Procurando…",
    resultado: "{{quantos}} resultado",
    resultados: "{{quantos}} resultados",
    nadaCom: "Nada com {{termo}} por aqui.",
    soOsQuePodeLer: "A busca só olha os canais que você pode ler.",
  },

  entrada: {
    semNome: "conversa",
    anexo: "(anexo)",
    titulo: "Caixa de entrada",
    naoLidas: "Não lidas",
    salvas: "Salvas",
    mencoes: "Menções",
    fimTitulo: "Você chegou ao fim",
    fimDetalhe: "Não há nada por ler. Quando chegar mensagem nova, ela aparece aqui.",
    semSalvosTitulo: "Nenhum item salvo",
    semSalvosDetalhe:
      "Segure Shift e clique no marcador de uma mensagem para guardá-la e ver depois.",
    tirarDosSalvos: "Tirar dos salvos",
    semMencoesTitulo: "Nenhuma menção ainda",
    semMencoesDetalhe: "As menções a você aparecem aqui pelos últimos 7 dias.",
  },

  forum: {
    descricao:
      "Cada assunto vira uma conversa separada — bom pra dúvida que não pode se perder no meio do papo.",
    novoAssunto: "Novo assunto",
    vazio: "Nenhum assunto ainda. Comece o primeiro e a conversa fica organizada desde o início.",
    titulo: "Título",
    doQueSeTrata: "Do que se trata?",
    primeiraMensagem: "Primeira mensagem",
    conteDoCaso: "Conte o caso",
  },
};
