
export const servidor = {
  comunidade: {
    ativa: "A comunidade está aberta",
    ativaDesde: "Aberta desde {{quando}}",
    membrosAgora: "{{quantos}} membros",
    criarParaMim: "Criar um para mim",
    canalDeRegras: "Canal de regras",
    canalDeRegrasDetalhe: "Onde ficam as regras que todo mundo lê antes de falar.",
    canalDeAvisos: "Canal de avisos da comunidade",
    canalDeAvisosDetalhe: "Para onde mandamos o que muda por aqui, só para quem administra.",
    canalDeSeguranca: "Canal de alertas de segurança",
    canalDeSegurancaDetalhe: "Onde a moderação recebe o que os filtros pegaram.",
    idiomaPrincipal: "Idioma principal",
    idiomaPrincipalDetalhe: "O idioma em que a maior parte da conversa acontece.",
    semIdioma: "Nenhum idioma escolhido",
    semCanal: "Nenhum canal",
    finalTitulo: "Quase lá",
    finalDetalhe: "Antes de abrir, veja o que muda para quem chega.",
    confereRegras: "Quem entra vê o canal de regras antes de tudo.",
    confereEveryone: "Só quem tem cargo usa @everyone e @here.",
    confereMencoes: "Marcar todo mundo de uma vez passa a pedir permissão.",
    concordo: "Concordo e entendo",
    concordoDetalhe: "Você confirma que a comunidade segue as diretrizes da casa.",
    proximo: "Próximo",
    terminar: "Terminar configuração",
    visaoGeral: "Visão geral",
    visaoGeralDetalhe: "Os canais que a comunidade usa para falar com quem chega.",
    seguranca: "Segurança",
    segurancaDetalhe: "Os freios que seguram spam e conteúdo pesado.",
    habilitada: "Comunidade habilitada.",
    falhou: "Não deu para habilitar a comunidade.",
    titulo: "Comunidade",
    ilustracao: "Balões de conversa",
    convite: "Você está montando uma comunidade?",
    conviteDetalhe: "Vire uma comunidade para ganhar as ferramentas de quem cuida de um lugar grande: canal de regras, avisos da casa e filtros que moderam sozinhos.",
    contagem: "{{membros}} de {{minimo}} membros",
    faltam: "Faltam {{quantos}} para abrir.",
    prontoParaAbrir: "Já dá para abrir.",
    habilitar: "Habilitar comunidade",
    vantagemCrescer: "Crescer",
    vantagemCrescerDetalhe: "A comunidade pode se candidatar ao Explorar, e quem procura o assunto te acha.",
    vantagemModerar: "Moderar",
    vantagemModerarDetalhe: "Exigir e-mail verificado, filtrar mídia e ligar o AutoMod de uma vez.",
    vantagemAvisos: "Ficar sabendo",
    vantagemAvisosDetalhe: "A casa manda o que muda para quem administra, num canal só seu.",
    assistenteTitulo: "Vamos montar a sua comunidade.",
    passoSeguranca: "Verificações de segurança",
    passoBasico: "Preparação básica",
    passoFinal: "Toques finais",
    seguraTitulo: "Mantenha a comunidade segura",
    seguraDetalhe: "Comunidade grande atrai spam. Estes dois freios ficam ligados por padrão, e você desliga depois se atrapalharem.",
    emailVerificado: "Exigir e-mail verificado",
    emailVerificadoDetalhe: "Quem ainda não confirmou o e-mail não manda mensagem. Quem tem cargo passa direto.",
    filtroDeMidia: "Filtrar mídia explícita",
    filtroDeMidiaDetalhe: "A imagem e o vídeo que chegam entram escondidos, e só aparecem quando alguém escolhe ver.",
    basicoTitulo: "Prepare o básico",
    basicoDetalhe: "Diga em qual canal ficam as regras e para onde vão os avisos da casa. Sem canal escolhido, eu crio os dois.",
  },
  descoberta: {
    quantosComandos: "{{quantos}} comandos",
    previa: "Como o cartão fica",
    trocarIcone: "Trocar o ícone",
    tirarCapa: "Tirar a capa",
    heroComunidades: "Tem gente falando do que você gosta",
    heroComunidadesDetalhe: "Comunidades abertas por quem usa o Gravaê. Entre, leia o papo e fique se gostar.",
    emDestaque: "Em destaque",
    todasAsComunidades: "As outras",
    heroTitulo: "O que a sua turma vai usar hoje?",
    heroDetalhe: "Bots de música, de jogo e de moderação, feitos por quem também está aqui. Escolha um e ele entra no servidor.",
    novidades: "Chegaram agora",
    todosOsApps: "Os outros",
    lojaTitulo: "Página do aplicativo",
    lojaDetalhe: "É o que aparece no Explorar para quem ainda não conhece.",
    capa: "Capa",
    capaDetalhe: "A imagem larga do alto da página. 1280 × 720 cai bem.",
    trocarCapa: "Trocar capa",
    categorias: "Categorias",
    categoriasDetalhe: "Até {{quantas}}. É por elas que se navega no Explorar.",
    idiomas: "Idiomas",
    idiomasDetalhe: "Até {{quantos}}. Em quais idiomas o aplicativo responde.",
    termos: "Termos de uso",
    politica: "Política de privacidade",
    politicas: "Políticas",
    servidorDeSuporte: "Servidor de suporte",
    servidorDeSuporteDetalhe: "Para onde vai quem precisar de ajuda com o aplicativo.",
    semServidor: "Nenhum",
    emQuantosServidores: "Em quantos servidores",
    categoria: {
      GAMES: "Games",
      MUSICA: "Música",
      MODERACAO: "Moderação",
      PRODUTIVIDADE: "Produtividade",
      SOCIAL: "Social",
      UTILIDADES: "Utilidades",
      ARTE_E_CRIACAO: "Arte e criação",
      EDUCACAO: "Educação",
      OUTRA: "Outra",
    },
    appIndisponivel: "Aplicativo indisponível",
    voltarParaExplorar: "Voltar para o Explorar",
    adicionarApp: "Adicionar app",
    copiarLink: "Copiar o link",
    denunciarApp: "Denúncia no app",
    copiarIdDoApp: "Copiar ID do aplicativo",
    visaoGeral: "Visão geral",
    comandos: "Comandos",
    permissoes: "Permissões",
    semPermissoes: "Este aplicativo não pede nenhuma permissão.",
    avisoDePermissoes: "Ele entra com um cargo próprio. Dá para mexer nessas permissões depois, em Configurações do servidor → Cargos.",
    servidoresEmComum: "Servidores em comum",
    umServidorEmComum: "1 servidor",
    quantosServidoresEmComum: "{{quantos}} servidores",
    feitoPor: "Feito por",
    publicadoEm: "Publicado em",
    denunciarNome: "Denunciar {{nome}}",
    denunciaDetalhe: "A denúncia vai para a equipe do Gravaê. Quem fez o aplicativo não fica sabendo que foi você.",
    denunciaFalhou: "Não deu para enviar a denúncia.",
    umMembro: "1 membro",
    semDescricao: "Sem descrição.",
    adicionar: "Adicionar",
    jaEstaAqui: "Você já está aqui",
    entrando: "Entrando…",
    entrar: "Entrar",
    comunidadePublica: "Comunidade pública",
    online: "{{quantos}} online",
    membros: "{{quantos}} membros",
    abrirComunidade: "Abrir a comunidade",
  },
  trilho: {
    transmitindo: "Alguém transmitindo",
    emChamada: "{{count}} em chamada",
  },
  titulo: "Configurações do servidor",
  novasMensagens: "Novas mensagens",
  menu: {
    silenciar: "Silenciar comunidade",
    reativar: "Reativar comunidade",
    porQuinze: "Por 15 minutos",
    porMeiaHora: "Por 30 minutos",
    porTresHoras: "Por 3 horas",
    porTresDias: "Por 3 dias",
    porUmaHora: "Por 1 hora",
    porOitoHoras: "Por 8 horas",
    porUmDia: "Por 24 horas",
    ateReativar: "Até eu reativar",
    notificacoes: "Configurações de notificação",
    padrao: "Seguir o padrão",
    todas: "Todas as mensagens",
    soMencoes: "Só menções",
    nada: "Nada",
    ocultarSilenciados: "Ocultar canais silenciados",
    denunciar: "Denunciar comunidade",
    marcarLida: "Marcar como lida",
    convidar: "Convidar membros",
    editarPerfil: "Editar perfil da comunidade",
    configuracoes: "Configurações da comunidade",
    sair: "Sair da comunidade",
    sairTitulo: "Sair de {{nome}}?",
    sairDescricao: "Para voltar, vai precisar de um convite novo.",
    copiarId: "Copiar ID da comunidade",
    idCopiado: "ID copiado.",
  },
  convite: {
    cartaoTitulo: "Você foi convidado a entrar numa comunidade",
    indisponivel: "Convite indisponível",
    indisponivelDetalhe: "Ele expirou, esgotou, ou quem criou apagou.",
    entrar: "Entrar na comunidade",
    chamado: "Você foi convidado(a) para entrar em",
    aceitarComo: "Aceitar como {{nome}}",
    abrir: "Abrir a comunidade",
    recusar: "Não, valeu",
  },
  pasta: {
    silenciarTodas: "Silenciar comunidades",
    reativarTodas: "Reativar comunidades",
    mostrarSilenciados: "Mostrar canais silenciados",
    notificacoesDaComunidade: "Configurações de notificação",
    silenciarEveryone: "Silenciar @everyone e @here",
    permitirEveryone: "Permitir @everyone e @here",
    silenciarCargos: "Silenciar menções de cargo",
    permitirCargos: "Permitir menções de cargo",
    dicaDaCor: "Escreva uma cor (hex, rgb(), hsl() ou nome) ou use o seletor.",
    mostrarIcone: "Mostrar ícone quando fechada",
    dicaDoIcone: "Fechada, mostra o ícone em vez dos servidores de dentro.",
    icone: "Ícone da pasta",
    excluir: "Excluir pasta",
    icones: {
      pasta: "Pasta",
      estrela: "Favoritar",
      coracao: "Coração",
      salvar: "Salvar",
      jogo: "Controle de jogo",
      escudo: "Proteger",
      nota: "Nota musical",
    },
    marcarLida: "Marcar pasta como lida",
    configuracoes: "Configurações da pasta",
    desfazer: "Desfazer pasta",
    titulo: "Pasta",
    nome: "Nome",
    semNome: "Sem nome",
    cor: "Cor",
    semCor: "Sem cor",
    salvar: "Salvar",
  },
  denuncia: {
    titulo: "Denunciar {{nome}}",
    descricao: "A denúncia vai para a equipe do Gravaê. Conte o que aconteceu.",
    motivo: "Motivo",
    detalhes: "Detalhes (opcional)",
    enviar: "Enviar denúncia",
    enviada: "Denúncia enviada. Obrigado.",
    motivos: {
      spam: "Spam ou propaganda",
      assedio: "Assédio ou ódio",
      conteudo: "Conteúdo impróprio",
      golpe: "Golpe ou fraude",
      outro: "Outro",
    },
  },
  selos: {
    verificada: "Comunidade verificada",
    detectavel: "Comunidade detectável",
  },

  abas: {
    pesquisar: "Pesquisar nas configurações",
    semResultado: "Nada com esse nome por aqui.",
    comunidade: "Comunidade",
    expressoes: "Expressões",
    pessoas: "Pessoas",
    apps: "Apps",
    moderacao: "Moderação",
    banimentos: "Banimentos",
  },

  auditoria: {
    titulo: "Registro de auditoria",
    porUsuario: "Filtrar por usuário",
    porAcao: "Filtrar por ação",
    vazio: "Nada registrado ainda com esse filtro.",
    motivo: "Motivo:",
    todasAsAcoes: "Todas as ações",
    todosOsUsuarios: "Todos os usuários",
    filtroMembros: "Membros",
    filtroCanais: "Canais",
    filtroEmojis: "Emojis",
    filtroServidor: "Servidor",
  },

  banimentos: {
    titulo: "Lista de banimentos do servidor",
    descricao:
      "Quem está aqui não entra nem com convite novo. Desbanir devolve o acesso na hora.",
    procurar: "Procurar banimentos por nome de usuário",
    vazioTitulo: "Sem banimentos",
    vazio: "Você ainda não baniu ninguém… mas se e quando precisar, não hesite.",
    desbanir: "Desbanir",
  },

  excluir: {
    titulo: "Excluir servidor",
    aviso: "Isso não pode ser desfeito.",
    tudoVai:
      "Todos os canais, mensagens e convites de {{servidor}} serão apagados para os {{membros}} membros. Ninguém consegue recuperar depois.",
    digite: "Digite {{servidor}} para confirmar",
  },

  emblemas: {
    titulo: "Emblemas",
    vazio: "Nenhum emblema ainda.",
    novo: "Novo emblema",
    apagarDescricao: "Ele sai de quem estiver usando. Não dá pra desfazer.",
  },

  convites: {
    titulo: "Convites",
    descricao: "Todos os links de convite ativos deste servidor.",
    vazio: "Nenhum convite criado ainda.",
    revogar: "Revogar convite",
    revogarTitulo: "Revogar convite?",
    revogarAcao: "Revogar",
    revogarDescricao:
      "O link {{codigo}} para de funcionar na hora. Quem já entrou por ele continua no servidor.",
  },

  integracoes: {
    titulo: "Integrações",
    descricao:
      "Um webhook é um endereço que posta num canal sem precisar de conta. Serve pra avisar quando um build passa, quando alguém abre um chamado, ou o que você quiser mandar de um script.",
    novo: "Novo webhook",
    vazio: "Nenhum webhook ainda. Crie um e cole a URL onde quiser que a mensagem venha.",
    canal: "Canal",
    apagar: "Apagar webhook",
    comoUsar: "Como usar",
    comoUsarTexto:
      "Mande um POST com JSON:",
    opcionais:
      "username e avatar_url são opcionais e valem por mensagem. O limite é de 5 mensagens a cada 5 segundos.",
    apagarDescricao:
      "A URL para de funcionar na hora. As mensagens que ele já mandou continuam no canal.",
  },

  explorar: {
    titulo: "Explorar",
  },
  engajamento: {
    titulo: "Engajamento",
    descricao:
      "O que o servidor faz sozinho para não parecer vazio quando chega gente nova.",
    sistema: "Mensagens do sistema",
    boasVindas: "Enviar uma mensagem de boas-vindas quando alguém entrar",
    sorteio: "Sem texto próprio embaixo, a frase é sorteada — sempre a mesma cansa rápido.",
    canalDoSistema: "Canal de mensagens do sistema",
    mensagem: "Mensagem de boas-vindas",
    deixeVazio: "Deixe vazio para sortear entre as frases prontas",
    semCanal: "Sem canal de sistema",
  },

  automod: {
    titulo: "AutoMod",
    descricao:
      "Filtros que moderam sozinhos, antes de a mensagem existir. Quem administra o servidor nunca é filtrado — e cargos isentos passam direto.",
    palavras: {
      titulo: "Bloquear palavras personalizadas",
      descricao: "Sua lista de palavras que ninguém pode escrever.",
    },
    mencoes: {
      titulo: "Bloquear spam de menções",
      descricao: "Bloqueia mensagem com menções demais de uma vez.",
    },
    links: {
      titulo: "Bloquear links",
      descricao: "Segura qualquer endereço colado no chat.",
    },
    definir: "Definir",
    nomeDaRegra: "Nome da regra",
    bloqueadas: "Palavras bloqueadas",
    digiteEnter: "Digite e aperte Enter",
    comparacao:
      "A comparação ignora maiúscula, acento e pontuação — e não pega palavra dentro de outra (\"burro\" não bloqueia \"burrocracia\").",
    aPartirDe: "Bloquear a partir de quantas menções",
    oQueFazer: "O que fazer",
    canalDoAlerta: "Canal do alerta",
    escolhaCanal: "Escolha um canal",
    castigo: "Castigo (minutos)",
    isentos: "Cargos isentos",
    semCargos: "Nenhum cargo criado ainda.",
    salvarRegra: "Salvar regra",
    apagar: "Apagar regra",
    excluirTitulo: "Excluir regra do AutoMod?",
    excluirDescricao:
      "O servidor deixa de filtrar por ela na hora. Dá pra criar de novo, mas a configuração atual se perde.",
    excluirAcao: "Excluir regra",
  },

  cargos: {
    titulo: "Cargos",
    descricao:
      "Cargos dão nome, cor e poderes. Quem está mais alto na lista manda em quem está abaixo — e ninguém mexe em cargo igual ou acima do próprio.",
    criar: "Criar cargo",
    vazio: "Nenhum cargo ainda.",
    abaExibicao: "Exibição",
    abaPermissoes: "Permissões",
    abaMembros: "Membros — {{quantos}}",
    everyone: "Vale para todo mundo no servidor. É a base sobre a qual os outros cargos somam.",
    nomeDoCargo: "Nome do cargo",
    cor: "Cor do cargo",
    corDica: "Pinta o nome de quem tem o cargo na lista de membros e no chat.",
    semCor: "Sem cor",
    corPersonalizada: "Cor personalizada",
    estilo: "Estilo do nome",
    segundaCor: "Segunda cor",
    segundaCorDica: "Sem ela, o gradiente cai para cor sólida — não some.",
    limparSegundaCor: "Limpar segunda cor",
    icone: "Ícone",
    iconeDica: "Aparece ao lado do cargo no cartão de perfil de quem o tem.",
    exibirSeparado: "Exibir separado dos outros membros",
    exibirSeparadoDica: "O cargo ganha uma seção própria na lista de membros.",
    permitirMencionar: "Permitir mencionar este cargo",
    permitirMencionarDica: "Qualquer um poderá notificar todo mundo que tem o cargo.",
    semPoderDeConceder: "{{descricao}} (você não tem esta permissão para conceder)",
    adicionar: "Adicionar alguém a este cargo",
    tirar: "Tirar o cargo",
    semNinguem: "Ninguém tem este cargo ainda.",
    apagar: "Apagar cargo",
    excluirTitulo: "Excluir cargo \"{{nome}}\"?",
    excluirDescricao: "Quem tem esse cargo perde tudo o que ele dava. Não dá pra desfazer.",
    excluirAcao: "Excluir cargo",
  },

  membros: {
    procurar: "Pesquisar pelo nome ou usuário",
    membroDesde: "Membro desde",
    vazio: "Ninguém encontrado.",
    acoesPara: "Ações para {{nome}}",
    deCastigo: "de castigo",
    tirarCastigo: "Tirar do castigo",
    castigo5min: "5 minutos",
    castigo1h: "1 hora",
    castigo1d: "1 dia",
    castigo1s: "1 semana",
    expulsar: "Expulsar",
    expulsarTitulo: "Expulsar {{nome}}?",
    expulsarDescricao:
      "sai de {{servidor}} na hora. Pode entrar de novo com um convite — expulsar não impede a volta.",
    banir: "Banir",
    banirTitulo: "Banir {{nome}}?",
    banirDescricao:
      "sai de {{servidor}} e não consegue voltar, nem com convite, até ser desbanido.",
    motivo: "Motivo (opcional)",
    motivoDica: "Fica registrado na auditoria",
  },

  perfil: {
    titulo: "Perfil do servidor",
    descricao: "É assim que seu servidor aparece na lista e nos links de convite.",
    icone: "Ícone",
    faixa: "Faixa do topo",
    nomeDoServidor: "Nome do servidor",
    campoDescricao: "Descrição",
    doQueE: "Do que é esse servidor?",
    comprimido: "Comprimido antes de subir: {{economia}}",
  },

  etiqueta: {
    titulo: "Tag do servidor",
    descricao:
      "Uma etiqueta de até 4 letras que aparece ao lado do nome de quem é membro — no chat e na lista de pessoas. Aqui é de graça: sem impulso, sem nível.",
    escolhaNome: "Escolha um nome",
    limite: "No máximo 4 caracteres, letras e números.",
    escolhaInsignia: "Escolha uma insígnia",
    voce: "Você",
    fala1: "alguém aí pra jogar?",
    fala2: "dá uma olhada na minha tag!",
    fala3: "eita, como conseguiu isso",
  },

  expressoes: {
    comoUsar:
      "Adicione até {{limite}} emojis que todo mundo pode usar neste servidor. Digite :nome: no chat para mandar.",
    imagem: "Imagem",
    enviadoPor: "Enviado por",
    semEmoji: "Nenhum emoji ainda.",
    figurinhas: "Figurinhas",
    enviarFigurinha: "Enviar figurinha",
    nomeDaFigurinha: "Nome da figurinha",
    exemploFigurinha: "Ex: abraço de gatinho",
    figurinhaGrande: "A figurinha passa de {{limite}}.",
    deixaPraLa: "Deixa pra lá",
    sons: "Painel de efeitos sonoros",
    enviarSom: "Enviar som",
    nomeDoSom: "Nome do som",
    semSom: "Nenhum som ainda.",
    somGrande: "O som passa de {{limite}}.",
    emojiRelacionado: "Emoji relacionado",
    ouvir: "Ouvir",
    ouvirAssim: "Ouvir assim",
    volumeDe: "Volume de {{nome}}",
    volumeDica:
      "Vale pra todo mundo do servidor. Cada pessoa ainda pode abaixar os sons só pra ela, no painel da chamada.",
    falhaEnvio: "Não deu pra subir o arquivo.",
    excluirTitulo: "Excluir {{tipo}} \"{{nome}}\"?",
    excluirDescricao:
      "Some do servidor para todo mundo. As mensagens que já usaram continuam como estão.",
  },

  canal: {
    tipoLink: "Link",
    tipoLinkDica: "Aponta para um endereço de fora e abre no navegador",
    endereco: "Endereço",
    enderecoDica: "Para onde este canal leva. Precisa começar com https://",
    visaoGeral: "Visão geral",
    nome: "Nome do canal",
    topico: "Tópico do canal",
    topicoDica: "Do que se fala aqui?",
    modoLento:
      "Cada pessoa só manda uma mensagem por intervalo. Quem gerencia mensagens ou canais passa direto.",
    visibilidade: "Visibilidade do conteúdo",
    padrao: "Padrão",
    padraoDica: "O conteúdo do canal fica sempre visível.",
    spoiler: "Canal de spoiler",
    spoilerDica:
      "Marque este canal como contendo spoilers, para que plot twists e assuntos pesados fiquem ocultos até alguém escolher ver.",
    idade: "Canal com restrição de idade",
    idadeDica: "Quem entrar precisa confirmar que é maior de idade para ver o conteúdo.",
    bitrateDica: "Passar de 64 kbps pode atrapalhar quem tem internet ruim.",
    qualidadeDeVideo: "Qualidade do vídeo",
    automatica: "Automática",
    limite: "Limite de usuários — {{valor}}",
    pessoas: "{{quantos}} pessoas",
    semLimite: "sem limite",
    permissoesDescricao:
      "Aqui você muda o que vale neste canal. O que ficar em “herdar” continua seguindo o cargo.",
    excluir: {
      titulo: "Excluir canal",
      historico: "Todo o histórico de {{canal}} vai junto, para todo mundo.",
      digite: "Digite {{canal}} para confirmar",
    },
  },

  moderacao: {
    titulo: "Visualização de moderador",
    semPermissao: "Você precisa da permissão “Moderar membros” para ver isto.",
    fecharEsc: "Fechar (Esc)",
    atividade: "Atividade no servidor",
    mensagens: "Mensagens",
    links: "Links",
    midia: "Mídia",
    acoesNaAuditoria: "Ações na auditoria",
    moderacoesSofridas: "Moderações sofridas",
    permissoes: "Permissões ({{quantas}})",
    semPermissaoEspecial: "Nenhuma permissão especial.",
    conta: "Conta",
    entrouNoServidor: "Entrou no servidor",
    contaCriadaEm: "Conta criada em",
    deCastigoAte: "De castigo até",
    formaDeAdesao: "Forma de adesão",
    mensagem: "Mensagem",
    castigo: "Castigo",
    copiarId: "Copiar ID",
    idCopiado: "ID copiado.",
    adicionarCargo: "Adicionar cargo",
    semCargos: "Nenhum cargo criado",
    soEveryone: "Só o @everyone.",
    voltar: "Voltar",
    vazio: "Nada por aqui.",
    cinquenta: "Mostrando as 50 mais recentes.",
    irParaMensagem: "Ir para mensagem",
    precisaSerAmigo: "Vocês precisam ser amigos para conversar.",
    expulsarDescricao: "Sai do servidor na hora, mas pode voltar com um convite.",
    banirDescricao:
      "Sai do servidor e não consegue voltar, nem com convite, até ser desbanido.",
    castigarTitulo: "Castigar {{nome}}?",
    castigoDescricao: "Enquanto durar, não escreve nem fala em nenhum canal do servidor.",
    aplicarCastigo: "Aplicar castigo",
    duracao: "Duração em minutos",
    informeDuracao: "Informe a duração em minutos.",
  },
};
