export const amizades = {
  ativosAgora: "Active now",
  procurando: "Seeing who's around…",
  tudoTranquilo: "All quiet for now…",
  tudoTranquiloDetalhe: "When you or a friend joins a call, it shows up here — and you can jump in with one click.",
  emVoz: "In voice",
  voce: "You",
  soVoce: "Just you",
  pessoas: "{{quantas}} people",
  voltarParaChamada: "Back to the call",
  entrarNaChamada: "Join the call",
  abrirCanal: "Open {{canal}} in {{servidor}}",
  mensagensDiretas: "Direct messages",
  encontreConversa: "Find a conversation",
  amigos: "Friends",
  conversas: "Conversations",
  semConversas: "No conversations yet. Add a friend to get started.",
  semConversaComEsseNome: "No conversation by that name.",
  abrirMenu: "Open servers and conversations",
  solicitacoes: "Message requests",
  pedidos: "Requests",
  spam: "Spam",
  pedidosPendentes: "Pending requests",
  marcadosComoSpam: "Marked as spam",
  aceitar: "Accept",
  ignorar: "Ignore",
  marcarSpam: "Mark as spam",
  semPedidos: "No requests waiting.",
  semPedidosDetalhe: "People who aren't your friends but share a server with you land here before reaching your conversations.",
  semSpam: "Nothing marked as spam.",
  semSpamDetalhe: "Whatever the spam filter sets aside, or whatever you mark, is kept in this tab.",
  umServidorEmComum: "1 server in common",
  servidoresEmComum: "{{quantos}} servers in common",
  semServidoresEmComum: "No servers in common",
};
