export const comum = {
  voltar: "Back",
  agoraNao: "Not now",
  erro: {
    tentarDeNovo: "Try again",
    recarregar: "Reload",
    copiarDetalhes: "Copy the details",
    parteQuebrou: "This part of the screen broke.",
    titulo: "Gravaê tripped up.",
    detalhe: "Something broke along the way and the screen couldn't draw itself. Your conversation isn't lost — it's all on the server.",
  },
  conexao: {
    voltou: "Connected again",
    reconectando: "Reconnecting",
    tentativaSufixo: " · attempt {{numero}}",
    aSalvo: "The conversation is safe on the server. This comes back on its own as soon as the connection returns.",
  },
  avisoDoNavegador: {
    titulo: "Want to be told about messages?",
    detalhe: "With Gravaê behind another window, it will call you.",
  },
  atualizacao: {
    titulo: "Update",
    semAuto: "This version of the app can't update itself. Download the newest installer below and install over the top.",
    versaoAtual: "You're on version {{versao}}.",
    instalando: "Installing version {{versao}}…",
    prontaVersao: "Version {{versao}} is ready to install",
    baixandoVersao: "Downloading version {{versao}}…",
    baixandoComProgresso: "Downloading version {{versao}}… {{porcento}}%",
    saiuVersao: "Version {{versao}} is out",
    saiuVersaoClique: "Version {{versao}} is out — click to download",
    instalarVersaoEReiniciar: "Install version {{versao}} and restart",
    erroTenteDeNovo: "{{erro}} Click to try again.",
    procurando: "Looking…",
    emDia: "You're up to date",
    vaiFechar: "The app will close in a moment.",
    comoInstala: "The app closes, swaps the version and reopens on its own. You'll leave any call you're in.",
    semServidor: "I couldn't reach the version server.",
    procuraSozinho: "The app looks on its own at startup and every six hours.",
    instalandoReticencias: "Installing…",
    instalandoCurto: "Installing",
    baixandoCurto: "Downloading",
    tentarDeNovo: "Try again",
    reiniciarAgora: "Restart now",
    instalarEReiniciar: "Install and restart",
    baixar: "Download",
    procurar: "Check",
    baixarApp: "Download the app",
    ariaBotao: "App update",
  },
  janela: {
    ajustarAltura: "Adjust the height",
    redimensionar: "Resize the window",
    ajustarLargura: "Adjust the width",
  },
  dica: {
    rotulo: "Tip:",
    pularConfirmacao: "hold Shift as you click to skip this confirmation.",
  },
  cor: {
    pescar: "Pick a color from the screen",
    hex: "Hexadecimal value",
  },
  imagem: {
    titulo: "Choose an image",
    enviar: "Send an image",
    escolherGif: "Choose a GIF",
    buscarGif: "Search GIFs",
  },
  fonte: {
    rotulo: "Message font",
    padrao: "Default",
    comNome: "Message font — {{fonte}}",
  },
  recorte: {
    titulo: "Crop the icon",
    detalhe: "Drag to choose the part you want and use the slider to zoom. The icon is round everywhere in the app.",
    voltarAoComeco: "Back to the start",
    usar: "Use this crop",
  },
  mais: "More",
  carregando: "Loading…",
  salvar: "Save",
  salvando: "Saving…",
  descartar: "Discard",
  redefinir: "Reset",
  naoSalvo: "You have unsaved changes.",
  fechar: "Close",
  criar: "Create",
  nome: "Name",
  emoji: "Emoji",
  previa: "Preview",
  cancelar: "Cancel",
  enviar: "Send",
  apagar: "Delete",
  excluir: "Delete",
  remover: "Remove",
  trocar: "Change",
};
