export const configuracoes = {
  sair: "Log out",
  versoes: {
    copiar: "Click to copy",
    copiado: "Copied",
  },
  telas: {
    conta: "My account",
    privacidade: "Privacy",
    conexoes: "Connections",
    voz: "Audio",
    video: "Video",
    avisos: "Notifications",
    aplicativos: "Applications",
    aparencia: "Appearance",
    batePapo: "Chat",
    acessibilidade: "Accessibility",
    idioma: "Language",
    aplicativo: "Get the app",
    atalhos: "Shortcuts",
    desktop: "Desktop app",
    avancado: "Advanced",
    servidor: "Server",
  },
  grupos: {
    conta: "Account",
    app: "App settings",
    desenvolvedor: "Developer",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Login details",
    dispositivos: "Devices",
    usuariosBloqueados: "Blocked users",
    aplicativosAutorizados: "Authorized apps",
    sessoes: "Sessions",
    amigosEDms: "Friends and direct messages",
    compartilhamentoDeAtividade: "Activity sharing",
    visibilidadeDoPerfil: "Profile visibility",
    exportarDados: "Export data",
    exclusaoDeDados: "Delete data",
    tema: "Theme",
    corDeDestaque: "Accent color",
    interface: "Interface",
    listaDeCanais: "Channel list",
    zoomDoApp: "App zoom level",
    escalaDaFonte: "Chat font scale",
    modoStreamer: "Streaming privacy",
    movimento: "Motion",
    textoEmVoz: "Text to speech",
    teclado: "Keyboard",
    formatoDaHora: "Time format",
    idiomaDaInterface: "Interface language",
    dispositivosDeVoz: "Devices",
    testeDoMicrofone: "Microphone test",
    modoDeEntrada: "Input mode",
    sensibilidade: "Input sensitivity",
    qualidade: "Quality",
    camera: "Camera",
    transmissao: "Streaming",
    exibicao: "Display",
    entrada: "Input",
    midia: "Media",
    geral: "General",
    preferenciaDeMencao: "Mention preference",
    sons: "Sounds",
  },
};
