export const configuracoes = {
  efeitos: {
    titulo: "Pointer effects",
    detalhe: "A trail and sparks drawn over the app. They start off, and switch themselves off if you asked for less motion.",
    rastro: "Cursor trail",
    rastroDetalhe: "A line that follows the pointer and fades out behind it.",
    faisca: "Spark on click",
    faiscaDetalhe: "Short lines that fly out from where you clicked.",
    cor: "Color",
    espessura: "Thickness",
    comprimento: "Length",
    tamanho: "Size",
    quantidade: "Count",
  },
  email: {
    verificarTitulo: "Confirm your email",
    verificarDetalhe: "Some communities only let confirmed people post. It takes one click.",
    enviar: "Send the link",
    enviado: "Check the inbox. The link lasts a day.",
    falhou: "The email couldn't be sent.",
    confirmado: "Email confirmed",
    confirmadoDetalhe: "Done. Now you can post in any community that asks for it.",
    linkIncompleto: "Incomplete link",
    linkIncompletoDetalhe: "The code is missing from the address. Open the link straight from the email.",
    confirmando: "Confirming…",
    expirou: "This link has already been used or has expired.",
    irParaOApp: "Go to the app",
  },
  tema: {
    indisponivel: "Theme unavailable",
    indisponivelDetalhe: "Whoever published it deleted it, or the link is wrong.",
    indisponivelLinha: "Theme unavailable. Whoever published it deleted it, or the link is wrong.",
    importar: "Import theme",
    importarCurto: "Import",
    importarDetalhe: "This replaces the theme you have now. You can edit it afterwards in Settings > Appearance > Theme studio.",
    porAutor: "by {{autor}}",
    umaCorTrocada: "1 color swapped",
    coresTrocadas: "{{quantas}} colors swapped",
    avisoDeCss: "This theme carries CSS from whoever wrote it, and CSS reaches every corner of the screen. Only import from people you trust.",
    soCores: "This theme only swaps colors. No CSS from outside.",
    aplicar: "Apply",
    previaSemMotor: "The preview doesn't run the engine. Install it to see it.",
    motorAnimado: "{{motor}} animated",
  },
  sair: "Log out",
  versoes: {
    termos: "Terms of service",
    privacidade: "Privacy policy",
    copiar: "Click to copy",
    copiado: "Copied",
  },
  telas: {
    conta: "My account",
    privacidade: "Privacy",
    conexoes: "Connections",
    voz: "Audio",
    video: "Video",
    avisos: "Notifications",
    aplicativos: "Applications",
    aparencia: "Appearance",
    batePapo: "Chat",
    acessibilidade: "Accessibility",
    idioma: "Language",
    aplicativo: "Get the app",
    atalhos: "Shortcuts",
    desktop: "Desktop app",
    avancado: "Advanced",
    servidor: "Server",
    comunicado: "System announcement",
    denuncias: "Reports",
    publicacoes: "Deployments",
  },
  grupos: {
    conta: "Account",
    app: "App settings",
    desenvolvedor: "Developer",
    administracao: "Administration",
  },
  secoes: {
    detalhesDeLogin: "Login details",
    dispositivos: "Devices",
    usuariosBloqueados: "Blocked users",
    aplicativosAutorizados: "Authorized apps",
    sessoes: "Sessions",
    amigosEDms: "Friends and direct messages",
    compartilhamentoDeAtividade: "Activity sharing",
    visibilidadeDoPerfil: "Profile visibility",
    exportarDados: "Export data",
    exclusaoDeDados: "Delete data",
    tema: "Theme",
    corDeDestaque: "Accent color",
    interface: "Interface",
    listaDeCanais: "Channel list",
    zoomDoApp: "App zoom level",
    escalaDaFonte: "Chat font scale",
    modoStreamer: "Streaming privacy",
    cursores: "Cursors",
    movimento: "Motion",
    textoEmVoz: "Text to speech",
    teclado: "Keyboard",
    formatoDaHora: "Time format",
    idiomaDaInterface: "Interface language",
    dispositivosDeVoz: "Devices",
    testeDoMicrofone: "Microphone test",
    modoDeEntrada: "Input mode",
    sensibilidade: "Input sensitivity",
    qualidade: "Quality",
    camera: "Camera",
    transmissao: "Streaming",
    exibicao: "Display",
    entrada: "Input",
    midia: "Media",
    geral: "General",
    preferenciaDeMencao: "Mention preference",
    sons: "Sounds",
  },
};
