export const conversa = {
  lista: {
    carregando: "Loading messages…",
    carregandoMais: "Loading…",
    verMais: "Scroll up to see more",
    semHistorico: "History unavailable",
    semHistoricoDetalhe: "Your role doesn't have permission to read the history of #{{canal}}. New messages keep showing up while you're here.",
    boasVindas: "Welcome to #{{canal}}",
    boasVindasDetalhe: "This is the beginning of #{{canal}}.",
  },
  data: {
    hoje: "Today",
    ontem: "Yesterday",
    hojeAs: "today at {{hora}}",
    ontemAs: "yesterday at {{hora}}",
  },
  digitando: {
    um: "{{nome}} is typing…",
    dois: "{{primeiro}} and {{segundo}} are typing…",
    varios: "{{quantidade}} people are typing…",
  },
  mensagem: {
    usou: "used",
    fixada: "pinned",
    editado: "(edited)",
    ignorada: "Message from someone you ignore.",
    mostrar: "Show",
    escPara: "Esc to",
    cancelar: "cancel",
    enterParaSalvar: "Enter to save",
    falhou: "It wasn't sent. Try again",
    naoLidasDaqui: "Unread from here.",
    linkCopiado: "Link copied.",
    idCopiado: "ID copied.",
    naoDeuParaCopiar: "Your browser wouldn't let us copy.",
    apagarTitulo: "Delete message?",
    apagarDescricao: "It disappears for everyone in the channel. There is no undo.",
    apagarAcao: "Delete",
    citacaoAnexo: "click to see the attachment",
    citacaoSumiu: "The original message isn't here anymore.",
    reagirCom: "React with {{emoji}} — hold to super react",
    segureParaSuper: "{{emoji}} — hold to super react",
  },
  acoes: {
    reagir: "React",
    responder: "Reply",
    encaminhar: "Forward",
    favoritar: "Bookmark message",
    tirarDosFavoritos: "Remove from bookmarks",
    marcarNaoLida: "Mark as unread",
    copiarLink: "Copy message link",
    copiarId: "Copy message ID",
    fixar: "Pin message",
    desafixar: "Unpin",
    editar: "Edit",
    apagar: "Delete",
    mais: "More",
    adicionarReacao: "Add reaction",
    superReagirCom: "Super react with {{emoji}}",
    fixarMensagem: "Pin message",
    desafixarMensagem: "Unpin message",
    editarMensagem: "Edit message",
    apagarMensagem: "Delete message",
  },
  mencao: {
    cargo: "Role mention",
    pessoa: "Mention",
    alguem: "someone",
    cargoSemNome: "role",
    here: "Notifies whoever is online",
    everyone: "Notifies the server",
  },
  codigo: {
    copiar: "Copy",
    copiado: "Copied",
    copiarAria: "Copy the code",
    copiadoAria: "Code copied",
  },
  caixa: {
    escrever: "Message #{{canal}}",
    escreverSemCanal: "Message",
    semPermissao: "You don't have permission to send messages in this channel",
    solteParaAnexar: "Drop to attach",
    respondendoPara: "Replying to",
    vaiNotificar: "They will be notified",
    naoVaiNotificar: "They won't be notified",
    ligado: "on",
    desligado: "off",
    pararDeResponder: "Stop replying",
    mais: "More",
    enviarArquivo: "Upload a file",
    criarEnquete: "Create a poll",
    expressoes: "Emoji, GIF and stickers",
    enviar: "Send",
    aguardandoEnvio: "Waiting for the upload",
    modoLento: "Slow mode on ({{tempo}})",
    modoLentoDica: "Slow mode is set to {{segundos}}s. Wait before sending another message.",
  },
  anexos: {
    enviando: "Uploading…",
    modificar: "Modify {{arquivo}}",
    remover: "Remove {{arquivo}}",
    ver: "View {{arquivo}}",
    mostrarSpoiler: "Show spoiler: {{arquivo}}",
    spoiler: "spoiler",
    spoilerTitulo: "Spoiler",
    editarTitulo: "Edit attachment",
    nomeDoArquivo: "File name",
    descricao: "Alt text description",
    descricaoDica: "Describe this media for screen readers",
    marcarSpoiler: "Mark as spoiler",
    cancelar: "Cancel",
    salvar: "Save",
  },
  cartao: {
    tocador: "Player",
    abrir: "Open {{destino}}",
    tocar: "Play {{titulo}}",
    video: "video",
    verImagem: "View image",
  },
  enquete: {
    titulo: "Poll",
    encerrada: "Poll closed",
    variasRespostas: "Poll — multiple answers",
    umVoto: "{{quantidade}} vote",
    votos: "{{quantidade}} votes",
    umVotoNoTotal: "{{quantidade}} vote in total",
    votosNoTotal: "{{quantidade}} votes in total",
    encerraEm: "closes {{quando}}",
    encerrarAgora: "Close now",
  },
  fixadas: {
    titulo: "Pinned messages",
    vazio: "This channel has no pinned messages… yet.",
    desafixar: "Unpin",
    anexo: "(attachment)",
    enquete: "(poll)",
    dicaRotulo: "PROTIP:",
    dica: "anyone with the “Manage messages” permission can pin straight from the message menu.",
  },
  encaminhar: {
    titulo: "Forward message",
    paraOnde: "Where to?",
    semTexto: "(message with no text)",
    nenhumLugar: "No place with that name.",
    canais: "Channels",
    conversas: "Direct messages",
  },
};
