export const perfil = {
  carregando: "Loading…",
  editar: "Edit profile",
  mensagem: "Message",
  abrirConversa: "Open conversation",
  verCompleto: "See full profile",
  convidarParaServidor: "Invite to server",
  semServidores: "You have no servers",
  conviteEnviado: "Invite sent to {{nome}}.",
  moderador: "Open in moderator view",
  mais: "More",
  ignorar: "Ignore",
  deixarDeIgnorar: "Stop ignoring",
  copiarId: "Copy user ID",
  idCopiado: "ID copied.",
  conexoes: "Connections",
  membroDesde: "Member since",
  sobre: "About",
  cargosTitulo: "Roles",
  visaoGeral: "Overview",
  amigosEmComum: "Mutual friends ({{quantidade}})",
  servidoresEmComum: "Mutual servers ({{quantidade}})",
  amizade: {
    amigo: "Friend",
    pedidoEnviado: "Friend request sent",
    respondaAbaixo: "Sent you a request — answer below",
    adicionar: "Add friend",
    teMandouPedido: "Sent you a friend request",
    aceitar: "Accept",
    desfazer: "Remove friend",
    desfazerTitulo: "Remove {{nome}} from your friends?",
    desfazerDescricao: "You stop being friends. The private conversation stays in your history, and you can add them again later.",
    bloquear: "Block",
    bloquearTitulo: "Block {{nome}}?",
    bloquearDescricao: "You stop being friends, the private conversation stops accepting messages, and they can no longer send you a friend request.",
    linkCopiado: "You aren't friends — the link was copied for you to send.",
  },
  recado: {
    escrever: "Message @{{usuario}}",
    enviar: "Send",
    enviada: "Message sent",
    falhou: "Couldn't send it. Try from the conversation.",
  },
  cartao: {
    trocarFaixa: "Change the card banner",
    trocarFaixaCurto: "Change the banner",
    trocarFoto: "Change the profile picture",
    trocarFotoCurto: "Change the picture",
    suaEtiqueta: "Your tag",
    editarEtiqueta: "Click to edit your tag",
    conteAlgo: "Tell us something about yourself",
    adicionarStatus: "Add a status",
    adicionarDescricao: "Click to add a description",
    cargo: "Role",
    cargos: "Roles",
    cargosCom: "Roles — {{quantidade}}",
    tirarCargo: "Remove the {{cargo}} role",
  },
  cargos: {
    adicionar: "Add role",
    procurar: "Search for a role",
  },
  etiqueta: {
    escolher: "Choose the server tag",
    nenhuma: "No server tag",
    semEtiqueta: "None of your servers has a tag",
  },
  emblemas: {
    doServidor: "Badges from this server",
    limite: "You can wear up to {{quantidade}} badges.",
  },
  nota: {
    vazia: "Click to jot something down",
    rotulo: "Note (only you see it)",
    adicionar: "Add note (only you can see it)",
  },
  status: {
    titulo: "Status",
    definir: "Set your status",
    escolherEmoji: "Choose emoji",
    tirarEmoji: "Remove the emoji",
    oQuePensa: "What's on your mind?",
    limparAgora: "Clear status now",
    naoLimpar: "Don't clear",
    limpar30m: "Clear in 30 minutes",
    limpar1h: "Clear in 1 hour",
    limpar4h: "Clear in 4 hours",
    limparHoje: "Clear today",
    limparAmanha: "Clear tomorrow",
    comHora: "{{prazo}} at {{hora}}",
  },
  presenca: {
    disponivel: "Available",
    ausente: "Idle",
    naoPerturbar: "Do not disturb",
    naoPerturbarDetalhe: "You get no alert for new messages",
    invisivel: "Invisible",
    invisivelDetalhe: "You appear offline to others",
  },
  menu: {
    mudarDeConta: "Switch account",
    gerenciarContas: "Manage accounts",
  },
  editor: {
    decoracao: "Change the avatar decoration",
    naoSalvo: "Don't forget to save your changes!",
    principal: "Main profile",
  },
};
