export const servidor = {
  trilho: {
    transmitindo: "Someone is streaming",
    emChamada: "{{count}} in a call",
  },
  titulo: "Server settings",
  auditoria: {
    todasAsAcoes: "All actions",
    todosOsUsuarios: "All users",
    filtroMembros: "Members",
    filtroCanais: "Channels",
    filtroEmojis: "Emojis",
    filtroServidor: "Server",
    titulo: "Audit log",
    porUsuario: "Filter by user",
    porAcao: "Filter by action",
    vazio: "Nothing logged yet with this filter.",
    motivo: "Reason:",
  },
  banimentos: {
    titulo: "Server ban list",
    descricao: "People here can't get back in, not even with a new invite. Unbanning restores access right away.",
    procurar: "Search bans by username",
    vazioTitulo: "No bans",
    vazio: "You haven't banned anyone yet… but if and when you need to, don't hesitate.",
    desbanir: "Unban",
  },
  excluir: {
    tudoVai: "Every channel, message and invite in {{servidor}} will be deleted for all {{membros}} members. Nobody can get them back afterwards.",
    digite: "Type {{servidor}} to confirm",
    titulo: "Delete server",
    aviso: "This can't be undone.",
  },
  emblemas: {
    apagarDescricao: "It comes off whoever is wearing it. This can't be undone.",
    titulo: "Badges",
    vazio: "No badges yet.",
    novo: "New badge",
  },
  convites: {
    revogarTitulo: "Revoke invite?",
    revogarAcao: "Revoke",
    revogarDescricao: "The link {{codigo}} stops working right away. Whoever already joined through it stays on the server.",
    titulo: "Invites",
    descricao: "Every active invite link for this server.",
    vazio: "No invites created yet.",
    revogar: "Revoke invite",
  },
  integracoes: {
    opcionais: "username and avatar_url are optional and apply per message. The limit is 5 messages every 5 seconds.",
    apagarDescricao: "The URL stops working right away. The messages it already sent stay in the channel.",
    titulo: "Integrations",
    descricao: "A webhook is an address that posts to a channel without needing an account. Handy for announcing when a build passes, when someone opens a ticket, or whatever you want to send from a script.",
    novo: "New webhook",
    vazio: "No webhooks yet. Create one and paste the URL wherever you want the message to come from.",
    canal: "Channel",
    apagar: "Delete webhook",
    comoUsar: "How to use",
    comoUsarTexto: "Send a POST with JSON:",
  },
  explorar: {
    titulo: "Discovery",
  },
  engajamento: {
    semCanal: "No system channel",
    titulo: "Engagement",
    descricao: "What the server does on its own so it doesn't feel empty when someone new arrives.",
    sistema: "System messages",
    boasVindas: "Send a welcome message when someone joins",
    sorteio: "With no text of your own below, the line is picked at random — always the same one gets old fast.",
    canalDoSistema: "System message channel",
    mensagem: "Welcome message",
    deixeVazio: "Leave empty to pick from the ready-made lines",
  },
  automod: {
    titulo: "AutoMod",
    descricao: "Filters that moderate on their own, before the message even exists. Server admins are never filtered — and exempt roles pass straight through.",
    palavras: {
      titulo: "Block custom words",
      descricao: "Your list of words nobody may write.",
    },
    mencoes: {
      titulo: "Block mention spam",
      descricao: "Blocks a message with too many mentions at once.",
    },
    links: {
      titulo: "Block links",
      descricao: "Catches any address pasted in chat.",
    },
    definir: "Set up",
    nomeDaRegra: "Rule name",
    bloqueadas: "Blocked words",
    digiteEnter: "Type and press Enter",
    comparacao: "Matching ignores case, accents and punctuation — and doesn't catch a word inside another (\"ass\" doesn't block \"assess\").",
    aPartirDe: "Block from how many mentions",
    oQueFazer: "What to do",
    canalDoAlerta: "Alert channel",
    escolhaCanal: "Pick a channel",
    castigo: "Timeout (minutes)",
    isentos: "Exempt roles",
    semCargos: "No roles created yet.",
    salvarRegra: "Save rule",
    apagar: "Delete rule",
    excluirTitulo: "Delete this AutoMod rule?",
    excluirDescricao: "The server stops filtering by it right away. You can create it again, but the current setup is lost.",
    excluirAcao: "Delete rule",
  },
  cargos: {
    titulo: "Roles",
    descricao: "Roles give a name, a colour and powers. Whoever sits higher on the list outranks those below — and nobody touches a role equal to or above their own.",
    criar: "Create role",
    vazio: "No roles yet.",
    abaExibicao: "Display",
    abaPermissoes: "Permissions",
    abaMembros: "Members — {{quantos}}",
    everyone: "Applies to everyone on the server. It's the base the other roles add on top of.",
    nomeDoCargo: "Role name",
    cor: "Role colour",
    corDica: "Colours the name of whoever has the role in the member list and in chat.",
    semCor: "No colour",
    corPersonalizada: "Custom colour",
    estilo: "Name style",
    segundaCor: "Second colour",
    segundaCorDica: "Without it the gradient falls back to a solid colour — it doesn't disappear.",
    limparSegundaCor: "Clear second colour",
    icone: "Icon",
    iconeDica: "Shows next to the role on the profile card of whoever has it.",
    exibirSeparado: "Display separately from other members",
    exibirSeparadoDica: "The role gets its own section in the member list.",
    permitirMencionar: "Allow mentioning this role",
    permitirMencionarDica: "Anyone will be able to notify everyone who has the role.",
    semPoderDeConceder: "{{descricao}} (you don't have this permission to grant)",
    adicionar: "Add someone to this role",
    tirar: "Remove the role",
    semNinguem: "Nobody has this role yet.",
    apagar: "Delete role",
    excluirTitulo: "Delete the role \"{{nome}}\"?",
    excluirDescricao: "Whoever has this role loses everything it gave. This can't be undone.",
    excluirAcao: "Delete role",
  },
  membros: {
    procurar: "Search by name or username",
    membroDesde: "Member since",
    vazio: "Nobody found.",
    acoesPara: "Actions for {{nome}}",
    deCastigo: "in timeout",
    tirarCastigo: "End timeout",
    castigo5min: "5 minutes",
    castigo1h: "1 hour",
    castigo1d: "1 day",
    castigo1s: "1 week",
    expulsar: "Kick",
    expulsarTitulo: "Kick {{nome}}?",
    expulsarDescricao: "leaves {{servidor}} right away. They can come back with an invite — kicking doesn't stop the return.",
    banir: "Ban",
    banirTitulo: "Ban {{nome}}?",
    banirDescricao: "leaves {{servidor}} and can't come back, not even with an invite, until unbanned.",
    motivo: "Reason (optional)",
    motivoDica: "Recorded in the audit log",
  },
  perfil: {
    titulo: "Server profile",
    descricao: "This is how your server shows up in the list and in invite links.",
    icone: "Icon",
    faixa: "Top banner",
    nomeDoServidor: "Server name",
    campoDescricao: "Description",
    doQueE: "What is this server about?",
    comprimido: "Compressed before upload: {{economia}}",
  },
  etiqueta: {
    titulo: "Server tag",
    descricao: "A tag of up to 4 letters that shows next to the name of anyone who's a member — in chat and in the people list. Here it's free: no boosts, no levels.",
    escolhaNome: "Pick a name",
    limite: "4 characters max, letters and numbers.",
    escolhaInsignia: "Pick a badge",
    voce: "You",
    fala1: "anyone up for a game?",
    fala2: "take a look at my tag!",
    fala3: "whoa, how'd you get that",
  },
  expressoes: {
    comoUsar: "Add up to {{limite}} emojis anyone can use on this server. Type :name: in chat to send one.",
    imagem: "Image",
    enviadoPor: "Uploaded by",
    semEmoji: "No emoji yet.",
    figurinhas: "Stickers",
    enviarFigurinha: "Upload sticker",
    nomeDaFigurinha: "Sticker name",
    exemploFigurinha: "E.g. kitten hug",
    figurinhaGrande: "The sticker is over {{limite}}.",
    deixaPraLa: "Never mind",
    sons: "Soundboard",
    enviarSom: "Upload sound",
    nomeDoSom: "Sound name",
    semSom: "No sounds yet.",
    somGrande: "The sound is over {{limite}}.",
    emojiRelacionado: "Related emoji",
    ouvir: "Play",
    ouvirAssim: "Play it like this",
    volumeDe: "Volume of {{nome}}",
    volumeDica: "Applies to everyone on the server. Each person can still turn the sounds down just for themselves, in the call panel.",
    falhaEnvio: "Couldn't upload the file.",
    excluirTitulo: "Delete {{tipo}} \"{{nome}}\"?",
    excluirDescricao: "It disappears from the server for everyone. Messages that already used it stay as they are.",
  },
  canal: {
    visaoGeral: "Overview",
    nome: "Channel name",
    topico: "Channel topic",
    topicoDica: "What is talked about here?",
    modoLento: "Each person only sends one message per interval. Anyone who manages messages or channels goes straight through.",
    visibilidade: "Content visibility",
    padrao: "Default",
    padraoDica: "The channel's content is always visible.",
    spoiler: "Spoiler channel",
    spoilerDica: "Mark this channel as containing spoilers, so plot twists and heavy topics stay hidden until someone chooses to look.",
    idade: "Age-restricted channel",
    idadeDica: "Whoever enters has to confirm they're of age to see the content.",
    bitrateDica: "Going over 64 kbps can hurt people with a poor connection.",
    qualidadeDeVideo: "Video quality",
    automatica: "Automatic",
    limite: "User limit — {{valor}}",
    pessoas: "{{quantos}} people",
    semLimite: "no limit",
    permissoesDescricao: "Here you change what applies in this channel. Whatever stays on “inherit” keeps following the role.",
    excluir: {
      titulo: "Delete channel",
      historico: "The whole history of {{canal}} goes with it, for everyone.",
      digite: "Type {{canal}} to confirm",
    },
  },
  moderacao: {
    titulo: "Moderator view",
    semPermissao: "You need the “Moderate members” permission to see this.",
    fecharEsc: "Close (Esc)",
    atividade: "Activity on the server",
    mensagens: "Messages",
    links: "Links",
    midia: "Media",
    acoesNaAuditoria: "Audit log actions",
    moderacoesSofridas: "Moderation received",
    permissoes: "Permissions ({{quantas}})",
    semPermissaoEspecial: "No special permissions.",
    conta: "Account",
    entrouNoServidor: "Joined the server",
    contaCriadaEm: "Account created on",
    deCastigoAte: "In timeout until",
    formaDeAdesao: "How they joined",
    mensagem: "Message",
    castigo: "Timeout",
    copiarId: "Copy ID",
    idCopiado: "ID copied.",
    adicionarCargo: "Add role",
    semCargos: "No roles created",
    soEveryone: "Only @everyone.",
    voltar: "Back",
    vazio: "Nothing here.",
    cinquenta: "Showing the 50 most recent.",
    irParaMensagem: "Go to message",
    precisaSerAmigo: "You two have to be friends to talk.",
    expulsarDescricao: "Leaves the server right away, but can come back with an invite.",
    banirDescricao: "Leaves the server and can't come back, not even with an invite, until unbanned.",
    castigarTitulo: "Time out {{nome}}?",
    castigoDescricao: "While it lasts, they can't write or speak in any channel on the server.",
    aplicarCastigo: "Apply timeout",
    duracao: "Duration in minutes",
    informeDuracao: "Enter the duration in minutes.",
  },
  abas: {
    expressoes: "Expressions",
    pessoas: "People",
    apps: "Apps",
    moderacao: "Moderation",
    banimentos: "Bans",
  },
};
