export const amizades = {
  ativosAgora: "अभी सक्रिय",
  procurando: "देख रहे हैं कौन है…",
  tudoTranquilo: "अभी सब शांत है…",
  tudoTranquiloDetalhe: "जब आप या कोई दोस्त कॉल में आएंगे, वह यहाँ दिखेगी — और आप एक क्लिक में जुड़ सकते हैं।",
  emVoz: "वॉइस में",
  voce: "आप",
  soVoce: "सिर्फ आप",
  pessoas: "{{quantas}} लोग",
  voltarParaChamada: "कॉल पर लौटें",
  entrarNaChamada: "कॉल में शामिल हों",
  abrirCanal: "{{servidor}} में {{canal}} खोलें",
  mensagensDiretas: "सीधे संदेश",
  encontreConversa: "बातचीत खोजें",
  amigos: "दोस्त",
  conversas: "बातचीत",
  semConversas: "अभी कोई बातचीत नहीं। शुरू करने के लिए एक दोस्त जोड़ें।",
  semConversaComEsseNome: "उस नाम की कोई बातचीत नहीं।",
  abrirMenu: "सर्वर और बातचीत खोलें",
  solicitacoes: "संदेश अनुरोध",
  pedidos: "अनुरोध",
  spam: "स्पैम",
  pedidosPendentes: "लंबित अनुरोध",
  marcadosComoSpam: "स्पैम के रूप में चिह्नित",
  aceitar: "स्वीकारें",
  ignorar: "अनदेखा करें",
  marcarSpam: "स्पैम चिह्नित करें",
  semPedidos: "कोई अनुरोध लंबित नहीं।",
  semPedidosDetalhe: "जो आपका दोस्त नहीं है पर आपके साथ एक सर्वर साझा करता है, वह आपकी बातचीत तक पहुँचने से पहले यहाँ आता है।",
  semSpam: "कुछ भी स्पैम चिह्नित नहीं।",
  semSpamDetalhe: "स्पैम फ़िल्टर जो अलग करे, या आप जो चिह्नित करें, वह इस टैब में रहता है।",
  umServidorEmComum: "1 साझा सर्वर",
  servidoresEmComum: "{{quantos}} साझा सर्वर",
  semServidoresEmComum: "कोई साझा सर्वर नहीं",
};
