export const chamada = {
  conectando: "कॉल से जुड़ रहे हैं…",
  naoEntrou: "कॉल में शामिल नहीं हो सके",
  sair: "कॉल छोड़ें",
  sairDaVoz: "वॉइस कॉल छोड़ें",
  desconectar: "डिस्कनेक्ट करें",
  voltar: "कॉल पर लौटें",
  voltarAosQuadros: "कॉल के टाइल पर लौटें",
  fecharChat: "चैट बंद करें",
  mostrarChat: "चैट दिखाएँ",
  convidar: "कॉल में आमंत्रित करें",
  carregandoPrevia: "झलक लोड हो रही है…",
  maisOpcoes: "और विकल्प",
  deVideo: "वीडियो कॉल",
  deVoz: "वॉइस कॉल",
  alguem: "कोई",
  volume: {
    entrada: "इनपुट वॉल्यूम",
    saida: "आउटपुट वॉल्यूम",
    live: "लाइव का वॉल्यूम",
    liveComPorcento: "लाइव का वॉल्यूम ({{porcento}}%)",
    liveSemSom: "लाइव म्यूट",
  },
  aparelhos: {
    entrada: "इनपुट डिवाइस",
    saida: "आउटपुट डिवाइस",
    camera: "कैमरा",
    microfone: "माइक्रोफ़ोन",
    saidaCurto: "आउटपुट",
    oDoSistema: "सिस्टम वाला",
    aDoSistema: "सिस्टम वाला",
    semEscolhaDeSaida: "यह ब्राउज़र आउटपुट चुनने नहीं देता — सिस्टम तय करता है।",
    espelhar: "मेरा कैमरा मिरर करें",
    configEntrada: "इनपुट सेटिंग",
    configSaida: "आउटपुट सेटिंग",
    configCamera: "कैमरा सेटिंग",
    configAudioEVideo: "ऑडियो और वीडियो सेटिंग",
  },
  tela: {
    compartilhar: "स्क्रीन साझा करें",
    compartilharAcao: "साझा करें",
    cancelar: "रद्द करें",
    telas: "स्क्रीन",
    janelas: "विंडो",
    somDoComputador: "कंप्यूटर की आवाज़ भी ले जाएँ",
    somDoSistema: "सिस्टम की आवाज़ भी ले जाएँ",
    configCompartilhamento: "साझाकरण सेटिंग",
    mostrarSemVideo: "बिना वीडियो वालों को दिखाएँ",
    semFontes: "सिस्टम ने साझा करने के लिए कोई स्क्रीन या विंडो नहीं लौटाई।",
    pararDeCompartilhar: "साझा करना बंद करें",
    encerrarTransmissao: "प्रसारण समाप्त करें",
  },
  live: {
    etiqueta: "लाइव",
    etiquetaMaiuscula: "लाइव",
    assistir: "प्रसारण देखें",
    assistirPessoa: "{{nome}} को देखें",
    pararDeAssistir: "देखना बंद करें",
  },
  membro: {
    mudarMeuApelido: "मेरा उपनाम बदलें",
    meuMicrofone: "मेरा माइक्रोफ़ोन",
    ouvirChamada: "कॉल सुनें",
    copiarMeuId: "मेरी ID कॉपी करें",
    idCopiado: "ID कॉपी हो गई।",
    mensagem: "संदेश",
    silenciar: "म्यूट करें",
    alterarApelido: "उपनाम बदलें",
    cargos: "भूमिकाएँ",
    semCargo: "कोई भूमिका नहीं बनाई गई",
    moverPara: "यहाँ ले जाएँ",
    silenciarNoServidor: "सर्वर पर आवाज़ म्यूट करें",
    desativarAudioNoServidor: "सर्वर पर ऑडियो बंद करें",
    desconectar: "डिस्कनेक्ट करें",
    apelidoTitulo: "इस सर्वर पर आपका उपनाम",
    apelidoDeAlguem: "{{nome}} का उपनाम",
    apelidoCampo: "उपनाम",
    apelidoDicaPropria: "सिर्फ़ यहीं लागू। खाली छोड़ने पर आपका सामान्य नाम लौट आएगा।",
    apelidoDicaDeOutro: "सिर्फ़ इसी सर्वर पर लागू। मूल नाम पर लौटने के लिए खाली छोड़ें।",
  },
  detalhes: {
    abrir: "वॉइस विवरण",
    titulo: "वॉइस विवरण",
    conexao: "कनेक्शन",
    pingMedio: "औसत पिंग",
    ultimoPing: "आख़िरी पिंग",
    perda: "भेजे गए पैकेट का नुकसान",
    medindo: "माप रहे हैं…",
    criptografado: "सर्वर तक एन्क्रिप्टेड (DTLS-SRTP)",
    explicacao: "250 ms से ऊपर बातचीत में देरी महसूस होने लगती है — लोग एक-दूसरे की बात काटने लगते हैं। 10% से ऊपर पैकेट लॉस आवाज़ को रोबोट जैसा बना देता है। दोनों ही मामलों में समस्या लगभग हमेशा आपके और इंटरनेट के बीच होती है: Wi-Fi की जगह केबल आज़माएँ, या राउटर दोबारा चालू करें।",
  },
  microfone: {
    bloqueado: "माइक्रोफ़ोन ब्लॉक है — आप सिर्फ़ सुन रहे हैं। ब्राउज़र की अनुमतियों में एक्सेस दें।",
    bloqueadoNoMac: "macOS माइक्रोफ़ोन रोक रहा है। इसे चुनें:",
    caminhoNoMac: "सिस्टम सेटिंग → गोपनीयता और सुरक्षा → माइक्रोफ़ोन",
    abrirAjustes: "सेटिंग खोलें",
    vaiReabrir: "macOS ऐप दोबारा खोलने को कहेगा।",
    naoAbriu: "माइक्रोफ़ोन नहीं खुल सका — आप सिर्फ़ सुन रहे हैं। सेटिंग → वॉइस और वीडियो में डिवाइस जाँचें।",
  },
  gravacaoDeTela: {
    bloqueada: "macOS ने अभी स्क्रीन रिकॉर्डिंग की अनुमति नहीं दी है। उसके बिना साझा की गई स्क्रीन काली आती है।",
    marque: "इसे चुनें:",
    reabra: "स्क्रीन रिकॉर्डिंग में चालू करें और ऐप दोबारा खोलें।",
    jaMarcado: "अगर पहले से चुना हुआ है, तो पिछली अपडेट में अनुमति पुरानी पड़ गई: उसे हटाएँ, फिर से चुनें और ऐप दोबारा खोलें।",
  },
  ruido: {
    titulo: "शोर दमन",
    explicacao: "अपनी आवाज़ से पीछे का शोर हटाएँ। बोलते हुए ताली बजाकर या कीबोर्ड सरकाकर देखें — कॉल में मौजूद लोग सिर्फ़ आपको सुनेंगे।",
    semSuporte: "यह ब्राउज़र उन्नत दमन नहीं चला सकता। ब्राउज़र का अपना दमन फिर भी लागू रहता है, जो कमज़ोर है।",
    aplicando: "कॉल पर लागू हो रहा है…",
    faleParaTestar: "जाँचने के लिए बोलिए",
    verdeQuandoPassa: "आपकी आवाज़ जाने पर हरा हो जाता है।",
    teOuvindo: "अभी वे आपको सुन रहे हैं।",
    feitoCom: "किससे बना:",
    aquiNoAparelho: ", यहीं आपके डिवाइस पर",
    ajustes: "सेटिंग",
  },
  permissoes: {
    titulo: "macOS की अनुमतियाँ",
    detalhe: "macOS एक ही बार पूछता है, और उसके बाद यह सिर्फ़ उसी के पैनल में बदलता है। यहाँ देख सकते हैं क्या लागू है और जो कमी है उसे ठीक कर सकते हैं।",
    concedida: "दी गई",
    negada: "अस्वीकृत",
    naoPedida: "नहीं माँगी गई",
    permitir: "अनुमति दें",
    abrirAjustes: "सेटिंग खोलें",
    microfone: "माइक्रोफ़ोन",
    microfoneDetalhe: "कॉल में बोलना और अपना इनपुट जाँचना।",
    camera: "कैमरा",
    cameraDetalhe: "कॉल में वीडियो चालू करना।",
    tela: "स्क्रीन रिकॉर्डिंग",
    telaDetalhe: "स्क्रीन और विंडो साझा करना।",
    monitoramento: "इनपुट मॉनिटरिंग",
    monitoramentoDetalhe: "Gravaê के बैकग्राउंड में रहने पर भी पुश-टू-टॉक इस्तेमाल करना।",
  },
  jaConectado: {
    titulo: "आप पहले से इस कॉल में हैं",
    trazer: "कॉल यहाँ ले आएँ",
    deixar: "जैसा है वैसा रहने दें",
    detalhe: "यहाँ लाने पर दूसरा छोर कॉल से बाहर हो जाता है — आपका खाता एक बार में एक ही जगह रहता है।",
  },
};
