export const comum = {
  carregando: "लोड हो रहा है…",
  salvar: "सहेजें",
  salvando: "सहेजा जा रहा है…",
  descartar: "छोड़ें",
  redefinir: "रीसेट करें",
  naoSalvo: "आपके पास बिना सहेजे बदलाव हैं।",
  fechar: "बंद करें",
  criar: "बनाएँ",
  nome: "नाम",
  emoji: "इमोजी",
  previa: "झलक",
  cancelar: "रद्द करें",
  enviar: "भेजें",
  apagar: "मिटाएँ",
  excluir: "मिटाएँ",
  remover: "हटाएँ",
  trocar: "बदलें",
};
