export const configuracoes = {
  efeitos: {
    titulo: "पॉइंटर के असर",
    detalhe: "ऐप के ऊपर बनने वाली लकीर और चिंगारी। शुरू में बंद रहती हैं, और कम एनिमेशन माँगा हो तो खुद बंद हो जाती हैं।",
    rastro: "कर्सर की लकीर",
    rastroDetalhe: "एक लकीर जो पॉइंटर के पीछे चलती है और धीरे-धीरे मिट जाती है।",
    faisca: "क्लिक पर चिंगारी",
    faiscaDetalhe: "छोटी लकीरें जो क्लिक की जगह से निकलती हैं।",
    cor: "रंग",
    espessura: "मोटाई",
    comprimento: "लंबाई",
    tamanho: "आकार",
    quantidade: "संख्या",
  },
  email: {
    verificarTitulo: "अपना ईमेल पक्का करें",
    verificarDetalhe: "कुछ समुदाय सिर्फ़ पुष्टि किए लोगों को बोलने देते हैं। एक क्लिक की बात है।",
    enviar: "लिंक भेजें",
    enviado: "इनबॉक्स देखिए। लिंक एक दिन चलता है।",
    falhou: "ईमेल नहीं भेजा जा सका।",
    confirmado: "ईमेल पक्का हो गया",
    confirmadoDetalhe: "हो गया। अब हर उस समुदाय में लिख सकते हैं जो यह माँगता है।",
    linkIncompleto: "अधूरा लिंक",
    linkIncompletoDetalhe: "पते में कोड नहीं है। लिंक सीधे ईमेल से खोलिए।",
    confirmando: "पक्का किया जा रहा है…",
    expirou: "यह लिंक पहले ही इस्तेमाल हो चुका या इसकी मियाद बीत गई।",
    irParaOApp: "ऐप पर जाएँ",
  },
  tema: {
    indisponivel: "थीम उपलब्ध नहीं",
    indisponivelDetalhe: "जिसने इसे प्रकाशित किया था उसने मिटा दिया, या लिंक गलत है।",
    indisponivelLinha: "थीम उपलब्ध नहीं। जिसने इसे प्रकाशित किया था उसने मिटा दिया, या लिंक गलत है।",
    importar: "थीम आयात करें",
    importarCurto: "आयात करें",
    importarDetalhe: "यह आपकी मौजूदा थीम की जगह ले लेगा। बाद में सेटिंग्स > दिखावट > थीम स्टूडियो में बदल सकते हैं।",
    porAutor: "{{autor}} की ओर से",
    umaCorTrocada: "1 रंग बदला",
    coresTrocadas: "{{quantas}} रंग बदले",
    avisoDeCss: "यह थीम लिखने वाले का CSS साथ लाती है, और CSS स्क्रीन के हर कोने तक पहुँचता है। सिर्फ़ भरोसेमंद लोगों से ही आयात करें।",
    soCores: "यह थीम सिर्फ़ रंग बदलती है। बाहर का कोई CSS नहीं।",
    aplicar: "लागू करें",
    previaSemMotor: "झलक इंजन नहीं चलाती। देखने के लिए इंस्टॉल करें।",
    motorAnimado: "{{motor}} एनिमेटेड",
  },
  sair: "साइन आउट",
  versoes: {
    termos: "सेवा की शर्तें",
    privacidade: "गोपनीयता नीति",
    copiar: "कॉपी करने के लिए क्लिक करें",
    copiado: "कॉपी हो गया",
  },
  telas: {
    conta: "मेरा खाता",
    privacidade: "गोपनीयता",
    conexoes: "कनेक्शन",
    voz: "ऑडियो",
    video: "वीडियो",
    avisos: "सूचनाएँ",
    aplicativos: "एप्लिकेशन",
    aparencia: "रूप",
    batePapo: "चैट",
    acessibilidade: "सुगम्यता",
    idioma: "भाषा",
    aplicativo: "ऐप डाउनलोड करें",
    atalhos: "शॉर्टकट",
    desktop: "डेस्कटॉप ऐप",
    avancado: "उन्नत",
    servidor: "सर्वर",
    comunicado: "सिस्टम घोषणा",
    denuncias: "शिकायतें",
    publicacoes: "डिप्लॉयमेंट",
  },
  grupos: {
    conta: "खाता",
    app: "ऐप सेटिंग्स",
    desenvolvedor: "डेवलपर",
    administracao: "प्रशासन",
  },
  secoes: {
    detalhesDeLogin: "लॉगिन विवरण",
    dispositivos: "डिवाइस",
    usuariosBloqueados: "अवरुद्ध उपयोगकर्ता",
    aplicativosAutorizados: "अधिकृत ऐप्स",
    sessoes: "सत्र",
    amigosEDms: "मित्र और सीधे संदेश",
    compartilhamentoDeAtividade: "गतिविधि साझा करना",
    visibilidadeDoPerfil: "प्रोफ़ाइल दृश्यता",
    exportarDados: "डेटा निर्यात करें",
    exclusaoDeDados: "डेटा हटाएँ",
    tema: "थीम",
    corDeDestaque: "एक्सेंट रंग",
    interface: "इंटरफ़ेस",
    listaDeCanais: "चैनल सूची",
    zoomDoApp: "ऐप ज़ूम स्तर",
    escalaDaFonte: "चैट फ़ॉन्ट आकार",
    modoStreamer: "स्ट्रीमिंग गोपनीयता",
    cursores: "कर्सर",
    movimento: "गति",
    textoEmVoz: "टेक्स्ट से वाणी",
    teclado: "कीबोर्ड",
    formatoDaHora: "समय प्रारूप",
    idiomaDaInterface: "इंटरफ़ेस की भाषा",
    dispositivosDeVoz: "डिवाइस",
    testeDoMicrofone: "माइक्रोफ़ोन परीक्षण",
    modoDeEntrada: "इनपुट मोड",
    sensibilidade: "इनपुट संवेदनशीलता",
    qualidade: "गुणवत्ता",
    camera: "कैमरा",
    transmissao: "प्रसारण",
    exibicao: "प्रदर्शन",
    entrada: "इनपुट",
    midia: "मीडिया",
    geral: "सामान्य",
    preferenciaDeMencao: "उल्लेख वरीयता",
    sons: "ध्वनियाँ",
  },
};
