export const configuracoes = {
  telas: {
    conta: "मेरा खाता",
    privacidade: "गोपनीयता",
    conexoes: "कनेक्शन",
    voz: "ऑडियो",
    video: "वीडियो",
    avisos: "सूचनाएँ",
    aplicativos: "एप्लिकेशन",
    aparencia: "रूप",
    batePapo: "चैट",
    acessibilidade: "सुगम्यता",
    idioma: "भाषा",
    aplicativo: "ऐप डाउनलोड करें",
    servidor: "सर्वर",
  },
  grupos: {
    conta: "खाता",
    app: "ऐप सेटिंग्स",
    desenvolvedor: "डेवलपर",
    administracao: "प्रशासन",
  },
  secoes: {
    detalhesDeLogin: "लॉगिन विवरण",
    dispositivos: "डिवाइस",
    usuariosBloqueados: "अवरुद्ध उपयोगकर्ता",
    aplicativosAutorizados: "अधिकृत ऐप्स",
    sessoes: "सत्र",
    amigosEDms: "मित्र और सीधे संदेश",
    compartilhamentoDeAtividade: "गतिविधि साझा करना",
    visibilidadeDoPerfil: "प्रोफ़ाइल दृश्यता",
    exportarDados: "डेटा निर्यात करें",
    exclusaoDeDados: "डेटा हटाएँ",
    tema: "थीम",
    corDeDestaque: "एक्सेंट रंग",
    interface: "इंटरफ़ेस",
    listaDeCanais: "चैनल सूची",
    zoomDoApp: "ऐप ज़ूम स्तर",
    escalaDaFonte: "चैट फ़ॉन्ट आकार",
    modoStreamer: "स्ट्रीमिंग गोपनीयता",
    movimento: "गति",
    textoEmVoz: "टेक्स्ट से वाणी",
    teclado: "कीबोर्ड",
    formatoDaHora: "समय प्रारूप",
    idiomaDaInterface: "इंटरफ़ेस की भाषा",
    dispositivosDeVoz: "डिवाइस",
    testeDoMicrofone: "माइक्रोफ़ोन परीक्षण",
    modoDeEntrada: "इनपुट मोड",
    sensibilidade: "इनपुट संवेदनशीलता",
    qualidade: "गुणवत्ता",
    camera: "कैमरा",
    transmissao: "प्रसारण",
    exibicao: "प्रदर्शन",
    entrada: "इनपुट",
    midia: "मीडिया",
    geral: "सामान्य",
    preferenciaDeMencao: "उल्लेख वरीयता",
    sons: "ध्वनियाँ",
  },
};
