export const configuracoes = {
  efeitos: {
    titulo: "पॉइंटर के असर",
    detalhe: "ऐप के ऊपर बनने वाली लकीर और चिंगारी। शुरू में बंद रहती हैं, और कम एनिमेशन माँगा हो तो खुद बंद हो जाती हैं।",
    rastro: "कर्सर की लकीर",
    rastroDetalhe: "एक लकीर जो पॉइंटर के पीछे चलती है और धीरे-धीरे मिट जाती है।",
    faisca: "क्लिक पर चिंगारी",
    faiscaDetalhe: "छोटी लकीरें जो क्लिक की जगह से निकलती हैं।",
    cor: "रंग",
    espessura: "मोटाई",
    comprimento: "लंबाई",
    tamanho: "आकार",
    quantidade: "संख्या",
  },
  email: {
    verificarTitulo: "अपना ईमेल पक्का करें",
    verificarDetalhe: "कुछ समुदाय सिर्फ़ पुष्टि किए लोगों को बोलने देते हैं। एक क्लिक की बात है।",
    enviar: "लिंक भेजें",
    enviado: "इनबॉक्स देखिए। लिंक एक दिन चलता है।",
    falhou: "ईमेल नहीं भेजा जा सका।",
    confirmado: "ईमेल पक्का हो गया",
    confirmadoDetalhe: "हो गया। अब हर उस समुदाय में लिख सकते हैं जो यह माँगता है।",
    linkIncompleto: "अधूरा लिंक",
    linkIncompletoDetalhe: "पते में कोड नहीं है। लिंक सीधे ईमेल से खोलिए।",
    confirmando: "पक्का किया जा रहा है…",
    expirou: "यह लिंक पहले ही इस्तेमाल हो चुका या इसकी मियाद बीत गई।",
    irParaOApp: "ऐप पर जाएँ",
  },
  tema: {
    indisponivel: "थीम उपलब्ध नहीं",
    indisponivelDetalhe: "जिसने इसे प्रकाशित किया था उसने मिटा दिया, या लिंक गलत है।",
    indisponivelLinha: "थीम उपलब्ध नहीं। जिसने इसे प्रकाशित किया था उसने मिटा दिया, या लिंक गलत है।",
    importar: "थीम आयात करें",
    importarCurto: "आयात करें",
    importarDetalhe: "यह आपकी मौजूदा थीम की जगह ले लेगा। बाद में सेटिंग्स > दिखावट > थीम स्टूडियो में बदल सकते हैं।",
    porAutor: "{{autor}} की ओर से",
    umaCorTrocada: "1 रंग बदला",
    coresTrocadas: "{{quantas}} रंग बदले",
    avisoDeCss: "यह थीम लिखने वाले का CSS साथ लाती है, और CSS स्क्रीन के हर कोने तक पहुँचता है। सिर्फ़ भरोसेमंद लोगों से ही आयात करें।",
    soCores: "यह थीम सिर्फ़ रंग बदलती है। बाहर का कोई CSS नहीं।",
    verCss: "CSS देखें",
    esconderCss: "CSS छिपाएँ",
    aplicar: "लागू करें",
    previaSemMotor: "झलक इंजन नहीं चलाती। देखने के लिए इंस्टॉल करें।",
    motorAnimado: "{{motor}} एनिमेटेड",
  },
  sair: "साइन आउट",
  versoes: {
    termos: "सेवा की शर्तें",
    privacidade: "गोपनीयता नीति",
    copiar: "कॉपी करने के लिए क्लिक करें",
    copiado: "कॉपी हो गया",
  },
  subscription: {
    seePlans: "प्लान देखें",
    upgradeSubtitle: "लिखने, फ़ाइल भेजने और स्ट्रीम करने के लिए ज़्यादा सीमाएँ और खास सुविधाएँ।",
    perMonth: "प्रति माह",
    perYear: "प्रति वर्ष",
    save: "{{percent}}% बचाएँ",
    howToPay: "आप कैसे भुगतान करना चाहते हैं?",
    legal: "भुगतान के 7 दिनों के भीतर आप रिफ़ंड माँग सकते हैं। भुगतान Stripe प्रोसेस करता है; हम आपका कार्ड नंबर कभी नहीं देखते।",
    compare: "मुफ़्त बनाम Infinity",
    featureColumn: "सुविधा",
    freeColumn: "मुफ़्त",
    messageRow: "संदेश की अक्षर सीमा",
    attachmentRow: "भेजी जाने वाली फ़ाइल का आकार",
    screenRow: "वीडियो गुणवत्ता",
    megabytesValue: "{{value}} MB",
    screenValue: "{{resolution}} · {{fps}} fps",
    alreadyPremium: "आपके पास {{date}} तक Infinity पहले से है।",
    upsell: "Infinity से सीमा बढ़ाएँ",
    screenUpsell: "Infinity से बेहतर गुणवत्ता",
    free: "आप मुफ़्त प्लान पर हैं।",
    activeUntil: "Infinity {{date}} तक सक्रिय है।",
    renews: "{{date}} को अपने आप रिन्यू होगा।",
    endsAt: "सदस्यता रद्द हो गई है और {{date}} को खत्म होगी।",
    pastDue: "पिछला भुगतान असफल रहा। Infinity बनाए रखने के लिए अपना कार्ड अपडेट करें।",
    waiting: "भुगतान की पुष्टि हो रही है…",
    subscribe: "सदस्यता लें",
    monthly: "मासिक",
    yearly: "वार्षिक",
    automatic: "कार्ड",
    manage: "भुगतान प्रबंधित करें",
    refund: "रिफ़ंड माँगें",
    refundDetail: "भुगतान के 7 दिनों के भीतर आप रद्द कर सकते हैं: {{amount}}, {{date}} तक।",
    refundConfirm: "रिफ़ंड माँगें?",
    refundConfirmDetail: "पैसा उसी भुगतान तरीके में लौटेगा और Infinity तुरंत खत्म हो जाएगा।",
    refunded: "रिफ़ंड का अनुरोध किया गया।",
    unavailable: "सदस्यता अभी उपलब्ध नहीं है।",
    success: "भुगतान मिल गया। धन्यवाद!",
    canceled: "भुगतान रद्द हुआ।",
    error: "कुछ गलत हो गया। फिर से कोशिश करें।",
    no: "नहीं",
    tagRow: "अपना यूज़र टैग",
    guildProfilesRow: "हर कम्युनिटी के लिए प्रोफ़ाइल",
    badgeRow: "प्रोफ़ाइल बैज",
    communitiesRow: "कम्युनिटी",
    savedRow: "सहेजे गए संदेश",
    animatedEmojiRow: "एनिमेटेड इमोजी",
    expressionsRow: "हर जगह से इमोजी और स्टिकर",
    animatedProfileRow: "एनिमेटेड अवतार और बैनर",
    earlyAccessRow: "नई सुविधाओं तक जल्दी पहुँच",
    themesRow: "अपनी थीम",
    pixOption: "Pix",
    pixHint: "बैंक ऐप खोलें, Pix चुनें और QR कोड स्कैन करें या कोड कॉपी-पेस्ट करें।",
    pixQrAlt: "Pix QR कोड",
    pixCopy: "Pix कोड कॉपी करें",
    pixCopied: "Pix कोड कॉपी हो गया",
    pixWaiting: "भुगतान का इंतज़ार",
    pixExpiresIn: "{{time}} में समाप्त",
    pixExpired: "यह Pix समाप्त हो गया। जारी रखने के लिए नया बनाएँ।",
    pixNew: "नया Pix बनाएँ",
    pixPaid: "Pix मिल गया! आपका Infinity सक्रिय है।",
    forMe: "अपने लिए",
    asGift: "उपहार के रूप में",
    buyGift: "उपहार खरीदें",
    giftReady: "उपहार तैयार है! लिंक कॉपी करें और जिसे चाहें भेजें।",
    giftClaimed: "उपहार भुनाया गया! Infinity आपके खाते में है।",
    gifts: "उपहार",
    giftsEmpty: "आपने अभी तक कोई उपहार नहीं खरीदा।",
    giftCode: "उपहार कोड",
    giftRedeem: "भुनाएँ",
    giftCopyLink: "लिंक कॉपी करें",
    giftLinkCopied: "लिंक कॉपी हुआ",
    giftClaimedBy: "{{name}} ने भुनाया",
    giftHint: "उपहार कोड है? यहाँ भुनाएँ। आपने जो उपहार खरीदे वे नीचे हैं।",
    cardPaid: "भुगतान स्वीकृत! आपका Infinity सक्रिय है।",
    payAmount: "{{amount}} भुगतान करें",
    giftLinkTitle: "आपको {{plan}} का उपहार मिला!",
    giftLinkDetail: "भुनाएँ दबाएँ और दिन आपके खाते में आ जाएँगे।",
    pageTitle: "{{plan}} के साथ फ़ायदों की दुनिया खोलें",
  },
  telas: {
    subscription: "Infinity",
    conta: "मेरा खाता",
    privacidade: "गोपनीयता",
    conexoes: "कनेक्शन",
    voz: "ऑडियो",
    video: "वीडियो",
    avisos: "सूचनाएँ",
    aplicativos: "एप्लिकेशन",
    aparencia: "रूप",
    batePapo: "चैट",
    acessibilidade: "सुगम्यता",
    idioma: "भाषा",
    aplicativo: "ऐप डाउनलोड करें",
    atalhos: "शॉर्टकट",
    desktop: "डेस्कटॉप ऐप",
    avancado: "उन्नत",
    servidor: "सर्वर",
    comunicado: "सिस्टम घोषणा",
    denuncias: "शिकायतें",
    publicacoes: "डिप्लॉयमेंट",
  },
  grupos: {
    conta: "खाता",
    app: "ऐप सेटिंग्स",
    desenvolvedor: "डेवलपर",
    administracao: "प्रशासन",
  },
  secoes: {
    detalhesDeLogin: "लॉगिन विवरण",
    dispositivos: "डिवाइस",
    usuariosBloqueados: "अवरुद्ध उपयोगकर्ता",
    aplicativosAutorizados: "अधिकृत ऐप्स",
    sessoes: "सत्र",
    amigosEDms: "मित्र और सीधे संदेश",
    compartilhamentoDeAtividade: "गतिविधि साझा करना",
    visibilidadeDoPerfil: "प्रोफ़ाइल दृश्यता",
    exportarDados: "डेटा निर्यात करें",
    exclusaoDeDados: "डेटा हटाएँ",
    tema: "थीम",
    corDeDestaque: "एक्सेंट रंग",
    interface: "इंटरफ़ेस",
    listaDeCanais: "चैनल सूची",
    zoomDoApp: "ऐप ज़ूम स्तर",
    escalaDaFonte: "चैट फ़ॉन्ट आकार",
    modoStreamer: "स्ट्रीमिंग गोपनीयता",
    cursores: "कर्सर",
    movimento: "गति",
    textoEmVoz: "टेक्स्ट से वाणी",
    teclado: "कीबोर्ड",
    formatoDaHora: "समय प्रारूप",
    idiomaDaInterface: "इंटरफ़ेस की भाषा",
    dispositivosDeVoz: "डिवाइस",
    testeDoMicrofone: "माइक्रोफ़ोन परीक्षण",
    modoDeEntrada: "इनपुट मोड",
    sensibilidade: "इनपुट संवेदनशीलता",
    qualidade: "गुणवत्ता",
    camera: "कैमरा",
    transmissao: "प्रसारण",
    exibicao: "प्रदर्शन",
    entrada: "इनपुट",
    midia: "मीडिया",
    geral: "सामान्य",
    preferenciaDeMencao: "उल्लेख वरीयता",
    sons: "ध्वनियाँ",
  },
};
