export const conversa = {
  lista: {
    carregando: "संदेश लोड हो रहे हैं…",
    carregandoMais: "लोड हो रहा है…",
    verMais: "और देखने के लिए ऊपर स्क्रॉल करें",
    semHistorico: "इतिहास उपलब्ध नहीं",
    semHistoricoDetalhe: "आपकी भूमिका को #{{canal}} का इतिहास पढ़ने की अनुमति नहीं है। आप यहाँ रहेंगे तब तक नए संदेश दिखते रहेंगे।",
    boasVindas: "#{{canal}} में आपका स्वागत है",
    boasVindasDetalhe: "यह #{{canal}} चैनल की शुरुआत है।",
  },
  data: {
    hoje: "आज",
    ontem: "कल",
    hojeAs: "आज {{hora}} बजे",
    ontemAs: "कल {{hora}} बजे",
  },
  digitando: {
    um: "{{nome}} लिख रहे हैं…",
    dois: "{{primeiro}} और {{segundo}} लिख रहे हैं…",
    varios: "{{quantidade}} लोग लिख रहे हैं…",
  },
  mensagem: {
    usou: "ने इस्तेमाल किया",
    fixada: "पिन किया गया",
    editado: "(संपादित)",
    ignorada: "किसी ऐसे व्यक्ति का संदेश जिसे आप अनदेखा करते हैं।",
    mostrar: "दिखाएँ",
    escPara: "रद्द करने के लिए Esc —",
    cancelar: "रद्द करें",
    enterParaSalvar: "सहेजने के लिए Enter",
    falhou: "भेजा नहीं गया। फिर कोशिश करें",
    naoLidasDaqui: "यहाँ से अपठित।",
    linkCopiado: "लिंक कॉपी हो गया।",
    idCopiado: "ID कॉपी हो गई।",
    naoDeuParaCopiar: "आपके ब्राउज़र ने कॉपी करने नहीं दिया।",
    apagarTitulo: "संदेश मिटाएँ?",
    apagarDescricao: "यह चैनल के सभी लोगों से हट जाएगा। इसे वापस नहीं लाया जा सकता।",
    apagarAcao: "मिटाएँ",
    citacaoAnexo: "अटैचमेंट देखने के लिए क्लिक करें",
    citacaoSumiu: "मूल संदेश अब यहाँ नहीं है।",
    reagirCom: "{{emoji}} से प्रतिक्रिया दें — सुपर प्रतिक्रिया के लिए दबाए रखें",
    segureParaSuper: "{{emoji}} — सुपर प्रतिक्रिया के लिए दबाए रखें",
  },
  acoes: {
    reagir: "प्रतिक्रिया",
    responder: "जवाब दें",
    encaminhar: "आगे भेजें",
    favoritar: "संदेश सहेजें",
    tirarDosFavoritos: "सहेजे गए से हटाएँ",
    marcarNaoLida: "अपठित के रूप में चिह्नित करें",
    copiarLink: "संदेश का लिंक कॉपी करें",
    copiarId: "संदेश की ID कॉपी करें",
    fixar: "संदेश पिन करें",
    desafixar: "पिन हटाएँ",
    editar: "संपादित करें",
    apagar: "मिटाएँ",
    mais: "और",
    adicionarReacao: "प्रतिक्रिया जोड़ें",
    superReagirCom: "{{emoji}} से सुपर प्रतिक्रिया",
    fixarMensagem: "संदेश पिन करें",
    desafixarMensagem: "संदेश का पिन हटाएँ",
    editarMensagem: "संदेश संपादित करें",
    apagarMensagem: "संदेश मिटाएँ",
  },
  mencao: {
    cargo: "भूमिका का उल्लेख",
    pessoa: "उल्लेख",
    alguem: "कोई",
    cargoSemNome: "भूमिका",
    here: "जो ऑनलाइन हैं उन्हें सूचित करता है",
    everyone: "पूरे सर्वर को सूचित करता है",
  },
  codigo: {
    copiar: "कॉपी करें",
    copiado: "कॉपी हो गया",
    copiarAria: "कोड कॉपी करें",
    copiadoAria: "कोड कॉपी हो गया",
    recolher: "छोटा करें",
    expandir: "बड़ा करें",
    verInteiro: "पूरी फ़ाइल देखें",
    maisOpcoes: "और विकल्प",
    baixar: "डाउनलोड",
    recolherLinhas: "छोटा करें ({{linhas}} पंक्तियाँ)",
    expandirLinhas: "बड़ा करें ({{linhas}} पंक्तियाँ)",
    mudarIdioma: "भाषा बदलें",
    procurarIdioma: "भाषा कोड खोजें…",
    nenhumIdioma: "कोई भाषा नहीं मिली.",
    quebrarTexto: "टेक्स्ट लपेटें",
  },
  caixa: {
    escrever: "#{{canal}} में लिखें",
    escreverSemCanal: "संदेश लिखें",
    semPermissao: "इस चैनल में संदेश भेजने की आपको अनुमति नहीं है",
    solteParaAnexar: "जोड़ने के लिए छोड़ें",
    longaTitulo: "आपका संदेश बहुत लंबा है…",
    longaDescricao: "आप {{limite}} अक्षरों की सीमा पर पहुँच गए. इसे फ़ाइल के रूप में भेजें.",
    enviarComoArquivo: "फ़ाइल के रूप में भेजें",
    textoComoArquivo: "टेक्स्ट को फ़ाइल के रूप में भेजें",
    arquivoGrandeTitulo: "यह फ़ाइल बहुत बड़ी है",
    arquivoGrandeDescricao: "“{{arquivo}}” प्रति फ़ाइल {{limite}} MB की सीमा से अधिक है.",
    respondendoPara: "जवाब:",
    vaiNotificar: "उन्हें सूचना जाएगी",
    naoVaiNotificar: "उन्हें सूचना नहीं जाएगी",
    ligado: "चालू",
    desligado: "बंद",
    pararDeResponder: "जवाब देना रोकें",
    mais: "और",
    enviarArquivo: "फ़ाइल भेजें",
    criarEnquete: "पोल बनाएँ",
    expressoes: "इमोजी, GIF और स्टिकर",
    enviar: "भेजें",
    aguardandoEnvio: "अपलोड का इंतज़ार",
    modoLento: "धीमा मोड चालू ({{tempo}})",
    modoLentoDica: "धीमा मोड {{segundos}} सेकंड पर सेट है। अगला संदेश भेजने से पहले रुकें।",
  },
  anexos: {
    enviando: "अपलोड हो रहा है…",
    modificar: "{{arquivo}} बदलें",
    remover: "{{arquivo}} हटाएँ",
    ver: "{{arquivo}} देखें",
    mostrarSpoiler: "स्पॉइलर दिखाएँ: {{arquivo}}",
    spoiler: "स्पॉइलर",
    spoilerTitulo: "स्पॉइलर",
    editarTitulo: "अटैचमेंट संपादित करें",
    nomeDoArquivo: "फ़ाइल का नाम",
    descricao: "वैकल्पिक पाठ का विवरण",
    descricaoDica: "स्क्रीन रीडर के लिए इस मीडिया का वर्णन करें",
    marcarSpoiler: "स्पॉइलर के रूप में चिह्नित करें",
    cancelar: "रद्द करें",
    salvar: "सहेजें",
  },
  cartao: {
    tocador: "प्लेयर",
    abrir: "{{destino}} खोलें",
    tocar: "{{titulo}} चलाएँ",
    video: "वीडियो",
    verImagem: "छवि देखें",
  },
  enquete: {
    titulo: "पोल",
    encerrada: "पोल बंद",
    variasRespostas: "पोल — कई जवाब",
    umVoto: "{{quantidade}} वोट",
    votos: "{{quantidade}} वोट",
    umVotoNoTotal: "कुल {{quantidade}} वोट",
    votosNoTotal: "कुल {{quantidade}} वोट",
    encerraEm: "{{quando}} को बंद होगा",
    encerrarAgora: "अभी बंद करें",
  },
  fixadas: {
    titulo: "पिन किए गए संदेश",
    vazio: "इस चैनल में अभी कोई पिन किया गया संदेश नहीं है।",
    desafixar: "पिन हटाएँ",
    anexo: "(अटैचमेंट)",
    enquete: "(पोल)",
    dicaRotulo: "सुझाव:",
    dica: "जिसके पास “संदेश प्रबंधित करें” अनुमति है, वह संदेश के मेन्यू से सीधे पिन कर सकता है।",
  },
  encaminhar: {
    titulo: "संदेश आगे भेजें",
    paraOnde: "कहाँ भेजें?",
    semTexto: "(बिना टेक्स्ट वाला संदेश)",
    nenhumLugar: "इस नाम की कोई जगह नहीं है।",
    canais: "चैनल",
    conversas: "सीधे संदेश",
  },
  expressoes: {
    gifs: "GIF",
    buscarGifs: "Klipy में खोजें",
    figurinha: "स्टिकर",
    buscarFigurinha: "सही स्टिकर ढूँढें",
    buscarEmoji: "सही इमोजी ढूँढें",
    buscarReacao: "सही प्रतिक्रिया ढूँढें",
    adicionarEmoji: "इमोजी जोड़ें",
    limparBusca: "खोज मिटाएँ",
  },
  busca: {
    fechar: "खोज बंद करें",
    procurando: "खोज रहे हैं…",
    resultado: "{{quantos}} परिणाम",
    resultados: "{{quantos}} परिणाम",
    nadaCom: "{{termo}} से जुड़ा यहाँ कुछ नहीं।",
    soOsQuePodeLer: "खोज सिर्फ़ उन चैनलों में देखती है जिन्हें आप पढ़ सकते हैं।",
  },
  entrada: {
    titulo: "इनबॉक्स",
    naoLidas: "अपठित",
    salvas: "सहेजी गई",
    mencoes: "उल्लेख",
    fimTitulo: "आप अंत तक पहुँच गए",
    fimDetalhe: "पढ़ने को कुछ नहीं बचा। नया संदेश आने पर वह यहाँ दिखेगा।",
    semSalvosTitulo: "कोई सहेजी चीज़ नहीं",
    semSalvosDetalhe: "Shift दबाए रखें और किसी संदेश के बुकमार्क पर क्लिक करें ताकि वह सहेजा जाए और बाद में पढ़ा जा सके।",
    tirarDosSalvos: "सहेजे गए से हटाएँ",
    semMencoesTitulo: "अभी कोई उल्लेख नहीं",
    semMencoesDetalhe: "आपके उल्लेख पिछले 7 दिनों के लिए यहाँ दिखते हैं।",
  },
  forum: {
    descricao: "हर विषय अलग बातचीत बन जाता है — उस सवाल के लिए अच्छा जो बातों के बीच खो नहीं सकता।",
    novoAssunto: "नया विषय",
    vazio: "अभी कोई विषय नहीं। पहला शुरू करें और बातचीत शुरू से व्यवस्थित रहेगी।",
    titulo: "शीर्षक",
    doQueSeTrata: "बात किस बारे में है?",
    primeiraMensagem: "पहला संदेश",
    conteDoCaso: "पूरी बात बताएँ",
  },
};
