export const perfil = {
  carregando: "लोड हो रहा है…",
  editar: "प्रोफ़ाइल संपादित करें",
  mensagem: "संदेश",
  abrirConversa: "बातचीत खोलें",
  verCompleto: "पूरी प्रोफ़ाइल देखें",
  convidarParaServidor: "सर्वर पर आमंत्रित करें",
  semServidores: "आपके पास कोई सर्वर नहीं है",
  conviteEnviado: "{{nome}} को आमंत्रण भेजा गया।",
  moderador: "मॉडरेटर दृश्य में खोलें",
  mais: "और",
  ignorar: "अनदेखा करें",
  deixarDeIgnorar: "अनदेखा करना बंद करें",
  copiarId: "उपयोगकर्ता ID कॉपी करें",
  idCopiado: "ID कॉपी हो गई।",
  conexoes: "कनेक्शन",
  membroDesde: "सदस्य बने",
  sobre: "परिचय",
  cargosTitulo: "भूमिकाएँ",
  visaoGeral: "अवलोकन",
  amigosEmComum: "साझा मित्र ({{quantidade}})",
  servidoresEmComum: "साझा सर्वर ({{quantidade}})",
  amizade: {
    amigo: "मित्र",
    pedidoEnviado: "मित्रता अनुरोध भेजा गया",
    respondaAbaixo: "आपको अनुरोध भेजा — नीचे जवाब दें",
    adicionar: "मित्र जोड़ें",
    teMandouPedido: "आपको मित्रता अनुरोध भेजा",
    aceitar: "स्वीकारें",
    desfazer: "मित्रता हटाएँ",
    desfazerTitulo: "{{nome}} को अपने मित्रों से हटाएँ?",
    desfazerDescricao: "आप दोनों अब मित्र नहीं रहेंगे। निजी बातचीत इतिहास में बनी रहती है, और बाद में आप उन्हें फिर जोड़ सकते हैं।",
    bloquear: "ब्लॉक करें",
    bloquearTitulo: "{{nome}} को ब्लॉक करें?",
    bloquearDescricao: "आप दोनों अब मित्र नहीं रहेंगे, निजी बातचीत संदेश लेना बंद कर देगी, और वे आपको मित्रता अनुरोध नहीं भेज पाएँगे।",
    linkCopiado: "आप मित्र नहीं हैं — लिंक कॉपी कर दिया गया है, आप खुद भेज दें।",
  },
  recado: {
    escrever: "@{{usuario}} को लिखें",
    enviar: "भेजें",
    enviada: "संदेश भेजा गया",
    falhou: "भेजा नहीं जा सका। बातचीत से आज़माएँ।",
  },
  cartao: {
    trocarFaixa: "कार्ड का बैनर बदलें",
    trocarFaixaCurto: "बैनर बदलें",
    trocarFoto: "प्रोफ़ाइल फ़ोटो बदलें",
    trocarFotoCurto: "फ़ोटो बदलें",
    suaEtiqueta: "आपका टैग",
    editarEtiqueta: "टैग संपादित करने के लिए क्लिक करें",
    conteAlgo: "अपने बारे में कुछ बताइए",
    adicionarStatus: "स्टेटस जोड़ें",
    adicionarDescricao: "विवरण जोड़ने के लिए क्लिक करें",
    cargo: "भूमिका",
    cargos: "भूमिकाएँ",
    cargosCom: "भूमिकाएँ — {{quantidade}}",
    tirarCargo: "{{cargo}} भूमिका हटाएँ",
  },
  cargos: {
    adicionar: "भूमिका जोड़ें",
    procurar: "भूमिका खोजें",
  },
  etiqueta: {
    escolher: "सर्वर टैग चुनें",
    nenhuma: "कोई सर्वर टैग नहीं",
    semEtiqueta: "आपके किसी भी सर्वर पर टैग नहीं है",
  },
  emblemas: {
    doServidor: "इस सर्वर के बैज",
    limite: "आप {{quantidade}} बैज तक पहन सकते हैं।",
  },
  nota: {
    vazia: "कुछ लिखने के लिए क्लिक करें",
    rotulo: "नोट (सिर्फ़ आप देखते हैं)",
    adicionar: "नोट जोड़ें (सिर्फ़ आपको दिखेगा)",
  },
  status: {
    titulo: "स्टेटस",
    definir: "अपना स्टेटस तय करें",
    escolherEmoji: "इमोजी चुनें",
    tirarEmoji: "इमोजी हटाएँ",
    oQuePensa: "आप क्या सोच रहे हैं?",
    limparAgora: "स्टेटस अभी हटाएँ",
    naoLimpar: "न हटाएँ",
    limpar30m: "30 मिनट में हटाएँ",
    limpar1h: "1 घंटे में हटाएँ",
    limpar4h: "4 घंटे में हटाएँ",
    limparHoje: "आज हटाएँ",
    limparAmanha: "कल हटाएँ",
    comHora: "{{prazo}} {{hora}} बजे",
  },
  presenca: {
    disponivel: "उपलब्ध",
    ausente: "अनुपस्थित",
    naoPerturbar: "परेशान न करें",
    naoPerturbarDetalhe: "नए संदेश की सूचना नहीं मिलती",
    invisivel: "अदृश्य",
    invisivelDetalhe: "दूसरों को आप ऑफ़लाइन दिखते हैं",
  },
  menu: {
    mudarDeConta: "खाता बदलें",
    gerenciarContas: "खाते प्रबंधित करें",
  },
  editor: {
    decoracao: "अवतार की सजावट बदलें",
    naoSalvo: "अपने बदलाव सहेजना न भूलें!",
    principal: "मुख्य प्रोफ़ाइल",
  },
};
